// أسئلة إضافية — الوحدة الثالثة: مجال النسيج

export const u3l1_extra = [
  {
    id:'u3l1q9', unit:'u3', lesson:'u3l1', page:52, type:'trueFalse',
    bloom:'remember', difficulty:'easy',
    question:'العصفور النسّاج يبني عشه بمهارة باستخدام منقاره وأرجله.',
    paragraph:'إنه ينسج عشه. ما اسم هذا العصفور؟ إنه العصفور النسّاج. (ص52)',
    correctAnswer:true,
    explanation:'العصفور النسّاج يستخدم منقاره وأرجله بمهارة في نسج عشه من الأوراق والأغصان.',
    goldenRule:'العصفور النسّاج = مهندس الطبيعة = ينسج بمنقاره وأرجله.',
  },
  {
    id:'u3l1q10', unit:'u3', lesson:'u3l1', page:53, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'النسيج هو تداخل مجموعتين من الخيوط بزوايا:',
    paragraph:'النسيج: هو تداخل مجموعتين من الخيوط بزوايا قائمة. (ص53)',
    options:[
      {text:'قائمة (90 درجة)',correct:true},
      {text:'حادة (45 درجة)',correct:false},
      {text:'منفرجة (120 درجة)',correct:false},
      {text:'مائلة (60 درجة)',correct:false},
    ],
    explanation:'الخيوط تتداخل بزوايا قائمة (90 درجة) — السدى رأسي واللحمة أفقي.',
    goldenRule:'النسيج = زاوية قائمة (90°) = سدى رأسي + لحمة أفقي.',
  },
  {
    id:'u3l1q11', unit:'u3', lesson:'u3l1', page:53, type:'trueFalse',
    bloom:'remember', difficulty:'easy',
    question:'خيوط السدى هي الخيوط الرأسية في النسيج.',
    paragraph:'تعرف المجموعة الأولى باسم خيوط السدى. (ص53)',
    correctAnswer:true,
    explanation:'السدى = الخيوط الرأسية (من أعلى لأسفل). اللحمة = الخيوط الأفقية (من يمين ليسار).',
    goldenRule:'السدى = رأسي (↑↓). اللحمة = أفقي (→←). الزاوية بينهما = 90°.',
  },
  {
    id:'u3l1q12', unit:'u3', lesson:'u3l1', page:53, type:'trueFalse',
    bloom:'remember', difficulty:'easy',
    question:'خيوط اللُّحمة هي الخيوط الأفقية في النسيج.',
    paragraph:'وتعرف المجموعة الثانية باسم خيوط اللُّحمة. (ص53)',
    correctAnswer:true,
    explanation:'اللحمة = الخيوط الأفقية التي تمر فوق وتحت خيوط السدى.',
    goldenRule:'اللحمة = أفقي (→←). تمر فوق وتحت السدى = تداخل.',
  },
  {
    id:'u3l1q13', unit:'u3', lesson:'u3l1', page:54, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'الخوص المستخدم في النسيج مصنوع من:',
    paragraph:'الأشكال التالية لمجموعة من الأنسجة بخامات متنوعة... نسيج من الخوص. (ص54)',
    options:[
      {text:'أغصان نخيل جافة (الجريد)',correct:true},
      {text:'خيوط القطن',correct:false},
      {text:'أوراق الأشجار الخضراء',correct:false},
      {text:'الصوف الحيواني',correct:false},
    ],
    explanation:'الخوص = جريد النخيل المجفف — يُستخدم في نسج الحصر والقفاف والسلال.',
    goldenRule:'الخوص = جريد النخيل = تراث المدينة المنورة = حصر وقفاف وسلال.',
  },
  {
    id:'u3l1q14', unit:'u3', lesson:'u3l1', page:55, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'الطوف المائي أقدم وسيلة نقل مائية قبل اختراع السفينة.',
    paragraph:'استخدم الإنسان (طوف مائي) قبل أن يصنع السفينة في الصيد والانتقال عبر البحار. (ص55)',
    correctAnswer:true,
    explanation:'الطوف = أقدم وسيلة نقل مائية — مصنوع من أخشاب منسوجة معاً.',
    goldenRule:'الطوف المائي = نسيج خشبي = أقدم وسيلة نقل بحري.',
  },
  {
    id:'u3l1q15', unit:'u3', lesson:'u3l1', page:57, type:'multipleChoice',
    bloom:'apply', difficulty:'medium',
    question:'في صنع الطوف المائي، نُثبّت الأعواد الخشبية على:',
    paragraph:'الخطوة الأولى: نُثبت الأعواد الخشبية على الفلين. (ص57)',
    options:[
      {text:'الفلين',correct:true},
      {text:'الحديد',correct:false},
      {text:'الزجاج',correct:false},
      {text:'البلاستيك',correct:false},
    ],
    explanation:'الفلين خفيف ويطفو — نثبّت عليه الأعواد الخشبية كقاعدة للطوف.',
    goldenRule:'الطوف = فلين (يطفو) + أعواد خشبية (سدى) + خيوط (لحمة) = نسيج مائي.',
  },
  {
    id:'u3l1q16', unit:'u3', lesson:'u3l1', page:58, type:'trueFalse',
    bloom:'apply', difficulty:'medium',
    question:'في النسيج، نمرّر الخيط بالتبادل فوق السدى وتحته.',
    paragraph:'نبدأ عملية النسيج بتمرير الخيط بالتبادل فوق السدى وتحته. (ص58)',
    correctAnswer:true,
    explanation:'التبادل = فوق وتحت بالتناوب — هذا سر متانة النسيج.',
    goldenRule:'النسيج = تبادل (فوق/تحت) = متانة + مرونة.',
  },
  {
    id:'u3l1q17', unit:'u3', lesson:'u3l1', page:59, type:'fillBlank',
    bloom:'apply', difficulty:'easy',
    question:'أكمل: "نُثبّت على الطوف رايتنا راية ___ ليكون جاهزاً."',
    paragraph:'نُثبّت عليها رايتنا راية التوحيد ليكون جاهزاً. (ص59)',
    blanks:['التوحيد'],
    wordBank:['التوحيد','السلام','النصر','العلم'],
    explanation:'راية التوحيد = لا إله إلا الله — راية المملكة العربية السعودية.',
    goldenRule:'راية التوحيد = لا إله إلا الله = هوية المملكة على الطوف.',
  },
  {
    id:'u3l1q18', unit:'u3', lesson:'u3l1', page:54, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف خامات النسيج:',
    paragraph:'نسيج من الخوص / نسيج من الخيوط والأشرطة / نسيج من الورق الملون. (ص54)',
    categories:['خامات طبيعية 🌿','خامات مصنوعة 🏭'],
    items:[
      {text:'الخوص (جريد النخيل)',correct_category:0},
      {text:'الأغصان الجافة',correct_category:0},
      {text:'الخيوط الصوفية',correct_category:1},
      {text:'أشرطة القماش',correct_category:1},
      {text:'الورق الملون',correct_category:1},
    ],
    explanation:'طبيعية: خوص + أغصان. مصنوعة: خيوط + أشرطة + ورق.',
    goldenRule:'نسيج طبيعي = خوص/أغصان. نسيج مصنوع = خيوط/أشرطة/ورق.',
  },
  {
    id:'u3l1q19', unit:'u3', lesson:'u3l1', page:55, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'لماذا يطفو الطوف المائي على سطح الماء؟',
    paragraph:'استخدم الإنسان (طوف مائي) قبل أن يصنع السفينة في الصيد والانتقال عبر البحار. (ص55)',
    options:[
      {text:'لأن الأخشاب والفلين أخفّ من الماء فتطفو',correct:true},
      {text:'لأنه مصنوع من المعدن الثقيل',correct:false},
      {text:'لأنه يحتوي على محرك',correct:false},
      {text:'لأنه كبير الحجم فقط',correct:false},
    ],
    explanation:'الأخشاب والفلين أقل كثافة من الماء — لهذا تطفو بسهولة.',
    goldenRule:'الخفّة = طفو. الأخشاب + الفلين = أخفّ من الماء = طوف يطفو.',
  },
  {
    id:'u3l1q20', unit:'u3', lesson:'u3l1', page:53, type:'fillBlank',
    bloom:'remember', difficulty:'easy',
    question:'أكمل: "الخيوط الرأسية في النسيج تسمى خيوط ___."',
    paragraph:'تعرف المجموعة الأولى باسم خيوط السدى. (ص53)',
    blanks:['السدى'],
    wordBank:['السدى','اللحمة','الإطار','الربط'],
    explanation:'السدى = الخيوط الرأسية. اللحمة = الخيوط الأفقية.',
    goldenRule:'السدى = رأسي. اللحمة = أفقي. زاوية قائمة بينهما.',
  },
  {
    id:'u3l1q21', unit:'u3', lesson:'u3l1', page:53, type:'fillBlank',
    bloom:'remember', difficulty:'easy',
    question:'أكمل: "الخيوط الأفقية في النسيج تسمى خيوط ___."',
    paragraph:'وتعرف المجموعة الثانية باسم خيوط اللُّحمة. (ص53)',
    blanks:['اللُّحمة'],
    wordBank:['اللُّحمة','السدى','العرض','الطول'],
    explanation:'اللحمة = الخيوط الأفقية. السدى = الخيوط الرأسية.',
    goldenRule:'اللحمة = أفقي. السدى = رأسي. كلاهما يتداخل بزاوية 90°.',
  },
  {
    id:'u3l1q22', unit:'u3', lesson:'u3l1', page:59, type:'trueFalse',
    bloom:'apply', difficulty:'easy',
    question:'بعد صنع الطوف المائي علينا أن نحافظ عليه.',
    paragraph:'نحافظ عليها. (ص59)',
    correctAnswer:true,
    explanation:'المحافظة على العمل الفني = قيمة فنية وتربوية — فنان مسؤول.',
    goldenRule:'اصنع + استمتع + حافظ = فنان مسؤول ومبدع.',
  },
  {
    id:'u3l1q23', unit:'u3', lesson:'u3l1', page:52, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'ما الدرس المستفاد من قصة العصفور النسّاج؟',
    paragraph:'إنه ينسج عشه. ما اسم هذا العصفور؟ إنه العصفور النسّاج. (ص52)',
    options:[
      {text:'أن الطبيعة مليئة بالإبداع وأن النسج فطرة في الكائنات',correct:true},
      {text:'أن العصفور أذكى من الإنسان',correct:false},
      {text:'أن النسج صعب لا يمكن تعلمه',correct:false},
      {text:'لا درس مستفاد',correct:false},
    ],
    explanation:'العصفور ينسج بفطرته — الطبيعة معلّم والنسج إبداع فطري.',
    goldenRule:'الطبيعة = إبداع فطري. العصفور النسّاج يُلهمنا الإتقان والمهارة.',
  },
  {
    id:'u3l1q24', unit:'u3', lesson:'u3l1', page:54, type:'matching',
    bloom:'understand', difficulty:'medium',
    question:'صِل كل نسيج بخامته:',
    paragraph:'نسيج من الخوص / نسيج من الخيوط والأشرطة / نسيج من الورق الملون. (ص54)',
    pairs:[
      {left:'نسيج من الخوص',right:'أغصان نخيل جافة'},
      {left:'نسيج من الخيوط',right:'خيوط وأشرطة قماش'},
      {left:'نسيج من الورق',right:'أوراق ملونة مقصوصة'},
    ],
    explanation:'خوص = جريد. خيوط = قماش. ورق = أوراق ملونة.',
    goldenRule:'كل نسيج = خامة. الخوص/الخيوط/الورق = خامات متنوعة للنسيج.',
  },
  {
    id:'u3l1q25', unit:'u3', lesson:'u3l1', page:53, type:'multipleChoice',
    bloom:'analyze', difficulty:'medium',
    question:'ماذا يحدث لو لم تتداخل خيوط السدى واللحمة بزوايا قائمة؟',
    paragraph:'النسيج: هو تداخل مجموعتين من الخيوط بزوايا قائمة. (ص53)',
    options:[
      {text:'لن يتكوّن نسيج متين ويكون ضعيفاً',correct:true},
      {text:'سيكون أجمل',correct:false},
      {text:'لا فرق',correct:false},
      {text:'سيكون أقوى',correct:false},
    ],
    explanation:'الزاوية القائمة ضرورية لتداخل صحيح = متانة. بدونه = نسيج ضعيف مفكك.',
    goldenRule:'زاوية قائمة = تداخل = متانة. بدونها = نسيج ضعيف مفكك.',
  },
  {
    id:'u3l1q26', unit:'u3', lesson:'u3l1', page:57, type:'ordering',
    bloom:'apply', difficulty:'medium',
    question:'رتّب خطوات الطوف المائي:',
    paragraph:'نُثبت الأعواد الخشبية على الفلين / نبدأ عملية النسيج / نُنهي نسج ثلاثة صفوف / نقص الخيوط الزائدة. (ص57-59)',
    items:['نقص الخيوط الزائدة','نُثبت الأعواد الخشبية على الفلين','نُنهي نسج ثلاثة صفوف','نبدأ عملية النسيج بالتبادل'],
    correctOrder:[1,3,2,0],
    explanation:'(1) تثبيت الأعواد ← (2) بدء النسج ← (3) ثلاثة صفوف ← (4) قص الزائد.',
    goldenRule:'الطوف: تثبيت ← نسج ← إنهاء ← قص. 4 خطوات لإتمام الطوف.',
  },
  {
    id:'u3l1q27', unit:'u3', lesson:'u3l1', page:58, type:'trueFalse',
    bloom:'apply', difficulty:'medium',
    question:'ننهي نسج ثلاثة صفوف في أسفل الطوف ثم نبدأ الجزء الأعلى.',
    paragraph:'نُنهي نسج ثلاثة صفوف في الأسفل ونبدأ الجزء الأعلى. (ص58)',
    correctAnswer:true,
    explanation:'نبدأ بالأسفل (3 صفوف) ثم ننتقل للأعلى — ترتيب منطقي في النسيج.',
    goldenRule:'النسيج: أسفل أولاً (3 صفوف) ← أعلى. من القاعدة للقمة.',
  },
  {
    id:'u3l1q28', unit:'u3', lesson:'u3l1', page:60, type:'multipleChoice',
    bloom:'evaluate', difficulty:'medium',
    question:'في تقويم الوحدة: اتجاه خيوط السدى:',
    paragraph:'ما هو اتجاه خيوط السدى؟ (ص60)',
    options:[
      {text:'رأسي (من أعلى لأسفل)',correct:true},
      {text:'أفقي (من يمين ليسار)',correct:false},
      {text:'قطري',correct:false},
      {text:'دائري',correct:false},
    ],
    explanation:'السدى = رأسي. اللحمة = أفقي.',
    goldenRule:'السدى = رأسي ↑↓. اللحمة = أفقي →←. اتجاهان متعامدان.',
  },
  {
    id:'u3l1q29', unit:'u3', lesson:'u3l1', page:60, type:'multipleChoice',
    bloom:'evaluate', difficulty:'medium',
    question:'في تقويم الوحدة: اتجاه خيوط اللحمة:',
    paragraph:'وما هو اتجاه خيوط اللُّحمة؟ (ص60)',
    options:[
      {text:'أفقي (من يمين ليسار)',correct:true},
      {text:'رأسي (من أعلى لأسفل)',correct:false},
      {text:'قطري',correct:false},
      {text:'دائري',correct:false},
    ],
    explanation:'اللحمة = أفقي. السدى = رأسي.',
    goldenRule:'اللحمة = أفقي →←. السدى = رأسي ↑↓. متعامدان.',
  },
  {
    id:'u3l1q30', unit:'u3', lesson:'u3l1', page:59, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'ما الراية التي نثبتها على الطوف المائي؟',
    paragraph:'نُثبّت عليها رايتنا راية التوحيد. (ص59)',
    options:[
      {text:'راية التوحيد',correct:true},
      {text:'راية السلام',correct:false},
      {text:'راية النصر',correct:false},
      {text:'لا راية',correct:false},
    ],
    explanation:'راية التوحيد = لا إله إلا الله = راية المملكة العربية السعودية.',
    goldenRule:'راية التوحيد على الطوف = هوية وطنية + إبداع فني.',
  },
  {
    id:'u3l1q31', unit:'u3', lesson:'u3l1', page:53, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'تداخل خيوط السدى واللحمة يُنتج قماشاً متيناً.',
    paragraph:'النسيج: هو تداخل مجموعتين من الخيوط بزوايا قائمة. (ص53)',
    correctAnswer:true,
    explanation:'التداخل المنتظم = متانة. كلما كان التداخل أكثف = قماش أقوى.',
    goldenRule:'تداخل + كثافة = متانة. النسيج المتقن = قماش قوي.',
  },
  {
    id:'u3l1q32', unit:'u3', lesson:'u3l1', page:55, type:'multipleChoice',
    bloom:'create', difficulty:'hard',
    question:'لو أردت صنع طوف مائي، ما الخامات التي تحتاجها؟',
    paragraph:'نُثبت الأعواد الخشبية على الفلين... نبدأ عملية النسيج... (ص57-58)',
    options:[
      {text:'فلين + أعواد خشبية + خيوط',correct:true},
      {text:'حديد + أسمنت',correct:false},
      {text:'زجاج + بلاستيك',correct:false},
      {text:'ورق + صمغ فقط',correct:false},
    ],
    explanation:'الطوف = فلين (قاعدة عائمة) + أعواد (سدى) + خيوط (لحمة) = نسيج يطفو.',
    goldenRule:'الطوف = 3 خامات: فلين (طفو) + أعواد (سدى) + خيوط (لحمة).',
  },
];

export const u3l2_extra = [
  {
    id:'u3l2q9', unit:'u3', lesson:'u3l2', page:61, type:'trueFalse',
    bloom:'remember', difficulty:'easy',
    question:'الأعرابي نسج خيمته من صوف ماشيته.',
    paragraph:'نسج الأعرابي خيمته وأثاث بيته من صوف ماشيته التي يربيها في البادية. (ص61)',
    correctAnswer:true,
    explanation:'الأعرابي غزل صوف الغنم والإبل ونسج منه خيمته — اكتفاء ذاتي بيئي.',
    goldenRule:'الأعرابي = يربي + يغزل + ينسج = خيمة من بيئته = اكتفاء ذاتي.',
  },
  {
    id:'u3l2q10', unit:'u3', lesson:'u3l2', page:61, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'لماذا شبهت الخيمة البدوية الكثبان الرملية؟',
    paragraph:'وقد أخذت الخيمة شكل الكثبان الرملية الموجودة في الصحراء التي كان يعيش فيها. (ص61)',
    options:[
      {text:'لأن الأعرابي استوحى شكلها من بيئته الصحراوية',correct:true},
      {text:'لأنها مصنوعة من الرمل',correct:false},
      {text:'لأنها تنهار كالرمل',correct:false},
      {text:'لا علاقة بالبيئة',correct:false},
    ],
    explanation:'البيئة الصحراوية ألهمت الأعرابي شكل الكثبان — فن بيئي أصيل.',
    goldenRule:'الخيمة = شكل الكثبان = استلهام من البيئة = انسجام صحراوي.',
  },
  {
    id:'u3l2q11', unit:'u3', lesson:'u3l2', page:62, type:'trueFalse',
    bloom:'remember', difficulty:'easy',
    question:'القطن نبات زرعه الإنسان على ضفاف الأنهار.',
    paragraph:'كذلك زرع الإنسان القطن شكل (٦٤) في المدن على ضفاف الأنهار. (ص62)',
    correctAnswer:true,
    explanation:'القطن نبات زراعي قديم يُزرع قرب الأنهار لاحتياجه للماء.',
    goldenRule:'القطن = نبات + نهر = خيوط ناعمة = ملابس يومية.',
  },
  {
    id:'u3l2q12', unit:'u3', lesson:'u3l2', page:62, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'ما الأداة التي استخدمها الإنسان لغزل القطن؟',
    paragraph:'وغزله باستخدام المغازل اليدوية في المنازل إلى خيوط ناعمة. (ص62)',
    options:[
      {text:'المغازل اليدوية',correct:true},
      {text:'الآلات البخارية',correct:false},
      {text:'الإبرة والخيط',correct:false},
      {text:'الأصابع فقط',correct:false},
    ],
    explanation:'المغزل اليدوي = أداة قديمة لتحويل القطن الخام إلى خيوط ناعمة.',
    goldenRule:'المغزل اليدوي = أداة غزل تقليدية = من القطن الخام إلى الخيط.',
  },
  {
    id:'u3l2q13', unit:'u3', lesson:'u3l2', page:63, type:'trueFalse',
    bloom:'understand', difficulty:'medium',
    question:'في النسيج، خيط اللحمة الأول يمر تحت الخيوط الزوجية من السدى.',
    paragraph:'تعتمد عملية النسج على تمرير خيط اللُّحمة الأول تحت الخيوط الزوجية من خيوط السدى. (ص63)',
    correctAnswer:true,
    explanation:'اللحمة 1 = تحت الزوجي. اللحمة 2 = تحت الفردي. تبادل منتظم.',
    goldenRule:'اللحمة 1 = تحت الزوجي. اللحمة 2 = تحت الفردي. تبادل = متانة.',
  },
  {
    id:'u3l2q14', unit:'u3', lesson:'u3l2', page:63, type:'trueFalse',
    bloom:'understand', difficulty:'medium',
    question:'خيط اللحمة الثاني يمر بالتبادل تحت الخيوط الفردية.',
    paragraph:'ويتم تمرير خيط اللُّحمة الثاني بالتبادل تحت الخيوط الفردية بالتبادل. (ص63)',
    correctAnswer:true,
    explanation:'التبادل: الأول تحت الزوجي، الثاني تحت الفردي — تعاقب منتظم.',
    goldenRule:'التبادل = فوق/تحت بالتناوب = نسيج متين.',
  },
  {
    id:'u3l2q15', unit:'u3', lesson:'u3l2', page:63, type:'fillBlank',
    bloom:'remember', difficulty:'easy',
    question:'أكمل: "اللون الأخضر يُمثّل خيوط ___ والبرتقالي يُمثّل خيوط ___."',
    paragraph:'اللون الأخضر يمثل خيوط (السدى) واللون البرتقالي يمثل خيوط (اللحمة). (ص63)',
    blanks:['السدى','اللحمة'],
    wordBank:['السدى','اللحمة','الإطار','الربط'],
    explanation:'في رسم النسيج: الأخضر = السدى (رأسي). البرتقالي = اللحمة (أفقي).',
    goldenRule:'في رسم النسيج: أخضر = سدى (رأسي)، برتقالي = لحمة (أفقي).',
  },
  {
    id:'u3l2q16', unit:'u3', lesson:'u3l2', page:64, type:'multipleChoice',
    bloom:'apply', difficulty:'medium',
    question:'من استخدامات الأشكال المنسوجة:',
    paragraph:'يمكننا عمل شكل منسوج واستخدامه لأغراض مختلفة كحافظات الأقلام والأدوات المكتبية. (ص64)',
    options:[
      {text:'حافظات الأقلام والأدوات المكتبية',correct:true},
      {text:'إصلاح الأجهزة',correct:false},
      {text:'صنع الطعام',correct:false},
      {text:'بناء المنازل',correct:false},
    ],
    explanation:'النسيج التطبيقي: حافظات أقلام = فن + فائدة عملية مكتبية.',
    goldenRule:'النسيج التطبيقي = حافظة أقلام = جمال + نفع في المكتب.',
  },
  {
    id:'u3l2q17', unit:'u3', lesson:'u3l2', page:65, type:'ordering',
    bloom:'apply', difficulty:'medium',
    question:'رتّب خطوات عمل مقلمية بالنسيج:',
    paragraph:'نقص الورق إلى شرائح / نثبت الأعواد على الفلين / نمرر الأشرطة كلحمة / نضيف الخرزات / نضع شريطاً حول الأعواد / النتيجة النهائية. (ص65)',
    items:['نضع شريطاً حول الأعواد بعد الخرزات','نقص الورق إلى شرائح طولية','نمرر الأشرطة الورقية كلحمة في السدى','نثبت الأعواد الخشبية على الفلين'],
    correctOrder:[1,3,2,0],
    explanation:'(1) قص شرائح ← (2) تثبيت أعواد ← (3) تمرير شرائح ← (4) شريط حول الأعواد.',
    goldenRule:'المقلمية المنسوجة: قص ← تثبيت ← نسج ← تشطيب.',
  },
  {
    id:'u3l2q18', unit:'u3', lesson:'u3l2', page:70, type:'trueFalse',
    bloom:'apply', difficulty:'easy',
    question:'في تقويم الوحدة: شكل الخيام الخارجي يشبه الكثبان الرملية.',
    paragraph:'٢. ضع/ي إشارة (✓) أو (X): شكل الخيام الخارجي يشبه كثبان الرمال. (ص70)',
    correctAnswer:true,
    explanation:'نعم — الخيمة البدوية اتخذت شكل الكثبان الرملية استلهاماً من البيئة.',
    goldenRule:'الخيمة = كثبان رملية = انسجام مع البيئة الصحراوية.',
  },
  {
    id:'u3l2q19', unit:'u3', lesson:'u3l2', page:80, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'في تقويم الوحدة: مصدر الصوف هو:',
    paragraph:'ج. ما هو مصدر الصوف الذي نصنع منه النسيج: الخروف / الدجاجة / الغزال. (ص80)',
    options:[
      {text:'الخروف',correct:true},
      {text:'الدجاجة',correct:false},
      {text:'الغزال',correct:false},
      {text:'السمكة',correct:false},
    ],
    explanation:'الصوف = من الخروف. القطن = من النبات. الحرير = من دودة القز.',
    goldenRule:'الصوف = خروف. القطن = نبات. الحرير = دودة قز. 3 مصادر للخيوط.',
  },
  {
    id:'u3l2q20', unit:'u3', lesson:'u3l2', page:63, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف خيوط النسيج:',
    paragraph:'خيوط السدى (رأسية) / خيوط اللحمة (أفقية). (ص53-63)',
    categories:['خيوط السدى (رأسية)','خيوط اللحمة (أفقية)'],
    items:[
      {text:'خيوط من أعلى لأسفل',correct_category:0},
      {text:'خيوط عمودية على الأرض',correct_category:0},
      {text:'خيوط من يمين لشمال',correct_category:1},
      {text:'خيوط موازية للأرض',correct_category:1},
    ],
    explanation:'سدى = رأسي (↑↓). لحمة = أفقي (→←).',
    goldenRule:'السدى = رأسي. اللحمة = أفقي. متعامدان بزاوية 90°.',
  },
  {
    id:'u3l2q21', unit:'u3', lesson:'u3l2', page:61, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'ما الفائدة من اتخاذ الخيمة شكل الكثبان الرملية؟',
    paragraph:'وقد أخذت الخيمة شكل الكثبان الرملية الموجودة في الصحراء. (ص61)',
    options:[
      {text:'الانسجام مع البيئة ومقاومة الرياح الصحراوية',correct:true},
      {text:'لتكون أكبر حجماً',correct:false},
      {text:'لتكون أثقل',correct:false},
      {text:'لا فائدة',correct:false},
    ],
    explanation:'الشكل المنحني يقاوم الرياح وينسجم مع البيئة = حكمة بيئية.',
    goldenRule:'الشكل المنحني = مقاومة رياح + انسجام بيئي = حكمة الأعرابي.',
  },
  {
    id:'u3l2q22', unit:'u3', lesson:'u3l2', page:62, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'المغازل اليدوية أداة منزلية قديمة لغزل القطن.',
    paragraph:'وغزله باستخدام المغازل اليدوية في المنازل إلى خيوط ناعمة. (ص62)',
    correctAnswer:true,
    explanation:'المغزل اليدوي = أداة منزلية صغيرة يدوية لتحويل القطن لخيوط.',
    goldenRule:'المغزل = أداة منزلية = غزل يدوي = من القطن الخام إلى الخيط.',
  },
  {
    id:'u3l2q23', unit:'u3', lesson:'u3l2', page:63, type:'multipleChoice',
    bloom:'analyze', difficulty:'medium',
    question:'ماذا يحدث لو مرّت جميع خيوط اللحمة من جهة واحدة فقط؟',
    paragraph:'تعتمد عملية النسج على تمرير خيط اللُّحمة الأول تحت الخيوط الزوجية... والثاني بالتبادل. (ص63)',
    options:[
      {text:'لن يكون النسيج متيناً ويتفكك بسهولة',correct:true},
      {text:'سيكون أجمل',correct:false},
      {text:'لا فرق',correct:false},
      {text:'سيكون أقوى',correct:false},
    ],
    explanation:'التبادل فوق/تحت = متانة. من جهة واحدة = نسيج مفكك وضعيف.',
    goldenRule:'التبادل = فوق/تحت = متانة. جهة واحدة = ضعف وتفكك.',
  },
  {
    id:'u3l2q24', unit:'u3', lesson:'u3l2', page:64, type:'trueFalse',
    bloom:'apply', difficulty:'easy',
    question:'يمكن استخدام النسيج في صنع حافظات الأقلام.',
    paragraph:'يمكننا عمل شكل منسوج واستخدامه... كحافظات الأقلام والأدوات المكتبية. (ص64)',
    correctAnswer:true,
    explanation:'حافظة الأقلام المنسوجة = فن تطبيقي نافع = جمال + تنظيم.',
    goldenRule:'حافظة أقلام منسوجة = فن + نفع = تنظيم مكتب جميل.',
  },
  {
    id:'u3l2q25', unit:'u3', lesson:'u3l2', page:61, type:'fillBlank',
    bloom:'remember', difficulty:'easy',
    question:'أكمل: "نسج الأعرابي خيمته من ___ ماشيته التي يربيها في البادية."',
    paragraph:'نسج الأعرابي خيمته وأثاث بيته من صوف ماشيته التي يربيها في البادية. (ص61)',
    blanks:['صوف'],
    wordBank:['صوف','قطن','حرير','نايلون'],
    explanation:'الأعرابي نسج من صوف الغنم والإبل = خامات بيئته المتاحة.',
    goldenRule:'صوف الغنم والإبل = مادة الخيمة البدوية = اكتفاء ذاتي.',
  },
  {
    id:'u3l2q26', unit:'u3', lesson:'u3l2', page:62, type:'fillBlank',
    bloom:'remember', difficulty:'easy',
    question:'أكمل: "زرع الإنسان القطن على ضفاف ___."',
    paragraph:'كذلك زرع الإنسان القطن شكل (٦٤) في المدن على ضفاف الأنهار. (ص62)',
    blanks:['الأنهار'],
    wordBank:['الأنهار','الجبال','الصحراء','البحار'],
    explanation:'القطن يحتاج ماءً وفيراً — يُزرع على ضفاف الأنهار.',
    goldenRule:'القطن = نهر + ماء = زراعة على الضفاف = خيوط ناعمة.',
  },
  {
    id:'u3l2q27', unit:'u3', lesson:'u3l2', page:63, type:'multipleChoice',
    bloom:'create', difficulty:'hard',
    question:'لو أردت نسج قطعة قماش، ما الترتيب الصحيح لخيوط اللحمة؟',
    paragraph:'تمرير خيط اللُّحمة الأول تحت الخيوط الزوجية... والثاني بالتبادل تحت الخيوط الفردية. (ص63)',
    options:[
      {text:'الأول تحت الزوجي، الثاني تحت الفردي بالتبادل',correct:true},
      {text:'الكل من جهة واحدة',correct:false},
      {text:'الكل فوق السدى',correct:false},
      {text:'الكل تحت السدى',correct:false},
    ],
    explanation:'التبادل: 1 تحت الزوجي، 2 تحت الفردي = تعاقب = متانة.',
    goldenRule:'نسج صحيح = تبادل: زوجي/فردي بالتناوب = متانة.',
  },
  {
    id:'u3l2q28', unit:'u3', lesson:'u3l2', page:61, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'ما الذي غزله الأعرابي لنسج خيمته؟',
    paragraph:'نسج الأعرابي خيمته وأثاث بيته من صوف ماشيته... وغزلها إلى خيوط سميكة. (ص61)',
    options:[
      {text:'صوف الماشية إلى خيوط سميكة',correct:true},
      {text:'القطن إلى خيوط ناعمة',correct:false},
      {text:'الحرير إلى خيوط لامعة',correct:false},
      {text:'البلاستيك إلى خيوط صناعية',correct:false},
    ],
    explanation:'الأعرابي غزل الصوف لخيوط سميكة = خيمة دافئة ومتينة للصحراء.',
    goldenRule:'صوف + غزل = خيوط سميكة = خيمة دافئة متينة.',
  },
  {
    id:'u3l2q29', unit:'u3', lesson:'u3l2', page:70, type:'trueFalse',
    bloom:'evaluate', difficulty:'medium',
    question:'الخيمة البدوية مثال على الفن البيئي المنسجم مع الطبيعة.',
    paragraph:'وقد أخذت الخيمة شكل الكثبان الرملية الموجودة في الصحراء. (ص61)',
    correctAnswer:true,
    explanation:'الخيمة = فن بيئي = انسجام مع الصحراء + حكمة في التصميم.',
    goldenRule:'الخيمة البدوية = فن بيئي = انسجام + حكمة + هوية.',
  },
  {
    id:'u3l2q30', unit:'u3', lesson:'u3l2', page:62, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'ما الفرق بين خيوط الصوف وخيوط القطن؟',
    paragraph:'نسج الأعرابي خيمته من صوف ماشيته... وغزلها إلى خيوط سميكة. (ص61) / زرع الإنسان القطن... وغزله إلى خيوط ناعمة. (ص62)',
    options:[
      {text:'الصوف سميك من الحيوان، والقطن ناعم من النبات',correct:true},
      {text:'كلاهما من النبات',correct:false},
      {text:'كلاهما من الحيوان',correct:false},
      {text:'لا فرق بينهما',correct:false},
    ],
    explanation:'الصوف = حيواني + سميك + دافئ. القطن = نباتي + ناعم + مريح.',
    goldenRule:'الصوف = خروف + سميك + دافئ. القطن = نبات + ناعم + مريح.',
  },
  {
    id:'u3l2q31', unit:'u3', lesson:'u3l2', page:64, type:'multipleChoice',
    bloom:'apply', difficulty:'easy',
    question:'ما الفائدة من صنع حافظة أقلام منسوجة؟',
    paragraph:'يمكننا عمل شكل منسوج واستخدامه لأغراض مختلفة كحافظات الأقلام. (ص64)',
    options:[
      {text:'تنظيم الأقلام بشكل جميل وفني',correct:true},
      {text:'لا فائدة',correct:false},
      {text:'إصلاح الأقلام',correct:false},
      {text:'صناعة الأقلام',correct:false},
    ],
    explanation:'حافظة الأقلام المنسوجة = تنظيم + جمال = فن تطبيقي.',
    goldenRule:'حافظة منسوجة = تنظيم + جمال = فن نافع للمكتب.',
  },
  {
    id:'u3l2q32', unit:'u3', lesson:'u3l2', page:63, type:'trueFalse',
    bloom:'remember', difficulty:'easy',
    question:'في رسم النسيج بالألوان، الأخضر للسدى والبرتقالي للّحمة.',
    paragraph:'اللون الأخضر يمثل خيوط (السدى) واللون البرتقالي يمثل خيوط (اللحمة). (ص63)',
    correctAnswer:true,
    explanation:'تلوين السدى واللحمة بألوان مختلفة يساعد على تمييز التداخل بصرياً.',
    goldenRule:'ألوان مختلفة للسدى واللحمة = وضوح التداخل = فهم أسهل.',
  },
];

export const u3l3_extra = [
  {
    id:'u3l3q9', unit:'u3', lesson:'u3l3', page:71, type:'trueFalse',
    bloom:'remember', difficulty:'easy',
    question:'الأغصان والريش من الخامات الطبيعية للنسيج.',
    paragraph:'خامات طبيعية مثل: أغصان الأشجار، الريش، سعف النخيل، الحبال. (ص71)',
    correctAnswer:true,
    explanation:'الخامات الطبيعية = من الطبيعة مباشرة: أغصان + ريش + سعف + حبال.',
    goldenRule:'طبيعية = أغصان + ريش + خوص + حبال = من الطبيعة مباشرة.',
  },
  {
    id:'u3l3q10', unit:'u3', lesson:'u3l3', page:71, type:'trueFalse',
    bloom:'remember', difficulty:'easy',
    question:'أشرطة الساتان والبلاستيك من الخامات المصنوعة للنسيج.',
    paragraph:'خامات مصنوعة مثل: أشرطة الساتان، البلاستيك، أوراق التزيين، والخيوط. (ص71)',
    correctAnswer:true,
    explanation:'المصنوعة = من المصنع: ساتان + بلاستيك + أوراق ملونة + خيوط.',
    goldenRule:'مصنوعة = ساتان + بلاستيك + ورق ملون + خيوط = من المصنع.',
  },
  {
    id:'u3l3q11', unit:'u3', lesson:'u3l3', page:73, type:'trueFalse',
    bloom:'remember', difficulty:'easy',
    question:'النخلة رمز أساسي لسكان المملكة العربية السعودية.',
    paragraph:'تعتبر النخلة رمزاً من الرموز الأساسية لسكان المملكة العربية السعودية. (ص73)',
    correctAnswer:true,
    explanation:'النخلة = رمز المملكة = أصالة + خير + هوية وطنية.',
    goldenRule:'النخلة = رمز المملكة = أصالة + خير + هوية = شعار يوم التأسيس.',
  },
  {
    id:'u3l3q12', unit:'u3', lesson:'u3l3', page:73, type:'trueFalse',
    bloom:'remember', difficulty:'easy',
    question:'النخلة انعكست كرمز في شعار يوم التأسيس.',
    paragraph:'انعكست كرمز من رموز شعار يوم التأسيس في المملكة العربية السعودية. (ص73)',
    correctAnswer:true,
    explanation:'شعار يوم التأسيس يحتوي على النخلة = رمز وطني رسمي.',
    goldenRule:'النخلة + شعار يوم التأسيس = رمز وطني سعودي رسمي.',
  },
  {
    id:'u3l3q13', unit:'u3', lesson:'u3l3', page:73, type:'trueFalse',
    bloom:'remember', difficulty:'easy',
    question:'أهل المدينة المنورة نسجوا الحصر والقفاف من جريد النخيل.',
    paragraph:'وقد نسج أهل المدينة المنورة الحصر والقفاف من جريد النخيل. (ص73)',
    correctAnswer:true,
    explanation:'أهل المدينة نسجوا الحصر والقفاف = تراث إسلامي أصيل من الخوص.',
    goldenRule:'المدينة المنورة = حصر + قفاف = جريد النخيل = تراث إسلامي.',
  },
  {
    id:'u3l3q14', unit:'u3', lesson:'u3l3', page:73, type:'trueFalse',
    bloom:'remember', difficulty:'easy',
    question:'رسول الله صلى الله عليه وسلم كان يستخدم الحصر في بيته.',
    paragraph:'وكان الرسول صلى الله عليه وسلم يستخدم الحصر في بيته وينام عليها. (ص73)',
    correctAnswer:true,
    explanation:'الحصير = بساط بسيط كان يستخدمه رسول الله = بساطة + زهد + تراث.',
    goldenRule:'الحصير = سنة نبوية = بساطة + زهد = تراث نبوي شريف.',
  },
  {
    id:'u3l3q15', unit:'u3', lesson:'u3l3', page:72, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'استُخدمت خصائص الخامات النسيجية مثل الألوان والملامس في:',
    paragraph:'استخدمت خصائص الخامات النسيجية مثل الألوان والملامس المختلفة في زخرفة النسيج. (ص72)',
    options:[
      {text:'زخرفة النسيج',correct:true},
      {text:'صنع الطعام',correct:false},
      {text:'بناء المنازل',correct:false},
      {text:'صنع الأدوية',correct:false},
    ],
    explanation:'خصائص الخامات (ألوان + ملامس) تُستخدم في زخرفة النسيج لجماله.',
    goldenRule:'ألوان + ملامس الخامات = زخرفة النسيج = جمال بصري ولمسي.',
  },
  {
    id:'u3l3q16', unit:'u3', lesson:'u3l3', page:73, type:'trueFalse',
    bloom:'understand', difficulty:'medium',
    question:'الأجداد استخدموا خامات متنوعة كالجلود والخرز والألوان في تزيين منسوجاتهم.',
    paragraph:'كما استخدم الأجداد خامات مختلفة في تزيين منسوجاتهم، مثل الجلود والخرز والألوان. (ص73)',
    correctAnswer:true,
    explanation:'الأجداد زيّنوا منسوجاتهم بجلود + خرز + ألوان = ثراء فني تراثي.',
    goldenRule:'المنسوجات التراثية = نسيج + جلود + خرز + ألوان = إبداع أصيل.',
  },
  {
    id:'u3l3q17', unit:'u3', lesson:'u3l3', page:74, type:'multipleChoice',
    bloom:'evaluate', difficulty:'medium',
    question:'ما الفائدة من استخدام الخامات المستهلكة في النسيج؟',
    paragraph:'بإمكاننا كذلك أن نستخدم الخامات المستهلكة في بيئتنا بعدة طرق. (ص74)',
    options:[
      {text:'حماية البيئة وتشجيع الإبداع وتقليل النفايات',correct:true},
      {text:'لأنها أغلى ثمناً',correct:false},
      {text:'لأنها أجمل',correct:false},
      {text:'لا فائدة',correct:false},
    ],
    explanation:'إعادة استخدام الخامات المستهلكة = بيئة نظيفة + إبداع + تقليل نفايات.',
    goldenRule:'الخامات المستهلكة = إعادة تدوير = بيئة + إبداع + توفير.',
  },
  {
    id:'u3l3q18', unit:'u3', lesson:'u3l3', page:75, type:'ordering',
    bloom:'apply', difficulty:'medium',
    question:'رتّب خطوات عمل بطاقة دعوة بالورق الملون:',
    paragraph:'نقص الورقة إلى شرائح / نقص الورقة الخضراء ونشق فيها / نضع الصمغ / ندخل شرائح الورق / النتيجة. (ص75)',
    items:['ندخل شرائح الورق داخل الشقوق','نقص الورقة إلى شرائح ملونة','نضع الصمغ لتثبيت','نقص الورقة الخضراء وندخل فيها شقوقاً'],
    correctOrder:[1,3,2,0],
    explanation:'(1) قص شرائح ← (2) قص الورقة الخضراء + شقوق ← (3) صمغ ← (4) إدخال الشرائح.',
    goldenRule:'بطاقة دعوة ورقية: قص ← شقوق ← صمغ ← إدخال = نسيج ورقي.',
  },
  {
    id:'u3l3q19', unit:'u3', lesson:'u3l3', page:80, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'في تقويم الوحدة: الخيوط التي تكوّن النسيج تسمى:',
    paragraph:'ب. ما اسم الخيوط التي تكوّن النسيج: 1- خيوط الطول والعرض / 2- خيوط السدى واللحمة / 3- الخيوط الطويلة والقصيرة. (ص80)',
    options:[
      {text:'خيوط السدى واللحمة',correct:true},
      {text:'خيوط الطول والعرض',correct:false},
      {text:'الخيوط الطويلة والقصيرة',correct:false},
      {text:'خيوط الإطار والربط',correct:false},
    ],
    explanation:'النسيج = سدى + لحمة. ليس الطول والعرض ولا الطويلة والقصيرة.',
    goldenRule:'خيوط النسيج = سدى + لحمة. التسمية الصحيحة فقط.',
  },
  {
    id:'u3l3q20', unit:'u3', lesson:'u3l3', page:71, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف خامات النسيج:',
    paragraph:'خامات طبيعية: أغصان، ريش، سعف، حبال. خامات مصنوعة: ساتان، بلاستيك، أوراق تزيين، خيوط. (ص71)',
    categories:['خامات طبيعية 🌿','خامات مصنوعة 🏭'],
    items:[
      {text:'أغصان الأشجار',correct_category:0},
      {text:'ريش الطيور',correct_category:0},
      {text:'سعف النخيل',correct_category:0},
      {text:'أشرطة الساتان',correct_category:1},
      {text:'البلاستيك',correct_category:1},
      {text:'أوراق التزيين',correct_category:1},
    ],
    explanation:'طبيعية = من الطبيعة. مصنوعة = من المصنع.',
    goldenRule:'طبيعية = طبيعة. مصنوعة = مصنع. صنف حسب المصدر.',
  },
  {
    id:'u3l3q21', unit:'u3', lesson:'u3l3', page:73, type:'fillBlank',
    bloom:'remember', difficulty:'easy',
    question:'أكمل: "النخلة رمز من الرموز الأساسية لسكان ___ العربية السعودية."',
    paragraph:'تعتبر النخلة رمزاً من الرموز الأساسية لسكان المملكة العربية السعودية. (ص73)',
    blanks:['المملكة'],
    wordBank:['المملكة','الجمهورية','الإمارة','الدولة'],
    explanation:'النخلة = رمز المملكة العربية السعودية = هوية وطنية.',
    goldenRule:'النخلة = المملكة العربية السعودية = رمز وطني = هوية.',
  },
  {
    id:'u3l3q22', unit:'u3', lesson:'u3l3', page:73, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'من أين نسج أهل المدينة الحصر والقفاف؟',
    paragraph:'وقد نسج أهل المدينة المنورة الحصر والقفاف من جريد النخيل. (ص73)',
    options:[
      {text:'من جريد النخيل',correct:true},
      {text:'من القطن المستورد',correct:false},
      {text:'من البلاستيك',correct:false},
      {text:'من الصوف',correct:false},
    ],
    explanation:'أهل المدينة نسجوا من جريد النخيل = تراث إسلامي أصيل.',
    goldenRule:'المدينة + جريد النخيل = حصر وقفاف = تراث إسلامي نبوي.',
  },
  {
    id:'u3l3q23', unit:'u3', lesson:'u3l3', page:73, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'ما الذي كان يستخدمه رسول الله صلى الله عليه وسلم في بيته من المنسوجات؟',
    paragraph:'وكان الرسول صلى الله عليه وسلم يستخدم الحصر في بيته وينام عليها. (ص73)',
    options:[
      {text:'الحصر المنسوجة من جريد النخيل',correct:true},
      {text:'السجاد الفارسي',correct:false},
      {text:'الأقمشة الحريرية',correct:false},
      {text:'البلاستيك',correct:false},
    ],
    explanation:'رسول الله استخدم الحصير = بساطة + زهد + سنة نبوية.',
    goldenRule:'الحصير = سنة نبوية = بساطة + زهد = تراث نبوي شريف.',
  },
  {
    id:'u3l3q24', unit:'u3', lesson:'u3l3', page:72, type:'trueFalse',
    bloom:'apply', difficulty:'easy',
    question:'خصائص الخامات النسيجية تساعد في زخرفة النسيج.',
    paragraph:'استخدمت خصائص الخامات النسيجية مثل الألوان والملامس المختلفة في زخرفة النسيج. (ص72)',
    correctAnswer:true,
    explanation:'تنوع الألوان والملامس في الخامات يُعطي النسيج جمالاً بصرياً ولمسياً.',
    goldenRule:'ألوان + ملامس متنوعة = زخرفة نسيج = جمال بصري + لمسي.',
  },
  {
    id:'u3l3q25', unit:'u3', lesson:'u3l3', page:73, type:'trueFalse',
    bloom:'evaluate', difficulty:'medium',
    question:'المنسوجات التراثية في المملكة تُعبّر عن هوية الشعب السعودي وتراثه.',
    paragraph:'لنتأمل معاً جمال الزخارف في المنسوجات النسيجية التراثية، شكل (٧٦). (ص73)',
    correctAnswer:true,
    explanation:'المنسوجات التراثية = هوية + تراث + إبداع أجداد = فخر وطني.',
    goldenRule:'المنسوجات التراثية = هوية + تراث + إبداع = فخر سعودي أصيل.',
  },
  {
    id:'u3l3q26', unit:'u3', lesson:'u3l3', page:74, type:'multipleChoice',
    bloom:'create', difficulty:'hard',
    question:'لو أردت نسج قطعة من خامات مستهلكة، ماذا تختار؟',
    paragraph:'بإمكاننا كذلك أن نستخدم الخامات المستهلكة في بيئتنا بعدة طرق. (ص74)',
    options:[
      {text:'زجاجات بلاستيك مقصوصة + أوراق قديمة',correct:true},
      {text:'زجاج مكسور',correct:false},
      {text:'معادن ثقيلة',correct:false},
      {text:'لا شيء',correct:false},
    ],
    explanation:'الخامات المستهلكة الآمنة: بلاستيك + ورق قديم = إعادة تدوير فنية.',
    goldenRule:'إعادة تدوير = بلاستيك + ورق قديم = فن + بيئة نظيفة.',
  },
  {
    id:'u3l3q27', unit:'u3', lesson:'u3l3', page:73, type:'matching',
    bloom:'understand', difficulty:'medium',
    question:'صِل كل خامة تزيينية بمصدرها:',
    paragraph:'استخدم الأجداد خامات مختلفة في تزيين منسوجاتهم، مثل الجلود والخرز والألوان. (ص73)',
    pairs:[
      {left:'الجلود',right:'من جلود الحيوانات'},
      {left:'الخرز',right:'حبيبات صغيرة ملونة'},
      {left:'الألوان',right:'من النباتات والمعادن'},
    ],
    explanation:'الجلود = حيوانية. الخرز = حبيبات. الألوان = نباتات/معادن.',
    goldenRule:'تزيين التراث = جلود (حيوان) + خرز (حبيبات) + ألوان (نبات/معدن).',
  },
  {
    id:'u3l3q28', unit:'u3', lesson:'u3l3', page:71, type:'fillBlank',
    bloom:'remember', difficulty:'easy',
    question:'أكمل: "خامات ___ مثل أغصان الأشجار والريش وسعف النخيل."',
    paragraph:'خامات طبيعية مثل: أغصان الأشجار، الريش، سعف النخيل، الحبال. (ص71)',
    blanks:['طبيعية'],
    wordBank:['طبيعية','مصنوعة','صناعية','مستوردة'],
    explanation:'طبيعية = من الطبيعة مباشرة دون تصنيع.',
    goldenRule:'طبيعية = طبيعة. مصنوعة = مصنع. المصدر يحدد النوع.',
  },
  {
    id:'u3l3q29', unit:'u3', lesson:'u3l3', page:71, type:'fillBlank',
    bloom:'remember', difficulty:'easy',
    question:'أكمل: "خامات ___ مثل أشرطة الساتان والبلاستيك وأوراق التزيين."',
    paragraph:'خامات مصنوعة مثل: أشرطة الساتان، البلاستيك، أوراق التزيين، والخيوط. (ص71)',
    blanks:['مصنوعة'],
    wordBank:['مصنوعة','طبيعية','حية','زراعية'],
    explanation:'مصنوعة = من المصنع = ساتان + بلاستيك + أوراق + خيوط.',
    goldenRule:'مصنوعة = مصنع. طبيعية = طبيعة. صنف حسب المصدر.',
  },
  {
    id:'u3l3q30', unit:'u3', lesson:'u3l3', page:73, type:'trueFalse',
    bloom:'analyze', difficulty:'medium',
    question:'استخدام رسول الله صلى الله عليه وسلم للحصر يدل على البساطة والزهد.',
    paragraph:'وكان الرسول صلى الله عليه وسلم يستخدم الحصر في بيته وينام عليها. (ص73)',
    correctAnswer:true,
    explanation:'الحصير = بساطة + زهد = سنة نبوية في حياة بسيطة.',
    goldenRule:'الحصير النبوي = بساطة + زهد = قدوة + تراث + قيمة.',
  },
  {
    id:'u3l3q31', unit:'u3', lesson:'u3l3', page:72, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'ما الخصائص التي تُستخدم في زخرفة النسيج؟',
    paragraph:'استخدمت خصائص الخامات النسيجية مثل الألوان والملامس المختلفة في زخرفة النسيج. (ص72)',
    options:[
      {text:'الألوان والملامس المختلفة',correct:true},
      {text:'الأوزان والأحجام فقط',correct:false},
      {text:'الأسماء فقط',correct:false},
      {text:'لا خصائص',correct:false},
    ],
    explanation:'خصائص الخامة: ألوان (بصري) + ملامس (لمسي) = زخرفة نسيج.',
    goldenRule:'زخرفة النسيج = ألوان + ملامس = جمال بصري + لمسي.',
  },
  {
    id:'u3l3q32', unit:'u3', lesson:'u3l3', page:73, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'لماذا تعتبر النخلة رمزاً للمملكة العربية السعودية؟',
    paragraph:'تعتبر النخلة رمزاً من الرموز الأساسية لسكان المملكة العربية السعودية فهي تعبير عن الأصالة والخير. (ص73)',
    options:[
      {text:'لأنها تعبير عن الأصالة والخير والهوية الوطنية',correct:true},
      {text:'لأنها أكبر الأشجار',correct:false},
      {text:'لأنها الوحيدة في الصحراء',correct:false},
      {text:'لا سبب محدد',correct:false},
    ],
    explanation:'النخلة = أصالة + خير + هوية = رمز وطني = شعار يوم التأسيس.',
    goldenRule:'النخلة = أصالة + خير + هوية = رمز المملكة = فخر وطني.',
  },
];

export const u3_extra = [...u3l1_extra, ...u3l2_extra, ...u3l3_extra];