// أسئلة إضافية — الوحدة الأولى: مجال الرسم
// درس 1: الطبيعة في بلادي (صفحة 10-19)

export const u1l1_extra = [
  {
    id:'u1l1q9', unit:'u1', lesson:'u1l1', page:10, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'تُعدّ صحراء النفود الكبير من أشهر المعالم الطبيعية في المملكة، وتقع في:',
    paragraph:'صحراء النفود الكبير: تمتد في شمال المملكة العربية السعودية، وتشتهر بكثبانها الرملية الذهبية المتحركة. (ص10)',
    options:[
      {text:'شمال المملكة العربية السعودية',correct:true},
      {text:'جنوب المملكة العربية السعودية',correct:false},
      {text:'شرق المملكة العربية السعودية',correct:false},
      {text:'غرب المملكة العربية السعودية',correct:false},
    ],
    explanation:'صحراء النفود الكبير تقع في شمال المملكة وتمتد لمسافات طويلة بكثبانها الرملية الذهبية.',
    goldenRule:'النفود الكبير = شمال المملكة = كثبان رملية ذهبية متحركة.',
  },
  {
    id:'u1l1q10', unit:'u1', lesson:'u1l1', page:10, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'تتميز شواطئ المملكة العربية السعودية بأنها تمتد على:',
    paragraph:'شاطئ البحر: تمتد شواطئ المملكة العربية السعودية على البحر الأحمر غرباً والخليج العربي شرقاً. (ص10)',
    options:[
      {text:'البحر الأحمر غرباً والخليج العربي شرقاً',correct:true},
      {text:'البحر المتوسط شمالاً فقط',correct:false},
      {text:'المحيط الهندي جنوباً فقط',correct:false},
      {text:'بحر قزوين غرباً فقط',correct:false},
    ],
    explanation:'المملكة لها شواطئ على البحر الأحمر (غرب) وعلى الخليج العربي (شرق) — تنوع ساحلي رائع.',
    goldenRule:'المملكة = بحرّان: الأحمر غرباً + الخليج شرقاً = تنوع ساحلي.',
  },
  {
    id:'u1l1q11', unit:'u1', lesson:'u1l1', page:11, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'الفنان التشكيلي السعودي "محمد السليم" اشتهر برسم لوحات تعبّر عن البيئة الصحراوية.',
    paragraph:'الفنان التشكيلي السعودي محمد السليم اشتهر برسم لوحات تعبّر عن البيئة الصحراوية بكثبانها الرملية. (ص11)',
    correctAnswer:true,
    explanation:'محمد السليم من رواد الفن التشكيلي السعودي، تميّز بلوحاته عن الصحراء وكثبانها الذهبية.',
    goldenRule:'محمد السليم = فنان الصحراء السعودية = لوحات ذهبية بالكثبان الرملية.',
  },
  {
    id:'u1l1q12', unit:'u1', lesson:'u1l1', page:12, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'تُمثّل لوحة الفنان "محمد العبلان" في الكتاب مشهداً طبيعياً يتميز بـ:',
    paragraph:'لوحة الفنان محمد العبلان تعبّر عن البيئة الجبلية والزراعية في المملكة. (ص12)',
    options:[
      {text:'الجبال الشاهقة والمدرجات الزراعية',correct:true},
      {text:'الصحراء والكثبان الرملية',correct:false},
      {text:'البحر والأمواج',correct:false},
      {text:'المدينة والناطحات',correct:false},
    ],
    explanation:'محمد العبلان عبّر في لوحته عن الجبال الشاهقة والمدرجات الزراعية كالتي في منطقة عسير.',
    goldenRule:'محمد العبلان = فنان الجبال والمدرجات = لوحات خضراء عالية.',
  },
  {
    id:'u1l1q13', unit:'u1', lesson:'u1l1', page:13, type:'trueFalse',
    bloom:'remember', difficulty:'easy',
    question:'مسابقة "ملون السعودية" للفن التشكيلي مخصصة للأطفال.',
    paragraph:'شارك الطفل طه حسين عيسى في مسابقة «ملون السعودية» للفن التشكيلي في دورتها الرابعة لعام 1998م. (ص13)',
    correctAnswer:true,
    explanation:'مسابقة "ملون السعودية" تشجّع الأطفال على ممارسة الفن التشكيلي والتعبير عن بيئتهم.',
    goldenRule:'مسابقة "ملون السعودية" = منصة للأطفال المبدعين = تشجيع الفن منذ الصغر.',
  },
  {
    id:'u1l1q14', unit:'u1', lesson:'u1l1', page:14, type:'multipleChoice',
    bloom:'apply', difficulty:'medium',
    question:'عند رسم مشهد الغروب بالباستيل، نبدأ بألوان:',
    paragraph:'نرسم منظراً للغروب، ونختار اللون الأصفر والبرتقالي والأحمر، ثم ندمج الألوان بالأصبع. (ص14)',
    options:[
      {text:'الأصفر والبرتقالي والأحمر (الألوان الدافئة)',correct:true},
      {text:'الأزرق والأخضر (الألوان الباردة)',correct:false},
      {text:'الأسود والرمادي (الألوان المحايدة)',correct:false},
      {text:'البنفسجي والوردي (الألوان الباستيلية)',correct:false},
    ],
    explanation:'مشهد الغروب يتميّز بالألوان الدافئة: أصفر + برتقالي + أحمر = تدرّج الغروب.',
    goldenRule:'ألوان الغروب = دافئة: أصفر ← برتقالي ← أحمر. الألوان الباردة = للبحر والسماء.',
  },
  {
    id:'u1l1q15', unit:'u1', lesson:'u1l1', page:14, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف الألوان التالية: دافئة أم باردة؟',
    paragraph:'الألوان الدافئة: أصفر، برتقالي، أحمر. الألوان الباردة: أزرق، أخضر، بنفسجي. (ص14)',
    categories:['ألوان دافئة 🔥','ألوان باردة ❄️'],
    items:[
      {text:'الأصفر',correct_category:0},
      {text:'الأحمر',correct_category:0},
      {text:'البرتقالي',correct_category:0},
      {text:'الأزرق',correct_category:1},
      {text:'الأخضر',correct_category:1},
      {text:'البنفسجي',correct_category:1},
    ],
    explanation:'الدافئة: أصفر+برتقالي+أحمر (كالنار والشمس). الباردة: أزرق+أخضر+بنفسجي (كالماء والظل).',
    goldenRule:'عجلة الألوان: نصف دافئ (نار/شمس) + نصف بارد (ماء/ظل).',
  },
  {
    id:'u1l1q16', unit:'u1', lesson:'u1l1', page:14, type:'trueFalse',
    bloom:'apply', difficulty:'easy',
    question:'في رسم الغروب، نستخدم الأصبع لدمج الألوان مع بعضها للحصول على تدرّج ناعم.',
    paragraph:'نرسم منظراً للغروب... ثم ندمج الألوان بالأصبع. (ص14)',
    correctAnswer:true,
    explanation:'دمج الألوان بالأصبع يُعطي تدرّجاً ناعماً بين الألوان — تقنية الباستيل الشمعي.',
    goldenRule:'دمج الباستيل بالأصبع = تدرّج ناعم = احترافية في الرسم.',
  },
  {
    id:'u1l1q17', unit:'u1', lesson:'u1l1', page:15, type:'multipleChoice',
    bloom:'apply', difficulty:'medium',
    question:'لرسم جذع وأغصان الشجرة في مشهد الغروب، نستخدم اللون:',
    paragraph:'نرسم جذع وأغصان الشجرة باللون البني. (ص14)',
    options:[
      {text:'البني',correct:true},
      {text:'الأزرق',correct:false},
      {text:'الأحمر',correct:false},
      {text:'الأصفر',correct:false},
    ],
    explanation:'جذع الشجرة وأغصانها تُرسم بالبني لأنه اللون الطبيعي للخشب.',
    goldenRule:'لون الخشب = بني. الأغصان والجذوع دائماً بالبني.',
  },
  {
    id:'u1l1q18', unit:'u1', lesson:'u1l1', page:15, type:'trueFalse',
    bloom:'apply', difficulty:'medium',
    question:'لرسم أوراق الشجرة ندمج اللونين البني الغامق والأسود معاً.',
    paragraph:'نرسم أوراق الشجرة بدمج اللونين البني الغامق والأسود معاً. (ص14)',
    correctAnswer:true,
    explanation:'دمج البني الغامق مع الأسود يُعطي ظلاً غامقاً للأوراق يُ contrast مع ألوان الغروب الدافئة.',
    goldenRule:'دمج بني غامق + أسود = أوراق غامقة = تباين مع الغروب الدافئ.',
  },
  {
    id:'u1l1q19', unit:'u1', lesson:'u1l1', page:15, type:'multipleChoice',
    bloom:'analyze', difficulty:'medium',
    question:'نضع اللون البني القاتم في أسفل اللوحة للحصول على:',
    paragraph:'نضع اللون البني القاتم في أسفل اللوحة للحصول على الظلال. (ص14)',
    options:[
      {text:'الظلال',correct:true},
      {text:'الضوء',correct:false},
      {text:'السماء',correct:false},
      {text:'الماء',correct:false},
    ],
    explanation:'اللون البني القاتم في الأسفل يُمثّل الظلال التي تصنعها الشجرة على الأرض.',
    goldenRule:'الظلال = لون غامق في الأسفل. الضوء = لون فاتح في الأعلى.',
  },
  {
    id:'u1l1q20', unit:'u1', lesson:'u1l1', page:16, type:'fillBlank',
    bloom:'remember', difficulty:'easy',
    question:'أكمل: "أنا أحافظ على ألواني جيداً بعد الرسم، ولا أكسرها وأضعها في ___ المخصصة لها."',
    paragraph:'أنا أحافظ على ألواني جيداً بعد الرسم، ولا أكسرها وأضعها في العلبة المخصصة لها. (ص14)',
    blanks:['العلبة'],
    wordBank:['العلبة','الحقيبة','الدرج','السيارة'],
    explanation:'المحافظة على الألوان تعني ترتيبها في علبتها المخصصة دون كسرها.',
    goldenRule:'نظّف ورتّب أدواتك الفنية بعد كل استخدام = فنان مسؤول.',
  },
  {
    id:'u1l1q21', unit:'u1', lesson:'u1l1', page:10, type:'matching',
    bloom:'remember', difficulty:'medium',
    question:'صِل كل منطقة في المملكة بنوع طبيعتها المميزة:',
    paragraph:'تنوع المناظر الطبيعية في المملكة: تبوك (جبال)، جدة (شاطئ)، النفود (صحراء)، أبها (مدرجات). (ص10)',
    pairs:[
      {left:'تبوك',right:'جبال شاهقة'},
      {left:'جدة',right:'شاطئ بحر'},
      {left:'النفود',right:'صحراء رملية'},
      {left:'أبها',right:'مدرجات زراعية'},
    ],
    explanation:'كل منطقة في المملكة لها طبيعتها المميزة التي تُمثّل تنوع المملكة الجغرافي.',
    goldenRule:'المملكة = 4 مناظر: جبال (تبوك) + بحر (جدة) + صحراء (النفود) + زراعة (أبها).',
  },
  {
    id:'u1l1q22', unit:'u1', lesson:'u1l1', page:11, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'لماذا يُعدّ التنوع الطبيعي في المملكة مصدر إلهام للفنانين؟',
    paragraph:'تتميز الطبيعة في المملكة العربية السعودية بتنوع المناظر الطبيعية... وقد استوحى كثير من الفنانين التشكيليين أعمالهم الفنية من طبيعة المملكة. (ص10-11)',
    options:[
      {text:'لأن التنوع يوفّر موضوعات لا تنتهي للتعبير الفني من صحراء وجبال وبحر وزراعة',correct:true},
      {text:'لأن الفنانين مضطرون لذلك',correct:false},
      {text:'لأنه لا يوجد ما يرسمونه غير الطبيعة',correct:false},
      {text:'لأن القانون يُلزم بذلك',correct:false},
    ],
    explanation:'التنوع الطبيعي يُغني الفنان بمصادر إلهام متعددة: الصحراء للدافئ، البحر للبارد، الجبال للعالي، الزراعة للأخضر.',
    goldenRule:'التنوع البيئي = ثروة فنية. كل بيئة تُلهم أسلوباً وألواناً وموضوعاً.',
  },
  {
    id:'u1l1q23', unit:'u1', lesson:'u1l1', page:12, type:'trueFalse',
    bloom:'analyze', difficulty:'medium',
    question:'استخدم الفنانون في لوحاتهم الطبيعية العناصر الشكلية من خط ولون وملمس.',
    paragraph:'وقد استخدم الفنانون في لوحاتهم السابقة العناصر الشكلية من خط ولون وملمس؛ للتعبير عن المناظر الطبيعية. (ص12)',
    correctAnswer:true,
    explanation:'العناصر الشكلية الثلاثة (خط + لون + ملمس) هي أدوات الفنان للتعبير عن الطبيعة.',
    goldenRule:'الخط يحدد + اللون يعبّر + الملمس يُحسّس = عناصر اللوحة الفنية.',
  },
  {
    id:'u1l1q24', unit:'u1', lesson:'u1l1', page:10, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'المدرجات الزراعية المذكورة في الكتاب تقع في مدينة:',
    paragraph:'مدرجات زراعية من أبها. (ص10)',
    options:[
      {text:'أبها',correct:true},
      {text:'الرياض',correct:false},
      {text:'تبوك',correct:false},
      {text:'جدة',correct:false},
    ],
    explanation:'أبها في منطقة عسير جنوب المملكة تشتهر بالمدرجات الزراعية الخضراء على جبال السروات.',
    goldenRule:'أبها = مدرجات زراعية خضراء على الجبال = جبال + زراعة معاً.',
  },
  {
    id:'u1l1q25', unit:'u1', lesson:'u1l1', page:13, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'ما الشجرة التي رسمها الطفل طه حسين عيسى في لوحته؟',
    paragraph:'شارك الطفل «طه حسين عيسى»... بلوحة تعبر عن النخيل، شكل (٤). (ص13)',
    options:[
      {text:'النخيل',correct:true},
      {text:'السنديان',correct:false},
      {text:'الصبّار',correct:false},
      {text:'الورد',correct:false},
    ],
    explanation:'النخلة هي الشجرة التي رسمها الطفل — رمز المملكة العربية السعودية.',
    goldenRule:'النخلة = شجرة المملكة = رمز الخير والكرم.',
  },
  {
    id:'u1l1q26', unit:'u1', lesson:'u1l1', page:14, type:'ordering',
    bloom:'apply', difficulty:'hard',
    question:'رتّب ألوان الغروب من الأعلى للأسفل (من السماء للأرض):',
    paragraph:'نرسم منظراً للغروب، ونختار اللون الأصفر والبرتقالي والأحمر، ثم ندمج الألوان بالأصبع. (ص14)',
    items:['الأحمر (قرب الأفق)','البرتقالي (المنتصف)','الأصفر (أعلى السماء)','البني القاتم (الأرض والظلال)'],
    correctOrder:[2,1,0,3],
    explanation:'من الأعلى: أصفر (سماء عالية) ← برتقالي (وسط) ← أحمر (أفق) ← بني قاتم (أرض وظلال).',
    goldenRule:'تدرّج الغروب: أصفر ← برتقالي ← أحمر ← بني. الضوء من أعلى، الظل في أسفل.',
  },
  {
    id:'u1l1q27', unit:'u1', lesson:'u1l1', page:12, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'ما العنصر الشكلي الذي يُستخدم لتحديد حدود الأشياء في اللوحة؟',
    paragraph:'وقد استخدم الفنانون في لوحاتهم السابقة العناصر الشكلية من خط ولون وملمس. (ص12)',
    options:[
      {text:'الخط',correct:true},
      {text:'اللون',correct:false},
      {text:'الملمس',correct:false},
      {text:'الحجم',correct:false},
    ],
    explanation:'الخط هو العنصر الذي يُحدّد حدود الأشكال والمناظر في اللوحة.',
    goldenRule:'الخط = حدود الشكل. اللون = تعبير. الملمس = إحساس لمسي.',
  },
  {
    id:'u1l1q28', unit:'u1', lesson:'u1l1', page:11, type:'trueFalse',
    bloom:'evaluate', difficulty:'medium',
    question:'يُعتبر الفن وسيلة للتعبير عن الهوية الوطنية والبيئة المحلية.',
    paragraph:'وقد استوحى كثير من الفنانين التشكيليين أعمالهم الفنية من طبيعة المملكة العربية السعودية المتنوعة. (ص11)',
    correctAnswer:true,
    explanation:'الفن يعكس هوية الفنان وبيئته — الفنانون السعوديون يُعبّرون عن المملكة في لوحاتهم.',
    goldenRule:'الفن = هوية. لوحاتنا تعكس بيئتنا وتراثنا وانتماءنا.',
  },
  {
    id:'u1l1q29', unit:'u1', lesson:'u1l1', page:14, type:'trueFalse',
    bloom:'apply', difficulty:'easy',
    question:'ألوان الباستيل الشمعية سهلة الدمج بالأصابع.',
    paragraph:'نرسم منظراً للغروب، ونختار اللون الأصفر والبرتقالي والأحمر، ثم ندمج الألوان بالأصبع. (ص14)',
    correctAnswer:true,
    explanation:'الباستيل الشمعي يتميّز بسهولة دمجه بالأصابع لإنتاج تدرّجات لونية ناعمة.',
    goldenRule:'الباستيل الشمعي = دمج بالأصبع = تدرّجات ناعمة وجميلة.',
  },
  {
    id:'u1l1q30', unit:'u1', lesson:'u1l1', page:10, type:'multipleChoice',
    bloom:'create', difficulty:'hard',
    question:'لو أردت رسم لوحة تعبّر عن تنوّع طبيعة المملكة، ما الألوان التي تختارها؟',
    paragraph:'تنوع المناظر الطبيعية في المملكة: صحراء ذهبية، جبال خضراء، بحر أزرق، مدرجات زراعية. (ص10)',
    options:[
      {text:'ذهبي للصحراء + أخضر للجبال + أزرق للبحر + بني للأرض',correct:true},
      {text:'أحمر وأسود فقط',correct:false},
      {text:'أبيض ورمادي فقط',correct:false},
      {text:'وردي وبنفسجي فقط',correct:false},
    ],
    explanation:'لكل بيئة لونها: ذهبي للصحراء، أخضر للجبال والزراعة، أزرق للبحر، بني للأرض والظلال.',
    goldenRule:'ألوان المملكة: ذهبي (صحراء) + أخضر (جبال) + أزرق (بحر) + بني (أرض).',
  },
  {
    id:'u1l1q31', unit:'u1', lesson:'u1l1', page:12, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'الملمس في اللوحة يعطينا إحساساً بأننا نلمس الشكل المرسوم.',
    paragraph:'وقد استخدم الفنانون في لوحاتهم... ملمس؛ للتعبير عن المناظر الطبيعية. (ص12)',
    correctAnswer:true,
    explanation:'الملمس يُعيد إحساس اللمس للشكل: ناعم، خشن، مadrid — يجعل اللوحة أكثر واقعية.',
    goldenRule:'الملمس = إحساس لمسي في اللوحة = ناعم/خشن/مadrid/لامع.',
  },
  {
    id:'u1l1q32', unit:'u1', lesson:'u1l1', page:14, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'ما الأداة المستخدمة لدمج ألوان الباستيل في رسم الغروب؟',
    paragraph:'ثم ندمج الألوان بالأصبع. (ص14)',
    options:[
      {text:'الأصبع',correct:true},
      {text:'الفرشاة',correct:false},
      {text:'الإسفنجة',correct:false},
      {text:'السكين',correct:false},
    ],
    explanation:'الأصبع هي الأداة المستخدمة لدمج الباستيل الشمعي بسهولة.',
    goldenRule:'دمج الباستيل = بالأصبع. الدمج يُنتج تدرّجاً لونياً ناعماً.',
  },
  {
    id:'u1l1q33', unit:'u1', lesson:'u1l1', page:11, type:'multipleChoice',
    bloom:'analyze', difficulty:'hard',
    question:'ما القاسم المشترك بين لوحات الفنانين السعوديين المذكورين في الكتاب؟',
    paragraph:'وقد استوحى كثير من الفنانين التشكيليين أعمالهم الفنية من طبيعة المملكة العربية السعودية المتنوعة. (ص11)',
    options:[
      {text:'جميعها مستوحاة من الطبيعة والبيئة السعودية',correct:true},
      {text:'جميعها عن البحر فقط',correct:false},
      {text:'جميعها عن المدينة فقط',correct:false},
      {text:'لا قاسم مشترك بينها',correct:false},
    ],
    explanation:'جميع الفنانين السعوديين في الكتاب استوحوا أعمالهم من البيئة السعودية المتنوعة.',
    goldenRule:'الفن السعودي = فن بيئي. مصدر الإلهام = المملكة بتنوعها.',
  },
  // ─── درس 2: الفن والطبيعة (صفحة 20-25) ───
  {
    id:'u1l2q9', unit:'u1', lesson:'u1l2', page:20, type:'trueFalse',
    bloom:'remember', difficulty:'easy',
    question:'الجبال والصخور من عناصر الطبيعة التي تُلهم الفنان.',
    paragraph:'تتجلى قدرة الخالق سبحانه وتعالى فيما نراه من عناصر طبيعية متعددة... مثل: النباتات والأشجار والأزهار والثمار والجبال والصخور والرمال والحيوانات والطيور والحشرات. (ص20)',
    correctAnswer:true,
    explanation:'الجبال والصخور من عناصر الطبيعة التي يستلهم منها الفنان أشكالاً وألواناً وملامس.',
    goldenRule:'الطبيعة = جبال + صخور + رمال + نباتات + حيوانات = مصدر لا ينضب للفن.',
  },
  {
    id:'u1l2q10', unit:'u1', lesson:'u1l2', page:20, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'الحشرات والطيور من عناصر الطبيعة التي:',
    paragraph:'مثل: النباتات والأشجار والأزهار والثمار والجبال والصخور والرمال والحيوانات والطيور والحشرات. (ص20)',
    options:[
      {text:'تُلهم الفنان بأشكالها وألوانها الجميلة',correct:true},
      {text:'تُزعج الفنان فقط',correct:false},
      {text:'لا علاقة لها بالفن',correct:false},
      {text:'تمنع الفنان من الرسم',correct:false},
    ],
    explanation:'الطيور بحلقها وحشرات بألوانها (كالفراشات) تُلهم الفنان أشكالاً وألواناً.',
    goldenRule:'الفراشة = تحفة طبيعية. ألوانها وأجنحتها مصدر إلهام فني.',
  },
  {
    id:'u1l2q11', unit:'u1', lesson:'u1l2', page:21, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'عند تأمل أوراق النبات نلاحظ اختلاف خطوطها الداخلية (العروق) والخارجية (الحواف).',
    paragraph:'نصفها من حيث: ألوانها، وملمسها، وخطوطها الداخلية والخارجية. (ص21)',
    correctAnswer:true,
    explanation:'الخطوط الداخلية = عروق الورقة. الخطوط الخارجية = حواف الورقة (مسننة، ناعمة، مدوّرة).',
    goldenRule:'كل ورقة نبات: خطوط داخلية (عروق) + خطوط خارجية (حواف) + لون + ملمس.',
  },
  {
    id:'u1l2q12', unit:'u1', lesson:'u1l2', page:22, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'الفنان "كلود مونيه" من أي دولة؟',
    paragraph:'شكل (9): لوحة للفنان الفرنسي «كلود مونيه». (ص22)',
    options:[
      {text:'فرنسا',correct:true},
      {text:'إيطاليا',correct:false},
      {text:'إسبانيا',correct:false},
      {text:'اليابان',correct:false},
    ],
    explanation:'كلود مونيه فنان فرنسي من رواد المدرسة الانطباعية في الرسم.',
    goldenRule:'كلود مونيه = فرنسي = انطباعي = لوحات عن الطبيعة بألوان ناعمة.',
  },
  {
    id:'u1l2q13', unit:'u1', lesson:'u1l2', page:22, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'الفنانان السعوديان المذكوران مع كلود مونيه في الكتاب هما:',
    paragraph:'وقد استوحى الفنانون التشكيليون العالميون والمحليون أعمالهم الفنية من الطبيعة... شكل (9): لوحة للفنان الفرنسي «كلود مونيه»، شكل (10): لوحة للفنان «إحسان برهان»، شكل (11): لوحة للفنان «إبراهيم بوقس». (ص22)',
    options:[
      {text:'إحسان برهان وإبراهيم بوقس',correct:true},
      {text:'محمد السليم ومحمد العبلان',correct:false},
      {text:'أحمد الأعرج وسعود النفيعي',correct:false},
      {text:'رائدة عاشور وماجد رضوي',correct:false},
    ],
    explanation:'إحسان برهان وإبراهيم بوقس فنانان سعوديان استوحيا من الطبيعة مثل مونيه.',
    goldenRule:'الفنانون السعوديون: إحسان برهان + إبراهيم بوقس = استلهموا من الطبيعة.',
  },
  {
    id:'u1l2q14', unit:'u1', lesson:'u1l2', page:23, type:'trueFalse',
    bloom:'remember', difficulty:'easy',
    question:'الفنان "مجدي عبد الحليم رضوي" شارك في معرض المراسم الرابع عام 1409هـ.',
    paragraph:'شارك الفنان «مجدي عبد الحليم رضوي» في معرض المراسم الرابع لعام 1409هـ. (ص23)',
    correctAnswer:true,
    explanation:'معرض المراسم معرض فني سعودي دوري شارك فيه مجدي رضوي عام 1409هـ.',
    goldenRule:'معرض المراسم = معرض فني سعودي = منصة للفنانين السعوديين.',
  },
  {
    id:'u1l2q15', unit:'u1', lesson:'u1l2', page:23, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'عند تأمل لوحة فنية، ماذا نطلب من الطالب أن يفعل؟',
    paragraph:'نتأمل اللوحة جيداً، ثم: نعدد العناصر الشكلية المستخدمة في اللوحة؟ نضع عنواناً لهذه اللوحة. (ص23)',
    options:[
      {text:'يُعدّد العناصر الشكلية ويضع عنواناً للوحة',correct:true},
      {text:'يقلّد اللوحة فوراً',correct:false},
      {text:'يتجاهل اللوحة',correct:false},
      {text:'يكتفي بالنظر فقط',correct:false},
    ],
    explanation:'تأمل اللوحة = عدّ العناصر الشكلية (خط/لون/ملمس) + وضع عنوان مناسب.',
    goldenRule:'التأمل الفني = عدّ العناصر + التسمية + الوصف = فهم عميق للوحة.',
  },
  {
    id:'u1l2q16', unit:'u1', lesson:'u1l2', page:24, type:'multipleChoice',
    bloom:'apply', difficulty:'medium',
    question:'بأي أداة نرسم الخطوط الداخلية لجناح الفراشة؟',
    paragraph:'نرسم مجموعة من الخطوط داخل الشكل باللون الأسود الشمعي. (ص24)',
    options:[
      {text:'لون أسود شمعي',correct:true},
      {text:'قلم رصاص فاتح',correct:false},
      {text:'لون أبيض',correct:false},
      {text:'ألوان مائية',correct:false},
    ],
    explanation:'الخطوط الداخلية للفراشة تُرسم باللون الأسود الشمعي لإبراز تفاصيل الجناح.',
    goldenRule:'الخطوط الداخلية = أسود شمعي = تفاصيل واضحة على الجناح.',
  },
  {
    id:'u1l2q17', unit:'u1', lesson:'u1l2', page:24, type:'trueFalse',
    bloom:'apply', difficulty:'medium',
    question:'نستخدم اللون الفاتح للضوء واللون الغامق للظل في تلوين جناح الفراشة.',
    paragraph:'نوزع الألوان على جناح الفراشة (فاتح للضوء وغامق للظل). (ص24)',
    correctAnswer:true,
    explanation:'الضوء = لون فاتح. الظل = لون غامق. هذا يُعطي الفراشة عمقاً وواقعية.',
    goldenRule:'الضوء فاتح + الظل غامق = عمق ثلاثي الأبعاد في الرسم.',
  },
  {
    id:'u1l2q18', unit:'u1', lesson:'u1l2', page:24, type:'ordering',
    bloom:'apply', difficulty:'medium',
    question:'رتّب خطوات رسم الفراشة بالباستيل الشمعي:',
    paragraph:'الخطوة الأولى: نرسم الخط الخارجي للفراشة. الخطوة الثانية: نرسم مجموعة من الخطوط داخل الشكل باللون الأسود الشمعي. الخطوة الثالثة: نوزع الألوان على جناح الفراشة (فاتح للضوء وغامق للظل). الخطوة الرابعة: نقص الفراشة بالمقص. (ص24-25)',
    items:['نقص الفراشة بالمقص','نوزع الألوان (فاتح للضوء وغامق للظل)','نرسم الخطوط الداخلية بالأسود الشمعي','نرسم الخط الخارجي للفراشة'],
    correctOrder:[3,2,1,0],
    explanation:'(1) إطار خارجي ← (2) خطوط داخلية ← (3) توزيع ألوان ← (4) قص.',
    goldenRule:'رسم الفراشة: إطار ← خطوط داخلية ← ألوان (فاتح/غامق) ← قص.',
  },
  {
    id:'u1l2q19', unit:'u1', lesson:'u1l2', page:24, type:'fillBlank',
    bloom:'apply', difficulty:'easy',
    question:'أكمل: "وحتى نحصل على ملمس لجناح الفراشة نضع تحت ورقة الرسم ___ ثم نُلوّن باللون."',
    paragraph:'وحتى نحصل على ملمس لجناح الفراشة نضع تحت ورقة الرسم ورق صنفرة أو خيش ثم نُلوّن باللون. (ص24)',
    blanks:['ورق صنفرة أو خيش'],
    wordBank:['ورق صنفرة أو خيش','قطعة معدن','زجاج شفاف','قطعة قماش حريرية'],
    explanation:'ورق الصنفرة أو الخيش خشن الملمس — عند وضعه تحت الورقة وتلوينها ينتقل الملمس الخشن للرسم.',
    goldenRule:'ورق صنفرة/خيش تحت الورقة + تلوين = ملمس خشن على الرسم.',
  },
  {
    id:'u1l2q20', unit:'u1', lesson:'u1l2', page:25, type:'multipleChoice',
    bloom:'apply', difficulty:'medium',
    question:'ما الأداة المستخدمة لتثبيت الفراشة المقصوصة على حقيبة أو برواز؟',
    paragraph:'نستعمل الغراء لتثبيت الفراشة على حقيبة أو برواز صورة... وغيرها. (ص25)',
    options:[
      {text:'الغراء (الصمغ)',correct:true},
      {text:'الخيط والإبرة',correct:false},
      {text:'الشريط اللاصق فقط',correct:false},
      {text:'الدبابيس',correct:false},
    ],
    explanation:'الغراء يُثبّت الفراشة المقصوصة على الحقيبة أو البرواز بشكل آمن وجمالي.',
    goldenRule:'الغراء = أداة تثبيت فنية. تُثبّت الرسم على المنتج.',
  },
  {
    id:'u1l2q21', unit:'u1', lesson:'u1l2', page:25, type:'trueFalse',
    bloom:'evaluate', difficulty:'medium',
    question:'يمكن تثبيت الفراشة المقصوصة على حقيبة لإضافة لمسة جمالية عملية.',
    paragraph:'نستعمل الغراء لتثبيت الفراشة على حقيبة أو برواز صورة. (ص25)',
    correctAnswer:true,
    explanation:'هذا مثال على الفن التطبيقي — تحويل الرسم لمنتج جميل ومفيد.',
    goldenRule:'الفن التطبيقي = جمال + فائدة. من الرسم إلى منتج.',
  },
  {
    id:'u1l2q22', unit:'u1', lesson:'u1l2', page:20, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف عناصر الطبيعة المذكورة في الكتاب:',
    paragraph:'مثل: النباتات والأشجار والأزهار والثمار والجبال والصخور والرمال والحيوانات والطيور والحشرات. (ص20)',
    categories:['عناصر نباتية 🌿','عناصر حيوانية 🦋','عناصر أرضية 🏔️'],
    items:[
      {text:'الأشجار',correct_category:0},
      {text:'الأزهار',correct_category:0},
      {text:'الثمار',correct_category:0},
      {text:'الطيور',correct_category:1},
      {text:'الحشرات',correct_category:1},
      {text:'الحيوانات',correct_category:1},
      {text:'الجبال',correct_category:2},
      {text:'الصخور',correct_category:2},
      {text:'الرمال',correct_category:2},
    ],
    explanation:'نباتية: أشجار/أزهار/ثمار. حيوانية: طيور/حشرات/حيوانات. أرضية: جبال/صخور/رمال.',
    goldenRule:'الطبيعة = نباتات + حيوانات + أرض. ثلاث مملكات لإلهام الفنان.',
  },
  {
    id:'u1l2q23', unit:'u1', lesson:'u1l2', page:22, type:'matching',
    bloom:'remember', difficulty:'medium',
    question:'صِل كل فنان بدولته:',
    paragraph:'الفنانون العالميون والمحليون: كلود مونيه (فرنسي)، إحسان برهان (سعودي)، إبراهيم بوقس (سعودي). (ص22)',
    pairs:[
      {left:'كلود مونيه',right:'فرنسا'},
      {left:'إحسان برهان',right:'السعودية'},
      {left:'إبراهيم بوقس',right:'السعودية'},
    ],
    explanation:'مونيه فرنسي. إحسان برهان وإبراهيم بوقس سعوديان. جميعهم استلهموا من الطبيعة.',
    goldenRule:'الفن عالمي — فنانون من كل الدول يلهمهم نفس المصدر: الطبيعة.',
  },
  {
    id:'u1l2q24', unit:'u1', lesson:'u1l2', page:24, type:'trueFalse',
    bloom:'apply', difficulty:'medium',
    question:'الخط الخارجي للفراشة يُرسم أولاً قبل الخطوط الداخلية.',
    paragraph:'الخطوة الأولى: نرسم الخط الخارجي للفراشة. الخطوة الثانية: نرسم مجموعة من الخطوط داخل الشكل. (ص24)',
    correctAnswer:true,
    explanation:'دائماً نرسم الإطار الخارجي أولاً ثم التفاصيل الداخلية — قاعدة الرسم الأساسية.',
    goldenRule:'الإطار الخارجي أولاً ← التفاصيل الداخلية ثانياً = قاعدة الرسم.',
  },
  {
    id:'u1l2q25', unit:'u1', lesson:'u1l2', page:21, type:'multipleChoice',
    bloom:'analyze', difficulty:'medium',
    question:'ما الذي يختلف بين أوراق النبات المختلفة عند تأملها فنياً؟',
    paragraph:'وإذا تأملناها وجدناها تختلف في خطوطها وألوانها وملامسها. (ص20-21)',
    options:[
      {text:'خطوطها وألوانها وملامسها',correct:true},
      {text:'أسعارها وأوزانها',correct:false},
      {text:'أسمائها ومواطنها فقط',correct:false},
      {text:'لا شيء يختلف',correct:false},
    ],
    explanation:'التأمل الفني يكشف الاختلاف في: الخطوط (عروق/حواف) + الألوان (أخضر فاتح/غامق) + الملامس (ناعم/خشن).',
    goldenRule:'كل ورقة فريدة في: خطوطها + ألوانها + ملامسها = إلهام لا ينتهي.',
  },
  {
    id:'u1l2q26', unit:'u1', lesson:'u1l2', page:23, type:'trueFalse',
    bloom:'evaluate', difficulty:'hard',
    question:'وضع عنوان للوحة يساعد المشاهد على فهم رسالة الفنان.',
    paragraph:'نضع عنواناً لهذه اللوحة. (ص23)',
    correctAnswer:true,
    explanation:'العنوان يُوجّه المشاهد ويعطيه مفتاحاً لفهم اللوحة ورسالتها.',
    goldenRule:'العنوان = مفتاح اللوحة. يربط الفنان بالمشاهد.',
  },
  {
    id:'u1l2q27', unit:'u1', lesson:'u1l2', page:24, type:'multipleChoice',
    bloom:'create', difficulty:'hard',
    question:'لو أردت إضافة ملمس لرسمة فراشة، ماذا تضع تحت الورقة؟',
    paragraph:'وحتى نحصل على ملمس لجناح الفراشة نضع تحت ورقة الرسم ورق صنفرة أو خيش ثم نُلوّن. (ص24)',
    options:[
      {text:'ورق صنفرة أو خيش (مادة خشنة)',correct:true},
      {text:'ورق زجاجي ناعم',correct:false},
      {text:'قطعة بلاستيك ملساء',correct:false},
      {text:'لا شيء',correct:false},
    ],
    explanation:'المادة الخشنة تحت الورقة تنقل ملمسها للرسم عند التلوين فوقها.',
    goldenRule:'الملمس = مادة خشنة تحت الورقة + تلوين = نسيج جميل على الرسم.',
  },
  {
    id:'u1l2q28', unit:'u1', lesson:'u1l2', page:20, type:'trueFalse',
    bloom:'remember', difficulty:'easy',
    question:'الرمال من عناصر الطبية التي يمكن للفنان أن يستوحي منها.',
    paragraph:'مثل: النباتات والأشجار والأزهار والثمار والجبال والصخور والرمال والحيوانات والطيور والحشرات. (ص20)',
    correctAnswer:true,
    explanation:'الرمال بألوانها الذهبية وأشكال كثبانها مصدر إلهام للفنان — كما في لوحات محمد السليم.',
    goldenRule:'الرمال الذهبية = لون + ملمس + شكل = مصدر فني صحراوي.',
  },
  {
    id:'u1l2q29', unit:'u1', lesson:'u1l2', page:24, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'لماذا نستخدم اللون الفاتح في جانب والغامق في آخر من جناح الفراشة؟',
    paragraph:'نوزع الألوان على جناح الفراشة (فاتح للضوء وغامق للظل). (ص24)',
    options:[
      {text:'لإظهار الضوء والظل وإعطاء الجناح عمقاً ثلاثي الأبعاد',correct:true},
      {text:'لتوفير الألوان فقط',correct:false},
      {text:'لأنه لا توجد ألوان أخرى',correct:false},
      {text:'لتلوين الجانبين بنفس اللون',correct:false},
    ],
    explanation:'توزيع الفاتح والغامق يُحاكي الضوء الطبيعي ويُعطي الجناح عمقاً وواقعية.',
    goldenRule:'الضوء/الظل = فاتح/غامق = عمق وواقعية في الرسم.',
  },
  {
    id:'u1l2q30', unit:'u1', lesson:'u1l2', page:25, type:'multipleChoice',
    bloom:'apply', difficulty:'easy',
    question:'ما الفائدة العملية من رسم الفراشة وقصّها؟',
    paragraph:'نستعمل الغراء لتثبيت الفراشة على حقيبة أو برواز صورة... وغيرها. (ص25)',
    options:[
      {text:'تزيين حقيبة أو برواز صورة بلمسة فنية',correct:true},
      {text:'لا فائدة عملية',correct:false},
      {text:'لتعليقها على الجدار فقط',correct:false},
      {text:'لرميها بعد الرسم',correct:false},
    ],
    explanation:'الفراشة المقصوصة تُزيّن حقائب وبراويز الصور = فن تطبيقي نافع.',
    goldenRule:'الفراشة المقصوصة = فن تطبيقي = جمال + فائدة في الحياة اليومية.',
  },
  // ─── درس 3: أجدادنا وفن الرسم (صفحة 26-35) ───
  {
    id:'u1l3q9', unit:'u1', lesson:'u1l3', page:26, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'الخط يُعتبر ___ الوسائل في التعبير الفني.',
    paragraph:'الخط هو أقدم الوسائل التي استُخدمت في التعبير الفني، ويعتبر العنصر الأساس في الرسم. (ص26)',
    options:[
      {text:'أقدم',correct:true},
      {text:'أحدث',correct:false},
      {text:'أصعب',correct:false},
      {text:'أقل أهمية',correct:false},
    ],
    explanation:'الخط هو أقدم وسيلة فنية استخدمها الإنسان — من نقوش الكهوف إلى الفن الحديث.',
    goldenRule:'الخط = أقدم أداة فنية = أساس كل الرسم.',
  },
  {
    id:'u1l3q10', unit:'u1', lesson:'u1l3', page:26, type:'trueFalse',
    bloom:'remember', difficulty:'easy',
    question:'الخط يُعتبر العنصر الأساس في الرسم.',
    paragraph:'ويعتبر العنصر الأساس في الرسم. (ص26)',
    correctAnswer:true,
    explanation:'الخط هو العنصر الأساسي — كل رسم يبدأ بخط يحدد الشكل.',
    goldenRule:'الخط = العنصر الأساسي في الرسم = بداية كل لوحة.',
  },
  {
    id:'u1l3q11', unit:'u1', lesson:'u1l3', page:26, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'من وظائف الخط في الرسم:',
    paragraph:'و له وظائف مختلفة منها: تحديد الخط الخارجي للشكل، إظهار تفاصيل الشكل الداخلية. (ص26)',
    options:[
      {text:'تحديد الخط الخارجي + إظهار تفاصيل الشكل الداخلية',correct:true},
      {text:'إضافة الألوان فقط',correct:false},
      {text:'تنظيف اللوحة',correct:false},
      {text:'قص الورق',correct:false},
    ],
    explanation:'الخط يحدد الشكل من الخارج ويُظهر تفاصيله من الداخل — وظيفتان أساسيتان.',
    goldenRule:'الخط: (1) خارجي = حدود الشكل (2) داخلي = تفاصيل الشكل.',
  },
  {
    id:'u1l3q12', unit:'u1', lesson:'u1l3', page:26, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف أنواع الخطوط:',
    paragraph:'الخط قد يكون مستقيماً أو متعرجاً أو منحنياً أو منكسراً، رأسياً أو أفقياً أو مائلاً. (ص26)',
    categories:['خطوط مستقيمة','خطوط منحنية/متحركة'],
    items:[
      {text:'رأسي مستقيم',correct_category:0},
      {text:'أفقي مستقيم',correct_category:0},
      {text:'مائل مستقيم',correct_category:0},
      {text:'منحني',correct_category:1},
      {text:'متعرج',correct_category:1},
      {text:'منكسر',correct_category:1},
    ],
    explanation:'مستقيمة: رأسي + أفقي + مائل. منحنية/متحركة: منحني + متعرج + منكسر.',
    goldenRule:'6 أنواع للخط: مستقيم (3) + متحرك (3). كل خط له إيحاءه.',
  },
  {
    id:'u1l3q13', unit:'u1', lesson:'u1l3', page:28, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'استخدم الفنان ___ الخط لتحديد الشكل في الرسم.',
    paragraph:'لقد استخدم الفنان الشعبي الخط لتحديد الشكل في الرسم، شكل (١٦). (ص28)',
    options:[
      {text:'الشعبي',correct:true},
      {text:'الحديث',correct:false},
      {text:'الرقمي',correct:false},
      {text:'الأجنبي',correct:false},
    ],
    explanation:'الفنان الشعبي استخدم الخط — أقدم أداة فنية — في تحديد الأشكال والزخارف.',
    goldenRule:'الفنان الشعبي = يحدد الشكل بالخط = فطرة فنية أصيلة.',
  },
  {
    id:'u1l3q14', unit:'u1', lesson:'u1l3', page:28, type:'trueFalse',
    bloom:'understand', difficulty:'medium',
    question:'الفنان الشعبي استوحى خطوطه من عناصر الطبيعة المحيطة به.',
    paragraph:'فالفنان الشعبي من فطرته رسم الخطوط بأنواعها المختلفة مستوحياً من الطبيعة: الجبال، الشمس، القمر، البرق، عناقيد العنب. (ص28)',
    correctAnswer:true,
    explanation:'الفنان الشعبي نظر للطبيعة: جبال (خطوط مرتفعة)، شمس (دوائر)، برق (خطوط متعرجة)، عناقيد (منحنيات).',
    goldenRule:'الطبيعة = معلم الخطوط. جبال = رأسي، شمس = دائري، برق = متعرج.',
  },
  {
    id:'u1l3q15', unit:'u1', lesson:'u1l3', page:28, type:'matching',
    bloom:'analyze', difficulty:'medium',
    question:'صِل كل عنصر طبيعي بنوع الخط الذي يستوحي منه الفنان الشعبي:',
    paragraph:'مستوحياً من الطبيعة: الجبال، الشمس، القمر، البرق، عناقيد العنب. (ص28)',
    pairs:[
      {left:'الجبال',right:'خطوط رأسية مرتفعة'},
      {left:'الشمس والقمر',right:'خطوط منحنية دائرية'},
      {left:'البرق',right:'خطوط متعرجة حادة'},
      {left:'عناقيد العنب',right:'خطوط منحنية متدلية'},
    ],
    explanation:'الجبال = رأسي. الشمس/القمر = دائري. البرق = متعرج. العنب = منحني متدلٍ.',
    goldenRule:'كل عنصر طبيعي يُلهم نوعاً من الخطوط — الطبيعة معلّم الفنان.',
  },
  {
    id:'u1l3q16', unit:'u1', lesson:'u1l3', page:30, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'فن "القط العسيري" اشتهر في منطقة:',
    paragraph:'زخارف شعبية من فن القط العسيري الذي اشتُهرت به منطقة عسير في جنوب المملكة. (ص30)',
    options:[
      {text:'عسير في جنوب المملكة',correct:true},
      {text:'الرياض في وسط المملكة',correct:false},
      {text:'تبوك في شمال المملكة',correct:false},
      {text:'الدمام في شرق المملكة',correct:false},
    ],
    explanation:'القط العسيري فن شعبي من منطقة عسير جنوب المملكة — تراث نسائي أصيل.',
    goldenRule:'القط العسيري = عسير = جنوب المملكة = تراث نسائي فني.',
  },
  {
    id:'u1l3q17', unit:'u1', lesson:'u1l3', page:30, type:'trueFalse',
    bloom:'remember', difficulty:'easy',
    question:'سُجّل فن القط العسيري كتراث ثقافي سعودي غير مادي في منظمة اليونسكو.',
    paragraph:'تم تسجيله كتراث ثقافي سعودي غير مادي في منظمة اليونسكو 2017م. (ص30)',
    correctAnswer:true,
    explanation:'اليونسكو سجّل القط العسيري كتراث إنساني غير مادي — اعتراف عالمي بفننا الشعبي.',
    goldenRule:'القط العسيري = تراث عالمي معترف به من اليونسكو 2017م.',
  },
  {
    id:'u1l3q18', unit:'u1', lesson:'u1l3', page:30, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'في أي عام سُجّل القط العسيري في اليونسكو؟',
    paragraph:'تم تسجيله كتراث ثقافي سعودي غير مادي في منظمة اليونسكو 2017م. (ص30)',
    options:[
      {text:'2017م',correct:true},
      {text:'2010م',correct:false},
      {text:'2005م',correct:false},
      {text:'2020م',correct:false},
    ],
    explanation:'عام 2017م — سنة اعتراف اليونسكو بالقط العسيري كتراث إنساني.',
    goldenRule:'القط العسيري + اليونسكو = 2017م = سنة الاعتراف العالمي.',
  },
  {
    id:'u1l3q19', unit:'u1', lesson:'u1l3', page:29, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'ما الأشياء التي زخرفها الفنان الشعبي بخطوطه؟',
    paragraph:'وزخرف بهذه الخطوط جدران المنازل والأبواب والنوافذ، وأواني الشرب والطهي وتطريز الملابس... وغيرها. (ص29)',
    options:[
      {text:'جدران المنازل + الأبواب + الأواني + الملابس',correct:true},
      {text:'السيارات والطائرات فقط',correct:false},
      {text:'الهواتف والأجهزة فقط',correct:false},
      {text:'الكتب فقط',correct:false},
    ],
    explanation:'الفن الشعبي شامل: جدران + أبواب + نوافذ + أواني + ملابس + حُلي.',
    goldenRule:'الفن الشعبي = فن شامل لكل مجالات الحياة اليومية.',
  },
  {
    id:'u1l3q20', unit:'u1', lesson:'u1l3', page:29, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف الأشياء التي زخرفها الفنان الشعبي:',
    paragraph:'وزخرف بهذه الخطوط جدران المنازل والأبواب والنوافذ، وأواني الشرب والطهي وتطريز الملابس. (ص29)',
    categories:['زخرفة معمارية 🏠','زخرفة منزلية 🍵','زخرفة شخصية 👕'],
    items:[
      {text:'جدران المنازل',correct_category:0},
      {text:'الأبواب',correct_category:0},
      {text:'النوافذ',correct_category:0},
      {text:'أواني الشرب',correct_category:1},
      {text:'أواني الطهي',correct_category:1},
      {text:'تطريز الملابس',correct_category:2},
    ],
    explanation:'معمارية: جدران/أبواب/نوافذ. منزلية: أواني. شخصية: ملابس مطرّزة.',
    goldenRule:'الفن الشعبي = زخرفة معمارية + منزلية + شخصية = فن الحياة.',
  },
  {
    id:'u1l3q21', unit:'u1', lesson:'u1l3', page:31, type:'trueFalse',
    bloom:'understand', difficulty:'medium',
    question:'الفنانون التشكيليون الحديثون استوحوا من الفن الشعبي وأضافوا إليه أسلوباً حديثاً.',
    paragraph:'رسم الفنان الشعبي بفطرته واستوحى الفنانون التشكيليون من أعماله فأنتجوا لوحات جديدة تحمل سمات الفن الشعبي، والفن الحديث. (ص31)',
    correctAnswer:true,
    explanation:'الفنانون الحديثون أخذوا من التراث الشعبي وأضافوا لمساتهم = الأصالة + المعاصرة.',
    goldenRule:'الفن الحديث = تراث شعبي + لمسة عصرية = أصيلة + معاصرة.',
  },
  {
    id:'u1l3q22', unit:'u1', lesson:'u1l3', page:31, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'الفنانان التشكيليان اللذان استوحيا من الفن الشعبي هما:',
    paragraph:'الشكلين (١٩، ٢٠): لوحتا الفنانين «أحمد الأعرج» و«سعود النفيعي». (ص31)',
    options:[
      {text:'أحمد الأعرج وسعود النفيعي',correct:true},
      {text:'محمد السليم ومحمد العبلان',correct:false},
      {text:'إحسان برهان وإبراهيم بوقس',correct:false},
      {text:'مجدي رضوي ورائدة عاشور',correct:false},
    ],
    explanation:'أحمد الأعرج وسعود النفيعي فنانان تشكيليان استوحيا من الفن الشعبي في لوحاتهما.',
    goldenRule:'أحمد الأعرج + سعود النفيعي = فنانون حديثون مستوحون من التراث الشعبي.',
  },
  {
    id:'u1l3q23', unit:'u1', lesson:'u1l3', page:31, type:'multipleChoice',
    bloom:'remember', difficulty:'medium',
    question:'الفنانة "رائدة عاشور" شاركت في معرض:',
    paragraph:'شاركت الفنانة «رائدة عاشور» في معرض «رؤى سعودية» لعام 1418هـ. (ص31)',
    options:[
      {text:'رؤى سعودية عام 1418هـ',correct:true},
      {text:'ملون السعودية 1998م',correct:false},
      {text:'معرض المراسم الرابع 1409هـ',correct:false},
      {text:'معرض البحرين 2010م',correct:false},
    ],
    explanation:'رائدة عاشور شاركت في معرض "رؤى سعودية" عام 1418هـ بلوحة مستوحاة من الفن الشعبي.',
    goldenRule:'رائدة عاشور + رؤى سعودية 1418هـ = فنانة مستوحية من التراث.',
  },
  {
    id:'u1l3q24', unit:'u1', lesson:'u1l3', page:26, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'الخط المنكسر يتكوّن من زوايا حادة وانكسارات.',
    paragraph:'الخط قد يكون مستقيماً أو متعرجاً أو منحنياً أو منكسراً. (ص26)',
    correctAnswer:true,
    explanation:'الخط المنكسر = زوايا حادة + انكسارات مفاجئة — مثل البرق أو أوراق الخريف المتشققة.',
    goldenRule:'الخط المنكسر = زوايا حادة = إيحاء بالقوة والحركة المفاجئة.',
  },
  {
    id:'u1l3q25', unit:'u1', lesson:'u1l3', page:26, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'الخط المتعرج يوحي بـ:',
    paragraph:'الخط قد يكون مستقيماً أو متعرجاً أو منحنياً أو منكسراً. (ص26)',
    options:[
      {text:'الموجات والحركة الناعمة المترددة',correct:true},
      {text:'الثبات والاستقرار',correct:false},
      {text:'القوة والحدّة',correct:false},
      {text:'الهدوء التام',correct:false},
    ],
    explanation:'الخط المتعرج = موجات = حركة ناعمة مترددة — مثل أمواج البحر أو أوراق الغار.',
    goldenRule:'المتعرج = موجات. المنكسر = زوايا. المنحني = نعومة. المستقيم = ثبات.',
  },
  {
    id:'u1l3q26', unit:'u1', lesson:'u1l3', page:33, type:'matching',
    bloom:'apply', difficulty:'medium',
    question:'صِل كل ورقة شجر بنوع الخط المناسب لرسمها:',
    paragraph:'صل/ي كل ورقة شجر فيما يأتي بالخط المستخدم في رسمها: منكسر / متعرج / مقوس. (ص33)',
    pairs:[
      {left:'ورقة بأطراف حادة',right:'منكسر'},
      {left:'ورقة بأطراف مموجة',right:'متعرج'},
      {left:'ورقة بأطراف ناعمة منحنية',right:'مقوس'},
    ],
    explanation:'حاد = منكسر. مموج = متعرج. ناعم منحني = مقوس.',
    goldenRule:'شكل حواف الورقة يحدد نوع الخط: حاد↔منكسر، موجي↔متعرج، ناعم↔مقوس.',
  },
  {
    id:'u1l3q27', unit:'u1', lesson:'u1l3', page:34, type:'multipleChoice',
    bloom:'evaluate', difficulty:'medium',
    question:'في تقويم الوحدة: يستخدم الفنان القديم في زخرفة البيوت الشعبية:',
    paragraph:'٤. اختار/ي الإجابة الصحيحة: يستخدم الفنان القديم في زخرفة البيوت الشعبية: اللون الأسود / اللون الأبيض / ألوان متنوعة. (ص34)',
    options:[
      {text:'ألوان متنوعة',correct:true},
      {text:'اللون الأسود فقط',correct:false},
      {text:'اللون الأبيض فقط',correct:false},
      {text:'لوناً واحداً فقط',correct:false},
    ],
    explanation:'الفنان الشعبي القديم يستخدم ألواناً متنوعة زاهية في زخرفة البيوت.',
    goldenRule:'الزخرفة الشعبية = ألوان متنوعة = جمال زاهي أصيل.',
  },
  {
    id:'u1l3q28', unit:'u1', lesson:'u1l3', page:29, type:'trueFalse',
    bloom:'apply', difficulty:'easy',
    question:'تطريز الملابس من استخدامات الخط في الفن الشعبي.',
    paragraph:'وزخرف بهذه الخطوط... وتطريز الملابس... وغيرها. (ص29)',
    correctAnswer:true,
    explanation:'التطريز بالخطوط الشعبية على الملابس من أبرز استخدامات الفن الشعبي.',
    goldenRule:'تطريز الملابس = خطوط شعبية = فن شخصي أصيل.',
  },
  {
    id:'u1l3q29', unit:'u1', lesson:'u1l3', page:28, type:'multipleChoice',
    bloom:'analyze', difficulty:'hard',
    question:'ما الفرق بين الفنان الشعبي والفنان التشكيلي الحديث؟',
    paragraph:'رسم الفنان الشعبي بفطرته واستوحى الفنانون التشكيليون من أعماله فأنتجوا لوحات جديدة. (ص31)',
    options:[
      {text:'الفنان الشعبي يرسم بفطرته، والتشكيلي يدرس الفن ويطوّره',correct:true},
      {text:'الفنان الشعبي أفضل دائماً',correct:false},
      {text:'الفنان التشكيلي لا يستوحي من الشعبي',correct:false},
      {text:'لا فرق بينهما',correct:false},
    ],
    explanation:'الشعبي = فطرة وبيئة. التشكيلي = دراسة وتطوير. التشكيلي يستوحي من الشعبي ويُضيف.',
    goldenRule:'الفنان الشعبي = فطرة. الفنان التشكيلي = دراسة + استلهام من الشعبي = تطوير.',
  },
  {
    id:'u1l3q30', unit:'u1', lesson:'u1l3', page:26, type:'trueFalse',
    bloom:'remember', difficulty:'easy',
    question:'الخط الرأسي المستقيم يوحي بالثبات والارتفاع.',
    paragraph:'الخط قد يكون... رأسياً أو أفقياً أو مائلاً. (ص26)',
    correctAnswer:true,
    explanation:'الخط الرأسي = ارتفاع + ثبات (كالجبال والأعمدة). الأفقي = سكون + اتساع.',
    goldenRule:'رأسي = ارتفاع/ثبات. أفقي = سكون/اتساع. مائل = حركة.',
  },
  {
    id:'u1l3q31', unit:'u1', lesson:'u1l3', page:30, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'لماذا يُعدّ تسجيل القط العسيري في اليونسكو مهماً للمملكة؟',
    paragraph:'تم تسجيله كتراث ثقافي سعودي غير مادي في منظمة اليونسكو 2017م. (ص30)',
    options:[
      {text:'لأنه يعترف عالمياً بالتراث السعودي ويحميه للأجيال القادمة',correct:true},
      {text:'لأنه يدرّ أموالاً فقط',correct:false},
      {text:'لأنه منافسة بين الدول',correct:false},
      {text:'لا أهمية للتسجيل',correct:false},
    ],
    explanation:'تسجيل اليونسكو = اعتراف عالمي + حماية التراث + تعريف به دولياً + فخر وطني.',
    goldenRule:'اليونسكو = اعتراف + حماية + تعريف دولي = صون التراث للأجيال.',
  },
  {
    id:'u1l3q32', unit:'u1', lesson:'u1l3', page:26, type:'fillBlank',
    bloom:'remember', difficulty:'easy',
    question:'أكمل: "الخط هو ___ الوسائل التي استُخدمت في التعبير الفني."',
    paragraph:'الخط هو أقدم الوسائل التي استُخدمت في التعبير الفني. (ص26)',
    blanks:['أقدم'],
    wordBank:['أقدم','أحدث','أصعب','أغلى'],
    explanation:'الخط هو أقدم وسيلة فنية — الإنسان الأول رسم بالخط في الكهوف.',
    goldenRule:'الخط = أقدم وسيلة فنية = بداية الفن الإنساني.',
  },
];

export const u1_extra = [...u1l1_extra];