// بنك أسئلة التربية الفنية — الصف الثالث الابتدائي — الفصل الأول 1447
// مرجع: كتاب التربية الفنية ط 2025 وزارة التعليم السعودية

export const ART_G3_S1_META = {
  subject: 'التربية الفنية',
  grade: 'الصف الثالث الابتدائي',
  semester: 'الفصل الأول',
  year: '1447 هـ / 2025 م',
  publisher: 'وزارة التعليم — المملكة العربية السعودية',
};

export const ART_G3_S1_UNITS = [
  {
    id: 'u1',
    title_ar: 'الوحدة الأولى: مجال الرسم',
    icon: '🎨',
    color: '#6366f1',
    lessons: [
      { id: 'u1l1', title_ar: 'عناصر التصميم', page: '10-16' },
      { id: 'u1l2', title_ar: 'التخطيط الأولي (الإسكتش)', page: '17-25' },
    ],
  },
  {
    id: 'u2',
    title_ar: 'الوحدة الثانية: مجال الزخرفة',
    icon: '🌿',
    color: '#b45309',
    lessons: [
      { id: 'u2l1', title_ar: 'الزخرفة البدائية والشعبية', page: '28-45' },
      { id: 'u2l2', title_ar: 'الزخارف الشعبية السعودية', page: '46-58' },
    ],
  },
  {
    id: 'u3',
    title_ar: 'الوحدة الثالثة: مجال الطباعة',
    icon: '🖨️',
    color: '#0891b2',
    lessons: [
      { id: 'u3l1', title_ar: 'أطبع بوحداتي الهندسية', page: '60-65' },
      { id: 'u3l2', title_ar: 'تكوينات وملامس مطبوعة', page: '66-71' },
      { id: 'u3l3', title_ar: 'طباعة وحدات ذات ملامس مختلفة', page: '72-79' },
    ],
  },
  {
    id: 'u4',
    title_ar: 'الوحدة الرابعة: مجال النسيج',
    icon: '🧵',
    color: '#059669',
    lessons: [
      { id: 'u4l1', title_ar: 'النسيج البسيط الملون', page: '82-93' },
    ],
  },
];

export const ART_G3_S1_QUESTIONS = [

  // ─── الوحدة 1: مجال الرسم ───────────────────────────────────────────

  // درس 1: عناصر التصميم
  {
    id: 'g3a_001', unit: 'u1', lesson: 'u1l1', page: 12, difficulty: 'easy',
    type: 'multipleChoice',
    question: 'ما هو العنصر الأصغر في التصميم الفني؟',
    options: [
      { text: 'الخط', correct: false },
      { text: 'النقطة', correct: true },
      { text: 'المساحة', correct: false },
      { text: 'اللون', correct: false },
    ],
    explanation: 'النقطة هي أصغر عنصر في التصميم الفني وتُولّد منها الخطوط والأشكال.',
    goldenRule: 'النقطة → الخط → الشكل: هذا هو ترتيب بناء التصميم.',
    paragraph: 'تصميم بالنقطة — ص ١٢',
  },
  {
    id: 'g3a_002', unit: 'u1', lesson: 'u1l1', page: 13, difficulty: 'easy',
    type: 'trueFalse',
    question: 'الخطوط الأفقية تُعطي إحساساً بالحركة والحيوية.',
    correctAnswer: 'false',
    explanation: 'الخطوط الأفقية تعطي إحساساً بالهدوء والاستقرار، أما الخطوط المنحنية فهي التي توحي بالحركة.',
    goldenRule: 'خطوط أفقية = هدوء | خطوط قطرية = حركة | خطوط منحنية = إيقاع.',
    paragraph: 'أنواع الخطوط — ص ١٣',
  },
  {
    id: 'g3a_003', unit: 'u1', lesson: 'u1l1', page: 14, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'أيّ الفنانين التالية لوحته مبنية على توظيف الخط والنقطة؟',
    options: [
      { text: 'فيكتور فازاريللي', correct: true },
      { text: 'بابلو بيكاسو', correct: false },
      { text: 'ليوناردو دافنشي', correct: false },
      { text: 'سعود النفيعي', correct: false },
    ],
    explanation: 'الفنان فيكتور فازاريللي اشتُهر باستخدام الخط والنقطة في تصاميم هندسية بصرية.',
    goldenRule: 'الفنانون التشكيليون يوظفون عناصر التصميم بطرق إبداعية مختلفة.',
    paragraph: 'لوحة الفنان فيكتور فازاريللي — ص ١٤',
  },
  {
    id: 'g3a_004', unit: 'u1', lesson: 'u1l1', page: 12, difficulty: 'easy',
    type: 'multipleChoice',
    question: 'من أين يستمد الفنان عناصر التصميم من البيئة؟',
    options: [
      { text: 'من الفواكه والأزهار والحيوانات والأشياء المحيطة', correct: true },
      { text: 'من الكتب والمراجع العلمية فقط', correct: false },
      { text: 'من الخيال المجرد بعيداً عن الواقع', correct: false },
      { text: 'من الإنترنت فقط', correct: false },
    ],
    explanation: 'الفنان يلاحظ النقطة في الفواكه، والخط في أوراق الأشجار، والأشكال في المنتجات اليومية.',
    goldenRule: 'البيئة المحيطة هي المصدر الأثرى لعناصر التصميم الفني.',
    paragraph: 'العناصر التشكيلية للتصميم — ص ١٢',
  },
  {
    id: 'g3a_005', unit: 'u1', lesson: 'u1l1', page: 10, difficulty: 'easy',
    type: 'trueFalse',
    question: 'التصميم هو تخطيط الشيء وإنشاؤه بطريقة جميلة وممتعة.',
    correctAnswer: 'true',
    explanation: 'التصميم هو العملية الإبداعية لتخطيط الشيء وإنشائه بطريقة جمالية ونفعية.',
    goldenRule: 'التصميم = جمال + فائدة.',
    paragraph: 'مفهوم التصميم — ص ١٠',
  },
  {
    id: 'g3a_006', unit: 'u1', lesson: 'u1l1', page: 11, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'في أيٍّ من المجالات الآتية يُستخدم التصميم؟',
    options: [
      { text: 'الفنون والعمارة فقط', correct: false },
      { text: 'الفنون والعمارة والأثاث فقط', correct: false },
      { text: 'جميع مجالات الحياة اليومية', correct: true },
      { text: 'الملابس والمجوهرات فقط', correct: false },
    ],
    explanation: 'التصميم يُستخدم في جميع مجالات الحياة: الملابس، المنزل، الأثاث، السيارات، المنتجات اليومية، وغيرها.',
    goldenRule: 'التصميم موجود في كل شيء حولنا!',
    paragraph: 'خطوات تنفيذ لوحة — ص ١١',
  },
  {
    id: 'g3a_007', unit: 'u1', lesson: 'u1l1', page: 15, difficulty: 'medium',
    type: 'ordering',
    question: 'رتّب عناصر التصميم الفني من الأصغر إلى الأكبر:',
    items: ['الشكل', 'الخط', 'النقطة', 'المساحة'],
    correctOrder: [2, 1, 0, 3],
    explanation: 'النقطة أصغر عنصر → تتكون منها الخطوط → تتكون من الخطوط الأشكال → تملأ الأشكال المساحة.',
    goldenRule: 'النقطة ← الخط ← الشكل ← المساحة.',
    paragraph: 'أنواع الخطوط — ص ١٣',
  },
  {
    id: 'g3a_008', unit: 'u1', lesson: 'u1l1', page: 13, difficulty: 'medium',
    type: 'classify',
    question: 'صنّف الخطوط التالية حسب نوعها:',
    categories: ['خطوط منتظمة', 'خطوط حرة'],
    items: [
      { text: 'الخط الأفقي المستقيم', correct_category: 0 },
      { text: 'الخط العمودي المستقيم', correct_category: 0 },
      { text: 'الخط المنحني بحرية', correct_category: 1 },
      { text: 'الخط المتعرج العشوائي', correct_category: 1 },
    ],
    explanation: 'الخطوط المنتظمة لها اتجاه ثابت، والخطوط الحرة تتدفق بشكل عفوي.',
    goldenRule: 'تنوع الخطوط يُثري التصميم الفني.',
    paragraph: 'أنواع الخطوط — ص ١٣',
  },

  // درس 2: الإسكتش
  {
    id: 'g3a_009', unit: 'u1', lesson: 'u1l2', page: 17, difficulty: 'easy',
    type: 'multipleChoice',
    question: 'ما معنى كلمة "إسكتش" في الفن؟',
    options: [
      { text: 'اللوحة الفنية النهائية', correct: false },
      { text: 'التخطيط الأولي للعمل الفني', correct: true },
      { text: 'التلوين بالألوان المائية', correct: false },
      { text: 'الزخرفة الشعبية', correct: false },
    ],
    explanation: 'الإسكتش هو التخطيط الأولي (المسودة) الذي يرسمه الفنان قبل تنفيذ عمله الفني النهائي.',
    goldenRule: 'الإسكتش = المسودة الأولى للعمل الفني.',
    paragraph: 'التخطيط الأولي (الإسكتش) — ص ١٧',
  },
  {
    id: 'g3a_010', unit: 'u1', lesson: 'u1l2', page: 18, difficulty: 'easy',
    type: 'trueFalse',
    question: 'كانت الفنانة صفية بن زقر فنانة سعودية.',
    correctAnswer: 'true',
    explanation: 'صفية بن زقر فنانة تشكيلية سعودية رائدة، وردت في الكتاب إسكتشاتها ضمن أمثلة التخطيط الأولي.',
    goldenRule: 'للمملكة العربية السعودية فنانون تشكيليون مبدعون.',
    paragraph: 'إسكتش للفنانة صفية بن زقر — ص ١٨',
  },
  {
    id: 'g3a_011', unit: 'u1', lesson: 'u1l2', page: 19, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'ما الهدف الرئيسي من رسم الإسكتش قبل اللوحة النهائية؟',
    options: [
      { text: 'إضاعة الوقت', correct: false },
      { text: 'تجريب الأفكار وتنظيمها قبل التنفيذ', correct: true },
      { text: 'استخدام أدوات التلوين', correct: false },
      { text: 'نسخ أعمال الفنانين الآخرين', correct: false },
    ],
    explanation: 'الإسكتش يساعد الفنان على تجريب أفكاره وتنظيمها قبل الشروع في العمل الفني النهائي.',
    goldenRule: 'خطط ثم نفذ — الإسكتش يوفر الوقت والجهد.',
    paragraph: 'إسكتش للفنان ليوناردو دافنشي — ص ١٩',
  },
  {
    id: 'g3a_012', unit: 'u1', lesson: 'u1l2', page: 22, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'ما الأداة التي تُستخدم لتأطير المنظر وتحديد ما نريد رسمه؟',
    options: [
      { text: 'الفرشاة', correct: false },
      { text: 'شباك الورق', correct: true },
      { text: 'المقص', correct: false },
      { text: 'قلم الحبر', correct: false },
    ],
    explanation: 'شباك الورق أداة بسيطة يضعها الفنان أمام عينه ليحدد ما يريد رسمه ويتحكم في تأطير المنظر.',
    goldenRule: 'شباك الورق = أداة التأطير الأولى للفنان المبتدئ.',
    paragraph: 'طريقة استخدام شباك الورق للتأطير — ص ٢٣',
  },
  {
    id: 'g3a_013', unit: 'u1', lesson: 'u1l2', page: 25, difficulty: 'hard',
    type: 'multipleChoice',
    question: 'ما الخطوة الأخيرة في رسم الإسكتش؟',
    options: [
      { text: 'التلوين بالألوان الكاملة', correct: false },
      { text: 'تحديد الشكل النهائي وإزالة الخطوط الزائدة', correct: true },
      { text: 'رسم الإطار أولاً', correct: false },
      { text: 'نسخ الرسم مرة أخرى', correct: false },
    ],
    explanation: 'بعد رسم التخطيط الأولي تُحدَّد الأشكال الرئيسية وتُزال الخطوط الزائدة للحصول على الإسكتش النهائي.',
    goldenRule: 'الإسكتش الجيد واضح ومحدد المعالم.',
    paragraph: 'خطوات رسم الإسكتش — ص ٢٥',
  },

  // ─── الوحدة 2: مجال الزخرفة ─────────────────────────────────────────

  // درس 1: الزخرفة البدائية والشعبية
  {
    id: 'g3a_014', unit: 'u2', lesson: 'u2l1', page: 28, difficulty: 'easy',
    type: 'multipleChoice',
    question: 'ماذا زيّن الإنسان البدائي بالزخارف في العصور القديمة؟',
    options: [
      { text: 'السيارات والطائرات', correct: false },
      { text: 'الكهوف والأكواخ والأدوات', correct: true },
      { text: 'الهواتف والأجهزة الإلكترونية', correct: false },
      { text: 'المصانع والمراكز التجارية', correct: false },
    ],
    explanation: 'عمل الإنسان القديم على تزيين الكهوف والأكواخ والأدوات بزخارف مستمدة من البيئة والحياة التي يعيشها.',
    goldenRule: 'الزخرفة قديمة قدم الإنسان نفسه!',
    paragraph: 'زخرفة الجدار برسوم معبرة — ص ٢٨',
  },
  {
    id: 'g3a_015', unit: 'u2', lesson: 'u2l1', page: 30, difficulty: 'easy',
    type: 'trueFalse',
    question: 'الطبيعة مصدر للأشكال الزخرفية.',
    correctAnswer: 'true',
    explanation: 'الطبيعة بعناصرها من نباتات وحيوانات وجمادات كانت ولا تزال المصدر الرئيسي للزخرفة عبر العصور.',
    goldenRule: 'الطبيعة = أغنى مصدر للزخرفة.',
    paragraph: 'الطبيعة مصدر الأشكال الزخرفية — ص ٣٠',
  },
  {
    id: 'g3a_016', unit: 'u2', lesson: 'u2l1', page: 31, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'ما أنواع التشكيلات الزخرفية المستمدة من النقطة؟',
    options: [
      { text: 'التشكيلات المستقيمة فقط', correct: false },
      { text: 'مجموعات من النقاط المتكررة والمتنوعة الأحجام والألوان', correct: true },
      { text: 'الأشكال الهندسية الكبيرة فقط', correct: false },
      { text: 'الصور التشخيصية للإنسان والحيوان', correct: false },
    ],
    explanation: 'تُشكَّل تشكيلات جميلة من النقطة بتكرارها وتنويع أحجامها وألوانها.',
    goldenRule: 'النقطة المتكررة = زخرفة جميلة.',
    paragraph: 'تشكيلات من النقطة — ص ٣١',
  },
  {
    id: 'g3a_017', unit: 'u2', lesson: 'u2l1', page: 39, difficulty: 'medium',
    type: 'classify',
    question: 'صنّف الأشكال التالية حسب طبيعتها الزخرفية:',
    categories: ['أشكال هندسية', 'أشكال نباتية'],
    items: [
      { text: 'المثلث', correct_category: 0 },
      { text: 'الدائرة', correct_category: 0 },
      { text: 'وردة', correct_category: 1 },
      { text: 'ورقة شجر', correct_category: 1 },
    ],
    explanation: 'الأشكال الهندسية هي المثلث والدائرة والمربع، أما النباتية فتشمل الورود والأوراق والثمار.',
    goldenRule: 'الزخرفة نوعان: هندسية ونباتية.',
    paragraph: 'أشكال هندسية متنوعة — ص ٣٩',
  },
  {
    id: 'g3a_018', unit: 'u2', lesson: 'u2l1', page: 36, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'ما الشكل الزخرفي الذي تتكون منه تشكيلات من الدائرة؟',
    options: [
      { text: 'المربعات المتداخلة', correct: false },
      { text: 'دوائر متحدة المركز أو متكررة بأحجام مختلفة', correct: true },
      { text: 'الخطوط المتوازية', correct: false },
      { text: 'المثلثات المتراصة', correct: false },
    ],
    explanation: 'تتكون تشكيلات الدائرة من دوائر متحدة المركز أو متكررة بأحجام وألوان مختلفة.',
    goldenRule: 'الدائرة المتكررة المتنوعة = زخرفة دائرية.',
    paragraph: 'تشكيلات من الدائرة — ص ٣٦',
  },
  {
    id: 'g3a_019', unit: 'u2', lesson: 'u2l1', page: 39, difficulty: 'easy',
    type: 'trueFalse',
    question: 'يمكن الحصول على الأشكال الزخرفية من أوراق ملونة جاهزة مقصوصة.',
    correctAnswer: 'true',
    explanation: 'يمكن استخدام الأوراق الملونة الجاهزة المقصوصة بأشكال هندسية لتكوين عناصر زخرفية وتثبيتها على أسطح مختلفة.',
    goldenRule: 'الخامات البسيطة يمكن توظيفها لإنتاج زخارف جميلة.',
    paragraph: 'أشكال هندسية متنوعة — ص ٣٩',
  },
  {
    id: 'g3a_020', unit: 'u2', lesson: 'u2l1', page: 41, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'ما التشكيلات الزخرفية المستمدة من العناصر الطبيعية المحيطة؟',
    options: [
      { text: 'المثلثات والمربعات', correct: false },
      { text: 'أزهار وثمار وأوراق الأشجار والنخيل', correct: true },
      { text: 'الحروف العربية والأرقام', correct: false },
      { text: 'الأدوات المنزلية والأثاث', correct: false },
    ],
    explanation: 'التشكيلات الزخرفية الطبيعية مستقة من أجزاء النبات كالأزهار والثمار والفواكه والأشجار وأوراقها والنخيل.',
    goldenRule: 'الطبيعة = مصدر لا ينضب للزخرفة.',
    paragraph: 'تشكيلات من العناصر الطبيعية — ص ٤١',
  },
  {
    id: 'g3a_021', unit: 'u2', lesson: 'u2l1', page: 44, difficulty: 'hard',
    type: 'multipleChoice',
    question: 'كيف تؤثر الزخرفة على المنتجات الحرفية؟',
    options: [
      { text: 'لا تؤثر عليها إطلاقاً', correct: false },
      { text: 'تُضيف إليها جمالاً فنياً إلى جانب الاستفادة النفعية', correct: true },
      { text: 'تجعلها أقل قيمة', correct: false },
      { text: 'تصعّب استخدامها', correct: false },
    ],
    explanation: 'الزخرفة من أهم الفنون التشكيلية التي تُضيف جمالاً إلى المنتجات الحرفية مع الحفاظ على استخداماتها النفعية.',
    goldenRule: 'الزخرفة = جمال + نفعية معاً.',
    paragraph: 'أثر الزخرفة على المنتجات الحرفية — ص ٤٤',
  },
  {
    id: 'g3a_022', unit: 'u2', lesson: 'u2l1', page: 40, difficulty: 'medium',
    type: 'ordering',
    question: 'رتّب خطوات تثبيت العناصر الزخرفية على أسطح مختلفة:',
    items: [
      'نثبتها بواسطة الصمغ على الأسطح',
      'نختار الشكل الزخرفي المناسب',
      'نقص الأشكال من الورق أو الإسفنج بدقة',
    ],
    correctOrder: [1, 2, 0],
    explanation: 'الخطوة الأولى: اختيار الشكل → الثانية: قصه → الثالثة: تثبيته بالصمغ.',
    goldenRule: 'اختر → اقص → ثبّت.',
    paragraph: 'أسطح مختلفة لتثبيت العناصر الزخرفية — ص ٤٠',
  },

  // درس 2: الزخارف الشعبية السعودية
  {
    id: 'g3a_023', unit: 'u2', lesson: 'u2l2', page: 46, difficulty: 'easy',
    type: 'trueFalse',
    question: 'تمتازت المملكة العربية السعودية بتراثها الفني الشعبي لاتساع مساحتها الجغرافية.',
    correctAnswer: 'true',
    explanation: 'تمتازت المملكة بتراثها الفني الشعبي لاتساع مساحتها الجغرافية واختلاف طبيعة البيئة والسكان.',
    goldenRule: 'تنوع بيئة المملكة = تنوع تراثها الفني.',
    paragraph: 'فن الزخرفة الشعبية — ص ٤٦',
  },
  {
    id: 'g3a_024', unit: 'u2', lesson: 'u2l2', page: 47, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'بماذا تمتازت العمارة الشعبية السعودية ارتباطاً بالبيئة؟',
    options: [
      { text: 'استخدام الزجاج والحديد فقط', correct: false },
      { text: 'استخدام الأحجار والطين والخشب المتوفرة في البيئة', correct: true },
      { text: 'الاستيراد من الخارج', correct: false },
      { text: 'استخدام البلاستيك والألومنيوم', correct: false },
    ],
    explanation: 'ارتبطت العمارة الشعبية بجغرافية المنطقة ومناخها من حيث توفر خامات البناء كالأحجار والطين والخشب.',
    goldenRule: 'البيئة تُملي على الإنسان خامات بناء منزله وزخرفته.',
    paragraph: 'البيوت الشعبية — ص ٤٦',
  },
  {
    id: 'g3a_025', unit: 'u2', lesson: 'u2l2', page: 47, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'ما الذي يُطلق عليه النقش على الجص في الزخرفة الشعبية السعودية؟',
    options: [
      { text: 'النقش على المنسوجات', correct: false },
      { text: 'الزخرفة الشعبية على المباني في الأبواب والتغطية الداخلية والخارجية', correct: true },
      { text: 'الزخرفة على الأواني الفخارية', correct: false },
      { text: 'الرسم بالألوان المائية', correct: false },
    ],
    explanation: 'الزخرفة الشعبية أو النقش سمة بارزة في الموروث الشعبي ويرتبط بالعمارة في الأبواب والتغطية ويُطلق عليه النقش على الجص.',
    goldenRule: 'النقش على الجص = فن شعبي سعودي أصيل.',
    paragraph: 'نقش وتلوين المنازل — ص ٤٧',
  },
  {
    id: 'g3a_026', unit: 'u2', lesson: 'u2l2', page: 48, difficulty: 'easy',
    type: 'multipleChoice',
    question: 'ما الألوان المميزة للزخارف الشعبية على الأبواب والجدران السعودية؟',
    options: [
      { text: 'الرمادي والبني والأسود', correct: false },
      { text: 'الأزرق والأخضر والبنفسجي والأحمر والأصفر', correct: true },
      { text: 'الأبيض والكريمي فقط', correct: false },
      { text: 'الذهبي والفضي فقط', correct: false },
    ],
    explanation: 'تتميز النقوش الشعبية على الأبواب والجدران بألوان جميلة كالأزرق والأخضر والبنفسجي والأحمر والأصفر.',
    goldenRule: 'الألوان الزاهية = روح الزخرفة الشعبية السعودية.',
    paragraph: 'نقش وتلوين الجدران والأبواب — ص ٤٨',
  },
  {
    id: 'g3a_027', unit: 'u2', lesson: 'u2l2', page: 48, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'ما الأشكال الهندسية التي تتنوع منها الزخرفة الشعبية السعودية؟',
    options: [
      { text: 'النجمة والقمر فقط', correct: false },
      { text: 'الدائري والمثلث والمربع والمعين وتكرارها', correct: true },
      { text: 'الخطوط المتوازية فقط', correct: false },
      { text: 'الأشكال الحيوانية فقط', correct: false },
    ],
    explanation: 'تتنوع الزخرفة من الشكل الدائري إلى المثلث والمربع والمعين، ومن خلال تكرار هذه العناصر تتكون الزخرفة.',
    goldenRule: 'دائرة + مثلث + مربع + معين = زخرفة شعبية سعودية.',
    paragraph: 'أسلوب الزخرفة الشعبية — ص ٤٨',
  },
  {
    id: 'g3a_028', unit: 'u2', lesson: 'u2l2', page: 52, difficulty: 'medium',
    type: 'classify',
    question: 'صنّف المنتجات الحرفية الشعبية السعودية:',
    categories: ['منتجات من مواد طبيعية', 'منتجات نسيجية'],
    items: [
      { text: 'المنتجات الخزفية', correct_category: 0 },
      { text: 'المنتجات الجلدية', correct_category: 0 },
      { text: 'السجاد', correct_category: 1 },
      { text: 'المنتجات السعفية', correct_category: 1 },
    ],
    explanation: 'تنوعت المنتجات الحرفية الشعبية بين الخزف والجلود والسجاد والمنتجات السعفية.',
    goldenRule: 'الحرفي الشعبي يوظف الزخرفة في كل ما يصنعه.',
    paragraph: 'المنتجات الخزفية والسعفية والجلدية والسجاد — ص ٥٢',
  },
  {
    id: 'g3a_029', unit: 'u2', lesson: 'u2l2', page: 53, difficulty: 'hard',
    type: 'multipleChoice',
    question: 'ما أهم مميزات الفن الشعبي في المنتجات الحرفية؟',
    options: [
      { text: 'الانفراد والتعقيد الشديد', correct: false },
      { text: 'التكرار والأشكال الهندسية والألوان الزاهية', correct: true },
      { text: 'الألوان الباهتة والأشكال الكبيرة', correct: false },
      { text: 'الخطوط العشوائية غير المنتظمة', correct: false },
    ],
    explanation: 'اعتمد الحرفي الشعبي على التكرار كأهم مميزات الفن الشعبي، مع المضلعات والأشكال النجمية والدوائر المتداخلة.',
    goldenRule: 'التكرار = أهم سمات الفن الشعبي.',
    paragraph: 'الزخرفة المحفورة — ص ٥٣',
  },
  {
    id: 'g3a_030', unit: 'u2', lesson: 'u2l2', page: 56, difficulty: 'medium',
    type: 'trueFalse',
    question: 'اهتم الفنانون التشكيليون السعوديون بالتراث الشعبي ووظفوا زخارفه في لوحاتهم.',
    correctAnswer: 'true',
    explanation: 'اهتم الفنانون كأحمد الأعرج وإبراهيم بوقس وسعيد العلاوي وسعود النفيعي بالتراث الشعبي ووظفوا زخارفه بطرقهم الخاصة.',
    goldenRule: 'الفنان التشكيلي يستلهم من تراثه ليخلق فناً معاصراً.',
    paragraph: 'الفنان التشكيلي والتراث الشعبي — ص ٥٦',
  },
  {
    id: 'g3a_031', unit: 'u2', lesson: 'u2l2', page: 49, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'ما الأشكال الزخرفية التي يعتمد عليها الحرفيون في نقوش المنازل؟',
    options: [
      { text: 'الصور التشخيصية للناس والحيوانات فقط', correct: false },
      { text: 'الزخرفة الهندسية والنباتية كالمثلث والدائرة والورود والأوراق', correct: true },
      { text: 'الكتابات والنصوص فقط', correct: false },
      { text: 'صور الطبيعة الفوتوغرافية', correct: false },
    ],
    explanation: 'يعتمد الحرفيون في زخارف الأبواب الخشبية على الزخرفة الهندسية والنباتية كالمثلث والدائرة والمربع والورود والأوراق.',
    goldenRule: 'الهندسي + النباتي = جوهر الزخرفة الشعبية في المنازل.',
    paragraph: 'فن الزخرفة الشعبية في المنازل — ص ٤٩',
  },

  // ─── الوحدة 3: مجال الطباعة ─────────────────────────────────────────

  // درس 1: أطبع بوحداتي الهندسية
  {
    id: 'g3a_032', unit: 'u3', lesson: 'u3l1', page: 60, difficulty: 'easy',
    type: 'multipleChoice',
    question: 'من أين جاءت فكرة اكتشاف الطباعة وفق قصة الكتاب؟',
    options: [
      { text: 'من أثر الكف على الرمال', correct: false },
      { text: 'من آثار أوراق الأشجار والنباتات على ملابس صياد في الغابة', correct: true },
      { text: 'من تجربة علمية في المختبر', correct: false },
      { text: 'من الرسم بالأصابع على الطين', correct: false },
    ],
    explanation: 'قصة الكتاب: صياد نام في الغابة تحت شجرة فوجد آثار أوراق النباتات على ملابسه، فكانت بداية فكرة الطباعة.',
    goldenRule: 'الاكتشاف العظيم يبدأ من ملاحظة بسيطة!',
    paragraph: 'قصة اكتشاف الطباعة — ص ٦٠',
  },
  {
    id: 'g3a_033', unit: 'u3', lesson: 'u3l1', page: 61, difficulty: 'easy',
    type: 'trueFalse',
    question: 'يجب استخدام ألوان مائية أو ألوان قابلة للغسل عند الطباعة.',
    correctAnswer: 'true',
    explanation: 'من التعليمات الهامة في الطباعة: يجب استخدام ألوان مائية أو ألوان قابلة للغسل، ولبس معطف للرسم يقي من الألوان.',
    goldenRule: 'السلامة أولاً: ألوان قابلة للغسل + معطف الرسم.',
    paragraph: 'تعليمات هامة — ص ٦١',
  },
  {
    id: 'g3a_034', unit: 'u3', lesson: 'u3l1', page: 62, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'ما أنواع التكرار في الطباعة الفنية؟',
    options: [
      { text: 'نوع واحد فقط هو المنتظم', correct: false },
      { text: 'المنتظم والمتعاكس والمتبادل', correct: true },
      { text: 'العشوائي والفوضوي فقط', correct: false },
      { text: 'المتوازي والمائل فقط', correct: false },
    ],
    explanation: 'أنواع التكرار: ١- تكرار منتظم، ٢- تكرار متعاكس، ٣- تكرار متبادل من وحدتين مختلفتين.',
    goldenRule: 'منتظم + متعاكس + متبادل = أنواع التكرار في الطباعة.',
    paragraph: 'أنواع التكرار — ص ٦٢',
  },
  {
    id: 'g3a_035', unit: 'u3', lesson: 'u3l1', page: 62, difficulty: 'medium',
    type: 'classify',
    question: 'صنّف أنواع التكرار في الطباعة:',
    categories: ['تكرار بوحدة واحدة', 'تكرار بوحدتين'],
    items: [
      { text: 'التكرار المنتظم', correct_category: 0 },
      { text: 'التكرار المتعاكس', correct_category: 0 },
      { text: 'التكرار المتبادل', correct_category: 1 },
      { text: 'تكرار شكل + نقيضه', correct_category: 1 },
    ],
    explanation: 'التكرار المنتظم والمتعاكس يستخدمان وحدة واحدة، أما المتبادل فيتعاقب بين وحدتين مختلفتين.',
    goldenRule: 'التنوع في التكرار يُثري العمل الطباعي.',
    paragraph: 'أنواع التكرار — ص ٦٢',
  },
  {
    id: 'g3a_036', unit: 'u3', lesson: 'u3l1', page: 64, difficulty: 'medium',
    type: 'ordering',
    question: 'رتّب خطوات الطباعة بالقالب الهندسي:',
    items: [
      'نضع القالب على السطح ونضغط بقوة',
      'نقص الفلين بأشكال هندسية',
      'توزيع اللون بالفرشاة على الشكل الزخرفي',
      'نكوّن أشكالاً نباتية على القالب',
    ],
    correctOrder: [1, 3, 2, 0],
    explanation: 'الخطوة ١: قص الفلين → ٢: تكوين أشكال نباتية → ٣: توزيع اللون → ٤: الضغط على السطح.',
    goldenRule: 'اقص → كوّن → لوّن → اطبع.',
    paragraph: 'خطوات الطباعة — ص ٦٤',
  },
  {
    id: 'g3a_037', unit: 'u3', lesson: 'u3l1', page: 65, difficulty: 'easy',
    type: 'trueFalse',
    question: 'يمكن الطباعة بأكثر من لون واحد على نفس السطح.',
    correctAnswer: 'true',
    explanation: 'يمكن استخدام أكثر من لون واحد عند تكرار عملية الطباعة على السطح للحصول على تأثيرات لونية متنوعة.',
    goldenRule: 'التنوع اللوني يُثري الطباعة.',
    paragraph: 'القالب المراد الطباعة عليه — ص ٦٥',
  },
  {
    id: 'g3a_038', unit: 'u3', lesson: 'u3l1', page: 63, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'ما المادة الأساسية التي تُستخدم في صناعة قالب الطباعة الهندسي؟',
    options: [
      { text: 'الخشب الصلب', correct: false },
      { text: 'الفلين المقصوص بأشكال هندسية', correct: true },
      { text: 'الورق المقوى فقط', correct: false },
      { text: 'الحجر الطبيعي', correct: false },
    ],
    explanation: 'يُستخدم الفلين المقصوص بأشكال هندسية متعددة لصناعة قوالب الطباعة، ويمكن الحصول عليه من المكتبات.',
    goldenRule: 'الفلين المقصوص = أداة الطباعة الهندسية المثالية.',
    paragraph: 'شكل: أشكال هندسية من الفلين — ص ٦٣',
  },

  // درس 2: تكوينات وملامس مطبوعة
  {
    id: 'g3a_039', unit: 'u3', lesson: 'u3l2', page: 66, difficulty: 'easy',
    type: 'trueFalse',
    question: 'ريش الطاووس يظهر في تكرار هندسي جميل من صنع الخالق سبحانه.',
    correctAnswer: 'true',
    explanation: 'جمّل الخالق عز وجل ريش الطيور وجلود الحيوانات وأجنحة الفراشات في تكوينات زخرفية هندسية متنوعة فتبارك الله أحسن الخالقين.',
    goldenRule: 'قدرة الله في خلق الجمال تفوق كل تصميم بشري.',
    paragraph: 'ريش الطاووس — ص ٦٦',
  },
  {
    id: 'g3a_040', unit: 'u3', lesson: 'u3l2', page: 66, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'ما الذي يُعدّ مثالاً على الوحدة الزخرفية المتكررة في الطبيعة؟',
    options: [
      { text: 'الرمال في الصحراء', correct: false },
      { text: 'خلايا النحل السداسية الشكل', correct: true },
      { text: 'مياه البحر', correct: false },
      { text: 'السحاب في السماء', correct: false },
    ],
    explanation: 'تقوم النحلة ببناء خلاياها بتكرار جميل ومنظم بأشكال هندسية متقنة، وهي مثال رائع على الوحدة الزخرفية في الطبيعة.',
    goldenRule: 'النحلة مهندسة ماهرة تُكرر الشكل السداسي بإتقان.',
    paragraph: 'خلايا النحل — ص ٦٦',
  },
  {
    id: 'g3a_041', unit: 'u3', lesson: 'u3l2', page: 66, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'ما تعريف الوحدة الزخرفية؟',
    options: [
      { text: 'شكل واحد بسيط يتكرر بنفس الحجم واللون', correct: false },
      { text: 'علاقات الأشكال ببعضها وعلاقة الجزء بالكل، وقد تكون متشابهة أو مختلفة', correct: true },
      { text: 'مجرد نقطة أو خط مستقيم', correct: false },
      { text: 'تجميع ألوان متعددة بدون نظام', correct: false },
    ],
    explanation: 'الوحدة هي علاقات الأشكال ببعضها البعض وعلاقة الجزء منها بالكل، وليس شرطاً أن تكون الأشكال كلها متشابهة.',
    goldenRule: 'الوحدة الزخرفية = علاقة منظمة بين الأشكال.',
    paragraph: 'لنتساءل معاً ما هي الوحدة؟ — ص ٦٦',
  },
  {
    id: 'g3a_042', unit: 'u3', lesson: 'u3l2', page: 67, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'كيف يمكن الحصول على تكوينات مطبوعة جميلة لأشكال من الطبيعة؟',
    options: [
      { text: 'بنسخ الصور الفوتوغرافية مباشرة', correct: false },
      { text: 'بتنظيم العناصر الهندسية وتنويع حجم الوحدة والتكرار بأساليب مختلفة', correct: true },
      { text: 'باستخدام الألوان المائية فقط', correct: false },
      { text: 'برسم الطبيعة بدون أي تنظيم', correct: false },
    ],
    explanation: 'عند تنظيم العناصر الهندسية مع التنوع في الحجم والتكرار بأساليب مختلفة يمكننا الحصول على تكوينات مطبوعة جميلة.',
    goldenRule: 'التنظيم + التنويع + التكرار = تكوين مطبوع جميل.',
    paragraph: 'تكوين منظر طبيعي من وحدات هندسية مختلفة — ص ٦٨',
  },
  {
    id: 'g3a_043', unit: 'u3', lesson: 'u3l2', page: 69, difficulty: 'medium',
    type: 'ordering',
    question: 'رتّب خطوات إنشاء تكوين مطبوع بالقوالب:',
    items: [
      'أكمل الطباعة بالقوالب المختلفة بألوان مختلفة',
      'أجهز الأشكال الهندسية وأنظمها في أشكال',
      'أكرر طباعة الأشكال لتكوين الشكل المرغوب',
      'أوزع اللون على سطح القالب بعناية',
      'أبدأ بالطباعة باستخدام القوالب واحداً بعد الآخر',
    ],
    correctOrder: [1, 3, 4, 2, 0],
    explanation: 'جهّز الأشكال → وزّع اللون → ابدأ الطباعة → كرّر الأشكال → أكمل الطباعة.',
    goldenRule: 'الطباعة المتقنة تحتاج تخطيطاً وتنفيذاً خطوة بخطوة.',
    paragraph: 'خطوات الطباعة — ص ٦٩-٧٠',
  },

  // درس 3: طباعة وحدات ذات ملامس مختلفة
  {
    id: 'g3a_044', unit: 'u3', lesson: 'u3l3', page: 72, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'ما نوعا الملامس المستخدمة في طباعة القالب؟',
    options: [
      { text: 'الملامس الناعمة والخشنة فقط', correct: false },
      { text: 'الملامس الطبيعية (كالأحجار) والصناعية (كالفلين والخيش)', correct: true },
      { text: 'الملامس الزجاجية والبلاستيكية فقط', correct: false },
      { text: 'ملامس الأقمشة فقط', correct: false },
    ],
    explanation: 'الملامس نوعان: طبيعية تكونت دون تدخل الإنسان كالأحجار والمرجان، وصناعية تكونت بتدخل الإنسان كالفلين والخيش.',
    goldenRule: 'طبيعي = بدون تدخل بشري | صناعي = بتدخل بشري.',
    paragraph: 'فن طباعة القالب — ص ٧٢',
  },
  {
    id: 'g3a_045', unit: 'u3', lesson: 'u3l3', page: 72, difficulty: 'easy',
    type: 'trueFalse',
    question: 'عند طباعة وجه قطعة نقود معدنية على الورق، يظهر الأثر بشكل معكوس.',
    correctAnswer: 'true',
    explanation: 'عند وضع اللون على وجه قطعة النقود وضغطها على الورق تتم طباعة العناصر البارزة على الورق ولكن بشكل معكوس.',
    goldenRule: 'الطباعة بالقالب دائماً تُنتج أثراً معكوساً.',
    paragraph: 'العناصر البارزة في قطعة النقود مطبوعة — ص ٧٢',
  },
  {
    id: 'g3a_046', unit: 'u3', lesson: 'u3l3', page: 73, difficulty: 'hard',
    type: 'multipleChoice',
    question: 'لماذا يجب أن يكون الحرف العربي بارزاً في قالب الطباعة؟',
    options: [
      { text: 'لأن الحروف يجب أن تُرسم عادية', correct: false },
      { text: 'لأن الطباعة تنقل الأجزاء البارزة فقط على الورق', correct: true },
      { text: 'لأن الحرف المحفور لا يظهر', correct: false },
      { text: 'لأن اللون يلتصق بالمساحات الغائرة فقط', correct: false },
    ],
    explanation: 'كما تعلمنا من تجربة قطعة النقود، الأثر الذي يُطبع على الورق هو أثر الأجزاء البارزة، لذلك يجب أن يكون الحرف بارزاً.',
    goldenRule: 'البارز في القالب = المطبوع على الورق.',
    paragraph: 'طباعة الحروف العربية — ص ٧٣',
  },
  {
    id: 'g3a_047', unit: 'u3', lesson: 'u3l3', page: 76, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'ما طرق صناعة الملامس الصناعية للطباعة؟',
    options: [
      { text: 'طريقة واحدة فقط', correct: false },
      { text: 'بواسطة حلقات المطاط أو بواسطة صمغ الزجاج', correct: true },
      { text: 'بواسطة الطباعة الرقمية فقط', correct: false },
      { text: 'باستخدام الأختام الجاهزة فقط', correct: false },
    ],
    explanation: 'يمكن صناعة ملامس من اختيارنا بطريقتين: بواسطة حلقات المطاط، أو بواسطة صمغ الزجاج على سطح خشبي.',
    goldenRule: 'حلقات المطاط أو صمغ الزجاج = ملامس صناعية للطباعة.',
    paragraph: 'ملامس من صنعي — ص ٧٦',
  },

  // ─── الوحدة 4: مجال النسيج ──────────────────────────────────────────

  {
    id: 'g3a_048', unit: 'u4', lesson: 'u4l1', page: 82, difficulty: 'easy',
    type: 'multipleChoice',
    question: 'ما تعريف النسيج؟',
    options: [
      { text: 'رسم الخطوط على الورق', correct: false },
      { text: 'تشابك وتقاطع خيوط طولية تُسمى السدى مع خيوط عرضية تُسمى اللحمة', correct: true },
      { text: 'طباعة الألوان على القماش', correct: false },
      { text: 'قص الأقمشة وتصميم الملابس', correct: false },
    ],
    explanation: 'النسيج هو تشابك وتقاطع خيوط طولية تُسمى السدى مع خيوط عرضية تُسمى اللحمة.',
    goldenRule: 'سدى (طولي) + لحمة (عرضي) = نسيج.',
    paragraph: 'تعريف النسيج — ص ٨٢',
  },
  {
    id: 'g3a_049', unit: 'u4', lesson: 'u4l1', page: 82, difficulty: 'easy',
    type: 'trueFalse',
    question: 'النسيج من أقدم الحرف والصناعات التي نشأت مع الإنسان.',
    correctAnswer: 'true',
    explanation: 'يُعتبر النسيج من أقدم الحرف والصناعات التي نشأت مع الإنسان، وقد ظهر نتيجة حاجته إلى ستر نفسه ووقايتها.',
    goldenRule: 'النسيج قديم قدم الإنسان على الأرض.',
    paragraph: 'بدايات ظهور فن النسيج — ص ٨٢',
  },
  {
    id: 'g3a_050', unit: 'u4', lesson: 'u4l1', page: 82, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'ما سبب ظهور النسيج عند الإنسان البدائي؟',
    options: [
      { text: 'للزينة والتجميل فقط', correct: false },
      { text: 'الحاجة إلى ستر نفسه والوقاية من العوامل الجوية', correct: true },
      { text: 'لصناعة الأدوات المنزلية', correct: false },
      { text: 'لبناء المنازل', correct: false },
    ],
    explanation: 'ظهر النسيج نتيجة حاجة الإنسان إلى ستر نفسه ووقايتها من العوامل الجوية، واستخدم الألياف والفروع النباتية من بيئته.',
    goldenRule: 'الحاجة أم الاختراع — النسيج نشأ من ضرورة الحياة.',
    paragraph: 'بدايات ظهور فن النسيج — ص ٨٢',
  },
  {
    id: 'g3a_051', unit: 'u4', lesson: 'u4l1', page: 85, difficulty: 'medium',
    type: 'classify',
    question: 'صنّف أدوات النسيج البسيط:',
    categories: ['أدوات تنظيم الخيوط', 'أدوات قطع وإدارة الخيط'],
    items: [
      { text: 'المشط', correct_category: 0 },
      { text: 'النول', correct_category: 0 },
      { text: 'المقص', correct_category: 1 },
      { text: 'المكوك', correct_category: 1 },
    ],
    explanation: 'النول والمشط لتنظيم الخيوط، والمقص للقص والمكوك لإدارة خيط اللحمة.',
    goldenRule: 'نول + مشط + مسطرة + مكوك + مقص = أدوات النسيج.',
    paragraph: 'الأدوات المستخدمة في عمل النسيج البسيط — ص ٨٥',
  },
  {
    id: 'g3a_052', unit: 'u4', lesson: 'u4l1', page: 85, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'ما وظيفة المسطرة في النسيج البسيط؟',
    options: [
      { text: 'لقياس طول القماش', correct: false },
      { text: 'شريحة خشبية رقيقة تُستخدم في فصل خيوط السدى الزوجية عن الفردية', correct: true },
      { text: 'لضغط خيوط اللحمة لأسفل', correct: false },
      { text: 'لف الخيوط حولها', correct: false },
    ],
    explanation: 'المسطرة شريحة خشبية رقيقة تُستخدم في فصل خيوط السدى الزوجية عن الفردية لعمل النسيج.',
    goldenRule: 'المسطرة = أداة الفصل بين خيوط السدى الزوجي والفردي.',
    paragraph: 'الأدوات المستخدمة في النسيج البسيط — ص ٨٦',
  },
  {
    id: 'g3a_053', unit: 'u4', lesson: 'u4l1', page: 86, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'ما نوعا الخامات المستخدمة في النسيج؟',
    options: [
      { text: 'الخامات الطبيعية فقط', correct: false },
      { text: 'خامات طبيعية كالقطن والحرير، وخامات صناعية كالنايلون والأكريلك', correct: true },
      { text: 'الخامات الصناعية فقط', correct: false },
      { text: 'المعادن والبلاستيك فقط', correct: false },
    ],
    explanation: 'الخامات طبيعية مثل: القطن والأصواف والحرير، وصناعية مثل: الفسكوز والنايلون والأكريلك.',
    goldenRule: 'خامات طبيعية + صناعية = تنوع في إنتاج النسيج.',
    paragraph: 'خامات ومستهلكات متنوعة — ص ٨٦',
  },
  {
    id: 'g3a_054', unit: 'u4', lesson: 'u4l1', page: 83, difficulty: 'easy',
    type: 'trueFalse',
    question: 'مجالات استخدام المنسوجات محدودة وتقتصر على الملابس فقط.',
    correctAnswer: 'false',
    explanation: 'مجالات استخدام المنسوجات كثيرة ومتعددة: الملابس، المناديل، الستائر، المفارش، أقمشة الكراسي والسيارات، الحقائب، وغيرها.',
    goldenRule: 'النسيج في كل مكان حولنا!',
    paragraph: 'أهمية النسيج في حياتنا اليومية — ص ٨٣',
  },
  {
    id: 'g3a_055', unit: 'u4', lesson: 'u4l1', page: 84, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'ما الألوان المميزة للمنسوجات الشعبية التراثية في المملكة العربية السعودية؟',
    options: [
      { text: 'الأزرق والبنفسجي والوردي', correct: false },
      { text: 'الأحمر والأسود والأخضر والأبيض المائل للاصفرار', correct: true },
      { text: 'البرتقالي والرمادي والبيج', correct: false },
      { text: 'الذهبي والفضي فقط', correct: false },
    ],
    explanation: 'تميزت التصاميم الزخرفية في المنسوجات الشعبية السعودية بالألوان: الأحمر والأسود والأخضر والأبيض المائل للاصفرار.',
    goldenRule: 'أحمر + أسود + أخضر + أبيض مصفر = لوحة ألوان المنسوج الشعبي السعودي.',
    paragraph: 'التصاميم الزخرفية المستخدمة — ص ٨٤',
  },
  {
    id: 'g3a_056', unit: 'u4', lesson: 'u4l1', page: 84, difficulty: 'medium',
    type: 'classify',
    question: 'صنّف القطع النسجية الشعبية السعودية حسب وظيفتها:',
    categories: ['للسكن والمفروشات', 'للحفظ والتخزين'],
    items: [
      { text: 'الخيمة', correct_category: 0 },
      { text: 'الشملة (مفروشات للأرضية)', correct_category: 0 },
      { text: 'أكياس لحفظ البن والحبوب', correct_category: 1 },
      { text: 'الخرج للجمال', correct_category: 1 },
    ],
    explanation: 'المنسوجات الشعبية متعددة الوظائف: للسكن (الخيمة)، للمفروشات (الشملة)، للحفظ (الأكياس والخرج).',
    goldenRule: 'المنسوج الشعبي جميل ونافع في آنٍ واحد.',
    paragraph: 'منسوجات شعبية من البيئة السعودية — ص ٨٤',
  },
  {
    id: 'g3a_057', unit: 'u4', lesson: 'u4l1', page: 88, difficulty: 'hard',
    type: 'ordering',
    question: 'رتّب خطوات النسيج البسيط على الفلين:',
    items: [
      'عملية النسيج بإدخال خامة اللحمة فوق وتحت خيوط السدى بالتناوب',
      'إخراج القطعة من النول وتثبيت الخيوط',
      'تجهيز النول (قطعة الفلين)',
      'تسدية النول بشد خيوط السدى',
    ],
    correctOrder: [2, 3, 0, 1],
    explanation: 'الخطوة ١: تجهيز النول → ٢: التسدية → ٣: عملية النسيج → ٤: إخراج القطعة.',
    goldenRule: 'جهّز → سدِّ → انسج → أخرج.',
    paragraph: 'خطوات التنفيذ — ص ٨٧-٨٩',
  },
  {
    id: 'g3a_058', unit: 'u4', lesson: 'u4l1', page: 89, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'كيف يتم نسج الصف الثاني مقارنة بالصف الأول في النسيج البسيط؟',
    options: [
      { text: 'بنفس الطريقة تماماً', correct: false },
      { text: 'بطريقة عكسية: ما كان فوق يصبح تحت وما كان تحت يصبح فوق', correct: true },
      { text: 'بإضافة خيوط سدى جديدة', correct: false },
      { text: 'باستخدام لون مختلف دائماً', correct: false },
    ],
    explanation: 'كل سطر يكون عكس السابق له: إذا كان الأول فوق-تحت فالثاني يكون تحت-فوق، وهكذا حتى تنتهي عملية النسيج.',
    goldenRule: 'تناوب فوق/تحت = مبدأ النسيج البسيط.',
    paragraph: 'عملية النسيج — ص ٨٩',
  },
  {
    id: 'g3a_059', unit: 'u4', lesson: 'u4l1', page: 90, difficulty: 'medium',
    type: 'trueFalse',
    question: 'يمكن عمل نسيج باستخدام الشرائح البلاستيكية الملونة.',
    correctAnswer: 'true',
    explanation: 'يمكن استخدام الشرائح البلاستيكية الملونة لأغلفة الملفات القديمة والأكياس البلاستيكية لعمل ميدالية نسجية جميلة.',
    goldenRule: 'الخامات المستهلكة يمكن إعادة توظيفها في النسيج الإبداعي.',
    paragraph: 'خطوات عملية النسج — ص ٩٠',
  },
  {
    id: 'g3a_060', unit: 'u4', lesson: 'u4l1', page: 91, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'كيف يمكن توظيف قطعة الخيش في النسيج البسيط؟',
    options: [
      { text: 'بصبغها بألوان مختلفة فقط', correct: false },
      { text: 'بإزالة بعض خيوط اللحمة منها ثم نسج تلك الأجزاء بخامات ملونة', correct: true },
      { text: 'باستخدامها كنول عادي دون تعديل', correct: false },
      { text: 'بقصها إلى شرائط وإعادة نسجها', correct: false },
    ],
    explanation: 'يمكن إحضار قطعة خيش وإزالة بعض خيوط اللحمة منها ثم نسج تلك الأجزاء بخامات ملونة للحصول على تأثير نسجي جميل.',
    goldenRule: 'الخيش كنول: أزل بعض خيوط اللحمة ثم انسج بألوانك.',
    paragraph: 'عملية النسيج بعد الإزالة — ص ٩٢',
  },
];

export const TOTAL_QUESTIONS_G3_ART = ART_G3_S1_QUESTIONS.length;