// أسئلة إضافية — الوحدة الرابعة: مجال الطباعة

export const u4l1_extra = [
  {
    id:'u4l1q9', unit:'u4', lesson:'u4l1', page:82, type:'trueFalse',
    bloom:'remember', difficulty:'easy',
    question:'شعب أشانتي في غانا برع في زخرفة القماش بفن الطباعة.',
    paragraph:'السكان في مملكة أشانتي القديمة برعوا في زخرفة القماش بواسطة قوالب. (ص82)',
    correctAnswer:true,
    explanation:'شعب أشانتي في مملكة أشانتي القديمة (غانا) برع في فن الطباعة على القماش.',
    goldenRule:'أشانتي = غانا = أفريقيا = برعوا في الطباعة على القماش.',
  },
  {
    id:'u4l1q10', unit:'u4', lesson:'u4l1', page:82, type:'trueFalse',
    bloom:'remember', difficulty:'easy',
    question:'صنع أشانتي قوالب الطباعة من خشب شجر الكباش.',
    paragraph:'برعوا في زخرفة القماش بواسطة قوالب صنعوها من خشب شجر الكباش. (ص82)',
    correctAnswer:true,
    explanation:'القالب الخشبي من شجر الكباش — مادة طبيعية محلية.',
    goldenRule:'قالب أشانتي = خشب شجر الكباش = مادة طبيعية = فن بيئي.',
  },
  {
    id:'u4l1q11', unit:'u4', lesson:'u4l1', page:82, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'ما المادة التي يُغمس فيها قالب الطباعة قبل وضعه على القماش؟',
    paragraph:'برعوا في زخرفة القماش بواسطة قوالب صنعوها من خشب شجر الكباش بعد غمسها في الصبغة. (ص82)',
    options:[
      {text:'الصبغة',correct:true},
      {text:'الماء',correct:false},
      {text:'الزيت',correct:false},
      {text:'العسل',correct:false},
    ],
    explanation:'القالب يُغمس في الصبغة (لون سائل) ثم يُضغط على القماش فيطبع الشكل.',
    goldenRule:'قالب + صبغة + قماش = طباعة. القالب ينقل الشكل للقماش.',
  },
  {
    id:'u4l1q12', unit:'u4', lesson:'u4l1', page:83, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'القالب الهلال مستمد من شكل الهلال الذي يظهر في السماء.',
    paragraph:'هذا القالب مستمد من شكل يظهر في السماء بداية كل شهر قمري. (ص83)',
    correctAnswer:true,
    explanation:'قالب الهلال مستوحى من هلال القمر في بداية كل شهر هجري.',
    goldenRule:'قالب الهلال = هلال القمر = بداية شهر قمري = استلهام سماوي.',
  },
  {
    id:'u4l1q13', unit:'u4', lesson:'u4l1', page:83, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'القالب الثاني من قوالب أشانتي مستوحى من الأزهار المنتشرة في الطبيعة.',
    paragraph:'وهذا القالب مستوحى من شكل المنتشرة في الطبيعة. (ص83)',
    correctAnswer:true,
    explanation:'قالب الأزهار مستوحى من الأزهار المنتشرة في الطبيعة حولهم.',
    goldenRule:'قالب الأزهار = زهور الطبيعة = استلهام أرضي.',
  },
  {
    id:'u4l1q14', unit:'u4', lesson:'u4l1', page:82, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'الأشكال المطبوعة على القماش الغاني مستمدة من الطبيعة كأوراق الأشجار.',
    paragraph:'الأشكال المطبوعة على القماش مستمدة من الطبيعة كأوراق الأشجار. (ص82)',
    correctAnswer:true,
    explanation:'الطبيعة = مصدر قوالب الطباعة: أوراق + هلال + أزهار = إلهام طبيعي.',
    goldenRule:'الطباعة من الطبيعة = أوراق + هلال + أزهار = قوالب طبيعية.',
  },
  {
    id:'u4l1q15', unit:'u4', lesson:'u4l1', page:84, type:'trueFalse',
    bloom:'apply', difficulty:'easy',
    question:'يمكن الاستفادة من الطبيعة لصنع قوالب طباعية من أوراق الأشجار.',
    paragraph:'صل/ي القوالب الطباعية بأوراق الشجر في العمود الثاني التي استُمدّت منها. (ص84)',
    correctAnswer:true,
    explanation:'أوراق الأشجار أشكالها متنوعة = قوالب طباعة مجانية من الطبيعة.',
    goldenRule:'أوراق الأشجار = قوالب طباعة طبيعية = مجانية + جميلة + متنوعة.',
  },
  {
    id:'u4l1q16', unit:'u4', lesson:'u4l1', page:82, type:'fillBlank',
    bloom:'remember', difficulty:'easy',
    question:'أكمل: "صنع أشانتي القوالب من خشب شجر ___."',
    paragraph:'قوالب صنعوها من خشب شجر الكباش بعد غمسها في الصبغة. (ص82)',
    blanks:['الكباش'],
    wordBank:['الكباش','الصنوبر','النخيل','البلوط'],
    explanation:'خشب شجر الكباش = مادة القالب عند أشانتي — متوفر محلياً وسهل النحت.',
    goldenRule:'قالب أشانتي = خشب الكباش + نحت + صبغة = قالب طباعي.',
  },
  {
    id:'u4l1q17', unit:'u4', lesson:'u4l1', page:83, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'القالب الهلال مستوحى من:',
    paragraph:'هذا القالب مستمد من شكل يظهر في السماء بداية كل شهر قمري. (ص83)',
    options:[
      {text:'هلال القمر في السماء',correct:true},
      {text:'أوراق الأشجار',correct:false},
      {text:'الأزهار',correct:false},
      {text:'الجبال',correct:false},
    ],
    explanation:'قالب الهلال = هلال القمر = استلهام سماوي من بداية الشهر القمري.',
    goldenRule:'قالب الهلال = قمر السماء = استلهام سماوي شهري.',
  },
  {
    id:'u4l1q18', unit:'u4', lesson:'u4l1', page:83, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'القالب الثاني مستوحى من:',
    paragraph:'وهذا القالب مستوحى من شكل المنتشرة في الطبيعة. (ص83)',
    options:[
      {text:'الأزهار المنتشرة في الطبيعة',correct:true},
      {text:'النجوم في السماء',correct:false},
      {text:'الجبال',correct:false},
      {text:'الأنهار',correct:false},
    ],
    explanation:'قالب الأزهار = زهور الطبيعة المنتشرة = استلهام أرضي نباتي.',
    goldenRule:'قالب الأزهار = زهور الأرض = استلهام أرضي.',
  },
  {
    id:'u4l1q19', unit:'u4', lesson:'u4l1', page:84, type:'matching',
    bloom:'analyze', difficulty:'medium',
    question:'صِل كل قالب طباعي بالورقة المستمدّ منها:',
    paragraph:'صل/ي القوالب الطباعية بأوراق الشجر في العمود الثاني التي استُمدّت منها. (ص84)',
    pairs:[
      {left:'قالب بشكل ورقة عنقودية',right:'ورقة العنب'},
      {left:'قالب بشكل ورقة مستدقّة',right:'ورقة اللبلاب'},
      {left:'قالب بشكل ورقة مثلثة',right:'ورقة الكستناء'},
    ],
    explanation:'عنقودية = عنب. مستدقة = لبلاب. مثلثة = كستناء.',
    goldenRule:'كل قالب = ورقة. شكل القالب = شكل الورقة = استلهام طبيعي.',
  },
  {
    id:'u4l1q20', unit:'u4', lesson:'u4l1', page:82, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'ماذا يعني أن أشانتي "برعوا" في زخرفة القماش؟',
    paragraph:'السكان في مملكة أشانتي القديمة برعوا في زخرفة القماش. (ص82)',
    options:[
      {text:'أجادوا وأتقنوا فن الطباعة على القماش',correct:true},
      {text:'فشلوا في الزخرفة',correct:false},
      {text:'تعلّموا للتو',correct:false},
      {text:'نسوا الفن',correct:false},
    ],
    explanation:'برعوا = أجادوا وأتقنوا = درجة عالية من الإتقان والمهارة الفنية.',
    goldenRule:'برعوا = إتقان + مهارة = درجة عالية من الإجادة الفنية.',
  },
  {
    id:'u4l1q21', unit:'u4', lesson:'u4l1', page:82, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف مصادر قوالب أشانتي:',
    paragraph:'القالب مستمد من شكل يظهر في السماء... مستوحى من شكل المنتشرة في الطبيعة... مستمدة من الطبيعة كأوراق الأشجار. (ص82-83)',
    categories:['استلهام سماوي ☽','استلهام أرضي 🌿'],
    items:[
      {text:'قالب الهلال',correct_category:0},
      {text:'قالب الأزهار المنتشرة',correct_category:1},
      {text:'قالب أوراق الأشجار',correct_category:1},
      {text:'قالب ورقة العنب',correct_category:1},
    ],
    explanation:'سماوي = الهلال. أرضي = أزهار + أوراق = استلهام من الأرض.',
    goldenRule:'قوالب أشانتي = سماوي (هلال) + أرضي (أزهار/أوراق) = إلهام طبيعي شامل.',
  },
  {
    id:'u4l1q22', unit:'u4', lesson:'u4l1', page:82, type:'trueFalse',
    bloom:'evaluate', difficulty:'medium',
    question:'فن الطباعة عند أشانتي مثال على كيفية استلهام الفن من البيئة المحلية.',
    paragraph:'السكان في مملكة أشانتي القديمة برعوا في زخرفة القماش بواسطة قوالب... الأشكال مستمدة من الطبيعة. (ص82-83)',
    correctAnswer:true,
    explanation:'الفن البيئي = استلهام من البيئة المحلية. أشانتي استلهموا من السماء والأرض.',
    goldenRule:'الفن البيئي = بيئة + إلهام = فن أصيل منسجم مع المحيط.',
  },
  {
    id:'u4l1q23', unit:'u4', lesson:'u4l1', page:82, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'في أي دولة تقع مملكة أشانتي القديمة؟',
    paragraph:'السكان في مملكة أشانتي القديمة... (ص82)',
    options:[
      {text:'غانا في غرب أفريقيا',correct:true},
      {text:'مصر في شمال أفريقيا',correct:false},
      {text:'اليابان في شرق آسيا',correct:false},
      {text:'البرازيل في أمريكا الجنوبية',correct:false},
    ],
    explanation:'أشانتي = مملكة قديمة في غانا = دولة في غرب أفريقيا.',
    goldenRule:'أشانتي = غانا = غرب أفريقيا = مملكة فنية قديمة.',
  },
  {
    id:'u4l1q24', unit:'u4', lesson:'u4l1', page:82, type:'multipleChoice',
    bloom:'apply', difficulty:'medium',
    question:'ما الخطوات الأساسية للطباعة بالقالب؟',
    paragraph:'قوالب صنعوها من خشب شجر الكباش بعد غمسها في الصبغة. (ص82)',
    options:[
      {text:'صنع القالب + غمس في الصبغة + ضغط على القماش',correct:true},
      {text:'رسم بالقلم فقط',correct:false},
      {text:'طلاء بالفرشاة فقط',correct:false},
      {text:'لا خطوات',correct:false},
    ],
    explanation:'الطباعة بالقالب: (1) صنع قالب (2) غمس في صبغة (3) ضغط على قماش = طباعة.',
    goldenRule:'طباعة بالقالب = قالب + صبغة + قماش = 3 خطوات = شكل مطبوع.',
  },
  {
    id:'u4l1q25', unit:'u4', lesson:'u4l1', page:84, type:'trueFalse',
    bloom:'apply', difficulty:'easy',
    question:'أوراق الأشجار بأشكالها المتنوعة تصلح كقوالب للطباعة.',
    paragraph:'صل/ي القوالب الطباعية بأوراق الشجر... التي استُمدّت منها. (ص84)',
    correctAnswer:true,
    explanation:'أوراق الأشجار = قوالب طبيعية مجانية + متنوعة الأشكال = مثالية للطباعة.',
    goldenRule:'أوراق الأشجار = قوالب طبيعية = مجانية + متنوعة = جاهزة للطباعة.',
  },
  {
    id:'u4l1q26', unit:'u4', lesson:'u4l1', page:83, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'لماذا استوحى أشانتي قوالبهم من الطبيعة؟',
    paragraph:'الأشكال المطبوعة على القماش مستمدة من الطبيعة كأوراق الأشجار... (ص82-83)',
    options:[
      {text:'لأن الطبيعة كانت مصدر إلهامهم الأول والمتاح حولهم',correct:true},
      {text:'لأنهم أُجبروا على ذلك',correct:false},
      {text:'لأنهم لم يعرفوا شكلاً آخر',correct:false},
      {text:'لا سبب',correct:false},
    ],
    explanation:'الطبيعة المحيطة = مصدر الإلهام الأول = متاحة + جميلة + متنوعة.',
    goldenRule:'الطبيعة = مصدر الإلهام الأول = متاحة + مجانية + لا تنتهي.',
  },
  {
    id:'u4l1q27', unit:'u4', lesson:'u4l1', page:83, type:'trueFalse',
    bloom:'analyze', difficulty:'medium',
    question:'الفنان الأشانتي نظر للسماء فاستلهم الهلال، ونظر للأرض فاستلهم الأزهار.',
    paragraph:'هذا القالب مستمد من شكل يظهر في السماء... مستوحى من شكل المنتشرة في الطبيعة. (ص83)',
    correctAnswer:true,
    explanation:'الفنان نظر: سماء → هلال، أرض → أزهار. عينان مفتوحتان على الطبيعة كلها.',
    goldenRule:'الفنان = عين مفتوحة: سماء + أرض = مصادر إلهام لا تنتهي.',
  },
  {
    id:'u4l1q28', unit:'u4', lesson:'u4l1', page:82, type:'fillBlank',
    bloom:'remember', difficulty:'easy',
    question:'أكمل: "غمس أشانتي القوالب في ___ ثم ضغطوها على القماش."',
    paragraph:'قوالب صنعوها من خشب شجر الكباش بعد غمسها في الصبغة. (ص82)',
    blanks:['الصبغة'],
    wordBank:['الصبغة','الماء','الزيت','العسل'],
    explanation:'الصبغة = لون سائل. القالب يُغمس فيها ثم يُضغط = طباعة ملونة.',
    goldenRule:'الصبغة = لون سائل. قالب + صبغة = طباعة ملونة على القماش.',
  },
  {
    id:'u4l1q29', unit:'u4', lesson:'u4l1', page:84, type:'multipleChoice',
    bloom:'create', difficulty:'hard',
    question:'لو أردت صنع قالب طباعة من الطبيعة، ماذا تختار؟',
    paragraph:'صل/ي القوالب الطباعية بأوراق الشجر... (ص84)',
    options:[
      {text:'أوراق أشجار بأشكال متنوعة (عنب/لبلاب/كستناء)',correct:true},
      {text:'زجاج مكسور',correct:false},
      {text:'معدن ثقيل',correct:false},
      {text:'بلاستيك صلب',correct:false},
    ],
    explanation:'أوراق الأشجار = آمنة + متنوعة + مجانية = قوالب طباعة طبيعية مثالية.',
    goldenRule:'قالب طبيعي = أوراق أشجار = آمن + متنوع + مجاني = طباعة بيئية.',
  },
  {
    id:'u4l1q30', unit:'u4', lesson:'u4l1', page:83, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'ما الذي يربط بين قالب الهلال وقالب الأزهار في فن أشانتي؟',
    paragraph:'هذا القالب مستمد من شكل يظهر في السماء... مستوحى من شكل المنتشرة في الطبيعة. (ص83)',
    options:[
      {text:'كلاهما مستلهم من الطبيعة (السماء والأرض)',correct:true},
      {text:'كلاهما من المصنع',correct:false},
      {text:'لا علاقة بينهما',correct:false},
      {text:'كلاهما من الكتب',correct:false},
    ],
    explanation:'القوالب كلها مستلهمة من الطبيعة — سماء (هلال) وأرض (أزهار) = وحدة المصدر.',
    goldenRule:'قوالب أشانتي = كلها من الطبيعة. سماء + أرض = مصدر واحد = إلهام بيئي.',
  },
  {
    id:'u4l1q31', unit:'u4', lesson:'u4l1', page:82, type:'trueFalse',
    bloom:'evaluate', difficulty:'medium',
    question:'فن الطباعة عند أشانتي دليل على إبداع الإنسان القديم في استخدام ما حوله.',
    paragraph:'السكان في مملكة أشانتي القديمة برعوا في زخرفة القماش بواسطة قوالب. (ص82)',
    correctAnswer:true,
    explanation:'أشانتي = إبداع بيئي = خشب محلي + صبغة + قماش = طباعة = فن من لا شيء.',
    goldenRule:'الإنسان المبدع = يصنع فناً من ما حوله = إبداع + بيئة = فن نافع.',
  },
  {
    id:'u4l1q32', unit:'u4', lesson:'u4l1', page:82, type:'fillBlank',
    bloom:'remember', difficulty:'easy',
    question:'أكمل: "برع أشانتي في زخرفة ___ بواسطة قوالب."',
    paragraph:'برعوا في زخرفة القماش بواسطة قوالب صنعوها من خشب شجر الكباش. (ص82)',
    blanks:['القماش'],
    wordBank:['القماش','الورق','الزجاج','الحديد'],
    explanation:'أشانتي طبعوا على القماش — مادة مرنة تمتص الصبغة وتحفظ الشكل.',
    goldenRule:'طباعة أشانتي = على القماش = مادة مرنة + صبغة = طباعة واضحة.',
  },
  {
    id:'u4l1q33', unit:'u4', lesson:'u4l1', page:84, type:'trueFalse',
    bloom:'apply', difficulty:'easy',
    question:'تنوع أشكال أوراق الأشجار يوفر تنوعاً في قوالب الطباعة.',
    paragraph:'صل/ي القوالب الطباعية بأوراق الشجر... (ص84)',
    correctAnswer:true,
    explanation:'أوراق متنوعة = قوالب متنوعة = طباعة غنية بالأشكال والأنماط.',
    goldenRule:'تنوع الأوراق = تنوع القوالب = تنوع الطباعة = إبداع لا محدود.',
  },
  {
    id:'u4l1q34', unit:'u4', lesson:'u4l1', page:82, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'ما المادة الأساسية التي يطبع عليها أشانتي؟',
    paragraph:'برعوا في زخرفة القماش بواسطة قوالب. (ص82)',
    options:[
      {text:'القماش',correct:true},
      {text:'الورق',correct:false},
      {text:'الزجاج',correct:false},
      {text:'الحديد',correct:false},
    ],
    explanation:'أشانتي طبعوا على القماش — مادة مرنة تمتص الصبغة وتحفظ الشكل المطبوع.',
    goldenRule:'طباعة أشانتي = على القماش. القماش يمتص الصبغة ويحفظ الشكل.',
  },
  {
    id:'u4l1q35', unit:'u4', lesson:'u4l1', page:83, type:'trueFalse',
    bloom:'remember', difficulty:'easy',
    question:'قالب الهلال من قوالب أشانتي يظهر في السماء بداية كل شهر قمري.',
    paragraph:'هذا القالب مستمد من شكل يظهر في السماء بداية كل شهر قمري. (ص83)',
    correctAnswer:true,
    explanation:'هلال القمر يظهر بداية كل شهر هجري — أشانتي استلهموا منه شكلاً للطباعة.',
    goldenRule:'هلال القمر = بداية الشهر القمري = قالب طباعي = استلهام سماوي.',
  },
  {
    id:'u4l1q36', unit:'u4', lesson:'u4l1', page:84, type:'multipleChoice',
    bloom:'analyze', difficulty:'medium',
    question:'ما الفائدة من استخدام أوراق الأشجار كقوالب للطباعة؟',
    paragraph:'صل/ي القوالب الطباعية بأوراق الشجر في العمود الثاني التي استُمدّت منها. (ص84)',
    options:[
      {text:'تنوع الأشكال + مجانية + من الطبيعة',correct:true},
      {text:'لأنها أغلى ثمناً',correct:false},
      {text:'لأنها صعبة',correct:false},
      {text:'لا فائدة',correct:false},
    ],
    explanation:'أوراق الأشجار = متنوعة + مجانية + طبيعية = قوالب مثالية للطباعة البيئية.',
    goldenRule:'أوراق الأشجار = تنوع + مجانية + طبيعية = قوالب بيئية مثالية.',
  },
  {
    id:'u4l1q37', unit:'u4', lesson:'u4l1', page:82, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'ما علاقة فن أشانتي ببيئتهم المحلية؟',
    paragraph:'السكان في مملكة أشانتي القديمة برعوا في زخرفة القماش بواسطة قوالب صنعوها من خشب شجر الكباش. (ص82)',
    options:[
      {text:'استخدموا خامات بيئتهم: خشب محلي + صبغة + قماش',correct:true},
      {text:'استوردوا كل شيء من الخارج',correct:false},
      {text:'استخدموا المعادن الثمينة فقط',correct:false},
      {text:'لا علاقة بالبيئة',correct:false},
    ],
    explanation:'أشانتي = فن بيئي = خشب محلي (الكباش) + صبغة + قماش = اكتفاء ذاتي.',
    goldenRule:'فن أشانتي = بيئة محلية = خشب + صبغة + قماش = اكتفاء ذاتي بيئي.',
  },
  {
    id:'u4l1q38', unit:'u4', lesson:'u4l1', page:83, type:'fillBlank',
    bloom:'remember', difficulty:'easy',
    question:'أكمل: "قالب الأزهار مستوحى من الأزهار ___ في الطبيعة."',
    paragraph:'وهذا القالب مستوحى من شكل المنتشرة في الطبيعة. (ص83)',
    blanks:['المنتشرة'],
    wordBank:['المنتشرة','النادرة','الكبيرة','الصغيرة'],
    explanation:'الأزهار المنتشرة = المتوفرة بكثرة في الطبيعة المحيطة = سهلة المراقبة.',
    goldenRule:'الأزهار المنتشرة = متوفرة + كثيرة = مصدر إلهام سهل ومتاح.',
  },
  {
    id:'u4l1q39', unit:'u4', lesson:'u4l1', page:82, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'القالب الخشبي يحمل الشكل المنحوت وينقله إلى القماش بالضغط.',
    paragraph:'قوالب صنعوها من خشب شجر الكباش بعد غمسها في الصبغة. (ص82)',
    correctAnswer:true,
    explanation:'القالب = قالب نحت عليه شكلاً. نغمس في صبغة + نضغط = ينقل الشكل للقماش.',
    goldenRule:'القالب = نحت + صبغة + ضغط = نقل الشكل للقماش = طباعة.',
  },
  {
    id:'u4l1q40', unit:'u4', lesson:'u4l1', page:84, type:'multipleChoice',
    bloom:'apply', difficulty:'easy',
    question:'لو أردت طباعة شكل ورقة العنب، ماذا تفعل؟',
    paragraph:'صل/ي القوالب الطباعية بأوراق الشجر... (ص84)',
    options:[
      {text:'أخذ ورقة عنب + غمس في صبغة + ضغط على ورقة',correct:true},
      {text:'رسمها بالقلم فقط',correct:false},
      {text:'قصها فقط',correct:false},
      {text:'لا شيء',correct:false},
    ],
    explanation:'ورقة عنب + صبغة + ضغط = طباعة ورقة العنب على الورقة أو القماش.',
    goldenRule:'ورقة طبيعية + صبغة + ضغط = طباعة طبيعية = قالب مجاني.',
  },
  {
    id:'u4l1q41', unit:'u4', lesson:'u4l1', page:83, type:'trueFalse',
    bloom:'evaluate', difficulty:'hard',
    question:'تنوع قوالب أشانتي (هلال + أزهار + أوراق) يدل على ملاحظة الفنان للطبيعة بكل تفاصيلها.',
    paragraph:'هذا القالب مستمد من شكل يظهر في السماء... مستوحى من شكل المنتشرة في الطبيعة... مستمدة من الطبيعة كأوراق الأشجار. (ص82-84)',
    correctAnswer:true,
    explanation:'الفنان الأشانتي لاحظ: السماء (هلال) + الأرض (أزهار) + الأشجار (أوراق) = ملاحظة شاملة.',
    goldenRule:'الفنان المُلاحظ = سماء + أرض + أشجار = مصادر متعددة = إبداع غني.',
  },
  {
    id:'u4l1q42', unit:'u4', lesson:'u4l1', page:82, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'ما الشجرة التي صنع منها أشانتي قوالبهم؟',
    paragraph:'قوالب صنعوها من خشب شجر الكباش. (ص82)',
    options:[
      {text:'شجر الكباش',correct:true},
      {text:'شجر النخيل',correct:false},
      {text:'شجر الصنوبر',correct:false},
      {text:'شجر البلوط',correct:false},
    ],
    explanation:'خشب شجر الكباش = المادة المحلية المتوفرة في بيئة أشانتي = سهل النحت.',
    goldenRule:'شجر الكباش = خشب القالب = مادة محلية = سهل النحت للطباعة.',
  },
  {
    id:'u4l1q43', unit:'u4', lesson:'u4l1', page:84, type:'trueFalse',
    bloom:'apply', difficulty:'easy',
    question:'كل ورقة شجر لها شكل مختلف يعطي قالباً طباعياً مختلفاً.',
    paragraph:'صل/ي القوالب الطباعية بأوراق الشجر في العمود الثاني التي استُمدّت منها. (ص84)',
    correctAnswer:true,
    explanation:'عنب = عنقودية. لبلاب = مستدقة. كستناء = مثلثة. كل ورقة = قالب فريد.',
    goldenRule:'تنوع الأوراق = تنوع القوالب = تنوع الطباعة = إبداع لا محدود.',
  },
  {
    id:'u4l1q44', unit:'u4', lesson:'u4l1', page:83, type:'multipleChoice',
    bloom:'create', difficulty:'hard',
    question:'لو أردت تصميم قالب طباعي مستوحى من الطبيعة في بيئتك، ماذا تختار؟',
    paragraph:'الأشكال المطبوعة على القماش مستمدة من الطبيعة. (ص82)',
    options:[
      {text:'أوراق النخيل أو أزهار الصحراء أو شكل القمر',correct:true},
      {text:'شكل السيارة',correct:false},
      {text:'شكل الهاتف',correct:false},
      {text:'لا شيء',correct:false},
    ],
    explanation:'من بيئة المملكة: نخيل + أزهار صحراوية + قمر = قوالب طباعية بيئية سعودية.',
    goldenRule:'قوالب من بيئتك = نخيل + صحراء + قمر = طباعة سعودية أصيلة.',
  },
  {
    id:'u4l1q45', unit:'u4', lesson:'u4l1', page:82, type:'trueFalse',
    bloom:'remember', difficulty:'easy',
    question:'فن الطباعة بالقالب من أقدم طرق تزيين الأقمشة.',
    paragraph:'السكان في مملكة أشانتي القديمة برعوا في زخرفة القماش بواسطة قوالب. (ص82)',
    correctAnswer:true,
    explanation:'الطباعة بالقالب = طريقة قديمة = قبل الآلات الحديثة = فن يدوي أصيل.',
    goldenRule:'الطباعة بالقالب = فن يدوي قديم = قالب + صبغة + قماش = تزيين تقليدي.',
  },
];

export const u4_extra = [...u4l1_extra];