// أسئلة إضافية — الوحدة الثانية: مجال الرسم الزخرفي

export const u2l1_extra = [
  {
    id:'u2l1q9', unit:'u2', lesson:'u2l1', page:36, type:'trueFalse',
    bloom:'remember', difficulty:'easy',
    question:'الزخرفة النباتية مستوحاة من النباتات والأزهار والأوراق.',
    paragraph:'درسنا معاً أن للزخارف أنواعاً ثلاثة وهي: زخارف نباتية وزخارف هندسية وزخارف خطية كتابية. (ص36)',
    correctAnswer:true,
    explanation:'الزخرفة النباتية تأخذ عناصرها من الطبيعة النباتية: أوراق + أزهار + ثمار + أغصان.',
    goldenRule:'الزخرفة النباتية = من النبات. الزخرفة الهندسية = من الأشكال. الزخرفة الخطية = من الخط.',
  },
  {
    id:'u2l1q10', unit:'u2', lesson:'u2l1', page:36, type:'trueFalse',
    bloom:'remember', difficulty:'easy',
    question:'الزخرفة الهندسية تعتمد على الأشكال الرياضية كالمثلث والمربع والدائرة.',
    paragraph:'زخارف هندسية... (ص36)',
    correctAnswer:true,
    explanation:'الزخرفة الهندسية تستخدم الأشكال الهندسية: مثلثات + مربعات + دوائر + نجوم + مضلعات.',
    goldenRule:'زخرفة هندسية = مثلث + مربع + دائرة + نجمة + خطوط مستقيمة.',
  },
  {
    id:'u2l1q11', unit:'u2', lesson:'u2l1', page:36, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'الزخرفة الخطية الكتابية تعتمد على:',
    paragraph:'زخارف خطية كتابية. (ص36)',
    options:[
      {text:'الخط العربي الجميل',correct:true},
      {text:'الأشكال الهندسية',correct:false},
      {text:'أوراق النبات',correct:false},
      {text:'ألوان الطبيعة',correct:false},
    ],
    explanation:'الزخرفة الخطية الكتابية تستخدم الخط العربي (كلمة "الله" أو "محمد" أو آيات قرآنية) كعنصر زخرفي.',
    goldenRule:'الزخرفة الخطية = الخط العربي = جمال الحروف والكلمات.',
  },
  {
    id:'u2l1q12', unit:'u2', lesson:'u2l1', page:37, type:'fillBlank',
    bloom:'remember', difficulty:'easy',
    question:'أكمل: "التكرار هو ___ الشيء مرة بعد الأخرى."',
    paragraph:'التكرار: هو إعادة الشيء مرة بعد الأخرى. (ص37)',
    blanks:['إعادة'],
    wordBank:['إعادة','حذف','تكبير','تلوين'],
    explanation:'التكرار = إعادة الوحدة الزخرفية مرة بعد أخرى بشكل منتظم.',
    goldenRule:'التكرار = إعادة + انتظام = إيقاع بصري جميل.',
  },
  {
    id:'u2l1q13', unit:'u2', lesson:'u2l1', page:37, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'ما الوحدة الزخرفية؟',
    paragraph:'التكرار: هو إعادة الشيء مرة بعد الأخرى. (ص37)',
    options:[
      {text:'الشكل الأساسي الذي يُكرَّر في الزخرفة',correct:true},
      {text:'اللون المستخدم في الزخرفة',correct:false},
      {text:'الخلفية وراء الزخرفة',correct:false},
      {text:'الإطار حول الزخرفة',correct:false},
    ],
    explanation:'الوحدة الزخرفية = العنصر الأساسي (زهرة، نجمة، ورقة) الذي يتكرر لتكوين الزخرفة.',
    goldenRule:'الوحدة الزخرفية = بذرة الزخرفة. بتكرارها تتكوّن الزخرفة الكاملة.',
  },
  {
    id:'u2l1q14', unit:'u2', lesson:'u2l1', page:38, type:'trueFalse',
    bloom:'remember', difficulty:'easy',
    question:'التكرار العادي هو تكرار الوحدة الزخرفية في وضع ثابت متناوب.',
    paragraph:'التكرار العادي / التكرار المتعاكس / التكرار المتبادل. (ص38)',
    correctAnswer:true,
    explanation:'التكرار العادي: نفس الوحدة بنفس الوضع تتكرر بانتظام — أبسط أنواع التكرار.',
    goldenRule:'التكرار العادي = وحدة واحدة + وضع ثابت + تكرار منتظم.',
  },
  {
    id:'u2l1q15', unit:'u2', lesson:'u2l1', page:38, type:'trueFalse',
    bloom:'understand', difficulty:'medium',
    question:'في التكرار المتعاكس، تتجاور الوحدات في أوضاع متعاكسة (أعلى/أسفل أو يمين/شمال).',
    paragraph:'التكرار المتعاكس: وفيه تتجاور الوحدات الزخرفية في أوضاع متعاكسة تارةً إلى الأعلى أو الأسفل وتارة إلى اليمين أو إلى الشمال. (ص38)',
    correctAnswer:true,
    explanation:'التكرار المتعاكس: الوحدة تُقلَب رأساً على عقب أو يميناً ليساراً بشكل متعاكس ومنتظم.',
    goldenRule:'التكرار المتعاكس = قلب الوحدة (↑↓ أو →←) = تقابل متناسق.',
  },
  {
    id:'u2l1q16', unit:'u2', lesson:'u2l1', page:38, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'التكرار المتبادل يستخدم:',
    paragraph:'التكرار المتبادل: وهو استخدام وحدتين زخرفيتين مختلفتين في تجاور وتعاقب الواحدة تلو الأخرى. (ص38)',
    options:[
      {text:'وحدتين زخرفيتين مختلفتين تتناوبان',correct:true},
      {text:'وحدة واحدة فقط',correct:false},
      {text:'ثلاث وحدات',correct:false},
      {text:'أربع وحدات',correct:false},
    ],
    explanation:'التكرار المتبادل: وحدتان مختلفتان (مثل وردة + نجمة) تتناوبان بالتسلسل.',
    goldenRule:'التكرار المتبادل = وحدتان + تناوب = ثراء بصري ثنائي.',
  },
  {
    id:'u2l1q17', unit:'u2', lesson:'u2l1', page:39, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف أنواع الزخارف:',
    paragraph:'أنواع الزخارف: نباتية / هندسية / خطية كتابية. (ص36-39)',
    categories:['زخرفة نباتية 🌿','زخرفة هندسية 📐','زخرفة خطية ✍️'],
    items:[
      {text:'ورقة معدّلة منكوبة',correct_category:0},
      {text:'زهرة وردة منمّقة',correct_category:0},
      {text:'نجمة ثمانية',correct_category:1},
      {text:'مضلع سداسي',correct_category:1},
      {text:'كلمة "الله" بخط الثلث',correct_category:2},
      {text:'آية قرآنية مزخرفة',correct_category:2},
    ],
    explanation:'نباتية: من الطبيعة. هندسية: أشكال رياضية. خطية: الخط العربي.',
    goldenRule:'3 أنواع زخارف: نباتي (طبيعة) + هندسي (رياضيات) + خطي (عربية).',
  },
  {
    id:'u2l1q18', unit:'u2', lesson:'u2l1', page:37, type:'trueFalse',
    bloom:'analyze', difficulty:'medium',
    question:'الزخرفة الإسلامية تعتمد على مبدأ التكرار.',
    paragraph:'ب - لاحظ التكرار في الزخرفة الإسلامية، هل يمكنك وصف ما تراه؟ (ص37)',
    correctAnswer:true,
    explanation:'الزخرفة الإسلامية قائمة على التكرار — الوحدة الزخرفية تتكرر لتملأ المساحة بتناسق.',
    goldenRule:'الزخرفة الإسلامية = تكرار + تناسق = جمال لا نهائي.',
  },
  {
    id:'u2l1q19', unit:'u2', lesson:'u2l1', page:40, type:'multipleChoice',
    bloom:'apply', difficulty:'medium',
    question:'من الاستخدامات العملية للزخرفة النباتية:',
    paragraph:'يمكن الاستفادة منها في رسم زخارف متنوعة تفيد في تزيين المنزل كعمل بطاقة تهنئة. (ص40)',
    options:[
      {text:'بطاقة تهنئة وإطار لوحة جدارية',correct:true},
      {text:'صنع الطعام',correct:false},
      {text:'إصلاح السيارات',correct:false},
      {text:'بناء المنازل',correct:false},
    ],
    explanation:'الزخرفة النباتية تُزيّن: بطاقات التهنئة + إطارات اللوحات + الأقمشة + الأواني.',
    goldenRule:'الزخرفة النباتية = تزيين بطاقات + إطارات + أقمشة = فن تطبيقي.',
  },
  {
    id:'u2l1q20', unit:'u2', lesson:'u2l1', page:38, type:'matching',
    bloom:'understand', difficulty:'medium',
    question:'صِل كل نوع تكرار بوصفه:',
    paragraph:'أنواع التكرار: عادي / متعاكس / متبادل. (ص38)',
    pairs:[
      {left:'التكرار العادي',right:'وحدة واحدة + وضع ثابت'},
      {left:'التكرار المتعاكس',right:'وحدة مقلوبة (أعلى/أسفل)'},
      {left:'التكرار المتبادل',right:'وحدتان مختلفتان تتناوبان'},
    ],
    explanation:'عادي: ثابت. متعاكس: مقلوب. متبادل: وحدتان.',
    goldenRule:'عادي=ثابت، متعاكس=مقلوب، متبادل=وحدتان. 3 أنواع للتكرار.',
  },
  {
    id:'u2l1q21', unit:'u2', lesson:'u2l1', page:36, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'لماذا يُعدّ التكرار أهم عنصر في الزخرفة؟',
    paragraph:'التكرار: هو إعادة الشيء مرة بعد الأخرى. (ص37)',
    options:[
      {text:'لأنه يخلق إيقاعاً بصرياً متناسقاً يملأ المساحة بالجمال',correct:true},
      {text:'لأنه يوفّر الألوان فقط',correct:false},
      {text:'لأنه سهل الرسم فقط',correct:false},
      {text:'لا أهمية للتكرار',correct:false},
    ],
    explanation:'التكرار يُنشئ إيقاعاً بصرياً منتظماً يملأ المساحات بتناسق وجمال لا ينتهي.',
    goldenRule:'التكرار = إيقاع + تناسق + امتلاء = جمال الزخرفة.',
  },
  {
    id:'u2l1q22', unit:'u2', lesson:'u2l1', page:40, type:'trueFalse',
    bloom:'apply', difficulty:'easy',
    question:'يمكن استخدام الزخرفة النباتية في تزيين بطاقة تهنئة.',
    paragraph:'تفيد في تزيين المنزل كعمل بطاقة تهنئة الشكل (٣٤)، والشكل (٣٥). (ص40)',
    correctAnswer:true,
    explanation:'بطاقة التهنئة المزخرفة بالعناصر النباتية مثال عملي للفن التطبيقي.',
    goldenRule:'بطاقة تهنئة + زخرفة نباتية = فن تطبيقي نافع + جميل.',
  },
  {
    id:'u2l1q23', unit:'u2', lesson:'u2l1', page:37, type:'multipleChoice',
    bloom:'understand', difficulty:'easy',
    question:'عند ملاحظة التكرار في الزخرفة الإسلامية، ماذا نلاحظ؟',
    paragraph:'ب - لاحظ التكرار في الزخرفة الإسلامية، هل يمكنك وصف ما تراه؟ (ص37)',
    options:[
      {text:'وحدات زخرفية تتكرر بانتظام وتملأ المساحة بتناسق',correct:true},
      {text:'ألوان عشوائية بلا نظام',correct:false},
      {text:'أشكال مختلفة تماماً',correct:false},
      {text:'لا شيء يُلاحظ',correct:false},
    ],
    explanation:'التكرار في الزخرفة الإسلامية = وحدات تكرر بانتظام تملأ المساحة بجمال متناسق.',
    goldenRule:'الزخرفة الإسلامية = وحدات + تكرار + تناسق = امتداد لا نهائي.',
  },
  {
    id:'u2l1q24', unit:'u2', lesson:'u2l1', page:38, type:'multipleChoice',
    bloom:'create', difficulty:'hard',
    question:'لو أردت تصميم زخرفة بتكرار متبادل، ماذا تختار؟',
    paragraph:'التكرار المتبادل: استخدام وحدتين زخرفيتين مختلفتين في تجاور وتعاقب. (ص38)',
    options:[
      {text:'وردة ونجمة تتناوبان بالتسلسل',correct:true},
      {text:'وردة واحدة فقط',correct:false},
      {text:'نجمة واحدة فقط',correct:false},
      {text:'وردة مقلوبة فقط',correct:false},
    ],
    explanation:'التكرار المتبادل يحتاج وحدتين مختلفتين: وردة + نجمة تتناوبان.',
    goldenRule:'التكرار المتبادل = وحدتان مختلفتان + تناوب = تنوع + انتظام.',
  },
  {
    id:'u2l1q25', unit:'u2', lesson:'u2l1', page:39, type:'trueFalse',
    bloom:'remember', difficulty:'easy',
    question:'الزخرفة الخطية الكتابية تستخدم الخط العربي كعنصر جمالي.',
    paragraph:'زخارف خطية كتابية. (ص36)',
    correctAnswer:true,
    explanation:'الخط العربي يُستخدم كزخرفة في المساجد والقصور والعملات والمباني الإسلامية.',
    goldenRule:'الخط العربي = زخرفة + فن + هوية = جمال الحروف العربية.',
  },
  {
    id:'u2l1q26', unit:'u2', lesson:'u2l1', page:36, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'كم نوعاً للزخارف كما ذُكر في الكتاب؟',
    paragraph:'درسنا معاً أن للزخارف أنواعاً ثلاثة. (ص36)',
    options:[
      {text:'ثلاثة أنواع',correct:true},
      {text:'نوع واحد',correct:false},
      {text:'خمسة أنواع',correct:false},
      {text:'عشرة أنواع',correct:false},
    ],
    explanation:'ثلاثة أنواع: نباتية + هندسية + خطية كتابية.',
    goldenRule:'3 أنواع زخارف: نباتية + هندسية + خطية. ثلاثة فقط كما في الكتاب.',
  },
  {
    id:'u2l1q27', unit:'u2', lesson:'u2l1', page:40, type:'multipleChoice',
    bloom:'apply', difficulty:'easy',
    question:'ما الذي يمكن تزيينه بالزخرفة النباتية في المنزل؟',
    paragraph:'تفيد في تزيين المنزل كعمل بطاقة تهنئة. (ص40)',
    options:[
      {text:'بطاقة تهنئة وإطار لوحة جدارية',correct:true},
      {text:'الطعام في المطبخ',correct:false},
      {text:'السيارة في المرآب',correct:false},
      {text:'الحديقة الخارجية فقط',correct:false},
    ],
    explanation:'الزخرفة النباتية تُستخدم في تزيين البطاقات والإطارات داخل المنزل.',
    goldenRule:'الزخرفة النباتية = تزيين منزلي: بطاقات + إطارات + أقمشة + أوانٍ.',
  },
  {
    id:'u2l1q28', unit:'u2', lesson:'u2l1', page:38, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'التكرار المتعاكس يُعطي إيقاعاً بصرياً متوازناً لأن الوحدات تتقابل.',
    paragraph:'التكرار المتعاكس: وفيه تتجاور الوحدات الزخرفية في أوضاع متعاكسة. (ص38)',
    correctAnswer:true,
    explanation:'التقابل في التكرار المتعاكس يخلق توازناً بصرياً جميلاً بين النصفين.',
    goldenRule:'التكرار المتعاكس = تقابل = توازن = جمال متناظر.',
  },
  {
    id:'u2l1q29', unit:'u2', lesson:'u2l1', page:36, type:'fillBlank',
    bloom:'remember', difficulty:'easy',
    question:'أكمل: "للزخارف أنواع ___: نباتية وهندسية وخطية كتابية."',
    paragraph:'درسنا معاً أن للزخارف أنواعاً ثلاثة وهي: زخارف نباتية وزخارف هندسية وزخارف خطية كتابية. (ص36)',
    blanks:['ثلاثة'],
    wordBank:['ثلاثة','أربعة','خمسة','ستة'],
    explanation:'ثلاثة أنواع فقط: نباتية + هندسية + خطية كتابية.',
    goldenRule:'3 أنواع زخارف: نباتية + هندسية + خطية = ثلاثة فقط.',
  },
  {
    id:'u2l1q30', unit:'u2', lesson:'u2l1', page:37, type:'ordering',
    bloom:'apply', difficulty:'medium',
    question:'رتّب خطوات تصميم زخرفة بتكرار:',
    paragraph:'التكرار: هو إعادة الشيء مرة بعد الأخرى. (ص37)',
    items:['تكرار الوحدة بانتظام لتملأ المساحة','اختيار نوع التكرار (عادي/متعاكس/متبادل)','رسم الوحدة الزخرفية الأساسية','تلوين الزخرفة'],
    correctOrder:[2,1,0,3],
    explanation:'(1) رسم الوحدة ← (2) اختيار نوع التكرار ← (3) تكرار ← (4) تلوين.',
    goldenRule:'تصميم الزخرفة: وحدة ← نوع تكرار ← تكرار ← تلوين.',
  },
  {
    id:'u2l1q31', unit:'u2', lesson:'u2l1', page:38, type:'multipleChoice',
    bloom:'analyze', difficulty:'medium',
    question:'أي نوع تكرار يُعطي أكبر تنوع بصري؟',
    paragraph:'أنواع التكرار: عادي / متعاكس / متبادل. (ص38)',
    options:[
      {text:'التكرار المتبادل (وحدتان مختلفتان)',correct:true},
      {text:'التكرار العادي (وحدة واحدة)',correct:false},
      {text:'التكرار المتعاكس (وحدة مقلوبة)',correct:false},
      {text:'كلها متساوية في التنوع',correct:false},
    ],
    explanation:'التكرار المتبادل يُعطي أكبر تنوع لأنه يستخدم وحدتين مختلفتين بدلاً من واحدة.',
    goldenRule:'أكثر تنوع = التكرار المتبادل (وحدتان). أبسط = العادي (وحدة واحدة).',
  },
  {
    id:'u2l1q32', unit:'u2', lesson:'u2l1', page:39, type:'trueFalse',
    bloom:'evaluate', difficulty:'medium',
    question:'الزخرفة الإسلامية تجمع بين النباتي والهندسي والخطي في تناسق رائع.',
    paragraph:'أنواع الزخارف: نباتية / هندسية / خطية كتابية. (ص36-39)',
    correctAnswer:true,
    explanation:'الزخرفة الإسلامية تدمج الأنواع الثلاثة في تناسق فريد = قمة الإبداع الفني.',
    goldenRule:'الزخرفة الإسلامية = نباتي + هندسي + خطي = تكامل فني رائع.',
  },
];

export const u2l2_extra = [
  {
    id:'u2l2q9', unit:'u2', lesson:'u2l2', page:43, type:'trueFalse',
    bloom:'remember', difficulty:'easy',
    question:'زخرفة الإطارات هي حصر التعبيرات الزخرفية بين خطين متوازيين.',
    paragraph:'زخرفة الإطارات: وهي حصر التعبيرات الزخرفية بين خطين متوازيين. (ص43)',
    correctAnswer:true,
    explanation:'الإطار الزخرفي = مساحة محصورة بين خطين متوازيين تُملأ بالوحدات الزخرفية.',
    goldenRule:'الإطار الزخرفي = خط علوي + خط سفلي + وحدات بينهما = زخرفة محدودة.',
  },
  {
    id:'u2l2q10', unit:'u2', lesson:'u2l2', page:43, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'زخرفة الإطارات تنقسم إلى:',
    paragraph:'وينقسم إلى: وحدات زخرفية رأسية / وحدات زخرفية أفقية. (ص43)',
    options:[
      {text:'وحدات رأسية + وحدات أفقية',correct:true},
      {text:'وحدات دائرية فقط',correct:false},
      {text:'وحدات مربعة فقط',correct:false},
      {text:'وحدات كبيرة فقط',correct:false},
    ],
    explanation:'نوعان: رأسية (عمودية على الخطين) + أفقية (موازية للخطين).',
    goldenRule:'الإطار: رأسي (عمودي على الخطين) + أفقي (موازٍ للخطين) = نوعان.',
  },
  {
    id:'u2l2q11', unit:'u2', lesson:'u2l2', page:43, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'الوحدة الزخرفية الرأسية تكون عمودية على خطي الإطار.',
    paragraph:'وحدات زخرفية رأسية: وهي ما اتخذت فيه الوحدة اتجاهاً رأسياً وكانت عمودية على خطي الإطار. (ص43)',
    correctAnswer:true,
    explanation:'الوحدة الرأسية تقف عمودياً بين الخطين العلوي والسفلي.',
    goldenRule:'رأسية = عمودية على الخطين. أفقية = موازية للخطين.',
  },
  {
    id:'u2l2q12', unit:'u2', lesson:'u2l2', page:43, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'الوحدة الزخرفية الأفقية تكون موازية لخطي الإطار.',
    paragraph:'وحدات زخرفية أفقية: وهي ما اتخذت فيه الوحدة اتجاهاً أفقياً وكانت موازية لخطي الإطار. (ص43)',
    correctAnswer:true,
    explanation:'الوحدة الأفقية تسير بموازاة الخطين العلوي والسفلي.',
    goldenRule:'أفقية = موازية للخطين. رأسية = عمودية على الخطين.',
  },
  {
    id:'u2l2q13', unit:'u2', lesson:'u2l2', page:44, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'من استخدامات الإطارات الزخرفية في الحياة اليومية:',
    paragraph:'يستفاد منها في حياتنا اليومية في زخرفة غلاف كتاب وأيضاً لزخرفة بطاقات التهنئة ولرسم لوحة جدارية. (ص44)',
    options:[
      {text:'زخرفة غلاف كتاب + بطاقات التهنئة + لوحة جدارية',correct:true},
      {text:'صنع الطعام',correct:false},
      {text:'إصلاح الأجهزة',correct:false},
      {text:'تنظيف المنزل',correct:false},
    ],
    explanation:'الإطارات الزخرفية تُزيّن: أغلفة الكتب + بطاقات التهنئة + اللوحات الجدارية.',
    goldenRule:'الإطار الزخرفي = أغلفة + بطاقات + لوحات = فن تطبيقي نافع.',
  },
  {
    id:'u2l2q14', unit:'u2', lesson:'u2l2', page:44, type:'trueFalse',
    bloom:'apply', difficulty:'easy',
    question:'يمكن استخدام الإطار الزخرفي في تزيين غلاف كتاب.',
    paragraph:'يستفاد منها في حياتنا اليومية في زخرفة غلاف كتاب. (ص44)',
    correctAnswer:true,
    explanation:'غلاف الكتاب المزخرف بإطار جميل يُضفي عليه جمالاً وقيمة.',
    goldenRule:'غلاف كتاب + إطار زخرفي = جمال + احترافية.',
  },
  {
    id:'u2l2q15', unit:'u2', lesson:'u2l2', page:44, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'ما نوع التكرار الأكثر شيوعاً في زخرفة الإطارات؟',
    paragraph:'من أنواع التكرار المستخدمة في الفنون الزخرفية: التكرار المتعاكس. (ص44)',
    options:[
      {text:'التكرار المتعاكس',correct:true},
      {text:'التكرار العشوائي',correct:false},
      {text:'التكرار الفردي',correct:false},
      {text:'التكرار الدائري',correct:false},
    ],
    explanation:'التكرار المتعاكس الأكثر استخداماً في الإطارات لأنه يُعطي توازناً بصرياً.',
    goldenRule:'الإطار الزخرفي = تكرار متعاكس = تقابل = توازن.',
  },
  {
    id:'u2l2q16', unit:'u2', lesson:'u2l2', page:50, type:'multipleChoice',
    bloom:'evaluate', difficulty:'medium',
    question:'في تقويم الوحدة: نرسم الزخارف لنزيّن بها:',
    paragraph:'٣. اختار/ي الإجابة الصحيحة: نرسم الزخارف لنزين بها: أ- الإطارات / ب- الطعام / ج- النباتات. (ص50)',
    options:[
      {text:'الإطارات',correct:true},
      {text:'الطعام',correct:false},
      {text:'النباتات',correct:false},
      {text:'السيارات',correct:false},
    ],
    explanation:'الزخارف تُرسم لتزيين الإطارات — الإجابة (أ) الإطارات.',
    goldenRule:'الزخرفة = تزيين الإطارات. نزخرف الإطارات وليس الطعام أو النباتات.',
  },
  {
    id:'u2l2q17', unit:'u2', lesson:'u2l2', page:49, type:'multipleChoice',
    bloom:'analyze', difficulty:'medium',
    question:'الزخرفة التي تستمد وحداتها من النبات تُسمى:',
    paragraph:'١. اكتب/ي نوع الزخرفة أسفل الصورة، مستعيناً بالكلمات: نباتية - هندسية - كتابية. (ص49)',
    options:[
      {text:'زخرفة نباتية',correct:true},
      {text:'زخرفة هندسية',correct:false},
      {text:'زخرفة كتابية',correct:false},
      {text:'زخرفة شعبية',correct:false},
    ],
    explanation:'مصدر الوحدة = نبات → زخرفة نباتية. مصدرها = شكل رياضي → هندسية. مصدرها = خط → كتابية.',
    goldenRule:'عرف نوع الزخرفة من مصدر وحدتها: نبات=نباتية، شكل=هندسية، خط=كتابية.',
  },
  {
    id:'u2l2q18', unit:'u2', lesson:'u2l2', page:49, type:'matching',
    bloom:'understand', difficulty:'medium',
    question:'صِل كل نوع تكرار بوصفه:',
    paragraph:'٢. اكتب/ي نوع التكرار أسفل كل صورة: متعاكس - متبادل - عادي. (ص49)',
    pairs:[
      {left:'★★★★ (ثابت)',right:'عادي'},
      {left:'♡△♡△ (وحدتان)',right:'متبادل'},
      {left:'☽✦☽✦ (متعاكس)',right:'متعاكس'},
    ],
    explanation:'ثابت=عادي. وحدتان=متبادل. مقلوب=متعاكس.',
    goldenRule:'عرف التكرار: ثابت=عادي، وحدتان=متبادل، مقلوب=متعاكس.',
  },
  {
    id:'u2l2q19', unit:'u2', lesson:'u2l2', page:43, type:'fillBlank',
    bloom:'remember', difficulty:'easy',
    question:'أكمل: "زخرفة الإطارات هي ___ التعبيرات الزخرفية بين خطين متوازيين."',
    paragraph:'زخرفة الإطارات: وهي حصر التعبيرات الزخرفية بين خطين متوازيين. (ص43)',
    blanks:['حصر'],
    wordBank:['حصر','نشر','حذف','تكبير'],
    explanation:'الإطار الزخرفي = حصر الزخرفة بين خطين متوازيين.',
    goldenRule:'الإطار = حصر + خطان متوازيان = زخرفة محدودة وجميلة.',
  },
  {
    id:'u2l2q20', unit:'u2', lesson:'u2l2', page:43, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف وحدات الإطار الزخرفي:',
    paragraph:'وحدات زخرفية رأسية / وحدات زخرفية أفقية. (ص43)',
    categories:['وحدات رأسية (عمودية على الخطين)','وحدات أفقية (موازية للخطين)'],
    items:[
      {text:'زهرة واقفة بين الخطين',correct_category:0},
      {text:'سهم صاعد عمودي',correct_category:0},
      {text:'شريط زخرفي ممتد أفقياً',correct_category:1},
      {text:'خط متموّج موازٍ للإطار',correct_category:1},
    ],
    explanation:'رأسية: عمودية على الخطين (واقفة). أفقية: موازية للخطين (ممدودة).',
    goldenRule:'رأسي=واقف عمودي، أفقي=ممدود موازٍ. حسب اتجاه الوحدة بين الخطين.',
  },
  {
    id:'u2l2q21', unit:'u2', lesson:'u2l2', page:44, type:'trueFalse',
    bloom:'evaluate', difficulty:'medium',
    question:'الإطارات الزخرفية تتميز بأشكال جمالية مبتكرة ومتنوعة.',
    paragraph:'تتميز الإطارات الزخرفية بأشكال جمالية مبتكرة ومتنوعة. (ص44)',
    correctAnswer:true,
    explanation:'الإطارات الزخرفية متنوعة ومبتكرة — كل إطار له أسلوبه وشكله الجمالي الفريد.',
    goldenRule:'الإطار الزخرفي = ابتكار + تنوع = جمال لا يتكرر.',
  },
  {
    id:'u2l2q22', unit:'u2', lesson:'u2l2', page:44, type:'multipleChoice',
    bloom:'apply', difficulty:'easy',
    question:'ما الذي يمكن تزيينه بالإطار الزخرفي؟',
    paragraph:'في زخرفة غلاف كتاب وأيضاً لزخرفة بطاقات التهنئة ولرسم لوحة جدارية. (ص44)',
    options:[
      {text:'غلاف كتاب + بطاقة تهنئة + لوحة جدارية',correct:true},
      {text:'الطعام في المطبخ',correct:false},
      {text:'السيارة',correct:false},
      {text:'الحديقة فقط',correct:false},
    ],
    explanation:'3 استخدامات: غلاف كتاب + بطاقة تهنئة + لوحة جدارية.',
    goldenRule:'الإطار الزخرفي = 3 استخدامات: أغلفة + بطاقات + لوحات جدارية.',
  },
  {
    id:'u2l2q23', unit:'u2', lesson:'u2l2', page:46, type:'trueFalse',
    bloom:'apply', difficulty:'easy',
    question:'الزخارف النباتية موجودة في كثير من الأشياء حولنا.',
    paragraph:'الزخارف النباتية نلاحظها في كثير من الأشياء حولنا. (ص40)',
    correctAnswer:true,
    explanation:'الزخرفة النباتية منتشرة: أقمشة + أوانٍ + أثاث + أغلفة + مبانٍ.',
    goldenRule:'الزخرفة النباتية = في كل مكان. افتح عينيك وستجدها حولك.',
  },
  {
    id:'u2l2q24', unit:'u2', lesson:'u2l2', page:43, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'ما الفرق بين الوحدة الرأسية والأفقية في الإطار الزخرفي؟',
    paragraph:'وحدات زخرفية رأسية... عمودية على خطي الإطار. وحدات زخرفية أفقية... موازية لخطي الإطار. (ص43)',
    options:[
      {text:'الرأسية عمودية على الخطين، والأفقية موازية لهما',correct:true},
      {text:'الرأسية أكبر حجماً',correct:false},
      {text:'الأفقية أجمل',correct:false},
      {text:'لا فرق بينهما',correct:false},
    ],
    explanation:'الاتجاه هو الفرق: رأسي=عمودي، أفقي=موازٍ. كلاهما بين الخطين.',
    goldenRule:'رأسي=عمودي على الخطين. أفقي=موازٍ لهما. الاتجاه هو الفرق.',
  },
  {
    id:'u2l2q25', unit:'u2', lesson:'u2l2', page:44, type:'multipleChoice',
    bloom:'create', difficulty:'hard',
    question:'لو أردت تصميم إطار زخرفي لبطاقة تهنئة، ما نوع التكرار الذي تختار؟',
    paragraph:'من أنواع التكرار المستخدمة في الفنون الزخرفية: التكرار المتعاكس. (ص44)',
    options:[
      {text:'التكرار المتعاكس (للتوازن البصري)',correct:true},
      {text:'التكرار العشوائي',correct:false},
      {text:'لا أستخدم تكراراً',correct:false},
      {text:'التكرار الدائري',correct:false},
    ],
    explanation:'التكرار المتعاكس يُعطي توازناً بصرياً جميلاً مناسباً لبطاقات التهنئة.',
    goldenRule:'بطاقة تهنئة + تكرار متعاكس = توازن + جمال = احترافية.',
  },
  {
    id:'u2l2q26', unit:'u2', lesson:'u2l2', page:49, type:'trueFalse',
    bloom:'evaluate', difficulty:'medium',
    question:'في تقويم الوحدة: نرسم الزخارف لنزين بها الإطارات وليس الطعام.',
    paragraph:'نرسم الزخارف لنزين بها: أ- الإطارات / ب- الطعام / ج- النباتات. (ص50)',
    correctAnswer:true,
    explanation:'الزخرفة تُزيّن الإطارات والأشياء الجامدة، وليس الطعام أو النباتات الحية.',
    goldenRule:'الزخرفة = تزيين الإطارات والأسطح. لا تُزيّن الطعام أو الكائنات الحية.',
  },
  {
    id:'u2l2q27', unit:'u2', lesson:'u2l2', page:50, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'كم نوعاً لوحدات الإطار الزخرفي؟',
    paragraph:'ينقسم إلى: وحدات زخرفية رأسية / وحدات زخرفية أفقية. (ص43)',
    options:[
      {text:'نوعان: رأسية وأفقية',correct:true},
      {text:'نوع واحد',correct:false},
      {text:'ثلاثة أنواع',correct:false},
      {text:'أربعة أنواع',correct:false},
    ],
    explanation:'نوعان فقط: رأسية + أفقية.',
    goldenRule:'وحدات الإطار = 2: رأسية + أفقية. نوعان فقط.',
  },
  {
    id:'u2l2q28', unit:'u2', lesson:'u2l2', page:44, type:'fillBlank',
    bloom:'apply', difficulty:'easy',
    question:'أكمل: "تتميز الإطارات الزخرفية بأشكال جمالية ___ ومتنوعة."',
    paragraph:'تتميز الإطارات الزخرفية بأشكال جمالية مبتكرة ومتنوعة. (ص44)',
    blanks:['مبتكرة'],
    wordBank:['مبتكرة','قديمة','بسيطة','متكررة'],
    explanation:'الإطارات الزخرفية مبتكرة = جديدة وإبداعية في تصاميمها.',
    goldenRule:'الإطار الزخرفي = ابتكار + تنوع = جديد ومبدع في كل مرة.',
  },
  {
    id:'u2l2q29', unit:'u2', lesson:'u2l2', page:49, type:'multipleChoice',
    bloom:'analyze', difficulty:'medium',
    question:'إذا كانت وحدات الزخرفة أوراق أشجار منمّقة، فما نوعها؟',
    paragraph:'١. اكتب/ي نوع الزخرفة... مستعيناً بالكلمات: نباتية - هندسية - كتابية. (ص49)',
    options:[
      {text:'زخرفة نباتية',correct:true},
      {text:'زخرفة هندسية',correct:false},
      {text:'زخرفة كتابية',correct:false},
      {text:'زخرفة حيوانية',correct:false},
    ],
    explanation:'مصدر الوحدة = أوراق أشجار = نبات → زخرفة نباتية.',
    goldenRule:'مصدر الوحدة نباتي → زخرفة نباتية. ابحث عن مصدر الوحدة.',
  },
  {
    id:'u2l2q30', unit:'u2', lesson:'u2l2', page:43, type:'trueFalse',
    bloom:'remember', difficulty:'easy',
    question:'الإطار الزخرفي محصور بين خطين متوازيين.',
    paragraph:'وهي حصر التعبيرات الزخرفية بين خطين متوازيين. (ص43)',
    correctAnswer:true,
    explanation:'الإطار = بين خطين متوازيين (علوي + سفلي) تحصر الوحدات الزخرفية بينهما.',
    goldenRule:'الإطار = خطان متوازيان + وحدات بينهما = حصر زخرفي.',
  },
  {
    id:'u2l2q31', unit:'u2', lesson:'u2l2', page:44, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'لماذا يُعدّ التكرار المتعاكس الأنسب لزخرفة الإطارات؟',
    paragraph:'من أنواع التكرار المستخدمة في الفنون الزخرفية: التكرار المتعاكس. (ص44)',
    options:[
      {text:'لأن التقابل بين الوحدات يُعطي توازناً بصرياً في المساحة الضيقة بين الخطين',correct:true},
      {text:'لأنه الأسهل في الرسم',correct:false},
      {text:'لأنه الوحيد المتاح',correct:false},
      {text:'لا سبب محدد',correct:false},
    ],
    explanation:'المساحة بين الخطين ضيقة والتقابل يُوازن الوحدات بشكل جميل فيها.',
    goldenRule:'الإطار ضيق + تكرار متعاكس = تقابل = توازن في مساحة محدودة.',
  },
  {
    id:'u2l2q32', unit:'u2', lesson:'u2l2', page:49, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'الزخرفة الهندسية تستمد وحداتها من الأشكال الرياضية.',
    paragraph:'الكلمات: نباتية - هندسية - كتابية. (ص49)',
    correctAnswer:true,
    explanation:'الزخرفة الهندسية = مثلثات + مربعات + دوائر + نجوم + مضلعات.',
    goldenRule:'هندسية = أشكال رياضية. نباتية = نباتات. كتابية = خطوط.',
  },
];

export const u2_extra = [...u2l1_extra, ...u2l2_extra];