// بنك بلوم — اللغة العربية
// ٦٦ سؤالاً موزّعة على الصفوف ١-٦ ومستويات بلوم الستة
// المواضيع: النحو، الإملاء، الفهم القرائي، البلاغة، الإعراب

export const BLOOM_ARABIC = [
  // ════ الصف الأول (١١) ════
  { grade: 1, bloom: 'remember', subject: 'arabic', topic_ar: 'الحروف', question_ar: 'كم عدد حروف اللغة العربية؟', options_ar: ['٢٨ حرفاً', '٣٠ حرفاً', '٢٥ حرفاً', '٣٢ حرفاً'], correct_answer: '0', explanation_ar: 'حروف اللغة العربية ٢٨ حرفاً.', image_key: null },
  { grade: 1, bloom: 'remember', subject: 'arabic', topic_ar: 'أنواع الكلمة', question_ar: 'كم نوعاً للكلمة في العربية؟', options_ar: ['ثلاثة: اسم وفعل وحرف', 'خمسة', 'اثنان', 'أربعة'], correct_answer: '0', explanation_ar: 'أنواع الكلمة ثلاثة: اسم، فعل، حرف.', image_key: null },
  { grade: 1, bloom: 'understand', subject: 'arabic', topic_ar: 'الجملة', question_ar: 'ما الجملة المفيدة؟', options_ar: ['التي تفيد معنى تاماً كـ«جاء محمدٌ»', 'كلمة واحدة', 'حرف واحد', 'لا شيء'], correct_answer: '0', explanation_ar: 'الجملة المفيدة ما تم المعنى بها كـ«جاء محمدٌ».', image_key: null },
  { grade: 1, bloom: 'understand', subject: 'arabic', topic_ar: 'الاسم والفعل', question_ar: 'ما الفرق بين الاسم والفعل؟', options_ar: ['الفعل يدل على حدثٍ في زمنٍ والاسم لا', 'لا فرق', 'الاسم للماضي والفعل للمستقبل', 'الاسم أكبر'], correct_answer: '0', explanation_ar: 'الفعل يدل على حدثٍ مقترنٍ بزمن، والاسم لا يقترن بزمن.', image_key: null },
  { grade: 1, bloom: 'apply', subject: 'arabic', topic_ar: 'تكوين الجملة', question_ar: 'ككِّن جملةً من كلمة «محمد» و«جاء»', options_ar: ['جاء محمدٌ', 'محمد جاء', 'جاء جاء', 'محمد محمد'], correct_answer: '0', explanation_ar: 'الجملة: «جاء محمدٌ» فعل + فاعل، جملةٌ مفيدة.', image_key: null },
  { grade: 1, bloom: 'apply', subject: 'arabic', topic_ar: 'المذكر والمؤنث', question_ar: 'ما مؤنث كلمة «أستاذ»؟', options_ar: ['أستاذة', 'أستاذون', 'أستاذان', 'أستاذٌ'], correct_answer: '0', explanation_ar: 'مؤنث «أستاذ»: أستاذة، بتاء التأنيث.', image_key: null },
  { grade: 1, bloom: 'analyze', subject: 'arabic', topic_ar: 'الحروف', question_ar: 'أيُّ حرفٍ يُكتب ويرسم ولا يُنطق في وسط الكلمة؟', options_ar: ['الألف في «قال»', 'الباء', 'التاء', 'السين'], correct_answer: '0', explanation_ar: 'الألف في «قال» تُكتب ولا تُنطق وقفاً.', image_key: null },
  { grade: 1, bloom: 'analyze', subject: 'arabic', topic_ar: 'المفرد والجمع', question_ar: 'ما الفرق بين المفرد والجمع؟', options_ar: ['المفرد يدل على واحد والجمع على ثلاثة فأكثر', 'لا فرق', 'المفرد أكثر', 'الجمع واحد'], correct_answer: '0', explanation_ar: 'المفرد يدل على واحد، والجمع يدل على ثلاثة فأكثر.', image_key: null },
  { grade: 1, bloom: 'evaluate', subject: 'arabic', topic_ar: 'الجملة', question_ar: ['أيُّ جملةٍ صحيحة؟', 'أي جملة صحيحة؟'], correct_answer: '0', options_ar: ['كتب الولدُ الدرسَ', 'كتب الولد الدرس', 'كتب الولدٌ الدرسٌ', 'كتب الولد الدرسٌ'], explanation_ar: '«كتب الولدُ الدرسَ»: فعل + فاعل مرفوع + مفعول منصوب، إعراب صحيح.', image_key: null },
  { grade: 1, bloom: 'evaluate', subject: 'arabic', topic_ar: 'الإملاء', question_ar: 'أيُّ كلمةٍ مكتوبةٌ correctly؟', options_ar: ['كِتاب', 'كتااب', 'كتابْ', 'كتاَب'], correct_answer: '0', explanation_ar: '«كِتاب» بالكسرة تحت الكاف هي الكتابة الصحيحة.', image_key: null },
  { grade: 1, bloom: 'create', subject: 'arabic', topic_ar: 'الكتابة', question_ar: 'اكتب جملةً عن نفسك', options_ar: ['أنا طالبٌ مجتهدٌ', 'طالب', 'مجتهد', 'أنا'], correct_answer: '0', explanation_ar: '«أنا طالبٌ مجتهدٌ»: مبتدأ + خبر، جملة مفيدة عن النفس.', image_key: null },

  // ════ الصف الثاني (١١) ════
  { grade: 2, bloom: 'remember', subject: 'arabic', topic_ar: 'الضمائر', question_ar: 'أيٌّ من هذه ضميرٌ منفصل؟', options_ar: ['هو', 'كتب', 'في', 'مال'], correct_answer: '0', explanation_ar: '«هو» ضميرٌ منفصلٌ للغائب، أما «كتب» فعل و«في» حرف.', image_key: null },
  { grade: 2, bloom: 'remember', subject: 'arabic', topic_ar: 'المذكر والمؤنث', question_ar: 'كيف نُؤنث كلمة «كاتب»؟', options_ar: ['بإضافة تاء التأنيث: كاتبة', 'بزيادة ألف', 'بتضاعف الحرف', 'لا يُؤنث'], correct_answer: '0', explanation_ar: 'نُؤنث «كاتب» بتاء التأنيث المربوطة: «كاتبة».', image_key: null },
  { grade: 2, bloom: 'understand', subject: 'arabic', topic_ar: 'الفعل', question_ar: 'ما الفعل الماضي؟', options_ar: ['ما دل على حدثٍ وقع وانتهى قبل زمن التكلم', 'ما يحدث الآن', 'ما سيحدث', 'ما لم يحدث'], correct_answer: '0', explanation_ar: 'الفعل الماضي ما دل على حدثٍ وقع وانتهى قبل زمن التكلم.', image_key: null },
  { grade: 2, bloom: 'understand', subject: 'arabic', topic_ar: 'الاسم', question_ar: 'ما علامة الاسم في جملة «جاء محمدٌ»؟', options_ar: ['التنوين بالضمة', 'السكون', 'الفتحة', 'الكسرة'], correct_answer: '0', explanation_ar: '«محمدٌ» اسمٌ مرفوعٌ بالضمة وعلامتها التنوين بالضم.', image_key: null },
  { grade: 2, bloom: 'apply', subject: 'arabic', topic_ar: 'الضمائر', question_ar: 'ضع ضميراً مناسباً: ____ مجتهدٌ', options_ar: ['هو', 'هي', 'هما', 'هم'], correct_answer: '0', explanation_ar: '«هو مجتهدٌ»: الضمير «هو» للمذكر المفرد الغائب.', image_key: null },
  { grade: 2, bloom: 'apply', subject: 'arabic', topic_ar: 'التأنيث', question_ar: 'حوّل جملة «المعلمُ شرحَ» للمؤنث', options_ar: ['المعلمةُ شرحتْ', 'المعلمُ شرحتْ', 'المعلمةُ شرحَ', 'المعلمون شرحوا'], correct_answer: '0', explanation_ar: '«المعلمةُ شرحتْ»: نؤنث الاسم بتاء ونؤنث الفعل بتاء التأنيث الساكنة.', image_key: null },
  { grade: 2, bloom: 'analyze', subject: 'arabic', topic_ar: 'الأزمنة', question_ar: 'ما الفرق بين «كتب» و«يكتب»؟', options_ar: ['«كتب» للماضي و«يكتب» للمضارع', 'لا فرق', 'كلاهما للماضي', 'كلاهما للمستقبل'], correct_answer: '0', explanation_ar: '«كتب» فعل ماضٍ و«يكتب» فعل مضارع للحاضر أو المستقبل.', image_key: null },
  { grade: 2, bloom: 'analyze', subject: 'arabic', topic_ar: 'الجمع', question_ar: 'ما الفرق بين جمع المذكر السالم وجمع المؤنث السالم؟', options_ar: ['المذكر بواو ونون والمؤنث بألف وتاء', 'لا فرق', 'كلاهما بألف', 'كلاهما بواو'], correct_answer: '0', explanation_ar: 'جمع المذكر السالم بواو ونون، وجمع المؤنث السالم بألف وتاء.', image_key: null },
  { grade: 2, bloom: 'evaluate', subject: 'arabic', topic_ar: 'الجملة', question_ar: 'أيُّ جملةٍ صحيحة إعراباً؟', options_ar: ['المعلمُ يشرحُ الدرسَ', 'المعلمِ يشرحِ الدرسِ', 'المعلمَ يشرحَ الدرسُ', 'المعلمْ يشرحْ الدرسْ'], correct_answer: '0', explanation_ar: '«المعلمُ يشرحُ الدرسَ»: مبتدأ مرفوع + فعل مرفوع + مفعول منصوب.', image_key: null },
  { grade: 2, bloom: 'evaluate', subject: 'arabic', topic_ar: 'الإملاء', question_ar: 'أيُّ كلمةٍ مكتوبةٌ صحيحة؟', options_ar: ['هذا', 'هاذا', 'هذها', 'هذَها'], correct_answer: '0', explanation_ar: '«هذا» اسم إشارة للمذكر، تكتب بلا ألف بعد الهاء.', image_key: null },
  { grade: 2, bloom: 'create', subject: 'arabic', topic_ar: 'القصة', question_ar: 'اكتب قصةً قصيرةً في جملتين', options_ar: ['خرج الطفلُ يلعبُ، فجاءَ الليلُ فعادَ إلى بيتِهِ', 'طفل', 'لعب', 'ليل'], correct_answer: '0', explanation_ar: 'القصة: بداية + حدث + نهاية، في جملتين متصلتين.', image_key: null },

  // ════ الصف الثالث (١١) ════
  { grade: 3, bloom: 'remember', subject: 'arabic', topic_ar: 'أنواع الفعل', question_ar: 'كم نوعاً للفعل؟', options_ar: ['ثلاثة: ماضٍ ومضارع وأمر', 'خمسة', 'اثنان', 'أربعة'], correct_answer: '0', explanation_ar: 'الفعل ثلاثة أنواع: ماضٍ ومضارع وأمر.', image_key: null },
  { grade: 3, bloom: 'remember', subject: 'arabic', topic_ar: 'المبتدأ والخبر', question_ar: 'ما المبتدأ والخبر؟', options_ar: ['المبتدأ اسمٌ مرفوعٌ في أول الجملة والخبر يتم المعنى', 'الخبر في الأول', 'لا يوجد', 'كلاهما منصوب'], correct_answer: '0', explanation_ar: 'المبتدأ اسمٌ مرفوعٌ يبتدأ به، والخبر يتم معناه ويكون مرفوعاً.', image_key: null },
  { grade: 3, bloom: 'understand', subject: 'arabic', topic_ar: 'الإعراب', question_ar: 'ما الإعراب؟', options_ar: ['تغيير أواخر الكلمات بتغير موقعها في الجملة', 'كتابة الكلمات', 'قراءة النص', 'حفظ القصيدة'], correct_answer: '0', explanation_ar: 'الإعراب: تغير أواخر الكلمات بحسب موقعها في الجملة.', image_key: null },
  { grade: 3, bloom: 'understand', subject: 'arabic', topic_ar: 'اللام الشمسية والقمرية', question_ar: 'ما الفرق بين اللام الشمسية والقمرية؟', options_ar: ['الشمسية تُدغم وتُكتب ولا تُنطق، والقمرية تُنطق', 'لا فرق', 'كلاهما تُنطق', 'الشمسية تُنطق والقمرية لا'], correct_answer: '0', explanation_ar: 'الشمسية: تكتب وتُدغم ولا تنطق (الشمس). القمرية: تنطق (القمر).', image_key: null },
  { grade: 3, bloom: 'apply', subject: 'arabic', topic_ar: 'الإعراب', question_ar: 'أعرب: «الكتابُ مفيدٌ»', options_ar: ['الكتابُ: مبتدأ مرفوع، مفيدٌ: خبر مرفوع', 'الكتابُ: مفعول، مفيدٌ: فاعل', 'كلاهما منصوب', 'كلاهما مجرور'], correct_answer: '0', explanation_ar: '«الكتابُ» مبتدأ مرفوع بالضمة، و«مفيدٌ» خبر مرفوع بالضمة.', image_key: null },
  { grade: 3, bloom: 'apply', subject: 'arabic', topic_ar: 'اللام', question_ar: 'أيُّ كلمةٍ فيها لامٌ قمرية؟', options_ar: ['القمر', 'الشمس', 'الصباح', 'الضوء'], correct_answer: '0', explanation_ar: '«القمر» لامه قمرية تُنطق، لأن القاف من حروف القمرية.', image_key: null },
  { grade: 3, bloom: 'analyze', subject: 'arabic', topic_ar: 'الفعل', question_ar: 'ما علامة إعراب الفعل المضارع؟', options_ar: ['الرفع بالضمة والنصب بالفتحة والجزم بالسكون', 'الضمة فقط', 'الفتحة دائماً', 'السكون دائماً'], correct_answer: '0', explanation_ar: 'المضارع يرفع بالضمة وينصب بالفتحة بعد حرف النصب ويجزم بالسكون.', image_key: null },
  { grade: 3, bloom: 'analyze', subject: 'arabic', topic_ar: 'أنواع الفعل', question_ar: 'ما الفرق بين الفعل الأمر والماضي؟', options_ar: ['الأمر طلبٌ للفعل في المستقبل والماضي حدثٌ انتهى', 'لا فرق', 'كلاهما للماضي', 'كلاهما للمستقبل'], correct_answer: '0', explanation_ar: 'الأمر: طلبٌ لوقوع الفعل بعد التكلم. الماضي: حدثٌ وقع قبل التكلم.', image_key: null },
  { grade: 3, bloom: 'evaluate', subject: 'arabic', topic_ar: 'الإعراب', question_ar: 'أيُّ إعرابٍ صحيحٍ لجملة «كتب الطالبُ الدرسَ»؟', options_ar: ['كتب: فعل ماضٍ، الطالبُ: فاعل مرفوع، الدرسَ: مفعول منصوب', 'كتب: فاعل، الطالبُ: مفعول', 'الدرسَ: فاعل', 'كلها مرفوعة'], correct_answer: '0', explanation_ar: 'الإعراب الصحيح: فعل + فاعل مرفوع + مفعول منصوب.', image_key: null },
  { grade: 3, bloom: 'evaluate', subject: 'arabic', topic_ar: 'الإملاء', question_ar: 'أيُّ كتابةٍ صحيحة لكلمة «سماء»؟', options_ar: ['سماء', 'سماءْ', 'سماا', 'سماءَ'], correct_answer: '0', explanation_ar: '«سماء» تكتب بهمزة على الألف في آخر الكلمة.', image_key: null },
  { grade: 3, bloom: 'create', subject: 'arabic', topic_ar: 'الكتابة', question_ar: 'اكتب فقرةً من ثلاث جملٍ عن الصباح', options_ar: ['طلع الصباحُ، غردَ العصفورُ، انطلقَ الطفلُ إلى مدرستِهِ', 'صباح', 'طلع', 'انطلق'], correct_answer: '0', explanation_ar: 'الفقرة: ثلاث جملٍ مترابطةٍ تصف مشهداً واحداً.', image_key: null },

  // ════ الصف الرابع (١١) ════
  { grade: 4, bloom: 'remember', subject: 'arabic', topic_ar: 'الفاعل', question_ar: 'ما الفاعل؟', options_ar: ['اسمٌ مرفوعٌ يقع بعد الفعل ويقوم به الحدث', 'اسمٌ منصوب', 'حرف', 'فعل'], correct_answer: '0', explanation_ar: 'الفاعل: اسمٌ مرفوعٌ يأتي بعد الفعل ويقوم بالفعل.', image_key: null },
  { grade: 4, bloom: 'remember', subject: 'arabic', topic_ar: 'المفعول به', question_ar: 'ما المفعول به؟', options_ar: ['اسمٌ منصوبٌ يقع عليه فعل الفاعل', 'اسمٌ مرفوع', 'فعل ماضٍ', 'حرف جر'], correct_answer: '0', explanation_ar: 'المفعول به: اسمٌ منصوبٌ يقع عليه فعل الفاعل.', image_key: null },
  { grade: 4, bloom: 'understand', subject: 'arabic', topic_ar: 'اسم الإشارة', question_ar: 'ما اسم الإشارة للبعيد المثنى؟', options_ar: ['ذانك', 'هذا', 'هذه', 'أولئك'], correct_answer: '0', explanation_ar: '«ذانك» اسم إشارة للمثنى المذكر البعيد.', image_key: null },
  { grade: 4, bloom: 'understand', subject: 'arabic', topic_ar: 'الموصولات', question_ar: 'ما الاسم الموصول للمفرد المذكر؟', options_ar: ['الذي', 'التي', 'الذين', 'اللاتي'], correct_answer: '0', explanation_ar: '«الذي» اسم موصول للمفرد المذكر العاقل.', image_key: null },
  { grade: 4, bloom: 'apply', subject: 'arabic', topic_ar: 'اسم الإشارة', question_ar: 'ضع اسم إشارة مناسباً: ____ طالبةٌ مجتهدةٌ', options_ar: ['هذه', 'هذا', 'ذانك', 'أولئك'], correct_answer: '0', explanation_ar: '«هذه» اسم إشارة للمفردة المؤنثة القريب.', image_key: null },
  { grade: 4, bloom: 'apply', subject: 'arabic', topic_ar: 'الإعراب', question_ar: 'أعرب: «أكلَ الولدُ التفاحةَ»', options_ar: ['أكلَ: فعل ماضٍ، الولدُ: فاعل مرفوع، التفاحةَ: مفعول منصوب', 'أكلَ: فاعل، الولدُ: مفعول', 'التفاحةَ: فاعل', 'كلها مرفوعة'], correct_answer: '0', explanation_ar: '«أكل» فعل ماضٍ، «الولدُ» فاعل مرفوع، «التفاحةَ» مفعول منصوب.', image_key: null },
  { grade: 4, bloom: 'analyze', subject: 'arabic', topic_ar: 'الفاعل والمفعول', question_ar: 'ما الفرق بين الفاعل والمفعول به؟', options_ar: ['الفاعل مرفوع يقوم بالفعل والمفعول منصوب يقع عليه الفعل', 'لا فرق', 'كلاهما مرفوع', 'كلاهما منصوب'], correct_answer: '0', explanation_ar: 'الفاعل مرفوع وهو من قام بالفعل، والمفعول منصوب وهو من وقع عليه.', image_key: null },
  { grade: 4, bloom: 'analyze', subject: 'arabic', topic_ar: 'الموصولات', question_ar: 'ما الفرق بين «الذي» و«الذين»؟', options_ar: ['«الذي» للمفرد و«الذين» للجمع', 'لا فرق', 'كلاهما للجمع', 'كلاهما للمفرد'], correct_answer: '0', explanation_ar: '«الذي» للمفرد المذكر و«الذين» لجمع المذكر.', image_key: null },
  { grade: 4, bloom: 'evaluate', subject: 'arabic', topic_ar: 'الإعراب', question_ar: 'أيُّ إعرابٍ صحيحٍ لـ«نصرَ اللهُ المؤمنينَ»؟', options_ar: ['نصرَ: فعل ماضٍ، اللهُ: فاعل مرفوع، المؤمنينَ: مفعول منصوب', 'نصرَ: فاعل، اللهُ: مفعول', 'المؤمنينَ: فاعل', 'كلها مرفوعة'], correct_answer: '0', explanation_ar: '«نصر» فعل ماضٍ، «اللهُ» فاعل مرفوع، «المؤمنينَ» مفعول منصوب بالياء.', image_key: null },
  { grade: 4, bloom: 'evaluate', subject: 'arabic', topic_ar: 'الهمزة', question_ar: 'أيُّ كتابةٍ صحيحةٍ لهمزةٍ وسط الكلمة؟', options_ar: ['مُقْتَرِئ', 'مقتَرِء', 'مقتَرئْ', 'مقتَرِئَ'], correct_answer: '0', explanation_ar: 'الهمزة على نبرة (ئ) إذا سبقها كسر، كـ«مقتَرِئ».', image_key: null },
  { grade: 4, bloom: 'create', subject: 'arabic', topic_ar: 'النص الوصفي', question_ar: 'اكتب نصاً وصفيّاً قصيراً عن مدينتك', options_ar: ['مدينتي جميلةٌ، شوارعُها نظيفةٌ، وأهلُها كرماءُ', 'مدينة', 'جميلة', 'أهل'], correct_answer: '0', explanation_ar: 'النص الوصفي: جملٌ متتابعةٌ تصف الموصوف بصفاته.', image_key: null },

  // ════ الصف الخامس (١١) ════
  { grade: 5, bloom: 'remember', subject: 'arabic', topic_ar: 'كان وأخواتها', question_ar: 'ماذا تفعل «كان» وأخواتها بالاسم والخبر؟', options_ar: ['ترفع المبتدأ وينصب الخبر', 'تنصب المبتدأ وترفع الخبر', 'تجزم المبتدأ', 'لا تفعل شيئاً'], correct_answer: '0', explanation_ar: '«كان» وأخواتها ترفع المبتدأ (اسمها) وتنصب الخبر (خبرها).', image_key: null },
  { grade: 5, bloom: 'remember', subject: 'arabic', topic_ar: 'إن وأخواتها', question_ar: 'أيٌّ من هذه من أخوات «إن»؟', options_ar: ['أنَّ - كأنَّ - لكنَّ', 'كان - أصبح - أضحى', 'ظنَّ - حسب - زعم', 'إلا - لعل'], correct_answer: '0', explanation_ar: 'أخوات «إن»: أنَّ، كأنَّ، لكنَّ، لعلَّ، ليت.', image_key: null },
  { grade: 5, bloom: 'understand', subject: 'arabic', topic_ar: 'التشبيه', question_ar: 'ما التشبيه في البلاغة؟', options_ar: ['تشبيه شيءٍ بشيءٍ لبيان صفةٍ فيه', 'سرد قصة', 'كتابة شعر', 'إعراب جملة'], correct_answer: '0', explanation_ar: 'التشبيه: عقد مماثلة بين شيئين لبيان صفة المشبه به.', image_key: null },
  { grade: 5, bloom: 'understand', subject: 'arabic', topic_ar: 'إن وأخواتها', question_ar: 'ماذا تفعل «إنَّ» وأخواتها؟', options_ar: ['تنصب المبتدأ وترفع الخبر', 'ترفع المبتدأ وتنصب الخبر', 'تجزم المبتدأ', 'لا تفعل شيئاً'], correct_answer: '0', explanation_ar: '«إنَّ» وأخواتها تنصب المبتدأ (اسمها) وترفع الخبر (خبرها).', image_key: null },
  { grade: 5, bloom: 'apply', subject: 'arabic', topic_ar: 'كان وأخواتها', question_ar: 'أدخل «كان» على جملة «العلمُ نورٌ»', options_ar: ['كان العلمُ نوراً', 'كان العلمِ نورٌ', 'كان العلمَ نورُ', 'كان العلمْ نورْ'], correct_answer: '0', explanation_ar: '«كان العلمُ نوراً»: كان + اسمها مرفوع + خبرها منصوب.', image_key: null },
  { grade: 5, bloom: 'apply', subject: 'arabic', topic_ar: 'إن وأخواتها', question_ar: 'أدخل «إنَّ» على جملة «الصبرُ مفتاحُ الفرج»', options_ar: ['إنَّ الصبرَ مفتاحُ الفرجِ', 'إنَّ الصبرُ مفتاحَ الفرجِ', 'إنَّ الصبرِ مفتاحْ الفرج', 'إنَّ الصبرْ مفتاحْ الفرج'], correct_answer: '0', explanation_ar: '«إنَّ الصبرَ مفتاحُ الفرج»: إن + اسمها منصوب + خبرها مرفوع.', image_key: null },
  { grade: 5, bloom: 'analyze', subject: 'arabic', topic_ar: 'كان وإن', question_ar: 'ما الفرق بين «كان» و«إنَّ» في عملها؟', options_ar: ['كان ترفع الاسم وتنصب الخبر وإنَّ تنصب الاسم وترفع الخبر', 'لا فرق', 'كلاهما يرفع الاسم', 'كلاهما ينصب الاسم'], correct_answer: '0', explanation_ar: 'كان: ترفع المبتدأ وتنصب الخبر. إن: تنصب المبتدأ وترفع الخبر.', image_key: null },
  { grade: 5, bloom: 'analyze', subject: 'arabic', topic_ar: 'أركان التشبيه', question_ar: 'ما أركان التشبيه الأربعة؟', options_ar: ['المشبه والمشبه به وأداة التشبيه ووجه الشبه', 'الاسم والفعل والحرف', 'المبتدأ والخبر والفاعل والمفعول', 'لا أركان'], correct_answer: '0', explanation_ar: 'أركان التشبيه: المشبه، المشبه به، أداة التشبيه، وجه الشبه.', image_key: null },
  { grade: 5, bloom: 'evaluate', subject: 'arabic', topic_ar: 'التشبيه', question_ar: 'أيُّ جملةٍ فيها تشبيهٌ تامٌّ؟', options_ar: ['المؤمنُ كالأسدِ في شجاعته', 'المؤمنُ شجاعٌ', 'الأسدُ قويٌّ', 'المؤمنُ يصلي'], correct_answer: '0', explanation_ar: '«المؤمنُ كالأسدِ في شجاعته»: مشبه + أداة + مشبه به + وجه الشبه.', image_key: null },
  { grade: 5, bloom: 'evaluate', subject: 'arabic', topic_ar: 'الإعراب', question_ar: 'أيُّ إعرابٍ صحيحٍ لـ«كانَ الطقسُ جميلاً»؟', options_ar: ['كانَ: فعل ماضٍ ناقص، الطقسُ: اسمها مرفوع، جميلاً: خبرها منصوب', 'كانَ: فعل تام، الطقسُ: فاعل', 'جميلاً: مفعول', 'كلها مرفوعة'], correct_answer: '0', explanation_ar: '«كان» ناقص، «الطقسُ» اسمها مرفوع، «جميلاً» خبرها منصوب.', image_key: null },
  { grade: 5, bloom: 'create', subject: 'arabic', topic_ar: 'البلاغة', question_ar: 'اكتب تشبيهاً بليغاً للقمر', options_ar: ['القمرُ كالدرِّ في بهائه', 'القمرُ أبيض', 'القمرُ يضيء', 'القمرُ في السماء'], correct_answer: '0', explanation_ar: 'التشبيه البليغ: مشبه + مشبه به + وجه شبه، كأن القمر درة.', image_key: null },

  // ════ الصف السادس (١١) ════
  { grade: 6, bloom: 'remember', subject: 'arabic', topic_ar: 'الممنوع من الصرف', question_ar: 'ما الممنوع من الصرف؟', options_ar: ['اسمٌ لا يُنوّن ولا يُجر إلا بالكسرة', 'فعلٌ لا يُرفع', 'حرفٌ لا يدخل', 'لا شيء'], correct_answer: '0', explanation_ar: 'الممنوع من الصرف: ما لا يلحقه تنوين ولا كسرة بل فتحة.', image_key: null },
  { grade: 6, bloom: 'remember', subject: 'arabic', topic_ar: 'التمييز', question_ar: 'ما التمييز؟', options_ar: ['اسمٌ نكرةٌ منصوبٌ يُزيل الإبهام', 'اسمٌ معرفةٌ مرفوع', 'فعلٌ ماضٍ', 'حرف جر'], correct_answer: '0', explanation_ar: 'التمييز: اسمٌ نكرةٌ منصوبٌ يزيل الإبهام عن المُبهم قبله.', image_key: null },
  { grade: 6, bloom: 'understand', subject: 'arabic', topic_ar: 'الإعراب', question_ar: 'ما الفرق بين الإعراب اللفظي والتقديري؟', options_ar: ['اللفظي يظهر في النطق والتقديري يقدر لثقلٍ أو تعذر', 'لا فرق', 'كلاهما مقدر', 'كلاهما لفظي'], correct_answer: '0', explanation_ar: 'اللفظي يظهر في النطق، والتقديري يقدر لاستثقال أو تعذر كآخر المقصور.', image_key: null },
  { grade: 6, bloom: 'understand', subject: 'arabic', topic_ar: 'الاستعارة', question_ar: 'ما الاستعارة في البلاغة؟', options_ar: ['تشبيهٌ حُذف أحد طرفيه', 'تشبيهٌ تام', 'سرد قصة', 'إعراب جملة'], correct_answer: '0', explanation_ar: 'الاستعارة: تشبيه حُذف أحد طرفيه (المشبه أو المشبه به).', image_key: null },
  { grade: 6, bloom: 'apply', subject: 'arabic', topic_ar: 'الإعراب', question_ar: 'أعرب: «رأيتُ الفتى»', options_ar: ['الفتى: مفعول به منصوب بفتحة مقدرة على الألف', 'الفتى: فاعل مرفوع', 'الفتى: مبتدأ', 'الفتى: مجرور'], correct_answer: '0', explanation_ar: '«الفتى» مفعول منصوب بفتحة مقدرة على الألف للتعذر.', image_key: null },
  { grade: 6, bloom: 'apply', subject: 'arabic', topic_ar: 'التمييز', question_ar: 'أعرب التمييز في «اشتريتُ رطلاً عسلاً»', options_ar: ['عسلاً: تمييز منصوب', 'عسلاً: فاعل', 'عسلاً: مبتدأ', 'عسلاً: مجرور'], correct_answer: '0', explanation_ar: '«عسلاً» تمييز منصوب يزيل الإبهام عن المقدار «رطلاً».', image_key: null },
  { grade: 6, bloom: 'analyze', subject: 'arabic', topic_ar: 'التشبيه والاستعارة', question_ar: 'ما الفرق بين التشبيه والاستعارة؟', options_ar: ['التشبيه يذكر الطرفين والاستعارة تحذف أحدهما', 'لا فرق', 'الاستعارة تذكر الطرفين', 'التشبيه يحذف'], correct_answer: '0', explanation_ar: 'التشبيه يذكر المشبه والمشبه به، والاستعارة تحذف أحدهما.', image_key: null },
  { grade: 6, bloom: 'analyze', subject: 'arabic', topic_ar: 'أنواع الكناية', question_ar: 'ما الفرق بين كناية الصفة وكناية الذات؟', options_ar: ['الصفة تكني عن صفةٍ والذات تكني عن ذاتٍ', 'لا فرق', 'كلاهما عن صفة', 'كلاهما عن ذات'], correct_answer: '0', explanation_ar: 'كناية الصفة: عن صفة كـ«طويل النجاد». كناية الذات: عن ذات كـ«أبو فلان».', image_key: null },
  { grade: 6, bloom: 'evaluate', subject: 'arabic', topic_ar: 'البلاغة', question_ar: 'أيُّ جملةٍ فيها استعارةٌ تصريحية؟', options_ar: ['رأيتُ أسداً يخطبُ (للرجل الشجاع)', 'الرجلُ شجاعٌ كالأسد', 'الأسدُ قويٌّ', 'الرجلُ يخطب'], correct_answer: '0', explanation_ar: '«رأيت أسداً يخطب»: استعارة تصريحية، صرّح بالمشبه به (الأسد) وحذف المشبه.', image_key: null },
  { grade: 6, bloom: 'evaluate', subject: 'arabic', topic_ar: 'الإعراب', question_ar: 'أيُّ إعرابٍ صحيحٍ لـ«جاءَ أحمدُ» (علم ممنوع من الصرف)؟', options_ar: ['أحمدُ: فاعل مرفوع بضمة', 'أحمدَ: فاعل منصوب', 'أحمدٍ: فاعل مجرور', 'أحمدْ: فاعل ساكن'], correct_answer: '0', explanation_ar: '«أحمدُ» ممنوع من الصرف للعلمية ووزن الفعل، يرفع بضمة بلا تنوين.', image_key: null },
  { grade: 6, bloom: 'create', subject: 'arabic', topic_ar: 'البلاغة', question_ar: 'اكتب نصاً بليغاً تستخدم فيه استعارةً', options_ar: ['بزغَ الصباحُ يضحكُ للوجودِ، فانتبهَ الطيرُ يشدو', 'الصباح جاء', 'الطير غرد', 'الشمس طلعت'], correct_answer: '0', explanation_ar: '«يضحك الصباح»: استعارة، إسناد فعل الإنسان لشيءٍ غير عاقل.', image_key: null },
];