// بنك بلوم — التربية الإسلامية
// ٦٧ سؤالاً موزّعة على الصفوف ١-٦ ومستويات بلوم الستة
// المواضيع: أركان الإسلام والإيمان، العبادات، السيرة، الأخلاق، العقيدة، الفقه

export const BLOOM_ISLAMIC = [
  // ════ الصف الأول (١١) ════
  { grade: 1, bloom: 'remember', subject: 'islamic', topic_ar: 'أركان الإسلام', question_ar: 'كم عدد أركان الإسلام؟', options_ar: ['خمسة', 'ستة', 'أربعة', 'ثلاثة'], correct_answer: '0', explanation_ar: 'أركان الإسلام خمسة: الشهادتان، الصلاة، الزكاة، الصوم، الحج.', image_key: null },
  { grade: 1, bloom: 'remember', subject: 'islamic', topic_ar: 'الصلاة', question_ar: 'كم عدد الصلوات المفروضة في اليوم؟', options_ar: ['خمس صلوات', 'ثلاث صلوات', 'ست صلوات', 'صلاتان'], correct_answer: '0', explanation_ar: 'الصلوات الخمس: الفجر، الظهر، العصر، المغرب، العشاء.', image_key: null },
  { grade: 1, bloom: 'understand', subject: 'islamic', topic_ar: 'الصلاة', question_ar: 'لماذا نصلي كل يوم؟', options_ar: ['لنطيع الله ونعبده', 'لأن الجميع يصلي', 'لنتقابل مع الأصدقاء', 'لأنها رياضة'], correct_answer: '0', explanation_ar: 'نصلي طاعةً لله وعبادةً له وشكراً على نعمه.', image_key: null },
  { grade: 1, bloom: 'understand', subject: 'islamic', topic_ar: 'الوضوء', question_ar: 'متى نتوضأ قبل الصلاة؟', options_ar: ['قبل كل صلاة إذا انتقض وضوؤنا', 'مرة في الصباح', 'مرة في الأسبوع', 'لا نتوضأ'], correct_answer: '0', explanation_ar: 'نتوضأ قبل الصلاة إذا انتقض وضوؤنا بنوم أو حدث.', image_key: null },
  { grade: 1, bloom: 'apply', subject: 'islamic', topic_ar: 'ترتيب الصلوات', question_ar: 'أي صلاة تأتي أولاً في النهار؟', options_ar: ['الفجر', 'العصر', 'المغرب', 'العشاء'], correct_answer: '0', explanation_ar: 'الفجر هي أول صلوات النهار قبل طلوع الشمس.', image_key: null },
  { grade: 1, bloom: 'apply', subject: 'islamic', topic_ar: 'آداب المسجد', question_ar: 'ماذا نفعل قبل دخول المسجد؟', options_ar: ['نخلع الحذاء ونقدم الرجل اليمنى', 'نركض بسرعة', 'نتكلم بصوت عالٍ', 'نأكل طعامنا'], correct_answer: '0', explanation_ar: 'نخلع الحذاء ونقدم الرجل اليمنى ونقول ذكر الدخول.', image_key: null },
  { grade: 1, bloom: 'analyze', subject: 'islamic', topic_ar: 'الأخلاق', question_ar: 'لماذا يجب أن نطيع والدينا؟', options_ar: ['لأن الله أمر بذلك ولجميل صنعهما', 'لأنهما أكبر منا', 'خوفاً من العقاب فقط', 'لا يجب إطاعتهما'], correct_answer: '0', explanation_ar: 'الله أمر بطاعة الوالدين لما لهما من فضل علينا في التربية.', image_key: null },
  { grade: 1, bloom: 'analyze', subject: 'islamic', topic_ar: 'الصدق', question_ar: 'ما الفرق بين الصدق والكذب؟', options_ar: ['الصدق قول الحق والكذب قول الباطل', 'لا فرق بينهما', 'الصدق صعب والكذب سهل', 'الصدق للكبار والكذب للصغار'], correct_answer: '0', explanation_ar: 'الصدق مطابقة القول للواقع، والكذب عدم مطابقته.', image_key: null },
  { grade: 1, bloom: 'evaluate', subject: 'islamic', topic_ar: 'الأخلاق', question_ar: 'أيٌّ من هذه الأفعال أفضل؟', options_ar: ['مساعدة صديق محتاج', 'اللعب وحدي', 'إهمال الواجب', 'التحدث بأذى للآخرين'], correct_answer: '0', explanation_ar: 'مساعدة المحتاج من أفضل الأعمال وأحبها إلى الله.', image_key: null },
  { grade: 1, bloom: 'evaluate', subject: 'islamic', topic_ar: 'الصلاة', question_ar: 'أي تصرفٍ صحيحٌ قبل الصلاة؟', options_ar: ['التوضؤ ولبس الثوب النظيف', 'اللعب بالطين', 'الأكل بسرعة', 'النوم حتى المتأخر'], correct_answer: '0', explanation_ar: 'الطهارة ونظافة الثواب من شروط صحة الصلاة.', image_key: null },
  { grade: 1, bloom: 'create', subject: 'islamic', topic_ar: 'الأخلاق', question_ar: 'كيف تساعد صديقك الذي يشعر بالحزن؟', options_ar: ['أواسيه وألعب معه وأدعوه للابتسامة', 'أتركه وحيداً', 'أسخر منه', 'أقول له لا أبالي'], correct_answer: '0', explanation_ar: 'مواساة الصديق ومشاركته اللعب من أخلاق الإسلام.', image_key: null },

  // ════ الصف الثاني (١١) ════
  { grade: 2, bloom: 'remember', subject: 'islamic', topic_ar: 'أركان الإيمان', question_ar: 'كم عدد أركان الإيمان؟', options_ar: ['ستة', 'خمسة', 'أربعة', 'سبعة'], correct_answer: '0', explanation_ar: 'أركان الإيمان ستة: الإيمان بالله وملائكته وكتبه ورسله واليوم الآخر والقدر.', image_key: null },
  { grade: 2, bloom: 'remember', subject: 'islamic', topic_ar: 'قصص الأنبياء', question_ar: 'من هو النبي الذي صنع السفينة؟', options_ar: ['نوح عليه السلام', 'موسى عليه السلام', 'إبراهيم عليه السلام', 'عيسى عليه السلام'], correct_answer: '0', explanation_ar: 'نوح عليه السلام صنع السفينة بأمر الله لينجو هو والمؤمنون من الطوفان.', image_key: null },
  { grade: 2, bloom: 'understand', subject: 'islamic', topic_ar: 'قصة إبراهيم', question_ar: 'لماذا بنى إبراهيم عليه السلام الكعبة؟', options_ar: ['لبيت الله الحرام ليعبد فيه الناس', ' ليسكن فيه', 'ليتجار فيه', 'ليحفظ أمتعته'], correct_answer: '0', explanation_ar: 'بنى إبراهيم وابنه إسماعيل الكعبة بيتاً لله ليعبده الناس فيه.', image_key: null },
  { grade: 2, bloom: 'understand', subject: 'islamic', topic_ar: 'أخلاق المسلم', question_ar: 'ماذا نقول قبل الأكل؟', options_ar: ['بسم الله', 'شكراً', 'لا شيء', 'السلام عليكم'], correct_answer: '0', explanation_ar: 'نقول بسم الله قبل الأكل ونقول الحمد لله بعده.', image_key: null },
  { grade: 2, bloom: 'apply', subject: 'islamic', topic_ar: 'آداب الطعام', question_ar: 'أيُّ يدٍ نستخدمها للأكل؟', options_ar: ['اليمنى', 'اليسرى', 'كلتاهما', 'لا فرق'], correct_answer: '0', explanation_ar: 'السنة الأكل باليد اليمنى تيمناً واتباعاً لهدى النبي ﷺ.', image_key: null },
  { grade: 2, bloom: 'apply', subject: 'islamic', topic_ar: 'آداب المسجد', question_ar: 'ماذا نفعل داخل المسجد؟', options_ar: ['نصلي ونذكر الله بهدوء', 'نلعب ونجري', 'نتكلم بصوت عالٍ', 'نأكل'], correct_answer: '0', explanation_ar: 'المسجد للصلاة وذكر الله وقراءة القرآن بهدوء واحترام.', image_key: null },
  { grade: 2, bloom: 'analyze', subject: 'islamic', topic_ar: 'قصة نوح', question_ar: 'لماذا صبر نوح عليه السلام على قومه طويلاً؟', options_ar: ['ليدعوهم إلى الإيمان بالله', 'ليعاقبهم', 'ليبني بيته', 'ليستريح'], correct_answer: '0', explanation_ar: 'صبر نوح ليدعو قومه إلى توحيد الله ألف سنة إلا خمسين عاماً.', image_key: null },
  { grade: 2, bloom: 'analyze', subject: 'islamic', topic_ar: 'قصة إبراهيم', question_ar: 'لماذا ضحى إبراهيم عليه السلام بابنه؟', options_ar: ['لطاعة الله وامتثال أمره', 'لأنه لم يحبه', 'خوفاً من الناس', 'ليس لأسباب'], correct_answer: '0', explanation_ar: 'ضحى إبراهيم طاعةً لله وفداه الله بكبشٍ عظيم.', image_key: null },
  { grade: 2, bloom: 'evaluate', subject: 'islamic', topic_ar: 'الإيمان', question_ar: 'أيٌّ من هذه يدل على قوة الإيمان؟', options_ar: ['الصلاة في وقتها دائماً', 'النوم في وقت الصلاة', 'ترك الصلاة أحياناً', 'السخرية من المصلين'], correct_answer: '0', explanation_ar: 'المحافظة على الصلاة في وقتها من أعظم علامات الإيمان.', image_key: null },
  { grade: 2, bloom: 'evaluate', subject: 'islamic', topic_ar: 'الصدق', question_ar: 'أي تصرفٍ يدل على الصدق؟', options_ar: ['أخبر أبي بحقيقة ما حدث', 'أكذب لأتجنب العقاب', 'أخفي ما فعلت', 'ألقي اللوم على غيري'], correct_answer: '0', explanation_ar: 'قول الحقيقة ولو على النفس من علامات الصدق.', image_key: null },
  { grade: 2, bloom: 'create', subject: 'islamic', topic_ar: 'قصص الأنبياء', question_ar: 'كيف تروي قصة نوح عليه السلام لصديقك بكلماتك؟', options_ar: ['نادى قومه للإيمان فكذبوه فصنع السفينة ونجا المؤمنون', 'بنى قصراً كبيراً', 'سافر لبلد بعيد', 'لم يدعُ أحداً'], correct_answer: '0', explanation_ar: 'تلخص القصة: دعوة → تكذيب → سفينة → طوفان → نجاة.', image_key: null },

  // ════ الصف الثالث (١٢) ════
  { grade: 3, bloom: 'remember', subject: 'islamic', topic_ar: 'التوحيد', question_ar: 'ما معنى لا إله إلا الله؟', options_ar: ['لا معبود بحق إلا الله', 'لا إله في السماء', 'لا أحد يصلي', 'لا أحد يعرف الله'], correct_answer: '0', explanation_ar: 'لا إله إلا الله: لا معبود يستحق العبادة بحق إلا الله وحده.', image_key: null },
  { grade: 3, bloom: 'remember', subject: 'islamic', topic_ar: 'أسماء الله الحسنى', question_ar: 'أيُّ هذه من أسماء الله الحسنى؟', options_ar: ['الرحمن', 'الشمس', 'القمر', 'البحر'], correct_answer: '0', explanation_ar: 'الرحمن من أسماء الله الحسنى، أما الشمس والقمر والبحر فمخلوقات.', image_key: null },
  { grade: 3, bloom: 'understand', subject: 'islamic', topic_ar: 'محمد رسول الله', question_ar: 'ماذا يعني الإيمان بأن محمداً رسول الله؟', options_ar: ['تصديقه فيما أخبر وطاعته فيما أمر واجتناب ما نهى عنه', 'معرفة اسمه فقط', 'قراءة قصته بدون عمل', 'الحديث عنه دون اتباع'], correct_answer: '0', explanation_ar: 'الإيمان برسالة النبي ﷺ يتطلب تصديقه وطاعته واتباع سنته.', image_key: null },
  { grade: 3, bloom: 'understand', subject: 'islamic', topic_ar: 'الزكاة', question_ar: 'لماذا شرع الله الزكاة؟', options_ar: ['لتطهير المال وإغناء الفقراء', 'لتقليل المال', 'لإعطاء الأغنياء', 'لتخزين الذهب'], correct_answer: '0', explanation_ar: 'الزكاة تطهر المال وتغني الفقراء وتحقق التكافل الاجتماعي.', image_key: null },
  { grade: 3, bloom: 'apply', subject: 'islamic', topic_ar: 'الصيام', question_ar: 'متى يبدأ صيام يوم رمضان؟', options_ar: ['من طلوع الفجر', 'من طلوع الشمس', 'من الظهر', 'من الغروب'], correct_answer: '0', explanation_ar: 'يبدأ الصيام من طلوع الفجر الصادق وينتهي بغروب الشمس.', image_key: null },
  { grade: 3, bloom: 'apply', subject: 'islamic', topic_ar: 'الزكاة', question_ar: 'من هم المستحقون للزكاة؟', options_ar: ['الفقراء والمساكين', 'الأغنياء', 'الأصحاء', 'القادرون على العمل'], correct_answer: '0', explanation_ar: 'الزكاة للفقراء والمساكين والغارمين وابن السبيل وغيرهم من المصارف الثمانية.', image_key: null },
  { grade: 3, bloom: 'analyze', subject: 'islamic', topic_ar: 'أنواع التوحيد', question_ar: 'ما الفرق بين توحيد الربوبية وتوحيد الألوهية؟', options_ar: ['الربوبية إفراد الله بالخلق والألوهية إفراده بالعبادة', 'لا فرق بينهما', 'الربوبية للعبادة والألوهية للخلق', 'كلاهما للمخلوقات'], correct_answer: '0', explanation_ar: 'الربوبية: إفراد الله بالخلق والتدبير. الألوهية: إفراده بالعبادة والدعاء.', image_key: null },
  { grade: 3, bloom: 'analyze', subject: 'islamic', topic_ar: 'أثر التوحيد', question_ar: 'ما أثر التوحيد في حياة المسلم؟', options_ar: ['الطمأنينة والثقة بالله والاعتماد عليه', 'الخوف والقلق', 'التكبر على الناس', 'الانعزال عن المجتمع'], correct_answer: '0', explanation_ar: 'التوحيد يمنح المسلم طمأنينة القلب وثقةً بالله واعتماداً عليه.', image_key: null },
  { grade: 3, bloom: 'evaluate', subject: 'islamic', topic_ar: 'فضل العلم', question_ar: 'أيٌّ أفضل: العلم أم المال؟', options_ar: ['العلم، لأنه يبقى والمال يفنى', 'المال، لأنه ينفع الآن', 'كلاهما سواء', 'لا أهمية لأحدهما'], correct_answer: '0', explanation_ar: 'العلم أفضل لأنه يبقى وينفع صاحبه والمال يفنى ويزول.', image_key: null },
  { grade: 3, bloom: 'evaluate', subject: 'islamic', topic_ar: 'العبادات', question_ar: 'أيُّ عملٍ يحبه الله أكثر؟', options_ar: ['إطعام الفقير بكرة وعشياً', 'النوم طوال النهار', 'اللعب دون فائدة', 'التحدث بأذى'], correct_answer: '0', explanation_ar: 'إطعام الفقراء من أحب الأعمال إلى الله تعالى.', image_key: null },
  { grade: 3, bloom: 'create', subject: 'islamic', topic_ar: 'نشاط إسلامي', question_ar: 'صمم نشاطاً لتعليم أصدقائك فضل الصدق', options_ar: ['مسرحية قصيرة تظهر أثر الصدق في حياة طالب', 'رسمة بلا معنى', 'لعبة عشوائية', 'أغنية عن اللعب'], correct_answer: '0', explanation_ar: 'المسرحية تجسد القيم في مواقف عملية يفهمها الطلاب.', image_key: null },
  { grade: 3, bloom: 'create', subject: 'islamic', topic_ar: 'كتابة قصة', question_ar: 'اكتب نهاية لقصة طفل كذب على أمه ثم ندم', options_ar: ['اعتذر لأمه واعترف بالحق فعفا الله عنه', 'استمر في الكذب', 'هرب من البيت', 'لم يفعل شيئاً'], correct_answer: '0', explanation_ar: 'الاعتذار والاعتراف بالحق سبب لمغفرة الله ورضا الوالدين.', image_key: null },

  // ════ الصف الرابع (١١) ════
  { grade: 4, bloom: 'remember', subject: 'islamic', topic_ar: 'أركان الصوم', question_ar: 'ما ركن الصوم؟', options_ar: ['الإمساك عن المفطرات من الفجر إلى الغروب بنية', 'الأكل عند الغروب', 'النوم نهاراً', 'الصلاة فقط'], correct_answer: '0', explanation_ar: 'ركن الصوم: الإمساك عن المفطرات من طلوع الفجر إلى غروب الشمس بنية.', image_key: null },
  { grade: 4, bloom: 'remember', subject: 'islamic', topic_ar: 'أركان الحج', question_ar: 'أيٌّ من هذه من أركان الحج؟', options_ar: ['الطواف بالبيت', 'الأكل في الحرم', 'النوم في الخيمة', 'شراء الهدايا'], correct_answer: '0', explanation_ar: 'أركان الحج: الإحرام، الطواف، السعي، الوقوف بعرفة.', image_key: null },
  { grade: 4, bloom: 'understand', subject: 'islamic', topic_ar: 'الحج', question_ar: 'لماذا يُفرض الحج مرة واحدة في العمر؟', options_ar: ['لرفع الحرج عن المسلمين', 'لأنه سهل', 'لأنه قصير', 'لا سبب'], correct_answer: '0', explanation_ar: 'فُرض الحج مرة واحدة لرفع الحرج، فهو شاقٌ ومكلفٌ لمن استطاع.', image_key: null },
  { grade: 4, bloom: 'understand', subject: 'islamic', topic_ar: 'الصوم', question_ar: 'ما الحكمة من الصيام؟', options_ar: ['تقوى الله والشعور بمعاناة الفقراء', 'تخسيس الوزن فقط', 'النوم أكثر', 'توفير المال'], correct_answer: '0', explanation_ar: 'الصيام يحقق التقوى ويُشعر الغني بجوع الفقير فيُكثر الصدقة.', image_key: null },
  { grade: 4, bloom: 'apply', subject: 'islamic', topic_ar: 'مفسدات الصوم', question_ar: 'أيٌّ من هذه يُفطر الصائم؟', options_ar: ['الأكل والشرب عمداً', 'النسيان', 'البلع من اللعاب', 'الاستحمام'], correct_answer: '0', explanation_ar: 'الأكل والشرب عمداً يفطر، أما الناسي فلا إثم عليه.', image_key: null },
  { grade: 4, bloom: 'apply', subject: 'islamic', topic_ar: 'آداب الحج', question_ar: 'ماذا يفعل الحاج في عرفة؟', options_ar: ['يقف ويدعو الله ويتذكر يوم القيامة', 'ينام في الخيمة', 'يتسوق', 'يلعب'], correct_answer: '0', explanation_ar: 'الوقوف بعرفة ركن الحج الأكبر، فيه الدعاء والتضرع والذكر.', image_key: null },
  { grade: 4, bloom: 'analyze', subject: 'islamic', topic_ar: 'العبادات', question_ar: 'ما الفرق بين الصوم والحج من حيث الفرضية؟', options_ar: ['الصوم كل سنة والحج مرة في العمر لمن استطاع', 'كلاهما كل سنة', 'كلاهما مرة', 'الحج كل سنة والصوم مرة'], correct_answer: '0', explanation_ar: 'الصوم يفعل كل سنة، والحج مرة لمن استطاع إليه سبيلاً.', image_key: null },
  { grade: 4, bloom: 'analyze', subject: 'islamic', topic_ar: 'الأخلاق', question_ar: 'لماذا حث الإسلام على بر الوالدين؟', options_ar: ['لتفضيلهما على النفس وجميل صنعهما في التربية', 'لأنهما أكبر سناً', 'خوفاً منهما', 'لا سبب'], correct_answer: '0', explanation_ar: 'بر الوالدين لفضلهما وعظيم تضحياتهما في التربية والرعاية.', image_key: null },
  { grade: 4, bloom: 'evaluate', subject: 'islamic', topic_ar: 'الحج', question_ar: 'أيُّ عملٍ في الحج أفضل؟', options_ar: ['الوقوف بعرفة في خير يوم', 'شراء الهدايا', 'الصعود على الجبال', 'التجول في الأسواق'], correct_answer: '0', explanation_ar: 'الوقوف بعرفة أعظم أركان الحج وفيه مغفرة الذنوب.', image_key: null },
  { grade: 4, bloom: 'evaluate', subject: 'islamic', topic_ar: 'الصدق في الصوم', question_ar: 'أيُّ صائمٍ صيامُه أفضل؟', options_ar: ['من حفظ لسانه ولم يكذب ولم يغتب', 'من أكل كثيراً عند الإفطار', 'من نام النهار كله', 'من اشتكى من الجوع'], correct_answer: '0', explanation_ar: 'الصوم الكامل يكف الجوارح عن المعاصي لا الجوع فقط.', image_key: null },
  { grade: 4, bloom: 'create', subject: 'islamic', topic_ar: 'مشروع خيري', question_ar: 'خطط مشروعاً لمساعدة الفقراء في رمضان', options_ar: ['جمع التبرعات وتوزيع وجبات الإفطار على المحتاجين', 'بناء مسجد فاخر', 'شراء حلويات للأغنياء', 'إقامة حفل غنائي'], correct_answer: '0', explanation_ar: 'توزيع وجبات الإفطار من السنن والمشاريع النافعة في رمضان.', image_key: null },

  // ════ الصف الخامس (١٢) ════
  { grade: 5, bloom: 'remember', subject: 'islamic', topic_ar: 'اليوم الآخر', question_ar: 'ما معنى الإيمان باليوم الآير؟', options_ar: ['التصديق بكل ما أخبر به الله مما يكون بعد الموت', 'معرفة تاريخ الوفاة', 'الخوف من الموت فقط', 'ترك الدنيا'], correct_answer: '0', explanation_ar: 'الإيمان باليوم الآخر: التصديق بكل ما بعد الموت من بعث وحساب وجنة ونار.', image_key: null },
  { grade: 5, bloom: 'remember', subject: 'islamic', topic_ar: 'الملائكة', question_ar: 'من الملك الموكل بالوحي؟', options_ar: ['جبريل عليه السلام', 'إسرافيل', 'ميكال', 'ملك الموت'], correct_answer: '0', explanation_ar: 'جبريل عليه السلام هو الملك الموكل بالوحي إلى الأنبياء.', image_key: null },
  { grade: 5, bloom: 'understand', subject: 'islamic', topic_ar: 'علامات الساعة', question_ar: 'ما هي علامات الساعة الصغرى؟', options_ar: ['أمارات تقرب قيام الساعة مثل ظهور الفتن', 'كوارث طبيعية', 'أمراض', 'لا شيء'], correct_answer: '0', explanation_ar: 'علامات الساعة الصغرى أمارات تقرب قيامها كبعثة النبي وظهور الفتن.', image_key: null },
  { grade: 5, bloom: 'understand', subject: 'islamic', topic_ar: 'يوم القيامة', question_ar: 'ماذا يحدث في يوم القيامة؟', options_ar: ['يبعث الله الناس ويحاسبهم على أعمالهم', 'ينام الجميع', 'ينتهي كل شيء', 'لا شيء يحدث'], correct_answer: '0', explanation_ar: 'في يوم القيامة يبعث الله الخلق ويحاسبهم: فمؤمن إلى جنة وكافر إلى نار.', image_key: null },
  { grade: 5, bloom: 'apply', subject: 'islamic', topic_ar: 'المعاملات', question_ar: 'أيُّ بيعٍ جائز شرعاً؟', options_ar: ['بيع واضح بلا غش بثمن معلوم', 'بيع فيه غش', 'بيع المجهول', 'بيع فيه ربا'], correct_answer: '0', explanation_ar: 'البيع الجائز: أن يكون بلا غش ولا جهالة ولا ربا، بثمن معلوم.', image_key: null },
  { grade: 5, bloom: 'apply', subject: 'islamic', topic_ar: 'آداب المعاملة', question_ar: 'كيف تعامل زميلك في البيع والشراء؟', options_ar: ['بالصدق والبيان ولا أغشه', 'أخفي العيوب', 'أكذب في السعر', 'أزيد الثمن بلا سبب'], correct_answer: '0', explanation_ar: 'الصدق والبيان في المعاملات من آداب الإسلام ويبارك الله فيها.', image_key: null },
  { grade: 5, bloom: 'analyze', subject: 'islamic', topic_ar: 'الربا', question_ar: 'ما الفرق بين البيع والربا؟', options_ar: ['البيع مبادلة بطيب نفس والربا زيادة على دين بلا مقابل', 'لا فرق', 'الربا أفضل', 'البيع حرام والربا حلال'], correct_answer: '0', explanation_ar: 'البيع مبادلة مال بمال بطيب نفس، والربا زيادة في دين مقابل الأجل وهو محرم.', image_key: null },
  { grade: 5, bloom: 'analyze', subject: 'islamic', topic_ar: 'أثر الإيمان', question_ar: 'ما أثر الإيمان باليوم الآخر على سلوك المسلم؟', options_ar: ['يمنعه من الظلم ويحفزه على الطاعة', 'يزيد طمعه', 'يقلل عمله', 'لا أثر له'], correct_answer: '0', explanation_ar: 'الإيمان باليوم الآخر يردع عن المعاصي ويبعث على الطاعة والعدل.', image_key: null },
  { grade: 5, bloom: 'evaluate', subject: 'islamic', topic_ar: 'المعاملات', question_ar: ['أيُّ معاملةٍ أفضل عند الله؟', 'أي معاملةٍ يحبها الله؟'], correct_answer: '0', options_ar: ['حسن المعاملة مع الناس وبر الوالدين', 'أخذ مال الناس', 'بيع الغش', 'الربح الكثير بأي وسيلة'], explanation_ar: 'حسن الخلق وبر الوالدين من أحب الأعمال إلى الله.', image_key: null },
  { grade: 5, bloom: 'evaluate', subject: 'islamic', topic_ar: 'بر الوالدين', question_ar: 'أيُّ تصرفٍ يدل على بر الوالدين؟', options_ar: ['الإصغاء لحديثهما وعدم رفع الصوت عليهما', 'الذهاب دون إذنهما', 'الاستهزاء برأيهما', 'ترك مساعدتهما'], correct_answer: '0', explanation_ar: 'الإصغاء وعدم رفع الصوت من مظاهر البر والاحترام.', image_key: null },
  { grade: 5, bloom: 'create', subject: 'islamic', topic_ar: 'مشروع خيري', question_ar: 'صمم مشروعاً خيرياً في مدرستك', options_ar: ['صندوق تبرعات يوزع على الأسر المحتاجة شهرياً', 'حفلة ترفيهية', 'مسابقة ألعاب', 'بيع حلويات للربح'], correct_answer: '0', explanation_ar: 'صندوق التبرعات المستمر يحقق التكافل وينفع الأسر المحتاجة.', image_key: null },
  { grade: 5, bloom: 'create', subject: 'islamic', topic_ar: 'نصيحة', question_ar: 'اكتب نصيحة لصديق يهمل الصلاة', options_ar: ['الصلاة عمود الدين فاحافظ عليها قبل أن يأتي يوم لا ينفع فيه ندم', 'لا تصلِّ فهي متعبة', 'صلِّ مرة في الأسبوع', 'لا بأس بالتأجيل'], correct_answer: '0', explanation_ar: 'النصيحة: تذكير بأهمية الصلاة وعاقبة التهاون فيها.', image_key: null },

  // ════ الصف السادس (١٠) ════
  { grade: 6, bloom: 'remember', subject: 'islamic', topic_ar: 'مصادر الشريعة', question_ar: 'ما المصدر الأول للشريعة الإسلامية؟', options_ar: ['القرآن الكريم', 'كتب الفقه', 'الإنترنت', 'آراء الناس'], correct_answer: '0', explanation_ar: 'القرآن الكريم هو المصدر الأول، ثم السنة النبوية ثم الإجماع والقياس.', image_key: null },
  { grade: 6, bloom: 'remember', subject: 'islamic', topic_ar: 'أنواع الأحكام', question_ar: 'كم عدد الأحكام الشرعية التكليفية؟', options_ar: ['خمسة', 'ثلاثة', 'ستة', 'أربعة'], correct_answer: '0', explanation_ar: 'الأحكام الخمسة: واجب، مندوب، مباح، مكروه، محرم.', image_key: null },
  { grade: 6, bloom: 'understand', subject: 'islamic', topic_ar: 'مقاصد الشريعة', question_ar: 'ما المقصود بمقاصد الشريعة؟', options_ar: ['الأهداف والحكم التي شرع الله الأحكام لأجلها', 'قواعد اللغة', 'أنظمة الدولة', 'آداب الطعام'], correct_answer: '0', explanation_ar: 'مقاصد الشريعة: الأهداف التي قصد الشارع من تشريع الأحكام.', image_key: null },
  { grade: 6, bloom: 'understand', subject: 'islamic', topic_ar: 'الإجتهاد', question_ar: 'ما الاجتهاد في الفقه الإسلامي؟', options_ar: ['بذل العالم وسعه في استنباط حكم شرعي من أدلته', 'تخمين بلا دليل', 'نسخ الأحكام', 'اتباع الهوى'], correct_answer: '0', explanation_ar: 'الاجتهاد: بذل الفقيه وسعه في طلب الحكم الشرعي من أدلته التفصيلية.', image_key: null },
  { grade: 6, bloom: 'apply', subject: 'islamic', topic_ar: 'تطبيق الأحكام', question_ar: 'إذا ورد نصٌ صريحٌ في مسألة، فما الحكم؟', options_ar: ['نعمل به ولا مجال للاجتهاد', 'نجتهد في تأويله', 'نتركه ونتبع رأينا', 'نسأل الناس'], correct_answer: '0', explanation_ar: 'إذا ورد نص صريح فالعمل به ولا مجال للاجتهاد فيما فيه نص.', image_key: null },
  { grade: 6, bloom: 'apply', subject: 'islamic', topic_ar: 'الأحكام', question_ar: 'صلاة الفجر أيُّ حكمٍ هي؟', options_ar: ['فرض عين', 'مندوب', 'مكروه', 'مباح'], correct_answer: '0', explanation_ar: 'صلاة الفجر فرض عين على كل مسلم بالغ عاقل.', image_key: null },
  { grade: 6, bloom: 'analyze', subject: 'islamic', topic_ar: 'الفرض والواجب', question_ar: 'ما الفرق بين الفرض والواجب عند بعض الأئمة؟', options_ar: ['الفرض ما ثبت بدليل قطعي والواجب بدليل ظني عند الحنفية', 'لا فرق', 'الواجب أقوى', 'الفرض للصلاة والواجب للزكاة'], correct_answer: '0', explanation_ar: 'عند الحنفية: الفرض بدليل قطعي والواجب بدليل ظني، والجمهور لا يفرقون.', image_key: null },
  { grade: 6, bloom: 'analyze', subject: 'islamic', topic_ar: 'الحكمة من التشريع', question_ar: 'لماذا شرع الله الحدود؟', options_ar: ['لحماية المجتمع وزجر المجرمين وإحقاق الحق', 'للانتقام', 'لتعذيب الناس', 'لا حكمة'], correct_answer: '0', explanation_ar: 'الحدود لحماية المجتمع من الجريمة وتحقيق العدل والردع.', image_key: null },
  { grade: 6, bloom: 'evaluate', subject: 'islamic', topic_ar: 'العلم الشرعي', question_ar: 'أيُّ علمٍ أفضل طلباً؟', options_ar: ['العلم الشرعي الذي يقرب إلى الله', 'علم الموسيقى', 'علم السحر', 'علم النجوم التنجيمي'], correct_answer: '0', explanation_ar: 'العلم الشرعي أفضل لأنه يعرف العبد ربه ودينه.', image_key: null },
  { grade: 6, bloom: 'create', subject: 'islamic', topic_ar: 'بحث فقهي', question_ar: 'صمم بحثاً عن مقاصد الشريعة في حفظ النفس', options_ar: ['تأصيل المسألة بأدلة من الكتاب والسنة وتطبيقات معاصرة', 'سرد قصص بلا أدلة', 'تجميع آراء بلا ترتيب', 'لا شيء'], correct_answer: '0', explanation_ar: 'البحث: تأصيل + أدلة + تطبيقات، منهجٌ علميٌ متكامل.', image_key: null },
];