// بنك بلوم — الاجتماعيات
// ٦٧ سؤالاً موزّعة على الصفوف ١-٦ ومستويات بلوم الستة
// المواضيع: الوطن، الجغرافيا، التاريخ، رؤية ٢٠٣٠، الموارد، الحضارات

export const BLOOM_SOCIAL = [
  // ════ الصف الأول (١١) ════
  { grade: 1, bloom: 'remember', subject: 'social', topic_ar: 'الوطن', question_ar: 'ما اسم وطننا؟', options_ar: ['المملكة العربية السعودية', 'مصر', 'الأردن', 'العراق'], correct_answer: '0', explanation_ar: 'وطننا هو المملكة العربية السعودية، تقع في جنوب غرب آسيا.', image_key: null },
  { grade: 1, bloom: 'remember', subject: 'social', topic_ar: 'العلم', question_ar: 'ما لون علم المملكة العربية السعودية؟', options_ar: ['أخضر', 'أحمر', 'أزرق', 'أصفر'], correct_answer: '0', explanation_ar: 'علم المملكة العربية السعودية أخضر وفي وسطه الشهادة والسيف.', image_key: null },
  { grade: 1, bloom: 'understand', subject: 'social', topic_ar: 'الوطن', question_ar: 'لماذا نحب وطننا؟', options_ar: ['لأنه موضع ولادتنا وسكننا وننشأ فيه', 'لأنه كبير', 'لأنه بعيد', 'لا سبب'], correct_answer: '0', explanation_ar: 'نحب الوطن لأننا نولد ونعيش ونتعلم فيه، وهو مكان أمننا.', image_key: null },
  { grade: 1, bloom: 'understand', subject: 'social', topic_ar: 'الجوار', question_ar: 'كيف نعامل جارنا؟', options_ar: ['بالإحسان واحترام وعدم إيذاء', 'بالإهمال', 'بالأذى', 'بالابتعاد'], correct_answer: '0', explanation_ar: 'الإسلام أوصى بالجار إحساناً واحتراماً وعدم إيذاء.', image_key: null },
  { grade: 1, bloom: 'apply', subject: 'social', topic_ar: 'العلم', question_ar: 'ماذا نفعل عند سماع النشيد الوطني؟', options_ar: ['نقف باحترام ونصغي', 'نجلس', 'نتكلم', 'نلعب'], correct_answer: '0', explanation_ar: 'الوقوف احتراماً عند النشيد الوطني واجب وطني.', image_key: null },
  { grade: 1, bloom: 'apply', subject: 'social', topic_ar: 'الأسرة', question_ar: 'ما واجبك نحو والدك؟', options_ar: ['طاعتهما ومساعدتهما والرفق بهما', 'العصيان', 'الصراخ', 'الإهمال'], correct_answer: '0', explanation_ar: 'طاعة الوالدين ومساعدتهما من أهم الواجبات.', image_key: null },
  { grade: 1, bloom: 'analyze', subject: 'social', topic_ar: 'المدينة والقرية', question_ar: 'ما الفرق بين المدينة والقرية؟', options_ar: ['المدينة أكبر وبها خدمات أكثر', 'لا فرق', 'القرية أكبر', 'المدينة أصغر'], correct_answer: '0', explanation_ar: 'المدينة أكبر وبها مستشفيات ومدارس أكثر، والقرية أصغر وأقل خدمات.', image_key: null },
  { grade: 1, bloom: 'analyze', subject: 'social', topic_ar: 'المعلم', question_ar: 'لماذا نحترم المعلم؟', options_ar: ['لأنه يعلمونا ويرشدنا', 'لأنه أكبر سناً', 'خوفاً منه', 'لا سبب'], correct_answer: '0', explanation_ar: 'المعلم له فضل تعليمنا فنحترمه ونطيعه.', image_key: null },
  { grade: 1, bloom: 'evaluate', subject: 'social', topic_ar: 'المواصلات', question_ar: 'أيُّ وسيلةٍ أنقل في المدينة؟', options_ar: ['الحافلة', 'الدراجة في الطريق السريع', 'السيارة بسرعة جنونية', 'الجري'], correct_answer: '0', explanation_ar: 'الحافلة وسيلة آمنة ومنظمة للنقل داخل المدينة.', image_key: null },
  { grade: 1, bloom: 'evaluate', subject: 'social', topic_ar: 'المهن', question_ar: 'أيُّ مهنةٍ تنفع الناس أكثر؟', options_ar: ['الطبيب الذي يعالج المرضى', 'اللص', 'المهمل', 'الكسول'], correct_answer: '0', explanation_ar: 'الطبيب ينفع الناس بعلاجهم وإنقاذ حياتهم.', image_key: null },
  { grade: 1, bloom: 'create', subject: 'social', topic_ar: 'البيت', question_ar: 'ارسم خريطة بسيطة لغرفة جلوسك', options_ar: ['أحدد الباب والنوافذ ومكان الأثاث برموز', 'أرسم دوائر عشوائية', 'أكتب كلمات', 'لا شيء'], correct_answer: '0', explanation_ar: 'الخريطة تستخدم رموزاً لتمثيل الأشياء بمواضعها الصحيحة.', image_key: null },

  // ════ الصف الثاني (١١) ════
  { grade: 2, bloom: 'remember', subject: 'social', topic_ar: 'مدن المملكة', question_ar: 'ما عاصمة المملكة العربية السعودية؟', options_ar: ['الرياض', 'جدة', 'مكة', 'الدمام'], correct_answer: '0', explanation_ar: 'الرياض هي عاصمة المملكة العربية السعودية وأكبر مدنها.', image_key: null },
  { grade: 2, bloom: 'remember', subject: 'social', topic_ar: 'مناطق المملكة', question_ar: 'كم عدد المناطق الإدارية في المملكة؟', options_ar: ['ثلاث عشرة منطقة', 'خمس مناطق', 'عشر مناطق', 'ثلاث مناطق'], correct_answer: '0', explanation_ar: 'تتكون المملكة من ١٣ منطقة إدارية.', image_key: null },
  { grade: 2, bloom: 'understand', subject: 'social', topic_ar: 'الموقع', question_ar: 'أين تقع المملكة العربية السعودية جغرافياً؟', options_ar: ['في جنوب غرب قارة آسيا', 'في أفريقيا', 'في أوروبا', 'في أمريكا'], correct_answer: '0', explanation_ar: 'المملكة تقع في جنوب غرب قارة آسيا في شبه الجزيرة العربية.', image_key: null },
  { grade: 2, bloom: 'understand', subject: 'social', topic_ar: 'النفط', question_ar: 'ماذا تصدّر المملكة للعالم؟', options_ar: ['النفط ومشتقاته', 'القمح', 'الملابس', 'الأخشاب'], correct_answer: '0', explanation_ar: 'المملكة من أكبر مصدّري النفط في العالم.', image_key: null },
  { grade: 2, bloom: 'apply', subject: 'social', topic_ar: 'النقل', question_ar: 'أيُّ وسيلةٍ تُستخدم للسفر بين المدن البعيدة؟', options_ar: ['الطائرة', 'الدراجة', 'السير على الأقدام', 'القارب'], correct_answer: '0', explanation_ar: 'الطائرة أنسب وسيلة للسفر بين المدن البعيدة بسرعة.', image_key: null },
  { grade: 2, bloom: 'apply', subject: 'social', topic_ar: 'المهن', question_ar: 'ماذا يفعل المهندس؟', options_ar: ['يصمم المباني والجسور', 'يعالج المرضى', 'يبيع الطعام', 'يقود السيارة'], correct_answer: '0', explanation_ar: 'المهندس يصمم المباني والطرق والجسور ويشرف على بنائها.', image_key: null },
  { grade: 2, bloom: 'analyze', subject: 'social', topic_ar: 'البحر والبر', question_ar: 'ما الفرق بين البيئة البحرية والبرية؟', options_ar: ['البحر فيه ماء وسمك والبر فيه يابسة ونبات', 'لا فرق', 'البحر أصغر', 'البر فيه ماء'], correct_answer: '0', explanation_ar: 'البحر بيئة مائية فيها كائنات بحرية، والبر يابسة فيها نبات وحيوان.', image_key: null },
  { grade: 2, bloom: 'analyze', subject: 'social', topic_ar: 'النفط', question_ar: 'لماذا النفط مهم للمملكة؟', options_ar: ['لأنه مصدر الدخل الرئيسي ويُصدر للعالم', 'لأنه يشرب', 'لأنه للزينة', 'لا أهمية'], correct_answer: '0', explanation_ar: 'النفط هو المصدر الاقتصادي الرئيسي للمملكة ويمول مشاريعها.', image_key: null },
  { grade: 2, bloom: 'evaluate', subject: 'social', topic_ar: 'السياحة', question_ar: 'أيُّ مدينةٍ تشتهر بالسياحة الدينية؟', options_ar: ['مكة المكرمة', 'الرياض', 'حائل', 'تبوك'], correct_answer: '0', explanation_ar: 'مكة المكرمة مقصد الحجاج والمعتمرين من كل العالم.', image_key: null },
  { grade: 2, bloom: 'evaluate', subject: 'social', topic_ar: 'الموارد', question_ar: 'أيُّ موردٍ أهم لاقتصاد المملكة؟', options_ar: ['النفط', 'الرمال', 'الهواء', 'الحجارة'], correct_answer: '0', explanation_ar: 'النفط أهم مورد اقتصادي للمملكة.', image_key: null },
  { grade: 2, bloom: 'create', subject: 'social', topic_ar: 'العلم', question_ar: 'صمم علماً يمثل قيم وطنك', options_ar: ['أخضر عليه شهادة التوحيد وسيف', 'أحمر بنجوم', 'أزرق بخطوط', 'أصفر بدوائر'], correct_answer: '0', explanation_ar: 'العلم السعودي أخضر يحمل كلمة التوحيد والسيف رمز العدل.', image_key: null },

  // ════ الصف الثالث (١١) ════
  { grade: 3, bloom: 'remember', subject: 'social', topic_ar: 'الموارد الطبيعية', question_ar: 'أيٌّ من هذه مورد طبيعي متجدد؟', options_ar: ['الشمس والرياح', 'النفط', 'الفحم', 'الغاز'], correct_answer: '0', explanation_ar: 'الشمس والرياح موارد متجددة لا تنفد، بخلاف النفط والفحم.', image_key: null },
  { grade: 3, bloom: 'remember', subject: 'social', topic_ar: 'رؤية ٢٠٣٠', question_ar: 'من أطلق رؤية المملكة ٢٠٣٠؟', options_ar: ['الملك سلمان بن عبدالعزيز', 'الملك فهد', 'الملك عبدالله', 'الملك خالد'], correct_answer: '0', explanation_ar: 'أطلق رؤية ٢٠٣٠ الملك سلمان بن عبدالعزيز آل سعود.', image_key: null },
  { grade: 3, bloom: 'understand', subject: 'social', topic_ar: 'الخريطة', question_ar: 'ما الذي تُوضّحه خريطة المملكة؟', options_ar: ['مواقع المدن والمناطق والبحار المحيطة', 'أسماء الناس', 'ألوان العلم', 'عدد السكان'], correct_answer: '0', explanation_ar: 'الخريطة توضح المواقع الجغرافية للمدن والمناطق والحدود.', image_key: null },
  { grade: 3, bloom: 'understand', subject: 'social', topic_ar: 'رؤية ٢٠٣٠', question_ar: 'ما هدف رؤية ٢٠٣٠؟', options_ar: ['تنويع الاقتصاد وتقليل الاعتماد على النفط', 'زيادة النفط فقط', 'إلغاء التعليم', 'تقليل السكان'], correct_answer: '0', explanation_ar: 'رؤية ٢٠٣٠ تهدف لتنويع مصادر الدخل وتنمية البلاد في كل المجالات.', image_key: null },
  { grade: 3, bloom: 'apply', subject: 'social', topic_ar: 'حفظ الماء', question_ar: 'كيف نحافظ على الماء في المنزل؟', options_ar: ['إغلاق الصنبور أثناء التنظيف', 'تركه مفتوحاً', 'استهلاك أكبر', 'رمي النفايات فيه'], correct_answer: '0', explanation_ar: 'إغلاق الصنبور وترشيد الاستهلاك من طرق حفظ الماء.', image_key: null },
  { grade: 3, bloom: 'apply', subject: 'social', topic_ar: 'الموارد', question_ar: 'أيُّ تصرفٍ يحافظ على الكهرباء؟', options_ar: ['إطفاء الأضواء عند الخروج', 'إبقاء كل الأضواء', 'تشغيل المكيف بارداً جداً', 'شحن الهاتف طوال الليل'], correct_answer: '0', explanation_ar: 'إطفاء الأضواء عند الخروج من طرق ترشيد الكهرباء.', image_key: null },
  { grade: 3, bloom: 'analyze', subject: 'social', topic_ar: 'أنواع الموارد', question_ar: 'ما الفرق بين المورد المتجدد وغير المتجدد؟', options_ar: ['المتجدد لا ينفد وغير المتجدد ينفد', 'لا فرق', 'كلاهما ينفد', 'كلاهما لا ينفد'], correct_answer: '0', explanation_ar: 'المتجدد كالشمس لا ينفد، وغير المتجدد كالنفط ينفد بالاستهلاك.', image_key: null },
  { grade: 3, bloom: 'analyze', subject: 'social', topic_ar: 'رؤية ٢٠٣٠', question_ar: 'ما أثر رؤية ٢٠٣٠ على التعليم؟', options_ar: ['تحسين المدارس وتطوير المهارات', 'إغلاق المدارس', 'تقليل المعلمين', 'لا أثر'], correct_answer: '0', explanation_ar: 'الرؤية تطور التعليم وتبني مدارس ومشاريع تعليمية حديثة.', image_key: null },
  { grade: 3, bloom: 'evaluate', subject: 'social', topic_ar: 'رؤية ٢٠٣٠', question_ar: 'أيُّ مشروعٍ من رؤية ٢٠٣٠ أهم للشباب؟', options_ar: ['تطوير التعليم وبناء المهارات', 'بناء قصور', 'شراء سيارات', 'إقامة ملاعب'], correct_answer: '0', explanation_ar: 'التعليم والمهارات أهم ما يطور الشباب ويمكّنهم في سوق العمل.', image_key: null },
  { grade: 3, bloom: 'evaluate', subject: 'social', topic_ar: 'البيئة', question_ar: 'أيُّ سلوكٍ أفضل للحفاظ على البيئة؟', options_ar: ['إعادة التدوير وتقليل النفايات', 'رمي النفايات', 'قطع الأشجار', 'إهدار الماء'], correct_answer: '0', explanation_ar: 'إعادة التدوير وتقليل النفايات تحافظ على البيئة.', image_key: null },
  { grade: 3, bloom: 'create', subject: 'social', topic_ar: 'توفير الطاقة', question_ar: 'ضع خطة لتوفير الكهرباء في مدرستك', options_ar: ['إطفاء الأضواء والمكيفات عند الفراغ', 'إبقاؤها دائماً', 'زيادة الإضاءة', 'لا شيء'], correct_answer: '0', explanation_ar: 'خطة الترشيد: إطفاء عند الفراغ + صيانة + توعية.', image_key: null },

  // ════ الصف الرابع (١١) ════
  { grade: 4, bloom: 'remember', subject: 'social', topic_ar: 'تاريخ المملكة', question_ar: 'من مؤسس المملكة العربية السعودية الحديثة؟', options_ar: ['الملك عبدالعزيز آل سعود', 'الملك فيصل', 'الملك سعود', 'الملك خالد'], correct_answer: '0', explanation_ar: 'الملك عبدالعزيز بن عبدالرحمن آل سعود مؤسس المملكة وموحدها.', image_key: null },
  { grade: 4, bloom: 'remember', subject: 'social', topic_ar: 'توحيد المملكة', question_ar: 'متى تأسست المملكة العربية السعودية؟', options_ar: ['١٣٥١هـ / ١٩٣٢م', '١٤٠٠هـ', '١٢٠٠هـ', '١٥٠٠م'], correct_answer: '0', explanation_ar: 'تأسست المملكة عام ١٣٥١هـ الموافق ١٩٣٢م بضم الحجاز.', image_key: null },
  { grade: 4, bloom: 'understand', subject: 'social', topic_ar: 'التوحيد', question_ar: 'ما أهمية توحيد المملكة على يد الملك عبدالعزيز؟', options_ar: ['الأمن والاستقرار وتوحيد البلاد', 'زيادة الحروب', 'تقسيم البلاد', 'لا أهمية'], correct_answer: '0', explanation_ar: 'التوحيد حقق الأمن والاستقرار بعد فترة من الفرقة والخلاف.', image_key: null },
  { grade: 4, bloom: 'understand', subject: 'social', topic_ar: 'الموقع الجغرافي', question_ar: 'ما الموقع الجغرافي المميز للمملكة؟', options_ar: ['تتوسط قارات العالم القديم', 'في أقصى الشمال', 'في أقصى الجنوب', 'لا موقع مميز'], correct_answer: '0', explanation_ar: 'المملكة تتوسط العالم القديم بين آسيا وأفريقيا وأوروبا.', image_key: null },
  { grade: 4, bloom: 'apply', subject: 'social', topic_ar: 'الاقتصاد', question_ar: 'ما أهم قطاعٍ اقتصادي في المملكة تاريخياً؟', options_ar: ['النفط والبترول', 'الزراعة', 'الصيد', 'الحرف'], correct_answer: '0', explanation_ar: 'النفط هو المحرك الاقتصادي الرئيسي للمملكة منذ اكتشافه.', image_key: null },
  { grade: 4, bloom: 'apply', subject: 'social', topic_ar: 'التجارة', question_ar: 'أيُّ ميناءٍ من أهم موانئ المملكة على البحر الأحمر؟', options_ar: ['ميناء جدة', 'ميناء الدمام', 'ميناء ينبع', 'ميناء الجبيل'], correct_answer: '0', explanation_ar: 'ميناء جدة الإسلامي أكبر موانئ البحر الأحمر وأهمها.', image_key: null },
  { grade: 4, bloom: 'analyze', subject: 'social', topic_ar: 'التوحيد', question_ar: 'ما الأسباب التي ساعدت الملك عبدالعزيز على توحيد المملكة؟', options_ar: ['الإيمان والشجعة وحكمة القيادة', 'الحظ فقط', 'القوة العسكرية فقط', 'لا أسباب'], correct_answer: '0', explanation_ar: 'الإيمان بالله والشجاعة وحكمة القيادة من أهم أسباب نجاح التوحيد.', image_key: null },
  { grade: 4, bloom: 'analyze', subject: 'social', topic_ar: 'النفط', question_ar: 'ما أثر اكتشاف النفط على المملكة؟', options_ar: ['نهضة اقتصادية وعمرانية شاملة', 'انخفاض الدخل', 'توقف التجارة', 'لا أثر'], correct_answer: '0', explanation_ar: 'النفط حقق نهضة اقتصادية و عمرانية وخدمية شاملة في المملكة.', image_key: null },
  { grade: 4, bloom: 'evaluate', subject: 'social', topic_ar: 'التاريخ', question_ar: 'أيُّ حدثٍ تاريخيٍ أهم في تاريخ المملكة؟', options_ar: ['توحيد المملكة عام ١٣٥١هـ', 'اكتشاف الكهرباء', 'بناء أول مدرسة', 'شراء أول طائرة'], correct_answer: '0', explanation_ar: 'توحيد المملكة أهم حدثٍ لأنه أساس قيام الدولة الحديثة.', image_key: null },
  { grade: 4, bloom: 'evaluate', subject: 'social', topic_ar: 'القرارات', question_ar: 'أيُّ قرارٍ كان أفضل للمملكة؟', options_ar: ['تنويع الاقتصاد في رؤية ٢٠٣٠', 'الاعتماد على مورد واحد', 'إغلاق التجارة', 'تقليل التعليم'], correct_answer: '0', explanation_ar: 'تنويع الاقتصاد يحمي المستقبل من تقلبات أسعار النفط.', image_key: null },
  { grade: 4, bloom: 'create', subject: 'social', topic_ar: 'الخطابة', question_ar: 'اكتب خطبة قصيرة عن حب الوطن', options_ar: ['الوطن نعمةٌ نحفظها بالعمل والولاء والدفاع عنه', 'الوطن للعب فقط', 'لا نحب الوطن', 'الوطن مكان عابر'], correct_answer: '0', explanation_ar: 'الخطبة: تمهيد + فضل الوطن + واجبنا نحوه + خاتمة دعائية.', image_key: null },

  // ════ الصف الخامس (١١) ════
  { grade: 5, bloom: 'remember', subject: 'social', topic_ar: 'قارات العالم', question_ar: 'كم عدد قارات العالم؟', options_ar: ['سبع قارات', 'خمس قارات', 'ثلاث قارات', 'ست قارات'], correct_answer: '0', explanation_ar: 'قارات العالم سبع: آسيا، أفريقيا، أوروبا، أمريكا الشمالية، أمريكا الجنوبية، أستراليا، القارة القطبية الجنوبية.', image_key: null },
  { grade: 5, bloom: 'remember', subject: 'social', topic_ar: 'رؤية ٢٠٣٠', question_ar: 'أيُّ مشروعٍ من مشاريع رؤية ٢٠٣٠؟', options_ar: ['نيوم', 'برج إيفل', 'سور الصين', 'أهرامات الجيزة'], correct_answer: '0', explanation_ar: 'نيوم من أكبر مشاريع رؤية ٢٠٣٠ في شمال المملكة.', image_key: null },
  { grade: 5, bloom: 'understand', subject: 'social', topic_ar: 'نيوم', question_ar: 'أين يقع مشروع نيوم؟', options_ar: ['في شمال غرب المملكة على البحر الأحمر', 'في جنوب المملكة', 'في وسط المملكة', 'في شرق المملكة'], correct_answer: '0', explanation_ar: 'نيوم يقع في شمال غرب المملكة على ساحل البحر الأحمر.', image_key: null },
  { grade: 5, bloom: 'understand', subject: 'social', topic_ar: 'القدية', question_ar: 'ما هو مشروع القدية؟', options_ar: ['مدينة ترفيهية وسياحية كبرى قرب الرياض', 'ميناء بحري', 'مصنع نفط', 'مطار'], correct_answer: '0', explanation_ar: 'القدية مدينة ترفيهية وسياحية ضخمة جنوب الرياض من مشاريع الرؤية.', image_key: null },
  { grade: 5, bloom: 'apply', subject: 'social', topic_ar: 'المناخ', question_ar: 'كيف يؤثر المناخ على الزراعة في المملكة؟', options_ar: ['المناخ الحار يحد من المحاصيل ويتطلب تقنيات حديثة', 'يزيد المحاصيل', 'لا أثر', 'يجعل الزراعة مستحيلة'], correct_answer: '0', explanation_ar: 'المناخ الحار الجاف يتطلب تقنيات حديثة كالري بالتنقيط للزراعة.', image_key: null },
  { grade: 5, bloom: 'apply', subject: 'social', topic_ar: 'السكان', question_ar: 'أين يتركز معظم سكان المملكة؟', options_ar: ['في المدن الكبرى كالرياض وجدة', 'في الصحراء', 'في الجبال', 'في الجزر'], correct_answer: '0', explanation_ar: 'معظم السكان في المدن الكبرى بسبب الخدمات وفرص العمل.', image_key: null },
  { grade: 5, bloom: 'analyze', subject: 'social', topic_ar: 'القارات', question_ar: 'ما الفرق بين قارة آسيا وأفريقيا من حيث المساحة؟', options_ar: ['آسيا أكبر مساحةً من أفريقيا', 'أفريقيا أكبر', 'متساويتان', 'لا فرق'], correct_answer: '0', explanation_ar: 'آسيا أكبر قارات العالم مساحةً وسكاناً، تليها أفريقيا.', image_key: null },
  { grade: 5, bloom: 'analyze', subject: 'social', topic_ar: 'المناخ', question_ar: 'ما أثر المناخ على توزيع السكان؟', options_ar: ['يتركز السكان في المناطق المعتدلة ويقلون في الصحراء', 'لا أثر', 'الصحراء أكثر سكاناً', 'المناخ يزيد السكان في كل مكان'], correct_answer: '0', explanation_ar: 'المناخ يؤثر: المناطق المعتدلة أكثر سكاناً، والصحاري أقل.', image_key: null },
  { grade: 5, bloom: 'evaluate', subject: 'social', topic_ar: 'رؤية ٢٠٣٠', question_ar: ['أيُّ مشروعٍ من رؤية ٢٠٣٠ أفضل للسياحة؟', 'أي مشروع رؤية أفضل للسياحة؟'], correct_answer: '0', options_ar: ['البحر الأحمر ونيوم', 'مصنع بترول', 'سجن', 'مكتب حكومي'], explanation_ar: 'مشروع البحر الأحمر ونيوم سياحيان ويجذبان زوار العالم.', image_key: null },
  { grade: 5, bloom: 'evaluate', subject: 'social', topic_ar: 'القارات', question_ar: 'أيُّ قارةٍ أكثر سكاناً؟', options_ar: ['آسيا', 'أستراليا', 'أمريكا الجنوبية', 'القارة القطبية'], correct_answer: '0', explanation_ar: 'آسيا أكبر قارات العالم سكاناً بأكثر من ٤ مليارات نسمة.', image_key: null },
  { grade: 5, bloom: 'create', subject: 'social', topic_ar: 'نيوم', question_ar: 'صمم عرضاً تعريفياً قصيراً عن مشروع نيوم', options_ar: ['موقع + أهداف + مميزات ذكية + أثر اقتصادي', 'سرد بلا ترتيب', 'صور عشوائية', 'لا شيء'], correct_answer: '0', explanation_ar: 'العرض: تمهيد → موقع → أهداف → مميزات → أثر → خاتمة.', image_key: null },

  // ════ الصف السادس (١٢) ════
  { grade: 6, bloom: 'remember', subject: 'social', topic_ar: 'الحضارات', question_ar: 'أيُّ حضارةٍ قديمةٍ ازدهرت في شبه الجزيرة العربية؟', options_ar: ['حضارة العرب قبل الإسلام', 'الحضارة الرومانية', 'حضارة الإنكا', 'الحضارة اليابانية'], correct_answer: '0', explanation_ar: 'ازدهرت في الجزيرة العربية حضاراتٌ كحضارة معين وسبأ وحمير في اليمن.', image_key: null },
  { grade: 6, bloom: 'remember', subject: 'social', topic_ar: 'الموارد المائية', question_ar: 'ما أكبر مصدرٍ للمياه المحلاة في المملكة؟', options_ar: ['محطات تحلية المياه على السواحل', 'الأنهار', 'الآبار الجوفية فقط', 'الأمطار'], correct_answer: '0', explanation_ar: 'المملكة من أكبر منتجي المياه المحلاة في العالم عبر محطاتها.', image_key: null },
  { grade: 6, bloom: 'understand', subject: 'social', topic_ar: 'الجغرافيا الطبيعية', question_ar: 'ما تضاريس المملكة الغالبة؟', options_ar: ['الصحاري والهضاب', 'الغابات الكثيفة', 'الأنهار الكبيرة', 'الجليد'], correct_answer: '0', explanation_ar: 'يغلب على تضاريس المملكة الصحاري والهضاب كصحراء الربع الخالي.', image_key: null },
  { grade: 6, bloom: 'understand', subject: 'social', topic_ar: 'العلاقات الدولية', question_ar: 'ما دور المملكة في مجلس التعاون الخليجي؟', options_ar: ['عضو مؤسس ودور قيادي', 'عضو مراقب', 'ليست عضواً', 'عضو جديد'], correct_answer: '0', explanation_ar: 'المملكة عضو مؤسس لمجلس التعاون لدول الخليج العربية عام ١٩٨١م.', image_key: null },
  { grade: 6, bloom: 'apply', subject: 'social', topic_ar: 'التجارة الدولية', question_ar: 'ما أهم صادرات المملكة غير النفط في ظل الرؤية؟', options_ar: ['البتروكيماويات والمنتجات الصناعية', 'الأخشاب', 'الملابس المستعملة', 'القمح'], correct_answer: '0', explanation_ar: 'البتروكيماويات والمنتجات الصناعية من أبرز الصادرات غير النفطية.', image_key: null },
  { grade: 6, bloom: 'apply', subject: 'social', topic_ar: 'الموارد', question_ar: 'كيف تسهم تحلية المياه في تنمية المملكة؟', options_ar: ['توفير مياه الشرب للمدن الساحلية والداخلية', 'زيادة العطش', 'تلوث البيئة', 'لا أثر'], correct_answer: '0', explanation_ar: 'تحلية المياه توفر مياه الشرب للمدن وتدعم التنمية العمرانية.', image_key: null },
  { grade: 6, bloom: 'analyze', subject: 'social', topic_ar: 'نهوض الحضارات', question_ar: 'ما العوامل التي ساعدت على نهوض الحضارات القديمة؟', options_ar: ['الموقع الجغرافي والموارد والاستقرار', 'الحروب فقط', 'العزلة', 'لا أسباب'], correct_answer: '0', explanation_ar: 'الموقع الجغرافي والموارد والاستقرار والأمن من عوامل نهوض الحضارات.', image_key: null },
  { grade: 6, bloom: 'analyze', subject: 'social', topic_ar: 'الجغرافيا والاقتصاد', question_ar: 'ما أثر الجغرافيا على الاقتصاد؟', options_ar: ['تحدد الموارد والطرق التجارية وأنماط الاستثمار', 'لا أثر', 'تمنع التجارة', 'تزيد الحروب'], correct_answer: '0', explanation_ar: 'الجغرافيا تحدد الموارد المتاحة والطرق التجارية وفرص الاستثمار.', image_key: null },
  { grade: 6, bloom: 'evaluate', subject: 'social', topic_ar: 'الحضارات', question_ar: 'أيُّ حضارةٍ أكثر إسهاماً في الحضارة الإنسانية؟', options_ar: ['الحضارة الإسلامية بحفظها العلم ونشره', 'حضارة مغمورة', 'لا حضارة', 'حضارة لا أثر لها'], correct_answer: '0', explanation_ar: 'الحضارة الإسلامية أسهمت في العلوم والطب والفلك والفلسفة.', image_key: null },
  { grade: 6, bloom: 'evaluate', subject: 'social', topic_ar: 'الموارد الاقتصادية', question_ar: 'أيُّ موردٍ أكثر ضماناً للمستقبل؟', options_ar: ['الموارد المتجددة كالطاقة الشمسية', 'النفط', 'الفحم', 'الغاز'], correct_answer: '0', explanation_ar: 'الموارد المتجددة كالطاقة الشمسية لا تنفد وأكثر أماناً للمستقبل.', image_key: null },
  { grade: 6, bloom: 'create', subject: 'social', topic_ar: 'مشروع سياحي', question_ar: 'صمم مشروعاً سياحياً مستداماً في منطقتك', options_ar: ['منتجع صديق للبيئة يعتمد الطاقة المتجددة ويحافظ على الحياة الفطرية', 'مصنع ضخم', 'مقلع حجارة', 'مكب نفايات'], correct_answer: '0', explanation_ar: 'المشروع المستدام يجمع بين السياحة والحفاظ على البيئة والطاقة النظيفة.', image_key: null },
  { grade: 6, bloom: 'create', subject: 'social', topic_ar: 'بحث اقتصادي', question_ar: 'ضع خطة بحثٍ عن تنويع الاقتصاد السعودي', options_ar: ['مقدمة + مشكلة الاعتماد على النفط + جهود الرؤية + توصيات', 'سرد عشوائي', 'قصص بلا أدلة', 'لا شيء'], correct_answer: '0', explanation_ar: 'البحث: مقدمة + إشكالية + معالجة + توصيات، منهجٌ علمي.', image_key: null },
];