// المهارات الرقمية - الصف الثاني - الفصل الأول - أسئلة إضافية الوحدتين 4 و 5 + مراجعات
export const COMPUTER_EXTRA_2 = [
  // ── الوحدة 4: الأمان والصحة الرقمية (ص 48-60) ──
  { id:'c151',page:48,type:'multipleChoice',bloom:'remember',difficulty:'easy',
    question:'يجب الجلوس ___ أمام الحاسوب للحفاظ على الظهر.',
    paragraph:'الجلوس المستقيم يحمي الظهر. (ص48)',
    options:[{text:'مستقيماً',correct:true},{text:'منحنياً',correct:false},{text:'مائلاً',correct:false},{text:'راكعاً',correct:false}],
    explanation:'جلوس مستقيم = ظهر سليم + عين مريحة.',
    goldenRule:'جلوس مستقيم = ظهر سليم + عين مريحة.' },
  { id:'c152',page:50,type:'trueFalse',bloom:'understand',difficulty:'easy',
    question:'الشاشة على مستوى العينين وبُعد مناسب تحمي النظر.',
    paragraph:'الشاشة على مستوى العين وبُعد مناسب. (ص50)',
    correctAnswer:true,
    explanation:'شاشة = مستوى عين + بُعد = نظر آمن.',
    goldenRule:'شاشة = مستوى العين + بُعد مناسب = نظر آمن.' },
  { id:'c153',page:52,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف السلوكيات:',
    paragraph:'صحيح: استراحة، إضاءة، استقامة. خاطئ: قرب، ظلام، إطالة. (ص52)',
    categories:['سلوك صحيح ✅','سلوك خاطئ ❌'],
    items:[
      {text:'استراحة كل 30 دقيقة',correct_category:0},{text:'إضاءة مناسبة',correct_category:0},{text:'جلوس مستقيم',correct_category:0},
      {text:'شاشة قريبة جداً',correct_category:1},{text:'الظلام',correct_category:1},{text:'ساعات طويلة بلا راحة',correct_category:1},
    ],
    explanation:'صحيح: راحة، إضاءة، استقامة. خاطئ: قرب، ظلام، إطالة.',
    goldenRule:'صحة رقمية = راحة + إضاءة + استقامة + بُعد.' },
  { id:'c154',page:54,type:'multipleChoice',bloom:'understand',difficulty:'medium',
    question:'مدة الجلوس المناسبة أمام الحاسوب للطفل:',
    paragraph:'30 دقيقة متواصلة حد أقصى للطفل. (ص54)',
    options:[{text:'30 دقيقة ثم استراحة',correct:true},{text:'3 ساعات',correct:false},{text:'طوال اليوم',correct:false},{text:'لا يهم',correct:false}],
    explanation:'30 دقيقة = حد آمن = راحة = عين سليمة.',
    goldenRule:'30 دقيقة = حد آمن. استراح = عين سليمة.' },
  { id:'c155',page:56,type:'trueFalse',bloom:'evaluate',difficulty:'medium',
    question:'لا أعطي اسمي أو صورتي لأحد عبر الإنترنت دون إذن والديّ.',
    paragraph:'لا تشارك بياناتك مع الغرباء. (ص56)',
    correctAnswer:true,
    explanation:'بياناتي = خاصة = لا أشاركها دون إذن.',
    goldenRule:'بياناتي = خاصة. لا أشاركها دون إذن والديّ.' },
  { id:'c156',page:58,type:'multipleChoice',bloom:'evaluate',difficulty:'hard',
    question:'لو رأيت ما يخالف دينك أثناء استخدام الحاسوب:',
    paragraph:'أغلق الشاشة وأخبر الكبار. (ص58)',
    options:[{text:'أغلق الشاشة وأخبر الكبار',correct:true},{text:'أكمل المشاهدة',correct:false},{text:'أرسلها لأصدقائي',correct:false},{text:'أحفظها',correct:false}],
    explanation:'رأيت منكراً = إغلاق + إخبار الكبار.',
    goldenRule:'رأيت منكراً رقمياً = أغلق + أخبر الكبار.',
    feedbackQuestion:{question:'لو وصلك رسالة من غريب، ماذا تفعل؟',
      options:[{text:'لا أرد وأخبر والديّ',correct:true},{text:'أرد عليه',correct:false},{text:'أرسل صورتي',correct:false},{text:'أقابله',correct:false}],
      explanation:'رسائل الغرباء = خطر = لا ترد + أخبر والديك.'} },
  { id:'c157',page:60,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "أحافظ على ___ الحاسوب ولا آكل أو أشرب قربه."',
    paragraph:'لا أكل أو شرب قرب الحاسوب. (ص60)',
    blanks:['نظافة'],
    wordBank:['نظافة','إتلاف','كسر','تخريب'],
    explanation:'طعام وشراب = ضرر للجهاز = نظافة + بعد.',
    goldenRule:'لا أكل ولا شرب قرب الحاسوب = جهاز سليم.' },
  { id:'c158',page:48,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل نصيحة بالسبب:',
    paragraph:'استراحة = راحة العين، إضاءة = وضوح، استقامة = سلامة الظهر، بُعد = حماية النظر. (ص48-52)',
    pairs:[{left:'استراحة',right:'راحة العين'},{left:'إضاءة مناسبة',right:'وضوح الرؤية'},{left:'جلوس مستقيم',right:'سلامة الظهر'},{left:'بُعد الشاشة',right:'حماية النظر'}],
    explanation:'كل نصيحة لها سبب علمي.',
    goldenRule:'صحة رقمية = راحة + إضاءة + استقامة + بُعد.' },
  { id:'c159',page:50,type:'trueFalse',bloom:'understand',difficulty:'easy',
    question:'الجلوس المنحني يضر الظهر.',
    paragraph:'الجلوس المنحني يضر الظهر. (ص50)',
    correctAnswer:true,
    explanation:'انحناء = ضرر ظهر. استقامة = سلامة.',
    goldenRule:'استقامة = سلامة. انحناء = ضرر.' },
  { id:'c160',page:52,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف السلوكيات الصحية:',
    paragraph:'صحيح: راحة، إضاءة، بُعد. خاطئ: قرب، ظلام، إطالة، أكل قرب الجهاز. (ص52)',
    categories:['سلوك صحي ✅','سلوك ضار ❌'],
    items:[
      {text:'راحة منتظمة',correct_category:0},{text:'إضاءة مناسبة',correct_category:0},{text:'بُعد مناسب',correct_category:0},
      {text:'شاشة قريبة',correct_category:1},{text:'ظلام',correct_category:1},{text:'أكل قرب الجهاز',correct_category:1},
    ],
    explanation:'صحيح: راحة، إضاءة، بُعد. ضار: قرب، ظلام، أكل.',
    goldenRule:'صحة رقمية = راحة + إضاءة + بُعد + نظافة.' },
  { id:'c161',page:54,type:'multipleChoice',bloom:'understand',difficulty:'medium',
    question:'الإضاءة المناسبة تكون:',
    paragraph:'إضاءة مناسبة لا شديدة ولا خافتة. (ص54)',
    options:[{text:'مناسبة لا شديدة ولا خافتة',correct:true},{text:'شديدة جداً',correct:false},{text:'مظلمة',correct:false},{text:'لا يهم',correct:false}],
    explanation:'إضاءة مناسبة = وضوح + راحة عين.',
    goldenRule:'إضاءة مناسبة = وضوح + راحة عين.' },
  { id:'c162',page:56,type:'trueFalse',bloom:'evaluate',difficulty:'medium',
    question:'كلمة المرور سر خاص لا أشاركها مع أحد.',
    paragraph:'كلمة المرور سر. (ص56)',
    correctAnswer:true,
    explanation:'كلمة مرور = سر = لا مشاركة = أمان.',
    goldenRule:'كلمة المرور = سر = لا تشاركها مع أحد.' },
  { id:'c163',page:58,type:'ordering',bloom:'apply',difficulty:'medium',
    question:'رتّب خطوات عند رؤية ما يخالف:',
    paragraph:'أغلق الشاشة، ابتعد، أخبر الكبار، لا أعود. (ص58)',
    items:['لا أعود','أخبر الكبار','ابتعد','أغلق الشاشة'],
    correctOrder:[3,2,1,0],
    explanation:'إغلاق ← ابتعاد ← إخبار ← لا عودة.',
    goldenRule:'رأيت منكراً = أغلق + ابتعد + أخبر + لا تعد.' },
  { id:'c164',page:60,type:'fillBlank',bloom:'understand',difficulty:'easy',
    question:'أكمل: "لا أضع ___ على الحاسوب فيحميه من الضرر."',
    paragraph:'لا أكل أو شرب قرب الحاسوب. (ص60)',
    blanks:['طعام'],
    wordBank:['طعام','كتاب','قلم','دفتر'],
    explanation:'طعام = ضرر = ابتعد عن الجهاز.',
    goldenRule:'طعام + شراب = ضرر للجهاز.' },
  { id:'c165',page:48,type:'multipleChoice',bloom:'evaluate',difficulty:'hard',
    question:'لو تعبت عيناك من الشاشة، ما الصواب؟',
    paragraph:'راحة العين واجبة بعد الشاشة. (ص48)',
    options:[{text:'أستريح وأغلق قليلاً',correct:true},{text:'أكمل',correct:false},{text:'أقترب أكثر',correct:false},{text:'أزيد الإضاءة',correct:false}],
    explanation:'تعب = راحة + إغلاق = حماية عين.',
    goldenRule:'تعب العين = راحة + إغلاق = حماية.',
    feedbackQuestion:{question:'لو شعرت بألم في ظهرك من الجلوس، ماذا تفعل؟',
      options:[{text:'أقف وأمشي قليلاً',correct:true},{text:'أكمل الجلوس',correct:false},{text:'أنحني أكثر',correct:false},{text:'أترك الحاسوب',correct:false}],
      explanation:'مشية قصيرة = راحة ظهر = صحة.'} },
  { id:'c166',page:50,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف المواقف:',
    paragraph:'آمن: إذن والديّ، موقع موثوق، راحة منتظمة. خطر: غريب، موقع مجهول، إطالة. (ص50-56)',
    categories:['موقف آمن ✅','موقف خطر ❌'],
    items:[
      {text:'إذن والديّ في الدخول',correct_category:0},{text:'موقع موثوق',correct_category:0},{text:'راحة منتظمة',correct_category:0},
      {text:'محدث غريب',correct_category:1},{text:'موقع مجهول',correct_category:1},{text:'إطالة بلا راحة',correct_category:1},
    ],
    explanation:'آمن: إذن، موثوق، راحة. خطر: غريب، مجهول، إطالة.',
    goldenRule:'أمان = إذن + موثوق + راحة.' },
  { id:'c167',page:52,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل خطر بالحل:',
    paragraph:'غريب = لا ترد، موقع مجهول = لا تدخل، إطالة = استراح، منكر = أغلق + أخبر. (ص52-58)',
    pairs:[{left:'محدث غريب',right:'لا ترد'},{left:'موقع مجهول',right:'لا تدخل'},{left:'إطالة الشاشة',right:'استراح'},{left:'رؤية منكر',right:'أغلق + أخبر'}],
    explanation:'كل خطر له حل.',
    goldenRule:'خطر = حل مناسب = أمان.' },
  { id:'c168',page:54,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "أستريح ___ 30 دقيقة أمام الحاسوب."',
    paragraph:'استراحة كل 30 دقيقة. (ص54)',
    blanks:['كل'],
    wordBank:['كل','بعد','قبل','بدون'],
    explanation:'كل 30 دقيقة = راحة = صحة.',
    goldenRule:'كل 30 دقيقة = راحة = صحة.' },
  { id:'c169',page:56,type:'trueFalse',bloom:'evaluate',difficulty:'hard',
    question:'مشاركة كلمة المرور مع الأصدقاء آمنة.',
    paragraph:'كلمة المرور سر. (ص56)',
    correctAnswer:false,
    explanation:'كلمة مرور = سر = مشاركتها خطر.',
    goldenRule:'كلمة المرور = سر = لا تشاركها.' },
  { id:'c170',page:58,type:'multipleChoice',bloom:'evaluate',difficulty:'hard',
    question:'لو أرسل لك غريب رسالة، ما الصواب؟',
    paragraph:'رسائل الغرباء خطر. (ص58)',
    options:[{text:'لا أرد وأخبر والديّ',correct:true},{text:'أرد عليه',correct:false},{text:'أرسل صورتي',correct:false},{text:'أقابله',correct:false}],
    explanation:'رسالة غريب = لا ترد + أخبر والديك.',
    goldenRule:'رسالة غريب = لا ترد + أخبر والديك.',
    feedbackQuestion:{question:'لو طلب منك غريب لقاء، ماذا تفعل؟',
      options:[{text:'أرفض وأخبر والديّ',correct:true},{text:'أوافق',correct:false},{text:'أفكر',correct:false},{text:'أسأل صديقي',correct:false}],
      explanation:'لقاء غريب = خطر = رفض + إخبار والديك.'} },
  { id:'c171',page:60,type:'ordering',bloom:'apply',difficulty:'medium',
    question:'رتّب عادات صحية أمام الحاسوب:',
    paragraph:'جلوس مستقيم، إضاءة مناسبة، بُعد مناسب، راحة. (ص60)',
    items:['راحة','بُعد مناسب','إضاءة مناسبة','جلوس مستقيم'],
    correctOrder:[3,2,1,0],
    explanation:'جلوس ← إضاءة ← بُعد ← راحة.',
    goldenRule:'صحة رقمية = جلوس + إضاءة + بُعد + راحة.' },
  { id:'c172',page:48,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف الأمان:',
    paragraph:'آمن: إذن والديّ، موقع موثوق، راحة. خطر: غريب، مجهول، إطالة. (ص48-56)',
    categories:['أمان رقمي ✅','خطر رقمي ❌'],
    items:[
      {text:'إذن والديّ',correct_category:0},{text:'موقع موثوق',correct_category:0},{text:'راحة منتظمة',correct_category:0},
      {text:'محدث غريب',correct_category:1},{text:'موقع مجهول',correct_category:1},{text:'إطالة بلا راحة',correct_category:1},
    ],
    explanation:'آمن: إذن، موثوق، راحة. خطر: غريب، مجهول، إطالة.',
    goldenRule:'أمان رقمي = إذن + موثوق + راحة.' },
  { id:'c173',page:50,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل مشكلة بالحل:',
    paragraph:'عين متعبة = راحة، ظهر يؤلمي = استقامة + مشي، شاشة قريبة = بُعد، ظلام = إضاءة. (ص50)',
    pairs:[{left:'عين متعبة',right:'راحة'},{left:'ظهر يؤلمي',right:'استقامة + مشي'},{left:'شاشة قريبة',right:'بُعد'},{left:'ظلام',right:'إضاءة'}],
    explanation:'كل مشكلة لها حل.',
    goldenRule:'مشكلة صحية = حل مناسب.' },
  { id:'c174',page:52,type:'fillBlank',bloom:'understand',difficulty:'easy',
    question:'أكمل: "الجلوس المستقيم يحافظ على ___."',
    paragraph:'الجلوس المستقيم يحمي الظهر. (ص52)',
    blanks:['الظهر'],
    wordBank:['الظهر','العين','الأذن','الأسنان'],
    explanation:'استقامة = ظهر سليم.',
    goldenRule:'استقامة = ظهر سليم.' },
  { id:'c175',page:54,type:'trueFalse',bloom:'understand',difficulty:'easy',
    question:'الإضاءة الشديدة جداً تضر العين.',
    paragraph:'الإضاءة الشديدة تضر العين. (ص54)',
    correctAnswer:true,
    explanation:'إضاءة شديدة = ضرر عين = اعتدال = راحة.',
    goldenRule:'إضاءة معتدلة = راحة عين.' },
  { id:'c176',page:56,type:'multipleChoice',bloom:'remember',difficulty:'easy',
    question:'من معلوماتي الشخصية:',
    paragraph:'معلومات شخصية: اسمي، صورتي، عنواني، رقم هاتفي. (ص56)',
    options:[{text:'اسمي وصورتي وعنواني',correct:true},{text:'اسم المدرسة',correct:false},{text:'اسم الدولة',correct:false},{text:'اسم الجار',correct:false}],
    explanation:'شخصية = اسم + صورة + عنوان + هاتف = لا تشارك.',
    goldenRule:'معلوماتي الشخصية = سر = لا أشاركها.' },
  { id:'c177',page:58,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف المواقع:',
    paragraph:'موثوق: موقع رسمي، تعليمي، معروف. غير موثوق: غريب، مجهول، مشبوه. (ص58)',
    categories:['مواقع موثوقة ✅','مواقع غير موثوقة ❌'],
    items:[
      {text:'موقع رسمي',correct_category:0},{text:'موقع تعليمي',correct_category:0},{text:'موقع معروف',correct_category:0},
      {text:'موقع غريب',correct_category:1},{text:'موقع مجهول',correct_category:1},{text:'موقع مشبوه',correct_category:1},
    ],
    explanation:'موثوق: رسمي، تعليمي، معروف. غير: غريب، مجهول، مشبوه.',
    goldenRule:'موقع موثوق = أمان. مجهول = خطر.' },
  { id:'c178',page:60,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل نصيحة بالسبب:',
    paragraph:'راحة = عين، استقامة = ظهر، بُعد = نظر، إضاءة = وضوح. (ص60)',
    pairs:[{left:'راحة',right:'عين'},{left:'استقامة',right:'ظهر'},{left:'بُعد',right:'نظر'},{left:'إضاءة',right:'وضوح'}],
    explanation:'كل نصيحة لها فائدة صحية.',
    goldenRule:'نصائح صحية = راحة + استقامة + بُعد + إضاءة.' },
  { id:'c179',page:48,type:'ordering',bloom:'apply',difficulty:'medium',
    question:'رتّب خطوات بقاء صحي أمام الحاسوب:',
    paragraph:'جلوس مستقيم، بُعد مناسب، إضاءة مناسبة، راحة. (ص48-52)',
    items:['راحة','إضاءة مناسبة','بُعد مناسب','جلوس مستقيم'],
    correctOrder:[3,2,1,0],
    explanation:'جلوس ← بُعد ← إضاءة ← راحة.',
    goldenRule:'صحة = جلوس + بُعد + إضاءة + راحة.' },
  { id:'c180',page:50,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "الشاشة على مستوى ___ لا أعلى ولا أسفل."',
    paragraph:'الشاشة على مستوى العينين. (ص50)',
    blanks:['العينين'],
    wordBank:['العينين','الكتف','الركبة','القدم'],
    explanation:'شاشة = مستوى العينين = راحة عنق + نظر.',
    goldenRule:'شاشة = مستوى العينين = راحة.' },
  { id:'c181',page:52,type:'trueFalse',bloom:'evaluate',difficulty:'medium',
    question:'الجلوس الطويل بلا راحة يسبب آلام الظهر.',
    paragraph:'الجلوس الطويل يضر الظهر. (ص52)',
    correctAnswer:true,
    explanation:'جلوس طويل = ألم ظهر = راحة = علاج.',
    goldenRule:'جلوس طويل = ألم. راحة = علاج.' },
  { id:'c182',page:54,type:'multipleChoice',bloom:'understand',difficulty:'medium',
    question:'من آداب الأمان الرقمي:',
    paragraph:'أمان رقمي: إذن والديّ، موقع موثوق، راحة، لا مشاركة بيانات. (ص54-56)',
    options:[{text:'إذن والديّ + موقع موثوق + لا مشاركة بيانات',correct:true},{text:'مشاركة كلمة المرور',correct:false},{text:'دخول مواقع مجهولة',correct:false},{text:'محدث غريب',correct:false}],
    explanation:'أمان = إذن + موثوق + لا مشاركة + راحة.',
    goldenRule:'أمان رقمي = إذن + موثوق + لا مشاركة + راحة.' },
  { id:'c183',page:56,type:'classify',bloom:'analyze',difficulty:'hard',
    question:'صنّف المعلومات:',
    paragraph:'شخصية: اسمي، صورتي، عنواني، هاتفي. عامة: اسم المدرسة، اسم الدولة، اسم الجار. (ص56)',
    categories:['معلومات شخصية 🔒','معلومات عامة 📢'],
    items:[
      {text:'اسمي',correct_category:0},{text:'صورتي',correct_category:0},{text:'عنواني',correct_category:0},{text:'رقم هاتفي',correct_category:0},
      {text:'اسم المدرسة',correct_category:1},{text:'اسم الدولة',correct_category:1},
    ],
    explanation:'شخصية = اسم، صورة، عنوان، هاتف = سر. عامة = لا ضرر بمشاركتها.',
    goldenRule:'معلومات شخصية = سر. عامة = لا ضرر.' },
  { id:'c184',page:58,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل خطر بالإجراء:',
    paragraph:'محدث غريب = لا ترد، موقع مجهول = لا تدخل، منكر = أغلق، إطالة = استراح. (ص58)',
    pairs:[{left:'محدث غريب',right:'لا ترد'},{left:'موقع مجهول',right:'لا تدخل'},{left:'منكر',right:'أغلق'},{left:'إطالة',right:'استراح'}],
    explanation:'كل خطر له إجراء مناسب.',
    goldenRule:'خطر = إجراء = أمان.' },
  { id:'c185',page:60,type:'fillBlank',bloom:'understand',difficulty:'easy',
    question:'أكمل: "لا آكل ولا أشرب ___ الحاسوب."',
    paragraph:'لا أكل ولا شرب قرب الحاسوب. (ص60)',
    blanks:['قرب'],
    wordBank:['قرب','بعيد','خلف','أمام'],
    explanation:'قرب = خطر انسكاب = ضرر جهاز.',
    goldenRule:'لا أكل ولا شرب قرب الجهاز = سلامة.' },
  { id:'c186',page:48,type:'trueFalse',bloom:'evaluate',difficulty:'medium',
    question:'الجلوس المستقيم أمام الحاسوب يحمي الظهر والعين.',
    paragraph:'الجلوس المستقيم = ظهر + عين. (ص48)',
    correctAnswer:true,
    explanation:'استقامة = ظهر + عين = صحة.',
    goldenRule:'استقامة = ظهر + عين = صحة.' },
  { id:'c187',page:50,type:'multipleChoice',bloom:'understand',difficulty:'medium',
    question:'الشاشة القريبة جداً تضر:',
    paragraph:'الشاشة القريبة تضر العين. (ص50)',
    options:[{text:'العين',correct:true},{text:'الأذن',correct:false},{text:'الأسنان',correct:false},{text:'الشعر',correct:false}],
    explanation:'قرب شاشة = إجهاد عين = بُعد = حماية.',
    goldenRule:'بُعد الشاشة = حماية العين.' },
  { id:'c188',page:52,type:'ordering',bloom:'apply',difficulty:'medium',
    question:'رتّب عادات صحية أمام الشاشة:',
    paragraph:'جلوس مستقيم، بُعد مناسب، إضاءة، راحة. (ص52)',
    items:['راحة','إضاءة','بُعد مناسب','جلوس مستقيم'],
    correctOrder:[3,2,1,0],
    explanation:'جلوس ← بُعد ← إضاءة ← راحة.',
    goldenRule:'صحة = جلوس + بُعد + إضاءة + راحة.' },
  { id:'c189',page:54,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف السلوكيات:',
    paragraph:'صحيح: راحة 30 دقيقة، إضاءة، بُعد. ضار: قرب، ظلام، إطالة. (ص54)',
    categories:['سلوك صحي ✅','سلوك ضار ❌'],
    items:[
      {text:'راحة 30 دقيقة',correct_category:0},{text:'إضاءة مناسبة',correct_category:0},{text:'بُعد مناسب',correct_category:0},
      {text:'قرب الشاشة',correct_category:1},{text:'ظلام',correct_category:1},{text:'إطالة',correct_category:1},
    ],
    explanation:'صحيح: راحة، إضاءة، بُعد. ضار: قرب، ظلام، إطالة.',
    goldenRule:'صحة رقمية = راحة + إضاءة + بُعد.' },
  { id:'c190',page:56,type:'trueFalse',bloom:'evaluate',difficulty:'hard',
    question:'مشاركة عنواني مع غريب آمنة.',
    paragraph:'لا تشارك معلوماتك الشخصية. (ص56)',
    correctAnswer:false,
    explanation:'عنواني = شخصي = لا أشاركه مع الغرباء.',
    goldenRule:'عنواني = شخصي = سر = لا أشاركه.' },
  { id:'c191',page:58,type:'multipleChoice',bloom:'evaluate',difficulty:'hard',
    question:'لو طلب منك غريب صورة لك، ما الصواب؟',
    paragraph:'لا ترسل صورك للغرباء. (ص58)',
    options:[{text:'أرفض وأخبر والديّ',correct:true},{text:'أرسلها',correct:false},{text:'أفكر',correct:false},{text:'أسأل صديقي',correct:false}],
    explanation:'صورتي = شخصية = لا أرسلها للغرباء.',
    goldenRule:'صورتي = شخصية = لا أرسلها للغرباء.',
    feedbackQuestion:{question:'لو طلب منك زميل كلمة مرورك، ماذا تفعل؟',
      options:[{text:'لا أعطيها لأحد',correct:true},{text:'أعطيها',correct:false},{text:'أفكر',correct:false},{text:'أسأل',correct:false}],
      explanation:'كلمة المرور = سر = لا أعطيها لأحد.'} },
  { id:'c192',page:60,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "أحافظ على نظافة الحاسوب ولا ___ قربه."',
    paragraph:'لا أكل أو شرب قرب الحاسوب. (ص60)',
    blanks:['آكل'],
    wordBank:['آكل','أنام','أكتب','أقرأ'],
    explanation:'طعام = ضرر = نظافة + بعد.',
    goldenRule:'لا أكل قرب الجهاز = نظافة + سلامة.' },
  { id:'c193',page:48,type:'ordering',bloom:'apply',difficulty:'medium',
    question:'رتّب نصائح الأمان الرقمي:',
    paragraph:'إذن والديّ، موقع موثوق، لا مشاركة بيانات، راحة. (ص48-56)',
    items:['راحة','لا مشاركة بيانات','موقع موثوق','إذن والديّ'],
    correctOrder:[3,2,1,0],
    explanation:'إذن ← موثوق ← لا مشاركة ← راحة.',
    goldenRule:'أمان رقمي = إذن + موثوق + لا مشاركة + راحة.' },
  { id:'c194',page:50,type:'trueFalse',bloom:'remember',difficulty:'easy',
    question:'الشاشة على مستوى العين تحمي النظر والرقبة.',
    paragraph:'الشاشة على مستوى العين. (ص50)',
    correctAnswer:true,
    explanation:'مستوى عين = نظر + رقبة = صحة.',
    goldenRule:'شاشة = مستوى العين = نظر + رقبة.' },
  { id:'c195',page:52,type:'classify',bloom:'analyze',difficulty:'hard',
    question:'صنّف المواقف:',
    paragraph:'آمن: إذن والديّ، موثوق، راحة. خطر: غريب، مجهول، إطالة. (ص52)',
    categories:['موقف آمن ✅','موقف خطر ❌'],
    items:[
      {text:'إذن والديّ',correct_category:0},{text:'موقع موثوق',correct_category:0},{text:'راحة منتظمة',correct_category:0},
      {text:'محدث غريب',correct_category:1},{text:'موقع مجهول',correct_category:1},{text:'إطالة بلا راحة',correct_category:1},
    ],
    explanation:'آمن: إذن، موثوق، راحة. خطر: غريب، مجهول، إطالة.',
    goldenRule:'أمان = إذن + موثوق + راحة.' },

  // ── الوحدة 5: الرسم والكتابة البسيطة (ص 62-74) ──
  { id:'c196',page:62,type:'multipleChoice',bloom:'remember',difficulty:'easy',
    question:'برنامج الرسم يُستخدم لـ:',
    paragraph:'برنامج الرسم لتلوين ورسم الأشكال. (ص62)',
    options:[{text:'تلوين ورسم الأشكال',correct:true},{text:'النوم',correct:false},{text:'الأكل',correct:false},{text:'السباحة',correct:false}],
    explanation:'برنامج الرسم = ألوان + أشكال = إبداع.',
    goldenRule:'برنامج الرسم = ألوان + أشكال = إبداع رقمي.' },
  { id:'c197',page:64,type:'trueFalse',bloom:'understand',difficulty:'easy',
    question:'يمكنني تغيير لون الفرشاة في برنامج الرسم.',
    paragraph:'برنامج الرسم يتيح اختيار الألوان. (ص64)',
    correctAnswer:true,
    explanation:'برنامج الرسم = ألوان + فرش = حرية إبداع.',
    goldenRule:'برنامج الرسم = ألوان + فرش = حرية إبداع.' },
  { id:'c198',page:66,type:'multipleChoice',bloom:'apply',difficulty:'medium',
    question:'لحفظ رسمتي في برنامج الرسم أختار:',
    paragraph:'ملف ← حفظ باسم. (ص66)',
    options:[{text:'ملف ← حفظ',correct:true},{text:'إطفاء الحاسوب',correct:false},{text:'حذف الرسمة',correct:false},{text:'إغلاق النافذة',correct:false}],
    explanation:'حفظ = ملف ← حفظ ← اسم ← مكان.',
    goldenRule:'حفظ عملك = ملف ← حفظ ← اسم ← مكان.' },
  { id:'c199',page:68,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف أدوات برنامج الرسم:',
    paragraph:'رسم: فرشاة، قلم، ألوان، أشكال. كتابة: لوحة مفاتيح، نص. (ص68)',
    categories:['أدوات الرسم 🎨','أدوات الكتابة ✍️'],
    items:[
      {text:'الفرشاة',correct_category:0},{text:'القلم الرقمي',correct_category:0},{text:'الألوان',correct_category:0},{text:'الأشكال',correct_category:0},
      {text:'لوحة المفاتيح',correct_category:1},{text:'أداة النص',correct_category:1},
    ],
    explanation:'رسم = فرش/ألوان/أشكال. كتابة = لوحة/نص.',
    goldenRule:'رسم = فرش/ألوان. كتابة = لوحة مفاتيح/نص.' },
  { id:'c200',page:70,type:'matching',bloom:'understand',difficulty:'medium',
    question:'صِل كل أداة بوظيفتها:',
    paragraph:'الفرشاة للرسم الحر، الألوان للتلوين، الأشكال لجاهز، الممحاة للمسح. (ص70)',
    pairs:[{left:'الفرشاة',right:'الرسم الحر'},{left:'الألوان',right:'التلوين'},{left:'الأشكال',right:'أشكال جاهزة'},{left:'الممحاة',right:'المسح'}],
    explanation:'كل أداة لها وظيفة في برنامج الرسم.',
    goldenRule:'فرشاة=رسم، لون=تلوين، شكل=جاهز، ممحاة=مسح.' },
  { id:'c201',page:72,type:'trueFalse',bloom:'apply',difficulty:'easy',
    question:'أستطيع كتابة اسمي على الحاسوب باستخدام لوحة المفاتيح.',
    paragraph:'لوحة المفاتيح للكتابة. (ص72)',
    correctAnswer:true,
    explanation:'كتابة = لوحة مفاتيح = حروف + أرقام.',
    goldenRule:'الكتابة على الحاسوب = لوحة المفاتيح = حروف وأرقام.' },
  { id:'c202',page:74,type:'ordering',bloom:'apply',difficulty:'medium',
    question:'رتّب خطوات رسم وتلوين شجرة ثم حفظها:',
    paragraph:'افتح برنامج الرسم، ارسم الشجرة، لوّنها، احفظ. (ص74)',
    items:['احفظ الرسمة','لوّن الشجرة','ارسم الشجرة','افتح برنامج الرسم'],
    correctOrder:[3,2,1,0],
    explanation:'فتح ← رسم ← تلوين ← حفظ.',
    goldenRule:'رسم رقمي = فتح ← رسم ← تلوين ← حفظ.' },
  { id:'c203',page:62,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "في برنامج الرسم أختار ___ لألوّن رسمتي."',
    paragraph:'الألوان للتلوين. (ص64)',
    blanks:['الألوان'],
    wordBank:['الألوان','الممحاة','الحذف','الإغلاق'],
    explanation:'ألوان = تلوين. فرشاة = رسم. ممحاة = مسح.',
    goldenRule:'ألوان = تلوين. فرشاة = رسم. ممحاة = مسح.' },
  { id:'c204',page:64,type:'multipleChoice',bloom:'understand',difficulty:'medium',
    question:'من أدوات برنامج الرسم:',
    paragraph:'أدوات الرسم: فرشاة، قلم، ألوان، أشكال، ممحاة. (ص64)',
    options:[{text:'فرشاة + قلم + ألوان + أشكال',correct:true},{text:'ثلاجة',correct:false},{text:'سيارة',correct:false},{text:'كرسي',correct:false}],
    explanation:'أدوات الرسم = فرشاة + قلم + ألوان + أشكال.',
    goldenRule:'أدوات الرسم = فرشاة + قلم + ألوان + أشكال.' },
  { id:'c205',page:66,type:'trueFalse',bloom:'apply',difficulty:'easy',
    question:'لحفظ رسمتي أختار ملف ثم حفظ.',
    paragraph:'ملف ← حفظ باسم. (ص66)',
    correctAnswer:true,
    explanation:'حفظ = ملف ← حفظ ← اسم ← مكان.',
    goldenRule:'حفظ = ملف ← حفظ ← اسم ← مكان.' },
  { id:'c206',page:68,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف أدوات برنامج الرسم:',
    paragraph:'رسم: فرشاة، قلم، أشكال. مسح: ممحاة، حذف. كتابة: نص. (ص68)',
    categories:['أدوات رسم وإضافة 🎨','أدوات مسح وحذف 🗑️'],
    items:[
      {text:'الفرشاة',correct_category:0},{text:'القلم',correct_category:0},{text:'الأشكال',correct_category:0},{text:'الألوان',correct_category:0},
      {text:'الممحاة',correct_category:1},{text:'الحذف',correct_category:1},
    ],
    explanation:'رسم/إضافة: فرش، قلم، أشكال، ألوان. مسح/حذف: ممحاة، حذف.',
    goldenRule:'رسم = فرش/قلم/أشكال. مسح = ممحاة/حذف.' },
  { id:'c207',page:70,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل أداة بوظيفتها:',
    paragraph:'الفرشاة = رسم حر، القلم = كتابة بيد، الأشكال = مربع/دائرة، الممحاة = مسح. (ص70)',
    pairs:[{left:'الفرشاة',right:'رسم حر'},{left:'القلم',right:'كتابة بيد'},{left:'الأشكال',right:'مربع/دائرة'},{left:'الممحاة',right:'مسح'}],
    explanation:'كل أداة لها وظيفة محددة.',
    goldenRule:'كل أداة = وظيفة محددة.' },
  { id:'c208',page:72,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "للكتابة على الحاسوب أستخدم ___."',
    paragraph:'لوحة المفاتيح للكتابة. (ص72)',
    blanks:['لوحة المفاتيح'],
    wordBank:['لوحة المفاتيح','الفأرة','الشاشة','الطابعة'],
    explanation:'كتابة = لوحة مفاتيح = حروف + أرقام.',
    goldenRule:'الكتابة = لوحة المفاتيح = حروف + أرقام.' },
  { id:'c209',page:74,type:'ordering',bloom:'apply',difficulty:'medium',
    question:'رتّب خطوات كتابة اسمك على الحاسوب:',
    paragraph:'افتح برنامج الكتابة، اكتب اسمك بلوحة المفاتيح، احفظ. (ص74)',
    items:['احفظ','اكتب اسمك','افتح برنامج الكتابة'],
    correctOrder:[2,1,0],
    explanation:'فتح ← كتابة ← حفظ.',
    goldenRule:'كتابة رقمية = فتح ← كتابة ← حفظ.' },
  { id:'c210',page:62,type:'multipleChoice',bloom:'understand',difficulty:'medium',
    question:'برنامج الرسم يحتوي على:',
    paragraph:'برنامج الرسم = فرش + ألوان + أشكال + ممحاة. (ص62)',
    options:[{text:'فرش + ألوان + أشكال + ممحاة',correct:true},{text:'أكل',correct:false},{text:'نوم',correct:false},{text:'لعب',correct:false}],
    explanation:'برنامج الرسم = فرش + ألوان + أشكال + ممحاة.',
    goldenRule:'برنامج الرسم = فرش + ألوان + أشكال + ممحاة.' },
  { id:'c211',page:64,type:'trueFalse',bloom:'understand',difficulty:'easy',
    question:'برنامج الرسم يتيح اختيار لون من قائمة الألوان.',
    paragraph:'برنامج الرسم يتيح الألوان. (ص64)',
    correctAnswer:true,
    explanation:'ألوان = اختيار + تلوين = إبداع.',
    goldenRule:'ألوان = اختيار + تلوين = إبداع.' },
  { id:'c212',page:66,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف خطوات العمل في برنامج الرسم:',
    paragraph:'قبل: فتح، اختيار أداة. أثناء: رسم، تلوين. بعد: حفظ، إغلاق. (ص66)',
    categories:['قبل البدء 🚀','بعد الانتهاء 💾'],
    items:[
      {text:'فتح البرنامج',correct_category:0},{text:'اختيار الأداة',correct_category:0},
      {text:'حفظ العمل',correct_category:1},{text:'إغلاق البرنامج',correct_category:1},
    ],
    explanation:'قبل: فتح، اختيار. بعد: حفظ، إغلاق.',
    goldenRule:'قبل البدء = فتح + اختيار. بعد = حفظ + إغلاق.' },
  { id:'c213',page:68,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل خطوة بنتيجتها:',
    paragraph:'فتح = بداية، رسم = عمل، تلوين = جمال، حفظ = سلامة. (ص68)',
    pairs:[{left:'فتح البرنامج',right:'بداية'},{left:'الرسم',right:'عمل'},{left:'التلوين',right:'جمال'},{left:'الحفظ',right:'سلامة'}],
    explanation:'كل خطوة لها نتيجة.',
    goldenRule:'خطوة = نتيجة. اختار الترتيب الصحيح.' },
  { id:'c214',page:70,type:'fillBlank',bloom:'understand',difficulty:'easy',
    question:'أكمل: "للتلوين أستخدم ___ من برنامج الرسم."',
    paragraph:'الألوان للتلوين. (ص70)',
    blanks:['الألوان'],
    wordBank:['الألوان','الممحاة','الحذف','الإغلاق'],
    explanation:'ألوان = تلوين = جمال.',
    goldenRule:'ألوان = تلوين = جمال.' },
  { id:'c215',page:72,type:'trueFalse',bloom:'apply',difficulty:'easy',
    question:'أستطيع كتابة الحروف على الحاسوب باستخدام لوحة المفاتيح.',
    paragraph:'لوحة المفاتيح للكتابة. (ص72)',
    correctAnswer:true,
    explanation:'كتابة = لوحة مفاتيح = حروف + أرقام.',
    goldenRule:'الكتابة = لوحة المفاتيح = حروف + أرقام.' },
  { id:'c216',page:74,type:'ordering',bloom:'apply',difficulty:'medium',
    question:'رتّب خطوات عمل فني في برنامج الرسم:',
    paragraph:'افتح البرنامج، اختر الفرشاة، ارسم، لوّن، احفظ. (ص74)',
    items:['احفظ','لوّن','ارسم','اختر الفرشاة','افتح البرنامج'],
    correctOrder:[4,3,2,1,0],
    explanation:'فتح ← اختيار ← رسم ← تلوين ← حفظ.',
    goldenRule:'عمل فني = فتح ← اختيار ← رسم ← تلوين ← حفظ.' },
  { id:'c217',page:62,type:'multipleChoice',bloom:'evaluate',difficulty:'hard',
    question:'لو أردت إكمال رسمتي غداً، ماذا أفعل بعد رسمها؟',
    paragraph:'لإكمال العمل لاحقاً احفظه باسم معروف. (ص62)',
    options:[{text:'أحفظها باسم معروف في مكان معروف',correct:true},{text:'أغلق دون حفظ',correct:false},{text:'أحذفها',correct:false},{text:'أتركها',correct:false}],
    explanation:'حفظ باسم + مكان = إيجاد لاحقاً = إكمال.',
    goldenRule:'حفظ ذكي = اسم + مكان = سهولة الإيجاد لاحقاً.',
    feedbackQuestion:{question:'لو نسيت مكان حفظ رسمتك، ماذا يحدث؟',
      options:[{text:'لا أجدها',correct:true},{text:'أجدها بسهولة',correct:false},{text:'لا يهم',correct:false},{text:'تطبع وحدها',correct:false}],
      explanation:'حفظ بلا اسم/مكان = صعوبة إيجاد.'} },
  { id:'c218',page:64,type:'trueFalse',bloom:'understand',difficulty:'easy',
    question:'الفرشاة في برنامج الرسم للرسم الحر.',
    paragraph:'الفرشاة للرسم الحر. (ص64)',
    correctAnswer:true,
    explanation:'فرشاة = رسم حر = إبداع.',
    goldenRule:'فرشاة = رسم حر = إبداع.' },
  { id:'c219',page:66,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف أدوات برنامج الرسم:',
    paragraph:'رسم: فرشاة، قلم. تلوين: ألوان. جاهز: أشكال. مسح: ممحاة. (ص66)',
    categories:['أدوات رسم وتلوين 🎨','أدوات مسح 🗑️'],
    items:[
      {text:'الفرشاة',correct_category:0},{text:'القلم',correct_category:0},{text:'الألوان',correct_category:0},{text:'الأشكال',correct_category:0},
      {text:'الممحاة',correct_category:1},
    ],
    explanation:'رسم/تلوين: فرش، قلم، ألوان، أشكال. مسح: ممحاة.',
    goldenRule:'رسم = فرش/قلم/ألوان/أشكال. مسح = ممحاة.' },
  { id:'c220',page:68,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل أداة بوصفها:',
    paragraph:'الفرشاة = سميكة، القلم = رفيعة، الأشكال = جاهزة، الألوان = متعددة. (ص68)',
    pairs:[{left:'الفرشاة',right:'سميكة'},{left:'القلم',right:'رفيعة'},{left:'الأشكال',right:'جاهزة'},{left:'الألوان',right:'متعددة'}],
    explanation:'كل أداة لها وصفها.',
    goldenRule:'كل أداة = وصف + وظيفة.' },
  { id:'c221',page:70,type:'fillBlank',bloom:'understand',difficulty:'easy',
    question:'أكمل: "للمسح في برنامج الرسم أستخدم ___."',
    paragraph:'الممحاة للمسح. (ص70)',
    blanks:['الممحاة'],
    wordBank:['الممحاة','الفرشاة','القلم','الألوان'],
    explanation:'ممحاة = مسح = تصحيح.',
    goldenRule:'ممحاة = مسح = تصحيح.' },
  { id:'c222',page:72,type:'trueFalse',bloom:'apply',difficulty:'easy',
    question:'للكتابة أضغط على مفاتيح الحروف في لوحة المفاتيح.',
    paragraph:'لوحة المفاتيح للكتابة. (ص72)',
    correctAnswer:true,
    explanation:'كتابة = ضغط مفاتيح = حروف + أرقام.',
    goldenRule:'الكتابة = ضغط مفاتيح = حروف + أرقام.' },
  { id:'c223',page:74,type:'ordering',bloom:'apply',difficulty:'medium',
    question:'رتّب خطوات كتابة جملة على الحاسوب:',
    paragraph:'افتح برنامج الكتابة، اكتب الجملة بلوحة المفاتيح، احفظ. (ص74)',
    items:['احفظ','اكتب الجملة','افتح برنامج الكتابة'],
    correctOrder:[2,1,0],
    explanation:'فتح ← كتابة ← حفظ.',
    goldenRule:'كتابة رقمية = فتح ← كتابة ← حفظ.' },
  { id:'c224',page:62,type:'multipleChoice',bloom:'remember',difficulty:'easy',
    question:'برنامج الرسم أداة لل:',
    paragraph:'برنامج الرسم للإبداع الفني. (ص62)',
    options:[{text:'إبداع فني',correct:true},{text:'نوم',correct:false},{text:'أكل',correct:false},{text:'سباحة',correct:false}],
    explanation:'رسم = إبداع فني = ألوان + أشكال.',
    goldenRule:'برنامج الرسم = إبداع فني = ألوان + أشكال.' },
  { id:'c225',page:64,type:'trueFalse',bloom:'understand',difficulty:'easy',
    question:'يمكنني تغيير حجم الفرشاة في برنامج الرسم.',
    paragraph:'برنامج الرسم يتيح تغيير حجم الفرشاة. (ص64)',
    correctAnswer:true,
    explanation:'حجم فرشاة = اختيار = دقة الرسم.',
    goldenRule:'حجم الفرشاة = اختيار = دقة الرسم.' },
  { id:'c226',page:66,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف خطوات العمل:',
    paragraph:'بداية: فتح، اختيار أداة. وسط: رسم، تلوين. نهاية: حفظ، إغلاق. (ص66)',
    categories:['بداية ووسط العمل 🎨','نهاية العمل 💾'],
    items:[
      {text:'فتح البرنامج',correct_category:0},{text:'اختيار الفرشاة',correct_category:0},{text:'الرسم',correct_category:0},{text:'التلوين',correct_category:0},
      {text:'حفظ العمل',correct_category:1},{text:'إغلاق البرنامج',correct_category:1},
    ],
    explanation:'بداية/وسط: فتح، اختيار، رسم، تلوين. نهاية: حفظ، إغلاق.',
    goldenRule:'عمل فني = بداية + وسط + نهاية.' },
  { id:'c227',page:68,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل أداة بنتيجتها:',
    paragraph:'الفرشاة = رسم، الألوان = تلوين، الأشكال = جاهز، الممحاة = مسح. (ص68)',
    pairs:[{left:'الفرشاة',right:'رسم'},{left:'الألوان',right:'تلوين'},{left:'الأشكال',right:'جاهز'},{left:'الممحاة',right:'مسح'}],
    explanation:'كل أداة = نتيجة محددة.',
    goldenRule:'أداة = نتيجة. اختار الأداة المناسبة.' },
  { id:'c228',page:70,type:'fillBlank',bloom:'understand',difficulty:'easy',
    question:'أكمل: "لرسم مربع أختار ___ من برنامج الرسم."',
    paragraph:'الأشكال لرسم مربع/دائرة. (ص70)',
    blanks:['الأشكال'],
    wordBank:['الأشكال','الممحاة','القلم','الألوان'],
    explanation:'أشكال = جاهز = مربع + دائرة.',
    goldenRule:'أشكال = جاهز = مربع + دائرة.' },
  { id:'c229',page:72,type:'trueFalse',bloom:'apply',difficulty:'easy',
    question:'لحفظ ما كتبته أختار ملف ثم حفظ.',
    paragraph:'ملف ← حفظ. (ص72)',
    correctAnswer:true,
    explanation:'حفظ = ملف ← حفظ ← اسم ← مكان.',
    goldenRule:'حفظ = ملف ← حفظ ← اسم ← مكان.' },
  { id:'c230',page:74,type:'ordering',bloom:'apply',difficulty:'medium',
    question:'رتّب عمل فني كامل:',
    paragraph:'افتح، اختر فرشاة، ارسم، لوّن، احفظ، أغلق. (ص74)',
    items:['أغلق','احفظ','لوّن','ارسم','اختر فرشاة','افتح'],
    correctOrder:[5,4,3,2,1,0],
    explanation:'فتح ← اختيار ← رسم ← تلوين ← حفظ ← إغلاق.',
    goldenRule:'عمل فني = فتح ← اختيار ← رسم ← تلوين ← حفظ ← إغلاق.' },
  { id:'c231',page:62,type:'multipleChoice',bloom:'evaluate',difficulty:'hard',
    question:'لو أردت تصحيح خطأ في رسمتي، ماذا أستخدم؟',
    paragraph:'الممحاة للمسح والتصحيح. (ص62)',
    options:[{text:'الممحاة',correct:true},{text:'الفرشاة',correct:false},{text:'الألوان',correct:false},{text:'الأشكال',correct:false}],
    explanation:'ممحاة = مسح + تصحيح = خطأ يزول.',
    goldenRule:'الممحاة = مسح + تصحيح = خطأ يزول.',
    feedbackQuestion:{question:'لو لونت خارج الخط، كيف تصحح؟',
      options:[{text:'أستخدم الممحاة',correct:true},{text:'أكمل التلوين',correct:false},{text:'أحذف الكل',correct:false},{text:'أغلق البرنامج',correct:false}],
      explanation:'ممحاة = مسح الجزء الخطأ = تصحيح.'} },
  { id:'c232',page:64,type:'trueFalse',bloom:'understand',difficulty:'easy',
    question:'الأشكال الجاهزة تساعد في رسم دائرة أو مربع بسرعة.',
    paragraph:'الأشكال لرسم جاهز. (ص64)',
    correctAnswer:true,
    explanation:'أشكال = جاهز = دائرة + مربع = سرعة.',
    goldenRule:'أشكال = جاهز = سرعة الرسم.' },
  { id:'c233',page:66,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف أدوات برنامج الرسم:',
    paragraph:'رسم: فرشاة، قلم. تلوين: ألوان. جاهز: أشكال. مسح: ممحاة. (ص66)',
    categories:['أدوات إضافة 🎨','أدوات مسح 🗑️'],
    items:[
      {text:'الفرشاة',correct_category:0},{text:'القلم',correct_category:0},{text:'الألوان',correct_category:0},{text:'الأشكال',correct_category:0},
      {text:'الممحاة',correct_category:1},{text:'الحذف',correct_category:1},
    ],
    explanation:'إضافة: فرش، قلم، ألوان، أشكال. مسح: ممحاة، حذف.',
    goldenRule:'إضافة = فرش/قلم/ألوان/أشكال. مسح = ممحاة/حذف.' },
  { id:'c234',page:68,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل أداة بشكلها:',
    paragraph:'الفرشاة = عريضة، القلم = رفيعة، الأشكال = مربع/دائرة، الممحاة = مسح. (ص68)',
    pairs:[{left:'الفرشاة',right:'عريضة'},{left:'القلم',right:'رفيعة'},{left:'الأشكال',right:'مربع/دائرة'},{left:'الممحاة',right:'مسح'}],
    explanation:'كل أداة لها شكلها الخاص.',
    goldenRule:'كل أداة = شكل + وظيفة.' },
  { id:'c235',page:70,type:'fillBlank',bloom:'understand',difficulty:'easy',
    question:'أكمل: "لحفظ رسمتي أختار ملف ثم ___."',
    paragraph:'ملف ← حفظ. (ص70)',
    blanks:['حفظ'],
    wordBank:['حفظ','حذف','طباعة','إغلاق'],
    explanation:'حفظ = ملف ← حفظ = سلامة العمل.',
    goldenRule:'حفظ = ملف ← حفظ = سلامة العمل.' },
  { id:'c236',page:72,type:'trueFalse',bloom:'apply',difficulty:'easy',
    question:'للكتابة أضغط مفاتيح الحروف ثم Enter.',
    paragraph:'لوحة المفاتيح + Enter. (ص72)',
    correctAnswer:true,
    explanation:'كتابة = مفاتيح + Enter = تأكيد.',
    goldenRule:'الكتابة = مفاتيح + Enter = تأكيد.' },
  { id:'c237',page:74,type:'ordering',bloom:'apply',difficulty:'medium',
    question:'رتّب خطوات رسم دائرة وتلوينها:',
    paragraph:'افتح البرنامج، اختر الأشكال، ارسم دائرة، لوّنها، احفظ. (ص74)',
    items:['احفظ','لوّن الدائرة','ارسم دائرة','اختر الأشكال','افتح البرنامج'],
    correctOrder:[4,3,2,1,0],
    explanation:'فتح ← أشكال ← دائرة ← تلوين ← حفظ.',
    goldenRule:'رسم دائرة = فتح ← أشكال ← دائرة ← تلوين ← حفظ.' },
  { id:'c238',page:62,type:'multipleChoice',bloom:'understand',difficulty:'medium',
    question:'برنامج الرسم يحتاج:',
    paragraph:'برنامج الرسم يحتاج حاسوب + فأرة/لمس. (ص62)',
    options:[{text:'حاسوب + فأرة أو لمس',correct:true},{text:'ثلاجة',correct:false},{text:'سيارة',correct:false},{text:'قلم رصاص',correct:false}],
    explanation:'برنامج الرسم = حاسوب + فأرة/لمس = عمل.',
    goldenRule:'برنامج الرسم = حاسوب + فأرة/لمس = عمل.' },
  { id:'c239',page:64,type:'trueFalse',bloom:'understand',difficulty:'easy',
    question:'في برنامج الرسم أستطيع رسم خطوط مستقيمة ومنحنية.',
    paragraph:'برنامج الرسم يتيح خطوط. (ص64)',
    correctAnswer:true,
    explanation:'خطوط = مستقيمة + منحنية = فرشاة/قلم.',
    goldenRule:'خطوط = مستقيمة + منحنية = فرشاة/قلم.' },
  { id:'c240',page:66,type:'classify',bloom:'analyze',difficulty:'hard',
    question:'صنّف أعمال برنامج الرسم:',
    paragraph:'رسم: خطوط، أشكال. تلوين: ألوان. تصحيح: مسح. حفظ: ملف. (ص66)',
    categories:['أعمال إبداعية 🎨','أعمال تنظيمية 💾'],
    items:[
      {text:'رسم خطوط',correct_category:0},{text:'رسم أشكال',correct_category:0},{text:'التلوين',correct_category:0},
      {text:'حفظ العمل',correct_category:1},{text:'فتح البرنامج',correct_category:1},
    ],
    explanation:'إبداع: رسم، أشكال، تلوين. تنظيم: حفظ، فتح.',
    goldenRule:'برنامج الرسم = إبداع + تنظيم = عمل متكامل.' },
  { id:'c241',page:68,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل عمل بنتيجته:',
    paragraph:'رسم = شكل، تلوين = جمال، مسح = تصحيح، حفظ = سلامة. (ص68)',
    pairs:[{left:'الرسم',right:'شكل'},{left:'التلوين',right:'جمال'},{left:'المسح',right:'تصحيح'},{left:'الحفظ',right:'سلامة'}],
    explanation:'كل عمل = نتيجة.',
    goldenRule:'عمل = نتيجة. اختار العمل المناسب.' },
  { id:'c242',page:70,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "برنامج الرسم يحتوي على فرشاة وقلم و___ وممحاة."',
    paragraph:'برنامج الرسم = فرش + قلم + ألوان + ممحاة. (ص70)',
    blanks:['ألوان'],
    wordBank:['ألوان','ثلاجة','سيارة','كرسي'],
    explanation:'ألوان = تلوين = جمال.',
    goldenRule:'برنامج الرسم = فرش + قلم + ألوان + ممحاة.' },
  { id:'c243',page:72,type:'trueFalse',bloom:'apply',difficulty:'easy',
    question:'لحفظ ما كتبته أضغط ملف ثم حفظ.',
    paragraph:'ملف ← حفظ. (ص72)',
    correctAnswer:true,
    explanation:'حفظ = ملف ← حفظ = سلامة.',
    goldenRule:'حفظ = ملف ← حفظ = سلامة.' },
  { id:'c244',page:74,type:'ordering',bloom:'apply',difficulty:'medium',
    question:'رتّب كتابة وتنسيق جملة:',
    paragraph:'افتح برنامج الكتابة، اكتب الجملة، اختر لوناً، احفظ. (ص74)',
    items:['احفظ','اختر لوناً','اكتب الجملة','افتح برنامج الكتابة'],
    correctOrder:[3,2,1,0],
    explanation:'فتح ← كتابة ← لون ← حفظ.',
    goldenRule:'كتابة منسقة = فتح ← كتابة ← لون ← حفظ.' },
  { id:'c245',page:62,type:'multipleChoice',bloom:'evaluate',difficulty:'hard',
    question:'لو أردت طباعة رسمتي، ماذا أحتاج إضافاً؟',
    paragraph:'للطباعة أحتاج طابعة. (ص62)',
    options:[{text:'طابعة مربوطة بالحاسوب',correct:true},{text:'ثلاجة',correct:false},{text:'سيارة',correct:false},{text:'تلفاز',correct:false}],
    explanation:'طباعة = طابعة + حاسوب + رسمة محفوظة.',
    goldenRule:'طباعة = طابعة + حاسوب + عمل محفوظ.',
    feedbackQuestion:{question:'لو لم تكن الطابعة مربوطة، ماذا يحدث؟',
      options:[{text:'لا تتم الطباعة',correct:true},{text:'تتم بسرعة',correct:false},{text:'لا يهم',correct:false},{text:'تطبع وحدها',correct:false}],
      explanation:'الطابعة تحتاج ربطاً بالحاسوب = لا طباعة بلا ربط.'} },
  { id:'c246',page:64,type:'trueFalse',bloom:'understand',difficulty:'easy',
    question:'برنامج الرسم يحتوي على ألوان كثيرة.',
    paragraph:'برنامج الرسم = ألوان كثيرة. (ص64)',
    correctAnswer:true,
    explanation:'ألوان كثيرة = اختيار + إبداع.',
    goldenRule:'ألوان كثيرة = اختيار + إبداع.' },
  { id:'c247',page:66,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف أدوات برنامج الرسم:',
    paragraph:'رسم: فرشاة، قلم. تلوين: ألوان. جاهز: أشكال. مسح: ممحاة. (ص66)',
    categories:['أدوات خلق 🎨','أدوات حذف 🗑️'],
    items:[
      {text:'الفرشاة',correct_category:0},{text:'القلم',correct_category:0},{text:'الألوان',correct_category:0},{text:'الأشكال',correct_category:0},
      {text:'الممحاة',correct_category:1},
    ],
    explanation:'خلق: فرش، قلم، ألوان، أشكال. حذف: ممحاة.',
    goldenRule:'خلق = فرش/قلم/ألوان/أشكال. حذف = ممحاة.' },
  { id:'c248',page:68,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل أداة بلونها:',
    paragraph:'الفرشاة = أبيض/أسود، القلم = دقيق، الألوان = متعددة، الممحاة = محو. (ص68)',
    pairs:[{left:'الفرشاة',right:'عريضة'},{left:'القلم',right:'دقيقة'},{left:'الألوان',right:'متعددة'},{left:'الممحاة',right:'محو'}],
    explanation:'كل أداة لها وصفها.',
    goldenRule:'كل أداة = وصف + وظيفة.' },
  { id:'c249',page:70,type:'fillBlank',bloom:'understand',difficulty:'easy',
    question:'أكمل: "لرسم خط مستقيم أستخدم ___ أو القلم."',
    paragraph:'الفرشاة أو القلم للخطوط. (ص70)',
    blanks:['الفرشاة'],
    wordBank:['الفرشاة','الممحاة','الأشكال','الحفظ'],
    explanation:'فرشاة/قلم = خطوط = رسم.',
    goldenRule:'فرشاة/قلم = خطوط = رسم.' },
  { id:'c250',page:72,type:'trueFalse',bloom:'apply',difficulty:'easy',
    question:'للكتابة على الحاسوب أستخدم لوحة المفاتيح لا الفأرة.',
    paragraph:'الكتابة بلوحة المفاتيح. (ص72)',
    correctAnswer:true,
    explanation:'كتابة = لوحة مفاتيح. توجيه = فأرة.',
    goldenRule:'كتابة = لوحة مفاتيح. توجيه = فأرة.' },
  { id:'c251',page:74,type:'ordering',bloom:'apply',difficulty:'medium',
    question:'رتّب عمل فني كامل وحفظه:',
    paragraph:'افتح، ارسم، لوّن، احفظ، أغلق. (ص74)',
    items:['أغلق','احفظ','لوّن','ارسم','افتح'],
    correctOrder:[4,3,2,1,0],
    explanation:'فتح ← رسم ← تلوين ← حفظ ← إغلاق.',
    goldenRule:'عمل فني = فتح ← رسم ← تلوين ← حفظ ← إغلاق.' },
  { id:'c252',page:62,type:'multipleChoice',bloom:'understand',difficulty:'medium',
    question:'برنامج الرسم من برامج:',
    paragraph:'برنامج الرسم برنامج إبداعي. (ص62)',
    options:[{text:'الإبداع الفني',correct:true},{text:'الأكل',correct:false},{text:'النوم',correct:false},{text:'السباحة',correct:false}],
    explanation:'برنامج الرسم = إبداع فني = ألوان + أشكال.',
    goldenRule:'برنامج الرسم = إبداع فني = ألوان + أشكال.' },
  { id:'c253',page:64,type:'trueFalse',bloom:'remember',difficulty:'easy',
    question:'برنامج الرسم يحتاج مهارة وفن.',
    paragraph:'برنامج الرسم = فن + مهارة. (ص64)',
    correctAnswer:true,
    explanation:'رسم = فن + مهارة = إبداع.',
    goldenRule:'رسم = فن + مهارة = إبداع.' },
  { id:'c254',page:66,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف ما يفعله برنامج الرسم:',
    paragraph:'يضيف: رسم، تلوين، أشكال. يزيل: مسح، حذف. يحفظ: حفظ. (ص66)',
    categories:['يضيف ويزيد 🎨','يزيل ويحفظ 🗑️💾'],
    items:[
      {text:'الرسم',correct_category:0},{text:'التلوين',correct_category:0},{text:'الأشكال',correct_category:0},
      {text:'المسح',correct_category:1},{text:'الحفظ',correct_category:1},
    ],
    explanation:'يضيف: رسم، تلوين، أشكال. يزيل/يحفظ: مسح، حذف، حفظ.',
    goldenRule:'برنامج الرسم = إضافة + إزالة + حفظ.' },
  { id:'c255',page:68,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل أداة بنتيجتها:',
    paragraph:'الفرشاة = رسم حر، الألوان = تلوين، الأشكال = جاهز، الممحاة = مسح. (ص68)',
    pairs:[{left:'الفرشاة',right:'رسم حر'},{left:'الألوان',right:'تلوين'},{left:'الأشكال',right:'جاهز'},{left:'الممحاة',right:'مسح'}],
    explanation:'كل أداة = نتيجة محددة.',
    goldenRule:'أداة = نتيجة. اختار الأداة المناسبة.' },
  { id:'c256',page:70,type:'fillBlank',bloom:'understand',difficulty:'easy',
    question:'أكمل: "برنامج الرسم أداة لل___ الفني."',
    paragraph:'برنامج الرسم للإبداع الفني. (ص70)',
    blanks:['إبداع'],
    wordBank:['إبداع','أكل','نوم','سباحة'],
    explanation:'رسم = إبداع فني = ألوان + أشكال.',
    goldenRule:'برنامج الرسم = إبداع فني = ألوان + أشكال.' },
  { id:'c257',page:72,type:'trueFalse',bloom:'apply',difficulty:'easy',
    question:'لحفظ رسمتي أضغط ملف ثم حفظ.',
    paragraph:'ملف ← حفظ. (ص72)',
    correctAnswer:true,
    explanation:'حفظ = ملف ← حفظ = سلامة.',
    goldenRule:'حفظ = ملف ← حفظ = سلامة.' },
  { id:'c258',page:74,type:'ordering',bloom:'apply',difficulty:'medium',
    question:'رتّب عمل إبداعي كامل:',
    paragraph:'افتح، اختر لون، ارسم، لوّن، احفظ. (ص74)',
    items:['احفظ','لوّن','ارسم','اختر لون','افتح'],
    correctOrder:[4,3,2,1,0],
    explanation:'فتح ← لون ← رسم ← تلوين ← حفظ.',
    goldenRule:'إبداع = فتح ← لون ← رسم ← تلوين ← حفظ.' },
  { id:'c259',page:62,type:'multipleChoice',bloom:'evaluate',difficulty:'hard',
    question:'لو أردت إرسال رسمتي لصديق، ماذا أحتاج؟',
    paragraph:'لإرسال رسمتي أحتاج حفظها ثم إرسالها. (ص62)',
    options:[{text:'أحفظها ثم أرسلها بأمان بإذن والديّ',correct:true},{text:'أرسلها بلا حفظ',correct:false},{text:'أطبعها فقط',correct:false},{text:'أحذفها',correct:false}],
    explanation:'حفظ + إرسال آمن + إذن والديّ = سلامة.',
    goldenRule:'إرسال = حفظ + آمن + إذن والديّ.',
    feedbackQuestion:{question:'لو أردت مشاركة رسمتك مع العائلة فقط، كيف؟',
      options:[{text:'أحفظها وأعرضها على العائلة',correct:true},{text:'أنشرها للجميع',correct:false},{text:'أحذفها',correct:false},{text:'أتركها',correct:false}],
      explanation:'مشاركة العائلة = حفظ + عرض = أمان.'} },
  { id:'c260',page:64,type:'trueFalse',bloom:'understand',difficulty:'easy',
    question:'برنامج الرسم يحتوي على أدوات كثيرة للإبداع.',
    paragraph:'برنامج الرسم = أدوات كثيرة. (ص64)',
    correctAnswer:true,
    explanation:'أدوات كثيرة = فرش + قلم + ألوان + أشكال + ممحاة = إبداع.',
    goldenRule:'أدوات كثيرة = إبداع واسع.' },
  { id:'c261',page:66,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف أدوات برنامج الرسم حسب الوظيفة:',
    paragraph:'رسم: فرشاة، قلم، أشكال. تلوين: ألوان. مسح: ممحاة. (ص66)',
    categories:['رسم وتلوين 🎨','مسح وتصحيح 🗑️'],
    items:[
      {text:'الفرشاة',correct_category:0},{text:'القلم',correct_category:0},{text:'الأشكال',correct_category:0},{text:'الألوان',correct_category:0},
      {text:'الممحاة',correct_category:1},{text:'الحذف',correct_category:1},
    ],
    explanation:'رسم/تلوين: فرش، قلم، أشكال، ألوان. مسح/تصحيح: ممحاة، حذف.',
    goldenRule:'رسم/تلوين = فرش/قلم/أشكال/ألوان. مسح = ممحاة/حذف.' },
  { id:'c262',page:68,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل خطوة بالأداة المناسبة:',
    paragraph:'رسم حر = فرشاة، رسم دقيق = قلم، تلوين = ألوان، مسح = ممحاة. (ص68)',
    pairs:[{left:'رسم حر',right:'الفرشاة'},{left:'رسم دقيق',right:'القلم'},{left:'التلوين',right:'الألوان'},{left:'المسح',right:'الممحاة'}],
    explanation:'كل خطوة لها أداة مناسبة.',
    goldenRule:'خطوة + أداة = عمل صحيح.' },
  { id:'c263',page:70,type:'fillBlank',bloom:'understand',difficulty:'easy',
    question:'أكمل: "في برنامج الرسم أختار ___ لرسم دائرة جاهزة."',
    paragraph:'الأشكال لرسم جاهز. (ص70)',
    blanks:['الأشكال'],
    wordBank:['الأشكال','الممحاة','القلم','الحفظ'],
    explanation:'أشكال = دائرة + مربع = جاهز.',
    goldenRule:'أشكال = جاهز = دائرة + مربع.' },
  { id:'c264',page:72,type:'trueFalse',bloom:'apply',difficulty:'easy',
    question:'للكتابة على الحاسوب أستخدم لوحة المفاتيح.',
    paragraph:'لوحة المفاتيح للكتابة. (ص72)',
    correctAnswer:true,
    explanation:'كتابة = لوحة مفاتيح = حروف + أرقام.',
    goldenRule:'الكتابة = لوحة المفاتيح = حروف + أرقام.' },
  { id:'c265',page:74,type:'ordering',bloom:'apply',difficulty:'medium',
    question:'رتّب عمل رقمي كامل:',
    paragraph:'تشغيل، فتح برنامج، عمل (رسم/كتابة)، حفظ، إطفاء آمن. (ص74)',
    items:['إطفاء آمن','حفظ العمل','عمل','فتح برنامج','تشغيل'],
    correctOrder:[4,3,2,1,0],
    explanation:'تشغيل ← فتح ← عمل ← حفظ ← إطفاء.',
    goldenRule:'عمل رقمي = تشغيل ← فتح ← عمل ← حفظ ← إطفاء.' },
  { id:'c266',page:62,type:'multipleChoice',bloom:'remember',difficulty:'easy',
    question:'برنامج الرسم من برامج:',
    paragraph:'برنامج الرسم برنامج إبداعي. (ص62)',
    options:[{text:'الإبداع الفني',correct:true},{text:'الأكل',correct:false},{text:'النوم',correct:false},{text:'اللعب',correct:false}],
    explanation:'برنامج الرسم = إبداع فني = ألوان + أشكال.',
    goldenRule:'برنامج الرسم = إبداع فني = ألوان + أشكال.' },
  { id:'c267',page:64,type:'trueFalse',bloom:'understand',difficulty:'easy',
    question:'برنامج الرسم يحتاج إبداعاً لا مهارة فقط.',
    paragraph:'برنامج الرسم = إبداع + مهارة. (ص64)',
    correctAnswer:true,
    explanation:'رسم = إبداع + مهارة = فن.',
    goldenRule:'رسم = إبداع + مهارة = فن.' },
  { id:'c268',page:66,type:'classify',bloom:'analyze',difficulty:'hard',
    question:'صنّف أدوات برنامج الرسم:',
    paragraph:'رسم: فرشاة، قلم. تلوين: ألوان. جاهز: أشكال. مسح: ممحاة. (ص66)',
    categories:['أدوات خلق وإضافة 🎨','أدوات مسح وتصحيح 🗑️'],
    items:[
      {text:'الفرشاة',correct_category:0},{text:'القلم',correct_category:0},{text:'الألوان',correct_category:0},{text:'الأشكال',correct_category:0},
      {text:'الممحاة',correct_category:1},{text:'الحذف',correct_category:1},
    ],
    explanation:'خلق/إضافة: فرش، قلم، ألوان، أشكال. مسح/تصحيح: ممحاة، حذف.',
    goldenRule:'خلق = فرش/قلم/ألوان/أشكال. تصحيح = ممحاة/حذف.' },
  { id:'c269',page:68,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل أداة بنتيجتها:',
    paragraph:'الفرشاة = رسم حر، القلم = دقيق، الألوان = تلوين، الممحاة = مسح. (ص68)',
    pairs:[{left:'الفرشاة',right:'رسم حر'},{left:'القلم',right:'دقيق'},{left:'الألوان',right:'تلوين'},{left:'الممحاة',right:'مسح'}],
    explanation:'كل أداة = نتيجة.',
    goldenRule:'أداة = نتيجة. اختار الأداة المناسبة.' },
  { id:'c270',page:70,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "برنامج الرسم = فرشاة + قلم + ألوان + ___."',
    paragraph:'برنامج الرسم = فرش + قلم + ألوان + ممحاة. (ص70)',
    blanks:['ممحاة'],
    wordBank:['ممحاة','ثلاجة','سيارة','كرسي'],
    explanation:'ممحاة = مسح + تصحيح.',
    goldenRule:'برنامج الرسم = فرش + قلم + ألوان + ممحاة.' },
  { id:'c271',page:72,type:'trueFalse',bloom:'apply',difficulty:'easy',
    question:'للكتابة على الحاسوب أستخدم لوحة المفاتيح.',
    paragraph:'لوحة المفاتيح للكتابة. (ص72)',
    correctAnswer:true,
    explanation:'كتابة = لوحة مفاتيح = حروف + أرقام.',
    goldenRule:'الكتابة = لوحة المفاتيح = حروف + أرقام.' },
  { id:'c272',page:74,type:'ordering',bloom:'apply',difficulty:'medium',
    question:'رتّب عمل إبداعي:',
    paragraph:'افتح البرنامج، اختر الأداة، ارسم، لوّن، احفظ. (ص74)',
    items:['احفظ','لوّن','ارسم','اختر الأداة','افتح البرنامج'],
    correctOrder:[4,3,2,1,0],
    explanation:'فتح ← اختيار ← رسم ← تلوين ← حفظ.',
    goldenRule:'إبداع = فتح ← اختيار ← رسم ← تلوين ← حفظ.' },
  { id:'c273',page:62,type:'multipleChoice',bloom:'evaluate',difficulty:'hard',
    question:'لو أردت إكمال رسمتي في يوم آخر، ما الصواب؟',
    paragraph:'لإكمال العمل احفظه باسم معروف. (ص62)',
    options:[{text:'أحفظه باسم ومكان معروفين',correct:true},{text:'أغلق بلا حفظ',correct:false},{text:'أحذفه',correct:false},{text:'أتركه',correct:false}],
    explanation:'حفظ + اسم + مكان = إيجاد لاحقاً = إكمال.',
    goldenRule:'حفظ ذكي = اسم + مكان = سهولة الإيجاد.',
    feedbackQuestion:{question:'لو أردت تعديل رسمتك المحفوظة، ماذا تفعل أولاً؟',
      options:[{text:'أفتح الملف المحفوظ',correct:true},{text:'أرسم من جديد',correct:false},{text:'أحذفه',correct:false},{text:'أتركه',correct:false}],
      explanation:'تعديل = فتح المحفوظ = ثم تعديل.'} },
  { id:'c274',page:64,type:'trueFalse',bloom:'understand',difficulty:'easy',
    question:'برنامج الرسم يتيح تغيير حجم ولون الفرشاة.',
    paragraph:'برنامج الرسم يتيح تغيير الفرشاة. (ص64)',
    correctAnswer:true,
    explanation:'حجم + لون = دقة + إبداع.',
    goldenRule:'حجم + لون = دقة + إبداع.' },
  { id:'c275',page:66,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف أدوات برنامج الرسم:',
    paragraph:'رسم: فرشاة، قلم، أشكال. تلوين: ألوان. مسح: ممحاة. (ص66)',
    categories:['أدوات خلق 🎨','أدوات تصحيح 🗑️'],
    items:[
      {text:'الفرشاة',correct_category:0},{text:'القلم',correct_category:0},{text:'الأشكال',correct_category:0},{text:'الألوان',correct_category:0},
      {text:'الممحاة',correct_category:1},
    ],
    explanation:'خلق: فرش، قلم، أشكال، ألوان. تصحيح: ممحاة.',
    goldenRule:'خلق = فرش/قلم/أشكال/ألوان. تصحيح = ممحاة.' },
  { id:'c276',page:68,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل أداة بوظيفتها:',
    paragraph:'الفرشاة = رسم حر، القلم = كتابة بيد، الأشكال = جاهز، الممحاة = مسح. (ص68)',
    pairs:[{left:'الفرشاة',right:'رسم حر'},{left:'القلم',right:'كتابة بيد'},{left:'الأشكال',right:'جاهز'},{left:'الممحاة',right:'مسح'}],
    explanation:'كل أداة لها وظيفة محددة.',
    goldenRule:'كل أداة = وظيفة محددة.' },
  { id:'c277',page:70,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "للتلوين أستخدم ___ من برنامج الرسم."',
    paragraph:'الألوان للتلوين. (ص70)',
    blanks:['الألوان'],
    wordBank:['الألوان','الممحاة','الحذف','الإغلاق'],
    explanation:'ألوان = تلوين = جمال.',
    goldenRule:'ألوان = تلوين = جمال.' },
  { id:'c278',page:72,type:'trueFalse',bloom:'apply',difficulty:'easy',
    question:'للكتابة على الحاسوب أستخدم لوحة المفاتيح لا الفأرة.',
    paragraph:'الكتابة بلوحة المفاتيح. (ص72)',
    correctAnswer:true,
    explanation:'كتابة = لوحة مفاتيح. توجيه = فأرة.',
    goldenRule:'كتابة = لوحة مفاتيح. توجيه = فأرة.' },
  { id:'c279',page:74,type:'ordering',bloom:'apply',difficulty:'medium',
    question:'رتّب عمل رقمي كامل:',
    paragraph:'تشغيل، فتح برنامج، عمل، حفظ، إطفاء آمن. (ص74)',
    items:['إطفاء آمن','حفظ العمل','عمل','فتح برنامج','تشغيل'],
    correctOrder:[4,3,2,1,0],
    explanation:'تشغيل ← فتح ← عمل ← حفظ ← إطفاء.',
    goldenRule:'عمل رقمي = تشغيل ← فتح ← عمل ← حفظ ← إطفاء.' },
  { id:'c280',page:62,type:'multipleChoice',bloom:'remember',difficulty:'easy',
    question:'برنامج الرسم أداة لل:',
    paragraph:'برنامج الرسم للإبداع الفني. (ص62)',
    options:[{text:'إبداع فني',correct:true},{text:'أكل',correct:false},{text:'نوم',correct:false},{text:'سباحة',correct:false}],
    explanation:'برنامج الرسم = إبداع فني = ألوان + أشكال.',
    goldenRule:'برنامج الرسم = إبداع فني = ألوان + أشكال.' },
  { id:'c281',page:64,type:'trueFalse',bloom:'understand',difficulty:'easy',
    question:'برنامج الرسم يحتاج إبداعاً وفناً.',
    paragraph:'برنامج الرسم = إبداع + فن. (ص64)',
    correctAnswer:true,
    explanation:'رسم = إبداع + فن = ألوان + أشكال.',
    goldenRule:'رسم = إبداع + فن = ألوان + أشكال.' },
  { id:'c282',page:66,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف أدوات برنامج الرسم:',
    paragraph:'رسم: فرشاة، قلم. تلوين: ألوان. جاهز: أشكال. مسح: ممحاة. (ص66)',
    categories:['أدوات إضافة 🎨','أدوات مسح 🗑️'],
    items:[
      {text:'الفرشاة',correct_category:0},{text:'القلم',correct_category:0},{text:'الألوان',correct_category:0},{text:'الأشكال',correct_category:0},
      {text:'الممحاة',correct_category:1},
    ],
    explanation:'إضافة: فرش، قلم، ألوان، أشكال. مسح: ممحاة.',
    goldenRule:'إضافة = فرش/قلم/ألوان/أشكال. مسح = ممحاة.' },
  { id:'c283',page:68,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل أداة بنتيجتها:',
    paragraph:'الفرشاة = رسم حر، الألوان = تلوين، الأشكال = جاهز، الممحاة = مسح. (ص68)',
    pairs:[{left:'الفرشاة',right:'رسم حر'},{left:'الألوان',right:'تلوين'},{left:'الأشكال',right:'جاهز'},{left:'الممحاة',right:'مسح'}],
    explanation:'كل أداة = نتيجة محددة.',
    goldenRule:'أداة = نتيجة. اختار الأداة المناسبة.' },
  { id:'c284',page:70,type:'fillBlank',bloom:'understand',difficulty:'easy',
    question:'أكمل: "لحفظ رسمتي أختار ملف ثم ___."',
    paragraph:'ملف ← حفظ. (ص70)',
    blanks:['حفظ'],
    wordBank:['حفظ','حذف','طباعة','إغلاق'],
    explanation:'حفظ = ملف ← حفظ = سلامة العمل.',
    goldenRule:'حفظ = ملف ← حفظ = سلامة العمل.' },
  { id:'c285',page:72,type:'trueFalse',bloom:'apply',difficulty:'easy',
    question:'للكتابة على الحاسوب أستخدم لوحة المفاتيح.',
    paragraph:'لوحة المفاتيح للكتابة. (ص72)',
    correctAnswer:true,
    explanation:'كتابة = لوحة مفاتيح = حروف + أرقام.',
    goldenRule:'الكتابة = لوحة المفاتيح = حروف + أرقام.' },
  { id:'c286',page:74,type:'ordering',bloom:'apply',difficulty:'medium',
    question:'رتّب عمل رقمي كامل:',
    paragraph:'تشغيل، فتح برنامج، عمل، حفظ، إطفاء آمن. (ص74)',
    items:['إطفاء آمن','حفظ العمل','عمل','فتح برنامج','تشغيل'],
    correctOrder:[4,3,2,1,0],
    explanation:'تشغيل ← فتح ← عمل ← حفظ ← إطفاء.',
    goldenRule:'عمل رقمي = تشغيل ← فتح ← عمل ← حفظ ← إطفاء.' },
  { id:'c287',page:62,type:'multipleChoice',bloom:'evaluate',difficulty:'hard',
    question:'لو أردت مشاركة رسمتي مع عائلتي بأمان، ما الصواب؟',
    paragraph:'مشاركة العائلة = حفظ + عرض. (ص62)',
    options:[{text:'أحفظها وأعرضها على العائلة بإذن والديّ',correct:true},{text:'أنشرها للجميع',correct:false},{text:'أحذفها',correct:false},{text:'أتركها',correct:false}],
    explanation:'مشاركة عائلية = حفظ + عرض + إذن = أمان.',
    goldenRule:'مشاركة آمنة = حفظ + عرض + إذن والديّ.',
    feedbackQuestion:{question:'لو أردت طباعة رسمتك، ماذا تحتاج؟',
      options:[{text:'طابعة مربوطة بالحاسوب',correct:true},{text:'ثلاجة',correct:false},{text:'تلفاز',correct:false},{text:'سيارة',correct:false}],
      explanation:'طباعة = طابعة + حاسوب + عمل محفوظ.'} },
  { id:'c288',page:64,type:'trueFalse',bloom:'understand',difficulty:'easy',
    question:'برنامج الرسم يحتوي على ألوان كثيرة للاختيار.',
    paragraph:'برنامج الرسم = ألوان كثيرة. (ص64)',
    correctAnswer:true,
    explanation:'ألوان كثيرة = اختيار + إبداع.',
    goldenRule:'ألوان كثيرة = اختيار + إبداع.' },
  { id:'c289',page:66,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف أدوات برنامج الرسم:',
    paragraph:'رسم: فرشاة، قلم، أشكال. تلوين: ألوان. مسح: ممحاة. (ص66)',
    categories:['أدوات رسم وتلوين 🎨','أدوات مسح 🗑️'],
    items:[
      {text:'الفرشاة',correct_category:0},{text:'القلم',correct_category:0},{text:'الأشكال',correct_category:0},{text:'الألوان',correct_category:0},
      {text:'الممحاة',correct_category:1},
    ],
    explanation:'رسم/تلوين: فرش، قلم، أشكال، ألوان. مسح: ممحاة.',
    goldenRule:'رسم/تلوين = فرش/قلم/أشكال/ألوان. مسح = ممحاة.' },
  { id:'c290',page:68,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل أداة بنتيجتها:',
    paragraph:'الفرشاة = رسم حر، الألوان = تلوين، الأشكال = جاهز، الممحاة = مسح. (ص68)',
    pairs:[{left:'الفرشاة',right:'رسم حر'},{left:'الألوان',right:'تلوين'},{left:'الأشكال',right:'جاهز'},{left:'الممحاة',right:'مسح'}],
    explanation:'كل أداة = نتيجة محددة.',
    goldenRule:'أداة = نتيجة. اختار الأداة المناسبة.' },
  { id:'c291',page:70,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "برنامج الرسم = فرشاة + قلم + ___ + ممحاة."',
    paragraph:'برنامج الرسم = فرش + قلم + ألوان + ممحاة. (ص70)',
    blanks:['ألوان'],
    wordBank:['ألوان','ثلاجة','سيارة','كرسي'],
    explanation:'ألوان = تلوين = جمال.',
    goldenRule:'برنامج الرسم = فرش + قلم + ألوان + ممحاة.' },
  { id:'c292',page:72,type:'trueFalse',bloom:'apply',difficulty:'easy',
    question:'للكتابة على الحاسوب أستخدم لوحة المفاتيح.',
    paragraph:'لوحة المفاتيح للكتابة. (ص72)',
    correctAnswer:true,
    explanation:'كتابة = لوحة مفاتيح = حروف + أرقام.',
    goldenRule:'الكتابة = لوحة المفاتيح = حروف + أرقام.' },
  { id:'c293',page:74,type:'ordering',bloom:'apply',difficulty:'medium',
    question:'رتّب عمل رقمي كامل:',
    paragraph:'تشغيل، فتح برنامج، عمل، حفظ، إطفاء آمن. (ص74)',
    items:['إطفاء آمن','حفظ العمل','عمل','فتح برنامج','تشغيل'],
    correctOrder:[4,3,2,1,0],
    explanation:'تشغيل ← فتح ← عمل ← حفظ ← إطفاء.',
    goldenRule:'عمل رقمي = تشغيل ← فتح ← عمل ← حفظ ← إطفاء.' },
  { id:'c294',page:62,type:'multipleChoice',bloom:'understand',difficulty:'medium',
    question:'برنامج الرسم يحتاج:',
    paragraph:'برنامج الرسم يحتاج حاسوب + فأرة/لمس. (ص62)',
    options:[{text:'حاسوب + فأرة أو لمس',correct:true},{text:'ثلاجة',correct:false},{text:'سيارة',correct:false},{text:'قلم رصاص',correct:false}],
    explanation:'برنامج الرسم = حاسوب + فأرة/لمس = عمل.',
    goldenRule:'برنامج الرسم = حاسوب + فأرة/لمس = عمل.' },
  { id:'c295',page:64,type:'trueFalse',bloom:'understand',difficulty:'easy',
    question:'برنامج الرسم يحتاج إبداعاً وفناً.',
    paragraph:'برنامج الرسم = إبداع + فن. (ص64)',
    correctAnswer:true,
    explanation:'رسم = إبداع + فن = ألوان + أشكال.',
    goldenRule:'رسم = إبداع + فن = ألوان + أشكال.' },
  { id:'c296',page:66,type:'classify',bloom:'analyze',difficulty:'hard',
    question:'صنّف أدوات برنامج الرسم:',
    paragraph:'رسم: فرشاة، قلم، أشكال. تلوين: ألوان. مسح: ممحاة. (ص66)',
    categories:['أدوات رسم وتلوين 🎨','أدوات مسح 🗑️'],
    items:[
      {text:'الفرشاة',correct_category:0},{text:'القلم',correct_category:0},{text:'الأشكال',correct_category:0},{text:'الألوان',correct_category:0},
      {text:'الممحاة',correct_category:1},
    ],
    explanation:'رسم/تلوين: فرش، قلم، أشكال، ألوان. مسح: ممحاة.',
    goldenRule:'رسم/تلوين = فرش/قلم/أشكال/ألوان. مسح = ممحاة.' },
  { id:'c297',page:68,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل أداة بنتيجتها:',
    paragraph:'الفرشاة = رسم حر، الألوان = تلوين، الأشكال = جاهز، الممحاة = مسح. (ص68)',
    pairs:[{left:'الفرشاة',right:'رسم حر'},{left:'الألوان',right:'تلوين'},{left:'الأشكال',right:'جاهز'},{left:'الممحاة',right:'مسح'}],
    explanation:'كل أداة = نتيجة محددة.',
    goldenRule:'أداة = نتيجة. اختار الأداة المناسبة.' },
  { id:'c298',page:70,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "برنامج الرسم أداة لل___ الفني."',
    paragraph:'برنامج الرسم للإبداع الفني. (ص70)',
    blanks:['إبداع'],
    wordBank:['إبداع','أكل','نوم','سباحة'],
    explanation:'برنامج الرسم = إبداع فني = ألوان + أشكال.',
    goldenRule:'برنامج الرسم = إبداع فني = ألوان + أشكال.' },
  { id:'c299',page:72,type:'trueFalse',bloom:'apply',difficulty:'easy',
    question:'للكتابة على الحاسوب أستخدم لوحة المفاتيح.',
    paragraph:'لوحة المفاتيح للكتابة. (ص72)',
    correctAnswer:true,
    explanation:'كتابة = لوحة مفاتيح = حروف + أرقام.',
    goldenRule:'الكتابة = لوحة المفاتيح = حروف + أرقام.' },
  { id:'c300',page:74,type:'ordering',bloom:'apply',difficulty:'medium',
    question:'رتّب عمل رقمي كامل:',
    paragraph:'تشغيل، فتح برنامج، عمل، حفظ، إطفاء آمن. (ص74)',
    items:['إطفاء آمن','حفظ العمل','عمل','فتح برنامج','تشغيل'],
    correctOrder:[4,3,2,1,0],
    explanation:'تشغيل ← فتح ← عمل ← حفظ ← إطفاء.',
    goldenRule:'عمل رقمي = تشغيل ← فتح ← عمل ← حفظ ← إطفاء.',
    feedbackQuestion:{question:'لو أردت عمل رسمة جميلة، بأي أداة تبدأ؟',
      options:[{text:'الفرشاة للرسم الحر',correct:true},{text:'الممحاة للمسح',correct:false},{text:'الحفظ',correct:false},{text:'الإغلاق',correct:false}],
      explanation:'الرسم يبدأ بالفرشاة أو القلم، ثم التلوين، ثم الحفظ.'} },
];