// المهارات الرقمية - الصف الثاني الابتدائي - الفصل الأول
// بنك تفاعلي موحد
import { COMPUTER_EXTRA_1 } from './computerGrade2S1Bank_Extra1';
import { COMPUTER_EXTRA_2 } from './computerGrade2S1Bank_Extra2';

export const META = {
  title: 'بنك المهارات الرقمية',
  subject: 'المهارات الرقمية',
  grade: 'الصف الثاني الابتدائي',
  term: 'الفصل الأول',
  publisher: 'وزارة التعليم - المملكة العربية السعودية',
  book: 'المهارات الرقمية 1447هـ',
  icon: '💻',
};

export const BLOOM_LABELS = {
  remember: 'تذكُّر', understand: 'فهم', apply: 'تطبيق',
  analyze: 'تحليل', create: 'تركيب', evaluate: 'تقويم',
};
export const DIFFICULTY_LABELS = { easy: 'سهل', medium: 'متوسط', hard: 'صعب' };

export const QUESTIONS = [
  // ── الوحدة 1: الحاسوب وحولنا (ص 6-18) ──
  { id:'c1',page:6,type:'multipleChoice',bloom:'remember',difficulty:'easy',
    question:'الحاسوب جهاز يساعدنا في:',
    paragraph:'الحاسوب جهاز إلكتروني يساعدنا في الدراسة والعمل واللعب والتواصل. (ص6)',
    options:[{text:'الدراسة والعمل واللعب والتواصل',correct:true},{text:'النوم فقط',correct:false},{text:'الأكل',correct:false},{text:'السباحة',correct:false}],
    explanation:'الحاسوب يساعدنا في مهام كثيرة: دراسة، عمل، لعب، تواصل، بحث.',
    goldenRule:'الحاسوب = جهاز إلكتروني متعدد الاستخدامات.' },
  { id:'c2',page:8,type:'trueFalse',bloom:'understand',difficulty:'easy',
    question:'الحاسوب آلة إلكترونية تحتاج كهرباء ليعمل.',
    paragraph:'الحاسوب آلة إلكترونية يعمل بالكهرباء. (ص8)',
    correctAnswer:true,
    explanation:'الحاسوب آلة إلكترونية، يحتاج مصدر كهرباء للعمل.',
    goldenRule:'الحاسوب إلكتروني = يحتاج كهرباء = لا يعمل وحده.' },
  { id:'c3',page:10,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف الأجهزة إلى رقمية وغير رقمية:',
    paragraph:'الأجهزة الرقمية: الحاسوب، الجوال، اللوحي. غير الرقمية: القلم، الدفتر، الكتاب. (ص10)',
    categories:['أجهزة رقمية 💻','أدوات عادية ✏️'],
    items:[
      {text:'الحاسوب',correct_category:0},{text:'الجوال',correct_category:0},{text:'اللوحي',correct_category:0},{text:'الساعة الذكية',correct_category:0},
      {text:'القلم',correct_category:1},{text:'الدفتر',correct_category:1},{text:'الكتاب',correct_category:1},
    ],
    explanation:'رقمية: حاسوب، جوال، لوحي، ساعة ذكية. عادية: قلم، دفتر، كتاب.',
    goldenRule:'رقمية = تعمل بالكهرباء + تُخزّن معلومات. عادية = ورقية.' },
  { id:'c4',page:12,type:'multipleChoice',bloom:'remember',difficulty:'easy',
    question:'من أجهزة الحاسوب في المنزل:',
    paragraph:'نجد الحاسوب المكتبي والمحمول واللوحي في كثير من المنازل. (ص12)',
    options:[{text:'المكتبي + المحمول + اللوحي',correct:true},{text:'الثلاجة',correct:false},{text:'الساعة',correct:false},{text:'الكرسي',correct:false}],
    explanation:'أنواع الحاسوب: مكتبي، محمول، لوحي — كلها في المنازل.',
    goldenRule:'حاسوب = مكتبي أو محمول أو لوحي.' },
  { id:'c5',page:14,type:'matching',bloom:'understand',difficulty:'medium',
    question:'صِل كل جهاز باستخدامه:',
    paragraph:'الحاسوب للدراسة، الجوال للاتصال، اللوحي للقراءة، الساعة الذكية للوقت. (ص14)',
    pairs:[{left:'الحاسوب',right:'الدراسة والعمل'},{left:'الجوال',right:'الاتصال'},{left:'اللوحي',right:'القراءة'},{left:'الساعة الذكية',right:'معرفة الوقت'}],
    explanation:'كل جهاز له استخدام مناسب، لكن الحاسوب أعمقها.',
    goldenRule:'حاسوب=دراسة، جوال=اتصال، لوحي=قراءة، ساعة=وقت.' },
  { id:'c6',page:16,type:'trueFalse',bloom:'evaluate',difficulty:'medium',
    question:'يجب عدم استخدام الحاسوب لفترة طويلة بدون راحة.',
    paragraph:'استراح العينين والجسم بعد استخدام الحاسوب فترة طويلة. (ص16)',
    correctAnswer:true,
    explanation:'الجلوس الطويل أمام الشاشة يضر العين والظهر، فاسترح كل فترة.',
    goldenRule:'صحتك أولاً: استراح بعد كل 30 دقيقة أمام الشاشة.' },
  { id:'c7',page:18,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "الحاسوب جهاز ___ يساعدنا في كثير من الأعمال."',
    paragraph:'الحاسوب جهاز إلكتروني يساعدنا في كثير من الأعمال. (ص6)',
    blanks:['إلكتروني'],
    wordBank:['إلكتروني','خشبي','حديدي','ورقي'],
    explanation:'الحاسوب جهاز إلكتروني يعمل بالكهرباء.',
    goldenRule:'الحاسوب إلكتروني = يعمل بالكهرباء = أداة ذكية.' },

  // ── الوحدة 2: أجزاء الحاسوب (ص 20-32) ──
  { id:'c8',page:20,type:'multipleChoice',bloom:'remember',difficulty:'easy',
    question:'من الأجزاء الأساسية للحاسوب:',
    paragraph:'أجزاء الحاسوب الرئيسة: الشاشة، لوحة المفاتيح، الفأرة، وحدة المعالجة. (ص20)',
    options:[{text:'الشاشة + لوحة المفاتيح + الفأرة + الوحدة',correct:true},{text:'القلم',correct:false},{text:'الدفتر',correct:false},{text:'الكتاب',correct:false}],
    explanation:'الأجزاء الأساسية: شاشة + لوحة مفاتيح + فأرة + وحدة معالجة.',
    goldenRule:'حاسوب = شاشة + لوحة مفاتيح + فأرة + وحدة معالجة.' },
  { id:'c9',page:22,type:'trueFalse',bloom:'remember',difficulty:'easy',
    question:'الشاشة تُظهر ما نعمله على الحاسوب.',
    paragraph:'الشاشة تُظهر الصور والنصوص التي نعملها على الحاسوب. (ص22)',
    correctAnswer:true,
    explanation:'الشاشة تُظهر كل ما نراه من صور ونصوص وألعاب.',
    goldenRule:'الشاشة = نافذة الحاسوب = تُظهر عملك.' },
  { id:'c10',page:24,type:'multipleChoice',bloom:'understand',difficulty:'easy',
    question:'لوحة المفاتيح نستخدمها لـ:',
    paragraph:'لوحة المفاتيح نكتب بها الحروف والأرقام على الحاسوب. (ص24)',
    options:[{text:'كتابة الحروف والأرقام',correct:true},{text:'تحريك المؤشر',correct:false},{text:'إطفاء الجهاز',correct:false},{text:'طباعة الصور',correct:false}],
    explanation:'لوحة المفاتيح للأحرف والأرقام والرموز.',
    goldenRule:'لوحة المفاتيح = كتابة. الفأرة = تحريك.' },
  { id:'c11',page:26,type:'multipleChoice',bloom:'understand',difficulty:'easy',
    question:'الفأرة (الماوس) نستخدمها لـ:',
    paragraph:'الفأرة نحرّكها لتوجيه المؤشر على الشاشة ونضغط للاختيار. (ص26)',
    options:[{text:'تحريك المؤشر والاختيار',correct:true},{text:'كتابة الحروف',correct:false},{text:'تشغيل الكهرباء',correct:false},{text:'طباعة الورق',correct:false}],
    explanation:'الفأرة تحرّك المؤشر (السهم) وتنقر للاختيار.',
    goldenRule:'فأرة = مؤشر + نقرة. توجيه واختيار.' },
  { id:'c12',page:28,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف أجزاء الحاسوب:',
    paragraph:'إدخال: لوحة المفاتيح، الفأرة، الميكروفون. إخراج: الشاشة، السماعة، الطابعة. (ص28)',
    categories:['أجهزة إدخال ⌨️','أجهزة إخراج 🖥️'],
    items:[
      {text:'لوحة المفاتيح',correct_category:0},{text:'الفأرة',correct_category:0},{text:'الميكروفون',correct_category:0},
      {text:'الشاشة',correct_category:1},{text:'السماعة',correct_category:1},{text:'الطابعة',correct_category:1},
    ],
    explanation:'إدخال: ما ندخل به المعلومة. إخراج: ما يُظهر لنا النتيجة.',
    goldenRule:'إدخال = نُدخل. إخراج = يُخرج لنا.' },
  { id:'c13',page:30,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل جزء بوظيفته:',
    paragraph:'الشاشة للعرض، لوحة المفاتيح للكتابة، الفأرة للتوجيه، السماعة للصوت. (ص30)',
    pairs:[{left:'الشاشة',right:'العرض'},{left:'لوحة المفاتيح',right:'الكتابة'},{left:'الفأرة',right:'التوجيه'},{left:'السماعة',right:'الصوت'}],
    explanation:'كل جزء له وظيفة محددة في الحاسوب.',
    goldenRule:'شاشة=عرض، لوحة=كتابة، فأرة=توجيه، سماعة=صوت.' },
  { id:'c14',page:32,type:'trueFalse',bloom:'understand',difficulty:'easy',
    question:'الطابعة جهاز إخراج يطبع الصور والنصوص على الورق.',
    paragraph:'الطابعة جهاز إخراج يطبع ما نعمله على الحاسوب على ورق. (ص32)',
    correctAnswer:true,
    explanation:'الطابعة جهاز إخراج، تُخرج عملك على ورق.',
    goldenRule:'الطابعة = إخراج = من شاشة إلى ورق.' },
  { id:'c15',page:20,type:'ordering',bloom:'apply',difficulty:'medium',
    question:'رتّب أجزاء الحاسوب حسب استخدامك لها للكتابة:',
    paragraph:'للكتابة على الحاسوب: شغّل الحاسوب، انظر الشاشة، استخدم لوحة المفاتيح، احفظ العمل. (ص20-32)',
    items:['احفظ العمل','استخدم لوحة المفاتيح','انظر الشاشة','شغّل الحاسوب'],
    correctOrder:[3,2,1,0],
    explanation:'(1) تشغيل ← (2) شاشة ← (3) كتابة ← (4) حفظ.',
    goldenRule:'عمل الحاسوب = تشغيل ← شاشة ← كتابة ← حفظ.' },

  // ── الوحدة 3: تشغيل الحاسوب وإطفاؤه (ص 34-46) ──
  { id:'c16',page:34,type:'multipleChoice',bloom:'apply',difficulty:'easy',
    question:'لتشغيل الحاسوب نضغط زر:',
    paragraph:'لتشغيل الحاسوب نضغط زر التشغيل (Power) في الوحدة. (ص34)',
    options:[{text:'التشغيل (Power)',correct:true},{text:'زر الفأرة',correct:false},{text:'حرف الألف',correct:false},{text:'زر الطابعة',correct:false}],
    explanation:'زر التشغيل (Power) يشغّل الحاسوب.',
    goldenRule:'زر Power = تشغيل وإطفاء الحاسوب.' },
  { id:'c17',page:36,type:'trueFalse',bloom:'understand',difficulty:'easy',
    question:'يجب الانتظار حتى تظهر شاشة الحاسوب قبل البدء بالعمل.',
    paragraph:'بعد الضغط على زر التشغيل ننتظر حتى تظهر الشاشة الرئيسة. (ص36)',
    correctAnswer:true,
    explanation:'الحاسوب يحتاج وقتاً ليبدأ، انتظر حتى تظهر الشاشة الرئيسة.',
    goldenRule:'صبر = انتظر بدء الحاسوب قبل العمل.' },
  { id:'c18',page:38,type:'multipleChoice',bloom:'understand',difficulty:'medium',
    question:'لإطفاء الحاسوب بشكل صحيح:',
    paragraph:'لإطفاء الحاسوب نختار "إيقاف التشغيل" من القائمة لا نقطع الكهرباء. (ص38)',
    options:[{text:'اختيار "إيقاف التشغيل" من القائمة',correct:true},{text:'نزع سلك الكهرباء',correct:false},{text:'الضغط على الشاشة',correct:false},{text:'إغلاق الفأرة',correct:false}],
    explanation:'الإطفاء الصحيح: قائمة ← إيقاف تشغيل. لا تقطع الكهرباء فجأة.',
    goldenRule:'إطفاء صحيح = قائمة + إيقاف تشغيل = حماية الجهاز.' },
  { id:'c19',page:40,type:'trueFalse',bloom:'evaluate',difficulty:'medium',
    question:'نزع سلك الكهرباء فجأة قد يُتلف الحاسوب ويفقد عملك.',
    paragraph:'نزع الكهرباء فجأة قد يُتلف الجهاز ويفقد ما لم تحفظه. (ص40)',
    correctAnswer:true,
    explanation:'قطع الكهرباء فجأة يضر الجهاز ويفقد عملك غير المحفوظ.',
    goldenRule:'لا تقطع الكهرباء = احفظ عملك + أطفئ بأمان.' },
  { id:'c20',page:42,type:'ordering',bloom:'apply',difficulty:'medium',
    question:'رتّب خطوات إطفاء الحاسوب بأمان:',
    paragraph:'احفظ عملك، اضغط قائمة البدء، اختر إيقاف التشغيل، انتظر إطفاء الشاشة. (ص42)',
    items:['انتظر إطفاء الشاشة','اختر إيقاف التشغيل','اضغط قائمة البدء','احفظ عملك'],
    correctOrder:[3,2,1,0],
    explanation:'(1) حفظ ← (2) قائمة بدء ← (3) إيقاف ← (4) انتظار.',
    goldenRule:'إطفاء آمن = حفظ ← بدء ← إيقاف ← انتظار.' },
  { id:'c21',page:44,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "لإطفاء الحاسوب نختار ___ التشغيل من القائمة."',
    paragraph:'لإطفاء الحاسوب نختار إيقاف التشغيل. (ص38)',
    blanks:['إيقاف'],
    wordBank:['إيقاف','بدء','تشغيل','فتح'],
    explanation:'"إيقاف التشغيل" الخيار الصحيح لإطفاء الحاسوب بأمان.',
    goldenRule:'إيقاف التشغيل = إطفاء آمن.' },
  { id:'c22',page:46,type:'multipleChoice',bloom:'evaluate',difficulty:'hard',
    question:'لو علّق الحاسوب ولم يستجب، ما الصواب؟',
    paragraph:'إذا توقف الحاسوب عن الاستجابة ننتظر قليلاً ثم نطلب مساعدة الكبار. (ص46)',
    options:[{text:'أنتظر قليلاً وأطلب مساعدة الكبار',correct:true},{text:'أضرب الشاشة',correct:false},{text:'أنزع السلك فجأة',correct:false},{text:'أصرخ',correct:false}],
    explanation:'علّق الجهاز = صبر + مساعدة كبار. لا عنف ولا قطع كهرباء.',
    goldenRule:'جهاز معلّق = صبر + استعن بالكبار.',
    feedbackQuestion:{question:'لو تعطلت الفأرة أثناء العمل، ماذا تفعل؟',
      options:[{text:'أخبر المعلم أو ولي الأمر',correct:true},{text:'أرميها',correct:false},{text:'أتركها دون عمل',correct:false},{text:'أضربها',correct:false}],
      explanation:'الأعطال تُحل بمساعدة الكبار لا بالعنف.'} },

  // ── الوحدة 4: الأمان والصحة الرقمية (ص 48-60) ──
  { id:'c23',page:48,type:'multipleChoice',bloom:'remember',difficulty:'easy',
    question:'يجب الجلوس ___ الحاسوب للحفاظ على صحة الظهر.',
    paragraph:'يجلس الطالب مستقيماً أمام الحاسوب للحفاظ على ظهره وعينيه. (ص48)',
    options:[{text:'مستقيماً',correct:true},{text:'منحنياً',correct:false},{text:'مائل',correct:false},{text:'راكعاً',correct:false}],
    explanation:'الجلوس المستقيم يحمي الظهر والعين.',
    goldenRule:'جلوس مستقيم = ظهر سليم + عين مريحة.' },
  { id:'c24',page:50,type:'trueFalse',bloom:'understand',difficulty:'easy',
    question:'يجب أن تكون الشاشة على مستوى العينين لا قريبة جداً.',
    paragraph:'توضع الشاشة على مستوى العينين وبُعد مناسب لحماية النظر. (ص50)',
    correctAnswer:true,
    explanation:'الشاشة على مستوى العين وبُعد مناسب تحمي النظر والرقبة.',
    goldenRule:'شاشة = مستوى العين + بُعد مناسب = نظر آمن.' },
  { id:'c25',page:52,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف السلوك إلى صحي وخطأ أمام الحاسوب:',
    paragraph:'صحيح: استراحة كل 30 دقيقة، إضاءة مناسبة، جلوس مستقيم. خطأ: شاشة قريبة، ظلام، جلوس طويل. (ص52)',
    categories:['سلوك صحيح ✅','سلوك خاطئ ❌'],
    items:[
      {text:'استراحة كل 30 دقيقة',correct_category:0},{text:'إضاءة مناسبة',correct_category:0},{text:'جلوس مستقيم',correct_category:0},
      {text:'شاشة قريبة جداً',correct_category:1},{text:'الجلوس في ظلام',correct_category:1},{text:'ساعات طويلة بلا راحة',correct_category:1},
    ],
    explanation:'صحيح: راحة، إضاءة، استقامة. خطأ: قرب، ظلام، إطالة.',
    goldenRule:'صحة رقمية = راحة + إضاءة + استقامة + بُعد.' },
  { id:'c26',page:54,type:'multipleChoice',bloom:'understand',difficulty:'medium',
    question:'مدة الجلوس المناسبة أمام الحاسوب للطفل:',
    paragraph:'يُنصح بألا يزيد وقت الطفل أمام الشاشة عن 30 دقيقة متواصلة. (ص54)',
    options:[{text:'30 دقيقة ثم استراحة',correct:true},{text:'3 ساعات متواصلة',correct:false},{text:'طوال اليوم',correct:false},{text:'لا يهم',correct:false}],
    explanation:'30 دقيقة متواصلة حدّ أقصى، ثم استراحة لحماية العين.',
    goldenRule:'30 دقيقة = حد آمن. استراح = عين سليمة.' },
  { id:'c27',page:56,type:'trueFalse',bloom:'evaluate',difficulty:'medium',
    question:'لا أعطي اسمي أو صورتي لأحد عبر الإنترنت دون إذن والديّ.',
    paragraph:'لا تشارك اسمك أو صورتك أو بياناتك مع غرباء عبر الإنترنت. (ص56)',
    correctAnswer:true,
    explanation:'المعلومات الشخصية خاصة، لا تشاركها مع غرباء.',
    goldenRule:'بياناتي = خاصة. لا أشاركها دون إذن والديّ.' },
  { id:'c28',page:58,type:'multipleChoice',bloom:'evaluate',difficulty:'hard',
    question:'لو رأيت صورة أو مقطعاً يخالف ديني أثناء استخدام الحاسوب:',
    paragraph:'إذا رأيت ما يخالف الدين أو الآداب أغلق الشاشة وأخبر الكبار. (ص58)',
    options:[{text:'أغلق الشاشة وأخبر الكبار',correct:true},{text:'أكمل المشاهدة',correct:false},{text:'أرسلها لأصدقائي',correct:false},{text:'أحفظها',correct:false}],
    explanation:'الصواب: إغلاق + إخبار الكبار. لا مشاركة ولا إكمال.',
    goldenRule:'رأيت منكراً رقمياً = أغلق + أخبر الكبار.',
    feedbackQuestion:{question:'لو وصلك رسالة من شخص لا تعرفه، ماذا تفعل؟',
      options:[{text:'لا أرد وأخبر والديّ',correct:true},{text:'أرد عليه',correct:false},{text:'أرسل له صورتي',correct:false},{text:'أقابله',correct:false}],
      explanation:'الرسائل من الغرباء خطر — لا ترد وأخبر والديك.'} },
  { id:'c29',page:60,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "أحافظ على ___ الحاسوب ولا آكل أو أشرب قربه."',
    paragraph:'يجب عدم الأكل أو الشرب قرب الحاسوب للحفاظ عليه. (ص60)',
    blanks:['نظافة'],
    wordBank:['نظافة','إتلاف','كسر','تخريب'],
    explanation:'الطعام والشراب قد يضرّان الجهاز، فحافظ على نظافته وابعد عنه الأكل.',
    goldenRule:'لا أكل ولا شرب قرب الحاسوب = جهاز سليم.' },
  { id:'c30',page:48,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل نصيحة بالسبب:',
    paragraph:'استراح → راحة العين، إضاءة → وضوح الرؤية، جلوس مستقيم → سلامة الظهر، بُعد الشاشة → حماية النظر. (ص48-52)',
    pairs:[{left:'استراحة',right:'راحة العين'},{left:'إضاءة مناسبة',right:'وضوح الرؤية'},{left:'جلوس مستقيم',right:'سلامة الظهر'},{left:'بُعد الشاشة',right:'حماية النظر'}],
    explanation:'كل نصيحة صحية لها سبب علمي.',
    goldenRule:'صحة رقمية = راحة + إضاءة + استقامة + بُعد.' },

  // ── الوحدة 5: الرسم والكتابة البسيطة (ص 62-74) ──
  { id:'c31',page:62,type:'multipleChoice',bloom:'remember',difficulty:'easy',
    question:'برنامج الرسم في الحاسوب يُستخدم لـ:',
    paragraph:'برنامج الرسم يُستخدم لتلوين ورسم الأشكال على الحاسوب. (ص62)',
    options:[{text:'تلوين ورسم الأشكال',correct:true},{text:'النوم',correct:false},{text:'الأكل',correct:false},{text:'السباحة',correct:false}],
    explanation:'برنامج الرسم لتلوين ورسم الأشكال بالفأرة أو القلم الرقمي.',
    goldenRule:'برنامج الرسم = ألوان + أشكال = إبداع رقمي.' },
  { id:'c32',page:64,type:'trueFalse',bloom:'understand',difficulty:'easy',
    question:'يمكنني تغيير لون الفرشاة في برنامج الرسم.',
    paragraph:'في برنامج الرسم نختار اللون ثم نرسم بالفرشاة. (ص64)',
    correctAnswer:true,
    explanation:'برنامج الرسم يتيح اختيار الألوان وتغيير حجم الفرشاة.',
    goldenRule:'برنامج الرسم = ألوان + فرش = حرية إبداع.' },
  { id:'c33',page:66,type:'multipleChoice',bloom:'apply',difficulty:'medium',
    question:'لحفظ رسمتي في برنامج الرسم أختار:',
    paragraph:'لحفظ الرسم نختار ملف ثم حفظ باسم. (ص66)',
    options:[{text:'ملف ← حفظ',correct:true},{text:'إطفاء الحاسوب',correct:false},{text:'حذف الرسمة',correct:false},{text:'إغلاق النافذة',correct:false}],
    explanation:'حفظ = ملف ← حفظ باسم ← اختيار المكان ← كتابة الاسم.',
    goldenRule:'حفظ عملك = ملف ← حفظ ← اسم ← مكان.' },
  { id:'c34',page:68,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف أدوات برنامج الرسم:',
    paragraph:'أدوات الرسم: الفرشاة، القلم، الألوان، الأشكال. أدوات الكتابة: لوحة المفاتيح، النص. (ص68)',
    categories:['أدوات الرسم 🎨','أدوات الكتابة ✍️'],
    items:[
      {text:'الفرشاة',correct_category:0},{text:'القلم الرقمي',correct_category:0},{text:'الألوان',correct_category:0},{text:'الأشكال',correct_category:0},
      {text:'لوحة المفاتيح',correct_category:1},{text:'أداة النص',correct_category:1},
    ],
    explanation:'الرسم = فرش وألوان وأشكال. الكتابة = لوحة مفاتيح ونص.',
    goldenRule:'رسم = فرش/ألوان. كتابة = لوحة مفاتيح/نص.' },
  { id:'c35',page:70,type:'matching',bloom:'understand',difficulty:'medium',
    question:'صِل كل أداة بوظيفتها في برنامج الرسم:',
    paragraph:'الفرشاة للرسم الحر، الألوان للتلوين، الأشكال لرسم أشكال جاهزة، الممحاة للمسح. (ص70)',
    pairs:[{left:'الفرشاة',right:'الرسم الحر'},{left:'الألوان',right:'التلوين'},{left:'الأشكال',right:'أشكال جاهزة'},{left:'الممحاة',right:'المسح'}],
    explanation:'كل أداة في برنامج الرسم لها وظيفة محددة.',
    goldenRule:'فرشاة=رسم، لون=تلوين، شكل=جاهز، ممحاة=مسح.' },
  { id:'c36',page:72,type:'trueFalse',bloom:'apply',difficulty:'easy',
    question:'أستطيع كتابة اسمي على الحاسوب باستخدام لوحة المفاتيح.',
    paragraph:'للكتابة على الحاسوب أستخدم لوحة المفاتيح لكتابة الحروف. (ص72)',
    correctAnswer:true,
    explanation:'لوحة المفاتيح تكتب الحروف والأرقام والرموز على الحاسوب.',
    goldenRule:'الكتابة على الحاسوب = لوحة المفاتيح = حروف وأرقام.' },
  { id:'c37',page:74,type:'ordering',bloom:'apply',difficulty:'medium',
    question:'رتّب خطوات رسم وتلوين شجرة ثم حفظها:',
    paragraph:'افتح برنامج الرسم، ارسم الشجرة بالفرشاة، لوّنها، احفظ الرسمة. (ص74)',
    items:['احفظ الرسمة','لوّن الشجرة','ارسم الشجرة بالفرشاة','افتح برنامج الرسم'],
    correctOrder:[3,2,1,0],
    explanation:'(1) فتح البرنامج ← (2) رسم ← (3) تلوين ← (4) حفظ.',
    goldenRule:'رسم رقمي = فتح ← رسم ← تلوين ← حفظ.' },
  { id:'c38',page:62,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "في برنامج الرسم أختار ___ لألوّن رسمتي."',
    paragraph:'في برنامج الرسم نختار الألوان للتلوين. (ص64)',
    blanks:['الألوان'],
    wordBank:['الألوان','الممحاة','الحذف','الإغلاق'],
    explanation:'أداة الألوان تستخدم لتلوين الرسمة.',
    goldenRule:'ألوان = تلوين. فرشاة = رسم. ممحاة = مسح.' },
  { id:'c39',page:50,type:'trueFalse',bloom:'evaluate',difficulty:'hard',
    question:'مشاركة كلمة المرور (الباسوورد) مع الأصدقاء آمنة.',
    paragraph:'كلمة المرور سر خاص بك، لا تشاركها مع أحد. (ص56)',
    correctAnswer:false,
    explanation:'كلمة المرور سر، مشاركتها خطر على حسابك وبياناتك.',
    goldenRule:'كلمة المرور = سر = لا تشاركها مع أحد.' },
  { id:'c40',page:22,type:'multipleChoice',bloom:'evaluate',difficulty:'hard',
    question:'لماذا تُعد الشاشة مهمة في الحاسوب؟',
    paragraph:'الشاشة تُظهر كل ما نعمله على الحاسوب، بدونها لا نرى شيئاً. (ص22)',
    options:[{text:'لأنها تُظهر كل ما نعمله على الحاسوب',correct:true},{text:'لأنها تطبع الورق',correct:false},{text:'لأنها تكتب',correct:false},{text:'لأنها تشغّل الكهرباء',correct:false}],
    explanation:'بدون الشاشة لا نرى عملنا، فهي نافذة الحاسوب.',
    goldenRule:'الشاشة = نافذة الحاسوب = بدونها عمل أعمى.' },
  { id:'c41',page:24,type:'trueFalse',bloom:'remember',difficulty:'easy',
    question:'لوحة المفاتيح تحت على حروف وأرقام ورموز.',
    paragraph:'لوحة المفاتيح تحت على مفاتيح الحروف والأرقام والرموز. (ص24)',
    correctAnswer:true,
    explanation:'لوحة المفاتيح فيها مفاتيح لكل حرف ورقم ورمز.',
    goldenRule:'لوحة المفاتيح = حروف + أرقام + رموز = كتابة.' },
  { id:'c42',page:12,type:'classify',bloom:'analyze',difficulty:'hard',
    question:'صنّف أجهزة الحاسوب حسب النوع:',
    paragraph:'أنواع الحاسوب: مكتبي، محمول، لوحي، جوال ذكي. (ص12)',
    categories:['حاسوب بالمعنى الضيق 💻','أجهزة ذكية محمولة 📱'],
    items:[
      {text:'الحاسوب المكتبي',correct_category:0},{text:'الحاسوب المحمول',correct_category:0},
      {text:'اللوحي',correct_category:1},{text:'الجوال الذكي',correct_category:1},{text:'الساعة الذكية',correct_category:1},
    ],
    explanation:'مكتبي ومحمول = حاسوب بالمعنى الضيق. لوحي/جوال/ساعة = أجهزة ذكية محمولة.',
    goldenRule:'حاسوب ضيق = مكتبي/محمول. أجهزة ذكية = لوحي/جوال/ساعة.' },
  { id:'c43',page:34,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "لتشغيل الحاسوب أضغط زر ___."',
    paragraph:'لتشغيل الحاسوب أضغط زر التشغيل Power. (ص34)',
    blanks:['التشغيل'],
    wordBank:['التشغيل','الحذف','الطباعة','الكتابة'],
    explanation:'زر التشغيل (Power) يبدأ تشغيل الحاسوب.',
    goldenRule:'زر التشغيل = بداية عمل الحاسوب.' },
  { id:'c44',page:66,type:'multipleChoice',bloom:'apply',difficulty:'medium',
    question:'لو أردت إعادة رسمتي غداً، ماذا أفعل بعد رسمها؟',
    paragraph:'لإعادة العمل لاحقاً يجب حفظه باسم معروف في مكان معروف. (ص66)',
    options:[{text:'أحفظها باسم معروف في مكان معروف',correct:true},{text:'أغلق بدون حفظ',correct:false},{text:'أحذفها',correct:false},{text:'أتركها فقط',correct:false}],
    explanation:'حفظ العمل باسم ومكان واضح يتيح إيجاده وإكماله لاحقاً.',
    goldenRule:'حفظ ذكي = اسم + مكان = سهولة الإيجاد لاحقاً.' },
  { id:'c45',page:58,type:'trueFalse',bloom:'evaluate',difficulty:'medium',
    question:'من الآمن تحميل أي برنامج من أي موقع دون فحص.',
    paragraph:'يجب تحميل البرامج من مصادر موثوقة فقط لحماية الجهاز. (ص58)',
    correctAnswer:false,
    explanation:'البرامج من مصادر غير موثوقة قد تحمل فيروسات تضر الجهاز.',
    goldenRule:'تحميل آمن = مصدر موثوق فقط = لا فيروسات.' },
  ...COMPUTER_EXTRA_1,
  ...COMPUTER_EXTRA_2,
];