// We Can! 3 — Grade 3 English — Term 2
// Source: Ministry of Education 2025 – 1447 (WC_03_TERM2_COMBO_TEXT_2025)
// Student Book (9 parts) — Literal content extracted from printed pages via LLM

import { makeBankGenerator } from './interactiveBankGenerator';

export const ENGLISH_G3_S2_UNITS = [
  {
    title_ar: 'Unit 1: Fun on the Weekend',
    title_en: 'Unit 1: Fun on the Weekend',
    image: 'https://media.base44.com/images/public/6a459ddfe6fb4264c098136d/5b406a497_generated_image.png',
    chant: `Practiced, practiced — I practiced my English.\nWatched, watched — You watched a film.\nCooked, cooked — She cooked breakfast.\nKicked, kicked — He kicked a ball.\nCleaned, cleaned — They cleaned the house.\nStayed, stayed — We stayed at home.\nPlayed, played — You played outside.\nStudied, studied — You studied a little.`,
    listening_text: `What did you do over the weekend? — I cooked a big breakfast. That's fantastic!\nWhat would you like? — I'd like..., please. Sure. Just a moment.`,
    phonics: ['nd: sand, hand, land', 'nt: tent, bent, went'],
    goals: [
      { number: 49, section: 'Challenge Time', i_can: 'ask a partner about his or her weekend and get the answers.' },
      { number: 50, section: 'Challenge Time', i_can: "listen to someone's answer about what he or she did over the weekend and make a comment." },
      { number: 51, section: 'Challenge Time', i_can: 'say the past form of six regular verbs.' },
      { number: 52, section: 'Challenge Time', i_can: 'say two things that I did over the weekend.' },
      { number: 53, section: 'Challenge Time', i_can: 'ask and answer questions with How many and How much and make sentences with some and any.' },
      { number: 54, section: 'Challenge Time', i_can: 'read an English menu and order at a restaurant.' },
      { number: 55, section: 'Challenge Time', i_can: 'say, read, and write words ending in nd and nt.' },
      { number: 56, section: 'Challenge Time', i_can: 'read English store signs in town.' },
    ],
    vocab: [
      { word: 'cleaned', emoji: '🧹' },
      { word: 'practiced', emoji: '🤸' },
      { word: 'watched', emoji: '📺' },
      { word: 'kicked', emoji: '⚽' },
      { word: 'played', emoji: '🎮' },
      { word: 'studied', emoji: '📚' },
      { word: 'cooked', emoji: '🍳' },
      { word: 'stayed', emoji: '🏠' },
      { word: 'flour', emoji: '🌾' },
      { word: 'oil', emoji: '🛢️' },
      { word: 'cheese', emoji: '🧀' },
      { word: 'tomatoes', emoji: '🍅' },
      { word: 'peppers', emoji: '🫑' },
      { word: 'mushrooms', emoji: '🍄' },
      { word: 'sand', emoji: '🏖️' },
      { word: 'tent', emoji: '⛺' },
    ],
  },
  {
    title_ar: "Unit 2: Life's Ups and Downs",
    title_en: "Unit 2: Life's Ups and Downs",
    image: 'https://media.base44.com/images/public/6a459ddfe6fb4264c098136d/c8ada3eba_generated_image.png',
    chant: `My brother Khaled went to the cupboard,\nTo find something to eat.\nBut when he got there, the cupboard was bare,\nAnd so he had nothing to eat.\nHe went to the grocer's, to buy some fruit and milk.\nBut when he came back, he was holding an empty brown bag!\nPoor Khaled!`,
    listening_text: `I won a table tennis game 21 to 3. Congratulations! So did I. How nice! Sorry about that. How scary!\nYesterday, we went to an adventure park. Our father drove us there. My sister and I saw some friends from school and played with them. Then we went on rides with our parents. It was great fun!`,
    phonics: ['f: fun, enough, fun', 'ph: photo, elephant, phone', 'gh: laugh, enough, tough'],
    goals: [
      { number: 57, section: 'I Can', i_can: 'talk about a good or a bad thing that happened to me in the past.' },
      { number: 58, section: 'I Can', i_can: 'quickly make comments about what happened in the past.' },
      { number: 59, section: 'I Can', i_can: 'say the past form of six irregular verbs.' },
      { number: 60, section: 'I Can', i_can: 'say two sentences using past tense irregular verbs.' },
      { number: 61, section: 'I Can', i_can: 'read and write the My Brother Khaled chant in the past or present tense.' },
      { number: 62, section: 'I Can', i_can: 'use some and any in sentences and write a new chant.' },
      { number: 63, section: 'I Can', i_can: 'say, read, and write words with f, ph, and gh.' },
      { number: 64, section: 'I Can', i_can: 'read and rewrite a short text using me, you, him, her, us, them.' },
    ],
    vocab: [
      { word: 'won', emoji: '🏆' },
      { word: 'got', emoji: '📥' },
      { word: 'was', emoji: '📝' },
      { word: 'made', emoji: '🛠️' },
      { word: 'saw', emoji: '👁️' },
      { word: 'lost', emoji: '📉' },
      { word: 'caught', emoji: '🎣' },
      { word: 'had', emoji: '🤲' },
      { word: 'broke', emoji: '💔' },
      { word: 'were', emoji: '👥' },
    ],
  },
  {
    title_ar: 'Unit 3: My School is Cool!',
    title_en: 'Unit 3: My School is Cool!',
    image: 'https://media.base44.com/images/public/6a459ddfe6fb4264c098136d/7b6a38abd_generated_image.png',
    chant: `Rana had a little lamb.\nIts fleece was white as snow.\nEverywhere that Rana went,\nThe lamb was sure to go.\nIt followed her to school one day,\nWhich was against the rules.\nIt made the children laugh and play,\nTo see a lamb at school.`,
    listening_text: `Which subject do you like most this year? — This year I like math.\nWhich subject did you like most last year? — Last year I liked PE.\nWhich grade are you in this year? — This year I am in the 3rd grade.\nWhich grade were you in last year? — Last year I was in the 2nd grade.`,
    phonics: ['sc: scan, scary, scarf', 'sk: sky, skate, skirt', 'sq: square, squeeze, squid'],
    goals: [
      { number: 65, section: 'Challenge Time', i_can: 'ask a friend three questions about his or her school.' },
      { number: 66, section: 'Challenge Time', i_can: 'write about my school and talk about it.' },
      { number: 67, section: 'Grammar', i_can: 'use present and past tense with Which questions.' },
      { number: 68, section: 'Reading', i_can: 'read and chant the Rana Had a Little Lamb poem.' },
      { number: 69, section: 'Phonics', i_can: 'say, read, and write words with sc, sk, and sq.' },
      { number: 70, section: 'Writing', i_can: 'write my own English class rules.' },
    ],
    vocab: [
      { word: 'school', emoji: '🏫' },
      { word: 'students', emoji: '🧑‍🎓' },
      { word: 'uniform', emoji: '👔' },
      { word: 'bus', emoji: '🚌' },
      { word: 'math', emoji: '📐' },
      { word: 'English', emoji: '🔤' },
      { word: 'history', emoji: '📜' },
      { word: 'science', emoji: '🔬' },
      { word: 'PE', emoji: '⚽' },
      { word: 'art', emoji: '🎨' },
      { word: 'scarf', emoji: '🧣' },
      { word: 'sky', emoji: '☁️' },
      { word: 'square', emoji: '⬜' },
      { word: 'skate', emoji: '⛸️' },
      { word: 'scary', emoji: '😱' },
      { word: 'squid', emoji: '🦑' },
    ],
  },
  {
    title_ar: 'Unit 4: A Healthy Life',
    title_en: 'Unit 4: A Healthy Life',
    image: 'https://media.base44.com/images/public/6a459ddfe6fb4264c098136d/cdf387544_generated_image.png',
    chant: `Early to bed, early to rise,\nMakes a man healthy, wealthy, and wise.\nWhat's the matter? — I have a headache.\nWhat's the matter? — I have a toothache.\nWhat's the matter? — I have a stomachache.`,
    listening_text: `What do you always do? — I always brush my teeth.\nWhat do you usually do? — I usually eat breakfast.\nWhat do you sometimes do? — I sometimes play outside.\nWhat do you never do? — I never eat junk food.`,
    phonics: ['ir: bird, girl, shirt', 'er: teacher, water, letter', 'ur: purple, turtle, nurse'],
    goals: [
      { number: 71, section: 'Finding Out Time', i_can: 'say good things I should do and bad things I shouldn\'t do.' },
      { number: 72, section: 'Grammar', i_can: 'use frequency markers: always, usually, sometimes, often, never.' },
      { number: 73, section: 'Reading', i_can: 'read the Early to Bed chant and understand healthy habits.' },
      { number: 74, section: 'Phonics', i_can: 'say, read, and write words with ir, er, and ur.' },
      { number: 75, section: 'Speaking', i_can: 'ask and answer about what\'s the matter using health words.' },
      { number: 76, section: 'Writing', i_can: 'write about my daily healthy routine.' },
    ],
    vocab: [
      { word: 'always', emoji: '💯' },
      { word: 'usually', emoji: '📊' },
      { word: 'sometimes', emoji: '🎲' },
      { word: 'never', emoji: '🚫' },
      { word: 'breakfast', emoji: '🍳' },
      { word: 'brush teeth', emoji: '🪥' },
      { word: 'play outside', emoji: '🏃' },
      { word: 'go to bed', emoji: '🛏️' },
      { word: 'headache', emoji: '🤕' },
      { word: 'toothache', emoji: '🦷' },
      { word: 'stomachache', emoji: '🤢' },
      { word: 'healthy', emoji: '🥗' },
      { word: 'junk food', emoji: '🍔' },
      { word: 'soda', emoji: '🥤' },
      { word: 'exercise', emoji: '🤸' },
      { word: 'sleep', emoji: '😴' },
    ],
  },
  {
    title_ar: 'Unit 5: Hanging Out in Town',
    title_en: 'Unit 5: Hanging Out in Town',
    image: 'https://media.base44.com/images/public/6a459ddfe6fb4264c098136d/57b5a2ec5_generated_image.png',
    chant: `I want a stapler and staples. I'm going to the stationery store.\nYou want some candy. You're going to the candy store.\nMom wants some bread and cakes. She's going to the bakery.\nWe want some books. We're going to the bookstore.\nGrandma and Grandpa want some flowers and pots. They're going to the flower store.`,
    listening_text: `Excuse me. Where's the post office? Is it far from here? — Go straight and you'll find it on your left. It's near. You're welcome.`,
    phonics: ['u_e: cube, cute, mule', 'ue: barbecue, blue, glue'],
    goals: [
      { number: 81, section: 'Challenge Time', i_can: 'tell a partner how to get to two places on the map.' },
      { number: 82, section: 'Challenge Time', i_can: 'give someone directions in my town when I\'m asked.' },
      { number: 83, section: 'Challenge Time', i_can: 'say six names of stores.' },
      { number: 84, section: 'Challenge Time', i_can: 'say what I want and where I\'m going to buy it.' },
      { number: 85, section: 'Reading', i_can: 'read and chant the There Was a Little Green House chant.' },
      { number: 86, section: 'Writing', i_can: 'write my own version of the chant, add pictures, and present it.' },
      { number: 87, section: 'Phonics', i_can: 'say, read, and write words with u_e and ue.' },
      { number: 88, section: 'Challenge Time', i_can: 'read six signs in my town in English.' },
    ],
    vocab: [
      { word: 'bakery', emoji: '🥖' },
      { word: 'stationery store', emoji: '✏️' },
      { word: 'coffee shop', emoji: '☕' },
      { word: 'bookstore', emoji: '📚' },
      { word: 'flower store', emoji: '🌻' },
      { word: 'butcher shop', emoji: '🥩' },
      { word: 'convenience store', emoji: '🏪' },
      { word: 'supermarket', emoji: '🛒' },
      { word: 'post office', emoji: '📮' },
      { word: 'bus stop', emoji: '🚏' },
      { word: 'train station', emoji: '🚉' },
      { word: 'elementary school', emoji: '🏫' },
      { word: 'straight', emoji: '⬆️' },
      { word: 'left', emoji: '⬅️' },
      { word: 'right', emoji: '➡️' },
      { word: 'near', emoji: '📍' },
    ],
  },
  {
    title_ar: 'Unit 6: My Dream Vacation',
    title_en: 'Unit 6: My Dream Vacation',
    image: 'https://media.base44.com/images/public/6a459ddfe6fb4264c098136d/e24af7527_generated_image.png',
    chant: `I'm going to visit the city of Abha in Asir.\nYou're going to watch camel races in Riyadh.\nHe's going to visit the Children's Art Show at the Kingdom Tower.\nShe's going to shop in Dubai.\nWe're going to go rock climbing in the Wadi Rum Reserve, in Jordan.\nThey're going to eat traditional dishes in Lebanon.`,
    listening_text: `Where are you going? — I'm going to Abha.\nHow long does it take to get there? — It takes about two hours.\nWhat are you going to do there? — I'm going sightseeing.\nGood evening. What would you like to drink? — I'd like some juice, please. Apple or orange juice? — Apple juice, please.`,
    phonics: ['Review: beautiful, clouds, seas, enough, photo, square, scarf, barbecue'],
    goals: [
      { number: 89, section: 'Speaking', i_can: "say where I'm going, how long it takes, and what I'm going to do on a trip." },
      { number: 90, section: 'Speaking', i_can: 'do a dialogue between a flight attendant and a customer with a partner.' },
      { number: 91, section: 'Speaking', i_can: 'chant the Going To + Verb chant.' },
      { number: 92, section: 'Speaking', i_can: 'say where I want to go on my trip and what I want to do there.' },
      { number: 93, section: 'Reading', i_can: 'read the Vision 2030 Kingdom of Saudi Arabia chant by myself.' },
      { number: 94, section: 'Writing', i_can: 'write my own chant, add my own pictures, and present it.' },
      { number: 95, section: 'Grammar', i_can: 'use too or enough to say if something is the right or wrong size.' },
      { number: 96, section: 'Writing', i_can: 'read and write a short postcard from my trip.' },
    ],
    vocab: [
      { word: 'sightseeing', emoji: '📸' },
      { word: 'skiing', emoji: '⛷️' },
      { word: 'diving', emoji: '🤿' },
      { word: 'English camp', emoji: '⛺' },
      { word: 'juice', emoji: '🧃' },
      { word: 'water', emoji: '💧' },
      { word: 'cola', emoji: '🥤' },
      { word: 'beef', emoji: '🥩' },
      { word: 'fish', emoji: '🐟' },
      { word: 'noodles', emoji: '🍜' },
      { word: 'rice', emoji: '🍚' },
      { word: 'tea', emoji: '🍵' },
      { word: 'coffee', emoji: '☕' },
      { word: 'Abha', emoji: '📍' },
      { word: 'Riyadh', emoji: '🏙️' },
      { word: 'Dubai', emoji: '🇦🇪' },
    ],
  },
  // === Phonics Sections ===
  {
    title_ar: 'Phonics: Long Vowels (a_e, i_e, o_e, u_e)',
    title_en: 'Phonics: Long Vowels',
    image: 'https://media.base44.com/images/public/6a459ddfe6fb4264c098136d/7b6a38abd_generated_image.png',
    chant: '',
    listening_text: '',
    phonics: ['a_e: tape, snake, cake, gate', 'i_e: pine, time, bike, dive', 'o_e: rose, home, bone, rope', 'u_e: cube, tube, cute, mule'],
    goals: [
      { number: 97, section: 'Phonics', i_can: 'identify and say long vowel sounds.' },
      { number: 98, section: 'Phonics', i_can: 'spell words with long vowel patterns.' },
    ],
    vocab: [
      { word: 'tape', emoji: '🎞️' },
      { word: 'snake', emoji: '🐍' },
      { word: 'cake', emoji: '🎂' },
      { word: 'gate', emoji: '⛩️' },
      { word: 'pine', emoji: '🌲' },
      { word: 'time', emoji: '⏰' },
      { word: 'bike', emoji: '🚲' },
      { word: 'dive', emoji: '🤿' },
      { word: 'rose', emoji: '🌹' },
      { word: 'home', emoji: '🏠' },
      { word: 'bone', emoji: '🦴' },
      { word: 'rope', emoji: '🪢' },
      { word: 'cube', emoji: '🧊' },
      { word: 'cute', emoji: '🥰' },
      { word: 'mule', emoji: '🐴' },
      { word: 'globe', emoji: '🌍' },
    ],
  },
  {
    title_ar: 'Phonics: Vowel Teams (ai, ea, oa, etc.)',
    title_en: 'Phonics: Vowel Teams',
    image: 'https://media.base44.com/images/public/6a459ddfe6fb4264c098136d/cdf387544_generated_image.png',
    chant: '',
    listening_text: '',
    phonics: ['ai: rain, train, snail', 'ay: day, hay, May', 'ea: peach, meat, seal', 'ee: cheese, green, sleep', 'oa: boat, coat, goat', 'oo: book, look, moon'],
    goals: [
      { number: 99, section: 'Phonics', i_can: 'identify and say vowel team sounds.' },
      { number: 100, section: 'Phonics', i_can: 'spell words with vowel team patterns.' },
    ],
    vocab: [
      { word: 'rain', emoji: '🌧️' },
      { word: 'train', emoji: '🚆' },
      { word: 'snail', emoji: '🐌' },
      { word: 'day', emoji: '☀️' },
      { word: 'hay', emoji: '🌾' },
      { word: 'peach', emoji: '🍑' },
      { word: 'meat', emoji: '🥩' },
      { word: 'seal', emoji: '🦭' },
      { word: 'cheese', emoji: '🧀' },
      { word: 'green', emoji: '🟢' },
      { word: 'sleep', emoji: '😴' },
      { word: 'monkey', emoji: '🐒' },
      { word: 'honey', emoji: '🍯' },
      { word: 'boat', emoji: '⛵' },
      { word: 'coat', emoji: '🧥' },
      { word: 'goat', emoji: '🐐' },
    ],
  },
  {
    title_ar: 'Phonics: Consonant Blends & Digraphs',
    title_en: 'Phonics: Blends & Digraphs',
    image: 'https://media.base44.com/images/public/6a459ddfe6fb4264c098136d/e24af7527_generated_image.png',
    chant: `Knock, knock! Who's there? Lettuce. Lettuce who? Lettuce in. It's cold out here!`,
    listening_text: '',
    phonics: ['th: think, bath, this', 'ng: ring, spring, swing', 'ck: duck, rock, sock', 'cl: clock, cloud, clown', 'cr: crab, crayon, cry', 'pl: plant, plate, play', 'kn: knock, knee, knife', 'igh: night, light, right', 'wr: write, wrist', 'tch: catch, match, switch'],
    goals: [
      { number: 101, section: 'Phonics', i_can: 'identify and say consonant blend sounds.' },
      { number: 102, section: 'Phonics', i_can: 'spell words with consonant blends and digraphs.' },
    ],
    vocab: [
      { word: 'think', emoji: '🤔' },
      { word: 'bath', emoji: '🛁' },
      { word: 'ring', emoji: '💍' },
      { word: 'spring', emoji: '🌸' },
      { word: 'duck', emoji: '🦆' },
      { word: 'rock', emoji: '🪨' },
      { word: 'clock', emoji: '⏰' },
      { word: 'cloud', emoji: '☁️' },
      { word: 'crab', emoji: '🦀' },
      { word: 'plant', emoji: '🌱' },
      { word: 'flag', emoji: '🇸🇦' },
      { word: 'knock', emoji: '✊' },
      { word: 'knee', emoji: '🦵' },
      { word: 'night', emoji: '🌙' },
      { word: 'write', emoji: '✍️' },
      { word: 'catch', emoji: '⚾' },
    ],
  },
];

export const WORD_EMOJI_EN_G3 = ENGLISH_G3_S2_UNITS.reduce((acc, unit) => {
  unit.vocab.forEach(v => { acc[v.word] = v.emoji; });
  return acc;
}, {});

const _gen = makeBankGenerator(
  ENGLISH_G3_S2_UNITS.map(u => ({
    title_ar: u.title_en,
    image: u.image,
    lessons: u.vocab.map((v, i) => ({
      title_ar: v.word,
      words: u.vocab.slice(i, i + 4).map(w => w.word),
      ordering_items: u.goals.slice(0, 3).map(g => g.i_can),
      comprehension_q: [`What does "${v.word}" mean?`, `Use "${v.word}" in a sentence.`, `Show me ${v.word}.`],
      key_sentence: u.listening_text.split('\n')[0] || `I can say: ${v.word}`,
    })),
  })),
  WORD_EMOJI_EN_G3,
  'topic'
);

export const getExercisesForEnglishG3S2Lesson = _gen.getExercisesForLesson;
export const getAdaptiveLadderG3 = _gen.getAdaptiveLadder;
export const TOTAL_LESSONS_ENGLISH_G3_S2 = _gen.totalLessons;
export const TOTAL_QUESTIONS_ENGLISH_G3_S2 = _gen.totalQuestions;