// بنك أسئلة اللغة الإنجليزية — الصف السادس الابتدائي — الفصل الثاني
// موضوعات: Past Tense · Future Plans · Health & Advice · Travel & Places

export const ENGLISH_G6_S2_UNITS = [
  // ══════════════════════════════════════════════════════
  // Unit 1 — Past Tense Stories
  // ══════════════════════════════════════════════════════
  {
    id: 'past',
    title_ar: 'Unit 7 — Past Tense Stories',
    color: 'from-rose-600 to-rose-400',
    icon: '📖',
    lessons: [
      {
        id: 'past_l1',
        title_ar: 'Was / Were (p4–7)',
        questions: [
          {
            type: 'yesno',
            q: 'We use "was" with I, He, She, It in the past tense.',
            correct: true,
            explanation: '"Was" is used with singular subjects (I, He, She, It). "Were" is used with plural subjects and "You".',
            golden_rule: 'Singular (I/He/She/It) → was. Plural (We/You/they) → were.',
          },
          {
            type: 'mc',
            q: 'Choose: "They ___ at the park yesterday."',
            options: ['was', 'were', 'is', 'are'],
            correct: 1,
            explanation: '"They" is plural, so we use "were". "Yesterday" signals the past tense.',
            golden_rule: 'Plural subject + past → were.',
          },
          {
            type: 'mc',
            q: 'Choose: "She ___ happy last night."',
            options: ['were', 'was', 'is', 'are'],
            correct: 1,
            explanation: '"She" is singular, so we use "was". "Last night" signals the past.',
            golden_rule: 'Singular subject + past → was.',
          },
          {
            type: 'word_order',
            q: 'Form a sentence:',
            words: ['I', 'was', 'at', 'home', 'yesterday'],
            correct_sentence: 'I was at home yesterday',
            explanation: 'Subject (I) + was + place (at home) + time (yesterday).',
            golden_rule: 'Subject + was/were + complement + time.',
          },
          {
            type: 'matching',
            q: 'Match the subject to the correct past verb:',
            pairs: [
              { left: 'I', right: 'was' },
              { left: 'They', right: 'were' },
              { left: 'She', right: 'was' },
              { left: 'We', right: 'were' },
            ],
            explanation: 'I/She → was (singular). They/We → were (plural).',
            golden_rule: 'Singular → was. Plural → were.',
          },
          {
            type: 'yesno',
            q: '"You were tired" is grammatically correct.',
            correct: true,
            explanation: '"You" always takes "were" in the past tense, even when singular.',
            golden_rule: 'You → were (always, even for one person).',
          },
          {
            type: 'mc',
            q: 'Choose: "___ you at school on Monday?"',
            options: ['Was', 'Were', 'Is', 'Do'],
            correct: 1,
            explanation: 'Question form: Were + you + place + time? "You" always uses "were".',
            golden_rule: 'Question: Were/Was + subject + ...?',
          },
          {
            type: 'ordering',
            q: 'Order the days of the past week (oldest first):',
            items: ['Wednesday', 'Monday', 'Tuesday', 'Thursday'],
            correct_order: [1, 2, 0, 3],
            explanation: 'Monday → Tuesday → Wednesday → Thursday.',
            golden_rule: 'Days in order: Mon, Tue, Wed, Thu, Fri, Sat, Sun.',
          },
          {
            type: 'classify',
            q: 'Classify: Singular (was) or Plural (were)?',
            categories: ['Singular (was)', 'Plural (were)'],
            items: [
              { text: 'He', correct_cat: 0 },
              { text: 'They', correct_cat: 1 },
              { text: 'It', correct_cat: 0 },
              { text: 'We', correct_cat: 1 },
            ],
            explanation: 'He/It → singular → was. They/We → plural → were.',
            golden_rule: 'Singular → was. Plural → were.',
          },
        ],
      },
      {
        id: 'past_l2',
        title_ar: 'Regular & Irregular Verbs (p8–13)',
        questions: [
          {
            type: 'mc',
            q: 'Past form of "play":',
            options: ['plaied', 'played', 'playd', 'plays'],
            correct: 1,
            explanation: 'Regular verbs add -ed: play → played.',
            golden_rule: 'Regular verb + ed = past tense.',
          },
          {
            type: 'mc',
            q: 'Past form of "go":',
            options: ['goed', 'gone', 'went', 'going'],
            correct: 2,
            explanation: '"Go" is irregular: go → went (past), gone (past participle).',
            golden_rule: 'Irregular verbs change the whole word: go → went.',
          },
          {
            type: 'mc',
            q: 'Past form of "eat":',
            options: ['eated', 'ate', 'eaten', 'eats'],
            correct: 1,
            explanation: '"Eat" is irregular: eat → ate.',
            golden_rule: 'Irregular: eat → ate.',
          },
          {
            type: 'yesno',
            q: 'The past form of "study" is "studyed".',
            correct: false,
            explanation: 'Wrong! After a consonant + y, change y to i: study → studied.',
            golden_rule: 'Consonant + y → change y to i + ed: study → studied.',
          },
          {
            type: 'matching',
            q: 'Match each verb to its past form:',
            pairs: [
              { left: 'see', right: 'saw' },
              { left: 'have', right: 'had' },
              { left: 'run', right: 'ran' },
              { left: 'come', right: 'came' },
            ],
            explanation: 'Irregular verbs: see→saw, have→had, run→ran, come→came.',
            golden_rule: 'Irregular verbs must be memorized — they don\'t follow -ed.',
          },
          {
            type: 'word_order',
            q: 'Form a past tense sentence:',
            words: ['She', 'visited', 'her', 'grandmother', 'yesterday'],
            correct_sentence: 'She visited her grandmother yesterday',
            explanation: 'Subject + past verb + object + time.',
            golden_rule: 'Subject + past verb + object + time.',
          },
          {
            type: 'classify',
            q: 'Classify: Regular (+ed) or Irregular?',
            categories: ['Regular (+ed)', 'Irregular'],
            items: [
              { text: 'walk → walked', correct_cat: 0 },
              { text: 'go → went', correct_cat: 1 },
              { text: 'jump → jumped', correct_cat: 0 },
              { text: 'see → saw', correct_cat: 1 },
            ],
            explanation: 'walk/jump → +ed (regular). go/see → changed (irregular).',
            golden_rule: 'Regular = +ed. Irregular = word changes.',
          },
          {
            type: 'mc',
            q: 'Choose: "They ___ football last Friday."',
            options: ['play', 'played', 'plays', 'playing'],
            correct: 1,
            explanation: '"Last Friday" = past → played. Regular verb play → played.',
            golden_rule: 'Time signal (last/yesterday/ago) → past tense.',
          },
          {
            type: 'ordering',
            q: 'Order the story events:',
            items: ['They went home', 'They played football', 'They ate lunch', 'They woke up'],
            correct_order: [3, 1, 2, 0],
            explanation: 'Story order: woke up → played → ate → went home.',
            golden_rule: 'Past tense tells events in order — use time signals.',
          },
        ],
      },
    ],
  },

  // ══════════════════════════════════════════════════════
  // Unit 2 — Future Plans
  // ══════════════════════════════════════════════════════
  {
    id: 'future',
    title_ar: 'Unit 8 — Future Plans',
    color: 'from-sky-600 to-sky-400',
    icon: '🚀',
    lessons: [
      {
        id: 'fut_l1',
        title_ar: 'Will & Going To (p14–18)',
        questions: [
          {
            type: 'yesno',
            q: '"Will" is used for instant decisions and predictions.',
            correct: true,
            explanation: '"Will" = instant decision ("I\'ll help you"), prediction ("It will rain"), or promise.',
            golden_rule: 'Will = instant decision / prediction / promise.',
          },
          {
            type: 'mc',
            q: 'Choose: "I think it ___ rain tomorrow."',
            options: ['will', 'going to', 'is', 'was'],
            correct: 0,
            explanation: 'Prediction about tomorrow → "will rain".',
            golden_rule: 'Prediction → will + verb.',
          },
          {
            type: 'mc',
            q: 'Choose: "They are ___ visit their aunt next week."',
            options: ['will', 'going to', 'was', 'go'],
            correct: 1,
            explanation: 'Planned future → "going to". Structure: am/is/are + going to + verb.',
            golden_rule: 'Plan/intention → am/is/are + going to + verb.',
          },
          {
            type: 'word_order',
            q: 'Form a future sentence:',
            words: ['I', 'will', 'call', 'you', 'tomorrow'],
            correct_sentence: 'I will call you tomorrow',
            explanation: 'Subject + will + verb + object + time.',
            golden_rule: 'Subject + will + verb + rest.',
          },
          {
            type: 'matching',
            q: 'Match the time signal to the tense:',
            pairs: [
              { left: 'tomorrow', right: 'future' },
              { left: 'yesterday', right: 'past' },
              { left: 'now', right: 'present' },
              { left: 'next week', right: 'future' },
            ],
            explanation: 'tomorrow/next week → future. yesterday → past. now → present.',
            golden_rule: 'Time signals tell you the tense: tomorrow=future, yesterday=past.',
          },
          {
            type: 'yesno',
            q: '"Going to" is used for plans decided before speaking.',
            correct: true,
            explanation: 'Correct! "Going to" = plan made earlier. "Will" = instant decision.',
            golden_rule: 'Plan before = going to. Instant = will.',
          },
          {
            type: 'mc',
            q: 'Choose: "The phone is ringing. I ___ answer it."',
            options: ['will', 'am going to', 'was', 'answered'],
            correct: 0,
            explanation: 'Instant decision (reacting now) → "will answer".',
            golden_rule: 'Instant reaction → will.',
          },
          {
            type: 'classify',
            q: 'Classify: Will (instant/prediction) or Going to (plan)?',
            categories: ['Will', 'Going to'],
            items: [
              { text: 'I think it will snow', correct_cat: 0 },
              { text: 'I am going to travel', correct_cat: 1 },
              { text: 'I\'ll help you now', correct_cat: 0 },
              { text: 'We plan to visit', correct_cat: 1 },
            ],
            explanation: 'Prediction/instant → will. Plan → going to.',
            golden_rule: 'Will = prediction/instant. Going to = plan.',
          },
          {
            type: 'ordering',
            q: 'Order the future time signals (nearest first):',
            items: ['next year', 'tomorrow', 'next week', 'tonight'],
            correct_order: [3, 1, 2, 0],
            explanation: 'tonight → tomorrow → next week → next year.',
            golden_rule: 'Future time signals: tonight, tomorrow, next week, next year.',
          },
        ],
      },
      {
        id: 'fut_l2',
        title_ar: 'Future Questions & Negatives (p19–22)',
        questions: [
          {
            type: 'mc',
            q: 'Negative: "She ___ come to the party."',
            options: ["won't", "willn't", "don't", "isn't"],
            correct: 0,
            explanation: 'Negative of "will" = "will not" = "won\'t".',
            golden_rule: 'Will not = won\'t.',
          },
          {
            type: 'yesno',
            q: '"Will you help me?" is a correct future question.',
            correct: true,
            explanation: 'Question form: Will + subject + verb?',
            golden_rule: 'Future question: Will + subject + verb?',
          },
          {
            type: 'word_order',
            q: 'Form a negative future sentence:',
            words: ['They', "won't", 'travel', 'next', 'summer'],
            correct_sentence: "They won't travel next summer",
            explanation: 'Subject + won\'t + verb + time.',
            golden_rule: 'Negative future: Subject + won\'t + verb.',
          },
          {
            type: 'mc',
            q: 'Question: "___ you going to study tonight?"',
            options: ['Will', 'Are', 'Is', 'Do'],
            correct: 1,
            explanation: 'Going-to question: Are/Is + subject + going to + verb?',
            golden_rule: 'Going-to question: Am/Is/Are + subject + going to + verb?',
          },
          {
            type: 'matching',
            q: 'Match the sentence to its type:',
            pairs: [
              { left: 'I will help', right: 'promise' },
              { left: 'I won\'t go', right: 'negative' },
              { left: 'Will you come?', right: 'question' },
              { left: 'It will rain', right: 'prediction' },
            ],
            explanation: 'will help = promise. won\'t go = negative. Will you come? = question. will rain = prediction.',
            golden_rule: 'Will has many uses: promise, negative (won\'t), question, prediction.',
          },
          {
            type: 'mc',
            q: 'Choose: "He isn\'t ___ play football tomorrow."',
            options: ['going to', 'will', 'went', 'go'],
            correct: 0,
            explanation: 'Negative going-to: isn\'t + going to + verb.',
            golden_rule: 'Negative going-to: isn\'t/aren\'t + going to + verb.',
          },
          {
            type: 'yesno',
            q: '"Won\'t" is the short form of "will not".',
            correct: true,
            explanation: 'Correct! won\'t = will not. Used for negative future.',
            golden_rule: 'won\'t = will not.',
          },
          {
            type: 'ordering',
            q: 'Order words to form a question:',
            items: ['Will', 'you', 'help', 'me'],
            correct_order: [0, 1, 2, 3],
            explanation: 'Question: Will + subject + verb + object?',
            golden_rule: 'Future question: Will + subject + verb + object?',
          },
        ],
      },
    ],
  },

  // ══════════════════════════════════════════════════════
  // Unit 3 — Health & Advice
  // ══════════════════════════════════════════════════════
  {
    id: 'health',
    title_ar: 'Unit 9 — Health & Advice',
    color: 'from-emerald-600 to-emerald-400',
    icon: '🩺',
    lessons: [
      {
        id: 'hl_l1',
        title_ar: 'Should / Shouldn\'t (p23–27)',
        questions: [
          {
            type: 'yesno',
            q: '"Should" is used to give advice.',
            correct: true,
            explanation: '"Should" = advice or recommendation. "Shouldn\'t" = advice not to do something.',
            golden_rule: 'Should = advice. Shouldn\'t = don\'t do it.',
          },
          {
            type: 'mc',
            q: 'Advice: "You ___ drink lots of water."',
            options: ['should', 'shouldn\'t', 'will', 'was'],
            correct: 0,
            explanation: 'Positive advice → should + verb.',
            golden_rule: 'Positive advice → should + verb.',
          },
          {
            type: 'mc',
            q: 'Advice: "You ___ eat too much junk food."',
            options: ['should', 'shouldn\'t', 'will', 'do'],
            correct: 1,
            explanation: 'Negative advice (don\'t eat junk food) → shouldn\'t + verb.',
            golden_rule: 'Negative advice → shouldn\'t + verb.',
          },
          {
            type: 'word_order',
            q: 'Form advice:',
            words: ['You', 'should', 'sleep', 'early'],
            correct_sentence: 'You should sleep early',
            explanation: 'Subject + should + verb + rest.',
            golden_rule: 'Advice: Subject + should + verb.',
          },
          {
            type: 'matching',
            q: 'Match the problem to the advice:',
            pairs: [
              { left: 'I have a headache', right: 'You should rest' },
              { left: 'I\'m tired', right: 'You should sleep' },
              { left: 'I\'m hungry', right: 'You should eat' },
              { left: 'I\'m thirsty', right: 'You should drink' },
            ],
            explanation: 'Match each problem to its logical advice using "should".',
            golden_rule: 'Problem → You should + (solution).',
          },
          {
            type: 'yesno',
            q: '"Shouldn\'t" means "it is a good idea to do it".',
            correct: false,
            explanation: 'Wrong! "Shouldn\'t" means "it is NOT a good idea". Should = good idea.',
            golden_rule: 'Should = good idea. Shouldn\'t = bad idea.',
          },
          {
            type: 'mc',
            q: 'Question: "___ I see a doctor?"',
            options: ['Should', 'Will', 'Was', 'Do'],
            correct: 0,
            explanation: 'Asking for advice → Should + subject + verb?',
            golden_rule: 'Advice question: Should + subject + verb?',
          },
          {
            type: 'classify',
            q: 'Classify: Good idea (should) or Bad idea (shouldn\'t)?',
            categories: ['Should (good)', 'Shouldn\'t (bad)'],
            items: [
              { text: 'Exercise daily', correct_cat: 0 },
              { text: 'Smoke', correct_cat: 1 },
              { text: 'Eat vegetables', correct_cat: 0 },
              { text: 'Stay up all night', correct_cat: 1 },
            ],
            explanation: 'Exercise/eat veg → should. Smoke/stay up → shouldn\'t.',
            golden_rule: 'Healthy → should. Unhealthy → shouldn\'t.',
          },
          {
            type: 'ordering',
            q: 'Order the health tips (most important first):',
            items: ['Eat healthy food', 'Exercise', 'Sleep 8 hours', 'Drink water'],
            correct_order: [3, 0, 1, 2],
            explanation: 'Water → food → exercise → sleep — all essential for health.',
            golden_rule: 'Water, food, exercise, sleep = four health pillars.',
          },
        ],
      },
      {
        id: 'hl_l2',
        title_ar: 'Body Parts & Illness (p28–32)',
        questions: [
          {
            type: 'mc',
            q: 'What do you use to see?',
            options: ['Ears', 'Eyes', 'Nose', 'Mouth'],
            correct: 1,
            explanation: 'We see with our eyes 👀.',
            golden_rule: 'See → eyes. Hear → ears. Smell → nose. Taste → mouth.',
          },
          {
            type: 'mc',
            q: 'What do you use to hear?',
            options: ['Eyes', 'Ears', 'Hands', 'Feet'],
            correct: 1,
            explanation: 'We hear with our ears 👂.',
            golden_rule: 'Hear → ears.',
          },
          {
            type: 'matching',
            q: 'Match the body part to its action:',
            pairs: [
              { left: 'Eyes', right: 'see' },
              { left: 'Ears', right: 'hear' },
              { left: 'Nose', right: 'smell' },
              { left: 'Mouth', right: 'taste' },
            ],
            explanation: 'Eyes→see, Ears→hear, Nose→smell, Mouth→taste.',
            golden_rule: 'Five senses: see, hear, smell, taste, touch.',
          },
          {
            type: 'yesno',
            q: '"I have a stomachache" means my stomach hurts.',
            correct: true,
            explanation: 'Stomachache = pain in the stomach. Headache = head pain. Toothache = tooth pain.',
            golden_rule: '-ache = pain: headache, stomachache, toothache, earache.',
          },
          {
            type: 'mc',
            q: 'Choose: "I have a ___. My tooth hurts."',
            options: ['headache', 'toothache', 'stomachache', 'fever'],
            correct: 1,
            explanation: 'Tooth pain → toothache.',
            golden_rule: 'Toothache = tooth pain. See a dentist.',
          },
          {
            type: 'classify',
            q: 'Classify: Illness or Body part?',
            categories: ['Illness', 'Body part'],
            items: [
              { text: 'Headache', correct_cat: 0 },
              { text: 'Arm', correct_cat: 1 },
              { text: 'Fever', correct_cat: 0 },
              { text: 'Leg', correct_cat: 1 },
            ],
            explanation: 'Headache/fever = illness. Arm/leg = body parts.',
            golden_rule: 'Illness = a health problem. Body part = a part of you.',
          },
          {
            type: 'word_order',
            q: 'Form a sentence:',
            words: ['I', 'have', 'a', 'headache'],
            correct_sentence: 'I have a headache',
            explanation: 'I + have + a + illness.',
            golden_rule: 'Describing illness: I have a + (illness).',
          },
          {
            type: 'mc',
            q: 'Advice for a fever: "You ___ see a doctor."',
            options: ['should', 'shouldn\'t', 'won\'t', 'was'],
            correct: 0,
            explanation: 'Fever is serious → should see a doctor.',
            golden_rule: 'Serious illness → should see a doctor.',
          },
        ],
      },
    ],
  },

  // ══════════════════════════════════════════════════════
  // Unit 4 — Travel & Places
  // ══════════════════════════════════════════════════════
  {
    id: 'travel',
    title_ar: 'Unit 10 — Travel & Places',
    color: 'from-amber-600 to-amber-400',
    icon: '✈️',
    lessons: [
      {
        id: 'tr_l1',
        title_ar: 'There is / There are (p33–37)',
        questions: [
          {
            type: 'yesno',
            q: '"There is" is used for singular nouns.',
            correct: true,
            explanation: 'Singular → There is. Plural → There are.',
            golden_rule: 'Singular → There is. Plural → There are.',
          },
          {
            type: 'mc',
            q: 'Choose: "___ a book on the table."',
            options: ['There is', 'There are', 'There was', 'There were'],
            correct: 0,
            explanation: '"A book" is singular → There is.',
            golden_rule: 'One thing → There is + a + noun.',
          },
          {
            type: 'mc',
            q: 'Choose: "___ three chairs in the room."',
            options: ['There is', 'There are', 'There was', 'It is'],
            correct: 1,
            explanation: '"Three chairs" is plural → There are.',
            golden_rule: 'More than one → There are + plural noun.',
          },
          {
            type: 'word_order',
            q: 'Form a sentence:',
            words: ['There', 'is', 'a', 'mosque', 'near', 'my', 'house'],
            correct_sentence: 'There is a mosque near my house',
            explanation: 'There is + a + noun + place.',
            golden_rule: 'There is + a + singular noun + place.',
          },
          {
            type: 'matching',
            q: 'Match the quantity to the structure:',
            pairs: [
              { left: 'One cat', right: 'There is' },
              { left: 'Two cats', right: 'There are' },
              { left: 'A pen', right: 'There is' },
              { left: 'Five pens', right: 'There are' },
            ],
            explanation: 'One/a → There is. Two+/number → There are.',
            golden_rule: 'Singular quantity → is. Plural quantity → are.',
          },
          {
            type: 'yesno',
            q: 'Negative: "There isn\'t a park here." is correct.',
            correct: true,
            explanation: 'Negative singular: There isn\'t (is not). Negative plural: There aren\'t (are not).',
            golden_rule: 'Negative: isn\'t (singular), aren\'t (plural).',
          },
          {
            type: 'mc',
            q: 'Question: "___ there a bank near here?"',
            options: ['Is', 'Are', 'Was', 'Do'],
            correct: 0,
            explanation: 'Question singular: Is there + a + noun?',
            golden_rule: 'Question: Is/Are + there + noun?',
          },
          {
            type: 'classify',
            q: 'Classify: Singular (is) or Plural (are)?',
            categories: ['Singular (is)', 'Plural (are)'],
            items: [
              { text: 'a school', correct_cat: 0 },
              { text: 'two schools', correct_cat: 1 },
              { text: 'a hospital', correct_cat: 0 },
              { text: 'three hospitals', correct_cat: 1 },
            ],
            explanation: 'a + noun → singular → is. number + noun → plural → are.',
            golden_rule: 'a/an → is. number>1 → are.',
          },
          {
            type: 'ordering',
            q: 'Order places from smallest to largest:',
            items: ['City', 'Village', 'Country', 'Town'],
            correct_order: [1, 3, 0, 2],
            explanation: 'Village (smallest) → Town → City → Country (largest).',
            golden_rule: 'Place sizes: Village < Town < City < Country.',
          },
        ],
      },
      {
        id: 'tr_l2',
        title_ar: 'Transportation & Directions (p38–42)',
        questions: [
          {
            type: 'mc',
            q: 'Which one flies in the sky?',
            options: ['Plane', 'Ship', 'Car', 'Train'],
            correct: 0,
            explanation: 'Plane ✈️ flies. Ship sails. Car drives. Train runs on tracks.',
            golden_rule: 'Plane = air. Ship = sea. Car/Bus = road. Train = tracks.',
          },
          {
            type: 'mc',
            q: 'Which one travels on water?',
            options: ['Plane', 'Ship', 'Car', 'Bus'],
            correct: 1,
            explanation: 'Ship 🚢 sails on water.',
            golden_rule: 'Water transport: ship, boat, ferry.',
          },
          {
            type: 'matching',
            q: 'Match the transport to where it travels:',
            pairs: [
              { left: 'Plane', right: 'Air' },
              { left: 'Ship', right: 'Water' },
              { left: 'Train', right: 'Tracks' },
              { left: 'Car', right: 'Road' },
            ],
            explanation: 'Plane→air, Ship→water, Train→tracks, Car→road.',
            golden_rule: 'Each transport has its place: air, water, tracks, road.',
          },
          {
            type: 'yesno',
            q: '"Turn left" means go to the left side.',
            correct: true,
            explanation: 'Turn left ←, turn right →, go straight ↑, stop 🛑.',
            golden_rule: 'Directions: left, right, straight, stop, turn around.',
          },
          {
            type: 'mc',
            q: 'The opposite of "turn left" is:',
            options: ['Turn right', 'Go straight', 'Stop', 'Turn around'],
            correct: 0,
            explanation: 'Left ↔ Right. Opposite of left = right.',
            golden_rule: 'Opposites: left ↔ right, fast ↔ slow, near ↔ far.',
          },
          {
            type: 'classify',
            q: 'Classify: Air or Water transport?',
            categories: ['Air', 'Water'],
            items: [
              { text: 'Plane', correct_cat: 0 },
              { text: 'Boat', correct_cat: 1 },
              { text: 'Helicopter', correct_cat: 0 },
              { text: 'Ship', correct_cat: 1 },
            ],
            explanation: 'Plane/helicopter → air. Boat/ship → water.',
            golden_rule: 'Air: plane, helicopter. Water: boat, ship, ferry.',
          },
          {
            type: 'word_order',
            q: 'Form a directions sentence:',
            words: ['Go', 'straight', 'and', 'turn', 'left'],
            correct_sentence: 'Go straight and turn left',
            explanation: 'Direction command: Go straight + and + turn + direction.',
            golden_rule: 'Directions: Go straight → turn left/right.',
          },
          {
            type: 'mc',
            q: 'Choose: "The hospital is ___ the school and the park."',
            options: ['between', 'on', 'in', 'under'],
            correct: 0,
            explanation: '"Between" = in the middle of two things.',
            golden_rule: 'Between = middle of two. Next to = beside. In front of / behind.',
          },
        ],
      },
    ],
  },
];

export const ENGLISH_G6_S2_TOTAL = ENGLISH_G6_S2_UNITS.reduce(
  (sum, u) => sum + u.lessons.reduce((s, l) => s + l.questions.length, 0),
  0
);