// بنك أسئلة TopGoal 2 — تدريبات كتاب التدريبات (الوحدات 3–7)
// المصدر: TopGoal 2 Workbook | McGraw-Hill 2025-1447 | p150–207

export const TOPGOAL2_WB_UNITS_3TO7 = [
  // ══════════════════════════════════════════════════════
  // Workbook Units 3 & 4 — Jobs / Food
  // ══════════════════════════════════════════════════════
  {
    id: 'wb34',
    title_ar: 'Workbook — Units 3 & 4 (Jobs & Food)',
    color: 'from-amber-700 to-orange-500',
    icon: '📋',
    lessons: [
      {
        id: 'wb34_l1',
        title_ar: 'Unit 3 WB: May / Might / Be Going To (p150–151)',
        questions: [
          {
            type: 'mc',
            q: 'Complete: "Layla is sure she ___ be an artist. She hates painting." (WB p151)',
            options: ['may', 'might', "isn't going to", 'is going to'],
            correct: 2,
            explanation: 'From WB p151: "Layla is sure she isn\'t going to be an artist." = 0% certain → isn\'t going to.',
            golden_rule: '"Isn\'t going to" = definitely NOT going to happen. "May/might" = possible.',
          },
          {
            type: 'mc',
            q: 'Complete: "I think Justin ___ be a singer. His voice is very nice." (WB p151)',
            options: ['is going to', "isn't going to", 'may', 'won\'t'],
            correct: 2,
            explanation: 'From WB p151: "I think Justin may be a singer." — "think" suggests possibility, not certainty.',
            golden_rule: 'Use MAY when something is POSSIBLE (about 50%). Use BE GOING TO only when certain.',
          },
          {
            type: 'classify',
            q: 'Classify the future probability (WB p150–151):',
            categories: ['Certain (100%) — BE GOING TO', 'Possible (30–50%) — MAY / MIGHT'],
            items: [
              { text: 'They are going to be engineers. (✓ decided)', correct_cat: 0 },
              { text: 'She might not act in the future. (uncertain)', correct_cat: 1 },
              { text: 'My brother may be a fashion designer.', correct_cat: 1 },
              { text: 'You are not going to be a singer. (✗ decided)', correct_cat: 0 },
            ],
            explanation: 'From WB p150–151: future probability sentences.',
            golden_rule: 'BE GOING TO = certain plan. MAY/MIGHT = possibility, not certainty.',
          },
          {
            type: 'yesno',
            q: '"He\'s a flight attendant, isn\'t he?" is a correctly formed question tag. (WB p155)',
            correct: true,
            explanation: 'From WB p155: "He\'s a flight attendant, isn\'t he?" — affirmative statement → negative tag ✓.',
            golden_rule: 'Positive statement → negative tag (isn\'t he?). Negative statement → positive tag (is he?).',
          },
          {
            type: 'matching',
            q: 'Match each job to a key skill (WB p159):',
            pairs: [
              { left: 'pilot', right: 'is able to stay calm' },
              { left: 'manager', right: 'has leadership skills' },
              { left: 'artist', right: 'has knowledge of colors' },
              { left: 'flight attendant', right: 'communicates well' },
            ],
            explanation: 'From WB p159: job skills matching exercise.',
            golden_rule: 'Each job requires specific skills — learn them together.',
          },
          {
            type: 'word_order',
            q: 'Order the words to make a sentence about future possibility (WB p151):',
            words: ['Dan', 'in', 'work', 'company', 'may', "mom's", 'his', 'as', 'a', 'manager'],
            correct_sentence: "Dan may work as a manager in his mom's company",
            explanation: 'From WB p151: sentence rewrite exercise using "may".',
            golden_rule: 'Structure: Subject + may + base verb (no "to").',
          },
        ],
      },
      {
        id: 'wb34_l2',
        title_ar: 'Unit 4 WB: Should / Had Better / Zero Conditional (p162–167)',
        questions: [
          {
            type: 'mc',
            q: 'Choose the correct kitchen safety rule: "You ___ cook alone." (WB p162)',
            options: ['should', 'shouldn\'t', 'had better not', 'might'],
            correct: 1,
            explanation: 'From WB p162: "You shouldn\'t cook alone." — safety rule for children.',
            golden_rule: '"Shouldn\'t" = negative advice. "Had better not" = stronger negative warning.',
          },
          {
            type: 'mc',
            q: 'Choose the correct option: "If you ___ a good breakfast, you ___ lots of energy." (WB p167)',
            options: ['eat / have', 'ate / have', 'eat / will have', 'will eat / have'],
            correct: 0,
            explanation: 'From WB p167: "If you eat a good breakfast, you have lots of energy." — Zero Conditional.',
            golden_rule: 'Zero Conditional: If + simple present, simple present = always true.',
          },
          {
            type: 'classify',
            q: 'Classify each as a cooking SAFETY RULE (had better) or general ADVICE (should)? (WB p162)',
            categories: ['Safety — Had Better ⚠️', 'Advice — Should 💡'],
            items: [
              { text: 'You had better wash your hands before cooking.', correct_cat: 0 },
              { text: 'You should buy all your ingredients first.', correct_cat: 1 },
              { text: 'You had better not lick spoons or your fingers.', correct_cat: 0 },
              { text: 'You should bake in the oven.', correct_cat: 1 },
            ],
            explanation: 'From WB p162: Cooking Safety Tips for Children.',
            golden_rule: '"Had better" for urgent safety rules. "Should" for general good advice.',
          },
          {
            type: 'yesno',
            q: '"You shouldn\'t make a mess in the kitchen." can be rewritten as "You had better not make a mess." (WB p162)',
            correct: true,
            explanation: 'From WB p162: "shouldn\'t" → "had better not" — both express negative advice/warnings.',
            golden_rule: '"Shouldn\'t" and "had better not" both mean "it\'s a bad idea to..." — had better is stronger.',
          },
          {
            type: 'matching',
            q: 'Match each situation to the correct advice (WB p163):',
            pairs: [
              { left: '"This milk smells bad."', right: '"You had better not drink it."' },
              { left: '"I think I\'m getting toothache."', right: '"You shouldn\'t eat so much sugar."' },
              { left: '"We must get up early tomorrow."', right: '"Shouldn\'t you all be in bed now?"' },
              { left: '"I can\'t remember the recipe!"', right: '"You should have a recipe notebook."' },
            ],
            explanation: 'From WB p163: matching advice to situations.',
            golden_rule: 'Match the strength of advice to the seriousness of the situation.',
          },
          {
            type: 'word_order',
            q: 'Order the words to make a Zero Conditional sentence (WB p167):',
            words: ['don\'t', 'if', 'the', 'pancakes', 'beat', 'you', 'eggs', 'get', 'flat', 'the'],
            correct_sentence: "if you don't beat the eggs the pancakes get flat",
            explanation: 'From WB p167: "If you don\'t beat the eggs, the pancakes get flat."',
            golden_rule: 'Zero Conditional describes natural consequences: if A happens, B always happens.',
          },
        ],
      },
    ],
  },

  // ══════════════════════════════════════════════════════
  // Workbook Units 5 & 6 — Storylines / Outdoor Activities
  // ══════════════════════════════════════════════════════
  {
    id: 'wb56',
    title_ar: 'Workbook — Units 5 & 6 (Stories & Outdoors)',
    color: 'from-purple-700 to-teal-600',
    icon: '📖',
    lessons: [
      {
        id: 'wb56_l1',
        title_ar: 'Unit 5 WB: Story Genres & Past Progressive (p172–175)',
        questions: [
          {
            type: 'mc',
            q: 'Which story genre "creates a feeling of fear"? (WB p172)',
            options: ['comedy', 'horror', 'western', 'musical'],
            correct: 1,
            explanation: 'From WB p172: "This kind of story creates a feeling of fear." → horror.',
            golden_rule: 'Horror = fear. Comedy = laughter. Musical = songs. Western = American Wild West.',
          },
          {
            type: 'mc',
            q: '"Ivy ___ a fairy tale yesterday at 3 p.m." (WB p174)',
            options: ['reads', 'read', 'was reading', 'has read'],
            correct: 2,
            explanation: 'From WB p174: "Ivy was reading a fairy tale." — ongoing action at a specific past time.',
            golden_rule: 'Past Progressive (was/were + -ing) describes ongoing actions at a specific past moment.',
          },
          {
            type: 'classify',
            q: 'Classify these story types as REAL-LIFE or FANTASY (WB p172–173):',
            categories: ['Real-life / Based on facts', 'Fantasy / Imaginary'],
            items: [
              { text: 'documentary', correct_cat: 0 },
              { text: 'fairy tale', correct_cat: 1 },
              { text: 'western (real history)', correct_cat: 0 },
              { text: 'sci-fi (aliens & space)', correct_cat: 1 },
              { text: 'animation (3D)', correct_cat: 1 },
              { text: 'mystery (detective)', correct_cat: 0 },
            ],
            explanation: 'From WB p172–173: story genre vocabulary.',
            golden_rule: 'Documentaries present real facts. Fairy tales and sci-fi involve imaginary elements.',
          },
          {
            type: 'yesno',
            q: '"Was Bella writing a play yesterday at 3 p.m.?" is a correct Past Progressive question. (WB p175)',
            correct: true,
            explanation: 'From WB p175: "Was + subject + verb-ing?" is the correct Past Progressive question form.',
            golden_rule: 'Past Progressive questions: Was/Were + subject + verb-ing?',
          },
          {
            type: 'matching',
            q: 'Match each sentence to the correct tense (WB p174–175):',
            pairs: [
              { left: 'Ivy was reading a fairy tale.', right: 'Past Progressive (ongoing)' },
              { left: 'Elias made a documentary.', right: 'Simple Past (completed)' },
              { left: 'Were they watching a play?', right: 'Past Progressive (question)' },
              { left: 'Adam acted in a sci-fi movie.', right: 'Simple Past (completed)' },
            ],
            explanation: 'From WB p174: tense identification exercise.',
            golden_rule: 'Past Progressive = was/were + -ing. Simple Past = verb-ed or irregular.',
          },
          {
            type: 'word_order',
            q: 'Order the words to make a suggestion (WB p179):',
            words: ["don't", 'why', 'drama', 'pick', 'a', 'we'],
            correct_sentence: "why don't we pick a drama",
            explanation: 'From WB p179: "Why don\'t we pick a drama?"',
            golden_rule: '"Why don\'t we + base verb" suggests an activity. "How about + -ing" also works.',
          },
        ],
      },
      {
        id: 'wb56_l2',
        title_ar: 'Unit 6 WB: Outdoor Activities & When/While (p184–191)',
        questions: [
          {
            type: 'mc',
            q: '"Eli was ___ (lie) in the tent when he heard a noise." (WB p187)',
            options: ['lay', 'lied', 'lying', 'was lie'],
            correct: 2,
            explanation: 'From WB p187: "Eli was lying in the tent when he heard a noise." — Past Progressive for long action.',
            golden_rule: 'Past Progressive (was + -ing) = the long/background action. Simple Past = the short interrupting action.',
          },
          {
            type: 'mc',
            q: '"Carol was horseback riding ___ Mila was surfing." (WB p191)',
            options: ['when', 'while', 'after', 'before'],
            correct: 1,
            explanation: 'From WB p191: "Carol was horseback riding while Mila was surfing." — two simultaneous ongoing actions.',
            golden_rule: '"While" connects two ongoing (Past Progressive) actions happening at the same time.',
          },
          {
            type: 'classify',
            q: 'Choose when or while for each sentence (WB p191):',
            categories: ['when', 'while'],
            items: [
              { text: '___ Jack was rafting, his raft hit a rock.', correct_cat: 1 },
              { text: 'We ate the hotdogs ___ they were ready.', correct_cat: 0 },
              { text: '___ Dad was lighting the campfire, I was fishing.', correct_cat: 1 },
              { text: 'Did you fall ___ you were mountain biking?', correct_cat: 0 },
            ],
            explanation: 'From WB p191: when/while exercises.',
            golden_rule: '"While" = during a long ongoing action. "When" = at the moment of a short action.',
          },
          {
            type: 'yesno',
            q: '"Mary was reading in her tent when I saw her." is correct. (WB p186)',
            correct: true,
            explanation: 'From WB p186: "Mary was reading" (long action) + "I saw" (short interrupting action) ✓.',
            golden_rule: 'Long action = Past Progressive. Short interrupting action = Simple Past.',
          },
          {
            type: 'matching',
            q: 'Match each outdoor activity to the needed equipment (WB p184–185):',
            pairs: [
              { left: 'camping', right: 'tent and sleeping bag' },
              { left: 'rafting', right: 'raft and life jacket' },
              { left: 'fishing', right: 'fishing rod' },
              { left: 'mountain biking', right: 'helmet' },
            ],
            explanation: 'From WB p184–185: outdoor activities and equipment.',
            golden_rule: 'Always carry the right safety equipment before any outdoor activity.',
          },
          {
            type: 'word_order',
            q: 'Order the words to make a correct sentence (WB p191):',
            words: ['we', 'canoeing', 'it', 'when', 'started', 'were', 'raining'],
            correct_sentence: 'we were canoeing when it started raining',
            explanation: 'From WB p191: "We were canoeing when it started raining."',
            golden_rule: 'Long action (were canoeing) was interrupted by short action (started raining).',
          },
        ],
      },
    ],
  },

  // ══════════════════════════════════════════════════════
  // Workbook Unit 7 Extended — Reading & Travel Phrasal Verbs
  // ══════════════════════════════════════════════════════
  {
    id: 'wb7_ext',
    title_ar: 'Workbook — Unit 7 Extended (Reading & Phrasal Verbs)',
    color: 'from-indigo-600 to-blue-500',
    icon: '🗺️',
    lessons: [
      {
        id: 'wb7_ext_l1',
        title_ar: 'Unit 7 WB: Travelling Blog & Phrasal Verbs (p204–207)',
        questions: [
          {
            type: 'mc',
            q: 'In Kai\'s blog, why does his family sometimes want to "get away"? (WB p204)',
            options: ['Because they hate the beach.', 'Because they want to escape city life.', 'Because they don\'t have a car.', 'Because they are afraid of planes.'],
            correct: 1,
            explanation: 'From WB p204: "We sometimes want to get away from city life and go on trips."',
            golden_rule: '"Get away" means to escape from a place or situation for a rest.',
          },
          {
            type: 'mc',
            q: 'Match: "Passengers should check ___ two hours before the flight." (WB p205)',
            options: ['out', 'in', 'off', 'away'],
            correct: 1,
            explanation: 'From WB p205: "Passengers should check in two hours before the flight." = register at the airport.',
            golden_rule: '"Check in" = register at airport/hotel. "Check out" = pay and leave hotel.',
          },
          {
            type: 'matching',
            q: 'Match each travel phrasal verb to its meaning (WB p202, p205):',
            pairs: [
              { left: 'take off', right: 'when a plane begins to fly' },
              { left: 'get away', right: 'escape from a place for a rest' },
              { left: 'check out', right: 'pay the bill and leave a hotel' },
              { left: 'find out', right: 'discover new information' },
            ],
            explanation: 'From WB p202, p205: travel phrasal verbs exercises.',
            golden_rule: 'Phrasal verbs are common in travel contexts — learn them with example sentences.',
          },
          {
            type: 'classify',
            q: 'Classify these Present Perfect sentences by use (WB p207):',
            categories: ['Completed action (result)', 'Not done yet (negative)'],
            items: [
              { text: 'Dad has already bought the plane tickets.', correct_cat: 0 },
              { text: 'I haven\'t been to any fair yet.', correct_cat: 1 },
              { text: 'Mom has found a cool hotel.', correct_cat: 0 },
              { text: 'I haven\'t done it yet.', correct_cat: 1 },
            ],
            explanation: 'From WB p207: Present Perfect in context (diary entry).',
            golden_rule: 'Already = action done (positive). Yet = action not done (negative/question).',
          },
          {
            type: 'yesno',
            q: 'In the subway directions text (WB p206), the kids need to get off after THREE stops.',
            correct: true,
            explanation: 'From WB p206: "You\'ll go through three stops and get off at Green Park Station."',
            golden_rule: 'Read transport directions carefully — count the stops before getting off.',
          },
          {
            type: 'word_order',
            q: 'Order the words to make a Present Perfect sentence (WB p207):',
            words: ['have', 'the', 'already', 'they', 'tickets', 'booked', 'fair', 'for', 'the'],
            correct_sentence: 'they have already booked the tickets for the fair',
            explanation: 'From WB p207: "They have booked the tickets for the fair, too!"',
            golden_rule: '"Already" comes between have/has and the past participle.',
          },
        ],
      },
    ],
  },

  // ══════════════════════════════════════════════════════
  // Workbook Unit 7 — Trips & Present Perfect
  {
    id: 'wb7',
    title_ar: 'Workbook — Unit 7 (Trips & Present Perfect)',
    color: 'from-cyan-700 to-blue-600',
    icon: '✈️',
    lessons: [
      {
        id: 'wb7_l1',
        title_ar: 'Unit 7 WB: Travel Vocabulary (p196–197)',
        questions: [
          {
            type: 'mc',
            q: 'What is a "platform" at a train station? (WB p196)',
            options: ['the train itself', 'a large bag', 'the raised area where you board the train', 'the road for trains'],
            correct: 2,
            explanation: 'From WB p196: platform = where you wait and board a train.',
            golden_rule: 'A platform is the raised area at a station where passengers board/exit trains.',
          },
          {
            type: 'mc',
            q: '"What time does your plane ___?" (WB p197)',
            options: ['arrive', 'depart', 'land', 'take off'],
            correct: 1,
            explanation: 'From WB p197: "What time does your plane depart?" — depart = leave (for planes/trains).',
            golden_rule: '"Depart" = leave. "Arrive" = get there. "Take off" = when a plane lifts into the air.',
          },
          {
            type: 'classify',
            q: 'Classify these travel words as PLACES or DOCUMENTS/OBJECTS (WB p196):',
            categories: ['Places 📍', 'Documents / Objects 🧳'],
            items: [
              { text: 'airport terminal', correct_cat: 0 },
              { text: 'passport', correct_cat: 1 },
              { text: 'platform', correct_cat: 0 },
              { text: 'suitcase', correct_cat: 1 },
              { text: 'subway station', correct_cat: 0 },
              { text: 'security (check)', correct_cat: 0 },
            ],
            explanation: 'From WB p196: Trips vocabulary.',
            golden_rule: 'Organize new vocabulary by category to remember it more efficiently.',
          },
          {
            type: 'yesno',
            q: '"I haven\'t written to you before now." is a correct Present Perfect sentence. (WB p199)',
            correct: true,
            explanation: 'From WB p199: "I\'m sorry I haven\'t written to you before now." — Present Perfect with negative ✓.',
            golden_rule: 'Present Perfect negative: Subject + haven\'t/hasn\'t + past participle.',
          },
          {
            type: 'matching',
            q: 'Match each travel verb to its meaning (WB p202):',
            pairs: [
              { left: 'check in', right: 'to register at an airport or hotel' },
              { left: 'check out', right: 'to pay the bill and leave a hotel' },
              { left: 'take off', right: 'to begin to fly' },
              { left: 'land', right: 'to arrive on the ground after flying' },
            ],
            explanation: 'From WB p202: travel phrasal verb matching.',
            golden_rule: 'Learn travel phrasal verbs in pairs: check in / check out, take off / land.',
          },
          {
            type: 'word_order',
            q: 'Order the words to make a Present Perfect sentence (WB p199):',
            words: ['parents', 'My', 'plane', 'bought', 'tickets', 'the', 'have'],
            correct_sentence: 'My parents have bought the plane tickets',
            explanation: 'From WB p199: "My parents have bought the plane tickets."',
            golden_rule: 'Present Perfect: Subject + have/has + past participle (irregular: buy → bought).',
          },
        ],
      },
      {
        id: 'wb7_l2',
        title_ar: 'Unit 7 WB: Present Perfect — Already / Yet / Just (p203)',
        questions: [
          {
            type: 'mc',
            q: '"My grandparents have ___ arrived." — they arrived very recently. (WB p203)',
            options: ['already', 'just', 'yet', 'never'],
            correct: 1,
            explanation: 'From WB p203: "My grandparents have just arrived." — very recently completed action.',
            golden_rule: '"JUST" = very recently (moments ago). "ALREADY" = sooner than expected. "YET" = up to now (negatives/questions).',
          },
          {
            type: 'mc',
            q: '"The plane hasn\'t taken off ___." (WB p203)',
            options: ['just', 'already', 'yet', 'never'],
            correct: 2,
            explanation: 'From WB p203: "The plane hasn\'t taken off yet." — "yet" used in negatives.',
            golden_rule: '"YET" goes at the END of negative sentences and questions.',
          },
          {
            type: 'classify',
            q: 'Classify: does the sentence use ALREADY, JUST, or YET? (WB p203)',
            categories: ['ALREADY / JUST (positive)', 'YET (negative/question)'],
            items: [
              { text: 'Rose has already found her passport.', correct_cat: 0 },
              { text: 'She hasn\'t packed the suitcase yet.', correct_cat: 1 },
              { text: 'The Browns have just arrived at the hotel.', correct_cat: 0 },
              { text: 'Many passengers haven\'t checked in yet.', correct_cat: 1 },
            ],
            explanation: 'From WB p203: already/yet/just exercises.',
            golden_rule: 'Already/Just → positive sentences (middle). Yet → negative sentences and questions (end).',
          },
          {
            type: 'yesno',
            q: '"I have already planned the whole trip." means the plan was made BEFORE now. (WB p203)',
            correct: true,
            explanation: 'From WB p203: "I have already planned the whole trip." — completed before expected.',
            golden_rule: '"Already" in Present Perfect means the action is done — often sooner than expected.',
          },
          {
            type: 'matching',
            q: 'Match each Present Perfect sentence to its meaning (WB p198–199):',
            pairs: [
              { left: 'The plane has departed.', right: 'Result: you missed it' },
              { left: 'Oliver hasn\'t packed his suitcase.', right: 'Action not done yet (problem)' },
              { left: 'They have taken a city tour.', right: 'Past experience affecting now' },
              { left: 'I have flown to Europe three times.', right: 'Repeated past experience' },
            ],
            explanation: 'From WB p198–199: Present Perfect uses.',
            golden_rule: 'Present Perfect connects past actions to the present: experience, results, or unfinished time.',
          },
          {
            type: 'word_order',
            q: 'Order the words to make a sentence with "yet" (WB p203):',
            words: ['hasn\'t', 'pilot', 'passengers', 'the', 'to', 'spoken', 'yet', 'The'],
            correct_sentence: "The pilot hasn't spoken to the passengers yet",
            explanation: 'From WB p203: "The pilot hasn\'t spoken to the passengers yet."',
            golden_rule: '"Yet" comes at the END of the sentence in negatives.',
          },
        ],
      },
    ],
  },
  // ══════════════════════════════════════════════════════
  // Workbook Unit 8 — Outfits, Materials & Present Perfect
  // ══════════════════════════════════════════════════════
  {
    id: 'wb8',
    title_ar: 'Workbook — Unit 8 (Outfits & Materials)',
    color: 'from-rose-600 to-pink-500',
    icon: '👗',
    lessons: [
      {
        id: 'wb8_l1',
        title_ar: 'Unit 8 WB: Accessories Vocabulary (p208–209)',
        questions: [
          {
            type: 'mc',
            q: 'Which accessory do you wear around your finger? (WB p208–209)',
            options: ['bracelet', 'ring', 'necklace', 'earring'],
            correct: 1,
            explanation: 'From WB p208: "ring" — worn on the finger.',
            golden_rule: 'Ring = finger. Bracelet = wrist. Necklace = neck. Earring = ear.',
          },
          {
            type: 'mc',
            q: 'What do you use a "comb" for? (WB p209)',
            options: ['to keep money', 'to fix your hair', 'to keep warm', 'to carry things'],
            correct: 1,
            explanation: 'From WB p209: "Your hair\'s a mess. Have you lost your comb?" — a comb fixes hair.',
            golden_rule: 'A comb is used to style and fix hair. A brush is also used for hair.',
          },
          {
            type: 'classify',
            q: 'Classify these items — worn on the BODY or CARRIED? (WB p208–209)',
            categories: ['Worn on the body 👕', 'Carried / held 👜'],
            items: [
              { text: 'earrings', correct_cat: 0 },
              { text: 'purse', correct_cat: 1 },
              { text: 'belt', correct_cat: 0 },
              { text: 'umbrella', correct_cat: 1 },
              { text: 'crown', correct_cat: 0 },
              { text: 'comb', correct_cat: 1 },
            ],
            explanation: 'From WB p208–209: accessories vocabulary exercises.',
            golden_rule: 'Some accessories are worn (belt, earrings). Others are carried (purse, umbrella).',
          },
          {
            type: 'yesno',
            q: '"Do you wear a uniform to school?" — A uniform is a matching set of clothes required at school. (WB p209)',
            correct: true,
            explanation: 'From WB p209: "Do you wear a uniform to school? No. I can wear anything I like."',
            golden_rule: 'A uniform is the official clothing required at school or work.',
          },
          {
            type: 'matching',
            q: 'Match each accessory to its context (WB p209):',
            pairs: [
              { left: 'belt', right: 'worn around the waist to hold up pants' },
              { left: 'crown', right: 'worn on the head by royalty' },
              { left: 'purse', right: 'used to carry money and small items' },
              { left: 'umbrella', right: 'used to protect from rain' },
            ],
            explanation: 'From WB p209: accessories in context.',
            golden_rule: 'Learn accessories with their purpose and where on the body they are worn.',
          },
          {
            type: 'word_order',
            q: 'Order the words to make a Present Perfect question (WB p210):',
            words: ['on', 'you', 'your', 'tried', 'new', 'uniform', 'have'],
            correct_sentence: 'have you tried on your new uniform',
            explanation: 'From WB p210: "Have you tried on your new uniform?"',
            golden_rule: 'Present Perfect questions: Have/Has + subject + past participle?',
          },
        ],
      },
      {
        id: 'wb8_l2',
        title_ar: 'Unit 8 WB: Be Made Of & Present Perfect "How Long" (p210–211)',
        questions: [
          {
            type: 'mc',
            q: '"Dad\'s striped tie ___ wool." (WB p215)',
            options: ['is made of', 'are made of', 'is made from', 'made of'],
            correct: 0,
            explanation: 'From WB p215: "Dad\'s striped tie is made of wool." — singular subject uses "is made of".',
            golden_rule: 'Singular: "is made of". Plural: "are made of". Always + material noun.',
          },
          {
            type: 'mc',
            q: '"How long ___ you ___ that belt?" — asking about duration. (WB p211)',
            options: ['did / have', 'have / had', 'did / had', 'have / have'],
            correct: 1,
            explanation: 'From WB p211: "How long have you had that belt?" — Present Perfect with "How long".',
            golden_rule: '"How long have you + past participle?" asks about duration from the past to now.',
          },
          {
            type: 'classify',
            q: 'Classify these materials as NATURAL or MAN-MADE (WB p214):',
            categories: ['Natural (from nature)', 'Man-made / Synthetic'],
            items: [
              { text: 'wool', correct_cat: 0 },
              { text: 'plastic', correct_cat: 1 },
              { text: 'silk', correct_cat: 0 },
              { text: 'metal', correct_cat: 1 },
              { text: 'leather', correct_cat: 0 },
              { text: 'nylon', correct_cat: 1 },
            ],
            explanation: 'From WB p214: materials vocabulary.',
            golden_rule: 'Natural materials: wool, silk, leather, cotton. Man-made: plastic, metal, nylon.',
          },
          {
            type: 'yesno',
            q: '"This beautiful bracelet isn\'t made of silver." is a correctly structured sentence. (WB p215)',
            correct: true,
            explanation: 'From WB p215: "This beautiful bracelet isn\'t made of silver." — subject + isn\'t made of + material ✓.',
            golden_rule: 'Negative: "isn\'t/aren\'t made of" + material. Always use "of" not "from" with "made".',
          },
          {
            type: 'matching',
            q: 'Match each sentence start to the correct material (WB p218):',
            pairs: [
              { left: 'Noura\'s earrings are made of', right: 'wood' },
              { left: 'Sarah\'s spotted dress is', right: 'blue and white' },
              { left: 'Noura has worn her purple dress', right: 'twice' },
              { left: 'Noura has had the purple dress for', right: 'two months' },
            ],
            explanation: 'From WB p218: conversation between Noura and Sarah.',
            golden_rule: 'Present Perfect + "for" = duration. Present Perfect + "twice/before" = experience.',
          },
          {
            type: 'word_order',
            q: 'Order the words to describe a material (WB p215):',
            words: ['of', 'leather', 'is', 'coin', 'made', 'beautiful', 'This', 'purse'],
            correct_sentence: 'This beautiful coin purse is made of leather',
            explanation: 'From WB p215: "This beautiful coin purse is made of leather."',
            golden_rule: 'Structure: This/These + adjective + noun + is/are + made of + material.',
          },
        ],
      },
    ],
  },
];