// بنك أسئلة TopGoal 2 — الوحدات 2-3-4
// Unit 2: At Home | Unit 3: Job Paths | Unit 4: Glorious Food

export const TOPGOAL2_UNITS_2TO4 = [
  // ══════════════════════════════════════════════════════
  // Workbook Practice — Units 1 & 2 Integrated
  // ══════════════════════════════════════════════════════
  {
    id: 'wb12',
    title_ar: 'Workbook — Units 1 & 2 Practice',
    color: 'from-slate-600 to-slate-500',
    icon: '📝',
    lessons: [
      {
        id: 'wb12_l1',
        title_ar: 'Unit 1 WB: Vocabulary & Simple Past (p124–127)',
        questions: [
          {
            type: 'mc',
            q: 'Choose the correct option: "I ___ the new spaceship movie!" (WB p126)',
            options: ['watch', 'watches', 'watched', 'watching'],
            correct: 2,
            explanation: 'From WB p126: Simple Past of "watch" = watched. Add -ed to regular verbs.',
            golden_rule: 'Regular Simple Past: add -ed. watch → watched, play → played.',
          },
          {
            type: 'mc',
            q: 'Tom: "Did you like it?" Jimmy: "Yes, I ___ it a lot!" (WB p126)',
            options: ['like', 'liked', 'likes', 'liking'],
            correct: 1,
            explanation: 'From WB p126: "Yes, I liked it a lot!" — Simple Past of "like" = liked.',
            golden_rule: 'In Simple Past, all persons use the same form: I/you/he/she liked.',
          },
          {
            type: 'classify',
            q: 'Classify these verbs as ACTION or STATE verbs (WB p131):',
            categories: ['Action Verbs', 'State Verbs'],
            items: [
              { text: 'cook', correct_cat: 0 },
              { text: 'like', correct_cat: 1 },
              { text: 'dance', correct_cat: 0 },
              { text: 'believe', correct_cat: 1 },
              { text: 'walk', correct_cat: 0 },
              { text: 'know', correct_cat: 1 },
            ],
            explanation: 'From WB p131: Action verbs describe activities; state verbs describe feelings/states.',
            golden_rule: 'State verbs (like, know, believe, want) are NOT used in continuous tenses.',
          },
          {
            type: 'yesno',
            q: '"She prefers sunny days." is correct. (NOT "She is preferring sunny days.") (WB p131)',
            correct: true,
            explanation: 'From WB p131: "prefer" is a state verb — use simple form, never continuous.',
            golden_rule: 'State verbs (prefer, want, need, know, like) always use simple tense, not -ing.',
          },
          {
            type: 'matching',
            q: 'Match the adjective to its meaning (WB p124):',
            pairs: [
              { left: 'wonderful', right: 'brilliant and pleasing' },
              { left: 'frightening', right: 'scary' },
              { left: 'tidy', right: 'clean and organized' },
              { left: 'popular', right: 'liked by many people' },
            ],
            explanation: 'From WB p124–125: adjective vocabulary exercises.',
            golden_rule: 'Learn adjectives with their definitions and example sentences for context.',
          },
          {
            type: 'word_order',
            q: 'Order the words to make a Simple Past question (WB p127):',
            words: ['did', 'last', 'Where', 'on', 'go', 'you', 'vacation', 'your'],
            correct_sentence: 'Where did you go on your last vacation',
            explanation: 'From WB p127: "Where did you go on your last vacation?"',
            golden_rule: 'Past questions: Where/What/When + did + subject + base verb?',
          },
        ],
      },
      {
        id: 'wb12_l2',
        title_ar: 'Unit 2 WB: Will / Be Going To (p138–143)',
        questions: [
          {
            type: 'mc',
            q: '"The front door lock doesn\'t open." → "Don\'t worry! I ___ call for help." (WB p138)',
            options: ['am going to', 'will', 'won\'t', 'might'],
            correct: 1,
            explanation: 'From WB p138: spontaneous decision → use WILL. "Don\'t worry! I will call for help."',
            golden_rule: 'WILL = spontaneous decision made at the moment of speaking.',
          },
          {
            type: 'mc',
            q: '"My family and I ___ travel to the lake tomorrow. Do you want to join us?" (WB p143)',
            options: ['will', 'are going to', 'might', 'won\'t'],
            correct: 1,
            explanation: 'From WB p143: "My family and I are going to travel to the lake tomorrow." — pre-planned.',
            golden_rule: 'BE GOING TO = already planned/arranged before the moment of speaking.',
          },
          {
            type: 'classify',
            q: 'Classify each sentence: SPONTANEOUS (will) or PRE-PLANNED (be going to)? (WB p143)',
            categories: ['Spontaneous — WILL', 'Pre-planned — BE GOING TO'],
            items: [
              { text: 'I am going to read a book this evening. (decided earlier)', correct_cat: 1 },
              { text: '"The gate is locked!" "No problem! I\'ll get the key."', correct_cat: 0 },
              { text: 'Henry is going to start college soon.', correct_cat: 1 },
              { text: '"I can\'t find my wallet!" "Don\'t worry. I\'ll buy the tickets."', correct_cat: 0 },
            ],
            explanation: 'From WB p138–143: WILL vs BE GOING TO exercises.',
            golden_rule: 'WILL for on-the-spot decisions. BE GOING TO for plans made in advance.',
          },
          {
            type: 'yesno',
            q: '"I\'ll be late again." means the same as "I am going to be late again." (WB p138)',
            correct: false,
            explanation: 'From WB p138: "Sorry, Mr. Adams. I won\'t be late again." — this is a promise (will), not a plan.',
            golden_rule: 'WILL is also used for promises and offers. "I won\'t be late again" = a promise.',
          },
          {
            type: 'matching',
            q: 'Match each situation to the correct response (WB p138):',
            pairs: [
              { left: '"I must go home. Mom\'s waiting."', right: '"Come on! I\'ll give you a ride."' },
              { left: '"I don\'t feel well. I have a fever."', right: '"I\'ll take you to the hospital."' },
              { left: '"The gate is locked!"', right: '"No problem! I\'ll get the key."' },
              { left: '"Classes start at 8 a.m."', right: '"Sorry. I won\'t be late again."' },
            ],
            explanation: 'From WB p138: matching exercise on spontaneous WILL responses.',
            golden_rule: 'Use WILL to offer help or make promises in response to problems.',
          },
          {
            type: 'word_order',
            q: 'Order the words to make a sentence using "be going to" (WB p143):',
            words: ['going', 'redesign', 'parents', 'are', 'My', 'room', 'to', 'the'],
            correct_sentence: 'My parents are going to redesign the room',
            explanation: 'From WB p147: "My parents say that they are going to redesign the room."',
            golden_rule: 'Structure: Subject + am/are/is + going to + base verb.',
          },
        ],
      },
    ],
  },

  // ══════════════════════════════════════════════════════
  // Unit 2 — At Home (Future Plans)
  // ══════════════════════════════════════════════════════
  {
    id: 'u2',
    title_ar: 'Unit 2 — At Home (Future Plans)',
    color: 'from-indigo-600 to-indigo-400',
    icon: '🏠',
    lessons: [
      {
        id: 'u2_l1',
        title_ar: 'Vocabulary: House & Home (p27–28)',
        questions: [
          {
            type: 'mc',
            q: 'What does "cushion" mean? (p28)',
            options: ['a bookcase shelf', 'a soft pillow used on a sofa', 'the corner of a room', 'a yard outside'],
            correct: 1,
            explanation: 'From p28: "cushion" — a soft pillow placed on a sofa or chair.',
            golden_rule: '"Cushion" = a soft pillow for comfort on a sofa or chair.',
          },
          {
            type: 'mc',
            q: 'Choose the correct word: "No! Let\'s meet at my house ___." (p28)',
            options: ['instead', 'corner', 'empty', 'shelf'],
            correct: 0,
            explanation: 'From p28 dialogue: "No! Let\'s meet at my house instead." Instead = as an alternative.',
            golden_rule: '"Instead" means in place of something else.',
          },
          {
            type: 'matching',
            q: 'Match each house vocabulary word to its meaning (p28):',
            pairs: [
              { left: 'shelf', right: 'a flat board fixed to a wall for storing things' },
              { left: 'corner', right: 'the place where two walls meet' },
              { left: 'empty', right: 'containing nothing; not full' },
              { left: 'take', right: 'to need a certain amount of time' },
            ],
            explanation: 'From p28: house vocabulary.',
            golden_rule: 'Learn home vocabulary with examples in context.',
          },
          {
            type: 'classify',
            q: 'Classify these words — PLACES/THINGS in a house or ACTIONS? (p28)',
            categories: ['Places / Things 🏠', 'Actions 🏃'],
            items: [
              { text: 'shelf', correct_cat: 0 },
              { text: 'take (two hours)', correct_cat: 1 },
              { text: 'cushion', correct_cat: 0 },
              { text: 'instead', correct_cat: 1 },
              { text: 'corner', correct_cat: 0 },
              { text: 'empty (the box)', correct_cat: 1 },
            ],
            explanation: 'From p28: vocabulary exercise.',
            golden_rule: 'Some words can be nouns or verbs — context tells you which.',
          },
          {
            type: 'yesno',
            q: 'In "Young Architects" (p30), Kai won a competition to redesign his bedroom.',
            correct: true,
            explanation: 'From p30: "Last month\'s Young Architects competition winner, Kai, is going to design his dream bedroom!"',
            golden_rule: 'Reading for the main idea helps you understand who, what, and why.',
          },
          {
            type: 'word_order',
            q: 'Order the words to make a sentence about Kai\'s bedroom (p30):',
            words: ['the', 'measurements', 'change', 'going', 'to', "I'm", 'of', 'bedroom', 'my'],
            correct_sentence: "I'm going to change the measurements of my bedroom",
            explanation: 'From p30: "I\'m going to change the measurements of my bedroom."',
            golden_rule: '"Be going to" expresses a plan or decision made before now.',
          },
        ],
      },
      {
        id: 'u2_l2',
        title_ar: 'Grammar: Will vs Be Going To (p29)',
        questions: [
          {
            type: 'mc',
            q: 'Choose the correct form for a spontaneous decision: "Charlotte doesn\'t like fish, so I ___ ask for chicken instead." (p29)',
            options: ['am going to', 'will', 'was going to', 'might'],
            correct: 1,
            explanation: 'From p29: "will ask" — a decision made at that moment = will.',
            golden_rule: 'Use WILL for spontaneous decisions made at the moment of speaking.',
          },
          {
            type: 'mc',
            q: 'Choose the correct form for a pre-arranged plan: "She ___ come to my house after school." (p29)',
            options: ['will', 'is going to', 'won\'t', 'might'],
            correct: 1,
            explanation: 'From p29: "She is going to come to my house after school." — a plan made before = be going to.',
            golden_rule: 'Use BE GOING TO for plans and arrangements made before now.',
          },
          {
            type: 'classify',
            q: 'Classify each sentence: SPONTANEOUS (will) or PREVIOUS ARRANGEMENT (be going to)? (p29)',
            categories: ['Spontaneous — WILL', 'Previous Arrangement — BE GOING TO'],
            items: [
              { text: 'I will tell my dad you don\'t like fish.', correct_cat: 0 },
              { text: 'She is going to come to my house after school.', correct_cat: 1 },
              { text: 'I am not going to sleep at home tonight.', correct_cat: 1 },
              { text: 'We missed the bus! We won\'t be home before 4 p.m.', correct_cat: 0 },
            ],
            explanation: 'From p29 grammar chart.',
            golden_rule: 'WILL = instant decision. BE GOING TO = already decided/arranged.',
          },
          {
            type: 'yesno',
            q: '"Will you bring some extra pajamas?" is a correct WILL question form. (p29)',
            correct: true,
            explanation: 'From p29: "Will you bring some extra pajamas?" — Will + subject + base verb? ✓',
            golden_rule: 'Will questions: Will + subject + base verb.',
          },
          {
            type: 'matching',
            q: 'Match each sentence to the future form it uses (p29–30):',
            pairs: [
              { left: 'We\'re going to put big cushions in the corner.', right: 'be going to (pre-arranged)' },
              { left: 'I think I\'ll have a big screen.', right: 'will (spontaneous)' },
              { left: 'Will they finish before my birthday?', right: 'will (question)' },
              { left: 'I am not going to sleep at home tonight.', right: 'be going to (negative)' },
            ],
            explanation: 'From p29–30: future forms.',
            golden_rule: 'Both WILL and BE GOING TO talk about the future — the difference is HOW the plan was made.',
          },
          {
            type: 'word_order',
            q: 'Order the words to make a "be going to" sentence (p30):',
            words: ['builders', 'the', 'are', 'the', 'changes', 'to', 'start', 'going', 'next', 'week'],
            correct_sentence: 'the builders are going to start the changes next week',
            explanation: 'From p30: "The builders are going to start the changes next week."',
            golden_rule: 'Structure: Subject + am/are/is + going to + base verb.',
          },
        ],
      },
    ],
  },

  // ══════════════════════════════════════════════════════
  // Unit 3 — Job Paths
  // ══════════════════════════════════════════════════════
  {
    id: 'u3',
    title_ar: 'Unit 3 — Job Paths',
    color: 'from-amber-600 to-yellow-500',
    icon: '💼',
    lessons: [
      {
        id: 'u3_l1',
        title_ar: 'Vocabulary: Jobs & Workplaces (p34–35, p40)',
        questions: [
          {
            type: 'mc',
            q: 'Where does a pilot work? (p40)',
            options: ['office', 'factory', 'airport', 'gallery'],
            correct: 2,
            explanation: 'From p40: pilot → airport.',
            golden_rule: 'Match each job to its workplace: pilot → airport, actor → stage, journalist → news studio.',
          },
          {
            type: 'mc',
            q: 'Which job involves writing and reporting the news? (p35)',
            options: ['mechanic', 'journalist', 'waiter', 'pilot'],
            correct: 1,
            explanation: 'From p35: "Hello. I\'m a journalist. I talk about the news."',
            golden_rule: 'A journalist reports news for newspapers, TV, or online.',
          },
          {
            type: 'matching',
            q: 'Match each job to its workplace (p40):',
            pairs: [
              { left: 'actor', right: 'stage or gallery' },
              { left: 'journalist', right: 'news studio' },
              { left: 'businessman', right: 'office' },
              { left: 'flight attendant', right: 'airport' },
            ],
            explanation: 'From p40: "Where do they work?" vocabulary.',
            golden_rule: 'Each job has a typical workplace.',
          },
          {
            type: 'classify',
            q: 'Classify these jobs: INDOORS or OUTDOORS/BOTH? (p34–35)',
            categories: ['Mainly Indoors 🏢', 'Mainly Outdoors / Both 🌤️'],
            items: [
              { text: 'journalist (news studio)', correct_cat: 0 },
              { text: 'pilot', correct_cat: 1 },
              { text: 'businessman (office)', correct_cat: 0 },
              { text: 'fashion designer', correct_cat: 0 },
              { text: 'mechanic', correct_cat: 1 },
              { text: 'flight attendant', correct_cat: 1 },
            ],
            explanation: 'From p34–40: jobs vocabulary.',
            golden_rule: 'Think about where each job happens to remember the vocabulary.',
          },
          {
            type: 'yesno',
            q: 'A "manager" is someone who leads and organizes a team of workers. (p35)',
            correct: true,
            explanation: 'From p35: "I\'m a manager of business people."',
            golden_rule: '"Manager" = someone in charge of organizing people or a business.',
          },
          {
            type: 'word_order',
            q: 'Order the words to describe a job (p35):',
            words: ['journalist', 'a', "I'm", 'the', 'about', 'I', 'talk', 'news'],
            correct_sentence: "I'm a journalist I talk about the news",
            explanation: 'From p35 chant: "Hello. I\'m a journalist. I talk about the news."',
            golden_rule: 'Introduce a job with "I\'m a/an + job" then describe what you do.',
          },
        ],
      },
      {
        id: 'u3_l2',
        title_ar: 'Grammar: May / Might / Be Going To & Question Tags (p36, p41)',
        questions: [
          {
            type: 'mc',
            q: 'Choose the correct word for 50% probability: "You ___ fly all over the world." (p36)',
            options: ['are going to', 'might', 'may', 'won\'t'],
            correct: 2,
            explanation: 'From p36: "You may/may not fly all over the world." May = 50% possible.',
            golden_rule: 'MAY = possible (50%). MIGHT = unlikely (30%). BE GOING TO = certain (100%).',
          },
          {
            type: 'mc',
            q: 'Choose the correct question tag: "This is the theater, ___ it?" (p41)',
            options: ['isn\'t', 'is', 'wasn\'t', 'doesn\'t'],
            correct: 0,
            explanation: 'From p41: "This is the theater, isn\'t it?" — affirmative → negative tag.',
            golden_rule: 'Affirmative statement → negative tag. Negative statement → affirmative tag.',
          },
          {
            type: 'classify',
            q: 'Classify these futures by certainty level (p36):',
            categories: ['Certain — BE GOING TO (100%)', 'Possible — MAY/MIGHT (30–50%)'],
            items: [
              { text: 'I am going to be an artist.', correct_cat: 0 },
              { text: 'She might become an engineer.', correct_cat: 1 },
              { text: 'You may fly all over the world.', correct_cat: 1 },
              { text: 'He isn\'t going to act on TV.', correct_cat: 0 },
            ],
            explanation: 'From p36: future probability chart.',
            golden_rule: 'Be going to = definite. May = likely. Might = unlikely. Isn\'t going to = impossible.',
          },
          {
            type: 'yesno',
            q: '"You haven\'t managed a team before, have you?" is a correct question tag. (p41)',
            correct: true,
            explanation: 'From p41: negative statement → positive tag ✓.',
            golden_rule: 'Negative statement → positive tag. Positive statement → negative tag.',
          },
          {
            type: 'matching',
            q: 'Match each future expression to its meaning (p36):',
            pairs: [
              { left: 'be going to', right: '100% certain future plan' },
              { left: 'may', right: 'likely (50%) future possibility' },
              { left: 'might', right: 'unlikely (30%) future possibility' },
              { left: "isn't going to", right: 'impossible future plan (0%)' },
            ],
            explanation: 'From p36: future probability chart.',
            golden_rule: 'Use different words to express how sure you are about future plans.',
          },
          {
            type: 'word_order',
            q: 'Order the words to make a question tag sentence (p41):',
            words: ['engineer', 'an', 'is', "isn't", 'he?', 'uncle', 'your'],
            correct_sentence: "your uncle is an engineer isn't he?",
            explanation: 'From p41: "Your uncle is an engineer, isn\'t he?"',
            golden_rule: 'Question tags check information or invite agreement.',
          },
        ],
      },
    ],
  },

  // ══════════════════════════════════════════════════════
  // Unit 4 — Glorious Food
  // ══════════════════════════════════════════════════════
  {
    id: 'u4',
    title_ar: 'Unit 4 — Glorious Food',
    color: 'from-orange-600 to-red-500',
    icon: '🍳',
    lessons: [
      {
        id: 'u4_l1',
        title_ar: 'Vocabulary: Food, Ingredients & Cooking (p46–47, p52)',
        questions: [
          {
            type: 'mc',
            q: 'Which word means the raw mixture of flour and water before baking? (p47)',
            options: ['topping', 'ingredient', 'dough', 'countertop'],
            correct: 2,
            explanation: 'From p47: "dough" — the mixture of flour and water that you bake.',
            golden_rule: '"Dough" is the raw mixture before baking.',
          },
          {
            type: 'mc',
            q: 'What is the FIRST step when baking cookies? (p46)',
            options: ['Roll the dough', 'Melt the butter', 'Preheat the oven', 'Taste the mixture'],
            correct: 2,
            explanation: 'From p46: recipe step 1: "Preheat the oven to 300 degrees."',
            golden_rule: 'Always preheat the oven before baking.',
          },
          {
            type: 'ordering',
            q: 'Order the steps for making cookies (p46–52):',
            items: ['Measure the ingredients', 'Preheat the oven', 'Mix the dough', 'Roll and cut the dough', 'Bake the cookies'],
            correct_order: [0, 1, 2, 3, 4],
            explanation: 'From p46–52: cookie-making process in order.',
            golden_rule: 'Recipes follow a strict sequence — follow steps in the correct order.',
          },
          {
            type: 'matching',
            q: 'Match each cooking word to its meaning (p52):',
            pairs: [
              { left: 'measure', right: 'find the exact amount of an ingredient' },
              { left: 'stir', right: 'mix a liquid by moving a spoon in circles' },
              { left: 'pour', right: 'tip liquid from one container to another' },
              { left: 'roll', right: 'flatten dough with a rolling pin' },
            ],
            explanation: 'From p52: cooking action vocabulary.',
            golden_rule: 'Cooking verbs describe specific actions in a recipe.',
          },
          {
            type: 'classify',
            q: 'Classify these as INGREDIENTS or EQUIPMENT (p46–52):',
            categories: ['Ingredients 🥚', 'Equipment / Tools 🥄'],
            items: [
              { text: 'flour', correct_cat: 0 },
              { text: 'rolling pin', correct_cat: 1 },
              { text: 'butter', correct_cat: 0 },
              { text: 'oven', correct_cat: 1 },
              { text: 'honey', correct_cat: 0 },
              { text: 'countertop', correct_cat: 1 },
            ],
            explanation: 'From p46–52: food vocabulary.',
            golden_rule: 'Ingredients go INTO the recipe. Equipment is what you USE to make it.',
          },
          {
            type: 'yesno',
            q: 'In the story "An Experiment in Cooking Class" (p50), Layla\'s carrot cookies smelled bad.',
            correct: false,
            explanation: 'From p50: "A sweet smell starts to fill the classroom" — carrot cookies smelled sweet.',
            golden_rule: 'Read carefully — garlic smelled bad; the final carrot cookies smelled sweet.',
          },
        ],
      },
      {
        id: 'u4_l2',
        title_ar: 'Grammar: Should / Had Better & Zero Conditional (p48, p53)',
        questions: [
          {
            type: 'mc',
            q: 'Choose the stronger warning: "___ not leave them in the oven too long!" (p48)',
            options: ['Should', 'You\'d better', 'You should', 'Do'],
            correct: 1,
            explanation: 'From p48: "You\'d better not leave them in the oven too long!" — "had better" = stronger warning.',
            golden_rule: '"Had better" is stronger than "should". Use it for urgent warnings.',
          },
          {
            type: 'mc',
            q: 'Which is the correct Zero Conditional? "If you ___ a sweet snack, you ___ sugar." (p53)',
            options: ['wanted / add', 'want / add', 'will want / added', 'want / will add'],
            correct: 1,
            explanation: 'From p53: "If you want a sweet snack, you add sugar." — Zero Conditional: if + simple present, simple present.',
            golden_rule: 'Zero Conditional: If + simple present, simple present. Used for always-true facts.',
          },
          {
            type: 'classify',
            q: 'Classify each as ADVICE (should) or WARNING (had better) (p48):',
            categories: ['Advice — Should 💡', 'Warning — Had Better ⚠️'],
            items: [
              { text: 'You should buy all your ingredients before you begin.', correct_cat: 0 },
              { text: 'You\'d better wash your hands.', correct_cat: 1 },
              { text: 'You should bake the cake in the oven.', correct_cat: 0 },
              { text: 'You\'d better not forget the sugar!', correct_cat: 1 },
            ],
            explanation: 'From p48–49: "should" and "had better" chant.',
            golden_rule: '"Should" = good advice. "Had better" = urgent warning with consequences.',
          },
          {
            type: 'yesno',
            q: '"If we don\'t have sugar, we use honey." is a correct Zero Conditional sentence. (p53)',
            correct: true,
            explanation: 'From p53: "If we don\'t have sugar, we use honey." — Zero Conditional ✓.',
            golden_rule: 'Zero Conditional = always true facts. Both verbs use simple present tense.',
          },
          {
            type: 'matching',
            q: 'Match each situation to the correct advice/warning (p48–54):',
            pairs: [
              { left: 'Before you start cooking', right: 'You should get your ingredients ready first.' },
              { left: 'Hygiene in the kitchen', right: 'You had better wash your hands.' },
              { left: 'If you want a sweet snack', right: 'Eat some fruit and yogurt.' },
              { left: 'If you leave cookies in the oven too long', right: 'They will burn.' },
            ],
            explanation: 'From p48, p54: cooking advice and warnings.',
            golden_rule: '"Should" for advice. "Had better" for urgent warnings. "If + present, present" for facts.',
          },
          {
            type: 'word_order',
            q: 'Order the words to make a Zero Conditional sentence (p53):',
            words: ["don't", 'if', 'cookies', 'bake', 'you', 'like', 'a', 'cake'],
            correct_sentence: "if you don't like cookies bake a cake",
            explanation: 'From p53: "If you don\'t like cookies, bake a cake."',
            golden_rule: 'Zero Conditional: If + subject + simple present, subject + simple present.',
          },
        ],
      },
    ],
  },
];