// التربية الإسلامية - الصف الثاني الابتدائي - الفصل الأول
// الفقه والسلوك — الوحدة الثالثة: آداب النظافة
// الدرس الأول: نظافة البدن + الدرس الثاني: نظافة الملابس والمكان

export const FIQH_U3 = [
  { id:'fu3q1', unit:'u3', lesson:'u3l1', page:54, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'النظافة من الإيمان، فالمسلم يحافظ على نظافة:',
    paragraph:'النظافة من الإيمان. أحافظ على نظافة بدني وملابسي ومكاني. (ص54)',
    image:'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=600',
    options:[{text:'بدني وملابسي ومكاني',correct:true},{text:'بدني فقط',correct:false},{text:'ملابسي فقط',correct:false},{text:'مكاني فقط',correct:false}],
    explanation:'النظافة من الإيمان، والمسلم يحافظ على نظافة بدنه وملابسه ومكانه.',
    goldenRule:'النظافة = بدن + ملابس + مكان + إيمان.',
    feedbackQuestion:{question:'على ماذا يحافظ المسلم من النظافة؟',options:[{text:'البدن والملابس والمكان',correct:true},{text:'البدن فقط',correct:false},{text:'الملابس فقط',correct:false},{text:'المكان فقط',correct:false}]} },
  { id:'fu3q2', unit:'u3', lesson:'u3l1', page:54, type:'multipleChoice', bloom:'understand', difficulty:'easy',
    question:'«النظافة من الإيمان» تعني أن النظافة:',
    paragraph:'النظافة من الإيمان. (ص54)',
    image:'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=600',
    options:[{text:'من صفات المؤمنين',correct:true},{text:'ليس لها علاقة بالإيمان',correct:false},{text:'مكروهة',correct:false},{text:'محرمة',correct:false}],
    explanation:'«النظافة من الإيمان» تعني أن النظافة من صفات المؤمنين وأخلاقهم.',
    goldenRule:'النظافة = إيمان + خلق + طهارة.',
    feedbackQuestion:{question:'ماذا تعني «النظافة من الإيمان»؟',options:[{text:'من صفات المؤمنين',correct:true},{text:'لا علاقة بالإيمان',correct:false},{text:'مكروهة',correct:false},{text:'محرمة',correct:false}]} },
  { id:'fu3q3', unit:'u3', lesson:'u3l1', page:54, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'من نظافة البدن:',
    paragraph:'نظافة البدن: قص الأظافر، تسريك الشعر، غسل الوجه واليدين. (ص54)',
    image:'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=600',
    options:[{text:'قص الأظافر وتسريك الشعر وغسل الوجه',correct:true},{text:'الأكل فقط',correct:false},{text:'النوم',correct:false},{text:'اللعب',correct:false}],
    explanation:'من نظافة البدن: قص الأظافر، تسريك الشعر، غسل الوجه واليدين.',
    goldenRule:'نظافة البدن = أظافر + شعر + وجه + يدين.',
    feedbackQuestion:{question:'أي مما يلي من نظافة البدن؟',options:[{text:'قص الأظافر',correct:true},{text:'الأكل',correct:false},{text:'النوم',correct:false},{text:'اللعب',correct:false}]} },
  { id:'fu3q4', unit:'u3', lesson:'u3l1', page:55, type:'trueFalse', bloom:'understand', difficulty:'easy',
    question:'غسل اليدين قبل الأكل وبعده من النظافة.',
    paragraph:'غسل اليدين قبل الأكل وبعده من آداب النظافة. (ص54-55)',
    image:'https://images.unsplash.com/photo-1583947581928-8f49f1cb4be6?w=600',
    correctAnswer:true,
    explanation:'غسل اليدين قبل الأكل وبعده من نظافة البدن وآداب الإسلام.',
    goldenRule:'غسل اليدين = قبل أكل + بعد أكل + نظافة + أدب.',
    feedbackQuestion:{question:'هل غسل اليدين قبل الأكل من النظافة؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'مكروه',correct:false},{text:'لا أعرف',correct:false}]} },
  { id:'fu3q5', unit:'u3', lesson:'u3l1', page:55, type:'multipleChoice', bloom:'apply', difficulty:'medium',
    question:'إذا استيقظت من النوم، فأول ما تفعل للنظافة:',
    paragraph:'من آداب النظافة: غسل الوجه واليدين بعد الاستيقاظ. (ص55)',
    image:'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=600',
    options:[{text:'أغسل وجهي ويدي',correct:true},{text:'أنام ثانية',correct:false},{text:'ألعب',correct:false},{text:'آكل',correct:false}],
    explanation:'عند الاستيقاظ تغسل وجهك ويديك للنظافة وإزالة النوم.',
    goldenRule:'الاستيقاظ = غسل وجه + يدين + نظافة + نشاط.',
    feedbackQuestion:{question:'ماذا تفعل عند الاستيقاظ؟',options:[{text:'أغسل وجهي ويدي',correct:true},{text:'أنام',correct:false},{text:'ألعب',correct:false},{text:'آكل',correct:false}]} },
  { id:'fu3q6', unit:'u3', lesson:'u3l1', page:54, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'قص الأظافر بانتظام:',
    paragraph:'قص الأظافر بانتظام من نظافة البدن. (ص54)',
    image:'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=600',
    options:[{text:'من نظافة البدن',correct:true},{text:'عادة لا أكثر',correct:false},{text:'مكروه',correct:false},{text:'لا قيمة له',correct:false}],
    explanation:'قص الأظافر بانتظام من نظافة البدن ويمنع تجمع الأوساخ تحتها.',
    goldenRule:'قص الأظافر = نظافة + منع أوساخ + سنة.',
    feedbackQuestion:{question:'ما حكم قص الأظافر؟',options:[{text:'من النظافة والسنة',correct:true},{text:'عادة',correct:false},{text:'مكروه',correct:false},{text:'لا قيمة',correct:false}]} },
  { id:'fu3q7', unit:'u3', lesson:'u3l1', page:55, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'تطويل الأظافر قد يؤدي إلى:',
    paragraph:'تطويل الأظافر يجمع الأوساخ والجراثيم. (ص55)',
    image:'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=600',
    options:[{text:'تجمع الأوساخ والجراثيم',correct:true},{text:'النظافة',correct:false},{text:'الجمال',correct:false},{text:'لا شيء',correct:false}],
    explanation:'تطويل الأظافر يجمع الأوساخ والجراثيم تحتها ويضر بالصحة.',
    goldenRule:'تطويل الأظافر = أوساخ + جراثيم + ضرر.',
    feedbackQuestion:{question:'ماذا يفعل تطويل الأظافر؟',options:[{text:'يجمع الأوساخ والجراثيم',correct:true},{text:'نظافة',correct:false},{text:'جمال',correct:false},{text:'لا شيء',correct:false}]} },
  { id:'fu3q8', unit:'u3', lesson:'u3l1', page:54, type:'ordering', bloom:'apply', difficulty:'medium',
    question:'رتّب خطوات نظافة البدن صباحاً:',
    paragraph:'نظافة البدن: غسل الوجه + الأظافر + الشعر. (ص54)',
    items:['أقص أظافري','أغسل وجهي','أسرّك شعري'],
    correctOrder:[1,2,0],
    explanation:'نظافة البدن صباحاً: أغسل وجهي ← أسرّك شعري ← أقص أظافري (حسب الحاجة).',
    goldenRule:'نظافة الصباح = وجه + شعر + أظافر.' },
  { id:'fu3q9', unit:'u3', lesson:'u3l2', page:56, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'نظافة الملابس تعني:',
    paragraph:'نظافة الملابس: غسلها وكويها وترتيبها. (ص56)',
    image:'https://images.unsplash.com/photo-1611652022415-a9419f74343d?w=600',
    options:[{text:'غسلها وكويها وترتيبها',correct:true},{text:'رميها',correct:false},{text:'إهمالها',correct:false},{text:'لا شيء',correct:false}],
    explanation:'نظافة الملابس: غسلها من الأوساخ وكويها لتنسيقها وترتيبها في الخزانة.',
    goldenRule:'نظافة الملابس = غسل + كي + ترتيب.',
    feedbackQuestion:{question:'كيف تحافظ على نظافة ملابسك؟',options:[{text:'أغسلها وأكويها وأرتبها',correct:true},{text:'أرميها',correct:false},{text:'أهملها',correct:false},{text:'لا شيء',correct:false}]} },
  { id:'fu3q10', unit:'u3', lesson:'u3l2', page:56, type:'trueFalse', bloom:'understand', difficulty:'easy',
    question:'ارتداء الملابس النظيفة من آداب الإسلام.',
    paragraph:'ارتداء الملابس النظيفة من آداب النظافة. (ص56)',
    image:'https://images.unsplash.com/photo-1611652022415-a9419f74343d?w=600',
    correctAnswer:true,
    explanation:'ارتداء الملابس النظيفة من آداب الإسلام ويُظهر حسن خلق المسلم.',
    goldenRule:'الملابس النظيفة = أدب + خلق + احترام.',
    feedbackQuestion:{question:'هل الملابس النظيفة من الآداب؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'مكروه',correct:false},{text:'لا أعرف',correct:false}]} },
  { id:'fu3q11', unit:'u3', lesson:'u3l2', page:56, type:'multipleChoice', bloom:'apply', difficulty:'medium',
    question:'إذا اتسخت ملابسك، فالأدب:',
    paragraph:'غسل الملابس المتسخة من النظافة. (ص56)',
    image:'https://images.unsplash.com/photo-1611652022415-a9419f74343d?w=600',
    options:[{text:'أغسلها فوراً',correct:true},{text:'أهملها',correct:false},{text:'أرميها',correct:false},{text:'أنام',correct:false}],
    explanation:'إذا اتسخت ملابسك تغسلها فوراً للحفاظ على نظافتك.',
    goldenRule:'الملابس المتسخة = غسل فوري + لا تأخير + نظافة.',
    feedbackQuestion:{question:'ماذا تفعل إذا اتسخت ملابسك؟',options:[{text:'أغسلها فوراً',correct:true},{text:'أهملها',correct:false},{text:'أرميها',correct:false},{text:'أنام',correct:false}]} },
  { id:'fu3q12', unit:'u3', lesson:'u3l2', page:56, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'نظافة المكان تعني:',
    paragraph:'نظافة المكان: ترتيب الغرفة وكنس الأرض ومسح الطاولات. (ص56)',
    image:'https://images.unsplash.com/photo-1584559350860-6c7b3a4c4e6e?w=600',
    options:[{text:'ترتيب الغرفة وكنس الأرض',correct:true},{text:'اللعب فقط',correct:false},{text:'النوم',correct:false},{text:'لا شيء',correct:false}],
    explanation:'نظافة المكان: ترتيب الغرفة وكنس الأرض ومسح الطاولات ورمي القمامة.',
    goldenRule:'نظافة المكان = ترتيب + كنس + مسح + رمي قمامة.',
    feedbackQuestion:{question:'أي مما يلي من نظافة المكان؟',options:[{text:'ترتيب الغرفة وكنس الأرض',correct:true},{text:'اللعب',correct:false},{text:'النوم',correct:false},{text:'لا شيء',correct:false}]} },
  { id:'fu3q13', unit:'u3', lesson:'u3l2', page:57, type:'multipleChoice', bloom:'apply', difficulty:'medium',
    question:'إذا رأيت قمامة في فناء المدرسة، فالأدب:',
    paragraph:'نظافة المكان: رمي القمامة في سلتها. (ص57)',
    image:'https://images.unsplash.com/photo-1584559350860-6c7b3a4c4e6e?w=600',
    options:[{text:'أرفعها وأرميها في السلة',correct:true},{text:'أتجاهلها',correct:false},{text:'أركلها',correct:false},{text:'أنصرف',correct:false}],
    explanation:'إذا رأيت قمامة في المكان ترفعها وترميها في سلة المهملات للحفاظ على النظافة.',
    goldenRule:'رؤية قمامة = رفع + رمي في سلة + نظافة.',
    feedbackQuestion:{question:'ماذا تفعل إذا رأيت قمامة في المدرسة؟',options:[{text:'أرفعها وأرميها',correct:true},{text:'أتجاهل',correct:false},{text:'أركل',correct:false},{text:'أنصرف',correct:false}]} },
  { id:'fu3q14', unit:'u3', lesson:'u3l2', page:56, type:'classify', bloom:'analyze', difficulty:'medium',
    question:'صنّف: نظافة بدن أم نظافة مكان؟',
    paragraph:'النظافة: بدن + ملابس + مكان. (ص54-56)',
    categories:['نظافة البدن 🧼','نظافة المكان 🏠'],
    items:[
      {text:'غسل الوجه',correct_category:0},{text:'كنس الأرض',correct_category:1},
      {text:'قص الأظافر',correct_category:0},{text:'ترتيب الغرفة',correct_category:1},
      {text:'تسريك الشعر',correct_category:0},{text:'رمي القمامة',correct_category:1},
    ],
    explanation:'نظافة البدن: غسل وجه + أظافر + شعر. نظافة المكان: كنس + ترتيب + رمي قمامة.',
    goldenRule:'النظافة نوعان: بدن + مكان.' },
  { id:'fu3q15', unit:'u3', lesson:'u3l1', page:54, type:'multipleChoice', bloom:'evaluate', difficulty:'hard',
    question:'لماذا أمر الإسلام بالنظافة؟',
    paragraph:'النظافة من الإيمان. (ص54)',
    image:'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=600',
    options:[{text:'لصحة المسلم وطهارته وحسن منظره',correct:true},{text:'عادة',correct:false},{text:'لا سبب',correct:false},{text:'مكروه',correct:false}],
    explanation:'أمر الإسلام بالنظافة لصحة المسلم وطهارته وحسن منظره ومحبة الناس له.',
    goldenRule:'النظافة = صحة + طهارة + حسن منظر + محبة.',
    feedbackQuestion:{question:'لماذا أمر الإسلام بالنظافة؟',options:[{text:'للصحة والطهارة',correct:true},{text:'عادة',correct:false},{text:'لا سبب',correct:false},{text:'مكروه',correct:false}]} },
  { id:'fu3q16', unit:'u3', lesson:'u3l2', page:56, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'ترتيب الغرفة من:',
    paragraph:'نظافة المكان: ترتيب الغرفة. (ص56)',
    image:'https://images.unsplash.com/photo-1584559350860-6c7b3a4c4e6e?w=600',
    options:[{text:'نظافة المكان',correct:true},{text:'نظافة البدن',correct:false},{text:'نظافة الملابس',correct:false},{text:'لا شيء',correct:false}],
    explanation:'ترتيب الغرفة من نظافة المكان ويُظهر حسن خلق المسلم.',
    goldenRule:'ترتيب الغرفة = نظافة مكان + أدب + حسن خلق.',
    feedbackQuestion:{question:'ترتيب الغرفة من أي نظافة؟',options:[{text:'نظافة المكان',correct:true},{text:'نظافة البدن',correct:false},{text:'نظافة الملابس',correct:false},{text:'لا شيء',correct:false}]} },
  { id:'fu3q17', unit:'u3', lesson:'u3l2', page:57, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'ترتيب الأغراض في خزانتك:',
    paragraph:'ترتيب الأغراض من نظافة المكان. (ص56-57)',
    image:'https://images.unsplash.com/photo-1584559350860-6c7b3a4c4e6e?w=600',
    options:[{text:'يجعل الغرفة منظمة ويُسهل إيجاد الأشياء',correct:true},{text:'لا فائدة',correct:false},{text:'يضر',correct:false},{text:'مكروه',correct:false}],
    explanation:'ترتيب الأغراض في الخزانة يجعل الغرفة منظمة ويُسهل إيجاد الأشياء.',
    goldenRule:'ترتيب الأغراض = غرفة منظمة + سهولة إيجاد + أدب.',
    feedbackQuestion:{question:'ما فائدة ترتيب الأغراض؟',options:[{text:'غرفة منظمة وسهولة إيجاد',correct:true},{text:'لا فائدة',correct:false},{text:'يضر',correct:false},{text:'مكروه',correct:false}]} },
  { id:'fu3q18', unit:'u3', lesson:'u3l1', page:55, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'تسريك الشعر وتمشيطه:',
    paragraph:'تسريك الشعر من نظافة البدن. (ص54)',
    image:'https://images.unsplash.com/photo-1503951914875-452162b13f5e?w=600',
    options:[{text:'من نظافة البدن وحسن المظهر',correct:true},{text:'عادة',correct:false},{text:'مكروه',correct:false},{text:'لا قيمة',correct:false}],
    explanation:'تسريك الشعر وتمشيطه من نظافة البدن وحسن المظهر.',
    goldenRule:'تسريك الشعر = نظافة بدن + حسن مظهر + أدب.',
    feedbackQuestion:{question:'ما حكم تسريك الشعر؟',options:[{text:'من النظافة',correct:true},{text:'عادة',correct:false},{text:'مكروه',correct:false},{text:'لا قيمة',correct:false}]} },
  { id:'fu3q19', unit:'u3', lesson:'u3l2', page:57, type:'fillBlank', bloom:'apply', difficulty:'easy',
    question:'أكمل: النظافة من ___.',
    paragraph:'النظافة من الإيمان. (ص54)',
    blanks:['الإيمان'],
    wordBank:['الإيمان','الكفر','العادة','اللعب'],
    explanation:'النظافة من الإيمان — فالمؤمن نظيف بدنه وملابسه ومكانه.',
    goldenRule:'النظافة من الإيمان.' },
  { id:'fu3q20', unit:'u3', lesson:'u3l2', page:56, type:'matching', bloom:'understand', difficulty:'medium',
    question:'صِل كل نوع بنظافته:',
    paragraph:'النظافة ثلاثة أنواع: بدن + ملابس + مكان. (ص54-56)',
    pairs:[
      {left:'غسل الوجه',right:'نظافة البدن'},
      {left:'غسل الملابس',right:'نظافة الملابس'},
      {left:'كنس الأرض',right:'نظافة المكان'},
      {left:'قص الأظافر',right:'نظافة البدن'},
    ],
    explanation:'غسل الوجه والأظافر = بدن، غسل الملابس = ملابس، كنس الأرض = مكان.',
    goldenRule:'النظافة ثلاثة: بدن + ملابس + مكان.' },
  { id:'fu3q21', unit:'u3', lesson:'u3l1', page:55, type:'multipleChoice', bloom:'apply', difficulty:'medium',
    question:'قبل الصلاة تتوضأ، والوضوء:',
    paragraph:'الوضوء من النظافة والطهارة قبل الصلاة. (ص55)',
    image:'https://images.unsplash.com/photo-1591189863430-bb9a05c4f4b0?w=600',
    options:[{text:'نظافة وطهارة للصلاة',correct:true},{text:'عادة',correct:false},{text:'مكروه',correct:false},{text:'لا قيمة',correct:false}],
    explanation:'الوضوء نظافة وطهارة للبدن قبل الصلاة، ويجعل المسلم طاهراً.',
    goldenRule:'الوضوء = نظافة + طهارة + استعداد للصلاة.',
    feedbackQuestion:{question:'ما الوضوو قبل الصلاة؟',options:[{text:'نظافة وطهارة',correct:true},{text:'عادة',correct:false},{text:'مكروه',correct:false},{text:'لا قيمة',correct:false}]} },
  { id:'fu3q22', unit:'u3', lesson:'u3l2', page:57, type:'multipleChoice', bloom:'evaluate', difficulty:'hard',
    question:'ما أثر النظافة على المسلم؟',
    paragraph:'النظافة من الإيمان. (ص54)',
    image:'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=600',
    options:[{text:'صحة جيدة ومظهر حسن ومحبة الناس',correct:true},{text:'مرض',correct:false},{text:'كراهية',correct:false},{text:'لا شيء',correct:false}],
    explanation:'النظافة تمنح المسلم صحة جيدة ومظهراً حسناً ومحبة الناس له.',
    goldenRule:'النظافة = صحة + مظهر حسن + محبة + أجر.',
    feedbackQuestion:{question:'ما أثر النظافة على المسلم؟',options:[{text:'صحة ومظهر ومحبة',correct:true},{text:'مرض',correct:false},{text:'كراهية',correct:false},{text:'لا شيء',correct:false}]} },
  { id:'fu3q23', unit:'u3', lesson:'u3l1', page:55, type:'trueFalse', bloom:'understand', difficulty:'easy',
    question:'ترك الأظافر طويلة يجمع الأوساخ ويضر الصحة.',
    paragraph:'تطويل الأظافر يجمع الأوساخ. (ص55)',
    correctAnswer:true,
    explanation:'ترك الأظافر طويلة يجمع الأوساخ والجراثيم تحتها ويضر بصحة المسلم.',
    goldenRule:'تطويل الأظافر = أوساخ + جراثيم + ضرر صحي.',
    feedbackQuestion:{question:'هل تطويل الأظافر يضر الصحة؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'مفيد',correct:false},{text:'لا أعرف',correct:false}]} },
  { id:'fu3q24', unit:'u3', lesson:'u3l2', page:57, type:'multipleChoice', bloom:'create', difficulty:'hard',
    question:'اكتب جملة فيها: نظافة بدن + نظافة ملابس + نظافة مكان:',
    paragraph:'النظافة: بدن + ملابس + مكان. (ص54-56)',
    options:[
      {text:'أحافظ على نظافة بدني وملابسي ومكاني',correct:true},
      {text:'أنام وأهمل',correct:false},
      {text:'ألعب فقط',correct:false},
      {text:'لا شيء',correct:false},
    ],
    explanation:'الجملة: أحافظ على نظافة بدني وملابسي ومكاني — ثلاثة أنواع للنظافة.',
    goldenRule:'الجملة الكاملة: نظافة بدن + ملابس + مكان.' },
  { id:'fu3q25', unit:'u3', lesson:'u3l1', page:55, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'السواك من السنة وهو:',
    paragraph:'السواك من السنة ويُنظف الأسنان. (ص55)',
    image:'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=600',
    options:[{text:'تنظيف الأسنان وتباهي الوجه',correct:true},{text:'عادة',correct:false},{text:'مكروه',correct:false},{text:'لا قيمة',correct:false}],
    explanation:'السواك من السنة ويُنظف الأسنان ويُطيب الفم ويُبهي الوجه.',
    goldenRule:'السواك = سنة + نظافة أسنان + طيب فم.',
    feedbackQuestion:{question:'ما السواك؟',options:[{text:'تنظيف الأسنان',correct:true},{text:'عادة',correct:false},{text:'مكروه',correct:false},{text:'لا قيمة',correct:false}]} },
  { id:'fu3q26', unit:'u3', lesson:'u3l2', page:57, type:'multipleChoice', bloom:'apply', difficulty:'medium',
    question:'في نهاية اليوم، فالأدب:',
    paragraph:'ترتيب الغرفة قبل النوم من النظافة. (ص56-57)',
    image:'https://images.unsplash.com/photo-1584559350860-6c7b3a4c4e6e?w=600',
    options:[{text:'أرتب غرفتي وأجهز ملابسي للغد',correct:true},{text:'أنام فوراً',correct:false},{text:'ألعب',correct:false},{text:'أنصرف',correct:false}],
    explanation:'في نهاية اليوم أرتب غرفتي وأجهز ملابسي للغد — من آداب النظافة والتنظيم.',
    goldenRule:'نهاية اليوم = ترتيب غرفة + تجهيز ملابس + استعداد غد.',
    feedbackQuestion:{question:'ماذا تفعل في نهاية اليوم؟',options:[{text:'أرتب غرفتي',correct:true},{text:'أنام',correct:false},{text:'ألعب',correct:false},{text:'أنصرف',correct:false}]} },
  { id:'fu3q27', unit:'u3', lesson:'u3l1', page:54, type:'trueFalse', bloom:'evaluate', difficulty:'hard',
    question:'الإسلام دين النظافة في البدن والملابس والمكان.',
    paragraph:'النظافة من الإيمان. (ص54)',
    correctAnswer:true,
    explanation:'الإسلام دين النظافة ويأمر بنظافة البدن والملابس والمكان.',
    goldenRule:'الإسلام = دين نظافة + طهارة + جمال.',
    feedbackQuestion:{question:'هل الإسلام دين النظافة؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'بعض الأحيان',correct:false},{text:'لا أعرف',correct:false}]} },
  { id:'fu3q28', unit:'u3', lesson:'u3l2', page:56, type:'classify', bloom:'analyze', difficulty:'medium',
    question:'صنّف: آداب النظافة أم لا؟',
    paragraph:'آداب النظافة: غسل + ترتيب + قص أظافر + سواك. (ص54-56)',
    categories:['من آداب النظافة 🧹','ليس من الآداب ❌'],
    items:[
      {text:'غسل اليدين',correct_category:0},{text:'ترك القمامة',correct_category:1},
      {text:'ترتيب الغرفة',correct_category:0},{text:'تطويل الأظافر',correct_category:1},
      {text:'السواك',correct_category:0},{text:'إهمال الملابس',correct_category:1},
    ],
    explanation:'من آداب النظافة: غسل + ترتيب + سواك. ليس منها: ترك قمامة + تطويل أظافر + إهمال.',
    goldenRule:'آداب النظافة = غسل + ترتيب + سواك + قص أظافر.' },
  { id:'fu3q29', unit:'u3', lesson:'u3l1', page:55, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'غسل اليدين بعد الخروج من الحمام:',
    paragraph:'غسل اليدين بعد الحمام من النظافة. (ص55)',
    image:'https://images.unsplash.com/photo-1583947581928-8f49f1cb4be6?w=600',
    options:[{text:'من النظافة والطهارة',correct:true},{text:'عادة',correct:false},{text:'مكروه',correct:false},{text:'لا قيمة',correct:false}],
    explanation:'غسل اليدين بعد الخروج من الحمام من النظافة والطهارة لإزالة الجراثيم.',
    goldenRule:'غسل اليدين بعد الحمام = نظافة + طهارة + منع جراثيم.',
    feedbackQuestion:{question:'ما حكم غسل اليدين بعد الحمام؟',options:[{text:'من النظافة',correct:true},{text:'عادة',correct:false},{text:'مكروه',correct:false},{text:'لا قيمة',correct:false}]} },
  { id:'fu3q30', unit:'u3', lesson:'u3l2', page:57, type:'ordering', bloom:'apply', difficulty:'medium',
    question:'رتّب خطوات نظافة الغرفة:',
    paragraph:'نظافة الغرفة: كنس + مسح + ترتيب + رمي قمامة. (ص56-57)',
    items:['أرتب الأغراض','أكنس الأرض','أرمي القمامة'],
    correctOrder:[1,0,2],
    explanation:'نظافة الغرفة: أكنس الأرض ← أرتب الأغراض ← أرمي القمامة.',
    goldenRule:'نظافة الغرفة = كنس ← ترتيب ← رمي قمامة.' },
];

export default FIQH_U3;