// التربية الإسلامية - الصف الثاني الابتدائي - الفصل الأول
// الوحدة الرابعة: الفقه والسلوك — التعامل مع الناس (الآداب)
// الدرس الثاني: الآداب (2) — صفحة 36-41

export const ADAB_L2 = [
  { id:'ad2q1', unit:'u4', lesson:'u4l2', page:36, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'المحافظة على النظام والآداب من:',
    paragraph:'المحافظة على النظام والآداب من أخلاق المسلم. (ص36)',
    image:'https://images.unsplash.com/photo-1503676262392-70a456368e8b?w=600',
    options:[{text:'أخلاق المسلم',correct:true},{text:'صفات الكافر',correct:false},{text:'عادات فقط',correct:false},{text:'لا قيمة لها',correct:false}],
    explanation:'المحافظة على النظام والآداب من أخلاق المسلم التي يحبها الله ورسوله.',
    goldenRule:'النظام + الآداب = أخلاق المسلم.',
    feedbackQuestion:{question:'ممَّ تتألف أخلاق المسلم؟',options:[{text:'النظام والآداب',correct:true},{text:'الفوضى',correct:false},{text:'العبوس',correct:false},{text:'الصراخ',correct:false}]} },
  { id:'ad2q2', unit:'u4', lesson:'u4l2', page:37, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'اختيار الصديق الصالح مهم لأن:',
    paragraph:'نشاط: أحرص على أن يكونوا أصدقائي (اختيار الأصدقاء). (ص37)',
    image:'https://images.unsplash.com/photo-1545241047-6083a3684587?w=600',
    options:[{text:'الصديق يؤثر في صاحبه بخُلقه وأعماله',correct:true},{text:'الصديق لا يؤثر',correct:false},{text:'الصديق للّعب فقط',correct:false},{text:'الصديق لا قيمة له',correct:false}],
    explanation:'الصديق يؤثر في صاحبه، فالصديق الصالح يدلك على الخير والطالح يدلك على الشر.',
    goldenRule:'الصديق يؤثر في صاحبه — اختر صديقك الصالح.',
    feedbackQuestion:{question:'لماذا تختار صديقك الصالح؟',options:[{text:'لأنه يؤثر فيك بخلقه',correct:true},{text:'لا يؤثر',correct:false},{text:'للّعب',correct:false},{text:'لا قيمة له',correct:false}]} },
  { id:'ad2q3', unit:'u4', lesson:'u4l2', page:37, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'احترام العامل وتقدير جهده من:',
    paragraph:'احترام العامل وتقدير جهده. (ص37)',
    image:'https://images.unsplash.com/photo-1581090700227-4c7c0c5e6e1e?w=600',
    options:[{text:'آداب المسلم',correct:true},{text:'عادات فقط',correct:false},{text:'لا قيمة له',correct:false},{text:'ضعف',correct:false}],
    explanation:'احترام العامل وتقدير جهده من آداب المسلم لأن العامل يخدم المجتمع ويستحق التقدير.',
    goldenRule:'احترام العامل = تقدير + أدب + شكر على جهده.',
    feedbackQuestion:{question:'ماذا يستحق العامل منك؟',options:[{text:'الاحترام والتقدير',correct:true},{text:'الإهانة',correct:false},{text:'التجاهل',correct:false},{text:'الصراخ',correct:false}]} },
  { id:'ad2q4', unit:'u4', lesson:'u4l2', page:37, type:'multipleChoice', bloom:'apply', difficulty:'medium',
    question:'عند فرح أحد أقاربك بنجاح، فالموقف الأدب:',
    paragraph:'مشاركة الأهل والأقارب الأفراح وتهنئتهم. (ص37)',
    image:'https://images.unsplash.com/photo-1530103862676-df6c8c8f4f5e?w=600',
    options:[{text:'أُهنّئه وأشاركه فرحته',correct:true},{text:'أتجاهله',correct:false},{text:'أنصرف',correct:false},{text:'أغضب',correct:false}],
    explanation:'مشاركة الأقارب أفراحهم وتهنئتهم من آداب الإسلام وتزيد المحبة بين الأهل.',
    goldenRule:'مشاركة الأفراح = تهنئة + سرور + محبة.',
    feedbackQuestion:{question:'ماذا تفعل عند نجاح قريبك؟',options:[{text:'أُهنّئه وأشاركه',correct:true},{text:'أتجاهل',correct:false},{text:'أنصرف',correct:false},{text:'أغضب',correct:false}]} },
  { id:'ad2q5', unit:'u4', lesson:'u4l2', page:36, type:'trueFalse', bloom:'understand', difficulty:'easy',
    question:'الوقوف في الطابور بانتظام من أخلاق المسلم.',
    paragraph:'المحافظة على النظام والآداب من أخلاق المسلم. (ص36)',
    image:'https://images.unsplash.com/photo-1503676262392-70a456368e8b?w=600',
    correctAnswer:true,
    explanation:'الوقوف في الطابور بانتظام واحترام الدور من أخلاق المسلم.',
    goldenRule:'النظام في الطابور = أدب + احترام + أخلاق.',
    feedbackQuestion:{question:'هل الوقوف في الطابور بانتظام من الأخلاق؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'مكروه',correct:false},{text:'لا قيمة له',correct:false}]} },
  { id:'ad2q6', unit:'u4', lesson:'u4l2', page:37, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'الصديق الصالح هو الذي:',
    paragraph:'أحرص على أن يكونوا أصدقائي (اختيار الأصدقاء). (ص37)',
    image:'https://images.unsplash.com/photo-1545241047-6083a3684587?w=600',
    options:[{text:'يُعينني على الخير والطاعة',correct:true},{text:'يُعينني على الشر',correct:false},{text:'يضيع وقتي',correct:false},{text:'يؤذيني',correct:false}],
    explanation:'الصديق الصالح يُعينك على الخير والطاعة ويحب لك ما يحب لنفسه.',
    goldenRule:'الصديق الصالح = إعانة على الخير + محبة + نصح.',
    feedbackQuestion:{question:'من هو الصديق الصالح؟',options:[{text:'من يُعينني على الخير',correct:true},{text:'من يُعينني على الشر',correct:false},{text:'من يضيع وقتي',correct:false},{text:'من يؤذيني',correct:false}]} },
  { id:'ad2q7', unit:'u4', lesson:'u4l2', page:37, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'العامل الذي ينظف المدرسة يستحق:',
    paragraph:'احترام العامل وتقدير جهده. (ص37)',
    image:'https://images.unsplash.com/photo-1581090700227-4c7c0c5e6e1e?w=600',
    options:[{text:'الاحترام والشكر على جهده',correct:true},{text:'الإهانة',correct:false},{text:'التجاهل',correct:false},{text:'الصراخ عليه',correct:false}],
    explanation:'العامل يستحق الاحترام والشكر على جهده في خدمة المجتمع وتنظيف المدرسة.',
    goldenRule:'العامل = احترام + شكر + تقدير لجهده.',
    feedbackQuestion:{question:'ماذا يستحق عامل النظافة؟',options:[{text:'الاحترام والشكر',correct:true},{text:'الإهانة',correct:false},{text:'التجاهل',correct:false},{text:'الصراخ',correct:false}]} },
  { id:'ad2q8', unit:'u4', lesson:'u4l2', page:37, type:'ordering', bloom:'apply', difficulty:'medium',
    question:'رتّب مواقف مشاركة الأقارب:',
    paragraph:'مشاركة الأهل والأقارب الأفراح والأتراح. (ص37)',
    items:['تهنئة الناجح','زيارة المريض','مواساة الحزين'],
    correctOrder:[0,1,2],
    explanation:'مشاركة الأقارب: تهنئة الناجح ← زيارة المريض ← مواساة الحزين.',
    goldenRule:'مشاركة الأقارب = تهنئة + زيارة مريض + مواساة حزين.' },
  { id:'ad2q9', unit:'u4', lesson:'u4l2', page:36, type:'multipleChoice', bloom:'apply', difficulty:'medium',
    question:'في الصف، إذا أراد المعلم الكلام، فالأدب:',
    paragraph:'المحافظة على النظام والآداب من أخلاق المسلم. (ص36)',
    image:'https://images.unsplash.com/photo-1581579188871-4e6f6a5e0c4e?w=600',
    options:[{text:'أنصت وأستمع بأدب',correct:true},{text:'أتحدث مع زميلي',correct:false},{text:'أصرخ',correct:false},{text:'أنصرف',correct:false}],
    explanation:'عند كلام المعلم أنصت وأستمع بأدب ولا أقاطعه — هذا من النظام والآداب.',
    goldenRule:'النظام في الصف = إنصات + أدب + احترام للمعلم.',
    feedbackQuestion:{question:'ماذا تفعل عندما يتحدث المعلم؟',options:[{text:'أنصت وأستمع',correct:true},{text:'أتحدث',correct:false},{text:'أصرخ',correct:false},{text:'أنصرف',correct:false}]} },
  { id:'ad2q10', unit:'u4', lesson:'u4l2', page:37, type:'classify', bloom:'analyze', difficulty:'medium',
    question:'صنّف: آداب في الأفراح أم آداب في الأتراح؟',
    paragraph:'مشاركة الأهل الأفراح والأتراح. (ص37)',
    categories:['آداب الأفراح 🎉','آداب الأتراح 💧'],
    items:[
      {text:'التهنئة بالنجاح',correct_category:0},{text:'مواساة الحزين',correct_category:1},
      {text:'زيارة المريض',correct_category:1},{text:'تقديم الهدية',correct_category:0},
      {text:'الدعاء للمريض',correct_category:1},{text:'الابتسام و الفرح',correct_category:0},
    ],
    explanation:'الأفراح: تهنئة + هدية + ابتسام. الأتراح: مواساة + زيارة مريض + دعاء.',
    goldenRule:'الأفراح = تهنئة + هدية. الأتراح = مواساة + زيارة + دعاء.' },
  { id:'ad2q11', unit:'u4', lesson:'u4l2', page:36, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'المحافظة على النظام تعني:',
    paragraph:'المحافظة على النظام والآداب من أخلاق المسلم. (ص36)',
    image:'https://images.unsplash.com/photo-1503676262392-70a456368e8b?w=600',
    options:[{text:'الالتزام بالترتيب واحترام الدور',correct:true},{text:'الفوضى',correct:false},{text:'الصراخ',correct:false},{text:'التزاحم',correct:false}],
    explanation:'المحافظة على النظام تعني الالتزام بالترتيب واحترام الدور وعدم التزاحم.',
    goldenRule:'النظام = ترتيب + احترام دور + لا تزاحم.',
    feedbackQuestion:{question:'ما معنى المحافظة على النظام؟',options:[{text:'الالتزام بالترتيب واحترام الدور',correct:true},{text:'الفوضى',correct:false},{text:'الصراخ',correct:false},{text:'التزاحم',correct:false}]} },
  { id:'ad2q12', unit:'u4', lesson:'u4l2', page:37, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'إذا دعاك صديق سيئ الخلق للّعب معه، فالسلوك الأنسب:',
    paragraph:'أحرص على أن يكونوا أصدقائي (اختيار الأصدقاء). (ص37)',
    image:'https://images.unsplash.com/photo-1545241047-6083a3684587?w=600',
    options:[{text:'أرفض بأدب وأبتعد عنه',correct:true},{text:'أقبل فوراً',correct:false},{text:'أصرخ عليه',correct:false},{text:'أشكوه',correct:false}],
    explanation:'الصديق سيئ الخلق يُؤثر عليك، فأرفض بأدب وابتعد عنه واختر صديقاً صالحاً.',
    goldenRule:'الصديق السيئ = ابتعد + ارفض بأدب + اختر الصالح.',
    feedbackQuestion:{question:'ماذا تفعل إذا دعاك صديق سيئ الخلق؟',options:[{text:'أرفض وأبتعد',correct:true},{text:'أقبل',correct:false},{text:'أصرخ',correct:false},{text:'أشكوه',correct:false}]} },
  { id:'ad2q13', unit:'u4', lesson:'u4l2', page:37, type:'trueFalse', bloom:'understand', difficulty:'easy',
    question:'العامل الذي يخدم المجتمع يستحق الإهانة والسخرية.',
    paragraph:'احترام العامل وتقدير جهده. (ص37)',
    correctAnswer:false,
    explanation:'العامل يستحق الاحترام والتقدير لا الإهانة والسخرية، لأنه يخدم المجتمع.',
    goldenRule:'العامل = احترام + تقدير — لا إهانة + لا سخرية.',
    feedbackQuestion:{question:'هل يستحق العامل الإهانة؟',options:[{text:'لا، يستحق الاحترام',correct:true},{text:'نعم',correct:false},{text:'بعض الأحيان',correct:false},{text:'لا أعرف',correct:false}]} },
  { id:'ad2q14', unit:'u4', lesson:'u4l2', page:37, type:'multipleChoice', bloom:'apply', difficulty:'medium',
    question:'إذا مرض قريبك، فالأدب الإسلامي:',
    paragraph:'مشاركة الأهل الأتراح: زيارة المريض. (ص37)',
    image:'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600',
    options:[{text:'أزوره وأدعو له بالشفاء',correct:true},{text:'أتجاهله',correct:false},{text:'أنصرف',correct:false},{text:'أغضب',correct:false}],
    explanation:'زيارة المريض والدعاء له من آداب الإسلام وحقوق الأقارب.',
    goldenRule:'زيارة المريض = زيارة + دعاء بالشفاء + مواساة.',
    feedbackQuestion:{question:'ماذا تفعل عند مرض قريبك؟',options:[{text:'أزوره وأدعو له',correct:true},{text:'أتجاهل',correct:false},{text:'أنصرف',correct:false},{text:'أغضب',correct:false}]} },
  { id:'ad2q15', unit:'u4', lesson:'u4l2', page:36, type:'multipleChoice', bloom:'evaluate', difficulty:'hard',
    question:'لماذا أمر الإسلام بالمحافظة على النظام؟',
    paragraph:'المحافظة على النظام والآداب من أخلاق المسلم. (ص36)',
    image:'https://images.unsplash.com/photo-1503676262392-70a456368e8b?w=600',
    options:[{text:'لأنه يحقق الانضباط ويسهّل الأمور',correct:true},{text:'لأنه عادة',correct:false},{text:'لا سبب',correct:false},{text:'مكروه',correct:false}],
    explanation:'النظام يحقق الانضباط ويسهل الأمور ويمنع الفوضى، لذا أمر به الإسلام.',
    goldenRule:'النظام = انضباط + سهولة + منع فوضى.',
    feedbackQuestion:{question:'لماذا أمر الإسلام بالنظام؟',options:[{text:'لتحقيق الانضباط وسهولة الأمور',correct:true},{text:'عادة',correct:false},{text:'لا سبب',correct:false},{text:'مكروه',correct:false}]} },
  { id:'ad2q16', unit:'u4', lesson:'u4l2', page:37, type:'matching', bloom:'understand', difficulty:'medium',
    question:'صِل كل موقف بأدبه:',
    paragraph:'الآداب: اختيار الأصدقاء، احترام العامل، مشاركة الأقارب. (ص37)',
    pairs:[
      {left:'اختيار صديق',right:'أختار الصالح'},
      {left:'رؤية العامل',right:'أحترمه وأشكر جهده'},
      {left:'نجاح قريب',right:'أُهنّئه'},
      {left:'مرض قريب',right:'أزوره وأدعو له'},
    ],
    explanation:'لكل موقف أدبه: صديق صالح + احترام عامل + تهنئة + زيارة مريض.',
    goldenRule:'لكل موقف أدبه المناسب.' },
  { id:'ad2q17', unit:'u4', lesson:'u4l2', page:37, type:'fillBlank', bloom:'apply', difficulty:'easy',
    question:'أكمل: المحافظة على النظام والآداب من ___ المسلم.',
    paragraph:'المحافظة على النظام والآداب من أخلاق المسلم. (ص36)',
    blanks:['أخلاق'],
    wordBank:['أخلاق','عادات','صفات','معاصي'],
    explanation:'المحافظة على النظام والآداب من أخلاق المسلم.',
    goldenRule:'النظام + الآداب = أخلاق المسلم.' },
  { id:'ad2q18', unit:'u4', lesson:'u4l2', page:37, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'تهنئة الناجح من آداب:',
    paragraph:'مشاركة الأهل الأفراح وتهنئتهم. (ص37)',
    image:'https://images.unsplash.com/photo-1530103862676-df6c8c8f4f5e?w=600',
    options:[{text:'الأفراح',correct:true},{text:'الأتراح',correct:false},{text:'المرض',correct:false},{text:'الحزن',correct:false}],
    explanation:'تهنئة الناجح من آداب الأفراح التي يشرع للمسلم مشاركتها لإخوانه.',
    goldenRule:'التهنئة = أدب أفراح + محبة + سرور.',
    feedbackQuestion:{question:'أي الأحوال تشرع فيها التهنئة؟',options:[{text:'الأفراح',correct:true},{text:'الأتراح',correct:false},{text:'المرض',correct:false},{text:'الحزن',correct:false}]} },
  { id:'ad2q19', unit:'u4', lesson:'u4l2', page:36, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'في الأماكن المزدحمة كالأسواق، فالأدب:',
    paragraph:'المحافظة على النظام والآداب في كل مكان. (ص36)',
    image:'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=600',
    options:[{text:'ألتزم النظام ولا أزاحم الناس',correct:true},{text:'أزاحم بقوة',correct:false},{text:'أصرخ',correct:false},{text:'أجري',correct:false}],
    explanation:'في الأماكن المزدحمة ألتزم النظام ولا أزاحم الناس بل أحترم الدور.',
    goldenRule:'الازدحام = نظام + لا زحام + احترام دور.',
    feedbackQuestion:{question:'ماذا تفعل في مكان مزدحم؟',options:[{text:'ألتزم النظام',correct:true},{text:'أزاحم',correct:false},{text:'أصرخ',correct:false},{text:'أجري',correct:false}]} },
  { id:'ad2q20', unit:'u4', lesson:'u4l2', page:37, type:'trueFalse', bloom:'evaluate', difficulty:'hard',
    question:'الصديق السيئ الخلق لا يؤثر على صاحبه إطلاقاً.',
    paragraph:'أحرص على أن يكونوا أصدقائي (اختيار الأصدقاء). (ص37)',
    correctAnswer:false,
    explanation:'الصديق السيئ يؤثر على صاحبه ويجره إلى الشر، لذا يجب اختيار الصديق الصالح.',
    goldenRule:'الصديق يؤثر — الصالح يدل الخير، السيئ يدل الشر.',
    feedbackQuestion:{question:'هل الصديق السيئ يؤثر عليك؟',options:[{text:'نعم، يدلك على الشر',correct:true},{text:'لا',correct:false},{text:'بعض الأحيان',correct:false},{text:'لا أعرف',correct:false}]} },
  { id:'ad2q21', unit:'u4', lesson:'u4l2', page:36, type:'multipleChoice', bloom:'apply', difficulty:'medium',
    question:'عند دخول المسجد، فالأدب:',
    paragraph:'المحافظة على النظام والآداب من أخلاق المسلم. (ص36)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'أدخل بهدوء وأصلي ركعتين',correct:true},{text:'أدخل بصوت عالٍ',correct:false},{text:'أجري',correct:false},{text:'أتحدث',correct:false}],
    explanation:'دخول المسجد بهدوء وأدب وصلاة ركعتين تحية المسجد من آداب الإسلام.',
    goldenRule:'دخول المسجد = هدوء + أدب + تحية المسجد.',
    feedbackQuestion:{question:'كيف تدخل المسجد؟',options:[{text:'بهدوء وأصلي تحية المسجد',correct:true},{text:'بصوت عالٍ',correct:false},{text:'جرياً',correct:false},{text:'أتحدث',correct:false}]} },
  { id:'ad2q22', unit:'u4', lesson:'u4l2', page:37, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'مشاركة الأقارب أفراحهم تزيد:',
    paragraph:'مشاركة الأهل والأقارب الأفراح. (ص37)',
    image:'https://images.unsplash.com/photo-1530103862676-df6c8c8f4f5e?w=600',
    options:[{text:'المحبة وصلة الرحم',correct:true},{text:'الكراهية',correct:false},{text:'البغضاء',correct:false},{text:'القطيعة',correct:false}],
    explanation:'مشاركة الأقارب أفراحهم تزيد المحبة وتحفظ صلة الرحم.',
    goldenRule:'مشاركة الأقارب = محبة + صلة رحم + سرور.',
    feedbackQuestion:{question:'ماذا تزيد مشاركة الأقارب أفراحهم؟',options:[{text:'المحبة وصلة الرحم',correct:true},{text:'الكراهية',correct:false},{text:'البغضاء',correct:false},{text:'القطيعة',correct:false}]} },
  { id:'ad2q23', unit:'u4', lesson:'u4l2', page:37, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'الهدية عند التهنئة:',
    paragraph:'مشاركة الأهل الأفراح وتهنئتهم وتقديم الهدية. (ص37)',
    image:'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=600',
    options:[{text:'تُفرح صاحبها وتزيد المودة',correct:true},{text:'لا قيمة لها',correct:false},{text:'تضر',correct:false},{text:'مكروهة',correct:false}],
    explanation:'الهدية تُفرح صاحبها وتزيد المودة والمحبة بين الناس.',
    goldenRule:'الهدية = فرح + مودة + محبة.',
    feedbackQuestion:{question:'ما أثر الهدية على صاحبها؟',options:[{text:'تُفرحه وتزيد المودة',correct:true},{text:'لا أثر',correct:false},{text:'تضر',correct:false},{text:'مكروهة',correct:false}]} },
  { id:'ad2q24', unit:'u4', lesson:'u4l2', page:36, type:'classify', bloom:'analyze', difficulty:'medium',
    question:'صنّف: آداب في المدرسة أم في المنزل؟',
    paragraph:'النظام والآداب في كل مكان: المدرسة، المنزل، السوق. (ص36-37)',
    categories:['آداب في المدرسة 🏫','آداب في المنزل 🏠'],
    items:[
      {text:'الإنصات للمعلم',correct_category:0},{text:'الوقوف في الطابور',correct_category:0},
      {text:'احترام الوالدين',correct_category:1},{text:'مشاركة الأهل الأفراح',correct_category:1},
      {text:'احترام العامل',correct_category:0},{text:'ترتيب الغرفة',correct_category:1},
    ],
    explanation:'المدرسة: إنصات + طابور + احترام عامل. المنزل: احترام والدين + مشاركة أفراح + ترتيب غرفة.',
    goldenRule:'الآداب في كل مكان: مدرسة + منزل + سوق.' },
  { id:'ad2q25', unit:'u4', lesson:'u4l2', page:37, type:'multipleChoice', bloom:'create', difficulty:'hard',
    question:'اكتب جملة فيها أدبان من آداب مشاركة الأقارب:',
    paragraph:'مشاركة الأهل الأفراح والأتراح. (ص37)',
    options:[
      {text:'أُهنّئ الناجح وأزور المريض',correct:true},
      {text:'أتجاهل وأغضب',correct:false},
      {text:'أصرخ وأنصرف',correct:false},
      {text:'أنام',correct:false},
    ],
    explanation:'الجملة: أُهنّئ الناجح وأزور المريض — أدبان من آداب مشاركة الأقارب.',
    goldenRule:'مشاركة الأقارب = تهنئة + زيارة مريض.' },
  { id:'ad2q26', unit:'u4', lesson:'u4l2', page:36, type:'multipleChoice', bloom:'evaluate', difficulty:'hard',
    question:'ما الفرق بين المسلم المنظم والمسلم الفوضوي؟',
    paragraph:'المحافظة على النظام والآداب من أخلاق المسلم. (ص36)',
    image:'https://images.unsplash.com/photo-1503676262392-70a456368e8b?w=600',
    options:[{text:'المنظم محبوب ومنتج، والفوضوي مكروه وغير منتج',correct:true},{text:'لا فرق',correct:false},{text:'الفوضوي أفضل',correct:false},{text:'لا أعرف',correct:false}],
    explanation:'المنظم محبوب ومنتج في عمله، والفوضوي مكروه وغير منتج لأنه لا يلتزم بالنظام.',
    goldenRule:'النظام = محبة + إنتاج. الفوضى = كراهية + فشل.',
    feedbackQuestion:{question:'أيهما أفضل: المنظم أم الفوضوي؟',options:[{text:'المنظم',correct:true},{text:'الفوضوي',correct:false},{text:'متساويان',correct:false},{text:'لا أعرف',correct:false}]} },
  { id:'ad2q27', unit:'u4', lesson:'u4l2', page:37, type:'ordering', bloom:'apply', difficulty:'medium',
    question:'رتّب خطوات اختيار الصديق:',
    paragraph:'أحرص على أن يكونوا أصدقائي (اختيار الأصدقاء). (ص37)',
    items:['أراقب أخلاقه','أختار الصالح','أبتعد عن السيئ'],
    correctOrder:[0,1,2],
    explanation:'اختيار الصديق: أراقب أخلاقه ← أختار الصالح ← أبتعد عن السيئ.',
    goldenRule:'اختيار الصديق = مراقبة + اختيار صالح + ابتعاد عن سيئ.' },
  { id:'ad2q28', unit:'u4', lesson:'u4l2', page:37, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'احترام العامل فيه:',
    paragraph:'احترام العامل وتقدير جهده. (ص37)',
    image:'https://images.unsplash.com/photo-1581090700227-4c7c0c5e6e1e?w=600',
    options:[{text:'شكر للعامل على خدمته وتشجيع له',correct:true},{text:'إهانة له',correct:false},{text:'ضعف',correct:false},{text:'لا قيمة له',correct:false}],
    explanation:'احترام العامل شكر له على خدمته وتشجيع له على الاستمرار في خدمة المجتمع.',
    goldenRule:'احترام العامل = شكر + تشجيع + تقدير خدمة.',
    feedbackQuestion:{question:'ماذا في احترام العامل؟',options:[{text:'شكر وتشجيع',correct:true},{text:'إهانة',correct:false},{text:'ضعف',correct:false},{text:'لا قيمة',correct:false}]} },
  { id:'ad2q29', unit:'u4', lesson:'u4l2', page:37, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'التهنئة بالنجاح تكون بـ:',
    paragraph:'مشاركة الأهل الأفراح وتهنئتهم. (ص37)',
    image:'https://images.unsplash.com/photo-1530103862676-df6c8c8f4f5e?w=600',
    options:[{text:'قول: بارك الله فيك ومبروك',correct:true},{text:'الصراخ',correct:false},{text:'العبوس',correct:false},{text:'الصمت',correct:false}],
    explanation:'التهنئة بالنجاح: بارك الله فيك ومبروك النجاح — تُدخل السرور على قلب أخيك.',
    goldenRule:'التهنئة = بارك الله + مبروك + سرور.',
    feedbackQuestion:{question:'بماذا تُهنّئ الناجح؟',options:[{text:'بارك الله فيك ومبروك',correct:true},{text:'الصراخ',correct:false},{text:'العبوس',correct:false},{text:'الصمت',correct:false}]} },
  { id:'ad2q30', unit:'u4', lesson:'u4l2', page:36, type:'trueFalse', bloom:'apply', difficulty:'medium',
    question:'ترك القمامة في الفناء أمامك أدب من آداب المسلم.',
    paragraph:'المحافظة على النظام والآداب من أخلاق المسلم. (ص36)',
    correctAnswer:false,
    explanation:'ترك القمامة في الفناء ليس من الآداب؛ بل رميها في سلة المهملات من النظافة والآداب.',
    goldenRule:'النظافة = رمي القمامة في سلتها + أدب + أخلاق.',
    feedbackQuestion:{question:'أين ترمي القمامة؟',options:[{text:'في سلة المهملات',correct:true},{text:'في الفناء',correct:false},{text:'في الطريق',correct:false},{text:'في الصف',correct:false}]} },
  { id:'ad2q31', unit:'u4', lesson:'u4l2', page:37, type:'multipleChoice', bloom:'evaluate', difficulty:'hard',
    question:'لماذا أمر الإسلام باحترام العامل؟',
    paragraph:'احترام العامل وتقدير جهده. (ص37)',
    image:'https://images.unsplash.com/photo-1581090700227-4c7c0c5e6e1e?w=600',
    options:[{text:'لأنه يخدم المجتمع ويستحق الشكر',correct:true},{text:'لأنه ضعيف',correct:false},{text:'لا سبب',correct:false},{text:'عادة',correct:false}],
    explanation:'احترام العامل لأنه يخدم المجتمع ويتعب من أجلنا، فيستحق الشكر والاحترام.',
    goldenRule:'احترام العامل = شكر على خدمته + تقدير لتعبه.',
    feedbackQuestion:{question:'لماذا نحترم العامل؟',options:[{text:'لأنه يخدم المجتمع',correct:true},{text:'لأنه ضعيف',correct:false},{text:'لا سبب',correct:false},{text:'عادة',correct:false}]} },
  { id:'ad2q32', unit:'u4', lesson:'u4l2', page:37, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'الدعاء للمريض يكون بـ:',
    paragraph:'زيارة المريض والدعاء له. (ص37)',
    image:'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600',
    options:[{text:'اللهم اشفه وعافه',correct:true},{text:'لا أدعو',correct:false},{text:'أغضب',correct:false},{text:'أنصرف',correct:false}],
    explanation:'الدعاء للمريض: اللهم اشفه وعافه — من آداب زيارة المريض.',
    goldenRule:'دعاء المريض = اللهم اشفه + عافه + شفاء عاجل.',
    feedbackQuestion:{question:'بماذا تدعو للمريض؟',options:[{text:'اللهم اشفه وعافه',correct:true},{text:'لا أدعو',correct:false},{text:'أغضب',correct:false},{text:'أنصرف',correct:false}]} },
  { id:'ad2q33', unit:'u4', lesson:'u4l2', page:36, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'الوقوف في الطابور بانتظام يحقق:',
    paragraph:'المحافظة على النظام والآداب من أخلاق المسلم. (ص36)',
    image:'https://images.unsplash.com/photo-1503676262392-70a456368e8b?w=600',
    options:[{text:'العدالة والإنصاف بين الطلاب',correct:true},{text:'الفوضى',correct:false},{text:'الصراخ',correct:false},{text:'الزحام',correct:false}],
    explanation:'الوقوف في الطابور بانتظام يحقق العدالة والإنصاف بين الطلاب.',
    goldenRule:'الطابور = عدالة + إنصاف + نظام.',
    feedbackQuestion:{question:'ماذا يحقق الطابور؟',options:[{text:'العدالة والإنصاف',correct:true},{text:'الفوضى',correct:false},{text:'الصراخ',correct:false},{text:'الزحام',correct:false}]} },
  { id:'ad2q34', unit:'u4', lesson:'u4l2', page:37, type:'multipleChoice', bloom:'apply', difficulty:'medium',
    question:'إذا نجح أخوك في الامتحان، فالموقف الأدب:',
    paragraph:'مشاركة الأهل الأفراح وتهنئتهم. (ص37)',
    image:'https://images.unsplash.com/photo-1530103862676-df6c8c8f4f5e?w=600',
    options:[{text:'أُهنّئه وأفرح معه',correct:true},{text:'أغار منه',correct:false},{text:'أتجاهله',correct:false},{text:'أنصرف',correct:false}],
    explanation:'نجاح أخيك فرحة لك، فتهنّئه وتفرح معه لأنه أخوك.',
    goldenRule:'نجاح أخيك = تهنئة + فرح + محبة.',
    feedbackQuestion:{question:'ماذا تفعل عند نجاح أخيك؟',options:[{text:'أُهنّئه',correct:true},{text:'أغار',correct:false},{text:'أتجاهل',correct:false},{text:'أنصرف',correct:false}]} },
  { id:'ad2q35', unit:'u4', lesson:'u4l2', page:37, type:'matching', bloom:'understand', difficulty:'medium',
    question:'صِل كل شخص بأدبه نحوه:',
    paragraph:'الآداب: مع الأصدقاء، مع العامل، مع الأقارب، مع المعلم. (ص36-37)',
    pairs:[
      {left:'مع الأصدقاء',right:'أختار الصالح'},
      {left:'مع العامل',right:'أحترم وأشكر'},
      {left:'مع الأقارب',right:'أشارك أفراحهم وأتراحهم'},
      {left:'مع المعلم',right:'أنصت وأحترم'},
    ],
    explanation:'لكل شخص أدب: صديق صالح + احترام عامل + مشاركة أقارب + إنصات للمعلم.',
    goldenRule:'لكل شخص أدبه: صديق + عامل + قريب + معلم.' },
  { id:'ad2q36', unit:'u4', lesson:'u4l2', page:36, type:'fillBlank', bloom:'remember', difficulty:'easy',
    question:'أكمل: المحافظة على النظام من أخلاق ___.',
    paragraph:'المحافظة على النظام والآداب من أخلاق المسلم. (ص36)',
    blanks:['المسلم'],
    wordBank:['المسلم','الكافر','الحيوان','الجماد'],
    explanation:'المحافظة على النظام من أخلاق المسلم الذي يحبه الله ورسوله.',
    goldenRule:'النظام = خلق المسلم.' },
  { id:'ad2q37', unit:'u4', lesson:'u4l2', page:37, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'اختيار الصديق الصالح يكون بـ:',
    paragraph:'أحرص على أن يكونوا أصدقائي (اختيار الأصدقاء). (ص37)',
    image:'https://images.unsplash.com/photo-1545241047-6083a3684587?w=600',
    options:[{text:'مراقبة أخلاقه وأعماله',correct:true},{text:'شكله فقط',correct:false},{text:'ماله',correct:false},{text:'صوته',correct:false}],
    explanation:'اختيار الصديق الصالح يكون بمراقبة أخلاقه وأعماله لا شكله وماله.',
    goldenRule:'اختيار الصديق = مراقبة أخلاق + أعمال + لا شكل ومال.',
    feedbackQuestion:{question:'بماذا تختار صديقك؟',options:[{text:'بمراقبة أخلاقه',correct:true},{text:'بشكله',correct:false},{text:'بماله',correct:false},{text:'بصوته',correct:false}]} },
  { id:'ad2q38', unit:'u4', lesson:'u4l2', page:37, type:'trueFalse', bloom:'evaluate', difficulty:'hard',
    question:'مشاركة الأقارب أتراحهم تُخفف عنهم وتُذهب حزنهم.',
    paragraph:'مشاركة الأهل الأتراح ومواساتهم. (ص37)',
    correctAnswer:true,
    explanation:'مشاركة الأقارب أتراحهم تُخفف عنهم وتُذهب حزنهم وتزيد محبتهم لك.',
    goldenRule:'مواساة الأقارب = تخفيف حزن + محبة + صلة رحم.',
    feedbackQuestion:{question:'هل مواساة الحزين تُخفف حزنه؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'تزيده',correct:false},{text:'لا أثر',correct:false}]} },
  { id:'ad2q39', unit:'u4', lesson:'u4l2', page:37, type:'multipleChoice', bloom:'create', difficulty:'hard',
    question:'ركّب جملة فيها: نظام + احترام عامل + مشاركة أقارب:',
    paragraph:'الآداب: نظام + احترام عامل + مشاركة أقارب. (ص36-37)',
    options:[
      {text:'ألتزم النظام وأحترم العامل وأشارك أقاربي أفراحهم',correct:true},
      {text:'أفسد وأصرخ وأتجاهل',correct:false},
      {text:'أنام وألعب فقط',correct:false},
      {text:'لا شيء',correct:false},
    ],
    explanation:'الجملة: ألتزم النظام وأحترم العامل وأشارك أقاربي أفراحهم.',
    goldenRule:'الجملة الكاملة: نظام + احترام عامل + مشاركة أقارب.' },
  { id:'ad2q40', unit:'u4', lesson:'u4l2', page:37, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'مواساة الحزين تكون بـ:',
    paragraph:'مشاركة الأهل الأتراح ومواساتهم. (ص37)',
    image:'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600',
    options:[{text:'الكلمة الطيبة والدعاء والوقوف بجانبه',correct:true},{text:'الصراخ',correct:false},{text:'العبوس',correct:false},{text:'الصمت',correct:false}],
    explanation:'مواساة الحزين: كلمة طيبة + دعاء + وقوف بجانبه + تخفيف حزنه.',
    goldenRule:'مواساة الحزين = كلمة طيبة + دعاء + وقوف بجانبه.',
    feedbackQuestion:{question:'كيف تواسي الحزين؟',options:[{text:'بالكلمة الطيبة والدعاء',correct:true},{text:'الصراخ',correct:false},{text:'العبوس',correct:false},{text:'الصمت',correct:false}]} },
  { id:'ad2q41', unit:'u4', lesson:'u4l2', page:36, type:'multipleChoice', bloom:'apply', difficulty:'medium',
    question:'في طابور الصباح، ينبغي أن تقف:',
    paragraph:'المحافظة على النظام والآداب من أخلاق المسلم. (ص36)',
    image:'https://images.unsplash.com/photo-1503676262392-70a456368e8b?w=600',
    options:[{text:'في دورك بانتظام وهدوء',correct:true},{text:'تتزاحم',correct:false},{text:'تصرخ',correct:false},{text:'تجري',correct:false}],
    explanation:'في طابور الصباح تقف في دورك بانتظام وهدوء ولا تتزاحم أو تصرخ.',
    goldenRule:'الطابور = دورك + نظام + هدوء.',
    feedbackQuestion:{question:'كيف تقف في طابور الصباح؟',options:[{text:'في دوري بانتظام',correct:true},{text:'أتزاحم',correct:false},{text:'أصرخ',correct:false},{text:'أجري',correct:false}]} },
  { id:'ad2q42', unit:'u4', lesson:'u4l2', page:37, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'«أحرص على أن يكونوا أصدقائي» تعني:',
    paragraph:'نشاط: أحرص على أن يكونوا أصدقائي. (ص37)',
    image:'https://images.unsplash.com/photo-1545241047-6083a3684587?w=600',
    options:[{text:'أختار أصدقائي الصالحين',correct:true},{text:'أقبل كل صديق',correct:false},{text:'أصاحب الكل',correct:false},{text:'لا أصاحب أحداً',correct:false}],
    explanation:'«أحرص على أن يكونوا أصدقائي» تعني أختار أصدقائي الصالحين وأبتعد عن السيئين.',
    goldenRule:'أحرص = اختيار صالح + بعد عن سيئ.',
    feedbackQuestion:{question:'ماذا تعني «أحرص على أن يكونوا أصدقائي»؟',options:[{text:'أختار الصالحين',correct:true},{text:'أقبل كل صديق',correct:false},{text:'أصاحب الكل',correct:false},{text:'لا أصاحب أحداً',correct:false}]} },
  { id:'ad2q43', unit:'u4', lesson:'u4l2', page:36, type:'classify', bloom:'analyze', difficulty:'medium',
    question:'صنّف: صديق صالح أم صديق سيئ؟',
    paragraph:'أحرص على أن يكونوا أصدقائي (اختيار الأصدقاء). (ص37)',
    categories:['صديق صالح ✅','صديق سيئ ❌'],
    items:[
      {text:'يُعينك على الصلاة',correct_category:0},{text:'يُعينك على الكذب',correct_category:1},
      {text:'يحب لك الخير',correct_category:0},{text:'يؤذيك',correct_category:1},
      {text:'ينصحك بالخير',correct_category:0},{text:'يسخر منك',correct_category:1},
    ],
    explanation:'الصالح: يُعين على الصلاة + يحب الخير + ينصح. السيئ: يُعين على الكذب + يؤذي + يسخر.',
    goldenRule:'الصديق الصالح = خير + نصح + محبة. السيئ = شر + أذى + سخرية.' },
  { id:'ad2q44', unit:'u4', lesson:'u4l2', page:37, type:'multipleChoice', bloom:'evaluate', difficulty:'hard',
    question:'ما النتيجة على المجتمع إذا التزم الجميع بالآداب؟',
    paragraph:'المحافظة على النظام والآداب من أخلاق المسلم. (ص36-37)',
    image:'https://images.unsplash.com/photo-1503676262392-70a456368e8b?w=600',
    options:[{text:'مجتمع آمن محبوب مترابط',correct:true},{text:'مجتمع فوضوي',correct:false},{text:'مجتمع متفرق',correct:false},{text:'مجتمع كاره',correct:false}],
    explanation:'التزام الجميع بالآداب يصنع مجتمعاً آمناً محبوباً مترابطاً.',
    goldenRule:'الآداب = مجتمع آمن + محبوب + مترابط.',
    feedbackQuestion:{question:'ماذا يصنع التزام الجميع بالآداب؟',options:[{text:'مجتمع آمن مترابط',correct:true},{text:'فوضى',correct:false},{text:'تفرقة',correct:false},{text:'كراهية',correct:false}]} },
  { id:'ad2q45', unit:'u4', lesson:'u4l2', page:37, type:'ordering', bloom:'apply', difficulty:'medium',
    question:'رتّب خطوات زيارة المريض:',
    paragraph:'زيارة المريض والدعاء له. (ص37)',
    items:['أدعو له بالشفاء','أزوره','أجلس معه قليلاً'],
    correctOrder:[1,2,0],
    explanation:'زيارة المريض: أزوره ← أجلس معه قليلاً ← أدعو له بالشفاء.',
    goldenRule:'زيارة المريض = زيارة + جلوس قليل + دعاء.' },
  { id:'ad2q46', unit:'u4', lesson:'u4l2', page:36, type:'trueFalse', bloom:'understand', difficulty:'easy',
    question:'النظام في المنزل كترتيب الغرفة من أخلاق المسلم.',
    paragraph:'المحافظة على النظام والآداب من أخلاق المسلم. (ص36)',
    correctAnswer:true,
    explanation:'ترتيب الغرفة ونظافة المنزل من النظام الذي أمر به الإسلام.',
    goldenRule:'النظام في المنزل = ترتيب غرفة + نظافة + أدب.',
    feedbackQuestion:{question:'هل ترتيب الغرفة من النظام؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'مكروه',correct:false},{text:'لا قيمة له',correct:false}]} },
  { id:'ad2q47', unit:'u4', lesson:'u4l2', page:37, type:'multipleChoice', bloom:'apply', difficulty:'medium',
    question:'إذا قابلت أبا صديقك في الطريق، فالأدب:',
    paragraph:'احترام الكبير وأدب اللقاء. (ص34-37)',
    image:'https://images.unsplash.com/photo-1581579188871-4e6f6a5e0c4e?w=600',
    options:[{text:'أسلِّم عليه وأحترمه',correct:true},{text:'أتجاهله',correct:false},{text:'أنصرف',correct:false},{text:'أصرخ',correct:false}],
    explanation:'أبوك صديقك كبير فأسلِّم عليه وأحترمه لأنه أكبر مني سناً.',
    goldenRule:'احترام كبير: سلام + احترام + لا تقدّم.',
    feedbackQuestion:{question:'ماذا تفعل مع والد صديقك؟',options:[{text:'أسلِّم وأحترم',correct:true},{text:'أتجاهل',correct:false},{text:'أنصرف',correct:false},{text:'أصرخ',correct:false}]} },
  { id:'ad2q48', unit:'u4', lesson:'u4l2', page:37, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'مواساة الحزين تكون:',
    paragraph:'مشاركة الأهل الأتراح ومواساتهم. (ص37)',
    image:'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600',
    options:[{text:'بالوقوف بجانبه والكلمة الطيبة',correct:true},{text:'بالصراخ',correct:false},{text:'بالتجاهل',correct:false},{text:'بالانصراف',correct:false}],
    explanation:'مواساة الحزين بالوقوف بجانبه والكلمة الطيبة والدعاء له.',
    goldenRule:'مواساة الحزين = وقوف + كلمة طيبة + دعاء.',
    feedbackQuestion:{question:'كيف تواسي الحزين؟',options:[{text:'بالوقوف والكلمة الطيبة',correct:true},{text:'الصراخ',correct:false},{text:'التجاهل',correct:false},{text:'الانصراف',correct:false}]} },
  { id:'ad2q49', unit:'u4', lesson:'u4l2', page:36, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'الالتزام بالنظام في كل مكان يدل على:',
    paragraph:'المحافظة على النظام والآداب من أخلاق المسلم. (ص36)',
    image:'https://images.unsplash.com/photo-1503676262392-70a456368e8b?w=600',
    options:[{text:'حسن خلق المسلم وطاعته لله',correct:true},{text:'ضعف',correct:false},{text:'خوف',correct:false},{text:'جبن',correct:false}],
    explanation:'الالتزام بالنظام في كل مكان يدل على حسن خلق المسلم وطاعته لله.',
    goldenRule:'النظام = حسن خلق + طاعة + أدب.',
    feedbackQuestion:{question:'على ماذا يدل الالتزام بالنظام؟',options:[{text:'حسن الخلق والطاعة',correct:true},{text:'ضعف',correct:false},{text:'خوف',correct:false},{text:'جبن',correct:false}]} },
  { id:'ad2q50', unit:'u4', lesson:'u4l2', page:37, type:'multipleChoice', bloom:'create', difficulty:'hard',
    question:'اكتب جملة فيها: احترام عامل + تهنئة ناجح:',
    paragraph:'الآداب: احترام العامل + تهنئة الناجح. (ص37)',
    options:[
      {text:'أحترم العامل وأُهنّئ الناجح',correct:true},
      {text:'أصرخ وأغضب',correct:false},
      {text:'أتجاهل وأنام',correct:false},
      {text:'أنصرف',correct:false},
    ],
    explanation:'الجملة: أحترم العامل وأُهنّئ الناجح — أدبان من آداب الإسلام.',
    goldenRule:'الجملة الكاملة: احترام عامل + تهنئة ناجح.' },
];

export default ADAB_L2;