// التربية الإسلامية - الصف الثاني الابتدائي - الفصل الأول
// الفقه والسلوك — الوحدة الرابعة: آداب الأكل والشرب
// الدرس: آداب الأكل والشرب (1) و (2)

export const FIQH_U4 = [
  // ملاحظة: unit='u4a', lesson='u4l1a' — مطابق للمدخل
  { id:'fu4q1', unit:'u4a', lesson:'u4l1a', page:58, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'قبل الأكل تقول:',
    paragraph:'قبل الأكل أسمي الله: بسم الله. (ص58)',
    image:'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600',
    options:[{text:'بسم الله',correct:true},{text:'لا شيء',correct:false},{text:'الحمد لله',correct:false},{text:'سبحان الله',correct:false}],
    explanation:'قبل الأكل تقول «بسم الله» تبركاً واستعانة بالله.',
    goldenRule:'قبل الأكل = بسم الله + تبرك + استعانة.',
    feedbackQuestion:{question:'بماذا تبدأ قبل الأكل؟',options:[{text:'بسم الله',correct:true},{text:'لا شيء',correct:false},{text:'الحمد لله',correct:false},{text:'سبحان الله',correct:false}]} },
  { id:'fu4q2', unit:'u4a', lesson:'u4l1a', page:58, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'بعد الانتهاء من الأكل تقول:',
    paragraph:'بعد الأكل أحمد الله: الحمد لله. (ص58)',
    image:'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600',
    options:[{text:'الحمد لله',correct:true},{text:'بسم الله',correct:false},{text:'سبحان الله',correct:false},{text:'لا شيء',correct:false}],
    explanation:'بعد الانتهاء من الأكل تقول «الحمد لله» شكراً لله على نعمة الطعام.',
    goldenRule:'بعد الأكل = الحمد لله + شكر + رضا.',
    feedbackQuestion:{question:'بماذا تختم بعد الأكل؟',options:[{text:'الحمد لله',correct:true},{text:'بسم الله',correct:false},{text:'سبحان الله',correct:false},{text:'لا شيء',correct:false}]} },
  { id:'fu4q3', unit:'u4a', lesson:'u4l1a', page:58, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'غسل اليدين قبل الأكل:',
    paragraph:'أغسل يدي قبل الأكل وبعده. (ص58)',
    image:'https://images.unsplash.com/photo-1583947581928-8f49f1cb4be6?w=600',
    options:[{text:'من آداب الأكل والنظافة',correct:true},{text:'عادة',correct:false},{text:'مكروه',correct:false},{text:'لا قيمة',correct:false}],
    explanation:'غسل اليدين قبل الأكل من آداب الأكل والنظافة وإزالة الجراثيم.',
    goldenRule:'غسل اليدين قبل الأكل = نظافة + أدب + منع جراثيم.',
    feedbackQuestion:{question:'ما حكم غسل اليدين قبل الأكل؟',options:[{text:'من الآداب',correct:true},{text:'عادة',correct:false},{text:'مكروه',correct:false},{text:'لا قيمة',correct:false}]} },
  { id:'fu4q4', unit:'u4a', lesson:'u4l1a', page:59, type:'trueFalse', bloom:'understand', difficulty:'easy',
    question:'الأكل باليد اليمنى من آداب الإسلام.',
    paragraph:'آكل ويشرب بيدي اليمنى. (ص59)',
    image:'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600',
    correctAnswer:true,
    explanation:'الأكل والشرب باليد اليمنى من آداب الإسلام وسنة رسول الله ﷺ.',
    goldenRule:'الأكل = باليمنى + سنة + أدب + بركة.',
    feedbackQuestion:{question:'هل الأكل باليمنى من الآداب؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'مكروه',correct:false},{text:'لا أعرف',correct:false}]} },
  { id:'fu4q5', unit:'u4a', lesson:'u4l1a', page:59, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'بأي يد يأكل المسلم؟',
    paragraph:'آكل ويشرب بيدي اليمنى. (ص59)',
    image:'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600',
    options:[{text:'اليمنى',correct:true},{text:'اليسرى',correct:false},{text:'كلتاهما',correct:false},{text:'لا فرق',correct:false}],
    explanation:'يأكل ويشرب المسلم بيده اليمنى تبعاً لسنة رسول الله ﷺ.',
    goldenRule:'الأكل والشرب = باليمنى دائماً.',
    feedbackQuestion:{question:'بأي يد تأكل؟',options:[{text:'اليمنى',correct:true},{text:'اليسرى',correct:false},{text:'كلتاهما',correct:false},{text:'لا فرق',correct:false}]} },
  { id:'fu4q6', unit:'u4a', lesson:'u4l1a', page:58, type:'multipleChoice', bloom:'apply', difficulty:'medium',
    question:'على المائدة، الأدب أن:',
    paragraph:'آداب الأكل: التسمية + الأكل باليمنى + عدم النفخ. (ص58-59)',
    image:'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600',
    options:[{text:'أسمي الله وآكل بيدي اليمنى',correct:true},{text:'أنفخ في الطعام',correct:false},{text:'آكل باليسرى',correct:false},{text:'لا أسمي',correct:false}],
    explanation:'على المائدة أسمي الله وآكل بيدي اليمنى ولا أنفخ في الطعام.',
    goldenRule:'المائدة = تسمية + يمنى + لا نفخ + أدب.',
    feedbackQuestion:{question:'ماذا تفعل على المائدة؟',options:[{text:'أسمي وآكل باليمنى',correct:true},{text:'أنفخ',correct:false},{text:'آكل باليسرى',correct:false},{text:'لا أسمي',correct:false}]} },
  { id:'fu4q7', unit:'u4a', lesson:'u4l1a', page:59, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'النفخ في الطعام الساخن:',
    paragraph:'لا أنفخ في الطعام ولا شرابه. (ص59)',
    image:'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600',
    options:[{text:'منهي عنه في الإسلام',correct:true},{text:'مستحب',correct:false},{text:'واجب',correct:false},{text:'لا قيمة',correct:false}],
    explanation:'النفخ في الطعام منهي عنه في الإسلام، بل يُترك حتى يبرد.',
    goldenRule:'لا نفخ في الطعام = انتظار حتى يبرد + أدب.',
    feedbackQuestion:{question:'ما حكم النفخ في الطعام؟',options:[{text:'منهي عنه',correct:true},{text:'مستحب',correct:false},{text:'واجب',correct:false},{text:'لا قيمة',correct:false}]} },
  { id:'fu4q8', unit:'u4a', lesson:'u4l1a', page:60, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'آداب الشرب تشبه آداب:',
    paragraph:'آداب الشرب كآداب الأكل: تسمية + يمنى + جلوس. (ص60)',
    image:'https://images.unsplash.com/photo-1548837551-7c6d2e4f4f3e?w=600',
    options:[{text:'الأكل',correct:true},{text:'النوم',correct:false},{text:'اللعب',correct:false},{text:'لا شيء',correct:false}],
    explanation:'آداب الشرب تشبه آداب الأكل: التسمية + اليمنى + الجلوس.',
    goldenRule:'آداب الشرب = آداب الأكل = تسمية + يمنى + جلوس.',
    feedbackQuestion:{question:'على ماذا تشبه آداب الشرب؟',options:[{text:'آداب الأكل',correct:true},{text:'النوم',correct:false},{text:'اللعب',correct:false},{text:'لا شيء',correct:false}]} },
  { id:'fu4q9', unit:'u4a', lesson:'u4l1a', page:60, type:'trueFalse', bloom:'understand', difficulty:'easy',
    question:'الشرب جالساً أفضل من الشرب واقفاً.',
    paragraph:'أشرب جالسًا وأسمي الله. (ص60)',
    image:'https://images.unsplash.com/photo-1548837551-7c6d2e4f4f3e?w=600',
    correctAnswer:true,
    explanation:'الشرب جالساً أفضل وأدب وأسلم من الشرب واقفاً.',
    goldenRule:'الشرب = جلوس + يمنى + تسمية + أدب.',
    feedbackQuestion:{question:'كيف تشرب؟',options:[{text:'جالساً',correct:true},{text:'واقفاً',correct:false},{text:'راكضاً',correct:false},{text:'لا فرق',correct:false}]} },
  { id:'fu4q10', unit:'u4a', lesson:'u4l1a', page:59, type:'multipleChoice', bloom:'apply', difficulty:'medium',
    question:'إذا سقطت لقمة من فمك، فالأدب:',
    paragraph:'آكل ما سقط فأغسله وآكله ولا أهدر الطعام. (ص59)',
    image:'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600',
    options:[{text:'أغسلها وآكلها ولا أهدر الطعام',correct:true},{text:'أرميها',correct:false},{text:'أتركها',correct:false},{text:'أطأها',correct:false}],
    explanation:'إذا سقطت لقمة أغسلها وآكلها ولا أهدر الطعام لأن الطعام نعمة.',
    goldenRule:'سقوط لقمة = غسل + أكل + لا هدر + احترام نعمة.',
    feedbackQuestion:{question:'ماذا تفعل إذا سقطت لقمة؟',options:[{text:'أغسلها وآكلها',correct:true},{text:'أرميها',correct:false},{text:'أتركها',correct:false},{text:'أطأها',correct:false}]} },
  { id:'fu4q11', unit:'u4a', lesson:'u4l1a', page:58, type:'ordering', bloom:'apply', difficulty:'medium',
    question:'رتّب آداب الأكل:',
    paragraph:'آداب الأكل: تسمية + يمنى + حمد. (ص58)',
    items:['الحمد لله','بسم الله','الأكل باليمنى'],
    correctOrder:[1,2,0],
    explanation:'آداب الأكل: بسم الله ← الأكل باليمنى ← الحمد لله.',
    goldenRule:'آداب الأكل = تسمية ← يمنى ← حمد.' },
  { id:'fu4q12', unit:'u4a', lesson:'u4l1a', page:59, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'عدم إهدار الطعام:',
    paragraph:'لا أهدر الطعام بل آكل ما أحتاج. (ص59)',
    image:'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600',
    options:[{text:'من احترام نعمة الله',correct:true},{text:'عادة',correct:false},{text:'مكروه',correct:false},{text:'لا قيمة',correct:false}],
    explanation:'عدم إهدار الطعام من احترام نعمة الله وشكره عليها.',
    goldenRule:'لا إهدار = احترام نعمة + شكر + أدب.',
    feedbackQuestion:{question:'لماذا لا نهدر الطعام؟',options:[{text:'احترام نعمة الله',correct:true},{text:'عادة',correct:false},{text:'مكروه',correct:false},{text:'لا قيمة',correct:false}]} },
  { id:'fu4q13', unit:'u4a', lesson:'u4l1a', page:59, type:'classify', bloom:'analyze', difficulty:'medium',
    question:'صنّف: من آداب الأكل أم لا؟',
    paragraph:'آداب الأكل: بسم الله + يمنى + لا نفخ + حمد. (ص58-59)',
    categories:['من آداب الأكل 🍽️','ليس من الآداب ❌'],
    items:[
      {text:'بسم الله',correct_category:0},{text:'النفخ في الطعام',correct_category:1},
      {text:'الأكل باليمنى',correct_category:0},{text:'الأكل باليسرى',correct_category:1},
      {text:'الحمد لله',correct_category:0},{text:'إهدار الطعام',correct_category:1},
    ],
    explanation:'من آداب الأكل: تسمية + يمنى + حمد. ليس منها: نفخ + يسري + إهدار.',
    goldenRule:'آداب الأكل = تسمية + يمنى + حمد + لا نفخ + لا إهدار.' },
  { id:'fu4q14', unit:'u4a', lesson:'u4l1a', page:60, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'قبل الشرب تقول:',
    paragraph:'أسمي الله قبل الشرب وأحمده بعده. (ص60)',
    image:'https://images.unsplash.com/photo-1548837551-7c6d2e4f4f3e?w=600',
    options:[{text:'بسم الله',correct:true},{text:'الحمد لله',correct:false},{text:'سبحان الله',correct:false},{text:'لا شيء',correct:false}],
    explanation:'قبل الشرب تقول «بسم الله» كما في الأكل.',
    goldenRule:'قبل الشرب = بسم الله.',
    feedbackQuestion:{question:'بماذا تبدأ قبل الشرب؟',options:[{text:'بسم الله',correct:true},{text:'الحمد لله',correct:false},{text:'سبحان الله',correct:false},{text:'لا شيء',correct:false}]} },
  { id:'fu4q15', unit:'u4a', lesson:'u4l1a', page:60, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'الشرب على ثلاث دفعات:',
    paragraph:'أشرب على ثلاث دفعات. (ص60)',
    image:'https://images.unsplash.com/photo-1548837551-7c6d2e4f4f3e?w=600',
    options:[{text:'من السنة وأسلم للمعدة',correct:true},{text:'عادة',correct:false},{text:'مكروه',correct:false},{text:'لا قيمة',correct:false}],
    explanation:'الشرب على ثلاث دفعات من السنة وأسلم للمعدة وأطيب للنفس.',
    goldenRule:'الشرب = ثلاث دفعات + سنة + سلامة + راحة.',
    feedbackQuestion:{question:'كم دفعة تشرب؟',options:[{text:'ثلاث دفعات',correct:true},{text:'دفعة واحدة',correct:false},{text:'دفعتين',correct:false},{text:'لا فرق',correct:false}]} },
  { id:'fu4q16', unit:'u4a', lesson:'u4l1a', page:59, type:'fillBlank', bloom:'apply', difficulty:'easy',
    question:'أكمل: قبل الأكل أقول ___.',
    paragraph:'قبل الأكل أسمي الله. (ص58)',
    blanks:['بسم الله'],
    wordBank:['بسم الله','الحمد لله','سبحان الله','لا إله إلا الله'],
    explanation:'قبل الأكل أقول «بسم الله».',
    goldenRule:'قبل الأكل = بسم الله.' },
  { id:'fu4q17', unit:'u4a', lesson:'u4l1a', page:59, type:'fillBlank', bloom:'apply', difficulty:'easy',
    question:'أكمل: بعد الأكل أقول ___.',
    paragraph:'بعد الأكل أحمد الله. (ص58)',
    blanks:['الحمد لله'],
    wordBank:['الحمد لله','بسم الله','سبحان الله','الله أكبر'],
    explanation:'بعد الأكل أقول «الحمد لله» شكراً لله.',
    goldenRule:'بعد الأكل = الحمد لله.' },
  { id:'fu4q18', unit:'u4a', lesson:'u4l1a', page:58, type:'multipleChoice', bloom:'evaluate', difficulty:'hard',
    question:'لماذا نسمي الله قبل الأكل؟',
    paragraph:'قبل الأكل أسمي الله. (ص58)',
    image:'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600',
    options:[{text:'للبركة وشكر الله على نعمته',correct:true},{text:'عادة',correct:false},{text:'لا سبب',correct:false},{text:'مكروه',correct:false}],
    explanation:'نسمي الله قبل الأكل للبركة وشكر الله على نعمة الطعام.',
    goldenRule:'التسمية = بركة + شكر + نعمة.',
    feedbackQuestion:{question:'لماذا نسمي الله قبل الأكل؟',options:[{text:'للبركة والشكر',correct:true},{text:'عادة',correct:false},{text:'لا سبب',correct:false},{text:'مكروه',correct:false}]} },
  { id:'fu4q19', unit:'u4a', lesson:'u4l1a', page:59, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'الأكل باليسرى:',
    paragraph:'آكل بيدي اليمنى. (ص59)',
    image:'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600',
    options:[{text:'خلاف السنة',correct:true},{text:'سنة',correct:false},{text:'واجب',correct:false},{text:'مستحب',correct:false}],
    explanation:'الأكل باليسرى خلاف السنة، فالسنة الأكل باليمنى.',
    goldenRule:'الأكل باليسرى = خلاف سنة + خطأ + لا أدب.',
    feedbackQuestion:{question:'ما حكم الأكل باليسرى؟',options:[{text:'خلاف السنة',correct:true},{text:'سنة',correct:false},{text:'واجب',correct:false},{text:'مستحب',correct:false}]} },
  { id:'fu4q20', unit:'u4a', lesson:'u4l1a', page:59, type:'matching', bloom:'understand', difficulty:'medium',
    question:'صِل كل فعل بوقته:',
    paragraph:'آداب الأكل: بسم الله (قبل) + يمنى (أثناء) + الحمد لله (بعد). (ص58-59)',
    pairs:[
      {left:'قبل الأكل',right:'بسم الله'},
      {left:'أثناء الأكل',right:'باليمنى'},
      {left:'بعد الأكل',right:'الحمد لله'},
      {left:'قبل الشرب',right:'بسم الله'},
    ],
    explanation:'قبل: بسم الله، أثناء: اليمنى، بعد: الحمد لله.',
    goldenRule:'آداب الأكل = قبل (تسمية) + أثناء (يمنى) + بعد (حمد).' },
  { id:'fu4q21', unit:'u4a', lesson:'u4l1a', page:60, type:'multipleChoice', bloom:'apply', difficulty:'medium',
    question:'على مائدة الإفطار، فالأدب:',
    paragraph:'آداب الأكل: تسمية + يمنى + جلوس. (ص58-60)',
    image:'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600',
    options:[{text:'أسمي الله وآكل باليمنى جالساً',correct:true},{text:'أنفخ في الطعام',correct:false},{text:'آكل باليسرى',correct:false},{text:'لا أسمي',correct:false}],
    explanation:'على مائدة الإفطار أسمي الله وآكل باليمنى جالساً.',
    goldenRule:'مائدة الإفطار = تسمية + يمنى + جلوس + أدب.',
    feedbackQuestion:{question:'ماذا تفعل على مائدة الإفطار؟',options:[{text:'أسمي وآكل باليمنى',correct:true},{text:'أنفخ',correct:false},{text:'آكل باليسرى',correct:false},{text:'لا أسمي',correct:false}]} },
  { id:'fu4q22', unit:'u4a', lesson:'u4l1a', page:59, type:'trueFalse', bloom:'evaluate', difficulty:'hard',
    question:'إهدار الطعام ورميه بلا حاجة من إهانة نعمة الله.',
    paragraph:'لا أهدر الطعام. (ص59)',
    correctAnswer:true,
    explanation:'إهدار الطعام ورميه بلا حاجة من إهانة نعمة الله وعدم شكرها.',
    goldenRule:'إهدار الطعام = إهانة نعمة + ذنب + لا شكر.',
    feedbackQuestion:{question:'هل إهدار الطعام إهانة للنعمة؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'بعض الأحيان',correct:false},{text:'لا أعرف',correct:false}]} },
  { id:'fu4q23', unit:'u4a', lesson:'u4l1a', page:58, type:'multipleChoice', bloom:'create', difficulty:'hard',
    question:'ركّب جملة فيها: تسمية + يمنى + حمد:',
    paragraph:'آداب الأكل: تسمية + يمنى + حمد. (ص58)',
    options:[
      {text:'أسمي الله وآكل باليمنى ثم أحمد الله',correct:true},
      {text:'أنفخ وآكل باليسرى',correct:false},
      {text:'أنام',correct:false},
      {text:'ألعب',correct:false},
    ],
    explanation:'الجملة: أسمي الله وآكل باليمنى ثم أحمد الله.',
    goldenRule:'الجملة الكاملة: تسمية + يمنى + حمد.' },
  { id:'fu4q24', unit:'u4a', lesson:'u4l1a', page:60, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'الأكل جالساً:',
    paragraph:'آكل جالساً وبهدوء. (ص60)',
    image:'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600',
    options:[{text:'من الآداب وأسلم للمعدة',correct:true},{text:'مكروه',correct:false},{text:'مضر',correct:false},{text:'لا قيمة',correct:false}],
    explanation:'الأكل جالساً من الآداب وأسلم للمعدة وأطيب للأكل.',
    goldenRule:'الأكل = جلوس + هدوء + أدب + سلامة.',
    feedbackQuestion:{question:'كيف تأكل؟',options:[{text:'جالساً',correct:true},{text:'واقفاً',correct:false},{text:'راكضاً',correct:false},{text:'لا فرق',correct:false}]} },
  { id:'fu4q25', unit:'u4a', lesson:'u4l1a', page:60, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'بعد الشرب تقول:',
    paragraph:'بعد الشرب أحمد الله. (ص60)',
    image:'https://images.unsplash.com/photo-1548837551-7c6d2e4f4f3e?w=600',
    options:[{text:'الحمد لله',correct:true},{text:'بسم الله',correct:false},{text:'سبحان الله',correct:false},{text:'لا شيء',correct:false}],
    explanation:'بعد الشرب تقول «الحمد لله» شكراً لله على نعمة الماء.',
    goldenRule:'بعد الشرب = الحمد لله + شكر + رضا.',
    feedbackQuestion:{question:'بماذا تختم بعد الشرب؟',options:[{text:'الحمد لله',correct:true},{text:'بسم الله',correct:false},{text:'سبحان الله',correct:false},{text:'لا شيء',correct:false}]} },
  { id:'fu4q26', unit:'u4a', lesson:'u4l1a', page:59, type:'multipleChoice', bloom:'apply', difficulty:'medium',
    question:'إذا نسيت التسمية في أوله، فتقول:',
    paragraph:'إذا نسيت التسمية في أوله فقل: بسم الله أوله وآخره. (ص59)',
    image:'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600',
    options:[{text:'بسم الله أوله وآخره',correct:true},{text:'لا شيء',correct:false},{text:'الحمد لله',correct:false},{text:'استغفر الله',correct:false}],
    explanation:'إذا نسيت التسمية في أوله تقول: «بسم الله أوله وآخره».',
    goldenRule:'نسيان التسمية = بسم الله أوله وآخره.',
    feedbackQuestion:{question:'ماذا تقول إذا نسيت التسمية؟',options:[{text:'بسم الله أوله وآخره',correct:true},{text:'لا شيء',correct:false},{text:'الحمد لله',correct:false},{text:'استغفر الله',correct:false}]} },
  { id:'fu4q27', unit:'u4a', lesson:'u4l1a', page:58, type:'trueFalse', bloom:'understand', difficulty:'easy',
    question:'الطعام نعمة من الله يجب احترامها وعدم إهدارها.',
    paragraph:'الطعام نعمة من الله. لا أهدر الطعام. (ص59)',
    correctAnswer:true,
    explanation:'الطعام نعمة من الله يجب احترامها وعدم إهدارها وشكر الله عليها.',
    goldenRule:'الطعام = نعمة + احترام + شكر + لا إهدار.',
    feedbackQuestion:{question:'هل الطعام نعمة يجب احترامها؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'بعض الأحيان',correct:false},{text:'لا أعرف',correct:false}]} },
  { id:'fu4q28', unit:'u4a', lesson:'u4l1a', page:60, type:'ordering', bloom:'apply', difficulty:'medium',
    question:'رتّب آداب الشرب:',
    paragraph:'آداب الشرب: تسمية + ثلاث دفعات + حمد. (ص60)',
    items:['الحمد لله','بسم الله','شرب على ثلاث دفعات'],
    correctOrder:[1,2,0],
    explanation:'آداب الشرب: بسم الله ← شرب على ثلاث دفعات ← الحمد لله.',
    goldenRule:'آداب الشرب = تسمية ← ثلاث دفعات ← حمد.' },
  { id:'fu4q29', unit:'u4a', lesson:'u4l1a', page:59, type:'multipleChoice', bloom:'evaluate', difficulty:'hard',
    question:'ما أثر آداب الأكل على المسلم؟',
    paragraph:'آداب الأكل: تسمية + يمنى + حمد + لا إهدار. (ص58-59)',
    image:'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600',
    options:[{text:'بركة في الطعام وأجر وصحة',correct:true},{text:'لا شيء',correct:false},{text:'ضرر',correct:false},{text:'مكروه',correct:false}],
    explanation:'آداب الأكل تمنح بركة في الطعام وأجراً من الله وصحة جيدة.',
    goldenRule:'آداب الأكل = بركة + أجر + صحة + رضا.',
    feedbackQuestion:{question:'ما أثر آداب الأكل؟',options:[{text:'بركة وأجر وصحة',correct:true},{text:'لا شيء',correct:false},{text:'ضرر',correct:false},{text:'مكروه',correct:false}]} },
  { id:'fu4q30', unit:'u4a', lesson:'u4l1a', page:60, type:'multipleChoice', bloom:'create', difficulty:'hard',
    question:'اكتب جملة فيها: تسمية + شرب باليمنى + حمد:',
    paragraph:'آداب الشرب: تسمية + يمنى + حمد. (ص60)',
    options:[
      {text:'أسمي الله وأشرب باليمنى وأحمده بعد الشرب',correct:true},
      {text:'أنفخ وأشرب باليسرى',correct:false},
      {text:'أنام',correct:false},
      {text:'ألعب',correct:false},
    ],
    explanation:'الجملة: أسمي الله وأشرب باليمنى وأحمده بعد الشرب.',
    goldenRule:'الجملة الكاملة: تسمية + يمنى + حمد.' },
];

export default FIQH_U4;