// التربية الإسلامية - الصف الثاني الابتدائي - الفصل الأول
// الوحدة الخامسة: الفقه والسلوك — الأذكار والأدعية
// الدرس الثاني: أذكار العطاس والنوم — صفحة 50-53

export const ADHKAR_L2 = [
  { id:'adk2q1', unit:'u5', lesson:'u5l2', page:50, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'عند العطاس، الأدب أن:',
    paragraph:'آداب العطاس: تغطية الفم وحمده. (ص50)',
    image:'https://images.unsplash.com/photo-1581579188871-4e6f6a5e0c4e?w=600',
    options:[{text:'أغطي فمي وأقول الحمد لله',correct:true},{text:'أصرخ',correct:false},{text:'أنصرف',correct:false},{text:'أتجاهل',correct:false}],
    explanation:'عند العطاس أغطي فمي بمنديل أو يدي ثم أقول «الحمد لله».',
    goldenRule:'العطاس = تغطية فم + الحمد لله + أدب.',
    feedbackQuestion:{question:'ماذا تفعل عند العطاس؟',options:[{text:'أغطي فمي وأحمد الله',correct:true},{text:'أصرخ',correct:false},{text:'أنصرف',correct:false},{text:'أتجاهل',correct:false}]} },
  { id:'adk2q2', unit:'u5', lesson:'u5l2', page:50, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'إذا عطس مسلم وقال «الحمد لله»، فماذا ترد عليه؟',
    paragraph:'إذا عطس مسلم وقال الحمد لله، يرد عليه: يرحمك الله. (ص50)',
    image:'https://images.unsplash.com/photo-1581579188871-4e6f6a5e0c4e?w=600',
    options:[{text:'يرحمك الله',correct:true},{text:'مرحبا',correct:false},{text:'لا شيء',correct:false},{text:'أهلاً',correct:false}],
    explanation:'إذا عطس المسلم وقال «الحمد لله»، ترد عليه بـ «يرحمك الله».',
    goldenRule:'العاطس: الحمد لله. الراد: يرحمك الله.',
    feedbackQuestion:{question:'بماذا ترد على العاطس؟',options:[{text:'يرحمك الله',correct:true},{text:'مرحبا',correct:false},{text:'لا شيء',correct:false},{text:'أهلاً',correct:false}]} },
  { id:'adk2q3', unit:'u5', lesson:'u5l2', page:50, type:'trueFalse', bloom:'understand', difficulty:'easy',
    question:'تغطية الفم عند العطاس من آداب الإسلام.',
    paragraph:'آداب العطاس: تغطية الفم. (ص50)',
    image:'https://images.unsplash.com/photo-1581579188871-4e6f6a5e0c4e?w=600',
    correctAnswer:true,
    explanation:'تغطية الفم عند العطاس من آداب الإسلام لأنها تحفظ الناس من الجراثيم.',
    goldenRule:'تغطية الفم عند العطاس = أدب + نظافة + حفظ.',
    feedbackQuestion:{question:'هل تغطية الفم عند العطاس من الآداب؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'مكروه',correct:false},{text:'لا أعرف',correct:false}]} },
  { id:'adk2q4', unit:'u5', lesson:'u5l2', page:50, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'العاطس يقول:',
    paragraph:'إذا عطس يقول: الحمد لله. (ص50)',
    image:'https://images.unsplash.com/photo-1581579188871-4e6f6a5e0c4e?w=600',
    options:[{text:'الحمد لله',correct:true},{text:'سبحان الله',correct:false},{text:'الله أكبر',correct:false},{text:'لا إله إلا الله',correct:false}],
    explanation:'العاطس يقول «الحمد لله» حمداً لله على نعمة العطاس.',
    goldenRule:'العاطس: الحمد لله — حمد لله على النعمة.',
    feedbackQuestion:{question:'ماذا يقول العاطس؟',options:[{text:'الحمد لله',correct:true},{text:'سبحان الله',correct:false},{text:'الله أكبر',correct:false},{text:'لا إله إلا الله',correct:false}]} },
  { id:'adk2q5', unit:'u5', lesson:'u5l2', page:50, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'تغطية الفم عند العطاس تحفظ من:',
    paragraph:'تغطية الفم عند العطاس تحفظ من انتقال الجراثيم. (ص50)',
    image:'https://images.unsplash.com/photo-1581579188871-4e6f6a5e0c4e?w=600',
    options:[{text:'انتقال الجراثيم للآخرين',correct:true},{text:'الملل',correct:false},{text:'النوم',correct:false},{text:'لا شيء',correct:false}],
    explanation:'تغطية الفم عند العطاس تحفظ من انتقال الجراثيم للأشخاص حولك.',
    goldenRule:'تغطية الفم = منع جراثيم + حفظ + نظافة.',
    feedbackQuestion:{question:'مم تحفظ تغطية الفم عند العطاس؟',options:[{text:'من انتقال الجراثيم',correct:true},{text:'الملل',correct:false},{text:'النوم',correct:false},{text:'لا شيء',correct:false}]} },
  { id:'adk2q6', unit:'u5', lesson:'u5l2', page:50, type:'multipleChoice', bloom:'apply', difficulty:'medium',
    question:'إذا عطس زميلك في الصف وقال «الحمد لله»، فماذا تقول له؟',
    paragraph:'إذا عطس وقال الحمد لله، يرد عليه: يرحمك الله. (ص50)',
    image:'https://images.unsplash.com/photo-1581579188871-4e6f6a5e0c4e?w=600',
    options:[{text:'يرحمك الله',correct:true},{text:'لا شيء',correct:false},{text:'اصمت',correct:false},{text:'مرحبا',correct:false}],
    explanation:'ترد على زميلك العاطس بـ «يرحمك الله» بعد قوله «الحمد لله».',
    goldenRule:'رد العاطس: يرحمك الله — أدب الإسلام.',
    feedbackQuestion:{question:'بماذا ترد على زميلك العاطس؟',options:[{text:'يرحمك الله',correct:true},{text:'لا شيء',correct:false},{text:'اصمت',correct:false},{text:'مرحبا',correct:false}]} },
  { id:'adk2q7', unit:'u5', lesson:'u5l2', page:50, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'بماذا يغطي المسلم فمه عند العطاس؟',
    paragraph:'آداب العطاس: تغطية الفم بمنديل أو يد. (ص50)',
    image:'https://images.unsplash.com/photo-1581579188871-4e6f6a5e0c4e?w=600',
    options:[{text:'بمنديل أو بكف يده',correct:true},{text:'لا شيء',correct:false},{text:'بقلم',correct:false},{text:'بكتاب',correct:false}],
    explanation:'يغطي فمه عند العطاس بمنديل أو بكف يده لمنع انتقال الجراثيم.',
    goldenRule:'تغطية الفم = منديل أو كف + حفظ + نظافة.',
    feedbackQuestion:{question:'بماذا تغطي فمك عند العطاس؟',options:[{text:'بمنديل أو كف',correct:true},{text:'لا شيء',correct:false},{text:'بقلم',correct:false},{text:'بكتاب',correct:false}]} },
  { id:'adk2q8', unit:'u5', lesson:'u5l2', page:50, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'حمد العاطس بعد العطاس شكر لله على:',
    paragraph:'العاطس يقول الحمد لله. (ص50)',
    image:'https://images.unsplash.com/photo-1581579188871-4e6f6a5e0c4e?w=600',
    options:[{text:'نفسه وشفائه من ضيق النفس',correct:true},{text:'لا شيء',correct:false},{text:'المرض',correct:false},{text:'الجوع',correct:false}],
    explanation:'العطاس يفرج ضيق النفس، فيحمد العاطس ربه على تخفيف هذا الضيق.',
    goldenRule:'العطاس = فرج ضيق + حمد لله + شكر.',
    feedbackQuestion:{question:'على ماذا يحمد العاطس ربه؟',options:[{text:'على فرج ضيق النفس',correct:true},{text:'لا شيء',correct:false},{text:'المرض',correct:false},{text:'الجوع',correct:false}]} },
  { id:'adk2q9', unit:'u5', lesson:'u5l2', page:50, type:'trueFalse', bloom:'evaluate', difficulty:'hard',
    question:'ترك رد العاطس تارك لحق المسلم على أخيه.',
    paragraph:'إذا عطس وقال الحمد لله، يرد عليه: يرحمك الله. (ص50)',
    correctAnswer:true,
    explanation:'رد العاطس بـ «يرحمك الله» حق المسلم على أخيه، وتركه ترك لحق.',
    goldenRule:'رد العاطس = حق المسلم على أخيه + أدب + محبة.',
    feedbackQuestion:{question:'هل رد العاطس حق للمسلم؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'بعض الأحيان',correct:false},{text:'لا أعرف',correct:false}]} },
  { id:'adk2q10', unit:'u5', lesson:'u5l2', page:50, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'العطاس يجعل النفس:',
    paragraph:'العطاس يفرج ضيق النفس. (ص50)',
    image:'https://images.unsplash.com/photo-1581579188871-4e6f6a5e0c4e?w=600',
    options:[{text:'مسترخية بعد ضيق',correct:true},{text:'أشد ضيقاً',correct:false},{text:'مريضة',correct:false},{text:'لا شيء',correct:false}],
    explanation:'العطاس يفرج ضيق النفس ويريح الصدر، لذا نحمد الله عليه.',
    goldenRule:'العطاس = فرج + راحة + حمد.',
    feedbackQuestion:{question:'ماذا يفعل العطاس بالنفس؟',options:[{text:'يفرج ضيقها',correct:true},{text:'يضيقها',correct:false},{text:'يؤذيها',correct:false},{text:'لا شيء',correct:false}]} },
  { id:'adk2q11', unit:'u5', lesson:'u5l2', page:50, type:'classify', bloom:'analyze', difficulty:'medium',
    question:'صنّف: آداب العطاس أم لا؟',
    paragraph:'آداب العطاس: تغطية الفم + الحمد لله + رد يرحمك الله. (ص50)',
    categories:['من آداب العطاس 🤧','ليس من آداب العطاس ❌'],
    items:[
      {text:'تغطية الفم',correct_category:0},{text:'الصراخ',correct_category:1},
      {text:'قول الحمد لله',correct_category:0},{text:'ترك رد العاطس',correct_category:1},
      {text:'الرد بيرحمك الله',correct_category:0},{text:'نشر الجراثيم',correct_category:1},
    ],
    explanation:'من آداب العطاس: تغطية الفم + الحمد لله + رد يرحمك الله. الصراخ ونشر الجراثيم من المساوئ.',
    goldenRule:'آداب العطاس = تغطية + حمد + رد.' },
  { id:'adk2q12', unit:'u5', lesson:'u5l2', page:50, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'إذا عطست ولم يرد عليك أحد، فماذا تفعل؟',
    paragraph:'إذا عطس وقال الحمد لله ولم يرد عليه أحد، يقول لنفسه: يرحمك الله. (ص50)',
    options:[{text:'أقول لنفسي: يرحني الله',correct:true},{text:'أصرخ',correct:false},{text:'أغضب',correct:false},{text:'أنصرف',correct:false}],
    explanation:'إذا عطست ولم يرد عليك أحد، تقول لنفسك: «يرحمني الله ويصلحني ويهدني».',
    goldenRule:'عدم الرد = قول لنفسك: يرحني الله.',
    feedbackQuestion:{question:'ماذا تقول إذا لم يرد عليك أحد بعد العطاس؟',options:[{text:'يرحني الله',correct:true},{text:'أصرخ',correct:false},{text:'أغضب',correct:false},{text:'أنصرف',correct:false}]} },
  { id:'adk2q13', unit:'u5', lesson:'u5l2', page:50, type:'multipleChoice', bloom:'apply', difficulty:'medium',
    question:'في طابور الصباح، إذا عطس صديقك وغطى فمه وقال الحمد لله، فماذا تقول؟',
    paragraph:'إذا عطس وقال الحمد لله، يرد عليه: يرحمك الله. (ص50)',
    image:'https://images.unsplash.com/photo-1503676262392-70a456368e8b?w=600',
    options:[{text:'يرحمك الله',correct:true},{text:'لا شيء',correct:false},{text:'أنصرف',correct:false},{text:'أصرخ',correct:false}],
    explanation:'ترد على صديقك العاطس بـ «يرحمك الله» بعد قوله «الحمد لله».',
    goldenRule:'رد العاطس في كل مكان: يرحمك الله.',
    feedbackQuestion:{question:'ماذا تقول لصديقك العاطس؟',options:[{text:'يرحمك الله',correct:true},{text:'لا شيء',correct:false},{text:'أنصرف',correct:false},{text:'أصرخ',correct:false}]} },
  { id:'adk2q14', unit:'u5', lesson:'u5l2', page:50, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'تغطية الفم عند العطاس:',
    paragraph:'تغطية الفم عند العطاس تحفظ من الجراثيم. (ص50)',
    image:'https://images.unsplash.com/photo-1581579188871-4e6f6a5e0c4e?w=600',
    options:[{text:'أدب ونظافة وحفظ للناس',correct:true},{text:'ضعف',correct:false},{text:'عادة',correct:false},{text:'لا قيمة',correct:false}],
    explanation:'تغطية الفم عند العطاس أدب ونظافة وحفظ للناس من الجراثيم.',
    goldenRule:'تغطية الفم = أدب + نظافة + حفظ.',
    feedbackQuestion:{question:'ماذا في تغطية الفم عند العطاس؟',options:[{text:'أدب ونظافة وحفظ',correct:true},{text:'ضعف',correct:false},{text:'عادة',correct:false},{text:'لا قيمة',correct:false}]} },
  { id:'adk2q15', unit:'u5', lesson:'u5l2', page:50, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'ترتيب آداب العطاس:',
    paragraph:'آداب العطاس: تغطية الفم ثم قول الحمد لله. (ص50)',
    image:'https://images.unsplash.com/photo-1581579188871-4e6f6a5e0c4e?w=600',
    options:[{text:'أغطي فمي ثم أقول الحمد لله',correct:true},{text:'أقول الحمد لله ثم أغطي',correct:false},{text:'لا أغطي',correct:false},{text:'لا أقول',correct:false}],
    explanation:'ترتيب آداب العطاس: أغطي فمي أولاً ثم أقول الحمد لله.',
    goldenRule:'ترتيب العطاس = تغطية ← حمد.',
    feedbackQuestion:{question:'ماذا تفعل أولاً عند العطاس؟',options:[{text:'أغطي فمي',correct:true},{text:'أقول الحمد لله',correct:false},{text:'لا أغطي',correct:false},{text:'لا أقول',correct:false}]} },
  { id:'adk2q16', unit:'u5', lesson:'u5l2', page:50, type:'ordering', bloom:'apply', difficulty:'medium',
    question:'رتّب آداب العطاس:',
    paragraph:'آداب العطاس: تغطية + حمد + رد. (ص50)',
    items:['أقول الحمد لله','أغطي فمي','يرد عليّ الناس بيرحمك الله'],
    correctOrder:[1,0,2],
    explanation:'آداب العطاس: أغطي فمي ← أقول الحمد لله ← يرد الناس بيرحمك الله.',
    goldenRule:'آداب العطاس = تغطية ← حمد ← رد.' },
  { id:'adk2q17', unit:'u5', lesson:'u5l2', page:50, type:'multipleChoice', bloom:'evaluate', difficulty:'hard',
    question:'لماذا أمر الإسلام بآداب العطاس؟',
    paragraph:'آداب العطاس: تغطية الفم والحمد لله. (ص50)',
    image:'https://images.unsplash.com/photo-1581579188871-4e6f6a5e0c4e?w=600',
    options:[{text:'للنظافة وحفظ الناس وحمد الله',correct:true},{text:'عادة',correct:false},{text:'لا سبب',correct:false},{text:'مكروه',correct:false}],
    explanation:'آداب العطاس للنظافة وحفظ الناس من الجراثيم وحمد الله على نعمة العطاس.',
    goldenRule:'آداب العطاس = نظافة + حفظ + حمد + أدب.',
    feedbackQuestion:{question:'لماذا أمر الإسلام بآداب العطاس؟',options:[{text:'للنظافة والحفظ والحمد',correct:true},{text:'عادة',correct:false},{text:'لا سبب',correct:false},{text:'مكروه',correct:false}]} },
  { id:'adk2q18', unit:'u5', lesson:'u5l2', page:50, type:'trueFalse', bloom:'understand', difficulty:'easy',
    question:'إذا عطس مسلم ولم يقل الحمد لله، لا يُرد عليه بيرحمك الله.',
    paragraph:'إذا عطس وقال الحمد لله، يرد عليه: يرحمك الله. (ص50)',
    correctAnswer:true,
    explanation:'لا يُرد على العاطس إلا إذا قال «الحمد لله»، فإذا لم يقلها فلا رد.',
    goldenRule:'الرد على العاطس = بعد قوله «الحمد لله».',
    feedbackQuestion:{question:'متى ترد على العاطس؟',options:[{text:'بعد قوله الحمد لله',correct:true},{text:'قبل قوله',correct:false},{text:'دائماً',correct:false},{text:'لا أعرف',correct:false}]} },
  { id:'adk2q19', unit:'u5', lesson:'u5l2', page:50, type:'multipleChoice', bloom:'create', difficulty:'hard',
    question:'ركّب جملة فيها: تغطية + حمد + رد:',
    paragraph:'آداب العطاس: تغطية + حمد + رد. (ص50)',
    options:[
      {text:'أغطي فمي وأقول الحمد لله ويرد الناس بيرحمك الله',correct:true},
      {text:'أنام وأنسى',correct:false},
      {text:'أصرخ',correct:false},
      {text:'أنصرف',correct:false},
    ],
    explanation:'الجملة: أغطي فمي وأقول الحمد لله ويرد الناس بيرحمك الله.',
    goldenRule:'الجملة الكاملة: تغطية + حمد + رد.' },
  { id:'adk2q20', unit:'u5', lesson:'u5l2', page:50, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'الجار الذي يعطس بجانبك ويقول الحمد لله، تقول له:',
    paragraph:'إذا عطس وقال الحمد لله، يرد عليه: يرحمك الله. (ص50)',
    image:'https://images.unsplash.com/photo-1581579188871-4e6f6a5e0c4e?w=600',
    options:[{text:'يرحمك الله',correct:true},{text:'لا شيء',correct:false},{text:'أنصرف',correct:false},{text:'أصرخ',correct:false}],
    explanation:'ترد على جارك العاطس بـ «يرحمك الله» حقاً له عليك.',
    goldenRule:'رد الجار العاطس: يرحمك الله.',
    feedbackQuestion:{question:'ماذا تقول لجارك العاطس؟',options:[{text:'يرحمك الله',correct:true},{text:'لا شيء',correct:false},{text:'أنصرف',correct:false},{text:'أصرخ',correct:false}]} },
  { id:'adk2q21', unit:'u5', lesson:'u5l2', page:50, type:'matching', bloom:'understand', difficulty:'medium',
    question:'صِل كل خطوة بفعلها:',
    paragraph:'آداب العطاس: تغطية + حمد + رد. (ص50)',
    pairs:[
      {left:'أغطي',right:'فمي بمنديل'},
      {left:'أقول',right:'الحمد لله'},
      {left:'يرد الناس',right:'يرحمك الله'},
      {left:'إذا لم يرد أحد',right:'أقول لنفسي: يرحني الله'},
    ],
    explanation:'آداب العطاس: أغطي فمي ← أقول الحمد لله ← يرد الناس ← إذا لم يرد أحد أقول لنفسي.',
    goldenRule:'آداب العطاس الكاملة = تغطية + حمد + رد + دعاء النفس.' },
  { id:'adk2q22', unit:'u5', lesson:'u5l2', page:50, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'العطاس بدون تغطية الفم:',
    paragraph:'تغطية الفم عند العطاس من الآداب. (ص50)',
    image:'https://images.unsplash.com/photo-1581579188871-4e6f6a5e0c4e?w=600',
    options:[{text:'ينشر الجراثيم ويؤذي الناس',correct:true},{text:'لا شيء',correct:false},{text:'مفيد',correct:false},{text:'مستحب',correct:false}],
    explanation:'العطاس بدون تغطية ينشر الجراثيم ويؤذي الناس، لذا أمر الإسلام بتغطية الفم.',
    goldenRule:'عدم تغطية الفم = أذى + جراثيم + قبح.',
    feedbackQuestion:{question:'ماذا يفعل العطاس بدون تغطية؟',options:[{text:'ينشر الجراثيم',correct:true},{text:'لا شيء',correct:false},{text:'مفيد',correct:false},{text:'مستحب',correct:false}]} },
  { id:'adk2q23', unit:'u5', lesson:'u5l2', page:50, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'«الحمد لله» تعني:',
    paragraph:'العاطس يقول الحمد لله. (ص50)',
    options:[{text:'شكر الله وحمده على نعمه',correct:true},{text:'دعاء فقط',correct:false},{text:'استغفار',correct:false},{text:'لا شيء',correct:false}],
    explanation:'«الحمد لله» تعني شكر الله وحمده على نعمه، خاصة نعمة العطاس.',
    goldenRule:'الحمد لله = شكر + حمد + ثناء على الله.',
    feedbackQuestion:{question:'ماذا تعني «الحمد لله»؟',options:[{text:'شكر الله وحمده',correct:true},{text:'دعاء',correct:false},{text:'استغفار',correct:false},{text:'لا شيء',correct:false}]} },
  { id:'adk2q24', unit:'u5', lesson:'u5l2', page:50, type:'multipleChoice', bloom:'apply', difficulty:'medium',
    question:'إذا عطست في المسجد، فالأدب:',
    paragraph:'آداب العطاس في كل مكان: تغطية + حمد. (ص50)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'أغطي فمي وأقول الحمد لله',correct:true},{text:'أصرخ',correct:false},{text:'أنصرف',correct:false},{text:'أتجاهل',correct:false}],
    explanation:'في المسجد وكل مكان أغطي فمي عند العطاس وأقول الحمد لله.',
    goldenRule:'آداب العطاس في كل مكان = تغطية + حمد.',
    feedbackQuestion:{question:'ماذا تفعل إذا عطست في المسجد؟',options:[{text:'أغطي فمي وأحمد الله',correct:true},{text:'أصرخ',correct:false},{text:'أنصرف',correct:false},{text:'أتجاهل',correct:false}]} },
  { id:'adk2q25', unit:'u5', lesson:'u5l2', page:50, type:'fillBlank', bloom:'apply', difficulty:'easy',
    question:'أكمل: إذا عطس مسلم يقول ___.',
    paragraph:'إذا عطس يقول: الحمد لله. (ص50)',
    blanks:['الحمد لله'],
    wordBank:['الحمد لله','سبحان الله','الله أكبر','استغفر الله'],
    explanation:'إذا عطس المسلم يقول «الحمد لله» شكراً لله.',
    goldenRule:'العاطس: الحمد لله.' },
  { id:'adk2q26', unit:'u5', lesson:'u5l2', page:50, type:'trueFalse', bloom:'evaluate', difficulty:'hard',
    question:'آداب العطاس تدل على اهتمام الإسلام بالنظافة وحفظ الصحة.',
    paragraph:'آداب العطاس: تغطية الفم للحفظ. (ص50)',
    correctAnswer:true,
    explanation:'آداب العطاس تدل على اهتمام الإسلام بالنظافة وحفظ صحة الأفراد.',
    goldenRule:'آداب العطاس = نظافة + صحة + حفظ + أدب.',
    feedbackQuestion:{question:'على ماذا تدل آداب العطاس؟',options:[{text:'الاهتمام بالنظافة والصحة',correct:true},{text:'لا شيء',correct:false},{text:'عادة',correct:false},{text:'مكروه',correct:false}]} },
  { id:'adk2q27', unit:'u5', lesson:'u5l2', page:50, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'رد العاطس «يرحمك الله» دعاء له بـ:',
    paragraph:'يرد عليه: يرحمك الله. (ص50)',
    options:[{text:'الرحمة',correct:true},{text:'العذاب',correct:false},{text:'المرض',correct:false},{text:'الفقر',correct:false}],
    explanation:'«يرحمك الله» دعاء للعاطس بالرحمة من الله سبحانه وتعالى.',
    goldenRule:'يرحمك الله = دعاء + رحمة + محبة.',
    feedbackQuestion:{question:'بماذا يدعو الراد للعاطس؟',options:[{text:'بالرحمة',correct:true},{text:'العذاب',correct:false},{text:'المرض',correct:false},{text:'الفقر',correct:false}]} },
  { id:'adk2q28', unit:'u5', lesson:'u5l2', page:50, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'إذا عطس غير المسلم بجانبك، فهل ترد عليه بيرحمك الله؟',
    paragraph:'الرد بيرحمك الله للمسلم الذي قال الحمد لله. (ص50)',
    options:[{text:'لا، الرد للمسلم فقط',correct:true},{text:'نعم',correct:false},{text:'بعض الأحيان',correct:false},{text:'لا أعرف',correct:false}],
    explanation:'الرد «يرحمك الله» للمسلم الذي عطس وقال «الحمد لله». لغير المسلم تُدعى له بالهداية.',
    goldenRule:'رد العاطس = للمسلم الذي قال الحمد لله.',
    feedbackQuestion:{question:'هل ترد على غير المسلم بيرحمك الله؟',options:[{text:'لا، للمسلم فقط',correct:true},{text:'نعم',correct:false},{text:'بعض الأحيان',correct:false},{text:'لا أعرف',correct:false}]} },
  { id:'adk2q29', unit:'u5', lesson:'u5l2', page:50, type:'multipleChoice', bloom:'create', difficulty:'hard',
    question:'اكتب جملة فيها: تغطية فم + حمد + رد الناس:',
    paragraph:'آداب العطاس: تغطية + حمد + رد. (ص50)',
    options:[
      {text:'أغطي فمي عند العطاس وأحمد الله ويرد الناس بيرحمك الله',correct:true},
      {text:'أنام وأنسى',correct:false},
      {text:'أصرخ',correct:false},
      {text:'أنصرف',correct:false},
    ],
    explanation:'الجملة: أغطي فمي عند العطاس وأحمد الله ويرد الناس بيرحمك الله.',
    goldenRule:'الجملة الكاملة: تغطية + حمد + رد.' },
  { id:'adk2q30', unit:'u5', lesson:'u5l2', page:50, type:'classify', bloom:'analyze', difficulty:'medium',
    question:'صنّف: ما الذي تقوله في كل موقف؟',
    paragraph:'العاطس: الحمد لله. الراد: يرحمك الله. غير المردود: يرحني الله. (ص50)',
    categories:['يقولها العاطس 🤧','يقولها الراد 🤲'],
    items:[
      {text:'الحمد لله',correct_category:0},{text:'يرحمك الله',correct_category:1},
      {text:'يرحمني الله',correct_category:0},{text:'يرحمكم الله',correct_category:1},
    ],
    explanation:'العاطس يقول: الحمد لله + يرحني الله (إن لم يرد). الراد يقول: يرحمك الله.',
    goldenRule:'لكل طرف ما يقول: عاطس + راد.' },
  { id:'adk2q31', unit:'u5', lesson:'u5l2', page:50, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'تغطية الفم عند العطاس تُظهر:',
    paragraph:'تغطية الفم عند العطاس أدب ونظافة. (ص50)',
    image:'https://images.unsplash.com/photo-1581579188871-4e6f6a5e0c4e?w=600',
    options:[{text:'رحمة المسلم بالناس ونظافته',correct:true},{text:'أنانية',correct:false},{text:'كراهة',correct:false},{text:'لا شيء',correct:false}],
    explanation:'تغطية الفم عند العطاس تُظهر رحمة المسلم بالناس ونظافته وأدبه.',
    goldenRule:'تغطية الفم = رحمة + نظافة + أدب.',
    feedbackQuestion:{question:'على ماذا تدل تغطية الفم عند العطاس؟',options:[{text:'الرحمة والنظافة',correct:true},{text:'الأنانية',correct:false},{text:'الكراهة',correct:false},{text:'لا شيء',correct:false}]} },
  { id:'adk2q32', unit:'u5', lesson:'u5l2', page:50, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'من علَّمنا آداب العطاس؟',
    paragraph:'آداب العطاس من السنة النبوية. (ص50)',
    image:'https://images.unsplash.com/photo-1581579188871-4e6f6a5e0c4e?w=600',
    options:[{text:'رسول الله ﷺ',correct:true},{text:'أبوك',correct:false},{text:'أخوك',correct:false},{text:'صديقك',correct:false}],
    explanation:'آداب العطاس علَّمنا إياها رسول الله ﷺ في سنته.',
    goldenRule:'رسول الله ﷺ علَّمنا: غطِّ فمك + احمد الله + يرد الناس.',
    feedbackQuestion:{question:'من علَّمنا آداب العطاس؟',options:[{text:'رسول الله ﷺ',correct:true},{text:'أبوك',correct:false},{text:'أخوك',correct:false},{text:'صديقك',correct:false}]} },
  { id:'adk2q33', unit:'u5', lesson:'u5l2', page:50, type:'multipleChoice', bloom:'evaluate', difficulty:'hard',
    question:'لماذا يُعد العطاس نعمة تستحق الحمد؟',
    paragraph:'العطاس يفرج ضيق النفس. (ص50)',
    image:'https://images.unsplash.com/photo-1581579188871-4e6f6a5e0c4e?w=600',
    options:[{text:'لأنه يفرج ضيق النفس ويريح الصدر',correct:true},{text:'لا سبب',correct:false},{text:'لأنه أذى',correct:false},{text:'لا أعرف',correct:false}],
    explanation:'العطاس نعمة لأنه يفرج ضيق النفس ويريح الصدر، فيستحق الحمد.',
    goldenRule:'العطاس = فرج + راحة + نعمة = حمد.',
    feedbackQuestion:{question:'لماذا العطاس نعمة؟',options:[{text:'لأنه يفرج ضيق النفس',correct:true},{text:'لا سبب',correct:false},{text:'أذى',correct:false},{text:'لا أعرف',correct:false}]} },
  { id:'adk2q34', unit:'u5', lesson:'u5l2', page:50, type:'ordering', bloom:'apply', difficulty:'medium',
    question:'رتّب ما يحدث عند العطاس:',
    paragraph:'آداب العطاس: عطس ← تغطية ← حمد ← رد. (ص50)',
    items:['يقول الحمد لله','أعطس','أغطي فمي'],
    correctOrder:[1,2,0],
    explanation:'عند العطاس: أعطس ← أغطي فمي ← أقول الحمد لله.',
    goldenRule:'ترتيب العطاس = عطس ← تغطية ← حمد.' },
  { id:'adk2q35', unit:'u5', lesson:'u5l2', page:50, type:'trueFalse', bloom:'understand', difficulty:'easy',
    question:'تغطية الفم عند التثاؤب أيضاً من الآداب.',
    paragraph:'آداب العطاس والنظافة: تغطية الفم. (ص50)',
    correctAnswer:true,
    explanation:'تغطية الفم عند التثاؤب والعطاس كلها من الآداب الإسلامية.',
    goldenRule:'تغطية الفم = عند عطاس + عند تثاؤب = أدب.',
    feedbackQuestion:{question:'هل تغطية الفم عند التثاؤب من الآداب؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'مكروه',correct:false},{text:'لا أعرف',correct:false}]} },
  { id:'adk2q36', unit:'u5', lesson:'u5l2', page:50, type:'multipleChoice', bloom:'apply', difficulty:'medium',
    question:'إذا عطست في مكان عام، فالأدب:',
    paragraph:'آداب العطاس في كل مكان: تغطية + حمد. (ص50)',
    image:'https://images.unsplash.com/photo-1503676262392-70a456368e8b?w=600',
    options:[{text:'أغطي فمي وأقول الحمد لله',correct:true},{text:'أصرخ',correct:false},{text:'أنصرف',correct:false},{text:'أتجاهل',correct:false}],
    explanation:'في المكان العام أغطي فمي عند العطاس وأقول الحمد لله لحفظ الناس.',
    goldenRule:'آداب العطاس العامة = تغطية + حمد + حفظ.',
    feedbackQuestion:{question:'ماذا تفعل إذا عطست في مكان عام؟',options:[{text:'أغطي فمي وأحمد الله',correct:true},{text:'أصرخ',correct:false},{text:'أنصرف',correct:false},{text:'أتجاهل',correct:false}]} },
  { id:'adk2q37', unit:'u5', lesson:'u5l2', page:50, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'العاطس والراد كلاهما:',
    paragraph:'العاطس: الحمد لله. الراد: يرحمك الله. (ص50)',
    options:[{text:'يؤجران على ما يقولان',correct:true},{text:'لا أجر',correct:false},{text:'يأثمان',correct:false},{text:'لا شيء',correct:false}],
    explanation:'العاطس والراد كلاهما يؤجران: العاطس على حمد الله، والراد على دعائه لأخيه.',
    goldenRule:'العاطس + الراد = أجر + ثواب + خير.',
    feedbackQuestion:{question:'هل العاطس والراد يؤجران؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'أحدهما',correct:false},{text:'لا أعرف',correct:false}]} },
  { id:'adk2q38', unit:'u5', lesson:'u5l2', page:50, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'إذا عطست ولم أقل الحمد لله، فماذا يفعل الناس حولي؟',
    paragraph:'لا يرد على العاطس إلا إذا قال الحمد لله. (ص50)',
    options:[{text:'لا يردون عليّ',correct:true},{text:'يردون',correct:false},{text:'يصرخون',correct:false},{text:'ينصرفون',correct:false}],
    explanation:'إذا عطست ولم تقل «الحمد لله» فلا يرد عليك الناس لأن الرد مشروط بالحمد.',
    goldenRule:'الرد مشروط بـ «الحمد لله» من العاطس.',
    feedbackQuestion:{question:'ماذا يفعل الناس إذا عطست ولم تقل الحمد لله؟',options:[{text:'لا يردون',correct:true},{text:'يردون',correct:false},{text:'يصرخون',correct:false},{text:'ينصرفون',correct:false}]} },
  { id:'adk2q39', unit:'u5', lesson:'u5l2', page:50, type:'multipleChoice', bloom:'create', difficulty:'hard',
    question:'ركّب جملة فيها: تغطية + حمد + رد:',
    paragraph:'آداب العطاس: تغطية + حمد + رد. (ص50)',
    options:[
      {text:'أغطي فمي عند العطاس وأحمد الله فيرد الناس بيرحمك الله',correct:true},
      {text:'أنام وأنسى',correct:false},
      {text:'أصرخ',correct:false},
      {text:'أنصرف',correct:false},
    ],
    explanation:'الجملة: أغطي فمي عند العطاس وأحمد الله فيرد الناس بيرحمك الله.',
    goldenRule:'الجملة الكاملة: تغطية + حمد + رد.' },
  { id:'adk2q40', unit:'u5', lesson:'u5l2', page:50, type:'multipleChoice', bloom:'evaluate', difficulty:'hard',
    question:'ما أثر آداب العطاس على المجتمع؟',
    paragraph:'آداب العطاس: تغطية + حمد + رد. (ص50)',
    image:'https://images.unsplash.com/photo-1581579188871-4e6f6a5e0c4e?w=600',
    options:[{text:'تحفظ الصحة وتزيد المحبة بين المسلمين',correct:true},{text:'لا أثر',correct:false},{text:'تضر',correct:false},{text:'مكروهة',correct:false}],
    explanation:'آداب العطاس تحفظ صحة المجتمع وتزيد المحبة بين المسلمين بالدعاء.',
    goldenRule:'آداب العطاس = حفظ صحة + محبة + دعاء + أدب.',
    feedbackQuestion:{question:'ما أثر آداب العطاس على المجتمع؟',options:[{text:'حفظ الصحة والمحبة',correct:true},{text:'لا أثر',correct:false},{text:'تضر',correct:false},{text:'مكروهة',correct:false}]} },
  { id:'adk2q41', unit:'u5', lesson:'u5l2', page:50, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'تغطية الفم بالكف عند العطاس:',
    paragraph:'تغطية الفم بمنديل أو كف اليد. (ص50)',
    image:'https://images.unsplash.com/photo-1581579188871-4e6f6a5e0c4e?w=600',
    options:[{text:'تُساوي المنديل في الحفظ',correct:true},{text:'لا فائدة',correct:false},{text:'تضر',correct:false},{text:'مكروه',correct:false}],
    explanation:'تغطية الفم بالكف عند العطاس تُساوي المنديل في حفظ الناس من الجراثيم.',
    goldenRule:'تغطية الفم = منديل أو كف = حفظ + نظافة.',
    feedbackQuestion:{question:'هل تغطية الفم بالكف مفيدة؟',options:[{text:'نعم، كالمنديل',correct:true},{text:'لا فائدة',correct:false},{text:'تضر',correct:false},{text:'مكروه',correct:false}]} },
  { id:'adk2q42', unit:'u5', lesson:'u5l2', page:50, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'الرد على العاطس «يرحمك الله» يكون بـ:',
    paragraph:'إذا عطس وقال الحمد لله، يرد عليه: يرحمك الله. (ص50)',
    options:[{text:'صوت واضح مسموع',correct:true},{text:'همس',correct:false},{text:'صمت',correct:false},{text:'صراخ',correct:false}],
    explanation:'الرد على العاطس «يرحمك الله» يكون بصوت واضح مسموع ليصل للعاطس.',
    goldenRule:'رد العاطس = صوت واضح + مسموع + يرحمك الله.',
    feedbackQuestion:{question:'كيف ترد على العاطس؟',options:[{text:'بصوت واضح',correct:true},{text:'همس',correct:false},{text:'صمت',correct:false},{text:'صراخ',correct:false}]} },
  { id:'adk2q43', unit:'u5', lesson:'u5l2', page:50, type:'trueFalse', bloom:'evaluate', difficulty:'hard',
    question:'من ترك تغطية فمه عند العطاس فقد قصر في الأدب.',
    paragraph:'آداب العطاس: تغطية الفم. (ص50)',
    correctAnswer:true,
    explanation:'من ترك تغطية فمه عند العطاس فقد قصر في الأدب وعرّض الناس للجراثيم.',
    goldenRule:'ترك تغطية الفم = قصور في الأدب + أذى للناس.',
    feedbackQuestion:{question:'هل من ترك تغطية فمه قصر في الأدب؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'بعض الأحيان',correct:false},{text:'لا أعرف',correct:false}]} },
  { id:'adk2q44', unit:'u5', lesson:'u5l2', page:50, type:'multipleChoice', bloom:'apply', difficulty:'medium',
    question:'إذا عطس معلمك وغطى فمه وقال الحمد لله، فماذا تقول؟',
    paragraph:'إذا عطس وقال الحمد لله، يرد عليه: يرحمك الله. (ص50)',
    image:'https://images.unsplash.com/photo-1581579188871-4e6f6a5e0c4e?w=600',
    options:[{text:'يرحمك الله',correct:true},{text:'لا شيء',correct:false},{text:'أنصرف',correct:false},{text:'أصرخ',correct:false}],
    explanation:'ترد على معلمك العاطس بـ «يرحمك الله» احتراماً وأدباً ودعاءً له.',
    goldenRule:'رد معلمك العاطس: يرحمك الله — أدب + احترام + دعاء.',
    feedbackQuestion:{question:'ماذا تقول لمعلمك العاطس؟',options:[{text:'يرحمك الله',correct:true},{text:'لا شيء',correct:false},{text:'أنصرف',correct:false},{text:'أصرخ',correct:false}]} },
  { id:'adk2q45', unit:'u5', lesson:'u5l2', page:50, type:'matching', bloom:'understand', difficulty:'medium',
    question:'صِل كل شخص بموقفه:',
    paragraph:'آداب العطاس: العاطس + الراد + من لم يرد. (ص50)',
    pairs:[
      {left:'العاطس',right:'يقول الحمد لله'},
      {left:'الراد',right:'يقول يرحمك الله'},
      {left:'من عطس ولم يرد',right:'يقول لنفسه يرحني الله'},
      {left:'الكل',right:'يؤجر على فعله'},
    ],
    explanation:'العاطس: الحمد لله. الراد: يرحمك الله. من لم يرد: يرحني الله. الكل يؤجر.',
    goldenRule:'لكل طرف فعله وقوله + أجره.' },
  { id:'adk2q46', unit:'u5', lesson:'u5l2', page:50, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'عدم تغطية الفم عند العطاس يدل على:',
    paragraph:'آداب العطاس: تغطية الفم. (ص50)',
    image:'https://images.unsplash.com/photo-1581579188871-4e6f6a5e0c4e?w=600',
    options:[{text:'قلة أدب وعدم اهتمام بالناس',correct:true},{text:'قوة',correct:false},{text:'أدب',correct:false},{text:'نظافة',correct:false}],
    explanation:'عدم تغطية الفم عند العطاس يدل على قلة أدب وعدم اهتمام بصحة الناس.',
    goldenRule:'عدم تغطية الفم = قلة أدب + لا اهتمام + أذى.',
    feedbackQuestion:{question:'على ماذا يدل عدم تغطية الفم عند العطاس؟',options:[{text:'قلة أدب',correct:true},{text:'قوة',correct:false},{text:'أدب',correct:false},{text:'نظافة',correct:false}]} },
  { id:'adk2q47', unit:'u5', lesson:'u5l2', page:50, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'آداب العطاس تشبه آداب:',
    paragraph:'آداب العطاس والتثاؤب: تغطية الفم. (ص50)',
    image:'https://images.unsplash.com/photo-1581579188871-4e6f6a5e0c4e?w=600',
    options:[{text:'التثاؤب في تغطية الفم',correct:true},{text:'النوم',correct:false},{text:'الأكل',correct:false},{text:'اللعب',correct:false}],
    explanation:'آداب العطاس تشبه آداب التثاؤب في تغطية الفم للحفظ والنظافة.',
    goldenRule:'تغطية الفم = عند عطاس + عند تثاؤب = أدب مشترك.',
    feedbackQuestion:{question:'ماذا تشبه آداب العطاس؟',options:[{text:'آداب التثاؤب',correct:true},{text:'النوم',correct:false},{text:'الأكل',correct:false},{text:'اللعب',correct:false}]} },
  { id:'adk2q48', unit:'u5', lesson:'u5l2', page:50, type:'multipleChoice', bloom:'evaluate', difficulty:'hard',
    question:'لماذا يقول العاطس «الحمد لله» ولا يقول سبحان الله مثلاً؟',
    paragraph:'العاطس يقول: الحمد لله. (ص50)',
    options:[{text:'لأن العطاس نعمة تستحق الحمد والشكر',correct:true},{text:'لا سبب',correct:false},{text:'عادة',correct:false},{text:'لا أعرف',correct:false}],
    explanation:'العاطس يقول «الحمد لله» لأن العطاس نعمة تستحق الحمد والشكر على فرجها.',
    goldenRule:'الحمد لله = نعمة العطاس + شكر + فرج.',
    feedbackQuestion:{question:'لماذا الحمد لله عند العطاس؟',options:[{text:'لأنه نعمة تستحق الحمد',correct:true},{text:'لا سبب',correct:false},{text:'عادة',correct:false},{text:'لا أعرف',correct:false}]} },
  { id:'adk2q49', unit:'u5', lesson:'u5l2', page:50, type:'multipleChoice', bloom:'apply', difficulty:'medium',
    question:'إذا عطست في الصف وغطيت فمي وقلت الحمد لله، ولم يرد أحد، فماذا تفعل؟',
    paragraph:'إذا عطس ولم يرد عليه أحد، يقول لنفسه: يرحني الله. (ص50)',
    image:'https://images.unsplash.com/photo-1581579188871-4e6f6a5e0c4e?w=600',
    options:[{text:'أقول لنفسي: يرحني الله',correct:true},{text:'أصرخ',correct:false},{text:'أغضب',correct:false},{text:'أنصرف',correct:false}],
    explanation:'إذا عطست ولم يرد أحد، تقول لنفسك: «يرحمني الله ويصلحني ويهدني».',
    goldenRule:'عدم رد الناس = قول: يرحني الله + دعاء + رضا.',
    feedbackQuestion:{question:'ماذا تقول إذا عطست ولم يرد أحد؟',options:[{text:'يرحني الله',correct:true},{text:'أصرخ',correct:false},{text:'أغضب',correct:false},{text:'أنصرف',correct:false}]} },
  { id:'adk2q50', unit:'u5', lesson:'u5l2', page:50, type:'multipleChoice', bloom:'create', difficulty:'hard',
    question:'ركّب جملة فيها: تغطية + حمد + رد + دعاء النفس:',
    paragraph:'آداب العطاس: تغطية + حمد + رد + دعاء النفس. (ص50)',
    options:[
      {text:'أغطي فمي وأحمد الله ويرد الناس بيرحمك الله فإن لم يرد أحد قلت يرحني الله',correct:true},
      {text:'أنام وأنسى',correct:false},
      {text:'أصرخ',correct:false},
      {text:'أنصرف',correct:false},
    ],
    explanation:'الجملة: أغطي فمي وأحمد الله ويرد الناس بيرحمك الله فإن لم يرد أحد قلت يرحني الله.',
    goldenRule:'الجملة الكاملة: تغطية + حمد + رد + دعاء النفس.' },
];

export default ADHKAR_L2;