// التربية الإسلامية - الصف الثاني الابتدائي - الفصل الأول
// كتاب التوحيد — الوحدة الأولى: أسماء الله وصفاته
// 3 دروس: الله الواحد + الله الرحمن الرحيم + الله السميع البصير

export const TAWHEED_U1 = [
  { id:'tw1q1', unit:'tw1', lesson:'tw1l1', page:6, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'الله سبحانه وتعالى:',
    paragraph:'الله الواحد الذي لا شريك له. (ص6)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'واحد لا شريك له',correct:true},{text:'كثيرون',correct:false},{text:'اثنان',correct:false},{text:'ثلاثة',correct:false}],
    explanation:'الله واحد لا شريك له، لم يلد ولم يولد ولم يكن له كفواً أحد.',
    goldenRule:'الله = واحد + لا شريك + لا ولد + لا كفؤ.',
    feedbackQuestion:{question:'كم إله في الإسلام؟',options:[{text:'واحد',correct:true},{text:'اثنان',correct:false},{text:'ثلاثة',correct:false},{text:'كثيرون',correct:false}]} },
  { id:'tw1q2', unit:'tw1', lesson:'tw1l1', page:6, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'«قل هو الله أحد» سورة تُسمى:',
    paragraph:'قال تعالى: «قُلْ هُوَ اللَّهُ أَحَدٌ». (ص6)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'سورة الإخلاص',correct:true},{text:'سورة الفلق',correct:false},{text:'سورة الناس',correct:false},{text:'سورة الفاتحة',correct:false}],
    explanation:'سورة «قل هو الله أحد» هي سورة الإخلاص.',
    goldenRule:'الإخلاص = قل هو الله أحد + توحيد + لا شريك.',
    feedbackQuestion:{question:'ما اسم سورة «قل هو الله أحد»؟',options:[{text:'الإخلاص',correct:true},{text:'الفلق',correct:false},{text:'الناس',correct:false},{text:'الفاتحة',correct:false}]} },
  { id:'tw1q3', unit:'tw1', lesson:'tw1l1', page:7, type:'trueFalse', bloom:'understand', difficulty:'easy',
    question:'الله لم يلد ولم يولد.',
    paragraph:'قال تعالى: «لَمْ يَلِدْ وَلَمْ يُولَدْ». (ص7)',
    correctAnswer:true,
    explanation:'الله لم يلد ولم يولد — ليس له ولد ولا والد، فهو الأول بلا بداية.',
    goldenRule:'الله = لم يلد + لم يولد + لا والد + لا ولد.',
    feedbackQuestion:{question:'هل لله ولد؟',options:[{text:'لا، لم يلد ولم يولد',correct:true},{text:'نعم',correct:false},{text:'بعض الأحيان',correct:false},{text:'لا أعرف',correct:false}]} },
  { id:'tw1q4', unit:'tw1', lesson:'tw1l1', page:7, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'«ولم يكن له كفواً أحد» تعني:',
    paragraph:'قال تعالى: «وَلَمْ يَكُنْ لَهُ كُفُوًا أَحَدٌ». (ص7)',
    options:[{text:'لا مماثل له ولا شبيه',correct:true},{text:'له شبيه',correct:false},{text:'له نظير',correct:false},{text:'له ولد',correct:false}],
    explanation:'«ولم يكن له كفواً أحد» تعني لا مماثل له ولا شبيه ولا نظير.',
    goldenRule:'لا كفؤ لله = لا مماثل + لا شبيه + لا نظير + لا شريك.',
    feedbackQuestion:{question:'ماذا تعني «ولم يكن له كفواً أحد»؟',options:[{text:'لا مماثل ولا شبيه',correct:true},{text:'له شبيه',correct:false},{text:'له نظير',correct:false},{text:'له ولد',correct:false}]} },
  { id:'tw1q5', unit:'tw1', lesson:'tw1l1', page:8, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'«الله الصمد» تعني:',
    paragraph:'قال تعالى: «اللَّهُ الصَّمَدُ». (ص8)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'السيّد الذي يُقصد في الحوائج',correct:true},{text:'الذي يحتاج',correct:false},{text:'الذي ينام',correct:false},{text:'الذي يأكل',correct:false}],
    explanation:'«الصمد» تعني السيّد الذي يُقصد في الحوائج ولا يحتاج إلى أحد.',
    goldenRule:'الصمد = سيّد + مقصود + لا يحتاج + كامل.',
    feedbackQuestion:{question:'ماذا تعني «الصمد»؟',options:[{text:'السيّد المقصود في الحوائج',correct:true},{text:'الذي يحتاج',correct:false},{text:'الذي ينام',correct:false},{text:'الذي يأكل',correct:false}]} },
  { id:'tw1q6', unit:'tw1', lesson:'tw1l1', page:6, type:'ordering', bloom:'apply', difficulty:'medium',
    question:'رتّب آيات سورة الإخلاص:',
    paragraph:'سورة الإخلاص: قل هو الله أحد + الله الصمد + لم يلد ولم يولد + ولم يكن له كفواً أحد. (ص6-7)',
    items:['ولم يكن له كفواً أحد','قل هو الله أحد','لم يلد ولم يولد','الله الصمد'],
    correctOrder:[1,3,2,0],
    explanation:'ترتيب سورة الإخلاص: قل هو الله أحد ← الله الصمد ← لم يلد ولم يولد ← ولم يكن له كفواً أحد.',
    goldenRule:'الإخلاص = أحد ← الصمد ← لم يلد ← لا كفؤ.' },
  { id:'tw1q7', unit:'tw1', lesson:'tw1l1', page:8, type:'multipleChoice', bloom:'evaluate', difficulty:'hard',
    question:'لماذا نقرأ سورة الإخلاص كثيراً؟',
    paragraph:'سورة الإخلاص تعدل ثلث القرآن. (ص8)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'لأنها تعدل ثلث القرآن في الأجر',correct:true},{text:'لأنها قصيرة',correct:false},{text:'عادة',correct:false},{text:'لا سبب',correct:false}],
    explanation:'سورة الإخلاص تعدل ثلث القرآن في الأجر لأنها تتحدث عن توحيد الله.',
    goldenRule:'الإخلاص = ثلث القرآن + أجر + توحيد + بركة.',
    feedbackQuestion:{question:'بمَ تعدل سورة الإخلاص؟',options:[{text:'ثلث القرآن',correct:true},{text:'نصف',correct:false},{text:'ربع',correct:false},{text:'لا شيء',correct:false}]} },
  { id:'tw1q8', unit:'tw1', lesson:'tw1l1', page:7, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'«أحد» في سورة الإخلاص تعني:',
    paragraph:'قال تعالى: «قُلْ هُوَ اللَّهُ أَحَدٌ». (ص6)',
    options:[{text:'الواحد الذي لا ثاني له',correct:true},{text:'الرقم واحد',correct:false},{text:'أول الناس',correct:false},{text:'لا شيء',correct:false}],
    explanation:'«أحد» تعني الواحد الذي لا ثاني له ولا شريك معه.',
    goldenRule:'أحد = واحد + لا ثاني + لا شريك + لا مماثل.',
    feedbackQuestion:{question:'ماذا تعني «أحد»؟',options:[{text:'الواحد الذي لا ثاني له',correct:true},{text:'الرقم واحد',correct:false},{text:'أول الناس',correct:false},{text:'لا شيء',correct:false}]} },
  { id:'tw1q9', unit:'tw1', lesson:'tw1l1', page:6, type:'classify', bloom:'analyze', difficulty:'medium',
    question:'صنّف: من صفات الله أم من صفات المخلوقين؟',
    paragraph:'الله: أحد + الصمد + لم يلد. المخلوق: يحتاج + يأكل + ينام. (ص6-8)',
    categories:['صفات الله 🤲','صفات المخلوقين 👤'],
    items:[
      {text:'الأحدية',correct_category:0},{text:'الحاجة',correct_category:1},
      {text:'الصمدية',correct_category:0},{text:'النوم',correct_category:1},
      {text:'لم يلد ولم يولد',correct_category:0},{text:'الأكل',correct_category:1},
    ],
    explanation:'صفات الله: أحدية + صمدية + لم يلد. صفات المخلوق: حاجة + نوم + أكل.',
    goldenRule:'صفات الله كمال + صفات المخلوق نقص.' },
  { id:'tw1q10', unit:'tw1', lesson:'tw1l1', page:8, type:'fillBlank', bloom:'apply', difficulty:'easy',
    question:'أكمل الآية: «قل هو الله ___».',
    paragraph:'قال تعالى: «قُلْ هُوَ اللَّهُ أَحَدٌ». (ص6)',
    blanks:['أحد'],
    wordBank:['أحد','صمد','كبير','عظيم'],
    explanation:'الآية: «قل هو الله أحد».',
    goldenRule:'قل هو الله أحد.' },
  { id:'tw1q11', unit:'tw1', lesson:'tw1l2', page:10, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'«الرحمن الرحيم» من أسماء:',
    paragraph:'الله الرحمن الرحيم. (ص10)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'الله الحسنى',correct:true},{text:'الملائكة',correct:false},{text:'الأنبياء',correct:false},{text:'الناس',correct:false}],
    explanation:'«الرحمن الرحيم» من أسماء الله الحسنى.',
    goldenRule:'الرحمن الرحيم = أسماء الله الحسنى + رحمة + رأفة.',
    feedbackQuestion:{question:'لمن «الرحمن الرحيم»؟',options:[{text:'من أسماء الله',correct:true},{text:'الملائكة',correct:false},{text:'الأنبياء',correct:false},{text:'الناس',correct:false}]} },
  { id:'tw1q12', unit:'tw1', lesson:'tw1l2', page:10, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'«الرحمن» تعني:',
    paragraph:'الرحمن: ذو الرحمة الواسعة لجميع خلقه. (ص10)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'ذو الرحمة الواسعة لجميع خلقه',correct:true},{text:'الذي يحتاج',correct:false},{text:'الذي ينام',correct:false},{text:'لا شيء',correct:false}],
    explanation:'«الرحمن» تعني ذو الرحمة الواسعة لجميع خلقه مؤمنهم وكافرهم.',
    goldenRule:'الرحمن = رحمة واسعة + جميع الخلق + دنيا + رزق.',
    feedbackQuestion:{question:'ماذا تعني «الرحمن»؟',options:[{text:'ذو الرحمة الواسعة لجميع خلقه',correct:true},{text:'الذي يحتاج',correct:false},{text:'الذي ينام',correct:false},{text:'لا شيء',correct:false}]} },
  { id:'tw1q13', unit:'tw1', lesson:'tw1l2', page:10, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'«الرحيم» تعني:',
    paragraph:'الرحيم: رحيم بالمؤمنين خاصة. (ص10)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'رحيم بالمؤمنين خاصة',correct:true},{text:'بالجميع',correct:false},{text:'بالكفار',correct:false},{text:'لا شيء',correct:false}],
    explanation:'«الرحيم» تعني رحيم بالمؤمنين خاصة برحمته في الآخرة.',
    goldenRule:'الرحيم = رحمة للمؤمنين + آخرة + رضا + جنة.',
    feedbackQuestion:{question:'بمن «الرحيم»؟',options:[{text:'بالمؤمنين خاصة',correct:true},{text:'بالجميع',correct:false},{text:'بالكفار',correct:false},{text:'لا شيء',correct:false}]} },
  { id:'tw1q14', unit:'tw1', lesson:'tw1l2', page:11, type:'trueFalse', bloom:'understand', difficulty:'easy',
    question:'رحمة الله واسعة تشمل جميع خلقه في الدنيا.',
    paragraph:'الرحمن رحمته واسعة لجميع الخلق. (ص10)',
    correctAnswer:true,
    explanation:'رحمة الله واسعة تشمل جميع خلقه في الدنيا: المؤمن والكافر والإنسان والحيوان.',
    goldenRule:'رحمة الله = واسعة + جميع الخلق + دنيا + رزق.',
    feedbackQuestion:{question:'هل رحمة الله واسعة لجميع الخلق؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'بعض الأحيان',correct:false},{text:'لا أعرف',correct:false}]} },
  { id:'tw1q15', unit:'tw1', lesson:'tw1l2', page:11, type:'multipleChoice', bloom:'apply', difficulty:'medium',
    question:'إذا أصابك مرض، فتقول:',
    paragraph:'الله رحيم بعباده ويفرج الكروب. (ص11)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'اللهم ارحمني واشفني',correct:true},{text:'لا شيء',correct:false},{text:'أغضب',correct:false},{text:'أنصرف',correct:false}],
    explanation:'عند المرض تقول: اللهم ارحمني واشفني لأن الله رحيم بعباده.',
    goldenRule:'عند المرض = اللهم ارحمني + شفاء + رحمة + دعاء.',
    feedbackQuestion:{question:'ماذا تقول عند المرض؟',options:[{text:'اللهم ارحمني واشفني',correct:true},{text:'لا شيء',correct:false},{text:'أغضب',correct:false},{text:'أنصرف',correct:false}]} },
  { id:'tw1q16', unit:'tw1', lesson:'tw1l2', page:11, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'في كل صلاة نقرأ سورة الفاتحة وفيها:',
    paragraph:'في الفاتحة: «الرحمن الرحيم». (ص10)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'الرحمن الرحيم',correct:true},{text:'الله أحد',correct:false},{text:'الله الصمد',correct:false},{text:'لا شيء',correct:false}],
    explanation:'في كل صلاة نقرأ الفاتحة وفيها «الرحمن الرحيم» من أسماء الله.',
    goldenRule:'الفاتحة = الرحمن الرحيم + حمد + عبادة + توحيد.',
    feedbackQuestion:{question:'أي اسم من أسماء الله في الفاتحة؟',options:[{text:'الرحمن الرحيم',correct:true},{text:'الله أحد',correct:false},{text:'الله الصمد',correct:false},{text:'لا شيء',correct:false}]} },
  { id:'tw1q17', unit:'tw1', lesson:'tw1l3', page:14, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'«السميع» تعني:',
    paragraph:'الله السميع: يسمع كل شيء. (ص14)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'الذي يسمع كل شيء',correct:true},{text:'الذي يرى فقط',correct:false},{text:'الذي يأكل',correct:false},{text:'الذي ينام',correct:false}],
    explanation:'«السميع» تعني الذي يسمع كل شيء دقيقها وجليلها لا يخفى عليه شيء.',
    goldenRule:'السميع = يسمع كل شيء + دقيق + جليل + لا يخفى.',
    feedbackQuestion:{question:'ماذا تعني «السميع»؟',options:[{text:'الذي يسمع كل شيء',correct:true},{text:'الذي يرى فقط',correct:false},{text:'الذي يأكل',correct:false},{text:'الذي ينام',correct:false}]} },
  { id:'tw1q18', unit:'tw1', lesson:'tw1l3', page:14, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'«البصير» تعني:',
    paragraph:'الله البصير: يرى كل شيء. (ص14)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'الذي يرى كل شيء',correct:true},{text:'الذي يسمع فقط',correct:false},{text:'الذي يأكل',correct:false},{text:'الذي ينام',correct:false}],
    explanation:'«البصير» تعني الذي يرى كل شيء صغيراً كان أو كبيراً في الظلام والنور.',
    goldenRule:'البصير = يرى كل شيء + صغير + كبير + ظلام ونور.',
    feedbackQuestion:{question:'ماذا تعني «البصير»؟',options:[{text:'الذي يرى كل شيء',correct:true},{text:'الذي يسمع فقط',correct:false},{text:'الذي يأكل',correct:false},{text:'الذي ينام',correct:false}]} },
  { id:'tw1q19', unit:'tw1', lesson:'tw1l3', page:14, type:'trueFalse', bloom:'understand', difficulty:'easy',
    question:'الله يسمع ويرى كل شيء ولو كان في الظلام.',
    paragraph:'الله السميع البصير يسمع ويرى كل شيء. (ص14)',
    correctAnswer:true,
    explanation:'الله يسمع ويرى كل شيء ولو كان في الظلام أو في الصدر لا يخفى عليه شيء.',
    goldenRule:'الله = يسمع + يرى + في الظلام + في الصدر.',
    feedbackQuestion:{question:'هل يسمع الله ويرى في الظلام؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'بعض الأحيان',correct:false},{text:'لا أعرف',correct:false}]} },
  { id:'tw1q20', unit:'tw1', lesson:'tw1l3', page:15, type:'multipleChoice', bloom:'apply', difficulty:'medium',
    question:'إذا أردت أن تتكلم، فتذكر أن الله:',
    paragraph:'الله السميع يسمع كلامك فاحفظ لسانك. (ص15)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'يسمعك فلا تقول إلا خيراً',correct:true},{text:'لا يسمع',correct:false},{text:'ينام',correct:false},{text:'لا يبالي',correct:false}],
    explanation:'إذا أردت الكلام تذكر أن الله يسمعك فلا تقول إلا خيراً ولا تؤذي أحداً.',
    goldenRule:'الله يسمع = لا تقل إلا خيراً + احفظ لسان + أدب + مراقبة.',
    feedbackQuestion:{question:'ماذا تفعل قبل أن تتكلم؟',options:[{text:'أتذكر أن الله يسمع',correct:true},{text:'لا شيء',correct:false},{text:'أنام',correct:false},{text:'أنصرف',correct:false}]} },
  { id:'tw1q21', unit:'tw1', lesson:'tw1l3', page:15, type:'multipleChoice', bloom:'evaluate', difficulty:'hard',
    question:'لماذا نحفظ ألسنتنا ونتجنب الإيذاء؟',
    paragraph:'الله السميع البصير يسمع ويرى كل شيء. (ص14)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'لأن الله يسمع ويرى وسيحاسبنا',correct:true},{text:'عادة',correct:false},{text:'لا سبب',correct:false},{text:'مكروه',correct:false}],
    explanation:'نحفظ ألسنتنا ونتجنب الإيذاء لأن الله يسمع ويرى وسيحاسبنا على كل صغيرة وكبيرة.',
    goldenRule:'حفظ اللسان = مراقبة الله + حساب + أدب + رضا.',
    feedbackQuestion:{question:'لماذا نحفظ ألسنتنا؟',options:[{text:'لأن الله يسمع ويرى',correct:true},{text:'عادة',correct:false},{text:'لا سبب',correct:false},{text:'مكروه',correct:false}]} },
  { id:'tw1q22', unit:'tw1', lesson:'tw1l3', page:14, type:'classify', bloom:'analyze', difficulty:'medium',
    question:'صنّف: من أسماء الله أم لا؟',
    paragraph:'أسماء الله: السميع + البصير + الرحمن + الرحيم. (ص10-14)',
    categories:['من أسماء الله 🤲','ليست من أسماء الله ❌'],
    items:[
      {text:'السميع',correct_category:0},{text:'الصمد',correct_category:0},
      {text:'الرحمن',correct_category:0},{text:'النائم',correct_category:1},
      {text:'البصير',correct_category:0},{text:'الجاهل',correct_category:1},
    ],
    explanation:'أسماء الله: السميع + الصمد + الرحمن + البصير. النائم والجاهل ليست من صفاته.',
    goldenRule:'أسماء الله كلها كمال + حسنى + جمال.' },
  { id:'tw1q23', unit:'tw1', lesson:'tw1l3', page:15, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'مراقبة الله تعني:',
    paragraph:'أتذكر أن الله يسمع ويرى فأحسن العمل. (ص15)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'أن تتذكر أن الله يسمع ويرى فتحسن العمل',correct:true},{text:'الخوف',correct:false},{text:'الهروب',correct:false},{text:'لا شيء',correct:false}],
    explanation:'مراقبة الله تعني أن تتذكر أن الله يسمع ويرى فيحسن عملك ويسكت لسانه.',
    goldenRule:'المراقبة = تذكر + إحسان عمل + حفظ لسان + خوف.',
    feedbackQuestion:{question:'ما مراقبة الله؟',options:[{text:'تذكر أن الله يسمع ويرى',correct:true},{text:'الخوف',correct:false},{text:'الهروب',correct:false},{text:'لا شيء',correct:false}]} },
  { id:'tw1q24', unit:'tw1', lesson:'tw1l1', page:7, type:'multipleChoice', bloom:'create', difficulty:'hard',
    question:'ركّب جملة فيها: أحد + صمد + لم يلد:',
    paragraph:'سورة الإخلاص: أحد + الصمد + لم يلد. (ص6-7)',
    options:[
      {text:'الله أحد صمد لم يلد ولم يولد',correct:true},
      {text:'الله كثير',correct:false},
      {text:'الله يحتاج',correct:false},
      {text:'لا شيء',correct:false},
    ],
    explanation:'الجملة: الله أحد صمد لم يلد ولم يولد — من سورة الإخلاص.',
    goldenRule:'الجملة الكاملة: أحد + صمد + لم يلد.' },
  { id:'tw1q25', unit:'tw1', lesson:'tw1l2', page:11, type:'fillBlank', bloom:'apply', difficulty:'easy',
    question:'أكمل: «ال___ الرحيم» من أسماء الله.',
    paragraph:'الله الرحمن الرحيم. (ص10)',
    blanks:['الرحمن'],
    wordBank:['الرحمن','السميع','البصير','الصمد'],
    explanation:'«الرحمن الرحيم» من أسماء الله الحسنى.',
    goldenRule:'الرحمن الرحيم = أسماء الله الحسنى.' },
  { id:'tw1q26', unit:'tw1', lesson:'tw1l3', page:14, type:'multipleChoice', bloom:'evaluate', difficulty:'hard',
    question:'ما الجامع بين «السميع» و«البصير»؟',
    paragraph:'الله السميع البصير. (ص14)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'كلها تدل على إحاطة الله بكل شيء',correct:true},{text:'لا جامع',correct:false},{text:'كلها للنوم',correct:false},{text:'لا علاقة',correct:false}],
    explanation:'الجامع: كلها تدل على إحاطة الله بكل شيء سمعاً وبصراً لا يخفى عليه شيء.',
    goldenRule:'السميع + البصير = إحاطة + علم + لا يخفى.',
    feedbackQuestion:{question:'ما الجامع بين «السميع» و«البصير»؟',options:[{text:'إحاطة الله بكل شيء',correct:true},{text:'لا جامع',correct:false},{text:'النوم',correct:false},{text:'لا علاقة',correct:false}]} },
  { id:'tw1q27', unit:'tw1', lesson:'tw1l2', page:10, type:'matching', bloom:'understand', difficulty:'medium',
    question:'صِل كل اسم بمعناه:',
    paragraph:'الرحمن = رحمة واسعة، الرحيم = رحمة للمؤمنين. (ص10)',
    pairs:[
      {left:'الرحمن',right:'رحمة واسعة لجميع الخلق'},
      {left:'الرحيم',right:'رحمة للمؤمنين خاصة'},
      {left:'السميع',right:'يسمع كل شيء'},
      {left:'البصير',right:'يرى كل شيء'},
    ],
    explanation:'الرحمن = رحمة واسعة، الرحيم = رحمة للمؤمنين، السميع = يسمع، البصير = يرى.',
    goldenRule:'لكل اسم معناه: رحمن + رحيم + سميع + بصير.' },
  { id:'tw1q28', unit:'tw1', lesson:'tw1l1', page:8, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'الصمد يحتاج إلى:',
    paragraph:'الصمد: السيّد الذي يُقصد ولا يحتاج إلى أحد. (ص8)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'لا يحتاج إلى أحد',correct:true},{text:'يحتاج',correct:false},{text:'يأكل',correct:false},{text:'ينام',correct:false}],
    explanation:'الصمد هو السيّد الذي يُقصد في الحوائج ولا يحتاج إلى أحد.',
    goldenRule:'الصمد = لا يحتاج + مقصود + سيّد + كامل.',
    feedbackQuestion:{question:'هل الصمد يحتاج؟',options:[{text:'لا، لا يحتاج إلى أحد',correct:true},{text:'نعم',correct:false},{text:'بعض الأحيان',correct:false},{text:'لا أعرف',correct:false}]} },
  { id:'tw1q29', unit:'tw1', lesson:'tw1l3', page:15, type:'trueFalse', bloom:'apply', difficulty:'medium',
    question:'إذا عملت عملاً في الخلاء وحده، فالله يراك.',
    paragraph:'الله البصير يرى كل شيء ولو في الخلاء. (ص14)',
    correctAnswer:true,
    explanation:'إذا عملت عملاً في الخلاء وحده فالله يراك لأنه البصير الذي يرى كل شيء.',
    goldenRule:'الله البصير = يرى في الخلاء + لا يخفى عليه شيء + مراقبة.',
    feedbackQuestion:{question:'هل الله يراك إذا كنت وحيداً؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'بعض الأحيان',correct:false},{text:'لا أعرف',correct:false}]} },
  { id:'tw1q30', unit:'tw1', lesson:'tw1l2', page:11, type:'multipleChoice', bloom:'create', difficulty:'hard',
    question:'ركّب جملة فيها: رحمن + رحيم + سميع + بصير:',
    paragraph:'أسماء الله: الرحمن الرحيم + السميع البصير. (ص10-14)',
    options:[
      {text:'الله الرحمن الرحيم السميع البصير',correct:true},
      {text:'الله كثير',correct:false},
      {text:'الله يحتاج',correct:false},
      {text:'لا شيء',correct:false},
    ],
    explanation:'الجملة: الله الرحمن الرحيم السميع البصير — أسماء الله الحسنى.',
    goldenRule:'الجملة الكاملة: رحمن + رحيم + سميع + بصير.' },
];

export default TAWHEED_U1;