// التربية الإسلامية - الصف الثاني الابتدائي - الفصل الأول
// الوحدة الأولى: الآداب | الوحدة الثانية: الأذكار والأدعية
import { ISLAMIC_EXTRA_1 } from './islamicGrade2S1Bank_Extra';

export const META = {
  title: 'بنك أسئلة التربية الإسلامية',
  subject: 'التربية الإسلامية',
  grade: 'الصف الثاني الابتدائي',
  term: 'الفصل الأول',
  publisher: 'وزارة التعليم - المملكة العربية السعودية',
  book: 'التربية الإسلامية 1447هـ / 2025م',
};

export const UNITS = [
  {
    id: 'unit1',
    title: 'الوحدة الأولى: الآداب',
    color: '#0891b2',
    icon: '📖',
    lessons: [
      { id: 'u1l1', title: 'الدرس الأول: الآداب (1)', page: 34, unitId: 'unit1' },
      { id: 'u1l2', title: 'الدرس الثاني: الآداب (2)', page: 38, unitId: 'unit1' },
      { id: 'u1l3', title: 'الدرس الثالث: الآداب (3) — مساعدة المحتاجين', page: 42, unitId: 'unit1' },
      { id: 'u1l4', title: 'الدرس الرابع: آداب الجار', page: 43, unitId: 'unit1' },
    ],
  },
  {
    id: 'unit2',
    title: 'الوحدة الثانية: الأذكار والأدعية',
    color: '#059669',
    icon: '🤲',
    lessons: [
      { id: 'u2l1', title: 'الدرس الرابع: أذكار الصباح والمساء', page: 46, unitId: 'unit2' },
      { id: 'u2l2', title: 'الدرس الخامس: أذكار العطاس والنوم', page: 50, unitId: 'unit2' },
    ],
  },
  {
    id: 'unit3',
    title: 'الوحدة الثالثة: المحافظة على الممتلكات',
    color: '#d97706',
    icon: '🏫',
    lessons: [
      { id: 'u3l1', title: 'الدرس الثاني عشر: المحافظة على الممتلكات العامة', page: 82, unitId: 'unit3' },
    ],
  },
];

export const BLOOM_LABELS = {
  remember: 'تذكُّر', understand: 'فهم', apply: 'تطبيق',
  analyze: 'تحليل', create: 'تركيب', evaluate: 'تقويم',
};
export const DIFFICULTY_LABELS = { easy: 'سهل', medium: 'متوسط', hard: 'صعب' };

// ─── وحدة 1 | درس 1: الآداب (1) ──────────────────────────────────────────
const u1l1Qs = [
  {
    id:'u1l1q1', unit:'unit1', lesson:'u1l1', page:34, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'علّمنا الإسلامُ أن نُساعد المحتاجين والضعفاء، فيشمل ذلك مساعدة:',
    paragraph:'عَلَّمَني الإسلامُ أن أُساعِدَ المُحتاجِين والضُّعَفاء. (ص42)',
    options:[
      {text:'المريض والكبير والكفيف',correct:true},
      {text:'الأقوياء فقط',correct:false},
      {text:'الأصدقاء فقط',correct:false},
      {text:'لا أحد',correct:false},
    ],
    explanation:'الإسلام يأمرنا بمساعدة جميع المحتاجين: المريض والكبير والكفيف وغيرهم.',
    goldenRule:'ساعد المريض والكبير والكفيف — هذا ما علّمنا إياه الإسلام.',
    feedbackQuestion:{question:'من يشمل واجب المساعدة في الإسلام؟',options:[{text:'جميع المحتاجين والضعفاء',correct:true},{text:'الأصدقاء فقط',correct:false},{text:'الجيران فقط',correct:false},{text:'لا أحد',correct:false}]},
  },
  {
    id:'u1l1q2', unit:'unit1', lesson:'u1l1', page:42, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'قال رسول الله ﷺ: "واللهُ في عَون العبد ما كان العبدُ في عون أخيه".',
    paragraph:'قالَ رسولُ الله ﷺ: «وَاللهُ فِي عَوْنِ الْعَبْدِ مَا كَانَ الْعَبْدُ فِي عَوْنِ أَخِيهِ». (ص42)',
    correctAnswer:true,
    explanation:'هذا حديث صحيح رواه مسلم (2699)، ومعناه أن الله يعين من يعين إخوانه.',
    goldenRule:'من أعان أخاه أعانه الله — هذا وعد النبي ﷺ.',
    feedbackQuestion:{question:'ما المعنى الصحيح للحديث: "الله في عون العبد ما كان العبد في عون أخيه"؟',options:[{text:'من أعان أخاه أعانه الله',correct:true},{text:'من صلّى أعانه الله',correct:false},{text:'من صام نصره الله',correct:false},{text:'من دعا استجاب الله',correct:false}]},
  },
  {
    id:'u1l1q3', unit:'unit1', lesson:'u1l1', page:42, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف: من نساعده حين يحتاج؟',
    paragraph:'أُساعدُ المريض / أُساعدُ الكبير / أُساعدُ الكفيف. (ص42)',
    categories:['نساعده ✅','لا نتركه وحده ✅'],
    items:[
      {text:'المريض',correct_category:0},
      {text:'الكفيف',correct_category:0},
      {text:'الكبير في السن',correct_category:0},
      {text:'المحتاج للمساعدة',correct_category:1},
    ],
    explanation:'الجميع يحتاج مساعدتنا: المريض، الكفيف، الكبير، وكل محتاج.',
    goldenRule:'لا تتركنّ محتاجاً بلا مساعدة — الله في عون العبد ما كان في عون أخيه.',
  },
  {
    id:'u1l1q4', unit:'unit1', lesson:'u1l1', page:42, type:'trueFalse',
    bloom:'apply', difficulty:'easy',
    question:'مساعدة الضعفاء والمحتاجين من أخلاق الإسلام الحسنة.',
    paragraph:'عَلَّمَني الإسلامُ أن أُساعِدَ المُحتاجِين والضُّعَفاء. (ص42)',
    correctAnswer:true,
    explanation:'مساعدة المحتاجين خُلُق إسلامي كريم دعا إليه النبي ﷺ.',
    goldenRule:'مساعدة المحتاجين من صميم الأخلاق الإسلامية.',
    feedbackQuestion:{question:'ما صفة الشخص الذي يساعد الضعفاء؟',options:[{text:'مسلم حسن الأخلاق',correct:true},{text:'مسلم يبحث عن المكافأة',correct:false},{text:'شخص لا يؤمن',correct:false},{text:'شخص متعجرف',correct:false}]},
  },
  {
    id:'u1l1q5', unit:'unit1', lesson:'u1l1', page:42, type:'ordering',
    bloom:'apply', difficulty:'medium',
    question:'رتّب خطوات مساعدة شخص يحمل أشياءً ثقيلة:',
    paragraph:'وَجَدتَّ أخاكَ يَحملُ أشياءَ ثقيلةً لِيُدخِلَها إلى البَيت، فماذا تَفعَل؟ (ص44)',
    items:['اسأله إن كان يحتاج مساعدة','ضع الأشياء الثقيلة في مكانها','اقترب منه بهدوء','ساعده في حملها'],
    correctOrder:[2,0,3,1],
    explanation:'الخطوات: اقترب ← اسأله ← ساعد ← ضع في مكانها.',
    goldenRule:'بادر بالمساعدة بلا تردد — هذا ما يريده منك ربك.',
  },
  {
    id:'u1l1q6', unit:'unit1', lesson:'u1l1', page:44, type:'multipleChoice',
    bloom:'evaluate', difficulty:'medium',
    question:'أزور المريض من أجل (اختر الهدف الصحيح):',
    paragraph:'أنا أزورُ المريضَ من أجلِ: إدخالِ السرورِ عليهِ والدعاءِ له والتسلية. (ص44)',
    options:[
      {text:'إدخال السرور عليه والدعاء له',correct:true},
      {text:'إضاعة الوقت والتسلية فقط',correct:false},
      {text:'رؤية ما يعانيه فقط',correct:false},
      {text:'طلب شيء منه',correct:false},
    ],
    explanation:'نزور المريض لإدخال السرور ودعائه بالشفاء، لا لإضاعة وقته.',
    goldenRule:'زيارة المريض = سرور + دعاء + تخفيف — لا إضاعة وقت.',
    feedbackQuestion:{question:'ما الهدف الأساسي من زيارة المريض؟',options:[{text:'إدخال السرور والدعاء له بالشفاء',correct:true},{text:'إضاعة الوقت',correct:false},{text:'الفضول لرؤيته',correct:false},{text:'أخذ شيء منه',correct:false}]},
  },
  {
    id:'u1l1q7', unit:'unit1', lesson:'u1l1', page:44, type:'matching',
    bloom:'understand', difficulty:'easy',
    question:'صِل سبب زيارة المريض بنتيجته:',
    paragraph:'أصِلُ كلَّ عبارةٍ من العمود (أ) بما يُناسِبُها من العمود (ب). (ص44)',
    pairs:[
      {left:'زيارة المريض',right:'من أخلاق المسلمين'},
      {left:'الاطلاع على أسرار الجيران',right:'لا يحبه الله'},
      {left:'أحب الناس إلى الله',right:'من صفات المؤمنين'},
      {left:'الإحسان إلى الجار',right:'أنفعهم للناس'},
    ],
    explanation:'زيارة المريض من أخلاق المسلمين. الاطلاع على الأسرار لا يحبه الله. أحب الناس من صفات المؤمنين. الإحسان للجار ينفع الناس.',
    goldenRule:'المسلم يزور المريض ويحسن للجار ويتجنب التجسس على الأسرار.',
  },
  {
    id:'u1l1q8', unit:'unit1', lesson:'u1l1', page:44, type:'trueFalse',
    bloom:'analyze', difficulty:'medium',
    question:'إضاعة الوقت عند المريض نوع من المساعدة المرفوضة.',
    paragraph:'أنا أزورُ المريضَ من أجلِ إدخالِ السرورِ والدعاء له، وليس إضاعة الوقت والتسلية. (ص44)',
    correctAnswer:true,
    explanation:'إضاعة وقت المريض تُرهقه، لذا يجب أن تكون الزيارة قصيرة هادفة.',
    goldenRule:'الزيارة المفيدة = سرور + دعاء + اختصار — لا إطالة.',
    feedbackQuestion:{question:'كيف تكون الزيارة المثالية للمريض؟',options:[{text:'قصيرة مع الدعاء وإدخال السرور',correct:true},{text:'طويلة للحديث عن كل شيء',correct:false},{text:'لا نزوره',correct:false},{text:'بلا هدف',correct:false}]},
  },
];

// ─── وحدة 1 | درس 2: الآداب (2) ──────────────────────────────────────────
const u1l2Qs = [
  {
    id:'u1l2q1', unit:'unit1', lesson:'u1l2', page:38, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'عندما علمتُ أن خالتي رُزقت بمولود، التصرف الأفضل هو:',
    paragraph:'إذا عَلِمتُ أنَّ خالتي رُزِقَت بِمَولودٍ: أ) أزورُها أنا وأُمِّي وأُهَنِّئَها. (ص41)',
    options:[
      {text:'أزورها أنا وأمي وأهنئها',correct:true},
      {text:'أفضّل عدم الذهاب',correct:false},
      {text:'أبعث لها رسالة فقط',correct:false},
      {text:'لا أفعل شيئاً',correct:false},
    ],
    explanation:'التهنئة بالمولود سنّة، وتكون بالزيارة والتهنئة الشخصية.',
    goldenRule:'التهنئة بالمولود: زيارة + تهنئة + دعاء بالبركة.',
    feedbackQuestion:{question:'ما الواجب عند سماع خبر مولود جديد؟',options:[{text:'زيارة الأسرة وتهنئتهم',correct:true},{text:'تجاهل الخبر',correct:false},{text:'الانتظار لحين كبر المولود',correct:false},{text:'إرسال هدية فقط',correct:false}]},
  },
  {
    id:'u1l2q2', unit:'unit1', lesson:'u1l2', page:41, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'يجب أن أحافظ على المدرسة وأشارك الأهل والأصدقاء في الأعمال.',
    paragraph:'أُحافِظُ على المدرسةِ. أُشارِكُ الأهلَ والأصدقاءَ في الأعمال وأُحسِنُ إليهم. (ص41)',
    correctAnswer:true,
    explanation:'المحافظة على المدرسة والتعاون مع الأهل والأصدقاء من صميم التربية الإسلامية.',
    goldenRule:'حافظ على مدرستك وشارك أهلك وأصدقاءك في الأعمال.',
    feedbackQuestion:{question:'ما واجبي تجاه المدرسة؟',options:[{text:'المحافظة عليها وعدم إتلافها',correct:true},{text:'إتلاف ما فيها',correct:false},{text:'أخذ أغراضها',correct:false},{text:'لا يوجد واجب',correct:false}]},
  },
  {
    id:'u1l2q3', unit:'unit1', lesson:'u1l2', page:40, type:'multipleChoice',
    bloom:'apply', difficulty:'medium',
    question:'عند مرض أحد إخواني في المنزل، أتجنّب:',
    paragraph:'لا أقترِبُ منه إذا كان مَرَضُه مُعدياً. أتجنَّبُ استِخدامَ أدواتِه. (ص40)',
    options:[
      {text:'استخدام أدواته والاقتراب منه إن كان مرضه معدياً',correct:true},
      {text:'الدعاء له بالشفاء',correct:false},
      {text:'مساعدته في حدود الأمان',correct:false},
      {text:'تذكيره بمواعيد الدواء',correct:false},
    ],
    explanation:'إذا كان المرض معدياً نتجنب الاقتراب واستخدام الأدوات لحماية أنفسنا.',
    goldenRule:'المرض المعدي: ابتعد عن الأدوات والاقتراب — ادعُ من بعيد.',
    feedbackQuestion:{question:'ما الذي نتجنبه عند مرض أخينا بمرض معدٍ؟',options:[{text:'استخدام أدواته والاقتراب منه',correct:true},{text:'الدعاء له',correct:false},{text:'مساعدته',correct:false},{text:'إخبار الأهل',correct:false}]},
  },
  {
    id:'u1l2q4', unit:'unit1', lesson:'u1l2', page:40, type:'ordering',
    bloom:'apply', difficulty:'medium',
    question:'رتّب التصرفات الصحيحة حين يمرض أحد في المنزل:',
    paragraph:'أُساعِدُه ولا أُزعِجُه. وأُذَكِّرُه بموعد الدواء. أدعو له بالشفاء. (ص40)',
    items:['أدعو له بالشفاء','أخبر والديّ بمرضه','أساعده ولا أزعجه','أذكّره بموعد الدواء'],
    correctOrder:[1,2,3,0],
    explanation:'الترتيب: إخبار الوالدين ← المساعدة دون إزعاج ← تذكير الدواء ← الدعاء.',
    goldenRule:'عند مرض أخيك: أخبر الأهل ← ساعد ← ذكّر بالدواء ← ادعُ له.',
  },
  {
    id:'u1l2q5', unit:'unit1', lesson:'u1l2', page:40, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'من الواجب تذكير المريض بمواعيد الدواء.',
    paragraph:'أُذَكِّرُه بِموعِدِ الدَّواء. (ص40)',
    correctAnswer:true,
    explanation:'تذكير المريض بمواعيد الدواء مساعدة مهمة تُعجّل شفاءه.',
    goldenRule:'ذكّر المريض بمواعيد دوائه — هذا من الإحسان إليه.',
    feedbackQuestion:{question:'لماذا نذكّر المريض بموعد الدواء؟',options:[{text:'لأنه قد ينسى وهو مريض',correct:true},{text:'لأننا مسؤولون عن شرائه',correct:false},{text:'لأن الدواء خطير',correct:false},{text:'لإزعاجه',correct:false}]},
  },
  {
    id:'u1l2q6', unit:'unit1', lesson:'u1l2', page:40, type:'fillBlank',
    bloom:'remember', difficulty:'easy',
    question:'أكمل: "أُساعِدُه ولا ___ ، وأتجنَّبُ ___ أدواتِه".',
    paragraph:'أُساعِدُه ولا أُزعِجُه. وأتجنَّبُ استِخدامَ أدواتِه. (ص40)',
    blanks:['أُزعِجُه','استخدام'],
    wordBank:['أُزعِجُه','استخدام','أهنئه','ترك'],
    explanation:'نساعد المريض دون إزعاجه، ونتجنب استخدام أدواته تحاشياً للعدوى.',
    goldenRule:'ساعد + لا تُزعج + لا تستخدم أدواته — مع الدعاء دائماً.',
  },
  {
    id:'u1l2q7', unit:'unit1', lesson:'u1l2', page:40, type:'multipleChoice',
    bloom:'analyze', difficulty:'medium',
    question:'أزور المريض لأكسب الأجر من الله وأدخل السرور عليه وأُخفّف عنه، ويُسمّى ذلك:',
    paragraph:'نقومُ بزيارةِ المريضِ لِكَسبِ الأجرِ من اللهِ وإدخالِ السرورِ إلى نفسِهِ والتخفيفِ عنه. (ص44)',
    options:[
      {text:'عيادة المريض',correct:true},
      {text:'التجسس عليه',correct:false},
      {text:'التسلية',correct:false},
      {text:'إضاعة الوقت',correct:false},
    ],
    explanation:'زيارة المريض تُسمّى "العيادة"، وهي سنّة نبوية للأجر وإدخال السرور.',
    goldenRule:'عيادة المريض = أجر من الله + سرور + تخفيف.',
    feedbackQuestion:{question:'ما اسم زيارة المريض في الإسلام؟',options:[{text:'العيادة',correct:true},{text:'الزيارة العادية',correct:false},{text:'التسلية',correct:false},{text:'الاطلاع',correct:false}]},
  },
  {
    id:'u1l2q8', unit:'unit1', lesson:'u1l2', page:40, type:'trueFalse',
    bloom:'evaluate', difficulty:'medium',
    question:'يجوز الإطالة في زيارة المريض إذا كان يستمتع بالحديث.',
    paragraph:'لا أُطيلُ الجلوسَ عنده حتى لا أُرهِقَه. (تمارين ص40)',
    correctAnswer:false,
    explanation:'حتى لو أبدى المريض استمتاعه، يجب عدم الإطالة لأنها تُرهقه.',
    goldenRule:'الزيارة القصيرة المفيدة أفضل من الطويلة المُرهِقة.',
    feedbackQuestion:{question:'لماذا لا نطيل الجلوس عند المريض؟',options:[{text:'حتى لا نُرهقه',correct:true},{text:'لأننا مشغولون',correct:false},{text:'لأن الزيارة ليست واجبة',correct:false},{text:'لا سبب',correct:false}]},
  },
];

// ─── وحدة 1 | درس 3: الآداب (3) ──────────────────────────────────────────
const u1l3Qs = [
  {
    id:'u1l3q1', unit:'unit1', lesson:'u1l3', page:43, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'قال رسول الله ﷺ: "مَن كان يؤمن بالله واليوم الآخِر فلا يُؤذِ":',
    paragraph:'قالَ رسولُ الله ﷺ: «مَن كانَ يُؤمِنُ بِاللهِ واليومِ الآخِرِ فَلَا يُؤذِ جارَهُ». (ص43)',
    options:[
      {text:'جارَه',correct:true},
      {text:'صديقه',correct:false},
      {text:'أخاه',correct:false},
      {text:'معلمه',correct:false},
    ],
    explanation:'الحديث رواه البخاري (5672): من آمن بالله لا يؤذي جاره.',
    goldenRule:'الإيمان الصحيح يمنع من إيذاء الجار — فلا تؤذِ جارك أبداً.',
    feedbackQuestion:{question:'ما الذي يمنعه الإيمان بالله واليوم الآخر؟',options:[{text:'إيذاء الجار',correct:true},{text:'الصلاة',correct:false},{text:'الصيام',correct:false},{text:'الزكاة',correct:false}]},
  },
  {
    id:'u1l3q2', unit:'unit1', lesson:'u1l3', page:43, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'المسلم يعود المريض ويدعو له بالشفاء.',
    paragraph:'المُسلِمُ يَعودُ المَريضَ ويَدعو له. (ص43)',
    correctAnswer:true,
    explanation:'عيادة المريض والدعاء له من حقوق المسلم على أخيه المسلم.',
    goldenRule:'عيادة المريض والدعاء له من حقوق المسلم الواجبة.',
    feedbackQuestion:{question:'ما واجب المسلم تجاه أخيه المريض؟',options:[{text:'عيادته والدعاء له',correct:true},{text:'تجاهله',correct:false},{text:'زيارته لإضاعة وقته',correct:false},{text:'تركه وحده',correct:false}]},
  },
  {
    id:'u1l3q3', unit:'unit1', lesson:'u1l3', page:43, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف هذه التصرفات: تصرف جيد مع الجار أم تصرف سيء؟',
    paragraph:'أُحَدِّدُ الصوابَ والخطأَ في الصورِ التالية. أُحسِنُ إلى الجيرانِ ولا أَفعَلُ ما يُؤذيهم. (ص43)',
    categories:['تصرف جيد مع الجار ✅','تصرف سيء مع الجار ❌'],
    items:[
      {text:'إحسان الجيران وعدم أذاهم',correct_category:0},
      {text:'الكتابة على جدران الجيران',correct_category:1},
      {text:'إزالة الأذى عن طريق الجيران',correct_category:0},
      {text:'إزعاج الجار بالضوضاء',correct_category:1},
    ],
    explanation:'الإحسان وإزالة الأذى: تصرف جيد. الكتابة والإزعاج: تصرف سيء.',
    goldenRule:'أحسن لجارك ولا تؤذِه — هذا أمر الله ورسوله.',
  },
  {
    id:'u1l3q4', unit:'unit1', lesson:'u1l3', page:43, type:'ordering',
    bloom:'apply', difficulty:'medium',
    question:'رتّب واجباتي تجاه الجار من الأهم للمهم:',
    paragraph:'أُحسِنُ إلى الجيرانِ، ولا أَفعَلُ ما يُؤذيهم. (ص43)',
    items:['لا أتجسس على أسراره','أحسن إليه وأنفعه','لا أؤذيه بأي شكل','أساعده عند الحاجة'],
    correctOrder:[2,0,3,1],
    explanation:'الأولوية: لا أؤذيه ← لا أتجسس ← أساعده ← أحسن إليه.',
    goldenRule:'أولى واجبات الجار: لا أذى ← لا تجسس ← مساعدة ← إحسان.',
  },
  {
    id:'u1l3q5', unit:'unit1', lesson:'u1l3', page:43, type:'trueFalse',
    bloom:'analyze', difficulty:'medium',
    question:'الاطلاع على أسرار الجيران لا يحبه الله.',
    paragraph:'الاطلاعُ على أسرارِ الجيرانِ: لا يُحِبُّه الله. (ص44)',
    correctAnswer:true,
    explanation:'التجسس على أسرار الجيران محرّم لأنه يؤذيهم ويخلّ بالثقة.',
    goldenRule:'الاطلاع على أسرار الجيران لا يحبه الله — احفظ خصوصيتهم.',
    feedbackQuestion:{question:'ما حكم الاطلاع على أسرار الجيران؟',options:[{text:'لا يحبه الله',correct:true},{text:'مباح',correct:false},{text:'مستحسن',correct:false},{text:'واجب',correct:false}]},
  },
  {
    id:'u1l3q6', unit:'unit1', lesson:'u1l3', page:44, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'"أحبُّ الناسِ إلى الله" وصفٌ لمن يكون؟',
    paragraph:'أحبُّ الناسِ إلى اللهِ من صفاتِ المؤمنين. الإحسانُ إلى الجارِ أَنفَعُهم للناسِ. (ص44)',
    options:[
      {text:'أنفعهم للناس',correct:true},
      {text:'أكثرهم مالاً',correct:false},
      {text:'أقواهم جسداً',correct:false},
      {text:'أكبرهم سناً',correct:false},
    ],
    explanation:'أحب الناس إلى الله أنفعهم للناس — كما دل عليه الحديث النبوي.',
    goldenRule:'أحب الناس إلى الله أنفعهم للناس — كُن نافعاً لمن حولك.',
    feedbackQuestion:{question:'من هو أحب الناس إلى الله؟',options:[{text:'أنفعهم للناس',correct:true},{text:'أكثرهم صياماً فقط',correct:false},{text:'أكثرهم مالاً',correct:false},{text:'أقلهم كلاماً',correct:false}]},
  },
  {
    id:'u1l3q7', unit:'unit1', lesson:'u1l3', page:44, type:'matching',
    bloom:'understand', difficulty:'medium',
    question:'صِل الصفة بالوصف المناسب:',
    paragraph:'أُصِلُ كلَّ عبارةٍ من العمود أ بما يُناسِبُها من العمود ب. (ص44)',
    pairs:[
      {left:'زيارة المريض',right:'من أخلاق المسلمين'},
      {left:'الاطلاع على الأسرار',right:'لا يُحبه الله'},
      {left:'أحب الناس إلى الله',right:'أنفعهم للناس'},
      {left:'الإحسان إلى الجار',right:'من صفات المؤمنين'},
    ],
    explanation:'زيارة المريض = أخلاق المسلمين. الأسرار = لا يحبه الله. أحبهم إلى الله = أنفعهم. الإحسان للجار = صفة المؤمنين.',
    goldenRule:'المسلم الحق: يعود المريض + يحترم خصوصية الجار + ينفع الناس.',
  },
  {
    id:'u1l3q8', unit:'unit1', lesson:'u1l3', page:44, type:'trueFalse',
    bloom:'evaluate', difficulty:'medium',
    question:'وجدتَ أخاك يحمل أشياء ثقيلة إلى البيت، يجب عليك مساعدته.',
    paragraph:'وَجَدتَّ أخاكَ يَحمِلُ أشياءً ثقيلةً لِيُدخِلَها إلى البيت، فماذا تَفعَل؟ (ص44)',
    correctAnswer:true,
    explanation:'مساعدة الأخ الذي يحتاج واجب إسلامي وأخلاقي.',
    goldenRule:'مساعدة أخيك عند الحاجة واجب لا يُؤجّل.',
    feedbackQuestion:{question:'ما التصرف الصحيح حين ترى أخاك يحمل شيئاً ثقيلاً؟',options:[{text:'تبادر بمساعدته',correct:true},{text:'تتركه يتعب وحده',correct:false},{text:'تتفرج عليه',correct:false},{text:'تطلب منه الاستراحة',correct:false}]},
  },
];

// ─── وحدة 1 | درس 4: آداب الجار الإضافية ─────────────────────────────────
const u1l4Qs = [
  {
    id:'u1l4q1', unit:'unit1', lesson:'u1l4', page:43, type:'multipleChoice',
    bloom:'understand', difficulty:'easy',
    question:'تعليم الإسلام في التعامل مع الجار يشمل:',
    paragraph:'الإسلامُ يُعلِّمُني أن أُحسِنَ إلى الجيرانِ ولا أَفعَلَ ما يُؤذيهم. (ص43)',
    options:[
      {text:'الإحسان إليه وعدم إيذائه',correct:true},
      {text:'التجسس على أسراره',correct:false},
      {text:'تجاهله تماماً',correct:false},
      {text:'إيذائه أحياناً',correct:false},
    ],
    explanation:'الإسلام يأمر بالإحسان للجار وعدم إيذائه بأي صورة.',
    goldenRule:'مع جارك: إحسان + لا أذى — هذا أمر الإسلام.',
    feedbackQuestion:{question:'ما موقف الإسلام من إيذاء الجار؟',options:[{text:'منهيٌّ عنه تماماً',correct:true},{text:'مباح في بعض الأحيان',correct:false},{text:'لا يهم',correct:false},{text:'مسموح به إذا كان بسيطاً',correct:false}]},
  },
  {
    id:'u1l4q2', unit:'unit1', lesson:'u1l4', page:43, type:'trueFalse',
    bloom:'apply', difficulty:'easy',
    question:'يجوز رمي القمامة أمام بيت الجار لأنه أمر بسيط.',
    paragraph:'لا أَفعَلُ ما يُؤذي جيرانِي مِن رَمي القُمامة أمامَ بُيوتِهم. (تمارين ص43)',
    correctAnswer:false,
    explanation:'رمي القمامة أمام بيت الجار إيذاء له، وقد نهى عنه الإسلام.',
    goldenRule:'لا تُلقِ القمامة أمام بيت جارك — هذا إيذاء محرّم.',
    feedbackQuestion:{question:'ما حكم رمي القمامة أمام بيت الجار؟',options:[{text:'محرّم لأنه إيذاء',correct:true},{text:'مباح',correct:false},{text:'مكروه فقط',correct:false},{text:'لا حكم له',correct:false}]},
  },
  {
    id:'u1l4q3', unit:'unit1', lesson:'u1l4', page:43, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف: التصرفات الجيدة والسيئة مع الجيران:',
    paragraph:'أُحَدِّدُ الصوابَ والخطأَ في الصورِ التالية مع الجيران. (ص43)',
    categories:['صواب مع الجار ✅','خطأ مع الجار ❌'],
    items:[
      {text:'مساعدة الجار المريض',correct_category:0},
      {text:'الكتابة على جدران الجيران',correct_category:1},
      {text:'استقبال الجار بوجه طلق',correct_category:0},
      {text:'إيذاء حيوانات الجيران',correct_category:1},
    ],
    explanation:'صواب: مساعدة الجار والابتسام له. خطأ: الكتابة على جدرانه وإيذاء حيواناته.',
    goldenRule:'مع جارك: ابتسم وساعده + لا تكتب على جدرانه ولا تؤذِ حيواناته.',
  },
  {
    id:'u1l4q4', unit:'unit1', lesson:'u1l4', page:43, type:'multipleChoice',
    bloom:'evaluate', difficulty:'medium',
    question:'أفضل نصيحة لمن يوقف سيارته في مواقف ذوي الإعاقة:',
    paragraph:'وَجِّه نصيحةً لمَن يُوقِفُ سيارتَه في المَواقِفِ المُخَصَّصةِ لذوي الإعاقة. (ص84)',
    options:[
      {text:'هذا المكان مخصص لذوي الإعاقة، أرجو الالتزام بالأنظمة',correct:true},
      {text:'لا أفعل شيئاً',correct:false},
      {text:'أضرب السيارة',correct:false},
      {text:'أتجاهل الأمر',correct:false},
    ],
    explanation:'ننصح برفق: المواقف المخصصة لذوي الإعاقة حق لهم، ويجب احترام الأنظمة.',
    goldenRule:'مواقف ذوي الإعاقة حق خاص بهم — لا تعتدِ عليها.',
    feedbackQuestion:{question:'لماذا لا يجوز الوقوف في مواقف ذوي الإعاقة؟',options:[{text:'لأنها مخصصة لهم وهم أكثر حاجة',correct:true},{text:'لأنها أقرب للمدخل',correct:false},{text:'لا سبب واضح',correct:false},{text:'لأن الشرطة ستغرّمنا',correct:false}]},
  },
  {
    id:'u1l4q5', unit:'unit1', lesson:'u1l4', page:43, type:'trueFalse',
    bloom:'remember', difficulty:'easy',
    question:'حديث النبي ﷺ: "من كان يؤمن بالله واليوم الآخر فلا يؤذِ جاره" رواه البخاري.',
    paragraph:'قالَ رسولُ الله ﷺ: «مَن كانَ يُؤمِنُ بِاللهِ واليومِ الآخِرِ فَلَا يُؤذِ جارَهُ». أخرجه البخاري (5672). (ص43)',
    correctAnswer:true,
    explanation:'الحديث صحيح رواه البخاري برقم 5672.',
    goldenRule:'إيذاء الجار ينافي الإيمان بالله — حديث البخاري.',
    feedbackQuestion:{question:'من أخرج حديث "لا يؤذِ جاره"؟',options:[{text:'البخاري',correct:true},{text:'مسلم',correct:false},{text:'الترمذي',correct:false},{text:'أبو داود',correct:false}]},
  },
  {
    id:'u1l4q6', unit:'unit1', lesson:'u1l4', page:84, type:'matching',
    bloom:'analyze', difficulty:'medium',
    question:'صِل الممتلك بتصنيفه الصحيح:',
    paragraph:'الأشياءُ التي أَملِكُها وَحدِي تُسَمَّى مُمتَلَكاتٍ خاصة. والأشياءُ التي يَستفيدُ منها أنا وسائِرُ الناسِ تُسَمَّى مُمتَلَكاتٍ عامة. (ص83)',
    pairs:[
      {left:'المسجد',right:'ممتلك عام'},
      {left:'ساعة يدي',right:'ممتلك خاص'},
      {left:'ملعب الحي',right:'ممتلك عام'},
      {left:'كتابي المدرسي',right:'ممتلك خاص'},
    ],
    explanation:'عام: المسجد والملعب. خاص: الساعة والكتاب المدرسي.',
    goldenRule:'الممتلكات العامة للجميع — حافظ عليها كحفاظك على ملكك الخاص.',
  },
];

// ─── وحدة 2 | درس 4: أذكار الصباح والمساء ──────────────────────────────────
const u2l1Qs = [
  {
    id:'u2l1q1', unit:'unit2', lesson:'u2l1', page:46, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'يُسنّ للمسلم المحافظة على أذكار الصباح والمساء بعد:',
    paragraph:'يُسَنُّ للمُسلِمِ المُحافَظةُ على أذكارِ الصَّباحِ والمَساءِ بعدَ صلاةِ الفجرِ وبعدَ صلاةِ العصرِ. (ص46)',
    options:[
      {text:'صلاة الفجر وصلاة العصر',correct:true},
      {text:'صلاة الظهر والمغرب',correct:false},
      {text:'صلاة المغرب والعشاء',correct:false},
      {text:'في أي وقت',correct:false},
    ],
    explanation:'وقت أذكار الصباح بعد الفجر، وأذكار المساء بعد العصر.',
    goldenRule:'أذكار الصباح: بعد الفجر. أذكار المساء: بعد العصر.',
    feedbackQuestion:{question:'متى تُقال أذكار المساء؟',options:[{text:'بعد صلاة العصر',correct:true},{text:'بعد صلاة المغرب',correct:false},{text:'بعد صلاة العشاء',correct:false},{text:'قبل النوم مباشرة',correct:false}]},
  },
  {
    id:'u2l1q2', unit:'unit2', lesson:'u2l1', page:46, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'الذِّكر ثقيلٌ في الميزان وحبيب إلى الرحمن ويُحيي القلب.',
    paragraph:'الذِّكرُ ثقيلٌ في الميزانِ، حَبيبٌ إلى الرحمنِ، جالِبٌ للرزقِ، يُحيي القلبَ. (ص46)',
    correctAnswer:true,
    explanation:'الذكر له صفات عديدة: ثقيل في الميزان، محبوب لله، يجلب الرزق، ويحيي القلب.',
    goldenRule:'الذكر: ثقيل في الميزان + حبيب لله + يجلب الرزق + يحيي القلب.',
    feedbackQuestion:{question:'ما من فوائد الذكر؟',options:[{text:'يحيي القلب ويجلب الرزق',correct:true},{text:'يُرهق القلب',correct:false},{text:'لا فائدة منه',correct:false},{text:'يُفقر صاحبه',correct:false}]},
  },
  {
    id:'u2l1q3', unit:'unit2', lesson:'u2l1', page:46, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف فوائد المحافظة على الأذكار:',
    paragraph:'فَوائِدُ المُحافَظةِ على الأذكارِ: القُربُ من اللهِ ورِضوانِه، الاقتداءُ بالنبيِّ، الحِفظُ من الشياطينِ، طُمَأنينةُ القَلبِ. (ص46)',
    categories:['فوائد روحية','فوائد نفسية وعملية'],
    items:[
      {text:'القرب من الله ورضوانه',correct_category:0},
      {text:'الاقتداء بالنبي ﷺ',correct_category:0},
      {text:'طمأنينة القلب وذهاب الهموم',correct_category:1},
      {text:'الحفظ من الشياطين والسلامة من الشرور',correct_category:1},
    ],
    explanation:'روحية: القرب من الله والاقتداء بالنبي. نفسية: الطمأنينة والحفظ من الشياطين.',
    goldenRule:'أذكار الصباح والمساء تجلب الطمأنينة والقرب من الله والحفظ من الشياطين.',
  },
  {
    id:'u2l1q4', unit:'unit2', lesson:'u2l1', page:47, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'من أذكار الصباح والمساء: قراءة سورة الإخلاص والمعوّذتين:',
    paragraph:'قِراءةُ سورةِ الإخلاصِ والفلقِ والناسِ (ثلاثَ مَرَّات). (ص47)',
    options:[
      {text:'ثلاث مرات',correct:true},
      {text:'مرة واحدة',correct:false},
      {text:'سبع مرات',correct:false},
      {text:'عشر مرات',correct:false},
    ],
    explanation:'من السنة قراءة المعوّذتين والإخلاص ثلاث مرات صباحاً ومساءً.',
    goldenRule:'المعوّذتان + الإخلاص: ثلاث مرات صباحاً ومساءً تكفيك من كل شيء.',
    feedbackQuestion:{question:'كم مرة تُقرأ سورة الإخلاص في أذكار الصباح والمساء؟',options:[{text:'ثلاث مرات',correct:true},{text:'مرة واحدة',correct:false},{text:'سبع مرات',correct:false},{text:'مئة مرة',correct:false}]},
  },
  {
    id:'u2l1q5', unit:'unit2', lesson:'u2l1', page:46, type:'trueFalse',
    bloom:'understand', difficulty:'medium',
    question:'من فوائد الذكر: محو السيئات وتقوية القلب والبدن.',
    paragraph:'يَمحو السيئاتِ ويُقوِّي القلبَ والبَدَن. (ص46)',
    correctAnswer:true,
    explanation:'الذكر يمحو السيئات ويقوّي القلب والجسم معاً.',
    goldenRule:'الذكر يمحو السيئات ويقوّي قلبك وجسمك — داوم عليه.',
    feedbackQuestion:{question:'ما أثر الذكر على السيئات؟',options:[{text:'يمحوها',correct:true},{text:'يزيدها',correct:false},{text:'لا أثر له',correct:false},{text:'يُثبّتها',correct:false}]},
  },
  {
    id:'u2l1q6', unit:'unit2', lesson:'u2l1', page:47, type:'fillBlank',
    bloom:'remember', difficulty:'easy',
    question:'أكمل: "سيِّدُ الاستغفار: اللَّهُمَّ أنتَ ___ لا إلهَ إلا أنتَ، خَلَقتَني وأنا ___ ."',
    paragraph:'سيِّدُ الاستِغفارِ: (اللهمَّ أنتَ رَبِّي لا إلهَ إلا أنتَ، خَلَقتَني وأنا عَبدُك). (ص47)',
    blanks:['رَبِّي','عَبدُك'],
    wordBank:['رَبِّي','عَبدُك','خالِقي','مَولاي'],
    explanation:'سيد الاستغفار: "اللهم أنت ربي لا إله إلا أنت، خلقتني وأنا عبدك".',
    goldenRule:'سيد الاستغفار يقوله من قاله صباحاً موقناً ومات من يومه فهو من أهل الجنة.',
  },
  {
    id:'u2l1q7', unit:'unit2', lesson:'u2l1', page:49, type:'multipleChoice',
    bloom:'analyze', difficulty:'medium',
    question:'متى تُقال أذكار الصباح والمساء تحديداً؟',
    paragraph:'متى تُقالُ أذكارُ الصباحِ والمَساء؟ (ص49)',
    options:[
      {text:'بعد صلاة الفجر وبعد صلاة العصر',correct:true},
      {text:'أي وقت خلال اليوم',correct:false},
      {text:'عند النوم فقط',correct:false},
      {text:'عند الاستيقاظ فقط',correct:false},
    ],
    explanation:'الوقت المسنون: أذكار الصباح بعد الفجر، والمساء بعد العصر.',
    goldenRule:'الفجر للصباح — العصر للمساء — لا تفوّت هذا الوقت الثمين.',
    feedbackQuestion:{question:'ما وقت أذكار الصباح تحديداً؟',options:[{text:'بعد صلاة الفجر',correct:true},{text:'قبل الفجر',correct:false},{text:'بعد الظهر',correct:false},{text:'أي وقت في الصباح',correct:false}]},
  },
  {
    id:'u2l1q8', unit:'unit2', lesson:'u2l1', page:49, type:'ordering',
    bloom:'apply', difficulty:'medium',
    question:'رتّب ثلاثة من أذكار الصباح والمساء حسب ورودها في الدرس:',
    paragraph:'من أذكار الصباح والمساء. (ص47)',
    items:['سيد الاستغفار','قراءة المعوّذتين والإخلاص','اللهم عافني في بدني وسمعي وبصري','أمسينا وأمسى الملك لله'],
    correctOrder:[1,0,3,2],
    explanation:'الترتيب في الكتاب: المعوّذتان ← سيد الاستغفار ← أمسينا ← اللهم عافني.',
    goldenRule:'اللهم عافني في بدني وسمعي وبصري — ثلاث مرات تكفيك من المرض.',
  },
];

// ─── وحدة 2 | درس 5: أذكار العطاس والنوم ──────────────────────────────────
const u2l2Qs = [
  {
    id:'u2l2q1', unit:'unit2', lesson:'u2l2', page:50, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'عند العطاس ما الذي يقوله العاطس أولاً؟',
    paragraph:'أيُّ التلاميذِ في الصورِ كانَ فِعلُه الأفضلَ عندَ العَطس؟ أنا أُحافِظُ على آدابِ العُطاس. (ص50)',
    options:[
      {text:'الحمد لله',correct:true},
      {text:'سبحان الله',correct:false},
      {text:'بسم الله',correct:false},
      {text:'الله أكبر',correct:false},
    ],
    explanation:'السنة عند العطاس: يقول "الحمد لله"، ثم يردّ عليه من يسمعه "يرحمك الله".',
    goldenRule:'العطاس: "الحمد لله" — ومن يسمعك: "يرحمك الله" — فترد: "يهديكم الله".',
    feedbackQuestion:{question:'ما الذي يرده من يسمع العاطس يقول الحمد لله؟',options:[{text:'يرحمك الله',correct:true},{text:'بارك الله فيك',correct:false},{text:'سبحان الله',correct:false},{text:'الحمد لله',correct:false}]},
  },
  {
    id:'u2l2q2', unit:'unit2', lesson:'u2l2', page:50, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'من آداب العطاس تغطية الفم واليد عند العطاس.',
    paragraph:'أنا أُحافِظُ على آدابِ العُطاس. (ص50) — الصورة الأولى تُظهر تغطية الفم عند العطاس.',
    correctAnswer:true,
    explanation:'تغطية الفم عند العطاس أدب صحي وإسلامي يمنع انتشار الجراثيم.',
    goldenRule:'غطِّ فمك عند العطاس — هذا أدب إسلامي وحماية صحية.',
    feedbackQuestion:{question:'لماذا نغطي الفم عند العطاس؟',options:[{text:'منعاً لانتشار الجراثيم وأدباً',correct:true},{text:'لإخفاء العطسة',correct:false},{text:'لأن ذلك عادة',correct:false},{text:'لا سبب',correct:false}]},
  },
  {
    id:'u2l2q3', unit:'unit2', lesson:'u2l2', page:50, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف هذه التصرفات: صحيحة أم خاطئة عند العطاس؟',
    paragraph:'أيُّ التلاميذِ في الصوِر كانَ فِعلُه الأفضلَ عندَ العطس؟ (ص50)',
    categories:['تصرف صحيح عند العطاس ✅','تصرف خاطئ عند العطاس ❌'],
    items:[
      {text:'تغطية الفم والأنف باليد أو المنديل',correct_category:0},
      {text:'العطاس بصوت عالٍ دون تغطية',correct_category:1},
      {text:'قول "الحمد لله" بعد العطاس',correct_category:0},
      {text:'العطاس في وجه الجالس أمامنا',correct_category:1},
    ],
    explanation:'صحيح: التغطية + الحمد لله. خاطئ: عدم التغطية + العطاس في الوجه.',
    goldenRule:'عند العطاس: غطِّ فمك + قل الحمد لله + ابتعد عن وجه الآخرين.',
  },
  {
    id:'u2l2q4', unit:'unit2', lesson:'u2l2', page:50, type:'matching',
    bloom:'understand', difficulty:'medium',
    question:'صِل الموقف بالذِّكر المناسب له:',
    paragraph:'أذكار العطاس والنوم. (ص50-51)',
    pairs:[
      {left:'عند العطاس',right:'الحمد لله'},
      {left:'عند سماع العاطس',right:'يرحمك الله'},
      {left:'ردّ العاطس على التشميت',right:'يهديكم الله ويصلح بالكم'},
      {left:'قبل النوم',right:'باسمك اللهم أموت وأحيا'},
    ],
    explanation:'مجموعة أذكار مرتبطة بمواقف يومية: عطاس ← سماع ← رد ← نوم.',
    goldenRule:'لكل موقف في يومك ذِكر يُقرّبك من الله — احفظها وأدِّها.',
  },
  {
    id:'u2l2q5', unit:'unit2', lesson:'u2l2', page:50, type:'trueFalse',
    bloom:'remember', difficulty:'easy',
    question:'يجب أن أحافظ على آداب العطاس في كل الأوقات والأماكن.',
    paragraph:'أنا أُحافِظُ على آدابِ العُطاسِ. (ص50)',
    correctAnswer:true,
    explanation:'آداب العطاس تُطبَّق دائماً في كل مكان لأنها أدب إسلامي وصحي.',
    goldenRule:'آداب العطاس دائمة في كل مكان — المدرسة والمنزل والمسجد وكل مكان.',
    feedbackQuestion:{question:'في أي الأماكن نُطبّق آداب العطاس؟',options:[{text:'في كل مكان وزمان',correct:true},{text:'في المدرسة فقط',correct:false},{text:'في المسجد فقط',correct:false},{text:'عند الكبار فقط',correct:false}]},
  },
  {
    id:'u2l2q6', unit:'unit2', lesson:'u2l2', page:50, type:'multipleChoice',
    bloom:'evaluate', difficulty:'medium',
    question:'أيّ تصرف هو الأفضل عند العطاس وفق ما رأيناه في الصور؟',
    paragraph:'أيُّ التلاميذِ في الصورِ كانَ فِعلُه الأفضلَ عندَ العطس؟ صورةٌ رقم (1) — الطالب يُغطّي فمه وقال "الحمد لله". (ص50)',
    options:[
      {text:'تغطية الفم وقول الحمد لله',correct:true},
      {text:'العطاس بصوت عالٍ',correct:false},
      {text:'ترك الفم مفتوحاً',correct:false},
      {text:'الإسراع بمغادرة المكان',correct:false},
    ],
    explanation:'الصورة الأولى في الكتاب تُظهر الطالب الذي يُغطّي فمه ويقول الحمد لله.',
    goldenRule:'التصرف الأفضل عند العطاس = تغطية الفم + الحمد لله.',
    feedbackQuestion:{question:'ما الذِّكر المقرون بتغطية الفم عند العطاس؟',options:[{text:'الحمد لله',correct:true},{text:'سبحان الله',correct:false},{text:'الله أكبر',correct:false},{text:'بسم الله',correct:false}]},
  },
];

// ─── وحدة 3 | درس 12: المحافظة على الممتلكات العامة ─────────────────────
const u3l1Qs = [
  {
    id:'u3l1q1', unit:'unit3', lesson:'u3l1', page:82, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'الممتلكات العامة هي الأشياء التي:',
    paragraph:'الأشياءُ التي يَستفيدُ منها أنا وسائِرُ الناسِ تُسَمَّى مُمتَلَكاتٍ عامة. (ص83)',
    options:[
      {text:'يستفيد منها الجميع',correct:true},
      {text:'يملكها شخص واحد فقط',correct:false},
      {text:'لا أحد يستفيد منها',correct:false},
      {text:'تخص الحكومة وحدها',correct:false},
    ],
    explanation:'الممتلكات العامة يستفيد منها الجميع مثل المساجد والمدارس والحدائق.',
    goldenRule:'الممتلك العام = للجميع — واجبنا المحافظة عليه.',
    feedbackQuestion:{question:'ما الفرق بين الممتلك الخاص والممتلك العام؟',options:[{text:'الخاص: يملكه فرد. العام: للجميع',correct:true},{text:'كلاهما للفرد',correct:false},{text:'كلاهما للجميع',correct:false},{text:'لا فرق',correct:false}]},
  },
  {
    id:'u3l1q2', unit:'unit3', lesson:'u3l1', page:82, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'المسجد وملعب الحي من أمثلة الممتلكات العامة.',
    paragraph:'أضَعُ علامةَ (✓) تحتَ صُورِ المُمتَلَكاتِ العامَّة. — المسجد، الملعب. (ص82)',
    correctAnswer:true,
    explanation:'المسجد والملعب يستفيد منهما المجتمع كله، فهما من الممتلكات العامة.',
    goldenRule:'المسجد والملعب والمدرسة: ممتلكات عامة — حافظ عليها.',
    feedbackQuestion:{question:'من أمثلة الممتلكات العامة:',options:[{text:'المسجد وملعب الحي والمدرسة',correct:true},{text:'ساعة اليد والقلم',correct:false},{text:'حذائي وكتابي',correct:false},{text:'سيارة أبي',correct:false}]},
  },
  {
    id:'u3l1q3', unit:'unit3', lesson:'u3l1', page:82, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف: ممتلكات خاصة أم ممتلكات عامة؟',
    paragraph:'الأشياءُ التي أَملِكُها وَحدِي: مُمتَلَكاتٌ خاصة. والأشياءُ التي يَستفيدُ منها أنا وسائِرُ الناسِ: مُمتَلَكاتٌ عامة. (ص83)',
    categories:['ممتلكات خاصة','ممتلكات عامة'],
    items:[
      {text:'ساعة اليد',correct_category:0},
      {text:'المدرسة',correct_category:1},
      {text:'القلم',correct_category:0},
      {text:'المسجد',correct_category:1},
      {text:'الحديقة العامة',correct_category:1},
      {text:'حذائي',correct_category:0},
    ],
    explanation:'خاصة: ساعة، قلم، حذاء. عامة: مدرسة، مسجد، حديقة.',
    goldenRule:'الممتلك الخاص ما أملكه وحدي. العام ما يشاركني فيه الناس.',
  },
  {
    id:'u3l1q4', unit:'unit3', lesson:'u3l1', page:84, type:'trueFalse',
    bloom:'apply', difficulty:'easy',
    question:'لا يجوز الكتابة على جدران المدرسة لأنها ممتلك عام.',
    paragraph:'لا تَعبَثُ بالمُمتَلَكاتِ العامَّة. (ص84)',
    correctAnswer:true,
    explanation:'الكتابة على الجدران تُتلف الممتلك العام وتؤذي المجتمع كله.',
    goldenRule:'الكتابة على الجدران إتلاف للممتلك العام — تجنّبه وانصح من يفعله.',
    feedbackQuestion:{question:'لماذا لا نكتب على جدران المدرسة؟',options:[{text:'لأنها ممتلك عام يجب المحافظة عليه',correct:true},{text:'لأن الحبر غالٍ',correct:false},{text:'لأن المعلم سيعاقبنا',correct:false},{text:'لا سبب',correct:false}]},
  },
  {
    id:'u3l1q5', unit:'unit3', lesson:'u3l1', page:85, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'قال الله تعالى: "وجعلنا من الماء كل شيء":',
    paragraph:'قالَ اللهُ تعالى: ﴿وَجَعَلْنَا مِنَ الْمَاءِ كُلَّ شَيْءٍ حَيٍّ﴾. (ص85)',
    options:[
      {text:'حيّ',correct:true},
      {text:'مبارك',correct:false},
      {text:'جميل',correct:false},
      {text:'طاهر',correct:false},
    ],
    explanation:'الآية الكريمة: ﴿وَجَعَلْنَا مِنَ الْمَاءِ كُلَّ شَيْءٍ حَيٍّ﴾ من سورة الأنبياء آية 30.',
    goldenRule:'الماء نعمة عظيمة أصل الحياة — قال تعالى: وجعلنا من الماء كل شيء حيّ.',
    feedbackQuestion:{question:'ما الكلمة المكملة للآية: "وجعلنا من الماء كل شيء..."؟',options:[{text:'حيّ',correct:true},{text:'طيّب',correct:false},{text:'نظيف',correct:false},{text:'مبارك',correct:false}]},
  },
  {
    id:'u3l1q6', unit:'unit3', lesson:'u3l1', page:85, type:'trueFalse',
    bloom:'understand', difficulty:'medium',
    question:'الماء نعمة عظيمة يجب الحفاظ عليها وعدم الإسراف فيها.',
    paragraph:'الماءُ نِعمةٌ عَظيمةٌ فَلنُحافِظُ عليها. (ص85)',
    correctAnswer:true,
    explanation:'الماء أصل الحياة وقد أمرنا الله بالمحافظة عليه وعدم الإسراف.',
    goldenRule:'الماء نعمة عظيمة — لا تُسرف وأطفئ الصنبور بعد الاستخدام.',
    feedbackQuestion:{question:'ما واجبنا تجاه نعمة الماء؟',options:[{text:'المحافظة عليها وعدم الإسراف',correct:true},{text:'استخدام ما نشاء',correct:false},{text:'ترك الصنبور مفتوحاً',correct:false},{text:'لا واجب',correct:false}]},
  },
  {
    id:'u3l1q7', unit:'unit3', lesson:'u3l1', page:87, type:'fillBlank',
    bloom:'apply', difficulty:'medium',
    question:'أكمل: "...... أُحافِظُ على نَظافةِ المسجدِ"، "...... أَعبَثُ بِسبّورةِ المدرسةِ".',
    paragraph:'أضَعُ كلمةَ (أنا) أو كلمةَ (أنا لا) في المَكانِ المُناسب. (ص87)',
    blanks:['أنا','أنا لا'],
    wordBank:['أنا','أنا لا'],
    explanation:'أنا أحافظ على نظافة المسجد — لكن أنا لا أعبث بسبّورة المدرسة.',
    goldenRule:'أنا + المحافظة على الممتلكات العامة. أنا لا + إتلاف أي ممتلك عام.',
  },
  {
    id:'u3l1q8', unit:'unit3', lesson:'u3l1', page:88, type:'classify',
    bloom:'evaluate', difficulty:'hard',
    question:'صنّف هذه التصرفات: يُعجبني أم لا يُعجبني؟',
    paragraph:'أُربِطُ بينَ كلِّ كلمةٍ والصورةِ المُناسبةِ لها: يُعجبُني / لا يُعجبُني. (ص88)',
    categories:['يُعجبني ✅','لا يُعجبني ❌'],
    items:[
      {text:'ريّ الأشجار في الحديقة',correct_category:0},
      {text:'الكتابة على الجدران',correct_category:1},
      {text:'ترتيب الكراسي في الفصل',correct_category:0},
      {text:'رمي القمامة في الحديقة',correct_category:1},
      {text:'الصلاة في المسجد',correct_category:0},
      {text:'إتلاف الأثاث المدرسي',correct_category:1},
    ],
    explanation:'يعجبني: ريّ الأشجار، ترتيب الكراسي، الصلاة. لا يعجبني: الكتابة على الجدران، القمامة، إتلاف الأثاث.',
    goldenRule:'كل ما يُحافظ على الممتلكات العامة يُعجبني — وكل إتلاف لا يُعجبني.',
  },
];

export const ALL_QUESTIONS = [
  ...u1l1Qs, ...u1l2Qs, ...u1l3Qs, ...u1l4Qs,
  ...u2l1Qs, ...u2l2Qs,
  ...u3l1Qs,
  ...ISLAMIC_EXTRA_1,
];