// التربية الإسلامية - الصف الثاني الابتدائي - الفصل الأول
// الوحدة الخامسة: الفقه والسلوك — الأذكار والأدعية
// الدرس الأول: أذكار الصباح والمساء — صفحة 46-49

export const ADHKAR_L1 = [
  { id:'adk1q1', unit:'u5', lesson:'u5l1', page:46, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'أذكار الصباح والمساء تُقال:',
    paragraph:'أذكار الصباح والمساء تُقال في الصباح بعد الفجر وفي المساء بعد العصر. (ص46)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'في الصباح بعد الفجر وفي المساء بعد العصر',correct:true},{text:'في الليل فقط',correct:false},{text:'في الظهر فقط',correct:false},{text:'لا وقت محدد',correct:false}],
    explanation:'أذكار الصباح تُقال بعد الفجر، وأذكار المساء تُقال بعد العصر — حسب السنة.',
    goldenRule:'أذكار الصباح = بعد الفجر. أذكار المساء = بعد العصر.',
    feedbackQuestion:{question:'متى تُقال أذكار الصباح؟',options:[{text:'بعد الفجر',correct:true},{text:'في الليل',correct:false},{text:'في الظهر',correct:false},{text:'لا وقت',correct:false}]} },
  { id:'adk1q2', unit:'u5', lesson:'u5l1', page:46, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'من فضائل ذكر الله أنه:',
    paragraph:'الذكر ثقيل في الميزان، محبوب لله، يأتي بالرزق، يحيي القلب. (ص46)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'ثقيل في الميزان ومحبوب لله ويأتي بالرزق',correct:true},{text:'لا قيمة له',correct:false},{text:'يضر',correct:false},{text:'مكروه',correct:false}],
    explanation:'ذكر الله ثقيل في الميزان، محبوب لله، يأتي بالرزق، يحيي القلب، يمحو الذنوب.',
    goldenRule:'الذكر = ثقل ميزان + محبة الله + رزق + حياة قلب.',
    feedbackQuestion:{question:'ماذا في فضل الذكر؟',options:[{text:'ثقيل في الميزان ومحبوب لله',correct:true},{text:'لا قيمة',correct:false},{text:'يضر',correct:false},{text:'مكروه',correct:false}]} },
  { id:'adk1q3', unit:'u5', lesson:'u5l1', page:46, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'من سور أذكار الصباح والمساء:',
    paragraph:'من أذكار الصباح والمساء: سورة الإخلاص، سورة الفلق، سورة الناس. (ص46)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'الإخلاص والفلق والناس',correct:true},{text:'البقرة فقط',correct:false},{text:'الفاتحة فقط',correct:false},{text:'الكوثر فقط',correct:false}],
    explanation:'من أذكار الصباح والمساء: الإخلاص + الفلق + الناس (المعوذات) تُقال ثلاثاً.',
    goldenRule:'المعوذات الثلاث: الإخلاص + الفلق + الناس — صباحاً ومساءً.',
    feedbackQuestion:{question:'أي سور تُقال في أذكار الصباح والمساء؟',options:[{text:'الإخلاص والفلق والناس',correct:true},{text:'البقرة',correct:false},{text:'الفاتحة',correct:false},{text:'الكوثر',correct:false}]} },
  { id:'adk1q4', unit:'u5', lesson:'u5l1', page:46, type:'trueFalse', bloom:'understand', difficulty:'easy',
    question:'سيد الاستغفار يُقال في أذكار الصباح والمساء.',
    paragraph:'من أذكار الصباح والمساء: سيد الاستغفار. (ص46)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    correctAnswer:true,
    explanation:'سيد الاستغفار من أذكار الصباح والمساء، وهو: «اللهم أنت ربي لا إله إلا أنت...».',
    goldenRule:'سيد الاستغفار = «اللهم أنت ربي لا إله إلا أنت خلقتني وأنا عبدك».',
    feedbackQuestion:{question:'هل سيد الاستغفار من أذكار الصباح والمساء؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'مكروه',correct:false},{text:'لا أعرف',correct:false}]} },
  { id:'adk1q5', unit:'u5', lesson:'u5l1', page:46, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'الذكر يُحيي:',
    paragraph:'الذكر يحيي القلب ويمحو الذنوب ويقوي الجسد. (ص46)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'القلب ويمحو الذنوب',correct:true},{text:'الجسد فقط',correct:false},{text:'لا شيء',correct:false},{text:'يضر',correct:false}],
    explanation:'الذكر يُحيي القلب ويمحو الذنوب ويقوي الجسد والروح.',
    goldenRule:'الذكر = حياة قلب + محو ذنوب + قوة جسد.',
    feedbackQuestion:{question:'ماذا يُحيي الذكر؟',options:[{text:'القلب',correct:true},{text:'الجسد فقط',correct:false},{text:'لا شيء',correct:false},{text:'يضر',correct:false}]} },
  { id:'adk1q6', unit:'u5', lesson:'u5l1', page:46, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'من أذكار الصباح والمساء: «اللهم بك أصبحنا وبك ___».',
    paragraph:'من أذكار الصباح والمساء: «اللهم بك أصبحنا وبك أمسينا». (ص46)',
    options:[{text:'أمسينا',correct:true},{text:'نمنا',correct:false},{text:'قمنا',correct:false},{text:'قعدنا',correct:false}],
    explanation:'الذكر: «اللهم بك أصبحنا وبك أمسينا، وبك نحيا وبك نموت وإليك النشور».',
    goldenRule:'أذكار الصباح: اللهم بك أصبحنا وبك أمسينا وبك نحيا وبك نموت وإليك النشور.',
    feedbackQuestion:{question:'بماذا يكمل «اللهم بك أصبحنا وبك»؟',options:[{text:'أمسينا',correct:true},{text:'نمنا',correct:false},{text:'قمنا',correct:false},{text:'قعدنا',correct:false}]} },
  { id:'adk1q7', unit:'u5', lesson:'u5l1', page:46, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'«بسم الله الذي لا يضر مع اسمه شيء» تُقال:',
    paragraph:'من أذكار الصباح والمساء: «بسم الله الذي لا يضر مع اسمه شيء في الأرض ولا في السماء». (ص46)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'في الصباح والمساء ثلاث مرات',correct:true},{text:'مرة واحدة',correct:false},{text:'عشر مرات',correct:false},{text:'لا تقال',correct:false}],
    explanation:'«بسم الله الذي لا يضر مع اسمه شيء» تُقال ثلاثاً في الصباح والمساء للحفظ.',
    goldenRule:'بسم الله الذي لا يضر مع اسمه شيء — ثلاثاً صباحاً ومساءً = حفظ.',
    feedbackQuestion:{question:'كم مرة تُقال «بسم الله الذي لا يضر مع اسمه شيء»؟',options:[{text:'ثلاث مرات',correct:true},{text:'مرة',correct:false},{text:'عشر',correct:false},{text:'لا تقال',correct:false}]} },
  { id:'adk1q8', unit:'u5', lesson:'u5l1', page:46, type:'multipleChoice', bloom:'apply', difficulty:'medium',
    question:'قبل النوم تُقال أذكار النوم، وفي الصباح تُقال أذكار:',
    paragraph:'أذكار الصباح تُقال بعد الفجر. (ص46)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'الصباح',correct:true},{text:'النوم',correct:false},{text:'العشاء',correct:false},{text:'الظهر',correct:false}],
    explanation:'في الصباح تُقال أذكار الصباح، وفي المساء أذكار المساء، وقبل النوم أذكار النوم.',
    goldenRule:'لكل وقت أذكاره: صباح + مساء + نوم.',
    feedbackQuestion:{question:'ماذا تُقال في الصباح؟',options:[{text:'أذكار الصباح',correct:true},{text:'أذكار النوم',correct:false},{text:'أذكار العشاء',correct:false},{text:'أذكار الظهر',correct:false}]} },
  { id:'adk1q9', unit:'u5', lesson:'u5l1', page:46, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'الذكر يأتي بـ:',
    paragraph:'الذكر يأتي بالرزق ويحيي القلب ويمحو الذنوب. (ص46)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'الرزق وحياة القلب ومحو الذنوب',correct:true},{text:'الجوع',correct:false},{text:'المرض',correct:false},{text:'لا شيء',correct:false}],
    explanation:'الذكر يأتي بالرزق ويحيي القلب ويمحو الذنوب ويقوي الجسد.',
    goldenRule:'الذكر = رزق + حياة قلب + محو ذنوب + قوة جسد.',
    feedbackQuestion:{question:'ماذا يأتي الذكر به؟',options:[{text:'الرزق وحياة القلب',correct:true},{text:'الجوع',correct:false},{text:'المرض',correct:false},{text:'لا شيء',correct:false}]} },
  { id:'adk1q10', unit:'u5', lesson:'u5l1', page:46, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'من أذكار الصباح والمساء: «رضيت بالله رباً وبالإسلام ديناً وبمحمد ﷺ ___».',
    paragraph:'من أذكار الصباح والمساء: «رضيت بالله رباً وبالإسلام ديناً وبمحمد ﷺ نبياً». (ص46)',
    options:[{text:'نبياً',correct:true},{text:'رسولاً',correct:false},{text:'خليفة',correct:false},{text:'أباً',correct:false}],
    explanation:'الذكر: «رضيت بالله رباً وبالإسلام ديناً وبمحمد ﷺ نبياً» ثلاثاً صباحاً ومساءً.',
    goldenRule:'رضيت بالله رباً + بالإسلام ديناً + بمحمد ﷺ نبياً — ثلاثاً.',
    feedbackQuestion:{question:'بماذا يكمل «رضيت بالله رباً وبالإسلام ديناً وبمحمد ﷺ»؟',options:[{text:'نبياً',correct:true},{text:'رسولاً',correct:false},{text:'خليفة',correct:false},{text:'أباً',correct:false}]} },
  { id:'adk1q11', unit:'u5', lesson:'u5l1', page:46, type:'trueFalse', bloom:'understand', difficulty:'easy',
    question:'الذكر يقوي القلب والجسد.',
    paragraph:'الذكر يقوي القلب والجسد ويذهب الهم والغم. (ص46)',
    correctAnswer:true,
    explanation:'الذكر يقوي القلب والجسد ويذهب الهم والغم ويشرح الصدر.',
    goldenRule:'الذكر = قوة قلب + قوة جسد + ذهاب هم + شرح صدر.',
    feedbackQuestion:{question:'هل الذكر يقوي القلب والجسد؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'يضر',correct:false},{text:'لا أعرف',correct:false}]} },
  { id:'adk1q12', unit:'u5', lesson:'u5l1', page:46, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'الذكر يُذهب:',
    paragraph:'الذكر يُذهب الهم والغم ويُشرح الصدر. (ص46)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'الهم والغم ويُشرح الصدر',correct:true},{text:'الرزق',correct:false},{text:'الصحة',correct:false},{text:'لا شيء',correct:false}],
    explanation:'الذكر يُذهب الهم والغم ويُشرح الصدر ويُطيب النفس.',
    goldenRule:'الذكر = ذهاب هم + ذهاب غم + شرح صدر + طيب نفس.',
    feedbackQuestion:{question:'ماذا يُذهب الذكر؟',options:[{text:'الهم والغم',correct:true},{text:'الرزق',correct:false},{text:'الصحة',correct:false},{text:'لا شيء',correct:false}]} },
  { id:'adk1q13', unit:'u5', lesson:'u5l1', page:46, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'من أذكار الصباح والمساء: «سبحان الله وبحمده» تُقال:',
    paragraph:'من أذكار الصباح والمساء: «سبحان الله وبحمده» مائة مرة. (ص46)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'مائة مرة',correct:true},{text:'مرة واحدة',correct:false},{text:'عشر مرات',correct:false},{text:'لا تقال',correct:false}],
    explanation:'«سبحان الله وبحمده» تُقال مائة مرة في الصباح والمساء وتحط الخطايا.',
    goldenRule:'سبحان الله وبحمده 100 مرة = حط خطايا + ثقل ميزان.',
    feedbackQuestion:{question:'كم مرة تُقال «سبحان الله وبحمده»؟',options:[{text:'100 مرة',correct:true},{text:'مرة',correct:false},{text:'عشر',correct:false},{text:'لا تقال',correct:false}]} },
  { id:'adk1q14', unit:'u5', lesson:'u5l1', page:46, type:'multipleChoice', bloom:'apply', difficulty:'medium',
    question:'إذا استيقظت في الصباح، فأول ما تقول:',
    paragraph:'أذكار الصباح تُقال بعد الاستيقاظ. (ص46)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'أذكار الصباح',correct:true},{text:'لا شيء',correct:false},{text:'أناشيد',correct:false},{text:'أنام',correct:false}],
    explanation:'عند الاستيقاظ في الصباح تقول أذكار الصباح التي علَّمنا رسول الله ﷺ.',
    goldenRule:'الاستيقاظ = أذكار صباح + حمد الله + شكر.',
    feedbackQuestion:{question:'ماذا تقول عند الاستيقاظ؟',options:[{text:'أذكار الصباح',correct:true},{text:'لا شيء',correct:false},{text:'أناشيد',correct:false},{text:'أنام',correct:false}]} },
  { id:'adk1q15', unit:'u5', lesson:'u5l1', page:46, type:'classify', bloom:'analyze', difficulty:'medium',
    question:'صنّف: من سور أذكار الصباح والمساء أم لا؟',
    paragraph:'من سور أذكار الصباح والمساء: الإخلاص + الفلق + الناس. (ص46)',
    categories:['من أذكار الصباح والمساء 📖','ليس منها ❌'],
    items:[
      {text:'الإخلاص',correct_category:0},{text:'الفلق',correct_category:0},
      {text:'الناس',correct_category:0},{text:'البقرة',correct_category:1},
      {text:'آل عمران',correct_category:1},{text:'الماعون',correct_category:1},
    ],
    explanation:'من أذكار الصباح والمساء: الإخلاص + الفلق + الناس (المعوذات). البقرة وآل عمران والماعون ليست منها.',
    goldenRule:'المعوذات الثلاث = الإخلاص + الفلق + الناس — أذكار الصباح والمساء.' },
  { id:'adk1q16', unit:'u5', lesson:'u5l1', page:46, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'من أذكار الصباح والمساء: «اللهم عافني في ___».',
    paragraph:'من أذكار الصباح والمساء: «اللهم عافني في بدني، اللهم عافني في سمعي، اللهم عافني في بصري». (ص46)',
    options:[{text:'بدني وسمعي وبصري',correct:true},{text:'مالي فقط',correct:false},{text:'ولدي',correct:false},{text:'بيتي',correct:false}],
    explanation:'الذكر: «اللهم عافني في بدني، اللهم عافني في سمعي، اللهم عافني في بصري» ثلاثاً.',
    goldenRule:'اللهم عافني = بدني + سمعي + بصري — ثلاثاً صباحاً ومساءً.',
    feedbackQuestion:{question:'في ماذا تطلب العافية؟',options:[{text:'البدن والسمع والبصر',correct:true},{text:'المال',correct:false},{text:'الولد',correct:false},{text:'البيت',correct:false}]} },
  { id:'adk1q17', unit:'u5', lesson:'u5l1', page:46, type:'multipleChoice', bloom:'evaluate', difficulty:'hard',
    question:'لماذا أمرنا الإسلام بأذكار الصباح والمساء؟',
    paragraph:'أذكار الصباح والمساء تحفظ من الشرور وتقرب من الله. (ص46)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'لحفظنا من الشرور وتقريبنا من الله',correct:true},{text:'عادة',correct:false},{text:'لا سبب',correct:false},{text:'مكروه',correct:false}],
    explanation:'أذكار الصباح والمساء تحفظنا من الشرور وتقربنا من الله وتملأ ميزاننا.',
    goldenRule:'الأذكار = حفظ + تقريب من الله + ثقل ميزان.',
    feedbackQuestion:{question:'لماذا أمرنا الإسلام بالأذكار؟',options:[{text:'للحفظ والتقريب من الله',correct:true},{text:'عادة',correct:false},{text:'لا سبب',correct:false},{text:'مكروه',correct:false}]} },
  { id:'adk1q18', unit:'u5', lesson:'u5l1', page:46, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'سورة الإخلاص تعدل:',
    paragraph:'سورة الإخلاص تعدل ثلث القرآن وتُقال في أذكار الصباح والمساء. (ص46)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'ثلث القرآن',correct:true},{text:'نصف القرآن',correct:false},{text:'ربع القرآن',correct:false},{text:'لا شيء',correct:false}],
    explanation:'سورة الإخلاص تعدل ثلث القرآن وتُقال ثلاثاً في أذكار الصباح والمساء.',
    goldenRule:'الإخلاص = ثلث القرآن + أذكار الصباح والمساء.',
    feedbackQuestion:{question:'بمَ تعدل سورة الإخلاص؟',options:[{text:'ثلث القرآن',correct:true},{text:'نصف',correct:false},{text:'ربع',correct:false},{text:'لا شيء',correct:false}]} },
  { id:'adk1q19', unit:'u5', lesson:'u5l1', page:46, type:'fillBlank', bloom:'apply', difficulty:'easy',
    question:'أكمل: أذكار الصباح تُقال بعد ___.',
    paragraph:'أذكار الصباح تُقال بعد الفجر. (ص46)',
    blanks:['الفجر'],
    wordBank:['الفجر','العصر','النوم','الظهر'],
    explanation:'أذكار الصباح تُقال بعد الفجر في الصباح الباكر.',
    goldenRule:'أذكار الصباح = بعد الفجر. أذكار المساء = بعد العصر.' },
  { id:'adk1q20', unit:'u5', lesson:'u5l1', page:46, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'المعوذات هي:',
    paragraph:'المعوذات: الإخلاص + الفلق + الناس. (ص46)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'الإخلاص والفلق والناس',correct:true},{text:'الفاتحة والبقرة',correct:false},{text:'الملك والكهف',correct:false},{text:'لا شيء',correct:false}],
    explanation:'المعوذات هي: الإخلاص + الفلق + الناس، تُقال ثلاثاً في الصباح والمساء للحفظ.',
    goldenRule:'المعوذات = الإخلاص + الفلق + الناس = حفظ + وقاية.',
    feedbackQuestion:{question:'ما المعوذات؟',options:[{text:'الإخلاص والفلق والناس',correct:true},{text:'الفاتحة والبقرة',correct:false},{text:'الملك والكهف',correct:false},{text:'لا شيء',correct:false}]} },
  { id:'adk1q21', unit:'u5', lesson:'u5l1', page:46, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'الذكر يحببه الله ورسوله ويجعله:',
    paragraph:'الذكر محبوب لله ورسوله ويقرب من الله. (ص46)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'قريباً من الله ومحبوباً له',correct:true},{text:'بعيداً',correct:false},{text:'مكروهاً',correct:false},{text:'لا شيء',correct:false}],
    explanation:'الذكر يجعل صاحبه قريباً من الله ومحبوباً له لأن الله يحب الذاكرين.',
    goldenRule:'الذاكر = قريب من الله + محبوب + راضٍ.',
    feedbackQuestion:{question:'ماذا يجعل الذكر صاحبه؟',options:[{text:'قريباً من الله ومحبوباً',correct:true},{text:'بعيداً',correct:false},{text:'مكروهاً',correct:false},{text:'لا شيء',correct:false}]} },
  { id:'adk1q22', unit:'u5', lesson:'u5l1', page:46, type:'matching', bloom:'understand', difficulty:'medium',
    question:'صِل كل ذكر بفضله:',
    paragraph:'فضائل الذكر: ثقل ميزان + محبة الله + رزق + حياة قلب + محو ذنوب. (ص46)',
    pairs:[
      {left:'ثقل الميزان',right:'سبحان الله وبحمده'},
      {left:'محبة الله',right:'الذكر المستمر'},
      {left:'محو الذنوب',right:'سيد الاستغفار'},
      {left:'حفظ من الشر',right:'المعوذات الثلاث'},
    ],
    explanation:'لكل ذكر فضله: تسبيح = ثقل، استغفار = محو ذنوب، معوذات = حفظ.',
    goldenRule:'لكل ذكر فضله: تسبيح + استغفار + معوذات + حمد.' },
  { id:'adk1q23', unit:'u5', lesson:'u5l1', page:46, type:'multipleChoice', bloom:'apply', difficulty:'medium',
    question:'إذا خرجت من البيت في الصباح، فتقول أذكار:',
    paragraph:'أذكار الصباح والمساء تحفظ في الخروج. (ص46)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'الصباح قبل الخروج',correct:true},{text:'النوم',correct:false},{text:'العشاء',correct:false},{text:'لا شيء',correct:false}],
    explanation:'قبل الخروج في الصباح تقول أذكار الصباح لتحفظك في يومك.',
    goldenRule:'الخروج صباحاً = أذكار صباح + حفظ + توفيق.',
    feedbackQuestion:{question:'ماذا تقول قبل الخروج صباحاً؟',options:[{text:'أذكار الصباح',correct:true},{text:'أذكار النوم',correct:false},{text:'أذكار العشاء',correct:false},{text:'لا شيء',correct:false}]} },
  { id:'adk1q24', unit:'u5', lesson:'u5l1', page:46, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'سورة الفلق وسورة الناس تُقال:',
    paragraph:'الفلق والناس تُقال ثلاثاً في أذكار الصباح والمساء. (ص46)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'ثلاث مرات',correct:true},{text:'مرة واحدة',correct:false},{text:'عشر مرات',correct:false},{text:'لا تقال',correct:false}],
    explanation:'سورة الفلق وسورة الناس تُقال ثلاث مرات في الصباح والمساء للحفظ.',
    goldenRule:'الفلق والناس = ثلاثاً = حفظ + وقاية من الشر.',
    feedbackQuestion:{question:'كم مرة تُقال الفلق والناس؟',options:[{text:'ثلاث مرات',correct:true},{text:'مرة',correct:false},{text:'عشر',correct:false},{text:'لا تقال',correct:false}]} },
  { id:'adk1q25', unit:'u5', lesson:'u5l1', page:46, type:'trueFalse', bloom:'evaluate', difficulty:'hard',
    question:'أذكار الصباح والمساء تحفظ المسلم من الشرور والمصائب.',
    paragraph:'أذكار الصباح والمساء تحفظ من الشرور والمصائب. (ص46)',
    correctAnswer:true,
    explanation:'أذكار الصباح والمساء تحفظ المسلم من الشرور والمصائب والأمراض بإذن الله.',
    goldenRule:'الأذكار = حفظ + وقاية + أمان من الشرور.',
    feedbackQuestion:{question:'هل تحفظ الأذكار من الشرور؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'بعض الأحيان',correct:false},{text:'لا أعرف',correct:false}]} },
  { id:'adk1q26', unit:'u5', lesson:'u5l1', page:46, type:'ordering', bloom:'apply', difficulty:'medium',
    question:'رتّب أذكار الصباح عند الاستيقاظ:',
    paragraph:'أذكار الصباح عند الاستيقاظ: المعوذات + سيد الاستغفار + أذكار الحفظ. (ص46)',
    items:['أذكار الحفظ','المعوذات الثلاث','سيد الاستغفار'],
    correctOrder:[1,2,0],
    explanation:'أذكار الصباح: المعوذات الثلاث ← سيد الاستغفار ← أذكار الحفظ.',
    goldenRule:'ترتيب الأذكار: معوذات + استغفار + حفظ.' },
  { id:'adk1q27', unit:'u5', lesson:'u5l1', page:46, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'الذكر يُشرح به:',
    paragraph:'الذكر يُشرح به الصدر ويُطيب النفس. (ص46)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'الصدر ويُطيب النفس',correct:true},{text:'الرأس فقط',correct:false},{text:'العين',correct:false},{text:'لا شيء',correct:false}],
    explanation:'الذكر يُشرح به الصدر ويُطيب النفس ويُذهب الهم والقلق.',
    goldenRule:'الذكر = شرح صدر + طيب نفس + ذهاب قلق.',
    feedbackQuestion:{question:'ماذا يُشرح الذكر؟',options:[{text:'الصدر',correct:true},{text:'الرأس',correct:false},{text:'العين',correct:false},{text:'لا شيء',correct:false}]} },
  { id:'adk1q28', unit:'u5', lesson:'u5l1', page:46, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'سيد الاستغفار يُقال:',
    paragraph:'سيد الاستغفار يُقال في الصباح والمساء. (ص46)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'صباحاً ومساءً',correct:true},{text:'في الليل فقط',correct:false},{text:'في النوم',correct:false},{text:'لا يقال',correct:false}],
    explanation:'سيد الاستغفار يُقال صباحاً ومساءً ويعدل عظيم الأجر.',
    goldenRule:'سيد الاستغفار = صباح + مساء = محو ذنوب + أجر.',
    feedbackQuestion:{question:'متى يُقال سيد الاستغفار؟',options:[{text:'صباحاً ومساءً',correct:true},{text:'الليل',correct:false},{text:'النوم',correct:false},{text:'لا يقال',correct:false}]} },
  { id:'adk1q29', unit:'u5', lesson:'u5l1', page:46, type:'multipleChoice', bloom:'create', difficulty:'hard',
    question:'ركّب جملة فيها: معوذات + استغفار + ذكر الصباح:',
    paragraph:'أذكار الصباح: معوذات + استغفار + ذكر. (ص46)',
    options:[
      {text:'أقول المعوذات وسيد الاستغفار وأذكار الصباح',correct:true},
      {text:'أنام وألعب',correct:false},
      {text:'أصرخ وأتجاهل',correct:false},
      {text:'أنصرف',correct:false},
    ],
    explanation:'الجملة: أقول المعوذات وسيد الاستغفار وأذكار الصباح.',
    goldenRule:'الجملة الكاملة: معوذات + استغفار + ذكر.' },
  { id:'adk1q30', unit:'u5', lesson:'u5l1', page:46, type:'multipleChoice', bloom:'evaluate', difficulty:'hard',
    question:'ما الفرق بين أذكار الصباح وأذكار المساء؟',
    paragraph:'أذكار الصباح بعد الفجر، وأذكار المساء بعد العصر. (ص46)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'الوقت: الصباح بعد الفجر، المساء بعد العصر',correct:true},{text:'لا فرق',correct:false},{text:'الكل بعد النوم',correct:false},{text:'لا أعرف',correct:false}],
    explanation:'الفرق في الوقت: أذكار الصباح بعد الفجر، وأذكار المساء بعد العصر.',
    goldenRule:'الفرق = الوقت: صباح (فجر) + مساء (عصر).',
    feedbackQuestion:{question:'ما الفرق بين أذكار الصباح والمساء؟',options:[{text:'الوقت',correct:true},{text:'لا فرق',correct:false},{text:'العدد',correct:false},{text:'لا أعرف',correct:false}]} },
  { id:'adk1q31', unit:'u5', lesson:'u5l1', page:46, type:'classify', bloom:'analyze', difficulty:'medium',
    question:'صنّف: أذكار صباح ومساء أم أذكار نوم؟',
    paragraph:'أذكار الصباح والمساء: المعوذات + الاستغفار. أذكار النوم: آية الكرسي. (ص46-50)',
    categories:['أذكار صباح ومساء 🌅','أذكار نوم 🌙'],
    items:[
      {text:'المعوذات',correct_category:0},{text:'سيد الاستغفار',correct_category:0},
      {text:'آية الكرسي قبل النوم',correct_category:1},{text:'«بسم الله الذي لا يضر»',correct_category:0},
      {text:'«اللهم بك أمسينا»',correct_category:0},{text:'«اللهم قني عذابك»',correct_category:1},
    ],
    explanation:'الصباح والمساء: معوذات + استغفار + بسم الله. النوم: آية الكرسي + اللهم قني عذابك.',
    goldenRule:'لكل وقت أذكاره: صباح/مساء + نوم.' },
  { id:'adk1q32', unit:'u5', lesson:'u5l1', page:46, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'اللهم عافني في بدني وسمعي وبصري تُقال:',
    paragraph:'«اللهم عافني في بدني، اللهم عافني في سمعي، اللهم عافني في بصري». (ص46)',
    options:[{text:'ثلاث مرات صباحاً ومساءً',correct:true},{text:'مرة واحدة',correct:false},{text:'عشر مرات',correct:false},{text:'لا تقال',correct:false}],
    explanation:'«اللهم عافني في بدني وسمعي وبصري» تُقال ثلاثاً صباحاً ومساءً.',
    goldenRule:'اللهم عافني = بدني + سمعي + بصري — ثلاثاً.',
    feedbackQuestion:{question:'كم مرة تُقال «اللهم عافني»؟',options:[{text:'ثلاث مرات',correct:true},{text:'مرة',correct:false},{text:'عشر',correct:false},{text:'لا تقال',correct:false}]} },
  { id:'adk1q33', unit:'u5', lesson:'u5l1', page:46, type:'trueFalse', bloom:'understand', difficulty:'easy',
    question:'الذكر يأتي بالرزق ويحيي القلب.',
    paragraph:'الذكر يأتي بالرزق ويحيي القلب. (ص46)',
    correctAnswer:true,
    explanation:'الذكر يأتي بالرزق ويحيي القلب كما جاء في فضائل الذكر.',
    goldenRule:'الذكر = رزق + حياة قلب + خير.',
    feedbackQuestion:{question:'هل الذكر يأتي بالرزق؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'بعض الأحيان',correct:false},{text:'لا أعرف',correct:false}]} },
  { id:'adk1q34', unit:'u5', lesson:'u5l1', page:46, type:'multipleChoice', bloom:'apply', difficulty:'medium',
    question:'إذا أردت حفظ أهل بيتك في الصباح، تقول:',
    paragraph:'أذكار الصباح تحفظ من الشرور. (ص46)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'المعوذات الثلاث على أهل البيت',correct:true},{text:'لا شيء',correct:false},{text:'أناشيد',correct:false},{text:'أنام',correct:false}],
    explanation:'تقول المعوذات الثلاث (الإخلاص + الفلق + الناس) على أهل البيت صباحاً لتحفظهم.',
    goldenRule:'حفظ الأهل = معوذات ثلاث + صباح + نفث.',
    feedbackQuestion:{question:'كيف تحفظ أهل بيتك صباحاً؟',options:[{text:'أقول المعوذات عليهم',correct:true},{text:'لا شيء',correct:false},{text:'أناشيد',correct:false},{text:'أنام',correct:false}]} },
  { id:'adk1q35', unit:'u5', lesson:'u5l1', page:46, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'الذكر يُذهب الذنوب كما:',
    paragraph:'الذكر يمحو الذنوب ويُطيب النفس. (ص46)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'يمحو الذنوب ويُطيب النفس',correct:true},{text:'يضاعفها',correct:false},{text:'لا أثر',correct:false},{text:'يضر',correct:false}],
    explanation:'الذكر يمحو الذنوب ويُطيب النفس ويقرب من الله.',
    goldenRule:'الذكر = محو ذنوب + طيب نفس + تقريب من الله.',
    feedbackQuestion:{question:'ماذا يفعل الذكر بالذنوب؟',options:[{text:'يمحوها',correct:true},{text:'يضاعفها',correct:false},{text:'لا أثر',correct:false},{text:'يضر',correct:false}]} },
  { id:'adk1q36', unit:'u5', lesson:'u5l1', page:46, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'«رضيت بالله رباً» تُقال:',
    paragraph:'«رضيت بالله رباً وبالإسلام ديناً وبمحمد ﷺ نبياً» ثلاثاً. (ص46)',
    options:[{text:'ثلاث مرات صباحاً ومساءً',correct:true},{text:'مرة واحدة',correct:false},{text:'عشر مرات',correct:false},{text:'لا تقال',correct:false}],
    explanation:'«رضيت بالله رباً...» تُقال ثلاث مرات صباحاً ومساءً.',
    goldenRule:'رضيت بالله رباً = ثلاثاً = رضا + يقين + أجر.',
    feedbackQuestion:{question:'كم مرة تُقال «رضيت بالله رباً»؟',options:[{text:'ثلاث مرات',correct:true},{text:'مرة',correct:false},{text:'عشر',correct:false},{text:'لا تقال',correct:false}]} },
  { id:'adk1q37', unit:'u5', lesson:'u5l1', page:46, type:'multipleChoice', bloom:'evaluate', difficulty:'hard',
    question:'لماذا يُسمى سيد الاستغفار بهذا الاسم؟',
    paragraph:'سيد الاستغفار يُسمى سيد الاستغفار لأنه أفضل صيغ الاستغفار. (ص46)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'لأنه أفضل صيغ الاستغفار وأكملها',correct:true},{text:'لأنه قصير',correct:false},{text:'لا سبب',correct:false},{text:'عادة',correct:false}],
    explanation:'سيد الاستغفار أفضل صيغ الاستغفار وأكملها لاشتماله على التوحيد والاعتراف بالذنب.',
    goldenRule:'سيد الاستغفار = أفضل استغفار = توحيد + اعتراف + توبة.',
    feedbackQuestion:{question:'لماذا يُسمى سيد الاستغفار؟',options:[{text:'لأنه أفضل صيغ الاستغفار',correct:true},{text:'قصير',correct:false},{text:'لا سبب',correct:false},{text:'عادة',correct:false}]} },
  { id:'adk1q38', unit:'u5', lesson:'u5l1', page:46, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'الذكر يقوي:',
    paragraph:'الذكر يقوي القلب والجسد. (ص46)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'القلب والجسد',correct:true},{text:'العين فقط',correct:false},{text:'الرأس',correct:false},{text:'لا شيء',correct:false}],
    explanation:'الذكر يقوي القلب والجسد ويشرح الصدر ويُذهب الهم.',
    goldenRule:'الذكر = قوة قلب + قوة جسد + شرح صدر.',
    feedbackQuestion:{question:'ماذا يقوي الذكر؟',options:[{text:'القلب والجسد',correct:true},{text:'العين',correct:false},{text:'الرأس',correct:false},{text:'لا شيء',correct:false}]} },
  { id:'adk1q39', unit:'u5', lesson:'u5l1', page:46, type:'multipleChoice', bloom:'create', difficulty:'hard',
    question:'اكتب جملة فيها: معوذات + سيد الاستغفار:',
    paragraph:'أذكار الصباح: المعوذات + سيد الاستغفار. (ص46)',
    options:[
      {text:'أقول المعوذات وسيد الاستغفار صباحاً',correct:true},
      {text:'أنام وأنسى',correct:false},
      {text:'أصرخ',correct:false},
      {text:'أنصرف',correct:false},
    ],
    explanation:'الجملة: أقول المعوذات وسيد الاستغفار صباحاً.',
    goldenRule:'الجملة الكاملة: معوذات + استغفار + صباح.' },
  { id:'adk1q40', unit:'u5', lesson:'u5l1', page:46, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'اللهم بك أصبحنا وبك أمسينا وبك نحيا وبك نموت وإليك:',
    paragraph:'«اللهم بك أصبحنا وبك أمسينا وبك نحيا وبك نموت وإليك النشور». (ص46)',
    options:[{text:'النشور',correct:true},{text:'الرجوع',correct:false},{text:'الموت',correct:false},{text:'الخلود',correct:false}],
    explanation:'الذكر: «اللهم بك أصبحنا وبك أمسينا وبك نحيا وبك نموت وإليك النشور».',
    goldenRule:'اللهم بك أصبحنا = إقرار بقدرة الله + توكل + رجوع.',
    feedbackQuestion:{question:'بماذا يكمل «وإليك»؟',options:[{text:'النشور',correct:true},{text:'الرجوع',correct:false},{text:'الموت',correct:false},{text:'الخلود',correct:false}]} },
  { id:'adk1q41', unit:'u5', lesson:'u5l1', page:46, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'الذكر يجلب:',
    paragraph:'الذكر يجلب الرزق والمحبة ويُحيي القلب. (ص46)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'الرزق والمحبة وحياة القلب',correct:true},{text:'الفقر',correct:false},{text:'المرض',correct:false},{text:'الهم',correct:false}],
    explanation:'الذكر يجلب الرزق والمحبة وحياة القلب ويُذهب الهم.',
    goldenRule:'الذكر = رزق + محبة + حياة قلب + ذهاب هم.',
    feedbackQuestion:{question:'ماذا يجلب الذكر؟',options:[{text:'الرزق والمحبة',correct:true},{text:'الفقر',correct:false},{text:'المرض',correct:false},{text:'الهم',correct:false}]} },
  { id:'adk1q42', unit:'u5', lesson:'u5l1', page:46, type:'trueFalse', bloom:'apply', difficulty:'medium',
    question:'من ترك أذكار الصباح والمساء فاته فضل كبير.',
    paragraph:'أذكار الصباح والمساء لها فضل عظيم. (ص46)',
    correctAnswer:true,
    explanation:'من ترك أذكار الصباح والمساء فاته فضل كبير من الحفظ والأجر والقرب من الله.',
    goldenRule:'ترك الأذكار = فوت فضل + فقد حفظ + نقص أجر.',
    feedbackQuestion:{question:'هل من ترك الأذكار فاته فضل؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'بعض الأحيان',correct:false},{text:'لا أعرف',correct:false}]} },
  { id:'adk1q43', unit:'u5', lesson:'u5l1', page:46, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'سورة الفلق تُقال للتحرز من:',
    paragraph:'سورة الفلق تُقال للتحرز من شرور الخلق والمخلوقات. (ص46)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'شر الخلق والخلق والمخلوقات',correct:true},{text:'الفقر',correct:false},{text:'المرض فقط',correct:false},{text:'لا شيء',correct:false}],
    explanation:'سورة الفلق تُقال للتحرز من شر الخلق والخلق والمخلوقات والشرور.',
    goldenRule:'الفلق = تحرز من شرور + حفظ + وقاية.',
    feedbackQuestion:{question:'مم تُقال سورة الفلق؟',options:[{text:'للتحرز من الشرور',correct:true},{text:'الفقر',correct:false},{text:'المرض فقط',correct:false},{text:'لا شيء',correct:false}]} },
  { id:'adk1q44', unit:'u5', lesson:'u5l1', page:46, type:'multipleChoice', bloom:'evaluate', difficulty:'hard',
    question:'ما الجامع بين أذكار الصباح والمساء؟',
    paragraph:'أذكار الصباح والمساء كلها ذكر ودعاء. (ص46)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'كلها ذكر ودعاء وحفظ من الله',correct:true},{text:'لا جامع',correct:false},{text:'كلها للّعب',correct:false},{text:'لا علاقة',correct:false}],
    explanation:'الجامع: كلها ذكر ودعاء وحفظ من الله وتقرب من الله.',
    goldenRule:'أذكار الصباح والمساء = ذكر + دعاء + حفظ + تقرب.',
    feedbackQuestion:{question:'ما الجامع بين أذكار الصباح والمساء؟',options:[{text:'الذكر والدعاء والحفظ',correct:true},{text:'لا شيء',correct:false},{text:'اللعب',correct:false},{text:'لا علاقة',correct:false}]} },
  { id:'adk1q45', unit:'u5', lesson:'u5l1', page:46, type:'matching', bloom:'understand', difficulty:'medium',
    question:'صِل كل ذكر بعدده:',
    paragraph:'أعداد الأذكار: معوذات ثلاثاً، سبحان الله وبحمده مائة، رضيت بالله ثلاثاً. (ص46)',
    pairs:[
      {left:'المعوذات',right:'ثلاث مرات'},
      {left:'سبحان الله وبحمده',right:'مائة مرة'},
      {left:'رضيت بالله رباً',right:'ثلاث مرات'},
      {left:'بسم الله الذي لا يضر',right:'ثلاث مرات'},
    ],
    explanation:'المعوذات ثلاثاً، سبحان الله وبحمده مائة، رضيت ثلاثاً، بسم الله ثلاثاً.',
    goldenRule:'لكل ذكر عدد: معوذات (3) + تسبيح (100) + رضيت (3) + بسم (3).' },
  { id:'adk1q46', unit:'u5', lesson:'u5l1', page:46, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'سورة الناس تُقال للتحرز من:',
    paragraph:'سورة الناس تُقال للتحرز من شر الوسواس. (ص46)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'شر الوسواس الخناس',correct:true},{text:'الفقر',correct:false},{text:'المرض',correct:false},{text:'لا شيء',correct:false}],
    explanation:'سورة الناس تُقال للتحرز من شر الوسواس الخناس الذي يوسوس في صدور الناس.',
    goldenRule:'سورة الناس = تحرز من وسواس + حفظ + وقاية.',
    feedbackQuestion:{question:'مم تُقال سورة الناس؟',options:[{text:'من شر الوسواس',correct:true},{text:'الفقر',correct:false},{text:'المرض',correct:false},{text:'لا شيء',correct:false}]} },
  { id:'adk1q47', unit:'u5', lesson:'u5l1', page:46, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'أذكار المساء تُقال بعد:',
    paragraph:'أذكار المساء تُقال بعد العصر. (ص46)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'العصر',correct:true},{text:'الفجر',correct:false},{text:'النوم',correct:false},{text:'الظهر',correct:false}],
    explanation:'أذكار المساء تُقال بعد العصر في المساء.',
    goldenRule:'أذكار المساء = بعد العصر.',
    feedbackQuestion:{question:'متى تُقال أذكار المساء؟',options:[{text:'بعد العصر',correct:true},{text:'بعد الفجر',correct:false},{text:'النوم',correct:false},{text:'الظهر',correct:false}]} },
  { id:'adk1q48', unit:'u5', lesson:'u5l1', page:46, type:'trueFalse', bloom:'evaluate', difficulty:'hard',
    question:'الذاكرون الله كثيراً والذاكرات أعدَّ الله لهم مغفرة وأجراً عظيماً.',
    paragraph:'الذكر محبوب لله ويأتي بالأجر العظيم. (ص46)',
    correctAnswer:true,
    explanation:'الله أعد للذاكرين والذاكرات مغفرة وأجراً عظيماً كما في القرآن الكريم.',
    goldenRule:'الذاكر الله كثيراً = مغفرة + أجر عظيم + جنة.',
    feedbackQuestion:{question:'ماذا أعدَّ الله للذاكرين؟',options:[{text:'مغفرة وأجر عظيم',correct:true},{text:'لا شيء',correct:false},{text:'عذاب',correct:false},{text:'فقر',correct:false}]} },
  { id:'adk1q49', unit:'u5', lesson:'u5l1', page:46, type:'multipleChoice', bloom:'apply', difficulty:'medium',
    question:'إذا أردت أن تحفظ نفسك قبل النوم، تقول:',
    paragraph:'أذكار النوم تُقال قبل النوم للحفظ. (ص46-50)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'أذكار النوم كآية الكرسي',correct:true},{text:'أذكار الصباح',correct:false},{text:'أناشيد',correct:false},{text:'لا شيء',correct:false}],
    explanation:'قبل النوم تقول أذكار النوم كآية الكرسي والمعوذات للحفظ في النوم.',
    goldenRule:'قبل النوم = آية الكرسي + معوذات + حفظ.',
    feedbackQuestion:{question:'ماذا تقول قبل النوم؟',options:[{text:'أذكار النوم',correct:true},{text:'أذكار الصباح',correct:false},{text:'أناشيد',correct:false},{text:'لا شيء',correct:false}]} },
  { id:'adk1q50', unit:'u5', lesson:'u5l1', page:46, type:'multipleChoice', bloom:'create', difficulty:'hard',
    question:'ركّب جملة فيها: معوذات + استغفار + ذكر الصباح:',
    paragraph:'أذكار الصباح والمساء. (ص46)',
    options:[
      {text:'أقول المعوذات الثلاث وسيد الاستغفار وأذكار الصباح',correct:true},
      {text:'أنام وألعب',correct:false},
      {text:'أصرخ',correct:false},
      {text:'أنسى',correct:false},
    ],
    explanation:'الجملة: أقول المعوذات الثلاث وسيد الاستغفار وأذكار الصباح.',
    goldenRule:'الجملة الكاملة: معوذات + استغفار + أذكار صباح.' },
];

export default ADHKAR_L1;