// التربية الإسلامية - الصف الثاني الابتدائي - الفصل الأول
// كتاب التوحيد — الوحدة الثانية: العبادة وما يضادها من الشرك
// 4 دروس: لماذا خلقنا الله + العبادة + عبادة الله وحده + عبادة غير الله شرك

export const TAWHEED_U2 = [
  { id:'tw2q1', unit:'tw2', lesson:'tw2l1', page:18, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'خلقنا الله لـ:',
    paragraph:'خلقنا الله لنعبده ولا نشرك به شيئاً. (ص18)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'نعبده ولا نشرك به شيئاً',correct:true},{text:'نلعب',correct:false},{text:'ننام',correct:false},{text:'نأكل',correct:false}],
    explanation:'خلقنا الله لعبادته وحده لا شريك له، ولم يخلقنا عبثاً.',
    goldenRule:'الخلق = عبادة الله + لا شرك + غاية + حكمة.',
    feedbackQuestion:{question:'لماذا خلقنا الله؟',options:[{text:'نعبده وحده',correct:true},{text:'نلعب',correct:false},{text:'ننام',correct:false},{text:'نأكل',correct:false}]} },
  { id:'tw2q2', unit:'tw2', lesson:'tw2l1', page:18, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'قال تعالى: «وما خلقت الجن والإنس إلا ليعبدون» — «إلا ليعبدون» تعني:',
    paragraph:'قال تعالى: «وَمَا خَلَقْتُ الْجِنَّ وَالْإِنْسَ إِلَّا لِيَعْبُدُونِ». (ص18)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'لعبادة الله وحده',correct:true},{text:'للّعب',correct:false},{text:'للنوم',correct:false},{text:'للأكل',correct:false}],
    explanation:'«إلا ليعبدون» تعني أن الله خلق الجن والإنس لعبادته وحده.',
    goldenRule:'إلا ليعبدون = عبادة الله + غاية الخلق + توحيد + لا شرك.',
    feedbackQuestion:{question:'ماذا تعني «إلا ليعبدون»؟',options:[{text:'لعبادة الله',correct:true},{text:'للّعب',correct:false},{text:'للنوم',correct:false},{text:'للأكل',correct:false}]} },
  { id:'tw2q3', unit:'tw2', lesson:'tw2l1', page:19, type:'trueFalse', bloom:'understand', difficulty:'easy',
    question:'لم يخلقنا الله عبثاً بلا غاية.',
    paragraph:'خلقنا الله لغاية عظيمة وهي عبادته. (ص18)',
    correctAnswer:true,
    explanation:'لم يخلقنا الله عبثاً بل لغاية عظيمة وهي عبادته وحده.',
    goldenRule:'الخلق = لغاية + لا عبث + عبادة + حكمة.',
    feedbackQuestion:{question:'هل خلقنا الله عبثاً؟',options:[{text:'لا، لعبادته',correct:true},{text:'نعم',correct:false},{text:'بعض الأحيان',correct:false},{text:'لا أعرف',correct:false}]} },
  { id:'tw2q4', unit:'tw2', lesson:'tw2l1', page:19, type:'multipleChoice', bloom:'apply', difficulty:'medium',
    question:'إذا أردت أن تعرف لماذا خلقت، فالجواب:',
    paragraph:'خلقنا الله لعبادته. (ص18)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'لعبادة الله وحده',correct:true},{text:'للّعب',correct:false},{text:'للأكل',correct:false},{text:'لا أعرف',correct:false}],
    explanation:'إذا أردت أن تعرف لماذا خلقت فالجواب: لعبادة الله وحده لا شريك له.',
    goldenRule:'لماذا خلقت = عبادة الله + لا شرك + غاية + حكمة.',
    feedbackQuestion:{question:'لماذا خلقت؟',options:[{text:'لعبادة الله',correct:true},{text:'للّعب',correct:false},{text:'للأكل',correct:false},{text:'لا أعرف',correct:false}]} },
  { id:'tw2q5', unit:'tw2', lesson:'tw2l2', page:22, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'العبادة هي:',
    paragraph:'العبادة: طاعة الله بفعل أوامره وترك نواهيه. (ص22)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'طاعة الله بفعل أوامره وترك نواهيه',correct:true},{text:'اللعب',correct:false},{text:'النوم',correct:false},{text:'الأكل',correct:false}],
    explanation:'العبادة هي طاعة الله بفعل أوامره وترك نواهيه حباً وتعظيماً.',
    goldenRule:'العبادة = طاعة + أوامر + ترك نواهي + حب + تعظيم.',
    feedbackQuestion:{question:'ما العبادة؟',options:[{text:'طاعة الله بفعل أوامره',correct:true},{text:'اللعب',correct:false},{text:'النوم',correct:false},{text:'الأكل',correct:false}]} },
  { id:'tw2q6', unit:'tw2', lesson:'tw2l2', page:22, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'من أنواع العبادة:',
    paragraph:'من العبادات: الصلاة، الصيام، الزكاة، الحج، الدعاء، الذكر. (ص22)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'الصلاة والصيام والزكاة',correct:true},{text:'اللعب',correct:false},{text:'النوم',correct:false},{text:'الأكل',correct:false}],
    explanation:'من أنواع العبادة: الصلاة + الصيام + الزكاة + الحج + الدعاء + الذكر + بر الوالدين.',
    goldenRule:'العبادات = صلاة + صيام + زكاة + حج + دعاء + ذكر.',
    feedbackQuestion:{question:'أي مما يلي من العبادات؟',options:[{text:'الصلاة',correct:true},{text:'اللعب',correct:false},{text:'النوم',correct:false},{text:'الأكل',correct:false}]} },
  { id:'tw2q7', unit:'tw2', lesson:'tw2l2', page:22, type:'trueFalse', bloom:'understand', difficulty:'easy',
    question:'الصلاة من أعظم العبادات.',
    paragraph:'الصلاة من أعظم العبادات. (ص22)',
    correctAnswer:true,
    explanation:'الصلاة من أعظم العبادات وهي عمود الإسلام.',
    goldenRule:'الصلاة = أعظم العبادات + عمود الإسلام + فريضة + طاعة.',
    feedbackQuestion:{question:'هل الصلاة من أعظم العبادات؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'بعض الأحيان',correct:false},{text:'لا أعرف',correct:false}]} },
  { id:'tw2q8', unit:'tw2', lesson:'tw2l2', page:23, type:'multipleChoice', bloom:'apply', difficulty:'medium',
    question:'إذا أطعت والديك، فأنت:',
    paragraph:'بر الوالدين من العبادة. (ص23)',
    image:'https://images.unsplash.com/photo-1581579188871-4e6f6a5e0c4e?w=600',
    options:[{text:'تعبد الله ببر الوالدين',correct:true},{text:'تؤذي',correct:false},{text:'تطعن',correct:false},{text:'لا شيء',correct:false}],
    explanation:'إذا أطعت والديك فأنت تعبد الله ببر الوالدين لأنه من العبادة.',
    goldenRule:'بر الوالدين = عبادة + طاعة + أجر + جنة.',
    feedbackQuestion:{question:'هل بر الوالدين عبادة؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'بعض الأحيان',correct:false},{text:'لا أعرف',correct:false}]} },
  { id:'tw2q9', unit:'tw2', lesson:'tw2l2', page:22, type:'classify', bloom:'analyze', difficulty:'medium',
    question:'صنّف: من العبادات أم لا؟',
    paragraph:'العبادات: صلاة + صيام + زكاة + حج + دعاء + ذكر. (ص22)',
    categories:['من العبادات 🤲','ليست من العبادات ❌'],
    items:[
      {text:'الصلاة',correct_category:0},{text:'اللعب',correct_category:1},
      {text:'الصيام',correct_category:0},{text:'النوم',correct_category:1},
      {text:'بر الوالدين',correct_category:0},{text:'الأكل بلا تسمية',correct_category:1},
    ],
    explanation:'من العبادات: صلاة + صيام + بر. ليست منها: لعب + نوم + أكل بلا تسمية.',
    goldenRule:'العبادات = طاعة + ذكر + صلاة + صيام.' },
  { id:'tw2q10', unit:'tw2', lesson:'tw2l2', page:23, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'العبادة ليست فقط صلاة، بل تشمل:',
    paragraph:'العبادة تشمل كل طاعة لله. (ص22-23)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'كل طاعة لله من صلاة وبر وذكر',correct:true},{text:'الصلاة فقط',correct:false},{text:'الأكل فقط',correct:false},{text:'اللعب',correct:false}],
    explanation:'العبادة ليست فقط صلاة، بل تشمل كل طاعة لله: صلاة + بر + ذكر + إحسان + حسن خلق.',
    goldenRule:'العبادة = كل طاعة + صلاة + بر + ذكر + إحسان + حسن خلق.',
    feedbackQuestion:{question:'هل العبادة فقط الصلاة؟',options:[{text:'لا، كل طاعة لله',correct:true},{text:'نعم',correct:false},{text:'بعض الأحيان',correct:false},{text:'لا أعرف',correct:false}]} },
  { id:'tw2q11', unit:'tw2', lesson:'tw2l3', page:26, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'عبادة الله وحده تعني:',
    paragraph:'أعبد الله وحده ولا أشرك به أحداً. (ص26)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'أن تعبد الله وحده ولا تشرك به',correct:true},{text:'أن تعبد غيره',correct:false},{text:'أن تعبد الأصنام',correct:false},{text:'أن تعبد الملائكة',correct:false}],
    explanation:'عبادة الله وحده تعني أن تعبده وحده ولا تشرك به أحداً لا ملكاً ولا نبياً.',
    goldenRule:'عبادة الله وحده = لا شرك + لا صنم + لا ولي + توحيد.',
    feedbackQuestion:{question:'ماذا تعني عبادة الله وحده؟',options:[{text:'أن تعبده وحده ولا تشرك به',correct:true},{text:'أن تعبد غيره',correct:false},{text:'أن تعبد الأصنام',correct:false},{text:'أن تعبد الملائكة',correct:false}]} },
  { id:'tw2q12', unit:'tw2', lesson:'tw2l3', page:26, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'إذا دعوت الله وحده فأنت:',
    paragraph:'أدعو الله وحده فأعبده. (ص26)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'تعبد الله وحده',correct:true},{text:'تشرك',correct:false},{text:'تؤذي',correct:false},{text:'لا شيء',correct:false}],
    explanation:'إذا دعوت الله وحده فأنت تعبده وحده ولا تشرك به أحداً.',
    goldenRule:'الدعاء لله = عبادة + توحيد + لا شرك + إخلاص.',
    feedbackQuestion:{question:'إذا دعوت الله وحده فماذا تفعل؟',options:[{text:'أعبد الله وحده',correct:true},{text:'أشرك',correct:false},{text:'أؤذي',correct:false},{text:'لا شيء',correct:false}]} },
  { id:'tw2q13', unit:'tw2', lesson:'tw2l3', page:27, type:'trueFalse', bloom:'understand', difficulty:'easy',
    question:'إخلاص العبادة لله وحده من التوحيد.',
    paragraph:'أخلص العبادة لله وحده. (ص26)',
    correctAnswer:true,
    explanation:'إخلاص العبادة لله وحده من التوحيد وهو أساس الإسلام.',
    goldenRule:'الإخلاص = توحيد + عبادة لله + لا شرك + أساس الإسلام.',
    feedbackQuestion:{question:'هل الإخلاص من التوحيد؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'بعض الأحيان',correct:false},{text:'لا أعرف',correct:false}]} },
  { id:'tw2q14', unit:'tw2', lesson:'tw2l3', page:27, type:'multipleChoice', bloom:'apply', difficulty:'medium',
    question:'إذا أردت حاجة، فتطلبها من:',
    paragraph:'أطلب حوائجي من الله وحده. (ص27)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'الله وحده',correct:true},{text:'الأصنام',correct:false},{text:'الأولياء',correct:false},{text:'الملائكة',correct:false}],
    explanation:'إذا أردت حاجة تطلبها من الله وحده لأنه القادر على كل شيء.',
    goldenRule:'طلب الحاجة = من الله وحده + دعاء + توحيد + لا شرك.',
    feedbackQuestion:{question:'ممن تطلب حاجتك؟',options:[{text:'من الله وحده',correct:true},{text:'الأصنام',correct:false},{text:'الأولياء',correct:false},{text:'الملائكة',correct:false}]} },
  { id:'tw2q15', unit:'tw2', lesson:'tw2l4', page:30, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'عبادة غير الله شرك:',
    paragraph:'عبادة غير الله شرك بالله. (ص30)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'من أعظم الذنوب',correct:true},{text:'عادة',correct:false},{text:'مكروه',correct:false},{text:'لا قيمة',correct:false}],
    explanation:'عبادة غير الله شرك بالله وهو من أعظم الذنوب وأكبر الكبائر.',
    goldenRule:'الشرك = عبادة غير الله + أعظم ذنب + لا مغفرة + نار.',
    feedbackQuestion:{question:'ما حكم عبادة غير الله؟',options:[{text:'شرك وأعظم الذنوب',correct:true},{text:'عادة',correct:false},{text:'مكروه',correct:false},{text:'لا قيمة',correct:false}]} },
  { id:'tw2q16', unit:'tw2', lesson:'tw2l4', page:30, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'الشرك بالله:',
    paragraph:'الشرك: عبادة غير الله. (ص30)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'أن تجعل لله شريكاً في عبادته',correct:true},{text:'أن تعبد الله',correct:false},{text:'أن تصلي',correct:false},{text:'أن تصوم',correct:false}],
    explanation:'الشرك أن تجعل لله شريكاً في عبادته كأن تدعو غيره أو تصلي لغيره.',
    goldenRule:'الشرك = شريك لله + دعاء غيره + صلاة لغيره + لا مغفرة.',
    feedbackQuestion:{question:'ما الشرك؟',options:[{text:'أن تجعل لله شريكاً',correct:true},{text:'أن تعبد الله',correct:false},{text:'أن تصلي',correct:false},{text:'أن تصوم',correct:false}]} },
  { id:'tw2q17', unit:'tw2', lesson:'tw2l4', page:31, type:'trueFalse', bloom:'understand', difficulty:'easy',
    question:'من أشرك بالله لا يغفر الله له إن مات على شركه.',
    paragraph:'الله لا يغفر الشرك إذا مات صاحبه عليه. (ص31)',
    correctAnswer:true,
    explanation:'من مات على الشرك لا يغفر الله له ويخلد في النار، أما غير الشرك فيغفره الله لمن يشاء.',
    goldenRule:'الشرك = لا مغفرة + خلود نار + أعظم ذنب + خطر.',
    feedbackQuestion:{question:'هل يغفر الله الشرك لمن مات عليه؟',options:[{text:'لا',correct:true},{text:'نعم',correct:false},{text:'بعض الأحيان',correct:false},{text:'لا أعرف',correct:false}]} },
  { id:'tw2q18', unit:'tw2', lesson:'tw2l4', page:31, type:'multipleChoice', bloom:'evaluate', difficulty:'hard',
    question:'لماذا الشرك أعظم الذنوب؟',
    paragraph:'الشرك أعظم الذنوب لأنه ظلم لله في حقه. (ص30)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'لأنه ظلم لله في أعظم حق له',correct:true},{text:'عادة',correct:false},{text:'لا سبب',correct:false},{text:'مكروه',correct:false}],
    explanation:'الشرك أعظم الذنوب لأنه ظلم لله في حقه على عباده أن يعبدوه وحده.',
    goldenRule:'الشرك = ظلم لله + أعظم ذنب + لا مغفرة + نار.',
    feedbackQuestion:{question:'لماذا الشرك أعظم الذنوب؟',options:[{text:'لأنه ظلم لله',correct:true},{text:'عادة',correct:false},{text:'لا سبب',correct:false},{text:'مكروه',correct:false}]} },
  { id:'tw2q19', unit:'tw2', lesson:'tw2l4', page:30, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'من أمثلة الشرك:',
    paragraph:'من الشرك: دعاء غير الله + الصلاة لغيره + النذر لغيره. (ص30)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'دعاء غير الله والصلاة لغيره',correct:true},{text:'الصلاة لله',correct:false},{text:'الدعاء لله',correct:false},{text:'الصيام لله',correct:false}],
    explanation:'من أمثلة الشرك: دعاء غير الله + الصلاة لغيره + النذر لغيره + الذبح لغيره.',
    goldenRule:'الشرك = دعاء غير الله + صلاة لغيره + نذر لغيره + ذبح لغيره.',
    feedbackQuestion:{question:'أي مما يلي من الشرك؟',options:[{text:'دعاء غير الله',correct:true},{text:'الصلاة لله',correct:false},{text:'الدعاء لله',correct:false},{text:'الصيام',correct:false}]} },
  { id:'tw2q20', unit:'tw2', lesson:'tw2l4', page:31, type:'classify', bloom:'analyze', difficulty:'medium',
    question:'صنّف: توحيد أم شرك؟',
    paragraph:'التوحيد: عبادة الله. الشرك: عبادة غير الله. (ص26-30)',
    categories:['توحيد ✅','شرك ❌'],
    items:[
      {text:'الدعاء لله',correct_category:0},{text:'الدعاء للأموات',correct_category:1},
      {text:'الصلاة لله',correct_category:0},{text:'الصلاة للأصنام',correct_category:1},
      {text:'الذبح لله',correct_category:0},{text:'النذر للأولياء',correct_category:1},
    ],
    explanation:'توحيد: دعاء + صلاة + ذبح لله. شرك: دعاء + صلاة + نذر لغير الله.',
    goldenRule:'التوحيد = لله وحده. الشرك = لغير الله.' },
  { id:'tw2q21', unit:'tw2', lesson:'tw2l1', page:18, type:'multipleChoice', bloom:'create', difficulty:'hard',
    question:'ركّب جملة فيها: خلق + عبادة + لا شرك:',
    paragraph:'خلقنا الله لعبادته لا لشركه. (ص18-26)',
    options:[
      {text:'خلقنا الله لنعبده ولا نشرك به',correct:true},
      {text:'خلقنا الله للّعب',correct:false},
      {text:'خلقنا الله للنوم',correct:false},
      {text:'لا شيء',correct:false},
    ],
    explanation:'الجملة: خلقنا الله لنعبده ولا نشرك به — غاية الخلق.',
    goldenRule:'الجملة الكاملة: خلق + عبادة + لا شرك.' },
  { id:'tw2q22', unit:'tw2', lesson:'tw2l2', page:22, type:'fillBlank', bloom:'apply', difficulty:'easy',
    question:'أكمل: الصلاة من ___.',
    paragraph:'الصلاة من أعظم العبادات. (ص22)',
    blanks:['العبادات'],
    wordBank:['العبادات','اللعب','النوم','الأكل'],
    explanation:'الصلاة من العبادات وأعظمها.',
    goldenRule:'الصلاة = عبادة + أعظم + عمود الإسلام.' },
  { id:'tw2q23', unit:'tw2', lesson:'tw2l3', page:27, type:'multipleChoice', bloom:'evaluate', difficulty:'hard',
    question:'ما أثر التوحيد على المسلم؟',
    paragraph:'التوحيد: عبادة الله وحده. (ص26)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'جنة وأجر وسعادة في الدنيا والآخرة',correct:true},{text:'لا شيء',correct:false},{text:'ضرر',correct:false},{text:'مكروه',correct:false}],
    explanation:'التوحيد يمنح المسلم جنة وأجراً وسعادة في الدنيا والآخرة.',
    goldenRule:'التوحيد = جنة + أجر + سعادة + نصر.',
    feedbackQuestion:{question:'ما أثر التوحيد؟',options:[{text:'جنة وأجر وسعادة',correct:true},{text:'لا شيء',correct:false},{text:'ضرر',correct:false},{text:'مكروه',correct:false}]} },
  { id:'tw2q24', unit:'tw2', lesson:'tw2l4', page:30, type:'matching', bloom:'understand', difficulty:'medium',
    question:'صِل كل فعل بحكمه:',
    paragraph:'توحيد = عبادة الله + أجر. شرك = عبادة غير الله + لا مغفرة. (ص26-30)',
    pairs:[
      {left:'الدعاء لله',right:'توحيد وأجر'},
      {left:'الدعاء لغير الله',right:'شرك وذنب'},
      {left:'الصلاة لله',right:'توحيد وأجر'},
      {left:'النذر للأموات',right:'شرك وذنب'},
    ],
    explanation:'لله = توحيد وأجر، لغير الله = شرك وذنب.',
    goldenRule:'لله = توحيد. لغير الله = شرك.' },
  { id:'tw2q25', unit:'tw2', lesson:'tw2l1', page:19, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'الآية «وما خلقت الجن والإنس إلا ليعبدون» في سورة:',
    paragraph:'قال تعالى: «وَمَا خَلَقْتُ الْجِنَّ وَالْإِنْسَ إِلَّا لِيَعْبُدُونِ». (ص18)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'الذاريات',correct:true},{text:'الفاتحة',correct:false},{text:'الإخلاص',correct:false},{text:'الفلق',correct:false}],
    explanation:'الآية «وما خلقت الجن والإنس إلا ليعبدون» في سورة الذاريات.',
    goldenRule:'الآية في الذاريات = غاية الخلق + عبادة + توحيد.',
    feedbackQuestion:{question:'في أي سورة آية «وما خلقت الجن والإنس إلا ليعبدون»؟',options:[{text:'الذاريات',correct:true},{text:'الفاتحة',correct:false},{text:'الإخلاص',correct:false},{text:'الفلق',correct:false}]} },
  { id:'tw2q26', unit:'tw2', lesson:'tw2l2', page:23, type:'trueFalse', bloom:'apply', difficulty:'medium',
    question:'إذا أطعت رسول الله ﷺ فأنت تعبد الله.',
    paragraph:'طاعة الرسول ﷺ من عبادة الله. (ص23)',
    correctAnswer:true,
    explanation:'إذا أطعت رسول الله ﷺ فأنت تعبد الله لأن طاعة الرسول من طاعة الله.',
    goldenRule:'طاعة الرسول = طاعة الله + عبادة + أجر + سنة.',
    feedbackQuestion:{question:'هل طاعة الرسول عبادة؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'بعض الأحيان',correct:false},{text:'لا أعرف',correct:false}]} },
  { id:'tw2q27', unit:'tw2', lesson:'tw2l3', page:26, type:'ordering', bloom:'apply', difficulty:'medium',
    question:'رتّب خطوات التوحيد:',
    paragraph:'التوحيد: إخلاص العبادة لله + لا شرك + دعاء الله وحده. (ص26-27)',
    items:['لا أشرك بالله','أعبد الله وحده','أدعو الله وحده'],
    correctOrder:[1,0,2],
    explanation:'التوحيد: أعبد الله وحده ← لا أشرك به ← أدعوه وحده.',
    goldenRule:'التوحيد = عبادة ← لا شرك ← دعاء.' },
  { id:'tw2q28', unit:'tw2', lesson:'tw2l4', page:31, type:'multipleChoice', bloom:'create', difficulty:'hard',
    question:'ركّب جملة فيها: توحيد + شرك + أجر:',
    paragraph:'التوحيد أجر والشرك ذنب. (ص26-31)',
    options:[
      {text:'التوحيد أجر والشرك ذنب لا يغفر',correct:true},
      {text:'التوحيد والشرك سواء',correct:false},
      {text:'لا فرق',correct:false},
      {text:'لا أعرف',correct:false},
    ],
    explanation:'الجملة: التوحيد أجر والشرك ذنب لا يغفر — فرق عظيم بينهما.',
    goldenRule:'الجملة الكاملة: توحيد + شرك + أجر.' },
  { id:'tw2q29', unit:'tw2', lesson:'tw2l2', page:22, type:'multipleChoice', bloom:'understand', difficulty:'medium',
    question:'العبادة تشمل:',
    paragraph:'العبادة: قول + فعل + ظاهر + باطن. (ص22-23)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'القول والفعل والظاهر والباطن',correct:true},{text:'الصلاة فقط',correct:false},{text:'الصيام فقط',correct:false},{text:'الأكل',correct:false}],
    explanation:'العبادة تشمل القول والفعل والظاهر والباطن — كل طاعة لله.',
    goldenRule:'العبادة = قول + فعل + ظاهر + باطن + طاعة.',
    feedbackQuestion:{question:'ماذا تشمل العبادة؟',options:[{text:'القول والفعل والظاهر والباطن',correct:true},{text:'الصلاة فقط',correct:false},{text:'الصيام فقط',correct:false},{text:'الأكل',correct:false}]} },
  { id:'tw2q30', unit:'tw2', lesson:'tw2l1', page:19, type:'multipleChoice', bloom:'evaluate', difficulty:'hard',
    question:'ماذا يحدث لمن عرف غاية خلقه (العبادة)؟',
    paragraph:'من عرف غاية الخلق حقق سعادته. (ص18-19)',
    image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=600',
    options:[{text:'سعادة في الدنيا والجنة في الآخرة',correct:true},{text:'لا شيء',correct:false},{text:'ضرر',correct:false},{text:'مكروه',correct:false}],
    explanation:'من عرف غاية خلقه (العبادة) وعمل بها حقق سعادة الدنيا والجنة في الآخرة.',
    goldenRule:'معرفة الغاية = سعادة دنيا + جنة آخرة + أجر + رضا.',
    feedbackQuestion:{question:'ماذا يحدث لمن عرف غاية خلقه؟',options:[{text:'سعادة وجنة',correct:true},{text:'لا شيء',correct:false},{text:'ضرر',correct:false},{text:'مكروه',correct:false}]} },
];

export default TAWHEED_U2;