// بنك أسئلة المهارات الحياتية والأسرية — الصف الثالث الابتدائي — الفصل الأول 1447
// مرجع: كتاب المهارات الحياتية والأسرية ط 2025 وزارة التعليم السعودية

export const LS3_S1_META = {
  subject: 'المهارات الحياتية والأسرية',
  grade: 'الصف الثالث الابتدائي',
  semester: 'الفصل الأول',
  year: '1447 هـ / 2025 م',
  publisher: 'وزارة التعليم — المملكة العربية السعودية',
};

export const LS3_S1_UNITS = [
  {
    id: 'u1',
    title_ar: 'الوحدة الأولى: صحتي وسلامتي',
    icon: '🏥',
    color: '#0891b2',
    lessons: [
      { id: 'u1l1', title_ar: 'رموز السلامة', page: '2-16' },
      { id: 'u1l2', title_ar: 'قوامي الصحيح', page: '17-29' },
      { id: 'u1l3', title_ar: 'الدواء', page: '30-35' },
      { id: 'u1l4', title_ar: 'الحمل الصحيح', page: '36-44' },
    ],
  },
  {
    id: 'u2',
    title_ar: 'الوحدة الثانية: شخصيتي',
    icon: '👤',
    color: '#7c3aed',
    lessons: [
      { id: 'u2l1', title_ar: 'كيف أتصرف إذا خرجت أمي من المنزل؟', page: '46-54' },
      { id: 'u2l2', title_ar: 'كيف أتصرف بملابسي التي لا أحتاجها؟', page: '55-63' },
    ],
  },
  {
    id: 'u3',
    title_ar: 'الوحدة الثالثة: وقتي',
    icon: '⏰',
    color: '#059669',
    lessons: [
      { id: 'u3l1', title_ar: 'الساعة', page: '65-79' },
    ],
  },
];

export const LS3_S1_QUESTIONS = [

  // ══════════════════════════════════════════════════════
  // الوحدة الأولى: صحتي وسلامتي
  // ══════════════════════════════════════════════════════

  // ── درس 1: رموز السلامة ──────────────────────────────

  {
    id: 'ls3_001', unit: 'u1', lesson: 'u1l1', page: 3, difficulty: 'easy',
    type: 'multipleChoice',
    question: 'ما الهدف من رموز السلامة الإرشادية؟',
    options: [
      { text: 'للزينة والتجميل فقط', correct: false },
      { text: 'توصيل تعليمات السلامة بطريقة موحدة مفهومة للجميع في كل العالم', correct: true },
      { text: 'تعليم الأطفال الألوان', correct: false },
      { text: 'الإعلان عن المنتجات التجارية', correct: false },
    ],
    explanation: 'الرموز الإرشادية موحدة في جميع أنحاء العالم وتهدف إلى توصيل تعليمات السلامة بطريقة مفهومة للجميع بغض النظر عن اللغة.',
    goldenRule: 'رموز السلامة لغة عالمية يفهمها الجميع.',
    paragraph: 'رموز وإشارات السلامة — ص ٣',
  },
  {
    id: 'ls3_002', unit: 'u1', lesson: 'u1l1', page: 4, difficulty: 'easy',
    type: 'trueFalse',
    question: 'الوقوف والمشي الصحيحان يؤديان إلى اعتدال القامة.',
    correctAnswer: 'true',
    explanation: 'الوقوف والمشي بطريقة صحيحة يُؤدي إلى اعتدال قامة الإنسان وصحة عموده الفقري.',
    goldenRule: 'القوام الصحيح يبدأ من طريقة وقوفك ومشيك.',
    paragraph: 'الوقوف والمشي الصحيحان يؤديان إلى اعتدال قامتك — ص ٤',
  },
  {
    id: 'ls3_003', unit: 'u1', lesson: 'u1l1', page: 5, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'ما دلالة اتباع مدلولات الرموز الإرشادية؟',
    options: [
      { text: 'يدل على الخوف', correct: false },
      { text: 'يدل على الوعي', correct: true },
      { text: 'يدل على الجهل', correct: false },
      { text: 'يدل على المرض', correct: false },
    ],
    explanation: 'اتباع مدلولات الرموز الإرشادية يدل على الوعي بقواعد السلامة والمسؤولية الشخصية.',
    goldenRule: 'اتباع الرموز الإرشادية = وعي وسلامة.',
    paragraph: 'اتباع مدلولات الرموز الإرشادية يدل على الوعي — ص ٥',
  },
  {
    id: 'ls3_004', unit: 'u1', lesson: 'u1l1', page: 8, difficulty: 'medium',
    type: 'classify',
    question: 'صنّف الرموز التالية حسب نوعها:',
    categories: ['رموز حظر ومنع', 'رموز إرشاد وتوجيه'],
    items: [
      { text: 'علامة ممنوع التدخين', correct_category: 0 },
      { text: 'علامة ممنوع الدخول', correct_category: 0 },
      { text: 'علامة مخرج الطوارئ', correct_category: 1 },
      { text: 'علامة أولويات الطريق', correct_category: 1 },
    ],
    explanation: 'رموز الحظر تمنع فعلاً معيناً، أما رموز الإرشاد فتوجه الشخص إلى الاتجاه الصحيح أو الإجراء المطلوب.',
    goldenRule: 'تعلّم رموز السلامة يحميك من الأخطار.',
    paragraph: 'رموز السلامة المختلفة — ص ٨',
  },
  {
    id: 'ls3_005', unit: 'u1', lesson: 'u1l1', page: 10, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'ما الصواب في التصرف عند وجود رموز حظر؟',
    options: [
      { text: 'تجاهل الرمز إذا لم يكن هناك حارس', correct: false },
      { text: 'الالتزام بالرمز في جميع الأحوال', correct: true },
      { text: 'اتباع الرمز عند وجود الآخرين فقط', correct: false },
      { text: 'التساؤل عن جدوى الرمز أولاً', correct: false },
    ],
    explanation: 'يجب الالتزام برموز الحظر والسلامة في جميع الأحوال لأنها وُضعت لحماية الجميع.',
    goldenRule: 'الالتزام برموز السلامة واجب دائم وليس اختيارياً.',
    paragraph: 'رموز السلامة الدولية — ص ١٠',
  },
  {
    id: 'ls3_006', unit: 'u1', lesson: 'u1l1', page: 12, difficulty: 'easy',
    type: 'trueFalse',
    question: 'رموز السلامة موحدة في جميع أنحاء العالم.',
    correctAnswer: 'true',
    explanation: 'نعم، رموز السلامة موحدة عالمياً حتى يستطيع أي شخص في أي مكان في العالم فهمها دون الحاجة إلى معرفة لغة معينة.',
    goldenRule: 'توحيد الرموز يجعلها لغة عالمية مشتركة.',
    paragraph: 'رموز السلامة موحدة في جميع أنحاء العالم — ص ١٢',
  },
  {
    id: 'ls3_007', unit: 'u1', lesson: 'u1l1', page: 14, difficulty: 'medium',
    type: 'ordering',
    question: 'رتّب الخطوات الصحيحة عند رؤية علامة الخطر:',
    items: [
      'ابتعد عن المنطقة الخطرة فوراً',
      'توقف وانتبه للعلامة',
      'أخبر المسؤولين إذا لزم الأمر',
      'اقرأ العلامة وافهم معناها',
    ],
    correctOrder: [1, 3, 0, 2],
    explanation: 'الخطوة الأولى: التوقف والانتباه → قراءة العلامة → الابتعاد عن الخطر → إخبار المسؤولين.',
    goldenRule: 'توقف → اقرأ → ابتعد → بلّغ.',
    paragraph: 'علامات الخطر والتحذير — ص ١٤',
  },

  // ── درس 2: قوامي الصحيح ──────────────────────────────

  {
    id: 'ls3_008', unit: 'u1', lesson: 'u1l2', page: 17, difficulty: 'easy',
    type: 'multipleChoice',
    question: 'ما تعريف القوام الصحيح؟',
    options: [
      { text: 'الوقوف والجلوس والمشي بطريقة تحافظ على صحة الجسم وشكله', correct: true },
      { text: 'ممارسة الرياضة يومياً فقط', correct: false },
      { text: 'الأكل الصحي والنوم المبكر فقط', correct: false },
      { text: 'ارتداء الملابس المناسبة', correct: false },
    ],
    explanation: 'القوام الصحيح هو اعتدال الجسم في الوقوف والجلوس والمشي بطريقة تحافظ على صحة العمود الفقري وشكل الجسم.',
    goldenRule: 'القوام الصحيح = الوقوف + الجلوس + المشي بطريقة صحيحة.',
    paragraph: 'قوامي الصحيح — ص ١٧',
  },
  {
    id: 'ls3_009', unit: 'u1', lesson: 'u1l2', page: 19, difficulty: 'medium',
    type: 'trueFalse',
    question: 'يمكن الجلوس أمام الكمبيوتر بأي طريقة لأن ذلك لا يؤثر على القوام.',
    correctAnswer: 'false',
    explanation: 'يجب الجلوس أمام الكمبيوتر بطريقة صحيحة: ظهر مستقيم، وكتفان للخلف، وعيون في مستوى الشاشة، وذلك للحفاظ على القوام.',
    goldenRule: 'الجلوس الصحيح أمام الشاشة يحمي عمودك الفقري.',
    paragraph: 'الجلوس الصحيح أمام الكمبيوتر — ص ١٩',
  },
  {
    id: 'ls3_010', unit: 'u1', lesson: 'u1l2', page: 20, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'ما الوضع الصحيح للجلوس على الكرسي؟',
    options: [
      { text: 'الاستناد للأمام والانحناء على المكتب', correct: false },
      { text: 'الظهر مستقيم والقدمان على الأرض والكتفان للخلف', correct: true },
      { text: 'مد الرجلين أمام الجسم', correct: false },
      { text: 'الجلوس على طرف الكرسي فقط', correct: false },
    ],
    explanation: 'الجلوس الصحيح: ظهر مستقيم مستند للكرسي، قدمان على الأرض، كتفان للخلف، ورأس في وضع طبيعي.',
    goldenRule: 'ظهر مستقيم + قدمان على الأرض + كتفان للخلف = جلوس صحيح.',
    paragraph: 'الجلوس الصحيح — ص ٢٠',
  },
  {
    id: 'ls3_011', unit: 'u1', lesson: 'u1l2', page: 22, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'ما الوضع الصحيح لحمل الحقيبة المدرسية؟',
    options: [
      { text: 'على كتف واحد فقط دائماً', correct: false },
      { text: 'على الكتفين معاً بحزام معتدل الضغط', correct: true },
      { text: 'باليد الواحدة فقط', correct: false },
      { text: 'جر الحقيبة على الأرض', correct: false },
    ],
    explanation: 'يجب حمل الحقيبة المدرسية على الكتفين معاً بحزام معتدل لتوزيع الحمل بالتساوي وعدم الإضرار بالعمود الفقري.',
    goldenRule: 'الحقيبة على الكتفين معاً = حماية العمود الفقري.',
    paragraph: 'حمل الحقيبة المدرسية — ص ٢٢',
  },
  {
    id: 'ls3_012', unit: 'u1', lesson: 'u1l2', page: 24, difficulty: 'easy',
    type: 'trueFalse',
    question: 'يُعدّ المشي مع النظر إلى الأسفل طوال الوقت وضعاً صحيحاً.',
    correctAnswer: 'false',
    explanation: 'المشي الصحيح يتطلب النظر إلى الأمام مع رفع الرأس ومد الظهر للخلف، وليس النظر إلى الأسفل.',
    goldenRule: 'المشي الصحيح: رأس مرفوع + نظر للأمام + ظهر مستقيم.',
    paragraph: 'المشي الصحيح — ص ٢٤',
  },
  {
    id: 'ls3_013', unit: 'u1', lesson: 'u1l2', page: 27, difficulty: 'medium',
    type: 'classify',
    question: 'صنّف العادات التالية حسب تأثيرها على القوام:',
    categories: ['تحافظ على القوام الصحيح', 'تضر بالقوام'],
    items: [
      { text: 'الوقوف منتصباً', correct_category: 0 },
      { text: 'ممارسة الرياضة يومياً', correct_category: 0 },
      { text: 'الجلوس منحنياً لساعات طويلة', correct_category: 1 },
      { text: 'حمل حقيبة ثقيلة على كتف واحد', correct_category: 1 },
    ],
    explanation: 'العادات الصحية كالوقوف المنتصب والرياضة تحافظ على القوام، أما الانحناء وحمل الأشياء بطريقة خاطئة فتضر بالعمود الفقري.',
    goldenRule: 'عاداتك اليومية تُحدد شكل قوامك مستقبلاً.',
    paragraph: 'عادات تؤثر على القوام — ص ٢٧',
  },

  // ── درس 3: الدواء ────────────────────────────────────

  {
    id: 'ls3_014', unit: 'u1', lesson: 'u1l3', page: 30, difficulty: 'easy',
    type: 'trueFalse',
    question: 'الدواء له مقدار معين ووقت محدد يجب الالتزام به.',
    correctAnswer: 'true',
    explanation: 'الدواء له جرعة محددة وأوقات محددة يجب الالتزام بها تماماً حسب تعليمات الطبيب أو الصيدلاني.',
    goldenRule: 'الجرعة الصحيحة في الوقت الصحيح = دواء آمن.',
    paragraph: 'الدواء له مقدار ووقت محدد يجب الالتزام به — ص ٣٠',
  },
  {
    id: 'ls3_015', unit: 'u1', lesson: 'u1l3', page: 31, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'من المسؤول عن إعطاء الدواء للطفل؟',
    options: [
      { text: 'الطفل نفسه إذا عرف الجرعة', correct: false },
      { text: 'الوالدان أو الكبار المسؤولون فقط', correct: true },
      { text: 'الأصدقاء في المدرسة', correct: false },
      { text: 'أي شخص بالغ', correct: false },
    ],
    explanation: 'يجب أن يتولى إعطاء الدواء للطفل الوالدان أو الكبار المسؤولون فقط بناءً على وصفة الطبيب.',
    goldenRule: 'الدواء لا يُعطى للطفل إلا من قِبل وليّ أمره.',
    paragraph: 'من يعطيني الدواء؟ — ص ٣١',
  },
  {
    id: 'ls3_016', unit: 'u1', lesson: 'u1l3', page: 32, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'ما الخطأ الذي يجب تجنبه مع الدواء؟',
    options: [
      { text: 'أخذ الدواء في موعده', correct: false },
      { text: 'تناول الدواء دون وصفة طبيب', correct: true },
      { text: 'الاحتفاظ بالدواء في مكان آمن', correct: false },
      { text: 'الالتزام بجرعة الطبيب', correct: false },
    ],
    explanation: 'يُحظر تناول الدواء دون وصفة طبيب، لأن ذلك قد يسبب أضراراً صحية خطيرة.',
    goldenRule: 'لا دواء بدون وصفة طبيب.',
    paragraph: 'تعليمات الدواء — ص ٣٢',
  },
  {
    id: 'ls3_017', unit: 'u1', lesson: 'u1l3', page: 33, difficulty: 'easy',
    type: 'trueFalse',
    question: 'يجب التخلص من بقايا الأدوية والحقن بعد الانتهاء منها.',
    correctAnswer: 'true',
    explanation: 'يجب التخلص من بقايا الأدوية والحقن بطريقة آمنة بعد الانتهاء منها لحماية الجميع من الأخطار.',
    goldenRule: 'بقايا الدواء والحقن يجب التخلص منها بأمان.',
    paragraph: 'ينبغي التخلص من بقايا الحقن والأدوية بعد الانتهاء منها — ص ٣٣',
  },
  {
    id: 'ls3_018', unit: 'u1', lesson: 'u1l3', page: 34, difficulty: 'hard',
    type: 'multipleChoice',
    question: 'لماذا يجب عدم الإسراف في الدواء؟',
    options: [
      { text: 'لأن الدواء مكلف فقط', correct: false },
      { text: 'لأن زيادة الدواء عن الحد تضر الجسم وقد تكون خطرة', correct: true },
      { text: 'لأن الدواء لا ينفع بكميات كبيرة', correct: false },
      { text: 'لأن الطبيب يرفض إعطاء الدواء مجدداً', correct: false },
    ],
    explanation: 'زيادة جرعة الدواء عن الحد المقرر قد تضر الجسم بدلاً من علاجه وقد تكون خطرة على الحياة.',
    goldenRule: 'الدواء بجرعته الصحيحة يُشفي، وبالزيادة يُؤذي.',
    paragraph: 'الإسراف في الدواء ضار — ص ٣٤',
  },
  {
    id: 'ls3_019', unit: 'u1', lesson: 'u1l3', page: 35, difficulty: 'medium',
    type: 'ordering',
    question: 'رتّب الخطوات الصحيحة عند الحاجة للدواء:',
    items: [
      'تناول الدواء في الوقت المحدد',
      'أخبر أحد والديك بشعورك بالمرض',
      'اذهب للطبيب للحصول على وصفة طبية',
      'احتفظ بالدواء في مكان آمن',
    ],
    correctOrder: [1, 2, 3, 0],
    explanation: 'أخبر والديك → اذهب للطبيب → احتفظ بالدواء بأمان → تناوله في وقته.',
    goldenRule: 'أخبر → الطبيب → الوصفة → الالتزام.',
    paragraph: 'خطوات التعامل مع الدواء — ص ٣٥',
  },

  // ── درس 4: الحمل الصحيح ──────────────────────────────

  {
    id: 'ls3_020', unit: 'u1', lesson: 'u1l4', page: 36, difficulty: 'easy',
    type: 'multipleChoice',
    question: 'ما الجهاز الذي يتأثر بالحمل الخاطئ للأشياء؟',
    options: [
      { text: 'الجهاز الهضمي', correct: false },
      { text: 'الجهاز التنفسي', correct: false },
      { text: 'العمود الفقري والظهر', correct: true },
      { text: 'الجهاز العصبي', correct: false },
    ],
    explanation: 'الحمل الخاطئ للأشياء يؤثر سلباً على العمود الفقري وسلامة الظهر.',
    goldenRule: 'الحمل الخاطئ يؤذي ظهرك وعمودك الفقري.',
    paragraph: 'الوقوف والمشي الخاطئان بطريقة خطأ يؤثر على شكل العمود الفقري — ص ٣٦',
  },
  {
    id: 'ls3_021', unit: 'u1', lesson: 'u1l4', page: 38, difficulty: 'medium',
    type: 'trueFalse',
    question: 'يجب طلب المساعدة من الآخرين عند حمل الأشياء الثقيلة.',
    correctAnswer: 'true',
    explanation: 'يجب طلب المساعدة من الآخرين عند حمل الأشياء الثقيلة حفاظاً على سلامة الظهر والعمود الفقري.',
    goldenRule: 'طلب المساعدة للأشياء الثقيلة قوة وليست ضعفاً.',
    paragraph: 'طلب المساعدة من الآخرين عند حمل الأشياء الثقيلة — ص ٣٨',
  },
  {
    id: 'ls3_022', unit: 'u1', lesson: 'u1l4', page: 39, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'ما الطريقة الصحيحة لرفع الأشياء الثقيلة من الأرض؟',
    options: [
      { text: 'الانحناء من الظهر مع إبقاء الرجلين مستقيمتين', correct: false },
      { text: 'القرفصاء ورفع الشيء بقوة الرجلين مع إبقاء الظهر مستقيماً', correct: true },
      { text: 'الرفع السريع بضربة واحدة', correct: false },
      { text: 'استخدام اليد الواحدة دائماً', correct: false },
    ],
    explanation: 'الطريقة الصحيحة: القرفصاء ثم رفع الشيء بقوة الرجلين مع إبقاء الظهر مستقيماً لتفادي إيذاء العمود الفقري.',
    goldenRule: 'ارفع برجليك لا بظهرك.',
    paragraph: 'طريقة الرفع الصحيح — ص ٣٩',
  },
  {
    id: 'ls3_023', unit: 'u1', lesson: 'u1l4', page: 40, difficulty: 'easy',
    type: 'trueFalse',
    question: 'يمكن استخدام العربات لنقل الأشياء الثقيلة بدلاً من حملها.',
    correctAnswer: 'true',
    explanation: 'نعم، يمكن استخدام العربات والمعدات المساعدة لنقل الأشياء الثقيلة بدلاً من حملها حفاظاً على الصحة.',
    goldenRule: 'العربات والمعدات المساعدة = حماية الظهر من الإجهاد.',
    paragraph: 'يستخدم عربة لنقل الأشياء الثقيلة — ص ٤٠',
  },
  {
    id: 'ls3_024', unit: 'u1', lesson: 'u1l4', page: 41, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'ماذا يُسبب الحمل الخاطئ للأشياء؟',
    options: [
      { text: 'يقوي عضلات الظهر', correct: false },
      { text: 'يؤدي إلى آلام الظهر والإصابات', correct: true },
      { text: 'يحسن التوازن', correct: false },
      { text: 'لا يسبب أي أضرار', correct: false },
    ],
    explanation: 'الحمل الخاطئ للأشياء يؤدي إلى آلام الظهر والإصابات في العمود الفقري على المدى البعيد.',
    goldenRule: 'الحمل الخاطئ اليوم = آلام الظهر غداً.',
    paragraph: 'الحمل الخاطئ للأشياء يؤثر على سلامة الظهر — ص ٤١',
  },
  {
    id: 'ls3_025', unit: 'u1', lesson: 'u1l4', page: 43, difficulty: 'medium',
    type: 'classify',
    question: 'صنّف طرق حمل الأشياء:',
    categories: ['طرق صحيحة للحمل', 'طرق خاطئة للحمل'],
    items: [
      { text: 'رفع الشيء بقوة الرجلين والظهر مستقيم', correct_category: 0 },
      { text: 'استخدام العربة للأشياء الثقيلة', correct_category: 0 },
      { text: 'الانحناء من الظهر لرفع الأشياء', correct_category: 1 },
      { text: 'حمل الحقيبة على كتف واحد فقط', correct_category: 1 },
    ],
    explanation: 'الحمل الصحيح يحمي الظهر أما الحمل الخاطئ فيُتعب العمود الفقري.',
    goldenRule: 'تعلم الحمل الصحيح قبل أن تشعر بالألم.',
    paragraph: 'الحمل الصحيح والخاطئ — ص ٤٣',
  },

  // ══════════════════════════════════════════════════════
  // الوحدة الثانية: شخصيتي
  // ══════════════════════════════════════════════════════

  // ── درس 1: كيف أتصرف إذا خرجت أمي من المنزل؟ ────────

  {
    id: 'ls3_026', unit: 'u2', lesson: 'u2l1', page: 46, difficulty: 'easy',
    type: 'multipleChoice',
    question: 'ما أسباب خروج الأم من المنزل؟',
    options: [
      { text: 'سبب واحد فقط هو الذهاب للعمل', correct: false },
      { text: 'أسباب متعددة: العمل، زيارة الوالدين، الترفيه، المستشفى', correct: true },
      { text: 'الذهاب للمستشفى فقط', correct: false },
      { text: 'زيارة الأصدقاء فقط', correct: false },
    ],
    explanation: 'تخرج الأم من المنزل لأسباب متعددة منها: الذهاب للعمل، زيارة والديها وأقاربها، الاجتماع بالصديقات أو الجيران، الترفيه، الذهاب للمستشفى.',
    goldenRule: 'للأم حقوق وأعمال تجعلها تخرج من المنزل — وهذا طبيعي.',
    paragraph: 'تخرج الأم من المنزل لعدة أسباب — ص ٤٦',
  },
  {
    id: 'ls3_027', unit: 'u2', lesson: 'u2l1', page: 47, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'ما التصرف السليم عند خروج الأم من المنزل؟',
    options: [
      { text: 'الخروج إلى الشارع والعب فيه', correct: false },
      { text: 'قضاء الوقت باللعب المفيد وإنجاز الواجبات والاهتمام بالإخوة', correct: true },
      { text: 'إثارة الفوضى في المنزل', correct: false },
      { text: 'مشاهدة التلفاز طوال الوقت', correct: false },
    ],
    explanation: 'التصرف السليم: قضاء الوقت باللعب المفيد، ممارسة الهوايات، الاهتمام بالإخوة الأصغر، إنجاز الواجبات والاستذكار، والمساعدة في ترتيب الغرفة.',
    goldenRule: 'غياب الأم فرصة لإثبات مسؤوليتك.',
    paragraph: 'التصرف السليم — ص ٤٧',
  },
  {
    id: 'ls3_028', unit: 'u2', lesson: 'u2l1', page: 47, difficulty: 'easy',
    type: 'trueFalse',
    question: 'من التصرفات السليمة عند غياب الأم: الاهتمام بالإخوة الأصغر سناً.',
    correctAnswer: 'true',
    explanation: 'من التصرفات السليمة عند غياب الأم: الاهتمام بالإخوة الأصغر سناً والتعاون مع أفراد الأسرة في تنفيذ توصيات الوالدين.',
    goldenRule: 'الاهتمام بالإخوة الصغار عند غياب الأم من أهم التصرفات الحميدة.',
    paragraph: 'التصرف السليم — ص ٤٧',
  },
  {
    id: 'ls3_029', unit: 'u2', lesson: 'u2l1', page: 48, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'ما نتيجة التصرف الخاطئ عند خروج الأم؟',
    options: [
      { text: 'رضا الوالدين', correct: false },
      { text: 'التعرض للخطر وغضب الوالدين والتخاصم مع الإخوة', correct: true },
      { text: 'قضاء وقت ممتع', correct: false },
      { text: 'اكتساب مهارات جديدة', correct: false },
    ],
    explanation: 'التصرف الخاطئ كالخروج للشارع واللعب بالأدوات الخطرة والتشاجر مع الإخوة يؤدي إلى: التعرض للخطر، غضب الوالدين، التخاصم مع الإخوة.',
    goldenRule: 'التصرف الخاطئ → خطر + غضب الوالدين + تخاصم مع الإخوة.',
    paragraph: 'التصرف الخاطئ ونتيجته — ص ٤٨',
  },
  {
    id: 'ls3_030', unit: 'u2', lesson: 'u2l1', page: 51, difficulty: 'medium',
    type: 'classify',
    question: 'صنّف التصرفات التالية عند غياب الأم:',
    categories: ['تصرفات سليمة', 'تصرفات خاطئة'],
    items: [
      { text: 'قضاء الوقت باللعب المفيد', correct_category: 0 },
      { text: 'إنجاز الواجبات والاستذكار', correct_category: 0 },
      { text: 'الخروج إلى الشارع', correct_category: 1 },
      { text: 'اللعب بالأدوات الخطرة', correct_category: 1 },
    ],
    explanation: 'التصرفات السليمة تحافظ على السلامة وتُرضي الوالدين، أما الخاطئة فتعرض الطفل للخطر.',
    goldenRule: 'في غياب الأم: آمن + منتج = ابن مسؤول.',
    paragraph: 'التصرف السليم والخاطئ — ص ٤٧-٤٨',
  },
  {
    id: 'ls3_031', unit: 'u2', lesson: 'u2l1', page: 51, difficulty: 'medium',
    type: 'trueFalse',
    question: 'يجب معرفة رقمَي جوالَي الوالدين أمر ضروري عند غيابهما.',
    correctAnswer: 'true',
    explanation: 'معرفة رقمَي جوالَي الوالدين أمر ضروري لأنه يُمكّن الطفل من التواصل معهما في أي حالة طارئة.',
    goldenRule: 'أرقام هواتف الوالدين = خط الأمان الأول.',
    paragraph: 'معرفة رقمي جوالي الوالدين أمر ضروري عند غيابهما — ص ٥١',
  },
  {
    id: 'ls3_032', unit: 'u2', lesson: 'u2l1', page: 51, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'ما الإرشادات العامة عند غياب الأم عن المنزل؟',
    options: [
      { text: 'إخبار الغرباء عن غياب الأم', correct: false },
      { text: 'لا تُخبر الغرباء عن غياب أمك ولا تُدخلهم المنزل', correct: true },
      { text: 'فتح الباب لأي شخص يطرق', correct: false },
      { text: 'الخروج من المنزل مع الأصدقاء', correct: false },
    ],
    explanation: 'من الإرشادات العامة المهمة: لا تخبر الغرباء بغياب أمك، ولا تدخل الغرباء إلى المنزل عند غيابها، وتنفيذ تعليماتها ونصائحها.',
    goldenRule: 'لا تخبر الغرباء بغياب أمك ← هذا سلامتك.',
    paragraph: 'إرشادات عامة — ص ٥١',
  },
  {
    id: 'ls3_033', unit: 'u2', lesson: 'u2l1', page: 49, difficulty: 'hard',
    type: 'multipleChoice',
    question: 'ما الموقف الصحيح إذا طرق شخص غريب الباب وأمك خارج المنزل؟',
    options: [
      { text: 'افتح الباب وادعه للدخول', correct: false },
      { text: 'لا تفتح الباب وأخبر أمك عند عودتها', correct: true },
      { text: 'أخبره بأن أمك غائبة', correct: false },
      { text: 'اخرج لتراه عن قرب', correct: false },
    ],
    explanation: 'الموقف الصحيح هو عدم فتح الباب لشخص غريب وعدم إخباره بغياب الأم، وإخبار الأم عند عودتها.',
    goldenRule: 'لا تفتح للغريب ولا تُخبره بغياب أمك.',
    paragraph: 'كيف أتصرف إذا طرق شخص غريب الباب وأمي خارج المنزل — ص ٤٩',
  },

  // ── درس 2: كيف أتصرف بملابسي التي لا أحتاجها؟ ────────

  {
    id: 'ls3_034', unit: 'u2', lesson: 'u2l2', page: 55, difficulty: 'easy',
    type: 'multipleChoice',
    question: 'لماذا يتغير قياس الملابس عند الأطفال؟',
    options: [
      { text: 'لأن الملابس تبلى بسرعة', correct: false },
      { text: 'لأن الجسم ينمو ويكبر مع مرور الوقت', correct: true },
      { text: 'لأن الموضة تتغير', correct: false },
      { text: 'لأن الألوان تبهت', correct: false },
    ],
    explanation: 'يتغير قياس الملابس عند الأطفال بسبب نمو الجسم وكبره مع مرور الوقت.',
    goldenRule: 'النمو الطبيعي للجسم يعني تغيير قياسات الملابس باستمرار.',
    paragraph: 'ما الذي حدث لزيّك المدرسي القديم؟ — ص ٥٦',
  },
  {
    id: 'ls3_035', unit: 'u2', lesson: 'u2l2', page: 57, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'ما التصرف السليم مع الملابس التي لا نحتاجها؟',
    options: [
      { text: 'رميها في القمامة مباشرة', correct: false },
      { text: 'التصدق بها على الفقراء أو الاحتفاظ بها للإخوة', correct: true },
      { text: 'تخزينها مدة طويلة دون استخدامها', correct: false },
      { text: 'تمزيقها', correct: false },
    ],
    explanation: 'التصرف السليم: التصدق بها على الفقراء، قال تعالى: (لن تنالوا البر حتى تنفقوا مما تحبون)، أو الاحتفاظ بها للإخوة، أو استثمارها في بعض الأعمال المفيدة.',
    goldenRule: 'الملابس غير المحتاجة → تصدق بها → أجر من الله.',
    paragraph: 'التصرف السليم — ص ٥٧',
  },
  {
    id: 'ls3_036', unit: 'u2', lesson: 'u2l2', page: 57, difficulty: 'easy',
    type: 'trueFalse',
    question: 'التصدق بالملابس على الفقراء يُدخل السرور على قلب المسلم.',
    correctAnswer: 'true',
    explanation: 'التصدق بالملابس على الفقراء يُدخل السرور على قلب المسلم ويحقق الاقتصاد والتوفير في المال، وينال الأجر من الله.',
    goldenRule: 'التصدق = أجر من الله + سرور في القلب + اقتصاد في المال.',
    paragraph: 'النتيجة من التصرف السليم — ص ٥٧',
  },
  {
    id: 'ls3_037', unit: 'u2', lesson: 'u2l2', page: 57, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'ما نتيجة التصرف الخاطئ في الملابس بتمزيقها أو رميها؟',
    options: [
      { text: 'نيل الأجر من الله', correct: false },
      { text: 'الإسراف وضياع المال والفرص', correct: true },
      { text: 'إدخال السرور على الآخرين', correct: false },
      { text: 'الاقتصاد في المال', correct: false },
    ],
    explanation: 'التصرف الخاطئ بتمزيق الملابس أو رميها يؤدي إلى الإسراف وضياع المال وفقدان فرصة الاستفادة منها.',
    goldenRule: 'تمزيق الملابس ورميها = إسراف مذموم.',
    paragraph: 'التصرف الخاطئ ونتيجته — ص ٥٧',
  },
  {
    id: 'ls3_038', unit: 'u2', lesson: 'u2l2', page: 60, difficulty: 'medium',
    type: 'trueFalse',
    question: 'يجب عدم الاستفادة من ملابس الإخوة الأكبر سناً.',
    correctAnswer: 'false',
    explanation: 'لا يجب الخجل من الاستفادة من ملابس الإخوة الأكبر سناً، بل هذا من الاقتصاد وعدم الإسراف.',
    goldenRule: 'الاستفادة من ملابس الإخوة الكبار = اقتصاد وتوفير مشروع.',
    paragraph: 'لا تخجل من الاستفادة من ملابس الإخوة الأكبر سناً — ص ٦٠',
  },
  {
    id: 'ls3_039', unit: 'u2', lesson: 'u2l2', page: 60, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'ما شرط الملابس التي يُتصدق بها؟',
    options: [
      { text: 'أن تكون جديدة تماماً فقط', correct: false },
      { text: 'أن تكون نظيفة وفي حالة جيدة', correct: true },
      { text: 'أن تكون ملونة', correct: false },
      { text: 'أي حالة مقبولة للتصدق', correct: false },
    ],
    explanation: 'الملابس التي يُتصدق بها يجب أن تكون نظيفة وفي حالة جيدة، لأن هذا من احترام المُعطَى له وتقدير ما يُعطى.',
    goldenRule: 'الملابس المُتصدَّق بها يجب أن تكون نظيفة وفي حالة جيدة.',
    paragraph: 'الملابس التي تتصدق بها يجب أن تكون نظيفة وفي حالة جيدة — ص ٦٠',
  },
  {
    id: 'ls3_040', unit: 'u2', lesson: 'u2l2', page: 60, difficulty: 'easy',
    type: 'trueFalse',
    question: 'هناك جمعيات خيرية تساعد على توصيل الملابس والمعونة الغذائية للمحتاجين.',
    correctAnswer: 'true',
    explanation: 'نعم، هناك جمعيات خيرية متخصصة بتوزيع فائض الملابس والمعونة الغذائية للمحتاجين.',
    goldenRule: 'الجمعيات الخيرية وسيلة رائعة للمساعدة في نقل الملابس للمحتاجين.',
    paragraph: 'هناك جمعيات خيرية تساعد على توصيل الملابس والمعونة الغذائية للمحتاجين — ص ٦٠',
  },
  {
    id: 'ls3_041', unit: 'u2', lesson: 'u2l2', page: 58, difficulty: 'hard',
    type: 'multipleChoice',
    question: 'لماذا يجب عدم الإسراف في شراء الملابس لمن هم في مرحلة الطفولة؟',
    options: [
      { text: 'لأن الملابس مكلفة جداً', correct: false },
      { text: 'لأن أجسامهم في نمو مستمر ولن يستخدموها طويلاً', correct: true },
      { text: 'لأن الأطفال لا يحبون الملابس', correct: false },
      { text: 'لأن الملابس الصغيرة أجمل', correct: false },
    ],
    explanation: 'يجب عدم الإسراف في شراء الملابس لمن هم في مرحلة الطفولة لأن أجسامهم في نمو مستمر ولن تناسبهم الملابس طويلاً.',
    goldenRule: 'جسم الطفل ينمو بسرعة = الاقتصاد في شراء الملابس ضرورة.',
    paragraph: 'لم يجب عدم الإسراف في شراء الملابس لمن هم في مرحلة الطفولة؟ — ص ٥٨',
  },

  // ══════════════════════════════════════════════════════
  // الوحدة الثالثة: وقتي
  // ══════════════════════════════════════════════════════

  {
    id: 'ls3_042', unit: 'u3', lesson: 'u3l1', page: 66, difficulty: 'easy',
    type: 'multipleChoice',
    question: 'كم عدد عقارب الساعة؟',
    options: [
      { text: 'عقرب واحد', correct: false },
      { text: 'عقربان اثنان', correct: false },
      { text: 'ثلاثة عقارب', correct: true },
      { text: 'أربعة عقارب', correct: false },
    ],
    explanation: 'للساعة ثلاثة عقارب: العقرب القصير (يشير إلى الساعات)، والعقرب الطويل (يشير إلى الدقائق)، والعقرب النحيف (يشير إلى الثواني).',
    goldenRule: 'ثلاثة عقارب: قصير للساعات، طويل للدقائق، نحيف للثواني.',
    paragraph: 'الساعة — ص ٦٧',
  },
  {
    id: 'ls3_043', unit: 'u3', lesson: 'u3l1', page: 67, difficulty: 'easy',
    type: 'multipleChoice',
    question: 'إلى ماذا يشير العقرب القصير في الساعة؟',
    options: [
      { text: 'إلى الثواني', correct: false },
      { text: 'إلى الدقائق', correct: false },
      { text: 'إلى الساعات', correct: true },
      { text: 'إلى الأيام', correct: false },
    ],
    explanation: 'العقرب القصير يشير إلى الساعات ويدور دورة كاملة كل نصف يوم أي كل 12 ساعة.',
    goldenRule: 'عقرب قصير = ساعات | عقرب طويل = دقائق | عقرب نحيف = ثواني.',
    paragraph: 'العقرب القصير يشير إلى الساعات — ص ٦٧',
  },
  {
    id: 'ls3_044', unit: 'u3', lesson: 'u3l1', page: 67, difficulty: 'easy',
    type: 'trueFalse',
    question: 'العقرب الطويل في الساعة يشير إلى الدقائق ويدور دورة كاملة كل ساعة.',
    correctAnswer: 'true',
    explanation: 'العقرب الطويل يشير إلى الدقائق ويدور دورة كاملة كل ساعة أي كل 60 دقيقة.',
    goldenRule: 'العقرب الطويل = الدقائق | 60 دقيقة = ساعة كاملة.',
    paragraph: 'العقرب الطويل يشير إلى الدقائق — ص ٦٧',
  },
  {
    id: 'ls3_045', unit: 'u3', lesson: 'u3l1', page: 67, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'كم ثانية في الدقيقة الواحدة؟',
    options: [
      { text: '12 ثانية', correct: false },
      { text: '30 ثانية', correct: false },
      { text: '60 ثانية', correct: true },
      { text: '100 ثانية', correct: false },
    ],
    explanation: 'الدقيقة الواحدة تحتوي على 60 ثانية، وهو الوقت الذي يستغرقه العقرب النحيف (الثواني) لإتمام دورة كاملة.',
    goldenRule: '60 ثانية = دقيقة | 60 دقيقة = ساعة.',
    paragraph: 'كم ثانية في الدقيقة؟ — ص ٦٧',
  },
  {
    id: 'ls3_046', unit: 'u3', lesson: 'u3l1', page: 67, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'كم ساعة في اليوم الكامل؟',
    options: [
      { text: '12 ساعة', correct: false },
      { text: '16 ساعة', correct: false },
      { text: '20 ساعة', correct: false },
      { text: '24 ساعة', correct: true },
    ],
    explanation: 'يحتوي اليوم الكامل على 24 ساعة: 12 ساعة صباحية + 12 ساعة مسائية.',
    goldenRule: '24 ساعة = يوم كامل = نعمة يجب استثمارها.',
    paragraph: 'بالتعاون مع الطلاب والمعلمي أحدد كم ساعة في اليوم — ص ٦٧',
  },
  {
    id: 'ls3_047', unit: 'u3', lesson: 'u3l1', page: 67, difficulty: 'easy',
    type: 'trueFalse',
    question: 'العقرب النحيف في الساعة يشير إلى الثواني.',
    correctAnswer: 'true',
    explanation: 'العقرب النحيف يشير إلى الثواني ويدور دورة كاملة كل 60 ثانية.',
    goldenRule: 'العقرب النحيف = الثواني | أسرع عقارب الساعة.',
    paragraph: 'العقرب النحيف يشير إلى الثواني — ص ٦٧',
  },
  {
    id: 'ls3_048', unit: 'u3', lesson: 'u3l1', page: 66, difficulty: 'easy',
    type: 'multipleChoice',
    question: 'ما أشكال الساعات المختلفة؟',
    options: [
      { text: 'شكل واحد فقط', correct: false },
      { text: 'أشكال وأحجام مختلفة مثل: الساعة العادية والرقمية وساعة الرمل وساعة الحائط', correct: true },
      { text: 'شكلان: مستديرة ومربعة', correct: false },
      { text: 'ثلاثة أشكال فقط', correct: false },
    ],
    explanation: 'للساعات أشكال وأحجام مختلفة: الساعة العادية بعقارب، الرقمية، ساعة الرمل، ساعة الحائط، وساعة برج مكة وغيرها.',
    goldenRule: 'للساعات أشكال كثيرة لكنها جميعاً تقيس الوقت.',
    paragraph: 'للساعات أشكال وأحجام مختلفة — ص ٦٦',
  },
  {
    id: 'ls3_049', unit: 'u3', lesson: 'u3l1', page: 69, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'ما الذي تدل عليه الأرقام على وجه الساعة؟',
    options: [
      { text: 'كل رقم يشير إلى ثانية واحدة', correct: false },
      { text: 'كل رقم يشير إلى ساعة واحدة', correct: true },
      { text: 'كل رقم يشير إلى دقيقة واحدة', correct: false },
      { text: 'الأرقام للزينة فقط', correct: false },
    ],
    explanation: 'أرقام الساعة: كل رقم يشير إلى ساعة واحدة، وتتراوح من 1 إلى 12.',
    goldenRule: 'أرقام الساعة من 1 إلى 12 وكل رقم = ساعة واحدة.',
    paragraph: 'الأرقام: يشير كل رقم إلى ساعة واحدة — ص ٦٧',
  },
  {
    id: 'ls3_050', unit: 'u3', lesson: 'u3l1', page: 69, difficulty: 'medium',
    type: 'trueFalse',
    question: 'تتوقف الساعة عن العمل لأنها غير صالحة، لكنها قد تحتاج إلى تغيير البطارية.',
    correctAnswer: 'true',
    explanation: 'توقف الساعة عن العمل لا يعني أنها غير صالحة، فقد تحتاج فقط إلى تغيير البطارية.',
    goldenRule: 'توقف الساعة ≠ عطل. قد تحتاج فقط لبطارية جديدة.',
    paragraph: 'توقف الساعة عن العمل لا يعني أنها غير صالحة، لكن قد تحتاج إلى تغيير البطارية — ص ٦٩',
  },
  {
    id: 'ls3_051', unit: 'u3', lesson: 'u3l1', page: 69, difficulty: 'easy',
    type: 'multipleChoice',
    question: 'في أي اتجاه تدور عقارب الساعة؟',
    options: [
      { text: 'من اليسار إلى اليمين', correct: false },
      { text: 'من اليمين إلى اليسار', correct: true },
      { text: 'تارةً يميناً وتارةً يساراً', correct: false },
      { text: 'لا تتحرك', correct: false },
    ],
    explanation: 'تدور عقارب الساعة من اليمين إلى اليسار.',
    goldenRule: 'عقارب الساعة تدور من اليمين إلى اليسار.',
    paragraph: 'تدور عقارب الساعة من اليمين إلى اليسار — ص ٦٩',
  },
  {
    id: 'ls3_052', unit: 'u3', lesson: 'u3l1', page: 69, difficulty: 'medium',
    type: 'ordering',
    question: 'رتّب الوحدات الزمنية من الأصغر إلى الأكبر:',
    items: ['الساعة', 'اليوم', 'الدقيقة', 'الثانية'],
    correctOrder: [3, 2, 0, 1],
    explanation: 'الثانية < الدقيقة (60 ثانية) < الساعة (60 دقيقة) < اليوم (24 ساعة).',
    goldenRule: 'ثانية ← دقيقة ← ساعة ← يوم.',
    paragraph: 'الوحدات الزمنية — ص ٦٧',
  },
  {
    id: 'ls3_053', unit: 'u3', lesson: 'u3l1', page: 72, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'أي نوع من أنواع الساعات يساعدك على الاستيقاظ من النوم؟',
    options: [
      { text: 'ساعة الرمل', correct: false },
      { text: 'ساعة الحائط العادية', correct: false },
      { text: 'الساعة المنبّه', correct: true },
      { text: 'ساعة برج مكة', correct: false },
    ],
    explanation: 'الساعة المنبّه تساعد على الاستيقاظ من النوم في الوقت المحدد.',
    goldenRule: 'الساعة المنبّه = صديق اليقظة والانضباط.',
    paragraph: 'أي نوع من أنواع الساعات يساعدك على الاستيقاظ من النوم؟ — ص ٧٢',
  },
];

export const TOTAL_QUESTIONS_LS3 = LS3_S1_QUESTIONS.length;