// مهارات الحياة والتربية الأسرية - الصف الثاني الابتدائي - الفصل الأول
// الوحدة الأولى: صحتي وسلامتي | الوحدة الثانية: شخصيتي

export const META = {
  title: 'بنك أسئلة المهارات الحياتية',
  subject: 'المهارات الحياتية والتربية الأسرية',
  grade: 'الصف الثاني الابتدائي',
  term: 'الفصل الأول',
  publisher: 'وزارة التعليم - المملكة العربية السعودية',
  book: 'المهارات الحياتية والتربية الأسرية - 1447هـ / 2025م',
};

export const UNITS = [
  {
    id: 'unit1',
    title: 'الوحدة الأولى: صحتي وسلامتي',
    color: '#059669',
    icon: '🌿',
    lessons: [
      { id: 'u1l1', title: 'درس 1: العناية بالأظافر', page: 12, unitId: 'unit1' },
      { id: 'u1l2', title: 'درس 2: ترتيب الشعر', page: 14, unitId: 'unit1' },
      { id: 'u1l3', title: 'درس 3: آداب استخدام دورة المياه', page: 22, unitId: 'unit1' },
    ],
  },
  {
    id: 'unit2',
    title: 'الوحدة الثانية: شخصيتي',
    color: '#e91e8c',
    icon: '⭐',
    lessons: [
      { id: 'u2l1', title: 'درس 1: الخجل', page: 34, unitId: 'unit2' },
      { id: 'u2l2', title: 'درس 2: كيف أتصرف إذا مرض أحد في المنزل؟', page: 39, unitId: 'unit2' },
    ],
  },
  {
    id: 'unit3',
    title: 'الوحدة الثالثة: وقتي',
    color: '#0891b2',
    icon: '⏰',
    lessons: [
      { id: 'u3l1', title: 'درس 1: التقويم الهجري والميلادي', page: 56, unitId: 'unit3' },
      { id: 'u3l2', title: 'درس 2: التقويم الميلادي', page: 60, unitId: 'unit3' },
    ],
  },
];

export const BLOOM_LABELS = {
  remember: 'تذكُّر', understand: 'فهم', apply: 'تطبيق',
  analyze: 'تحليل', create: 'تركيب', evaluate: 'تقويم',
};
export const DIFFICULTY_LABELS = { easy: 'سهل', medium: 'متوسط', hard: 'صعب' };

// ─── وحدة 1 | درس 1: العناية بالأظافر ──────────────────────────────────────
const u1l1Questions = [
  {
    id:'u1l1q1', unit:'unit1', lesson:'u1l1', page:12, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'قضمُ الأظفار بالأسنان ينقل الأوساخ إلى:',
    paragraph:'قَضْمُ الأظفار بالأسنان يَنْقُلُ الأوساخَ مِنها إلى الفَمِ مُباشَرةً. (ص12)',
    options:[
      {text:'الفم مباشرةً',correct:true},
      {text:'الجلد فقط',correct:false},
      {text:'الأنف',correct:false},
      {text:'العين',correct:false},
    ],
    explanation:'قضم الأظافر بالأسنان يُعدّ عادةً سيئةً لأنه ينقل الأوساخ والجراثيم من تحت الأظافر مباشرةً إلى داخل الفم.',
    goldenRule:'لا تقضم أظافرك بأسنانك! الأوساخ تنتقل للفم مباشرة.',
    feedbackQuestion:{question:'ما الخطر الرئيسي من قضم الأظافر بالأسنان؟',options:[{text:'نقل الجراثيم للفم',correct:true},{text:'كسر الأسنان',correct:false},{text:'ألم في الأصابع',correct:false},{text:'تلف الأظافر',correct:false}]},
  },
  {
    id:'u1l1q2', unit:'unit1', lesson:'u1l1', page:12, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'الأظافرُ الطويلةُ تؤذي صاحبها فقط ولا تؤذي الآخرين.',
    paragraph:'الأظفارُ الطَّويلةُ تُؤذيكَ وتُؤذي الآخِرين. (ص12)',
    correctAnswer:false,
    explanation:'الأظافر الطويلة تؤذي صاحبها والآخرين معاً، لذلك يجب تقليمها أسبوعياً.',
    goldenRule:'الأظافر الطويلة خطر على الجميع — قلّمها أسبوعياً.',
    feedbackQuestion:{question:'من يتأذى من الأظافر الطويلة؟',options:[{text:'الشخص والآخرون معاً',correct:true},{text:'الشخص فقط',correct:false},{text:'الآخرون فقط',correct:false},{text:'لا أحد',correct:false}]},
  },
  {
    id:'u1l1q3', unit:'unit1', lesson:'u1l1', page:12, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'حثّ الرسولُ ﷺ على تقليم الأظافر؛ وهذا يدل على أن العناية بها:',
    paragraph:'حَثَّ الرَّسولُ ـ صلَّى اللهُ عليهِ وسلَّمَ ـ على تَقْليمِ الأظفار. (ص12)',
    options:[
      {text:'سنّة نبوية مستحبة',correct:true},
      {text:'عادة خاصة بالمسلمين القدامى',correct:false},
      {text:'أمر غير مهم',correct:false},
      {text:'علاج طبي فقط',correct:false},
    ],
    explanation:'حثّ الرسول ﷺ على تقليم الأظافر يجعلها من سنن الفطرة المستحبة.',
    goldenRule:'تقليم الأظافر سنّة نبوية من سنن الفطرة.',
    feedbackQuestion:{question:'ما حكم تقليم الأظافر في الإسلام؟',options:[{text:'سنة نبوية مستحبة',correct:true},{text:'فريضة واجبة',correct:false},{text:'محرّم',correct:false},{text:'لا ذكر له في الإسلام',correct:false}]},
  },
  {
    id:'u1l1q4', unit:'unit1', lesson:'u1l1', page:12, type:'trueFalse',
    bloom:'understand', difficulty:'medium',
    question:'طلاء الأظافر يمنع وصول الماء والهواء إليها ويجعل الوضوء غير صحيح.',
    paragraph:'طِلاءُ الأظفار يَمْنعُ وُصولَ الماءِ والهواءِ إليها وَيَجْعلُ الوُضوءَ غَيرَ صَحيح. (ص12)',
    correctAnswer:true,
    explanation:'طلاء الأظافر يشكّل طبقةً مانعةً تحول دون وصول الماء، مما يُبطل الوضوء.',
    goldenRule:'طلاء الأظافر يمنع الوضوء الصحيح — تجنّبيه عند الصلاة.',
    feedbackQuestion:{question:'لماذا لا ينبغي للمصلية وضع طلاء الأظافر؟',options:[{text:'لأنه يمنع وصول الماء للوضوء',correct:true},{text:'لأنه يؤذي الأظافر',correct:false},{text:'لأنه مكلف',correct:false},{text:'لأنه يؤذي الجلد',correct:false}]},
  },
  {
    id:'u1l1q5', unit:'unit1', lesson:'u1l1', page:13, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف هذه العادات: هل هي عادات حسنة أم سيئة في العناية بالأظافر؟',
    paragraph:'لوّن الدائرةَ بالأخضر أمام العادات الحَسَنة، وبالأحمر أمام العادات السيئة. (ص13)',
    categories:['عادة حسنة ✅','عادة سيئة ❌'],
    items:[
      {text:'تقليم الأظافر أسبوعياً',correct_category:0},
      {text:'قضم الأظافر بالأسنان',correct_category:1},
      {text:'صبغ الأظافر بالحناء للفتيات',correct_category:1},
      {text:'ترك الأظافر طويلة',correct_category:1},
    ],
    explanation:'التقليم الأسبوعي عادة حسنة. أما قضمها وصبغها بالحناء وتركها طويلة فعادات سيئة.',
    goldenRule:'العادات الحسنة: التقليم الأسبوعي. العادات السيئة: القضم والطلاء والترك طويلة.',
  },
  {
    id:'u1l1q6', unit:'unit1', lesson:'u1l1', page:13, type:'ordering',
    bloom:'apply', difficulty:'medium',
    question:'رتّب خطوات العناية الصحيحة بالأظافر من الأولى للأخيرة:',
    paragraph:'العناية الصحيحة بالأظافر تشمل: الغسيل ثم التقليم ثم التنظيف. (ص12-13)',
    items:['تقليم الأظافر بالمقص المناسب','غسل الأيدي جيداً','التحقق من نظافة ما تحت الأظافر','تجفيف الأيدي بالمنشفة'],
    correctOrder:[1,0,2,3],
    explanation:'الخطوات الصحيحة: الغسيل ← التقليم ← التحقق من النظافة ← التجفيف.',
    goldenRule:'ابدأ بغسل يديك قبل تقليم أظافرك دائماً.',
  },
];

// ─── وحدة 1 | درس 2: ترتيب الشعر ──────────────────────────────────────────
const u1l2Questions = [
  {
    id:'u1l2q1', unit:'unit1', lesson:'u1l2', page:14, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'لتنظيف الشعر والعناية به نحتاج إلى:',
    paragraph:'لِتَنْظيفِ شَعري والعِنايةِ به أحتاجُ إلى: الماء، الشامبو، المشط، الكريمات المغذية. (ص14)',
    options:[
      {text:'الماء والشامبو والمشط',correct:true},
      {text:'الصابون فقط',correct:false},
      {text:'المقص فقط',correct:false},
      {text:'الزيت فقط',correct:false},
    ],
    explanation:'العناية الكاملة بالشعر تحتاج: ماء للاستحمام، شامبو، كريمات مغذية، ومشط.',
    goldenRule:'أدوات العناية بالشعر: ماء + شامبو + كريمات مغذية + مشط.',
    feedbackQuestion:{question:'أيّ هذه الأدوات يُستخدم لترتيب الشعر؟',options:[{text:'المشط',correct:true},{text:'المقص',correct:false},{text:'الصابون',correct:false},{text:'المنشفة',correct:false}]},
  },
  {
    id:'u1l2q2', unit:'unit1', lesson:'u1l2', page:15, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'يجب أن يكون الشعر نظيفاً ومرتّباً عند الذهاب إلى المدرسة.',
    paragraph:'عِنْدَ الذَّهابِ إلى المَدْرسةِ لا بُدَّ أنْ يَكونَ شَعري نَظيفاً ومُرتَّباً. (ص15)',
    correctAnswer:true,
    explanation:'النظافة والترتيب من متطلبات المدرسة؛ فالشعر المرتّب يعكس شخصية الطالب ويؤثر في مظهره.',
    goldenRule:'الشعر النظيف المرتّب ضرورة عند الذهاب للمدرسة.',
    feedbackQuestion:{question:'ما أهمية ترتيب الشعر قبل المدرسة؟',options:[{text:'يعكس مظهرك وشخصيتك',correct:true},{text:'لا أهمية له',correct:false},{text:'يجلب الحظ الجيد',correct:false},{text:'لإرضاء المعلم فقط',correct:false}]},
  },
  {
    id:'u1l2q3', unit:'unit1', lesson:'u1l2', page:16, type:'multipleChoice',
    bloom:'apply', difficulty:'medium',
    question:'يجب الاستحمام يومياً بعد العودة من المدرسة خاصةً في:',
    paragraph:'أحرصُ على الاستحمامِ يومياً بعدَ العودةِ من المدرسة، خاصةً في فصلِ الصيف. (ص16)',
    options:[
      {text:'فصل الصيف',correct:true},
      {text:'فصل الشتاء',correct:false},
      {text:'فصل الخريف',correct:false},
      {text:'فصل الربيع',correct:false},
    ],
    explanation:'في الصيف يزيد التعرق والحرارة، لذلك الاستحمام اليومي أكثر ضرورةً.',
    goldenRule:'الاستحمام يومي واجب، وأكثر أهمية في الصيف بسبب التعرق.',
    feedbackQuestion:{question:'لماذا يكثر غسل الشعر في الصيف؟',options:[{text:'بسبب الحرارة والتعرق',correct:true},{text:'لأنه يزيد جماله',correct:false},{text:'لأن المدرسة تشترط ذلك',correct:false},{text:'لأن الشعر ينمو أسرع',correct:false}]},
  },
  {
    id:'u1l2q4', unit:'unit1', lesson:'u1l2', page:19, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'نظافة الشعر تقي من الإصابة بـ:',
    paragraph:'نَظافةُ الشَّعرِ تَقي مِنَ الإصابةِ بالقَمل. (ص19)',
    options:[
      {text:'القمل',correct:true},
      {text:'الزكام',correct:false},
      {text:'كسر الشعر',correct:false},
      {text:'الصداع',correct:false},
    ],
    explanation:'القمل يسكن في الشعر غير النظيف؛ لذا تقليمه وغسله باستمرار يقي منه.',
    goldenRule:'الشعر النظيف يقي من القمل.',
    feedbackQuestion:{question:'ما الذي يسكن في الشعر غير النظيف؟',options:[{text:'القمل',correct:true},{text:'الغبار فقط',correct:false},{text:'الفطريات فقط',correct:false},{text:'لا شيء',correct:false}]},
  },
  {
    id:'u1l2q5', unit:'unit1', lesson:'u1l2', page:19, type:'trueFalse',
    bloom:'understand', difficulty:'medium',
    question:'استخدام الزيت للشعر يساعد على إعطائه لمعةً وجمالاً.',
    paragraph:'استعمالُ الزَّيتِ للشَّعرِ يُساعدُ على لُيونَتِهِ وإعطائِهِ لَمْعةً وجَمالاً. (ص19)',
    correctAnswer:true,
    explanation:'الزيت يغذي الشعر ويُلين خصلاته ويُعطيه لمعةً وجمالاً طبيعياً.',
    goldenRule:'زيت الشعر يُعطيه لمعة وجمالاً طبيعياً.',
    feedbackQuestion:{question:'ما فائدة استعمال الزيت للشعر؟',options:[{text:'يُلين الشعر ويُعطيه لمعة',correct:true},{text:'يقي من القمل فقط',correct:false},{text:'يجعل الشعر جافاً',correct:false},{text:'لا فائدة منه',correct:false}]},
  },
  {
    id:'u1l2q6', unit:'unit1', lesson:'u1l2', page:19, type:'ordering',
    bloom:'apply', difficulty:'medium',
    question:'رتّب خطوات تمشيط الشعر الصحيحة:',
    paragraph:'تَمشيطُ الشَّعرِ بتَقسيمِهِ إلى أقسام، والبدءُ بفَكِّ العُقد، ثمَّ مِن الأطراف، ثمَّ كاملاً. (ص19)',
    items:['تمشيط الشعر كاملاً','فكّ عقد الشعر','تقسيم الشعر إلى أقسام','التمشيط من الأطراف'],
    correctOrder:[2,1,3,0],
    explanation:'الترتيب الصحيح: تقسيم ← فكّ العقد ← من الأطراف ← كاملاً.',
    goldenRule:'ابدأ تمشيط شعرك من الأطراف تجنّباً للانقصاف.',
  },
];

// ─── وحدة 1 | درس 3: آداب دورة المياه ──────────────────────────────────────
const u1l3Questions = [
  {
    id:'u1l3q1', unit:'unit1', lesson:'u1l3', page:22, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'يُكمل دعاء دخول دورة المياه: "اللهم إني أعوذ بك من الخبث":',
    paragraph:'أكملُ دعاءَ دخولِ دورةِ المياه: (اللَّهُمَّ إِنِّي أعوذُ بكَ من ... والخبائث). (ص22)',
    options:[
      {text:'الخُبثِ والخبائث',correct:true},
      {text:'الشيطان والخبائث',correct:false},
      {text:'الشر والفتن',correct:false},
      {text:'الأذى والمرض',correct:false},
    ],
    explanation:'دعاء دخول دورة المياه: "اللهم إني أعوذ بك من الخُبث والخبائث".',
    goldenRule:'دعاء دخول الحمام: "اللهم إني أعوذ بك من الخُبث والخبائث".',
    feedbackQuestion:{question:'متى نقول دعاء دورة المياه؟',options:[{text:'عند الدخول',correct:true},{text:'عند الخروج',correct:false},{text:'قبل النوم',correct:false},{text:'عند الاستحمام',correct:false}]},
  },
  {
    id:'u1l3q2', unit:'unit1', lesson:'u1l3', page:22, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'وجود دورة المياه في كل بيت أمر ضروري للصحة والنظافة.',
    paragraph:'لماذا من الضَّروريِّ وُجودُ دَورةِ مياهٍ في كلِّ بَيت؟ (ص22)',
    correctAnswer:true,
    explanation:'دورة المياه ضرورة حياتية لقضاء الحاجة بشكل نظيف وصحي، وهي من مستلزمات كل بيت.',
    goldenRule:'دورة المياه ضرورة صحية لا غنى عنها في كل منزل.',
    feedbackQuestion:{question:'ما الفائدة الرئيسية من وجود دورة المياه في البيت؟',options:[{text:'الحفاظ على النظافة والصحة',correct:true},{text:'الزخرفة فقط',correct:false},{text:'توفير الماء',correct:false},{text:'لا فائدة محددة',correct:false}]},
  },
  {
    id:'u1l3q3', unit:'unit1', lesson:'u1l3', page:40, type:'multipleChoice',
    bloom:'apply', difficulty:'medium',
    question:'عند دخول دورة المياه يجب أن تُقدّم:',
    paragraph:'عِندَ دُخولي دَوْرةَ المياهِ، أُقَدِّمُ رِجْلي اليُسرى. (تمارين عامة ص73)',
    options:[
      {text:'الرِّجل اليسرى',correct:true},
      {text:'الرِّجل اليمنى',correct:false},
      {text:'أيّ رجل تشاء',correct:false},
      {text:'الرأس أولاً',correct:false},
    ],
    explanation:'عند دخول دورة المياه يُقدَّم الرجل اليسرى، وعند الخروج تُقدَّم اليمنى.',
    goldenRule:'دخول الحمام: الرجل اليسرى. خروجه: الرجل اليمنى.',
    feedbackQuestion:{question:'أيّ الرجلين تُقدّم عند الخروج من دورة المياه؟',options:[{text:'اليمنى',correct:true},{text:'اليسرى',correct:false},{text:'أيّهما تشاء',correct:false},{text:'لا يهم',correct:false}]},
  },
  {
    id:'u1l3q4', unit:'unit1', lesson:'u1l3', page:40, type:'matching',
    bloom:'understand', difficulty:'easy',
    question:'صِل كل موقف بالتصرف المناسب:',
    paragraph:'أختار الأفضل من وجهة نظري: عند دخول دورة المياه / عند مرض أحد إخوتي. (ص73)',
    pairs:[
      {left:'دخول دورة المياه',right:'أُقدّم الرِّجل اليسرى'},
      {left:'الخروج من دورة المياه',right:'أُقدّم الرِّجل اليمنى'},
      {left:'مرض أحد إخوتي',right:'أدعو له بالشفاء'},
      {left:'الانتهاء من دورة المياه',right:'أحافظ على نظافتها'},
    ],
    explanation:'دخول الحمام باليسرى، خروجه باليمنى، عند مرض الأخ: الدعاء، بعد الانتهاء: النظافة.',
    goldenRule:'آداب دورة المياه: الدعاء + الرجل اليسرى دخولاً + اليمنى خروجاً + النظافة.',
  },
  {
    id:'u1l3q5', unit:'unit1', lesson:'u1l3', page:41, type:'trueFalse',
    bloom:'apply', difficulty:'medium',
    question:'يجوز إزعاج المريض بزيارته في دورة مياهه.',
    paragraph:'أساعدُه ولا أُزعجُه. وأتجنَّبُ استخدامَ أدواتِه. (ص40)',
    correctAnswer:false,
    explanation:'يجب مساعدة المريض دون إزعاجه، ومن ذلك احترام راحته وعدم إزعاجه.',
    goldenRule:'عند مرض أحد: ساعده ولا تُزعجه.',
    feedbackQuestion:{question:'ما التصرف الصحيح مع المريض في البيت؟',options:[{text:'مساعدته دون إزعاجه',correct:true},{text:'إزعاجه لرفع روحه المعنوية',correct:false},{text:'استخدام أدواته',correct:false},{text:'تجاهله تماماً',correct:false}]},
  },
  {
    id:'u1l3q6', unit:'unit1', lesson:'u1l3', page:42, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف: أين يرتاح المريض؟ وأين يذهب؟',
    paragraph:'يَرتاحُ المريضُ في: غرفة النوم. يَذهبُ المريضُ إلى: المستشفى / الطبيب. (ص42)',
    categories:['أماكن راحة المريض','أماكن ذهاب المريض'],
    items:[
      {text:'غرفة النوم',correct_category:0},
      {text:'المستشفى',correct_category:1},
      {text:'غرفة الجلوس',correct_category:0},
      {text:'عيادة الطبيب',correct_category:1},
    ],
    explanation:'يرتاح المريض في غرفة النوم أو الجلوس، ويذهب للمستشفى أو عيادة الطبيب.',
    goldenRule:'المريض يرتاح في البيت ويذهب للطبيب أو المستشفى للعلاج.',
  },
];

// ─── وحدة 2 | درس 1: الخجل ─────────────────────────────────────────────────
const u2l1Questions = [
  {
    id:'u2l1q1', unit:'unit2', lesson:'u2l1', page:34, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'من علامات الخجل: تعرُّق اليدين عند الكلام، والارتباك، وعدم القدرة على:',
    paragraph:'مِن عَلامات الخَجَل: تَعرُّق اليَدَين. الارتباكُ والتَّلعثمُ عندَ الكلام. عَدمُ القُدرةِ على الدُّخولِ في المكانِ الذي فيهِ الضُّيوف. (ص35)',
    options:[
      {text:'الدخول في المكان الذي فيه الضيوف',correct:true},
      {text:'النوم في الليل',correct:false},
      {text:'تناول الطعام',correct:false},
      {text:'المشي بشكل طبيعي',correct:false},
    ],
    explanation:'من علامات الخجل: تعرّق اليدين، التلعثم، وعدم القدرة على الدخول لمكان فيه ضيوف.',
    goldenRule:'علامات الخجل: التعرق + التلعثم + صعوبة الدخول أمام الضيوف.',
    feedbackQuestion:{question:'أيّ العلامات لا تدل على الخجل؟',options:[{text:'النوم المبكر',correct:true},{text:'تعرّق اليدين',correct:false},{text:'التلعثم عند الكلام',correct:false},{text:'الارتباك',correct:false}]},
  },
  {
    id:'u2l1q2', unit:'unit2', lesson:'u2l1', page:35, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'الخجل ليس الحياء؛ فهما صفتان مختلفتان.',
    paragraph:'الخَجَلُ لَيسَ الحَياء. (ص36)',
    correctAnswer:true,
    explanation:'الخجل صفة سلبية تحول دون التواصل، أما الحياء فهو صفة إيجابية من الإيمان.',
    goldenRule:'الحياء من الإيمان — والخجل ليس الحياء بل صفة سلبية.',
    feedbackQuestion:{question:'ما الفرق بين الحياء والخجل؟',options:[{text:'الحياء إيجابي من الإيمان، والخجل سلبي',correct:true},{text:'هما نفس الشيء',correct:false},{text:'الخجل أفضل من الحياء',correct:false},{text:'كلاهما سلبيان',correct:false}]},
  },
  {
    id:'u2l1q3', unit:'unit2', lesson:'u2l1', page:36, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'يحثّنا ديننا على الحياء لأنه:',
    paragraph:'دينُنا يَحثُّنا على الحَياء؛ لأنَّهُ مِنَ الإيمان. (ص36)',
    options:[
      {text:'من الإيمان',correct:true},
      {text:'يجعلنا خجولين',correct:false},
      {text:'يمنعنا من الكلام',correct:false},
      {text:'يزيد ثقتنا بأنفسنا',correct:false},
    ],
    explanation:'الحياء من الإيمان كما ثبت في الحديث النبوي الشريف.',
    goldenRule:'الحياء من الإيمان — حافظ على حيائك.',
    feedbackQuestion:{question:'من أيّ شيء هو الحياء وفق تعاليم الإسلام؟',options:[{text:'من الإيمان',correct:true},{text:'من الخجل',correct:false},{text:'من العادة',correct:false},{text:'من الخوف',correct:false}]},
  },
  {
    id:'u2l1q4', unit:'unit2', lesson:'u2l1', page:36, type:'trueFalse',
    bloom:'analyze', difficulty:'medium',
    question:'الخجل الزائد قد يتحوّل إلى خوف.',
    paragraph:'الخَجَلُ الزّائدُ قَد يَتَحوَّلُ إلى خَوف. (ص36)',
    correctAnswer:true,
    explanation:'الخجل الزائد يؤدي إلى العزلة والخوف من المواقف الاجتماعية.',
    goldenRule:'الخجل الزائد خطر — قد يصبح خوفاً يمنعك من الحياة الطبيعية.',
    feedbackQuestion:{question:'ما نتيجة الخجل الزائد؟',options:[{text:'قد يتحول إلى خوف',correct:true},{text:'يجعلك أكثر ذكاءً',correct:false},{text:'يساعدك على التعلم',correct:false},{text:'لا أثر له',correct:false}]},
  },
  {
    id:'u2l1q5', unit:'unit2', lesson:'u2l1', page:36, type:'multipleChoice',
    bloom:'apply', difficulty:'medium',
    question:'لمساعدة زميل يعاني من الخجل، أختار:',
    paragraph:'اختَر ما تَراهُ مُناسِباً كَي تُساعِدَ طالِباً يُعاني مِنَ الخَجَل: أُشارِكُهُ اللَّعب / أُكثِرُ الحديثَ معه / أُعَرِّفُهُ على أكبرِ عَددٍ مِنَ الأصدقاء. (ص35)',
    options:[
      {text:'أشاركه اللعب وأكثر الحديث معه',correct:true},
      {text:'أتجاهله حتى يتعلم وحده',correct:false},
      {text:'أسخر منه أمام الآخرين',correct:false},
      {text:'أتركه منعزلاً',correct:false},
    ],
    explanation:'مساعدة الخجول تكون بمشاركته اللعب وإكثار الحديث معه وتعريفه بالأصدقاء.',
    goldenRule:'ساعد الخجول بمشاركته وإكثار الحديث معه.',
    feedbackQuestion:{question:'ما أفضل طريقة لمساعدة زميل خجول؟',options:[{text:'مشاركته اللعب والحديث معه',correct:true},{text:'تجاهله',correct:false},{text:'السخرية منه',correct:false},{text:'إخباره بعيوبه',correct:false}]},
  },
  {
    id:'u2l1q6', unit:'unit2', lesson:'u2l1', page:37, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف هذه الصفات: صفة خجول أم صفة اجتماعي؟',
    paragraph:'أُلوِّنُ الصِّفاتِ التي أتَّصِفُ بها: خَجول / مَرِح / مُتَعاوِن / مَحبوب / مُنعزل / اجتماعي. (ص37)',
    categories:['صفة الشخص الخجول','صفة الشخص الاجتماعي'],
    items:[
      {text:'منعزل',correct_category:0},
      {text:'مرِح',correct_category:1},
      {text:'خجول',correct_category:0},
      {text:'متعاون',correct_category:1},
      {text:'محبوب',correct_category:1},
      {text:'اجتماعي',correct_category:1},
    ],
    explanation:'الخجول: منعزل وخجول. الاجتماعي: مرِح، متعاون، محبوب، اجتماعي.',
    goldenRule:'كن اجتماعياً: مرحاً متعاوناً محبوباً — لا منعزلاً خجولاً.',
  },
];

// ─── وحدة 2 | درس 2: كيف أتصرف إذا مرض أحد ──────────────────────────────
const u2l2Questions = [
  {
    id:'u2l2q1', unit:'unit2', lesson:'u2l2', page:39, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'إذا مرض أحد في المنزل، المريضُ يحتاج إلى:',
    paragraph:'يَحتاجُ المريضُ إلى: الراحة، والدواء، وزيارة الطبيب. (ص39)',
    options:[
      {text:'الراحة والدواء ورعاية الأسرة',correct:true},
      {text:'اللعب كثيراً',correct:false},
      {text:'الخروج من البيت',correct:false},
      {text:'تناول الطعام فقط',correct:false},
    ],
    explanation:'المريض يحتاج: الراحة في الفراش، الدواء حسب إرشادات الطبيب، ورعاية الأسرة.',
    goldenRule:'المريض يحتاج: راحة + دواء + رعاية الأسرة + الدعاء.',
    feedbackQuestion:{question:'ما أهم شيء يحتاجه المريض أولاً؟',options:[{text:'الراحة في الفراش',correct:true},{text:'اللعب',correct:false},{text:'التلفاز',correct:false},{text:'الخروج',correct:false}]},
  },
  {
    id:'u2l2q2', unit:'unit2', lesson:'u2l2', page:40, type:'ordering',
    bloom:'understand', difficulty:'medium',
    question:'رتّب أحداث القصة: "مرض سعود" حسب تسلسلها الصحيح:',
    paragraph:'أرتّب الأحداث الآتية وَفْقاً لِتَسَلْسُلِها القَصَصيّ. (ص43)',
    items:[
      'تَماثَلَ للشفاء',
      'مَرِضَ سعودٌ وارتفعت حرارتُه',
      'اعتنت به أسرتُه',
      'ذهب إلى الطبيب وكتب له الدواء',
    ],
    correctOrder:[1,3,2,0],
    explanation:'الترتيب: مرض ← ذهاب للطبيب ← اعتناء الأسرة ← الشفاء.',
    goldenRule:'عند المرض: طبيب ← دواء ← راحة ← شفاء.',
  },
  {
    id:'u2l2q3', unit:'unit2', lesson:'u2l2', page:40, type:'multipleChoice',
    bloom:'apply', difficulty:'medium',
    question:'التصرف الصحيح مع المريض المصاب بمرض معدٍ هو:',
    paragraph:'لا أقترِبُ منه إذا كان مَرَضُه مُعدياً. (ص40)',
    options:[
      {text:'لا أقترب منه',correct:true},
      {text:'أُعانقه لأريحه',correct:false},
      {text:'أستخدم أدواته',correct:false},
      {text:'أنام بجانبه',correct:false},
    ],
    explanation:'إذا كان المرض معدياً يجب عدم الاقتراب من المريض تجنباً لانتقال العدوى.',
    goldenRule:'المرض المعدي: لا تقترب! وادعُ له بالشفاء من بعيد.',
    feedbackQuestion:{question:'لماذا لا نقترب من المريض بمرض معدٍ؟',options:[{text:'حتى لا تنتقل العدوى',correct:true},{text:'لأنه لا يريد زيارات',correct:false},{text:'لأن الطبيب نهى عن ذلك',correct:false},{text:'لا سبب',correct:false}]},
  },
  {
    id:'u2l2q4', unit:'unit2', lesson:'u2l2', page:40, type:'matching',
    bloom:'understand', difficulty:'easy',
    question:'صِل التصرف السليم بنقيضه الخاطئ:',
    paragraph:'التصرف السليم vs التصرف الخاطئ مع المريض. (ص40-41)',
    pairs:[
      {left:'أساعده ولا أُزعجه',right:'أُزعجه وقت راحته'},
      {left:'أتجنّب استخدام أدواته',right:'أستخدم أدواته وأدويته'},
      {left:'أذكّره بموعد الدواء',right:'أنسى موعد الدواء'},
      {left:'أدعو له بالشفاء',right:'أتجاهل دعاءه'},
    ],
    explanation:'مقابلة بين التصرف السليم والخاطئ مع المريض.',
    goldenRule:'التصرف السليم مع المريض: المساعدة + الدعاء + تذكير الدواء + عدم استخدام أدواته.',
  },
  {
    id:'u2l2q5', unit:'unit2', lesson:'u2l2', page:40, type:'trueFalse',
    bloom:'analyze', difficulty:'medium',
    question:'زيارة المريض تُدخل السرور إلى نفسه وتُخفّف عنه.',
    paragraph:'نَقومُ بِزيارةِ المريضِ لِكَسبِ الأجرِ مِنَ الله وإدخالِ السُّرورِ إلى نَفسِهِ والتَّخفيفِ عنه. (ص44)',
    correctAnswer:true,
    explanation:'زيارة المريض سنّة تُدخل السرور له وتُخفّف ألمه، ونكسب الأجر من الله.',
    goldenRule:'زيارة المريض: أجر عند الله + سرور للمريض + تخفيف عنه.',
    feedbackQuestion:{question:'ما فوائد زيارة المريض؟',options:[{text:'أجر + سرور + تخفيف عنه',correct:true},{text:'لا فائدة منها',correct:false},{text:'تُعدي المرض',correct:false},{text:'تُتعب المريض',correct:false}]},
  },
  {
    id:'u2l2q6', unit:'unit2', lesson:'u2l2', page:40, type:'fillBlank',
    bloom:'remember', difficulty:'easy',
    question:'أكمل دعاء شفاء المريض: "أسأل اللهَ العظيم ربَّ العرشِ العظيم أن ___ ."',
    paragraph:'"أسألُ اللهَ العَظيمَ رَبَّ العَرشِ العَظيمِ أنْ يَشفيَك." (ص40)',
    blanks:['يشفيَك'],
    wordBank:['يشفيَك','يرزقَك','يهديَك','يحفظَك'],
    explanation:'دعاء عيادة المريض يُقال 7 مرات: "أسأل الله العظيم رب العرش العظيم أن يشفيك".',
    goldenRule:'دعاء العيادة: "أسأل الله العظيم رب العرش العظيم أن يشفيك" — 7 مرات.',
  },
];

// ─── وحدة 3 | درس 1: التقويم الهجري والميلادي ──────────────────────────────
const u3l1Questions = [
  {
    id:'u3l1q1', unit:'unit3', lesson:'u3l1', page:56, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'تتكوّن السنةُ الهجرية من:',
    paragraph:'تَتَكوَّنُ السَّنةُ الهِجريَّةُ من اثنَي عَشَرَ شَهراً. (ص57)',
    options:[
      {text:'اثني عشر شهراً',correct:true},
      {text:'عشرة أشهر',correct:false},
      {text:'ثلاثة عشر شهراً',correct:false},
      {text:'أحد عشر شهراً',correct:false},
    ],
    explanation:'السنة الهجرية تتكوّن من 12 شهراً قمرياً تبدأ بمحرم وتنتهي بذي الحجة.',
    goldenRule:'السنة الهجرية = 12 شهراً من محرم حتى ذي الحجة.',
    feedbackQuestion:{question:'ما أول أشهر السنة الهجرية؟',options:[{text:'محرم',correct:true},{text:'رمضان',correct:false},{text:'رجب',correct:false},{text:'شوال',correct:false}]},
  },
  {
    id:'u3l1q2', unit:'unit3', lesson:'u3l1', page:57, type:'ordering',
    bloom:'remember', difficulty:'medium',
    question:'رتّب هذه الأشهر الهجرية ترتيباً صحيحاً:',
    paragraph:'أشهر السنة الهجرية: محرم، صفر، ربيع الأول، ربيع الثاني، جمادى الأولى، جمادى الثانية... (ص57)',
    items:['ربيع الأول','محرم','رجب','صفر'],
    correctOrder:[1,3,0,2],
    explanation:'الترتيب: محرم → صفر → ربيع الأول → رجب.',
    goldenRule:'أشهر هجرية: محرم، صفر، ربيع الأول، ربيع الثاني، جمادى الأولى، جمادى الثانية، رجب...',
  },
  {
    id:'u3l1q3', unit:'unit3', lesson:'u3l1', page:56, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'التقويم يُستخدم مدة عام كامل.',
    paragraph:'يُستعملُ التَّقويمُ مُدَّةَ عامٍ كامِل. (ص56)',
    correctAnswer:true,
    explanation:'التقويم يُستخدم طوال السنة الكاملة لتنظيم الأيام والمواعيد.',
    goldenRule:'التقويم يُستخدم سنةً كاملة لتنظيم الأيام والمواعيد.',
    feedbackQuestion:{question:'لماذا نستخدم التقويم؟',options:[{text:'لتنظيم الأيام والمواعيد',correct:true},{text:'للزينة فقط',correct:false},{text:'لمعرفة الطقس',correct:false},{text:'لا نستخدمه',correct:false}]},
  },
  {
    id:'u3l1q4', unit:'unit3', lesson:'u3l1', page:56, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'أوقات الصلاة الخمس في الترتيب الصحيح هي:',
    paragraph:'أُحدِّدُ أوقاتَ الصَّلواتِ الخَمسِ: الفجر، الظهر، العصر، المغرب، العشاء. (ص57)',
    options:[
      {text:'فجر، ظهر، عصر، مغرب، عشاء',correct:true},
      {text:'فجر، عصر، ظهر، مغرب، عشاء',correct:false},
      {text:'ظهر، فجر، عصر، مغرب، عشاء',correct:false},
      {text:'عشاء، مغرب، عصر، ظهر، فجر',correct:false},
    ],
    explanation:'الصلوات الخمس بترتيبها: الفجر → الظهر → العصر → المغرب → العشاء.',
    goldenRule:'الصلوات الخمس: فجر → ظهر → عصر → مغرب → عشاء.',
    feedbackQuestion:{question:'ما آخر صلاة في اليوم؟',options:[{text:'العشاء',correct:true},{text:'المغرب',correct:false},{text:'العصر',correct:false},{text:'الفجر',correct:false}]},
  },
  {
    id:'u3l1q5', unit:'unit3', lesson:'u3l1', page:57, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف هذه الأشهر: هجرية أم ميلادية؟',
    paragraph:'أشهر السنة الهجرية والميلادية. (ص57-61)',
    categories:['أشهر هجرية','أشهر ميلادية'],
    items:[
      {text:'محرم',correct_category:0},
      {text:'يناير',correct_category:1},
      {text:'رمضان',correct_category:0},
      {text:'مارس',correct_category:1},
      {text:'ذو الحجة',correct_category:0},
      {text:'ديسمبر',correct_category:1},
    ],
    explanation:'هجرية: محرم، رمضان، ذو الحجة. ميلادية: يناير، مارس، ديسمبر.',
    goldenRule:'هجرية: تبدأ بمحرم. ميلادية: تبدأ بيناير.',
  },
  {
    id:'u3l1q6', unit:'unit3', lesson:'u3l1', page:58, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'بعض التقاويم تحتوي على آيات وأحاديث فلا يجوز رميها.',
    paragraph:'بعضُ التَّقاويمِ تَحتوي على آياتٍ وأحاديثَ فلا تَرمِها بَل استَفِدْ منها للمَدرسة. (ص58)',
    correctAnswer:true,
    explanation:'التقاويم التي فيها آيات أو أحاديث يجب الاحتفاظ بها أو الاستفادة منها ولا يجوز رميها.',
    goldenRule:'التقويم الذي يحتوي آيات أو أحاديث لا يُرمى — استفد منه.',
    feedbackQuestion:{question:'ماذا نفعل بالتقويم الذي فيه آيات قرآنية؟',options:[{text:'نحتفظ به أو نستفيد منه',correct:true},{text:'نرميه مع النفايات',correct:false},{text:'نحرقه',correct:false},{text:'لا يهمنا',correct:false}]},
  },
];

// ─── وحدة 3 | درس 2: التقويم الميلادي ──────────────────────────────────────
const u3l2Questions = [
  {
    id:'u3l2q1', unit:'unit3', lesson:'u3l2', page:60, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'سُمّيت السنة الميلادية بهذا الاسم لأنها تدل على:',
    paragraph:'تُسَمَّى السَّنةُ المِيلاديَّةُ بالسَّنةِ الشَّمسيَّة؛ لأنَّها تَدُلُّ على إكمالِ الأرضِ دَورةً كاملةً حَولَ الشَّمس. (ص62)',
    options:[
      {text:'إكمال الأرض دورة كاملة حول الشمس',correct:true},
      {text:'ميلاد شخص مشهور',correct:false},
      {text:'بداية الزراعة',correct:false},
      {text:'اكتشاف القمر',correct:false},
    ],
    explanation:'تسمى السنة الميلادية "شمسية" لأنها تدل على إكمال الأرض دورة كاملة حول الشمس (365 يوماً).',
    goldenRule:'السنة الميلادية = شمسية = دورة الأرض حول الشمس = 12 شهراً.',
    feedbackQuestion:{question:'لماذا تُسمّى السنة الميلادية "شمسية"؟',options:[{text:'لأنها تعتمد على دوران الأرض حول الشمس',correct:true},{text:'لأن الشمس تشرق فيها',correct:false},{text:'لأنها حارة',correct:false},{text:'لأن أشهرها طويلة',correct:false}]},
  },
  {
    id:'u3l2q2', unit:'unit3', lesson:'u3l2', page:61, type:'ordering',
    bloom:'remember', difficulty:'medium',
    question:'رتّب هذه الأشهر الميلادية ترتيباً صحيحاً:',
    paragraph:'أشهر السنة الميلادية: يناير، فبراير، مارس، إبريل... (ص61)',
    items:['مارس','يناير','إبريل','فبراير'],
    correctOrder:[1,3,0,2],
    explanation:'يناير → فبراير → مارس → إبريل.',
    goldenRule:'أشهر ميلادية: يناير → فبراير → مارس → إبريل → مايو → يونيو → يوليو → أغسطس → سبتمبر → أكتوبر → نوفمبر → ديسمبر.',
  },
  {
    id:'u3l2q3', unit:'unit3', lesson:'u3l2', page:63, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'يوم 23 سبتمبر يُعدّ:',
    paragraph:'اقرأ ثمَّ لوِّن تاريخَ اليومِ الوطنيِّ السُّعودي. (ص63 — 23 سبتمبر)',
    options:[
      {text:'اليوم الوطني السعودي',correct:true},
      {text:'يوم الاستقلال',correct:false},
      {text:'يوم المعلم',correct:false},
      {text:'يوم الطفل',correct:false},
    ],
    explanation:'23 سبتمبر هو اليوم الوطني للمملكة العربية السعودية.',
    goldenRule:'23 سبتمبر = اليوم الوطني السعودي.',
    feedbackQuestion:{question:'في أيّ شهر يقع اليوم الوطني السعودي؟',options:[{text:'سبتمبر',correct:true},{text:'أكتوبر',correct:false},{text:'يناير',correct:false},{text:'مارس',correct:false}]},
  },
  {
    id:'u3l2q4', unit:'unit3', lesson:'u3l2', page:62, type:'matching',
    bloom:'remember', difficulty:'medium',
    question:'صِل كل فصل بأشهره الميلادية:',
    paragraph:'توزيع الشهور الميلادية بين الفصول الأربعة. (ص63)',
    pairs:[
      {left:'الشتاء',right:'ديسمبر، يناير، فبراير'},
      {left:'الربيع',right:'مارس، إبريل، مايو'},
      {left:'الصيف',right:'يونيو، يوليو، أغسطس'},
      {left:'الخريف',right:'سبتمبر، أكتوبر، نوفمبر'},
    ],
    explanation:'الشتاء: ديسمبر-يناير-فبراير. الربيع: مارس-إبريل-مايو. الصيف: يونيو-يوليو-أغسطس. الخريف: سبتمبر-أكتوبر-نوفمبر.',
    goldenRule:'أشهر الفصول: شتاء (12،1،2) — ربيع (3،4،5) — صيف (6،7،8) — خريف (9،10،11).',
  },
  {
    id:'u3l2q5', unit:'unit3', lesson:'u3l2', page:61, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'السنة الميلادية والهجرية لهما نفس عدد الأشهر.',
    paragraph:'تَتَكوَّنُ السَّنةُ المِيلاديَّةُ من اثنَي عَشَرَ شَهراً مِثلَ السَّنةِ الهِجريَّة، وَلَكِنَّ أسماءَها مُختَلِفة. (ص61)',
    correctAnswer:true,
    explanation:'كلتاهما 12 شهراً، لكن أسماء الأشهر مختلفة: الهجرية تبدأ بمحرم، والميلادية بيناير.',
    goldenRule:'الهجرية والميلادية: كلاهما 12 شهراً لكن الأسماء مختلفة.',
    feedbackQuestion:{question:'ما وجه الشبه بين السنة الهجرية والميلادية؟',options:[{text:'عدد الأشهر 12 في كلتيهما',correct:true},{text:'أسماء الأشهر متطابقة',correct:false},{text:'يبدآن في نفس اليوم',correct:false},{text:'لا يوجد شبه',correct:false}]},
  },
  {
    id:'u3l2q6', unit:'unit3', lesson:'u3l2', page:59, type:'fillBlank',
    bloom:'apply', difficulty:'medium',
    question:'أكمل الجدول: التقويم يُستعمل مدة ___ كامل. ويعرض التاريخ ___ والتاريخ ___ .',
    paragraph:'يستعمل التقويم مدة عامٍ كامل. يعرض التاريخ الهجري والتاريخ الميلادي. أوقات الصلاة كُتبت في التقويم. (ص59)',
    blanks:['عام','الهجري','الميلادي'],
    wordBank:['عام','الهجري','الميلادي','الشهري'],
    explanation:'التقويم: مدة عام، يعرض التاريخين الهجري والميلادي، وأوقات الصلاة.',
    goldenRule:'التقويم: عام كامل + تاريخ هجري + تاريخ ميلادي + أوقات الصلاة.',
  },
];

export const QUESTIONS_UNITS_1_3 = [
  ...u1l1Questions, ...u1l2Questions, ...u1l3Questions,
  ...u2l1Questions, ...u2l2Questions,
  ...u3l1Questions, ...u3l2Questions,
];