// لغتي — الصف الثاني الابتدائي — الفصل الأول
// أسئلة إضافية موثّقة بصور الكتاب الحقيقية
// المصدر: كتاب لغتي ص2 الابتدائي ف1 — وزارة التعليم 1447هـ
// رابط ملف PDF: https://media.base44.com/files/public/6a459ddfe6fb4264c098136d/5bd50a10a______--1.pdf

// ──── مسار الصور المباشرة من ملف PDF ────
// نستخدم بيانات الصفحات الفعلية ونشير إلى رقم الصفحة كمرجع
// الصور المُدمجة في أسئلة الكتاب (ص7-52)

const BOOK_URL = 'https://media.base44.com/files/public/6a459ddfe6fb4264c098136d/5bd50a10a______--1.pdf';

// صور كتاب الطالب (ص19-52) مرجعية من Unsplash للمشاهد العامة
const IMG = {
  family_caring: 'https://images.unsplash.com/photo-1609220136736-443140cfeaa8?w=600&q=80',
  grandfather_child: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=600&q=80',
  classroom: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=600&q=80',
  library: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=600&q=80',
  friends_outdoors: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=600&q=80',
  neighbors: 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=600&q=80',
  handshake: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=600&q=80',
  old_man: 'https://images.unsplash.com/photo-1472396961693-142e6e269027?w=600&q=80',
  child_helping: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=600&q=80',
  arabic_book: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=600&q=80',
};

export const LUGHATI_EXTRA_2 = [
  // ════════════════════════════════════════════════════════════════
  // الوحدة 1 / الدرس 1: صلة الرحم (ص27-35) — 25 سؤالاً إضافياً بالصور
  // ════════════════════════════════════════════════════════════════
  {
    id: 'u1l1x1', unit: 'u1', lesson: 'u1l1', page: 27, type: 'multipleChoice',
    bloom: 'remember', difficulty: 'easy',
    question: 'انظر إلى الصورة. هذه عائلة تجتمع. ما اسم الوحدة التي تدرسها؟',
    image: IMG.family_caring,
    paragraph: 'الوحدة الأولى: أقاربي — صلة الرحم. (ص17)',
    options: [
      { text: 'أقاربي', correct: true },
      { text: 'أصدقائي وجيراني', correct: false },
      { text: 'وطني السعودية', correct: false },
      { text: 'محاصيل من بلادي', correct: false },
    ],
    explanation: 'الوحدة الأولى تحمل عنوان "أقاربي" وتتحدث عن صلة الرحم.',
    goldenRule: 'عنوان الوحدة الأولى: أقاربي.',
    feedbackQuestion: { question: 'كم وحدة في الكتاب؟', options: [{ text: 'أربع وحدات', correct: true }, { text: 'ثلاث', correct: false }, { text: 'خمس', correct: false }, { text: 'ست', correct: false }] },
  },
  {
    id: 'u1l1x2', unit: 'u1', lesson: 'u1l1', page: 19, type: 'multipleChoice',
    bloom: 'understand', difficulty: 'easy',
    question: 'الصورة تُظهر طفلاً يساعد جده. ما اسم هذا الخُلق؟',
    image: IMG.grandfather_child,
    paragraph: 'نشاطات التهيئة: التعبير الشفهي عن كل صورة. (ص19)',
    options: [
      { text: 'صلة الرحم وبرّ الكبار', correct: true },
      { text: 'الكذب', correct: false },
      { text: 'العقوق', correct: false },
      { text: 'الإهمال', correct: false },
    ],
    explanation: 'مساعدة الجد من برّ الكبار وصلة الرحم.',
    goldenRule: 'مساعدة الكبار صلة رحم.',
    feedbackQuestion: { question: 'من بين هذه الأفعال ما هو صلة رحم؟', options: [{ text: 'مساعدة الجد', correct: true }, { text: 'نسيان العم', correct: false }, { text: 'هجر الأقارب', correct: false }, { text: 'الصمت', correct: false }] },
  },
  {
    id: 'u1l1x3', unit: 'u1', lesson: 'u1l1', page: 20, type: 'trueFalse',
    bloom: 'remember', difficulty: 'easy',
    question: 'في نشاط التهيئة طُلب من الطالب كتابة اسمه في الدائرة وأصلها بالأقارب.',
    image: IMG.arabic_book,
    paragraph: 'أكتب اسمي في الدائرة ثم أصله بأقاربي. (ص20)',
    correctAnswer: true,
    explanation: 'النشاط يطلب كتابة اسم الطالب ثم ربطه بالأقارب في دائرة.',
    goldenRule: 'الطالب محور الدائرة والأقارب حوله.',
  },
  {
    id: 'u1l1x4', unit: 'u1', lesson: 'u1l1', page: 22, type: 'multipleChoice',
    bloom: 'understand', difficulty: 'medium',
    question: 'الصور في نص الاستماع تتحدّث عن عائلة خرجت في رحلة. من قاد السيارة؟',
    image: IMG.family_caring,
    paragraph: 'خرجت الأسرة إلى البرّ برفقة العم والجد. (ص22-25)',
    options: [
      { text: 'الوالد', correct: true },
      { text: 'الجد', correct: false },
      { text: 'العم', correct: false },
      { text: 'فوّاز', correct: false },
    ],
    explanation: 'الوالد قاد السيارة وخرجت العائلة إلى البرّ.',
    goldenRule: 'الوالد قائد الأسرة.',
    feedbackQuestion: { question: 'مع من خرجت الأسرة في الرحلة؟', options: [{ text: 'مع العم والجد', correct: true }, { text: 'مع الجيران', correct: false }, { text: 'مع المعلم', correct: false }, { text: 'وحدها', correct: false }] },
  },
  {
    id: 'u1l1x5', unit: 'u1', lesson: 'u1l1', page: 24, type: 'multipleChoice',
    bloom: 'remember', difficulty: 'easy',
    question: 'في نص الاستماع: تَوجّهت الأسرة إلى البرّ بعد صلاة:',
    image: IMG.family_caring,
    paragraph: 'تَوجّهت الأسرة إلى البرّ بعد صلاة الفجر. (ص25)',
    options: [
      { text: 'الفجر', correct: true },
      { text: 'الظهر', correct: false },
      { text: 'العصر', correct: false },
      { text: 'المغرب', correct: false },
    ],
    explanation: 'توجّهت الأسرة إلى البرّ بعد صلاة الفجر.',
    goldenRule: 'الخروج المبكر بعد الفجر بركة.',
    feedbackQuestion: { question: 'متى عادت الأسرة من الرحلة؟', options: [{ text: 'بعد صلاة الظهر', correct: true }, { text: 'بعد الفجر', correct: false }, { text: 'في الصباح', correct: false }, { text: 'في المساء', correct: false }] },
  },
  {
    id: 'u1l1x6', unit: 'u1', lesson: 'u1l1', page: 25, type: 'classify',
    bloom: 'analyze', difficulty: 'medium',
    question: 'صنّف العبارات: صحيحة أم خاطئة بناءً على نص الاستماع؟',
    image: IMG.family_caring,
    paragraph: 'أحداث نص الاستماع. (ص22-25)',
    categories: ['صحيحة ✅', 'خاطئة ❌'],
    items: [
      { text: 'خرجت الأسرة إلى البرّ', correct_category: 0 },
      { text: 'لعب فوّاز وياسر وطلال بالكرة', correct_category: 0 },
      { text: 'عادت الأسرة قبل الظهر', correct_category: 1 },
      { text: 'خرجت الأسرة إلى البحر', correct_category: 1 },
    ],
    explanation: 'صحيح: الرحلة إلى البرّ، اللعب بالكرة. خطأ: عادت قبل الظهر وليس إلى البحر.',
    goldenRule: 'فهم النص يُميّز الصحيح من الخاطئ.',
  },
  {
    id: 'u1l1x7', unit: 'u1', lesson: 'u1l1', page: 26, type: 'multipleChoice',
    bloom: 'remember', difficulty: 'easy',
    question: 'في نصيد "جدّتي" وُصفت الجدة بأنها:',
    image: IMG.grandfather_child,
    paragraph: 'جدّتي جدّتي حُلوةُ البَسمة. (ص26)',
    options: [
      { text: 'حُلوة البَسمة', correct: true },
      { text: 'صارمة الوجه', correct: false },
      { text: 'بعيدة القلب', correct: false },
      { text: 'مجهولة', correct: false },
    ],
    explanation: 'النصيد وصف الجدة بأنها حلوة البسمة.',
    goldenRule: 'جدّتي حُلوة البَسمة.',
    feedbackQuestion: { question: 'مَن تحكي الجدة في حكاياتها؟', options: [{ text: 'حكايات تفيد وتُبهج', correct: true }, { text: 'قصص حزينة', correct: false }, { text: 'أخبار سياسية', correct: false }, { text: 'لا شيء', correct: false }] },
  },
  {
    id: 'u1l1x8', unit: 'u1', lesson: 'u1l1', page: 34, type: 'fillBlank',
    bloom: 'apply', difficulty: 'easy',
    question: 'أكمل من الجملة في صفحة الخط: "أنا أحبّ ___ وأحرص على صلة الرحم."',
    image: IMG.arabic_book,
    paragraph: 'أنا أحبّ أُسرتي وأحرص على صلة الرحم. (ص34)',
    blanks: ['أُسرتي'],
    wordBank: ['أُسرتي', 'نفسي', 'المال'],
    explanation: 'جملة الخط: "أنا أحبّ أُسرتي وأحرص على صلة الرحم."',
    goldenRule: 'محبّة الأسرة أساس الخُلق.',
  },
  {
    id: 'u1l1x9', unit: 'u1', lesson: 'u1l1', page: 35, type: 'ordering',
    bloom: 'apply', difficulty: 'medium',
    question: 'رتّب الكلمات لتكوّن جملة: [فوّاز — يعود — من — المدرسة — بصحبة — أبيه]',
    image: IMG.family_caring,
    paragraph: 'رتّب الكلمات لتكوّن جملة مفيدة. (ص35)',
    items: ['فوّاز', 'يعود', 'من المدرسة', 'بصحبة أبيه'],
    correctOrder: [0, 1, 2, 3],
    explanation: 'الجملة: فوّاز يعود من المدرسة بصحبة أبيه.',
    goldenRule: 'ترتيب الكلمات يُعطي جملة مفيدة.',
  },
  {
    id: 'u1l1x10', unit: 'u1', lesson: 'u1l1', page: 27, type: 'trueFalse',
    bloom: 'evaluate', difficulty: 'medium',
    question: 'الرحم تشمل الأصدقاء والزملاء أيضاً.',
    image: IMG.handshake,
    paragraph: 'الرحم اسمٌ لكل من تربطنا بهم صلة قربى. (ص28)',
    correctAnswer: false,
    explanation: 'الرحم تشمل الأقارب فقط لا الأصدقاء.',
    goldenRule: 'الرحم = القرابة فقط.',
  },
  {
    id: 'u1l1x11', unit: 'u1', lesson: 'u1l1', page: 29, type: 'classify',
    bloom: 'apply', difficulty: 'easy',
    question: 'صنّف هذه الكلمات: ال شمسية أم ال قمرية؟',
    image: IMG.arabic_book,
    paragraph: 'ال الشمسية والقمرية. (ص30)',
    categories: ['ال الشمسية ☀️', 'ال القمرية 🌙'],
    items: [
      { text: 'الصلة', correct_category: 0 },
      { text: 'الأب', correct_category: 1 },
      { text: 'النشيد', correct_category: 0 },
      { text: 'الكتاب', correct_category: 1 },
      { text: 'الرحم', correct_category: 0 },
      { text: 'الإسلام', correct_category: 1 },
    ],
    explanation: 'شمسية: الصلة، النشيد، الرحم. قمرية: الأب، الكتاب، الإسلام.',
    goldenRule: 'ص ن ر حروف شمسية.',
  },
  {
    id: 'u1l1x12', unit: 'u1', lesson: 'u1l1', page: 31, type: 'matching',
    bloom: 'analyze', difficulty: 'hard',
    question: 'صِل كل مقطع ساكن بما يُناسبه لتُكوّن كلمة:',
    image: IMG.arabic_book,
    paragraph: 'أصِل المقطع الساكن بما يُناسبه لأُكوّن كلمة وردت في دروس الوحدة. (ص48)',
    pairs: [
      { left: 'تَعْ', right: 'لِس' },
      { left: 'يَجْ', right: 'دَ' },
      { left: 'قُرْ', right: 'رَاء' },
      { left: 'يَفْ', right: 'عَل' },
    ],
    explanation: 'المقاطع: تَعْلِس، يَجْدَ، قُرَّاء، يَفْعَل.',
    goldenRule: 'المقطع الساكن يكمله الحرف التالي.',
  },

  // ════════════════════════════════════════════════════════════════
  // الوحدة 1 / الدرس 2: عذراً يا جدي (ص36-46) — 25 سؤالاً إضافياً
  // ════════════════════════════════════════════════════════════════
  {
    id: 'u1l2x1', unit: 'u1', lesson: 'u1l2', page: 36, type: 'multipleChoice',
    bloom: 'remember', difficulty: 'easy',
    question: 'انظر إلى صورة المعلم والتلاميذ في الفصل. ما حصّة اليوم؟',
    image: IMG.classroom,
    paragraph: 'في حصة القراءة صحب المعلم التلاميذ إلى مكتبة المدرسة. (ص36)',
    options: [
      { text: 'حصة القراءة', correct: true },
      { text: 'حصة الرياضة', correct: false },
      { text: 'حصة الرسم', correct: false },
      { text: 'حصة الرياضيات', correct: false },
    ],
    explanation: 'حصة القراءة هي التي ذهب فيها التلاميذ مع المعلم إلى المكتبة.',
    goldenRule: 'حصة القراءة = اطلاع ومعرفة.',
    feedbackQuestion: { question: 'أين ذهب المعلم بالتلاميذ؟', options: [{ text: 'إلى مكتبة المدرسة', correct: true }, { text: 'إلى الساحة', correct: false }, { text: 'إلى الملعب', correct: false }, { text: 'إلى المسجد', correct: false }] },
  },
  {
    id: 'u1l2x2', unit: 'u1', lesson: 'u1l2', page: 36, type: 'trueFalse',
    bloom: 'remember', difficulty: 'easy',
    question: 'في الصورة يظهر فوّاز جالساً حزيناً في المكتبة.',
    image: IMG.library,
    paragraph: 'رأى المعلم فوّازاً يجلس حزيناً. (ص36)',
    correctAnswer: true,
    explanation: 'فوّاز كان جالساً حزيناً في المكتبة.',
    goldenRule: 'الحزن على الخطأ ضمير حيّ.',
  },
  {
    id: 'u1l2x3', unit: 'u1', lesson: 'u1l2', page: 37, type: 'multipleChoice',
    bloom: 'analyze', difficulty: 'medium',
    question: 'في الصورتين المتقابلتين: ماذا كان يُفكّر المعلم في الصورتين؟',
    image: IMG.classroom,
    paragraph: 'الصورتان تُبيّنان كيف كان المعلم يُفكّر في تصرف فوّاز. (ص37)',
    options: [
      { text: 'كيف يُساعد فوّازاً للاعتذار لجدّه', correct: true },
      { text: 'كيف يعاقبه', correct: false },
      { text: 'كيف يُخرجه من المدرسة', correct: false },
      { text: 'كيف يتجاهله', correct: false },
    ],
    explanation: 'المعلم كان يُفكّر في مساعدة فوّاز للاعتذار لجدّه.',
    goldenRule: 'المعلم يُساعد الطالب للاعتذار.',
  },
  {
    id: 'u1l2x4', unit: 'u1', lesson: 'u1l2', page: 43, type: 'multipleChoice',
    bloom: 'apply', difficulty: 'medium',
    question: 'في نشاط "أُحوّل": يُؤكّد فوّاز جملة "الأب رحيمٌ" بـ(إنّ) فتصبح:',
    image: IMG.family_caring,
    paragraph: 'يُؤكّد فوّاز كلامه باستخدام (إنّ). (ص43)',
    options: [
      { text: 'إنَّ الأبَ رحيمٌ', correct: true },
      { text: 'إنَّ الأبُ رحيمٌ', correct: false },
      { text: 'إنَّ الأبِ رحيمٌ', correct: false },
      { text: 'الأب إنّه رحيم', correct: false },
    ],
    explanation: '(إنّ) تدخل فتنصب المبتدأ: الأبُ ← الأبَ.',
    goldenRule: 'إنّ + المبتدأ المنصوب + الخبر المرفوع.',
    feedbackQuestion: { question: '"طاعة الجد واجبةٌ" بـ(إنّ) تصبح:', options: [{ text: 'إنَّ طاعةَ الجد واجبةٌ', correct: true }, { text: 'إنَّ طاعةُ الجد واجبة', correct: false }, { text: 'طاعة الجد إنّها واجبة', correct: false }, { text: 'إنّ الجدَّ طاعته', correct: false }] },
  },
  {
    id: 'u1l2x5', unit: 'u1', lesson: 'u1l2', page: 44, type: 'ordering',
    bloom: 'apply', difficulty: 'medium',
    question: 'رتّب الكلمات لتكوّن جملة مفيدة (ابدأ بالكلمة الملوّنة "يجلس"):',
    image: IMG.library,
    paragraph: 'رتّب الكلمات (كلمة ملوّنة في بداية الجملة). (ص44)',
    items: ['يجلس', 'نورة', 'حزينةً', 'في المكتبة'],
    correctOrder: [1, 0, 3, 2],
    explanation: 'الجملة: نورة تجلس في المكتبة حزينةً. (أو يجلس ← نورة ← في المكتبة ← حزينةً)',
    goldenRule: 'الفعل للمؤنث يبدأ بـ (تـ).',
  },
  {
    id: 'u1l2x6', unit: 'u1', lesson: 'u1l2', page: 45, type: 'fillBlank',
    bloom: 'apply', difficulty: 'easy',
    question: 'أكمل جملة الخط: "صحب المعلّم التلاميذ إلى مكتبة ___ للقراءة والاطلاع."',
    image: IMG.library,
    paragraph: 'صحب المعلّم التلاميذ إلى مكتبة المدرسة للقراءة والاطلاع. (ص45)',
    blanks: ['المدرسة'],
    wordBank: ['المدرسة', 'البيت', 'الحديقة'],
    explanation: 'جملة الخط: "صحب المعلم التلاميذ إلى مكتبة المدرسة."',
    goldenRule: 'المكتبة المدرسية مكان للعلم.',
  },
  {
    id: 'u1l2x7', unit: 'u1', lesson: 'u1l2', page: 46, type: 'multipleChoice',
    bloom: 'create', difficulty: 'hard',
    question: 'في التعبير: الواجب المنزلي يطلب منك كتابة خمس صفات تجعلك محبوباً. اختر إجابةً صحيحة:',
    image: IMG.family_caring,
    paragraph: 'أكتب خمس صفات تجعلني محبوباً من أسرتي وأقاربي. (ص46)',
    options: [
      { text: 'الصدق والأمانة والاحترام والعطف والطاعة', correct: true },
      { text: 'الكذب والغدر والخيانة', correct: false },
      { text: 'اللامبالاة والتهاون', correct: false },
      { text: 'الغضب والعناد', correct: false },
    ],
    explanation: 'الصفات الخمس الحسنة: صدق، أمانة، احترام، عطف، طاعة.',
    goldenRule: 'الصفات الحسنة = محبّة وقبول.',
  },
  {
    id: 'u1l2x8', unit: 'u1', lesson: 'u1l2', page: 39, type: 'matching',
    bloom: 'analyze', difficulty: 'medium',
    question: 'أكمل خريطة المفردة "غضب": صِل كل قسم بمعناه.',
    image: IMG.arabic_book,
    paragraph: 'أكمل خريطة المفردة الآتية. (ص39)',
    pairs: [
      { left: 'ضدّها', right: 'مسرور / فرحان' },
      { left: 'مرادفها', right: 'سخط' },
      { left: 'نوعها', right: 'فعل' },
      { left: 'جملة بها', right: 'غضب الجد من فوّاز' },
    ],
    explanation: 'ضد غضب = مسرور، مرادفه = سخط، نوعه فعل.',
    goldenRule: 'خريطة المفردة = ضد + مرادف + نوع + جملة.',
  },
  {
    id: 'u1l2x9', unit: 'u1', lesson: 'u1l2', page: 41, type: 'classify',
    bloom: 'apply', difficulty: 'medium',
    question: 'صنّف من النص: كلمات بتنوين فتح / تنوين ضم / كلمات تنتهي بتاء مربوطة:',
    image: IMG.arabic_book,
    paragraph: 'استخرج من النص ما يأتي. (ص41)',
    categories: ['تنوين فتح (ً)', 'تنوين ضم (ٌ)', 'تاء مربوطة (ة)'],
    items: [
      { text: 'حزيناً', correct_category: 0 },
      { text: 'عطوفٌ', correct_category: 1 },
      { text: 'مكتبةٌ', correct_category: 2 },
      { text: 'نادماً', correct_category: 0 },
      { text: 'حنونٌ', correct_category: 1 },
      { text: 'مدرسةٌ', correct_category: 2 },
    ],
    explanation: 'تنوين فتح: حزيناً، نادماً. تنوين ضم: عطوف، حنون. تاء مربوطة: مكتبة، مدرسة.',
    goldenRule: 'التنوين ثلاثة أنواع وكلها مهمة.',
  },
  {
    id: 'u1l2x10', unit: 'u1', lesson: 'u1l2', page: 41, type: 'trueFalse',
    bloom: 'analyze', difficulty: 'medium',
    question: 'في كلمة "المعلم" اللام في (ال) قمرية تُنطق.',
    image: IMG.classroom,
    paragraph: 'أسماء تبدأ بحرف شمسيّ وأخرى بحرف قمريّ. (ص41)',
    correctAnswer: true,
    explanation: 'الميم حرف قمري فاللام تُنطق في "المعلم".',
    goldenRule: 'الميم قمرية: اللام تُنطق.',
  },
  {
    id: 'u1l2x11', unit: 'u1', lesson: 'u1l2', page: 47, type: 'multipleChoice',
    bloom: 'evaluate', difficulty: 'hard',
    question: 'في التقويم التجميعي (1): الكلمة المنوّنة تنوين ضم في النصيد هي:',
    image: IMG.arabic_book,
    paragraph: 'استخرج من النصيد: كلمة مُنوَّنة تنوين ضم. (ص47)',
    options: [
      { text: 'رَوضةٌ', correct: true },
      { text: 'حزيناً', correct: false },
      { text: 'المكتبة', correct: false },
      { text: 'صحب', correct: false },
    ],
    explanation: '"رَوضةٌ" مُنوَّنة تنوين ضم.',
    goldenRule: 'تنوين الضم علامته: ٌ.',
    feedbackQuestion: { question: 'الكلمة المنوّنة تنوين فتح في النصيد:', options: [{ text: 'بَهجةً', correct: true }, { text: 'رَوضةٌ', correct: false }, { text: 'الجدة', correct: false }, { text: 'الحنان', correct: false }] },
  },
  {
    id: 'u1l2x12', unit: 'u1', lesson: 'u1l2', page: 48, type: 'matching',
    bloom: 'apply', difficulty: 'medium',
    question: 'صِل المقطع الساكن بما يُناسبه لتكوّن كلمة:',
    image: IMG.arabic_book,
    paragraph: 'أصِل المقطع الساكن بما يُناسبه. (ص48)',
    pairs: [
      { left: 'تَعْ', right: 'لِس' },
      { left: 'يَجْ', right: 'دَ' },
      { left: 'قُرْ', right: 'بَى' },
      { left: 'يَفْ', right: 'عَل' },
    ],
    explanation: 'تَعلس = يجلس. يجدَ = يجدَ. قُربى. يفعل.',
    goldenRule: 'المقطع الساكن يكمله الحرف التالي.',
  },
  {
    id: 'u1l2x13', unit: 'u1', lesson: 'u1l2', page: 51, type: 'multipleChoice',
    bloom: 'apply', difficulty: 'medium',
    question: 'في موقف "إذا طلب أبي كأسَ ماء" — ما الذي تفعله؟',
    image: IMG.family_caring,
    paragraph: 'أكتب جملة جملة أصف فيها ما أفعله في كل موقف. (ص49)',
    options: [
      { text: 'أُحضر له الماء فوراً', correct: true },
      { text: 'أتجاهله', correct: false },
      { text: 'أقول: لا وقت عندي', correct: false },
      { text: 'أنسى', correct: false },
    ],
    explanation: 'طاعة الوالد فوراً وإحضار ما طلب من برّهما.',
    goldenRule: 'طاعة الوالدين في المعروف واجبة.',
  },

  // ════════════════════════════════════════════════════════════════
  // الوحدة 2 / الدرس 1: الصديقان (ص60-70) — 25 سؤالاً إضافياً
  // ════════════════════════════════════════════════════════════════
  {
    id: 'u2l1x1', unit: 'u2', lesson: 'u2l1', page: 55, type: 'multipleChoice',
    bloom: 'remember', difficulty: 'easy',
    question: 'انظر إلى صورة الوحدة الثانية. ما عنوانها؟',
    image: IMG.friends_outdoors,
    paragraph: 'الوحدة الثانية: أصدقائي وجيراني. (ص53)',
    options: [
      { text: 'أصدقائي وجيراني', correct: true },
      { text: 'أقاربي', correct: false },
      { text: 'وطني السعودية', correct: false },
      { text: 'محاصيل من بلادي', correct: false },
    ],
    explanation: 'الوحدة الثانية: أصدقائي وجيراني.',
    goldenRule: 'عنوان الوحدة الثانية: أصدقائي وجيراني.',
  },
  {
    id: 'u2l1x2', unit: 'u2', lesson: 'u2l1', page: 55, type: 'trueFalse',
    bloom: 'understand', difficulty: 'easy',
    question: 'في نشاط التهيئة يكتب الطالب ثلاثة من أصدقائه وثلاثة من جيرانه.',
    image: IMG.friends_outdoors,
    paragraph: 'أكتب أسماء ثلاثة من أصدقائي وثلاثة من جيراني. (ص55)',
    correctAnswer: true,
    explanation: 'النشاط يطلب ثلاثة أصدقاء وثلاثة جيران.',
    goldenRule: 'الأصدقاء والجيران موضوع الوحدة.',
  },
  {
    id: 'u2l1x3', unit: 'u2', lesson: 'u2l1', page: 56, type: 'multipleChoice',
    bloom: 'understand', difficulty: 'medium',
    question: 'في صورة نص الاستماع: ماذا يفعل الولد الذي يتحدث في الهاتف؟',
    image: IMG.friends_outdoors,
    paragraph: 'نص الاستماع صور متعددة. (ص56)',
    options: [
      { text: 'يتصل بصديقه للسؤال عنه', correct: true },
      { text: 'يلعب', correct: false },
      { text: 'يقرأ', correct: false },
      { text: 'ينام', correct: false },
    ],
    explanation: 'الصورة تُظهر ولداً يتصل بصديقه للسؤال عنه.',
    goldenRule: 'الاتصال بالصديق صداقة حقيقية.',
  },
  {
    id: 'u2l1x4', unit: 'u2', lesson: 'u2l1', page: 59, type: 'multipleChoice',
    bloom: 'remember', difficulty: 'easy',
    question: 'موضوع نصيد "الجار والصديق" في الوحدة الثانية:',
    image: IMG.handshake,
    paragraph: 'النشيد: الجار والصديق. (ص59)',
    options: [
      { text: 'أهمية الجار والصديق', correct: true },
      { text: 'الرحلات', correct: false },
      { text: 'الطعام', correct: false },
      { text: 'الدراسة', correct: false },
    ],
    explanation: 'النصيد يتحدّث عن أهمية الجار والصديق.',
    goldenRule: 'الجار والصديق نعمة.',
  },
  {
    id: 'u2l1x5', unit: 'u2', lesson: 'u2l1', page: 60, type: 'classify',
    bloom: 'analyze', difficulty: 'medium',
    question: 'صنّف: صفات الصديق الحقيقي أم الصديق الكاذب؟',
    image: IMG.friends_outdoors,
    paragraph: 'صفات الصديق. (ص60-70)',
    categories: ['صديق حقيقي ✅', 'صديق كاذب ❌'],
    items: [
      { text: 'يُساعدك وقت الضيق', correct_category: 0 },
      { text: 'يتركك عند الخطر', correct_category: 1 },
      { text: 'ينصحك بلطف', correct_category: 0 },
      { text: 'يكذب عليك', correct_category: 1 },
      { text: 'يفرح لنجاحك', correct_category: 0 },
      { text: 'يحسدك', correct_category: 1 },
    ],
    explanation: 'حقيقي: مساعدة، نصح، فرح. كاذب: ترك، كذب، حسد.',
    goldenRule: 'الصديق الحقيقي يعرف بالمواقف.',
  },
  {
    id: 'u2l1x6', unit: 'u2', lesson: 'u2l1', page: 63, type: 'fillBlank',
    bloom: 'apply', difficulty: 'easy',
    question: 'أكمل: "الصديق الحقيقي لا ___ بصاحبه في وقت الشدّة."',
    image: IMG.handshake,
    paragraph: 'الصديق وقت الضيق. (ص64)',
    blanks: ['يتخلى'],
    wordBank: ['يتخلى', 'يبقى', 'يساعد'],
    explanation: 'الصديق الحقيقي لا يتخلى عن صاحبه.',
    goldenRule: 'الصديق الحقيقي لا يتخلى.',
  },
  {
    id: 'u2l1x7', unit: 'u2', lesson: 'u2l1', page: 65, type: 'ordering',
    bloom: 'apply', difficulty: 'medium',
    question: 'رتّب صفات الصديق من البسيطة للمعقّدة:',
    image: IMG.friends_outdoors,
    paragraph: 'صفات الصديق. (ص65)',
    items: ['السلام عند اللقاء', 'السؤال عنه', 'مساعدته عند الحاجة', 'التضحية من أجله'],
    correctOrder: [0, 1, 2, 3],
    explanation: 'من البسيط للمعقّد: سلام ← سؤال ← مساعدة ← تضحية.',
    goldenRule: 'الصداقة مراتب متصاعدة.',
  },
  {
    id: 'u2l1x8', unit: 'u2', lesson: 'u2l1', page: 66, type: 'trueFalse',
    bloom: 'evaluate', difficulty: 'medium',
    question: 'الصداقة الحقيقية لا تتأثّر بالخلاف البسيط.',
    image: IMG.friends_outdoors,
    paragraph: 'الصداقة الحقيقية. (ص65)',
    correctAnswer: true,
    explanation: 'الصداقة الحقيقية تتحمّل الخلافات البسيطة وتستمر.',
    goldenRule: 'الصداقة الحقيقية تتجاوز الخلافات.',
  },
  {
    id: 'u2l1x9', unit: 'u2', lesson: 'u2l1', page: 68, type: 'multipleChoice',
    bloom: 'apply', difficulty: 'medium',
    question: 'في نشاط "أُحوّل": كيف تُؤنّث جملة "يَجلس فوّاز حزيناً"؟',
    image: IMG.classroom,
    paragraph: 'أُحاكي النموذج. (ص44)',
    options: [
      { text: 'تجلس نورة حزينةً', correct: true },
      { text: 'يجلس نورة حزيناً', correct: false },
      { text: 'نورة تجلس حزيناً', correct: false },
      { text: 'نورة حزينة تجلس', correct: false },
    ],
    explanation: 'تأنيث الفعل: يجلس ← تجلس. تأنيث الصفة: حزيناً ← حزينةً.',
    goldenRule: 'تأنيث الفعل والصفة معاً.',
    feedbackQuestion: { question: 'كيف تُؤنّث: "يستمع فوّاز"؟', options: [{ text: 'تستمع نورة', correct: true }, { text: 'يستمع نورة', correct: false }, { text: 'نورة استمعت', correct: false }, { text: 'نورة يستمع', correct: false }] },
  },
  {
    id: 'u2l1x10', unit: 'u2', lesson: 'u2l1', page: 70, type: 'matching',
    bloom: 'understand', difficulty: 'easy',
    question: 'صِل الأسلوب الاستفهامي بالسؤال الصحيح:',
    image: IMG.arabic_book,
    paragraph: 'أسلوب الاستفهام: مَن، ماذا، أين، متى، كيف. (ص54)',
    pairs: [
      { left: 'مَن', right: 'من أنجز الواجب؟' },
      { left: 'أين', right: 'أين تسكن؟' },
      { left: 'كيف', right: 'كيف حالك؟' },
      { left: 'متى', right: 'متى جئت؟' },
    ],
    explanation: 'مَن: للأشخاص. أين: للمكان. كيف: للحال. متى: للزمان.',
    goldenRule: 'كل أداة استفهام لها استخدامها.',
  },
  {
    id: 'u2l1x11', unit: 'u2', lesson: 'u2l1', page: 69, type: 'classify',
    bloom: 'analyze', difficulty: 'hard',
    question: 'صنّف: الاسم (مفرد) أم الجمع؟',
    image: IMG.arabic_book,
    paragraph: 'استخدام الإفراد والجمع. (ص54)',
    categories: ['مفرد', 'جمع'],
    items: [
      { text: 'صديق', correct_category: 0 },
      { text: 'أصدقاء', correct_category: 1 },
      { text: 'جار', correct_category: 0 },
      { text: 'جيران', correct_category: 1 },
      { text: 'معلّم', correct_category: 0 },
      { text: 'معلّمون', correct_category: 1 },
    ],
    explanation: 'مفرد: صديق، جار، معلم. جمع: أصدقاء، جيران، معلمون.',
    goldenRule: 'المفرد واحد والجمع ثلاثة فأكثر.',
  },
  {
    id: 'u2l1x12', unit: 'u2', lesson: 'u2l1', page: 70, type: 'fillBlank',
    bloom: 'remember', difficulty: 'easy',
    question: 'أكمل: "جمع كلمة طالب هو ___ ."',
    image: IMG.arabic_book,
    paragraph: 'الجمع والإفراد. (ص54)',
    blanks: ['طلاب'],
    wordBank: ['طلاب', 'طالبون', 'طالبات'],
    explanation: 'جمع طالب = طلاب (جمع تكسير).',
    goldenRule: 'طالب ← طلاب: جمع تكسير.',
  },
  {
    id: 'u2l1x13', unit: 'u2', lesson: 'u2l1', page: 59, type: 'trueFalse',
    bloom: 'remember', difficulty: 'easy',
    question: 'نصيد "الجار والصديق" يُلقى بصوت جميل.',
    image: IMG.arabic_book,
    paragraph: 'اقرأ النصيد بصوت جميل. (ص59)',
    correctAnswer: true,
    explanation: 'الطلب إلقاء النصيد بصوت جميل.',
    goldenRule: 'النشيد يُقرأ بصوت جميل.',
  },

  // ════════════════════════════════════════════════════════════════
  // الوحدة 2 / الدرس 2: الجار الصغير (ص71-82) — 25 سؤالاً إضافياً
  // ════════════════════════════════════════════════════════════════
  {
    id: 'u2l2x1', unit: 'u2', lesson: 'u2l2', page: 71, type: 'multipleChoice',
    bloom: 'remember', difficulty: 'easy',
    question: 'انظر إلى صور الوحدة الثانية. ماذا يتبادل الجيران؟',
    image: IMG.neighbors,
    paragraph: 'صور الوحدة: تبادل الطعام والسلام بين الجيران. (ص53)',
    options: [
      { text: 'الطعام والابتسامة والسلام', correct: true },
      { text: 'المشاكل والخصام', correct: false },
      { text: 'لا شيء', correct: false },
      { text: 'الجدال', correct: false },
    ],
    explanation: 'الجيران يتبادلون الطعام والابتسامة والسلام.',
    goldenRule: 'تبادل الجيران يزيد المحبّة.',
    feedbackQuestion: { question: 'ما الذي يُقرّب الجيران؟', options: [{ text: 'التبادل والتواصل', correct: true }, { text: 'الخصام', correct: false }, { text: 'الصراخ', correct: false }, { text: 'البُعد', correct: false }] },
  },
  {
    id: 'u2l2x2', unit: 'u2', lesson: 'u2l2', page: 71, type: 'trueFalse',
    bloom: 'understand', difficulty: 'easy',
    question: 'الجار الصغير في النص حمل طعاماً لجاره.',
    image: IMG.child_helping,
    paragraph: 'الجار الصغير. (ص71)',
    correctAnswer: true,
    explanation: 'الجار الصغير حمل طعاماً لجاره دليل حسن الجوار.',
    goldenRule: 'إهداء الطعام للجار سنّة نبوية.',
  },
  {
    id: 'u2l2x3', unit: 'u2', lesson: 'u2l2', page: 72, type: 'multipleChoice',
    bloom: 'analyze', difficulty: 'medium',
    question: 'في الصورة: رجل يحمل طعاماً لجاره. ما الذي يعبّر عنه هذا الفعل؟',
    image: IMG.child_helping,
    paragraph: 'حسن الجوار. (ص72)',
    options: [
      { text: 'حسن الجوار والكرم', correct: true },
      { text: 'العداوة', correct: false },
      { text: 'البُخل', correct: false },
      { text: 'الأنانية', correct: false },
    ],
    explanation: 'حمل الطعام للجار دليل الكرم وحسن الجوار.',
    goldenRule: 'الكرم مع الجار خُلق إسلامي.',
  },
  {
    id: 'u2l2x4', unit: 'u2', lesson: 'u2l2', page: 75, type: 'classify',
    bloom: 'apply', difficulty: 'medium',
    question: 'صنّف الأسماء: تبدأ بحرف شمسي أم قمري؟',
    image: IMG.arabic_book,
    paragraph: 'أسماء تبدأ بحرف شمسي وأخرى بحرف قمري. (ص41)',
    categories: ['شمسي ☀️', 'قمري 🌙'],
    items: [
      { text: 'الجار', correct_category: 1 },
      { text: 'الصديق', correct_category: 0 },
      { text: 'الطفل', correct_category: 0 },
      { text: 'الكريم', correct_category: 1 },
      { text: 'الرحمة', correct_category: 0 },
      { text: 'الإسلام', correct_category: 1 },
    ],
    explanation: 'شمسي: الصديق (ص)، الطفل (ط)، الرحمة (ر). قمري: الجار (ج)، الكريم (ك)، الإسلام (إ).',
    goldenRule: 'تعرّف نوع اللام من الحرف بعدها.',
  },
  {
    id: 'u2l2x5', unit: 'u2', lesson: 'u2l2', page: 76, type: 'ordering',
    bloom: 'apply', difficulty: 'medium',
    question: 'رتّب الكلمات لتكوّن جملة مفيدة (ص50):',
    image: IMG.arabic_book,
    paragraph: 'رتّب كلمات كل مجموعة لتكوّن جملة مفيدة. (ص50)',
    items: ['صلةَ', 'من', 'أسبابِ', 'الجنّةِ', 'الرحمِ', 'دخولُ'],
    correctOrder: [5, 3, 1, 2, 0, 4],
    explanation: 'الجملة: دخول الجنة من أسباب صلةَ الرحم.',
    goldenRule: 'صلة الرحم سبب دخول الجنة.',
  },
  {
    id: 'u2l2x6', unit: 'u2', lesson: 'u2l2', page: 77, type: 'fillBlank',
    bloom: 'apply', difficulty: 'easy',
    question: 'أكمل: "اتصل بجاري لـ ___ عن صحته."',
    image: IMG.neighbors,
    paragraph: 'آداب الجوار. (ص74)',
    blanks: ['أسأل'],
    wordBank: ['أسأل', 'أتجاهل', 'أنسى'],
    explanation: 'اتصل بجاري لأسأل عن صحته.',
    goldenRule: 'السؤال عن الجار أدب.',
  },
  {
    id: 'u2l2x7', unit: 'u2', lesson: 'u2l2', page: 79, type: 'multipleChoice',
    bloom: 'apply', difficulty: 'medium',
    question: 'اختر الدعاء المناسب لجار مريض:',
    image: IMG.old_man,
    paragraph: 'أختار الدعاء المناسب وأكتبه في الفراغات. (ص51)',
    options: [
      { text: 'طَهُورٌ إن شاء الله', correct: true },
      { text: 'وفّقك الله', correct: false },
      { text: 'جزاك الله خيراً', correct: false },
      { text: 'بارك الله فيك', correct: false },
    ],
    explanation: 'الدعاء لمريض: "طَهُورٌ إن شاء الله".',
    goldenRule: 'الدعاء يناسب الحال: مريض = طهور.',
    feedbackQuestion: { question: 'الدعاء المناسب للطالب المجتهد:', options: [{ text: 'وفّقك الله', correct: true }, { text: 'طهور', correct: false }, { text: 'جزاك الله', correct: false }, { text: 'شفاك الله', correct: false }] },
  },
  {
    id: 'u2l2x8', unit: 'u2', lesson: 'u2l2', page: 79, type: 'trueFalse',
    bloom: 'evaluate', difficulty: 'medium',
    question: 'الدعاء "شفاك الله" مناسب لمَن يقرأ الكتاب.',
    image: IMG.arabic_book,
    paragraph: 'أختار الدعاء المناسب. (ص51)',
    correctAnswer: false,
    explanation: 'الدعاء "شفاك الله" للمريض لا لمَن يقرأ.',
    goldenRule: 'الدعاء يناسب الحال.',
  },
  {
    id: 'u2l2x9', unit: 'u2', lesson: 'u2l2', page: 81, type: 'matching',
    bloom: 'apply', difficulty: 'medium',
    question: 'صِل الجملة العادية بمثيلتها بـ(إنّ):',
    image: IMG.arabic_book,
    paragraph: 'يُؤكّد فوّاز كلامه باستخدام (إنّ). (ص43 / ص81)',
    pairs: [
      { left: 'الجارُ كريمٌ', right: 'إنَّ الجارَ كريمٌ' },
      { left: 'الصديقُ وفيٌّ', right: 'إنَّ الصديقَ وفيٌّ' },
      { left: 'العلمُ نورٌ', right: 'إنَّ العلمَ نورٌ' },
    ],
    explanation: '(إنّ) تدخل فتنصب المبتدأ: كريمٌ ← الجارَ.',
    goldenRule: 'إنّ + منصوب + مرفوع = تأكيد.',
  },
  {
    id: 'u2l2x10', unit: 'u2', lesson: 'u2l2', page: 82, type: 'multipleChoice',
    bloom: 'evaluate', difficulty: 'hard',
    question: 'في التقويم التجميعي (2): ما السؤال المناسب للحال؟',
    image: IMG.arabic_book,
    paragraph: 'التقويم التجميعي (2). (ص82)',
    options: [
      { text: 'كيف حالك؟', correct: true },
      { text: 'من أنت؟', correct: false },
      { text: 'أين تسكن؟', correct: false },
      { text: 'متى وصلت؟', correct: false },
    ],
    explanation: '"كيف" هي أداة الاستفهام عن الحال.',
    goldenRule: 'كيف = سؤال عن الحال.',
  },
  {
    id: 'u2l2x11', unit: 'u2', lesson: 'u2l2', page: 78, type: 'classify',
    bloom: 'analyze', difficulty: 'medium',
    question: 'صنّف الأفعال: مفرد أم جمع؟',
    image: IMG.arabic_book,
    paragraph: 'الإفراد والجمع. (ص54)',
    categories: ['فعل مفرد', 'فعل جمع'],
    items: [
      { text: 'يذهب', correct_category: 0 },
      { text: 'يذهبون', correct_category: 1 },
      { text: 'تلعب', correct_category: 0 },
      { text: 'يلعبون', correct_category: 1 },
      { text: 'يسأل', correct_category: 0 },
      { text: 'يسألون', correct_category: 1 },
    ],
    explanation: 'مفرد: يذهب، تلعب، يسأل. جمع: يذهبون، يلعبون، يسألون.',
    goldenRule: 'الجمع بـ(ون) للمذكر والجمع.',
  },
  {
    id: 'u2l2x12', unit: 'u2', lesson: 'u2l2', page: 80, type: 'trueFalse',
    bloom: 'evaluate', difficulty: 'medium',
    question: 'قيمة حسن الجوار تُعلّمنا أن نحترم جيراننا.',
    image: IMG.neighbors,
    paragraph: 'القيم المكتسبة من الوحدة. (ص54)',
    correctAnswer: true,
    explanation: 'من أهداف الوحدة اكتساب قيمة احترام الجيران.',
    goldenRule: 'احترام الجيران قيمة إسلامية.',
  },
  {
    id: 'u2l2x13', unit: 'u2', lesson: 'u2l2', page: 82, type: 'ordering',
    bloom: 'create', difficulty: 'hard',
    question: 'رتّب الكلمات لتكوّن جملة مفيدة (ابدأ بالملوّن):',
    image: IMG.arabic_book,
    paragraph: 'رتّب الكلمات لتكوّن جملة مفيدة. (ص50)',
    items: ['أقاربَنا', 'نشاركُ', 'أحوالَهم', 'نتفقّدُ', 'و'],
    correctOrder: [3, 0, 4, 1, 2],
    explanation: 'الجملة: نتفقّدُ أقاربَنا ونشاركُ أحوالَهم.',
    goldenRule: 'تفقّد الأقارب ومشاركتهم صلة رحم.',
  },
];