// لغتي — الصف الثاني الابتدائي — الفصل الأول
// مستخرج من كتاب الطالب 1447هـ / 2025م
import { LUGHATI_EXTRA_1 } from './lughatiGrade2S1_Extra';
import { LUGHATI_EXTRA_2 } from './lughatiGrade2S1_Extra2';
import { LUGHATI_EXTRA_3 } from './lughatiGrade2S1_Extra3';
import { LUGHATI_EXTRA_4 } from './lughatiGrade2S1_Extra4';

export const META = {
  title: 'بنك أسئلة لغتي',
  subject: 'اللغة العربية — لغتي',
  grade: 'الصف الثاني الابتدائي',
  term: 'الفصل الأول',
  publisher: 'وزارة التعليم — المملكة العربية السعودية',
  book: 'لغتي 1447هـ / 2025م',
};

export const UNITS = [
  {
    id: 'u1',
    title: 'الوحدة الأولى: أقاربي',
    color: '#8b5cf6',
    icon: '👨‍👩‍👧‍👦',
    lessons: [
      { id: 'u1l1', title: 'الدرس الأول: صلة الرحم', page: 27, unitId: 'u1' },
      { id: 'u1l2', title: 'الدرس الثاني: عذراً يا جدي', page: 36, unitId: 'u1' },
    ],
  },
  {
    id: 'u2',
    title: 'الوحدة الثانية: أصدقائي وجيراني',
    color: '#0891b2',
    icon: '🤝',
    lessons: [
      { id: 'u2l1', title: 'الدرس الأول: الصديقان', page: 60, unitId: 'u2' },
      { id: 'u2l2', title: 'الدرس الثاني: الجار الصغير', page: 71, unitId: 'u2' },
    ],
  },
  {
    id: 'u3',
    title: 'الوحدة الثالثة: وطني السعودية',
    color: '#16a34a',
    icon: '🇸🇦',
    lessons: [
      { id: 'u3l1', title: 'الدرس الأول: مدينتان مقدستان', page: 90, unitId: 'u3' },
      { id: 'u3l2', title: 'الدرس الثاني: وطني الجميل', page: 110, unitId: 'u3' },
    ],
  },
  {
    id: 'u4',
    title: 'الوحدة الرابعة: محاصيل من بلادي',
    color: '#d97706',
    icon: '🌴',
    lessons: [
      { id: 'u4l1', title: 'الدرس الأول: النخيل', page: 130, unitId: 'u4' },
      { id: 'u4l2', title: 'الدرس الثاني: محاصيل أخرى', page: 150, unitId: 'u4' },
    ],
  },
];

export const BLOOM_LABELS = {
  remember: 'تذكُّر', understand: 'فهم', apply: 'تطبيق',
  analyze: 'تحليل', create: 'تركيب', evaluate: 'تقويم',
};
export const DIFFICULTY_LABELS = { easy: 'سهل', medium: 'متوسط', hard: 'صعب' };

// ──────── الوحدة الأولى / الدرس الأول: صلة الرحم ────────────────────────
const u1l1Qs = [
  {
    id:'u1l1q1', unit:'u1', lesson:'u1l1', page:27, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'سمع فوّاز ونورة في الإذاعة حديثاً شريفاً عن صلة الرحم. أمر الرسول صلى الله عليه وسلم بـ:',
    paragraph:'"مَن كَانَ يُؤمِنُ بِاللهِ وَاليَومِ الآخِرِ فَليَصِل رَحِمَهُ" — رواه البخاري رقم 6138. (ص27)',
    options:[
      {text:'صلة الرحم',correct:true},
      {text:'قطيعة الرحم',correct:false},
      {text:'الابتعاد عن الأقارب',correct:false},
      {text:'الصمت أمام الأهل',correct:false},
    ],
    explanation:'الحديث الشريف يأمر بصلة الرحم أي التواصل مع الأقارب ومساعدتهم والسؤال عنهم.',
    goldenRule:'مَن آمَن باللهِ واليومِ الآخِر فليَصِل رَحِمَهُ — صلة الرحم واجبة.',
    feedbackQuestion:{question:'ما الراوي الذي روى حديث "من كان يؤمن بالله واليوم الآخر فليصل رحمه"؟',options:[{text:'البخاري',correct:true},{text:'مسلم',correct:false},{text:'أبو داود',correct:false},{text:'الترمذي',correct:false}]},
  },
  {
    id:'u1l1q2', unit:'u1', lesson:'u1l1', page:28, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'الرحم اسمٌ لكل من تربطنا بهم صلة قربى.',
    paragraph:'الأب: الرحم اسمٌ لكل مَن تربطنا بهم صلة قربى. (ص28)',
    correctAnswer:true,
    explanation:'الرحم تعني جميع الأقارب الذين تجمعنا بهم علاقة قرابة سواء كانوا آباء أو أعماماً أو جدوداً.',
    goldenRule:'الرحم = كل من تربطنا بهم صلة قربى من الأقارب.',
    feedbackQuestion:{question:'مَن يشمله معنى "الأرحام"؟',options:[{text:'جميع الأقارب',correct:true},{text:'الأصدقاء فقط',correct:false},{text:'الجيران فقط',correct:false},{text:'زملاء الدراسة',correct:false}]},
  },
  {
    id:'u1l1q3', unit:'u1', lesson:'u1l1', page:28, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'تعني صلة الرحم زيارة الأقارب والسؤال عنهم وتفقّد أحوالهم ومساعدتهم عند الحاجة. هذا التعريف اقترحه:',
    paragraph:'الأب: صلة الرحم تعني زيارة الأقارب، والسؤال عنهم، وتفقّد أحوالهم، ومساعدتهم عند الحاجة، ومشاركتهم أفراحهم وأحزانهم. (ص28)',
    options:[
      {text:'الأب شارحاً لفوّاز ونورة',correct:true},
      {text:'فوّاز وحده',correct:false},
      {text:'نورة وحدها',correct:false},
      {text:'المذيع في الإذاعة',correct:false},
    ],
    explanation:'الأب هو من شرح لأبنائه معنى صلة الرحم في النص وأوضح مكوناتها الخمسة.',
    goldenRule:'صلة الرحم = زيارة + سؤال + تفقّد + مساعدة + مشاركة الأفراح والأحزان.',
    feedbackQuestion:{question:'ما عنصر من عناصر صلة الرحم؟',options:[{text:'مساعدتهم عند الحاجة',correct:true},{text:'الابتعاد عنهم',correct:false},{text:'تجنب مشاركتهم',correct:false},{text:'رفض زيارتهم',correct:false}]},
  },
  {
    id:'u1l1q4', unit:'u1', lesson:'u1l1', page:28, type:'ordering',
    bloom:'apply', difficulty:'medium',
    question:'رتّب عناصر صلة الرحم كما وردت في النص:',
    paragraph:'صلة الرحم تعني: (١) زيارة الأقارب (٢) السؤال عنهم (٣) تفقّد أحوالهم (٤) مساعدتهم عند الحاجة (٥) مشاركتهم أفراحهم وأحزانهم. (ص28)',
    items:['مساعدتهم عند الحاجة','زيارة الأقارب','مشاركة الأفراح والأحزان','السؤال عنهم'],
    correctOrder:[1,3,0,2],
    explanation:'الترتيب: زيارة ← سؤال ← تفقّد أحوال ← مساعدة ← مشاركة أفراح وأحزان.',
    goldenRule:'صلة الرحم عمل دائم ومتكامل — لا تقتصر على الزيارة وحدها.',
  },
  {
    id:'u1l1q5', unit:'u1', lesson:'u1l1', page:28, type:'multipleChoice',
    bloom:'analyze', difficulty:'medium',
    question:'اقترح فوّاز على أبيه أن يخصّصا يوماً لزيارة الأرحام. ردّ الأب على فكرة فوّاز بقوله:',
    paragraph:'الأب: إنه رأيٌ جميل، بارك الله فيك يا بُنيّ. (ص28)',
    options:[
      {text:'إنه رأيٌ جميل، بارك الله فيك يا بُنيّ',correct:true},
      {text:'لا، هذا الوقت غير مناسب',correct:false},
      {text:'سنرى في المستقبل',correct:false},
      {text:'نحن نزور أقاربنا كثيراً',correct:false},
    ],
    explanation:'الأب أيّد فكرة فوّاز ومدحه لأن الفكرة موافقة للحديث الشريف في صلة الرحم.',
    goldenRule:'الفكرة الجيدة تستحق المدح والتشجيع — صلة الرحم خير كله.',
    feedbackQuestion:{question:'كيف ردّت نورة على اقتراح أبيها بتخصيص يوم للزيارة؟',options:[{text:'أنا متشوّقة لهذا اليوم يا أبي',correct:true},{text:'لا أريد الذهاب',correct:false},{text:'لديّ واجبات كثيرة',correct:false},{text:'لم تردّ',correct:false}]},
  },
  {
    id:'u1l1q6', unit:'u1', lesson:'u1l1', page:29, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف الكلمات التالية: ال الشمسية أم ال القمرية؟',
    paragraph:'اللام في (ال) القمرية تُكتب ساكنةً وتُنطق ساكنة. اللام في (ال) الشمسية تُكتب ولا تُنطق والحرف الذي بعدها يُكتب مُشدَّداً. (ص30)',
    categories:['ال الشمسية ☀️','ال القمرية 🌙'],
    items:[
      {text:'الرحم',correct_category:0},
      {text:'الأقارب',correct_category:1},
      {text:'الحاجة',correct_category:0},
      {text:'اليوم',correct_category:1},
      {text:'السؤال',correct_category:0},
      {text:'البنت',correct_category:1},
    ],
    explanation:'الشمسية: الرحم، الحاجة، السؤال (اللام لا تُنطق). القمرية: الأقارب، اليوم، البنت (اللام تُنطق).',
    goldenRule:'ال الشمسية: اللام لا تُنطق + تشديد الحرف التالي. ال القمرية: اللام تُنطق.',
  },
  {
    id:'u1l1q7', unit:'u1', lesson:'u1l1', page:32, type:'fillBlank',
    bloom:'apply', difficulty:'easy',
    question:'أكمل جملة الدعاء باستخدام (اللهم):',
    paragraph:'أدعو الله أن يشفيَ أُمّي. → اللهمَّ اشفِ أُمّي. (ص32)',
    blanks:['اللهمّ','اشفِ'],
    wordBank:['اللهمّ','اشفِ','أنا','أدعو'],
    explanation:'أسلوب الدعاء: نقول "اللهمّ" ثم نذكر ما ندعو به. مثال: اللهمّ اشفِ أُمّي.',
    goldenRule:'أسلوب الدعاء = "اللهمّ" + الطلب. مثل: اللهمّ وفّقني / اللهمّ احفظ وطني.',
  },
  {
    id:'u1l1q8', unit:'u1', lesson:'u1l1', page:33, type:'matching',
    bloom:'understand', difficulty:'medium',
    question:'صِل كل فعل بنظيره المؤنّث:',
    paragraph:'الوالد يعطف على الأبناء. ← الوالدة تعطف على الأبناء. (ص33)',
    pairs:[
      {left:'الجد يحكي حكايات مفيدة',right:'الجدة تحكي حكايات مفيدة'},
      {left:'الخال يساعد الأسرة',right:'الخالة تساعد الأسرة'},
      {left:'الوالد يعطف على الأبناء',right:'الوالدة تعطف على الأبناء'},
      {left:'العمّ يحنو علينا',right:'العمّة تحنو علينا'},
    ],
    explanation:'الفعل يُؤنَّث بإضافة تاء في أوله: يَحكي → تَحكي، يُساعد → تُساعد.',
    goldenRule:'تأنيث الفعل: نضع (تـ) بدلاً من (يـ) في أول الفعل عند الحديث عن المؤنث.',
  },
  {
    id:'u1l1q9', unit:'u1', lesson:'u1l1', page:29, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'عبارة "تَفقَّد أحوالَهم" في سياق صلة الرحم تعني:',
    paragraph:'صلة الرحم تعني: وتفقّد أحوالهم. (ص28)',
    options:[
      {text:'الاطمئنان على أحوالهم والاهتمام بهم',correct:true},
      {text:'التحدث معهم بصوت عالٍ',correct:false},
      {text:'أخذ أموالهم',correct:false},
      {text:'مراقبتهم عن بُعد',correct:false},
    ],
    explanation:'تفقّد الأحوال يعني الاهتمام بالأقارب والسؤال عن صحتهم وأحوالهم الحياتية.',
    goldenRule:'تفقّد الأحوال = الاطمئنان + الاهتمام + السؤال الدوري.',
    feedbackQuestion:{question:'ما ضد "تفقّد أحوالهم"؟',options:[{text:'البُعد عنهم وإهمالهم',correct:true},{text:'زيارتهم كثيراً',correct:false},{text:'مساعدتهم',correct:false},{text:'السؤال عنهم',correct:false}]},
  },
  {
    id:'u1l1q10', unit:'u1', lesson:'u1l1', page:34, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'الجملة الاسمية تُؤكَّد بـ (إنّ). الجملة "الصلةُ واجبةٌ" مؤكَّدة بـ (إنّ) تصبح:',
    paragraph:'الصلةُ واجبةٌ. → إنَّ الصلةَ واجبةٌ. (ص33)',
    options:[
      {text:'إنَّ الصلةَ واجبةٌ',correct:true},
      {text:'الصلةُ إنّها واجبة',correct:false},
      {text:'إنّ الصلةُ واجبةٌ',correct:false},
      {text:'إنّ الصلةِ واجبة',correct:false},
    ],
    explanation:'عند دخول (إنّ) على الجملة الاسمية يُنصَب المبتدأ: الصلةُ ← الصلةَ.',
    goldenRule:'(إنّ) تدخل على الجملة الاسمية فتنصب المبتدأ: إنَّ الصلةَ واجبةٌ.',
    feedbackQuestion:{question:'عند دخول (إنّ) ماذا يحدث للمبتدأ؟',options:[{text:'يُنصَب',correct:true},{text:'يُرفَع',correct:false},{text:'يُجَرّ',correct:false},{text:'لا يتغير',correct:false}]},
  },
];

// ──────── الوحدة الأولى / الدرس الثاني: عذراً يا جدي ──────────────────
const u1l2Qs = [
  {
    id:'u1l2q1', unit:'u1', lesson:'u1l2', page:36, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'في حصة القراءة صحب المعلّم التلاميذ إلى المكتبة. كيف جلس فوّاز في المكتبة؟',
    paragraph:'في حصة القراءة، صحب المعلّم التلاميذ إلى مكتبة المدرسة للقراءة والاطلاع. رأى المعلّم فوّازاً يجلس حزيناً. (ص36)',
    options:[
      {text:'حزيناً',correct:true},
      {text:'فرحاً',correct:false},
      {text:'نائماً',correct:false},
      {text:'مشغولاً بالقراءة',correct:false},
    ],
    explanation:'رأى المعلم فوّازاً يجلس حزيناً في المكتبة فسأله عن سبب حزنه.',
    goldenRule:'الحزن الناتج عن الخطأ يدفعنا للاعتذار وإصلاح ما أسأنا فيه.',
    feedbackQuestion:{question:'ماذا فعل المعلم حين رأى فوّازاً حزيناً؟',options:[{text:'سأله عن سبب حزنه',correct:true},{text:'تجاهله',correct:false},{text:'أخرجه من المكتبة',correct:false},{text:'أرسله إلى المدير',correct:false}]},
  },
  {
    id:'u1l2q2', unit:'u1', lesson:'u1l2', page:36, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'أخطأ فوّاز في حق جده لأنه لم يخفض صوت التلفاز عندما طلب منه ذلك.',
    paragraph:'فوّاز: لقد طلب منّي جدّي أن أخفض صوت التلفاز فلم أفعل؛ لانشغالي بمتابعة برنامجي المفضّل، فغضب منّي. (ص36-37)',
    correctAnswer:true,
    explanation:'فوّاز كان منشغلاً ببرنامجه المفضّل فلم يُنفّذ طلب جده بخفض صوت التلفاز فغضب منه جده.',
    goldenRule:'طاعة الجد واجبة — لا يجوز الانشغال عن طلباته لأي سبب.',
    feedbackQuestion:{question:'ما السبب الذي جعل فوّاز لا يُنفّذ طلب جده؟',options:[{text:'انشغاله بمتابعة برنامجه المفضّل',correct:true},{text:'النوم',correct:false},{text:'خروجه من البيت',correct:false},{text:'عدم سماعه لطلب جده',correct:false}]},
  },
  {
    id:'u1l2q3', unit:'u1', lesson:'u1l2', page:37, type:'multipleChoice',
    bloom:'analyze', difficulty:'medium',
    question:'نصح المعلّم فوّازاً بشيء. ما نصيحة المعلّم؟',
    paragraph:'المعلّم: لقد أخطأت يا فوّاز، وعليك أن تعتذر إلى جدّك، وتطلب السماح منه. (ص37)',
    options:[
      {text:'أن يعتذر لجده ويطلب السماح منه',correct:true},
      {text:'أن ينسى الأمر ويكمل حياته',correct:false},
      {text:'أن يخبر أباه فقط',correct:false},
      {text:'أن يبتعد عن جده مدة',correct:false},
    ],
    explanation:'المعلم نصح فوّاز بالاعتذار لجده وطلب السماح منه لأن ذلك هو الحل الصحيح.',
    goldenRule:'الاعتذار يمحو الخطأ — الشجاع يعترف بخطئه ويطلب السماح.',
    feedbackQuestion:{question:'ماذا قال فوّاز بعد نصيحة المعلم؟',options:[{text:'ليت جدّي يسامحني',correct:true},{text:'لن أعتذر',correct:false},{text:'جدّي لا يغضب',correct:false},{text:'لم يقل شيئاً',correct:false}]},
  },
  {
    id:'u1l2q4', unit:'u1', lesson:'u1l2', page:37, type:'trueFalse',
    bloom:'evaluate', difficulty:'medium',
    question:'الجد عطوفٌ حنون وسيسامح فوّازاً إن شاء الله.',
    paragraph:'المعلم: إنّ الجدّ عطوفٌ حنونٌ، وسيسامحك إن شاء الله، ولكن احرص يا بُنيّ - على طاعة جدّك. (ص37)',
    correctAnswer:true,
    explanation:'المعلم وثق بطيبة الجد وعطفه وأكد أنه سيسامح فوّازاً لأن الأجداد عطوفون حنونون.',
    goldenRule:'إنّ الجدّ عطوفٌ حنونٌ — الأجداد يحبّون أحفادهم ويعفون عن أخطائهم.',
    feedbackQuestion:{question:'ما الصفتان اللتان وصف بهما المعلّم الجدّ؟',options:[{text:'عطوف وحنون',correct:true},{text:'صارم وقاسٍ',correct:false},{text:'غاضب ومتجهم',correct:false},{text:'بعيد وغير مبالٍ',correct:false}]},
  },
  {
    id:'u1l2q5', unit:'u1', lesson:'u1l2', page:38, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'الكلمة الملوّنة في "إنّ الجدّ عطوفٌ حنونٌ" — ما معنى "عطوف"؟',
    paragraph:'اصِلِ الكلمة الملوّنة بمعناها: إنَّ الجدَّ عطوفٌ حنونٌ — المعنى: رحيم. (ص38)',
    options:[
      {text:'رحيم',correct:true},
      {text:'شديد',correct:false},
      {text:'بعيد',correct:false},
      {text:'غاضب',correct:false},
    ],
    explanation:'عطوف تعني رحيم ذو عطف وحنان، وهي صفة من صفات الجد في النص.',
    goldenRule:'عطوف = رحيم = كثير العطف والحنان.',
    feedbackQuestion:{question:'ما ضد كلمة "عطوف"؟',options:[{text:'قاسٍ',correct:true},{text:'طيب',correct:false},{text:'كريم',correct:false},{text:'صبور',correct:false}]},
  },
  {
    id:'u1l2q6', unit:'u1', lesson:'u1l2', page:40, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف الكلمات: تبدأ بحرف شمسي أم قمري بعد (ال)؟',
    paragraph:'أسماء تبدأ بحرف شمسيّ، وأخرى بحرف قمريّ. (ص41)',
    categories:['تبدأ بحرف شمسي ☀️','تبدأ بحرف قمري 🌙'],
    items:[
      {text:'التلفاز',correct_category:0},
      {text:'المعلّم',correct_category:1},
      {text:'الصديق',correct_category:0},
      {text:'الأقارب',correct_category:1},
      {text:'الطالب',correct_category:0},
      {text:'الكتاب',correct_category:1},
    ],
    explanation:'الشمسية (اللام لا تُنطق): التلفاز، الصديق، الطالب. القمرية (اللام تُنطق): المعلم، الأقارب، الكتاب.',
    goldenRule:'حروف شمسية: ت ث د ذ ر ز س ش ص ض ط ظ ل ن. حروف قمرية: باقي الحروف.',
  },
  {
    id:'u1l2q7', unit:'u1', lesson:'u1l2', page:43, type:'multipleChoice',
    bloom:'apply', difficulty:'medium',
    question:'يُؤكّد فوّاز كلامه باستخدام (إنّ) فيقول: "الجدّ عطوفٌ" مؤكَّدة تصبح:',
    paragraph:'يُؤكّد فوّاز كلامه باستخدام (إنّ) محاكياً المثال الأول. (ص43)',
    options:[
      {text:'إنَّ الجدَّ عطوفٌ',correct:true},
      {text:'إنَّ الجدُّ عطوفٌ',correct:false},
      {text:'إنَّ الجدِّ عطوفٌ',correct:false},
      {text:'الجدُّ إنَّه عطوفٌ',correct:false},
    ],
    explanation:'إنّ تدخل على الجملة الاسمية وتنصب المبتدأ: الجدُّ → الجدَّ.',
    goldenRule:'(إنّ) تنصب المبتدأ: الجدُّ ← الجدَّ. تقول: إنَّ الجدَّ عطوفٌ.',
    feedbackQuestion:{question:'"طاعة الجد واجبة" بـ (إنّ) تصبح:',options:[{text:'إنَّ طاعةَ الجد واجبةٌ',correct:true},{text:'إنَّ طاعةُ الجد واجبة',correct:false},{text:'طاعة الجد إنّها واجبة',correct:false},{text:'إنَّ الجدَّ طاعةٌ واجبة',correct:false}]},
  },
  {
    id:'u1l2q8', unit:'u1', lesson:'u1l2', page:44, type:'ordering',
    bloom:'apply', difficulty:'medium',
    question:'رتّب الكلمات لتكوّن جملة مفيدة (ابدأ بالكلمة الملوّنة):',
    paragraph:'رتّب الكلمات: يجلس — فوّاز — حزيناً. (ص44)',
    items:['حزيناً','المكتبة','يجلس','فوّاز','في'],
    correctOrder:[2,3,4,0,1],
    explanation:'الجملة الصحيحة: يجلس فوّاز في المكتبة حزيناً. الفعل يأتي أولاً ثم الفاعل ثم المكان.',
    goldenRule:'ترتيب الجملة الفعلية: فعل + فاعل + متعلقات.',
  },
  {
    id:'u1l2q9', unit:'u1', lesson:'u1l2', page:38, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'ما الدرس الأخلاقي الأساسي المستفاد من قصة "عذراً يا جدي"؟',
    paragraph:'المعلم: لقد أخطأت يا فوّاز، وعليك أن تعتذر إلى جدّك، وتطلب السماح منه. (ص37)',
    options:[
      {text:'الاعتذار عن الخطأ وطاعة الأجداد واجبان',correct:true},
      {text:'مشاهدة التلفاز مباحة دائماً',correct:false},
      {text:'المكتبة أفضل من البيت',correct:false},
      {text:'المعلم لا يجب أن يتدخل في شؤون الطلاب',correct:false},
    ],
    explanation:'النص يعلّم طاعة الأجداد والاعتذار عند الخطأ لأن الأجداد عطوفون حنونون.',
    goldenRule:'طاعة الجد واجبة + الاعتذار عن الخطأ شجاعة = صفات المسلم المؤمن.',
    feedbackQuestion:{question:'كيف نُعبّر عن الاعتذار لشخص أكبر منا؟',options:[{text:'نعتذر بصدق ونطلب السماح',correct:true},{text:'نتجاهل الأمر',correct:false},{text:'ننتظر أن يأتي إلينا',correct:false},{text:'نتظاهر بأننا نسينا',correct:false}]},
  },
  {
    id:'u1l2q10', unit:'u1', lesson:'u1l2', page:40, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'ما الظاهرة الصوتية الموجودة في كلمة "الجدّ"؟',
    paragraph:'لاحِظ وأُلاحِظ: الكلمات الملوّنة بالحرف الملوّن. (ص40)',
    options:[
      {text:'التشديد في الدال',correct:true},
      {text:'التنوين بالفتح',correct:false},
      {text:'المد الطويل',correct:false},
      {text:'السكون على الدال',correct:false},
    ],
    explanation:'كلمة الجدّ تحتوي على تشديد في الدال وهي من الظواهر الصوتية المهمة.',
    goldenRule:'التشديد = حرف مشدّد = صوت الحرف يُلفظ مرتين. علامته: (ّ) فوق الحرف.',
  },
];

// ──────── الوحدة الثانية / الدرس الأول: الصديقان ──────────────────────
const u2l1Qs = [
  {
    id:'u2l1q1', unit:'u2', lesson:'u2l1', page:60, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'نصيد الوحدة الثانية "الجار والصديق" يدور حول موضوع:',
    paragraph:'الوحدة الثانية: أصدقائي وجيراني — نصيد "الجار والصديق". (ص59)',
    options:[
      {text:'حسن التعامل مع الأصدقاء والجيران',correct:true},
      {text:'الدراسة في المدرسة',correct:false},
      {text:'السفر إلى خارج المملكة',correct:false},
      {text:'لعب الرياضة',correct:false},
    ],
    explanation:'الوحدة الثانية تتحدث عن أهمية العلاقات مع الأصدقاء والجيران وحسن التعامل معهم.',
    goldenRule:'الصديق والجار أمانة — حسن التعامل معهم من أخلاق الإسلام.',
    feedbackQuestion:{question:'ما اسم الوحدة الثانية في كتاب لغتي؟',options:[{text:'أصدقائي وجيراني',correct:true},{text:'أقاربي',correct:false},{text:'وطني السعودية',correct:false},{text:'محاصيل من بلادي',correct:false}]},
  },
  {
    id:'u2l1q2', unit:'u2', lesson:'u2l1', page:60, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'يتعرّف الطلاب في مشروع الوحدة الثانية على طلاب من مختلف الدول.',
    paragraph:'بمساندة المعلم والموجه الطلابي أتعرّف على طلاب في المدرسة من مختلف الدول. (ص55)',
    correctAnswer:true,
    explanation:'مشروع الوحدة الثانية يهدف إلى التعرّف على طلاب من دول مختلفة وبناء صداقات متنوّعة.',
    goldenRule:'الصداقة لا تعرف حدوداً — نتعرّف على أصدقاء من مختلف الدول.',
    feedbackQuestion:{question:'ما هدف مشروع الوحدة الثانية؟',options:[{text:'التعرف على طلاب من مختلف الدول',correct:true},{text:'زيارة الأقارب',correct:false},{text:'دراسة الرياضيات',correct:false},{text:'رحلة مدرسية',correct:false}]},
  },
  {
    id:'u2l1q3', unit:'u2', lesson:'u2l1', page:60, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'في نشاط التهيئة للوحدة الثانية يكتب الطالب أسماء أصدقائه وجيرانه. ما الهدف من هذا النشاط؟',
    paragraph:'أكتبُ أسماءَ ثلاثةٍ من أصدقائي، وثلاثةٍ من جيراني. (ص55)',
    options:[
      {text:'التعرّف على مفردات "الأصدقاء والجيران" والتحدث عنهم',correct:true},
      {text:'حفظ أسماء الجيران فقط',correct:false},
      {text:'تعلّم حروف الهجاء',correct:false},
      {text:'كتابة القصص',correct:false},
    ],
    explanation:'نشاط التهيئة يُدخل الطالب في موضوع الوحدة ويجعله يتحدث عن الأصدقاء والجيران.',
    goldenRule:'نشاطات التهيئة تُوطّئ لدراسة الوحدة وتُنشّط المعرفة السابقة.',
    feedbackQuestion:{question:'في نشاط التهيئة كم اسماً يكتب الطالب من أصدقائه؟',options:[{text:'ثلاثة أسماء',correct:true},{text:'خمسة أسماء',correct:false},{text:'اسماً واحداً',correct:false},{text:'عشرة أسماء',correct:false}]},
  },
  {
    id:'u2l1q4', unit:'u2', lesson:'u2l1', page:60, type:'ordering',
    bloom:'apply', difficulty:'medium',
    question:'رتّب هذه الكلمات لتكوّن جملة مفيدة:',
    paragraph:'رتّب الكلمات: أبي — أصدقاء — من — أُتعلّم — مفيدةً — دروساً — وأُمّي. (ص50)',
    items:['دروساً','وأُمّي','أُتعلّم','من أبي','مفيدةً'],
    correctOrder:[2,3,0,4,1],
    explanation:'الجملة: أُتعلّم من أبي دروساً مفيدةً وأُمّي.',
    goldenRule:'الأسرة أول مدرسة — نتعلم من آبائنا وأمهاتنا دروساً قيّمة في الحياة.',
  },
  {
    id:'u2l1q5', unit:'u2', lesson:'u2l1', page:60, type:'multipleChoice',
    bloom:'analyze', difficulty:'medium',
    question:'في نصيد "جدّتي" وردت كلمة "بَهجة". ما معنى بَهجة؟',
    paragraph:'جدّتي رَوضةٌ … في حكاياتها بَهجةٌ وانتفاعٌ. (ص26)',
    options:[
      {text:'سعادة وفرح',correct:true},
      {text:'حزن وكآبة',correct:false},
      {text:'نوم وراحة',correct:false},
      {text:'غضب وانزعاج',correct:false},
    ],
    explanation:'بهجة تعني السعادة والفرح والسرور — والنصيد يصف حكايات الجدة بأنها تجلب الفرح والنفع.',
    goldenRule:'بهجة = سعادة + فرح + سرور. نقول: أبهجني لقاء الأصدقاء.',
    feedbackQuestion:{question:'ما مضاد كلمة "بهجة"؟',options:[{text:'حزن',correct:true},{text:'فرح',correct:false},{text:'نشاط',correct:false},{text:'حيوية',correct:false}]},
  },
  {
    id:'u2l1q6', unit:'u2', lesson:'u2l1', page:60, type:'matching',
    bloom:'remember', difficulty:'medium',
    question:'صِل كلمة في نصيد جدتي بمرادفها:',
    paragraph:'جدّتي جدّتي رَوضةٌ — سرورٌ — بهجةٌ — تأمُّل. (ص26)',
    pairs:[
      {left:'روضة',right:'حديقة جميلة'},
      {left:'سرور',right:'فرح وسعادة'},
      {left:'تأمّل',right:'التفكير والتدبّر'},
      {left:'انتفاع',right:'استفادة ونفع'},
    ],
    explanation:'روضة = حديقة. سرور = فرح. تأمّل = تفكير. انتفاع = استفادة.',
    goldenRule:'فهم المفردات يُعيننا على فهم النصوص — احفظ كل كلمة جديدة.',
  },
  {
    id:'u2l1q7', unit:'u2', lesson:'u2l1', page:60, type:'fillBlank',
    bloom:'remember', difficulty:'easy',
    question:'أكمل أبيات النصيد الناقصة:',
    paragraph:'جدّتي جدّتي ___ — جدّتي ___ الحَنانْ. (ص26)',
    blanks:['حُلوةُ البَسمة','رَوضةٌ من رياض'],
    wordBank:['حُلوةُ البَسمة','رَوضةٌ من رياض','بَهجةٌ وانتفاع','كُلّنا نَلتقي'],
    explanation:'النصيد: جدّتي جدّتي حُلوةُ البَسمة — جدّتي رَوضةٌ من رياض الحَنان.',
    goldenRule:'النصيد يُعبّر عن حب الجدة — قراءته بصوت عالٍ تُرسّخه في الذاكرة.',
  },
  {
    id:'u2l1q8', unit:'u2', lesson:'u2l1', page:60, type:'trueFalse',
    bloom:'apply', difficulty:'medium',
    question:'الاسم "الشمس" يبدأ بحرف شمسي تُدغم فيه لام (ال).',
    paragraph:'اللام في (ال) الشمسية تُكتب ولا تُنطق والحرف الذي بعدها يُكتب مُشدَّداً. (ص30)',
    correctAnswer:true,
    explanation:'الشين حرف شمسي، فعند دخول (ال) على "شمس" تصبح اللام مدغمة في الشين: الشَّمس.',
    goldenRule:'الشين حرف شمسي — تُدغم لام (ال) في حروف: ت ث د ذ ر ز س ش ص ض ط ظ ل ن.',
    feedbackQuestion:{question:'كلمة "الصديق" — ال فيها:',options:[{text:'شمسية',correct:true},{text:'قمرية',correct:false},{text:'ليست ال تعريف',correct:false},{text:'لا يمكن التحديد',correct:false}]},
  },
  {
    id:'u2l1q9', unit:'u2', lesson:'u2l1', page:60, type:'multipleChoice',
    bloom:'understand', difficulty:'easy',
    question:'في التراكيب اللغوية — الجمع المذكر "المعلم" جمعه:',
    paragraph:'يستخدم الطالب الإفراد والجمع. (ص54)',
    options:[
      {text:'المعلّمون / المعلّمين',correct:true},
      {text:'المعلّمات',correct:false},
      {text:'معلّمة',correct:false},
      {text:'معلّمتان',correct:false},
    ],
    explanation:'جمع المذكر السالم يُجمع بإضافة (ون) رفعاً أو (ين) نصباً وجراً: معلّم → معلّمون/معلّمين.',
    goldenRule:'جمع المذكر السالم: معلّم → معلّمون (رفع) / معلّمين (نصب وجر).',
    feedbackQuestion:{question:'جمع كلمة "طالب" هو:',options:[{text:'طالبون / طالبين',correct:true},{text:'طالبات',correct:false},{text:'طلاّب',correct:false},{text:'طالبتان',correct:false}]},
  },
  {
    id:'u2l1q10', unit:'u2', lesson:'u2l1', page:60, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'ما القيمة التي تعلّمتها من الوحدة الثانية "أصدقائي وجيراني"؟',
    paragraph:'يكتسب اتجاهات وقيماً تتعلق بـ: حق الجار والصديق، التواصل مع الآخرين، التسامح وحب الآخرين، المسؤولية والتعاون والمشاركة المجتمعية. (ص54)',
    options:[
      {text:'التسامح والتعاون ومراعاة حق الجار والصديق',correct:true},
      {text:'الفوز في المسابقات الرياضية',correct:false},
      {text:'حفظ القرآن الكريم فقط',correct:false},
      {text:'الاستقلالية وعدم التواصل',correct:false},
    ],
    explanation:'الوحدة الثانية تُرسّخ قيم التسامح والتعاون ومراعاة حق الجار والصديق والتواصل مع الآخرين.',
    goldenRule:'حق الجار مقدّس + الصديق الحقيقي يساعد في الضرّاء والسرّاء.',
    feedbackQuestion:{question:'ما أحد حقوق الجار في الإسلام؟',options:[{text:'مساعدته عند الحاجة',correct:true},{text:'تجاهله دائماً',correct:false},{text:'الإزعاج عليه',correct:false},{text:'عدم التحدث معه',correct:false}]},
  },
];

// ──────── الوحدة الثانية / الدرس الثاني: الجار الصغير ──────────────────
const u2l2Qs = [
  {
    id:'u2l2q1', unit:'u2', lesson:'u2l2', page:71, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'موضوع درس "الجار الصغير" يتحدث عن:',
    paragraph:'الوحدة الثانية — الدرس الثاني: الجار الصغير. (ص71)',
    options:[
      {text:'حسن التعامل مع الجار الصغير والاهتمام به',correct:true},
      {text:'اللعب في الملعب',correct:false},
      {text:'الذهاب إلى المكتبة',correct:false},
      {text:'الرحلة المدرسية',correct:false},
    ],
    explanation:'الدرس الثاني يتحدث عن حسن التعامل مع الجار الصغير والاهتمام بالجيران.',
    goldenRule:'حق الجار واجب سواء كان كبيراً أو صغيراً — أكرم جارك تسعد.',
    feedbackQuestion:{question:'ما الوحدة التي ينتمي إليها درس "الجار الصغير"؟',options:[{text:'الوحدة الثانية: أصدقائي وجيراني',correct:true},{text:'الوحدة الأولى: أقاربي',correct:false},{text:'الوحدة الثالثة: وطني السعودية',correct:false},{text:'الوحدة الرابعة: محاصيل من بلادي',correct:false}]},
  },
  {
    id:'u2l2q2', unit:'u2', lesson:'u2l2', page:72, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'الاسم المفرد "طالب" جمعه "طلاب".',
    paragraph:'يستخدم الطالب الإفراد والجمع. الطالب → طلاب. (ص54)',
    correctAnswer:true,
    explanation:'طالب جمعه طلاب وهو من جموع التكسير التي تغيّرت فيها بنية الكلمة.',
    goldenRule:'جمع تكسير: يتغير وزن الكلمة. مثل: كتاب → كُتب، طالب → طلاب.',
    feedbackQuestion:{question:'جمع "صديق" هو:',options:[{text:'أصدقاء',correct:true},{text:'صديقون',correct:false},{text:'صديقات',correct:false},{text:'صديقتان',correct:false}]},
  },
  {
    id:'u2l2q3', unit:'u2', lesson:'u2l2', page:72, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'في كتاب لغتي يتعلّم الطالب ظاهرة التضعيف. كلمة "الجدّ" فيها تضعيف. ما التضعيف؟',
    paragraph:'التعرف على ظاهرة التضعيف. (ص54)',
    options:[
      {text:'حرف يُكتب ويُنطق مرتين',correct:true},
      {text:'حرف يُكتب ولا يُنطق',correct:false},
      {text:'حرف المد الطويل',correct:false},
      {text:'حرف ساكن في آخر الكلمة',correct:false},
    ],
    explanation:'التضعيف يعني أن الحرف يُكتب مرة واحدة بعلامة التشديد (ّ) ولكن يُنطق مرتين.',
    goldenRule:'التشديد (ّ) = حرف مضعَّف يُنطق مرتين. مثل: جدّ = جَدْدَ، مدّ = مَدْدَ.',
    feedbackQuestion:{question:'أيّ هذه الكلمات فيها تضعيف؟',options:[{text:'الجدّ',correct:true},{text:'الأقارب',correct:false},{text:'الكتاب',correct:false},{text:'المدرسة',correct:false}]},
  },
  {
    id:'u2l2q4', unit:'u2', lesson:'u2l2', page:73, type:'matching',
    bloom:'apply', difficulty:'medium',
    question:'صِل الاسم بصيغة الجمع الصحيحة:',
    paragraph:'استخدام الإفراد والجمع. (ص54)',
    pairs:[
      {left:'صديق (مفرد)',right:'أصدقاء (جمع)'},
      {left:'جار (مفرد)',right:'جيران (جمع)'},
      {left:'معلّم (مفرد)',right:'معلّمون (جمع)'},
      {left:'طالب (مفرد)',right:'طلاب (جمع)'},
    ],
    explanation:'صديق → أصدقاء. جار → جيران. معلّم → معلّمون. طالب → طلاب.',
    goldenRule:'الجمع في العربية أنواع: مذكر سالم + مؤنث سالم + تكسير — لكل اسم جمعه الخاص.',
  },
  {
    id:'u2l2q5', unit:'u2', lesson:'u2l2', page:74, type:'trueFalse',
    bloom:'analyze', difficulty:'medium',
    question:'السؤال بـ (كيف) يُستخدم للسؤال عن الحال والوصف.',
    paragraph:'يستخدم أسلوب الاستفهام بـ (مَن، ماذا، أين، متى، كيف، لماذا، كم). (ص54)',
    correctAnswer:true,
    explanation:'كيف سؤال عن الحال والوصف، مثال: كيف حالك؟ كيف جلس فوّاز في المكتبة؟',
    goldenRule:'أدوات الاستفهام: مَن (عن الأشخاص) + أين (عن المكان) + كيف (عن الحال) + متى (عن الزمان).',
    feedbackQuestion:{question:'ما أداة الاستفهام المناسبة للسؤال عن المكان؟',options:[{text:'أين',correct:true},{text:'كيف',correct:false},{text:'متى',correct:false},{text:'لماذا',correct:false}]},
  },
  {
    id:'u2l2q6', unit:'u2', lesson:'u2l2', page:75, type:'fillBlank',
    bloom:'apply', difficulty:'medium',
    question:'أكمل الجملة بالفعل المناسب للمؤنث:',
    paragraph:'أُحاكي النموذج الأول بكتابة أفعال مناسبة للاسم الذي يأتي بعده. (ص44)',
    blanks:['تجلس','تستمع'],
    wordBank:['تجلس','تستمع','يجلس','يستمع'],
    explanation:'نورة مؤنث فنقول: نورة تجلس حزينةً. نورة تستمع إلى نصح جدّتها.',
    goldenRule:'الفعل للمؤنث يبدأ بـ (تـ): نورة تجلس — نورة تستمع — الجدّة تحكي.',
  },
  {
    id:'u2l2q7', unit:'u2', lesson:'u2l2', page:76, type:'multipleChoice',
    bloom:'apply', difficulty:'medium',
    question:'في الكتابة الإملائية — (ال) الشمسية في "الصديقان" — اللام فيها:',
    paragraph:'اللام في (ال) الشمسية تُكتب ولا تُنطق، والحرف الذي بعدها يُكتب مُشدَّداً. (ص30)',
    options:[
      {text:'تُكتب ولا تُنطق — والصاد تُشدَّد',correct:true},
      {text:'تُكتب وتُنطق — والصاد ساكنة',correct:false},
      {text:'لا تُكتب ولا تُنطق',correct:false},
      {text:'تُنطق مرتين',correct:false},
    ],
    explanation:'الصاد حرف شمسي فعند دخول (ال) على صديقان تصبح اللام صامتة والصاد مشددة: الصَّديقان.',
    goldenRule:'ال الشمسية: اكتبها وأسكت لامها وشدِّد الحرف التالي.',
    feedbackQuestion:{question:'كيف تُقرأ كلمة "الشمس"؟',options:[{text:'اَلشَّمس (اللام لا تُنطق)',correct:true},{text:'اَلْشَمس (اللام تُنطق)',correct:false},{text:'اَلْشَمسُ (اللام مع السكون)',correct:false},{text:'شَمس بدون ال',correct:false}]},
  },
  {
    id:'u2l2q8', unit:'u2', lesson:'u2l2', page:77, type:'classify',
    bloom:'analyze', difficulty:'hard',
    question:'صنّف الكلمات بحسب نوع التنوين:',
    paragraph:'استخرج من النص: كلمة مُنوَّنة تنوين فتح، كلمة مُنوَّنة تنوين ضم، كلمة مُنوَّنة تنوين كسر. (ص41)',
    categories:['تنوين ضم (ٌ)','تنوين فتح (ً)','تنوين كسر (ٍ)'],
    items:[
      {text:'حزيناً',correct_category:1},
      {text:'عطوفٌ',correct_category:0},
      {text:'جارٍ',correct_category:2},
      {text:'بهجةٌ',correct_category:0},
      {text:'رحيمٍ',correct_category:2},
      {text:'صادقاً',correct_category:1},
    ],
    explanation:'تنوين ضم (ٌ): عطوف، بهجة. تنوين فتح (ً): حزيناً، صادقاً. تنوين كسر (ٍ): جار، رحيم.',
    goldenRule:'التنوين ثلاثة أنواع: ضم (ٌ) + فتح (ً) + كسر (ٍ). الاسم المنوَّن نكرة.',
  },
  {
    id:'u2l2q9', unit:'u2', lesson:'u2l2', page:78, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'ما الواجب المنزلي المطلوب في درس "الجار الصغير"؟',
    paragraph:'الواجب المنزلي: أكتب خمس صفات تجعلني محبوباً من أسرتي وأقاربي. (ص46)',
    options:[
      {text:'كتابة خمس صفات تجعلني محبوباً من أسرتي وأقاربي',correct:true},
      {text:'رسم صورة للجار',correct:false},
      {text:'حفظ قصيدة كاملة',correct:false},
      {text:'كتابة ألف حرف',correct:false},
    ],
    explanation:'الواجب المنزلي يُعزّز القيم الإيجابية كالاحترام والطاعة والتعاون التي تجعل الطالب محبوباً.',
    goldenRule:'الصفات الحسنة تجعلنا محبوبين: الاحترام + الطاعة + الأمانة + التعاون + الصدق.',
    feedbackQuestion:{question:'ما صفة حسنة تجعلك محبوباً في أسرتك؟',options:[{text:'احترام الكبير',correct:true},{text:'التشاجر مع الإخوة',correct:false},{text:'رفض المساعدة',correct:false},{text:'الكذب',correct:false}]},
  },
  {
    id:'u2l2q10', unit:'u2', lesson:'u2l2', page:80, type:'multipleChoice',
    bloom:'create', difficulty:'hard',
    question:'عند تأليف جملة مفيدة من الكلمات: "أقاربَنا — نشاركُ — نتفقَّدُ — أحوالَهم — و" — الجملة الصحيحة هي:',
    paragraph:'رتّب الكلمات في كل مجموعة لتكوّن جملة مفيدة: أقاربَنا — نشاركُ — نتفقَّدُ — أحوالَهم — و. (ص50)',
    options:[
      {text:'أقاربَنا نشاركُ أحوالَهم ونتفقَّدُ',correct:false},
      {text:'نتفقَّدُ أقاربَنا أحوالَهم ونشاركُ',correct:true},
      {text:'أحوالَهم أقاربَنا نتفقَّدُ ونشاركُ',correct:false},
      {text:'ونشاركُ نتفقَّدُ أحوالَهم أقاربَنا',correct:false},
    ],
    explanation:'الجملة الصحيحة: نتفقَّدُ أقاربَنا أحوالَهم ونشاركُ (= نتفقّد أحوال أقاربنا ونشاركهم).',
    goldenRule:'ترتيب الجملة = فعل + فاعل مستتر + مفعول به. وَصل الجمل بـ (و) يُكمل المعنى.',
    feedbackQuestion:{question:'ما معنى "نتفقّد أحوال أقاربنا"؟',options:[{text:'نطمئن عليهم ونسأل عنهم',correct:true},{text:'نُراقبهم من بعيد',correct:false},{text:'نُعدّ قائمة بأسمائهم',correct:false},{text:'نزورهم مرة في السنة فقط',correct:false}]},
  },
];

export const ALL_QUESTIONS = [
  ...u1l1Qs, ...u1l2Qs,
  ...u2l1Qs, ...u2l2Qs,
  ...LUGHATI_EXTRA_1,
  ...LUGHATI_EXTRA_2,
  ...LUGHATI_EXTRA_3,
  ...LUGHATI_EXTRA_4,
];