// بنك رياضيات الصف الأول الابتدائي — الفصل الدراسي الثاني
// المصدر: كتاب وزارة التعليم (طبعة 1444-2022) — الفصول 7-13
// الفصول المستكملة: 10 (القياس)، 11 (أنماط الأعداد)
// البنية: كل درس: 8 أنواع (mc, tf, fill, compute, match, classify, order, word) × 2 سؤال

export const MATH1_S2_CHAPTERS = [
  {
    id: 'ch10',
    title_ar: 'الفصل العاشر: القياس',
    title_en: 'Chapter 10: Measurement',
    color: '#0891b2',
    lessons: [
      {
        id: 'ch10-l1',
        title_ar: 'مقارنة الأطوال وترتيبها',
        title_en: 'Comparing and Ordering Lengths',
        questions: LESSON_CH10_L1(),
      },
      {
        id: 'ch10-l2',
        title_ar: 'وحدات الطول غير القياسية',
        title_en: 'Nonstandard Units of Length',
        questions: LESSON_CH10_L2(),
      },
      {
        id: 'ch10-l3',
        title_ar: 'أحل المسألة: أخمن ثم أتحقق',
        title_en: 'Problem Solving: Estimate and Check',
        questions: LESSON_CH10_L3(),
      },
      {
        id: 'ch10-l4',
        title_ar: 'مقارنة الكتل وترتيبها',
        title_en: 'Comparing and Ordering Masses',
        questions: LESSON_CH10_L4(),
      },
      {
        id: 'ch10-l5',
        title_ar: 'مقارنة السعات وترتيبها',
        title_en: 'Comparing and Ordering Capacities',
        questions: LESSON_CH10_L5(),
      },
    ],
  },
  {
    id: 'ch11',
    title_ar: 'الفصل الحادي عشر: أنماط الأعداد',
    title_en: 'Chapter 11: Number Patterns',
    color: '#7c3aed',
    lessons: [
      {
        id: 'ch11-l1',
        title_ar: 'العد بالعشرات',
        title_en: 'Count by Tens',
        questions: LESSON_CH11_L1(),
      },
    ],
  },
  {
    id: 'ch12',
    title_ar: 'الفصل الثاني عشر: الأشكال الهندسية والكسور',
    title_en: 'Chapter 12: Geometry and Fractions',
    color: '#059669',
    lessons: [
      {
        id: 'ch12-l1',
        title_ar: 'الأشكال الهندسية الثلاثية الأبعاد',
        title_en: '3D Shapes',
        questions: LESSON_CH12_L1(),
      },
      {
        id: 'ch12-l2',
        title_ar: 'الكسور (النصف والربع)',
        title_en: 'Fractions (Half and Quarter)',
        questions: LESSON_CH12_L2(),
      },
    ],
  },
  {
    id: 'ch13',
    title_ar: 'الفصل الثالث عشر: النقود',
    title_en: 'Chapter 13: Money',
    color: '#d97706',
    lessons: [
      {
        id: 'ch13-l1',
        title_ar: 'النقود السعودية',
        title_en: 'Saudi Money',
        questions: LESSON_CH13_L1(),
      },
      {
        id: 'ch13-l2',
        title_ar: 'جمع النقود',
        title_en: 'Adding Money',
        questions: LESSON_CH13_L2(),
      },
    ],
  },
];

// ===== الفصل العاشر — الدرس الأول: مقارنة الأطوال وترتيبها =====
function LESSON_CH10_L1() {
  return [
    // 1) اختيار من متعدد
    {
      type: 'mc',
      q_ar: 'القلم الأطول هو الذي يكون:',
      q_en: 'The longest pencil is the one that:',
      options_ar: ['يمتد أكثر من نقطة البداية إلى نقطة النهاية', 'يمتد أقل', 'له نفس الطول', 'أصغر حجمًا'],
      options_en: ['extends more from start to end', 'extends less', 'has the same length', 'is smaller'],
      correct: '0',
      explanation_ar: 'الأطول هو الذي يمتد مسافةً أكبر بين نقطتي القياس.',
      explanation_en: 'The longest extends more between the two measurement points.',
    },
    {
      type: 'mc',
      q_ar: 'إذا رتّبنا ثلاثة أشياء من الأطول إلى الأقصر، يكون الأقصر في:',
      q_en: 'When ordering 3 objects from longest to shortest, the shortest is:',
      options_ar: ['المرتبة الثالثة', 'المرتبة الأولى', 'المرتبة الثانية', 'لا يوجد ترتيب'],
      options_en: ['third place', 'first place', 'second place', 'no order'],
      correct: '0',
      explanation_ar: 'عند الترتيب من الأطول: الأول أطول، والثالث أقصر.',
      explanation_en: 'When ordering longest first: third is shortest.',
    },
    // 2) صح أم خطأ
    {
      type: 'tf',
      q_ar: 'يمكننا مقارنة الأطوال بالنظر المباشر دون قياس.',
      q_en: 'We can compare lengths by looking directly without measuring.',
      options_ar: ['صح', 'خطأ'],
      options_en: ['True', 'False'],
      correct: '0',
      explanation_ar: 'نعم، نضع الأشياء جنبًا إلى جنب لمقارنة أطوالها.',
      explanation_en: 'Yes, we place objects side by side to compare lengths.',
    },
    {
      type: 'tf',
      q_ar: 'الشيء الذي نضع له الرقم ١ في الترتيب من الأطول هو الأقصر.',
      q_en: 'The object ranked 1 (longest to shortest) is the shortest.',
      options_ar: ['صح', 'خطأ'],
      options_en: ['True', 'False'],
      correct: '1',
      explanation_ar: 'خطأ: الرقم ١ يُعطى للأطول عند الترتيب من الأطول.',
      explanation_en: 'False: rank 1 goes to the longest when ordering longest first.',
    },
    // 3) أكمل الفراغ
    {
      type: 'fill',
      q_ar: 'عند ترتيب ثلاثة أقلام من الأطول إلى الأقصر نكتب الأرقام __ و __ و __.',
      q_en: 'When ordering 3 pencils longest to shortest we write __, __, __.',
      answer_ar: '١، ٢، ٣',
      answer_en: '1, 2, 3',
      explanation_ar: 'الأطول يأخذ ١ والأوسط ٢ والأقصر ٣.',
      explanation_en: 'Longest gets 1, middle 2, shortest 3.',
    },
    {
      type: 'fill',
      q_ar: 'الشيء الأطول من بين ثلاثة يأخذ الرقم __.',
      q_en: 'The longest of three objects gets rank __.',
      answer_ar: '١',
      answer_en: '1',
      explanation_ar: 'في الترتيب من الأطول يأخذ الأطول الرقم ١.',
      explanation_en: 'The longest gets rank 1.',
    },
    // 4) أوجد الناتج
    {
      type: 'compute',
      q_ar: 'قلم أحمر طوله ٨ وحدات، وقلم أزرق طوله ٥ وحدات. بكم وحدة الأحمر أطول؟',
      q_en: 'Red pencil is 8 units, blue is 5 units. By how many units is red longer?',
      answer_ar: '٣ وحدات',
      answer_en: '3 units',
      explanation_ar: '٨ − ٥ = ٣.',
      explanation_en: '8 − 5 = 3.',
    },
    {
      type: 'compute',
      q_ar: 'قضيب طوله ١٠ وحدات وآخر طوله ٦ وحدات. بكم وحدة الأول أطول؟',
      q_en: 'A rod is 10 units, another is 6 units. How many units longer is the first?',
      answer_ar: '٤ وحدات',
      answer_en: '4 units',
      explanation_ar: '١٠ − ٦ = ٤.',
      explanation_en: '10 − 6 = 4.',
    },
    // 5) وصل
    {
      type: 'match',
      q_ar: 'صل كل طول بترتيبه (من الأقصر إلى الأطول).',
      q_en: 'Match each length to its order (shortest to longest).',
      pairs_ar: [
        { left: '٣ وحدات', right: 'الأول (الأقصر)' },
        { left: '٦ وحدات', right: 'الثاني' },
        { left: '٩ وحدات', right: 'الثالث (الأطول)' },
      ],
      pairs_en: [
        { left: '3 units', right: '1st (shortest)' },
        { left: '6 units', right: '2nd' },
        { left: '9 units', right: '3rd (longest)' },
      ],
      explanation_ar: 'الأقصر يأتي أولًا ثم الأطول.',
      explanation_en: 'Shortest first, longest last.',
    },
    {
      type: 'match',
      q_ar: 'صل كل كلمة بمعناها في القياس.',
      q_en: 'Match each word to its meaning in measurement.',
      pairs_ar: [
        { left: 'الأطول', right: 'يمتد أكثر' },
        { left: 'الأقصر', right: 'يمتد أقل' },
        { left: 'متساويان', right: 'نفس الطول' },
      ],
      pairs_en: [
        { left: 'longest', right: 'extends more' },
        { left: 'shortest', right: 'extends less' },
        { left: 'equal', right: 'same length' },
      ],
      explanation_ar: 'مصطلحات المقارنة في القياس.',
      explanation_en: 'Comparison terms in measurement.',
    },
    // 6) صنّف
    {
      type: 'classify',
      q_ar: 'صنّف: طويل / قصير (مقارنةً بـ٥ وحدات).',
      q_en: 'Sort: long / short (compared to 5 units).',
      categories_ar: ['أطول من ٥', 'أقصر من ٥'],
      categories_en: ['longer than 5', 'shorter than 5'],
      items_ar: [
        { item: '٣ وحدات', correct_category: 1 },
        { item: '٧ وحدات', correct_category: 0 },
        { item: '٢ وحدات', correct_category: 1 },
        { item: '٨ وحدات', correct_category: 0 },
      ],
      items_en: [
        { item: '3 units', correct_category: 1 },
        { item: '7 units', correct_category: 0 },
        { item: '2 units', correct_category: 1 },
        { item: '8 units', correct_category: 0 },
      ],
      explanation_ar: 'قارن كل طول بالـ٥ وحدات.',
      explanation_en: 'Compare each length to 5 units.',
    },
    {
      type: 'classify',
      q_ar: 'صنّف: أطول من القلم / أقصر من القلم (القلم = ٦ وحدات).',
      q_en: 'Sort: longer / shorter than pencil (pencil = 6 units).',
      categories_ar: ['أطول من القلم', 'أقصر من القلم'],
      categories_en: ['longer than pencil', 'shorter than pencil'],
      items_ar: [
        { item: 'مسطرة ١٠ وحدات', correct_category: 0 },
        { item: 'ممحاة ٢ وحدات', correct_category: 1 },
        { item: 'قلم ملون ٨ وحدات', correct_category: 0 },
        { item: 'وتد ١ وحدة', correct_category: 1 },
      ],
      items_en: [
        { item: 'ruler 10 units', correct_category: 0 },
        { item: 'eraser 2 units', correct_category: 1 },
        { item: 'crayon 8 units', correct_category: 0 },
        { item: 'peg 1 unit', correct_category: 1 },
      ],
      explanation_ar: 'قارن بالقلم (٦ وحدات).',
      explanation_en: 'Compare to pencil (6 units).',
    },
    // 7) رتّب
    {
      type: 'order',
      q_ar: 'رتّب من الأطول إلى الأقصر.',
      q_en: 'Order from longest to shortest.',
      order_ar: ['١٢ وحدة', '٨ وحدات', '٤ وحدات', '١ وحدة'],
      order_en: ['12 units', '8 units', '4 units', '1 unit'],
      explanation_ar: '١٢ > ٨ > ٤ > ١.',
      explanation_en: '12 > 8 > 4 > 1.',
    },
    {
      type: 'order',
      q_ar: 'رتّب من الأقصر إلى الأطول.',
      q_en: 'Order from shortest to longest.',
      order_ar: ['٢ وحدات', '٥ وحدات', '٩ وحدات', '١١ وحدة'],
      order_en: ['2 units', '5 units', '9 units', '11 units'],
      explanation_ar: '٢ < ٥ < ٩ < ١١.',
      explanation_en: '2 < 5 < 9 < 11.',
    },
    // 8) مسألة حياتية
    {
      type: 'word',
      q_ar: 'لدى سارة قلم طوله ٩ وحدات، وقلم آخر طوله ٥ وحدات، وقلم ثالث طوله ٧ وحدات. رتّبيها من الأطول إلى الأقصر.',
      q_en: 'Sara has pencils of lengths 9, 5, and 7 units. Order them longest to shortest.',
      answer_ar: '٩، ٧، ٥',
      answer_en: '9, 7, 5',
      explanation_ar: '٩ > ٧ > ٥.',
      explanation_en: '9 > 7 > 5.',
    },
    {
      type: 'word',
      q_ar: 'قضيب أخضر طوله ٤، وأحمر طوله ٦، وأزرق طوله ٢. رتّبها من الأقصر إلى الأطول.',
      q_en: 'Green rod: 4, red: 6, blue: 2. Order shortest to longest.',
      answer_ar: '٢، ٤، ٦',
      answer_en: '2, 4, 6',
      explanation_ar: '٢ < ٤ < ٦.',
      explanation_en: '2 < 4 < 6.',
    },
  ];
}

// ===== الفصل العاشر — الدرس الثاني: وحدات الطول غير القياسية =====
function LESSON_CH10_L2() {
  return [
    {
      type: 'mc',
      q_ar: 'وحدة القياس غير القياسية هي:',
      q_en: 'A nonstandard unit of measurement is:',
      options_ar: ['أي شيء نستعمله وحدةً للقياس كالمكعبات', 'المتر فقط', 'السم فقط', 'الكيلومتر'],
      options_en: ['anything used as a unit like cubes', 'meter only', 'cm only', 'kilometer'],
      correct: '0',
      explanation_ar: 'وحدات القياس غير القياسية هي أي أشياء نستعملها للقياس مثل المكعبات أو الأصابع أو المشابك.',
      explanation_en: 'Nonstandard units are any objects used for measuring like cubes or fingers.',
    },
    {
      type: 'mc',
      q_ar: 'قِست طول القلم بالمكعبات فكان حوالي ٧ مكعبات. إذا كان المكعب أكبر فسيكون عدد المكعبات:',
      q_en: 'A pencil measures about 7 cubes. If the cube is bigger, the number of cubes will:',
      options_ar: ['أقل', 'أكثر', 'نفسه', 'لا فرق'],
      options_en: ['less', 'more', 'same', 'no difference'],
      correct: '0',
      explanation_ar: 'كلما كانت وحدة القياس أكبر، قلّ العدد المطلوب للقياس.',
      explanation_en: 'Larger units mean fewer are needed to measure.',
    },
    {
      type: 'tf',
      q_ar: 'يمكن استعمال مشابك الورق لقياس الطول.',
      q_en: 'Paper clips can be used to measure length.',
      options_ar: ['صح', 'خطأ'],
      options_en: ['True', 'False'],
      correct: '0',
      explanation_ar: 'نعم، مشابك الورق مثال على وحدة قياس غير قياسية.',
      explanation_en: 'Yes, paper clips are an example of nonstandard units.',
    },
    {
      type: 'tf',
      q_ar: 'وحدات القياس غير القياسية تعطي نفس القياس بالضبط لكل شخص.',
      q_en: 'Nonstandard units give exactly the same measurement for everyone.',
      options_ar: ['صح', 'خطأ'],
      options_en: ['True', 'False'],
      correct: '1',
      explanation_ar: 'خطأ: نتائج القياس بوحدات غير قياسية قد تختلف من شخص لآخر.',
      explanation_en: 'False: nonstandard measurements may vary between people.',
    },
    {
      type: 'fill',
      q_ar: 'قِست طول كتاب بالمكعبات فكان حوالي __ مكعبًا (الإجابة المتوقعة للدرس).',
      q_en: 'I measured a book with cubes and got about __ cubes.',
      answer_ar: 'إجابة تقديرية',
      answer_en: 'estimated answer',
      explanation_ar: 'نضع المكعبات بجانب الكتاب ونعدها.',
      explanation_en: 'Place cubes next to the book and count.',
    },
    {
      type: 'fill',
      q_ar: 'لقياس الطول بالمكعبات أضعها __ المكعبات بجانب الشيء وأعدها.',
      q_en: 'To measure length with cubes, I place them __ the object and count.',
      answer_ar: 'بجانب / على طول',
      answer_en: 'beside / along',
      explanation_ar: 'نرتب المكعبات على طول الجسم دون فجوات.',
      explanation_en: 'Line up cubes along the object with no gaps.',
    },
    {
      type: 'compute',
      q_ar: 'طول مسطرة يساوي ١٢ مكعبًا. طول القلم يساوي ٨ مكعبات. بكم مكعب المسطرة أطول؟',
      q_en: 'Ruler = 12 cubes, pencil = 8 cubes. How many cubes longer is the ruler?',
      answer_ar: '٤ مكعبات',
      answer_en: '4 cubes',
      explanation_ar: '١٢ − ٨ = ٤.',
      explanation_en: '12 − 8 = 4.',
    },
    {
      type: 'compute',
      q_ar: 'طول الممحاة ٣ مكعبات وطول القلم ٩ مكعبات. بكم مكعب القلم أطول؟',
      q_en: 'Eraser = 3 cubes, pencil = 9 cubes. By how many cubes is the pencil longer?',
      answer_ar: '٦ مكعبات',
      answer_en: '6 cubes',
      explanation_ar: '٩ − ٣ = ٦.',
      explanation_en: '9 − 3 = 6.',
    },
    {
      type: 'match',
      q_ar: 'صل كل شيء بتقدير طوله بالمكعبات.',
      q_en: 'Match each object to its approximate length in cubes.',
      pairs_ar: [
        { left: 'ممحاة صغيرة', right: '٣ مكعبات' },
        { left: 'قلم متوسط', right: '٧ مكعبات' },
        { left: 'مسطرة طويلة', right: '١٢ مكعبًا' },
      ],
      pairs_en: [
        { left: 'small eraser', right: '3 cubes' },
        { left: 'medium pencil', right: '7 cubes' },
        { left: 'long ruler', right: '12 cubes' },
      ],
      explanation_ar: 'الأشياء الأصغر تحتاج مكعبات أقل.',
      explanation_en: 'Smaller objects need fewer cubes.',
    },
    {
      type: 'match',
      q_ar: 'صل كل وحدة قياس بنوعها.',
      q_en: 'Match each unit to its type.',
      pairs_ar: [
        { left: 'مكعب', right: 'وحدة غير قياسية' },
        { left: 'مشبك الورق', right: 'وحدة غير قياسية' },
        { left: 'سنتيمتر', right: 'وحدة قياسية' },
      ],
      pairs_en: [
        { left: 'cube', right: 'nonstandard' },
        { left: 'paper clip', right: 'nonstandard' },
        { left: 'centimeter', right: 'standard' },
      ],
      explanation_ar: 'الوحدات القياسية مقبولة عالميًا.',
      explanation_en: 'Standard units are internationally accepted.',
    },
    {
      type: 'classify',
      q_ar: 'صنّف: وحدة قياسية / غير قياسية.',
      q_en: 'Sort: standard / nonstandard.',
      categories_ar: ['قياسية', 'غير قياسية'],
      categories_en: ['standard', 'nonstandard'],
      items_ar: [
        { item: 'سنتيمتر', correct_category: 0 },
        { item: 'مشبك ورق', correct_category: 1 },
        { item: 'متر', correct_category: 0 },
        { item: 'مكعب', correct_category: 1 },
      ],
      items_en: [
        { item: 'centimeter', correct_category: 0 },
        { item: 'paper clip', correct_category: 1 },
        { item: 'meter', correct_category: 0 },
        { item: 'cube', correct_category: 1 },
      ],
      explanation_ar: 'الوحدات القياسية مثل السم والمتر محددة عالميًا.',
      explanation_en: 'Standard units like cm and m are universally defined.',
    },
    {
      type: 'classify',
      q_ar: 'صنّف: أطول من ٥ مكعبات / أقصر من ٥ مكعبات.',
      q_en: 'Sort: longer than 5 cubes / shorter than 5 cubes.',
      categories_ar: ['أطول من ٥ مكعبات', 'أقصر من ٥ مكعبات'],
      categories_en: ['longer than 5', 'shorter than 5'],
      items_ar: [
        { item: '٣ مكعبات', correct_category: 1 },
        { item: '٨ مكعبات', correct_category: 0 },
        { item: '١ مكعب', correct_category: 1 },
        { item: '٧ مكعبات', correct_category: 0 },
      ],
      items_en: [
        { item: '3 cubes', correct_category: 1 },
        { item: '8 cubes', correct_category: 0 },
        { item: '1 cube', correct_category: 1 },
        { item: '7 cubes', correct_category: 0 },
      ],
      explanation_ar: 'قارن بالـ٥ مكعبات.',
      explanation_en: 'Compare to 5 cubes.',
    },
    {
      type: 'order',
      q_ar: 'رتّب من الأقصر إلى الأطول (بالمكعبات).',
      q_en: 'Order from shortest to longest (in cubes).',
      order_ar: ['٢ مكعبان', '٥ مكعبات', '٨ مكعبات', '١١ مكعبًا'],
      order_en: ['2 cubes', '5 cubes', '8 cubes', '11 cubes'],
      explanation_ar: '٢ < ٥ < ٨ < ١١.',
      explanation_en: '2 < 5 < 8 < 11.',
    },
    {
      type: 'order',
      q_ar: 'رتّب من الأطول إلى الأقصر.',
      q_en: 'Order from longest to shortest.',
      order_ar: ['١٠ مكعبات', '٧ مكعبات', '٤ مكعبات', '١ مكعب'],
      order_en: ['10 cubes', '7 cubes', '4 cubes', '1 cube'],
      explanation_ar: '١٠ > ٧ > ٤ > ١.',
      explanation_en: '10 > 7 > 4 > 1.',
    },
    {
      type: 'word',
      q_ar: 'قاس عمر طول قلمه فكان ٦ مكعبات. وطول ممحاته ٢ مكعبين. ما فرق الطول بينهما؟',
      q_en: 'Omar measured his pencil as 6 cubes and eraser as 2 cubes. What is the difference?',
      answer_ar: '٤ مكعبات',
      answer_en: '4 cubes',
      explanation_ar: '٦ − ٢ = ٤.',
      explanation_en: '6 − 2 = 4.',
    },
    {
      type: 'word',
      q_ar: 'قاست فاطمة طول كتابين: الأول ١٢ مكعبًا والثاني ٩ مكعبات. بكم مكعب الأول أطول؟',
      q_en: 'Fatima measured two books: first = 12 cubes, second = 9 cubes. How many longer is the first?',
      answer_ar: '٣ مكعبات',
      answer_en: '3 cubes',
      explanation_ar: '١٢ − ٩ = ٣.',
      explanation_en: '12 − 9 = 3.',
    },
  ];
}

// ===== الفصل العاشر — الدرس الثالث: أحل المسألة: أخمن ثم أتحقق =====
function LESSON_CH10_L3() {
  return [
    {
      type: 'mc',
      q_ar: 'الخطوة الأولى في حل مسألة التخمين ثم التحقق هي:',
      q_en: 'The first step in "estimate then check" is:',
      options_ar: ['أفهم المسألة', 'أحسب الجواب', 'أتحقق', 'أكتب العمليات'],
      options_en: ['understand the problem', 'calculate', 'check', 'write operations'],
      correct: '0',
      explanation_ar: 'نبدأ بفهم المطلوب (أفهم) ثم نخطط ثم نحل ثم نتحقق.',
      explanation_en: 'We start by understanding (comprehend), then plan, solve, then check.',
    },
    {
      type: 'mc',
      q_ar: 'خيار طوله ٧ مكعبات. إذا خمّنت أن طوله ٥ مكعبات هل إجابتك معقولة؟',
      q_en: 'A cucumber is 7 cubes. If you estimate 5 cubes, is your answer reasonable?',
      options_ar: ['لا، الخمين بعيد', 'نعم، معقول', 'لا علاقة', 'لا يمكن الحكم'],
      options_en: ['no, estimate is far', 'yes, reasonable', 'no relation', 'cannot decide'],
      correct: '0',
      explanation_ar: 'الخمين ٥ يبعد ٢ عن ٧. يُفضَّل تخمين أقرب.',
      explanation_en: 'Estimate 5 is 2 away from 7. Closer estimate is better.',
    },
    {
      type: 'tf',
      q_ar: 'في حل مسألة التخمين نُقدّر أولًا ثم نُجري القياس الفعلي للتحقق.',
      q_en: 'In estimate-then-check, we guess first then actually measure to verify.',
      options_ar: ['صح', 'خطأ'],
      options_en: ['True', 'False'],
      correct: '0',
      explanation_ar: 'نعم: التخمين ثم التحقق هو جوهر هذا الدرس.',
      explanation_en: 'Yes: guess then check is the core of this lesson.',
    },
    {
      type: 'tf',
      q_ar: 'إذا كانت الجزرة طولها ٦ مكعبات وخمّنت ١٠ مكعبات فإجابتك معقولة.',
      q_en: 'If a carrot is 6 cubes and you estimated 10, your answer is reasonable.',
      options_ar: ['صح', 'خطأ'],
      options_en: ['True', 'False'],
      correct: '1',
      explanation_ar: 'خطأ: الفرق ٤ مكعبات كبير نسبيًا لشيء صغير.',
      explanation_en: 'False: the difference of 4 cubes is relatively large.',
    },
    {
      type: 'fill',
      q_ar: 'في مسألة التخمين نتحقق من الإجابة بـ __ الطول فعليًا.',
      q_en: 'In estimate-and-check, we verify by actually __ the length.',
      answer_ar: 'قياس',
      answer_en: 'measuring',
      explanation_ar: 'نقيس فعليًا بعد التخمين لنعرف مدى دقته.',
      explanation_en: 'We measure actually after estimating to check accuracy.',
    },
    {
      type: 'fill',
      q_ar: 'خيار طوله ٧ مكعبات. إذا خمّنت ٦ فإجابتك __ (معقولة/بعيدة).',
      q_en: 'Cucumber = 7 cubes. Estimate = 6. Your answer is __ (reasonable/far).',
      answer_ar: 'معقولة',
      answer_en: 'reasonable',
      explanation_ar: 'فرق مكعب واحد فقط يُعدّ تخمينًا جيدًا.',
      explanation_en: 'One cube difference is a good estimate.',
    },
    {
      type: 'compute',
      q_ar: 'خمّنت أن طول الذرة ٨ مكعبات. قِست فعليًا فكانت ١٠ مكعبات. ما مقدار الفرق؟',
      q_en: 'You estimated corn = 8 cubes. Measured = 10 cubes. What is the difference?',
      answer_ar: '٢ مكعبان',
      answer_en: '2 cubes',
      explanation_ar: '١٠ − ٨ = ٢.',
      explanation_en: '10 − 8 = 2.',
    },
    {
      type: 'compute',
      q_ar: 'خمّنت أن طول الخيار ٥ مكعبات. قِست فعليًا فكانت ٨ مكعبات. ما مقدار الفرق؟',
      q_en: 'Estimated cucumber = 5 cubes. Measured = 8. What is the difference?',
      answer_ar: '٣ مكعبات',
      answer_en: '3 cubes',
      explanation_ar: '٨ − ٥ = ٣.',
      explanation_en: '8 − 5 = 3.',
    },
    {
      type: 'match',
      q_ar: 'صل كل خطوة بمعناها في حل المسألة.',
      q_en: 'Match each step to its meaning.',
      pairs_ar: [
        { left: 'أفهم', right: 'ما المطلوب من المسألة؟' },
        { left: 'أخطط', right: 'كيف سأحل المسألة؟' },
        { left: 'أتحقق', right: 'هل إجابتي معقولة؟' },
      ],
      pairs_en: [
        { left: 'Understand', right: 'What is the problem asking?' },
        { left: 'Plan', right: 'How will I solve it?' },
        { left: 'Check', right: 'Is my answer reasonable?' },
      ],
      explanation_ar: 'خطوات حل المسألة: أفهم، أخطط، أحل، أتحقق.',
      explanation_en: 'Problem-solving steps: understand, plan, solve, check.',
    },
    {
      type: 'match',
      q_ar: 'صل كل تخمين بمدى معقوليته.',
      q_en: 'Match each estimate to its reasonableness.',
      pairs_ar: [
        { left: 'طول فعلي ٧، تخمين ٦', right: 'معقول' },
        { left: 'طول فعلي ٧، تخمين ١٥', right: 'بعيد' },
        { left: 'طول فعلي ١٠، تخمين ١٠', right: 'دقيق' },
      ],
      pairs_en: [
        { left: 'actual 7, estimate 6', right: 'reasonable' },
        { left: 'actual 7, estimate 15', right: 'far off' },
        { left: 'actual 10, estimate 10', right: 'exact' },
      ],
      explanation_ar: 'التخمين الجيد قريب من القياس الفعلي.',
      explanation_en: 'A good estimate is close to the actual measurement.',
    },
    {
      type: 'classify',
      q_ar: 'صنّف التخمينات: معقول / بعيد (الطول الفعلي = ٦ مكعبات).',
      q_en: 'Sort estimates: reasonable / far off (actual = 6 cubes).',
      categories_ar: ['معقول', 'بعيد'],
      categories_en: ['reasonable', 'far off'],
      items_ar: [
        { item: 'تخمين ٥', correct_category: 0 },
        { item: 'تخمين ١٠', correct_category: 1 },
        { item: 'تخمين ٧', correct_category: 0 },
        { item: 'تخمين ١', correct_category: 1 },
      ],
      items_en: [
        { item: 'estimate 5', correct_category: 0 },
        { item: 'estimate 10', correct_category: 1 },
        { item: 'estimate 7', correct_category: 0 },
        { item: 'estimate 1', correct_category: 1 },
      ],
      explanation_ar: 'التخمين المعقول يبعد مكعبًا أو مكعبين عن الحقيقي.',
      explanation_en: 'Reasonable = 1-2 cubes away from actual.',
    },
    {
      type: 'classify',
      q_ar: 'صنّف: تخمين أكبر من الفعلي / أصغر من الفعلي (الفعلي = ٨ مكعبات).',
      q_en: 'Sort: overestimate / underestimate (actual = 8 cubes).',
      categories_ar: ['تخمين أكبر', 'تخمين أصغر'],
      categories_en: ['overestimate', 'underestimate'],
      items_ar: [
        { item: 'تخمين ١٠', correct_category: 0 },
        { item: 'تخمين ٥', correct_category: 1 },
        { item: 'تخمين ١٢', correct_category: 0 },
        { item: 'تخمين ٣', correct_category: 1 },
      ],
      items_en: [
        { item: 'estimate 10', correct_category: 0 },
        { item: 'estimate 5', correct_category: 1 },
        { item: 'estimate 12', correct_category: 0 },
        { item: 'estimate 3', correct_category: 1 },
      ],
      explanation_ar: 'إذا كان التخمين أكبر من الفعلي فهو مبالغ فيه.',
      explanation_en: 'If estimate > actual it is an overestimate.',
    },
    {
      type: 'order',
      q_ar: 'رتّب التخمينات من الأقرب إلى الأبعد (الفعلي ٧ مكعبات).',
      q_en: 'Order estimates closest to farthest (actual = 7 cubes).',
      order_ar: ['تخمين ٦', 'تخمين ٨', 'تخمين ١٠', 'تخمين ١٤'],
      order_en: ['estimate 6', 'estimate 8', 'estimate 10', 'estimate 14'],
      explanation_ar: 'الفرق: |٦−٧|=١، |٨−٧|=١، |١٠−٧|=٣، |١٤−٧|=٧.',
      explanation_en: 'Differences: |6-7|=1, |8-7|=1, |10-7|=3, |14-7|=7.',
    },
    {
      type: 'order',
      q_ar: 'رتّب خطوات حل المسألة بالترتيب الصحيح.',
      q_en: 'Order the problem-solving steps correctly.',
      order_ar: ['أفهم المسألة', 'أخطط للحل', 'أحل المسألة', 'أتحقق من الإجابة'],
      order_en: ['understand', 'plan', 'solve', 'check'],
      explanation_ar: 'الترتيب: أفهم → أخطط → أحل → أتحقق.',
      explanation_en: 'Order: understand → plan → solve → check.',
    },
    {
      type: 'word',
      q_ar: 'خمّن فهد أن طول حذائه ١٥ مشبكًا. قاس فعليًا فكان ١٢ مشبكًا. هل التخمين معقول؟',
      q_en: 'Fahd estimated his shoe = 15 clips. Measured = 12 clips. Is the estimate reasonable?',
      answer_ar: 'نعم، معقول (الفرق ٣ مشابك فقط)',
      answer_en: 'Yes, reasonable (difference = 3 clips only)',
      explanation_ar: 'فرق ٣ مشابك مقبول في التخمين.',
      explanation_en: 'A 3-clip difference is acceptable in estimation.',
    },
    {
      type: 'word',
      q_ar: 'خمّنت نورة أن طول كتابها ٢٠ مشبكًا. قاست فعليًا فكان ٦ مشابك. هل التخمين معقول؟',
      q_en: 'Noura estimated her book = 20 clips. Measured = 6 clips. Reasonable?',
      answer_ar: 'لا، التخمين بعيد جدًا (الفرق ١٤ مشبكًا)',
      answer_en: 'No, very far off (difference = 14 clips)',
      explanation_ar: 'فرق ١٤ مشبكًا كبير جدًا.',
      explanation_en: 'A 14-clip difference is too large.',
    },
  ];
}

// ===== الفصل العاشر — الدرس الرابع: مقارنة الكتل وترتيبها =====
function LESSON_CH10_L4() {
  return [
    {
      type: 'mc',
      q_ar: 'الكتلة هي:',
      q_en: 'Mass refers to:',
      options_ar: ['مقدار ما يحتويه الشيء من مادة (ثقل)', 'طول الشيء', 'لون الشيء', 'شكل الشيء'],
      options_en: ['amount of matter in an object (weight)', 'length of object', 'color', 'shape'],
      correct: '0',
      explanation_ar: 'الكتلة هي مقدار المادة في الشيء، وتُقاس بمفاهيم ثقيل وخفيف.',
      explanation_en: 'Mass is the amount of matter; described as heavy or light.',
    },
    {
      type: 'mc',
      q_ar: 'كتاب الرياضيات مقارنةً بقلم الرصاص هو:',
      q_en: 'Compared to a pencil, a math textbook is:',
      options_ar: ['أثقل', 'أخف', 'متساويان', 'لا يمكن المقارنة'],
      options_en: ['heavier', 'lighter', 'equal', 'incomparable'],
      correct: '0',
      explanation_ar: 'الكتاب أثقل من القلم بكثير.',
      explanation_en: 'The book is much heavier than the pencil.',
    },
    {
      type: 'tf',
      q_ar: 'الشيء الأثقل يكون رقمه ١ عند الترتيب من الأخف إلى الأثقل.',
      q_en: 'The heaviest object gets rank 1 when ordering lightest to heaviest.',
      options_ar: ['صح', 'خطأ'],
      options_en: ['True', 'False'],
      correct: '1',
      explanation_ar: 'خطأ: عند الترتيب من الأخف يأخذ الأخف رقم ١ والأثقل الرقم الأكبر.',
      explanation_en: 'False: lightest gets rank 1 when ordering light to heavy.',
    },
    {
      type: 'tf',
      q_ar: 'الريشة أخف من الحقيبة المدرسية.',
      q_en: 'A feather is lighter than a school bag.',
      options_ar: ['صح', 'خطأ'],
      options_en: ['True', 'False'],
      correct: '0',
      explanation_ar: 'نعم، الريشة أخف بكثير من الحقيبة.',
      explanation_en: 'Yes, a feather is much lighter.',
    },
    {
      type: 'fill',
      q_ar: 'عند ترتيب الأشياء من الأخف إلى الأثقل، يأخذ الأخف الرقم __.',
      q_en: 'Ordering lightest to heaviest, the lightest gets rank __.',
      answer_ar: '١',
      answer_en: '1',
      explanation_ar: 'الترتيب من الأخف: ١ للأخف.',
      explanation_en: 'Ordering lightest first: 1 for lightest.',
    },
    {
      type: 'fill',
      q_ar: 'الشيء الأثقل من بين ثلاثة يأخذ الرقم __.',
      q_en: 'The heaviest of three objects gets rank __.',
      answer_ar: '٣',
      answer_en: '3',
      explanation_ar: 'عند الترتيب من الأخف يكون الأثقل في المرتبة الثالثة.',
      explanation_en: 'When ordering lightest first, heaviest is third.',
    },
    {
      type: 'compute',
      q_ar: 'لديك مقص وساعة ومجموعة كتب. رتّبها من الأخف إلى الأثقل.',
      q_en: 'You have scissors, a watch, and a pile of books. Order lightest to heaviest.',
      answer_ar: 'ساعة، مقص، كتب',
      answer_en: 'watch, scissors, books',
      explanation_ar: 'الساعة الأخف، ثم المقص، ثم الكتب الأثقل.',
      explanation_en: 'Watch lightest, then scissors, then books heaviest.',
    },
    {
      type: 'compute',
      q_ar: 'قارن: طاولة مقارنةً بقلم. أيهما أثقل؟',
      q_en: 'Compare: table vs pencil. Which is heavier?',
      answer_ar: 'الطاولة',
      answer_en: 'the table',
      explanation_ar: 'الطاولة أثقل من القلم بكثير.',
      explanation_en: 'The table is much heavier.',
    },
    {
      type: 'match',
      q_ar: 'صل كل شيء بوصفه.',
      q_en: 'Match each object to its description.',
      pairs_ar: [
        { left: 'ريشة', right: 'خفيف جدًا' },
        { left: 'طاولة', right: 'ثقيل جدًا' },
        { left: 'كتاب', right: 'ثقيل نسبيًا' },
      ],
      pairs_en: [
        { left: 'feather', right: 'very light' },
        { left: 'table', right: 'very heavy' },
        { left: 'book', right: 'relatively heavy' },
      ],
      explanation_ar: 'الكتلة نسبية: نقارن الأشياء ببعضها.',
      explanation_en: 'Mass is relative: compare objects to each other.',
    },
    {
      type: 'match',
      q_ar: 'صل كل زوج بالوصف الصحيح.',
      q_en: 'Match each pair to the correct description.',
      pairs_ar: [
        { left: 'كتاب ومقص', right: 'الكتاب أثقل' },
        { left: 'ريشة وحقيبة', right: 'الحقيبة أثقل' },
        { left: 'قلم وقلم', right: 'متساويان' },
      ],
      pairs_en: [
        { left: 'book and scissors', right: 'book heavier' },
        { left: 'feather and bag', right: 'bag heavier' },
        { left: 'pencil and pencil', right: 'equal' },
      ],
      explanation_ar: 'استعمل الحواس والتجربة لمقارنة الكتل.',
      explanation_en: 'Use senses and experience to compare masses.',
    },
    {
      type: 'classify',
      q_ar: 'صنّف: ثقيل / خفيف.',
      q_en: 'Sort: heavy / light.',
      categories_ar: ['ثقيل', 'خفيف'],
      categories_en: ['heavy', 'light'],
      items_ar: [
        { item: 'حقيبة مدرسية', correct_category: 0 },
        { item: 'ورقة', correct_category: 1 },
        { item: 'مكتب', correct_category: 0 },
        { item: 'قلم رصاص', correct_category: 1 },
      ],
      items_en: [
        { item: 'school bag', correct_category: 0 },
        { item: 'paper sheet', correct_category: 1 },
        { item: 'desk', correct_category: 0 },
        { item: 'pencil', correct_category: 1 },
      ],
      explanation_ar: 'الأشياء الكبيرة المصنوعة من مواد صلبة عادةً ثقيلة.',
      explanation_en: 'Large solid objects are usually heavier.',
    },
    {
      type: 'classify',
      q_ar: 'صنّف: أثقل من الكتاب / أخف من الكتاب.',
      q_en: 'Sort: heavier than book / lighter than book.',
      categories_ar: ['أثقل من الكتاب', 'أخف من الكتاب'],
      categories_en: ['heavier than book', 'lighter than book'],
      items_ar: [
        { item: 'طاولة', correct_category: 0 },
        { item: 'ريشة', correct_category: 1 },
        { item: 'حقيبة كتب', correct_category: 0 },
        { item: 'مشبك ورق', correct_category: 1 },
      ],
      items_en: [
        { item: 'table', correct_category: 0 },
        { item: 'feather', correct_category: 1 },
        { item: 'book bag', correct_category: 0 },
        { item: 'paper clip', correct_category: 1 },
      ],
      explanation_ar: 'قارن بالكتاب.',
      explanation_en: 'Compare to the book.',
    },
    {
      type: 'order',
      q_ar: 'رتّب من الأخف إلى الأثقل.',
      q_en: 'Order from lightest to heaviest.',
      order_ar: ['ريشة', 'قلم', 'كتاب', 'طاولة'],
      order_en: ['feather', 'pencil', 'book', 'table'],
      explanation_ar: 'الريشة أخف الجميع والطاولة أثقلها.',
      explanation_en: 'Feather is lightest, table is heaviest.',
    },
    {
      type: 'order',
      q_ar: 'رتّب من الأثقل إلى الأخف.',
      q_en: 'Order from heaviest to lightest.',
      order_ar: ['مكتب', 'حقيبة', 'كتاب', 'مشبك ورق'],
      order_en: ['desk', 'bag', 'book', 'paper clip'],
      explanation_ar: 'المكتب أثقل، مشبك الورق أخف.',
      explanation_en: 'Desk is heaviest, paper clip is lightest.',
    },
    {
      type: 'word',
      q_ar: 'أحضرت ثلاثة أشياء: مقص وساعة ومجموعة كتب. الكتب أثقل من المقص، والمقص أثقل من الساعة. رتّبها من الأخف إلى الأثقل.',
      q_en: 'Three objects: scissors, watch, books. Books > scissors > watch. Order lightest to heaviest.',
      answer_ar: 'ساعة، مقص، كتب',
      answer_en: 'watch, scissors, books',
      explanation_ar: 'الساعة أخف، ثم المقص، ثم الكتب الأثقل.',
      explanation_en: 'Watch lightest, then scissors, books heaviest.',
    },
    {
      type: 'word',
      q_ar: 'قلم الرصاص أخف من المسطرة. المسطرة أخف من الكتاب. ما الأثقل من الثلاثة؟',
      q_en: 'Pencil < ruler < book in weight. Which is heaviest?',
      answer_ar: 'الكتاب',
      answer_en: 'the book',
      explanation_ar: 'الكتاب أثقل من المسطرة والقلم.',
      explanation_en: 'Book is heavier than both ruler and pencil.',
    },
  ];
}

// ===== الفصل العاشر — الدرس الخامس: مقارنة السعات وترتيبها =====
function LESSON_CH10_L5() {
  return [
    {
      type: 'mc',
      q_ar: 'السعة هي:',
      q_en: 'Capacity is:',
      options_ar: ['مقدار ما يسعه الوعاء من سائل', 'طول الوعاء', 'وزن الوعاء', 'شكل الوعاء'],
      options_en: ['how much a container holds', 'length of container', 'weight', 'shape'],
      correct: '0',
      explanation_ar: 'السعة هي مقدار ما يمكن للوعاء أن يحتويه من سائل.',
      explanation_en: 'Capacity is how much liquid a container can hold.',
    },
    {
      type: 'mc',
      q_ar: 'الكأس __ من الإبريق من حيث السعة.',
      q_en: 'A cup has __ capacity than a teapot.',
      options_ar: ['أقل سعةً', 'أكبر سعةً', 'نفس السعة', 'لا علاقة'],
      options_en: ['less', 'greater', 'same', 'no relation'],
      correct: '0',
      explanation_ar: 'الإبريق يسع أكثر من الكأس.',
      explanation_en: 'The teapot holds more than the cup.',
    },
    {
      type: 'tf',
      q_ar: 'الوعاء الأكبر حجمًا دائمًا له سعة أكبر.',
      q_en: 'A bigger container always has greater capacity.',
      options_ar: ['صح', 'خطأ'],
      options_en: ['True', 'False'],
      correct: '0',
      explanation_ar: 'عمومًا صحيح: الحجم الأكبر = سعة أكبر.',
      explanation_en: 'Generally true: larger size = greater capacity.',
    },
    {
      type: 'tf',
      q_ar: 'وعاء سعته أكبر يمتلئ بكمية أقل من الماء.',
      q_en: 'A container with greater capacity fills with less water.',
      options_ar: ['صح', 'خطأ'],
      options_en: ['True', 'False'],
      correct: '1',
      explanation_ar: 'خطأ: السعة الأكبر تعني استيعاب ماء أكثر.',
      explanation_en: 'False: greater capacity holds more water.',
    },
    {
      type: 'fill',
      q_ar: 'الوعاء الذي يسع __ من السائل له سعة أكبر.',
      q_en: 'The container holding __ liquid has greater capacity.',
      answer_ar: 'أكثر',
      answer_en: 'more',
      explanation_ar: 'السعة الأكبر = كمية سائل أكثر.',
      explanation_en: 'Greater capacity = more liquid.',
    },
    {
      type: 'fill',
      q_ar: 'عند ترتيب ثلاثة أوعية من الأقل إلى الأكثر سعةً، يأخذ الأقل سعةً الرقم __.',
      q_en: 'Ordering 3 containers least to greatest capacity, the smallest gets rank __.',
      answer_ar: '١',
      answer_en: '1',
      explanation_ar: 'الأقل سعةً يأخذ الرقم ١.',
      explanation_en: 'Least capacity gets rank 1.',
    },
    {
      type: 'compute',
      q_ar: 'أي الأوعية الثلاثة أكبر سعةً: كأس أو إبريق أو قدر طبخ؟',
      q_en: 'Which of the three has greatest capacity: cup, teapot, or cooking pot?',
      answer_ar: 'قدر الطبخ',
      answer_en: 'the cooking pot',
      explanation_ar: 'قدر الطبخ أكبر من الإبريق والكأس.',
      explanation_en: 'The cooking pot is biggest of the three.',
    },
    {
      type: 'compute',
      q_ar: 'كأس سعتها أقل من إبريق الشاي. إبريق الشاي سعته أقل من قدر. ما أكبر السعات الثلاث؟',
      q_en: 'Cup < teapot < pot. Which has greatest capacity?',
      answer_ar: 'القدر',
      answer_en: 'the pot',
      explanation_ar: 'القدر أكبر الثلاثة سعةً.',
      explanation_en: 'The pot has the greatest capacity.',
    },
    {
      type: 'match',
      q_ar: 'صل كل وعاء بسعته التقريبية.',
      q_en: 'Match each container to its approximate capacity.',
      pairs_ar: [
        { left: 'كأس صغير', right: 'سعة أقل' },
        { left: 'إبريق', right: 'سعة متوسطة' },
        { left: 'حوض كبير', right: 'سعة أكبر' },
      ],
      pairs_en: [
        { left: 'small cup', right: 'least capacity' },
        { left: 'teapot', right: 'medium capacity' },
        { left: 'large basin', right: 'greatest capacity' },
      ],
      explanation_ar: 'الحجم يحدد السعة التقريبية.',
      explanation_en: 'Size determines approximate capacity.',
    },
    {
      type: 'match',
      q_ar: 'صل كل زوج بالوصف الصحيح.',
      q_en: 'Match each pair to the correct description.',
      pairs_ar: [
        { left: 'كأس وحوض', right: 'الحوض أكبر سعةً' },
        { left: 'إبريق وكأس', right: 'الإبريق أكبر سعةً' },
        { left: 'كأسان متماثلان', right: 'نفس السعة' },
      ],
      pairs_en: [
        { left: 'cup and basin', right: 'basin has greater capacity' },
        { left: 'teapot and cup', right: 'teapot has greater capacity' },
        { left: 'two identical cups', right: 'same capacity' },
      ],
      explanation_ar: 'قارن سعة كل وعاء.',
      explanation_en: 'Compare the capacity of each container.',
    },
    {
      type: 'classify',
      q_ar: 'صنّف: سعة كبيرة / سعة صغيرة.',
      q_en: 'Sort: large capacity / small capacity.',
      categories_ar: ['سعة كبيرة', 'سعة صغيرة'],
      categories_en: ['large capacity', 'small capacity'],
      items_ar: [
        { item: 'حوض استحمام', correct_category: 0 },
        { item: 'ملعقة', correct_category: 1 },
        { item: 'قدر طبخ', correct_category: 0 },
        { item: 'كأس ماء', correct_category: 1 },
      ],
      items_en: [
        { item: 'bathtub', correct_category: 0 },
        { item: 'spoon', correct_category: 1 },
        { item: 'cooking pot', correct_category: 0 },
        { item: 'water glass', correct_category: 1 },
      ],
      explanation_ar: 'الأواني الكبيرة لها سعة أكبر.',
      explanation_en: 'Larger containers have greater capacity.',
    },
    {
      type: 'classify',
      q_ar: 'صنّف: أكبر سعةً من الإبريق / أصغر سعةً من الإبريق.',
      q_en: 'Sort: greater capacity than teapot / less than teapot.',
      categories_ar: ['أكبر سعةً من الإبريق', 'أصغر سعةً من الإبريق'],
      categories_en: ['greater than teapot', 'less than teapot'],
      items_ar: [
        { item: 'قدر كبير', correct_category: 0 },
        { item: 'كأس صغير', correct_category: 1 },
        { item: 'حوض سمك', correct_category: 0 },
        { item: 'ملعقة', correct_category: 1 },
      ],
      items_en: [
        { item: 'large pot', correct_category: 0 },
        { item: 'small cup', correct_category: 1 },
        { item: 'fish tank', correct_category: 0 },
        { item: 'spoon', correct_category: 1 },
      ],
      explanation_ar: 'قارن بالإبريق.',
      explanation_en: 'Compare to the teapot.',
    },
    {
      type: 'order',
      q_ar: 'رتّب من الأقل إلى الأكثر سعةً.',
      q_en: 'Order from least to greatest capacity.',
      order_ar: ['ملعقة', 'كأس', 'إبريق', 'قدر'],
      order_en: ['spoon', 'cup', 'teapot', 'pot'],
      explanation_ar: 'الملعقة أقل سعةً والقدر أكثرها.',
      explanation_en: 'Spoon least, pot greatest capacity.',
    },
    {
      type: 'order',
      q_ar: 'رتّب من الأكثر إلى الأقل سعةً.',
      q_en: 'Order from greatest to least capacity.',
      order_ar: ['حوض استحمام', 'قدر', 'إبريق', 'كأس'],
      order_en: ['bathtub', 'pot', 'teapot', 'cup'],
      explanation_ar: 'الحوض أكبر سعةً والكأس أقلها.',
      explanation_en: 'Bathtub greatest, cup least.',
    },
    {
      type: 'word',
      q_ar: 'مع عادل وعاءان للسوائل. إذا كانت سعة الإبريق ٦ كؤوس وسعة الوعاء الكبير ١٢ كأسًا فما الأكبر سعةً؟',
      q_en: 'Adel has two containers. Teapot = 6 cups, large container = 12 cups. Which is bigger?',
      answer_ar: 'الوعاء الكبير (١٢ كأسًا)',
      answer_en: 'the large container (12 cups)',
      explanation_ar: '١٢ > ٦ فالوعاء الكبير أكبر سعةً.',
      explanation_en: '12 > 6 so the large container has more capacity.',
    },
    {
      type: 'word',
      q_ar: 'رسمت سلمى ثلاثة أوعية. كأس فيه ١ كأس ماء، وإبريق فيه ٤ كؤوس، وقدر فيه ٨ كؤوس. رتّبيها من الأقل إلى الأكثر سعةً.',
      q_en: 'Three containers: cup holds 1 cup, teapot holds 4, pot holds 8. Order least to greatest.',
      answer_ar: 'كأس، إبريق، قدر',
      answer_en: 'cup, teapot, pot',
      explanation_ar: '١ < ٤ < ٨.',
      explanation_en: '1 < 4 < 8.',
    },
  ];
}

// ===== الفصل الحادي عشر — الدرس الأول: العد بالعشرات =====
function LESSON_CH11_L1() {
  return [
    {
      type: 'mc',
      q_ar: '٣ عشرات تساوي:',
      q_en: '3 tens equals:',
      options_ar: ['٣٠', '٣', '١٣', '٣٠٠'],
      options_en: ['30', '3', '13', '300'],
      correct: '0',
      explanation_ar: '٣ × ١٠ = ٣٠.',
      explanation_en: '3 × 10 = 30.',
    },
    {
      type: 'mc',
      q_ar: 'العدد ٧٠ يحتوي على كم عشرة؟',
      q_en: 'How many tens are in 70?',
      options_ar: ['٧', '٧٠', '١٧', '٠'],
      options_en: ['7', '70', '17', '0'],
      correct: '0',
      explanation_ar: '٧٠ = ٧ × ١٠ = ٧ عشرات.',
      explanation_en: '70 = 7 × 10 = 7 tens.',
    },
    {
      type: 'tf',
      q_ar: '٤ عشرات = ٤٠.',
      q_en: '4 tens = 40.',
      options_ar: ['صح', 'خطأ'],
      options_en: ['True', 'False'],
      correct: '0',
      explanation_ar: '٤ × ١٠ = ٤٠.',
      explanation_en: '4 × 10 = 40.',
    },
    {
      type: 'tf',
      q_ar: 'العدد ٦٠ يحتوي على ٨ عشرات.',
      q_en: '60 contains 8 tens.',
      options_ar: ['صح', 'خطأ'],
      options_en: ['True', 'False'],
      correct: '1',
      explanation_ar: 'خطأ: ٦٠ = ٦ عشرات.',
      explanation_en: 'False: 60 = 6 tens.',
    },
    {
      type: 'fill',
      q_ar: '٥ عشرات = __.',
      q_en: '5 tens = __.',
      answer_ar: '٥٠',
      answer_en: '50',
      explanation_ar: '٥ × ١٠ = ٥٠.',
      explanation_en: '5 × 10 = 50.',
    },
    {
      type: 'fill',
      q_ar: '٩٠ = __ عشرات.',
      q_en: '90 = __ tens.',
      answer_ar: '٩',
      answer_en: '9',
      explanation_ar: '٩٠ ÷ ١٠ = ٩.',
      explanation_en: '90 ÷ 10 = 9.',
    },
    {
      type: 'compute',
      q_ar: '٦ × ١٠ = ؟',
      q_en: '6 × 10 = ?',
      answer_ar: '٦٠',
      answer_en: '60',
      explanation_ar: '٦ عشرات = ٦٠.',
      explanation_en: '6 tens = 60.',
    },
    {
      type: 'compute',
      q_ar: '٨٠ ÷ ١٠ = ؟ (كم عشرة في ٨٠؟)',
      q_en: '80 ÷ 10 = ? (how many tens in 80?)',
      answer_ar: '٨',
      answer_en: '8',
      explanation_ar: '٨٠ = ٨ × ١٠.',
      explanation_en: '80 = 8 × 10.',
    },
    {
      type: 'match',
      q_ar: 'صل كل عدد بما يساويه من العشرات.',
      q_en: 'Match each number to its tens.',
      pairs_ar: [
        { left: '٢٠', right: '٢ عشرتان' },
        { left: '٥٠', right: '٥ عشرات' },
        { left: '٩٠', right: '٩ عشرات' },
      ],
      pairs_en: [
        { left: '20', right: '2 tens' },
        { left: '50', right: '5 tens' },
        { left: '90', right: '9 tens' },
      ],
      explanation_ar: 'العدد = عدد العشرات × ١٠.',
      explanation_en: 'Number = tens × 10.',
    },
    {
      type: 'match',
      q_ar: 'صل كل عبارة بعددها.',
      q_en: 'Match each expression to its number.',
      pairs_ar: [
        { left: '٣ عشرات', right: '٣٠' },
        { left: '٧ عشرات', right: '٧٠' },
        { left: '١٠٠ = __ عشرة', right: '١٠' },
      ],
      pairs_en: [
        { left: '3 tens', right: '30' },
        { left: '7 tens', right: '70' },
        { left: '100 = __ tens', right: '10' },
      ],
      explanation_ar: '١٠٠ = ١٠ × ١٠.',
      explanation_en: '100 = 10 × 10.',
    },
    {
      type: 'classify',
      q_ar: 'صنّف: أكثر من ٥ عشرات / أقل من ٥ عشرات.',
      q_en: 'Sort: more than 5 tens / less than 5 tens.',
      categories_ar: ['أكثر من ٥ عشرات', 'أقل من ٥ عشرات'],
      categories_en: ['more than 5 tens', 'less than 5 tens'],
      items_ar: [
        { item: '٣٠', correct_category: 1 },
        { item: '٧٠', correct_category: 0 },
        { item: '٢٠', correct_category: 1 },
        { item: '٨٠', correct_category: 0 },
      ],
      items_en: [
        { item: '30', correct_category: 1 },
        { item: '70', correct_category: 0 },
        { item: '20', correct_category: 1 },
        { item: '80', correct_category: 0 },
      ],
      explanation_ar: '٥ عشرات = ٥٠؛ ما يزيد عنه أكثر.',
      explanation_en: '5 tens = 50; greater than that is more.',
    },
    {
      type: 'classify',
      q_ar: 'صنّف: عشرات زوجية / عشرات فردية.',
      q_en: 'Sort: even tens / odd tens.',
      categories_ar: ['عشرات زوجية (٢٠، ٤٠...)، عشرات فردية (١٠، ٣٠...)'],
      categories_en: ['even tens', 'odd tens'],
      items_ar: [
        { item: '٢٠', correct_category: 0 },
        { item: '٣٠', correct_category: 1 },
        { item: '٤٠', correct_category: 0 },
        { item: '٧٠', correct_category: 1 },
      ],
      items_en: [
        { item: '20', correct_category: 0 },
        { item: '30', correct_category: 1 },
        { item: '40', correct_category: 0 },
        { item: '70', correct_category: 1 },
      ],
      explanation_ar: 'العشرات الزوجية: ٢٠، ٤٠، ٦٠، ٨٠، ١٠٠.',
      explanation_en: 'Even tens: 20, 40, 60, 80, 100.',
    },
    {
      type: 'order',
      q_ar: 'رتّب العشرات تصاعديًا.',
      q_en: 'Order the tens ascending.',
      order_ar: ['١٠', '٣٠', '٥٠', '٧٠'],
      order_en: ['10', '30', '50', '70'],
      explanation_ar: '١٠ < ٣٠ < ٥٠ < ٧٠.',
      explanation_en: '10 < 30 < 50 < 70.',
    },
    {
      type: 'order',
      q_ar: 'رتّب تنازليًا.',
      q_en: 'Order descending.',
      order_ar: ['١٠٠', '٨٠', '٦٠', '٤٠'],
      order_en: ['100', '80', '60', '40'],
      explanation_ar: '١٠٠ > ٨٠ > ٦٠ > ٤٠.',
      explanation_en: '100 > 80 > 60 > 40.',
    },
    {
      type: 'word',
      q_ar: 'مع كل طالب ١٠ أقلام. كم قلمًا مع ٥ طلاب؟',
      q_en: 'Each student has 10 pencils. How many pencils do 5 students have?',
      answer_ar: '٥٠ قلمًا',
      answer_en: '50 pencils',
      explanation_ar: '٥ × ١٠ = ٥٠.',
      explanation_en: '5 × 10 = 50.',
    },
    {
      type: 'word',
      q_ar: 'تريد سارة أن تعد حتى ١٠٠ بالعشرات. كم خطوة ستتخذ؟',
      q_en: 'Sara wants to count to 100 by tens. How many steps will she take?',
      answer_ar: '١٠ خطوات',
      answer_en: '10 steps',
      explanation_ar: '١٠، ٢٠، ٣٠، ... ، ١٠٠ = ١٠ خطوات.',
      explanation_en: '10, 20, 30, ..., 100 = 10 steps.',
    },
  ];
}

// ===== الفصل الثاني عشر — الدرس الأول: الأشكال الهندسية الثلاثية الأبعاد =====
function LESSON_CH12_L1() {
  return [
    { type: 'mc', q_ar: 'الشكل الهندسي الذي له وجوه مستطيلة فقط هو:', q_en: 'The 3D shape with only rectangular faces is:', options_ar: ['المكعب المستطيل', 'الكرة', 'المخروط', 'الأسطوانة'], options_en: ['rectangular prism', 'sphere', 'cone', 'cylinder'], correct: '0', explanation_ar: 'المكعب المستطيل له ٦ وجوه مستطيلة.', explanation_en: 'A rectangular prism has 6 rectangular faces.' },
    { type: 'mc', q_ar: 'الشكل الذي ليس له أي حافة مستقيمة هو:', q_en: 'The shape with no straight edges is:', options_ar: ['الكرة', 'المكعب', 'الهرم', 'المكعب المستطيل'], options_en: ['sphere', 'cube', 'pyramid', 'rectangular prism'], correct: '0', explanation_ar: 'الكرة دائرية تمامًا بلا حواف.', explanation_en: 'A sphere is perfectly round with no edges.' },
    { type: 'tf', q_ar: 'المكعب له ٦ وجوه متساوية.', q_en: 'A cube has 6 equal faces.', options_ar: ['صح', 'خطأ'], options_en: ['True', 'False'], correct: '0', explanation_ar: 'المكعب له ٦ وجوه مربعة متساوية.', explanation_en: 'A cube has 6 equal square faces.' },
    { type: 'tf', q_ar: 'الأسطوانة لها قاعدتان دائريتان.', q_en: 'A cylinder has two circular bases.', options_ar: ['صح', 'خطأ'], options_en: ['True', 'False'], correct: '0', explanation_ar: 'نعم، الأسطوانة لها قاعدتان دائريتان وجانب منحنٍ.', explanation_en: 'Yes, a cylinder has 2 circular bases and a curved side.' },
    { type: 'fill', q_ar: 'الشكل الهندسي الذي يشبه كرة القدم هو __.', q_en: 'The 3D shape that looks like a football is __.', answer_ar: 'الكرة', answer_en: 'sphere', explanation_ar: 'الكرة شكل كروي.', explanation_en: 'A sphere is round like a ball.' },
    { type: 'fill', q_ar: 'الهرم الذي قاعدته مثلث المثلث له __ أوجه.', q_en: 'A triangular pyramid has __ faces.', answer_ar: '٤', answer_en: '4', explanation_ar: 'الهرم المثلثي له ٤ أوجه مثلثية.', explanation_en: 'A triangular pyramid has 4 triangular faces.' },
    { type: 'compute', q_ar: 'كم وجهًا للمكعب؟', q_en: 'How many faces does a cube have?', answer_ar: '٦', answer_en: '6', explanation_ar: 'المكعب له ٦ وجوه مربعة.', explanation_en: 'A cube has 6 square faces.' },
    { type: 'compute', q_ar: 'كم حافةً للمكعب المستطيل؟', q_en: 'How many edges does a rectangular prism have?', answer_ar: '١٢', answer_en: '12', explanation_ar: 'المكعب المستطيل له ١٢ حافة.', explanation_en: 'A rectangular prism has 12 edges.' },
    { type: 'match', q_ar: 'صل كل شكل بوصفه.', q_en: 'Match each shape to its description.', pairs_ar: [{ left: 'كرة', right: 'لا حواف، دائرية' }, { left: 'مكعب', right: '٦ وجوه مربعة' }, { left: 'أسطوانة', right: 'قاعدتان دائريتان' }], pairs_en: [{ left: 'sphere', right: 'no edges, round' }, { left: 'cube', right: '6 square faces' }, { left: 'cylinder', right: '2 circular bases' }], explanation_ar: 'كل شكل له خصائصه المميزة.', explanation_en: 'Each shape has its distinct properties.' },
    { type: 'match', q_ar: 'صل كل شكل بمثاله في الحياة.', q_en: 'Match each shape to a real-life example.', pairs_ar: [{ left: 'مكعب', right: 'مكعب السكر' }, { left: 'أسطوانة', right: 'علبة عصير' }, { left: 'كرة', right: 'كرة قدم' }], pairs_en: [{ left: 'cube', right: 'sugar cube' }, { left: 'cylinder', right: 'juice can' }, { left: 'sphere', right: 'football' }], explanation_ar: 'الأشكال الهندسية موجودة في حياتنا.', explanation_en: '3D shapes exist in our daily life.' },
    { type: 'classify', q_ar: 'صنّف: له وجوه مستوية / له سطح منحنٍ.', q_en: 'Sort: flat faces only / has curved surface.', categories_ar: ['وجوه مستوية فقط', 'سطح منحنٍ'], categories_en: ['flat faces only', 'curved surface'], items_ar: [{ item: 'مكعب', correct_category: 0 }, { item: 'كرة', correct_category: 1 }, { item: 'مكعب مستطيل', correct_category: 0 }, { item: 'أسطوانة', correct_category: 1 }], items_en: [{ item: 'cube', correct_category: 0 }, { item: 'sphere', correct_category: 1 }, { item: 'rectangular prism', correct_category: 0 }, { item: 'cylinder', correct_category: 1 }], explanation_ar: 'الأشكال المنحنية: الكرة والأسطوانة.', explanation_en: 'Curved shapes: sphere and cylinder.' },
    { type: 'classify', q_ar: 'صنّف: يمكن أن يتدحرج / لا يتدحرج.', q_en: 'Sort: can roll / cannot roll.', categories_ar: ['يمكن أن يتدحرج', 'لا يتدحرج'], categories_en: ['can roll', 'cannot roll'], items_ar: [{ item: 'كرة', correct_category: 0 }, { item: 'مكعب', correct_category: 1 }, { item: 'أسطوانة', correct_category: 0 }, { item: 'هرم', correct_category: 1 }], items_en: [{ item: 'sphere', correct_category: 0 }, { item: 'cube', correct_category: 1 }, { item: 'cylinder', correct_category: 0 }, { item: 'pyramid', correct_category: 1 }], explanation_ar: 'الأشكال ذات الأسطح المنحنية تتدحرج.', explanation_en: 'Shapes with curved surfaces can roll.' },
    { type: 'order', q_ar: 'رتّب حسب عدد الوجوه تصاعديًا.', q_en: 'Order by number of faces ascending.', order_ar: ['كرة (٠)', 'مخروط (١)', 'أسطوانة (٢)', 'مكعب (٦)'], order_en: ['sphere (0)', 'cone (1)', 'cylinder (2)', 'cube (6)'], explanation_ar: 'الكرة: ٠ وجه مستوٍ، المخروط: ١، الأسطوانة: ٢، المكعب: ٦.', explanation_en: 'Sphere: 0 flat faces, cone: 1, cylinder: 2, cube: 6.' },
    { type: 'order', q_ar: 'رتّب حسب عدد الحواف تصاعديًا.', q_en: 'Order by number of edges ascending.', order_ar: ['كرة (٠)', 'مخروط (١)', 'مكعب (١٢)', 'مكعب مستطيل (١٢)'], order_en: ['sphere (0)', 'cone (1)', 'cube (12)', 'rectangular prism (12)'], explanation_ar: 'الكرة: ٠ حواف، المخروط: ١، المكعب: ١٢.', explanation_en: 'Sphere: 0 edges, cone: 1, cube: 12.' },
    { type: 'word', q_ar: 'وضعت سارة ٣ أشكال على الطاولة: مكعب وأسطوانة وكرة. أيها لا يمكن أن يتدحرج؟', q_en: 'Sara placed a cube, cylinder, sphere on a table. Which cannot roll?', answer_ar: 'المكعب', answer_en: 'the cube', explanation_ar: 'المكعب له وجوه مستوية فقط فلا يتدحرج.', explanation_en: 'The cube has only flat faces so it cannot roll.' },
    { type: 'word', q_ar: 'احتاج فهد شكلًا له ٦ وجوه متساوية. ما الشكل المناسب؟', q_en: 'Fahd needs a shape with 6 equal faces. Which shape?', answer_ar: 'المكعب', answer_en: 'cube', explanation_ar: 'المكعب له ٦ وجوه مربعة متساوية.', explanation_en: 'A cube has 6 equal square faces.' },
  ];
}

// ===== الفصل الثاني عشر — الدرس الثاني: الكسور (النصف والربع) =====
function LESSON_CH12_L2() {
  return [
    { type: 'mc', q_ar: 'الكسر ½ يعني:', q_en: 'The fraction ½ means:', options_ar: ['جزء واحد من جزأين متساويين', 'جزء من ثلاثة', 'جزءان من أربعة', 'كل الأجزاء'], options_en: ['1 of 2 equal parts', '1 of 3 parts', '2 of 4 parts', 'all parts'], correct: '0', explanation_ar: 'النصف = تقسيم الشيء إلى جزأين متساويين والأخذ بأحدهما.', explanation_en: 'Half = split into 2 equal parts and take 1.' },
    { type: 'mc', q_ar: 'الكسر ¼ يعني:', q_en: 'The fraction ¼ means:', options_ar: ['جزء واحد من أربعة أجزاء متساوية', 'أربعة أجزاء', 'جزءان من اثنين', 'نصف الشيء'], options_en: ['1 of 4 equal parts', '4 parts', '2 of 2', 'half'], correct: '0', explanation_ar: 'الربع = تقسيم إلى ٤ أجزاء متساوية والأخذ بواحد.', explanation_en: 'Quarter = 4 equal parts, take 1.' },
    { type: 'tf', q_ar: 'النصف يعني قسّمنا الشيء إلى جزأين متساويين.', q_en: 'Half means we divided into 2 equal parts.', options_ar: ['صح', 'خطأ'], options_en: ['True', 'False'], correct: '0', explanation_ar: 'نعم، النصف = ٢ جزء متساوٍ.', explanation_en: 'Yes, half = 2 equal parts.' },
    { type: 'tf', q_ar: '½ أكبر من ¼.', q_en: '½ is greater than ¼.', options_ar: ['صح', 'خطأ'], options_en: ['True', 'False'], correct: '0', explanation_ar: 'النصف أكبر من الربع: ½ > ¼.', explanation_en: 'Half is greater than quarter: ½ > ¼.' },
    { type: 'fill', q_ar: 'إذا قسّمت التفاحة إلى ٤ أجزاء متساوية وأخذت جزءًا واحدًا أخذت __ من التفاحة.', q_en: 'Divided apple into 4 equal parts, took 1 = __ of the apple.', answer_ar: '¼ (ربعًا)', answer_en: '¼ (one quarter)', explanation_ar: 'جزء من ٤ = ¼.', explanation_en: '1 of 4 = ¼.' },
    { type: 'fill', q_ar: 'الكسر الذي يمثل نصف الشكل هو __.', q_en: 'The fraction representing half is __.', answer_ar: '½', answer_en: '½', explanation_ar: 'النصف = ½.', explanation_en: 'Half = ½.' },
    { type: 'compute', q_ar: 'كم نصفًا يكوّن الكل الواحد؟', q_en: 'How many halves make a whole?', answer_ar: '٢', answer_en: '2', explanation_ar: 'نصفان = كامل.', explanation_en: '2 halves = 1 whole.' },
    { type: 'compute', q_ar: 'كم ربعًا يكوّن الكل الواحد؟', q_en: 'How many quarters make a whole?', answer_ar: '٤', answer_en: '4', explanation_ar: '٤ أرباع = كامل.', explanation_en: '4 quarters = 1 whole.' },
    { type: 'match', q_ar: 'صل كل كسر بمعناه.', q_en: 'Match each fraction to its meaning.', pairs_ar: [{ left: '½', right: 'جزء من جزأين' }, { left: '¼', right: 'جزء من أربعة' }, { left: '¾', right: 'ثلاثة أجزاء من أربعة' }], pairs_en: [{ left: '½', right: '1 of 2 parts' }, { left: '¼', right: '1 of 4 parts' }, { left: '¾', right: '3 of 4 parts' }], explanation_ar: 'الكسر = عدد الأجزاء المأخوذة ÷ إجمالي الأجزاء.', explanation_en: 'Fraction = parts taken ÷ total parts.' },
    { type: 'match', q_ar: 'صل كل كسر بترتيبه من الأصغر.', q_en: 'Match each fraction to its order (smallest first).', pairs_ar: [{ left: '¼', right: 'الأصغر' }, { left: '½', right: 'الأوسط' }, { left: '¾', right: 'الأكبر' }], pairs_en: [{ left: '¼', right: 'smallest' }, { left: '½', right: 'middle' }, { left: '¾', right: 'largest' }], explanation_ar: '¼ < ½ < ¾.', explanation_en: '¼ < ½ < ¾.' },
    { type: 'classify', q_ar: 'صنّف: أكبر من النصف / أصغر من النصف.', q_en: 'Sort: greater than half / less than half.', categories_ar: ['أكبر من ½', 'أصغر من ½'], categories_en: ['> ½', '< ½'], items_ar: [{ item: '¾', correct_category: 0 }, { item: '¼', correct_category: 1 }, { item: '⅛', correct_category: 1 }, { item: '⅔', correct_category: 0 }], items_en: [{ item: '¾', correct_category: 0 }, { item: '¼', correct_category: 1 }, { item: '⅛', correct_category: 1 }, { item: '⅔', correct_category: 0 }], explanation_ar: 'النصف = ٠.٥، ما يزيد عنه أكبر.', explanation_en: 'Half = 0.5; greater is above.' },
    { type: 'classify', q_ar: 'صنّف: نصف / ربع.', q_en: 'Sort: half / quarter.', categories_ar: ['نصف', 'ربع'], categories_en: ['half', 'quarter'], items_ar: [{ item: '½', correct_category: 0 }, { item: '¼', correct_category: 1 }, { item: '٢ من ٤ أجزاء', correct_category: 0 }, { item: '١ من ٤ أجزاء', correct_category: 1 }], items_en: [{ item: '½', correct_category: 0 }, { item: '¼', correct_category: 1 }, { item: '2 of 4 parts', correct_category: 0 }, { item: '1 of 4 parts', correct_category: 1 }], explanation_ar: 'النصف = ٢ جزء، الربع = ٤ أجزاء.', explanation_en: 'Half = 2 parts, quarter = 4 parts.' },
    { type: 'order', q_ar: 'رتّب الكسور من الأصغر إلى الأكبر.', q_en: 'Order fractions smallest to largest.', order_ar: ['¼', '½', '¾', '١ كامل'], order_en: ['¼', '½', '¾', '1 whole'], explanation_ar: '¼ < ½ < ¾ < ١.', explanation_en: '¼ < ½ < ¾ < 1.' },
    { type: 'order', q_ar: 'رتّب من الأكبر إلى الأصغر.', q_en: 'Order largest to smallest.', order_ar: ['١ كامل', '¾', '½', '¼'], order_en: ['1 whole', '¾', '½', '¼'], explanation_ar: '١ > ¾ > ½ > ¼.', explanation_en: '1 > ¾ > ½ > ¼.' },
    { type: 'word', q_ar: 'قسّمت أمل البيتزا إلى ٤ قطع متساوية وأكلت قطعة واحدة. ما الكسر الذي أكلته؟', q_en: 'Amal cut pizza into 4 equal slices and ate 1. What fraction did she eat?', answer_ar: '¼ (ربع البيتزا)', answer_en: '¼ (one quarter)', explanation_ar: '١ من ٤ أجزاء = ¼.', explanation_en: '1 of 4 parts = ¼.' },
    { type: 'word', q_ar: 'قسّم عمر الشريط إلى جزأين متساويين. ما كسر كل جزء؟', q_en: 'Omar split a ribbon into 2 equal parts. What fraction is each part?', answer_ar: '½ (نصف)', answer_en: '½ (one half)', explanation_ar: '١ من ٢ أجزاء = ½.', explanation_en: '1 of 2 parts = ½.' },
  ];
}

// ===== الفصل الثالث عشر — الدرس الأول: النقود السعودية =====
function LESSON_CH13_L1() {
  return [
    { type: 'mc', q_ar: 'كم ريالًا تساوي ورقة من فئة ١٠ ريالات؟', q_en: 'How many riyals is a 10-riyal note?', options_ar: ['١٠ ريالات', '١ ريال', '١٠٠ ريال', '٥ ريالات'], options_en: ['10 riyals', '1 riyal', '100 riyals', '5 riyals'], correct: '0', explanation_ar: 'ورقة ١٠ ريالات = ١٠ ريالات.', explanation_en: 'A 10-riyal note = 10 riyals.' },
    { type: 'mc', q_ar: 'أحمد يريد شراء هدية قيمتها ٢٧ ريالًا. أي النقود الكافية له؟', q_en: 'Ahmed wants a gift for 27 riyals. Which money is enough?', options_ar: ['ورقتان من ١٠ ريالات ونقطة من ١٠ هللات وورقة من ١٠ ريالات', 'ورقة ٥٠ ريالًا', 'ثلاث ورقات من ١٠ ريالات', 'ورقة ٢٠ ريالًا فقط'], options_en: ['two 10-riyal notes + extra', '50-riyal note', 'three 10-riyal notes', 'one 20-riyal note only'], correct: '2', explanation_ar: 'ثلاث ورقات ١٠ = ٣٠ ريالًا وهي أكثر من ٢٧.', explanation_en: 'Three 10-riyal notes = 30 riyals, enough for 27.' },
    { type: 'tf', q_ar: 'الريال الواحد يساوي ١٠٠ هللة.', q_en: 'One riyal equals 100 halalas.', options_ar: ['صح', 'خطأ'], options_en: ['True', 'False'], correct: '0', explanation_ar: 'نعم، ١ ريال = ١٠٠ هللة.', explanation_en: 'Yes, 1 riyal = 100 halalas.' },
    { type: 'tf', q_ar: 'ورقة ٥٠ ريالًا أقل قيمةً من ورقة ١٠٠ ريال.', q_en: 'A 50-riyal note is less than a 100-riyal note.', options_ar: ['صح', 'خطأ'], options_en: ['True', 'False'], correct: '0', explanation_ar: 'نعم، ٥٠ < ١٠٠.', explanation_en: 'Yes, 50 < 100.' },
    { type: 'fill', q_ar: 'ورقتان من ١٠ ريالات = __ ريالًا.', q_en: 'Two 10-riyal notes = __ riyals.', answer_ar: '٢٠', answer_en: '20', explanation_ar: '٢ × ١٠ = ٢٠.', explanation_en: '2 × 10 = 20.' },
    { type: 'fill', q_ar: '٣ عشرات ريالات = __ ريالًا.', q_en: '3 tens of riyals = __ riyals.', answer_ar: '٣٠', answer_en: '30', explanation_ar: '٣ × ١٠ = ٣٠.', explanation_en: '3 × 10 = 30.' },
    { type: 'compute', q_ar: 'كم ورقة من فئة ١٠ ريالات تحتاج لتكوين ٥٠ ريالًا؟', q_en: 'How many 10-riyal notes to make 50 riyals?', answer_ar: '٥ أوراق', answer_en: '5 notes', explanation_ar: '٥ × ١٠ = ٥٠.', explanation_en: '5 × 10 = 50.' },
    { type: 'compute', q_ar: 'مع سلمى ورقة ١٠ و٥ ريالات مفردة. كم ريالًا معها؟', q_en: 'Salma has a 10-riyal note and 5 single riyals. Total?', answer_ar: '١٥ ريالًا', answer_en: '15 riyals', explanation_ar: '١٠ + ٥ = ١٥.', explanation_en: '10 + 5 = 15.' },
    { type: 'match', q_ar: 'صل كل ورقة نقدية بقيمتها.', q_en: 'Match each note to its value.', pairs_ar: [{ left: 'ورقة خضراء', right: '١٠ ريالات' }, { left: 'ورقة حمراء', right: '٥٠ ريالًا' }, { left: 'ورقة بنية', right: '١٠٠ ريال' }], pairs_en: [{ left: 'green note', right: '10 riyals' }, { left: 'red note', right: '50 riyals' }, { left: 'brown note', right: '100 riyals' }], explanation_ar: 'الأوراق النقدية السعودية تتمايز بألوانها وأرقامها.', explanation_en: 'Saudi notes differ by color and number.' },
    { type: 'match', q_ar: 'صل كل مبلغ بعدد الأوراق من فئة ١٠ ريالات.', q_en: 'Match each amount to the number of 10-riyal notes.', pairs_ar: [{ left: '٢٠ ريالًا', right: 'ورقتان' }, { left: '٣٠ ريالًا', right: '٣ أوراق' }, { left: '٥٠ ريالًا', right: '٥ أوراق' }], pairs_en: [{ left: '20 riyals', right: '2 notes' }, { left: '30 riyals', right: '3 notes' }, { left: '50 riyals', right: '5 notes' }], explanation_ar: 'المبلغ ÷ ١٠ = عدد الأوراق.', explanation_en: 'Amount ÷ 10 = number of notes.' },
    { type: 'classify', q_ar: 'صنّف: أكثر من ٢٠ ريالًا / أقل من ٢٠ ريالًا.', q_en: 'Sort: more than 20 / less than 20 riyals.', categories_ar: ['أكثر من ٢٠', 'أقل من ٢٠'], categories_en: ['more than 20', 'less than 20'], items_ar: [{ item: '١٥ ريالًا', correct_category: 1 }, { item: '٣٠ ريالًا', correct_category: 0 }, { item: '١٠ ريالات', correct_category: 1 }, { item: '٥٠ ريالًا', correct_category: 0 }], items_en: [{ item: '15 riyals', correct_category: 1 }, { item: '30 riyals', correct_category: 0 }, { item: '10 riyals', correct_category: 1 }, { item: '50 riyals', correct_category: 0 }], explanation_ar: 'قارن بالـ٢٠ ريالًا.', explanation_en: 'Compare to 20 riyals.' },
    { type: 'classify', q_ar: 'صنّف: عملة / ورقة نقدية.', q_en: 'Sort: coin / paper note.', categories_ar: ['عملة معدنية', 'ورقة نقدية'], categories_en: ['coin', 'paper note'], items_ar: [{ item: 'ريال معدني', correct_category: 0 }, { item: 'ورقة ١٠ ريالات', correct_category: 1 }, { item: 'خمسون هللة', correct_category: 0 }, { item: 'ورقة ٥٠ ريالًا', correct_category: 1 }], items_en: [{ item: 'metal riyal', correct_category: 0 }, { item: '10-riyal note', correct_category: 1 }, { item: '50 halalas', correct_category: 0 }, { item: '50-riyal note', correct_category: 1 }], explanation_ar: 'العملات معدنية والأوراق من الورق.', explanation_en: 'Coins are metal, notes are paper.' },
    { type: 'order', q_ar: 'رتّب فئات النقود تصاعديًا.', q_en: 'Order denominations ascending.', order_ar: ['١ ريال', '٥ ريالات', '١٠ ريالات', '٥٠ ريالًا'], order_en: ['1 riyal', '5 riyals', '10 riyals', '50 riyals'], explanation_ar: '١ < ٥ < ١٠ < ٥٠.', explanation_en: '1 < 5 < 10 < 50.' },
    { type: 'order', q_ar: 'رتّب تنازليًا.', q_en: 'Order descending.', order_ar: ['١٠٠ ريال', '٥٠ ريالًا', '١٠ ريالات', '١ ريال'], order_en: ['100 riyals', '50 riyals', '10 riyals', '1 riyal'], explanation_ar: '١٠٠ > ٥٠ > ١٠ > ١.', explanation_en: '100 > 50 > 10 > 1.' },
    { type: 'word', q_ar: 'يريد أحمد شراء هدية قيمتها ٢٧ ريالًا. معه ٣ أوراق من ١٠ ريالات. هل يكفيه المبلغ؟', q_en: 'Ahmed wants a 27-riyal gift. He has 3 × 10-riyal notes. Is it enough?', answer_ar: 'نعم، ٣٠ ريالًا أكثر من ٢٧', answer_en: 'Yes, 30 riyals > 27', explanation_ar: '٣ × ١٠ = ٣٠ > ٢٧، يكفيه.', explanation_en: '3 × 10 = 30 > 27, enough.' },
    { type: 'word', q_ar: 'مع منى ورقتان من فئة ١٠ ريالات. وأخوها خالد معه ورقة واحدة من ١٠ ريالات وقطعتان نقديتان من فئة الريال. كم مجموع ما لديهما؟', q_en: 'Mona has 2×10 riyals, Khalid has 1×10 + 2×1 riyals. Total?', answer_ar: '٣٢ ريالًا', answer_en: '32 riyals', explanation_ar: '٢٠ + ١٢ = ٣٢.', explanation_en: '20 + 12 = 32.' },
  ];
}

// ===== الفصل الثالث عشر — الدرس الثاني: جمع النقود =====
function LESSON_CH13_L2() {
  return [
    { type: 'mc', q_ar: '١٠ + ١٠ + ٥ ريالات = __ ريالًا.', q_en: '10 + 10 + 5 riyals = __ riyals.', options_ar: ['٢٥', '١٥', '٢٠', '٣٠'], options_en: ['25', '15', '20', '30'], correct: '0', explanation_ar: '١٠ + ١٠ + ٥ = ٢٥.', explanation_en: '10 + 10 + 5 = 25.' },
    { type: 'mc', q_ar: 'اشترى سعيد كتابًا بـ١٢ ريالًا ودفع ورقة ٢٠ ريالًا. كم باقي المبلغ؟', q_en: 'Saeed bought a book for 12 riyals, paid 20. Change?', options_ar: ['٨ ريالات', '١٢ ريالًا', '٢٠ ريالًا', '٣٢ ريالًا'], options_en: ['8 riyals', '12 riyals', '20 riyals', '32 riyals'], correct: '0', explanation_ar: '٢٠ − ١٢ = ٨.', explanation_en: '20 − 12 = 8.' },
    { type: 'tf', q_ar: 'ورقتان من ١٠ ريالات تساوي ١ ورقة من ٢٠ ريالًا.', q_en: 'Two 10-riyal notes equal one 20-riyal note.', options_ar: ['صح', 'خطأ'], options_en: ['True', 'False'], correct: '0', explanation_ar: '٢ × ١٠ = ٢٠ = ورقة ٢٠ ريالًا.', explanation_en: '2 × 10 = 20 = one 20-riyal note.' },
    { type: 'tf', q_ar: '٥ ريالات + ٥ ريالات = ١٥ ريالًا.', q_en: '5 riyals + 5 riyals = 15 riyals.', options_ar: ['صح', 'خطأ'], options_en: ['True', 'False'], correct: '1', explanation_ar: 'خطأ: ٥ + ٥ = ١٠.', explanation_en: 'False: 5 + 5 = 10.' },
    { type: 'fill', q_ar: '١٠ + ٧ = __ ريالًا.', q_en: '10 + 7 = __ riyals.', answer_ar: '١٧', answer_en: '17', explanation_ar: '١٠ + ٧ = ١٧.', explanation_en: '10 + 7 = 17.' },
    { type: 'fill', q_ar: 'دفعت ٣٠ ريالًا واشتريت شيئًا بـ٢٢ ريالًا. الباقي __ ريالًا.', q_en: 'Paid 30, bought item for 22. Change = __.', answer_ar: '٨', answer_en: '8', explanation_ar: '٣٠ − ٢٢ = ٨.', explanation_en: '30 − 22 = 8.' },
    { type: 'compute', q_ar: '٢٠ + ٥ + ٢ = ؟ ريال', q_en: '20 + 5 + 2 = ? riyals', answer_ar: '٢٧ ريالًا', answer_en: '27 riyals', explanation_ar: '٢٠ + ٥ + ٢ = ٢٧.', explanation_en: '20 + 5 + 2 = 27.' },
    { type: 'compute', q_ar: 'دفع خالد ٥٠ ريالًا واشترى شيئًا بـ٣٦ ريالًا. كم باقي المبلغ؟', q_en: 'Khalid paid 50, bought for 36. Change?', answer_ar: '١٤ ريالًا', answer_en: '14 riyals', explanation_ar: '٥٠ − ٣٦ = ١٤.', explanation_en: '50 − 36 = 14.' },
    { type: 'match', q_ar: 'صل كل عملية بناتجها.', q_en: 'Match each operation to its result.', pairs_ar: [{ left: '١٠ + ١٠', right: '٢٠' }, { left: '٢٥ − ١٠', right: '١٥' }, { left: '٣٠ + ٧', right: '٣٧' }], pairs_en: [{ left: '10 + 10', right: '20' }, { left: '25 − 10', right: '15' }, { left: '30 + 7', right: '37' }], explanation_ar: 'الجمع والطرح في النقود.', explanation_en: 'Addition and subtraction with money.' },
    { type: 'match', q_ar: 'صل كل مسألة بإجابتها.', q_en: 'Match each problem to its answer.', pairs_ar: [{ left: 'دفع ٢٠، اشترى بـ١٢', right: 'باقي ٨' }, { left: 'جمع ١٥ و١٠', right: 'المجموع ٢٥' }, { left: 'دفع ٥٠، اشترى بـ٣٦', right: 'باقي ١٤' }], pairs_en: [{ left: 'paid 20, bought 12', right: 'change 8' }, { left: 'added 15 and 10', right: 'total 25' }, { left: 'paid 50, bought 36', right: 'change 14' }], explanation_ar: '٢٠−١٢=٨، ١٥+١٠=٢٥، ٥٠−٣٦=١٤.', explanation_en: '20−12=8, 15+10=25, 50−36=14.' },
    { type: 'classify', q_ar: 'صنّف: يكفي / لا يكفي لشراء شيء بـ٢٠ ريالًا.', q_en: 'Sort: enough / not enough to buy 20-riyal item.', categories_ar: ['يكفي', 'لا يكفي'], categories_en: ['enough', 'not enough'], items_ar: [{ item: '١٥ ريالًا', correct_category: 1 }, { item: '٢٥ ريالًا', correct_category: 0 }, { item: '١٨ ريالًا', correct_category: 1 }, { item: '٣٠ ريالًا', correct_category: 0 }], items_en: [{ item: '15 riyals', correct_category: 1 }, { item: '25 riyals', correct_category: 0 }, { item: '18 riyals', correct_category: 1 }, { item: '30 riyals', correct_category: 0 }], explanation_ar: 'يكفي إذا كان المبلغ ≥ ٢٠.', explanation_en: 'Enough if amount ≥ 20.' },
    { type: 'classify', q_ar: 'صنّف: جمع / طرح في النقود.', q_en: 'Sort: addition / subtraction with money.', categories_ar: ['جمع', 'طرح'], categories_en: ['addition', 'subtraction'], items_ar: [{ item: '١٠ + ٢٠', correct_category: 0 }, { item: '٣٠ − ١٢', correct_category: 1 }, { item: '١٥ + ٥', correct_category: 0 }, { item: '٥٠ − ٢٧', correct_category: 1 }], items_en: [{ item: '10 + 20', correct_category: 0 }, { item: '30 − 12', correct_category: 1 }, { item: '15 + 5', correct_category: 0 }, { item: '50 − 27', correct_category: 1 }], explanation_ar: 'الجمع للإضافة والطرح للباقي.', explanation_en: 'Addition for totals, subtraction for change.' },
    { type: 'order', q_ar: 'رتّب المبالغ تصاعديًا.', q_en: 'Order amounts ascending.', order_ar: ['٨ ريالات', '١٥ ريالًا', '٢٧ ريالًا', '٤٥ ريالًا'], order_en: ['8 riyals', '15 riyals', '27 riyals', '45 riyals'], explanation_ar: '٨ < ١٥ < ٢٧ < ٤٥.', explanation_en: '8 < 15 < 27 < 45.' },
    { type: 'order', q_ar: 'رتّب تنازليًا.', q_en: 'Order descending.', order_ar: ['٧٥ ريالًا', '٥٠ ريالًا', '٢٥ ريالًا', '١٠ ريالات'], order_en: ['75 riyals', '50 riyals', '25 riyals', '10 riyals'], explanation_ar: '٧٥ > ٥٠ > ٢٥ > ١٠.', explanation_en: '75 > 50 > 25 > 10.' },
    { type: 'word', q_ar: 'لدى منى ورقتان من ١٠ ريالات وورقة ١ ريال وعملتان من ١٠ ريالات. كم مجموع ما لديها؟', q_en: 'Mona has 2×10 notes + 1-riyal note + 2×10 coins. Total?', answer_ar: '٣١ ريالًا', answer_en: '31 riyals', explanation_ar: '٢٠ + ١ + ١٠ = ٣١.', explanation_en: '20 + 1 + 10 = 31.' },
    { type: 'word', q_ar: 'ما العدد الذي يقل بـ١٠ عن ٧٥؟', q_en: 'What number is 10 less than 75?', answer_ar: '٦٥', answer_en: '65', explanation_ar: '٧٥ − ١٠ = ٦٥.', explanation_en: '75 − 10 = 65.' },
  ];
}

export const MATH1_S2_TYPE_LABELS = {
  mc: 'اختيار من متعدد',
  tf: 'صح أم خطأ',
  fill: 'أكمل الفراغ',
  compute: 'أوجد الناتج',
  match: 'وصل',
  classify: 'صنّف',
  order: 'رتّب',
  word: 'مسألة حياتية',
};

export function getChapter(chId) {
  return MATH1_S2_CHAPTERS.find((c) => c.id === chId);
}
export function getLesson(chId, lId) {
  const ch = getChapter(chId);
  if (!ch) return null;
  return ch.lessons.find((l) => l.id === lId) || null;
}
export const TOTAL_CHAPTERS = MATH1_S2_CHAPTERS.length;
export const TOTAL_LESSONS = MATH1_S2_CHAPTERS.reduce((s, c) => s + c.lessons.length, 0);