// بنك رياضيات الصف الثالث الابتدائي — الفصل الثاني
// الفصل السادس: القسمة (١) | الفصل السابع: القسمة (٢)
// المصدر: صفحات الكتاب المُرفَعة (وزارة التعليم) ص٢٨–٤٨

// الأنواع: mc | tf | fill | compute | match | classify | order | word

// صور توضيحية مُولّدة للسيناريوهات (رسوم مائية تعليمية)
const IMG_APPLES = 'https://media.base44.com/images/public/6a459ddfe6fb4264c098136d/79a12b0a7_generated_image.png';
const IMG_BUS = 'https://media.base44.com/images/public/6a459ddfe6fb4264c098136d/df28d2a00_generated_image.png';
const IMG_JUICE = 'https://media.base44.com/images/public/6a459ddfe6fb4264c098136d/e4b7442b2_generated_image.png';
const IMG_OLIVE = 'https://media.base44.com/images/public/6a459ddfe6fb4264c098136d/bea70735d_generated_image.png';
const IMG_PENCILS = 'https://media.base44.com/images/public/6a459ddfe6fb4264c098136d/cd0aa6843_generated_image.png';
const IMG_FLOWERS = 'https://media.base44.com/images/public/6a459ddfe6fb4264c098136d/bedf9c112_generated_image.png';

// ===== الفصل السادس: القسمة (١) =====

// 6-1 القسمة بالطرح المتكرر
function LESSON_CH6_L1() {
  return [
    { type: 'mc', image: IMG_APPLES, q_ar: 'أي عملية نستخدم للقسمة بالطرح المتكرر في 12÷6؟', q_en: 'Which operation for repeated subtraction in 12÷6?', options_ar: ['نطرح 6 حتى نصل إلى الصفر', 'نجمع 6 مرتين', 'نضرب 6×2', 'نقسم 6 على 12'], options_en: ['Subtract 6 until zero', 'Add 6 twice', 'Multiply 6×2', 'Divide 6 by 12'], correct: '0', explanation_ar: 'الطرح المتكرر: 12-6=6 ثم 6-6=0، طرحنا مرتين.', explanation_en: 'Repeated subtraction: 12-6=6, 6-6=0, subtracted twice.' },
    { type: 'mc', image: IMG_APPLES, q_ar: '٨ ÷ ٢ = ؟ (بالطرح المتكرر)', q_en: '8 ÷ 2 = ? (repeated subtraction)', options_ar: ['٤', '٢', '٦', '٨'], options_en: ['4', '2', '6', '8'], correct: '0', explanation_ar: '٨-٢=٦-٢=٤-٢=٢-٢=٠، طرحنا ٤ مرات.', explanation_en: '8-2-2-2-2=0, subtracted 4 times.' },
    { type: 'tf', q_ar: '١٢ ÷ ٦ = ٢ لأننا طرحنا ٦ مرتين من ١٢.', q_en: '12 ÷ 6 = 2 because we subtracted 6 twice from 12.', options_ar: ['صح', 'خطأ'], options_en: ['True', 'False'], correct: '0', explanation_ar: '١٢-٦=٦-٦=٠، ٢ مرات.', explanation_en: '12-6=6, 6-6=0, twice.' },
    { type: 'tf', q_ar: '١٥ ÷ ٣ = ٦', q_en: '15 ÷ 3 = 6', options_ar: ['صح', 'خطأ'], options_en: ['True', 'False'], correct: '1', explanation_ar: '١٥-٣-٣-٣-٣-٣=٠، خمس مرات، إذن ١٥÷٣=٥.', explanation_en: 'Subtract 3 five times: 15÷3=5.' },
    { type: 'fill', image: 'https://media.base44.com/images/public/6a459ddfe6fb4264c098136d/568c730df_generated_image.png', q_ar: '١٠ ÷ ٢ = __ (استخدم خط الأعداد)', q_en: '10 ÷ 2 = __ (use number line)', answer_ar: '٥', answer_en: '5', explanation_ar: 'نطرح ٢ خمس مرات من ١٠.', explanation_en: 'Subtract 2 five times from 10.' },
    { type: 'fill', q_ar: '١٦ ÷ ٢ = __', q_en: '16 ÷ 2 = __', answer_ar: '٨', answer_en: '8', explanation_ar: '١٦-٢-٢-٢-٢-٢-٢-٢-٢=٠، ٨ مرات.', explanation_en: 'Subtract 2 eight times.' },
    { type: 'compute', q_ar: 'أوجد: ١٢ ÷ ٢', q_en: 'Find: 12 ÷ 2', answer_ar: '٦', answer_en: '6', explanation_ar: '١٢-٢-٢-٢-٢-٢-٢=٠، ٦ مرات.', explanation_en: 'Subtract 2 six times from 12.' },
    { type: 'compute', q_ar: 'أوجد: ٨ ÷ ٢', q_en: 'Find: 8 ÷ 2', answer_ar: '٤', answer_en: '4', explanation_ar: '٨÷٢=٤.', explanation_en: '8÷2=4.' },
    { type: 'match', q_ar: 'صل جملة القسمة بناتجها.', q_en: 'Match division sentence to result.', pairs_ar: [{ left: '١٢ ÷ ٦', right: '٢' }, { left: '١٠ ÷ ٢', right: '٥' }, { left: '١٦ ÷ ٢', right: '٨' }], pairs_en: [{ left: '12÷6', right: '2' }, { left: '10÷2', right: '5' }, { left: '16÷2', right: '8' }], explanation_ar: 'استخدم الطرح المتكرر.', explanation_en: 'Use repeated subtraction.' },
    { type: 'match', q_ar: 'صل العدد بعدد مرات الطرح لقسمته على ٢.', q_en: 'Match number to times of subtraction by 2.', pairs_ar: [{ left: '٦', right: '٣ مرات' }, { left: '٨', right: '٤ مرات' }, { left: '١٢', right: '٦ مرات' }], pairs_en: [{ left: '6', right: '3 times' }, { left: '8', right: '4 times' }, { left: '12', right: '6 times' }], explanation_ar: 'عدد مرات الطرح = ناتج القسمة.', explanation_en: 'Times of subtraction = division result.' },
    { type: 'classify', q_ar: 'صنّف: ناتج القسمة ٤ / ناتج القسمة غير ٤.', q_en: 'Sort: result is 4 / result is not 4.', categories_ar: ['الناتج ٤', 'الناتج ليس ٤'], categories_en: ['Result=4', 'Result≠4'], items_ar: [{ item: '٨÷٢', correct_category: 0 }, { item: '١٢÷٣', correct_category: 0 }, { item: '١٠÷٢', correct_category: 1 }, { item: '١٢÷٢', correct_category: 1 }], items_en: [{ item: '8÷2', correct_category: 0 }, { item: '12÷3', correct_category: 0 }, { item: '10÷2', correct_category: 1 }, { item: '12÷2', correct_category: 1 }], explanation_ar: '٨÷٢=٤، ١٢÷٣=٤، ١٠÷٢=٥، ١٢÷٢=٦.', explanation_en: '8÷2=4, 12÷3=4, 10÷2=5, 12÷2=6.' },
    { type: 'classify', q_ar: 'صنّف جمل القسمة: مقسوم عليه ٢ / مقسوم عليه ٦.', q_en: 'Sort: divisor 2 / divisor 6.', categories_ar: ['مقسوم عليه ٢', 'مقسوم عليه ٦'], categories_en: ['÷2', '÷6'], items_ar: [{ item: '١٤÷٢', correct_category: 0 }, { item: '١٠÷٢', correct_category: 0 }, { item: '١٢÷٦', correct_category: 1 }, { item: '١٨÷٦', correct_category: 1 }], items_en: [{ item: '14÷2', correct_category: 0 }, { item: '10÷2', correct_category: 1 }, { item: '12÷6', correct_category: 1 }, { item: '18÷6', correct_category: 1 }], explanation_ar: 'انظر المقسوم عليه.', explanation_en: 'Look at the divisor.' },
    { type: 'order', q_ar: 'رتّب نواتج القسمة (مقسوم عليه ٢) تصاعديًا: ٨÷٢، ١٢÷٢، ٦÷٢.', q_en: 'Order results (÷2) ascending: 8÷2, 12÷2, 6÷2.', order_ar: ['٦÷٢=٣', '٨÷٢=٤', '١٢÷٢=٦'], order_en: ['6÷2=3', '8÷2=4', '12÷2=6'], explanation_ar: '٣ < ٤ < ٦.', explanation_en: '3 < 4 < 6.' },
    { type: 'order', q_ar: 'رتّب جمل القسمة حسب ناتجها من الأكبر للأصغر: ١٦÷٢، ٨÷٢، ١٢÷٢.', q_en: 'Order by result descending: 16÷2, 8÷2, 12÷2.', order_ar: ['١٦÷٢=٨', '١٢÷٢=٦', '٨÷٢=٤'], order_en: ['16÷2=8', '12÷2=6', '8÷2=4'], explanation_ar: '٨ > ٦ > ٤.', explanation_en: '8 > 6 > 4.' },
    { type: 'word', image: IMG_PENCILS, q_ar: 'يريد خالد قراءة ١٨ فصلًا من كتاب يوميًا، فإذا كان الكتاب يتكوّن من ١٨ فصلًا، فكم يومًا يحتاج ليُنهيه إذا قرأ ٣ فصول يوميًا؟', q_en: 'Khalid reads 18 chapters, 3 per day. How many days?', answer_ar: '٦ أيام', answer_en: '6 days', explanation_ar: '١٨ ÷ ٣ = ٦ أيام.', explanation_en: '18 ÷ 3 = 6 days.' },
    { type: 'word', image: IMG_BUS, q_ar: 'قامت ١٢ طالبًا برحلة في ٢ حافلتين متساويتين؛ كم عدد الطلاب في كل حافلة؟', q_en: '12 students, 2 equal buses. Students per bus?', answer_ar: '٦ طلاب', answer_en: '6 students', explanation_ar: '١٢ ÷ ٢ = ٦.', explanation_en: '12 ÷ 2 = 6.' },
  ];
}

// 6-2 الحقائق المترابطة (الضرب والقسمة)
function LESSON_CH6_L2() {
  return [
    { type: 'mc', q_ar: 'أيٌّ من الجمل التالية تمثّل حقيقة مترابطة لـ ٣×٦=١٨؟', q_en: 'Which is a related fact for 3×6=18?', options_ar: ['١٨÷٦=٣', '١٨÷٣=٤', '٦÷٣=٢', '١٨÷٢=٩'], options_en: ['18÷6=3', '18÷3=4', '6÷3=2', '18÷2=9'], correct: '0', explanation_ar: 'الحقائق المترابطة: ٣×٦=١٨ و٦×٣=١٨ و١٨÷٦=٣ و١٨÷٣=٦.', explanation_en: 'Related: 3×6=18, 6×3=18, 18÷6=3, 18÷3=6.' },
    { type: 'mc', q_ar: 'جملة القسمة المترابطة لـ ٢×٨=١٦ هي:', q_en: 'Division sentence related to 2×8=16 is:', options_ar: ['١٦÷٨=٢', '١٦÷٢=٩', '٨÷٢=٤', '٢÷٨=٠.٢٥'], options_en: ['16÷8=2', '16÷2=9', '8÷2=4', '2÷8=0.25'], correct: '0', explanation_ar: '١٦÷٨=٢ أو ١٦÷٢=٨.', explanation_en: '16÷8=2 or 16÷2=8.' },
    { type: 'tf', q_ar: 'الحقائق المترابطة لمجموعة الأعداد ٢٧، ٩، ٣ هي: ٩×٣=٢٧ و٢٧÷٩=٣.', q_en: 'Related facts for 27,9,3: 9×3=27 and 27÷9=3.', options_ar: ['صح', 'خطأ'], options_en: ['True', 'False'], correct: '0', explanation_ar: 'صحيح: ٩×٣=٢٧ و٣×٩=٢٧ و٢٧÷٩=٣ و٢٧÷٣=٩.', explanation_en: 'Correct: 9×3=27, 27÷9=3, 27÷3=9.' },
    { type: 'tf', q_ar: 'من مجموعة ٥، ٢، ١٠: الحقائق المترابطة تشمل ٥×١٠=٢.', q_en: 'From group 5,2,10: related facts include 5×10=2.', options_ar: ['صح', 'خطأ'], options_en: ['True', 'False'], correct: '1', explanation_ar: '٥×٢=١٠ لا ٥×١٠.', explanation_en: '5×2=10, not 5×10.' },
    { type: 'fill', q_ar: 'أكمل: ٢×__ = ١٢ و١٢÷٦ = __', q_en: 'Complete: 2×__ = 12 and 12÷6 = __', answer_ar: '٦ ثم ٢', answer_en: '6 then 2', explanation_ar: 'الحقائق المترابطة: ٢×٦=١٢ و١٢÷٦=٢.', explanation_en: 'Related: 2×6=12, 12÷6=2.' },
    { type: 'fill', q_ar: 'اكتب الحقائق المترابطة لـ (١٠، ٢، ٥): ٢×٥=__، ١٠÷٢=__', q_en: 'Related facts for (10,2,5): 2×5=__, 10÷2=__', answer_ar: '١٠ ثم ٥', answer_en: '10 then 5', explanation_ar: '٢×٥=١٠ و١٠÷٢=٥.', explanation_en: '2×5=10, 10÷2=5.' },
    { type: 'compute', q_ar: 'اكتب الحقائق المترابطة لـ (٣، ٩، ٢٧).', q_en: 'Write related facts for (3,9,27).', answer_ar: '٣×٩=٢٧ و٩×٣=٢٧ و٢٧÷٩=٣ و٢٧÷٣=٩', answer_en: '3×9=27, 9×3=27, 27÷9=3, 27÷3=9', explanation_ar: 'أربع حقائق مترابطة.', explanation_en: 'Four related facts.' },
    { type: 'compute', q_ar: 'اكتب حقيقة الضرب المترابطة لـ ٨١÷٩=٩.', q_en: 'Write related multiplication fact for 81÷9=9.', answer_ar: '٩×٩=٨١', answer_en: '9×9=81', explanation_ar: 'إذا ٨١÷٩=٩، فإن ٩×٩=٨١.', explanation_en: 'If 81÷9=9, then 9×9=81.' },
    { type: 'match', q_ar: 'صل مجموعة الأعداد بحقائقها المترابطة.', q_en: 'Match number group to related facts.', pairs_ar: [{ left: '٢٧، ٩، ٣', right: '٩×٣=٢٧' }, { left: '١٠، ٢، ٥', right: '٢×٥=١٠' }, { left: '٨١، ٩، ٩', right: '٩×٩=٨١' }], pairs_en: [{ left: '27,9,3', right: '9×3=27' }, { left: '10,2,5', right: '2×5=10' }, { left: '81,9,9', right: '9×9=81' }], explanation_ar: 'الكبير هو الحاصل.', explanation_en: 'The largest is the product.' },
    { type: 'match', q_ar: 'صل جملة الضرب بجملة القسمة المترابطة.', q_en: 'Match multiplication to related division.', pairs_ar: [{ left: '٣×٦=١٨', right: '١٨÷٦=٣' }, { left: '٢×٨=١٦', right: '١٦÷٨=٢' }, { left: '٤×٥=٢٠', right: '٢٠÷٥=٤' }], pairs_en: [{ left: '3×6=18', right: '18÷6=3' }, { left: '2×8=16', right: '16÷8=2' }, { left: '4×5=20', right: '20÷5=4' }], explanation_ar: 'الضرب والقسمة عمليتان عكسيتان.', explanation_en: 'Multiplication and division are inverse operations.' },
    { type: 'classify', q_ar: 'صنّف: جمل ضرب / جمل قسمة.', q_en: 'Sort: multiplication / division sentences.', categories_ar: ['جمل ضرب', 'جمل قسمة'], categories_en: ['Multiplication', 'Division'], items_ar: [{ item: '٩×٣=٢٧', correct_category: 0 }, { item: '٢×٥=١٠', correct_category: 0 }, { item: '٢٧÷٩=٣', correct_category: 1 }, { item: '١٠÷٢=٥', correct_category: 1 }], items_en: [{ item: '9×3=27', correct_category: 0 }, { item: '2×5=10', correct_category: 0 }, { item: '27÷9=3', correct_category: 1 }, { item: '10÷2=5', correct_category: 1 }], explanation_ar: '× = ضرب، ÷ = قسمة.', explanation_en: '× = multiplication, ÷ = division.' },
    { type: 'classify', q_ar: 'صنّف: تنتمي لمجموعة (٢٧،٩،٣) / لا تنتمي.', q_en: 'Sort: belongs to group (27,9,3) / does not.', categories_ar: ['تنتمي للمجموعة', 'لا تنتمي'], categories_en: ['Belongs', 'Does not'], items_ar: [{ item: '٩×٣=٢٧', correct_category: 0 }, { item: '٢٧÷٩=٣', correct_category: 0 }, { item: '٩×٩=٨١', correct_category: 1 }, { item: '١٠÷٢=٥', correct_category: 1 }], items_en: [{ item: '9×3=27', correct_category: 0 }, { item: '27÷9=3', correct_category: 0 }, { item: '9×9=81', correct_category: 1 }, { item: '10÷2=5', correct_category: 1 }], explanation_ar: 'المجموعة: ٢٧ و٩ و٣.', explanation_en: 'Group: 27, 9, 3.' },
    { type: 'order', q_ar: 'رتّب: اكتب الأصغر فأكبر لمجموعة الأعداد (٣، ٩، ٢٧).', q_en: 'Order ascending: group (3,9,27).', order_ar: ['٣', '٩', '٢٧'], order_en: ['3', '9', '27'], explanation_ar: '٣ < ٩ < ٢٧.', explanation_en: '3 < 9 < 27.' },
    { type: 'order', q_ar: 'رتّب حقائق الضرب حسب الناتج تصاعديًا: ٢×٥، ٣×٦، ٢×٨.', q_en: 'Order by product ascending: 2×5, 3×6, 2×8.', order_ar: ['٢×٥=١٠', '٢×٨=١٦', '٣×٦=١٨'], order_en: ['2×5=10', '2×8=16', '3×6=18'], explanation_ar: '١٠ < ١٦ < ١٨.', explanation_en: '10 < 16 < 18.' },
    { type: 'word', q_ar: 'دفع كل طالب من طلاب نادي التربية الفنية ٨ ريالات، إذا تجمّع ٨٠ ريالًا، فكم عدد الطلاب؟', q_en: 'Each art club student paid 8 riyals, total 80. How many students?', answer_ar: '١٠ طلاب', answer_en: '10 students', explanation_ar: '٨٠ ÷ ٨ = ١٠.', explanation_en: '80 ÷ 8 = 10.' },
    { type: 'word', image: IMG_PENCILS, q_ar: 'لدى نواف ١٥٠ ريالًا، اشترى هديةً لوالدته بـ ٧٠ ريالًا، وقلمًا لوالده بـ ٤٥ ريالًا، فكم ريالًا بقي لدى نواف؟', q_en: 'Nawaf has 150, spent 70 on gift and 45 on pen. Left?', answer_ar: '٣٥ ريالًا', answer_en: '35 riyals', explanation_ar: '١٥٠ - ٧٠ - ٤٥ = ٣٥.', explanation_en: '150-70-45=35.' },
  ];
}

// 6-3 أحل المسألة: تحديد العملية المناسبة
function LESSON_CH6_L3() {
  return [
    { type: 'mc', q_ar: 'لتحديد العملية المناسبة لمسألة تتضمن توزيعًا بالتساوي نستخدم:', q_en: 'For equal sharing problems we use:', options_ar: ['القسمة', 'الجمع', 'الطرح', 'الضرب'], options_en: ['Division', 'Addition', 'Subtraction', 'Multiplication'], correct: '0', explanation_ar: 'التوزيع بالتساوي = قسمة.', explanation_en: 'Equal sharing = division.' },
    { type: 'mc', q_ar: 'الحافلة تسع ١٢ طالبًا، قام ١٢ طالبًا برحلة في حافلتين متساويتين، فكم طالبًا في كل حافلة؟', q_en: 'Bus holds 12, 12 students in 2 equal buses. Per bus?', options_ar: ['٦', '١٢', '٢٤', '١٠'], options_en: ['6', '12', '24', '10'], correct: '0', explanation_ar: '١٢ ÷ ٢ = ٦.', explanation_en: '12 ÷ 2 = 6.' },
    { type: 'tf', q_ar: 'إذا تجمّع ٣٥ ريالًا من ٥ أشخاص دفعوا بالتساوي، فكل شخص دفع ٧ ريالات.', q_en: 'If 35 riyals from 5 people equally, each paid 7.', options_ar: ['صح', 'خطأ'], options_en: ['True', 'False'], correct: '0', explanation_ar: '٣٥ ÷ ٥ = ٧.', explanation_en: '35 ÷ 5 = 7.' },
    { type: 'tf', q_ar: 'مسألة «كم مجموعة يمكن تكوينها» تحتاج عملية الجمع.', q_en: '"How many groups" problems use addition.', options_ar: ['صح', 'خطأ'], options_en: ['True', 'False'], correct: '1', explanation_ar: 'مسائل تكوين المجموعات تستخدم القسمة.', explanation_en: 'Group-forming problems use division.' },
    { type: 'fill', q_ar: 'دفع عادل ١٦ ريالًا لشراء ٢ لعبة بنفس الثمن، فثمن كل لعبة __ ريالًا.', q_en: 'Adel paid 16 for 2 equal toys. Price each = __ riyals.', answer_ar: '٨', answer_en: '8', explanation_ar: '١٦ ÷ ٢ = ٨.', explanation_en: '16 ÷ 2 = 8.' },
    { type: 'fill', q_ar: 'العملية المناسبة لمسألة «قسمة ١٤ تفاحة على ٧ أطفال بالتساوي» هي __ .', q_en: 'Correct operation for «divide 14 apples among 7» is __.', answer_ar: 'القسمة', answer_en: 'Division', explanation_ar: 'توزيع بالتساوي = قسمة.', explanation_en: 'Equal sharing = division.' },
    { type: 'compute', q_ar: 'قام ١٢ طالبًا برحلة في ٢ حافلتين متساويتين، كم عدد الطلاب في كل حافلة؟', q_en: '12 students in 2 equal buses. Per bus?', answer_ar: '٦ طلاب', answer_en: '6 students', explanation_ar: '١٢ ÷ ٢ = ٦.', explanation_en: '12 ÷ 2 = 6.' },
    { type: 'compute', q_ar: 'حدّد العملية المناسبة ثم احلل: دفع كل طالب ٨ ريالات ليعمل في التربية الفنية، فإذا تجمّع ٨٠ ريالًا، فكم عدد طلاب النادي؟', q_en: 'Each student paid 8, total 80. How many students?', answer_ar: 'القسمة: ٨٠ ÷ ٨ = ١٠ طلاب', answer_en: 'Division: 80 ÷ 8 = 10 students', explanation_ar: 'التوزيع المتساوي يستدعي القسمة.', explanation_en: 'Equal sharing requires division.' },
    { type: 'match', q_ar: 'صل المسألة بالعملية المناسبة.', q_en: 'Match problem to operation.', pairs_ar: [{ left: 'توزيع ٢٤ قلمًا على ٦ طلاب', right: 'قسمة' }, { left: 'دمج مجموعتين من الكتب', right: 'جمع' }, { left: 'إيجاد الفرق في عدد الكتب', right: 'طرح' }], pairs_en: [{ left: '24 pens among 6 students', right: 'Division' }, { left: 'Combine two book groups', right: 'Addition' }, { left: 'Find difference in books', right: 'Subtraction' }], explanation_ar: 'حدد نوع المسألة أولًا.', explanation_en: 'Identify problem type first.' },
    { type: 'match', q_ar: 'صل المسألة بجملتها العددية الصحيحة.', q_en: 'Match problem to number sentence.', pairs_ar: [{ left: '١٤ طالبًا في مجموعتين متساويتين', right: '١٤÷٢=٧' }, { left: 'بستان فيه ٣٥ شجرة في ٧ صفوف', right: '٣٥÷٧=٥' }, { left: '١٢ زهرة في زهريتين متساويتين', right: '١٢÷٢=٦' }], pairs_en: [{ left: '14 students, 2 equal groups', right: '14÷2=7' }, { left: '35 trees, 7 rows', right: '35÷7=5' }, { left: '12 flowers, 2 equal vases', right: '12÷2=6' }], explanation_ar: 'ابنِ الجملة العددية ثم احلل.', explanation_en: 'Build then solve.' },
    { type: 'classify', q_ar: 'صنّف المسائل: تحتاج قسمة / تحتاج ضربًا.', q_en: 'Sort: needs division / needs multiplication.', categories_ar: ['قسمة', 'ضرب'], categories_en: ['Division', 'Multiplication'], items_ar: [{ item: 'توزيع ٣٠ كرة على ٦ أطفال', correct_category: 0 }, { item: 'كم تبلغ ٥ أكياس من ٦ تفاحات', correct_category: 1 }, { item: 'تقسيم ١٨ ورقة على ٣ مجموعات', correct_category: 0 }, { item: 'إيجاد مجموع ٤ صفوف من ٧ طلاب', correct_category: 1 }], items_en: [{ item: '30 balls among 6 kids', correct_category: 0 }, { item: '5 bags of 6 apples each', correct_category: 1 }, { item: '18 papers to 3 groups', correct_category: 0 }, { item: '4 rows of 7 students', correct_category: 1 }], explanation_ar: 'التوزيع والتجميع = قسمة؛ المجموعات المتعددة = ضرب.', explanation_en: 'Sharing=division; equal groups=multiplication.' },
    { type: 'classify', q_ar: 'صنّف: مسألة يُستخدم فيها «÷» أم «-»؟', q_en: 'Sort: uses ÷ or uses -?', categories_ar: ['يستخدم القسمة', 'يستخدم الطرح'], categories_en: ['Uses ÷', 'Uses -'], items_ar: [{ item: 'توزيع ٢٠ بطاقة على ٤ مجموعات', correct_category: 0 }, { item: 'إيجاد ما بقي من ٣٥ بعد شراء ١٤', correct_category: 1 }, { item: 'تقسيم ١٦ على ٢ حافلتين', correct_category: 0 }, { item: 'حساب الفرق بين ٣٠ و١٨', correct_category: 1 }], items_en: [{ item: '20 cards to 4 groups', correct_category: 0 }, { item: 'Left from 35 after buying 14', correct_category: 1 }, { item: '16 into 2 buses', correct_category: 0 }, { item: 'Difference between 30 and 18', correct_category: 1 }], explanation_ar: 'حدد ما تريد إيجاده.', explanation_en: 'Identify what you need to find.' },
    { type: 'order', q_ar: 'رتّب خطوات حل المسألة بالتسلسل.', q_en: 'Order problem-solving steps.', order_ar: ['قرأ المسألة', 'تحديد العملية المناسبة', 'كتابة الجملة العددية', 'الحل والتحقق'], order_en: ['Read', 'Identify operation', 'Write number sentence', 'Solve and check'], explanation_ar: 'خطوات حل المسألة بالترتيب.', explanation_en: 'Problem-solving steps in order.' },
    { type: 'order', q_ar: 'رتّب نواتج القسمة التالية تصاعديًا: ٢٤÷٦، ٣٥÷٧، ١٢÷٢.', q_en: 'Order results ascending: 24÷6, 35÷7, 12÷2.', order_ar: ['٢٤÷٦=٤', '٣٥÷٧=٥', '١٢÷٢=٦'], order_en: ['24÷6=4', '35÷7=5', '12÷2=6'], explanation_ar: '٤ < ٥ < ٦.', explanation_en: '4 < 5 < 6.' },
    { type: 'word', q_ar: 'دفع طالبٌ كل طالب من طلاب نادي التربية الفنية ٨ ريالاتٍ استبدالًا لمواد الرسم، إذا تجمّع ٨٠ ريالًا، فكم عدد طلاب النادي؟', q_en: 'Art club: each paid 8, total 80. How many students?', answer_ar: '١٠ طلاب', answer_en: '10 students', explanation_ar: 'العملية: قسمة. ٨٠÷٨=١٠.', explanation_en: 'Operation: division. 80÷8=10.' },
    { type: 'word', image: IMG_BUS, q_ar: 'قام ١٥ طالبًا برحلة ميدانية مستقلّين حافلتين، في كل منهما العدد نفسه من الطلاب، فكم عدد الطلاب في كل حافلة منهما؟', q_en: '15 students split into 2 equal buses. Per bus?', answer_ar: '٧.٥ — يُعاد تقسيم المسألة (أو يُدوَّن أن ١٥ لا تقبل القسمة على ٢ بالتساوي)', answer_en: '15 does not divide evenly by 2', explanation_ar: 'هنا الكتاب يقصد ١٢ طالبًا في حافلتين (مثال الكتاب الأصلي).', explanation_en: 'Original book example: 12 students in 2 buses = 6 each.' },
  ];
}

// 6-4 الجبر (إيجاد العدد المفقود)
function LESSON_CH6_L4() {
  return [
    { type: 'mc', image: IMG_APPLES, q_ar: '__ ÷ ٢ = ٨، ما العدد المفقود؟', q_en: '__ ÷ 2 = 8, find the missing number.', options_ar: ['١٦', '٤', '١٠', '٦'], options_en: ['16', '4', '10', '6'], correct: '0', explanation_ar: '٨ × ٢ = ١٦.', explanation_en: '8 × 2 = 16.' },
    { type: 'mc', q_ar: '١٦ ÷ __ = ٢، ما المقسوم عليه؟', q_en: '16 ÷ __ = 2, find the divisor.', options_ar: ['٨', '٤', '٢', '١٦'], options_en: ['8', '4', '2', '16'], correct: '0', explanation_ar: '١٦ ÷ ٨ = ٢.', explanation_en: '16 ÷ 8 = 2.' },
    { type: 'tf', q_ar: 'إذا كان __ ÷ ٢ = ٦ فإن العدد المفقود = ١٢.', q_en: 'If __ ÷ 2 = 6, missing = 12.', options_ar: ['صح', 'خطأ'], options_en: ['True', 'False'], correct: '0', explanation_ar: '٦ × ٢ = ١٢.', explanation_en: '6 × 2 = 12.' },
    { type: 'tf', q_ar: '١٤ ÷ __ = ٢، المقسوم عليه = ٧.', q_en: '14 ÷ __ = 2, divisor = 7.', options_ar: ['صح', 'خطأ'], options_en: ['True', 'False'], correct: '0', explanation_ar: '١٤ ÷ ٧ = ٢.', explanation_en: '14 ÷ 7 = 2.' },
    { type: 'fill', q_ar: '__ ÷ ٢ = ٧، العدد المفقود = __', q_en: '__ ÷ 2 = 7, missing = __', answer_ar: '١٤', answer_en: '14', explanation_ar: '٧ × ٢ = ١٤.', explanation_en: '7 × 2 = 14.' },
    { type: 'fill', q_ar: '١٦ ÷ ٢ = __, أوجد العدد المفقود في التعبير', q_en: '16 ÷ 2 = __', answer_ar: '٨', answer_en: '8', explanation_ar: '١٦ ÷ ٢ = ٨.', explanation_en: '16 ÷ 2 = 8.' },
    { type: 'compute', q_ar: 'أوجد العدد المفقود: __ ÷ ٢ = ٩', q_en: 'Find missing: __ ÷ 2 = 9', answer_ar: '١٨', answer_en: '18', explanation_ar: '٩ × ٢ = ١٨.', explanation_en: '9 × 2 = 18.' },
    { type: 'compute', q_ar: 'أوجد العدد المفقود: ٢ = __ ÷ ١٦', q_en: 'Find missing: 2 = __ ÷ 16', answer_ar: '٣٢', answer_en: '32', explanation_ar: '٢ × ١٦ = ٣٢.', explanation_en: '2 × 16 = 32.' },
    { type: 'match', q_ar: 'صل التعبير بالعدد المفقود.', q_en: 'Match expression to missing number.', pairs_ar: [{ left: '__ ÷ ٢ = ٦', right: '١٢' }, { left: '__ ÷ ٢ = ٨', right: '١٦' }, { left: '__ ÷ ٢ = ٩', right: '١٨' }], pairs_en: [{ left: '__÷2=6', right: '12' }, { left: '__÷2=8', right: '16' }, { left: '__÷2=9', right: '18' }], explanation_ar: 'الناتج × المقسوم عليه = المقسوم.', explanation_en: 'Result × divisor = dividend.' },
    { type: 'match', q_ar: 'صل التعبير بقيمة المقسوم عليه المفقود.', q_en: 'Match to missing divisor.', pairs_ar: [{ left: '١٤ ÷ __ = ٢', right: '٧' }, { left: '١٦ ÷ __ = ٢', right: '٨' }, { left: '١٢ ÷ __ = ٢', right: '٦' }], pairs_en: [{ left: '14÷__=2', right: '7' }, { left: '16÷__=2', right: '8' }, { left: '12÷__=2', right: '6' }], explanation_ar: 'المقسوم ÷ الناتج = المقسوم عليه.', explanation_en: 'Dividend ÷ result = divisor.' },
    { type: 'classify', q_ar: 'صنّف: العدد المفقود أكبر من ١٠ / أصغر.', q_en: 'Sort: missing > 10 / < 10.', categories_ar: ['العدد المفقود > ١٠', 'العدد المفقود < ١٠'], categories_en: ['Missing > 10', 'Missing < 10'], items_ar: [{ item: '__ ÷ ٢ = ٧', correct_category: 0 }, { item: '__ ÷ ٢ = ٨', correct_category: 0 }, { item: '__ ÷ ٢ = ٤', correct_category: 1 }, { item: '__ ÷ ٢ = ٣', correct_category: 1 }], items_en: [{ item: '__÷2=7', correct_category: 0 }, { item: '__÷2=8', correct_category: 0 }, { item: '__÷2=4', correct_category: 1 }, { item: '__÷2=3', correct_category: 1 }], explanation_ar: '٧×٢=١٤ و٨×٢=١٦ كلاهما >١٠؛ ٤×٢=٨ و٣×٢=٦ كلاهما <١٠.', explanation_en: '7×2=14, 8×2=16 both >10; 4×2=8, 3×2=6 both <10.' },
    { type: 'classify', q_ar: 'صنّف: الناتج زوجي / الناتج فردي.', q_en: 'Sort: even result / odd result.', categories_ar: ['الناتج زوجي', 'الناتج فردي'], categories_en: ['Even result', 'Odd result'], items_ar: [{ item: '١٦÷٢', correct_category: 0 }, { item: '١٢÷٢', correct_category: 0 }, { item: '١٤÷٢', correct_category: 0 }, { item: '١٠÷٢', correct_category: 0 }], items_en: [{ item: '16÷2=8', correct_category: 0 }, { item: '12÷2=6', correct_category: 0 }, { item: '14÷2=7', correct_category: 1 }, { item: '10÷2=5', correct_category: 1 }], explanation_ar: '٨ و٦ زوجي؛ ٧ و٥ فردي.', explanation_en: '8,6 even; 7,5 odd.' },
    { type: 'order', q_ar: 'رتّب الأعداد المفقودة تصاعديًا: __÷٢=٤، __÷٢=٦، __÷٢=٣.', q_en: 'Order missing numbers ascending: __÷2=4, __÷2=6, __÷2=3.', order_ar: ['٣×٢=٦', '٤×٢=٨', '٦×٢=١٢'], order_en: ['3×2=6', '4×2=8', '6×2=12'], explanation_ar: '٦ < ٨ < ١٢.', explanation_en: '6 < 8 < 12.' },
    { type: 'order', q_ar: 'رتّب النواتج تنازليًا: ١٦÷٢، ١٤÷٢، ١٢÷٢.', q_en: 'Order results descending: 16÷2, 14÷2, 12÷2.', order_ar: ['١٦÷٢=٨', '١٤÷٢=٧', '١٢÷٢=٦'], order_en: ['16÷2=8', '14÷2=7', '12÷2=6'], explanation_ar: '٨ > ٧ > ٦.', explanation_en: '8 > 7 > 6.' },
    { type: 'word', image: IMG_FLOWERS, q_ar: 'هل يمكن توزيع ٦ وردات في ٢ زهريتين بالتساوي؟ أوجد إجابتك.', q_en: 'Can 6 flowers go equally in 2 vases? Find answer.', answer_ar: 'نعم، ٦ ÷ ٢ = ٣ وردات في كل زهرية', answer_en: 'Yes, 6 ÷ 2 = 3 per vase', explanation_ar: 'الجبر: __ × ٢ = ٦، العدد المفقود = ٣.', explanation_en: 'Algebra: __ × 2 = 6, missing = 3.' },
    { type: 'word', q_ar: 'قسمت ريم ١٦ ÷ ٢ = ٨، أي المسائل التالية تتحقق من إجابتها؟', q_en: 'Reem solved 16÷2=8. Which verifies her answer?', answer_ar: '٨ × ٢ = ١٦', answer_en: '8 × 2 = 16', explanation_ar: 'نتحقق بالضرب العكسي.', explanation_en: 'Verify with inverse multiplication.' },
  ];
}

// 6-5 القسمة على 5
function LESSON_CH6_L5() {
  return [
    { type: 'mc', q_ar: 'دفع سامر ٣٠ ريالًا لشراء مجموعة من الألعاب المتماثلة، فإذا كان ثمن اللعبة ٥ ريالات، فكم لعبةً اشترى؟', q_en: 'Samer paid 30 for toys at 5 each. How many toys?', options_ar: ['٦', '٥', '٣٠', '٨'], options_en: ['6', '5', '30', '8'], correct: '0', explanation_ar: '٣٠ ÷ ٥ = ٦.', explanation_en: '30 ÷ 5 = 6.' },
    { type: 'mc', q_ar: '٤٥ ÷ ٥ = ؟', q_en: '45 ÷ 5 = ?', options_ar: ['٩', '٥', '٨', '١٠'], options_en: ['9', '5', '8', '10'], correct: '0', explanation_ar: '٩ × ٥ = ٤٥.', explanation_en: '9 × 5 = 45.' },
    { type: 'tf', q_ar: '٣٥ ÷ ٥ = ٧.', q_en: '35 ÷ 5 = 7.', options_ar: ['صح', 'خطأ'], options_en: ['True', 'False'], correct: '0', explanation_ar: '٧ × ٥ = ٣٥.', explanation_en: '7 × 5 = 35.' },
    { type: 'tf', q_ar: '٢٠ ÷ ٥ = ٣.', q_en: '20 ÷ 5 = 3.', options_ar: ['صح', 'خطأ'], options_en: ['True', 'False'], correct: '1', explanation_ar: '٢٠ ÷ ٥ = ٤.', explanation_en: '20 ÷ 5 = 4.' },
    { type: 'fill', q_ar: '٤٠ ÷ ٥ = __', q_en: '40 ÷ 5 = __', answer_ar: '٨', answer_en: '8', explanation_ar: '٨ × ٥ = ٤٠.', explanation_en: '8 × 5 = 40.' },
    { type: 'fill', q_ar: '٢٥ ÷ ٥ = __', q_en: '25 ÷ 5 = __', answer_ar: '٥', answer_en: '5', explanation_ar: '٥ × ٥ = ٢٥.', explanation_en: '5 × 5 = 25.' },
    { type: 'compute', q_ar: 'أوجد: ٥٠ ÷ ٥', q_en: 'Find: 50 ÷ 5', answer_ar: '١٠', answer_en: '10', explanation_ar: '١٠ × ٥ = ٥٠.', explanation_en: '10 × 5 = 50.' },
    { type: 'compute', q_ar: 'أوجد: ٥ ÷ ٥', q_en: 'Find: 5 ÷ 5', answer_ar: '١', answer_en: '1', explanation_ar: '١ × ٥ = ٥.', explanation_en: '1 × 5 = 5.' },
    { type: 'match', q_ar: 'صل جملة القسمة بناتجها.', q_en: 'Match division to result.', pairs_ar: [{ left: '٣٠ ÷ ٥', right: '٦' }, { left: '٤٥ ÷ ٥', right: '٩' }, { left: '٢٠ ÷ ٥', right: '٤' }], pairs_en: [{ left: '30÷5', right: '6' }, { left: '45÷5', right: '9' }, { left: '20÷5', right: '4' }], explanation_ar: 'استخدم الحقيقة المترابطة.', explanation_en: 'Use related fact.' },
    { type: 'match', q_ar: 'صل الحقيقة المترابطة لكل قسمة على ٥.', q_en: 'Match division to multiplication fact.', pairs_ar: [{ left: '٣٥ ÷ ٥ = ٧', right: '٥ × ٧ = ٣٥' }, { left: '٤٥ ÷ ٥ = ٩', right: '٥ × ٩ = ٤٥' }, { left: '٥٠ ÷ ٥ = ١٠', right: '٥ × ١٠ = ٥٠' }], pairs_en: [{ left: '35÷5=7', right: '5×7=35' }, { left: '45÷5=9', right: '5×9=45' }, { left: '50÷5=10', right: '5×10=50' }], explanation_ar: 'الضرب يتحقق من القسمة.', explanation_en: 'Multiplication verifies division.' },
    { type: 'classify', q_ar: 'صنّف: مقسوم على ٥ / ناتجه ٥.', q_en: 'Sort: divided by 5 / result is 5.', categories_ar: ['مقسوم على ٥', 'ناتجه ٥'], categories_en: ['÷5', 'Result=5'], items_ar: [{ item: '٣٠÷٥=٦', correct_category: 0 }, { item: '٤٥÷٥=٩', correct_category: 0 }, { item: '٢٥÷٥=٥', correct_category: 1 }, { item: '٥÷١=٥', correct_category: 1 }], items_en: [{ item: '30÷5=6', correct_category: 0 }, { item: '45÷5=9', correct_category: 0 }, { item: '25÷5=5', correct_category: 1 }, { item: '5÷1=5', correct_category: 1 }], explanation_ar: 'ميّز بين المقسوم عليه والناتج.', explanation_en: 'Distinguish divisor from result.' },
    { type: 'classify', q_ar: 'صنّف القسمة على ٥: ناتجه أقل من ٧ / ناتجه ٧ فأكثر.', q_en: 'Sort ÷5: result < 7 / result ≥ 7.', categories_ar: ['الناتج < ٧', 'الناتج ≥ ٧'], categories_en: ['Result < 7', 'Result ≥ 7'], items_ar: [{ item: '٢٥÷٥', correct_category: 0 }, { item: '٣٠÷٥', correct_category: 0 }, { item: '٣٥÷٥', correct_category: 1 }, { item: '٤٥÷٥', correct_category: 1 }], items_en: [{ item: '25÷5=5', correct_category: 0 }, { item: '30÷5=6', correct_category: 0 }, { item: '35÷5=7', correct_category: 1 }, { item: '45÷5=9', correct_category: 1 }], explanation_ar: '٥ و٦ < ٧؛ ٧ و٩ ≥ ٧.', explanation_en: '5,6 < 7; 7,9 ≥ 7.' },
    { type: 'order', q_ar: 'رتّب النواتج تصاعديًا: ٤٥÷٥، ٢٠÷٥، ٣٥÷٥، ٥÷٥.', q_en: 'Order results ascending: 45÷5, 20÷5, 35÷5, 5÷5.', order_ar: ['٥÷٥=١', '٢٠÷٥=٤', '٣٥÷٥=٧', '٤٥÷٥=٩'], order_en: ['5÷5=1', '20÷5=4', '35÷5=7', '45÷5=9'], explanation_ar: '١ < ٤ < ٧ < ٩.', explanation_en: '1 < 4 < 7 < 9.' },
    { type: 'order', q_ar: 'رتّب مضاعفات ٥ تصاعديًا: ٤٥، ٢٠، ٣٥، ٥.', q_en: 'Order multiples of 5 ascending: 45, 20, 35, 5.', order_ar: ['٥', '٢٠', '٣٥', '٤٥'], order_en: ['5', '20', '35', '45'], explanation_ar: '٥ < ٢٠ < ٣٥ < ٤٥.', explanation_en: '5 < 20 < 35 < 45.' },
    { type: 'word', image: IMG_PENCILS, q_ar: 'تبيع مكتبةٌ ٥ أقلام بـ ٤٥ ريالات، ثمن القلم ٥ ريالات؛ إذا كان لدى وليد ٤٥ ريالًا فكم قلمًا يستطيع شراءه؟', q_en: 'Store: pen costs 5 riyals. Walid has 45. How many pens?', answer_ar: '٩ أقلام', answer_en: '9 pens', explanation_ar: '٤٥ ÷ ٥ = ٩.', explanation_en: '45 ÷ 5 = 9.' },
    { type: 'word', q_ar: 'الدبّ الرمادي يجري ٥٥ كيلومترًا في الساعة. ما ناتج قسمة هذا العدد على ٥؟', q_en: 'Bear runs 55 km/h. Divide by 5?', answer_ar: '١١', answer_en: '11', explanation_ar: '٥٥ ÷ ٥ = ١١.', explanation_en: '55 ÷ 5 = 11.' },
  ];
}

// 6-6 القسمة على 10
function LESSON_CH6_L6() {
  return [
    { type: 'mc', q_ar: '٥٠ ÷ ١٠ = ؟', q_en: '50 ÷ 10 = ?', options_ar: ['٥', '١٠', '٤', '٨'], options_en: ['5', '10', '4', '8'], correct: '0', explanation_ar: '٥ × ١٠ = ٥٠.', explanation_en: '5 × 10 = 50.' },
    { type: 'mc', image: IMG_JUICE, q_ar: 'كم صندوقًا يحتاج طلاب الصف الثالث لحفلتهم إذا كان الصندوق المجاور يحوي ١٠ علب عصير واحتاجوا إلى ٥٠ علبة؟', q_en: 'Class needs 50 juice boxes, 10 per box. Boxes needed?', options_ar: ['٥', '١٠', '٥٠', '٤٠'], options_en: ['5', '10', '50', '40'], correct: '0', explanation_ar: '٥٠ ÷ ١٠ = ٥.', explanation_en: '50 ÷ 10 = 5.' },
    { type: 'tf', q_ar: '٩٠ ÷ ١٠ = ٩.', q_en: '90 ÷ 10 = 9.', options_ar: ['صح', 'خطأ'], options_en: ['True', 'False'], correct: '0', explanation_ar: '٩ × ١٠ = ٩٠.', explanation_en: '9 × 10 = 90.' },
    { type: 'tf', q_ar: '٧٠ ÷ ١٠ = ٨.', q_en: '70 ÷ 10 = 8.', options_ar: ['صح', 'خطأ'], options_en: ['True', 'False'], correct: '1', explanation_ar: '٧٠ ÷ ١٠ = ٧.', explanation_en: '70 ÷ 10 = 7.' },
    { type: 'fill', q_ar: '٨٠ ÷ ١٠ = __', q_en: '80 ÷ 10 = __', answer_ar: '٨', answer_en: '8', explanation_ar: '٨ × ١٠ = ٨٠.', explanation_en: '8 × 10 = 80.' },
    { type: 'fill', q_ar: '١٠٠ ÷ ١٠ = __', q_en: '100 ÷ 10 = __', answer_ar: '١٠', answer_en: '10', explanation_ar: '١٠ × ١٠ = ١٠٠.', explanation_en: '10 × 10 = 100.' },
    { type: 'compute', q_ar: 'أوجد: ٧٠ ÷ ١٠', q_en: 'Find: 70 ÷ 10', answer_ar: '٧', answer_en: '7', explanation_ar: '٧ × ١٠ = ٧٠.', explanation_en: '7 × 10 = 70.' },
    { type: 'compute', q_ar: 'أوجد: ٦٠ ÷ ١٠', q_en: 'Find: 60 ÷ 10', answer_ar: '٦', answer_en: '6', explanation_ar: '٦ × ١٠ = ٦٠.', explanation_en: '6 × 10 = 60.' },
    { type: 'match', q_ar: 'صل جملة القسمة بناتجها.', q_en: 'Match division to result.', pairs_ar: [{ left: '٥٠ ÷ ١٠', right: '٥' }, { left: '٩٠ ÷ ١٠', right: '٩' }, { left: '٣٠ ÷ ١٠', right: '٣' }], pairs_en: [{ left: '50÷10', right: '5' }, { left: '90÷10', right: '9' }, { left: '30÷10', right: '3' }], explanation_ar: 'كل عشرة تساوي واحدًا.', explanation_en: 'Every ten equals one.' },
    { type: 'match', q_ar: 'صل الحقيقة المترابطة.', q_en: 'Match related multiplication fact.', pairs_ar: [{ left: '٥٠ ÷ ١٠ = ٥', right: '١٠ × ٥ = ٥٠' }, { left: '٨٠ ÷ ١٠ = ٨', right: '١٠ × ٨ = ٨٠' }, { left: '١٠٠ ÷ ١٠ = ١٠', right: '١٠ × ١٠ = ١٠٠' }], pairs_en: [{ left: '50÷10=5', right: '10×5=50' }, { left: '80÷10=8', right: '10×8=80' }, { left: '100÷10=10', right: '10×10=100' }], explanation_ar: 'الحقائق المترابطة تساعد في التحقق.', explanation_en: 'Related facts help verify.' },
    { type: 'classify', q_ar: 'صنّف نواتج القسمة على ١٠: زوجي / فردي.', q_en: 'Sort ÷10 results: even / odd.', categories_ar: ['ناتج زوجي', 'ناتج فردي'], categories_en: ['Even result', 'Odd result'], items_ar: [{ item: '٨٠÷١٠=٨', correct_category: 0 }, { item: '٦٠÷١٠=٦', correct_category: 0 }, { item: '٧٠÷١٠=٧', correct_category: 1 }, { item: '٥٠÷١٠=٥', correct_category: 1 }], items_en: [{ item: '80÷10=8', correct_category: 0 }, { item: '60÷10=6', correct_category: 0 }, { item: '70÷10=7', correct_category: 1 }, { item: '50÷10=5', correct_category: 1 }], explanation_ar: '٨ و٦ زوجيان؛ ٧ و٥ فرديان.', explanation_en: '8,6 even; 7,5 odd.' },
    { type: 'classify', q_ar: 'صنّف: ناتج القسمة على ١٠ أكبر من ٥ / أصغر.', q_en: 'Sort ÷10: result > 5 / ≤ 5.', categories_ar: ['الناتج > ٥', 'الناتج ≤ ٥'], categories_en: ['Result > 5', 'Result ≤ 5'], items_ar: [{ item: '٩٠÷١٠', correct_category: 0 }, { item: '٨٠÷١٠', correct_category: 0 }, { item: '٥٠÷١٠', correct_category: 1 }, { item: '٤٠÷١٠', correct_category: 1 }], items_en: [{ item: '90÷10=9', correct_category: 0 }, { item: '80÷10=8', correct_category: 0 }, { item: '50÷10=5', correct_category: 1 }, { item: '40÷10=4', correct_category: 1 }], explanation_ar: '٩ و٨ > ٥؛ ٥ و٤ ≤ ٥.', explanation_en: '9,8 > 5; 5,4 ≤ 5.' },
    { type: 'order', q_ar: 'رتّب النواتج تصاعديًا: ٩٠÷١٠، ٥٠÷١٠، ٧٠÷١٠، ٣٠÷١٠.', q_en: 'Order results ascending: 90÷10, 50÷10, 70÷10, 30÷10.', order_ar: ['٣٠÷١٠=٣', '٥٠÷١٠=٥', '٧٠÷١٠=٧', '٩٠÷١٠=٩'], order_en: ['30÷10=3', '50÷10=5', '70÷10=7', '90÷10=9'], explanation_ar: '٣ < ٥ < ٧ < ٩.', explanation_en: '3 < 5 < 7 < 9.' },
    { type: 'order', q_ar: 'رتّب مضاعفات ١٠ تنازليًا: ٩٠، ٤٠، ٧٠، ٥٠.', q_en: 'Order multiples of 10 descending: 90,40,70,50.', order_ar: ['٩٠', '٧٠', '٥٠', '٤٠'], order_en: ['90', '70', '50', '40'], explanation_ar: '٩٠ > ٧٠ > ٥٠ > ٤٠.', explanation_en: '90 > 70 > 50 > 40.' },
    { type: 'word', image: IMG_JUICE, q_ar: 'دفع عمر ٤٠ ريالًا لشراء علب العصير، فإذا كانت الصناديق من فئة ١٠ علب بثمن ٤٠ ريالًا لكل صندوق، فكم علبةً اشترى؟', q_en: 'Omar paid 40 for juice boxes at 10 each box. Boxes bought?', answer_ar: '٤ صناديق × ١٠ = ٤٠ علبة', answer_en: '4 boxes × 10 = 40 boxes', explanation_ar: '٤٠ ÷ ١٠ = ٤.', explanation_en: '40 ÷ 10 = 4.' },
    { type: 'word', image: IMG_JUICE, q_ar: 'إذا كان الصندوق المجاور يحوي ١٠ عُلَب وبثمن ٤٠ ريالًا لعُلبة الحليب الواحدة، فكم تكلفة شراء عُلبة واحدة؟', q_en: 'Box of 10 milk cans costs 40 riyals. Cost per can?', answer_ar: '٤ ريالات', answer_en: '4 riyals', explanation_ar: '٤٠ ÷ ١٠ = ٤.', explanation_en: '40 ÷ 10 = 4.' },
  ];
}

// 6-7 القسمة مع الصفر وعلى الواحد
function LESSON_CH6_L7() {
  return [
    { type: 'mc', q_ar: '٥ ÷ ١ = ؟', q_en: '5 ÷ 1 = ?', options_ar: ['٥', '١', '٠', '٦'], options_en: ['5', '1', '0', '6'], correct: '0', explanation_ar: 'أي عدد ÷ ١ = العدد نفسه.', explanation_en: 'Any number ÷ 1 = the same number.' },
    { type: 'mc', q_ar: '٠ ÷ ٧ = ؟', q_en: '0 ÷ 7 = ?', options_ar: ['٠', '٧', '١', 'غير محدد'], options_en: ['0', '7', '1', 'undefined'], correct: '0', explanation_ar: 'الصفر ÷ أي عدد (غير صفر) = ٠.', explanation_en: 'Zero ÷ any nonzero = 0.' },
    { type: 'tf', q_ar: '٩ ÷ ١ = ٩.', q_en: '9 ÷ 1 = 9.', options_ar: ['صح', 'خطأ'], options_en: ['True', 'False'], correct: '0', explanation_ar: 'أي عدد ÷ ١ = نفسه.', explanation_en: 'Any number ÷ 1 = itself.' },
    { type: 'tf', q_ar: '٠ ÷ ٠ = ١.', q_en: '0 ÷ 0 = 1.', options_ar: ['صح', 'خطأ'], options_en: ['True', 'False'], correct: '1', explanation_ar: 'القسمة على الصفر غير مُعرَّفة.', explanation_en: 'Division by zero is undefined.' },
    { type: 'fill', q_ar: '٤ ÷ ٤ = __', q_en: '4 ÷ 4 = __', answer_ar: '١', answer_en: '1', explanation_ar: 'أي عدد ÷ نفسه = ١.', explanation_en: 'Any number ÷ itself = 1.' },
    { type: 'fill', q_ar: '٠ ÷ ٥ = __', q_en: '0 ÷ 5 = __', answer_ar: '٠', answer_en: '0', explanation_ar: 'الصفر ÷ أي عدد = ٠.', explanation_en: 'Zero ÷ any = 0.' },
    { type: 'compute', q_ar: 'أوجد: ١٠ ÷ ١', q_en: 'Find: 10 ÷ 1', answer_ar: '١٠', answer_en: '10', explanation_ar: '١٠ ÷ ١ = ١٠.', explanation_en: '10 ÷ 1 = 10.' },
    { type: 'compute', q_ar: 'هل يمكن القسمة على الصفر؟', q_en: 'Can we divide by zero?', answer_ar: 'لا، القسمة على الصفر غير مُعرَّفة', answer_en: 'No, undefined', explanation_ar: 'من قواعد القسمة: لا يمكن القسمة على الصفر.', explanation_en: 'Rule: division by zero is undefined.' },
    { type: 'match', q_ar: 'صل التعبير بناتجه.', q_en: 'Match expression to result.', pairs_ar: [{ left: '٩ ÷ ١', right: '٩' }, { left: '٠ ÷ ٦', right: '٠' }, { left: '٥ ÷ ٥', right: '١' }], pairs_en: [{ left: '9÷1', right: '9' }, { left: '0÷6', right: '0' }, { left: '5÷5', right: '1' }], explanation_ar: 'قواعد القسمة الثلاث.', explanation_en: 'Three division rules.' },
    { type: 'match', q_ar: 'صل القاعدة بمثالها.', q_en: 'Match rule to example.', pairs_ar: [{ left: 'عدد ÷ ١ = العدد', right: '٧ ÷ ١ = ٧' }, { left: '٠ ÷ عدد = ٠', right: '٠ ÷ ٩ = ٠' }, { left: 'عدد ÷ نفسه = ١', right: '٦ ÷ ٦ = ١' }], pairs_en: [{ left: 'n÷1=n', right: '7÷1=7' }, { left: '0÷n=0', right: '0÷9=0' }, { left: 'n÷n=1', right: '6÷6=1' }], explanation_ar: 'كل قاعدة لها مثالها.', explanation_en: 'Each rule has its example.' },
    { type: 'classify', q_ar: 'صنّف: ناتجه صفر / ناتجه واحد / ناتجه العدد نفسه.', q_en: 'Sort: result is 0 / 1 / the number.', categories_ar: ['ناتجه ٠', 'ناتجه ١', 'ناتجه العدد نفسه'], categories_en: ['Result=0', 'Result=1', 'Result=number'], items_ar: [{ item: '٠÷٨', correct_category: 0 }, { item: '٨÷٨', correct_category: 1 }, { item: '٨÷١', correct_category: 2 }, { item: '٠÷٤', correct_category: 0 }], items_en: [{ item: '0÷8', correct_category: 0 }, { item: '8÷8', correct_category: 1 }, { item: '8÷1', correct_category: 2 }, { item: '0÷4', correct_category: 0 }], explanation_ar: '٠÷n=٠، n÷n=١، n÷١=n.', explanation_en: '0÷n=0, n÷n=1, n÷1=n.' },
    { type: 'classify', q_ar: 'صنّف: يمكن حسابه / لا يمكن حسابه.', q_en: 'Sort: can be computed / cannot.', categories_ar: ['يمكن حسابه', 'لا يمكن حسابه'], categories_en: ['Can compute', 'Cannot'], items_ar: [{ item: '٧÷١', correct_category: 0 }, { item: '٠÷٧', correct_category: 0 }, { item: '٤÷٠', correct_category: 1 }, { item: '٠÷٠', correct_category: 1 }], items_en: [{ item: '7÷1', correct_category: 0 }, { item: '0÷7', correct_category: 0 }, { item: '4÷0', correct_category: 1 }, { item: '0÷0', correct_category: 1 }], explanation_ar: 'القسمة على الصفر غير ممكنة.', explanation_en: 'Division by zero is impossible.' },
    { type: 'order', q_ar: 'رتّب النواتج: ٨÷١، ٠÷٨، ٨÷٨.', q_en: 'Order results: 8÷1, 0÷8, 8÷8.', order_ar: ['٠÷٨=٠', '٨÷٨=١', '٨÷١=٨'], order_en: ['0÷8=0', '8÷8=1', '8÷1=8'], explanation_ar: '٠ < ١ < ٨.', explanation_en: '0 < 1 < 8.' },
    { type: 'order', q_ar: 'رتّب تنازليًا: ٩÷١، ٩÷٩، ٠÷٩.', q_en: 'Order descending: 9÷1, 9÷9, 0÷9.', order_ar: ['٩÷١=٩', '٩÷٩=١', '٠÷٩=٠'], order_en: ['9÷1=9', '9÷9=1', '0÷9=0'], explanation_ar: '٩ > ١ > ٠.', explanation_en: '9 > 1 > 0.' },
    { type: 'word', q_ar: 'احتضرت القاعة ٦ أشخاص وكانت هناك ٦ مقاعد خالية، فما عدد المقاعد التي خُصِّصت لكل شخص؟', q_en: '6 people, 6 chairs. Chairs per person?', answer_ar: '١ مقعد لكل شخص (٦ ÷ ٦ = ١)', answer_en: '1 chair each (6÷6=1)', explanation_ar: 'عدد ÷ نفسه = ١.', explanation_en: 'n ÷ n = 1.' },
    { type: 'word', image: IMG_JUICE, q_ar: 'لدى سعيد ٥ أكواب من العصير، سيوزّعها على ٤ أصدقائه وحارس، إذا وُزِّعت بالتساوي فكم كوبًا يأخذ كل واحد منهم؟', q_en: 'Saeed has 5 cups, divided among 4 friends + 1 guard = 5 people. Per person?', answer_ar: '١ كوب لكل شخص (٥ ÷ ٥ = ١)', answer_en: '1 cup each (5÷5=1)', explanation_ar: '٥ ÷ ٥ = ١.', explanation_en: '5 ÷ 5 = 1.' },
  ];
}

// ===== الفصل السابع: القسمة (٢) =====

// 7-1 القسمة على 3 وعلى 4
function LESSON_CH7_L1() {
  return [
    { type: 'mc', image: IMG_APPLES, q_ar: '٢٤ ÷ ٣ = ؟', q_en: '24 ÷ 3 = ?', options_ar: ['٨', '٣', '٢٤', '٦'], options_en: ['8', '3', '24', '6'], correct: '0', explanation_ar: '٨ × ٣ = ٢٤.', explanation_en: '8 × 3 = 24.' },
    { type: 'mc', q_ar: '٢٠ ÷ ٤ = ؟', q_en: '20 ÷ 4 = ?', options_ar: ['٥', '٤', '٢٠', '٨'], options_en: ['5', '4', '20', '8'], correct: '0', explanation_ar: '٥ × ٤ = ٢٠.', explanation_en: '5 × 4 = 20.' },
    { type: 'tf', q_ar: '٢١ ÷ ٣ = ٧.', q_en: '21 ÷ 3 = 7.', options_ar: ['صح', 'خطأ'], options_en: ['True', 'False'], correct: '0', explanation_ar: '٧ × ٣ = ٢١.', explanation_en: '7 × 3 = 21.' },
    { type: 'tf', q_ar: '٢٤ ÷ ٤ = ٥.', q_en: '24 ÷ 4 = 5.', options_ar: ['صح', 'خطأ'], options_en: ['True', 'False'], correct: '1', explanation_ar: '٢٤ ÷ ٤ = ٦.', explanation_en: '24 ÷ 4 = 6.' },
    { type: 'fill', q_ar: '١٢ ÷ ٣ = __', q_en: '12 ÷ 3 = __', answer_ar: '٤', answer_en: '4', explanation_ar: '٤ × ٣ = ١٢.', explanation_en: '4 × 3 = 12.' },
    { type: 'fill', q_ar: '١٦ ÷ ٤ = __', q_en: '16 ÷ 4 = __', answer_ar: '٤', answer_en: '4', explanation_ar: '٤ × ٤ = ١٦.', explanation_en: '4 × 4 = 16.' },
    { type: 'compute', q_ar: 'أوجد: ٢٧ ÷ ٣', q_en: 'Find: 27 ÷ 3', answer_ar: '٩', answer_en: '9', explanation_ar: '٩ × ٣ = ٢٧.', explanation_en: '9 × 3 = 27.' },
    { type: 'compute', q_ar: 'أوجد: ٢٨ ÷ ٤', q_en: 'Find: 28 ÷ 4', answer_ar: '٧', answer_en: '7', explanation_ar: '٧ × ٤ = ٢٨.', explanation_en: '7 × 4 = 28.' },
    { type: 'match', q_ar: 'صل جملة القسمة بناتجها.', q_en: 'Match division to result.', pairs_ar: [{ left: '٢٤ ÷ ٣', right: '٨' }, { left: '٢٤ ÷ ٤', right: '٦' }, { left: '٢٧ ÷ ٣', right: '٩' }], pairs_en: [{ left: '24÷3', right: '8' }, { left: '24÷4', right: '6' }, { left: '27÷3', right: '9' }], explanation_ar: 'استخدم الحقائق المترابطة.', explanation_en: 'Use related facts.' },
    { type: 'match', q_ar: 'صل الحقيقة المترابطة.', q_en: 'Match related multiplication.', pairs_ar: [{ left: '٢١ ÷ ٣ = ٧', right: '٣ × ٧ = ٢١' }, { left: '٢٠ ÷ ٤ = ٥', right: '٤ × ٥ = ٢٠' }, { left: '٢٨ ÷ ٤ = ٧', right: '٤ × ٧ = ٢٨' }], pairs_en: [{ left: '21÷3=7', right: '3×7=21' }, { left: '20÷4=5', right: '4×5=20' }, { left: '28÷4=7', right: '4×7=28' }], explanation_ar: 'الضرب والقسمة معكوسان.', explanation_en: 'Multiplication and division are inverse.' },
    { type: 'classify', q_ar: 'صنّف: مقسوم على ٣ / مقسوم على ٤.', q_en: 'Sort: ÷3 / ÷4.', categories_ar: ['مقسوم على ٣', 'مقسوم على ٤'], categories_en: ['÷3', '÷4'], items_ar: [{ item: '٢١÷٣', correct_category: 0 }, { item: '٢٧÷٣', correct_category: 0 }, { item: '٢٠÷٤', correct_category: 1 }, { item: '٢٨÷٤', correct_category: 1 }], items_en: [{ item: '21÷3', correct_category: 0 }, { item: '27÷3', correct_category: 0 }, { item: '20÷4', correct_category: 1 }, { item: '28÷4', correct_category: 1 }], explanation_ar: 'انظر المقسوم عليه.', explanation_en: 'Look at the divisor.' },
    { type: 'classify', q_ar: 'صنّف: ناتج القسمة أكبر من ٦ / أصغر.', q_en: 'Sort: result > 6 / ≤ 6.', categories_ar: ['الناتج > ٦', 'الناتج ≤ ٦'], categories_en: ['Result > 6', 'Result ≤ 6'], items_ar: [{ item: '٢٤÷٣=٨', correct_category: 0 }, { item: '٢٧÷٣=٩', correct_category: 0 }, { item: '٢١÷٣=٧', correct_category: 0 }, { item: '١٢÷٣=٤', correct_category: 1 }], items_en: [{ item: '24÷3=8', correct_category: 0 }, { item: '27÷3=9', correct_category: 0 }, { item: '21÷3=7', correct_category: 0 }, { item: '12÷3=4', correct_category: 1 }], explanation_ar: '٨، ٩، ٧ > ٦؛ ٤ ≤ ٦.', explanation_en: '8,9,7 > 6; 4 ≤ 6.' },
    { type: 'order', q_ar: 'رتّب النواتج تصاعديًا: ٢٧÷٣، ١٢÷٣، ٢١÷٣.', q_en: 'Order ascending: 27÷3, 12÷3, 21÷3.', order_ar: ['١٢÷٣=٤', '٢١÷٣=٧', '٢٧÷٣=٩'], order_en: ['12÷3=4', '21÷3=7', '27÷3=9'], explanation_ar: '٤ < ٧ < ٩.', explanation_en: '4 < 7 < 9.' },
    { type: 'order', q_ar: 'رتّب مضاعفات ٤ تصاعديًا: ٢٤، ١٢، ٢٠، ٢٨.', q_en: 'Order multiples of 4 ascending: 24,12,20,28.', order_ar: ['١٢', '٢٠', '٢٤', '٢٨'], order_en: ['12', '20', '24', '28'], explanation_ar: '١٢ < ٢٠ < ٢٤ < ٢٨.', explanation_en: '12 < 20 < 24 < 28.' },
    { type: 'word', q_ar: 'مع محمد وعلي وحسن ٢٤ لُعبة، وكان كلٌّ منهم معه مثلُها، فكم لُعبةً مع كل واحد منهم؟', q_en: 'Mohammad, Ali, Hassan have 24 toys equal. Each has?', answer_ar: '٨ لُعب', answer_en: '8 toys', explanation_ar: '٢٤ ÷ ٣ = ٨.', explanation_en: '24 ÷ 3 = 8.' },
    { type: 'word', q_ar: 'يريد أحمد توزيع ٢٠ ريالًا على ٤ أشخاص بالتساوي. كم نصيب كل شخص؟', q_en: 'Ahmad divides 20 riyals among 4 equally. Per person?', answer_ar: '٥ ريالات', answer_en: '5 riyals', explanation_ar: '٢٠ ÷ ٤ = ٥.', explanation_en: '20 ÷ 4 = 5.' },
  ];
}

// 7-2 القسمة على 6 وعلى 7
function LESSON_CH7_L2() {
  return [
    { type: 'mc', q_ar: '٤٢ ÷ ٦ = ؟', q_en: '42 ÷ 6 = ?', options_ar: ['٧', '٦', '٨', '٩'], options_en: ['7', '6', '8', '9'], correct: '0', explanation_ar: '٧ × ٦ = ٤٢.', explanation_en: '7 × 6 = 42.' },
    { type: 'mc', q_ar: '٤٩ ÷ ٧ = ؟', q_en: '49 ÷ 7 = ?', options_ar: ['٧', '٦', '٨', '٥'], options_en: ['7', '6', '8', '5'], correct: '0', explanation_ar: '٧ × ٧ = ٤٩.', explanation_en: '7 × 7 = 49.' },
    { type: 'tf', q_ar: '٣٦ ÷ ٦ = ٦.', q_en: '36 ÷ 6 = 6.', options_ar: ['صح', 'خطأ'], options_en: ['True', 'False'], correct: '0', explanation_ar: '٦ × ٦ = ٣٦.', explanation_en: '6 × 6 = 36.' },
    { type: 'tf', q_ar: '٥٦ ÷ ٧ = ٩.', q_en: '56 ÷ 7 = 9.', options_ar: ['صح', 'خطأ'], options_en: ['True', 'False'], correct: '1', explanation_ar: '٥٦ ÷ ٧ = ٨.', explanation_en: '56 ÷ 7 = 8.' },
    { type: 'fill', q_ar: '٥٤ ÷ ٦ = __', q_en: '54 ÷ 6 = __', answer_ar: '٩', answer_en: '9', explanation_ar: '٩ × ٦ = ٥٤.', explanation_en: '9 × 6 = 54.' },
    { type: 'fill', q_ar: '٦٣ ÷ ٧ = __', q_en: '63 ÷ 7 = __', answer_ar: '٩', answer_en: '9', explanation_ar: '٩ × ٧ = ٦٣.', explanation_en: '9 × 7 = 63.' },
    { type: 'compute', q_ar: 'أوجد: ٤٨ ÷ ٦', q_en: 'Find: 48 ÷ 6', answer_ar: '٨', answer_en: '8', explanation_ar: '٨ × ٦ = ٤٨.', explanation_en: '8 × 6 = 48.' },
    { type: 'compute', q_ar: 'أوجد: ٣٥ ÷ ٧', q_en: 'Find: 35 ÷ 7', answer_ar: '٥', answer_en: '5', explanation_ar: '٥ × ٧ = ٣٥.', explanation_en: '5 × 7 = 35.' },
    { type: 'match', q_ar: 'صل جملة القسمة بناتجها.', q_en: 'Match division to result.', pairs_ar: [{ left: '٤٢ ÷ ٦', right: '٧' }, { left: '٤٩ ÷ ٧', right: '٧' }, { left: '٥٤ ÷ ٦', right: '٩' }], pairs_en: [{ left: '42÷6', right: '7' }, { left: '49÷7', right: '7' }, { left: '54÷6', right: '9' }], explanation_ar: 'استخدم الحقائق المترابطة.', explanation_en: 'Use related facts.' },
    { type: 'match', q_ar: 'صل الحقيقة المترابطة.', q_en: 'Match related fact.', pairs_ar: [{ left: '٣٦ ÷ ٦ = ٦', right: '٦ × ٦ = ٣٦' }, { left: '٦٣ ÷ ٧ = ٩', right: '٧ × ٩ = ٦٣' }, { left: '٤٨ ÷ ٦ = ٨', right: '٦ × ٨ = ٤٨' }], pairs_en: [{ left: '36÷6=6', right: '6×6=36' }, { left: '63÷7=9', right: '7×9=63' }, { left: '48÷6=8', right: '6×8=48' }], explanation_ar: 'الضرب يتحقق من القسمة.', explanation_en: 'Multiplication verifies division.' },
    { type: 'classify', q_ar: 'صنّف: مقسوم على ٦ / مقسوم على ٧.', q_en: 'Sort: ÷6 / ÷7.', categories_ar: ['÷٦', '÷٧'], categories_en: ['÷6', '÷7'], items_ar: [{ item: '٣٦÷٦', correct_category: 0 }, { item: '٤٨÷٦', correct_category: 0 }, { item: '٤٩÷٧', correct_category: 1 }, { item: '٦٣÷٧', correct_category: 1 }], items_en: [{ item: '36÷6', correct_category: 0 }, { item: '48÷6', correct_category: 0 }, { item: '49÷7', correct_category: 1 }, { item: '63÷7', correct_category: 1 }], explanation_ar: 'انظر المقسوم عليه.', explanation_en: 'Look at divisor.' },
    { type: 'classify', q_ar: 'صنّف: ناتجه ٧ / ناتجه غير ٧.', q_en: 'Sort: result=7 / result≠7.', categories_ar: ['الناتج ٧', 'الناتج ≠ ٧'], categories_en: ['Result=7', 'Result≠7'], items_ar: [{ item: '٤٢÷٦=٧', correct_category: 0 }, { item: '٤٩÷٧=٧', correct_category: 0 }, { item: '٣٦÷٦=٦', correct_category: 1 }, { item: '٦٣÷٧=٩', correct_category: 1 }], items_en: [{ item: '42÷6=7', correct_category: 0 }, { item: '49÷7=7', correct_category: 0 }, { item: '36÷6=6', correct_category: 1 }, { item: '63÷7=9', correct_category: 1 }], explanation_ar: '٤٢÷٦=٧ و٤٩÷٧=٧؛ ٣٦÷٦=٦ و٦٣÷٧=٩.', explanation_en: '42÷6=7, 49÷7=7; 36÷6=6, 63÷7=9.' },
    { type: 'order', q_ar: 'رتّب النواتج تصاعديًا: ٣٦÷٦، ٤٩÷٧، ٦٣÷٧.', q_en: 'Order results ascending: 36÷6, 49÷7, 63÷7.', order_ar: ['٣٦÷٦=٦', '٤٩÷٧=٧', '٦٣÷٧=٩'], order_en: ['36÷6=6', '49÷7=7', '63÷7=9'], explanation_ar: '٦ < ٧ < ٩.', explanation_en: '6 < 7 < 9.' },
    { type: 'order', q_ar: 'رتّب مضاعفات ٦ تصاعديًا: ٤٢، ٣٦، ٥٤، ٤٨.', q_en: 'Order multiples of 6 ascending: 42,36,54,48.', order_ar: ['٣٦', '٤٢', '٤٨', '٥٤'], order_en: ['36', '42', '48', '54'], explanation_ar: '٣٦ < ٤٢ < ٤٨ < ٥٤.', explanation_en: '36 < 42 < 48 < 54.' },
    { type: 'word', q_ar: 'كتلة فرخ النعام ٤ كيلوجرامات؛ إذا كان مجموع كتلة الأفراخ في العش ٢٨ كيلوجرامًا، فعدد الأفراخ في العش =؟', q_en: 'Ostrich chick: 4 kg each, total 28 kg in nest. Chicks?', answer_ar: '٧ أفراخ', answer_en: '7 chicks', explanation_ar: '٢٨ ÷ ٤ = ٧.', explanation_en: '28 ÷ 4 = 7.' },
    { type: 'word', image: IMG_OLIVE, q_ar: 'زرع محمود ١٤ شجرة زيتون في صفّين متساويين؛ كم شجرةً زُرِعت في الصف الواحد؟', q_en: 'Mahmoud planted 14 olive trees in 2 equal rows. Per row?', answer_ar: '٧ أشجار', answer_en: '7 trees', explanation_ar: '١٤ ÷ ٢ = ٧.', explanation_en: '14 ÷ 2 = 7.' },
  ];
}

// 7-3 القسمة على 8 وعلى 9
function LESSON_CH7_L3() {
  return [
    { type: 'mc', q_ar: '٧٢ ÷ ٨ = ؟', q_en: '72 ÷ 8 = ?', options_ar: ['٩', '٨', '٧', '١٠'], options_en: ['9', '8', '7', '10'], correct: '0', explanation_ar: '٩ × ٨ = ٧٢.', explanation_en: '9 × 8 = 72.' },
    { type: 'mc', q_ar: '٦٣ ÷ ٩ = ؟', q_en: '63 ÷ 9 = ?', options_ar: ['٧', '٩', '٦', '٨'], options_en: ['7', '9', '6', '8'], correct: '0', explanation_ar: '٧ × ٩ = ٦٣.', explanation_en: '7 × 9 = 63.' },
    { type: 'tf', q_ar: '٦٤ ÷ ٨ = ٨.', q_en: '64 ÷ 8 = 8.', options_ar: ['صح', 'خطأ'], options_en: ['True', 'False'], correct: '0', explanation_ar: '٨ × ٨ = ٦٤.', explanation_en: '8 × 8 = 64.' },
    { type: 'tf', q_ar: '٨١ ÷ ٩ = ٨.', q_en: '81 ÷ 9 = 8.', options_ar: ['صح', 'خطأ'], options_en: ['True', 'False'], correct: '1', explanation_ar: '٨١ ÷ ٩ = ٩.', explanation_en: '81 ÷ 9 = 9.' },
    { type: 'fill', q_ar: '٥٦ ÷ ٨ = __', q_en: '56 ÷ 8 = __', answer_ar: '٧', answer_en: '7', explanation_ar: '٧ × ٨ = ٥٦.', explanation_en: '7 × 8 = 56.' },
    { type: 'fill', q_ar: '٤٥ ÷ ٩ = __', q_en: '45 ÷ 9 = __', answer_ar: '٥', answer_en: '5', explanation_ar: '٥ × ٩ = ٤٥.', explanation_en: '5 × 9 = 45.' },
    { type: 'compute', q_ar: 'أوجد: ٤٨ ÷ ٨', q_en: 'Find: 48 ÷ 8', answer_ar: '٦', answer_en: '6', explanation_ar: '٦ × ٨ = ٤٨.', explanation_en: '6 × 8 = 48.' },
    { type: 'compute', q_ar: 'أوجد: ٧٢ ÷ ٩', q_en: 'Find: 72 ÷ 9', answer_ar: '٨', answer_en: '8', explanation_ar: '٨ × ٩ = ٧٢.', explanation_en: '8 × 9 = 72.' },
    { type: 'match', q_ar: 'صل جملة القسمة بناتجها.', q_en: 'Match division to result.', pairs_ar: [{ left: '٧٢ ÷ ٨', right: '٩' }, { left: '٦٣ ÷ ٩', right: '٧' }, { left: '٤٨ ÷ ٨', right: '٦' }], pairs_en: [{ left: '72÷8', right: '9' }, { left: '63÷9', right: '7' }, { left: '48÷8', right: '6' }], explanation_ar: 'استخدم الحقائق المترابطة.', explanation_en: 'Use related facts.' },
    { type: 'match', q_ar: 'صل الحقيقة المترابطة.', q_en: 'Match related multiplication.', pairs_ar: [{ left: '٦٤ ÷ ٨ = ٨', right: '٨ × ٨ = ٦٤' }, { left: '٨١ ÷ ٩ = ٩', right: '٩ × ٩ = ٨١' }, { left: '٧٢ ÷ ٨ = ٩', right: '٨ × ٩ = ٧٢' }], pairs_en: [{ left: '64÷8=8', right: '8×8=64' }, { left: '81÷9=9', right: '9×9=81' }, { left: '72÷8=9', right: '8×9=72' }], explanation_ar: 'الحقائق المترابطة.', explanation_en: 'Related facts.' },
    { type: 'classify', q_ar: 'صنّف: مقسوم على ٨ / مقسوم على ٩.', q_en: 'Sort: ÷8 / ÷9.', categories_ar: ['÷٨', '÷٩'], categories_en: ['÷8', '÷9'], items_ar: [{ item: '٦٤÷٨', correct_category: 0 }, { item: '٧٢÷٨', correct_category: 0 }, { item: '٨١÷٩', correct_category: 1 }, { item: '٦٣÷٩', correct_category: 1 }], items_en: [{ item: '64÷8', correct_category: 0 }, { item: '72÷8', correct_category: 0 }, { item: '81÷9', correct_category: 1 }, { item: '63÷9', correct_category: 1 }], explanation_ar: 'انظر المقسوم عليه.', explanation_en: 'Look at divisor.' },
    { type: 'classify', q_ar: 'صنّف: ناتجه ٩ / ناتجه أقل من ٩.', q_en: 'Sort: result=9 / result<9.', categories_ar: ['الناتج ٩', 'الناتج < ٩'], categories_en: ['Result=9', 'Result<9'], items_ar: [{ item: '٧٢÷٨=٩', correct_category: 0 }, { item: '٨١÷٩=٩', correct_category: 0 }, { item: '٦٣÷٩=٧', correct_category: 1 }, { item: '٤٨÷٨=٦', correct_category: 1 }], items_en: [{ item: '72÷8=9', correct_category: 0 }, { item: '81÷9=9', correct_category: 0 }, { item: '63÷9=7', correct_category: 1 }, { item: '48÷8=6', correct_category: 1 }], explanation_ar: '٧٢÷٨=٩ و٨١÷٩=٩؛ ٦٣÷٩=٧ و٤٨÷٨=٦.', explanation_en: '72÷8=9, 81÷9=9; 63÷9=7, 48÷8=6.' },
    { type: 'order', q_ar: 'رتّب النواتج تصاعديًا: ٤٥÷٩، ٦٣÷٩، ٨١÷٩.', q_en: 'Order ascending: 45÷9, 63÷9, 81÷9.', order_ar: ['٤٥÷٩=٥', '٦٣÷٩=٧', '٨١÷٩=٩'], order_en: ['45÷9=5', '63÷9=7', '81÷9=9'], explanation_ar: '٥ < ٧ < ٩.', explanation_en: '5 < 7 < 9.' },
    { type: 'order', q_ar: 'رتّب مضاعفات ٨ تصاعديًا: ٦٤، ٤٨، ٧٢، ٥٦.', q_en: 'Order multiples of 8 ascending: 64,48,72,56.', order_ar: ['٤٨', '٥٦', '٦٤', '٧٢'], order_en: ['48', '56', '64', '72'], explanation_ar: '٤٨ < ٥٦ < ٦٤ < ٧٢.', explanation_en: '48 < 56 < 64 < 72.' },
    { type: 'word', image: IMG_FLOWERS, q_ar: 'قسمت مريم الزهور على صفوف بنفس العدد. إذا كانت لديها ٤٠ زهرة وصنعت ٥ إسوارات، فكم زهرة في كل إسوارة؟', q_en: 'Mariam made 5 bracelets from 40 flowers equally. Per bracelet?', answer_ar: '٨ زهرات', answer_en: '8 flowers', explanation_ar: '٤٠ ÷ ٥ = ٨.', explanation_en: '40 ÷ 5 = 8.' },
    { type: 'word', q_ar: 'يوجد ٤٠ لاعبًا يُوزَّعون على ٨ فرق. كم لاعبًا في كل فريق؟', q_en: '40 players on 8 teams. Per team?', answer_ar: '٥ لاعبين', answer_en: '5 players', explanation_ar: '٤٠ ÷ ٨ = ٥.', explanation_en: '40 ÷ 8 = 5.' },
  ];
}

// ===== هيكل الفصول =====
export const MATH3_S2_DIVISION_CHAPTERS = [
  {
    id: 'ch6',
    title_ar: 'الفصل السادس: القسمة (١)',
    title_en: 'Chapter 6: Division (1)',
    color: '#16a34a',
    lessons: [
      { id: 'ch6-l1', title_ar: 'القسمة بالطرح المتكرر', title_en: 'Division by Repeated Subtraction', questions: LESSON_CH6_L1() },
      { id: 'ch6-l2', title_ar: 'الحقائق المترابطة', title_en: 'Related Facts', questions: LESSON_CH6_L2() },
      { id: 'ch6-l3', title_ar: 'أحل المسألة: العملية المناسبة', title_en: 'Problem Solving: Choose Operation', questions: LESSON_CH6_L3() },
      { id: 'ch6-l4', title_ar: 'الجبر: العدد المفقود', title_en: 'Algebra: Missing Number', questions: LESSON_CH6_L4() },
      { id: 'ch6-l5', title_ar: 'القسمة على ٥', title_en: 'Division by 5', questions: LESSON_CH6_L5() },
      { id: 'ch6-l6', title_ar: 'القسمة على ١٠', title_en: 'Division by 10', questions: LESSON_CH6_L6() },
      { id: 'ch6-l7', title_ar: 'القسمة مع الصفر وعلى الواحد', title_en: 'Division with Zero and One', questions: LESSON_CH6_L7() },
    ],
  },
  {
    id: 'ch7',
    title_ar: 'الفصل السابع: القسمة (٢)',
    title_en: 'Chapter 7: Division (2)',
    color: '#dc2626',
    lessons: [
      { id: 'ch7-l1', title_ar: 'القسمة على ٣ وعلى ٤', title_en: 'Division by 3 and 4', questions: LESSON_CH7_L1() },
      { id: 'ch7-l2', title_ar: 'القسمة على ٦ وعلى ٧', title_en: 'Division by 6 and 7', questions: LESSON_CH7_L2() },
      { id: 'ch7-l3', title_ar: 'القسمة على ٨ وعلى ٩', title_en: 'Division by 8 and 9', questions: LESSON_CH7_L3() },
    ],
  },
];

export const MATH3_S2_TOTAL_CHAPTERS = MATH3_S2_DIVISION_CHAPTERS.length;
export const MATH3_S2_TOTAL_LESSONS = MATH3_S2_DIVISION_CHAPTERS.reduce((n, c) => n + c.lessons.length, 0);