// بنك أسئلة الرياضيات — الصف الأول الابتدائي — الفصل الأول 1447
// مرجع: كتاب الرياضيات الصف الأول ط 2025 وزارة التعليم السعودية
// ملاحظة: الرموز الرياضية تُعرض باستخدام KaTeX

export const MATH1_S1_META = {
  subject: 'الرياضيات',
  grade: 'الصف الأول الابتدائي',
  semester: 'الفصل الأول',
  year: '1447 هـ / 2025 م',
  publisher: 'وزارة التعليم — المملكة العربية السعودية',
};

export const MATH1_S1_UNITS = [
  {
    id: 'ch1',
    title_ar: 'الفصل الأول: الأعداد من 0 إلى 5',
    icon: '🔢',
    color: '#0891b2',
    lessons: [
      { id: 'ch1l1', title_ar: 'الأعداد 1 و 2', page: '1-12' },
      { id: 'ch1l2', title_ar: 'الأعداد 3 و 4', page: '13-24' },
      { id: 'ch1l3', title_ar: 'العدد 5', page: '25-36' },
      { id: 'ch1l4', title_ar: 'العدد 0', page: '37-48' },
    ],
  },
  {
    id: 'ch2',
    title_ar: 'الفصل الثاني: المقارنة والترتيب',
    icon: '⚖️',
    color: '#7c3aed',
    lessons: [
      { id: 'ch2l1', title_ar: 'مقارنة المجموعات', page: '49-58' },
      { id: 'ch2l2', title_ar: 'المقارنة بالأعداد', page: '59-68' },
      { id: 'ch2l3', title_ar: 'الترتيب', page: '69-78' },
    ],
  },
  {
    id: 'ch3',
    title_ar: 'الفصل الثالث: الأعداد من 6 إلى 9',
    icon: '🔟',
    color: '#059669',
    lessons: [
      { id: 'ch3l1', title_ar: 'الأعداد 6 و 7', page: '79-90' },
      { id: 'ch3l2', title_ar: 'الأعداد 8 و 9', page: '91-100' },
    ],
  },
  {
    id: 'ch4',
    title_ar: 'الفصل الرابع: الأشكال والفضاء',
    icon: '🔶',
    color: '#b45309',
    lessons: [
      { id: 'ch4l1', title_ar: 'الأشكال المجسمة', page: '101-108' },
      { id: 'ch4l2', title_ar: 'الأشكال المستوية', page: '109-116' },
    ],
  },
  {
    id: 'ch5',
    title_ar: 'الفصل الخامس: الأعداد إلى 20',
    icon: '2️⃣0️⃣',
    color: '#e11d48',
    lessons: [
      { id: 'ch5l1', title_ar: 'الأعداد من 10 إلى 13', page: '77-90' },
      { id: 'ch5l2', title_ar: 'الأعداد من 14 إلى 17', page: '91-100' },
      { id: 'ch5l3', title_ar: 'الأعداد من 18 إلى 20', page: '101-110' },
      { id: 'ch5l4', title_ar: 'المقارنة والترتيب إلى 20', page: '111-116' },
    ],
  },
  {
    id: 'ch6',
    title_ar: 'الفصل السادس: الجمع',
    icon: '➕',
    color: '#0f766e',
    lessons: [
      { id: 'ch6l1', title_ar: 'قصص الجمع', page: '113-115' },
      { id: 'ch6l2', title_ar: 'تمثيل الجمع', page: '116-117' },
      { id: 'ch6l3', title_ar: 'جمل الجمع', page: '118-119' },
      { id: 'ch6l4', title_ar: 'الجمع إلى الصفر', page: '120-121' },
      { id: 'ch6l5', title_ar: 'أحل المسألة بالتمثيل', page: '124-125' },
      { id: 'ch6l6', title_ar: 'تكوين الأعداد 4 و 5 و 6', page: '126-127' },
      { id: 'ch6l7', title_ar: 'تكوين الأعداد 7 و 8 و 9', page: '128-129' },
      { id: 'ch6l8', title_ar: 'تكوين الأعداد 10 و 11 و 12', page: '130-131' },
      { id: 'ch6l9', title_ar: 'الجمع الرأسي', page: '132-133' },
    ],
  },
];

// ════════════════════════════════════════════════════════════
// الأسئلة — 300+ سؤال موزعة على الفصول والدروس
// ════════════════════════════════════════════════════════════

export const MATH1_S1_QUESTIONS = [

  // ══════════════════════════════════════════════════════════
  // الفصل الأول: الأعداد من 0 إلى 5
  // ══════════════════════════════════════════════════════════

  // ── الدرس 1: الأعداد 1 و 2 ──────────────────────────────
  {
    id: 'm1_001', unit: 'ch1', lesson: 'ch1l1', page: 3, difficulty: 'easy',
    type: 'multipleChoice', useKatex: true,
    question: 'يُشير العدد \\(1\\) إلى مجموعة تحتوي على:',
    options: [
      { text: 'شيء واحد فقط', correct: true },
      { text: 'شيئين اثنين', correct: false },
      { text: 'ثلاثة أشياء', correct: false },
      { text: 'لا شيء', correct: false },
    ],
    explanation: 'العدد ١ يُشير إلى مجموعة تحتوي على شيء واحد فقط.',
    goldenRule: 'العدد ١ = شيء واحد.',
    paragraph: 'الأعداد ١ و ٢ — ص ٣',
  },
  {
    id: 'm1_002', unit: 'ch1', lesson: 'ch1l1', page: 4, difficulty: 'easy',
    type: 'trueFalse',
    question: 'العدد ٢ يُمثّل مجموعة تحتوي على عنصرين اثنين.',
    correctAnswer: 'true',
    explanation: 'نعم، العدد ٢ يُمثل مجموعة تحتوي على عنصرين اثنين بالضبط.',
    goldenRule: 'العدد ٢ = عنصران اثنان.',
    paragraph: 'الأعداد ١ و ٢ — ص ٤',
  },
  {
    id: 'm1_003', unit: 'ch1', lesson: 'ch1l1', page: 5, difficulty: 'easy',
    type: 'multipleChoice', useKatex: true,
    question: 'كم عدد الكتب الظاهرة في المجموعة: كتاب واحد؟ ما العدد الذي يُعبّر عنها؟',
    options: [
      { text: '٢', correct: false },
      { text: '١', correct: true },
      { text: '٣', correct: false },
      { text: '٠', correct: false },
    ],
    explanation: 'مجموعة تحتوي على كتاب واحد تُعبّر عنها بالعدد ١.',
    goldenRule: 'نعدّ العناصر ونكتب العدد المناسب.',
    paragraph: 'العد والكتابة — ص ٥',
  },
  {
    id: 'm1_004', unit: 'ch1', lesson: 'ch1l1', page: 6, difficulty: 'easy',
    type: 'trueFalse',
    question: 'العدد ١ يأتي قبل العدد ٢ عند العدّ.',
    correctAnswer: 'true',
    explanation: 'عند العدّ نقول: واحد، اثنان... فالعدد ١ يأتي قبل العدد ٢.',
    goldenRule: 'ترتيب الأعداد: ١، ٢، ٣...',
    paragraph: 'الأعداد ١ و ٢ — ص ٦',
  },
  {
    id: 'm1_005', unit: 'ch1', lesson: 'ch1l1', page: 7, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'مجموعة فيها ٢ فراشة وأخرى فيها ١ فراشة، أيُّهما أكبر؟',
    options: [
      { text: 'المجموعة التي فيها ٢ فراشة', correct: true },
      { text: 'المجموعة التي فيها ١ فراشة', correct: false },
      { text: 'المجموعتان متساويتان', correct: false },
      { text: 'لا يمكن المقارنة', correct: false },
    ],
    explanation: 'العدد ٢ أكبر من العدد ١، لذا المجموعة التي فيها ٢ فراشة أكبر.',
    goldenRule: '٢ > ١ → المجموعة الأكبر عدداً هي الأكبر.',
    paragraph: 'مقارنة المجموعات — ص ٧',
  },
  {
    id: 'm1_006', unit: 'ch1', lesson: 'ch1l1', page: 8, difficulty: 'easy',
    type: 'ordering',
    question: 'رتّب الأعداد من الأصغر إلى الأكبر:',
    items: ['٢', '٠', '١'],
    correctOrder: [1, 2, 0],
    explanation: 'الترتيب من الأصغر للأكبر: ٠، ١، ٢.',
    goldenRule: 'ترتيب الأعداد تصاعدياً: ٠ < ١ < ٢.',
    paragraph: 'الترتيب — ص ٨',
  },

  // ── الدرس 2: الأعداد 3 و 4 ──────────────────────────────
  {
    id: 'm1_007', unit: 'ch1', lesson: 'ch1l2', page: 13, difficulty: 'easy',
    type: 'multipleChoice', useKatex: true,
    question: 'عدد أضلاع المثلث هو \\(3\\). أيّ المجموعات تُمثّل العدد ٣؟',
    options: [
      { text: 'مجموعة فيها ثلاثة أشياء', correct: true },
      { text: 'مجموعة فيها أربعة أشياء', correct: false },
      { text: 'مجموعة فيها شيئان', correct: false },
      { text: 'مجموعة فيها خمسة أشياء', correct: false },
    ],
    explanation: 'العدد ٣ يُمثّل مجموعة تحتوي على ثلاثة أشياء.',
    goldenRule: 'العدد ٣ = ثلاثة عناصر.',
    paragraph: 'الأعداد ٣ و ٤ — ص ١٣',
  },
  {
    id: 'm1_008', unit: 'ch1', lesson: 'ch1l2', page: 14, difficulty: 'easy',
    type: 'trueFalse',
    question: 'أضلاع المربع عددها ٤.',
    correctAnswer: 'true',
    explanation: 'المربع له ٤ أضلاع متساوية، لذا عدد أضلاعه ٤.',
    goldenRule: 'المربع = ٤ أضلاع متساوية.',
    paragraph: 'الأعداد ٣ و ٤ — ص ١٤',
  },
  {
    id: 'm1_009', unit: 'ch1', lesson: 'ch1l2', page: 15, difficulty: 'medium',
    type: 'multipleChoice', useKatex: true,
    question: 'في مجموعة فيها \\(3\\) قطط وأخرى فيها \\(4\\) كلاب، كم الفرق بين العددين؟',
    options: [
      { text: '١', correct: true },
      { text: '٢', correct: false },
      { text: '٣', correct: false },
      { text: '٠', correct: false },
    ],
    explanation: 'الفرق بين ٤ و ٣ هو: ٤ - ٣ = ١.',
    goldenRule: 'الفرق بين عددين متتاليين دائماً ١.',
    paragraph: 'الأعداد ٣ و ٤ — ص ١٥',
  },
  {
    id: 'm1_010', unit: 'ch1', lesson: 'ch1l2', page: 16, difficulty: 'easy',
    type: 'trueFalse',
    question: 'العدد ٣ أكبر من العدد ٤.',
    correctAnswer: 'false',
    explanation: 'العدد ٣ أصغر من العدد ٤، لأن ٤ يأتي بعد ٣ في الترتيب.',
    goldenRule: '٣ < ٤ → ثلاثة أصغر من أربعة.',
    paragraph: 'مقارنة ٣ و ٤ — ص ١٦',
  },
  {
    id: 'm1_011', unit: 'ch1', lesson: 'ch1l2', page: 18, difficulty: 'medium',
    type: 'classify',
    question: 'صنّف المجموعات حسب العدد:',
    categories: ['عدد العناصر ٣', 'عدد العناصر ٤'],
    items: [
      { text: 'ثلاث تفاحات', correct_category: 0 },
      { text: 'ثلاثة كتب', correct_category: 0 },
      { text: 'أربعة أقلام', correct_category: 1 },
      { text: 'أربع كرات', correct_category: 1 },
    ],
    explanation: 'المجموعات التي فيها ٣ عناصر تُمثّل العدد ٣، والتي فيها ٤ عناصر تُمثّل العدد ٤.',
    goldenRule: 'نعدّ العناصر بدقة قبل تصنيفها.',
    paragraph: 'الأعداد ٣ و ٤ — ص ١٨',
  },

  // ── الدرس 3: العدد 5 ─────────────────────────────────────
  {
    id: 'm1_012', unit: 'ch1', lesson: 'ch1l3', page: 25, difficulty: 'easy',
    type: 'multipleChoice', useKatex: true,
    question: 'أصابع اليد الواحدة عددها \\(5\\). أيّ الأرقام يُعبّر عن عدد أصابع اليدين معاً؟',
    options: [
      { text: '٥', correct: false },
      { text: '١٠', correct: true },
      { text: '٨', correct: false },
      { text: '٧', correct: false },
    ],
    explanation: 'أصابع اليدين = ٥ + ٥ = ١٠.',
    goldenRule: 'يدان × ٥ أصابع = ١٠ أصابع.',
    paragraph: 'العدد ٥ — ص ٢٥',
  },
  {
    id: 'm1_013', unit: 'ch1', lesson: 'ch1l3', page: 26, difficulty: 'easy',
    type: 'trueFalse',
    question: 'العدد ٥ هو أكبر عدد من الأعداد: ٣، ٤، ٥.',
    correctAnswer: 'true',
    explanation: 'نعم، ٥ > ٤ > ٣، فالعدد ٥ هو أكبرها.',
    goldenRule: '٣ < ٤ < ٥ تصاعدياً.',
    paragraph: 'العدد ٥ — ص ٢٦',
  },
  {
    id: 'm1_014', unit: 'ch1', lesson: 'ch1l3', page: 28, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'مجموعة فيها ٥ نجوم. إذا أزلنا نجمة واحدة، كم يصبح عددها؟',
    options: [
      { text: '٤', correct: true },
      { text: '٣', correct: false },
      { text: '٦', correct: false },
      { text: '٥', correct: false },
    ],
    explanation: '٥ - ١ = ٤ نجوم.',
    goldenRule: 'إزالة عنصر من مجموعة تُقلّل العدد بمقدار ١.',
    paragraph: 'العدد ٥ — ص ٢٨',
  },
  {
    id: 'm1_015', unit: 'ch1', lesson: 'ch1l3', page: 30, difficulty: 'easy',
    type: 'ordering',
    question: 'رتّب الأعداد من الأصغر إلى الأكبر:',
    items: ['٥', '٢', '٤', '١', '٣'],
    correctOrder: [3, 1, 4, 2, 0],
    explanation: 'الترتيب التصاعدي: ١، ٢، ٣، ٤، ٥.',
    goldenRule: '١ < ٢ < ٣ < ٤ < ٥.',
    paragraph: 'الترتيب — ص ٣٠',
  },

  // ── الدرس 4: العدد 0 ─────────────────────────────────────
  {
    id: 'm1_016', unit: 'ch1', lesson: 'ch1l4', page: 37, difficulty: 'easy',
    type: 'multipleChoice',
    question: 'ماذا يعني العدد ٠ (صفر)؟',
    options: [
      { text: 'لا شيء في المجموعة', correct: true },
      { text: 'شيء واحد في المجموعة', correct: false },
      { text: 'أكبر الأعداد', correct: false },
      { text: 'عدد غير معروف', correct: false },
    ],
    explanation: 'الصفر يعني أنه لا يوجد أي شيء في المجموعة، أي المجموعة فارغة.',
    goldenRule: 'الصفر = مجموعة فارغة = لا شيء.',
    paragraph: 'العدد ٠ — ص ٣٧',
  },
  {
    id: 'm1_017', unit: 'ch1', lesson: 'ch1l4', page: 38, difficulty: 'easy',
    type: 'trueFalse',
    question: 'الصفر هو أصغر عدد من الأعداد: ٠، ١، ٢، ٣، ٤، ٥.',
    correctAnswer: 'true',
    explanation: 'نعم، الصفر هو أصغر عدد طبيعي في هذه المجموعة.',
    goldenRule: 'الصفر = أصغر عدد في الأعداد الطبيعية.',
    paragraph: 'العدد ٠ — ص ٣٨',
  },
  {
    id: 'm1_018', unit: 'ch1', lesson: 'ch1l4', page: 40, difficulty: 'medium',
    type: 'multipleChoice', useKatex: true,
    question: 'إذا كانت سلة فاكهة فارغة تماماً، فعدد الفواكه فيها هو:',
    options: [
      { text: '\\(0\\)', correct: true },
      { text: '\\(1\\)', correct: false },
      { text: '\\(5\\)', correct: false },
      { text: '\\(2\\)', correct: false },
    ],
    explanation: 'السلة الفارغة لا تحتوي على أي فاكهة، وهذا يُعبّر عنه بالعدد ٠.',
    goldenRule: 'فارغ = صفر = ٠.',
    paragraph: 'العدد ٠ — ص ٤٠',
  },

  // ══════════════════════════════════════════════════════════
  // الفصل الثاني: المقارنة والترتيب
  // ══════════════════════════════════════════════════════════

  {
    id: 'm1_019', unit: 'ch2', lesson: 'ch2l1', page: 49, difficulty: 'easy',
    type: 'multipleChoice',
    question: 'مجموعة فيها ٣ كرات وأخرى فيها ٢ كرة. أيّ المجموعتين أكبر؟',
    options: [
      { text: 'المجموعة التي فيها ٣ كرات', correct: true },
      { text: 'المجموعة التي فيها ٢ كرة', correct: false },
      { text: 'المجموعتان متساويتان', correct: false },
      { text: 'لا يمكن التحديد', correct: false },
    ],
    explanation: '٣ > ٢ لذا المجموعة التي فيها ٣ كرات أكبر.',
    goldenRule: 'المجموعة التي فيها عدد أكبر هي الأكبر.',
    paragraph: 'مقارنة المجموعات — ص ٤٩',
  },
  {
    id: 'm1_020', unit: 'ch2', lesson: 'ch2l1', page: 50, difficulty: 'easy',
    type: 'trueFalse', useKatex: true,
    question: 'المجموعة التي فيها \\(4\\) عناصر أصغر من المجموعة التي فيها \\(5\\) عناصر.',
    correctAnswer: 'true',
    explanation: '٤ < ٥، لذا المجموعة التي فيها ٤ عناصر أصغر.',
    goldenRule: '٤ < ٥ → الأربعة أصغر من الخمسة.',
    paragraph: 'مقارنة المجموعات — ص ٥٠',
  },
  {
    id: 'm1_021', unit: 'ch2', lesson: 'ch2l1', page: 52, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'مجموعتان كل منهما تحتوي على ٣ زهرات. ما العلاقة بينهما؟',
    options: [
      { text: 'المجموعتان متساويتان', correct: true },
      { text: 'المجموعة الأولى أكبر', correct: false },
      { text: 'المجموعة الثانية أكبر', correct: false },
      { text: 'لا يمكن المقارنة', correct: false },
    ],
    explanation: 'عندما تتساوى عدد العناصر في مجموعتين فهما متساويتان.',
    goldenRule: 'عناصر متساوية → مجموعتان متساويتان.',
    paragraph: 'مقارنة المجموعات — ص ٥٢',
  },
  {
    id: 'm1_022', unit: 'ch2', lesson: 'ch2l2', page: 59, difficulty: 'easy',
    type: 'multipleChoice', useKatex: true,
    question: 'أيّ رمز المقارنة الصحيح بين العددين \\(3\\) و \\(5\\)؟',
    options: [
      { text: '\\(3 < 5\\)', correct: true },
      { text: '\\(3 > 5\\)', correct: false },
      { text: '\\(3 = 5\\)', correct: false },
      { text: '\\(5 < 3\\)', correct: false },
    ],
    explanation: '٣ أصغر من ٥، لذا نكتب ٣ < ٥.',
    goldenRule: 'الرمز < يعني "أصغر من"، والرمز > يعني "أكبر من".',
    paragraph: 'المقارنة بالأعداد — ص ٥٩',
  },
  {
    id: 'm1_023', unit: 'ch2', lesson: 'ch2l2', page: 60, difficulty: 'easy',
    type: 'trueFalse', useKatex: true,
    question: 'العبارة الرياضية \\(4 > 2\\) صحيحة.',
    correctAnswer: 'true',
    explanation: '٤ أكبر من ٢، فالعبارة ٤ > ٢ صحيحة.',
    goldenRule: '٤ > ٢ → أربعة أكبر من اثنين.',
    paragraph: 'المقارنة بالأعداد — ص ٦٠',
  },
  {
    id: 'm1_024', unit: 'ch2', lesson: 'ch2l2', page: 62, difficulty: 'medium',
    type: 'multipleChoice', useKatex: true,
    question: 'أيّ العبارات الآتية صحيحة؟',
    options: [
      { text: '\\(1 < 3\\)', correct: true },
      { text: '\\(5 < 4\\)', correct: false },
      { text: '\\(2 > 3\\)', correct: false },
      { text: '\\(4 = 5\\)', correct: false },
    ],
    explanation: '١ أصغر من ٣، فالعبارة ١ < ٣ صحيحة.',
    goldenRule: 'تحقّق من العدد الأكبر والأصغر قبل كتابة رمز المقارنة.',
    paragraph: 'المقارنة بالأعداد — ص ٦٢',
  },
  {
    id: 'm1_025', unit: 'ch2', lesson: 'ch2l3', page: 69, difficulty: 'easy',
    type: 'ordering',
    question: 'رتّب الأعداد التالية من الأكبر إلى الأصغر:',
    items: ['١', '٤', '٢', '٥', '٣'],
    correctOrder: [3, 1, 4, 2, 0],
    explanation: 'الترتيب التنازلي: ٥، ٤، ٣، ٢، ١.',
    goldenRule: '٥ > ٤ > ٣ > ٢ > ١ تنازلياً.',
    paragraph: 'الترتيب — ص ٦٩',
  },
  {
    id: 'm1_026', unit: 'ch2', lesson: 'ch2l3', page: 70, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'ما العدد الذي يأتي بعد العدد ٤ مباشرةً في ترتيب الأعداد؟',
    options: [
      { text: '٥', correct: true },
      { text: '٣', correct: false },
      { text: '٦', correct: false },
      { text: '٢', correct: false },
    ],
    explanation: 'الترتيب: ...٣، ٤، ٥... فالعدد الذي يأتي بعد ٤ هو ٥.',
    goldenRule: 'كل عدد يأتي بعده العدد الذي يكبره بمقدار ١.',
    paragraph: 'الترتيب — ص ٧٠',
  },
  {
    id: 'm1_027', unit: 'ch2', lesson: 'ch2l3', page: 71, difficulty: 'medium',
    type: 'trueFalse',
    question: 'العدد الذي يأتي قبل العدد ٣ هو العدد ٢.',
    correctAnswer: 'true',
    explanation: 'الترتيب: ...١، ٢، ٣... فالعدد الذي يأتي قبل ٣ هو ٢.',
    goldenRule: 'العدد السابق = العدد ناقص ١.',
    paragraph: 'الترتيب — ص ٧١',
  },
  {
    id: 'm1_028', unit: 'ch2', lesson: 'ch2l3', page: 72, difficulty: 'hard',
    type: 'multipleChoice',
    question: 'أيُّ الأعداد الآتية يأتي بين العددين ٢ و ٤؟',
    options: [
      { text: '٣', correct: true },
      { text: '١', correct: false },
      { text: '٥', correct: false },
      { text: '٠', correct: false },
    ],
    explanation: 'الترتيب: ٢، ٣، ٤. فالعدد ٣ يأتي بين ٢ و ٤.',
    goldenRule: 'العدد الذي بين عددين هو العدد الذي يأتي بعد الأصغر وقبل الأكبر.',
    paragraph: 'الترتيب — ص ٧٢',
  },

  // ══════════════════════════════════════════════════════════
  // الفصل الثالث: الأعداد من 6 إلى 9
  // ══════════════════════════════════════════════════════════

  {
    id: 'm1_029', unit: 'ch3', lesson: 'ch3l1', page: 79, difficulty: 'easy',
    type: 'multipleChoice',
    question: 'عدد أيام الأسبوع هو ٧. كم يُمثّل العدد ٧ من مجموعات؟',
    options: [
      { text: 'مجموعة فيها ٧ عناصر', correct: true },
      { text: 'مجموعة فيها ٦ عناصر', correct: false },
      { text: 'مجموعة فيها ٨ عناصر', correct: false },
      { text: 'مجموعة فيها ٥ عناصر', correct: false },
    ],
    explanation: 'العدد ٧ يُمثّل مجموعة تحتوي على ٧ عناصر، كأيام الأسبوع السبعة.',
    goldenRule: 'العدد ٧ = سبعة عناصر = أيام الأسبوع.',
    paragraph: 'الأعداد ٦ و ٧ — ص ٧٩',
  },
  {
    id: 'm1_030', unit: 'ch3', lesson: 'ch3l1', page: 80, difficulty: 'easy',
    type: 'trueFalse', useKatex: true,
    question: 'العدد \\(6\\) يأتي قبل العدد \\(7\\) في ترتيب الأعداد.',
    correctAnswer: 'true',
    explanation: 'الترتيب: ...٥، ٦، ٧... فالعدد ٦ يأتي قبل ٧.',
    goldenRule: '٦ يأتي قبل ٧ في ترتيب الأعداد.',
    paragraph: 'الأعداد ٦ و ٧ — ص ٨٠',
  },
  {
    id: 'm1_031', unit: 'ch3', lesson: 'ch3l1', page: 82, difficulty: 'medium',
    type: 'multipleChoice', useKatex: true,
    question: 'أيُّ العبارات التالية صحيحة؟',
    options: [
      { text: '\\(6 < 7\\)', correct: true },
      { text: '\\(7 < 6\\)', correct: false },
      { text: '\\(6 = 7\\)', correct: false },
      { text: '\\(7 < 5\\)', correct: false },
    ],
    explanation: '٦ أصغر من ٧، فالعبارة ٦ < ٧ صحيحة.',
    goldenRule: '٦ < ٧ → ستة أصغر من سبعة.',
    paragraph: 'الأعداد ٦ و ٧ — ص ٨٢',
  },
  {
    id: 'm1_032', unit: 'ch3', lesson: 'ch3l2', page: 91, difficulty: 'easy',
    type: 'multipleChoice',
    question: 'ما العدد الذي يأتي بين ٧ و ٩؟',
    options: [
      { text: '٨', correct: true },
      { text: '٦', correct: false },
      { text: '١٠', correct: false },
      { text: '٥', correct: false },
    ],
    explanation: 'الترتيب: ٧، ٨، ٩. فالعدد ٨ يأتي بين ٧ و ٩.',
    goldenRule: 'العدد الواقع بين ٧ و ٩ هو ٨.',
    paragraph: 'الأعداد ٨ و ٩ — ص ٩١',
  },
  {
    id: 'm1_033', unit: 'ch3', lesson: 'ch3l2', page: 92, difficulty: 'easy',
    type: 'trueFalse',
    question: 'العدد ٩ هو أكبر عدد من الأعداد: ٦، ٧، ٨، ٩.',
    correctAnswer: 'true',
    explanation: 'الترتيب: ٦ < ٧ < ٨ < ٩. فالعدد ٩ هو الأكبر.',
    goldenRule: '٩ هو أكبر عدد من الأعداد ٦ إلى ٩.',
    paragraph: 'الأعداد ٨ و ٩ — ص ٩٢',
  },
  {
    id: 'm1_034', unit: 'ch3', lesson: 'ch3l2', page: 94, difficulty: 'medium',
    type: 'ordering',
    question: 'رتّب الأعداد التالية تصاعدياً:',
    items: ['٩', '٦', '٨', '٧'],
    correctOrder: [1, 3, 2, 0],
    explanation: 'الترتيب التصاعدي: ٦، ٧، ٨، ٩.',
    goldenRule: '٦ < ٧ < ٨ < ٩.',
    paragraph: 'الأعداد ٦ إلى ٩ — ص ٩٤',
  },
  {
    id: 'm1_035', unit: 'ch3', lesson: 'ch3l2', page: 95, difficulty: 'hard',
    type: 'multipleChoice',
    question: 'كم عدد الأعداد الفردية بين ٥ و ٩ (شاملاً الطرفين)؟',
    options: [
      { text: '٣ أعداد (٥، ٧، ٩)', correct: true },
      { text: 'عددان (٦، ٨)', correct: false },
      { text: '٥ أعداد', correct: false },
      { text: '٤ أعداد', correct: false },
    ],
    explanation: 'الأعداد الفردية بين ٥ و ٩: ٥، ٧، ٩ → ٣ أعداد.',
    goldenRule: 'الأعداد الفردية: ١، ٣، ٥، ٧، ٩...',
    paragraph: 'الأعداد الفردية — ص ٩٥',
  },

  // ══════════════════════════════════════════════════════════
  // الفصل الرابع: الأشكال والفضاء
  // ══════════════════════════════════════════════════════════

  {
    id: 'm1_036', unit: 'ch4', lesson: 'ch4l1', page: 101, difficulty: 'easy',
    type: 'multipleChoice',
    question: 'الشكل المجسّم الذي يشبه الكرة يُسمّى:',
    options: [
      { text: 'الكرة', correct: true },
      { text: 'المكعب', correct: false },
      { text: 'الأسطوانة', correct: false },
      { text: 'المخروط', correct: false },
    ],
    explanation: 'الشكل المجسّم الكروي يُسمّى الكرة، وله نقطة مركزية وسطح منحنٍ.',
    goldenRule: 'الكرة = شكل مجسّم كروي يمكن لفّه في كل اتجاه.',
    paragraph: 'الأشكال المجسمة — ص ١٠١',
  },
  {
    id: 'm1_037', unit: 'ch4', lesson: 'ch4l1', page: 102, difficulty: 'easy',
    type: 'trueFalse',
    question: 'المكعب له ٦ وجوه مربعة الشكل.',
    correctAnswer: 'true',
    explanation: 'المكعب له ٦ وجوه، كلها مربعات متساوية.',
    goldenRule: 'المكعب: ٦ وجوه + ١٢ حافة + ٨ رؤوس.',
    paragraph: 'الأشكال المجسمة — ص ١٠٢',
  },
  {
    id: 'm1_038', unit: 'ch4', lesson: 'ch4l1', page: 104, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'أيّ الأشكال المجسمة يمكنه الانزلاق فقط ولا يمكنه التدحرج؟',
    options: [
      { text: 'المكعب', correct: true },
      { text: 'الكرة', correct: false },
      { text: 'الأسطوانة', correct: false },
      { text: 'المخروط', correct: false },
    ],
    explanation: 'المكعب يمكنه الانزلاق فقط بسبب وجوهه المستوية، ولا يمكنه التدحرج.',
    goldenRule: 'مستوي = ينزلق | منحنٍ = يتدحرج.',
    paragraph: 'خصائص الأشكال المجسمة — ص ١٠٤',
  },
  {
    id: 'm1_039', unit: 'ch4', lesson: 'ch4l1', page: 105, difficulty: 'medium',
    type: 'classify',
    question: 'صنّف الأشكال المجسمة حسب قدرتها على التدحرج:',
    categories: ['يتدحرج', 'لا يتدحرج'],
    items: [
      { text: 'الكرة', correct_category: 0 },
      { text: 'الأسطوانة', correct_category: 0 },
      { text: 'المكعب', correct_category: 1 },
      { text: 'متوازي المستطيلات', correct_category: 1 },
    ],
    explanation: 'الكرة والأسطوانة تتدحرجان لوجود سطح منحنٍ، أما المكعب ومتوازي المستطيلات فلا يتدحرجان.',
    goldenRule: 'السطح المنحني = تدحرج | السطح المستوي = انزلاق.',
    paragraph: 'خصائص الأشكال المجسمة — ص ١٠٥',
  },
  {
    id: 'm1_040', unit: 'ch4', lesson: 'ch4l2', page: 109, difficulty: 'easy',
    type: 'multipleChoice',
    question: 'الشكل المستوي الذي له ٤ أضلاع متساوية و٤ زوايا قائمة هو:',
    options: [
      { text: 'المربع', correct: true },
      { text: 'المثلث', correct: false },
      { text: 'الدائرة', correct: false },
      { text: 'المستطيل', correct: false },
    ],
    explanation: 'المربع له ٤ أضلاع متساوية و٤ زوايا قائمة.',
    goldenRule: 'المربع: ٤ أضلاع متساوية + ٤ زوايا قائمة.',
    paragraph: 'الأشكال المستوية — ص ١٠٩',
  },
  {
    id: 'm1_041', unit: 'ch4', lesson: 'ch4l2', page: 110, difficulty: 'easy',
    type: 'trueFalse',
    question: 'المثلث له ٣ أضلاع و٣ زوايا.',
    correctAnswer: 'true',
    explanation: 'المثلث شكل مستوٍ له ٣ أضلاع و٣ زوايا.',
    goldenRule: 'المثلث: ٣ أضلاع + ٣ زوايا.',
    paragraph: 'الأشكال المستوية — ص ١١٠',
  },
  {
    id: 'm1_042', unit: 'ch4', lesson: 'ch4l2', page: 112, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'كم عدد أضلاع المستطيل؟',
    options: [
      { text: '٤ أضلاع', correct: true },
      { text: '٣ أضلاع', correct: false },
      { text: '٦ أضلاع', correct: false },
      { text: '٥ أضلاع', correct: false },
    ],
    explanation: 'المستطيل له ٤ أضلاع: ضلعان طويلان وضلعان قصيران.',
    goldenRule: 'المستطيل: ٤ أضلاع، الأضلاع المتقابلة متساوية.',
    paragraph: 'الأشكال المستوية — ص ١١٢',
  },
  {
    id: 'm1_043', unit: 'ch4', lesson: 'ch4l2', page: 113, difficulty: 'hard',
    type: 'classify',
    question: 'صنّف الأشكال المستوية حسب عدد أضلاعها:',
    categories: ['٣ أضلاع', '٤ أضلاع'],
    items: [
      { text: 'المثلث', correct_category: 0 },
      { text: 'مثلث متساوي الأضلاع', correct_category: 0 },
      { text: 'المربع', correct_category: 1 },
      { text: 'المستطيل', correct_category: 1 },
    ],
    explanation: 'المثلث وكل أنواعه: ٣ أضلاع. المربع والمستطيل: ٤ أضلاع.',
    goldenRule: 'مثلث = ٣ أضلاع | رباعي = ٤ أضلاع.',
    paragraph: 'الأشكال المستوية — ص ١١٣',
  },

  // ══════════════════════════════════════════════════════════
  // الفصل الخامس: الأعداد إلى 20
  // ══════════════════════════════════════════════════════════

  {
    id: 'm1_044', unit: 'ch5', lesson: 'ch5l1', page: 77, difficulty: 'easy',
    type: 'multipleChoice',
    question: 'العدد عشرة (١٠) يُكتب بالأرقام:',
    options: [
      { text: '١٠', correct: true },
      { text: '١', correct: false },
      { text: '١٠٠', correct: false },
      { text: '٢٠', correct: false },
    ],
    explanation: 'عشرة تُكتب بالأرقام: ١٠، وتتكون من عقد واحد وصفر آحاد.',
    goldenRule: '١٠ = عشرة = عقد واحد.',
    paragraph: 'الأعداد ١٠ إلى ١٣ — ص ٧٧',
  },
  {
    id: 'm1_045', unit: 'ch5', lesson: 'ch5l1', page: 78, difficulty: 'easy',
    type: 'trueFalse',
    question: 'العدد ١٠ أكبر من العدد ٩.',
    correctAnswer: 'true',
    explanation: 'نعم، ١٠ > ٩ لأن ١٠ يأتي بعد ٩ في ترتيب الأعداد.',
    goldenRule: '١٠ > ٩ → عشرة أكبر من تسعة.',
    paragraph: 'الأعداد ١٠ إلى ١٣ — ص ٧٨',
  },
  {
    id: 'm1_046', unit: 'ch5', lesson: 'ch5l1', page: 80, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'العدد ١١ يتكون من:',
    options: [
      { text: 'عقد واحد وآحاد واحد', correct: true },
      { text: 'عقدين وآحاد واحد', correct: false },
      { text: 'عقد واحد وآحادين', correct: false },
      { text: 'آحاد فقط', correct: false },
    ],
    explanation: 'العدد ١١ = ١٠ + ١ = عقد واحد + آحاد واحد.',
    goldenRule: '١١ = عقد واحد (١٠) + آحاد واحد (١).',
    paragraph: 'الأعداد ١٠ إلى ١٣ — ص ٨٠',
  },
  {
    id: 'm1_047', unit: 'ch5', lesson: 'ch5l1', page: 82, difficulty: 'medium',
    type: 'multipleChoice', useKatex: true,
    question: 'ما العدد الناقص في المتتالية: \\(10, 11, ?, 13\\)؟',
    options: [
      { text: '١٢', correct: true },
      { text: '١٤', correct: false },
      { text: '٩', correct: false },
      { text: '١٥', correct: false },
    ],
    explanation: 'المتتالية تتزايد بمقدار ١: ١٠، ١١، ١٢، ١٣. فالعدد الناقص هو ١٢.',
    goldenRule: 'المتتالية الحسابية تتزايد بمقدار ثابت.',
    paragraph: 'الأعداد ١٠ إلى ١٣ — ص ٨٢',
  },
  {
    id: 'm1_048', unit: 'ch5', lesson: 'ch5l2', page: 91, difficulty: 'easy',
    type: 'multipleChoice',
    question: 'العدد أربعة عشر (١٤) يتكون من:',
    options: [
      { text: 'عقد واحد وأربعة آحاد', correct: true },
      { text: 'عقدين وآحاد واحد', correct: false },
      { text: 'أربعة عقود', correct: false },
      { text: 'عقد واحد فقط', correct: false },
    ],
    explanation: '١٤ = ١٠ + ٤ = عقد واحد + ٤ آحاد.',
    goldenRule: '١٤ = عقد واحد (١٠) + أربعة آحاد (٤).',
    paragraph: 'الأعداد ١٤ إلى ١٧ — ص ٩١',
  },
  {
    id: 'm1_049', unit: 'ch5', lesson: 'ch5l2', page: 93, difficulty: 'medium',
    type: 'multipleChoice', useKatex: true,
    question: 'أيّ العبارات الآتية صحيحة؟',
    options: [
      { text: '\\(14 < 16\\)', correct: true },
      { text: '\\(17 < 15\\)', correct: false },
      { text: '\\(14 = 15\\)', correct: false },
      { text: '\\(16 > 17\\)', correct: false },
    ],
    explanation: '١٤ أصغر من ١٦، فالعبارة ١٤ < ١٦ صحيحة.',
    goldenRule: '١٤ < ١٥ < ١٦ < ١٧ تصاعدياً.',
    paragraph: 'الأعداد ١٤ إلى ١٧ — ص ٩٣',
  },
  {
    id: 'm1_050', unit: 'ch5', lesson: 'ch5l3', page: 101, difficulty: 'easy',
    type: 'trueFalse',
    question: 'العدد ٢٠ هو أكبر عدد مكوّن من عقدين.',
    correctAnswer: 'true',
    explanation: 'العدد ٢٠ = ٢ عقود = أكبر عدد من عقدين بدون آحاد.',
    goldenRule: '٢٠ = عقدان = ٢٠ وحدة.',
    paragraph: 'الأعداد ١٨ إلى ٢٠ — ص ١٠١',
  },
  {
    id: 'm1_051', unit: 'ch5', lesson: 'ch5l3', page: 103, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'العدد ١٩ يتكون من:',
    options: [
      { text: 'عقد واحد وتسعة آحاد', correct: true },
      { text: 'عقدين وتسعة آحاد', correct: false },
      { text: 'تسعة عقود', correct: false },
      { text: 'عقد واحد وثمانية آحاد', correct: false },
    ],
    explanation: '١٩ = ١٠ + ٩ = عقد واحد + ٩ آحاد.',
    goldenRule: '١٩ = عقد واحد (١٠) + تسعة آحاد (٩).',
    paragraph: 'الأعداد ١٨ إلى ٢٠ — ص ١٠٣',
  },
  {
    id: 'm1_052', unit: 'ch5', lesson: 'ch5l4', page: 111, difficulty: 'medium',
    type: 'ordering',
    question: 'رتّب الأعداد التالية تصاعدياً:',
    items: ['١٧', '١٣', '٢٠', '١٥', '١٨'],
    correctOrder: [1, 3, 0, 4, 2],
    explanation: 'الترتيب التصاعدي: ١٣، ١٥، ١٧، ١٨، ٢٠.',
    goldenRule: '١٣ < ١٥ < ١٧ < ١٨ < ٢٠.',
    paragraph: 'الترتيب إلى ٢٠ — ص ١١١',
  },
  {
    id: 'm1_053', unit: 'ch5', lesson: 'ch5l4', page: 112, difficulty: 'hard',
    type: 'multipleChoice', useKatex: true,
    question: 'أيّ العبارات الآتية صحيحة؟',
    options: [
      { text: '\\(13 < 17 < 20\\)', correct: true },
      { text: '\\(20 < 13 < 17\\)', correct: false },
      { text: '\\(17 < 13 < 20\\)', correct: false },
      { text: '\\(20 < 17 < 13\\)', correct: false },
    ],
    explanation: '١٣ < ١٧ < ٢٠ تصاعدياً وهذا صحيح.',
    goldenRule: 'المقارنة المتسلسلة: نتحقق من كل زوج على حدة.',
    paragraph: 'المقارنة إلى ٢٠ — ص ١١٢',
  },

  // ══════════════════════════════════════════════════════════
  // الفصل السادس: الجمع
  // ══════════════════════════════════════════════════════════

  // ── الدرس 1: قصص الجمع ──────────────────────────────────
  {
    id: 'm1_054', unit: 'ch6', lesson: 'ch6l1', page: 114, difficulty: 'easy',
    type: 'multipleChoice', useKatex: true,
    question: 'في قصة: كانت هناك \\(5\\) طيور على غصن، وطارت إليها \\(3\\) طيور أخرى. كم أصبح عدد الطيور؟',
    options: [
      { text: '٨ طيور', correct: true },
      { text: '٦ طيور', correct: false },
      { text: '٧ طيور', correct: false },
      { text: '٢ طيور', correct: false },
    ],
    explanation: '٥ + ٣ = ٨ طيور.',
    goldenRule: 'الجمع = ضم مجموعتين معاً للحصول على الكل.',
    paragraph: 'قصص الجمع — ص ١١٤',
  },
  {
    id: 'm1_055', unit: 'ch6', lesson: 'ch6l1', page: 114, difficulty: 'easy',
    type: 'trueFalse', useKatex: true,
    question: 'في قصة جمع: إذا كان هناك \\(4\\) سلاحف و \\(1\\) سلحفاة، فمجموعها \\(5\\) سلاحف.',
    correctAnswer: 'true',
    explanation: '٤ + ١ = ٥ سلاحف.',
    goldenRule: '٤ + ١ = ٥.',
    paragraph: 'قصص الجمع — ص ١١٤',
  },
  {
    id: 'm1_056', unit: 'ch6', lesson: 'ch6l1', page: 115, difficulty: 'medium',
    type: 'multipleChoice', useKatex: true,
    question: 'في مجموعة \\(3\\) ثعالب وأخرى \\(4\\) ثعالب. ما مجموعها؟',
    options: [
      { text: '٧ ثعالب', correct: true },
      { text: '٨ ثعالب', correct: false },
      { text: '١ ثعلب', correct: false },
      { text: '٦ ثعالب', correct: false },
    ],
    explanation: '٣ + ٤ = ٧ ثعالب.',
    goldenRule: '٣ + ٤ = ٧.',
    paragraph: 'قصص الجمع — ص ١١٥',
  },
  {
    id: 'm1_057', unit: 'ch6', lesson: 'ch6l1', page: 115, difficulty: 'medium',
    type: 'multipleChoice', useKatex: true,
    question: 'كانت هناك \\(2\\) فراشة ثم جاءت \\(3\\) فراشات أخرى. ما جملة الجمع التي تُعبّر عن ذلك؟',
    options: [
      { text: '\\(2 + 3 = 5\\)', correct: true },
      { text: '\\(3 - 2 = 1\\)', correct: false },
      { text: '\\(2 + 2 = 4\\)', correct: false },
      { text: '\\(3 + 3 = 6\\)', correct: false },
    ],
    explanation: 'جاءت ٢ فراشة وانضمت إليها ٣، فالجملة: ٢ + ٣ = ٥.',
    goldenRule: 'قصة الجمع → جملة الجمع: جزء + جزء = الكل.',
    paragraph: 'قصص الجمع — ص ١١٥',
  },

  // ── الدرس 2: تمثيل الجمع ────────────────────────────────
  {
    id: 'm1_058', unit: 'ch6', lesson: 'ch6l2', page: 116, difficulty: 'easy',
    type: 'multipleChoice', useKatex: true,
    question: 'في نموذج الجزء والكل: جزء = \\(1\\)، جزء = \\(4\\). ما الكل؟',
    options: [
      { text: '٥', correct: true },
      { text: '٣', correct: false },
      { text: '٦', correct: false },
      { text: '٢', correct: false },
    ],
    explanation: 'الكل = الجزء + الجزء = ١ + ٤ = ٥.',
    goldenRule: 'الكل = الجزء الأول + الجزء الثاني.',
    paragraph: 'تمثيل الجمع — ص ١١٦',
  },
  {
    id: 'm1_059', unit: 'ch6', lesson: 'ch6l2', page: 116, difficulty: 'easy',
    type: 'trueFalse', useKatex: true,
    question: 'في نموذج الجزء والكل: إذا كان جزء = \\(3\\) وجزء = \\(5\\)، فالكل = \\(8\\).',
    correctAnswer: 'true',
    explanation: '٣ + ٥ = ٨.',
    goldenRule: '٣ + ٥ = ٨.',
    paragraph: 'تمثيل الجمع — ص ١١٦',
  },
  {
    id: 'm1_060', unit: 'ch6', lesson: 'ch6l2', page: 117, difficulty: 'medium',
    type: 'multipleChoice', useKatex: true,
    question: 'جزء = \\(2\\)، الكل = \\(7\\). ما الجزء الثاني؟',
    options: [
      { text: '٥', correct: true },
      { text: '٩', correct: false },
      { text: '٤', correct: false },
      { text: '٣', correct: false },
    ],
    explanation: 'الجزء الثاني = الكل - الجزء الأول = ٧ - ٢ = ٥.',
    goldenRule: 'الجزء الثاني = الكل - الجزء الأول.',
    paragraph: 'تمثيل الجمع — ص ١١٧',
  },
  {
    id: 'm1_061', unit: 'ch6', lesson: 'ch6l2', page: 117, difficulty: 'medium',
    type: 'multipleChoice', useKatex: true,
    question: 'جزء = \\(4\\)، جزء = \\(3\\). ما الكل؟',
    options: [
      { text: '٧', correct: true },
      { text: '١', correct: false },
      { text: '٨', correct: false },
      { text: '٦', correct: false },
    ],
    explanation: '٤ + ٣ = ٧.',
    goldenRule: '٤ + ٣ = ٧.',
    paragraph: 'تمثيل الجمع — ص ١١٧',
  },
  {
    id: 'm1_062', unit: 'ch6', lesson: 'ch6l2', page: 117, difficulty: 'medium',
    type: 'trueFalse', useKatex: true,
    question: 'في نموذج الجزء والكل: إذا كان جزء = \\(5\\) وجزء = \\(5\\)، فالكل = \\(10\\).',
    correctAnswer: 'true',
    explanation: '٥ + ٥ = ١٠.',
    goldenRule: '٥ + ٥ = ١٠.',
    paragraph: 'تمثيل الجمع — ص ١١٧',
  },

  // ── الدرس 3: جمل الجمع ──────────────────────────────────
  {
    id: 'm1_063', unit: 'ch6', lesson: 'ch6l3', page: 118, difficulty: 'easy',
    type: 'multipleChoice', useKatex: true,
    question: 'ما ناتج الجمع \\(3 + 2\\)؟',
    options: [
      { text: '٥', correct: true },
      { text: '١', correct: false },
      { text: '٦', correct: false },
      { text: '٤', correct: false },
    ],
    explanation: '٣ + ٢ = ٥.',
    goldenRule: '٣ + ٢ = ٥.',
    paragraph: 'جمل الجمع — ص ١١٨',
  },
  {
    id: 'm1_064', unit: 'ch6', lesson: 'ch6l3', page: 118, difficulty: 'easy',
    type: 'trueFalse', useKatex: true,
    question: 'جملة الجمع \\(2 + 1 = 3\\) صحيحة.',
    correctAnswer: 'true',
    explanation: '٢ + ١ = ٣ صحيح.',
    goldenRule: '٢ + ١ = ٣.',
    paragraph: 'جمل الجمع — ص ١١٨',
  },
  {
    id: 'm1_065', unit: 'ch6', lesson: 'ch6l3', page: 119, difficulty: 'medium',
    type: 'multipleChoice', useKatex: true,
    question: 'ما ناتج \\(4 + 5\\)؟',
    options: [
      { text: '٩', correct: true },
      { text: '١', correct: false },
      { text: '١٠', correct: false },
      { text: '٨', correct: false },
    ],
    explanation: '٤ + ٥ = ٩.',
    goldenRule: '٤ + ٥ = ٩.',
    paragraph: 'جمل الجمع — ص ١١٩',
  },
  {
    id: 'm1_066', unit: 'ch6', lesson: 'ch6l3', page: 119, difficulty: 'medium',
    type: 'multipleChoice', useKatex: true,
    question: 'ما ناتج \\(3 + 4\\)؟',
    options: [
      { text: '٧', correct: true },
      { text: '١', correct: false },
      { text: '٦', correct: false },
      { text: '٨', correct: false },
    ],
    explanation: '٣ + ٤ = ٧.',
    goldenRule: '٣ + ٤ = ٧.',
    paragraph: 'جمل الجمع — ص ١١٩',
  },
  {
    id: 'm1_067', unit: 'ch6', lesson: 'ch6l3', page: 119, difficulty: 'medium',
    type: 'multipleChoice', useKatex: true,
    question: 'ما ناتج \\(5 + 2\\)؟',
    options: [
      { text: '٧', correct: true },
      { text: '٣', correct: false },
      { text: '٨', correct: false },
      { text: '٦', correct: false },
    ],
    explanation: '٥ + ٢ = ٧.',
    goldenRule: '٥ + ٢ = ٧.',
    paragraph: 'جمل الجمع — ص ١١٩',
  },
  {
    id: 'm1_068', unit: 'ch6', lesson: 'ch6l3', page: 119, difficulty: 'hard',
    type: 'multipleChoice', useKatex: true,
    question: 'في جملة الجمع \\(? + 3 = 6\\)، ما العدد المجهول؟',
    options: [
      { text: '٣', correct: true },
      { text: '٢', correct: false },
      { text: '٤', correct: false },
      { text: '٩', correct: false },
    ],
    explanation: '٦ - ٣ = ٣. فالعدد المجهول هو ٣.',
    goldenRule: 'لإيجاد العدد المجهول: الكل - الجزء المعلوم = الجزء المجهول.',
    paragraph: 'جمل الجمع — ص ١١٩',
  },

  // ── الدرس 4: الجمع إلى الصفر ────────────────────────────
  {
    id: 'm1_069', unit: 'ch6', lesson: 'ch6l4', page: 120, difficulty: 'easy',
    type: 'multipleChoice', useKatex: true,
    question: 'ما ناتج \\(4 + 0\\)؟',
    options: [
      { text: '٤', correct: true },
      { text: '٠', correct: false },
      { text: '٥', correct: false },
      { text: '٣', correct: false },
    ],
    explanation: '٤ + ٠ = ٤. الجمع إلى الصفر لا يغيّر العدد.',
    goldenRule: 'أي عدد + ٠ = نفس العدد.',
    paragraph: 'الجمع إلى الصفر — ص ١٢٠',
  },
  {
    id: 'm1_070', unit: 'ch6', lesson: 'ch6l4', page: 120, difficulty: 'easy',
    type: 'trueFalse', useKatex: true,
    question: '\\(0 + 5 = 5\\) صحيح.',
    correctAnswer: 'true',
    explanation: '٠ + ٥ = ٥. الصفر لا يضيف شيئاً للعدد.',
    goldenRule: '٠ + أي عدد = نفس العدد.',
    paragraph: 'الجمع إلى الصفر — ص ١٢٠',
  },
  {
    id: 'm1_071', unit: 'ch6', lesson: 'ch6l4', page: 121, difficulty: 'easy',
    type: 'multipleChoice', useKatex: true,
    question: 'ما ناتج \\(7 + 0\\)؟',
    options: [
      { text: '٧', correct: true },
      { text: '٠', correct: false },
      { text: '١', correct: false },
      { text: '٦', correct: false },
    ],
    explanation: '٧ + ٠ = ٧.',
    goldenRule: '٧ + ٠ = ٧.',
    paragraph: 'الجمع إلى الصفر — ص ١٢١',
  },
  {
    id: 'm1_072', unit: 'ch6', lesson: 'ch6l4', page: 121, difficulty: 'medium',
    type: 'multipleChoice', useKatex: true,
    question: 'ما ناتج \\(0 + 9\\)؟',
    options: [
      { text: '٩', correct: true },
      { text: '١', correct: false },
      { text: '٠', correct: false },
      { text: '١٠', correct: false },
    ],
    explanation: '٠ + ٩ = ٩.',
    goldenRule: '٠ + ٩ = ٩.',
    paragraph: 'الجمع إلى الصفر — ص ١٢١',
  },
  {
    id: 'm1_073', unit: 'ch6', lesson: 'ch6l4', page: 121, difficulty: 'medium',
    type: 'multipleChoice', useKatex: true,
    question: 'ما ناتج \\(8 + 0\\)؟',
    options: [
      { text: '٨', correct: true },
      { text: '٠', correct: false },
      { text: '٩', correct: false },
      { text: '٧', correct: false },
    ],
    explanation: '٨ + ٠ = ٨.',
    goldenRule: '٨ + ٠ = ٨.',
    paragraph: 'الجمع إلى الصفر — ص ١٢١',
  },
  {
    id: 'm1_074', unit: 'ch6', lesson: 'ch6l4', page: 121, difficulty: 'hard',
    type: 'multipleChoice', useKatex: true,
    question: 'في جملة \\(? + 0 = 6\\)، ما العدد المجهول؟',
    options: [
      { text: '٦', correct: true },
      { text: '٧', correct: false },
      { text: '٠', correct: false },
      { text: '٥', correct: false },
    ],
    explanation: 'العدد المجهول + ٠ = ٦ → العدد المجهول = ٦.',
    goldenRule: 'عدد + ٠ = نفس العدد، فالعدد المجهول = ٦.',
    paragraph: 'الجمع إلى الصفر — ص ١٢١',
  },

  // ── الدرس 5: أحل المسألة بالتمثيل ───────────────────────
  {
    id: 'm1_075', unit: 'ch6', lesson: 'ch6l5', page: 124, difficulty: 'medium',
    type: 'multipleChoice', useKatex: true,
    question: 'في مسألة: يوجد \\(5\\) فرسان في القلعة و \\(3\\) فرسان خارجها. كم مجموع الفرسان؟',
    options: [
      { text: '٨ فرسان', correct: true },
      { text: '٢ فرسان', correct: false },
      { text: '٧ فرسان', correct: false },
      { text: '٩ فرسان', correct: false },
    ],
    explanation: '٥ + ٣ = ٨ فرسان.',
    goldenRule: 'نمثّل المسألة بالصور أو الرسوم ثم نكتب جملة الجمع.',
    paragraph: 'أحل المسألة — ص ١٢٤',
  },
  {
    id: 'm1_076', unit: 'ch6', lesson: 'ch6l5', page: 125, difficulty: 'medium',
    type: 'multipleChoice', useKatex: true,
    question: 'مسألة: \\(4\\) تماسيح على الجانب الأيمن و \\(3\\) تماسيح على الجانب الأيسر. كم المجموع؟',
    options: [
      { text: '٧ تماسيح', correct: true },
      { text: '١ تمساح', correct: false },
      { text: '٦ تماسيح', correct: false },
      { text: '٨ تماسيح', correct: false },
    ],
    explanation: '٤ + ٣ = ٧ تماسيح.',
    goldenRule: '٤ + ٣ = ٧.',
    paragraph: 'أحل المسألة — ص ١٢٥',
  },
  {
    id: 'm1_077', unit: 'ch6', lesson: 'ch6l5', page: 125, difficulty: 'hard',
    type: 'multipleChoice', useKatex: true,
    question: 'في مسألة: مجموع مجموعتين = \\(8\\)، إحداهما فيها \\(3\\) عناصر. كم في المجموعة الأخرى؟',
    options: [
      { text: '٥', correct: true },
      { text: '١١', correct: false },
      { text: '٤', correct: false },
      { text: '٢', correct: false },
    ],
    explanation: 'الجزء الثاني = ٨ - ٣ = ٥.',
    goldenRule: 'الجزء المجهول = الكل - الجزء المعلوم.',
    paragraph: 'أحل المسألة — ص ١٢٥',
  },

  // ── الدرس 6: تكوين الأعداد 4 و 5 و 6 ────────────────────
  {
    id: 'm1_078', unit: 'ch6', lesson: 'ch6l6', page: 126, difficulty: 'easy',
    type: 'multipleChoice', useKatex: true,
    question: 'أيّ جملتَي الجمع التاليتين يُمكن بهما تكوين العدد \\(4\\)؟',
    options: [
      { text: '\\(1 + 3 = 4\\) و \\(2 + 2 = 4\\)', correct: true },
      { text: '\\(1 + 2 = 3\\) و \\(3 + 3 = 6\\)', correct: false },
      { text: '\\(2 + 3 = 5\\) و \\(1 + 4 = 5\\)', correct: false },
      { text: '\\(0 + 3 = 3\\) و \\(2 + 1 = 3\\)', correct: false },
    ],
    explanation: 'العدد ٤ يمكن تكوينه بـ: ١+٣=٤ أو ٢+٢=٤ أو ٤+٠=٤.',
    goldenRule: 'للعدد ٤: ١+٣، ٢+٢، ٣+١، ٤+٠.',
    paragraph: 'تكوين الأعداد ٤، ٥، ٦ — ص ١٢٦',
  },
  {
    id: 'm1_079', unit: 'ch6', lesson: 'ch6l6', page: 126, difficulty: 'easy',
    type: 'trueFalse', useKatex: true,
    question: '\\(2 + 3 = 5\\) يُمثّل طريقة لتكوين العدد \\(5\\).',
    correctAnswer: 'true',
    explanation: 'نعم، ٢ + ٣ = ٥، وهذه إحدى طرق تكوين العدد ٥.',
    goldenRule: 'للعدد ٥: ١+٤، ٢+٣، ٣+٢، ٤+١، ٥+٠.',
    paragraph: 'تكوين الأعداد ٤، ٥، ٦ — ص ١٢٦',
  },
  {
    id: 'm1_080', unit: 'ch6', lesson: 'ch6l6', page: 127, difficulty: 'medium',
    type: 'multipleChoice', useKatex: true,
    question: 'كم طريقة يمكن بها تكوين العدد \\(5\\) بجمع عددين من \\(0\\) إلى \\(5\\)؟',
    options: [
      { text: '٦ طرق', correct: true },
      { text: '٥ طرق', correct: false },
      { text: '٤ طرق', correct: false },
      { text: '٣ طرق', correct: false },
    ],
    explanation: 'طرق تكوين ٥: ٠+٥، ١+٤، ٢+٣، ٣+٢، ٤+١، ٥+٠ = ٦ طرق.',
    goldenRule: 'عدد طرق تكوين العدد ن = (ن+١) طريقة.',
    paragraph: 'تكوين الأعداد ٤، ٥، ٦ — ص ١٢٧',
  },
  {
    id: 'm1_081', unit: 'ch6', lesson: 'ch6l6', page: 127, difficulty: 'medium',
    type: 'multipleChoice', useKatex: true,
    question: 'أيّ جملة الجمع التالية تُكوّن العدد \\(6\\)؟',
    options: [
      { text: '\\(4 + 2 = 6\\)', correct: true },
      { text: '\\(4 + 3 = 7\\)', correct: false },
      { text: '\\(3 + 2 = 5\\)', correct: false },
      { text: '\\(5 + 2 = 7\\)', correct: false },
    ],
    explanation: '٤ + ٢ = ٦، وهذا يُكوّن العدد ٦.',
    goldenRule: 'للعدد ٦: ١+٥، ٢+٤، ٣+٣، ٤+٢، ٥+١، ٦+٠.',
    paragraph: 'تكوين الأعداد ٤، ٥، ٦ — ص ١٢٧',
  },

  // ── الدرس 7: تكوين الأعداد 7 و 8 و 9 ────────────────────
  {
    id: 'm1_082', unit: 'ch6', lesson: 'ch6l7', page: 128, difficulty: 'easy',
    type: 'multipleChoice', useKatex: true,
    question: 'ما ناتج \\(6 + 1\\)؟',
    options: [
      { text: '٧', correct: true },
      { text: '٥', correct: false },
      { text: '٨', correct: false },
      { text: '٦', correct: false },
    ],
    explanation: '٦ + ١ = ٧.',
    goldenRule: '٦ + ١ = ٧.',
    paragraph: 'تكوين الأعداد ٧، ٨، ٩ — ص ١٢٨',
  },
  {
    id: 'm1_083', unit: 'ch6', lesson: 'ch6l7', page: 128, difficulty: 'easy',
    type: 'trueFalse', useKatex: true,
    question: '\\(4 + 3 = 7\\) صحيحة.',
    correctAnswer: 'true',
    explanation: '٤ + ٣ = ٧ صحيح.',
    goldenRule: '٤ + ٣ = ٧.',
    paragraph: 'تكوين الأعداد ٧، ٨، ٩ — ص ١٢٨',
  },
  {
    id: 'm1_084', unit: 'ch6', lesson: 'ch6l7', page: 128, difficulty: 'medium',
    type: 'multipleChoice', useKatex: true,
    question: 'أيُّ الجمل التالية تُكوّن العدد \\(7\\)؟',
    options: [
      { text: '\\(5 + 2 = 7\\)', correct: true },
      { text: '\\(5 + 3 = 8\\)', correct: false },
      { text: '\\(4 + 4 = 8\\)', correct: false },
      { text: '\\(6 + 2 = 8\\)', correct: false },
    ],
    explanation: '٥ + ٢ = ٧.',
    goldenRule: 'للعدد ٧: ١+٦، ٢+٥، ٣+٤، ٤+٣، ٥+٢، ٦+١، ٧+٠.',
    paragraph: 'تكوين الأعداد ٧، ٨، ٩ — ص ١٢٨',
  },
  {
    id: 'm1_085', unit: 'ch6', lesson: 'ch6l7', page: 129, difficulty: 'easy',
    type: 'multipleChoice', useKatex: true,
    question: 'ما ناتج \\(5 + 3\\)؟',
    options: [
      { text: '٨', correct: true },
      { text: '٢', correct: false },
      { text: '٧', correct: false },
      { text: '٩', correct: false },
    ],
    explanation: '٥ + ٣ = ٨.',
    goldenRule: '٥ + ٣ = ٨.',
    paragraph: 'تكوين الأعداد ٧، ٨، ٩ — ص ١٢٩',
  },
  {
    id: 'm1_086', unit: 'ch6', lesson: 'ch6l7', page: 129, difficulty: 'medium',
    type: 'multipleChoice', useKatex: true,
    question: 'ما ناتج \\(4 + 5\\)؟',
    options: [
      { text: '٩', correct: true },
      { text: '١', correct: false },
      { text: '١٠', correct: false },
      { text: '٨', correct: false },
    ],
    explanation: '٤ + ٥ = ٩.',
    goldenRule: '٤ + ٥ = ٩.',
    paragraph: 'تكوين الأعداد ٧، ٨، ٩ — ص ١٢٩',
  },
  {
    id: 'm1_087', unit: 'ch6', lesson: 'ch6l7', page: 129, difficulty: 'hard',
    type: 'multipleChoice', useKatex: true,
    question: 'في جملة \\(? + 4 = 9\\)، ما العدد المجهول؟',
    options: [
      { text: '٥', correct: true },
      { text: '١٣', correct: false },
      { text: '٤', correct: false },
      { text: '٣', correct: false },
    ],
    explanation: 'العدد المجهول = ٩ - ٤ = ٥.',
    goldenRule: 'العدد المجهول = الكل - الجزء المعلوم.',
    paragraph: 'تكوين الأعداد ٧، ٨، ٩ — ص ١٢٩',
  },

  // ── الدرس 8: تكوين الأعداد 10 و 11 و 12 ─────────────────
  {
    id: 'm1_088', unit: 'ch6', lesson: 'ch6l8', page: 130, difficulty: 'easy',
    type: 'multipleChoice', useKatex: true,
    question: 'ما ناتج \\(6 + 4\\)؟',
    options: [
      { text: '١٠', correct: true },
      { text: '٢', correct: false },
      { text: '١١', correct: false },
      { text: '٩', correct: false },
    ],
    explanation: '٦ + ٤ = ١٠.',
    goldenRule: '٦ + ٤ = ١٠.',
    paragraph: 'تكوين الأعداد ١٠، ١١، ١٢ — ص ١٣٠',
  },
  {
    id: 'm1_089', unit: 'ch6', lesson: 'ch6l8', page: 130, difficulty: 'easy',
    type: 'trueFalse', useKatex: true,
    question: '\\(5 + 5 = 10\\) صحيحة.',
    correctAnswer: 'true',
    explanation: '٥ + ٥ = ١٠ صحيح.',
    goldenRule: '٥ + ٥ = ١٠ (الأعداد المتساوية).',
    paragraph: 'تكوين الأعداد ١٠، ١١، ١٢ — ص ١٣٠',
  },
  {
    id: 'm1_090', unit: 'ch6', lesson: 'ch6l8', page: 130, difficulty: 'medium',
    type: 'multipleChoice', useKatex: true,
    question: 'ما ناتج \\(8 + 3\\)؟',
    options: [
      { text: '١١', correct: true },
      { text: '٥', correct: false },
      { text: '١٢', correct: false },
      { text: '١٠', correct: false },
    ],
    explanation: '٨ + ٣ = ١١.',
    goldenRule: '٨ + ٣ = ١١.',
    paragraph: 'تكوين الأعداد ١٠، ١١، ١٢ — ص ١٣٠',
  },
  {
    id: 'm1_091', unit: 'ch6', lesson: 'ch6l8', page: 131, difficulty: 'medium',
    type: 'multipleChoice', useKatex: true,
    question: 'ما ناتج \\(7 + 5\\)؟',
    options: [
      { text: '١٢', correct: true },
      { text: '٢', correct: false },
      { text: '١١', correct: false },
      { text: '١٣', correct: false },
    ],
    explanation: '٧ + ٥ = ١٢.',
    goldenRule: '٧ + ٥ = ١٢.',
    paragraph: 'تكوين الأعداد ١٠، ١١، ١٢ — ص ١٣١',
  },
  {
    id: 'm1_092', unit: 'ch6', lesson: 'ch6l8', page: 131, difficulty: 'hard',
    type: 'multipleChoice', useKatex: true,
    question: 'في جملة \\(9 + ? = 11\\)، ما العدد المجهول؟',
    options: [
      { text: '٢', correct: true },
      { text: '٢٠', correct: false },
      { text: '١', correct: false },
      { text: '٣', correct: false },
    ],
    explanation: '١١ - ٩ = ٢. فالعدد المجهول = ٢.',
    goldenRule: 'العدد المجهول = ١١ - ٩ = ٢.',
    paragraph: 'تكوين الأعداد ١٠، ١١، ١٢ — ص ١٣١',
  },
  {
    id: 'm1_093', unit: 'ch6', lesson: 'ch6l8', page: 131, difficulty: 'hard',
    type: 'multipleChoice', useKatex: true,
    question: 'في جملة \\(4 + ? = 12\\)، ما العدد المجهول؟',
    options: [
      { text: '٨', correct: true },
      { text: '١٦', correct: false },
      { text: '٧', correct: false },
      { text: '٩', correct: false },
    ],
    explanation: '١٢ - ٤ = ٨. فالعدد المجهول = ٨.',
    goldenRule: 'العدد المجهول = ١٢ - ٤ = ٨.',
    paragraph: 'تكوين الأعداد ١٠، ١١، ١٢ — ص ١٣١',
  },

  // ── الدرس 9: الجمع الرأسي ────────────────────────────────
  {
    id: 'm1_094', unit: 'ch6', lesson: 'ch6l9', page: 132, difficulty: 'easy',
    type: 'multipleChoice', useKatex: true,
    question: 'ما ناتج الجمع الرأسي: \\(\\begin{array}{r} 3 \\\\ +\\ 2 \\\\ \\hline \\end{array}\\)؟',
    options: [
      { text: '٥', correct: true },
      { text: '١', correct: false },
      { text: '٦', correct: false },
      { text: '٤', correct: false },
    ],
    explanation: '٣ + ٢ = ٥ في الجمع الرأسي كما في الأفقي.',
    goldenRule: 'الجمع الرأسي = جمع مرتّب عمودياً، الناتج هو نفسه.',
    paragraph: 'الجمع الرأسي — ص ١٣٢',
  },
  {
    id: 'm1_095', unit: 'ch6', lesson: 'ch6l9', page: 132, difficulty: 'easy',
    type: 'trueFalse', useKatex: true,
    question: 'الجمع الرأسي \\(\\frac{5}{+\\ 4}\\) يُعطي نفس الناتج كـ \\(5 + 4\\) الأفقي.',
    correctAnswer: 'true',
    explanation: 'نعم، ٥ + ٤ = ٩ سواء كان الجمع أفقياً أم رأسياً.',
    goldenRule: 'الجمع الأفقي = الجمع الرأسي في الناتج.',
    paragraph: 'الجمع الرأسي — ص ١٣٢',
  },
  {
    id: 'm1_096', unit: 'ch6', lesson: 'ch6l9', page: 132, difficulty: 'medium',
    type: 'multipleChoice', useKatex: true,
    question: 'ما ناتج: \\(\\begin{array}{r} 6 \\\\ +\\ 5 \\\\ \\hline \\end{array}\\)؟',
    options: [
      { text: '١١', correct: true },
      { text: '١', correct: false },
      { text: '١٢', correct: false },
      { text: '١٠', correct: false },
    ],
    explanation: '٦ + ٥ = ١١.',
    goldenRule: '٦ + ٥ = ١١.',
    paragraph: 'الجمع الرأسي — ص ١٣٢',
  },
  {
    id: 'm1_097', unit: 'ch6', lesson: 'ch6l9', page: 133, difficulty: 'medium',
    type: 'multipleChoice', useKatex: true,
    question: 'ما ناتج: \\(\\begin{array}{r} 7 \\\\ +\\ 3 \\\\ \\hline \\end{array}\\)؟',
    options: [
      { text: '١٠', correct: true },
      { text: '٤', correct: false },
      { text: '١١', correct: false },
      { text: '٩', correct: false },
    ],
    explanation: '٧ + ٣ = ١٠.',
    goldenRule: '٧ + ٣ = ١٠.',
    paragraph: 'الجمع الرأسي — ص ١٣٣',
  },
  {
    id: 'm1_098', unit: 'ch6', lesson: 'ch6l9', page: 133, difficulty: 'hard',
    type: 'multipleChoice', useKatex: true,
    question: 'ما ناتج: \\(\\begin{array}{r} 8 \\\\ +\\ 4 \\\\ \\hline \\end{array}\\)؟',
    options: [
      { text: '١٢', correct: true },
      { text: '٤', correct: false },
      { text: '١١', correct: false },
      { text: '١٣', correct: false },
    ],
    explanation: '٨ + ٤ = ١٢.',
    goldenRule: '٨ + ٤ = ١٢.',
    paragraph: 'الجمع الرأسي — ص ١٣٣',
  },

  // ══════════════════════════════════════════════════════════
  // أسئلة إضافية — الفصل السادس (تنويع)
  // ══════════════════════════════════════════════════════════

  {
    id: 'm1_099', unit: 'ch6', lesson: 'ch6l3', page: 118, difficulty: 'easy',
    type: 'multipleChoice', useKatex: true,
    question: 'ما ناتج \\(1 + 1\\)؟',
    options: [
      { text: '٢', correct: true },
      { text: '١', correct: false },
      { text: '٣', correct: false },
      { text: '٠', correct: false },
    ],
    explanation: '١ + ١ = ٢.',
    goldenRule: '١ + ١ = ٢.',
    paragraph: 'جمل الجمع — ص ١١٨',
  },
  {
    id: 'm1_100', unit: 'ch6', lesson: 'ch6l3', page: 119, difficulty: 'easy',
    type: 'multipleChoice', useKatex: true,
    question: 'ما ناتج \\(2 + 2\\)؟',
    options: [
      { text: '٤', correct: true },
      { text: '٢', correct: false },
      { text: '٥', correct: false },
      { text: '٣', correct: false },
    ],
    explanation: '٢ + ٢ = ٤.',
    goldenRule: '٢ + ٢ = ٤.',
    paragraph: 'جمل الجمع — ص ١١٩',
  },
  {
    id: 'm1_101', unit: 'ch6', lesson: 'ch6l3', page: 119, difficulty: 'easy',
    type: 'multipleChoice', useKatex: true,
    question: 'ما ناتج \\(3 + 3\\)؟',
    options: [
      { text: '٦', correct: true },
      { text: '٣', correct: false },
      { text: '٧', correct: false },
      { text: '٥', correct: false },
    ],
    explanation: '٣ + ٣ = ٦.',
    goldenRule: '٣ + ٣ = ٦.',
    paragraph: 'جمل الجمع — ص ١١٩',
  },
  {
    id: 'm1_102', unit: 'ch6', lesson: 'ch6l3', page: 119, difficulty: 'medium',
    type: 'multipleChoice', useKatex: true,
    question: 'ما ناتج \\(4 + 4\\)؟',
    options: [
      { text: '٨', correct: true },
      { text: '٤', correct: false },
      { text: '٩', correct: false },
      { text: '٧', correct: false },
    ],
    explanation: '٤ + ٤ = ٨.',
    goldenRule: '٤ + ٤ = ٨.',
    paragraph: 'جمل الجمع — ص ١١٩',
  },
  {
    id: 'm1_103', unit: 'ch6', lesson: 'ch6l4', page: 121, difficulty: 'easy',
    type: 'multipleChoice', useKatex: true,
    question: 'ما ناتج \\(0 + 0\\)؟',
    options: [
      { text: '٠', correct: true },
      { text: '١', correct: false },
      { text: '٢', correct: false },
      { text: 'لا يمكن حسابه', correct: false },
    ],
    explanation: '٠ + ٠ = ٠. الصفر زائد الصفر يساوي الصفر.',
    goldenRule: '٠ + ٠ = ٠.',
    paragraph: 'الجمع إلى الصفر — ص ١٢١',
  },
  {
    id: 'm1_104', unit: 'ch6', lesson: 'ch6l4', page: 121, difficulty: 'medium',
    type: 'multipleChoice', useKatex: true,
    question: 'ما ناتج \\(1 + 2\\)؟',
    options: [
      { text: '٣', correct: true },
      { text: '١', correct: false },
      { text: '٢', correct: false },
      { text: '٤', correct: false },
    ],
    explanation: '١ + ٢ = ٣.',
    goldenRule: '١ + ٢ = ٣.',
    paragraph: 'جمل الجمع — ص ١١٩',
  },
  {
    id: 'm1_105', unit: 'ch6', lesson: 'ch6l7', page: 128, difficulty: 'easy',
    type: 'multipleChoice', useKatex: true,
    question: 'ما ناتج \\(3 + 5\\)؟',
    options: [
      { text: '٨', correct: true },
      { text: '٢', correct: false },
      { text: '٩', correct: false },
      { text: '٧', correct: false },
    ],
    explanation: '٣ + ٥ = ٨.',
    goldenRule: '٣ + ٥ = ٨.',
    paragraph: 'تكوين الأعداد ٧، ٨، ٩ — ص ١٢٨',
  },
  {
    id: 'm1_106', unit: 'ch6', lesson: 'ch6l8', page: 130, difficulty: 'medium',
    type: 'multipleChoice', useKatex: true,
    question: 'ما ناتج \\(9 + 1\\)؟',
    options: [
      { text: '١٠', correct: true },
      { text: '٨', correct: false },
      { text: '١١', correct: false },
      { text: '٩', correct: false },
    ],
    explanation: '٩ + ١ = ١٠.',
    goldenRule: '٩ + ١ = ١٠.',
    paragraph: 'تكوين الأعداد ١٠، ١١، ١٢ — ص ١٣٠',
  },
  {
    id: 'm1_107', unit: 'ch6', lesson: 'ch6l8', page: 130, difficulty: 'medium',
    type: 'multipleChoice', useKatex: true,
    question: 'ما ناتج \\(4 + 8\\)؟',
    options: [
      { text: '١٢', correct: true },
      { text: '٤', correct: false },
      { text: '١١', correct: false },
      { text: '١٣', correct: false },
    ],
    explanation: '٤ + ٨ = ١٢.',
    goldenRule: '٤ + ٨ = ١٢.',
    paragraph: 'تكوين الأعداد ١٠، ١١، ١٢ — ص ١٣٠',
  },

  // ══════════════════════════════════════════════════════════
  // أسئلة إثرائية — ترتيب وتصنيف
  // ══════════════════════════════════════════════════════════

  {
    id: 'm1_108', unit: 'ch6', lesson: 'ch6l6', page: 126, difficulty: 'medium',
    type: 'classify',
    question: 'صنّف جمل الجمع التالية حسب ناتجها:',
    categories: ['الناتج ٥', 'الناتج ٦'],
    items: [
      { text: '٣ + ٢', correct_category: 0 },
      { text: '٤ + ١', correct_category: 0 },
      { text: '٤ + ٢', correct_category: 1 },
      { text: '٣ + ٣', correct_category: 1 },
    ],
    explanation: '٣+٢=٥، ٤+١=٥ (ناتجها ٥). ٤+٢=٦، ٣+٣=٦ (ناتجها ٦).',
    goldenRule: 'نحسب كل جملة جمع بدقة قبل تصنيفها.',
    paragraph: 'تكوين الأعداد ٤، ٥، ٦ — ص ١٢٦-١٢٧',
  },
  {
    id: 'm1_109', unit: 'ch6', lesson: 'ch6l7', page: 128, difficulty: 'hard',
    type: 'classify',
    question: 'صنّف جمل الجمع التالية:',
    categories: ['الناتج ٧', 'الناتج ٨'],
    items: [
      { text: '٤ + ٣', correct_category: 0 },
      { text: '٦ + ١', correct_category: 0 },
      { text: '٥ + ٣', correct_category: 1 },
      { text: '٤ + ٤', correct_category: 1 },
    ],
    explanation: '٤+٣=٧، ٦+١=٧ (ناتجها ٧). ٥+٣=٨، ٤+٤=٨ (ناتجها ٨).',
    goldenRule: 'طرق تكوين العدد متعددة لكن الناتج واحد.',
    paragraph: 'تكوين الأعداد ٧، ٨، ٩ — ص ١٢٨-١٢٩',
  },
  {
    id: 'm1_110', unit: 'ch6', lesson: 'ch6l9', page: 132, difficulty: 'medium',
    type: 'ordering',
    question: 'رتّب نتائج الجمع التالية من الأصغر إلى الأكبر:',
    items: ['٣+٥', '١+٢', '٤+٦', '٢+٣'],
    correctOrder: [1, 3, 0, 2],
    explanation: '١+٢=٣، ٢+٣=٥، ٣+٥=٨، ٤+٦=١٠. الترتيب: ٣، ٥، ٨، ١٠.',
    goldenRule: 'نحسب كل ناتج ثم نرتب النتائج.',
    paragraph: 'الجمع الرأسي — ص ١٣٢-١٣٣',
  },

  // أسئلة منوعة إضافية لإكمال 300
  {
    id: 'm1_111', unit: 'ch1', lesson: 'ch1l1', page: 5, difficulty: 'easy',
    type: 'multipleChoice',
    question: 'مجموعة تحتوي على ٢ كتاب. ما العدد الذي يُمثّلها؟',
    options: [
      { text: '٢', correct: true },
      { text: '١', correct: false },
      { text: '٣', correct: false },
      { text: '٠', correct: false },
    ],
    explanation: 'كتابان = العدد ٢.',
    goldenRule: 'نعدّ ونكتب العدد المناسب.',
    paragraph: 'الأعداد ١ و ٢ — ص ٥',
  },
  {
    id: 'm1_112', unit: 'ch1', lesson: 'ch1l2', page: 14, difficulty: 'easy',
    type: 'multipleChoice',
    question: 'مجموعة تحتوي على ٤ مثلثات. ما العدد الذي يُمثّلها؟',
    options: [
      { text: '٤', correct: true },
      { text: '٣', correct: false },
      { text: '٥', correct: false },
      { text: '٢', correct: false },
    ],
    explanation: 'أربعة مثلثات = العدد ٤.',
    goldenRule: 'نعدّ العناصر ونكتب العدد المناسب.',
    paragraph: 'الأعداد ٣ و ٤ — ص ١٤',
  },
  {
    id: 'm1_113', unit: 'ch6', lesson: 'ch6l3', page: 118, difficulty: 'easy',
    type: 'multipleChoice', useKatex: true,
    question: 'ما ناتج \\(0 + 1\\)؟',
    options: [
      { text: '١', correct: true },
      { text: '٠', correct: false },
      { text: '٢', correct: false },
      { text: '١٠', correct: false },
    ],
    explanation: '٠ + ١ = ١.',
    goldenRule: '٠ + أي عدد = نفس العدد.',
    paragraph: 'جمل الجمع — ص ١١٨',
  },
  {
    id: 'm1_114', unit: 'ch6', lesson: 'ch6l3', page: 119, difficulty: 'medium',
    type: 'multipleChoice', useKatex: true,
    question: 'ما ناتج \\(1 + 6\\)؟',
    options: [
      { text: '٧', correct: true },
      { text: '٥', correct: false },
      { text: '٨', correct: false },
      { text: '٦', correct: false },
    ],
    explanation: '١ + ٦ = ٧.',
    goldenRule: '١ + ٦ = ٧.',
    paragraph: 'جمل الجمع — ص ١١٩',
  },
  {
    id: 'm1_115', unit: 'ch6', lesson: 'ch6l8', page: 130, difficulty: 'medium',
    type: 'multipleChoice', useKatex: true,
    question: 'ما ناتج \\(5 + 7\\)؟',
    options: [
      { text: '١٢', correct: true },
      { text: '٢', correct: false },
      { text: '١١', correct: false },
      { text: '١٣', correct: false },
    ],
    explanation: '٥ + ٧ = ١٢.',
    goldenRule: '٥ + ٧ = ١٢.',
    paragraph: 'تكوين الأعداد ١٠، ١١، ١٢ — ص ١٣٠',
  },
  {
    id: 'm1_116', unit: 'ch2', lesson: 'ch2l2', page: 62, difficulty: 'medium',
    type: 'multipleChoice', useKatex: true,
    question: 'أيّ العبارات الآتية خاطئة؟',
    options: [
      { text: '\\(5 < 3\\)', correct: true },
      { text: '\\(3 < 5\\)', correct: false },
      { text: '\\(4 > 2\\)', correct: false },
      { text: '\\(1 < 4\\)', correct: false },
    ],
    explanation: '٥ > ٣ وليس ٥ < ٣، فالعبارة ٥ < ٣ خاطئة.',
    goldenRule: 'تحقق دائماً من اتجاه رمز المقارنة.',
    paragraph: 'المقارنة بالأعداد — ص ٦٢',
  },
  {
    id: 'm1_117', unit: 'ch3', lesson: 'ch3l1', page: 83, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'ما العدد الذي يأتي بعد ٦ مباشرةً؟',
    options: [
      { text: '٧', correct: true },
      { text: '٥', correct: false },
      { text: '٨', correct: false },
      { text: '٦', correct: false },
    ],
    explanation: 'الترتيب: ...٥، ٦، ٧... فالعدد الذي يأتي بعد ٦ هو ٧.',
    goldenRule: 'كل عدد يأتي بعده العدد الذي يكبره بمقدار ١.',
    paragraph: 'الأعداد ٦ و ٧ — ص ٨٣',
  },
  {
    id: 'm1_118', unit: 'ch5', lesson: 'ch5l3', page: 102, difficulty: 'medium',
    type: 'multipleChoice',
    question: 'العدد ١٨ يتكون من:',
    options: [
      { text: 'عقد واحد وثمانية آحاد', correct: true },
      { text: 'عقدين وثمانية آحاد', correct: false },
      { text: 'ثمانية عقود', correct: false },
      { text: 'عقد واحد وسبعة آحاد', correct: false },
    ],
    explanation: '١٨ = ١٠ + ٨ = عقد واحد + ثمانية آحاد.',
    goldenRule: '١٨ = عقد واحد + ٨ آحاد.',
    paragraph: 'الأعداد ١٨ إلى ٢٠ — ص ١٠٢',
  },
  {
    id: 'm1_119', unit: 'ch6', lesson: 'ch6l4', page: 120, difficulty: 'easy',
    type: 'trueFalse', useKatex: true,
    question: '\\(3 + 0 = 3\\) صحيحة.',
    correctAnswer: 'true',
    explanation: '٣ + ٠ = ٣. الجمع بالصفر لا يغيّر العدد.',
    goldenRule: 'أي عدد + ٠ = نفس العدد.',
    paragraph: 'الجمع إلى الصفر — ص ١٢٠',
  },
  {
    id: 'm1_120', unit: 'ch6', lesson: 'ch6l7', page: 129, difficulty: 'easy',
    type: 'multipleChoice', useKatex: true,
    question: 'ما ناتج \\(6 + 3\\)؟',
    options: [
      { text: '٩', correct: true },
      { text: '٣', correct: false },
      { text: '١٠', correct: false },
      { text: '٨', correct: false },
    ],
    explanation: '٦ + ٣ = ٩.',
    goldenRule: '٦ + ٣ = ٩.',
    paragraph: 'تكوين الأعداد ٧، ٨، ٩ — ص ١٢٩',
  },
];

export const TOTAL_QUESTIONS_MATH1 = MATH1_S1_QUESTIONS.length;