// بنك "جيل نيوم" — ربط المنهج بمشروع نيوم ورؤية ٢٠٣٠
// كل سؤال مرتبط بصورة تعليمية من سجل eduImages
import { EDU_IMAGES } from '@/lib/eduImages';

export const NEOM_SUBJECTS = [
  {
    id: 'science',
    titleAr: 'العلوم',
    titleEn: 'Science',
    icon: '⚡',
    color: 'from-emerald-500 to-teal-600',
    descAr: 'الطاقة المتجددة والاستدامة البيئية في نيوم',
    descEn: 'Renewable energy & environmental sustainability in NEOM',
    topics: [
      {
        id: 'renewable_energy',
        titleAr: 'الطاقة المتجددة',
        titleEn: 'Renewable Energy',
        questions: [
          {
            question_ar: 'نيوم تعتمد على الطاقة الشمسية. ما الذي تحوله الألواح الشمسية إلى طاقة كهربائية؟',
            question_en: 'NEOM relies on solar energy. What do solar panels convert into electricity?',
            options_ar: ['ضوء الشمس', 'الرياح', 'الماء', 'الغاز'],
            options_en: ['Sunlight', 'Wind', 'Water', 'Gas'],
            correct_answer: '0',
            explanation_ar: 'الألواح الشمسية تحول ضوء الشمس مباشرة إلى طاقة كهربائية عبر الخلايا الكهروضوئية دون انبعاثات.',
            explanation_en: 'Solar panels convert sunlight directly into electricity via photovoltaic cells with zero emissions.',
            image_url: EDU_IMAGES.S_SOLAR,
          },
          {
            question_ar: 'توربينات نيوم الهوائية تستغل الرياح. أي نوع من الطاقة تنتجه؟',
            question_en: "NEOM's wind turbines harness wind. What type of energy do they produce?",
            options_ar: ['طاقة حرارية', 'طاقة كهربائية', 'طاقة نووية', 'طاقة ضوئية'],
            options_en: ['Thermal energy', 'Electrical energy', 'Nuclear energy', 'Light energy'],
            correct_answer: '1',
            explanation_ar: 'الرياح تُدير شفرات التوربين فتُولّد طاقة كهربائية نظيفة ومتجددة.',
            explanation_en: 'Wind spins turbine blades to generate clean, renewable electrical energy.',
            image_url: EDU_IMAGES.S_WIND_VANE,
          },
          {
            question_ar: 'الهيدروجين الأخضر في نيوم يُنتج باستخدام:',
            question_en: 'Green hydrogen in NEOM is produced using:',
            options_ar: ['الفحم والغاز', 'الكهرباء المتجددة وتحليل الماء', 'النفط', 'الطاقة النووية'],
            options_en: ['Coal and gas', 'Renewable electricity and water electrolysis', 'Oil', 'Nuclear energy'],
            correct_answer: '1',
            explanation_ar: 'الهيدروجين الأخضر يُنتج بفصل الماء إلى هيدروجين وأكسجين باستخدام كهرباء متجددة (شمس/رياح) دون انبعاثات.',
            explanation_en: 'Green hydrogen is made by splitting water using renewable electricity with zero emissions.',
            image_url: EDU_IMAGES.S_ENERGY_TYPES,
          },
          {
            question_ar: 'ليكون نيوم منطقة خالية من الانبعاثات الكربونية، يجب أن تعتمد على:',
            question_en: 'For NEOM to be carbon-emission-free, it must rely on:',
            options_ar: ['الوقود الأحفوري', 'الطاقة المتجددة فقط', 'حرق الفحم', 'الديزل'],
            options_en: ['Fossil fuels', 'Renewable energy only', 'Burning coal', 'Diesel'],
            correct_answer: '1',
            explanation_ar: 'الخلو من الكربون يعني الاعتماد الكامل على مصادر متجددة (شمسية/رياح/هيدروجين) دون احتراق وقود أحفوري.',
            explanation_en: 'Carbon-free means relying entirely on renewables without burning fossil fuels.',
            image_url: EDU_IMAGES.S_RECYCLE,
          },
          {
            question_ar: 'أي مما يلي ليس من مصادر الطاقة المتجددة؟',
            question_en: 'Which of the following is NOT a renewable energy source?',
            options_ar: ['الطاقة الشمسية', 'طاقة الرياح', 'النفط', 'الطاقة المائية'],
            options_en: ['Solar', 'Wind', 'Oil', 'Hydropower'],
            correct_answer: '2',
            explanation_ar: 'النفط وقود أحفوري ناضب ينتج انبعاثات كربونية، ولا يتجدد طبيعياً.',
            explanation_en: 'Oil is a finite fossil fuel that emits carbon and does not naturally renew.',
            image_url: EDU_IMAGES.S_ENERGY_TYPES,
          },
          {
            question_ar: 'دورة الماء في نيوم تساهم في تبريد المناخ. ما المرحلة التي تصعد فيها الماء ك بخار؟',
            question_en: 'The water cycle helps cool NEOM. In which stage does water rise as vapor?',
            options_ar: ['التكثف', 'التبخر', 'الهطول', 'التجمد'],
            options_en: ['Condensation', 'Evaporation', 'Precipitation', 'Freezing'],
            correct_answer: '1',
            explanation_ar: 'التبخر هو صعود الماء على شكل بخار بفعل حرارة الشمس ثم يتكثف ليشكل الغيوم.',
            explanation_en: 'Evaporation is water rising as vapor due to solar heat, then condensing into clouds.',
            image_url: EDU_IMAGES.S_WATER_CYCLE2,
          },
        ],
      },
      {
        id: 'sustainability',
        titleAr: 'الاستدامة البيئية',
        titleEn: 'Environmental Sustainability',
        questions: [
          {
            question_ar: 'الاقتصاد الدائري في نيوم يعني:',
            question_en: 'The circular economy in NEOM means:',
            options_ar: ['إلقاء النفايات في البحر', 'إعادة تدوير كل نفايات المدينة واستخدامها', 'حرق النفايات', 'شراء مواد جديدة دائماً'],
            options_en: ['Dumping waste in the sea', 'Recycling and reusing all city waste', 'Burning waste', 'Always buying new materials'],
            correct_answer: '1',
            explanation_ar: 'الاقتصاد الدائري يعيد استخدام المواد ونفاياتها كموارد جديدة فلا هدر ولا تلوث.',
            explanation_en: 'Circular economy reuses materials and waste as new resources — no waste, no pollution.',
            image_url: EDU_IMAGES.S_RECYCLE,
          },
          {
            question_ar: 'البحر الأحمر بجوار نيوم غني بالشعاب المرجانية. لماذا يجب حمايتها؟',
            question_en: 'The Red Sea near NEOM is rich in coral reefs. Why protect them?',
            options_ar: ['لأنها مصدر غذائي فقط', 'لأنها تنظم الحرارة وتحمي التنوع البيولوجي', 'لا فائدة منها', 'لأنها تنتج نفطاً'],
            options_en: ['Only as food', 'They regulate heat and protect biodiversity', 'No benefit', 'They produce oil'],
            correct_answer: '1',
            explanation_ar: 'الشعاب المرجانية موطن لكائنات بحرية وتحمي السواحل وتنظم التوازن البيئي.',
            explanation_en: 'Coral reefs host marine life, protect coastlines, and balance the ecosystem.',
            image_url: EDU_IMAGES.S_OCEAN,
          },
          {
            question_ar: 'أفضل طريقة لتقليل استهلاك الطاقة في مباني نيوم هي:',
            question_en: 'The best way to reduce energy use in NEOM buildings is:',
            options_ar: ['استخدام مصابيح أكثر', 'التصميم المستدام والعزل الحراري', 'إبقاء الأجهزة تعمل', 'زيادة المكيفات'],
            options_en: ['More lamps', 'Sustainable design & thermal insulation', 'Leave devices on', 'More ACs'],
            correct_answer: '1',
            explanation_ar: 'العزل الحراري والتصميم الذكي يقللان الحاجة للتكييف والإضاءة فيوفّران الطاقة.',
            explanation_en: 'Thermal insulation and smart design reduce cooling and lighting needs, saving energy.',
            image_url: EDU_IMAGES.S_LIGHT_BULB,
          },
        ],
      },
    ],
  },
  {
    id: 'math',
    titleAr: 'الرياضيات',
    titleEn: 'Mathematics',
    icon: '📐',
    color: 'from-blue-500 to-indigo-600',
    descAr: 'حسابات ذا لاين والمساحات والطاقة',
    descEn: 'The Line calculations, areas & energy',
    topics: [
      {
        id: 'the_line_geometry',
        titleAr: 'هندسة ذا لاين',
        titleEn: 'The Line Geometry',
        questions: [
          {
            question_ar: '"ذا لاين" مدينة طولها ١٧٠ كم وعرضها ٢٠٠ م. ما مساحتها التقريبية؟',
            question_en: '"The Line" is 170 km long and 200 m wide. What is its approximate area?',
            options_ar: ['٣٤ كم^{2}', '٣٤٠ كم^{2}', '٣٤٠٠ كم^{2}', '١٧ كم^{2}'],
            options_en: ['34 km^{2}', '340 km^{2}', '3400 km^{2}', '17 km^{2}'],
            correct_answer: '0',
            explanation_ar: 'المساحة = الطول × العرض = ١٧٠ × ٠٫٢ = ٣٤ كم^{2} (حوّلنا ٢٠٠ م إلى ٠٫٢ كم).',
            explanation_en: 'Area = length × width = 170 × 0.2 = 34 km^{2} (200 m = 0.2 km).',
            image_url: EDU_IMAGES.M_AREA_RECT,
          },
          {
            question_ar: 'مبنى في ذا لاين ارتفاعه ٥٠٠ م وعرض قاعدته ٣٠ م. ما مساحة واجهته الأمامية؟',
            question_en: 'A building in The Line is 500 m tall with a 30 m base. What is its front face area?',
            options_ar: ['١٥٠٠ م^{2}', '١٥٠٠٠ م^{2}', '٥٣٠ م^{2}', '٥٠٠ م^{2}'],
            options_en: ['1500 m^{2}', '15000 m^{2}', '530 m^{2}', '500 m^{2}'],
            correct_answer: '1',
            explanation_ar: 'مساحة الواجهة = الارتفاع × العرض = ٥٠٠ × ٣٠ = ١٥٠٠٠ م^{2}.',
            explanation_en: 'Face area = height × width = 500 × 30 = 15000 m^{2}.',
            image_url: EDU_IMAGES.M_PERIMETER,
          },
          {
            question_ar: 'خزان طاقة في نيوم على شكل مكعب طول ضلعه ١٠ م. ما حجمه؟',
            question_en: 'An energy tank in NEOM is a cube with 10 m sides. What is its volume?',
            options_ar: ['١٠٠ م^{3}', '١٠٠٠ م^{3}', '١٠ م^{3}', '٣٠ م^{3}'],
            options_en: ['100 m^{3}', '1000 m^{3}', '10 m^{3}', '30 m^{3}'],
            correct_answer: '1',
            explanation_ar: 'حجم المكعب = الضلع^{3} = ١٠ × ١٠ × ١٠ = ١٠٠٠ م^{3}.',
            explanation_en: 'Cube volume = side^{3} = 10 × 10 × 10 = 1000 m^{3}.',
            image_url: EDU_IMAGES.M_VOLUME,
          },
          {
            question_ar: 'ذا لاين تستهلك ١٠٠٪ طاقة متجددة. لو احتاجت ٤٠٠٠ ميجاواط فكم نسبة الانبعاثات؟',
            question_en: 'The Line uses 100% renewable energy. If it needs 4000 MW, what is the emission percentage?',
            options_ar: ['١٠٠٪', '٥٠٪', '٠٪', '٢٥٪'],
            options_en: ['100%', '50%', '0%', '25%'],
            correct_answer: '2',
            explanation_ar: 'بما أن الطاقة متجددة بالكامل فلا انبعاثات كربونية = ٠٪.',
            explanation_en: 'Since energy is fully renewable, carbon emissions = 0%.',
            image_url: EDU_IMAGES.M_PERCENT,
          },
          {
            question_ar: 'لو وفر التصميم الذكي ٣٠٪ من استهلاك الطاقة في مدرسة، وكان الاستهلاك ١٠٠٠ كيلوواط، كم يصبح الاستهلاك الجديد؟',
            question_en: 'If smart design saves 30% of a school energy use (1000 kW), what is the new consumption?',
            options_ar: ['٣٠٠ كيلوواط', '٧٠٠ كيلوواط', '١٣٠٠ كيلوواط', '١٠٠٠ كيلوواط'],
            options_en: ['300 kW', '700 kW', '1300 kW', '1000 kW'],
            correct_answer: '1',
            explanation_ar: 'التوفير = ٣٠٪ من ١٠٠٠ = ٣٠٠، فالاستهلاك الجديد = ١٠٠٠ − ٣٠٠ = ٧٠٠ كيلوواط.',
            explanation_en: 'Saving = 30% of 1000 = 300; new consumption = 1000 − 300 = 700 kW.',
            image_url: EDU_IMAGES.M_BAR_GRAPH,
          },
        ],
      },
      {
        id: 'patterns_architecture',
        titleAr: 'أنماط العمارة',
        titleEn: 'Architectural Patterns',
        questions: [
          {
            question_ar: 'ذي لاين مصمم بشكل خط مستقيم. أي شكل هندسي يمثل ذلك؟',
            question_en: 'The Line is designed as a straight line. Which geometric shape represents it?',
            options_ar: ['دائرة', 'مستطيل طويل', 'مثلث', 'مكعب'],
            options_en: ['Circle', 'Long rectangle', 'Triangle', 'Cube'],
            correct_answer: '1',
            explanation_ar: 'المدينة مستطيل طويل جداً (١٧٠ كم) وضيق (٢٠٠ م) كخط مستقيم.',
            explanation_en: 'The city is a very long (170 km) narrow (200 m) rectangle — a straight line.',
            image_url: EDU_IMAGES.M_2D_SHAPES,
          },
          {
            question_ar: 'في الإحداثيات الجغرافية لنيوم، البحر الأحمر يقع على:',
            question_en: 'In NEOM geographic coordinates, the Red Sea lies to the:',
            options_ar: ['الشرق', 'الغرب', 'الشمال فقط', 'الجنوب فقط'],
            options_en: ['East', 'West', 'North only', 'South only'],
            correct_answer: '1',
            explanation_ar: 'نيوم تقع على الساحل الغربي للسعودية، فالبحر الأحمر غربها.',
            explanation_en: 'NEOM is on Saudi Arabia western coast, so the Red Sea is to its west.',
            image_url: EDU_IMAGES.M_COORDINATE_GRID,
          },
        ],
      },
    ],
  },
  {
    id: 'tech',
    titleAr: 'التقنية والحاسب',
    titleEn: 'Computer & Tech',
    icon: '🤖',
    color: 'from-violet-500 to-purple-600',
    descAr: 'الذكاء الاصطناعي وإنترنت الأشياء والروبوتات',
    descEn: 'AI, IoT & Robotics',
    topics: [
      {
        id: 'ai_iot',
        titleAr: 'الذكاء الاصطناعي وإنترنت الأشياء',
        titleEn: 'AI & IoT',
        questions: [
          {
            question_ar: 'نيوم تدير بنيتها التحتية بالذكاء الاصطناعي. ما الذكاء الاصطناعي (AI)؟',
            question_en: 'NEOM manages infrastructure with AI. What is AI?',
            options_ar: ['أنظمة تحاكي ذكاء الإنسان في التعلم والقرار', 'أجهزة ميكانيكية فقط', 'أسلاك كهربائية', 'برامج رسم فقط'],
            options_en: ['Systems that mimic human intelligence in learning & decisions', 'Mechanical devices only', 'Electrical wires', 'Drawing software only'],
            correct_answer: '0',
            explanation_ar: 'الذكاء الاصطناعي أنظمة تتعلم من البيانات وتتخذ قرارات ذكية كمراقبة حركة المرور أو الطاقة.',
            explanation_en: 'AI learns from data to make smart decisions like traffic or energy monitoring.',
            image_url: EDU_IMAGES.M_FUNCTION_MACHINE,
          },
          {
            question_ar: 'إنترنت الأشياء (IoT) في نيوم يعني:',
            question_en: 'IoT in NEOM means:',
            options_ar: ['أجهزة متصلة بالإنترنت وتبادل البيانات', 'إنترنت واحد فقط', 'أجهزة بلا اتصال', 'شبكة محلية فقط'],
            options_en: ['Devices connected to the internet exchanging data', 'Single internet only', 'Offline devices', 'Local network only'],
            correct_answer: '0',
            explanation_ar: 'IoT يربط أجهزة (حساسات، مصابيح، سيارات) بالإنترنت لتبادل البيانات وإدارة المدينة تلقائياً.',
            explanation_en: 'IoT connects devices (sensors, lights, vehicles) to the internet to manage the city automatically.',
            image_url: EDU_IMAGES.S_CIRCUIT,
          },
          {
            question_ar: 'الدائرة الكهربائية الذكية في نيوم تتحكم بالإضاءة. ما الذي يغلق الدائرة؟',
            question_en: 'A smart electrical circuit in NEOM controls lighting. What closes the circuit?',
            options_ar: ['المفتاح', 'الزجاج', 'الورق', 'الماء'],
            options_en: ['Switch', 'Glass', 'Paper', 'Water'],
            correct_answer: '0',
            explanation_ar: 'المفتاح يغلق الدائرة الكهربائية فيمر التيار ويضيء المصباح.',
            explanation_en: 'The switch closes the circuit, letting current flow to light the lamp.',
            image_url: EDU_IMAGES.S_CIRCUIT,
          },
          {
            question_ar: 'الروبوتات في نيوم تساعد في الزراعة والنقل. الروبوت هو:',
            question_en: 'Robots in NEOM help in farming & transport. A robot is:',
            options_ar: ['آلة قابلة للبرمجة تؤدي مهام تلقائياً', 'إنسان حقيقي', 'حيوان', 'نبات'],
            options_en: ['A programmable machine performing tasks automatically', 'A real human', 'An animal', 'A plant'],
            correct_answer: '0',
            explanation_ar: 'الروبوت آلة مبرمجة تؤدي مهاماً مثل الزراعة أو توصيل الطلبات بدقة وسرعة.',
            explanation_en: 'A robot is a programmed machine doing tasks like farming or delivery accurately.',
            image_url: EDU_IMAGES.S_GEARS,
          },
        ],
      },
    ],
  },
  {
    id: 'geography',
    titleAr: 'الجغرافيا',
    titleEn: 'Geography',
    icon: '🌍',
    color: 'from-cyan-500 to-blue-600',
    descAr: 'موقع نيوم الاستراتيجي والتخطيط الحضري',
    descEn: "NEOM's strategic location & urban planning",
    topics: [
      {
        id: 'location_climate',
        titleAr: 'الموقع والمناخ',
        titleEn: 'Location & Climate',
        questions: [
          {
            question_ar: 'نيوم تقع على ساحل:',
            question_en: 'NEOM is located on the coast of:',
            options_ar: ['البحر المتوسط', 'البحر الأحمر', 'الخليج العربي', 'المحيط الهندي'],
            options_en: ['Mediterranean Sea', 'Red Sea', 'Arabian Gulf', 'Indian Ocean'],
            correct_answer: '1',
            explanation_ar: 'نيوم في شمال غرب السعودية على ساحل البحر الأحمر مما يمنحها موقعاً تجارياً واستراتيجياً.',
            explanation_en: 'NEOM is in NW Saudi Arabia on the Red Sea coast, giving it a strategic trade location.',
            image_url: EDU_IMAGES.S_OCEAN,
          },
          {
            question_ar: 'مناخ نيوم صحراوي حار. أي تصميم عمراني يناسبها؟',
            question_en: "NEOM has a hot desert climate. Which urban design suits it?",
            options_ar: ['زجاج شفاف كثير', 'تظليل طبيعي وعزل ورياح متقاطعة', 'أسطح معدنية داكنة', 'نوافذ كبيرة بلا ظل'],
            options_en: ['Much clear glass', 'Natural shading, insulation & cross-ventilation', 'Dark metal roofs', 'Large unshaded windows'],
            correct_answer: '1',
            explanation_ar: 'التظليل والعزل والتهوية المتقاطعة تقلل الحرارة الداخلية وتوفر الطاقة في المناخ الصحراوي.',
            explanation_en: 'Shading, insulation and cross-ventilation reduce indoor heat and save energy in deserts.',
            image_url: EDU_IMAGES.S_DESERT,
          },
          {
            question_ar: 'الفصول الأربعة تؤثر على تصميم نيوم. أي فصل يحتاج أكبر تكييف؟',
            question_en: 'Seasons affect NEOM design. Which season needs the most cooling?',
            options_ar: ['الشتاء', 'الصيف', 'الربيع', 'الخريف'],
            options_en: ['Winter', 'Summer', 'Spring', 'Autumn'],
            correct_answer: '1',
            explanation_ar: 'الصيف صحراوي حار فيحتاج تكييفاً أكبر، لذا يُصمم العزل لتقليل الحمل الحراري.',
            explanation_en: 'Hot desert summer needs the most cooling, so insulation is designed to reduce heat load.',
            image_url: EDU_IMAGES.S_SEASONS,
          },
          {
            question_ar: 'التخطيط الحضري المستدام في نيوم يهدف إلى:',
            question_en: 'Sustainable urban planning in NEOM aims to:',
            options_ar: ['توسيع الزحف العمراني', 'تقليل المسافات والمشي والطاقة', 'هدم الطبيعة', 'زيادة السيارات'],
            options_en: ['Expand urban sprawl', 'Reduce distances, walking & energy', 'Destroy nature', 'Increase cars'],
            correct_answer: '1',
            explanation_ar: 'التخطيط المستدام يقلل المسافات (مدن ٥ دقائق) ويشجع المشي فلا حاجة للسيارات.',
            explanation_en: 'Sustainable planning shortens distances (5-minute cities) and encourages walking over cars.',
            image_url: EDU_IMAGES.S_CLOUDS,
          },
        ],
      },
    ],
  },
  {
    id: 'languages',
    titleAr: 'اللغة العربية والإنجليزية',
    titleEn: 'Arabic & English',
    icon: '📚',
    color: 'from-rose-500 to-pink-600',
    descAr: 'كتابة المقالات وقصص الخيال العلمي',
    descEn: 'Essays & sci-fi stories',
    topics: [
      {
        id: 'writing',
        titleAr: 'الكتابة الإبداعية',
        titleEn: 'Creative Writing',
        questions: [
          {
            question_ar: 'أي موضوع أنسب لمقال يقارن المدن التقليدية بالمدن الذكية كنيوم؟',
            question_en: 'Which topic best suits an essay comparing traditional vs smart cities like NEOM?',
            options_ar: ['وصف الصحراء', 'الاستدامة والتقنية وجودة الحياة', 'طبخ الطعام', 'تربية الحيوانات'],
            options_en: ['Describing desert', 'Sustainability, technology & quality of life', 'Cooking food', 'Raising animals'],
            correct_answer: '1',
            explanation_ar: 'المقارنة تركز على الفروق في الاستدامة والتقنية وجودة الحياة بين النمطين.',
            explanation_en: 'The comparison focuses on sustainability, technology and quality-of-life differences.',
            image_url: EDU_IMAGES.LA_STORY,
          },
          {
            question_ar: 'في قصة خيال علمي تدور في نيوم ٢٠٥٠، أي عنصر يجعلها خيالاً علمياً؟',
            question_en: 'In a sci-fi story set in NEOM 2050, what makes it sci-fi?',
            options_ar: ['وصف الماضي', 'تقنيات مستقبلية منطقية كالطيران والذكاء الاصطناعي', 'أساطير قديمة', 'رومانسية فقط'],
            options_en: ['Past description', 'Logical future tech like flying & AI', 'Ancient myths', 'Romance only'],
            correct_answer: '1',
            explanation_ar: 'الخيال العلمي يعتمد تقنيات مستقبلية ممكنة علمياً (طيران، ذكاء اصطناعي، طاقة نظيفة).',
            explanation_en: 'Sci-fi relies on scientifically plausible future technologies (flight, AI, clean energy).',
            image_url: EDU_IMAGES.E_STORY,
          },
          {
            question_ar: 'أي جملة تناسب مقالاً عن نيوم؟',
            question_en: 'Which sentence suits an essay about NEOM?',
            options_ar: ['نيوم مدينة ذكية خالية من الانبعاثات', 'أكلت تفاحة', 'السماء زرقاء', 'ذهبت للنوم'],
            options_en: ['NEOM is a smart zero-emission city', 'I ate an apple', 'The sky is blue', 'I went to sleep'],
            correct_answer: '0',
            explanation_ar: 'الجملة الأولى تتضمن موضوع المقال (مدينة ذكية + صفر انبعاثات).',
            explanation_en: 'The first sentence carries the essay topic (smart city + zero emissions).',
            image_url: EDU_IMAGES.LA_SENTENCE,
          },
        ],
      },
    ],
  },
  {
    id: 'pbl',
    titleAr: 'التعلم بالمشاريع والمهارات',
    titleEn: 'PBL & Soft Skills',
    icon: '💡',
    color: 'from-amber-500 to-orange-600',
    descAr: 'تحديات التصميم والتفكير التصميمي وريادة الأعمال',
    descEn: 'Design challenges, design thinking & entrepreneurship',
    topics: [
      {
        id: 'design_challenges',
        titleAr: 'تحديات التصميم',
        titleEn: 'Design Challenges',
        questions: [
          {
            question_ar: 'في تحدي تصميم مدرسة مستقبلية في نيوم، أي مبدأ يجب مراعاته؟',
            question_en: 'In designing a future school in NEOM, which principle should be followed?',
            options_ar: ['استهلاك طاقة عالٍ', 'الاستدامة والاعتماد على الطبيعة (Bio-design)', 'إهمال الإضاءة الطبيعية', 'استخدام مواد بلاستيكية فقط'],
            options_en: ['High energy use', 'Sustainability & bio-design', 'Ignore natural light', 'Only plastic materials'],
            correct_answer: '1',
            explanation_ar: 'التصميم المستدام يدمج الطبيعة (إضاءة، تهوية، مواد محلية) لتقليل البصمة البيئية.',
            explanation_en: 'Sustainable design integrates nature (light, ventilation, local materials) to reduce footprint.',
            image_url: EDU_IMAGES.S_LEVERS,
          },
          {
            question_ar: 'التفكير التصميمي (Design Thinking) يبدأ بـ:',
            question_en: 'Design Thinking starts with:',
            options_ar: ['البناء مباشرة', 'فهم احتياجات الإنسان', 'التسويق', 'البيع'],
            options_en: ['Building directly', 'Understanding human needs', 'Marketing', 'Selling'],
            correct_answer: '1',
            explanation_ar: 'التفكير التصميمي يبدأ بالتعاطف وفهم احتياجات المستخدم قبل التصميم والحل.',
            explanation_en: 'Design thinking begins with empathy and understanding user needs before solving.',
            image_url: EDU_IMAGES.M_PATTERNS,
          },
          {
            question_ar: 'ريادة الأعمال في نيوم تشجع الطلاب على:',
            question_en: 'Entrepreneurship in NEOM encourages students to:',
            options_ar: ['الانتظار للوظائف', 'ابتكار مشاريع ناشئة تخدم القطاعات الجديدة', 'تجنب التقنية', 'الاعتماد على الغير'],
            options_en: ['Wait for jobs', 'Create startups serving new sectors', 'Avoid technology', 'Rely on others'],
            correct_answer: '1',
            explanation_ar: 'ريادة الأعمال تدفع الطلاب لابتكار حلول ومشاريع في قطاعات نيوم (تكنولوجيا حيوية، غذاء، ترفيه).',
            explanation_en: 'Entrepreneurship drives students to create solutions in NEOM sectors (biotech, food, entertainment).',
            image_url: EDU_IMAGES.G_GRADUATION,
          },
          {
            question_ar: 'المواطنة الرقمية في مدينة تراقب بالذكاء الاصطناعي تتطلب:',
            question_en: 'Digital citizenship in an AI-monitored city requires:',
            options_ar: ['تجاهل الخصوصية', 'حماية خصوصية الأفراد وأخلاقيات التقنية', 'مشاركة كل البيانات', 'استخدام التقنية بلا حدود'],
            options_en: ['Ignoring privacy', 'Protecting privacy & tech ethics', 'Sharing all data', 'Limitless tech use'],
            correct_answer: '1',
            explanation_ar: 'المواطنة الرقمية المسؤولة توازن بين التقنية وحقوق الأفراد وخصوصيتهم.',
            explanation_en: 'Responsible digital citizenship balances technology with individual rights and privacy.',
            image_url: EDU_IMAGES.I_GOOD_DEED,
          },
          {
            question_ar: 'هاكاثون المدارس في نيوم يهدف إلى:',
            question_en: 'A school hackathon in NEOM aims to:',
            options_ar: ['تنظيم حفلة', 'ابتكار تطبيقات ذكية تخدم سكان نيوم', 'مباراة رياضية', 'عرض أزياء'],
            options_en: ['Throw a party', 'Invent smart apps serving NEOM residents', 'A sports match', 'A fashion show'],
            correct_answer: '1',
            explanation_ar: 'الهاكاثون مسابقة برمجية يبتكر فيها الطلاب تطبيقات (جودة هواء، توجيه زوار) في وقت قصير.',
            explanation_en: 'A hackathon is a coding contest where students invent apps (air quality, visitor guidance) fast.',
            image_url: EDU_IMAGES.S_ENERGY_TYPES,
          },
        ],
      },
    ],
  },
];