/**
 * العلوم — الصف الثاني الابتدائي · الفصل الثاني
 * الوحدة السادسة: القوى والطاقة — الفصل الحادي عشر: القوى (ص 104-126)
 * الدرس الأول: القوى تحرّك الأشياء (ص 105-112)
 * أنواع الأسئلة: multiple_choice · true_false · ordering · matching · classify
 */

/* ════════════════════════════════════════════════════
 *  مفردات الفكرة العامة (ص 105) — تشمل الدرسين
 * ════════════════════════════════════════════════════ */
export const FORCES_VOCAB_LESSON = {
  id: 'forces_vocab',
  title_ar: 'مفردات الفكرة العامة — القوى',
  title_en: 'Big Idea Vocabulary — Forces',
  questions: [
    {
      type: 'matching',
      question_ar: 'صِل كل مصطلح بتعريفه كما ورد في مفردات الفكرة العامة (ص 105):',
      question_en: 'Match each term to its definition from the big idea vocabulary (p.105):',
      pairs_ar: [
        { left: 'القوة', right: 'مؤثر يغيّر الحالة الحركية للجسم، فإما أن تكون سحباً أو دفعاً' },
        { left: 'الجاذبية', right: 'قوة تجذب بها الأرض الأجسام إليها' },
        { left: 'قوة الاحتكاك', right: 'قوة تنشأ عند تلامس سطح جسم متحرك مع سطح آخر، وتقلل من سرعة الأجسام' },
        { left: 'الوزن', right: 'مقدار قوة جذب الأرض للجسم' },
        { left: 'التجاذب', right: 'سحب الأجسام بعضها لبعض' },
        { left: 'قطبا المغناطيس', right: 'طرفا المغناطيس، حيث تكون قوة الجذب عندهما أكبر ما يمكن' },
        { left: 'التنافر', right: 'تباعد الأجسام بعضها عن بعض' },
      ],
      pairs_en: [
        { left: 'Force', right: 'An influence that changes the motion state of an object — a pull or push' },
        { left: 'Gravity', right: 'A force by which Earth pulls objects toward itself' },
        { left: 'Friction force', right: 'A force arising when a moving object touches another surface, reducing speed' },
        { left: 'Weight', right: 'The amount of Earth\'s gravitational pull on an object' },
        { left: 'Attraction', right: 'Objects pulling each other together' },
        { left: 'Magnet poles', right: 'The two ends of a magnet, where attraction force is greatest' },
        { left: 'Repulsion', right: 'Objects moving apart from each other' },
      ],
      explanation_ar: 'مفردات الفصل: القوة (دفع/شد)، الجاذبية (سحب الأرض)، الاحتكاك (يقلل السرعة)، الوزن (مقدار جذب الأرض)، التجاذب (سحب متبادل)، القطبان (أقوى جذب)، التنافر (تباعد).',
    },
    {
      type: 'multiple_choice',
      question_ar: 'ما تعريف القوة؟ (ص 105)',
      question_en: 'What is the definition of force? (p.105)',
      options_ar: [
        'مؤثر يغيّر الحالة الحركية للجسم، فإما أن تكون سحباً أو دفعاً',
        'مقدار قوة جذب الأرض للجسم',
        'قوة تنشأ عند تلامس سطحين',
        'تباعد الأجسام بعضها عن بعض',
      ],
      options_en: [
        'An influence that changes the motion state of an object — a pull or push',
        'The amount of Earth\'s gravitational pull on an object',
        'A force arising when two surfaces touch',
        'Objects moving apart from each other',
      ],
      correct: 0,
      explanation_ar: 'القوة: مؤثر يغيّر الحالة الحركية للجسم — إما سحب أو دفع. نستخدم القوة طوال الوقت لتحريك الأشياء.',
    },
    {
      type: 'multiple_choice',
      question_ar: 'ما تعريف الجاذبية؟ (ص 105)',
      question_en: 'What is the definition of gravity? (p.105)',
      options_ar: [
        'قوة تجذب بها الأرض الأجسام إليها',
        'مؤثر يغيّر الحالة الحركية للجسم',
        'قوة تنشأ عند تلامس سطحين',
        'تباعد الأجسام بعضها عن بعض',
      ],
      options_en: [
        'A force by which Earth pulls objects toward itself',
        'An influence that changes the motion state of an object',
        'A force arising when two surfaces touch',
        'Objects moving apart from each other',
      ],
      correct: 0,
      explanation_ar: 'الجاذبية: قوة تجذب بها الأرض الأجسام إليها — لا نراها لكنها تبقينا على الأرض وتسحبنا للأسفل عند القفز.',
    },
    {
      type: 'multiple_choice',
      question_ar: 'ما تعريف قوة الاحتكاك؟ (ص 105)',
      question_en: 'What is the definition of friction force? (p.105)',
      options_ar: [
        'قوة تنشأ عند تلامس سطح جسم متحرك مع سطح آخر، وتقلل من سرعة الأجسام المتحركة',
        'قوة تجذب بها الأرض الأجسام',
        'سحب الأجسام بعضها لبعض',
        'مقدار قوة جذب الأرض للجسم',
      ],
      options_en: [
        'A force arising when a moving object touches another surface, reducing speed',
        'A force by which Earth pulls objects',
        'Objects pulling each other',
        'The amount of Earth\'s pull on an object',
      ],
      correct: 0,
      explanation_ar: 'قوة الاحتكاك: تنشأ عند تلامس سطح جسم متحرك مع سطح آخر — تقلل من سرعة الأجسام المتحركة.',
    },
    {
      type: 'multiple_choice',
      question_ar: 'ما تعريف الوزن؟ (ص 105)',
      question_en: 'What is the definition of weight? (p.105)',
      options_ar: [
        'مقدار قوة جذب الأرض للجسم',
        'مؤثر يغيّر الحالة الحركية للجسم',
        'قوة تنشأ عند تلامس سطحين',
        'تباعد الأجسام بعضها عن بعض',
      ],
      options_en: [
        'The amount of Earth\'s gravitational pull on an object',
        'An influence that changes the motion state of an object',
        'A force arising when two surfaces touch',
        'Objects moving apart from each other',
      ],
      correct: 0,
      explanation_ar: 'الوزن: مقدار قوة جذب الأرض للجسم — وكلما زادت كتلة الجسم زادت قوة جاذبية الأرض له (زاد وزنه).',
    },
    {
      type: 'multiple_choice',
      question_ar: 'ما تعريف التجاذب؟ (ص 105)',
      question_en: 'What is the definition of attraction? (p.105)',
      options_ar: ['سحب الأجسام بعضها لبعض', 'تباعد الأجسام بعضها عن بعض', 'قوة تجذب بها الأرض الأجسام', 'قوة تنشأ عند التلامس'],
      options_en: ['Objects pulling each other together', 'Objects moving apart', 'Earth pulling objects', 'Force from touching'],
      correct: 0,
      explanation_ar: 'التجاذب: سحب الأجسام بعضها لبعض — مثل جذب المغناطيس لمشابك الورق، أو جذب الأرض للأجسام.',
    },
    {
      type: 'multiple_choice',
      question_ar: 'ما تعريف التنافر؟ (ص 105)',
      question_en: 'What is the definition of repulsion? (p.105)',
      options_ar: ['تباعد الأجسام بعضها عن بعض', 'سحب الأجسام بعضها لبعض', 'مقدار قوة جذب الأرض', 'قوة تنشأ عند التلامس'],
      options_en: ['Objects moving apart from each other', 'Objects pulling each other', 'Amount of Earth\'s pull', 'Force from touching'],
      correct: 0,
      explanation_ar: 'التنافر: تباعد الأجسام بعضها عن بعض — مثل تباعد قطبي مغناطيسين متشابهين عند تقريبهما.',
    },
    {
      type: 'multiple_choice',
      question_ar: 'ما تعريف قطبي المغناطيس؟ (ص 105)',
      question_en: 'What is the definition of magnet poles? (p.105)',
      options_ar: [
        'طرفا المغناطيس، حيث تكون قوة جذب المغناطيس عندهما أكبر ما يمكن',
        'منتصف المغناطيس',
        'قوة تجذب بها الأرض الأجسام',
        'تباعد الأجسام بعضها عن بعض',
      ],
      options_en: [
        'The two ends of a magnet, where attraction force is greatest',
        'The middle of the magnet',
        'Earth\'s pull on objects',
        'Objects moving apart',
      ],
      correct: 0,
      explanation_ar: 'قطبا المغناطيس: طرفا المغناطيس — عندهما تكون قوة الجذب أكبر ما يمكن. للقطبين نوعان: شمالي (ش) وجنوبي (ع).',
    },
  ],
};

/* ════════════════════════════════════════════════════
 *  الدرس الأول: القوى تحرّك الأشياء (ص 105-112)
 * ════════════════════════════════════════════════════ */
export const FORCES_LESSON_1 = {
  id: 'forces_move_objects',
  title_ar: 'الدرس الأول: القوى تحرّك الأشياء',
  title_en: 'Lesson 1: Forces Move Objects',
  questions: [

    /* ─── نشاط: كيف أجعل الأشياء تتحرك؟ (ص 106) ─── */
    {
      type: 'ordering',
      question_ar: 'رتّب خطوات نشاط "كيف أجعل الأشياء تتحرك؟" (ص 106):',
      question_en: 'Order the steps of the "How do I make things move?" activity (p.106):',
      items_ar: [
        'أضع السيارة على سطح مستوٍ بعد تعيين نقطة البداية، وأدفعها برفق',
        'أقيس: ما المسافة التي قطعتها السيارة؟',
        'أعيد السيارة إلى مكانها الأول، ثم أدفعها بقوة أكبر هذه المرة. ألاحظ ما يحدث',
        'أتوقع: ماذا يحدث إذا سحبت السيارة نحوي؟ هل ستقطع المسافة نفسها؟',
      ],
      items_en: [
        'Place the car on a flat surface after marking the start, push it gently',
        'Measure: what distance did the car cover?',
        'Return the car to its start, push with greater force. Observe what happens',
        'Predict: what happens if I pull the car toward me? Will it cover the same distance?',
      ],
      explanation_ar: 'خطوات النشاط: دفع برفق ← قياس المسافة ← دفع بقوة أكبر وملاحظة ← توقع عند السحب. الأدوات: سيارة لعبة، شريط لاصق، مسطرة مترية.',
    },
    {
      type: 'multiple_choice',
      question_ar: 'ما الأدوات التي أحتاجها لنشاط "كيف أجعل الأشياء تتحرك؟" (ص 106)',
      question_en: 'What tools do I need for the "How do I make things move?" activity? (p.106)',
      options_ar: ['سيارة لعبة، شريط لاصق، مسطرة مترية', 'مغناطيس، دبابيس', 'ميزان، كرات', 'مصباح، بطارية'],
      options_en: ['Toy car, adhesive tape, metric ruler', 'Magnet, pins', 'Balance, balls', 'Flashlight, battery'],
      correct: 0,
      explanation_ar: 'أحتاج: سيارة لعبة + شريط لاصق (لتحديد نقطة البداية) + مسطرة مترية (لقياس المسافة).',
    },
    {
      type: 'multiple_choice',
      question_ar: 'في نشاط السيارة (ص 106): ماذا يحدث عندما أدفع السيارة بقوة أكبر؟',
      question_en: 'In the car activity (p.106): what happens when I push the car with greater force?',
      options_ar: [
        'تقطع مسافة أكبر — القوة الأكبر تجعلها تتحرك أبعد',
        'تقطع مسافة أقل',
        'لا تتحرك',
        'تتحرك للخلف',
      ],
      options_en: [
        'It covers a greater distance — greater force makes it go farther',
        'It covers less distance',
        'It does not move',
        'It moves backward',
      ],
      correct: 0,
      explanation_ar: 'القوة الأكبر تجعل السيارة تقطع مسافة أكبر — كلما زادت القوة زادت المسافة التي تقطعها السيارة.',
    },
    {
      type: 'true_false',
      question_ar: 'في نشاط السيارة (ص 106): إذا سحبت السيارة نحوي بدلاً من دفعها، فإنها تتحرك.',
      question_en: 'In the car activity (p.106): if I pull the car toward me instead of pushing, it moves.',
      correct: 'true',
      explanation_ar: 'السحب والدفع كلاهما قوة تحرك الأشياء — سواء سحبت السيارة نحوي أو دفعتها بعيداً، فإنها تتحرك بقوة.',
    },

    /* ─── ما الذي يحرّك الأشياء؟ (ص 107) ─── */
    {
      type: 'multiple_choice',
      question_ar: 'ما الذي يحرّك الأشياء؟ (ص 107)',
      question_en: 'What makes things move? (p.107)',
      options_ar: [
        'القوى — الأجسام لا تتحرك من تلقاء نفسها، بل تحتاج إلى قوة تحرّكها',
        'الأجسام تتحرك من تلقاء نفسها',
        'الهواء فقط',
        'لا شيء يحرّك الأشياء',
      ],
      options_en: [
        'Forces — objects do not move by themselves, they need a force to move them',
        'Objects move by themselves',
        'Air only',
        'Nothing moves objects',
      ],
      correct: 0,
      explanation_ar: 'الأجسام لا تتحرك من تلقاء نفسها — تحتاج إلى قوة تحرّكها. القوة مؤثر يغيّر الحالة الحركية للجسم (دفع أو سحب).',
    },
    {
      type: 'multiple_choice',
      question_ar: 'القوة هي: (ص 107)',
      question_en: 'Force is: (p.107)',
      options_ar: [
        'مؤثر يغيّر الحالة الحركية للجسم — وهي قوة سحب أو قوة دفع',
        'مقدار الطاقة في الجسم',
        'وزن الجسم',
        'لون الجسم',
      ],
      options_en: [
        'An influence that changes the motion state of an object — a pull or push',
        'The amount of energy in an object',
        'The weight of an object',
        'The color of an object',
      ],
      correct: 0,
      explanation_ar: 'القوة: مؤثر يغيّر الحالة الحركية للجسم — إما سحب أو دفع. نستخدم القوة طوال الوقت لتحريك الأشياء.',
    },
    {
      type: 'multiple_choice',
      question_ar: 'عندما ألعب كرة القدم وأركل الكرة، ما نوع القوة التي أؤثر بها؟ (ص 107)',
      question_en: 'When I play soccer and kick the ball, what type of force do I exert? (p.107)',
      options_ar: ['دفع', 'سحب', 'جاذبية', 'احتكاك'],
      options_en: ['Push', 'Pull', 'Gravity', 'Friction'],
      correct: 0,
      explanation_ar: 'ركل الكرة يمثل دفعاً — إذا لم أركلها فلن تتحرك وستبقى في مكانها. الدفع قوة تحرك الشيء بعيداً عني.',
    },
    {
      type: 'true_false',
      question_ar: 'الأجسام تتحرك من تلقاء نفسها دون الحاجة إلى قوة. (ص 107)',
      question_en: 'Objects move by themselves without needing a force. (p.107)',
      correct: 'false',
      explanation_ar: 'الأجسام لا تتحرك من تلقاء نفسها — تحتاج إلى قوة تحرّكها. إذا لم أركل الكرة فلن تتحرك وستبقى في مكانها.',
    },

    /* ─── الدفع والسحب (ص 108) ─── */
    {
      type: 'multiple_choice',
      question_ar: 'عندما أسحب مقبض الباب، ماذا يحدث؟ (ص 108)',
      question_en: 'When I pull the door handle, what happens? (p.108)',
      options_ar: [
        'أقرّبه إليّ — القوة هنا سحب',
        'أبعده عني — القوة هنا دفع',
        'لا يتحرك الباب',
        'ينكسر الباب',
      ],
      options_en: [
        'I bring it closer to me — this force is a pull',
        'I push it away — this force is a push',
        'The door does not move',
        'The door breaks',
      ],
      correct: 0,
      explanation_ar: 'سحب مقبض الباب يقربه إليّ — هذه قوة سحب. أما دفع العربة فيبعدها عني — هذه قوة دفع. كلاهما يحرك الأشياء.',
    },
    {
      type: 'multiple_choice',
      question_ar: 'عندما أدفع العربة، ماذا يحدث؟ (ص 108)',
      question_en: 'When I push the cart, what happens? (p.108)',
      options_ar: [
        'أبعدها عني — القوة هنا دفع',
        'أقرّبها إليّ — القوة هنا سحب',
        'لا تتحرك',
        'تنكسر',
      ],
      options_en: [
        'I push it away from me — this force is a push',
        'I bring it closer — this force is a pull',
        'It does not move',
        'It breaks',
      ],
      correct: 0,
      explanation_ar: 'دفع العربة يبعدها عني — قوة دفع. الدفع والسحب يحركان العربة: السحب يقرّبها والدفع يبعدها.',
    },
    {
      type: 'classify',
      question_ar: 'صنّف كل فعل إلى: دفع / سحب (ص 108):',
      question_en: 'Classify each action as: push / pull (p.108):',
      categories_ar: ['دفع', 'سحب'],
      categories_en: ['Push', 'Pull'],
      items_ar: ['ركل الكرة', 'سحب مقبض الباب', 'دفع العربة', 'جذب الحقيبة إليك', 'دحرجة الكرة للأمام', 'سحب الحبل'],
      items_en: ['Kicking a ball', 'Pulling a door handle', 'Pushing a cart', 'Pulling a bag toward you', 'Rolling a ball forward', 'Pulling a rope'],
      correct_categories: [0, 1, 0, 1, 0, 1],
      explanation_ar: 'دفع: ركل الكرة، دفع العربة، دحرجة الكرة. سحب: مقبض الباب، الحقيبة، الحبل. الدفع يبعد والسحب يقرّب.',
    },
    {
      type: 'multiple_choice',
      question_ar: 'هل أستطيع تحريك أجسام مختلفة بقوى مختلفة في المقدار؟ (ص 108)',
      question_en: 'Can I move different objects with forces of different amounts? (p.108)',
      options_ar: [
        'نعم — أستطيع تحريك أجسام مختلفة بقوى مختلفة المقدار',
        'لا — كل القوى متساوية',
        'لا يمكن تحريك أي جسم',
        'فقط الأجسام الصغيرة',
      ],
      options_en: [
        'Yes — I can move different objects with forces of different amounts',
        'No — all forces are equal',
        'No object can be moved',
        'Only small objects',
      ],
      correct: 0,
      explanation_ar: 'أستطيع تحريك أجسام مختلفة بقوى مختلفة المقدار — الأجسام الكبيرة تحتاج قوة أكبر، والصغيرة تحتاج قوة أقل.',
    },
    {
      type: 'multiple_choice',
      question_ar: 'لماذا نحتاج إلى القوى؟ (ص 108)',
      question_en: 'Why do we need forces? (p.108)',
      options_ar: [
        'لتحريك الأشياء الساكنة وتغيير حركة المتحركة (سرعة/اتجاه/توقف)',
        'لرؤية الأشياء فقط',
        'لتغيير لون الأشياء',
        'لا نحتاج إلى القوى',
      ],
      options_en: [
        'To move stationary objects and change motion of moving ones (speed/direction/stop)',
        'Only to see things',
        'To change the color of things',
        'We do not need forces',
      ],
      correct: 0,
      explanation_ar: 'نحتاج القوى لتحريك الأشياء الساكنة، وتغيير سرعة المتحركة، وإيقافها، وتغيير اتجاهها — بدون قوة لا تتحرك الأشياء.',
    },

    /* ─── تغيير الحركة (ص 109) ─── */
    {
      type: 'multiple_choice',
      question_ar: 'كيف تغيّر القوى حركة الأجسام؟ (ص 109)',
      question_en: 'How do forces change the motion of objects? (p.109)',
      options_ar: [
        'تحرّك الساكن، تسرّع المتحرك، تبطئه، توقفه، أو تغيّر اتجاه حركته',
        'تغيّر لونها فقط',
        'تغيّر حجمها فقط',
        'لا تغيّر القوى الحركة',
      ],
      options_en: [
        'Move stationary, accelerate moving, slow down, stop, or change direction',
        'Only change color',
        'Only change size',
        'Forces do not change motion',
      ],
      correct: 0,
      explanation_ar: 'القوى تغيّر الحركة: تحرّك الساكن، تسرّع المتحرك، تبطئه، توقفه، أو تغيّر اتجاهه. مثال: كرة القدم.',
    },
    {
      type: 'classify',
      question_ar: 'صنّف كل تأثير للقوة في كرة القدم (ص 109):',
      question_en: 'Classify each effect of force on a soccer ball (p.109):',
      categories_ar: ['بدء الحركة', 'تغيير السرعة والاتجاه', 'إيقاف الحركة'],
      categories_en: ['Starting motion', 'Changing speed and direction', 'Stopping motion'],
      items_ar: ['حارس المرمى يرمي الكرة', 'اللاعب يركل الكرة المتحركة', 'حارس المرمى يمسك الكرة', 'الكرة تبدأ بالتحرك', 'الكرة تتوقف', 'الكرة تغيّر اتجاهها'],
      items_en: ['Goalkeeper throws the ball', 'Player kicks the moving ball', 'Goalkeeper catches the ball', 'Ball starts moving', 'Ball stops', 'Ball changes direction'],
      correct_categories: [0, 1, 2, 0, 2, 1],
      explanation_ar: 'بدء الحركة: رمي الكرة. تغيير السرعة/الاتجاه: ركل الكرة المتحركة. إيقاف الحركة: مسك الكرة. القوى تفعل كل ذلك.',
    },
    {
      type: 'multiple_choice',
      question_ar: 'ماذا يحدث عندما يرمي حارس المرمى الكرة؟ (ص 109)',
      question_en: 'What happens when the goalkeeper throws the ball? (p.109)',
      options_ar: ['تبدأ الكرة في الحركة', 'تتوقف الكرة', 'لا يحدث شيء', 'تنكسر الكرة'],
      options_en: ['The ball begins to move', 'The ball stops', 'Nothing happens', 'The ball breaks'],
      correct: 0,
      explanation_ar: 'عندما يرمي حارس المرمى الكرة تبدأ في الحركة — القوة (الرمي) حرّكت الجسم الساكن.',
    },
    {
      type: 'multiple_choice',
      question_ar: 'ماذا يحدث عندما يركل اللاعب الكرة المتحركة؟ (ص 109)',
      question_en: 'What happens when a player kicks the moving ball? (p.109)',
      options_ar: [
        'يغيّر من سرعتها واتجاه حركتها',
        'تتوقف عن الحركة',
        'لا يحدث شيء',
        'تنكسر',
      ],
      options_en: [
        'Changes its speed and direction of motion',
        'It stops moving',
        'Nothing happens',
        'It breaks',
      ],
      correct: 0,
      explanation_ar: 'عند ركل الكرة المتحركة: القوة تغيّر من سرعتها واتجاه حركتها — تؤثر فيها بقوة تغيّر حركتها.',
    },
    {
      type: 'multiple_choice',
      question_ar: 'ماذا يحدث عندما يمسك حارس المرمى الكرة؟ (ص 109)',
      question_en: 'What happens when the goalkeeper catches the ball? (p.109)',
      options_ar: ['تتوقف عن الحركة', 'تبدأ في الحركة', 'تغيّر اتجاهها فقط', 'لا يحدث شيء'],
      options_en: ['It stops moving', 'It starts moving', 'Only changes direction', 'Nothing happens'],
      correct: 0,
      explanation_ar: 'عندما يمسك حارس المرمى الكرة تتوقف عن الحركة — القوة (المسك) أوقفت حركة الكرة.',
    },
    {
      type: 'multiple_choice',
      question_ar: 'ماذا يحدث عندما أركل كرة متحركة بقدمي؟ (ص 110)',
      question_en: 'What happens when I kick a moving ball with my foot? (p.110)',
      options_ar: [
        'أغيّر من سرعتها واتجاه حركتها',
        'تبقى كما هي',
        'تتوقف فوراً',
        'تنكسر',
      ],
      options_en: [
        'I change its speed and direction of motion',
        'It stays the same',
        'It stops immediately',
        'It breaks',
      ],
      correct: 0,
      explanation_ar: 'ركل الكرة المتحركة يغيّر سرعتها واتجاهها — القوة المؤثرة تغيّر من حركتها.',
    },

    /* ─── أقرأ الصور + رؤية 2030 (ص 110) ─── */
    {
      type: 'multiple_choice',
      question_ar: 'أقرأ الصور (ص 110): كيف تغيّر القوى حركة الكرة؟',
      question_en: 'Read the pictures (p.110): How do forces change the ball\'s motion?',
      options_ar: [
        'الرمي يبدأ حركتها، الركل يغيّر سرعتها واتجاهها، المسك يوقفها',
        'فقط تبدأ حركتها',
        'فقط تتوقف',
        'لا تغيّر القوى حركة الكرة',
      ],
      options_en: [
        'Throwing starts motion, kicking changes speed and direction, catching stops it',
        'Only starts motion',
        'Only stops',
        'Forces do not change ball motion',
      ],
      correct: 0,
      explanation_ar: 'من الصور: الرمي يبدأ الحركة، الركل يغيّر السرعة والاتجاه، المسك يوقف الحركة — القوى تغيّر الحركة بطرق مختلفة.',
    },
    {
      type: 'multiple_choice',
      question_ar: 'الربط مع رؤية 2030 (ص 110): من أهداف الرؤية 2.2.1 تعزيز ممارسة الأنشطة الرياضية. كيف يرتبط ذلك بالدرس؟',
      question_en: 'Connecting with Vision 2030 (p.110): Goal 2.2.1 promotes sports activities. How does this relate to the lesson?',
      options_ar: [
        'الأنشطة الرياضية كرة القدم تعتمد على القوى — الدفع والسحب والركل',
        'لا علاقة للرياضة بالقوى',
        'الرياضة لا تستخدم القوى',
        'القوى تمنع الرياضة',
      ],
      options_en: [
        'Sports like soccer depend on forces — pushing, pulling, and kicking',
        'Sports have no relation to forces',
        'Sports do not use forces',
        'Forces prevent sports',
      ],
      correct: 0,
      explanation_ar: 'رؤية 2030 (هدف 2.2.1): تعزيز الأنشطة الرياضية. كرة القدم وغيرها تعتمد على القوى — ركل (دفع)، رمي، مسك — تطبيقات عملية للقوى.',
    },

    /* ─── ما أنواع القوى؟ (ص 111) ─── */
    {
      type: 'multiple_choice',
      question_ar: 'ما أنواع القوى؟ (ص 111)',
      question_en: 'What are the types of forces? (p.111)',
      options_ar: [
        'قوى التلامس (دفع الباب، ضرب الكرة) وقوى عن بُعد (المغناطيسية، الجاذبية)',
        'قوى الدفع فقط',
        'قوى السحب فقط',
        'نوع واحد فقط',
      ],
      options_en: [
        'Contact forces (pushing door, hitting ball) and non-contact forces (magnetic, gravity)',
        'Only push forces',
        'Only pull forces',
        'Only one type',
      ],
      correct: 0,
      explanation_ar: 'قوى التلامس: تنشأ عن تلامس الأشياء (دفع الباب، ضرب الكرة). قوى عن بُعد: تؤثر دون تلامس (المغناطيسية، الجاذبية).',
    },
    {
      type: 'classify',
      question_ar: 'صنّف كل قوة إلى: قوة تلامس / قوة عن بُعد (ص 111):',
      question_en: 'Classify each force as: contact force / non-contact force (p.111):',
      categories_ar: ['قوة تلامس', 'قوة عن بُعد'],
      categories_en: ['Contact force', 'Non-contact force'],
      items_ar: ['دفع الباب', 'ضرب الكرة بالمضرب', 'ركل الكرة بالقدم', 'القوة المغناطيسية', 'الجاذبية'],
      items_en: ['Pushing a door', 'Hitting a ball with a racket', 'Kicking a ball with foot', 'Magnetic force', 'Gravity'],
      correct_categories: [0, 0, 0, 1, 1],
      explanation_ar: 'تلامس: دفع الباب، ضرب الكرة، ركل الكرة (تلامس مباشر). عن بُعد: المغناطيسية، الجاذبية (تؤثر دون تلامس).',
    },
    {
      type: 'multiple_choice',
      question_ar: 'ما قوى التلامس؟ (ص 111)',
      question_en: 'What are contact forces? (p.111)',
      options_ar: [
        'قوى تنشأ عن تلامس الأشياء — مثل دفع الباب وضرب الكرة',
        'قوى تؤثر عن بُعد دون تلامس',
        'قوى الجاذبية فقط',
        'قوى المغناطيسية فقط',
      ],
      options_en: [
        'Forces arising from objects touching — like pushing a door or hitting a ball',
        'Forces acting at a distance without touching',
        'Gravity only',
        'Magnetic force only',
      ],
      correct: 0,
      explanation_ar: 'قوى التلامس: تنشأ عن تلامس الأشياء — دفع الباب، ضرب الكرة بالمضرب أو القدم. أكثر القوى شيوعاً وأشهرها.',
    },
    {
      type: 'multiple_choice',
      question_ar: 'أيُّ القوى التالية تؤثر عن بُعد دون تلامس؟ (ص 111)',
      question_en: 'Which of these forces acts at a distance without touching? (p.111)',
      options_ar: ['القوة المغناطيسية والجاذبية', 'دفع الباب', 'ضرب الكرة', 'ركل الكرة'],
      options_en: ['Magnetic force and gravity', 'Pushing a door', 'Hitting a ball', 'Kicking a ball'],
      correct: 0,
      explanation_ar: 'القوى التي تؤثر عن بُعد دون تلامس: القوة المغناطيسية (المغناطيس يجذب الحديد عن بُعد) والجاذبية (الأرض تجذب الأجسام دون تلامس).',
    },

    /* ─── القوة المغناطيسية (ص 111) ─── */
    {
      type: 'multiple_choice',
      question_ar: 'ما القوة المغناطيسية؟ (ص 111)',
      question_en: 'What is magnetic force? (p.111)',
      options_ar: [
        'قوة تجعل قطع الحديد تتحرك نحو المغناطيس وتلتصق به دون تلامس',
        'قوة تجذب بها الأرض الأجسام',
        'قوة تنشأ عند تلامس سطحين',
        'قوة دفع الباب',
      ],
      options_en: [
        'A force that makes iron pieces move toward and stick to a magnet without touching',
        'A force by which Earth pulls objects',
        'A force arising when surfaces touch',
        'A force of pushing a door',
      ],
      correct: 0,
      explanation_ar: 'القوة المغناطيسية: إذا قرّبت مغناطيساً من قطع حديدية (مشابك ورق) فإنها تتحرك نحو المغناطيس وتلتصق به — دون تلامس مباشر.',
    },
    {
      type: 'multiple_choice',
      question_ar: 'المغناطيس يجذب جميع المواد التالية ما عدا: (ص 111)',
      question_en: 'A magnet attracts all of the following except: (p.111)',
      options_ar: ['الخشب والزجاج والبلاستيك', 'الحديد', 'مشابك الورق', 'الصلب'],
      options_en: ['Wood, glass, and plastic', 'Iron', 'Paper clips', 'Steel'],
      correct: 0,
      explanation_ar: 'المغناطيس لا يجذب الخشب أو الزجاج أو البلاستيك — يجذب المواد الحديدية فقط مثل مشابك الورق.',
    },
    {
      type: 'classify',
      question_ar: 'صنّف كل مادة إلى: يجذبها المغناطيس / لا يجذبها المغناطيس (ص 111):',
      question_en: 'Classify each material as: magnet attracts / magnet does not attract (p.111):',
      categories_ar: ['يجذبها المغناطيس', 'لا يجذبها المغناطيس'],
      categories_en: ['Magnet attracts', 'Magnet does not attract'],
      items_ar: ['مشابك الورق الحديدية', 'الخشب', 'الزجاج', 'القطع الحديدية', 'البلاستيك'],
      items_en: ['Iron paper clips', 'Wood', 'Glass', 'Iron pieces', 'Plastic'],
      correct_categories: [0, 1, 1, 0, 1],
      explanation_ar: 'يجذبها المغناطيس: مشابك الورق الحديدية، القطع الحديدية. لا يجذبها: الخشب، الزجاج، البلاستيك.',
    },
    {
      type: 'true_false',
      question_ar: 'المغناطيس يجذب مشابك الورق دون أن يلامسها. (ص 111)',
      question_en: 'A magnet attracts paper clips without touching them. (p.111)',
      correct: 'true',
      explanation_ar: 'المغناطيس يجذب مشابك الورق الحديدية عن بُعد دون تلامس — هذه قوة عن بُعد تسمى القوة المغناطيسية.',
    },
    {
      type: 'multiple_choice',
      question_ar: 'كيف ألتقط مشابك الورق الحديدية دون أن ألمسها؟ (ص 112)',
      question_en: 'How do I pick up iron paper clips without touching them? (p.112)',
      options_ar: [
        'أستخدم مغناطيساً — القوة المغناطيسية تجذبها دون تلامس',
        'أستخدم ميزاناً',
        'أستخدم مسطرة',
        'لا يمكن ذلك',
      ],
      options_en: [
        'I use a magnet — magnetic force attracts them without touching',
        'I use a balance',
        'I use a ruler',
        'It cannot be done',
      ],
      correct: 0,
      explanation_ar: 'ألتقط مشابك الورق الحديدية بمغناطيس — القوة المغناطيسية تجذبها عن بُعد دون أن ألمسها بيدي.',
    },

    /* ─── الجاذبية (ص 112) ─── */
    {
      type: 'multiple_choice',
      question_ar: 'ما الجاذبية؟ (ص 112)',
      question_en: 'What is gravity? (p.112)',
      options_ar: [
        'قوة سحب أو جذب بين جسمين — الأرض تسحب الأجسام إليها',
        'قوة دفع الأشياء بعيداً',
        'قوة تنشأ عند التلامس',
        'قوة المغناطيس فقط',
      ],
      options_en: [
        'A pull or attraction between two objects — Earth pulls objects toward itself',
        'A force pushing things away',
        'A force from touching',
        'Only magnetic force',
      ],
      correct: 0,
      explanation_ar: 'الجاذبية قوة سحب أو جذب بين جسمين — لا أراها لكنها تبقيني على الأرض. عند القفز تسحبني الأرض للأسفل.',
    },
    {
      type: 'true_false',
      question_ar: 'أنا لا أرى الجاذبية، لكنني أعرف أنها هي التي تبقيني على الأرض. (ص 112)',
      question_en: 'I cannot see gravity, but I know it keeps me on Earth. (p.112)',
      correct: 'true',
      explanation_ar: 'لا نرى الجاذبية لكننا نحس بها — عندما أقفز إلى أعلى فإن جاذبية الأرض تسحبني إلى أسفل.',
    },
    {
      type: 'multiple_choice',
      question_ar: 'عندما أقفز إلى أعلى، ماذا يحدث؟ (ص 112)',
      question_en: 'When I jump upward, what happens? (p.112)',
      options_ar: [
        'جاذبية الأرض تسحبني إلى أسفل',
        'أبقى في الأعلى',
        'أطير بعيداً',
        'لا يحدث شيء',
      ],
      options_en: [
        'Earth\'s gravity pulls me back down',
        'I stay up',
        'I fly away',
        'Nothing happens',
      ],
      correct: 0,
      explanation_ar: 'عند القفز للأعلى، جاذبية الأرض تسحبني للأسفل — هذه القوة تبقينا على الأرض.',
    },
    {
      type: 'multiple_choice',
      question_ar: 'على ماذا تعمل جاذبية الأرض؟ (ص 112)',
      question_en: 'What does Earth\'s gravity work on? (p.112)',
      options_ar: [
        'الأجسام الصلبة والسائلة والغازية — وتبقي الهواء الجوي محيطاً بالأرض',
        'الصلبة فقط',
        'السائلة فقط',
        'الغازية فقط',
      ],
      options_en: [
        'Solid, liquid, and gas objects — and keeps the atmosphere around Earth',
        'Solids only',
        'Liquids only',
        'Gases only',
      ],
      correct: 0,
      explanation_ar: 'جاذبية الأرض تعمل على الأجسام الصلبة والسائلة والغازية — تبقي الهواء الجوي محيطاً بالأرض.',
    },
    {
      type: 'multiple_choice',
      question_ar: 'ما الوزن؟ (ص 112)',
      question_en: 'What is weight? (p.112)',
      options_ar: [
        'مقدار قوة جذب الأرض للجسم',
        'مقدار الطاقة في الجسم',
        'لون الجسم',
        'حجم الجسم',
      ],
      options_en: [
        'The amount of Earth\'s gravitational pull on an object',
        'The amount of energy in an object',
        'The color of an object',
        'The volume of an object',
      ],
      correct: 0,
      explanation_ar: 'الوزن: مقدار قوة جذب الأرض للجسم — وهو إجابة سؤال "ما مقدار قوة الجاذبية اللازمة لكي أبقى على الأرض؟".',
    },
    {
      type: 'multiple_choice',
      question_ar: 'ما العلاقة بين كتلة الجسم وقوة جاذبية الأرض له؟ (ص 112)',
      question_en: 'What is the relationship between an object\'s mass and Earth\'s gravitational pull? (p.112)',
      options_ar: [
        'كلما زادت كتلة الجسم زادت قوة جاذبية الأرض له (زاد وزنه)',
        'كلما زادت الكتلة نقصت الجاذبية',
        'لا علاقة بين الكتلة والجاذبية',
        'الكتلة تساوي صفر دائماً',
      ],
      options_en: [
        'The more mass an object has, the more Earth\'s gravity pulls it (more weight)',
        'More mass means less gravity',
        'No relation between mass and gravity',
        'Mass is always zero',
      ],
      correct: 0,
      explanation_ar: 'كلما زادت كتلة الجسم زادت قوة جاذبية الأرض له — أي زاد وزنه. الجسم الأثقل (أكبر كتلة) ت attractه الأرض بقوة أكبر.',
    },

    /* ─── نشاط: ألاحظ الجاذبية (ص 112) ─── */
    {
      type: 'ordering',
      question_ar: 'رتّب خطوات نشاط "ألاحظ الجاذبية" (ص 112):',
      question_en: 'Order the steps of the "I observe gravity" activity (p.112):',
      items_ar: [
        'أتوقع: هل تؤثر الجاذبية في جميع الأجسام بالتساوي؟',
        'أمسك قارورة فارغة بإحدى يدي، وقارورة مماثلة معبأة بالماء باليد الأخرى، وأمد يدي بعيداً عن جسمي',
        'ألاحظ: أصف ما أحس به — هل تسحب الأرض القارورتين بالقوة نفسها؟',
        'أستنتج: هل مقدار الجاذبية هو نفسه على القارورتين؟ كيف أتأكد من ذلك؟',
      ],
      items_en: [
        'Predict: does gravity affect all objects equally?',
        'Hold an empty bottle in one hand, and a same bottle filled with water in the other, extend arms',
        'Observe: describe what I feel — does Earth pull both bottles with the same force?',
        'Conclude: is the gravity amount the same on both? How do I verify?',
      ],
      explanation_ar: 'نشاط الجاذبية: توقع ← مسك قارورتين (فارغة ومعبأة) ومدّ اليدين ← ملاحظة ما أحس به ← استنتاج الفرق في الجاذبية.',
    },
    {
      type: 'multiple_choice',
      question_ar: 'في نشاط الجاذبية (ص 112): أيُّ القارورتين تسحبها الأرض بقوة أكبر؟',
      question_en: 'In the gravity activity (p.112): which bottle does Earth pull with greater force?',
      options_ar: [
        'القارورة المعبأة بالماء — لأن كتلتها أكبر فجاذبية الأرض لها أكبر',
        'القارورة الفارغة',
        'كلتاهما بالقوة نفسها',
        'لا تسحب الأرض أي منهما',
      ],
      options_en: [
        'The water-filled bottle — its mass is greater so Earth\'s gravity pulls it more',
        'The empty bottle',
        'Both with the same force',
        'Earth does not pull either',
      ],
      correct: 0,
      explanation_ar: 'القارورة المعبأة بالماء أكبر كتلة — وكلما زادت الكتلة زادت قوة جاذبية الأرض (زاد الوزن). لذلك تسحبها الأرض بقوة أكبر.',
    },
    {
      type: 'true_false',
      question_ar: 'في نشاط الجاذبية (ص 112): تسحب الأرض القارورتين الفارغة والمعبأة بالقوة نفسها.',
      question_en: 'In the gravity activity (p.112): Earth pulls the empty and filled bottles with the same force.',
      correct: 'false',
      explanation_ar: 'لا تسحب الأرض القارورتين بالقوة نفسها — القارورة المعبأة بالماء أكبر كتلة فتسحبها الأرض بقوة أكبر (وزنها أكبر).',
    },

    /* ─── الاحتكاك (ص 113) ─── */
    {
      type: 'multiple_choice',
      question_ar: 'ما قوة الاحتكاك؟ (ص 113)',
      question_en: 'What is friction force? (p.113)',
      options_ar: [
        'قوة تنشأ عن حركة الأجسام عندما تحتك بأجسام أخرى، تعمل ضد اتجاه الحركة وتبطئها وتوقفها',
        'قوة تجذب بها الأرض الأجسام',
        'قوة تجذب المغناطيس الحديد',
        'قوة دفع الأشياء بعيداً',
      ],
      options_en: [
        'A force arising when moving objects rub against others, opposes motion and slows/stops it',
        'A force by which Earth pulls objects',
        'A force by which magnets attract iron',
        'A force pushing things away',
      ],
      correct: 0,
      explanation_ar: 'الاحتكاك: قوة تنشأ عند احتكاك الأجسام المتحركة بأجسام أخرى — تعمل ضد اتجاه الحركة وتبطئها وتوقفها.',
    },
    {
      type: 'multiple_choice',
      question_ar: 'في أي اتجاه تعمل قوة الاحتكاك؟ (ص 113)',
      question_en: 'In which direction does friction force act? (p.113)',
      options_ar: [
        'ضد اتجاه حركة الجسم — تبطئه وتوقفه',
        'مع اتجاه حركة الجسم — تسرّعه',
        'عمودية على الحركة',
        'لا اتجاه للاحتكاك',
      ],
      options_en: [
        'Against the direction of motion — slows and stops it',
        'With the motion — accelerates it',
        'Perpendicular to motion',
        'Friction has no direction',
      ],
      correct: 0,
      explanation_ar: 'قوة الاحتكاك تعمل ضد اتجاه حركة الجسم — تبطئه وتوقفه. لذلك تتوقف الكرة المتدحرجة على الأرض بعد فترة.',
    },
    {
      type: 'multiple_choice',
      question_ar: 'لماذا يُستخدم الزيت في الآلات المتحركة؟ (ص 113)',
      question_en: 'Why is oil used in moving machines? (p.113)',
      options_ar: [
        'للتقليل من الاحتكاك بين أجزاء الآلات المتحركة',
        'لزيادة الاحتكاك',
        'لتغيير لون الآلة',
        'لتسخين الآلة',
      ],
      options_en: [
        'To reduce friction between moving machine parts',
        'To increase friction',
        'To change the machine color',
        'To heat the machine',
      ],
      correct: 0,
      explanation_ar: 'الزيت يقلل الاحتكاك بين أجزاء الآلات المتحركة — يجعلها تتحرك بسلاسة وتقلل التآكل.',
    },
    {
      type: 'multiple_choice',
      question_ar: 'كيف توقف المكابح (الفرامل) السيارة المتحركة؟ (ص 113)',
      question_en: 'How do brakes stop a moving car? (p.113)',
      options_ar: [
        'بزيادة الاحتكاك بين الإطارات والطريق',
        'بتقليل الاحتكاك',
        'بزيادة سرعة السيارة',
        'بإضافة الزيت',
      ],
      options_en: [
        'By increasing friction between tires and road',
        'By reducing friction',
        'By increasing car speed',
        'By adding oil',
      ],
      correct: 0,
      explanation_ar: 'المكابح (الفرامل) توقف السيارة عن طريق زيادة الاحتكاك بين الإطارات والطريق — الاحتكاك يبطئها ويوقفها.',
    },
    {
      type: 'true_false',
      question_ar: 'عندما أتزلج وأريد أن أتوقف، أجعل الكابح المطاطي يلامس الأرض فيسبب احتكاكاً يوقفني. (ص 113)',
      question_en: 'When skating and I want to stop, I make the rubber brake touch the ground causing friction that stops me. (p.113)',
      correct: 'true',
      explanation_ar: 'الكابح المطاطي للتزلج يلامس الأرض فينشأ احتكاك يبطئ الحركة ويوقفها — الاحتكاك قوة توقف الأجسام المتحركة.',
    },
    {
      type: 'multiple_choice',
      question_ar: 'على أي نوع من السطوح يكون الاحتكاك أكبر؟ (ص 113)',
      question_en: 'On which type of surface is friction greater? (p.113)',
      options_ar: [
        'السطوح الخشنة — يحتاج دفعها لجسم قوة أكبر',
        'السطوح الملساء',
        'السطوح المبللة بالزيت',
        'لا فرق بين السطوح',
      ],
      options_en: [
        'Rough surfaces — need greater force to push objects',
        'Smooth surfaces',
        'Oiled surfaces',
        'No difference between surfaces',
      ],
      correct: 0,
      explanation_ar: 'قوة الاحتكاك أكبر على السطوح الخشنة — يصعب دفع أو سحب جسم على سطح خشن لأنه يحتاج قوة أكبر من السطح الأملس.',
    },
    {
      type: 'multiple_choice',
      question_ar: 'لماذا يصعب دفع جسم على سطح خشن؟ (ص 113)',
      question_en: 'Why is it hard to push an object on a rough surface? (p.113)',
      options_ar: [
        'لأن الاحتكاك أكبر على السطوح الخشنة فيحتاج قوة أكبر',
        'لأن الاحتكاك أقل على الخشن',
        'لأن السطح خشن لا يؤثر',
        'لا علاقة لخشونة السطح',
      ],
      options_en: [
        'Because friction is greater on rough surfaces, needing more force',
        'Because friction is less on rough surfaces',
        'Because rough surface does not affect',
        'Roughness is unrelated',
      ],
      correct: 0,
      explanation_ar: 'الاحتكاك أكبر على السطوح الخشنة — لذلك يحتاج دفع الجسم قوة أكبر من القوة اللازمة على سطح أملس.',
    },
    {
      type: 'classify',
      question_ar: 'صنّف كل سطح إلى: احتكاكه كبير / احتكاكه قليل (ص 113):',
      question_en: 'Classify each surface as: high friction / low friction (p.113):',
      categories_ar: ['احتكاكه كبير (خشن)', 'احتكاكه قليل (أملس)'],
      categories_en: ['High friction (rough)', 'Low friction (smooth)'],
      items_ar: ['لوح تقطيع البصل (كرتون)', 'صينية بلاستيك (مرآة)', 'الأسفلت', 'الزجاج', 'الرمل', 'الجليد'],
      items_en: ['Onion cutting board (cardboard)', 'Plastic tray (mirror)', 'Asphalt', 'Glass', 'Sand', 'Ice'],
      correct_categories: [0, 1, 0, 1, 0, 1],
      explanation_ar: 'احتكاك كبير (خشن): الكرتون، الأسفلت، الرمل. احتكاك قليل (أملس): المرآة، الزجاج، الجليد.',
    },
    {
      type: 'ordering',
      question_ar: 'رتّب خطوات نشاط الاحتكاك (ص 113): تحريك قطعة خشبية على سطح مائل مغطى بمواد مختلفة:',
      question_en: 'Order the steps of the friction activity (p.113): moving a wooden piece on an inclined surface covered with different materials:',
      items_ar: [
        'أحرّك قطعة خشبية على سطح مائل',
        'أغطي سطحه مرة بصينية بلاستيك (مرآة)',
        'أغطيه مرة أخرى بلوح تقطيع البصل (كرتون)',
        'أقارن بين مقادير القوى اللازمة لتحريك القطعة على السطوح المختلفة',
      ],
      items_en: [
        'Move a wooden piece on an inclined surface',
        'Cover it once with a plastic tray (mirror)',
        'Cover it again with an onion cutting board (cardboard)',
        'Compare the amounts of force needed to move the piece on different surfaces',
      ],
      explanation_ar: 'نشاط الاحتكاك: تحريك قطعة خشبية ← تغطية بمرآة (أملس) ← تغطية بكرتون (خشن) ← مقارنة القوى اللازمة. الخشن يحتاج قوة أكبر.',
    },
    {
      type: 'multiple_choice',
      question_ar: 'فيمَ تتشابه قوة الجاذبية وقوة الاحتكاك؟ (ص 113)',
      question_en: 'How are gravity and friction similar? (p.113)',
      options_ar: [
        'كلتاهما قوى تؤثر في الأجسام — الجاذبية تسحبها للأسفل والاحتكاك يبطئ حركتها',
        'كلتاهما تسرّع الأجسام',
        'كلتاهما لا تؤثر في الأجسام',
        'لا تشابه بينهما',
      ],
      options_en: [
        'Both are forces affecting objects — gravity pulls down, friction slows motion',
        'Both accelerate objects',
        'Both do not affect objects',
        'No similarity between them',
      ],
      correct: 0,
      explanation_ar: 'الجاذبية والاحتكاك قوى تؤثر في الأجسام: الجاذبية تسحبها للأسفل، والاحتكاك يبطئ حركتها. كلتاهما قوى تغيّر الحركة.',
    },

    /* ─── مراجعة الدرس الأول (ص 114-115) ─── */
    {
      type: 'multiple_choice',
      question_ar: 'كيف تغيّر القوى الحركة؟ (ص 114 مراجعة)',
      question_en: 'How do forces change motion? (p.114 review)',
      options_ar: [
        'تحرّك الساكنة، توقف المتحركة، أو تغيّر اتجاهها — اللاعبون يستخدمون القوى في الملعب',
        'تغيّر لون الكرة فقط',
        'لا تغيّر الحركة',
        'تغيّر حجم الكرة',
      ],
      options_en: [
        'Move stationary, stop moving, or change direction — players use forces on the field',
        'Only change ball color',
        'Do not change motion',
        'Change ball size',
      ],
      correct: 0,
      explanation_ar: 'القوى تغيّر الحركة: تحرّك الساكنة، توقف المتحركة، تغيّر الاتجاه. اللاعبون يستخدمون القوى لتحريك الكرة وإيقافها وتغيير اتجاهها.',
    },
    {
      type: 'multiple_choice',
      question_ar: 'أفكر في لعبة رياضية تستخدم فيها الكرة. كيف يتغير اتجاه الكرة؟ (ص 114)',
      question_en: 'I think of a sport using a ball. How does the ball direction change? (p.114)',
      options_ar: [
        'بقوة اللاعب الذي يركلها أو يضربها — القوة تغيّر اتجاه حركتها',
        'تتغير وحدها',
        'لا يتغير اتجاهها',
        'يتغير بالهواء فقط',
      ],
      options_en: [
        'By the force of the player who kicks or hits it — force changes its direction',
        'It changes by itself',
        'Its direction does not change',
        'Only changes by air',
      ],
      correct: 0,
      explanation_ar: 'اتجاه الكرة يتغير بقوة اللاعب — ركلها أو ضربها يغيّر اتجاه حركتها. القوة تغيّر اتجاه الحركة.',
    },
    {
      type: 'multiple_choice',
      question_ar: 'كيف يؤثر حارس المرمى بقوة في الكرة؟ (ص 114)',
      question_en: 'How does the goalkeeper exert force on the ball? (p.114)',
      options_ar: [
        'بقوة للإمساك بها (إيقافها) وبقوة لتمريرها للاعب آخر (تحريكها)',
        'فقط بإمساكها',
        'فقط بتمريرها',
        'لا يؤثر بقوة',
      ],
      options_en: [
        'With force to catch it (stop) and force to pass it to another player (move)',
        'Only by catching',
        'Only by passing',
        'Does not exert force',
      ],
      correct: 0,
      explanation_ar: 'حارس المرمى يؤثر بقوة في الكرة: قوة لإمساكها (إيقاف حركتها) وقوة لتمريرها لزميله (بدء/تغيير حركتها).',
    },
    {
      type: 'multiple_choice',
      question_ar: 'السبب والنتيجة (ص 115): ماذا يحدث إذا زدت القوة التي أؤثر بها في جسم؟',
      question_en: 'Cause and effect (p.115): What happens if I increase the force I exert on an object?',
      options_ar: [
        'تزداد سرعته أو المسافة التي يقطعها — القوة الأكبر تسرّع الحركة',
        'تنقص سرعته',
        'يتوقف',
        'لا يحدث شيء',
      ],
      options_en: [
        'Its speed or distance increases — greater force accelerates motion',
        'Its speed decreases',
        'It stops',
        'Nothing happens',
      ],
      correct: 0,
      explanation_ar: 'زيادة القوة تزيد سرعة الجسم والمسافة التي يقطعها — كلما زادت القوة زادت سرعة الحركة.',
    },
    {
      type: 'multiple_choice',
      question_ar: 'عندما أركب الأرجوحة، ما القوة التي تجعلني أتباطأ وأنا أرتفع إلى أعلى؟ (ص 115)',
      question_en: 'When I ride a swing, what force slows me as I rise upward? (p.115)',
      options_ar: [
        'الجاذبية — تسحبني الأرض للأسفل فأتباطأ عند الارتفاع',
        'الاحتكاك فقط',
        'المغناطيسية',
        'لا توجد قوة',
      ],
      options_en: [
        'Gravity — Earth pulls me down so I slow as I rise',
        'Friction only',
        'Magnetism',
        'No force',
      ],
      correct: 0,
      explanation_ar: 'الجاذبية هي القوة التي تبطئني على الأرجوحة عند الارتفاع — تسحبني الأرض للأسفل فأتباطأ ثم أعود.',
    },
    {
      type: 'multiple_choice',
      question_ar: 'السؤال الأساسي للدرس الأول: كيف تغيّر القوى الحركة؟ (ص 115)',
      question_en: 'Essential question for Lesson 1: How do forces change motion? (p.115)',
      options_ar: [
        'القوى تحرّك الساكن، تسرّع المتحرك، تبطئه، توقفه، وتغيّر اتجاهه',
        'فقط تحرّك الساكن',
        'فقط توقف المتحرك',
        'لا تغيّر الحركة',
      ],
      options_en: [
        'Forces move stationary, accelerate, slow, stop, and change direction',
        'Only move stationary',
        'Only stop moving',
        'Do not change motion',
      ],
      correct: 0,
      explanation_ar: 'القوى تغيّر الحركة بكل الطرق: تحريك الساكن، تسريع المتحرك، إبطاؤه، إيقافه، وتغيير اتجاهه.',
    },
    {
      type: 'multiple_choice',
      question_ar: 'العلوم والمجتمع (ص 115): أفكر في لعبة رياضية مشهورة وأصف ما بها من قوى السحب والدفع. ما اللعبة الشهيرة؟',
      question_en: 'Science and Society (p.115): I think of a famous sport and describe its push and pull forces. What is a famous sport?',
      options_ar: [
        'كرة القدم — دفع (ركل) الكرة، سحب (جذب) اللاعب للكرة، الاحتكاك مع الأرض',
        'الشطرنج فقط',
        'لا توجد لعبة',
        'السباحة فقط',
      ],
      options_en: [
        'Soccer — pushing (kicking) the ball, pulling the player toward the ball, friction with ground',
        'Chess only',
        'No sport',
        'Swimming only',
      ],
      correct: 0,
      explanation_ar: 'كرة القدم لعبة مشهورة بها قوى: دفع (ركل الكرة)، سحب (جذب اللاعب)، احتكاك (الكرة بالأرض). العلوم والمجتمع يربطان القوى بالرياضة.',
    },
    {
      type: 'multiple_choice',
      question_ar: 'العلوم والرياضيات (ص 115): ما المسافة التي تتحركها الكرة؟ أراد الطلاب حساب...',
      question_en: 'Science and Math (p.115): What distance does the ball travel? Students wanted to calculate...',
      options_ar: [
        'المسافة التي تقطعها الكرة أثناء تمريرها لإحراز هدف',
        'وزن الكرة',
        'لون الكرة',
        'حجم الكرة',
      ],
      options_en: [
        'The distance the ball travels while passing to score a goal',
        'The ball\'s weight',
        'The ball\'s color',
        'The ball\'s volume',
      ],
      correct: 0,
      explanation_ar: 'العلوم والرياضيات: حساب المسافة التي تقطعها الكرة أثناء تمريرها لإحراز هدف — يربط القوى بقياس المسافة.',
    },
  ],
};

/* ════════════════════════════════════════════════════
 *  الدرس الثاني: ما المغناطيس؟ (ص 113+) — يُكمل لاحقاً
 * ════════════════════════════════════════════════════ */
export const FORCES_LESSON_2 = {
  id: 'what_is_magnet',
  title_ar: 'الدرس الثاني: ما المغناطيس؟',
  title_en: 'Lesson 2: What Is a Magnet?',
  questions: [
    {
      type: 'multiple_choice',
      question_ar: 'ما السؤال الأساسي للدرس الثاني؟ (ص 104)',
      question_en: 'What is the essential question for Lesson 2? (p.104)',
      options_ar: ['ما المغناطيس؟', 'كيف تُغيّر القوى الحركة؟', 'كيف نقيس المادة؟', 'ما التغيرات الكيميائية؟'],
      options_en: ['What is a magnet?', 'How do forces change motion?', 'How do we measure matter?', 'What are chemical changes?'],
      correct: 0,
      explanation_ar: 'السؤال الأساسي للدرس الثاني: ما المغناطيس؟ — المغناطيس جسم يجذب بعض المعادن مثل الحديد.',
    },
    {
      type: 'true_false',
      question_ar: 'المغناطيس يجذب جميع أنواع المعادن بما فيها الألومنيوم.',
      question_en: 'A magnet attracts all types of metals including aluminum.',
      correct: 'false',
      explanation_ar: 'المغناطيس لا يجذب كل المعادن — يجذب الحديد والصلب والنيكل والكوبالت، لكن لا يجذب الألومنيوم أو النحاس.',
    },
    {
      type: 'ordering',
      question_ar: 'رتّب خطوات مقارنة قوة المغناطيسات المختلفة:',
      question_en: 'Order the steps for comparing different magnet strengths:',
      items_ar: ['اختر عدة مغناطيسات مختلفة', 'ضع كل مغناطيس قرب مجموعة من الدبابيس', 'عُدّ عدد الدبابيس التي جذبها كل مغناطيس', 'قارن النتائج واستنتج أيها أقوى'],
      items_en: ['Choose several different magnets', 'Place each magnet near a group of pins', 'Count pins attracted by each magnet', 'Compare results and conclude which is strongest'],
      explanation_ar: 'مقارنة قوة المغناطيسات: اختيار ← وضع قرب دبابيس ← العد ← المقارنة والاستنتاج.',
    },
    {
      type: 'multiple_choice',
      question_ar: 'ما قطبا المغناطيس؟ (ص 105)',
      question_en: 'What are the magnet poles? (p.105)',
      options_ar: [
        'طرفا المغناطيس، حيث تكون قوة الجذب عندهما أكبر ما يمكن — شمالي (ش) وجنوبي (ع)',
        'منتصف المغناطيس',
        'قوة تجذب بها الأرض الأجسام',
        'تباعد الأجسام',
      ],
      options_en: [
        'The two ends of a magnet, where attraction is greatest — north (N) and south (S)',
        'The middle of the magnet',
        'Earth\'s pull on objects',
        'Objects moving apart',
      ],
      correct: 0,
      explanation_ar: 'قطبا المغناطيس: طرفاه — عندهما قوة الجذب أكبر ما يمكن. القطب الشمالي (ش) والقطب الجنوبي (ع).',
    },
    {
      type: 'multiple_choice',
      question_ar: 'ما التجاذب بين المغناطيسين؟ (ص 105)',
      question_en: 'What is attraction between magnets? (p.105)',
      options_ar: [
        'سحب المغناطيسين بعضهما لبعض — عند تقريب قطبين مختلفين (ش وع)',
        'تباعد المغناطيسين عن بعضهما',
        'لا يحدث شيء',
        'ينكسر المغناطيس',
      ],
      options_en: [
        'Magnets pulling each other together — when different poles approach (N and S)',
        'Magnets moving apart',
        'Nothing happens',
        'The magnet breaks',
      ],
      correct: 0,
      explanation_ar: 'التجاذب: سحب الأجسام بعضها لبعض — عند تقريب قطبين مختلفين (شمالي وجنوبي) يتجاذبان ويلتصقان.',
    },
    {
      type: 'multiple_choice',
      question_ar: 'ما التنافر بين المغناطيسين؟ (ص 105)',
      question_en: 'What is repulsion between magnets? (p.105)',
      options_ar: [
        'تباعد المغناطيسين عن بعضهما — عند تقريب قطبين متشابهين (ش وش أو ع وع)',
        'سحب المغناطيسين لبعضهما',
        'لا يحدث شيء',
        'ينكسر المغناطيس',
      ],
      options_en: [
        'Magnets moving apart — when same poles approach (N and N, or S and S)',
        'Magnets pulling each other',
        'Nothing happens',
        'The magnet breaks',
      ],
      correct: 0,
      explanation_ar: 'التنافر: تباعد الأجسام بعضها عن بعض — عند تقريب قطبين متشابهين (شمالي وشمالي، أو جنوبي وجنوبي) يتنافران ويتباعدان.',
    },
    {
      type: 'classify',
      question_ar: 'صنّف كل حالة تقريب مغناطيسين إلى: تجاذب / تنافر (ص 105):',
      question_en: 'Classify each case of approaching magnets as: attraction / repulsion (p.105):',
      categories_ar: ['تجاذب (التصاق)', 'تنافر (تباعد)'],
      categories_en: ['Attraction (sticking)', 'Repulsion (moving apart)'],
      items_ar: ['ش + ع', 'ش + ش', 'ع + ع', 'ع + ش'],
      items_en: ['N + S', 'N + N', 'S + S', 'S + N'],
      correct_categories: [0, 1, 1, 0],
      explanation_ar: 'تجاذب: الأقطاب المختلفة (ش+ع، ع+ش). تنافر: الأقطاب المتشابهة (ش+ش، ع+ع). الأضداد تتجاذب والمتشابهات تتنافر.',
    },

    /* ─── ماذا تفعل المغناطيسات؟ (ص 116-117) ─── */
    {
      type: 'multiple_choice',
      question_ar: 'ماذا تفعل المغناطيسات؟ (ص 117)',
      question_en: 'What do magnets do? (p.117)',
      options_ar: [
        'تجذب أو تسحب بعض الأجسام — حتى في وجود حواجز صلبة أو سائلة أو غازية',
        'تدفع الأجسام بعيداً',
        'تغيّر لون الأجسام',
        'لا تفعل شيئاً',
      ],
      options_en: [
        'Attract or pull some objects — even through solid, liquid, or gas barriers',
        'Push objects away',
        'Change object color',
        'Do nothing',
      ],
      correct: 0,
      explanation_ar: 'المغناطيس يجذب أو يسحب بعض الأجسام — يمكنه جذبها حتى في وجود حواجز صلبة أو سائلة أو غازية.',
    },
    {
      type: 'multiple_choice',
      question_ar: 'ما السؤال الأساسي للدرس الثاني؟ (ص 117)',
      question_en: 'What is the essential question for Lesson 2? (p.117)',
      options_ar: ['ما المغناطيسات؟', 'كيف تُغيّر القوى الحركة؟', 'ما الاحتكاك؟', 'ما الجاذبية؟'],
      options_en: ['What are magnets?', 'How do forces change motion?', 'What is friction?', 'What is gravity?'],
      correct: 0,
      explanation_ar: 'السؤال الأساسي للدرس الثاني: ما المغناطيسات؟ — المغناطيسات أجسام تجذب الحديد وتصنع منه.',
    },
    {
      type: 'multiple_choice',
      question_ar: 'هل يستطيع المغناطيس القوي جذب الأجسام البعيدة عنه؟ (ص 117)',
      question_en: 'Can a strong magnet attract objects far from it? (p.117)',
      options_ar: [
        'نعم — المغناطيس القوي يجذب الأجسام البعيدة عنه',
        'لا — يجذب فقط الملامسة',
        'يجذب فقط الأجسام الصغيرة',
        'لا يجذب أي شيء',
      ],
      options_en: [
        'Yes — a strong magnet attracts objects far from it',
        'No — only attracts touching objects',
        'Only attracts small objects',
        'Attracts nothing',
      ],
      correct: 0,
      explanation_ar: 'المغناطيس القوي يستطيع جذب الأجسام البعيدة عنه — وكلما ابتعد المغناطيس عن الجسم ضعفت قوة جذبه.',
    },
    {
      type: 'true_false',
      question_ar: 'كلما ابتعد المغناطيس عن الجسم ضعفت قوة جذبه له. (ص 117)',
      question_en: 'The farther the magnet is from an object, the weaker its attraction. (p.117)',
      correct: 'true',
      explanation_ar: 'قوة جذب المغناطيس تضعف مع البعد — المغناطيس القوي يجذب من مسافة أبعد، لكن مع البعد تضعف القوة تدريجياً.',
    },
    {
      type: 'multiple_choice',
      question_ar: 'ممَ تُصنع المغناطيسات؟ (ص 117)',
      question_en: 'What are magnets made of? (p.117)',
      options_ar: ['من الحديد', 'من الخشب', 'من البلاستيك', 'من الزجاج'],
      options_en: ['Of iron', 'Of wood', 'Of plastic', 'Of glass'],
      correct: 0,
      explanation_ar: 'المغناطيسات تُصنع من الحديد — وتجذب الأجسام التي تحتوي على حديد.',
    },
    {
      type: 'multiple_choice',
      question_ar: 'ما الأجسام التي يجذبها المغناطيس؟ (ص 117)',
      question_en: 'What objects does a magnet attract? (p.117)',
      options_ar: [
        'الأجسام التي تحتوي على حديد',
        'كل الأجسام',
        'الأجسام الخشبية فقط',
        'الأجسام البلاستيكية فقط',
      ],
      options_en: [
        'Objects containing iron',
        'All objects',
        'Wooden objects only',
        'Plastic objects only',
      ],
      correct: 0,
      explanation_ar: 'المغناطيس يجذب الأجسام التي تحتوي على حديد — مثل مشابك الورق والمسمار. لا يجذب الخشب أو الزجاج أو البلاستيك.',
    },
    {
      type: 'multiple_choice',
      question_ar: 'كيف يثبت المغناطيس الأوراق ويمنعها من السقوط؟ (ص 117)',
      question_en: 'How does a magnet hold papers and prevent them from falling? (p.117)',
      options_ar: [
        'يجذب القطع الحديدية (مثل مشابك الورق) التي تثبت الأوراق في مكانها',
        'يلصق الأوراق بالغراء',
        'يدفع الأوراق للأسفل',
        'لا علاقة له بالأوراق',
      ],
      options_en: [
        'Attracts iron pieces (like paper clips) that hold the papers in place',
        'Glues papers together',
        'Pushes papers down',
        'Unrelated to papers',
      ],
      correct: 0,
      explanation_ar: 'المغناطيس يثبت الأوراق بمشابك الورق الحديدية — يجذب المشابك فتثبت الأوراق في مكانها وتمنعها من السقوط.',
    },
    {
      type: 'true_false',
      question_ar: 'المغناطيس يجذب الأجسام حتى في وجود حواجز صلبة أو سائلة أو غازية. (ص 117)',
      question_en: 'A magnet attracts objects even through solid, liquid, or gas barriers. (p.117)',
      correct: 'true',
      explanation_ar: 'المغناطيس يجذب الأجسام الحديدية حتى عبر حواجز — صلبة (ورق)، سائلة (ماء)، غازية (هواء). قوته تعمل عن بُعد.',
    },
  ],
};

export const FORCES_CHAPTER = {
  id: 'forces_chapter',
  title_ar: 'الفصل الحادي عشر: القوى',
  title_en: 'Chapter 11: Forces',
  lessons: [FORCES_VOCAB_LESSON, FORCES_LESSON_1, FORCES_LESSON_2],
};