// العلوم - الصف الثاني الابتدائي - الفصل الأول
// الوحدة الثانية: المواطن
// مستخرج من كتاب الطالب 1447هـ / 2025م

export const U2_QUESTIONS = [
  // ─── الدرس 1: ما المواطن؟ (ص76-80) ────────────────────────────────────
  {
    id:'u2q1', unit:'u2', lesson:'u2l1', page:76, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'الموطن هو:',
    paragraph:'المَوْطِنُ هُوَ المَكانُ الَّذِي يَعِيشُ فِيهِ الكَائِنُ الحَيّ، وَيَجِدُ فِيهِ حاجاتِهِ مِنْ مَأْوىً وغِذاءٍ وماء. (ص76)',
    image:'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=600',
    options:[
      {text:'المكان الذي يعيش فيه الكائن الحي ويجد فيه حاجاته',correct:true},
      {text:'مكان اللعب فقط',correct:false},
      {text:'مكان النوم فقط',correct:false},
      {text:'الطريق إلى المدرسة',correct:false},
    ],
    explanation:'الموطن هو المكان الذي يعيش فيه الكائن الحي ويجد فيه المأوى والغذاء والماء.',
    goldenRule:'الموطن = بيت الكائن الحي = مأوى + غذاء + ماء.',
    feedbackQuestion:{question:'أين يعيش السمك؟',options:[{text:'في الماء (موطنه)',correct:true},{text:'في الجو',correct:false},{text:'في الصحراء',correct:false},{text:'في الجبال',correct:false}]},
  },
  {
    id:'u2q2', unit:'u2', lesson:'u2l1', page:76, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'الكائن الحي يحصل في موطنه على:',
    paragraph:'يَجِدُ فِيهِ حاجاتِهِ مِنْ مَأْوىً وغِذاءٍ وماء. (ص76)',
    image:'https://images.unsplash.com/photo-1500382017468-9049fedbd096?w=600',
    options:[
      {text:'المأوى والغذاء والماء',correct:true},
      {text:'الظلام فقط',correct:false},
      {text:'الضوضاء فقط',correct:false},
      {text:'الملح فقط',correct:false},
    ],
    explanation:'الموطن يوفر للكائن الحي المأوى والغذاء والماء الضرورية لحياته.',
    goldenRule:'حاجات الكائن في موطنه: مأوى + غذاء + ماء.',
    feedbackQuestion:{question:'أي مما يلي يوفره الموطن للكائن الحي؟',options:[{text:'المأوى والغذاء والماء',correct:true},{text:'الضوضاء',correct:false},{text:'الظلام',correct:false},{text:'البرد',correct:false}]},
  },
  {
    id:'u2q3', unit:'u2', lesson:'u2l1', page:76, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'موطن النبات هو:',
    paragraph:'مَوْطِنُ النَّباتِ التُّرْبَة. مَوْطِنُ الحُوتِ البَحْر. مَوْطِنُ الطائِرِ العُشّ. (ص76)',
    image:'https://images.unsplash.com/photo-1416879595882-3373a048020a?w=600',
    options:[
      {text:'التربة',correct:true},
      {text:'البحر',correct:false},
      {text:'العش',correct:false},
      {text:'الجو',correct:false},
    ],
    explanation:'موطن النبات التربة التي ينمو فيها ويجد فيها الماء والمعادن.',
    goldenRule:'موطن النبات = التربة. موطن الحوت = البحر. موطن الطائر = العش.',
    feedbackQuestion:{question:'ما موطن الحوت؟',options:[{text:'البحر',correct:true},{text:'التربة',correct:false},{text:'العش',correct:false},{text:'الصحراء',correct:false}]},
  },
  {
    id:'u2q4', unit:'u2', lesson:'u2l1', page:76, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'موطن الطائر هو:',
    paragraph:'مَوْطِنُ الطائِرِ العُشّ. (ص76)',
    image:'https://images.unsplash.com/photo-1444464669806-84f9a4e4e3b7?w=600',
    options:[
      {text:'العش',correct:true},
      {text:'البحر',correct:false},
      {text:'التربة',correct:false},
      {text:'الكهف',correct:false},
    ],
    explanation:'موطن الطائر العش الذي يبنيه ليضع بيضه ويحضن صغاره.',
    goldenRule:'موطن الطائر = العش الذي يبنيه بنفسه.',
    feedbackQuestion:{question:'ما موطن السمكة؟',options:[{text:'الماء',correct:true},{text:'العش',correct:false},{text:'التربة',correct:false},{text:'الكهف',correct:false}]},
  },
  {
    id:'u2q5', unit:'u2', lesson:'u2l1', page:76, type:'matching',
    bloom:'understand', difficulty:'easy',
    question:'صِل كل كائن حي بموطنه:',
    paragraph:'مَوْطِنُ النَّباتِ التُّرْبَة. مَوْطِنُ الحُوتِ البَحْر. مَوْطِنُ الطائِرِ العُشّ. (ص76)',
    pairs:[
      {left:'النبات',right:'التربة'},
      {left:'الحوت',right:'البحر'},
      {left:'الطائر',right:'العش'},
      {left:'السمكة',right:'الماء'},
    ],
    explanation:'لكل كائن حي موطن يناسبه يوفر له حاجاته.',
    goldenRule:'كل كائن حي له موطن خاص يناسبه.',
  },
  {
    id:'u2q6', unit:'u2', lesson:'u2l1', page:76, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف: أيها موطن في اليابسة وأيها في الماء؟',
    paragraph:'الأَمْكِنَةُ الَّتِي تَعِيشُ فِيها المُخْلُوقاتُ الحَيَّة: تُرْبَة، بَحْر، غابَة، بَحِيرَة. (ص76)',
    categories:['موطن في اليابسة 🌳','موطن في الماء 🌊'],
    items:[
      {text:'التربة',correct_category:0},
      {text:'البحر',correct_category:1},
      {text:'الغابة',correct_category:0},
      {text:'البحيرة',correct_category:1},
      {text:'الكهف',correct_category:0},
      {text:'النهر',correct_category:1},
    ],
    explanation:'موطن اليابسة: التربة، الغابة، الكهف. موطن الماء: البحر، البحيرة، النهر.',
    goldenRule:'المواطن نوعان: في اليابسة + في الماء.',
  },
  {
    id:'u2q7', unit:'u2', lesson:'u2l1', page:77, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'يمكن أن يعيش الكائن الحي في أي مكان بدون أن يجد حاجاته.',
    paragraph:'يَجِدُ الكَائِنُ الحَيُّ فِي مَوْطِنِهِ حاجاتِهِ مِنْ مَأْوىً وغِذاءٍ وماء. (ص76)',
    image:'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=600',
    correctAnswer:false,
    explanation:'لا يستطيع الكائن الحي العيش إلا في موطن يجد فيه حاجاته من مأوى وغذاء وماء.',
    goldenRule:'لا حياة بلا موطن — الموطن يوفر الحاجات الأساسية.',
    feedbackQuestion:{question:'ماذا يحدث إذا ترك السمك موطنه (الماء)؟',options:[{text:'يموت',correct:true},{text:'يكبر',correct:false},{text:'يطير',correct:false},{text:'ينام',correct:false}]},
  },
  {
    id:'u2q8', unit:'u2', lesson:'u2l1', page:77, type:'multipleChoice',
    bloom:'apply', difficulty:'medium',
    question:'إذا أردت أن أعرف موطن الأرنب فأبحث عن مكان يجد فيه:',
    paragraph:'يَجِدُ الكَائِنُ الحَيُّ فِي مَوْطِنِهِ حاجاتِهِ. (ص76)',
    image:'https://images.unsplash.com/photo-1535241749838-299277b6305f?w=600',
    options:[
      {text:'مأوى وغذاء وماء',correct:true},
      {text:'ظلام فقط',correct:false},
      {text:'حرارة شديدة',correct:false},
      {text:'ضوضاء',correct:false},
    ],
    explanation:'موطن الأرنب هو المكان الذي يجد فيه المأوى والغذاء والماء — مثل الحقول والحدائق.',
    goldenRule:'الموطن المناسب = المأوى + الغذاء + الماء.',
    feedbackQuestion:{question:'أين يعيش الأرنب عادةً؟',options:[{text:'في الحقول والحدائق',correct:true},{text:'في البحر',correct:false},{text:'في الكهوف الجليدية',correct:false},{text:'في الصحراء الحارة',correct:false}]},
  },
  {
    id:'u2q9', unit:'u2', lesson:'u2l1', page:78, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'لماذا لا يعيش الحوت في الصحراء؟',
    paragraph:'يَجِدُ الكَائِنُ الحَيُّ فِي مَوْطِنِهِ حاجاتِهِ مِنْ مَأْوىً وغِذاءٍ وماء. (ص76)',
    image:'https://images.unsplash.com/photo-1573529287898-5e5b9f7b4c2e?w=600',
    options:[
      {text:'لأنه لا يجد الماء والغذاء المناسبين',correct:true},
      {text:'لأنه يخاف من الرمل',correct:false},
      {text:'لأنه لا يحب الضوء',correct:false},
      {text:'لأنه كبير الحجم',correct:false},
    ],
    explanation:'الحوت يحتاج الماء للعيش والتنفس بالخياشيم، والصحراء لا توفر له ذلك.',
    goldenRule:'كل كائن حي يعيش في الموطن الذي يوفر له حاجاته.',
    feedbackQuestion:{question:'ما الذي يحتاجه الحوت ليعيش؟',options:[{text:'الماء',correct:true},{text:'الرمل',correct:false},{text:'الظلام',correct:false},{text:'الحرارة',correct:false}]},
  },
  {
    id:'u2q10', unit:'u2', lesson:'u2l1', page:78, type:'fillBlank',
    bloom:'remember', difficulty:'easy',
    question:'أكمل: الموطن هو المكان الذي ___ فيه الكائن الحي.',
    paragraph:'المَوْطِنُ هُوَ المَكانُ الَّذِي يَعِيشُ فِيهِ الكَائِنُ الحَيّ. (ص76)',
    blanks:['يعيش'],
    wordBank:['يعيش','يلعب','ينام','يطير'],
    explanation:'الموطن هو المكان الذي يعيش فيه الكائن الحي ويجد فيه حاجاته.',
    goldenRule:'الموطن = مكان عيش الكائن الحي.',
  },

  // ─── الدرس 2: الصحراء الحارة (ص82-88) ──────────────────────────────
  {
    id:'u2q11', unit:'u2', lesson:'u2l2', page:82, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'الصحراء الحارة موطن يتميز بـ:',
    paragraph:'الصَّحْراءُ الحارَّةُ مَكانٌ يَقِلُّ فِيهِ الماءُ جِدّاً، وَيَكْثُرُ فِيهِ الرَّمْلُ وَالحَصَى، وَتَعْلُو دَرَجَةُ حَرارَتِه. (ص82)',
    image:'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=600',
    options:[
      {text:'قلة الماء وكثرة الرمل والحرارة العالية',correct:true},
      {text:'كثرة الماء والثلج',correct:false},
      {text:'الغابات الكثيفة',correct:false},
      {text:'البرودة الشديدة',correct:false},
    ],
    explanation:'الصحراء الحارة قليلة الماء، كثيرة الرمل والحصى، عالية الحرارة.',
    goldenRule:'الصحراء الحارة = قلة ماء + رمل + حرارة عالية.',
    feedbackQuestion:{question:'ما الذي يقل في الصحراء الحارة؟',options:[{text:'الماء',correct:true},{text:'الرمل',correct:false},{text:'الحرارة',correct:false},{text:'الحصى',correct:false}]},
  },
  {
    id:'u2q12', unit:'u2', lesson:'u2l2', page:82, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'نباتات الصحراء الحارة تتميز بـ:',
    paragraph:'نَباتاتُ الصَّحْراءِ الحارَّةِ تَكْتَسِبُ الماءَ مِنَ الأمْطارِ القَلِيلَةِ، وَلَها جُذُورٌ عَمِيقَةٌ تَمْتَدُّ فِي الأَرْض. (ص82)',
    image:'https://images.unsplash.com/photo-1459257831343-f3a7b7063c2e?w=600',
    options:[
      {text:'جذور عميقة تمتد في الأرض لتمتص الماء',correct:true},
      {text:'أوراق عريضة كبيرة',correct:false},
      {text:'لا تحتاج الماء أبداً',correct:false},
      {text:'تعيش في الظل',correct:false},
    ],
    explanation:'نباتات الصحراء لها جذور عميقة تمتص الماء من أعماق الأرض.',
    goldenRule:'نبات الصحراء = جذور عميقة + يمتص الماء من الأعماق.',
    feedbackQuestion:{question:'لماذا لنبات الصحراء جذور عميقة؟',options:[{text:'لتمتص الماء من الأعماق',correct:true},{text:'للجمال',correct:false},{text:'للطيران',correct:false},{text:'للنوم',correct:false}]},
  },
  {
    id:'u2q13', unit:'u2', lesson:'u2l2', page:83, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'حيوانات الصحراء الحارة تحصل على الماء من:',
    paragraph:'تَحْصُلُ حَيَوَاناتُ الصَّحْراءِ عَلى الماءِ مِنَ الغِذاءِ الَّذِي تَأْكُلُهُ، وَأَوْرَاقِ النَّباتات. (ص83)',
    image:'https://images.unsplash.com/photo-1543589030-ff4c0d2c3c5e?w=600',
    options:[
      {text:'الغذاء الذي تأكله وأوراق النباتات',correct:true},
      {text:'من الأنهار',correct:false},
      {text:'من الثلج',correct:false},
      {text:'من البحار',correct:false},
    ],
    explanation:'حيوانات الصحراء تحصل على الماء من غذائها ومن أوراق النباتات لأن الماء نادر.',
    goldenRule:'حيوان الصحراء يحصل على الماء من غذائه وأوراق النباتات.',
    feedbackQuestion:{question:'من أين تحصل حيوانات الصحراء على الماء؟',options:[{text:'من الغذاء وأوراق النباتات',correct:true},{text:'من الأنهار',correct:false},{text:'من الثلج',correct:false},{text:'من البحار',correct:false}]},
  },
  {
    id:'u2q14', unit:'u2', lesson:'u2l2', page:83, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'الجمل يعيش في الصحراء و:',
    paragraph:'الجَمَلُ يَعِيشُ فِي الصَّحْراء، وَيَخْزُنُ الدَّهْنَ فِي سَنامِهِ، فَيُعْطِيهِ الماءَ وَالطَّاقَة. (ص83)',
    image:'https://images.unsplash.com/photo-1543589030-ff4c0d2c3c5e?w=600',
    options:[
      {text:'يخزن الدهن في سنامه فيعطيه الماء والطاقة',correct:true},
      {text:'يأكل كثيراً',correct:false},
      {text:'لا يحتاج الماء',correct:false},
      {text:'ينام طويلاً',correct:false},
    ],
    explanation:'الجمل يخزن الدهن في سنامه فيعطيه الماء والطاقة في الصحراء.',
    goldenRule:'الجمل = سنام يخزن الدهن ← ماء + طاقة.',
    feedbackQuestion:{question:'أين يخزن الجمل الدهن؟',options:[{text:'في سنامه',correct:true},{text:'في أرجله',correct:false},{text:'في أذنيه',correct:false},{text:'في عينيه',correct:false}]},
  },
  {
    id:'u2q15', unit:'u2', lesson:'u2l2', page:84, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'الوشق حيوان له صفات تساعده على العيش في موطنه، ومنها:',
    paragraph:'الوَشْقُ لَهُ فِراءٌ سَمِيكَةٌ تَحْفَظُهُ مِنَ الحَرارَة، وَأُذُنانِ مُزَوَّدَتانِ بِخُصْلاتٍ مِنَ الشَّعْر. (ص84)',
    image:'https://images.unsplash.com/photo-1535591273668-8c1f1c0b8e8e?w=600',
    options:[
      {text:'فراء سميكة تحفظه من الحرارة وأذنان بخصلات شعر',correct:true},
      {text:'خياشيم',correct:false},
      {text:'أجنحة',correct:false},
      {text:'قشور',correct:false},
    ],
    explanation:'الوشق له فراء سميكة تحفظه من حرارة الصحراء وأذنان بخصلات شعر.',
    goldenRule:'الوشق = فراء سميكة + أذنان بخصلات شعر للحماية.',
    feedbackQuestion:{question:'ما الذي يحفظ الوشق من حرارة الصحراء؟',options:[{text:'الفراء السميكة',correct:true},{text:'الخياشيم',correct:false},{text:'الأجنحة',correct:false},{text:'القشور',correct:false}]},
  },
  {
    id:'u2q16', unit:'u2', lesson:'u2l2', page:84, type:'trueFalse',
    bloom:'understand', difficulty:'medium',
    question:'حيوانات الصحراء الحارة لها صفات تساعدها على تحمل قلة الماء والحرارة.',
    paragraph:'لِحَيَوَاناتِ الصَّحْراءِ صِفاتٌ تُساعِدُها عَلى تَحَمُّلِ قِلَّةِ الماءِ وَالحَرارَة. (ص83-84)',
    image:'https://images.unsplash.com/photo-1543589030-ff4c0d2c3c5e?w=600',
    correctAnswer:true,
    explanation:'حيوانات الصحراء لها صفات خاصة تساعدها على تحمل قلة الماء والحرارة العالية.',
    goldenRule:'التكيف = صفات تساعد الكائن على العيش في موطنه.',
    feedbackQuestion:{question:'ما معنى "التكيف"؟',options:[{text:'صفات تساعد الكائن على العيش في موطنه',correct:true},{text:'اللعب',correct:false},{text:'النوم',correct:false},{text:'الأكل',correct:false}]},
  },
  {
    id:'u2q17', unit:'u2', lesson:'u2l2', page:85, type:'multipleChoice',
    bloom:'apply', difficulty:'medium',
    question:'الجراد له أجنحة قوية تساعده على:',
    paragraph:'لِلْجَرادِ أَجْنِحَةٌ قَوِيَّةٌ تُساعِدُهُ عَلى الطَّيَرانِ مَسافاتٍ بَعِيدَةً لِلْبَحْثِ عَنِ الغِذاء. (ص85)',
    image:'https://images.unsplash.com/photo-1564773777901-7f1c0b2e4b5e?w=600',
    options:[
      {text:'الطيران مسافات بعيدة للبحث عن الغذاء',correct:true},
      {text:'السباحة',correct:false},
      {text:'الحفر',correct:false},
      {text:'النوم',correct:false},
    ],
    explanation:'الجراد له أجنحة قوية تطير به مسافات بعيدة للبحث عن الغذاء في الصحراء.',
    goldenRule:'الجراد = أجنحة قوية + يطير للبحث عن الغذاء.',
    feedbackQuestion:{question:'لماذا يطير الجراد مسافات بعيدة؟',options:[{text:'للبحث عن الغذاء',correct:true},{text:'للنوم',correct:false},{text:'للسباحة',correct:false},{text:'للعب',correct:false}]},
  },
  {
    id:'u2q18', unit:'u2', lesson:'u2l2', page:82, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف: صفات تساعد على العيش في الصحراء الحارة؟',
    paragraph:'صِفاتُ حَيَوَاناتِ الصَّحْراءِ: فِراءٌ سَمِيكَة، جُذُورٌ عَمِيقَة، أَجْنِحَةٌ لِلطَّيَران. (ص82-85)',
    categories:['صفات تكيف في الصحراء 🐪','ليست صفات تكيف ❌'],
    items:[
      {text:'جذور عميقة',correct_category:0},
      {text:'فراء سميكة',correct_category:0},
      {text:'خياشيم للسباحة',correct_category:1},
      {text:'أجنحة قوية للطيران',correct_category:0},
      {text:'زعانف',correct_category:1},
      {text:'سنام يخزن الدهن',correct_category:0},
    ],
    explanation:'صفات الصحراء: جذور عميقة، فراء سميكة، أجنحة قوية، سنام. الخياشيم والزعانف للماء.',
    goldenRule:'التكيف في الصحراء: تخزين ماء + فراء + جذور عميقة + طيران.',
  },
  {
    id:'u2q19', unit:'u2', lesson:'u2l2', page:85, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'لماذا تنجح حيوانات الصحراء في العيش رغم قلة الماء؟',
    paragraph:'تَحْصُلُ حَيَوَاناتُ الصَّحْراءِ عَلى الماءِ مِنَ الغِذاءِ وَأَوْرَاقِ النَّباتات. (ص83)',
    image:'https://images.unsplash.com/photo-1543589030-ff4c0d2c3c5e?w=600',
    options:[
      {text:'لأنها تتكيف وتحصل على الماء من الغذاء والنباتات',correct:true},
      {text:'لأنها لا تحتاج الماء',correct:false},
      {text:'لأنها تنتظر المطر',correct:false},
      {text:'لأنها تنام',correct:false},
    ],
    explanation:'حيوانات الصحراء تتكيف وتحصل على الماء من الغذاء وأوراق النباتات وتخزن الدهن.',
    goldenRule:'التكيف في الصحراء = حلول ذكية لقلة الماء والحرارة.',
    feedbackQuestion:{question:'كيف يحصل الجمل على الماء في الصحراء؟',options:[{text:'من الدهن المخزن في سنامه',correct:true},{text:'من الأنهار',correct:false},{text:'من الثلج',correct:false},{text:'من البحار',correct:false}]},
  },
  {
    id:'u2q20', unit:'u2', lesson:'u2l2', page:85, type:'trueFalse',
    bloom:'apply', difficulty:'medium',
    question:'نباتات الصحراء لها أوراق عريضة لتخزن ماءً كثيراً.',
    paragraph:'نَباتاتُ الصَّحْراءِ لَها أَوْرَاقٌ صَغِيرَةٌ أَوْ أَشْواكٌ لِتُقَلِّلَ فَقْدَ الماء. (ص82)',
    image:'https://images.unsplash.com/photo-1459257831343-f3a7b701f2c8?w=600',
    correctAnswer:false,
    explanation:'نباتات الصحراء لها أوراق صغيرة أو أشواك لتقلل فقد الماء، وليست عريضة.',
    goldenRule:'نبات الصحراء = أوراق صغيرة أو أشواك لتقليل فقد الماء.',
    feedbackQuestion:{question:'لماذا لنبات الصحراء أوراق صغيرة؟',options:[{text:'لتقليل فقد الماء',correct:true},{text:'للجمال',correct:false},{text:'للطيران',correct:false},{text:'للنوم',correct:false}]},
  },

  // ─── الدرس 3: الغابة المطيرة (ص90-96) ─────────────────────────────────
  {
    id:'u2q21', unit:'u2', lesson:'u2l3', page:90, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'الغابة المطيرة موطن يتميز بـ:',
    paragraph:'الغابَةُ المَطِيرَةُ مَكانٌ يَكْثُرُ فِيهِ الماءُ وَالأَمْطار، وَتَنْمُو فِيهِ الأَشْجارُ الكَبِيرَةُ وَالنَّباتاتُ الكَثِيفَة. (ص90)',
    image:'https://images.unsplash.com/photo-1448375240586-882707db888b?w=600',
    options:[
      {text:'كثرة الماء والأمطار والأشجار الكبيرة والنباتات الكثيفة',correct:true},
      {text:'قلة الماء',correct:false},
      {text:'الرمال والكثبان',correct:false},
      {text:'الجليد',correct:false},
    ],
    explanation:'الغابة المطيرة تتميز بكثرة الماء والأمطار والأشجار الكبيرة والنباتات الكثيفة.',
    goldenRule:'الغابة المطيرة = ماء كثير + أمطار + أشجار كبيرة + نباتات كثيفة.',
    feedbackQuestion:{question:'ما الذي يكثر في الغابة المطيرة؟',options:[{text:'الماء والأمطار والأشجار',correct:true},{text:'الرمال',correct:false},{text:'الجليد',correct:false},{text:'الصخور',correct:false}]},
  },
  {
    id:'u2q22', unit:'u2', lesson:'u2l3', page:90, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'الأشجار في الغابة المطيرة:',
    paragraph:'تَنْمُو فِيها الأَشْجارُ الكَبِيرَةُ، وَالنَّباتاتُ الكَثِيفَة، وَتَتَسَلَّقُ عَلَيْها نَباتاتٌ أُخْرَى. (ص90)',
    image:'https://images.unsplash.com/photo-1448375240586-882707db888b?w=600',
    options:[
      {text:'كبيرة وتتسلق عليها نباتات أخرى',correct:true},
      {text:'صغيرة جداً',correct:false},
      {text:'لا أوراق لها',correct:false},
      {text:'ميتة',correct:false},
    ],
    explanation:'أشجار الغابة المطيرة كبيرة وتتسلق عليها نباتات أخرى كثيفة.',
    goldenRule:'أشجار الغابة المطيرة = كبيرة + نباتات متسلقة عليها.',
    feedbackQuestion:{question:'ماذا تتسلق على أشجار الغابة المطيرة؟',options:[{text:'نباتات أخرى',correct:true},{text:'الرمال',correct:false},{text:'الجليد',correct:false},{text:'الحشرات فقط',correct:false}]},
  },
  {
    id:'u2q23', unit:'u2', lesson:'u2l3', page:91, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'حيوانات الغابة المطيرة كثيرة ومنها:',
    paragraph:'فِي الغابَةِ المَطِيرَةِ أَنْواعٌ كَثِيرَةٌ مِنَ الحَيَوَانات، مِنْها: القِرْد، الطُّوحُل، الطُّيُور المُلَوِّنَة. (ص91)',
    image:'https://images.unsplash.com/photo-1530595467537-0b2c3d5e3c2e?w=600',
    options:[
      {text:'القرد والطيور الملونة',correct:true},
      {text:'الدب القطبي',correct:false},
      {text:'الجمل',correct:false},
      {text:'السمكة',correct:false},
    ],
    explanation:'حيوانات الغابة المطيرة كثيرة ومتنوعة: القرد والطيور الملونة والطوحل.',
    goldenRule:'الغابة المطيرة = تنوع كبير من الحيوانات والنباتات.',
    feedbackQuestion:{question:'أي حيوان يعيش في الغابة المطيرة؟',options:[{text:'القرد',correct:true},{text:'الدب القطبي',correct:false},{text:'الجمل',correct:false},{text:'السمكة',correct:false}]},
  },
  {
    id:'u2q24', unit:'u2', lesson:'u2l3', page:92, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'بعض حيوانات الغابة المطيرة تأكل النباتات، وبعضها يأكل:',
    paragraph:'بَعْضُ حَيَوَاناتِ الغابَةِ يَأْكُلُ النَّباتات، وَبَعْضُها يَأْكُلُ اللُّحُوم. (ص92)',
    image:'https://images.unsplash.com/photo-1535591273668-8c1f1c0b8e8e?w=600',
    options:[
      {text:'اللحوم (حيوانات أخرى)',correct:true},
      {text:'الرمل',correct:false},
      {text:'الجليد',correct:false},
      {text:'الصخور',correct:false},
    ],
    explanation:'في الغابة المطيرة حيوانات تأكل النباتات وحيوانات تأكل اللحوم (حيوانات أخرى).',
    goldenRule:'سلسلة الغذاء في الغابة: نباتات ← حيوانات عاشبة ← حيوانات لاحمة.',
    feedbackQuestion:{question:'ماذا يأكل الحيوان اللاحم؟',options:[{text:'اللحوم (حيوانات أخرى)',correct:true},{text:'النباتات فقط',correct:false},{text:'الرمل',correct:false},{text:'الجليد',correct:false}]},
  },
  {
    id:'u2q25', unit:'u2', lesson:'u2l3', page:92, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'الغابة المطيرة موطن دافئ كثير الماء.',
    paragraph:'الغابَةُ المَطِيرَةُ مَكانٌ يَكْثُرُ فِيهِ الماءُ وَالأَمْطار. (ص90)',
    image:'https://images.unsplash.com/photo-1448375240586-882707db888b?w=600',
    correctAnswer:true,
    explanation:'الغابة المطيرة موطن دافئ كثير الماء والأمطار والنباتات.',
    goldenRule:'الغابة المطيرة = دافئة + كثيرة الماء + كثيفة النباتات.',
    feedbackQuestion:{question:'هل الغابة المطيرة جافة؟',options:[{text:'لا، كثيرة الماء والأمطار',correct:true},{text:'نعم جافة',correct:false},{text:'بعض الأحيان',correct:false},{text:'لا أعرف',correct:false}]},
  },
  {
    id:'u2q26', unit:'u2', lesson:'u2l3', page:93, type:'multipleChoice',
    bloom:'apply', difficulty:'medium',
    question:'الطيور الملونة في الغابة المطيرة تعيش على:',
    paragraph:'تَعِيشُ الطُّيُورُ المُلَوِّنَةُ عَلى أَشْجارِ الغابَةِ المَطِيرَة، وَتَبْنِي أَعْشاشاً فِيها. (ص93)',
    image:'https://images.unsplash.com/photo-1444464669806-84f9a4e4e3b7?w=600',
    options:[
      {text:'أشجار الغابة وتبني أعشاشاً فيها',correct:true},
      {text:'في الصحراء',correct:false},
      {text:'في الكهوف الجليدية',correct:false},
      {text:'في البحار',correct:false},
    ],
    explanation:'الطيور الملونة تعيش على أشجار الغابة المطيرة وتبني أعشاشها فيها.',
    goldenRule:'طيور الغابة المطيرة = أعشاش على الأشجار + ألوان زاهية.',
    feedbackQuestion:{question:'أين تبني الطيور الملونة أعشاشها؟',options:[{text:'على أشجار الغابة',correct:true},{text:'في الصحراء',correct:false},{text:'في الجليد',correct:false},{text:'في الماء',correct:false}]},
  },
  {
    id:'u2q27', unit:'u2', lesson:'u2l3', page:93, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف الحيوانات: تعيش في الغابة المطيرة أم الصحراء؟',
    paragraph:'الغابَةُ المَطِيرَة: قِرْد، طُيُور مُلَوِّنَة. الصَّحْراء: جَمَل، وَشْق، جَراد. (ص83-93)',
    categories:['تعيش في الغابة المطيرة 🌴','تعيش في الصحراء 🐪'],
    items:[
      {text:'القرد',correct_category:0},
      {text:'الجمل',correct_category:1},
      {text:'الطيور الملونة',correct_category:0},
      {text:'الوشق',correct_category:1},
      {text:'الجراد',correct_category:1},
      {text:'الطوحل',correct_category:0},
    ],
    explanation:'الغابة: القرد والطيور الملونة والطوحل. الصحراء: الجمل والوشق والجراد.',
    goldenRule:'كل حيوان يعيش في الموطن المناسب لصفاته.',
  },
  {
    id:'u2q28', unit:'u2', lesson:'u2l3', page:94, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'لماذا تعيش القردة على أشجار الغابة المطيرة؟',
    paragraph:'القِرْدَةُ تَتَسَلَّقُ أَشْجارَ الغابَةِ المَطِيرَة، وَتَجِدُ فِيها غِذاءَها وَمَأْواها. (ص94)',
    image:'https://images.unsplash.com/photo-1530595467537-0b2c3d5e3c2e?w=600',
    options:[
      {text:'لأنها تجد غذاءها ومأواها على الأشجار',correct:true},
      {text:'لأنها تخاف من الماء',correct:false},
      {text:'لأنها لا تحب الأرض',correct:false},
      {text:'لأنها تسبح',correct:false},
    ],
    explanation:'القردة تتسلق الأشجار لأنها تجد غذاءها ومأواها عليها في الغابة المطيرة.',
    goldenRule:'القرد = يتسلق الأشجار + يجد غذاءه ومأواه عليها.',
    feedbackQuestion:{question:'ماذا يجد القرد على أشجار الغابة؟',options:[{text:'الغذاء والمأوى',correct:true},{text:'الرمال',correct:false},{text:'الجليد',correct:false},{text:'الصخور',correct:false}]},
  },
  {
    id:'u2q29', unit:'u2', lesson:'u2l3', page:94, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'النباتات في الغابة المطيرة:',
    paragraph:'نَباتاتُ الغابَةِ المَطِيرَةِ كَثِيفَةٌ وَمُتَنَوِّعَة، وَبَعْضُها يَتَسَلَّقُ الأَشْجار. (ص90)',
    image:'https://images.unsplash.com/photo-1448375240586-882707db888b?w=600',
    options:[
      {text:'كثيفة ومتنوعة وبعضها يتسلق الأشجار',correct:true},
      {text:'قليلة جداً',correct:false},
      {text:'ميتة',correct:false},
      {text:'صغيرة فقط',correct:false},
    ],
    explanation:'نباتات الغابة المطيرة كثيفة ومتنوعة وبعضها يتسلق الأشجار الكبيرة.',
    goldenRule:'نباتات الغابة المطيرة = كثيفة + متنوعة + متسلقة.',
    feedbackQuestion:{question:'كيف نباتات الغابة المطيرة؟',options:[{text:'كثيفة ومتنوعة',correct:true},{text:'قليلة',correct:false},{text:'ميتة',correct:false},{text:'صغيرة',correct:false}]},
  },
  {
    id:'u2q30', unit:'u2', lesson:'u2l3', page:95, type:'matching',
    bloom:'understand', difficulty:'medium',
    question:'صِل كل موطن بصفته:',
    paragraph:'الصَّحْراءُ الحارَّة: قَلِيلَةُ الماء. الغابَةُ المَطِيرَة: كَثِيرَةُ الماءِ وَالأَشْجار. (ص82-90)',
    pairs:[
      {left:'الصحراء الحارة',right:'قلة الماء والرمال'},
      {left:'الغابة المطيرة',right:'كثرة الماء والأشجار'},
      {left:'المنطقة القطبية',right:'الجليد والبرد'},
      {left:'البحر',right:'الماء والأسماك'},
    ],
    explanation:'كل موطن له صفات تناسب الكائنات التي تعيش فيه.',
    goldenRule:'المواطن تختلف: صحراء حارة + غابة مطيرة + منطقة قطبية + بحر.',
  },

  // ─── الدرس 4: المنطقة القطبية (ص98-104) ──────────────────────────────
  {
    id:'u2q31', unit:'u2', lesson:'u2l4', page:98, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'المنطقة القطبية موطن يتميز بـ:',
    paragraph:'المِنْطَقَةُ القُطْبِيَّةُ مَكانٌ بارِدٌ جِدّاً، وَيَكْثُرُ فِيهِ الجَلِيدُ وَالثَّلْج، وَقَلِيلٌ مِنَ النَّباتات. (ص98)',
    image:'https://images.unsplash.com/photo-1418985991508-e47386d96a71?w=600',
    options:[
      {text:'البرودة الشديدة والجليد والثلج وقلة النباتات',correct:true},
      {text:'الحرارة العالية',correct:false},
      {text:'كثرة الأمطار',correct:false},
      {text:'الغابات الكثيفة',correct:false},
    ],
    explanation:'المنطقة القطبية باردة جداً وتكثر فيها الجليد والثلج وقليلة النباتات.',
    goldenRule:'المنطقة القطبية = برد شديد + جليد + ثلج + قلة نباتات.',
    feedbackQuestion:{question:'ما الذي يكثر في المنطقة القطبية؟',options:[{text:'الجليد والثلج',correct:true},{text:'الرمال',correct:false},{text:'الأمطار',correct:false},{text:'الأشجار',correct:false}]},
  },
  {
    id:'u2q32', unit:'u2', lesson:'u2l4', page:99, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'الدب القطبي يعيش في المنطقة القطبية وله:',
    paragraph:'الدُّبُّ القُطْبِيُّ يَعِيشُ فِي المِنْطَقَةِ القُطْبِيَّة، وَلَهُ فِراءٌ سَمِيكَةٌ تُبْقِيهِ دافِئاً. (ص99)',
    image:'https://images.unsplash.com/photo-1589656967335-8d8b3c8c1c2e?w=600',
    options:[
      {text:'فراء سميكة تبقيه دافئاً',correct:true},
      {text:'خياشيم',correct:false},
      {text:'أجنحة',correct:false},
      {text:'قشور',correct:false},
    ],
    explanation:'الدب القطبي له فراء سميكة تبقيه دافئاً في البرد الشديد.',
    goldenRule:'الدب القطبي = فراء سميكة + يبقى دافئاً في الجليد.',
    feedbackQuestion:{question:'ما الذي يبقي الدب القطبي دافئاً؟',options:[{text:'الفراء السميكة',correct:true},{text:'الخياشيم',correct:false},{text:'الأجنحة',correct:false},{text:'القشور',correct:false}]},
  },
  {
    id:'u2q33', unit:'u2', lesson:'u2l4', page:99, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'الدب القطبي يسبح في الماء البارد وله:',
    paragraph:'يَسْبَحُ الدُّبُّ القُطْبِيُّ فِي الماءِ البارِد، وَيَصِيدُ الأَسْماك. (ص99)',
    image:'https://images.unsplash.com/photo-1589656967335-8d8b3c8c1c2e?w=600',
    options:[
      {text:'يصيد الأسماك في الماء البارد',correct:true},
      {text:'يأكل النباتات فقط',correct:false},
      {text:'ينام طوال الصيف',correct:false},
      {text:'يختبئ في الكهوف',correct:false},
    ],
    explanation:'الدب القطبي يسبح ويصيد الأسماك في الماء البارد.',
    goldenRule:'الدب القطبي = يسبح + يصيد الأسماك + فراء سميكة.',
    feedbackQuestion:{question:'ماذا يأكل الدب القطبي؟',options:[{text:'الأسماك',correct:true},{text:'الأعشاب',correct:false},{text:'الصخور',correct:false},{text:'الجليد',correct:false}]},
  },
  {
    id:'u2q34', unit:'u2', lesson:'u2l4', page:100, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'البطريق طائر يعيش في المنطقة القطبية و:',
    paragraph:'البِطْرِيقُ طائِرٌ يَعِيشُ فِي المِنْطَقَةِ القُطْبِيَّة، وَلا يَطِير، وَلَكِنَّهُ يَسْبَحُ فِي الماء. (ص100)',
    image:'https://images.unsplash.com/photo-1564773777901-7f1c0b2e4b5e?w=600',
    options:[
      {text:'لا يطير لكنه يسبح في الماء',correct:true},
      {text:'يطير لمسافات بعيدة',correct:false},
      {text:'يعيش في الصحراء',correct:false},
      {text:'يبيض في الأعشاش العالية',correct:false},
    ],
    explanation:'البطريق طائر لكنه لا يطير، يسبح في الماء البارد ويعيش في المنطقة القطبية.',
    goldenRule:'البطريق = طائر لا يطير + يسبح + يعيش في الجليد.',
    feedbackQuestion:{question:'هل يستطيع البطريق الطيران؟',options:[{text:'لا، يسبح في الماء',correct:true},{text:'نعم يطير',correct:false},{text:'أحياناً',correct:false},{text:'لا أعرف',correct:false}]},
  },
  {
    id:'u2q35', unit:'u2', lesson:'u2l4', page:100, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'للبطريق أجنحة تساعده على:',
    paragraph:'لِلْبِطْرِيقِ أَجْنِحَةٌ تُساعِدُهُ عَلى السِّباحَةِ فِي الماء. (ص100)',
    image:'https://images.unsplash.com/photo-1564773777901-7f1c0b2e4b5e?w=600',
    options:[
      {text:'السباحة في الماء',correct:true},
      {text:'الطيران في الجو',correct:false},
      {text:'الحفر',correct:false},
      {text:'الجري',correct:false},
    ],
    explanation:'أجنحة البطريق تساعده على السباحة وليس الطيران.',
    goldenRule:'أجنحة البطريق = للسباحة (ليس للطيران).',
    feedbackQuestion:{question:'بماذا يسبح البطريق؟',options:[{text:'بأجنحته',correct:true},{text:'بأرجله فقط',correct:false},{text:'بذيله',correct:false},{text:'لا يسبح',correct:false}]},
  },
  {
    id:'u2q36', unit:'u2', lesson:'u2l4', page:101, type:'multipleChoice',
    bloom:'apply', difficulty:'medium',
    question:'فرو البطريق ودهنه تحت الجلد:',
    paragraph:'لِلْبِطْرِيقِ فِراءٌ سَمِيكَةٌ وَدُهْنٌ تَحْتَ الجِلْدِ تَحْفَظُهُ مِنَ البَرْد. (ص101)',
    image:'https://images.unsplash.com/photo-1564773777901-7f1c0b2e4b5e?w=600',
    options:[
      {text:'تحفظه من البرد',correct:true},
      {text:'تزيده حرارة',correct:false},
      {text:'تجعله يطير',correct:false},
      {text:'لا فائدة لها',correct:false},
    ],
    explanation:'فراء البطريق ودهنه تحت الجلد يحفظانه من برد المنطقة القطبية.',
    goldenRule:'البطريق = فراء + دهن تحت الجلد + حماية من البرد.',
    feedbackQuestion:{question:'ما فائدة دهن البطريق تحت الجلد؟',options:[{text:'حمايته من البرد',correct:true},{text:'زيادة حرارته',correct:false},{text:'الطيران',correct:false},{text:'الجري',correct:false}]},
  },
  {
    id:'u2q37', unit:'u2', lesson:'u2l4', page:102, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'المنطقة القطبية موطن بارد لا تنمو فيه النباتات كثيراً.',
    paragraph:'المِنْطَقَةُ القُطْبِيَّةُ مَكانٌ بارِدٌ جِدّاً، وَقَلِيلٌ مِنَ النَّباتات. (ص98)',
    image:'https://images.unsplash.com/photo-1418985991508-e47386d96a71?w=600',
    correctAnswer:true,
    explanation:'المنطقة القطبية باردة جداً وقليلة النباتات بسبب الجليد والثلج.',
    goldenRule:'المنطقة القطبية = برد + جليد + قلة نباتات.',
    feedbackQuestion:{question:'هل تنمو النباتات بكثرة في المنطقة القطبية؟',options:[{text:'لا، قليلة',correct:true},{text:'نعم بكثرة',correct:false},{text:'بعض الأحيان',correct:false},{text:'لا أعرف',correct:false}]},
  },
  {
    id:'u2q38', unit:'u2', lesson:'u2l4', page:102, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف: صفات تساعد على العيش في المنطقة القطبية؟',
    paragraph:'صِفاتُ حَيَوَاناتِ المِنْطَقَةِ القُطْبِيَّة: فِراءٌ سَمِيكَة، دُهْنٌ تَحْتَ الجِلْد، قُدْرَةٌ عَلى السِّباحَة. (ص99-101)',
    categories:['صفات تكيف في المنطقة القطبية 🐻‍❄️','ليست صفات تكيف ❌'],
    items:[
      {text:'فراء سميكة',correct_category:0},
      {text:'دهن تحت الجلد',correct_category:0},
      {text:'جذور عميقة',correct_category:1},
      {text:'قدرة على السباحة في الماء البارد',correct_category:0},
      {text:'أجنحة للطيران مسافات بعيدة',correct_category:1},
      {text:'أوراق صغيرة',correct_category:1},
    ],
    explanation:'صفات المنطقة القطبية: فراء سميكة + دهن + سباحة في الماء البارد. الجذور والأوراق الصغيرة للصحراء.',
    goldenRule:'التكيف في المنطقة القطبية = فراء + دهن + سباحة في البرد.',
  },
  {
    id:'u2q39', unit:'u2', lesson:'u2l4', page:103, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'لماذا لا يعيش الجمل في المنطقة القطبية؟',
    paragraph:'الجَمَلُ يَعِيشُ فِي الصَّحْراء، وَالدُّبُّ القُطْبِيُّ يَعِيشُ فِي المِنْطَقَةِ القُطْبِيَّة. (ص83-99)',
    image:'https://images.unsplash.com/photo-1543589030-ff4c0d2c3c5e?w=600',
    options:[
      {text:'لأن صفاته تناسب الصحراء ولا تناسب البرد الشديد',correct:true},
      {text:'لأنه يخاف من الثلج',correct:false},
      {text:'لأنه كبير الحجم',correct:false},
      {text:'لأنه لا يحب الماء',correct:false},
    ],
    explanation:'الجمل متكيف للحرارة والصحراء، والدب القطبي متكيف للبرد — كل في موطنه.',
    goldenRule:'كل حيوان يعيش في الموطن الذي يناسب صفاته.',
    feedbackQuestion:{question:'أي حيوان يناسب المنطقة القطبية؟',options:[{text:'الدب القطبي',correct:true},{text:'الجمل',correct:false},{text:'الجراد',correct:false},{text:'القرد',correct:false}]},
  },
  {
    id:'u2q40', unit:'u2', lesson:'u2l4', page:103, type:'matching',
    bloom:'understand', difficulty:'medium',
    question:'صِل كل حيوان بموطنه:',
    paragraph:'الجَمَلُ فِي الصَّحْراء، الدُّبُّ القُطْبِيُّ فِي المِنْطَقَةِ القُطْبِيَّة، القِرْدُ فِي الغابَةِ المَطِيرَة. (ص83-99)',
    pairs:[
      {left:'الجمل',right:'الصحراء الحارة'},
      {left:'الدب القطبي',right:'المنطقة القطبية'},
      {left:'القرد',right:'الغابة المطيرة'},
      {left:'السمكة',right:'البحر'},
    ],
    explanation:'كل حيوان يعيش في موطن يناسب صفاته واحتياجاته.',
    goldenRule:'الموطن المناسب = بقاء الحيوان وحصوله على حاجاته.',
  },

  // ─── الدرس 5: تكيف الكائنات الحية في مواطنها (ص106-112) ───────────────
  {
    id:'u2q41', unit:'u2', lesson:'u2l5', page:106, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'التكيف يعني:',
    paragraph:'التَّكَيُّفُ صِفاتٌ فِي الكَائِنِ الحَيِّ تُساعِدُهُ عَلى العَيْشِ فِي مَوْطِنِه. (ص106)',
    image:'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=600',
    options:[
      {text:'صفات في الكائن الحي تساعده على العيش في موطنه',correct:true},
      {text:'اللعب',correct:false},
      {text:'النوم',correct:false},
      {text:'الأكل',correct:false},
    ],
    explanation:'التكيف صفات في الكائن الحي تساعده على العيش في موطنه والبقاء فيه.',
    goldenRule:'التكيف = صفات تساعد الكائن على البقاء في موطنه.',
    feedbackQuestion:{question:'ما معنى التكيف؟',options:[{text:'صفات تساعد الكائن على العيش في موطنه',correct:true},{text:'النوم',correct:false},{text:'اللعب',correct:false},{text:'الأكل',correct:false}]},
  },
  {
    id:'u2q42', unit:'u2', lesson:'u2l5', page:106, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'كل كائن حي له صفات تساعده على:',
    paragraph:'لِكُلِّ كَائِنٍ حَيٍّ صِفاتٌ تُساعِدُهُ عَلى البَقاءِ فِي مَوْطِنِهِ وَتَحَمُّلِ ظُرُوفِه. (ص106)',
    image:'https://images.unsplash.com/photo-1502786129293-79981df4dc2d?w=600',
    options:[
      {text:'البقاء في موطنه وتحمل ظروفه',correct:true},
      {text:'الانتقال لموطن آخر',correct:false},
      {text:'النوم',correct:false},
      {text:'اللعب',correct:false},
    ],
    explanation:'كل كائن حي له صفات تساعده على البقاء في موطنه وتحمل ظروفه.',
    goldenRule:'البقاء في الموطن = تكيف + تحمل ظروف + حصول على الحاجات.',
    feedbackQuestion:{question:'ماذا تساعد التكيف الكائن عليه؟',options:[{text:'البقاء في موطنه وتحمل ظروفه',correct:true},{text:'الانتقال',correct:false},{text:'النوم',correct:false},{text:'اللعب',correct:false}]},
  },
  {
    id:'u2q43', unit:'u2', lesson:'u2l5', page:107, type:'multipleChoice',
    bloom:'apply', difficulty:'medium',
    question:'الجمل متكيف للصحراء لأن:',
    paragraph:'الجَمَلُ مُتَكَيِّفٌ لِلصَّحْراء: يَخْزُنُ الدهن فِي سَنامِهِ، وَلَهُ خَفّ يَحْمِيهِ مِنْ حَرارَةِ الرَّمْل. (ص107)',
    image:'https://images.unsplash.com/photo-1543589030-ff4c0d2c3c5e?w=600',
    options:[
      {text:'يخزن الدهن في سنامه وله خف يحميه من حرارة الرمل',correct:true},
      {text:'له خياشيم',correct:false},
      {text:'يطير',correct:false},
      {text:'له فراء سميكة',correct:false},
    ],
    explanation:'الجمل متكيف للصحراء: يخزن الدهن في سنامه وخفه يحميه من حرارة الرمل.',
    goldenRule:'الجمل = سنام (دهن) + خف (حماية من حرارة الرمل).',
    feedbackQuestion:{question:'ما الذي يحمي الجمل من حرارة الرمل؟',options:[{text:'الخف',correct:true},{text:'الأجنحة',correct:false},{text:'الخياشيم',correct:false},{text:'الفراء',correct:false}]},
  },
  {
    id:'u2q44', unit:'u2', lesson:'u2l5', page:107, type:'multipleChoice',
    bloom:'apply', difficulty:'medium',
    question:'الدب القطبي متكيف للمنطقة القطبية لأن:',
    paragraph:'الدُّبُّ القُطْبِيُّ مُتَكَيِّفٌ لِلْبَرْد: لَهُ فِراءٌ سَمِيكَةٌ وَدُهْنٌ تَحْتَ الجِلْد. (ص107)',
    image:'https://images.unsplash.com/photo-1589656967335-8d8b3c8c1c2e?w=600',
    options:[
      {text:'له فراء سميكة ودهن تحت الجلد',correct:true},
      {text:'له خف',correct:false},
      {text:'يخزن الماء',correct:false},
      {text:'له جذور عميقة',correct:false},
    ],
    explanation:'الدب القطبي متكيف للبرد: فراء سميكة + دهن تحت الجلد يحفظانه دافئاً.',
    goldenRule:'الدب القطبي = فراء سميكة + دهن + حماية من البرد.',
    feedbackQuestion:{question:'ما الذي يحفظ الدب القطبي دافئاً؟',options:[{text:'الفراء السميكة والدهن',correct:true},{text:'الخف',correct:false},{text:'الجذور',correct:false},{text:'الأجنحة',correct:false}]},
  },
  {
    id:'u2q45', unit:'u2', lesson:'u2l5', page:108, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'السمكة متكيفة للعيش في الماء لأن:',
    paragraph:'السَّمَكَةُ مُتَكَيِّفَةٌ لِلْماء: لَها خَياشِمُ تَتَنَفَّسُ بِها، وَزَعانِفُ تَسْبَحُ بِها. (ص108)',
    image:'https://images.unsplash.com/photo-1535268647677-06f0c8412da9?w=600',
    options:[
      {text:'لها خياشيم تتنفس بها وزعانف تسبح بها',correct:true},
      {text:'لها فراء',correct:false},
      {text:'لها أجنحة',correct:false},
      {text:'لها خف',correct:false},
    ],
    explanation:'السمكة متكيفة للماء: خياشيم للتنفس + زعانف للسباحة.',
    goldenRule:'السمكة = خياشيم (تنفس في الماء) + زعانف (سباحة).',
    feedbackQuestion:{question:'بماذا تتنفس السمكة في الماء؟',options:[{text:'الخياشيم',correct:true},{text:'الرئتين',correct:false},{text:'الأنف',correct:false},{text:'الجلد',correct:false}]},
  },
  {
    id:'u2q46', unit:'u2', lesson:'u2l5', page:108, type:'multipleChoice',
    bloom:'apply', difficulty:'medium',
    question:'الطائر متكيف للطيران لأن:',
    paragraph:'الطائِرُ مُتَكَيِّفٌ لِلطَّيَران: لَهُ أَجْنِحَةٌ وَرِيشٌ خَفِيفٌ وَجِسْمٌ مُجَوَّفٌ خَفِيف. (ص108)',
    image:'https://images.unsplash.com/photo-1444464669806-84f9a4e4e3b7?w=600',
    options:[
      {text:'له أجنحة وريش خفيف وجسم مجوف خفيف',correct:true},
      {text:'له خياشيم',correct:false},
      {text:'له خف',correct:false},
      {text:'له فراء سميكة',correct:false},
    ],
    explanation:'الطائر متكيف للطيران: أجنحة + ريش خفيف + جسم مجوف خفيف.',
    goldenRule:'الطائر = أجنحة + ريش خفيف + جسم خفيف مجوف.',
    feedbackQuestion:{question:'ما الذي يجعل الطائر قادراً على الطيران؟',options:[{text:'الأجنحة والريش الخفيف',correct:true},{text:'الخياشيم',correct:false},{text:'الخف',correct:false},{text:'القشور',correct:false}]},
  },
  {
    id:'u2q47', unit:'u2', lesson:'u2l5', page:109, type:'classify',
    bloom:'analyze', difficulty:'hard',
    question:'صنّف صفات التكيف حسب الموطن:',
    paragraph:'الصَّحْراء: سَنام، خَفّ، فِراء. الماء: خَياشِم، زَعانِف. الجَو: أَجْنِحَة، رِيش. البَرْد: فِراء سَمِيكَة، دُهْن. (ص106-109)',
    categories:['تكيف للصحراء 🐪','تكيف للماء 🐟','تكيف للجو 🦢','تكيف للبرد 🐻‍❄️'],
    items:[
      {text:'السنام',correct_category:0},
      {text:'الخياشيم',correct_category:1},
      {text:'الأجنحة',correct_category:2},
      {text:'الفراء السميكة',correct_category:3},
      {text:'الزعانف',correct_category:1},
      {text:'الدهن تحت الجلد',correct_category:3},
      {text:'الخف',correct_category:0},
      {text:'الريش الخفيف',correct_category:2},
    ],
    explanation:'الصحراء: سنام، خف. الماء: خياشيم، زعانف. الجو: أجنحة، ريش. البرد: فراء، دهن.',
    goldenRule:'كل موطن له صفات تكيف خاصة تناسبه.',
  },
  {
    id:'u2q48', unit:'u2', lesson:'u2l5', page:110, type:'trueFalse',
    bloom:'evaluate', difficulty:'hard',
    question:'لو نُقل الدب القطبي إلى الصحراء فإنه سيعيش بنجاح لأنه قوي.',
    paragraph:'لِكُلِّ كَائِنٍ حَيٍّ صِفاتٌ تُساعِدُهُ عَلى البَقاءِ فِي مَوْطِنِهِ وَتَحَمُّلِ ظُرُوفِه. (ص106)',
    image:'https://images.unsplash.com/photo-1418985991508-e47386d96a71?w=600',
    correctAnswer:false,
    explanation:'الدب القطبي متكيف للبرد لا للحرارة، فلو نُقل للصحراء فإنه يموت لعدم وجود صفات التكيف المناسبة.',
    goldenRule:'كل كائن يعيش في موطنه — التكيف خاص بكل موطن.',
    feedbackQuestion:{question:'ماذا يحدث للدب القطبي في الصحراء؟',options:[{text:'يموت لعدم وجود تكيف للحرارة',correct:true},{text:'يعيش بنجاح',correct:false},{text:'يتكيف فوراً',correct:false},{text:'يطير',correct:false}]},
  },
  {
    id:'u2q49', unit:'u2', lesson:'u2l5', page:110, type:'multipleChoice',
    bloom:'create', difficulty:'hard',
    question:'إذا أردت أن أربي سمكة فأي موطن أختار؟',
    paragraph:'السَّمَكَةُ مُتَكَيِّفَةٌ لِلْماء: لَها خَياشِمُ تَتَنَفَّسُ بِها. (ص108)',
    image:'https://images.unsplash.com/photo-1535268647677-06f0c8412da9?w=600',
    options:[
      {text:'حوض فيه ماء',correct:true},
      {text:'قفص فيه رمل',correct:false},
      {text:'صندوق فيه ثلج',correct:false},
      {text:'قفص فيه هواء',correct:false},
    ],
    explanation:'السمكة تحتاج الماء لتعيش وتتنس بالخياشيم، لذلك أضعها في حوض ماء.',
    goldenRule:'اختر الموطن المناسب لصفات الكائن الحي.',
    feedbackQuestion:{question:'أين تعيش السمكة؟',options:[{text:'في الماء',correct:true},{text:'في الرمل',correct:false},{text:'في الثلج',correct:false},{text:'في الهواء',correct:false}]},
  },
  {
    id:'u2q50', unit:'u2', lesson:'u2l5', page:112, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'ماذا نتعلم من دراسة تكيف الكائنات في مواطنها؟',
    paragraph:'دِراسَةُ التَّكَيُّفِ تُعَلِّمُنا كَيْفَ يَحْفَظُ اللهُ الكَائِناتِ الحَيَّةَ بِصِفاتٍ تُناسِبُ مَواطِنَها. (ص112)',
    image:'https://images.unsplash.com/photo-1502786129293-79981df4dc2d?w=600',
    options:[
      {text:'أن الله خلق كل كائن بصفات تناسب موطنه',correct:true},
      {text:'أن الحيوانات تتحرك بلا هدف',correct:false},
      {text:'أن كل الكائنات تتشابه',correct:false},
      {text:'أن الموطن غير مهم',correct:false},
    ],
    explanation:'دراسة التكيف تعلمنا إبداع الله في خلق كل كائن بصفات تناسب موطنه.',
    goldenRule:'الله خلق كل كائن بصفات تناسب موطنه — هذا إبداع الخالق.',
    feedbackQuestion:{question:'ما الذي نتعلمه من التكيف؟',options:[{text:'إبداع الله في خلق الكائنات',correct:true},{text:'لا شيء',correct:false},{text:'أن الكائنات عشوائية',correct:false},{text:'أن الموطن غير مهم',correct:false}]},
  },
];

export default U2_QUESTIONS;