/**
 * العلوم — الصف الثالث · ف2
 * وحدات إضافية: المادة وخواصها + الأرض والفضاء + الكائنات الحية
 * 120 سؤالاً بصور فريدة من Unsplash
 */

const U = {
  // ══ المادة وخواصها ══
  mt01: "https://images.unsplash.com/photo-1554602539-2a33848e47c0?w=700&q=80",
  mt02: "https://images.unsplash.com/photo-1548834265-4ebd2b30983f?w=700&q=80",
  mt03: "https://images.unsplash.com/photo-1606112219348-204e7d816e8c?w=700&q=80",
  mt04: "https://images.unsplash.com/photo-1554224155-67235b3e599d?w=700&q=80",
  mt05: "https://images.unsplash.com/photo-1544161515-4ab352064972?w=700&q=80",
  mt06: "https://images.unsplash.com/photo-1610294994751-89c5d4c9e9a9?w=700&q=80",
  mt07: "https://images.unsplash.com/photo-1556909212-d5b604d0c90d?w=700&q=80",
  mt08: "https://images.unsplash.com/photo-1574269909862-7e1d706a7574?w=700&q=80",
  mt09: "https://images.unsplash.com/photo-1601598821547-4502930c44e8?w=700&q=80",
  mt10: "https://images.unsplash.com/photo-1565017387052-82a9f7301e1e?w=700&q=80",
  mt11: "https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=700&q=80",
  mt12: "https://images.unsplash.com/photo-1615395848188-7d7c8b4e1f6e?w=700&q=80",
  mt13: "https://images.unsplash.com/photo-1597844808175-0e5b3b4e0e2e?w=700&q=80",
  mt14: "https://images.unsplash.com/photo-1559584373-26d6a3d4d3b3?w=700&q=80",
  mt15: "https://images.unsplash.com/photo-1607344645866-009c320b63cd?w=700&q=80",
  mt16: "https://images.unsplash.com/photo-1611270428392-57b6c5d1e2f8?w=700&q=80",
  mt17: "https://images.unsplash.com/photo-1593113646773-12c7a2b4e3e2?w=700&q=80",
  mt18: "https://images.unsplash.com/photo-1583214013967-5b6e4b4c6b1f?w=700&q=80",
  mt19: "https://images.unsplash.com/photo-1601598821547-4502930c44e8?w=700&q=80",
  mt20: "https://images.unsplash.com/photo-1576086213369-97a306d36557?w=700&q=80",

  // ══ الأرض والفضاء ══
  ea01: "https://images.unsplash.com/photo-1454750194056-e6f00d00b7d3?w=700&q=80",
  ea02: "https://images.unsplash.com/photo-1462331942851-77708b4b0b3f?w=700&q=80",
  ea03: "https://images.unsplash.com/photo-1446776877081-d282a0f896e2?w=700&q=80",
  ea04: "https://images.unsplash.com/photo-1614728263952-7a7c5b5b4d5e?w=700&q=80",
  ea05: "https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?w=700&q=80",
  ea06: "https://images.unsplash.com/photo-1500380804539-4e1e8f1e3b8f?w=700&q=80",
  ea07: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=700&q=80",
  ea08: "https://images.unsplash.com/photo-1465101046534-3ad6c97076d2?w=700&q=80",
  ea09: "https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=700&q=80",
  ea10: "https://images.unsplash.com/photo-1506318137071-a8e063b4bec0?w=700&q=80",
  ea11: "https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=700&q=80",
  ea12: "https://images.unsplash.com/photo-1543716691-a7dba4f1a2e7?w=700&q=80",
  ea13: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=700&q=80",
  ea14: "https://images.unsplash.com/photo-1614733436491-7b7c8b4d5e3f?w=700&q=80",
  ea15: "https://images.unsplash.com/photo-1502134249123-7b7c8b4d3e2f?w=700&q=80",
  ea16: "https://images.unsplash.com/photo-1462331942851-77708b4b0b3f?w=700&q=80",
  ea17: "https://images.unsplash.com/photo-1606112219348-204e7d816e8c?w=700&q=80",
  ea18: "https://images.unsplash.com/photo-1454750194056-e6f00d00b7d3?w=700&q=80",
  ea19: "https://images.unsplash.com/photo-1500380804539-4e1e8f1e3b8f?w=700&q=80",
  ea20: "https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?w=700&q=80",

  // ══ جسم الإنسان والصحة ══
  hb01: "https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=700&q=80",
  hb02: "https://images.unsplash.com/photo-1576086213369-97a306d36557?w=700&q=80",
  hb03: "https://images.unsplash.com/photo-1551601503-1b1b9c8e3e1e?w=700&q=80",
  hb04: "https://images.unsplash.com/photo-1505682634904-dedd91ecb70c?w=700&q=80",
  hb05: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=700&q=80",
  hb06: "https://images.unsplash.com/photo-1530026405186-ed1f139313f8?w=700&q=80",
  hb07: "https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=700&q=80",
  hb08: "https://images.unsplash.com/photo-1576091060593-6cb5e2e1e2e1e?w=700&q=80",
  hb09: "https://images.unsplash.com/photo-1581595220892-b0739db3ba8c?w=700&q=80",
  hb10: "https://images.unsplash.com/photo-1551601503-1b1b9c8e3e1e?w=700&q=80",
  hb11: "https://images.unsplash.com/photo-1576086213369-97a306d36557?w=700&q=80",
  hb12: "https://images.unsplash.com/photo-1505682634904-dedd91ecb70c?w=700&q=80",
  hb13: "https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=700&q=80",
  hb14: "https://images.unsplash.com/photo-1530026405186-ed1f139313f8?w=700&q=80",
  hb15: "https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=700&q=80",
  hb16: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=700&q=80",
  hb17: "https://images.unsplash.com/photo-1581595220892-b0739db3ba8c?w=700&q=80",
  hb18: "https://images.unsplash.com/photo-1551601503-1b1b9c8e3e1e?w=700&q=80",
  hb19: "https://images.unsplash.com/photo-1576091060593-6cb5e2e1e2e1e?w=700&q=80",
  hb20: "https://images.unsplash.com/photo-1505682634904-dedd91ecb70c?w=700&q=80",

  // ══ الكائنات الحية ══
  lv01: "https://images.unsplash.com/photo-1416879595882-ad7d798863a1?w=700&q=80",
  lv02: "https://images.unsplash.com/photo-1490750967868-88df5649f8cd?w=700&q=80",
  lv03: "https://images.unsplash.com/photo-1444464666168-49d633b86797?w=700&q=80",
  lv04: "https://images.unsplash.com/photo-1574267422556-631b9c2d4e5f?w=700&q=80",
  lv05: "https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=700&q=80",
  lv06: "https://images.unsplash.com/photo-1416879595882-ad7d798863a1?w=700&q=80",
  lv07: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=700&q=80",
  lv08: "https://images.unsplash.com/photo-1505761671935-60b3a7427bad?w=700&q=80",
  lv09: "https://images.unsplash.com/photo-1546182990-dffeafbe8f5f?w=700&q=80",
  lv10: "https://images.unsplash.com/photo-1421422557791-7c2a5b4b1f4e?w=700&q=80",
  lv11: "https://images.unsplash.com/photo-1535241749838-299277b6305f?w=700&q=80",
  lv12: "https://images.unsplash.com/photo-1576174464269-4b6869e1c2e4?w=700&q=80",
  lv13: "https://images.unsplash.com/photo-1551974753-376a35c3b3f7?w=700&q=80",
  lv14: "https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=700&q=80",
  lv15: "https://images.unsplash.com/photo-1564325724739-bae0bd08762c?w=700&q=80",
  lv16: "https://images.unsplash.com/photo-1576086213369-97a306d36557?w=700&q=80",
  lv17: "https://images.unsplash.com/photo-1416879595882-ad7d798863a1?w=700&q=80",
  lv18: "https://images.unsplash.com/photo-1490750967868-88df5649f8cd?w=700&q=80",
  lv19: "https://images.unsplash.com/photo-1535241749838-299277b6305f?w=700&q=80",
  lv20: "https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=700&q=80",
};

export const SCIENCE_G3_S2_EXTRA_UNITS = [
  {
    id: 'matter',
    title_ar: 'المادة وخواصها',
    title_en: 'Matter & Its Properties',
    color: '#0e7490',
    emoji: '⚗️',
    image: U.mt01,
    lessons: [
      {
        id: 'states_of_matter',
        title_ar: 'حالات المادة',
        title_en: 'States of Matter',
        questions: [
          { type: 'multiple_choice', image_url: U.mt01, question_ar: '🔍 انظر إلى الصورة: كل ما له كتلة وحجم في الكون يُسمّى:', options_ar: ['المادة', 'الطاقة', 'الضوء', 'الصوت'], correct: 0, explanation_ar: 'المادة هي كل ما له كتلة وحجم ويشغل حيّزاً من الفراغ.', golden_rule_ar: '🪨 المادة = كتلة + حجم.' },
          { type: 'multiple_choice', image_url: U.mt02, question_ar: '🔍 انظر إلى صورة مكعبات الثلج: الماء في حالته الصلبة يُسمّى:', options_ar: ['الجليد', 'البخار', 'السائل', 'الغاز'], correct: 0, explanation_ar: 'الجليد هو الماء في حالته الصلبة. جزيئاته مرتّبة وثابتة.', golden_rule_ar: '🧊 جليد = ماء صلب.' },
          { type: 'multiple_choice', image_url: U.mt03, question_ar: '🔍 انظر إلى صورة كوب ماء: الماء السائل له شكل:', options_ar: ['يأخذ شكل الإناء الذي يوضع فيه', 'ثابت دائماً', 'لا شكل له', 'دائري دائماً'], correct: 0, explanation_ar: 'السائل له حجم ثابت لكنه يأخذ شكل الإناء. جزيئاته متحرّكة لكنها متلامسة.', golden_rule_ar: '💧 السائل = حجم ثابت + شكل متغيّر.' },
          { type: 'multiple_choice', image_url: U.mt04, question_ar: '🔍 انظر إلى صورة بخار الماء: الغاز له:', options_ar: ['لا شكل ثابت ولا حجم ثابت', 'شكل ثابت فقط', 'حجم ثابت فقط', 'شكل وحجم ثابتين'], correct: 0, explanation_ar: 'الغاز لا له شكل ثابت ولا حجم ثابت. جزيئاته بعيدة ومتحرّكة سريعاً.', golden_rule_ar: '💨 الغاز = لا شكل ولا حجم ثابت.' },
          { type: 'classify', image_url: U.mt05, question_ar: '🔍 انظر إلى الصورة: صنّف كل حالة من المادة:', categories_ar: ['صلب', 'سائل', 'غاز'], items_ar: ['الحجر', 'العصير', 'الهواء', 'المسمار', 'زيت الطبخ', 'الأكسجين'], correct_categories: [0, 1, 2, 0, 1, 2], explanation_ar: 'صلب: حجر + مسمار. سائل: عصير + زيت. غاز: هواء + أكسجين.' },
          { type: 'true_false', image_url: U.mt06, question_ar: '🔍 انظر إلى الصورة: للمادة ثلاث حالات: صلبة وسائلة وغازية.', correct: 'true', explanation_ar: 'للمادة ثلاث حالات أساسية: صلبة (حجر) وسائلة (ماء) وغازية (هواء).' },
          { type: 'multiple_choice', image_url: U.mt07, question_ar: '🔍 انظر إلى صورة غليان الماء: عند غليان الماء يتحوّل من:', options_ar: ['سائل إلى غاز (بخار)', 'غاز إلى سائل', 'صلب إلى سائل', 'سائل إلى صلب'], correct: 0, explanation_ar: 'الغليان تحوّل الماء من الحالة السائلة إلى الغازية (بخار الماء).', golden_rule_ar: '🔥 غليان = سائل ← غاز.' },
          { type: 'multiple_choice', image_url: U.mt08, question_ar: '🔍 انظر إلى صورة ذوبان الجليد: عند ذوبان الجليد يتحوّل من:', options_ar: ['صلب إلى سائل', 'سائل إلى غاز', 'غاز إلى صلب', 'سائل إلى صلب'], correct: 0, explanation_ar: 'الانصهار تحوّل المادة من الحالة الصلبة إلى السائلة.', golden_rule_ar: '🫠 انصهار = صلب ← سائل.' },
          { type: 'matching', image_url: U.mt09, question_ar: '🔍 انظر إلى الصورة: صِل كل تحوّل باسمه:', pairs_ar: [{ left: 'صلب ← سائل', right: 'انصهار' }, { left: 'سائل ← غاز', right: 'تبخّر/غليان' }, { left: 'غاز ← سائل', right: 'تكثّف' }, { left: 'سائل ← صلب', right: 'تجمّد' }], explanation_ar: 'انصهار = ذوبان | تبخّر = غليان | تكثّف = بخار←ماء | تجمّد = ماء←جليد.' },
          { type: 'true_false', image_url: U.mt10, question_ar: '🔍 انظر إلى صورة تكثّف بخار الماء على زجاج: التكثّف هو تحوّل الغاز إلى سائل.', correct: 'true', explanation_ar: 'التكثّف تحوّل الغاز (بخار الماء) إلى سائل (قطرات) عند برودته.' },
          { type: 'multiple_choice', image_url: U.mt11, question_ar: '🔍 انظر إلى صورة صخور متنوعة: أيّ خاصية فيزيائية تُميّز كل صخر؟', options_ar: ['اللون والصلابة والكثافة', 'الطعم فقط', 'الرائحة فقط', 'الصوت'], correct: 0, explanation_ar: 'الخصائص الفيزيائية للمادة: اللون، الصلابة، الكثافة، الملمس، المغناطيسية.', golden_rule_ar: '🎨 الخصائص الفيزيائية = لون + صلابة + كثافة.' },
          { type: 'classify', image_url: U.mt12, question_ar: '🔍 انظر إلى الصورة: صنّف كل خاصية:', categories_ar: ['خاصية فيزيائية', 'ليست خاصية فيزيائية'], items_ar: ['اللون', 'السعر', 'الصلابة', 'الاسم', 'الكثافة', 'الملمس'], correct_categories: [0, 1, 0, 1, 0, 0], explanation_ar: 'فيزيائية: لون + صلابة + كثافة + ملمس. ليست: سعر + اسم.' },
          { type: 'multiple_choice', image_url: U.mt13, question_ar: '🔍 انظر إلى صورة مواد تطفو وتغرق: أيّ المواد التالية تطفو على الماء؟', options_ar: ['الفلّين والخشب الخفيف', 'الحديد', 'الرصاص', 'النحاس'], correct: 0, explanation_ar: 'الأجسام ذات الكثافة الأقل من الماء (مثل الفلّين) تطفو. الأجسام الكثيفة كالحديد تغرق.', golden_rule_ar: '🛶 كثافة أقل من الماء = يطفو.' },
          { type: 'true_false', image_url: U.mt14, question_ar: '🔍 انظر إلى الصورة: قطعة الحديد تغرق في الماء لأن كثافتها أكبر من كثافة الماء.', correct: 'true', explanation_ar: 'الحديد كثافته 7.8 جم/سم^{3} بينما الماء 1 جم/سم^{3}. الأكبر كثافة يغرق.' },
          { type: 'multiple_choice', image_url: U.mt15, question_ar: '🔍 انظر إلى صورة مغناطيس: أيّ المواد التالية يجذبها المغناطيس؟', options_ar: ['الحديد والنيكل والكوبالت', 'الخشب', 'الزجاج', 'البلّاستيك'], correct: 0, explanation_ar: 'المغناطيس يجذب المعادن المغناطيسية: الحديد والنيكل والكوبالت فقط.', golden_rule_ar: '🧲 المغناطيس يجذب: حديد + نيكل + كوبالت.' },
          { type: 'classify', image_url: U.mt16, question_ar: '🔍 انظر إلى صورة مغناطيس ومواد: صنّف كل مادة: هل يجذبها المغناطيس؟', categories_ar: ['يجذبها المغناطيس', 'لا يجذبها'], items_ar: ['مسمار حديد', 'عملة نحاس', 'مشبك ورق معدني', 'قلم رصاص', 'مفتاح حديد', 'زجاجة بلاستيك'], correct_categories: [0, 1, 0, 1, 0, 1], explanation_ar: 'يجذب: مسمار + مشبك + مفتاح (حديد). لا يجذب: نحاس + قلم + بلاستيك.' },
          { type: 'multiple_choice', image_url: U.mt17, question_ar: '🔍 انظر إلى صورة ماء ملوّن: الخاصية التي تجعل لكل مادة لوناً مميّزاً هي:', options_ar: ['خاصية فيزيائية', 'خاصية كيميائية', 'خاصية ميكانيكية', 'خاصية كهربائية'], correct: 0, explanation_ar: 'اللون خاصية فيزيائية تُساعدنا على التعرّف على المواد وتمييزها.' },
          { type: 'ordering', image_url: U.mt18, question_ar: '🔍 انظر إلى صورة دورة الماء: رتّب تحوّلات الماء في الطبيعة:', items_ar: ['الماء يتبخّر من البحر', 'بخار الماء يصعد للسماء', 'بخار الماء يتكثّف إلى سحب', 'السحب تُمطر الماء', 'الماء يعود للبحر'], explanation_ar: 'تبخّر ← صعود ← تكثّف ← مطر ← عودة للبحر.' },
          { type: 'true_false', image_url: U.mt19, question_ar: '🔍 انظر إلى الصورة: الماء في حالتيه السائلة والصلبة لهما نفس الكثافة.', correct: 'false', explanation_ar: 'الجليد (صلب) كثافته أقل من الماء السائل — لهذا يطفو الجليد على الماء.' },
          { type: 'multiple_choice', image_url: U.mt20, question_ar: '🔍 انظر إلى صورة عدسة مكبّرة: لدراسة خصائص المادة نستخدم:', options_ar: ['الحواس والأدوات العلمية', 'الإحساس فقط', 'اللعب', 'الأحلام'], correct: 0, explanation_ar: 'ندرس خصائص المادة بالحواس (بصر/لمس) والأدوات (عدسة، ميزان، مخبار).', golden_rule_ar: '🔬 الحواس + الأدوات = دراسة المادة.' },
        ],
      },
      {
        id: 'physical_changes',
        title_ar: 'التغيّرات الفيزيائية',
        title_en: 'Physical Changes',
        questions: [
          { type: 'multiple_choice', image_url: U.mt07, question_ar: '🔍 انظر إلى صورة غليان الماء: الغليان مثال على تغيّر:', options_ar: ['فيزيائي (لا يُنتج مادة جديدة)', 'كيميائي', 'بيولوجي', 'كهربائي'], correct: 0, explanation_ar: 'التغيّر الفيزيائي لا يُنتج مادة جديدة — الماء يبقى ماءً سواء كان جليداً أو بخاراً.', golden_rule_ar: '🔄 تغيّر فيزيائي = لا مادة جديدة.' },
          { type: 'classify', image_url: U.mt08, question_ar: '🔍 انظر إلى الصورة: صنّف كل تغيّر:', categories_ar: ['تغيّر فيزيائي', 'تغيّر كيميائي'], items_ar: ['ذوبان الجليد', 'احتراق الورق', 'تمزّق الورق', 'صدأ الحديد', 'تبخّر الماء', 'طهي البيض'], correct_categories: [0, 1, 0, 1, 0, 1], explanation_ar: 'فيزيائي: ذوبان + تمزّق + تبخّر. كيميائي: احتراق + صدأ + طهي.' },
          { type: 'true_false', image_url: U.mt09, question_ar: '🔍 انظر إلى الصورة: قطع الورق بالمقص تغيّر كيميائي.', correct: 'false', explanation_ar: 'قطع الورق تغيّر فيزيائي — لا تنتج مادة جديدة، فقط تغيّر الشكل.' },
          { type: 'multiple_choice', image_url: U.mt10, question_ar: '🔍 انظر إلى صورة تكثّف: أيّ تغيّر يحدث عندما يتحوّل البخار إلى قطرات؟', options_ar: ['تغيّر فيزيائي (تكثّف)', 'تغيّر كيميائي', 'تغيّر بيولوجي', 'تغيّر ميكانيكي'], correct: 0, explanation_ar: 'التكثّف تغيّر فيزيائي — البخار والماء كلاهما H₂O، نفس المادة.' },
          { type: 'matching', image_url: U.mt11, question_ar: '🔍 انظر إلى الصورة: صِل كل تغيّر بنوعه:', pairs_ar: [{ left: 'ذوبان الشوكولاتة', right: 'فيزيائي' }, { left: 'احتراق الخشب', right: 'كيميائي' }, { left: 'تبخّر العطر', right: 'فيزيائي' }, { left: 'طبخ اللحم', right: 'كيميائي' }], explanation_ar: 'فيزيائي: ذوبان + تبخّر. كيميائي: احتراق + طبخ.' },
          { type: 'multiple_choice', image_url: U.mt12, question_ar: '🔍 انظر إلى الصورة: ما الدليل على حدوث تغيّر كيميائي؟', options_ar: ['ظهور مادة جديدة (لون/رائحة/حرارة)', 'تغيّر الشكل فقط', 'تغيّر الحجم فقط', 'لا شيء'], correct: 0, explanation_ar: 'التغيّر الكيميائي يُنتج مادة جديدة لها خصائص مختلفة: تغيّر اللون، أو انبعاث حرارة/ضوء/غاز.', golden_rule_ar: '🧪 كيميائي = مادة جديدة.' },
          { type: 'true_false', image_url: U.mt13, question_ar: '🔍 انظر إلى الصورة: الفلّين يطفو على الماء لأن كثافته أقل من كثافة الماء.', correct: 'true', explanation_ar: 'صحيح. كل جسم كثافته أقل من الماء يطفو، وكل جسم كثافته أكبر يغرق.' },
          { type: 'multiple_choice', image_url: U.mt14, question_ar: '🔍 انظر إلى الصورة: عند مزج الملح مع الماء يذوب الملح. هذا تغيّر:', options_ar: ['فيزيائي', 'كيميائي', 'كهربائي', 'مغناطيسي'], correct: 0, explanation_ar: 'الإذابة تغيّر فيزيائي — يمكن استرجاع الملح بالتبخّر. لا تنتج مادة جديدة.' },
          { type: 'ordering', image_url: U.mt15, question_ar: '🔍 انظر إلى صورة مغناطيس: رتّب خطوات فصل خليط من برادة الحديد والرمل:', items_ar: ['أحضر المغناطيس', 'قرّبه من الخليط', 'يجذب برادة الحديد', 'تبقى الرمل', 'انفصلت المكوّنات'], explanation_ar: 'مغناطيس ← تقريب ← جذب برادة ← تبقى رمل ← انفصال.' },
          { type: 'classify', image_url: U.mt16, question_ar: '🔍 انظر إلى الصورة: صنّف كل تغيّر فيزيائي:', categories_ar: ['تغيّر فيزيائي', 'تغيّر كيميائي'], items_ar: ['ذوبان السكر في الماء', 'احتراق الشمعة', 'تجميد الماء', 'عصر الليمون', 'هضم الطعام', 'بشر الجزر'], correct_categories: [0, 1, 0, 0, 1, 0], explanation_ar: 'فيزيائي: إذابة + تجميد + عصر + بشر. كيميائي: احتراق + هضم.' },
        ],
      },
    ],
  },

  {
    id: 'earth_space',
    title_ar: 'الأرض والفضاء',
    title_en: 'Earth & Space',
    color: '#1e40af',
    emoji: '🌍',
    image: U.ea01,
    lessons: [
      {
        id: 'solar_system',
        title_ar: 'المجموعة الشمسية',
        title_en: 'Solar System',
        questions: [
          { type: 'multiple_choice', image_url: U.ea01, question_ar: '🔍 انظر إلى صورة الكون: المجموعة الشمسية مكوّنة من:', options_ar: ['الشمس و8 كواكب', 'القمر فقط', 'النجوم فقط', 'الأرض فقط'], correct: 0, explanation_ar: 'المجموعة الشمسية تضم الشمس و8 كواكب تدور حولها: عطارد، الزهرة، الأرض، المرّيخ، المشتري، زحل، أورانوس، نبتون.', golden_rule_ar: '☀️ المجموعة = شمس + 8 كواكب.' },
          { type: 'multiple_choice', image_url: U.ea02, question_ar: '🔍 انظر إلى صورة الشمس: الشمس هي:', options_ar: ['نجم في مركز المجموعة الشمسية', 'كوكب', 'قمر', 'كويكب'], correct: 0, explanation_ar: 'الشمس نجم ضخم يمدّ الكواكب بالضوء والحرارة. هي مركز المجموعة الشمسية.', golden_rule_ar: '🌟 الشمس = نجم.' },
          { type: 'multiple_choice', image_url: U.ea03, question_ar: '🔍 انظر إلى صورة كوكب الأرض: الأرض هي الكوكب:', options_ar: ['الثالث من الشمس', 'الأول', 'الخامس', 'الأخير'], correct: 0, explanation_ar: 'الأرض الكوكب الثالث بعد عطارد والزهرة. هي الكوكب الوحيد المعروف بحياة فيه.', golden_rule_ar: '🌍 الأرض = الكوكب الثالث.' },
          { type: 'ordering', image_url: U.ea04, question_ar: '🔍 انظر إلى صورة الكواكب: رتّب الكواكب الأربعة الأولى من الأقرب للشمس:', items_ar: ['عطارد', 'الزهرة', 'الأرض', 'المرّيخ'], explanation_ar: 'عطارد ← الزهرة ← الأرض ← المرّيخ (الأقرب للأبعد).' },
          { type: 'classify', image_url: U.ea05, question_ar: '🔍 انظر إلى الصورة: صنّف كل جرم سماوي:', categories_ar: ['نجم', 'كوكب', 'قمر'], items_ar: ['الشمس', 'الأرض', 'قمر الأرض', 'المرّيخ', 'نجمة بعيدة', 'قمر المشتري'], correct_categories: [0, 1, 2, 1, 0, 2], explanation_ar: 'نجم: شمس + نجمة. كوكب: أرض + مرّيخ. قمر: قمر أرض + قمر مشتري.' },
          { type: 'true_false', image_url: U.ea06, question_ar: '🔍 انظر إلى صورة القمر: القمر يدور حول الأرض ويُضاء بضوء الشمس.', correct: 'true', explanation_ar: 'القمر تابع للأرض يدور حولها، ولا يُصدر ضوءاً بل يعكس ضوء الشمس.' },
          { type: 'multiple_choice', image_url: U.ea07, question_ar: '🔍 انظر إلى صورة الأرض من الفضاء: الأرض كوكب:', options_ar: ['يحتوي على ماء وهواء وحياة', 'لا يحتوي على ماء', 'لا يحتوي على هواء', 'خالٍ من الحياة'], correct: 0, explanation_ar: 'الأرض كوكب مميّز: يحوي ماءً سائلاً، هواءً للتنفّس، وحياة.', golden_rule_ar: '🌊 الأرض = ماء + هواء + حياة.' },
          { type: 'multiple_choice', image_url: U.ea08, question_ar: '🔍 انظر إلى صورة شروق الشمس: الشمس تشرق من:', options_ar: ['الشرق', 'الغرب', 'الشمال', 'الجنوب'], correct: 0, explanation_ar: 'الأرض تدور حول نفسها من الغرب للشرق، فتبدو الشمس طالعة من الشرق وغاربة في الغرب.', golden_rule_ar: '🌅 الشمس تشرق من الشرق.' },
          { type: 'true_false', image_url: U.ea09, question_ar: '🔍 انظر إلى الصورة: الكواكب تدور حول الشمس في مدارات بيضاوية.', correct: 'true', explanation_ar: 'كل كوكب يدور في مدار بيضاوي حول الشمس. زمن الدورة يختلف باختلاف الكوكب.' },
          { type: 'matching', image_url: U.ea10, question_ar: '🔍 انظر إلى الصورة: صِل الكوكب بموقعه:', pairs_ar: [{ left: 'عطارد', right: 'الأقرب للشمس' }, { left: 'الأرض', right: 'الثالث' }, { left: 'المشتري', right: 'الأكبر حجماً' }, { left: 'نبتون', right: 'الأبعد عن الشمس' }], explanation_ar: 'عطارد=أقرب | أرض=ثالث | مشتري=أكبر | نبتون=أبعد.' },
          { type: 'multiple_choice', image_url: U.ea11, question_ar: '🔍 انظر إلى صورة الليل والنهار: تعاقب الليل والنهار سببه:', options_ar: ['دوران الأرض حول نفسها', 'دوران القمر', 'حركة الشمس', 'لا سبب'], correct: 0, explanation_ar: 'الأرض تدور حول محورها كل 24 ساعة، فالجهة المواجهة للشمس نهار، والمقابلة ليل.', golden_rule_ar: '🔄 دوران الأرض = ليل + نهار.' },
          { type: 'multiple_choice', image_url: U.ea12, question_ar: '🔍 انظر إلى صورة الفصول: الفصول الأربعة سببها:', options_ar: ['دوران الأرض حول الشمس + ميل المحور', 'دوران القمر', 'حركة النجوم', 'الرياح'], correct: 0, explanation_ar: 'الأرض تدور حول الشمس في 365 يوم ومحورها مائل، فيتغيّر زاوية سقوط الضوء فتنشأ الفصول.', golden_rule_ar: '🍂 الفصول = دوران حول الشمس + ميل.' },
          { type: 'classify', image_url: U.ea13, question_ar: '🔍 انظر إلى الصورة: صنّف كل ظاهرة:', categories_ar: ['نتيجة دوران الأرض حول نفسها', 'نتيجة دوران الأرض حول الشمس'], items_ar: ['الليل والنهار', 'الفصول الأربعة', 'شروق الشمس', 'الصيف والشتاء', 'تعاقب الظلام والضوء', 'اختلاف طول النهار'], correct_categories: [0, 1, 0, 1, 0, 1], explanation_ar: 'حول نفسها: ليل/نهار + شروق + ظلام/ضوء. حول الشمس: فصول + صيف/شتاء + طول النهار.' },
          { type: 'true_false', image_url: U.ea14, question_ar: '🔍 انظر إلى الصورة: القمر يُصدر ضوءه الخاص ليلاً.', correct: 'false', explanation_ar: 'القمر لا يُصدر ضوءاً — يعكس ضوء الشمس الساقط عليه.' },
          { type: 'multiple_choice', image_url: U.ea15, question_ar: '🔍 انظر إلى صورة النجوم: النجوم أجسام سماوية:', options_ar: ['تُصدر الضوء والحرارة', 'تعكس الضوء فقط', 'لا ضوء لها', 'تدور حول الأرض'], correct: 0, explanation_ar: 'النجوم كرات غازية ضخمة تُصدر ضوءاً وحرارة ناتجَيْن عن التفاعلات النووية بداخلها.' },
          { type: 'ordering', image_url: U.ea16, question_ar: '🔍 انظر إلى الصورة: رتّب الكواكب حسب البُعد عن الشمس:', items_ar: ['عطارد', 'الزهرة', 'الأرض', 'المرّيخ', 'المشتري', 'زحل', 'أورانوس', 'نبتون'], explanation_ar: '8 كواكب: عطارد، الزهرة، الأرض، المرّيخ، المشتري، زحل، أورانوس، نبتون.' },
          { type: 'multiple_choice', image_url: U.ea17, question_ar: '🔍 انظر إلى صورة المرّيخ: المرّيخ يُلقّب بـ:', options_ar: ['الكوكب الأحمر', 'الكوكب الأزرق', 'الكوكب الأخضر', 'الكوكب الأصفر'], correct: 0, explanation_ar: 'المرّيخ يبدو أحمر بسبب أكسيد الحديد (الصدأ) على سطحه.', golden_rule_ar: '🔴 المرّيخ = الكوكب الأحمر.' },
          { type: 'true_false', image_url: U.ea18, question_ar: '🔍 انظر إلى الصورة: الشمس أكبر من الأرض بكثير جداً.', correct: 'true', explanation_ar: 'الشمس أكبر من الأرض بمليون مرة تقريباً. يمكن أن تتّسع لأكثر من مليون أرض.' },
          { type: 'multiple_choice', image_url: U.ea19, question_ar: '🔍 انظر إلى صورة فلكي: أيّ كوكب له حلقات بارزة؟', options_ar: ['زحل', 'الأرض', 'عطارد', 'الزهرة'], correct: 0, explanation_ar: 'زحل له حلقات جميلة من الجليد والصخور تدور حوله. هي الأبرز في المجموعة الشمسية.', golden_rule_ar: '🪐 زحل = كوكب الحلقات.' },
          { type: 'multiple_choice', image_url: U.ea20, question_ar: '🔍 انظر إلى صورة كوكب المشتري: المشتري هو:', options_ar: ['أكبر كواكب المجموعة الشمسية', 'أصغر الكواكب', 'كوكب أرضي', 'قمر'], correct: 0, explanation_ar: 'المشتري أكبر الكواكب — يمكن أن يتّسع لأكثر من 1300 أرض.' },
        ],
      },
      {
        id: 'earth_surface',
        title_ar: 'سطح الأرض والماء',
        title_en: "Earth's Surface & Water",
        questions: [
          { type: 'multiple_choice', image_url: U.ea05, question_ar: '🔍 انظر إلى صورة محيط: أكبر نسبة من سطح الأرض покрыّها:', options_ar: ['الماء (محيطات وبحار)', 'اليابسة', 'الجليد', 'الصحراء'], correct: 0, explanation_ar: 'الماء يغطّي ~71% من سطح الأرض، واليابسة ~29%. لهذا تُسمّى الأرض "الكوكب الأزرق".', golden_rule_ar: '🌊 71% من الأرض ماء.' },
          { type: 'classify', image_url: U.ea06, question_ar: '🔍 انظر إلى الصورة: صنّف كل مصدر مائي:', categories_ar: ['ماء مالح', 'ماء عذب'], items_ar: ['البحر', 'النهر', 'المحيط', 'البحيرة العذبة', 'بحيرة مالحة', 'ينبوع'], correct_categories: [0, 1, 0, 1, 0, 1], explanation_ar: 'مالح: بحر + محيط + بحيرة مالحة. عذب: نهر + بحيرة عذبة + ينبوع.' },
          { type: 'multiple_choice', image_url: U.ea07, question_ar: '🔍 انظر إلى صورة صحراء: أيّ منطقة من سطح الأرض تتميّز بالجفاف والرمال؟', options_ar: ['الصحراء', 'الغابة', 'المنطقة القطبية', 'البحر'], correct: 0, explanation_ar: 'الصحراء منطقة جافة قليلة المطر، رمال وحصى. تشمل الربع الخالي في السعودية.', golden_rule_ar: '🏜️ صحراء = جفاف + رمال.' },
          { type: 'multiple_choice', image_url: U.ea08, question_ar: '🔍 انظر إلى صورة جبال: الجبال تكوّنت بسبب:', options_ar: ['حركات القشرة الأرضية عبر ملايين السنين', 'الرياح فقط', 'المطر فقط', 'الإنسان'], correct: 0, explanation_ar: 'الجبال تكوّنت من حركات القشرة الأرضية وضغط الصفائح على بعضها عبر ملايين السنين.' },
          { type: 'true_false', image_url: U.ea09, question_ar: '🔍 انظر إلى الصورة: التربة المكوّن الأساسي لزراعة النباتات.', correct: 'true', explanation_ar: 'التربة توفر المعدن والماء للنباتات. بدون تربة خصبة لا زراعة.' },
          { type: 'matching', image_url: U.ea10, question_ar: '🔍 انظر إلى الصورة: صِل كل سطح بتسميته:', pairs_ar: [{ left: 'اليابسة المرتفعة جداً', right: 'الجبال' }, { left: 'المسطح المائي الكبير المالح', right: 'المحيط' }, { left: 'المسطح الرملي الجاف', right: 'الصحراء' }, { left: 'المسطح الأخضر الشجري', right: 'الغابة' }], explanation_ar: 'جبال + محيط + صحراء + غابة = تنوّع سطح الأرض.' },
          { type: 'multiple_choice', image_url: U.ea11, question_ar: '🔍 انظر إلى صورة المطر: المطر جزء من دورة الماء في الطبيعة. الماء يتبخّر من:', options_ar: ['المحيطات والبحار والأنهار', 'الجبال فقط', 'القمر', 'الفضاء'], correct: 0, explanation_ar: 'الماء يتبخّر من المسطحات المائية (محيطات/بحار/أنهار) بفعل حرارة الشمس.' },
          { type: 'ordering', image_url: U.ea12, question_ar: '🔍 انظر إلى صورة دورة الماء: رتّب مراحل دورة الماء:', items_ar: ['الشمس تُسخّن الماء', 'يتبخّر الماء بخاراً', 'الخار يصعد للسماء', 'يتكثّف إلى سحب', 'تُمطر السحب'], explanation_ar: 'تسخين ← تبخّر ← صعود ← تكثّف ← مطر.' },
          { type: 'true_false', image_url: U.ea13, question_ar: '🔍 انظر إلى الصورة: كمية الماء على الأرض ثابتة تتكرّر في دورة.', correct: 'true', explanation_ar: 'كمية الماء ثابتة في الطبيعة — يتبخّر ثم يُمطر ثم يعود للبحر. لا يُفقد ولا يُستحدث.' },
          { type: 'multiple_choice', image_url: U.ea14, question_ar: '🔍 انظر إلى صورة بركان: البراكين تخرج منها:', options_ar: ['صهارة ( magma) وغازات', 'ماء', 'ثلج', 'رمال'], correct: 0, explanation_ar: 'البركان يقذف الصهارة المنصهرة (الحارّة جداً) والغازات من باطن الأرض.', golden_rule_ar: '🌋 بركان = صهارة + غازات.' },
        ],
      },
    ],
  },

  {
    id: 'living_things',
    title_ar: 'الكائنات الحية',
    title_en: 'Living Things',
    color: '#15803d',
    emoji: '🌱',
    image: U.lv01,
    lessons: [
      {
        id: 'plants',
        title_ar: 'النباتات',
        title_en: 'Plants',
        questions: [
          { type: 'multiple_choice', image_url: U.lv01, question_ar: '🔍 انظر إلى صورة نبات: النباتات كائنات حية تُصنع غذاءها بعملية:', options_ar: ['البناء الضوئي', 'التنفّس', 'الهضم', 'الاحتراق'], correct: 0, explanation_ar: 'البناء الضوئي: النبات يستخدم ضوء الشمس + ماء + ثاني أكسيد الكربون ليصنع غذاءه.', golden_rule_ar: '🌱 بناء ضوئي = ضوء + ماء + CO₂.' },
          { type: 'multiple_choice', image_url: U.lv02, question_ar: '🔍 انظر إلى صورة شجرة: أيّ جزء من النبات يمتصّ الماء من التربة؟', options_ar: ['الجذور', 'الأوراق', 'الزهور', 'الثمار'], correct: 0, explanation_ar: 'الجذور تثبّت النبات وتمتصّ الماء والأملاح من التربة.', golden_rule_ar: '🌳 جذور = امتصاص الماء.' },
          { type: 'multiple_choice', image_url: U.lv03, question_ar: '🔍 انظر إلى صورة أوراق: أيّ جزء يصنع الغذاء للنبات؟', options_ar: ['الأوراق', 'الجذور', 'الساق فقط', 'الثمار'], correct: 0, explanation_ar: 'الأوراق تحتوي الكلوروفيل الأخضر الذي يصنع الغذاء بالبناء الضوئي.', golden_rule_ar: '🍃 أوراق = مصنع الغذاء.' },
          { type: 'matching', image_url: U.lv04, question_ar: '🔍 انظر إلى صورة نبتة كاملة: صِل كل جزء بوظيفته:', pairs_ar: [{ left: 'الجذور', right: 'تمتصّ الماء' }, { left: 'الساق', right: 'ينقل الماء والأملاح' }, { left: 'الأوراق', right: 'تصنع الغذاء' }, { left: 'الزهور', right: 'التكاثر وإنتاج الثمار' }], explanation_ar: 'جذور=امتصاص | ساق=نقل | أوراق=غذاء | زهور=تكاثر.' },
          { type: 'classify', image_url: U.lv05, question_ar: '🔍 انظر إلى الصورة: صنّف كل نبات:', categories_ar: ['نبات زهري', 'نبات غير زهري'], items_ar: ['الورد', 'السراخس', 'ال tulip', 'الأشجار الصنوبرية', 'الياسمين', 'الطحالب'], correct_categories: [0, 1, 0, 1, 0, 1], explanation_ar: 'زهري: ورد + توليب + ياسمين. غير زهري: سراخس + صنوبر + طحالب.' },
          { type: 'true_false', image_url: U.lv06, question_ar: '🔍 انظر إلى الصورة: النباتات تحتاج إلى ضوء الشمس لصنع غذائها.', correct: 'true', explanation_ar: 'بدون ضوء الشمس لا يحدث البناء الضوئي ويموت النبات جوعاً.' },
          { type: 'multiple_choice', image_url: U.lv07, question_ar: '🔍 انظر إلى صورة بذور: البذور تنبت إلى نبات جديد عندما تتوفّر:', options_ar: ['الماء والهواء والحرارة المناسبة', 'الظلام التام', 'البرد الشديد', 'لا شيء'], correct: 0, explanation_ar: 'البذرة تنبت عندما تجد الماء + الهواء + الحرارة المناسبة + تربة جيدة.', golden_rule_ar: '🌱 إنبات = ماء + هواء + حرارة.' },
          { type: 'ordering', image_url: U.lv08, question_ar: '🔍 انظر إلى صورة نبتة صغيرة: رتّب مراحل نموّ النبات من البذرة:', items_ar: ['بذرة في التربة', 'تمتصّ الماء وتنتفخ', 'تخرج الجذور للأسفل', 'يخرج الساق للأعلى', 'تنمو الأوراق', 'تُزهر وتُثمر'], explanation_ar: 'بذرة ← انتفاخ ← جذور ← ساق ← أوراق ← زهور وثمار.' },
          { type: 'multiple_choice', image_url: U.lv09, question_ar: '🔍 انظر إلى صورة صبار: الصبار نبات يعيش في:', options_ar: ['الصحراء (بيئة جافة)', 'الماء', 'الجليد', 'الكهوف'], correct: 0, explanation_ar: 'الصبار متكيّف مع الصحراء: يخزّن الماء في ساقه وأوراقه الإبرية تقلّل تبخّر الماء.' },
          { type: 'classify', image_url: U.lv10, question_ar: '🔍 انظر إلى الصورة: صنّف كل نبات حسب بيئته:', categories_ar: ['يعيش في الصحراء', 'يعيش في الماء'], items_ar: ['صبار', 'زنبق الماء', 'نخيل', 'طحالب البحر', 'صمغ عربي', 'اللوتس'], correct_categories: [0, 1, 0, 1, 0, 1], explanation_ar: 'صحراء: صبار + نخيل + صمغ. ماء: زنبق + طحالب + لوتس.' },
          { type: 'true_false', image_url: U.lv11, question_ar: '🔍 انظر إلى الصورة: النباتات تُطلق الأكسجين أثناء البناء الضوئي.', correct: 'true', explanation_ar: 'البناء الضوئي يُنتج غذاءً ويُطلق الأكسجين الذي نتنفّسه. لهذا النباتات مهمّة للحياة.' },
          { type: 'multiple_choice', image_url: U.lv12, question_ar: '🔍 انظر إلى صورة نخلة: النخلة شجرة تنمو بكثرة في:', options_ar: ['المناطق الحارة كالسعودية', 'القطب الشمالي', 'أعماق البحار', 'الكهوف'], correct: 0, explanation_ar: 'النخيل يثمر في المناطق الحارة. السعودية مشهورة بزراعة التمور.', golden_rule_ar: '🌴 النخيل = شجرة الصحراء.' },
          { type: 'multiple_choice', image_url: U.lv13, question_ar: '🔍 انظر إلى صورة زهرة ونحلة: النحل يساعد النباتات في:', options_ar: ['نقل اللقاح لتكوين الثمار', 'صنع الغذاء', 'امتصاص الماء', 'التنفّس'], correct: 0, explanation_ar: 'النحل ينقل اللقاح بين الزهور فتتكوّن الثمار والبذور. علاقة مفيدة للطرفين.' },
          { type: 'matching', image_url: U.lv14, question_ar: '🔍 انظر إلى صورة فاكهة: صِل كل نبات بثمرته:', pairs_ar: [{ left: 'النخلة', right: 'التمر' }, { left: 'شجرة التفاح', right: 'التفاح' }, { left: 'شجرة البرتقال', right: 'البرتقال' }, { left: 'شجرة الموز', right: 'الموز' }], explanation_ar: 'نخلة=تمر | تفاح | برتقال | موز.' },
          { type: 'true_false', image_url: U.lv15, question_ar: '🔍 انظر إلى الصورة: للنباتات حواس كالإنسان.', correct: 'false', explanation_ar: 'النباتات لا تحواس كالإنسان لكنها تستجيب للمؤثرات (ضوء/ماء/جاذبية).' },
          { type: 'multiple_choice', image_url: U.lv16, question_ar: '🔍 انظر إلى صورة نباتات طبخ: أيّ نبات من هذه نأكل جذره؟', options_ar: ['الجزر والبطاطس', 'التفاح', 'البرتقال', 'التمر'], correct: 0, explanation_ar: 'الجزر والبطاطس جذور درنية يخزّن النبات فيها غذاءه. نأكلها جذوراً.' },
          { type: 'multiple_choice', image_url: U.lv17, question_ar: '🔍 انظر إلى صورة ورق خس: أيّ نبات نأكل أوراقه؟', options_ar: ['الخس والملفوف', 'الجزر', 'البطاطس', 'الذرة'], correct: 0, explanation_ar: 'الخس والملفوف نباتات نأكل أوراقها الخضراء الغنية بالفيتامينات.' },
          { type: 'classify', image_url: U.lv18, question_ar: '🔍 انظر إلى صورة طعام نباتي: صنّف حسب الجزء المأكول:', categories_ar: ['نأكل الجذر', 'نأكل الورقة', 'نأكل الثمرة'], items_ar: ['جزر', 'خس', 'طماطم', 'بطاطس', 'سبانخ', 'تفاح'], correct_categories: [0, 1, 2, 0, 1, 2], explanation_ar: 'جذر: جزر + بطاطس. ورقة: خس + سبانخ. ثمرة: طماطم + تفاح.' },
          { type: 'ordering', image_url: U.lv19, question_ar: '🔍 انظر إلى صورة نخلة: رتّب مراحل نموّ التمرة:', items_ar: ['النخلة تُزهر', 'تُلقّح الزهور', 'تكوّن الثمار الصغيرة', 'تنمو التمرة', 'تنضج وتُحصد'], explanation_ar: 'إزهار ← تلقيح ← ثمار صغيرة ← نمو ← نضج وحصاد.' },
          { type: 'multiple_choice', image_url: U.lv20, question_ar: '🔍 انظر إلى صورة نباتات متنوعة: النباتات مهمّة لأنها:', options_ar: ['تُنتج الأكسجين والغذاء', 'تُنتج الصوت', 'تُنتج الكهرباء', 'لا فائدة منها'], correct: 0, explanation_ar: 'النباتات تُنتج الأكسجاء والغذاء لكل الكائنات الحية — أساس الحياة على الأرض.', golden_rule_ar: '🌿 نباتات = أكسجين + غذاء = حياة.' },
        ],
      },
      {
        id: 'animals',
        title_ar: 'الحيوانات',
        title_en: 'Animals',
        questions: [
          { type: 'multiple_choice', image_url: U.lv01, question_ar: '🔍 انظر إلى صورة قطة: الحيوانات كائنات حية تختلف عن النباتات بأنها:', options_ar: ['لا تصنع غذاءها بنفسها', 'تصنع غذاءها', 'لا تتحرّك', 'لا تتنفّس'], correct: 0, explanation_ar: 'الحيوانات لا تصنع غذاءها — تعتمد على أكل النباتات أو حيوانات أخرى.', golden_rule_ar: '🐾 حيوان = يأكل غذاءً جاهزاً.' },
          { type: 'classify', image_url: U.lv02, question_ar: '🔍 انظر إلى الصورة: صنّف كل حيوان:', categories_ar: ['حيوان أليف', 'حيوان برّي'], items_ar: ['قطة', 'أسد', 'كلب', 'فيل', 'دجاج', 'ذئب'], correct_categories: [0, 1, 0, 1, 0, 1], explanation_ar: 'أليف: قطة + كلب + دجاج. برّي: أسد + فيل + ذئب.' },
          { type: 'multiple_choice', image_url: U.lv03, question_ar: '🔍 انظر إلى صورة طائر: الطيور تتميّز بـ:', options_ar: ['الريش والمنقار والأجنحة', 'الشعر', 'الحراشف', 'القرون'], correct: 0, explanation_ar: 'الطيور لها ريش ومنقار وأجنحة. أغلبها يطير وبعضها لا يطير (النعامة).', golden_rule_ar: '🐦 طائر = ريش + منقار + أجنحة.' },
          { type: 'classify', image_url: U.lv04, question_ar: '🔍 انظر إلى الصورة: صنّف كل حيوان حسب groupe:', categories_ar: ['طائر', 'ثديي', 'سمكة'], items_ar: ['صقر', 'حصان', 'سمكة ذهبية', 'بط', 'بقرة', 'قرش'], correct_categories: [0, 1, 2, 0, 1, 2], explanation_ar: 'طائر: صقر + بط. ثديي: حصان + بقرة. سمكة: ذهبية + قرش.' },
          { type: 'multiple_choice', image_url: U.lv05, question_ar: '🔍 انظر إلى صورة أسماك: السمك يتنفّس عبر:', options_ar: ['الخياشيم', 'الرئتين', 'الجلد', 'الأنف'], correct: 0, explanation_ar: 'السمك يتنفّس عبر الخياشيم التي تستخلص الأكسجين الذائب في الماء.', golden_rule_ar: '🐟 سمك = خياشيم.' },
          { type: 'multiple_choice', image_url: U.lv06, question_ar: '🔍 انظر إلى صورة ثديّات: الثديّات تتميّز بأنها:', options_ar: ['ترضع صغارها حليباً', 'تبيض', 'لها رياش', 'تعيش في الماء'], correct: 0, explanation_ar: 'الثديّات حيوانات تُرضع صغارها حليباً من الأم. مثل: الإنسان، القطة، الحصان.', golden_rule_ar: '🐎 ثديي = يُرضع.' },
          { type: 'true_false', image_url: U.lv07, question_ar: '🔍 انظر إلى الصورة: الضفدع حيوان برمائي يعيش في البر والماء.', correct: 'true', explanation_ar: 'البرمائيات تعيش في الماء (شراغيف صغيرة) ثم على اليابسة (ضفادع بالغة).' },
          { type: 'matching', image_url: U.lv08, question_ar: '🔍 انظر إلى الصورة: صِل كل حيوان ببيئته:', pairs_ar: [{ left: 'الجمل', right: 'الصحراء' }, { left: 'الدلفين', right: 'البحر' }, { left: 'القرد', right: 'الغابة' }, { left: 'البطريق', right: 'القطب' }], explanation_ar: 'جمل=صحراء | دلفين=بحر | قرد=غابة | بطريق=قطب.' },
          { type: 'multiple_choice', image_url: U.lv09, question_ar: '🔍 انظر إلى صورة جَمَل: الجمل خلق ليكون صبوراً على العطش لأنه يخزّن:', options_ar: ['الدهن في سنامه', 'الماء في معدته', 'اللحم في رجليه', 'لا شيء'], correct: 0, explanation_ar: 'السنام يخزّن الدهن (لا ماء) الذي يُعطي الجسم طاقة وماءً عند الاحتراق.', golden_rule_ar: '🐫 سنام الجمل = دهن.' },
          { type: 'classify', image_url: U.lv10, question_ar: '🔍 انظر إلى الصورة: صنّف كل حيوان حسب غذائه:', categories_ar: ['لاحم (يأكل لحماً)', 'عاشب (يأكل نباتاً)'], items_ar: ['أسد', 'بقرة', 'ذئب', 'غزال', 'نمر', 'حصان'], correct_categories: [0, 1, 0, 1, 0, 1], explanation_ar: 'لاحم: أسد + ذئب + نمر. عاشب: بقرة + غزال + حصان.' },
          { type: 'multiple_choice', image_url: U.lv11, question_ar: '🔍 انظر إلى صورة دجاجة: الدجاجة تبيض، والبيض يفقس عن:', options_ar: ['كتكوت', 'عجلة', 'سمكة', 'حمل'], correct: 0, explanation_ar: 'الدجاجة تبيض، وبعد 21 يوماً يفقس البيض عن كتاكيت. الطيور عموماً تبيض.', golden_rule_ar: '🐔 دجاجة ← بيض ← كتاكيت.' },
          { type: 'ordering', image_url: U.lv12, question_ar: '🔍 انظر إلى صورة ضفدع: رتّب مراحل نموّ الضفدع:', items_ar: ['بيضة ضفدع', 'شرغوف (حيوان مائي بذيل)', 'ينمو له أرجل أمامية', 'يختفي الذيل', 'ضفدع بالغ'], explanation_ar: 'بيضة ← شرغوف ← أرجل ← اختفاء ذيل ← ضفدع.' },
          { type: 'true_false', image_url: U.lv13, question_ar: '🔍 انظر إلى الصورة: الحيوانات تتنفّس الأكسجين وتُطلق ثاني أكسيد الكربون.', correct: 'true', explanation_ar: 'الحيوانات تتنفّس الأكسجين من الهواء/الماء وتُطلق CO₂. عكس النبات.' },
          { type: 'multiple_choice', image_url: U.lv14, question_ar: '🔍 انظر إلى صورة فراشة: الفراشة قبل أن تصير فراشة كانت:', options_ar: ['يرقة (دودة)', 'بيضة فقط', 'سمكة', 'نبات'], correct: 0, explanation_ar: 'الفراشة تمر بـ4 أطوار: بيضة ← يرقة ← خادرة ← فراشة. هذا ما يُسمّى "التحوّل الكامل".', golden_rule_ar: '🦋 بيضة ← يرقة ← خادرة ← فراشة.' },
          { type: 'classify', image_url: U.lv15, question_ar: '🔍 انظر إلى الصورة: صنّف كل حيوان حسب طريقة تنقّله:', categories_ar: ['يطير', 'يسبح', 'يمشي/يجري'], items_ar: ['صقر', 'دلفين', 'حصان', 'بط', 'سمك', 'فيل'], correct_categories: [0, 1, 2, 0, 1, 2], explanation_ar: 'يطير: صقر + بط. يسبح: دلفين + سمك. يمشي: حصان + فيل.' },
          { type: 'multiple_choice', image_url: U.lv16, question_ar: '🔍 انظر إلى صورة نحل: النحل يُنتج:', options_ar: ['العسل', 'الحليب', 'البيض', 'الصوف'], correct: 0, explanation_ar: 'النحل يجمع رحيق الزهور ويحوّله لعسل في خليّته. ينتج أيضاً الشمع.' },
          { type: 'true_false', image_url: U.lv17, question_ar: '🔍 انظر إلى الصورة: كل الحيوانات تبيض.', correct: 'false', explanation_ar: 'الثديّات لا تبيض — تلد صغاراً حية وترضعها. الطيور والزواحف والأسماك تبيض.' },
          { type: 'multiple_choice', image_url: U.lv18, question_ar: '🔍 انظر إلى صورة حيوانات مفترسة: الحيوانات اللاحمة لها أسنان:', options_ar: ['حادة لتمزيق اللحم', 'مسطّحة لطحن النبات', 'لا أسنان لها', 'صغيرة جداً'], correct: 0, explanation_ar: 'اللاحمة (أسد/ذئب) لها أنياب حادة لتمزيق اللحم. العاشبة لها أسنان طاحنة للنبات.' },
          { type: 'matching', image_url: U.lv19, question_ar: '🔍 انظر إلى الصورة: صِل كل حيوان بطراز تغذّيه:', pairs_ar: [{ left: 'الأسد', right: 'لاحم' }, { left: 'الغزال', right: 'عاشب' }, { left: 'الدب', right: 'قارت (لاحم وعاشب)' }, { left: 'الضفدع', right: 'لاحم حشرات' }], explanation_ar: 'أسد=لاحم | غزال=عاشب | دب=قارت | ضفدع=آكل حشرات.' },
          { type: 'multiple_choice', image_url: U.lv20, question_ar: '🔍 انظر إلى صورة كلب وقط: الحيوانات الأليفة نربّيها لـ:', options_ar: ['الرفقة والحماية', 'إنتاج الكهرباء', 'إنتاج الفاكهة', 'لا فائدة'], correct: 0, explanation_ar: 'الحيوانات الأليفة (كلب/قط/دجاج) تُربّى للرفقة والحماية أو إنتاج البيض واللحم.' },
        ],
      },
      {
        id: 'human_body',
        title_ar: 'جسم الإنسان والصحة',
        title_en: 'Human Body & Health',
        questions: [
          { type: 'multiple_choice', image_url: U.hb01, question_ar: '🔍 انظر إلى صورة طفل: جسم الإنسان مكوّن من:', options_ar: ['رأس وجذع وأطراف', 'جذع فقط', 'رأس فقط', 'أطراف فقط'], correct: 0, explanation_ar: 'جسم الإنسان ثلاثة أجزاء رئيسية: رأس + جذع + أطراف (علوية وسفلية).', golden_rule_ar: '🧒 رأس + جذع + أطراف.' },
          { type: 'multiple_choice', image_url: U.hb02, question_ar: '🔍 انظر إلى صورة طفل يأكل: لنموّ جسم الإنسان نحتاج:', options_ar: ['غذاءً متوازناً وماءً', 'اللعب فقط', 'النوم فقط', 'لا شيء'], correct: 0, explanation_ar: 'الغذاء المتوازن (بروتين + نشويات + خضار + فواكه) + الماء ضروريان للنموّ.', golden_rule_ar: '🍎 غذاء متوازن = نموّ سليم.' },
          { type: 'classify', image_url: U.hb03, question_ar: '🔍 انظر إلى صورة أطعمة: صنّف كل غذاء:', categories_ar: ['غذاء صحي', 'غذاء غير صحي'], items_ar: ['تفاح', 'شيبس', 'جزر', 'حلوى', 'حليب', 'مشروب غازي'], correct_categories: [0, 1, 0, 1, 0, 1], explanation_ar: 'صحي: تفاح + جزر + حليب. غير صحي: شيبس + حلوى + مشروب غازي.' },
          { type: 'multiple_choice', image_url: U.hb04, question_ar: '🔍 انظر إلى صورة طفل يتنفّس: الإنسان يتنفّس عبر:', options_ar: ['الرئتين', 'المعدة', 'القلب', 'الدماغ'], correct: 0, explanation_ar: 'الرئتان يدخلان الأكسجين للجسم ويُخرجان ثاني أكسيد الكربون.', golden_rule_ar: '🫁 رئتان = تنفّس.' },
          { type: 'true_false', image_url: U.hb05, question_ar: '🔍 انظر إلى الصورة: القلب يضخّ الدم لكل الجسم.', correct: 'true', explanation_ar: 'القلب عضلة تضخّ الدم المحمّل بالأكسجين لكل خلايا الجسم بشكل مستمر.' },
          { type: 'multiple_choice', image_url: U.hb06, question_ar: '🔍 انظر إلى صورة دماغ: الدماغ هو:', options_ar: ['مركز التفكير والتحكّم بالجسم', 'مركز ضخّ الدم', 'مركز التنفّس', 'مركز الهضم'], correct: 0, explanation_ar: 'الدماغ يتحكّم بكل وظائف الجسم ويفكّر ويتذكّر ويحسّ.', golden_rule_ar: '🧠 دماغ = تحكّم + تفكير.' },
          { type: 'matching', image_url: U.hb07, question_ar: '🔍 انظر إلى الصورة: صِل كل عضو بوظيفته:', pairs_ar: [{ left: 'القلب', right: 'ضخّ الدم' }, { left: 'الرئتان', right: 'التنفّس' }, { left: 'المعدة', right: 'هضم الطعام' }, { left: 'الدماغ', right: 'التفكير والتحكّم' }], explanation_ar: 'قلب=ضخّ | رئة=تنفّس | معدة=هضم | دماغ=تفكير.' },
          { type: 'multiple_choice', image_url: U.hb08, question_ar: '🔍 انظر إلى صورة طفل ينظف أسنانه: يجب تنظيف الأسنان:', options_ar: ['مرتين يومياً (صباحاً ومساءً)', 'مرة في الشهر', 'لا تنظّف', 'مرة في الأسبوع'], correct: 0, explanation_ar: 'تنظيف الأسنان مرتين يومياً يمنع التسوّس ويحافظ على صحة الفم.', golden_rule_ar: '🪥 أسنان = نظافة مرتين يومياً.' },
          { type: 'classify', image_url: U.hb09, question_ar: '🔍 انظر إلى الصورة: صنّف كل عادة:', categories_ar: ['عادة صحية', 'عادة ضارة'], items_ar: ['غسل اليدين', 'أكل كثير حلوى', 'النوم مبكراً', 'الجلوس أمام الشاشة طويلاً', 'الرياضة', 'شرب مشروبات غازية'], correct_categories: [0, 1, 0, 1, 0, 1], explanation_ar: 'صحية: غسل + نوم + رياضة. ضارة: حلوى + شاشات + غازي.' },
          { type: 'true_false', image_url: U.hb10, question_ar: '🔍 انظر إلى الصورة: النوم لساعات كافية مهم لنموّ الأطفال.', correct: 'true', explanation_ar: 'النوم 8-10 ساعات ضروري لراحة الدماغ ونموّ الجسم عند الأطفال.' },
          { type: 'multiple_choice', image_url: U.hb11, question_ar: '🔍 انظر إلى صورة طفل يلعب رياضة: الرياضة:', options_ar: ['تُقوّي العضلات والعظام', 'تُضعف الجسم', 'لا فائدة منها', 'تُسبب المرض'], correct: 0, explanation_ar: 'الرياضة تُقوّي العضلات والقلب والعظام وتُحسّن المزاج.', golden_rule_ar: '⚽ رياضة = قوّة + صحة.' },
          { type: 'multiple_choice', image_url: U.hb12, question_ar: '🔍 انظر إلى صورة طعام متنوع: الغذاء المتوازن يحتوي على:', options_ar: ['بروتين + نشويات + خضار + فواكه', 'حلوى فقط', 'لحم فقط', 'خبز فقط'], correct: 0, explanation_ar: 'الغذاء المتوازن يضمّ مجموعات غذائية متنوعة لإعطاء الجسم كل احتياجاته.' },
          { type: 'true_false', image_url: U.hb13, question_ar: '🔍 انظر إلى الصورة: شرب الماء بكميات كافية ضروري لصحة الجسم.', correct: 'true', explanation_ar: 'الماء ضروري لكل خلايا الجسم. يجب شرب 6-8 أكواب يومياً.' },
          { type: 'multiple_choice', image_url: U.hb14, question_ar: '🔍 انظر إلى صورة طبيب: عند الشعور بألم يجب:', options_ar: ['إخبار الأهل ومراجعة الطبيب', 'تجاهل الألم', 'أخذ دواء دون استشارة', 'لا شيء'], correct: 0, explanation_ar: 'عند المرض أو الألم يجب إخبار الأهل ومراجعة الطبيب وعدم أخذ أدوية عشوائياً.' },
          { type: 'classify', image_url: U.hb15, question_ar: '🔍 انظر إلى الصورة: صنّف كل عضو:', categories_ar: ['عضو داخلي', 'جزء خارجي'], items_ar: ['القلب', 'الأنف', 'الرئتان', 'اليد', 'المعدة', 'العين'], correct_categories: [0, 1, 0, 1, 0, 1], explanation_ar: 'داخلي: قلب + رئة + معدية. خارجي: أنف + يد + عين.' },
          { type: 'multiple_choice', image_url: U.hb16, question_ar: '🔍 انظر إلى صورة هيكل عظمي: الهيكل العظمي:', options_ar: ['يدعم الجسم ويحمي الأعضاء', 'يضخّ الدم', 'يهضم الطعام', 'لا فائدة له'], correct: 0, explanation_ar: 'الهيكل العظمي (206 عظمة) يدعم الجسم ويحمي الأعضاء (الجمجمة تحمي الدماغ، الأضلع تحمي القلب).', golden_rule_ar: '🦴 هيكل عظمي = دعم + حماية.' },
          { type: 'ordering', image_url: U.hb17, question_ar: '🔍 انظر إلى صورة طعام: رتّب مسار الطعام في الجسم:', items_ar: ['الفم يكسر الطعام', 'ينزل عبر المريء', 'يصل للمعدة للهضم', 'الأمعاء تمتصّ الغذاء', 'الفضلات تخرج'], explanation_ar: 'فم ← مريء ← معدة ← أمعاء ← فضلات.' },
          { type: 'true_false', image_url: U.hb18, question_ar: '🔍 انظر إلى الصورة: العين عضو للرؤية والأذن للسمع.', correct: 'true', explanation_ar: 'العين ترى، الأذن تسمع، الأنف يشتمّ، اللسان يتذوّق، الجلد يحسّ — الحواس الخمس.' },
          { type: 'multiple_choice', image_url: U.hb19, question_ar: '🔍 انظر إلى صورة طفل يغسل يديه: غسل اليدين:', options_ar: ['يمنع انتشار الجراثيم', 'يُسبب المرض', 'لا فائدة', 'يُضعف الجلد'], correct: 0, explanation_ar: 'غسل اليدين بالصابون يقتل الجراثيم ويمنع انتقال الأمراض.', golden_rule_ar: '🧼 غسل اليدين = وقاية من الجراثيم.' },
          { type: 'multiple_choice', image_url: U.hb20, question_ar: '🔍 انظر إلى صورة شمس: ضوء الشمس مفيد لجسم الإنسان لأنه:', options_ar: ['يُساعد على إنتاج فيتامين D', 'يُسبب العمى', 'لا فائدة', 'يُضعف العظام'], correct: 0, explanation_ar: 'ضوء الشمس يُساعد الجسم على إنتاج فيتامين D الضروري لصحة العظام.', golden_rule_ar: '☀️ شمس = فيتامين D + عظام قوية.' },
        ],
      },
    ],
  },
];

export const TOTAL_EXTRA_QUESTIONS = SCIENCE_G3_S2_EXTRA_UNITS.reduce(
  (s, u) => s + u.lessons.reduce((ls, l) => ls + l.questions.length, 0), 0
);