// العلوم - الصف الثاني الابتدائي - الفصل الأول
// الوحدة الثالثة: أرضنا (الفصل الخامس: اليابسة والماء | الفصل السادس: التربة)
// + ملحق جسم الإنسان
import { SCIENCE_EXTRA_1 } from './scienceGrade2S1Bank_Extra';

export const META = {
  title: 'بنك أسئلة العلوم',
  subject: 'العلوم',
  grade: 'الصف الثاني الابتدائي',
  term: 'الفصل الأول',
  publisher: 'وزارة التعليم - المملكة العربية السعودية',
  book: 'العلوم 1447هـ / 2025م',
};

export const UNITS = [
  {
    id: 'unit3',
    title: 'الوحدة الثالثة: أرضنا',
    color: '#d97706',
    icon: '🌍',
    lessons: [
      { id: 'u3l1', title: 'الفصل الخامس — الدرس 1: اليابسة', page: 118, unitId: 'unit3' },
      { id: 'u3l2', title: 'الفصل الخامس — الدرس 2: الماء على الأرض', page: 124, unitId: 'unit3' },
      { id: 'u3l3', title: 'الفصل السادس — الدرس 1: التربة', page: 148, unitId: 'unit3' },
    ],
  },
  {
    id: 'unit4',
    title: 'الوحدة الرابعة: جسم الإنسان',
    color: '#0891b2',
    icon: '🫀',
    lessons: [
      { id: 'u4l1', title: 'الجهاز الهيكلي والعضلي', page: 160, unitId: 'unit4' },
      { id: 'u4l2', title: 'الجهاز الدوراني والتنفسي', page: 162, unitId: 'unit4' },
    ],
  },
];

export const BLOOM_LABELS = {
  remember: 'تذكُّر', understand: 'فهم', apply: 'تطبيق',
  analyze: 'تحليل', create: 'تركيب', evaluate: 'تقويم',
};
export const DIFFICULTY_LABELS = { easy: 'سهل', medium: 'متوسط', hard: 'صعب' };

// ─── الفصل الخامس | الدرس 1: اليابسة ──────────────────────────────────────
const u3l1Qs = [
  {
    id:'u3l1q1', unit:'unit3', lesson:'u3l1', page:118, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'تتكوّن أغلفة الأرض من الغلاف الجوي والغلاف الصخري وأيضاً:',
    paragraph:'تَتَكَوَّنُ الكُرَةُ الأرضيَّةُ مِنَ الغِلافِ الجَوِّيّ والغِلافِ الصَّخريّ والغِلافِ المائيّ. (ص118)',
    options:[
      {text:'الغلاف المائي',correct:true},
      {text:'الغلاف النباتي',correct:false},
      {text:'الغلاف الحيواني',correct:false},
      {text:'الغلاف الرملي',correct:false},
    ],
    explanation:'تتكوّن الأرض من ثلاثة أغلفة رئيسية: الجوي (الهواء) + الصخري (اليابسة) + المائي (الماء).',
    goldenRule:'أغلفة الأرض الثلاثة: جوي + صخري + مائي.',
    feedbackQuestion:{question:'ما الغلاف الذي يمثل اليابسة على سطح الأرض؟',options:[{text:'الغلاف الصخري',correct:true},{text:'الغلاف الجوي',correct:false},{text:'الغلاف المائي',correct:false},{text:'الغلاف الرملي',correct:false}]},
  },
  {
    id:'u3l1q2', unit:'unit3', lesson:'u3l1', page:118, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'الغلاف الصخري هو نسبة اليابسة على الكرة الأرضية وتشكّل جزءاً صغيراً من مساحة الأرض.',
    paragraph:'الغِلافُ الصَّخريُّ: هُوَ نِسبةُ اليابسةِ عَلى الأرضِ وَتُشَكِّلُ جُزءاً صَغيراً مِن مَساحةِ الأرض. (ص118)',
    correctAnswer:true,
    explanation:'اليابسة (الغلاف الصخري) تمثل جزءاً صغيراً من مساحة الأرض مقارنةً بالماء.',
    goldenRule:'اليابسة = الغلاف الصخري = جزء صغير من مساحة الأرض.',
    feedbackQuestion:{question:'أيّ الغلافين أكبر مساحةً على سطح الأرض؟',options:[{text:'الغلاف المائي',correct:true},{text:'الغلاف الصخري',correct:false},{text:'كلاهما متساويان',correct:false},{text:'الغلاف الجوي',correct:false}]},
  },
  {
    id:'u3l1q3', unit:'unit3', lesson:'u3l1', page:118, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف هذه المصطلحات: تنتمي لليابسة أم للماء؟',
    paragraph:'أشكالُ اليابسة: جبل، سهل، وادٍ، تلال. والماء: أنهار، بحيرات، محيطات. (ص118-120)',
    categories:['أشكال اليابسة 🏔','أشكال الماء 💧'],
    items:[
      {text:'الجبل',correct_category:0},
      {text:'النهر',correct_category:1},
      {text:'السهل',correct_category:0},
      {text:'المحيط',correct_category:1},
      {text:'الوادي',correct_category:0},
      {text:'البحيرة',correct_category:1},
    ],
    explanation:'يابسة: جبل، سهل، وادٍ. ماء: نهر، محيط، بحيرة.',
    goldenRule:'أشكال اليابسة: جبل + سهل + وادٍ + تلال. أشكال الماء: نهر + بحيرة + محيط.',
  },
  {
    id:'u3l1q4', unit:'unit3', lesson:'u3l1', page:119, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'الجبلُ منطقةٌ مرتفعة من اليابسة، وتكون للجبال قمم:',
    paragraph:'الجَبَلُ مِنطَقةٌ مُرتَفِعةٌ مِنَ اليابِسة. قَد يَكونُ للجِبالِ قِمَمٌ حادَّة، وجوانِبُ شديدةُ الانحِدار. (ص119)',
    options:[
      {text:'حادة وجوانبه شديدة الانحدار',correct:true},
      {text:'مسطحة وجوانبه ناعمة',correct:false},
      {text:'مائية من الجهتين',correct:false},
      {text:'منخفضة وواسعة',correct:false},
    ],
    explanation:'الجبل منطقة مرتفعة ذات قمم حادة وجوانب شديدة الانحدار.',
    goldenRule:'الجبل = مرتفع + قمم حادة + جوانب شديدة الانحدار.',
    feedbackQuestion:{question:'ما الفرق بين الجبل والتل؟',options:[{text:'التل أقل ارتفاعاً من الجبل',correct:true},{text:'الجبل أقل ارتفاعاً من التل',correct:false},{text:'كلاهما بنفس الارتفاع',correct:false},{text:'لا فرق بينهما',correct:false}]},
  },
  {
    id:'u3l1q5', unit:'unit3', lesson:'u3l1', page:119, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'الوادي أرض منخفضة تقع بين الجبال والتلال.',
    paragraph:'الوادي أرضٌ مُنخفِضةٌ بَينَ الجِبالِ والتِّلال. (ص119)',
    correctAnswer:true,
    explanation:'الوادي هو المنطقة المنخفضة التي تقع بين الجبال والتلال.',
    goldenRule:'الوادي = أرض منخفضة بين الجبال والتلال.',
    feedbackQuestion:{question:'أين يقع الوادي؟',options:[{text:'بين الجبال والتلال',correct:true},{text:'فوق الجبال',correct:false},{text:'في قاع البحر',correct:false},{text:'على الساحل',correct:false}]},
  },
  {
    id:'u3l1q6', unit:'unit3', lesson:'u3l1', page:119, type:'ordering',
    bloom:'apply', difficulty:'medium',
    question:'رتّب أشكال اليابسة من الأعلى ارتفاعاً إلى الأقل:',
    paragraph:'الجَبَلُ مُرتَفِعٌ ذو قِمَم حادة. التِّلالُ مُرتَفِعةٌ أَقلُّ من الجِبال. السَّهلُ مُنبَسِطٌ واسِع. الوادي مُنخَفِض. (ص119)',
    items:['السهل المنبسط','الجبل','التلال','الوادي'],
    correctOrder:[1,2,0,3],
    explanation:'من الأعلى للأقل: جبل ← تلال ← سهل ← وادٍ.',
    goldenRule:'ترتيب الارتفاع: جبل > تلال > سهل > وادٍ.',
  },
  {
    id:'u3l1q7', unit:'unit3', lesson:'u3l1', page:120, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'الكرة الجغرافية تمثّل نموذجاً للأرض، وهي خريطة على شكل:',
    paragraph:'يُمَثِّلُ مُجَسَّمُ الكُرةِ الجُغرافيَّةِ نَموذَجاً للأرض، وَهِيَ خَريطةٌ عَلى شَكلِ كُرةٍ. (ص120)',
    options:[
      {text:'كرة مستديرة',correct:true},
      {text:'مستطيل مسطح',correct:false},
      {text:'مثلث',correct:false},
      {text:'أسطوانة',correct:false},
    ],
    explanation:'الكرة الجغرافية نموذج مجسّم للأرض بشكل كروي يُبيّن اليابسة والماء.',
    goldenRule:'الكرة الجغرافية = خريطة كروية تُظهر اليابسة والماء على الأرض.',
    feedbackQuestion:{question:'ماذا تُظهر الكرة الجغرافية؟',options:[{text:'أشكال اليابسة والماء على الأرض',correct:true},{text:'درجات الحرارة فقط',correct:false},{text:'الطقس اليومي',correct:false},{text:'مسارات الطائرات',correct:false}]},
  },
  {
    id:'u3l1q8', unit:'unit3', lesson:'u3l1', page:121, type:'matching',
    bloom:'remember', difficulty:'medium',
    question:'صِل كل شكل من أشكال اليابسة بوصفه المناسب:',
    paragraph:'الجبل / السهل / التلال / الوادي. (ص119-121)',
    pairs:[
      {left:'الجبل',right:'منطقة مرتفعة ذات قمم حادة'},
      {left:'السهل',right:'منطقة منبسطة وواسعة'},
      {left:'التلال',right:'مناطق مرتفعة أقل من الجبال'},
      {left:'الوادي',right:'أرض منخفضة بين الجبال والتلال'},
    ],
    explanation:'جبل=مرتفع قمم حادة. سهل=منبسط. تلال=مرتفع أقل من الجبال. وادٍ=منخفض.',
    goldenRule:'أربعة أشكال رئيسية لليابسة: جبل + سهل + تلال + وادٍ.',
  },
];

// ─── الفصل الخامس | الدرس 2: الماء على الأرض ──────────────────────────────
const u3l2Qs = [
  {
    id:'u3l2q1', unit:'unit3', lesson:'u3l2', page:124, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'الماء العذب هو ماء غير مالح نستخدمه في الشرب والطبخ، ويوجد في:',
    paragraph:'الماءُ العَذبُ: ماءٌ غَيرُ مالِح نَستَخدِمُهُ في الشُّربِ والطَّبخ، وَيُوجَدُ في الأنهارِ وَالأوديةِ وَبَعضِ البُحيراتِ. (ص115)',
    options:[
      {text:'الأنهار والأودية وبعض البحيرات',correct:true},
      {text:'البحار والمحيطات فقط',correct:false},
      {text:'الهواء فقط',correct:false},
      {text:'الجبال فقط',correct:false},
    ],
    explanation:'الماء العذب غير مالح يوجد في الأنهار والأودية وبعض البحيرات.',
    goldenRule:'الماء العذب = غير مالح = أنهار + أودية + بعض البحيرات.',
    feedbackQuestion:{question:'أين نجد الماء العذب على الأرض؟',options:[{text:'في الأنهار والبحيرات',correct:true},{text:'في المحيطات فقط',correct:false},{text:'في الهواء فقط',correct:false},{text:'في الصحراء',correct:false}]},
  },
  {
    id:'u3l2q2', unit:'unit3', lesson:'u3l2', page:126, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'المحيط تجمّع كبير وعميق من الماء المالح.',
    paragraph:'المُحيطُ: تَجَمُّعٌ كَبيرٌ وَعَميقٌ مِنَ الماءِ المالِح. (ص115)',
    correctAnswer:true,
    explanation:'المحيط هو التجمع الأكبر والأعمق للماء المالح على سطح الأرض.',
    goldenRule:'المحيط = تجمع كبير وعميق من الماء المالح — يغطي معظم سطح الأرض.',
    feedbackQuestion:{question:'ما الفرق بين الماء العذب والماء المالح؟',options:[{text:'العذب يُشرب والمالح لا يُشرب',correct:true},{text:'كلاهما صالح للشرب',correct:false},{text:'لا فرق',correct:false},{text:'العذب أكثر من المالح',correct:false}]},
  },
  {
    id:'u3l2q3', unit:'unit3', lesson:'u3l2', page:126, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف: ماء عذب أم ماء مالح؟',
    paragraph:'الماء العذب: أنهار + بحيرات عذبة. الماء المالح: بحار + محيطات. (ص115-126)',
    categories:['ماء عذب 💧','ماء مالح 🌊'],
    items:[
      {text:'نهر النيل',correct_category:0},
      {text:'المحيط الهادئ',correct_category:1},
      {text:'بحيرة الجليد القطبية',correct_category:0},
      {text:'البحر الأحمر',correct_category:1},
      {text:'الجدول في الجبال',correct_category:0},
      {text:'المحيط الهندي',correct_category:1},
    ],
    explanation:'عذب: أنهار، بحيرات، جداول. مالح: بحار ومحيطات.',
    goldenRule:'ماء عذب في الأنهار والبحيرات. ماء مالح في البحار والمحيطات.',
  },
  {
    id:'u3l2q4', unit:'unit3', lesson:'u3l2', page:126, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'قال تعالى: ﴿وَجَعَلْنَا مِنَ الْمَاءِ كُلَّ شَيْءٍ حَيٍّ﴾. تدل هذه الآية على أن:',
    paragraph:'قالَ تَعالى: ﴿وَجَعَلْنَا مِنَ الْمَاءِ كُلَّ شَيْءٍ حَيٍّ﴾ الأنبياء:30. (ص126)',
    options:[
      {text:'الماء أساس الحياة لكل الكائنات',correct:true},
      {text:'الماء يوجد في الفضاء فقط',correct:false},
      {text:'الماء لا يهم الكائنات الحية',correct:false},
      {text:'الماء يُنتج من الهواء',correct:false},
    ],
    explanation:'الآية الكريمة تؤكد أن الماء أصل الحياة — لا تعيش الكائنات الحية بدونه.',
    goldenRule:'﴿وَجَعَلْنَا مِنَ الْمَاءِ كُلَّ شَيْءٍ حَيٍّ﴾ — الماء = أساس الحياة.',
    feedbackQuestion:{question:'ما معنى قوله تعالى: "وجعلنا من الماء كل شيء حي"؟',options:[{text:'الماء ضروري لكل الكائنات الحية',correct:true},{text:'الماء يُصنع من الهواء',correct:false},{text:'الكائنات لا تحتاج ماءً',correct:false},{text:'الماء موجود في النجوم فقط',correct:false}]},
  },
  {
    id:'u3l2q5', unit:'unit3', lesson:'u3l2', page:126, type:'trueFalse',
    bloom:'understand', difficulty:'medium',
    question:'الماء العذب تشكّل النسبة الأقل من مياه الأرض.',
    paragraph:'نِسبةُ المياهِ العَذبةِ عَلى سَطحِ الأرضِ أَقلُّ مِن نِسبةِ المياهِ المالِحة. (ص126)',
    correctAnswer:true,
    explanation:'الماء المالح (البحار والمحيطات) يشكّل الجزء الأكبر، والماء العذب نسبته قليلة جداً.',
    goldenRule:'الماء العذب نسبة قليلة جداً على الأرض — حافظ عليه ولا تبذّره.',
    feedbackQuestion:{question:'أيّ نوعي الماء أكثر على سطح الأرض؟',options:[{text:'الماء المالح',correct:true},{text:'الماء العذب',correct:false},{text:'كلاهما متساويان',correct:false},{text:'لا يوجد فرق',correct:false}]},
  },
  {
    id:'u3l2q6', unit:'unit3', lesson:'u3l2', page:125, type:'fillBlank',
    bloom:'remember', difficulty:'easy',
    question:'أكمل: "تنقسم مياه الأرض إلى مياه ___ ومياه ___ ".',
    paragraph:'تَنقَسِمُ المِياهُ عَلى الأرضِ إلى مِياهٍ عَذبةٍ وَمِياهٍ مالِحة. (ص126)',
    blanks:['عذبة','مالحة'],
    wordBank:['عذبة','مالحة','جوفية','سطحية'],
    explanation:'مياه الأرض قسمان: عذبة (للشرب والزراعة) ومالحة (البحار والمحيطات).',
    goldenRule:'مياه الأرض نوعان: عذبة (للشرب) + مالحة (بحار ومحيطات).',
  },
  {
    id:'u3l2q7', unit:'unit3', lesson:'u3l2', page:125, type:'trueFalse',
    bloom:'apply', difficulty:'medium',
    question:'الحيوانات والنباتات لا تستطيع العيش من دون ماء.',
    paragraph:'لا تَستَطيعُ المَخلوقاتُ الحَيَّةُ العَيشَ مِن دونِ ماء. (ص126)',
    correctAnswer:true,
    explanation:'الماء ضروري لجميع الكائنات الحية — بدونه تموت.',
    goldenRule:'الكائنات الحية لا تعيش بلا ماء — الماء = الحياة.',
    feedbackQuestion:{question:'ماذا يحدث للكائن الحي إذا لم يحصل على ماء؟',options:[{text:'يموت',correct:true},{text:'يعيش بشكل طبيعي',correct:false},{text:'يتحول لكائن آخر',correct:false},{text:'ينام فقط',correct:false}]},
  },
  {
    id:'u3l2q8', unit:'unit3', lesson:'u3l2', page:125, type:'ordering',
    bloom:'apply', difficulty:'medium',
    question:'رتّب استخدامات الماء اليومية من أكثرها شيوعاً في الكتاب:',
    paragraph:'فيمَ يَستَخدِمُ النَّاسُ الماءَ يَومِيَّاً؟ أعمَلُ قائمةً. (ص125) — الشرب / غسل الصحون / الوضوء / السباحة.',
    items:['السباحة','الشرب','الوضوء','غسل الصحون'],
    correctOrder:[1,2,3,0],
    explanation:'الترتيب الأكثر أهمية: شرب ← وضوء ← غسل ← سباحة.',
    goldenRule:'أهم استخدامات الماء: الشرب + الوضوء + الطهي + النظافة.',
  },
];

// ─── الفصل السادس | الدرس 1: التربة ───────────────────────────────────────
const u3l3Qs = [
  {
    id:'u3l3q1', unit:'unit3', lesson:'u3l3', page:148, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'التربة خليط من فتات الصخور وقطع صغيرة من بقايا:',
    paragraph:'التُّربةُ خَليطٌ مِن فُتاتِ الصُّخورِ، وَقِطَعٍ صَغيرةٍ مِن بَقايا النَّباتاتِ وَالحيواناتِ المَيِّتة. (ص148)',
    options:[
      {text:'النباتات والحيوانات الميتة',correct:true},
      {text:'الماء والهواء فقط',correct:false},
      {text:'الرمال الذهبية فقط',correct:false},
      {text:'الحديد والصلب',correct:false},
    ],
    explanation:'التربة = فتات صخور + بقايا نباتات وحيوانات ميتة متحللة.',
    goldenRule:'التربة = فتات صخور + بقايا نباتات وحيوانات ميتة.',
    feedbackQuestion:{question:'ما مكوّنات التربة الرئيسية؟',options:[{text:'فتات صخور + بقايا نباتات وحيوانات',correct:true},{text:'ماء وهواء فقط',correct:false},{text:'رمال وملح',correct:false},{text:'معادن وذهب',correct:false}]},
  },
  {
    id:'u3l3q2', unit:'unit3', lesson:'u3l3', page:149, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'التربة الداكنة اللون تحتفظ بالماء أكثر من التربة الفاتحة.',
    paragraph:'التُّربةُ الدَّاكِنةُ تَحتَفِظُ بِالماءِ أَكثَر. بَعضُ أنواعِ التُّربةِ نَاعِمٌ، وَبَعضُها الآخَرُ خَشِنٌ. (ص149)',
    correctAnswer:true,
    explanation:'التربة الداكنة تحتوي على مادة عضوية أكثر لذا تحتفظ بالماء أكثر.',
    goldenRule:'التربة الداكنة = تحتفظ بالماء أكثر = أفضل للزراعة.',
    feedbackQuestion:{question:'أيّ التربتين أفضل للزراعة: الداكنة أم الفاتحة؟',options:[{text:'الداكنة لأنها تحتفظ بالماء أكثر',correct:true},{text:'الفاتحة لأنها أجمل',correct:false},{text:'كلاهما متساويتان',correct:false},{text:'لا فرق',correct:false}]},
  },
  {
    id:'u3l3q3', unit:'unit3', lesson:'u3l3', page:148, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'التربة السطحية هي الطبقة العليا من التربة وتُعدّ الأفضل للزراعة لأنها:',
    paragraph:'هَذِهِ الطَّبَقةُ مِنَ التُّربةِ تُسَمَّى التُّربةَ السَّطحيَّة. إِنَّها الأَفضَلُ لِنُمُوِّ النَّباتات؛ لأنَّها تَحتَوي على بَقايا نَباتاتٍ وحَيواناتٍ مُتَحَلِّلة. (ص150)',
    options:[
      {text:'تحتوي على بقايا نباتات وحيوانات متحللة',correct:true},
      {text:'ألوانها جميلة',correct:false},
      {text:'تحتوي على حديد',correct:false},
      {text:'خالية من الديدان',correct:false},
    ],
    explanation:'التربة السطحية تحتوي على مواد عضوية متحللة تجعلها خصبة لنمو النباتات.',
    goldenRule:'التربة السطحية = الأفضل للزراعة = تحتوي على مواد عضوية متحللة.',
    feedbackQuestion:{question:'لماذا تُعدّ التربة السطحية أفضل للزراعة؟',options:[{text:'لاحتوائها على مواد عضوية متحللة',correct:true},{text:'لأنها خالية من الرطوبة',correct:false},{text:'لأنها كثيفة جداً',correct:false},{text:'لاحتوائها على حديد',correct:false}]},
  },
  {
    id:'u3l3q4', unit:'unit3', lesson:'u3l3', page:149, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف أنواع التربة:',
    paragraph:'أنواعُ التُّربة: طينيَّة + رمليَّة + زراعيَّة (سَطحيَّة). (ص149)',
    categories:['تربة ناعمة الملمس','تربة خشنة الملمس'],
    items:[
      {text:'التربة الطينية',correct_category:0},
      {text:'التربة الرملية',correct_category:1},
      {text:'التربة الزراعية السطحية',correct_category:0},
      {text:'التربة الحصوية',correct_category:1},
    ],
    explanation:'ناعمة: طينية وزراعية. خشنة: رملية وحصوية.',
    goldenRule:'التربة الطينية ناعمة تحتفظ بالماء. التربة الرملية خشنة لا تحتفظ بالماء.',
  },
  {
    id:'u3l3q5', unit:'unit3', lesson:'u3l3', page:150, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'التربة تحتاج وقتاً طويلاً لتتكوّن حتى تتفتّت الصخور والمعادن.',
    paragraph:'تَحتاجُ التُّربةُ إلى وَقتٍ طَويلٍ لِتَتَكَوَّن؛ حَيثُ تَتَفَتَّتُ الصُّخورُ وَالمَعادِنُ إِلى قِطَعٍ أَصغَر. (ص150)',
    correctAnswer:true,
    explanation:'تكوّن التربة عملية تستغرق آلاف السنين من تفتت الصخور وتحلل المواد العضوية.',
    goldenRule:'التربة نعمة تستغرق آلاف السنين لتتكوّن — حافظ عليها.',
    feedbackQuestion:{question:'لماذا يجب الحفاظ على التربة؟',options:[{text:'لأنها تحتاج وقتاً طويلاً لتتكوّن',correct:true},{text:'لأنها غالية الثمن في السوق',correct:false},{text:'لأن لها لوناً جميلاً',correct:false},{text:'لا يجب الحفاظ عليها',correct:false}]},
  },
  {
    id:'u3l3q6', unit:'unit3', lesson:'u3l3', page:150, type:'matching',
    bloom:'understand', difficulty:'medium',
    question:'صِل كل نوع تربة بمكانها الطبيعي:',
    paragraph:'أنواع التربة: رملية / طينية / زراعية. (ص149)',
    pairs:[
      {left:'تربة رملية',right:'الصحراء'},
      {left:'تربة طينية',right:'الأراضي قرب الأنهار'},
      {left:'التربة السطحية',right:'الطبقة العليا الخصبة'},
      {left:'التربة تحت السطحية',right:'الطبقة تحت السطحية الداكنة'},
    ],
    explanation:'رملية في الصحراء. طينية قرب الأنهار. السطحية = الطبقة الخصبة.',
    goldenRule:'الصحراء: رمل. الأنهار: طين. الطبقة العليا: سطحية خصبة.',
  },
  {
    id:'u3l3q7', unit:'unit3', lesson:'u3l3', page:154, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'النسبة الأكبر من الصخور التي جمعتها سمر كانت:',
    paragraph:'رَسَمَت سُمَرُ نُورةٌ رَسماً بَيانيَّاً لِلصُّخورِ الَّتي جَمَعَتها مِن حَديقةِ مَنزِلِها. أَيُّ العِباراتِ الآتيةِ تَصِفُ الصُّخورَ التي جَمَعَتها؟ خَمسُ صُخورٍ ناعِمةُ المَلمَس. (ص154)',
    options:[
      {text:'خمس صخور ناعمة الملمس',correct:true},
      {text:'ثماني صخور خشنة الملمس',correct:false},
      {text:'ثلاث صخور طريّة',correct:false},
      {text:'تسع صخور قاسية',correct:false},
    ],
    explanation:'من الرسم البياني: أكثر الصخور ناعمة الملمس (5 صخور).',
    goldenRule:'الصخور تختلف في الملمس: ناعمة / خشنة / قاسية — صنّفها بالملاحظة.',
    feedbackQuestion:{question:'كيف نصنّف الصخور؟',options:[{text:'بالملمس واللون والحجم',correct:true},{text:'بالاسم فقط',correct:false},{text:'بالثقل فقط',correct:false},{text:'لا نصنّفها',correct:false}]},
  },
  {
    id:'u3l3q8', unit:'unit3', lesson:'u3l3', page:158, type:'trueFalse',
    bloom:'analyze', difficulty:'medium',
    question:'الطبقة التي تُعدّ الأفضل لنمو النباتات تحتوي على بقايا نباتات وحيوانات متحللة وهي التربة السطحية.',
    paragraph:'تُعَدُّ هَذِهِ الطَّبَقةُ مِنَ التُّربةِ الأَفضَلَ لِنُمُوِّ النَّباتات؛ لأنَّها تَحتَوي على بَقايا نَباتاتٍ وَحيواناتٍ مُتَحَلِّلة. (ص158)',
    correctAnswer:true,
    explanation:'التربة السطحية هي الطبقة الخصبة الغنية بالمواد العضوية المتحللة.',
    goldenRule:'التربة السطحية = الطبقة الخصبة = أفضل للنباتات.',
    feedbackQuestion:{question:'أيّ طبقات التربة هي الأفضل للزراعة؟',options:[{text:'التربة السطحية',correct:true},{text:'التربة تحت السطحية',correct:false},{text:'طبقة الصخور الأساسية',correct:false},{text:'كل الطبقات متساوية',correct:false}]},
  },
];

// ─── جسم الإنسان | الجهاز الهيكلي والعضلي ────────────────────────────────
const u4l1Qs = [
  {
    id:'u4l1q1', unit:'unit4', lesson:'u4l1', page:160, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'يتكوّن الجهاز الهيكلي من أجزاء صلبة داخل الجسم تُسمّى:',
    paragraph:'الجِهازُ الهَيكَليُّ يَتَكَوَّنُ مِن أَجزاءٍ صُلبةٍ داخِلَ الجِسمِ تُسَمَّى العِظام. (ص160)',
    options:[
      {text:'العظام',correct:true},
      {text:'العضلات',correct:false},
      {text:'الأعصاب',correct:false},
      {text:'الأوردة',correct:false},
    ],
    explanation:'الجهاز الهيكلي يتكوّن من العظام التي تشكّل الهيكل الداخلي للجسم.',
    goldenRule:'الجهاز الهيكلي = العظام — تُعطي الجسم شكله وتُساعدنا على الحركة.',
    feedbackQuestion:{question:'ما وظيفة الجهاز الهيكلي؟',options:[{text:'يُعطي الجسم شكله ويُساعد على الحركة',correct:true},{text:'ينقل الدم في الجسم',correct:false},{text:'يُساعد على التنفس',correct:false},{text:'يُرسل الرسائل للدماغ',correct:false}]},
  },
  {
    id:'u4l1q2', unit:'unit4', lesson:'u4l1', page:160, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'العظام تُعطي أجسامنا شكلها وتُساعدنا على الوقوف معتدلين.',
    paragraph:'العِظامُ تُعطي أَجسامَنا شَكلَها، وَتُساعِدُنا على الوُقوفِ مُعتَدِلين. (ص160)',
    correctAnswer:true,
    explanation:'العظام مسؤولة عن منح الجسم شكله وتمكين الوقوف الاعتدالي.',
    goldenRule:'العظام = الشكل + الاعتدال + الحركة.',
    feedbackQuestion:{question:'بدون عظام ماذا سيحدث لجسمنا؟',options:[{text:'سيسقط ولا يستطيع الوقوف',correct:true},{text:'سيكون أسرع',correct:false},{text:'سيكون أقوى',correct:false},{text:'لا فرق',correct:false}]},
  },
  {
    id:'u4l1q3', unit:'unit4', lesson:'u4l1', page:161, type:'matching',
    bloom:'remember', difficulty:'medium',
    question:'صِل كل جزء بوصفه في الجهاز الهيكلي:',
    paragraph:'أجزاء الجهاز الهيكلي: عظام الجمجمة / العمود الفقري / عظام اليد / عظام الرجل. (ص160)',
    pairs:[
      {left:'عظام الجمجمة',right:'تحمي الدماغ'},
      {left:'العمود الفقري',right:'يدعم الظهر والرقبة'},
      {left:'عظام اليد',right:'تُساعد على الإمساك'},
      {left:'عظام الرجل',right:'تُساعد على المشي والجري'},
    ],
    explanation:'الجمجمة: تحمي الدماغ. العمود: يدعم الظهر. يد: إمساك. رجل: مشي.',
    goldenRule:'كل عظمة لها وظيفة: الجمجمة تحمي الدماغ. العمود يدعم الظهر.',
  },
  {
    id:'u4l1q4', unit:'unit4', lesson:'u4l1', page:161, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'العضلات هي أجزاء الجسم التي تُساعدنا على:',
    paragraph:'العَضَلاتُ هِيَ أَجزاءُ الجِسمِ الَّتي تُساعِدُنا على الحَرَكة. (ص161)',
    options:[
      {text:'الحركة',correct:true},
      {text:'التنفس فقط',correct:false},
      {text:'الهضم فقط',correct:false},
      {text:'النوم فقط',correct:false},
    ],
    explanation:'العضلات هي المحرّكات للجسم — بها يستطيع الإنسان الحركة في كل اتجاه.',
    goldenRule:'العضلات = أداة الحركة في الجسم — وتتقوى بالرياضة.',
    feedbackQuestion:{question:'كيف نُقوّي عضلاتنا؟',options:[{text:'بممارسة التمارين الرياضية',correct:true},{text:'بالنوم الكثير',correct:false},{text:'بالجلوس الطويل',correct:false},{text:'بالأكل فقط',correct:false}]},
  },
  {
    id:'u4l1q5', unit:'unit4', lesson:'u4l1', page:161, type:'trueFalse',
    bloom:'apply', difficulty:'easy',
    question:'مُمارسة التمارين الرياضية تُقوّي العضلات.',
    paragraph:'مُمارَسةُ التَّمارينِ الرِّياضيَّةِ تُقَوِّي العَضَلات. (ص161)',
    correctAnswer:true,
    explanation:'الرياضة المنتظمة تُنشّط العضلات وتُقوّيها.',
    goldenRule:'الرياضة تُقوّي العضلات — مارسها يومياً لجسم قوي صحيح.',
    feedbackQuestion:{question:'ما فائدة الرياضة للجهاز العضلي؟',options:[{text:'تُقوّي العضلات',correct:true},{text:'لا فائدة منها',correct:false},{text:'تُضعف العضلات',correct:false},{text:'تُبطئ الحركة',correct:false}]},
  },
  {
    id:'u4l1q6', unit:'unit4', lesson:'u4l1', page:161, type:'ordering',
    bloom:'apply', difficulty:'medium',
    question:'رتّب هذه الخطوات للحفاظ على الجهاز الهيكلي من الأهم:',
    paragraph:'كيفَ أُحافِظُ على عِظامي سَليمةً قَويَّة؟ (ص160)',
    items:['ارتداء الواقي عند اللعب','تناول الأطعمة الغنية بالكالسيوم','الإكثار من الحركة والرياضة','الحصول على قسط كافٍ من النوم'],
    correctOrder:[1,2,0,3],
    explanation:'الترتيب: كالسيوم ← رياضة ← واقٍ ← نوم.',
    goldenRule:'لعظام قوية: كالسيوم + رياضة + حماية + نوم.',
  },
  {
    id:'u4l1q7', unit:'unit4', lesson:'u4l1', page:161, type:'multipleChoice',
    bloom:'analyze', difficulty:'medium',
    question:'عندما نقفز إلى أعلى وإلى أسفل نستخدم عضلات:',
    paragraph:'أَقفِزُ إلى أَعلى وَإلى أَسفَل. أَيُّ العَضَلاتِ استَخدَمتُ؟ (ص161)',
    options:[
      {text:'عضلات الرجل',correct:true},
      {text:'عضلات الوجه',correct:false},
      {text:'عضلات اليد',correct:false},
      {text:'عضلات البطن فقط',correct:false},
    ],
    explanation:'القفز يستخدم بشكل رئيسي عضلات الرجل (الفخذ والساق).',
    goldenRule:'عضلات الرجل = للقفز والمشي والجري. عضلات اليد = للإمساك.',
    feedbackQuestion:{question:'أيّ عضلات نستخدم عند الرمي؟',options:[{text:'عضلات اليد والذراع',correct:true},{text:'عضلات الرجل',correct:false},{text:'عضلات الوجه',correct:false},{text:'عضلات البطن فقط',correct:false}]},
  },
  {
    id:'u4l1q8', unit:'unit4', lesson:'u4l1', page:161, type:'trueFalse',
    bloom:'evaluate', difficulty:'medium',
    question:'الجهاز العضلي والجهاز الهيكلي يعملان معاً لمساعدتنا على الحركة.',
    paragraph:'يَعمَلُ الجِهازُ الهَيكَليُّ والجِهازُ العَضَليُّ مَعاً لِمُساعَدَتِنا على الحَرَكة. (ص161)',
    correctAnswer:true,
    explanation:'العظام والعضلات شريكان: العضلات تتحرك على العظام فتُنتج الحركة.',
    goldenRule:'عظام + عضلات = حركة كاملة — كلاهما يعملان معاً.',
    feedbackQuestion:{question:'ما الذي يحدث إذا كانت العظام قوية لكن العضلات ضعيفة؟',options:[{text:'تكون الحركة صعبة ومحدودة',correct:true},{text:'تكون الحركة أسرع',correct:false},{text:'لا تأثير',correct:false},{text:'تكون الحركة طبيعية',correct:false}]},
  },
];

// ─── جسم الإنسان | الجهاز الدوراني والتنفسي ──────────────────────────────
const u4l2Qs = [
  {
    id:'u4l2q1', unit:'unit4', lesson:'u4l2', page:162, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'الجهاز الدوراني يتكوّن من القلب والشرايين والأوردة. وظيفته:',
    paragraph:'يَنتَقِلُ الدَّمُ خِلالَ أَجسامِنا؛ حَيثُ يَضُخُّ القَلبُ الدَّمَ إلى جَميعِ أَجزاءِ الجِسمِ عَبرَ أَنابيبَ تُسَمَّى الأَوعيةَ الدَّمويَّة. (ص162)',
    options:[
      {text:'ضخّ الدم لجميع أجزاء الجسم',correct:true},
      {text:'تنظيف الهواء',correct:false},
      {text:'هضم الطعام',correct:false},
      {text:'تحريك العضلات',correct:false},
    ],
    explanation:'الجهاز الدوراني يضخّ الدم عبر القلب والأوعية الدموية لجميع أجزاء الجسم.',
    goldenRule:'الجهاز الدوراني = القلب + الشرايين + الأوردة = ضخّ الدم للجسم كله.',
    feedbackQuestion:{question:'ما عضو الضخّ الرئيسي في الجهاز الدوراني؟',options:[{text:'القلب',correct:true},{text:'الرئتان',correct:false},{text:'الكبد',correct:false},{text:'المعدة',correct:false}]},
  },
  {
    id:'u4l2q2', unit:'unit4', lesson:'u4l2', page:162, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'الشرايين تحمل الدم من القلب إلى الجسم، والأوردة تعيده من الجسم للقلب.',
    paragraph:'الشَّرايينُ والأَوردةُ أَنابيبُ تُسَمَّى الأَوعيةَ الدَّمويَّة. (ص162)',
    correctAnswer:true,
    explanation:'الشرايين تحمل الدم المحمّل بالأكسجين من القلب للجسم، والأوردة تعيد الدم للقلب.',
    goldenRule:'شرايين: من القلب للجسم. أوردة: من الجسم للقلب.',
    feedbackQuestion:{question:'ما وظيفة الأوردة في الجهاز الدوراني؟',options:[{text:'إعادة الدم من الجسم للقلب',correct:true},{text:'حمل الدم من القلب للجسم',correct:false},{text:'تصفية الدم',correct:false},{text:'إنتاج الدم',correct:false}]},
  },
  {
    id:'u4l2q3', unit:'unit4', lesson:'u4l2', page:162, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'الجهاز التنفسي يتكوّن من الأنف والفم والقصبة الهوائية والرئتين، ووظيفته:',
    paragraph:'يَقومُ الجِهازُ التَّنفُسيُّ بِعَمَليَّتَي الشَّهيقِ والزَّفيرِ اللَّتَي تُساعِدانِ على دُخولِ غازِ الأُكسيسِجينِ الضَّروريِّ إلى أَجسامِنا. (ص162)',
    options:[
      {text:'إدخال الأكسجين وإخراج ثاني أكسيد الكربون',correct:true},
      {text:'هضم الطعام',correct:false},
      {text:'ضخّ الدم',correct:false},
      {text:'تحريك العضلات',correct:false},
    ],
    explanation:'الجهاز التنفسي يدخل الأكسجين بالشهيق ويُخرج ثاني أكسيد الكربون بالزفير.',
    goldenRule:'الجهاز التنفسي: شهيق (أكسجين داخل) + زفير (ثاني أكسيد الكربون خارج).',
    feedbackQuestion:{question:'ما الغاز الذي نُخرجه عند الزفير؟',options:[{text:'ثاني أكسيد الكربون',correct:true},{text:'الأكسجين',correct:false},{text:'النيتروجين',correct:false},{text:'الهيليوم',correct:false}]},
  },
  {
    id:'u4l2q4', unit:'unit4', lesson:'u4l2', page:162, type:'matching',
    bloom:'remember', difficulty:'medium',
    question:'صِل كل جزء بالجهاز الذي ينتمي إليه:',
    paragraph:'الجهاز الدوراني / الجهاز التنفسي / الجهاز العصبي / الجهاز الهيكلي. (ص160-162)',
    pairs:[
      {left:'القلب والأوعية الدموية',right:'الجهاز الدوراني'},
      {left:'الرئتان والقصبة الهوائية',right:'الجهاز التنفسي'},
      {left:'الدماغ والأعصاب',right:'الجهاز العصبي'},
      {left:'العظام والمفاصل',right:'الجهاز الهيكلي'},
    ],
    explanation:'دوراني: قلب + أوعية. تنفسي: رئتان + قصبة. عصبي: دماغ + أعصاب. هيكلي: عظام.',
    goldenRule:'أجهزة الجسم: دوراني + تنفسي + عصبي + هيكلي + عضلي — تعمل معاً.',
  },
  {
    id:'u4l2q5', unit:'unit4', lesson:'u4l2', page:162, type:'trueFalse',
    bloom:'apply', difficulty:'easy',
    question:'بعد ممارسة الرياضة يزيد معدل ضربات القلب لضخّ المزيد من الدم للعضلات.',
    paragraph:'مَا عَدَدُ ضَرَباتِ قَلبِي في الدَّقيقَة؟ أُحاوِلُ أَن أَعُدَّها. أَعُدُّ كَم مَرَّةً أَتَنَفَّسُ في الدَّقيقة، ثُمَّ أَقفِزُ عَشرَ مَرَّات. (ص162)',
    correctAnswer:true,
    explanation:'بعد القفز والتمرين يزيد معدل ضربات القلب لتوفير الأكسجين للعضلات.',
    goldenRule:'الرياضة تُسرّع القلب مؤقتاً لتوفير الطاقة — هذا دليل صحة.',
    feedbackQuestion:{question:'لماذا يزيد معدل ضربات القلب أثناء الرياضة؟',options:[{text:'لضخّ المزيد من الدم للعضلات',correct:true},{text:'لأن القلب مريض',correct:false},{text:'لا سبب',correct:false},{text:'لأن الجسم خائف',correct:false}]},
  },
  {
    id:'u4l2q6', unit:'unit4', lesson:'u4l2', page:162, type:'ordering',
    bloom:'understand', difficulty:'medium',
    question:'رتّب مسار الهواء في الجهاز التنفسي عند الشهيق:',
    paragraph:'الجِهازُ التَّنفُسيُّ: أَنفٌ / فَمٌ / قَصَبةٌ هَوائيَّةٌ / رِئَتان. (ص162)',
    items:['الرئتان','الأنف','القصبة الهوائية','الفم'],
    correctOrder:[1,3,2,0],
    explanation:'مسار الهواء: أنف ← فم ← قصبة هوائية ← رئتان.',
    goldenRule:'مسار الشهيق: أنف → قصبة هوائية → رئتان → الدم.',
  },
  {
    id:'u4l2q7', unit:'unit4', lesson:'u4l2', page:162, type:'multipleChoice',
    bloom:'analyze', difficulty:'medium',
    question:'الجهاز العصبي يُرسل رسائل من الدماغ لأجزاء الجسم عبر:',
    paragraph:'يُرسِلُ الدِّماغُ الرَّسائِلَ إلى جَميعِ أَنحاءِ الجِسمِ، تُنقَلُ هَذِهِ الرَّسائِلُ عَبرَ أَجزاءٍ دَقيقةٍ تُسَمَّى الأَعصاب. (ص161)',
    options:[
      {text:'الأعصاب',correct:true},
      {text:'الشرايين',correct:false},
      {text:'العضلات',correct:false},
      {text:'العظام',correct:false},
    ],
    explanation:'الجهاز العصبي يُرسل الرسائل عبر الأعصاب من الدماغ لكل أجزاء الجسم.',
    goldenRule:'الجهاز العصبي = دماغ + أعصاب = يُرسل الأوامر لكل الجسم.',
    feedbackQuestion:{question:'ما اسم الأجزاء التي تنقل رسائل الدماغ؟',options:[{text:'الأعصاب',correct:true},{text:'الشرايين',correct:false},{text:'العضلات',correct:false},{text:'المفاصل',correct:false}]},
  },
  {
    id:'u4l2q8', unit:'unit4', lesson:'u4l2', page:162, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف هذه الأجهزة: أيّها يتعلق بالحركة وأيّها يتعلق بالحياة الداخلية؟',
    paragraph:'أجهزة جسم الإنسان: هيكلي + عضلي + دوراني + تنفسي + عصبي. (ص160-162)',
    categories:['أجهزة الحركة والشكل','أجهزة الوظائف الحيوية'],
    items:[
      {text:'الجهاز الهيكلي (العظام)',correct_category:0},
      {text:'الجهاز العضلي',correct_category:0},
      {text:'الجهاز الدوراني',correct_category:1},
      {text:'الجهاز التنفسي',correct_category:1},
      {text:'الجهاز العصبي',correct_category:1},
    ],
    explanation:'الحركة والشكل: هيكلي + عضلي. الوظائف الحيوية: دوراني + تنفسي + عصبي.',
    goldenRule:'أجهزة الحركة: هيكلي + عضلي. أجهزة الحياة: دوراني + تنفسي + عصبي.',
  },
];

export const ALL_QUESTIONS = [
  ...u3l1Qs, ...u3l2Qs, ...u3l3Qs,
  ...u4l1Qs, ...u4l2Qs,
  ...SCIENCE_EXTRA_1,
];