// العلوم - الصف الثاني الابتدائي - الفصل الأول
// الوحدة الأولى: النباتات والحيوانات
// مستخرج من كتاب الطالب 1447هـ / 2025م

export const U1_QUESTIONS = [
  // ─── الفصل الأول | الدرس 1: حاجات المخلوقات الحية (ص30-33) ──────────────
  {
    id:'u1q1', unit:'u1', lesson:'u1l1', page:30, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'الحيوانات مخلوقات حية لأننا نراها:',
    paragraph:'نَحْنُ نَرَى الحَيَوَاناتِ تَتَحَرَّكُ، وَتَأْكُلُ الطَّعامَ، وَتَشْرَبُ الماءَ، وَتَتَنَفَّسُ الهَواءَ، فَنَعْرِفُ أَنَّها حَيَّةٌ. (ص32)',
    image:'https://images.unsplash.com/photo-1551855714-4c5f81dcf9a7?w=600',
    options:[
      {text:'تتحرك وتأكل الطعام وتشرب الماء وتتنفس',correct:true},
      {text:'لا تتحرك أبداً',correct:false},
      {text:'تعيش بدون ماء',correct:false},
      {text:'لا تحتاج للهواء',correct:false},
    ],
    explanation:'الحيوانات مخلوقات حية لأنها تتحرك وتأكل وتشرب وتتنفس.',
    goldenRule:'المخلوق الحي: يتحرك + يأكل + يشرب + يتنفس + ينمو.',
    feedbackQuestion:{question:'كيف نعرف أن الحيوان مخلوق حي؟',options:[{text:'يراه يتحرك ويأكل ويشرب ويتنفس',correct:true},{text:'لا يتحرك',correct:false},{text:'لا يأكل',correct:false},{text:'لا يشرب',correct:false}]},
  },
  {
    id:'u1q2', unit:'u1', lesson:'u1l1', page:32, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'من السهل علينا ملاحظة أن النباتات مخلوقات حية كما نلاحظ ذلك في الحيوانات.',
    paragraph:'النَّباتاتُ أيضاً مَخْلُوقاتٌ حَيَّةٌ، وَلَكِنْ لَيْسَ مِنَ السَّهْلِ عَلَيْنا مُلاحَظَةُ ذَلِكَ. نَحْتاجُ إِلى مُراقَبَةِ النَّباتاتِ فِتْرَةً مُعَيَّنَةً. (ص33)',
    image:'https://images.unsplash.com/photo-1530978958461-4aeb4d5b0a36?w=600',
    correctAnswer:false,
    explanation:'ليس من السهل ملاحظة أن النباتات حية لأنها لا تتحرك مثل الحيوانات، لكنها تنمو وتتغير.',
    goldenRule:'النباتات مخلوقات حية تنمو وتتغير لكنها لا تتحرك مثل الحيوانات.',
    feedbackQuestion:{question:'لماذا ليس من السهل ملاحظة أن النباتات حية؟',options:[{text:'لأنها لا تتحرك مثل الحيوانات',correct:true},{text:'لأنها لا تأكل',correct:false},{text:'لأنها لا تنمو',correct:false},{text:'لأنها لا تحتاج ماء',correct:false}]},
  },
  {
    id:'u1q3', unit:'u1', lesson:'u1l1', page:33, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'تحتاج النباتات لتعيش وتنمو إلى:',
    paragraph:'تَحْتاجُ النَّباتاتُ إِلى الهَواءِ والماءِ وضَوْءِ الشَّمْسِ والمَكانِ المُناسِبِ لِكَي تَعِيشَ وَتَنْمُوَ. (ص33)',
    image:'https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?w=600',
    options:[
      {text:'الهواء والماء وضوء الشمس والمكان المناسب',correct:true},
      {text:'الظلام فقط',correct:false},
      {text:'الملح فقط',correct:false},
      {text:'الحرارة الشديدة فقط',correct:false},
    ],
    explanation:'النباتات تحتاج أربعة أشياء: الهواء، الماء، ضوء الشمس، والمكان المناسب.',
    goldenRule:'حاجات النبات: هواء + ماء + ضوء شمس + مكان مناسب.',
    feedbackQuestion:{question:'أي مما يلي لا تحتاجه النباتات؟',options:[{text:'الظلام الدائم',correct:true},{text:'الهواء',correct:false},{text:'الماء',correct:false},{text:'ضوء الشمس',correct:false}]},
  },
  {
    id:'u1q4', unit:'u1', lesson:'u1l1', page:33, type:'ordering',
    bloom:'apply', difficulty:'medium',
    question:'رتّب مراحل نمو النبات كما في الكتاب:',
    paragraph:'النَّباتاتُ تَنْمُو وَتَتَغَيَّرُ: بَدْرَةٌ نابِتَةٌ → نَباتٌ صَغِيرٌ → نَباتٌ مُكْتَمِلُ النُّمُو. (ص33)',
    image:'https://images.unsplash.com/photo-1387212282092-9a4e7c68a50f?w=600',
    items:['نبات مكتمل النمو','بذرة نابتة','نبات صغير'],
    correctOrder:[1,2,0],
    explanation:'النبات يبدأ بذرة نابتة ثم ينمو ليصير نباتاً صغيراً ثم نباتاً مكتمل النمو.',
    goldenRule:'مراحل نمو النبات: بذرة ← نبات صغير ← نبات مكتمل النمو.',
  },
  {
    id:'u1q5', unit:'u1', lesson:'u1l1', page:32, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'الجرادة تأكل أزهار النبات، والبطّة تبني عشاً لصغارها قريباً من البركة. هذا يدل على أن الحيوانات:',
    paragraph:'تَأْكُلُ الجَرادَةُ أَزْهارَ النَّباتِ. تَبْنِي البَطَّةُ عُشًّا لِصِغارِها قَرِيباً مِنَ البِرْكَةِ. (ص32)',
    image:'https://images.unsplash.com/photo-1444464756325-7538eb4f1c60?w=600',
    options:[
      {text:'مخلوقات حية تحتاج للطعام والمأوى',correct:true},
      {text:'لا تحتاج للطعام',correct:false},
      {text:'تعيش بدون مأوى',correct:false},
      {text:'لا تتنفس',correct:false},
    ],
    explanation:'الحيوانات تأكل وتبني بيوتاً لصغارها مما يدل على أنها مخلوقات حية.',
    goldenRule:'الحيوان يأكل ويبني مأوى لصغاره لأنه مخلوق حي.',
    feedbackQuestion:{question:'لماذا تبني البطة عشاً قريباً من البركة؟',options:[{text:'لصغارها',correct:true},{text:'لنفسها فقط',correct:false},{text:'للأصدقاء',correct:false},{text:'لا تبني عشاً',correct:false}]},
  },
  {
    id:'u1q6', unit:'u1', lesson:'u1l1', page:30, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف الكائنات: حية أم غير حية؟',
    paragraph:'نَحْنُ نَرَى الحَيَوَاناتِ تَتَحَرَّكُ وَتَأْكُلُ فَنَعْرِفُ أَنَّها حَيَّةٌ. (ص32)',
    categories:['مخلوقات حية 🌱','أشياء غير حية 🪨'],
    items:[
      {text:'النبات',correct_category:0},
      {text:'الصخرة',correct_category:1},
      {text:'الأرنب',correct_category:0},
      {text:'الماء',correct_category:1},
      {text:'السمكة',correct_category:0},
      {text:'التراب',correct_category:1},
    ],
    explanation:'المخلوقات الحية: النبات والأرنب والسمكة. غير الحية: الصخرة والماء والتراب.',
    goldenRule:'المخلوق الحي ينمو ويتغير، غير الحي لا ينمو.',
  },
  {
    id:'u1q7', unit:'u1', lesson:'u1l1', page:33, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'النباتات تحتاج أيضاً إلى الغذاء كما تحتاج الحيوانات.',
    paragraph:'تَحْتاجُ النَّباتاتُ أَيْضاً إِلى الغِذاءِ. (ص33)',
    image:'https://images.unsplash.com/photo-1509223197845-458d8d187e98?w=600',
    correctAnswer:true,
    explanation:'النباتات تحتاج للغذاء لكنها تصنعه بنفسها من ضوء الشمس والماء والهواء.',
    goldenRule:'النباتات تصنع غذاءها بنفسها — لهذا فهي تحتاج ضوء الشمس.',
    feedbackQuestion:{question:'كيف تحصل النباتات على غذائها؟',options:[{text:'تصنعه بنفسها من الشمس والماء',correct:true},{text:'تأكله من الخارج',correct:false},{text:'تشتريه',correct:false},{text:'لا تحتاج غذاء',correct:false}]},
  },
  {
    id:'u1q8', unit:'u1', lesson:'u1l1', page:31, type:'multipleChoice',
    bloom:'apply', difficulty:'medium',
    question:'في نشاط "ما الذي تحتاج إليه أوراق النباتات لتعيش؟" غُطّيت أوراق إحدى النبتتين بورق الألومنيوم. ما الهدف؟',
    paragraph:'أَضَعُ نَبْتَتَيْنِ فِي مَكانٍ مُشْمِسٍ، ثُمَّ أُغَطِّي أَوْرَاقَ إِحْداهُما بِوَرَقِ الأَلُومِنْيُوم. (ص31)',
    image:'https://images.unsplash.com/photo-1416879595882-3373a048020a?w=600',
    options:[
      {text:'معرفة تأثير منع ضوء الشمس عن الأوراق',correct:true},
      {text:'تجميل النبتة',correct:false},
      {text:'زيادة نمو الأوراق',correct:false},
      {text:'حمايتها من الحشرات',correct:false},
    ],
    explanation:'تغطية الأوراق بورق الألومنيوم تمنع وصول ضوء الشمس لمعرفة أهميته للنبات.',
    goldenRule:'ضوء الشمس ضروري لصنع الغذاء في أوراق النبات.',
    feedbackQuestion:{question:'ماذا يحدث للورق المغطى بورق الألومنيوم؟',options:[{text:'لا يصنع غذاء لأنه بلا ضوء',correct:true},{text:'ينمو أكثر',correct:false},{text:'يصبح أكبر',correct:false},{text:'لا يتأثر',correct:false}]},
  },
  {
    id:'u1q9', unit:'u1', lesson:'u1l1', page:33, type:'fillBlank',
    bloom:'remember', difficulty:'easy',
    question:'أكمل: تحتاج النباتات إلى ___ و ___ وضوء الشمس والمكان المناسب لتعيش.',
    paragraph:'تَحْتاجُ النَّباتاتُ إِلى الهَواءِ والماءِ وضَوْءِ الشَّمْسِ والمَكانِ المُناسِبِ. (ص33)',
    blanks:['الهواء','الماء'],
    wordBank:['الهواء','الماء','الظلام','الملح'],
    explanation:'النباتات تحتاج الهواء والماء وضوء الشمس والمكان المناسب.',
    goldenRule:'حاجات النبات الأربع: هواء + ماء + ضوء شمس + مكان مناسب.',
  },
  {
    id:'u1q10', unit:'u1', lesson:'u1l1', page:32, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'نحتاج لمراقبة النباتات فترة معينة لمعرفة أنها مخلوقات حية لأن:',
    paragraph:'نَحْتاجُ إِلى مُراقَبَةِ النَّباتاتِ فِتْرَةً مُعَيَّنَةً؛ لِكَي نُلاحِظَ أَنَّها تَنْمُو وَتَتَغَيَّرُ. (ص33)',
    image:'https://images.unsplash.com/photo-1463936575829-2514821ca949?w=600',
    options:[
      {text:'نموها وتغيرها يحدث ببطء ولا نراه فوراً',correct:true},
      {text:'النباتات لا تنمو',correct:false},
      {text:'النباتات تتحرك بسرعة',correct:false},
      {text:'النباتات تتكلم',correct:false},
    ],
    explanation:'النباتات تنمو ببطء لذا نحتاج لمراقبتها فترة حتى نلاحظ نموها وتغيرها.',
    goldenRule:'النبات مخلوق حي ينمو ببطء — المراقبة تكشف ذلك.',
    feedbackQuestion:{question:'ما الذي نلاحظه بعد مراقبة النبات فترة؟',options:[{text:'أنها تنمو وتتغير',correct:true},{text:'أنها تتحرك',correct:false},{text:'أنها تتكلم',correct:false},{text:'أنها تصدر صوتاً',correct:false}]},
  },

  // ─── الفصل الأول | الدرس 2: كيف تصنع النباتات غذاءها (ص34-36) ───────────
  {
    id:'u1q11', unit:'u1', lesson:'u1l2', page:34, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'النباتات تمتص الماء والمعادن التي تمتزج في التربة في صورة:',
    paragraph:'الأَجْزاءُ يَمْتَصُّ الماءَ وَالمَعادِنَ الَّتي تَمْتَزُّها فِي صُورَةِ أَمْلاحٍ ذائِبَةٍ فِي التُّرْبَةِ لِتَصْنَعَ غِذاءَها. (ص34)',
    image:'https://images.unsplash.com/photo-1545241047-6083a3684587?w=600',
    options:[
      {text:'أملاح ذائبة في التربة',correct:true},
      {text:'حجر كبير',correct:false},
      {text:'رمل جاف',correct:false},
      {text:'غبار',correct:false},
    ],
    explanation:'النبات يمتص الماء والمعادن على شكل أملاح ذائبة في التربة ليصنع غذاءه.',
    goldenRule:'النبات يمتص = ماء + معادن (أملاح ذائبة) من التربة.',
    feedbackQuestion:{question:'من أين يحصل النبات على المعادن؟',options:[{text:'من التربة على شكل أملاح ذائبة',correct:true},{text:'من الهواء',correct:false},{text:'من الشمس',correct:false},{text:'من المطر',correct:false}]},
  },
  {
    id:'u1q12', unit:'u1', lesson:'u1l2', page:34, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'المعادن الموجودة في التربة هي:',
    paragraph:'المَعادِنُ أَجْزاءُ صُلْبَةٌ غَيْرُ حَيَّةٍ مِنَ التُّرْبَةِ. (ص34)',
    image:'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600',
    options:[
      {text:'أجزاء صلبة غير حية من التربة',correct:true},
      {text:'مخلوقات حية',correct:false},
      {text:'نباتات صغيرة',correct:false},
      {text:'حيوانات',correct:false},
    ],
    explanation:'المعادن أجزاء صلبة غير حية موجودة في التربة وتمتصها النباتات.',
    goldenRule:'المعادن = أجزاء صلبة غير حية في التربة — يمتصها النبات.',
    feedbackQuestion:{question:'هل المعادن مخلوقات حية؟',options:[{text:'لا، أجزاء صلبة غير حية',correct:true},{text:'نعم',correct:false},{text:'بعضها حي',correct:false},{text:'لا أعرف',correct:false}]},
  },
  {
    id:'u1q13', unit:'u1', lesson:'u1l2', page:35, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'عندما تصنع النباتات الغذاء تطلق غازاً في الهواء يسمى:',
    paragraph:'عِنْدَما تَصْنَعُ النَّباتاتُ الغِذاءَ تُطْلِقُ غازاً فِي الهَواءِ يُسَمَّى الأُكْسِجِينَ. (ص35)',
    image:'https://images.unsplash.com/photo-1463569593074-22ae0c20ae0d?w=600',
    options:[
      {text:'الأكسجين',correct:true},
      {text:'ثاني أكسيد الكربون',correct:false},
      {text:'النيتروجين',correct:false},
      {text:'الهيدروجين',correct:false},
    ],
    explanation:'النبات يطلق غاز الأكسجين عند صنع الغذاء وهو الغاز الذي يتنفسه الإنسان والحيوان.',
    goldenRule:'النبات يصنع غذاءه + يطلق الأكسجين الذي نتنفسه.',
    feedbackQuestion:{question:'ما الغاز الذي يطلقه النبات عند صنع الغذاء؟',options:[{text:'الأكسجين',correct:true},{text:'ثاني أكسيد الكربون',correct:false},{text:'النيتروجين',correct:false},{text:'الغبار',correct:false}]},
  },
  {
    id:'u1q14', unit:'u1', lesson:'u1l2', page:35, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'الأكسجين هو الغاز الذي يتنفسه الإنسان والحيوان ليعيشا.',
    paragraph:'الأُكْسِجِينُ هُوَ الغازُ الَّذي يَتَنَفَّسُهُ الإِنْسانُ وَالحَيَوانُ لِيَعيشا. (ص35)',
    image:'https://images.unsplash.com/photo-1576020799627-aeac74d58064?w=600',
    correctAnswer:true,
    explanation:'الأكسجين ضروري لحياة الإنسان والحيوان وينتجه النبات عند صنع الغذاء.',
    goldenRule:'النبات ينتج الأكسجين → الإنسان والحيوان يتنفسانه ليعيشا.',
    feedbackQuestion:{question:'لماذا يعتبر إنتاج النبات للأكسجين مهماً؟',options:[{text:'لأننا نتنفسه لنعيش',correct:true},{text:'لأنه جميل',correct:false},{text:'لأنه نادر',correct:false},{text:'لا أهمية له',correct:false}]},
  },
  {
    id:'u1q15', unit:'u1', lesson:'u1l2', page:34, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف ما يحتاجه النبات لصنع الغذاء:',
    paragraph:'تَحْتاجُ النَّباتاتُ إِلى ضَوْءِ الشَّمْسِ وَالهَواءِ وَالماءِ وَالمَعادِنِ لِتَصْنَعَ غِذاءَها. (ص34)',
    categories:['يحتاجه النبات لصنع الغذاء ☀️','لا يحتاجه 🚫'],
    items:[
      {text:'ضوء الشمس',correct_category:0},
      {text:'الظلام',correct_category:1},
      {text:'الماء',correct_category:0},
      {text:'الملح الزائد',correct_category:1},
      {text:'الهواء',correct_category:0},
      {text:'السم',correct_category:1},
    ],
    explanation:'النبات يحتاج ضوء الشمس والماء والهواء والمعادن لصنع الغذاء.',
    goldenRule:'صنع الغذاء = ضوء شمس + ماء + هواء + معادن.',
  },
  {
    id:'u1q16', unit:'u1', lesson:'u1l2', page:36, type:'multipleChoice',
    bloom:'apply', difficulty:'medium',
    question:'عند الملاحظة نستخدم حواسنا لنتعرف الأشياء. أي حاسة نستخدم لرؤية لون الأزهار؟',
    paragraph:'أَسْتَخْدِمُ حَواسِّي لِأَرَى وَأَسْمَعَ وَأَتَذَوَّقَ وَأَشُمَّ وَأُحِسَّ. (ص36)',
    image:'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=600',
    options:[
      {text:'حاسة البصر (الرؤية)',correct:true},
      {text:'حاسة السمع',correct:false},
      {text:'حاسة الذوق',correct:false},
      {text:'حاسة اللمس',correct:false},
    ],
    explanation:'نستخدم حاسة البصر (الرؤية) لرؤية ألوان الأزهار وأشكال النبات.',
    goldenRule:'الملاحظة تستخدم الحواس الخمس: رؤية + سمع + تذوق + شم + لمس.',
    feedbackQuestion:{question:'أي حاسة نستخدم لمعرفة رائحة الياسمين؟',options:[{text:'الشم',correct:true},{text:'البصر',correct:false},{text:'السمع',correct:false},{text:'اللمس',correct:false}]},
  },
  {
    id:'u1q17', unit:'u1', lesson:'u1l2', page:36, type:'matching',
    bloom:'understand', difficulty:'medium',
    question:'صِل كل حاسة بوظيفتها:',
    paragraph:'أَسْتَخْدِمُ حَواسِّي لِأَرَى وَأَسْمَعَ وَأَتَذَوَّقَ وَأَشُمَّ وَأُحِسَّ. (ص36)',
    pairs:[
      {left:'البصر',right:'أرى الألوان والأشكال'},
      {left:'السمع',right:'أسمع الأصوات'},
      {left:'الشم',right:'أشم الروائح'},
      {left:'اللمس',right:'أحس بالملمس'},
    ],
    explanation:'كل حاسة لها وظيفة خاصة بها لمعرفة العالم من حولنا.',
    goldenRule:'الحواس الخمس: البصر + السمع + الشم + الذوق + اللمس.',
  },
  {
    id:'u1q18', unit:'u1', lesson:'u1l2', page:35, type:'fillBlank',
    bloom:'apply', difficulty:'easy',
    question:'أكمل: النباتات تنتج غاز ___ الذي يتنفسه الإنسان والحيوان.',
    paragraph:'النَّباتاتُ تُنْتِجُ غازَ الأُكْسِجِينِ اللَّازِمَ لِحَياةِ الإِنْسانِ وَالحَيَوان. (ص35)',
    blanks:['الأكسجين'],
    wordBank:['الأكسجين','النيتروجين','الغبار','الملح'],
    explanation:'النبات ينتج غاز الأكسجين الذي يتنفسه الإنسان والحيوان ليعيشا.',
    goldenRule:'النبات مصنع الأكسجين الذي نتنفسه.',
  },
  {
    id:'u1q19', unit:'u1', lesson:'u1l2', page:34, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'لماذا تعتبر النباتات مهمة للإنسان والحيوان؟',
    paragraph:'هَذِهِ النَّباتاتُ تُنْتِجُ غازَ الأُكْسِجِينِ اللَّازِمَ لِحَياةِ الإِنْسانِ وَالحَيَوان. (ص35)',
    image:'https://images.unsplash.com/photo-1500382017468-9049fedbd096?w=600',
    options:[
      {text:'لأنها تنتج الأكسجين الذي يتنفسانه',correct:true},
      {text:'لأنها تصدر ضوضاء',correct:false},
      {text:'لأنها تتحرك',correct:false},
      {text:'لأنها تستهلك الأكسجين',correct:false},
    ],
    explanation:'النباتات تنتج الأكسجين الضروري لحياة الإنسان والحيوان.',
    goldenRule:'لا حياة بدون نبات — النبات يطعمنا ويطعمنا الأكسجين.',
    feedbackQuestion:{question:'ماذا يحدث لو اختفت النباتات من الأرض؟',options:[{text:'يقل الأكسجين ويصعب التنفس',correct:true},{text:'لا شيء',correct:false},{text:'يزيد الأكسجين',correct:false},{text:'يصبح الجو أبرد',correct:false}]},
  },
  {
    id:'u1q20', unit:'u1', lesson:'u1l2', page:36, type:'trueFalse',
    bloom:'apply', difficulty:'medium',
    question:'عند الملاحظة يمكنني استخدام لوحة أكتب عليها ملاحظاتي.',
    paragraph:'يُمْكِنُني عَمَلُ لَوْحَةٍ لِأَكْتُبَ عَلَيْها مُلاحَظاتي. (ص36)',
    image:'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=600',
    correctAnswer:true,
    explanation:'كتابة الملاحظات على لوحة تساعد على تنظيم وتسجيل ما نراه.',
    goldenRule:'العلماء يسجلون ملاحظاتهم على لوحات لتذكرها ومشاركتها.',
  },

  // ─── الفصل الأول | الدرس 3: تكاثر النباتات (ص37-54) ─────────────────
  {
    id:'u1q21', unit:'u1', lesson:'u1l3', page:29, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'البادرة هي:',
    paragraph:'البادِرَةُ نَبْتَةٌ صَغِيرَةٌ فِي بِدايَةِ نُمُوِّ البَذْرَة. (ص29)',
    image:'https://images.unsplash.com/photo-1387212282092-9a4e7c68a50f?w=600',
    options:[
      {text:'نبتة صغيرة في بداية نمو البذرة',correct:true},
      {text:'شجرة كبيرة',correct:false},
      {text:'زهرة كاملة',correct:false},
      {text:'ثمرة ناضجة',correct:false},
    ],
    explanation:'البادرة هي النبتة الصغيرة التي تبدأ بالنمو من البذرة.',
    goldenRule:'البادرة = أول ما ينمو من البذرة في بداية حياة النبات.',
    feedbackQuestion:{question:'ما المرحلة قبل البادرة؟',options:[{text:'البذرة',correct:true},{text:'الزهرة',correct:false},{text:'الثمرة',correct:false},{text:'الجذر',correct:false}]},
  },
  {
    id:'u1q22', unit:'u1', lesson:'u1l3', page:29, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'الزهرة جزء من النبات له:',
    paragraph:'الزَّهْرَةُ جُزْءٌ مِنَ النَّباتِ لَهُ أَلْوانٌ مُخْتَلِفَةٌ يُكَوِّنُ البُذُورَ والثِّمار. (ص29)',
    image:'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=600',
    options:[
      {text:'ألوان مختلفة ويكوّن البذور والثمار',correct:true},
      {text:'أوراقاً خضراء فقط',correct:false},
      {text:'جذوراً',correct:false},
      {text:'سيقاناً طويلة',correct:false},
    ],
    explanation:'الزهرة لها ألوان جميلة وتكوّن البذور والثمار للنبات.',
    goldenRule:'الزهرة = الجزء الملون الذي يكوّن البذور والثمار.',
    feedbackQuestion:{question:'ماذا يكوّن الزهرة؟',options:[{text:'البذور والثمار',correct:true},{text:'الجذور',correct:false},{text:'الأوراق',correct:false},{text:'السيقان',correct:false}]},
  },
  {
    id:'u1q23', unit:'u1', lesson:'u1l3', page:29, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'البذرة جزء من النبات:',
    paragraph:'البَذْرَةُ جُزْءٌ مِنَ النَّباتِ يَنْبُتُ وَيَصِيرُ نَباتاً جَدِيداً. (ص29)',
    image:'https://images.unsplash.com/photo-1574943320219-559eb6ef7310?w=600',
    options:[
      {text:'ينبت ويصير نباتاً جديداً',correct:true},
      {text:'لا ينبت أبداً',correct:false},
      {text:'يذوب في الماء',correct:false},
      {text:'يطير في الهواء',correct:false},
    ],
    explanation:'البذرة تنبت وتنمو لتصير نباتاً جديداً كاملاً.',
    goldenRule:'البذرة = بداية نبات جديد — تنبت وتنمو.',
    feedbackQuestion:{question:'ماذا يحدث للبذرة في التربة؟',options:[{text:'تنبت وتنمو نباتاً جديداً',correct:true},{text:'تختفي',correct:false},{text:'تتحول لصخرة',correct:false},{text:'تطير',correct:false}]},
  },
  {
    id:'u1q24', unit:'u1', lesson:'u1l3', page:29, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'حبوب اللقاح مسحوق يتكوّن داخل الزهرة:',
    paragraph:'حُبُوبُ اللَّقاحِ مَسْحُوقٌ يَتَكَوَّنُ داخِلَ الزَّهْرَةِ يُسْهِمُ فِي إِنْتاجِ البُذُور. (ص29)',
    image:'https://images.unsplash.com/photo-1455659817273-f8f1f7de9547?w=600',
    options:[
      {text:'يسهم في إنتاج البذور',correct:true},
      {text:'يسهم في تلوث الهواء',correct:false},
      {text:'ضرر للنبات',correct:false},
      {text:'لا فائدة له',correct:false},
    ],
    explanation:'حبوب اللقاح تساعد في إنتاج البذور داخل الزهرة.',
    goldenRule:'حبوب اللقاح = مسحوق داخل الزهرة يساعد إنتاج البذور.',
    feedbackQuestion:{question:'أين تتكوّن حبوب اللقاح؟',options:[{text:'داخل الزهرة',correct:true},{text:'في الجذور',correct:false},{text:'في الأوراق',correct:false},{text:'في الساق',correct:false}]},
  },
  {
    id:'u1q25', unit:'u1', lesson:'u1l3', page:29, type:'matching',
    bloom:'remember', difficulty:'medium',
    question:'صِل كل مفردة بمعناها:',
    paragraph:'المُفْرَدات: البادِرَةُ، الزَّهْرَةُ، البَذْرَةُ، حُبُوبُ اللَّقاح. (ص29)',
    pairs:[
      {left:'البادرة',right:'نبتة صغيرة في بداية نمو البذرة'},
      {left:'الزهرة',right:'جزء ملون يكوّن البذور والثمار'},
      {left:'البذرة',right:'تنبت وتصير نباتاً جديداً'},
      {left:'حبوب اللقاح',right:'مسحوق يسهم في إنتاج البذور'},
    ],
    explanation:'كل مفردة لها معنى خاص في دورة حياة النبات.',
    goldenRule:'مفردات النبات: بادرة + زهرة + بذرة + حبوب لقاح.',
  },
  {
    id:'u1q26', unit:'u1', lesson:'u1l3', page:29, type:'ordering',
    bloom:'apply', difficulty:'medium',
    question:'رتّب مراحل دورة حياة النبات:',
    paragraph:'البَذْرَةُ → البادِرَةُ → نَباتٌ صَغِيرٌ → نَباتٌ مُكْتَمِلُ النُّمُو. (ص33)',
    image:'https://images.unsplash.com/photo-1530836369250-972e3aa6a03e?w=600',
    items:['نبات مكتمل النمو','البذرة','البادرة'],
    correctOrder:[1,2,0],
    explanation:'النبات يبدأ بذرة ثم ينبت بادرة ثم يكبر ليصير نباتاً مكتمل النمو.',
    goldenRule:'دورة حياة النبات: بذرة ← بادرة ← نبات مكتمل.',
  },
  {
    id:'u1q27', unit:'u1', lesson:'u1l3', page:29, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'الزهرات لها ألوان مختلفة لتجذب الحشرات.',
    paragraph:'الزَّهْرَةُ جُزْءٌ مِنَ النَّباتِ لَهُ أَلْوانٌ مُخْتَلِفَةٌ. (ص29)',
    image:'https://images.unsplash.com/photo-1471416981898-4f7a2e1c800d?w=600',
    correctAnswer:true,
    explanation:'ألوان الزهور المختلفة تجذب الحشرات التي تساعد في نقل حبوب اللقاح.',
    goldenRule:'ألوان الزهور الجميلة تجذب الحشرات لنقل حبوب اللقاح.',
    feedbackQuestion:{question:'لماذا للزهور ألوان مختلفة؟',options:[{text:'لتجذب الحشرات',correct:true},{text:'لتجميل الحديقة فقط',correct:false},{text:'لتخوفي الطيور',correct:false},{text:'لا فائدة منها',correct:false}]},
  },
  {
    id:'u1q28', unit:'u1', lesson:'u1l3', page:29, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف أجزاء النبات:',
    paragraph:'النَّباتُ يَتَكَوَّنُ مِنْ جُذُورٍ وَساقٍ وَأَوْرَاقٍ وَزَهْرَةٍ وَبُذُور. (ص29)',
    categories:['أجزاء النبات 🌿','ليست أجزاء النبات ❌'],
    items:[
      {text:'الجذور',correct_category:0},
      {text:'الأوراق',correct_category:0},
      {text:'الزهرة',correct_category:0},
      {text:'الصخرة',correct_category:1},
      {text:'الساق',correct_category:0},
      {text:'الماء',correct_category:1},
    ],
    explanation:'أجزاء النبات: الجذور، الساق، الأوراق، الزهرة، البذور. الصخرة والماء ليسا من النبات.',
    goldenRule:'النبات = جذور + ساق + أوراق + زهرة + بذور.',
  },
  {
    id:'u1q29', unit:'u1', lesson:'u1l3', page:29, type:'fillBlank',
    bloom:'apply', difficulty:'easy',
    question:'أكمل: البذرة تنبت وتصير ___ جديداً.',
    paragraph:'البَذْرَةُ جُزْءٌ مِنَ النَّباتِ يَنْبُتُ وَيَصِيرُ نَباتاً جَدِيداً. (ص29)',
    blanks:['نباتاً'],
    wordBank:['نباتاً','صخرة','ماء','هواء'],
    explanation:'البذرة تنبت وتنمو لتصير نباتاً جديداً كاملاً.',
    goldenRule:'البذرة بداية نبات جديد.',
  },
  {
    id:'u1q30', unit:'u1', lesson:'u1l3', page:29, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'لماذا خلق الله للنباتات أزهاراً ملونة وبذوراً؟',
    paragraph:'الزَّهْرَةُ جُزْءٌ مِنَ النَّباتِ لَهُ أَلْوانٌ مُخْتَلِفَةٌ يُكَوِّنُ البُذُورَ والثِّمار. (ص29)',
    image:'https://images.unsplash.com/photo-1502786129293-79981df4dc2d?w=600',
    options:[
      {text:'لتتكاثر وتنتج نباتات جديدة وثماراً',correct:true},
      {text:'لتتحرك',correct:false},
      {text:'لتتنفس',correct:false},
      {text:'لتنام',correct:false},
    ],
    explanation:'الزهور والبذور تساعد النبات على التكاثر وإنتاج نباتات وثمار جديدة.',
    goldenRule:'تكاثر النبات = زهرة + بذور + ثمار = نباتات جديدة.',
    feedbackQuestion:{question:'ما فائدة البذور للنبات؟',options:[{text:'تنتج نباتات جديدة',correct:true},{text:'تحرك النبات',correct:false},{text:'تنظف الهواء',correct:false},{text:'لا فائدة',correct:false}]},
  },

  // ─── الفصل الثاني | الدرس 4: تصنيف الحيوانات (ص55-59) ─────────────────
  {
    id:'u1q31', unit:'u1', lesson:'u1l4', page:55, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'البجع من:',
    paragraph:'البَجَعُ مِنَ الطُّيُور، وَالطُّيُورُ هِيَ الحَيَوَاناتُ الوَحِيدَةُ الَّتي يُغَطِّي جِسْمَها الرِّيش. (ص55)',
    image:'https://images.unsplash.com/photo-1551082576-cd4ec2f7e1f2?w=600',
    options:[
      {text:'الطيور',correct:true},
      {text:'الأسماك',correct:false},
      {text:'الزواحف',correct:false},
      {text:'الثدييات',correct:false},
    ],
    explanation:'البجع من الطيور لأن جسمه مغطى بالريش وله منقار وجناحان.',
    goldenRule:'الطيور = الحيوانات الوحيدة التي يغطي جسمها الريش.',
    feedbackQuestion:{question:'ما الذي يميز الطيور عن غيرها؟',options:[{text:'الريش يغطي جسمها',correct:true},{text:'القشور',correct:false},{text:'الشعر',correct:false},{text:'لا شيء',correct:false}]},
  },
  {
    id:'u1q32', unit:'u1', lesson:'u1l4', page:55, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'جميع الطيور لها:',
    paragraph:'جَمِيعُ الطُّيُورِ لَها رِجْلانِ وَجَناحانِ وَمِنْقار، وَتَضَعُ بَيْضاً يَفْقِسُ مِنْهُ الصِّغار. (ص55)',
    image:'https://images.unsplash.com/photo-1444464669806-84f9a4e4e3b7?w=600',
    options:[
      {text:'رجلان وجناحان ومنقار وتضع بيضاً',correct:true},
      {text:'أربع أرجل فقط',correct:false},
      {text:'خياشيم',correct:false},
      {text:'ذيل طويل فقط',correct:false},
    ],
    explanation:'جميع الطيور لها رجلان وجناحان ومنقار وتضع بيضاً يفقس منه الصغار.',
    goldenRule:'الطائر = رجلان + جناحان + منقار + يبيض.',
    feedbackQuestion:{question:'كيف تتكاثر الطيور؟',options:[{text:'تبيض',correct:true},{text:'تلد',correct:false},{text:'تنقسم',correct:false},{text:'لا تتكاثر',correct:false}]},
  },
  {
    id:'u1q33', unit:'u1', lesson:'u1l4', page:55, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'الضب والسحلية من الزواحف، وجلدها:',
    paragraph:'الضَّبُّ وَهَذِهِ السِّحْلِيَّةُ مِنَ الزَّواحِف. جِلْدُ السِّحْلِيَّةِ خَشِنٌ وَمُغَطَّى بِالحَراشِفِ لِحِمايَتِها. (ص55)',
    image:'https://images.unsplash.com/photo-1565804440900-01c663c6f8d9?w=600',
    options:[
      {text:'خشن ومغطى بالحراشف للحماية',correct:true},
      {text:'ملساء بلا حراشف',correct:false},
      {text:'مغطى بالريش',correct:false},
      {text:'مغطى بالشعر',correct:false},
    ],
    explanation:'الزواحف مثل الضب والسحلية جلدها خشن ومغطى بالحراشف للحماية.',
    goldenRule:'الزواحف = جلد خشن + حراشف + حماية.',
    feedbackQuestion:{question:'لماذا جلد السحلية خشن؟',options:[{text:'للحماية',correct:true},{text:'للجمال',correct:false},{text:'للطيران',correct:false},{text:'للسباحة',correct:false}]},
  },
  {
    id:'u1q34', unit:'u1', lesson:'u1l4', page:55, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'الأسماك فقاريات تعيش في الماء وتستخدم لتنفس:',
    paragraph:'الأسماكُ فَقارِيَّاتٌ تُغَطِّي أَجْسامَها قُشُور، وَتَعِيشُ فِي الماء. تَسْتَعْمِلُ الأسماكُ خَياشِمَها لِتَتَنَفَّس. (ص55)',
    image:'https://images.unsplash.com/photo-1535268647677-06f0c8412da9?w=600',
    options:[
      {text:'الخياشيم',correct:true},
      {text:'الرئتين',correct:false},
      {text:'المنقار',correct:false},
      {text:'الأنف',correct:false},
    ],
    explanation:'الأسماك تتنفس بالخياشيم وتسبح بالزعانف وأجسامها مغطاة بالقشور.',
    goldenRule:'السمكة = قشور + خياشيم (تنفس) + زعانف (سباحة).',
    feedbackQuestion:{question:'بماذا تسبح الأسماك؟',options:[{text:'الزعانف',correct:true},{text:'الأجنحة',correct:false},{text:'الأرجل',correct:false},{text:'الذيل فقط',correct:false}]},
  },
  {
    id:'u1q35', unit:'u1', lesson:'u1l4', page:55, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'الضفدع والسلمندر من البرمائيات التي:',
    paragraph:'الضَّفْدَعُ وَهَذا السَّلَمَنْدَرُ مِنَ البَرْمائِيَّات. (ص55)',
    image:'https://images.unsplash.com/photo-1573529287898-5e5b9f7b4c2e?w=600',
    options:[
      {text:'تعيش في الماء وعلى اليابسة',correct:true},
      {text:'تعيش في الجو فقط',correct:false},
      {text:'تعيش في الصحراء فقط',correct:false},
      {text:'تعيش تحت الأرض',correct:false},
    ],
    explanation:'البرمائيات مثل الضفدع والسلمندر تعيش في الماء وعلى اليابسة.',
    goldenRule:'البرمائيات = تعيش في الماء + على اليابسة.',
    feedbackQuestion:{question:'أين يعيش الضفدع؟',options:[{text:'في الماء وعلى اليابسة',correct:true},{text:'في الجو',correct:false},{text:'في الصحراء',correct:false},{text:'في الجبال',correct:false}]},
  },
  {
    id:'u1q36', unit:'u1', lesson:'u1l4', page:55, type:'classify',
    bloom:'analyze', difficulty:'hard',
    question:'صنّف الحيوانات حسب مجموعتها:',
    paragraph:'البَجَعُ طَيْرٌ، الضَّبُّ زَحْلِفٌ، الأسماكُ فَقارِيَّات، الضَّفْدَعُ بَرْمائِيّ. (ص55)',
    categories:['طيور 🦢','أسماك 🐟','زواحف 🦎','برمائيات 🐸'],
    items:[
      {text:'البجع',correct_category:0},
      {text:'الضب',correct_category:2},
      {text:'السمكة',correct_category:1},
      {text:'الضفدع',correct_category:3},
      {text:'الحمامة',correct_category:0},
      {text:'السلمندر',correct_category:3},
    ],
    explanation:'البجع والحمامة طيور، الضب زاحف، السمكة سمك، الضفدع والسلمندر برمائيات.',
    goldenRule:'تصنيف الحيوانات: طيور + أسماك + زواحف + برمائيات + ثدييات.',
  },
  {
    id:'u1q37', unit:'u1', lesson:'u1l4', page:55, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'الجمل من الثدييات لأن:',
    paragraph:'لِماذا يُصَنَّفُ الجَمَلُ مِنَ الثَّدْيِيَّات؟ (ص55)',
    image:'https://images.unsplash.com/photo-1543589030-ff4c0d2c3c5e?w=600',
    options:[
      {text:'يلد صغاراً ويرضعها',correct:true},
      {text:'يبيض',correct:false},
      {text:'له خياشيم',correct:false},
      {text:'له ريش',correct:false},
    ],
    explanation:'الثدييات تلد صغاراً وترضعها، والجمل من الثدييات.',
    goldenRule:'الثدييات = تلد + ترضع صغارها بالحليب.',
    feedbackQuestion:{question:'أي الحيوانات التالية ثديي؟',options:[{text:'الجمل',correct:true},{text:'السمكة',correct:false},{text:'الضفدع',correct:false},{text:'البجع',correct:false}]},
  },
  {
    id:'u1q38', unit:'u1', lesson:'u1l4', page:55, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'الطيور هي الحيوانات الوحيدة التي يغطي جسمها الريش.',
    paragraph:'الطُّيُورُ هِيَ الحَيَوَاناتُ الوَحِيدَةُ الَّتي يُغَطِّي جِسْمَها الرِّيش. (ص55)',
    image:'https://images.unsplash.com/photo-1444464669806-84f9a4e4e3b7?w=600',
    correctAnswer:true,
    explanation:'الريش صفة فريدة للطيور لا توجد في أي حيوان آخر.',
    goldenRule:'الريش = صفة الطيور فقط — لا يوجد في غيرها.',
    feedbackQuestion:{question:'هل السحلية مغطاة بالريش؟',options:[{text:'لا، بالحراشف',correct:true},{text:'نعم',correct:false},{text:'بالشعر',correct:false},{text:'بالقشور',correct:false}]},
  },
  {
    id:'u1q39', unit:'u1', lesson:'u1l4', page:55, type:'matching',
    bloom:'understand', difficulty:'medium',
    question:'صِل كل حيوان بمجموعته:',
    paragraph:'تَصْنِيفُ الحَيَوَانات: طُيُور، أَسْماك، زَواحِف، بَرْمائِيَّات، ثَدْيِيَّات. (ص55)',
    pairs:[
      {left:'البجع',right:'طيور'},
      {left:'السمكة',right:'أسماك'},
      {left:'الضب',right:'زواحف'},
      {left:'الجمل',right:'ثدييات'},
    ],
    explanation:'كل حيوان ينتمي لمجموعة حسب صفاته: الريش، القشور، الخياشيم، إلخ.',
    goldenRule:'التصنيف يجمع المتشابه في مجموعات.',
  },
  {
    id:'u1q40', unit:'u1', lesson:'u1l4', page:55, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'بماذا تتنفس الأسماك في الماء؟',
    paragraph:'تَسْتَعْمِلُ الأسماكُ خَياشِمَها لِتَتَنَفَّس، وَزَعانِفَها لِتَسْبَح. (ص55)',
    image:'https://images.unsplash.com/photo-1535268647677-06f0c8412da9?w=600',
    options:[
      {text:'الخياشيم',correct:true},
      {text:'الرئتين',correct:false},
      {text:'الأنف',correct:false},
      {text:'الجلد',correct:false},
    ],
    explanation:'الأسماك تتنفس بالخياشيم التي تأخذ الأكسجين من الماء.',
    goldenRule:'السمكة تتنس بالخياشيم في الماء — لا تخرج للتنفس.',
    feedbackQuestion:{question:'بماذا تسبح الأسماك؟',options:[{text:'الزعانف',correct:true},{text:'الأجنحة',correct:false},{text:'الأرجل',correct:false},{text:'الخياشيم',correct:false}]},
  },

  // ─── الفصل الثاني | الدرس 5: الحيوانات اللافقارية (ص56-57) ────────────
  {
    id:'u1q41', unit:'u1', lesson:'u1l5', page:56, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'الحيوانات التي ليس لها عمود فقري تسمى:',
    paragraph:'هُناكَ الكَثِيرُ مِنَ الحَيَوَاناتِ لَيْسَ لَها عَمُودٌ فَقَرِيّ، وَهِيَ أَكْثَرُ مِنَ الحَيَوَاناتِ الفَقارِيَّة. (ص56)',
    image:'https://images.unsplash.com/photo-1564773777901-7f1c0b2e4b5e?w=600',
    options:[
      {text:'اللافقاريات',correct:true},
      {text:'الفقاريات',correct:false},
      {text:'الثدييات',correct:false},
      {text:'الطيور',correct:false},
    ],
    explanation:'اللافقاريات هي الحيوانات التي ليس لها عمود فقري وعددها أكثر من الفقاريات.',
    goldenRule:'لافقاريات = حيوانات بلا عمود فقري (أكثر عدداً).',
    feedbackQuestion:{question:'أيهما أكثر عدداً: الفقاريات أم اللافقاريات؟',options:[{text:'اللافقاريات',correct:true},{text:'الفقاريات',correct:false},{text:'متساويان',correct:false},{text:'لا أعرف',correct:false}]},
  },
  {
    id:'u1q42', unit:'u1', lesson:'u1l5', page:56, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'بعض اللافقاريات ومنها الحشرات يغطي جسمها:',
    paragraph:'بَعْضُ اللافَقارِيَّات — وَمِنْها الحَشَرات — يُغَطِّي جِسْمَها غِطاءٌ صُلْبٌ يُوَفِّرُ لَها الحِمايَةَ والأَمان. (ص56)',
    image:'https://images.unsplash.com/photo-1564773777901-7f1c0b2e4b5e?w=600',
    options:[
      {text:'غطاء صلب للحماية والأمان',correct:true},
      {text:'ريش',correct:false},
      {text:'شعر',correct:false},
      {text:'لا شيء',correct:false},
    ],
    explanation:'الحشرات لها غطاء صلب يحمي جسمها ويوفر لها الأمان.',
    goldenRule:'الحشرة = غطاء صلب + 6 أرجل + قرنا استشعار.',
    feedbackQuestion:{question:'ما فائدة الغطاء الصلب للحشرة؟',options:[{text:'الحماية والأمان',correct:true},{text:'الطيران',correct:false},{text:'السباحة',correct:false},{text:'الجمال',correct:false}]},
  },
  {
    id:'u1q43', unit:'u1', lesson:'u1l5', page:56, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'قناديل البحر من اللافقاريات و:',
    paragraph:'قَنادِيلُ البَحْرِ مِنَ اللافَقارِيَّات، وَلَيْسَ لَها غِطاءٌ خارِجِيّ صُلْب. إِنَّها تَلْسَعُ الحَيَوَاناتِ الأُخْرَى لِكَي تَبْقى فِي أَمان. (ص56)',
    image:'https://images.unsplash.com/photo-1535591273668-8c1f1c0b8e8e?w=600',
    options:[
      {text:'تلسع الحيوانات الأخرى لتبقى آمنة',correct:true},
      {text:'تطير في الجو',correct:false},
      {text:'تبني عشاً',correct:false},
      {text:'تلد صغاراً',correct:false},
    ],
    explanation:'قنديل البحر يلسع الحيوانات الأخرى لحماية نفسه والحصول على الغذاء.',
    goldenRule:'قنديل البحر = لافقاري + يلسع + لا غطاء صلب.',
    feedbackQuestion:{question:'لماذا يلسع قنديل البحر؟',options:[{text:'ليبقى آمناً ويحصل على غذائه',correct:true},{text:'للعب',correct:false},{text:'للسباحة',correct:false},{text:'للنوم',correct:false}]},
  },
  {
    id:'u1q44', unit:'u1', lesson:'u1l5', page:56, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'الخنفساء من الحشرات ولها:',
    paragraph:'الخُنْفُساءُ مِنَ الحَشَرات، لَها سِتُّ أَرْجُل، وَقَرْنا اسْتِشْعار، وَغِطاءٌ خارِجِيّ صُلْب. (ص56)',
    image:'https://images.unsplash.com/photo-1597223557154-780c3c2e5b58?w=600',
    options:[
      {text:'ست أرجل وقرنا استشعار وغطاء صلب',correct:true},
      {text:'أربع أرجل فقط',correct:false},
      {text:'جناحين فقط',correct:false},
      {text:'خياشيم',correct:false},
    ],
    explanation:'الخنفساء حشرة لها ست أرجل وقرنا استشعار وغطاء خارجي صلب.',
    goldenRule:'الحشرة = 6 أرجل + قرنا استشعار + غطاء صلب.',
    feedbackQuestion:{question:'كم عدد أرجل الخنفساء؟',options:[{text:'ست أرجل',correct:true},{text:'أربع',correct:false},{text:'ثمان',correct:false},{text:'اثنتان',correct:false}]},
  },
  {
    id:'u1q45', unit:'u1', lesson:'u1l5', page:56, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'قرنا الاستشعار يساعدان الحشرات على:',
    paragraph:'قَرْنا الِاسْتِشْعار يُساعِدانِ الحَشَراتِ عَلى الإِحْساسِ وَالتَّذَوُّقِ وَالشَّم. (ص56)',
    image:'https://images.unsplash.com/photo-1583197014638-9b3c2c5e6e1e?w=600',
    options:[
      {text:'الإحساس والتذوق والشم',correct:true},
      {text:'الطيران',correct:false},
      {text:'السباحة',correct:false},
      {text:'الأكل',correct:false},
    ],
    explanation:'قرنا الاستشعار يساعدان الحشرات على الإحساس والتذوق والشم.',
    goldenRule:'قرنا الاستشعار = إحساس + تذوق + شم للحشرة.',
    feedbackQuestion:{question:'ماذا يساعد قرنا الاستشعار الحشرة عليه؟',options:[{text:'الإحساس والتذوق والشم',correct:true},{text:'الطيران',correct:false},{text:'القفز',correct:false},{text:'السباحة',correct:false}]},
  },
  {
    id:'u1q46', unit:'u1', lesson:'u1l5', page:57, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'اليعسوب لافقاري له:',
    paragraph:'لِليَعْسُوبِ غِطاءٌ صُلْب، وَلَهُ أَجْنِحَةٌ يَطِيرُ بِها، وَيَهْرُبُ مِنْ أَعْدائِه. (ص57)',
    image:'https://images.unsplash.com/photo-1461301214746-1f3c628b9c70?w=600',
    options:[
      {text:'غطاء صلب وأجنحة يطير بها',correct:true},
      {text:'ريش',correct:false},
      {text:'خياشيم',correct:false},
      {text:'شعر',correct:false},
    ],
    explanation:'اليعسوب له غطاء صلب وأجنحة يطير بها ويهرب من أعدائه.',
    goldenRule:'اليعسوب = لافقاري + أجنحة + يهرب من الأعداء.',
    feedbackQuestion:{question:'كيف يحمي اليعسوب نفسه من أعدائه؟',options:[{text:'يهرب بطيرانه',correct:true},{text:'يختبئ تحت الأرض',correct:false},{text:'يلسع',correct:false},{text:'يلدغ',correct:false}]},
  },
  {
    id:'u1q47', unit:'u1', lesson:'u1l5', page:57, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف الحيوانات: فقارية أم لافقارية؟',
    paragraph:'اللافَقارِيَّات: خُنْفُساء، يَعْسُوب، قَنْدِيلُ بَحْر، دُودَةُ أَرْض. الفَقارِيَّات: جَمَل، سَمَكَة، ضَفْدَع. (ص56-57)',
    categories:['فقارية 🦴','لافقارية 🐛'],
    items:[
      {text:'الخنفساء',correct_category:1},
      {text:'الجمل',correct_category:0},
      {text:'اليعسوب',correct_category:1},
      {text:'السمكة',correct_category:0},
      {text:'قنديل البحر',correct_category:1},
      {text:'الضفدع',correct_category:0},
    ],
    explanation:'الفقارية لها عمود فقري (جمل، سمكة، ضفدع). اللافقارية بلا عمود فقري (خنفساء، يعسوب، قنديل بحر).',
    goldenRule:'فقارية = لها عمود فقري. لافقارية = بلا عمود فقري.',
  },
  {
    id:'u1q48', unit:'u1', lesson:'u1l5', page:57, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'دودة الأرض من الحيوانات اللافقارية.',
    paragraph:'دُودَةُ الأَرْضِ مِنَ اللافَقارِيَّات. (ص57)',
    image:'https://images.unsplash.com/photo-1597223557154-780c3c2e5b58?w=600',
    correctAnswer:true,
    explanation:'دودة الأرض لافقاري لأنها ليس لها عمود فقري.',
    goldenRule:'دودة الأرض = لافقاري تعيش في التربة.',
    feedbackQuestion:{question:'أين تعيش دودة الأرض؟',options:[{text:'في التربة',correct:true},{text:'في الجو',correct:false},{text:'في الماء',correct:false},{text:'في الجبال',correct:false}]},
  },
  {
    id:'u1q49', unit:'u1', lesson:'u1l5', page:57, type:'multipleChoice',
    bloom:'apply', difficulty:'medium',
    question:'كيف يمكن تصنيف الأسد والضفدع معاً؟',
    paragraph:'أُصَنِّفُ. كَيْفَ يُمْكِنُ أَنْ أُصَنِّفَ كُلًّا مِنَ الأَسَدِ والضَّفْدَع؟ (ص57)',
    image:'https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=600',
    options:[
      {text:'كلاهما من الفقاريات',correct:true},
      {text:'كلاهما من اللافقاريات',correct:false},
      {text:'الأسد لافقاري',correct:false},
      {text:'الضفدع لا يصنف',correct:false},
    ],
    explanation:'الأسد ثديي والضفدع برمائي، لكن كلاهما من الفقاريات لأن لهما عموداً فقرياً.',
    goldenRule:'التصنيف يجمع المتشابه: الأسد والضفدع فقاريات.',
    feedbackQuestion:{question:'ما المجموعة الكبيرة التي يندرج تحتها الأسد والضفدع؟',options:[{text:'الفقاريات',correct:true},{text:'اللافقاريات',correct:false},{text:'الطيور',correct:false},{text:'الأسماك',correct:false}]},
  },
  {
    id:'u1q50', unit:'u1', lesson:'u1l5', page:57, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'لماذا تبقى الحيوانات اللافقارية آمنة؟',
    paragraph:'كَيْفَ تَبْقى الحَيَوَاناتُ اللافَقارِيَّةُ آمِنَة؟ (ص57)',
    image:'https://images.unsplash.com/photo-1597223557154-780c3c2e5b58?w=600',
    options:[
      {text:'بأغطية صلبة أو باللسع أو بالهروب',correct:true},
      {text:'بالطيران دائماً',correct:false},
      {text:'بالأجنحة فقط',correct:false},
      {text:'بالأصداف فقط',correct:false},
    ],
    explanation:'اللافقاريات تحمي نفسها بطرق مختلفة: أغطية صلبة، لسع (قنديل البحر)، هروب (اليعسوب).',
    goldenRule:'حماية اللافقاريات: غطاء صلب + لسع + هروب.',
    feedbackQuestion:{question:'كيف يحمي قنديل البحر نفسه؟',options:[{text:'باللسع',correct:true},{text:'بالأجنحة',correct:false},{text:'بالأصداف',correct:false},{text:'بالصوت',correct:false}]},
  },

  // ─── الفصل الثاني | الدرس 6: دورة حياة الحيوانات (ص60-74) ─────────────
  {
    id:'u1q51', unit:'u1', lesson:'u1l6', page:62, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'دورة الحياة تبين:',
    paragraph:'دَوْرَةُ الحَياةِ تُبَيِّنُ كَيْفَ يَبْدَأُ الحَيَوانُ حَياتَهُ، وَكَيْفَ يَنْمُو لِيَصِيرَ كَبِيراً وَيُنْتِجَ صِغاراً ثُمَّ يَمُوت. (ص63)',
    image:'https://images.unsplash.com/photo-1502786129293-79981df4dc2d?w=600',
    options:[
      {text:'كيف يبدأ الحيوان حياته وينمو ويكبر',correct:true},
      {text:'كيف يأكل الحيوان',correct:false},
      {text:'كيف ينام الحيوان',correct:false},
      {text:'كيف يلعب الحيوان',correct:false},
    ],
    explanation:'دورة الحياة تبين كيف يبدأ الحيوان حياته وينمو ليصير كبيراً ثم ينتج صغاراً ثم يموت.',
    goldenRule:'دورة الحياة = ميلاد ← نمو ← نضج ← صغار ← موت.',
    feedbackQuestion:{question:'ما المرحلة الأخيرة في دورة الحياة؟',options:[{text:'الموت',correct:true},{text:'الولادة',correct:false},{text:'النمو',correct:false},{text:'اللعب',correct:false}]},
  },
  {
    id:'u1q52', unit:'u1', lesson:'u1l6', page:62, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'الحشرات والطيور والأسماك والزواحف والبرمائيات كلها:',
    paragraph:'الحَشَراتُ والطُّيُورُ والأَسْماكُ والزَّواحِفُ والبَرْمائِيَّاتُ كُلُّها تَبِيض. (ص62)',
    image:'https://images.unsplash.com/photo-1518709268805-4e8a06fbc85a?w=600',
    options:[
      {text:'تبيض',correct:true},
      {text:'تلد',correct:false},
      {text:'لا تتكاثر',correct:false},
      {text:'تنقسم',correct:false},
    ],
    explanation:'الحشرات والطيور والأسماك والزواحف والبرمائيات كلها تبيض.',
    goldenRule:'الطيور + الأسماك + الزواحف + البرمائيات + الحشرات = تبيض.',
    feedbackQuestion:{question:'أي الحيوانات التالية تلد صغاراً وترضعها؟',options:[{text:'الثدييات',correct:true},{text:'الطيور',correct:false},{text:'الأسماك',correct:false},{text:'الزواحف',correct:false}]},
  },
  {
    id:'u1q53', unit:'u1', lesson:'u1l6', page:62, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'أما الثدييات فإنها:',
    paragraph:'أَمَّا الثَّدْيِيَّاتُ فَتَلِدُ صِغاراً، وَتُرْضِعُها. (ص62)',
    image:'https://images.unsplash.com/photo-1543589030-ff4c0d2c3c5e?w=600',
    options:[
      {text:'تلد صغاراً وترضعها',correct:true},
      {text:'تبيض',correct:false},
      {text:'لا تتكاثر',correct:false},
      {text:'تنقسم',correct:false},
    ],
    explanation:'الثدييات تلد صغاراً وترضعها بالحليب، بخلاف الطيور والأسماك.',
    goldenRule:'الثدييات = تلد + ترضع صغارها بالحليب.',
    feedbackQuestion:{question:'كيف تتكاثر الثدييات؟',options:[{text:'تلد صغاراً وترضعها',correct:true},{text:'تبيض',correct:false},{text:'تنقسم',correct:false},{text:'لا تتكاثر',correct:false}]},
  },
  {
    id:'u1q54', unit:'u1', lesson:'u1l6', page:62, type:'ordering',
    bloom:'apply', difficulty:'medium',
    question:'رتّب مراحل دورة حياة الماعز:',
    paragraph:'دَوْرَةُ حَياةِ الماعِز: ماعِزٌ حَدِيثُ الوِلادَة → ماعِزٌ صَغِير → ماعِزٌ مُكْتَمِلُ النُّمُو. (ص62)',
    image:'https://images.unsplash.com/photo-1545241047-6083a3684587?w=600',
    items:['ماعز مكتمل النمو','ماعز حديث الولادة','ماعز صغير'],
    correctOrder:[1,2,0],
    explanation:'الماعز يبدأ حديث الولادة ثم ينمو ليصير صغيراً ثم مكتمل النمو.',
    goldenRule:'دورة حياة الماعز: حديث الولادة ← صغير ← مكتمل النمو.',
  },
  {
    id:'u1q55', unit:'u1', lesson:'u1l6', page:62, type:'ordering',
    bloom:'apply', difficulty:'hard',
    question:'رتّب مراحل دورة حياة الدجاج:',
    paragraph:'دَوْرَةُ حَياةِ الدَّجاج: الكُتْكُوتُ يَفْقِسُ البيضَةَ → يَكْبَر → دَجاجَةٌ أَوْ دِيكٌ مُكْتَمِلُ النُّمُو. (ص62-63)',
    image:'https://images.unsplash.com/photo-1518709268805-4e8a06fbc85a?w=600',
    items:['دجاجة مكتملة النمو','البيضة','الكتكوت'],
    correctOrder:[1,2,0],
    explanation:'الدجاجة تبدأ من البيضة ثم يفقس الكتكوت ثم يكبر ليصير دجاجة مكتملة.',
    goldenRule:'دورة حياة الدجاج: بيضة ← كتكوت ← دجاجة مكتملة.',
  },
  {
    id:'u1q56', unit:'u1', lesson:'u1l6', page:64, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'دورة حياة الفراشة تبدأ بـ:',
    paragraph:'تَبْدَأُ الفَراشَةُ حَياتَها مِنْ بَيْضَة، يَتَكَوَّنُ داخِلَها يَرْقَة. (ص64)',
    image:'https://images.unsplash.com/photo-1530248637725-3f3c9c3e3c2e?w=600',
    options:[
      {text:'البيضة',correct:true},
      {text:'الفراشة مباشرة',correct:false},
      {text:'اليرقة مباشرة',correct:false},
      {text:'العذراء مباشرة',correct:false},
    ],
    explanation:'الفراشة تبدأ حياتها من بيضة ثم تتكون داخلها يرقة.',
    goldenRule:'دورة حياة الفراشة: بيضة ← يرقة ← عذراء ← فراشة.',
    feedbackQuestion:{question:'ما المرحلة الأولى في حياة الفراشة؟',options:[{text:'البيضة',correct:true},{text:'اليرقة',correct:false},{text:'العذراء',correct:false},{text:'الفراشة',correct:false}]},
  },
  {
    id:'u1q57', unit:'u1', lesson:'u1l6', page:64, type:'ordering',
    bloom:'apply', difficulty:'hard',
    question:'رتّب مراحل دورة حياة الفراشة:',
    paragraph:'دَوْرَةُ حَياةِ الفَراشَة: بَيْضَة → يَرْقَة → عَذْراء (الشَّرْنَقَة) → فَراشَة. (ص64)',
    image:'https://images.unsplash.com/photo-1530248637725-3f3c9c3e3c2e?w=600',
    items:['الفراشة','البيضة','العذراء','اليرقة'],
    correctOrder:[1,3,2,0],
    explanation:'الفراشة: بيضة ← يرقة ← عذراء (شرنقة) ← فراشة مكتملة.',
    goldenRule:'4 مراحل للفراشة: بيضة ← يرقة ← عذراء ← فراشة.',
  },
  {
    id:'u1q58', unit:'u1', lesson:'u1l6', page:64, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'عندما تصير اليرقة جاهزة للتغير:',
    paragraph:'عِنْدَما تَصِيرُ جاهِزَةً لِلتَّغَيُّر تَتَوَقَّفُ عَنِ الحَرَكَة، وَيُصْبِحُ جِلْدُها قِشْرَةً صُلْبَة. (ص64)',
    image:'https://images.unsplash.com/photo-1530248637725-3f3c9c3e3c2e?w=600',
    options:[
      {text:'تتوقف عن الحركة ويصبح جلدها قشرة صلبة',correct:true},
      {text:'تطير بعيداً',correct:false},
      {text:'تنام طويلاً',correct:false},
      {text:'تموت',correct:false},
    ],
    explanation:'عندما تصير اليرقة جاهزة للتغير تتوقف عن الحركة ويصبح جلدها قشرة صلبة (العذراء/الشرنقة).',
    goldenRule:'العذراء (الشرنقة) = يرقة متوقفة جلدها قشرة صلبة تتغير بداخلها.',
    feedbackQuestion:{question:'ما اسم المرحلة التي تتغير فيها اليرقة داخل القشرة؟',options:[{text:'العذراء (الشرنقة)',correct:true},{text:'البيضة',correct:false},{text:'الفراشة',correct:false},{text:'الكتكوت',correct:false}]},
  },
  {
    id:'u1q59', unit:'u1', lesson:'u1l6', page:64, type:'trueFalse',
    bloom:'understand', difficulty:'medium',
    question:'بعض الحيوانات لا تشبه آباءها وهي صغيرة، بل تتغير خلال دورة حياتها.',
    paragraph:'بَعْضُ الحَيَوَانات — وَمِنْها الفَراشاتُ والضَّفادِعُ وسُرْطاناتُ البَحْر — لا تُشْبِهُ آباءَها وَهِيَ صَغِيرَة، بَلْ تَتَغَيَّرُ خِلالَ دَوْرَةِ حَياتِها. (ص64)',
    image:'https://images.unsplash.com/photo-1573529287898-5e5b9f7b4c2e?w=600',
    correctAnswer:true,
    explanation:'الفراشة والضفدع لا يشبهان آباءهما وهما صغيران (يرقة وأبو ذنيبة) ثم يتغيران.',
    goldenRule:'الفراشة (يرقة) والضفدع (أبو ذنيبة) لا يشبهان آباءهما وهما صغيران.',
    feedbackQuestion:{question:'أي حيوان لا يشبه والديه وهو صغير؟',options:[{text:'الفراشة (يرقة)',correct:true},{text:'الماعز',correct:false},{text:'الجمل',correct:false},{text:'القط',correct:false}]},
  },
  {
    id:'u1q60', unit:'u1', lesson:'u1l6', page:63, type:'multipleChoice',
    bloom:'remember', difficulty:'medium',
    question:'كم شهراً يستغرق جنين الإنسان لينمو ويولد؟',
    paragraph:'حَقِيقَة: يَسْتَغْرِقُ جَنِينُ الإِنْسانِ حَوالَيْ ٩ أَشْهُر لِيَنْمُوَ وَيُولَد. (ص63)',
    image:'https://images.unsplash.com/photo-1502786129293-79981df4dc2d?w=600',
    options:[
      {text:'٩ أشهر',correct:true},
      {text:'٦ أشهر',correct:false},
      {text:'٣ أشهر',correct:false},
      {text:'١٢ شهراً',correct:false},
    ],
    explanation:'جنين الإنسان يستغرق حوالي ٩ أشهر لينمو ويولد.',
    goldenRule:'جنين الإنسان = ٩ أشهر في بطن أمه.',
    feedbackQuestion:{question:'كم شهراً يستغرق جنين الماعز؟',options:[{text:'٦ أشهر',correct:true},{text:'٩ أشهر',correct:false},{text:'٣ أشهر',correct:false},{text:'١٢ شهراً',correct:false}]},
  },
  {
    id:'u1q61', unit:'u1', lesson:'u1l6', page:64, type:'multipleChoice',
    bloom:'apply', difficulty:'hard',
    question:'اليرقة تخرج من البيضة و:',
    paragraph:'تَخْرُجُ اليرَقَةُ مِنَ البيضَة، وَتَأْكُلُ النَّباتات، وَتَنْمُو. (ص64)',
    image:'https://images.unsplash.com/photo-1530248637725-3f3c9c3e3c2e?w=600',
    options:[
      {text:'تأكل النباتات وتنمو',correct:true},
      {text:'تطير في الجو',correct:false},
      {text:'تبني عشاً',correct:false},
      {text:'تلد صغاراً',correct:false},
    ],
    explanation:'اليرقة تخرج من البيضة وتأكل النباتات وتنمو حتى تصير جاهزة للتغير.',
    goldenRule:'اليرقة تأكل وتنمو استعداداً لمرحلة العذراء.',
    feedbackQuestion:{question:'ماذا تأكل اليرقة؟',options:[{text:'النباتات',correct:true},{text:'اللحم',correct:false},{text:'السمك',correct:false},{text:'الحشرات',correct:false}]},
  },
  {
    id:'u1q62', unit:'u1', lesson:'u1l6', page:62, type:'matching',
    bloom:'understand', difficulty:'medium',
    question:'صِل كل حيوان بطريقة تكاثره:',
    paragraph:'الحَشَراتُ والطُّيُورُ والأَسْماكُ تَبِيض. أَمَّا الثَّدْيِيَّاتُ فَتَلِدُ صِغاراً وَتُرْضِعُها. (ص62)',
    pairs:[
      {left:'الدجاجة',right:'تبيض'},
      {left:'الماعز',right:'تلد وترضع'},
      {left:'السمكة',right:'تبيض'},
      {left:'الجمل',right:'تلد وترضع'},
    ],
    explanation:'الطيور والأسماك والزواحف والحشرات تبيض، والثدييات تلد وترضع.',
    goldenRule:'التكاثر: بياض (طيور/أسماك/زواحف) ← ولود (ثدييات).',
  },
  {
    id:'u1q63', unit:'u1', lesson:'u1l6', page:64, type:'classify',
    bloom:'analyze', difficulty:'hard',
    question:'صنّف الحيوانات: تشبه آباءها صغيرة أم لا؟',
    paragraph:'بَعْضُ الحَيَوَانات لا تُشْبِهُ آباءَها وَهِيَ صَغِيرَة، بَلْ تَتَغَيَّرُ خِلالَ دَوْرَةِ حَياتِها. (ص64)',
    categories:['تشبه آباءها صغيرة 🐑','لا تشبه آباءها صغيرة 🐛'],
    items:[
      {text:'الماعز',correct_category:0},
      {text:'الفراشة',correct_category:1},
      {text:'الضفدع',correct_category:1},
      {text:'الدجاجة',correct_category:0},
      {text:'الجمل',correct_category:0},
      {text:'سرطان البحر',correct_category:1},
    ],
    explanation:'الماعز والدجاجة والجمل تشبه آباءها صغيرة. الفراشة والضفدع وسرطان البحر لا تشبه آباءها صغيرة.',
    goldenRule:'بعض الحيوانات تتغير شكلها أثناء دورة حياتها (الفراشة، الضفدع).',
  },
  {
    id:'u1q64', unit:'u1', lesson:'u1l6', page:62, type:'fillBlank',
    bloom:'apply', difficulty:'easy',
    question:'أكمل: جميع الحيوانات لها ___ حياة.',
    paragraph:'جَمِيعُ الحَيَوَاناتِ لَها دَوْرَةُ حَياة. (ص62)',
    blanks:['دورة'],
    wordBank:['دورة','بيت','صوت','لون'],
    explanation:'جميع الحيوانات لها دورة حياة: ميلاد ← نمو ← نضج ← صغار ← موت.',
    goldenRule:'كل حيوان له دورة حياة كاملة.',
  },
  {
    id:'u1q65', unit:'u1', lesson:'u1l6', page:65, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'فيم تتشابه دورة حياة الماعز ودورة حياة الإنسان؟',
    paragraph:'فِيمَ تَتَشابَهُ دَوْرَةُ حَياةِ الماعِزِ وَدَوْرَةُ حَياةِ الإِنْسان؟ (ص65)',
    image:'https://images.unsplash.com/photo-1543589030-ff4c0d2c3c5e?w=600',
    options:[
      {text:'كلاهما من الثدييات يلد ويرضع صغاره',correct:true},
      {text:'كلاهما يبيض',correct:false},
      {text:'كلاهما يطير',correct:false},
      {text:'كلاهما يعيش في الماء',correct:false},
    ],
    explanation:'الماعز والإنسان من الثدييات، كلاهما يلد ويرضع صغاره وله دورة حياة متشابهة.',
    goldenRule:'الثدييات (الماعز، الإنسان، الجمل) تلد وترضع وتشبه دورات حياتها.',
    feedbackQuestion:{question:'ما الصفة المشتركة بين الماعز والإنسان؟',options:[{text:'كلاهما ثديي يلد ويرضع',correct:true},{text:'كلاهما يبيض',correct:false},{text:'كلاهما يطير',correct:false},{text:'كلاهما يعيش في الماء',correct:false}]},
  },
];

export default U1_QUESTIONS;