// الاجتماعيات - الصف الثاني - الفصل الأول - أسئلة إضافية الوحدتين 1 و 2
export const SOCIAL_EXTRA_1 = [
  // ── الوحدة 1: أسرتي وبيتي (ص 6-18) ──
  { id:'s46',page:6,type:'multipleChoice',bloom:'remember',difficulty:'easy',
    question:'الأسرة الكبيرة تشمل بالإضافة للأسرة الصغيرة:',
    paragraph:'الأسرة الكبيرة تشمل الأجداد والأعمام والعمات والأخوال والخالات. (ص6)',
    options:[{text:'الأجداد والأعمام والعمات',correct:true},{text:'الجيران فقط',correct:false},{text:'المعلمين',correct:false},{text:'الغرباء',correct:false}],
    explanation:'الأسرة الكبيرة = الصغيرة + الأجداد + الأعمام + العمات + الأخوال + الخالات.',
    goldenRule:'أسرة كبيرة = أسرة صغيرة + أجداد + أعمام + أخوال.' },
  { id:'s47',page:7,type:'multipleChoice',bloom:'understand',difficulty:'easy',
    question:'أفضل وسيلة لمعاملة الوالدين:',
    paragraph:'طاعة الوالدين ومعاملتهما بلطف من أعظم الأعمال. (ص7)',
    options:[{text:'اللطف والطاعة والاحترام',correct:true},{text:'الصراخ عليهما',correct:false},{text:'عصيانهما',correct:false},{text:'إهمالهما',correct:false}],
    explanation:'اللطف + الطاعة + الاحترام = معاملة المسلم لوالديه.',
    goldenRule:'والداك = لطف + طاعة + احترام = رضا الله.' },
  { id:'s48',page:7,type:'trueFalse',bloom:'evaluate',difficulty:'medium',
    question:'الأم لها فضل كبير لأنها حملت ورضعت وربت.',
    paragraph:'الأم حملت ورضعت وربت، فلها فضل عظيم في الإسلام. (ص7)',
    correctAnswer:true,
    explanation:'الأم تحملت مشقة الحمل والرضاعة والتربية، فلها أعظم الفضل.',
    goldenRule:'الأم = حمل + رضاعة + تربية = الجنة تحت قدميها.' },
  { id:'s49',page:8,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف الأعمال إلى واجبات وسلوكيات خاطئة:',
    paragraph:'الواجبات: ترتيب الغرفة، المساعدة، الدراسة. الخاطئ: الإهمال، العصيان. (ص8)',
    categories:['واجبات صحيحة ✅','سلوكيات خاطئة ❌'],
    items:[
      {text:'ترتيب الغرفة',correct_category:0},{text:'مساعدة الأم',correct_category:0},{text:'الدراسة',correct_category:0},{text:'احترام الأب',correct_category:0},
      {text:'إهمال الواجب',correct_category:1},{text:'عصيان الوالدين',correct_category:1},{text:'الصراخ',correct_category:1},
    ],
    explanation:'واجبات: ترتيب، مساعدة، دراسة، احترام. خاطئ: إهمال، عصيان، صراخ.',
    goldenRule:'واجبات الطالب = ترتيب + مساعدة + دراسة + احترام.' },
  { id:'s50',page:9,type:'multipleChoice',bloom:'remember',difficulty:'easy',
    question:'الوالد الذي ينفق على الأسرة ويحميها يُسمى:',
    paragraph:'الأب هو راعي الأسرة الذي ينفق عليها ويحميها. (ص9)',
    options:[{text:'راعي الأسرة',correct:true},{text:'ضيف',correct:false},{text:'غريب',correct:false},{text:'جار',correct:false}],
    explanation:'الأب = راعي = ينفق + يحمي + يرعى.',
    goldenRule:'الأب راعي الأسرة = إنفاق + حماية + رعاية.' },
  { id:'s51',page:10,type:'trueFalse',bloom:'remember',difficulty:'easy',
    question:'الإخوة والإخوات من الأسرة الصغيرة.',
    paragraph:'الإخوة والإخوات يعيشون مع الأب والأم في الأسرة الصغيرة. (ص10)',
    correctAnswer:true,
    explanation:'الإخوة والإخوات = أسرة صغيرة مع الأب والأم.',
    goldenRule:'إخوة + أخوات + أب + أم = أسرة صغيرة.' },
  { id:'s52',page:11,type:'matching',bloom:'understand',difficulty:'medium',
    question:'صِل كل عضو بفضله عليك:',
    paragraph:'الأب ينفق، الأم تربي، الجد يحب، الأخت تساعد. (ص11)',
    pairs:[{left:'الأب',right:'ينفق ويرعى'},{left:'الأم',right:'تربي وتغذي'},{left:'الجد',right:'يدعو ويحب'},{left:'الأخت',right:'تساعد وتشارك'}],
    explanation:'لكل عضو فضل مختلف تجب مقابلته بالبر والإحسان.',
    goldenRule:'بر الأسرة = رد الجميل لكل عضو.' },
  { id:'s53',page:12,type:'multipleChoice',bloom:'understand',difficulty:'medium',
    question:'إذا اختل الإخوة في الرأي، ما الصواب؟',
    paragraph:'حسن الحوار وعدم الشجار من أدب الإخوة. (ص12)',
    options:[{text:'الحوار بهدوء واحترام',correct:true},{text:'الشجار',correct:false},{text:'الضرب',correct:false},{text:'الهجر',correct:false}],
    explanation:'الحوار الهادئ يحل الخلاف، والشجار يفسد العلاقة.',
    goldenRule:'خلاف = حوار + احترام = حل، لا شجار = خراب.' },
  { id:'s54',page:13,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "بر الوالدين من أعظم ___ في الإسلام."',
    paragraph:'بر الوالدين من أعظم الفرائض في الإسلام. (ص7)',
    blanks:['الفرائض'],
    wordBank:['الفرائض','الذنوب','النواهي','الخطايا'],
    explanation:'بر الوالدين فرض عظيم قرنه الله بالتوحيد.',
    goldenRule:'بر الوالدين = فرض = قرن مع التوحيد.' },
  { id:'s55',page:14,type:'ordering',bloom:'apply',difficulty:'medium',
    question:'رتّب واجبات الطالب الصباحية قبل المدرسة:',
    paragraph:'الاستيقاظ، ترتيب السرير، الوضوء، الإفطار، الذهاب للمدرسة. (ص14)',
    items:['الذهاب للمدرسة','الإفطار','الوضوء','ترتيب السرير','الاستيقاظ'],
    correctOrder:[4,3,2,1,0],
    explanation:'استيقاظ ← ترتيب سرير ← وضوء ← إفطار ← مدرسة.',
    goldenRule:'صباح منظم = استيقاظ ← ترتيب ← وضوء ← إفطار ← مدرسة.' },
  { id:'s56',page:14,type:'trueFalse',bloom:'evaluate',difficulty:'medium',
    question:'ترك أغراضك مبعثرة في البيت من احترام الأسرة.',
    paragraph:'ترتيب الأغراض احترام للأسرة والبيت. (ص14)',
    correctAnswer:false,
    explanation:'النظام احترام، والفوضى إهانة للبيت والأسرة.',
    goldenRule:'بيت مرتب = احترام. بيت مبعثر = إهانة.' },
  { id:'s57',page:15,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف الأعمال في البيت:',
    paragraph:'ترتيب الغرفة، تنظيف الأثاث، مساعدة الأم = واجبات. اللعب كثيراً، الإهمال = خاطئ. (ص15)',
    categories:['أعمال صحيحة ✅','أعمال خاطئة ❌'],
    items:[
      {text:'ترتيب الغرفة',correct_category:0},{text:'تنظيف الأثاث',correct_category:0},{text:'مساعدة الأم',correct_category:0},
      {text:'اللعب طول اليوم',correct_category:1},{text:'إهمال الدراسة',correct_category:1},{text:'ترك القمامة',correct_category:1},
    ],
    explanation:'صحيح: ترتيب، تنظيف، مساعدة. خاطئ: إطالة اللعب، إهمال، قذارة.',
    goldenRule:'مسؤوليات البيت = ترتيب + تنظيف + مساعدة.' },
  { id:'s58',page:16,type:'multipleChoice',bloom:'understand',difficulty:'easy',
    question:'الإخوة الصغار يحتاجون إلى:',
    paragraph:'الإخوة الصغار يحتاجون رعاية ولطف وحب من الكبار. (ص16)',
    options:[{text:'رعاية ولطف وحب',correct:true},{text:'إهمال',correct:false},{text:'ضرب',correct:false},{text:'هجر',correct:false}],
    explanation:'الصغار يحتاجون رعاية ولطفاً وحباً، لا قسوة ولا إهمالاً.',
    goldenRule:'إخوة صغار = رعاية + لطف + حب = أسرة سعيدة.' },
  { id:'s59',page:17,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل عمل بأثره على الأسرة:',
    paragraph:'الطاعة = رضا الوالدين، الشجار = حزن، المساعدة = راحة، الإهمال = تعب. (ص17)',
    pairs:[{left:'طاعة الوالدين',right:'رضا الوالدين'},{left:'الشجار',right:'حزن الأسرة'},{left:'المساعدة',right:'راحة الأم'},{left:'الإهمال',right:'تعب الأسرة'}],
    explanation:'كل عمل له أثر: طاعة=رضا، شجار=حزن، مساعدة=راحة، إهمال=تعب.',
    goldenRule:'عملك = أثر. اختر الأثر الحسن.' },
  { id:'s60',page:18,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "البيت النظيف يجلب ___ لساكنيه."',
    paragraph:'البيت النظيف يجلب الراحة والصحة لساكنيه. (ص18)',
    blanks:['الراحة'],
    wordBank:['الراحة','التعب','المرض','الحزن'],
    explanation:'النظافة = راحة + صحة + بركة.',
    goldenRule:'بيت نظيف = راحة + صحة + بركة.' },
  { id:'s61',page:6,type:'trueFalse',bloom:'remember',difficulty:'easy',
    question:'الأجداد لهم فضل تربية الآباء فيستحقون البر.',
    paragraph:'الأجداد ربّوا الآباء فلهم فضل البر والإحسان. (ص6)',
    correctAnswer:true,
    explanation:'الجد والجدة لهما فضل تربية والديك، فبرهما واجب.',
    goldenRule:'بر الأجداد = بر الوالدين في الفضل.' },
  { id:'s62',page:8,type:'multipleChoice',bloom:'apply',difficulty:'medium',
    question:'لو كانت أمك مريضة، ما الصواب أن تفعل؟',
    paragraph:'رعاية الأم المريضة من بر الوالدين. (ص8)',
    options:[{text:'أرعاها وأطمئن عليها وأساعدها',correct:true},{text:'أتركها وألعب',correct:false},{text:'أشكو منها',correct:false},{text:'أهجرها',correct:false}],
    explanation:'رعاية المريض خاصة الأم من أعظم البر.',
    goldenRule:'أم مريضة = رعاية + اطمئنان + مساعدة.',
    feedbackQuestion:{question:'لو طلب والدك مساعدتك في حمل شيء، ماذا تفعل؟',
      options:[{text:'أساعده فوراً بابتسامة',correct:true},{text:'أرفض',correct:false},{text:'أؤجل',correct:false},{text:'أشتكي',correct:false}],
      explanation:'مساعدة الوالد واجب فوري بحب.'} },
  { id:'s63',page:10,type:'ordering',bloom:'apply',difficulty:'medium',
    question:'رتّب حسب الصلة من الأقرب للأسرة:',
    paragraph:'الأسرة الصغيرة أقرب من الكبيرة، والكبيرة أقرب من الجيران. (ص10)',
    items:['الجيران','العمات','الأخ','الأب'],
    correctOrder:[3,2,1,0],
    explanation:'الأب (أقرب) ← الأخ ← العمات ← الجيران (أبعد).',
    goldenRule:'قرب الصلة = قوة الرابطة = أولوية البر.' },
  { id:'s64',page:12,type:'trueFalse',bloom:'evaluate',difficulty:'medium',
    question:'الإسلام حذر من العقوق وعدم البر بالوالدين.',
    paragraph:'العقوق من أكبر الذنوب في الإسلام. (ص7)',
    correctAnswer:true,
    explanation:'العقوق = ذنب كبير. البر = فضل عظيم.',
    goldenRule:'العقوق = ذنب. البر = فضل. اختر البر.' },
  { id:'s65',page:14,type:'fillBlank',bloom:'understand',difficulty:'easy',
    question:'أكمل: "أحافظ على ___ بيتي فلا أكسر الأثاث."',
    paragraph:'المحافظة على أثاث البيت من أدب الطالب. (ص14)',
    blanks:['أثاث'],
    wordBank:['أثاث','زجاج','حديقة','سيارة'],
    explanation:'أثاث البيت أمانة، حفظه احترام للأسرة.',
    goldenRule:'أثاث البيت = أمانة = حفظ = احترام.' },
  { id:'s66',page:16,type:'multipleChoice',bloom:'remember',difficulty:'easy',
    question:'من آداب الطعام مع الأسرة:',
    paragraph:'غسل اليدين، الأكل باليمين، عدم الإسراف من آداب الطعام. (ص16)',
    options:[{text:'غسل اليدين + اليمين + عدم الإسراف',correct:true},{text:'الأكل بشمال',correct:false},{text:'الإسراف',correct:false},{text:'الأكل وحدك',correct:false}],
    explanation:'آداب الطعام: غسل، يمين، عدم إسراف، مشاركة.',
    goldenRule:'طعام مؤدب = غسل + يمين + قصد + مشاركة.' },
  { id:'s67',page:17,type:'classify',bloom:'analyze',difficulty:'hard',
    question:'صنّف العبارات حسب تأثيرها:',
    paragraph:'كلمة طيبة، مساعدة، ابتسامة = إيجابي. صراخ، شجار، سب = سلبي. (ص17)',
    categories:['تأثير إيجابي 😊','تأثير سلبي 😞'],
    items:[
      {text:'كلمة طيبة',correct_category:0},{text:'مساعدة',correct_category:0},{text:'ابتسامة',correct_category:0},
      {text:'صراخ',correct_category:1},{text:'شجار',correct_category:1},{text:'سب',correct_category:1},
    ],
    explanation:'إيجابي = كلمة + مساعدة + ابتسامة. سلبي = صراخ + شجار + سب.',
    goldenRule:'الكلمة الطيبة صدقة = أثر إيجابي.' },
  { id:'s68',page:18,type:'trueFalse',bloom:'understand',difficulty:'easy',
    question:'الجلسة العائلية تقوي الروابط بين أفراد الأسرة.',
    paragraph:'الجلوس مع الأسرة وتناول الطعام معاً يقوي العلاقات. (ص18)',
    correctAnswer:true,
    explanation:'الجلسة العائلية = حب + حوار + ألفة.',
    goldenRule:'جلسة عائلية = حب + حوار = أسرة متماسكة.' },
  { id:'s69',page:6,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل فرد بدرجة قرابته:',
    paragraph:'الأب والأم أقرب، الجد والجدة أقرب من العم، العم أقرب من الجار. (ص6)',
    pairs:[{left:'الأب',right:'أقرب الناس'},{left:'الجد',right:'قريب جداً'},{left:'العم',right:'قريب'},{left:'الجار',right:'جار'}],
    explanation:'الأب أقرب، ثم الجد، ثم العم، ثم الجار.',
    goldenRule:'درجات القرابة = درجات البر والأولوية.' },
  { id:'s70',page:9,type:'multipleChoice',bloom:'evaluate',difficulty:'hard',
    question:'لو أمراك بأمر يخالف دينك، ما الصواب؟',
    paragraph:'لا طاعة لمخلوق في معصية الخالق. (ص7)',
    options:[{text:'لا أطيع في المعصية وأطيع في غيرها بأدب',correct:true},{text:'أطيع في كل شيء',correct:false},{text:'أعصيهما في كل شيء',correct:false},{text:'أهجرهما',correct:false}],
    explanation:'لا طاعة في معصية، لكن يبقى الأدب والبر فيما عدا المعصية.',
    goldenRule:'لا طاعة في معصية = بر + أدب = ميزان.' },
  { id:'s71',page:11,type:'fillBlank',bloom:'understand',difficulty:'easy',
    question:'أكمل: "أشارك إخوتي في ___ الألعاب."',
    paragraph:'المشاركة في الألعاب من آداب الإخوة. (ص11)',
    blanks:['ترتيب'],
    wordBank:['ترتيب','كسر','إتلاف','إخفاء'],
    explanation:'المشاركة في الترتيب = ألفة وتعاون.',
    goldenRule:'مشاركة + ترتيب = ألفة + محبة.' },
  { id:'s72',page:13,type:'trueFalse',bloom:'remember',difficulty:'easy',
    question:'الإسلام أوصى بالأقارب وصلة الرحم.',
    paragraph:'صلة الرحم من أعظم الأعمال في الإسلام. (ص13)',
    correctAnswer:true,
    explanation:'صلة الرحم = بر الأقارب = بركة في العمر والرزق.',
    goldenRule:'صلة الرحم = بركة + طول عمر + سعة رزق.' },
  { id:'s73',page:15,type:'ordering',bloom:'apply',difficulty:'hard',
    question:'رتّب واجباتك عند عودتك من المدرسة:',
    paragraph:'العودة، السلام، تغيير الملابس، الغداء، الواجب المدرسي. (ص15)',
    items:['الواجب المدرسي','الغداء','تغيير الملابس','السلام على الأسرة','العودة للبيت'],
    correctOrder:[4,3,2,1,0],
    explanation:'عودة ← سلام ← ملابس ← غداء ← واجب.',
    goldenRule:'عصر منظم = عودة ← سلام ← ملابس ← غداء ← واجب.' },
  { id:'s74',page:17,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف الأمور التي تقوي الأسرة:',
    paragraph:'تقوي: الحوار، الطاعة، المساعدة، الصلاة معاً. تضعف: الشجار، العقوق. (ص17)',
    categories:['تقوي الأسرة 💪','تضعف الأسرة 💔'],
    items:[
      {text:'الحوار',correct_category:0},{text:'الطاعة',correct_category:0},{text:'المساعدة',correct_category:0},{text:'الصلاة معاً',correct_category:0},
      {text:'الشجار',correct_category:1},{text:'العقوق',correct_category:1},
    ],
    explanation:'تقوي: حوار، طاعة، مساعدة، صلاة. تضعف: شجار، عقوق.',
    goldenRule:'أسرة قوية = حوار + طاعة + مساعدة + صلاة.' },

  // ── الوحدة 2: مدرستتي (ص 20-32) ──
  { id:'s75',page:20,type:'multipleChoice',bloom:'remember',difficulty:'easy',
    question:'المدرسة تعلّمنا الآداب و:',
    paragraph:'المدرسة تعلّم القراءة والكتابة والآداب والمعارف. (ص20)',
    options:[{text:'المعارف والآداب',correct:true},{text:'اللعب فقط',correct:false},{text:'النوم',correct:false},{text:'الأكل',correct:false}],
    explanation:'المدرسة = معارف + آداب + قراءة + كتابة.',
    goldenRule:'مدرسة = معارف + آداب = شخصية متكاملة.' },
  { id:'s76',page:21,type:'trueFalse',bloom:'understand',difficulty:'easy',
    question:'المدرسة بيتي الثاني يجب أن أحافظ عليها.',
    paragraph:'المدرسة بيتك الثاني فاحفظها كبيتك. (ص21)',
    correctAnswer:true,
    explanation:'المدرسة بيتك الثاني، فاحفظها كبيتك.',
    goldenRule:'مدرستي = بيتي الثاني = حفظ + محبة.' },
  { id:'s77',page:22,type:'multipleChoice',bloom:'remember',difficulty:'easy',
    question:'المعلم يحب من طلابه:',
    paragraph:'المعلم يحب من طلابه الإنصات والأدب والمثابرة. (ص22)',
    options:[{text:'الإنصات + الأدب + المثابرة',correct:true},{text:'الصراخ',correct:false},{text:'اللعب',correct:false},{text:'الإهمال',correct:false}],
    explanation:'المعلم يحب: إنصات + أدب + مثابرة + سؤال بأدب.',
    goldenRule:'طالب محبوب = إنصات + أدب + مثابرة.' },
  { id:'s78',page:23,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف سلوكيات الفصل:',
    paragraph:'صحيح: رفع اليد، الإنصات، الأدب. خاطئ: الكلام أثناء الدرس، اللعب. (ص23)',
    categories:['أدب الفصل ✅','إخلال بالنظام ❌'],
    items:[
      {text:'رفع اليد',correct_category:0},{text:'الإنصات',correct_category:0},{text:'الأدب',correct_category:0},
      {text:'الكلام أثناء الدرس',correct_category:1},{text:'اللعب بالقلم',correct_category:1},{text:'الخروج دون إذن',correct_category:1},
    ],
    explanation:'أدب: رفع يد، إنصات، أدب. إخلال: كلام، لعب، خروج.',
    goldenRule:'فصل منظّم = رفع يد + إنصات + أدب.' },
  { id:'s79',page:24,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل مرفق بوظيفته:',
    paragraph:'المكتبة للقراءة، الساحة للّعب، المختبر للتجارب، الممر للمرور. (ص24)',
    pairs:[{left:'المكتبة',right:'القراءة'},{left:'الساحة',right:'اللعب'},{left:'المختبر',right:'التجارب'},{left:'الممر',right:'المرور'}],
    explanation:'كل مرفق له وظيفة محددة في المدرسة.',
    goldenRule:'مكتبة=قراءة، ساحة=لعب، مختبر=تجربة، ممر=مرور.' },
  { id:'s80',page:25,type:'trueFalse',bloom:'understand',difficulty:'easy',
    question:'السلام على الزملاء من آداب الطالب في المدرسة.',
    paragraph:'السلام على الزملاء والمعلمين من آداب المدرسة. (ص25)',
    correctAnswer:true,
    explanation:'السلام يفتح القلوب وينشر المحبة.',
    goldenRule:'السلام = محبة + ألفة = بيئة آمنة.' },
  { id:'s81',page:26,type:'multipleChoice',bloom:'understand',difficulty:'easy',
    question:'إذا أردت السؤال في الفصل، ما الصواب؟',
    paragraph:'للسؤال ارفع يدك وانتظر إذن المعلم. (ص26)',
    options:[{text:'أرفع يدي وأنتظر الإذن',correct:true},{text:'أصرخ',correct:false},{text:'أقاطع',correct:false},{text:'أخرج',correct:false}],
    explanation:'رفع اليد = أدب + نظام + احترام.',
    goldenRule:'سؤال مؤدب = رفع يد + انتظار إذن.' },
  { id:'s82',page:27,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "أحافظ على ___ المدرسة ولا أكتب عليها."',
    paragraph:'الكتابة على الجدران إفساد للمرافق. (ص27)',
    blanks:['جدران'],
    wordBank:['جدران','كتب','حقائب','كراسي'],
    explanation:'الجدران لا للكتابة، بل للمحافظة.',
    goldenRule:'جدران المدرسة = أمانة = لا كتابة = لا تخريب.' },
  { id:'s83',page:28,type:'ordering',bloom:'apply',difficulty:'medium',
    question:'رتّب يومك في المدرسة:',
    paragraph:'الوصول، السلام، دخول الفصل، الدرس، الفسحة. (ص28)',
    items:['الفسحة','الدرس','دخول الفصل','السلام على الزملاء','الوصول للمدرسة'],
    correctOrder:[4,3,2,1,0],
    explanation:'وصول ← سلام ← فصل ← درس ← فسحة.',
    goldenRule:'يوم مدرسي = وصول ← سلام ← فصل ← درس ← فسحة.' },
  { id:'s84',page:29,type:'trueFalse',bloom:'evaluate',difficulty:'medium',
    question:'الغش في الاختبار سلوك مذموم يضر بالطالب.',
    paragraph:'الغش خيانة وظلم للنفس، والصدق نجاح حقيقي. (ص29)',
    correctAnswer:true,
    explanation:'الغش = خيانة + ظلم + خسارة. الصدق = أمانة + نجاح.',
    goldenRule:'غش = خيانة. صدق = أمانة = نجاح حقيقي.' },
  { id:'s85',page:30,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف السلوكيات في المدرسة:',
    paragraph:'إيجابي: احترام، نظافة، مساعدة. سلبي: شجار، قذارة، إهمال. (ص30)',
    categories:['سلوك إيجابي ✅','سلوك سلبي ❌'],
    items:[
      {text:'احترام المعلم',correct_category:0},{text:'نظافة الفصل',correct_category:0},{text:'مساعدة زميل',correct_category:0},
      {text:'الشجار',correct_category:1},{text:'رمي القمامة',correct_category:1},{text:'إهمال الواجب',correct_category:1},
    ],
    explanation:'إيجابي: احترام، نظافة، مساعدة. سلبي: شجار، قذارة، إهمال.',
    goldenRule:'طالب إيجابي = احترام + نظافة + مساعدة.' },
  { id:'s86',page:31,type:'matching',bloom:'understand',difficulty:'medium',
    question:'صِل كل شخصية بدورها في المدرسة:',
    paragraph:'المعلم يعلّم، المدير يدير، العامل ينظف، الطالب يتعلم. (ص31)',
    pairs:[{left:'المعلم',right:'يعلّم'},{left:'المدير',right:'يدير'},{left:'العامل',right:'ينظف'},{left:'الطالب',right:'يتعلم'}],
    explanation:'كل شخصية لها دور في منظومة المدرسة.',
    goldenRule:'مدرسة منظمة = معلم + مدير + عامل + طالب.' },
  { id:'s87',page:32,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "الحديقة في المدرسة لل___ والتنزه."',
    paragraph:'حديقة المدرسة للّعب والتنزه بين الدروس. (ص32)',
    blanks:['اللعب'],
    wordBank:['اللعب','الأكل','النوم','الدرس'],
    explanation:'حديقة المدرسة للّعب والاستراحة.',
    goldenRule:'حديقة المدرسة = راحة + لعب = تجديد نشاط.' },
  { id:'s88',page:20,type:'trueFalse',bloom:'remember',difficulty:'easy',
    question:'المدرسة لها نظام يحفظ حقوق الجميع.',
    paragraph:'نظام المدرسة ينظم الوقت والدروس والفسحة. (ص20)',
    correctAnswer:true,
    explanation:'النظام = حفظ حقوق + تنظيم وقت = نجاح.',
    goldenRule:'نظام المدرسة = حفظ حقوق + تنظيم وقت.' },
  { id:'s89',page:22,type:'multipleChoice',bloom:'evaluate',difficulty:'hard',
    question:'لو أخطأت في جواب الدرس، ما الصواب؟',
    paragraph:'الخطأ فرصة للتعلم، لا للخجل. (ص22)',
    options:[{text:'أقر بخطئي وأتعلم الصواب',correct:true},{text:'أعاند',correct:false},{text:'أكذب',correct:false},{text:'أهرب',correct:false}],
    explanation:'الخطأ طبيعي، والاعتراف به بداية التعلم.',
    goldenRule:'خطأ = اعتراف + تعلم = نمو، لا عتب + كذب = ركود.',
    feedbackQuestion:{question:'لو نسيت واجبك في البيت، ماذا تفعل؟',
      options:[{text:'أعترف وأعتذر وأحضره غداً',correct:true},{text:'أكذب',correct:false},{text:'أهرب',correct:false},{text:'أعاتب أمي',correct:false}],
      explanation:'الصدق في الاعتذار خير من الكذب.'} },
  { id:'s90',page:24,type:'trueFalse',bloom:'understand',difficulty:'easy',
    question:'الساحة مكان للّعب بحيث لا نؤذي أحداً.',
    paragraph:'اللعب في الساحة باحترام وعدم إيذاء الزملاء. (ص24)',
    correctAnswer:true,
    explanation:'اللعب بالساحة = متعة + أمان + احترام.',
    goldenRule:'لعب سليم = متعة + أمان + احترام.' },
  { id:'s91',page:26,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف أنواع الكلام في الفصل:',
    paragraph:'مسموح: سؤال، جواب، أدب. ممنوع: صراخ، شتم، كلام أثناء الدرس. (ص26)',
    categories:['كلام مسموح ✅','كلام ممنوع ❌'],
    items:[
      {text:'سؤال بأدب',correct_category:0},{text:'جواب الدرس',correct_category:0},
      {text:'صراخ',correct_category:1},{text:'شتم',correct_category:1},{text:'كلام أثناء الشرح',correct_category:1},
    ],
    explanation:'مسموح: سؤال، جواب. ممنوع: صراخ، شتم، مقاطعة.',
    goldenRule:'كلام الفصل = أدب + فائدة، لا صراخ + شتم.' },
  { id:'s92',page:28,type:'ordering',bloom:'apply',difficulty:'medium',
    question:'رتّب دخول المكتبة واختيار كتاب:',
    paragraph:'الدخول بهدوء، اختيار كتاب، القراءة، إعادة الكتاب، الخروج. (ص28)',
    items:['الخروج بهدوء','إعادة الكتاب','القراءة','اختيار كتاب','الدخول بهدوء'],
    correctOrder:[4,3,2,1,0],
    explanation:'دخول ← اختيار ← قراءة ← إعادة ← خروج.',
    goldenRule:'زيارة مكتبة = هدوء + احترام + ترتيب.' },
  { id:'s93',page:30,type:'fillBlank',bloom:'understand',difficulty:'easy',
    question:'أكمل: "أرمي القمامة في ___ لا على الأرض."',
    paragraph:'رمي القمامة في السلة من نظافة المدرسة. (ص30)',
    blanks:['السلة'],
    wordBank:['السلة','الأرض','النافذة','السبورة'],
    explanation:'القمامة في السلة، لا الأرض.',
    goldenRule:'قمامة = سلة = نظافة، لا أرض = قذارة.' },
  { id:'s94',page:32,type:'trueFalse',bloom:'evaluate',difficulty:'medium',
    question:'الأمانة في أدوات المدرسة واجبة فلا آخذ ما ليس لي.',
    paragraph:'أمانة الأدوات واجب، لا تأخذ ما لا يخصك. (ص32)',
    correctAnswer:true,
    explanation:'أدوات الزميل أمانة، أخذها خيانة.',
    goldenRule:'أمانة = حفظ + رد = فضل. خيانة = أخذ + إخفاء = ذنب.' },
  { id:'s95',page:21,type:'multipleChoice',bloom:'understand',difficulty:'easy',
    question:'المدرسة مكان آمن لأن فيها:',
    paragraph:'المدرسة آمنة بالنظام والمعلمين والتربية. (ص21)',
    options:[{text:'نظام + معلمين + تربية',correct:true},{text:'فوضى',correct:false},{text:'خطر',correct:false},{text:'إهمال',correct:false}],
    explanation:'المدرسة آمنة بالنظام والمعلمين والتربية.',
    goldenRule:'أمان المدرسة = نظام + معلمين + تربية.' },
  { id:'s96',page:23,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل وقت بنشاطه:',
    paragraph:'الدرس للتعلم، الفسحة للراحة، الصلاة للعبادة، الطعام للأكل. (ص23)',
    pairs:[{left:'وقت الدرس',right:'التعلم'},{left:'الفسحة',right:'الراحة'},{left:'وقت الصلاة',right:'العبادة'},{left:'وقت الطعام',right:'الأكل'}],
    explanation:'كل وقت له نشاطه المناسب.',
    goldenRule:'وقت مناسب + نشاط مناسب = نجاح.' },
  { id:'s97',page:25,type:'trueFalse',bloom:'remember',difficulty:'easy',
    question:'العامل الذي ينظف المدرسة يستحق الاحترام.',
    paragraph:'احترام العامل الذي ينظف المدرسة واجب. (ص25)',
    correctAnswer:true,
    explanation:'العامل يخدمك، فاحترامه احترام لخدمته.',
    goldenRule:'كل خادم للمجتمع يستحق الاحترام.' },
  { id:'s98',page:27,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "أحفظ كتبي وحقائبي في ___ نظيفة."',
    paragraph:'حفظ الكتب والحقائب في حقيبة نظيفة من آداب الطالب. (ص27)',
    blanks:['حقيبة'],
    wordBank:['حقيبة','الأرض','الشارع','الحديقة'],
    explanation:'الحقيبة تحفظ كتبك، فحافظ عليها نظيفة.',
    goldenRule:'حقيبة نظيفة = كتب محفوظة = طالب منظم.' },
  { id:'s99',page:29,type:'multipleChoice',bloom:'evaluate',difficulty:'hard',
    question:'لو شاهدت زميلاً يغش، ما الصواب؟',
    paragraph:'الغش مذموم، والنصح لأخيك خير من السكوت. (ص29)',
    options:[{text:'أنصحه بأدب وأتركه',correct:true},{text:'أساعده',correct:false},{text:'أخرس',correct:false},{text:'أشكوه للجميع',correct:false}],
    explanation:'النصح بأدب واجب، والسكوت عن الغش إقرار له.',
    goldenRule:'غش زميل = نصح + أدب = خير من سكوت.',
    feedbackQuestion:{question:'لو رأيت زميلاً يكتب على الجدار، ماذا تفعل؟',
      options:[{text:'أنصحه بأدب',correct:true},{text:'أساعده',correct:false},{text:'أخرس',correct:false},{text:'أكتب مثله',correct:false}],
      explanation:'النصح بأدب واجب، والسكوت عن المنكر ضعف.'} },
  { id:'s100',page:31,type:'ordering',bloom:'apply',difficulty:'medium',
    question:'رتّب آداب الطالب نحو المعلم:',
    paragraph:'السلام، الإنصات، السؤال بأدب، الشكر. (ص31)',
    items:['الشكر','السؤال بأدب','الإنصات','السلام'],
    correctOrder:[3,2,1,0],
    explanation:'سلام ← إنصات ← سؤال ← شكر.',
    goldenRule:'أدب المعلم = سلام + إنصات + سؤال + شكر.' },
  { id:'s101',page:32,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف مرافق المدرسة حسب النوع:',
    paragraph:'تعليمية: الفصل، المكتبة، المختبر. رياضية: الساحة، حديقة. خدمية: الممر، دورة المياه. (ص32)',
    categories:['مرافق تعليمية 📚','مرافق رياضية ⚽'],
    items:[
      {text:'الفصل',correct_category:0},{text:'المكتبة',correct_category:0},{text:'المختبر',correct_category:0},
      {text:'الساحة',correct_category:1},{text:'حديقة المدرسة',correct_category:1},
    ],
    explanation:'تعليمية: فصل، مكتبة، مختبر. رياضية: ساحة، حديقة.',
    goldenRule:'مرافق المدرسة = تعليمية + رياضية + خدمية.' },
  { id:'s102',page:20,type:'trueFalse',bloom:'remember',difficulty:'easy',
    question:'النظافة في المدرسة مسؤولية كل طالب لا العامل فقط.',
    paragraph:'نظافة المدرسة مسؤولية الجميع. (ص30)',
    correctAnswer:true,
    explanation:'النظافة مسؤولية جماعية، لا تترك للعامل وحده.',
    goldenRule:'نظافة المدرسة = مسؤولية الجميع = بيتك الثاني.' },
  { id:'s103',page:22,type:'fillBlank',bloom:'understand',difficulty:'easy',
    question:'أكمل: "أنصت للمعلم ولا ___ أثناء الشرح."',
    paragraph:'الإنصات للأدب، والمقاطعة إخلال. (ص22)',
    blanks:['أقاطع'],
    wordBank:['أقاطع','أسأل','أنصت','أكتب'],
    explanation:'المقاطعة إخلال، والإنصات أدب.',
    goldenRule:'إنصات = أدب. مقاطعة = إخلال.' },
  { id:'s104',page:24,type:'multipleChoice',bloom:'understand',difficulty:'medium',
    question:'الكسر أو العبث بأدوات المختبر يضر:',
    paragraph:'عبث أدوات المختبر خطر وضرر للجميع. (ص24)',
    options:[{text:'بنفسك وبزملائك وبالمدرسة',correct:true},{text:'بأحد',correct:false},{text:'لا يضر',correct:false},{text:'بالطعام',correct:false}],
    explanation:'عبث المختبر = خطر + ضرر + خسارة.',
    goldenRule:'أدوات المختبر = أمانة + حذر = سلامة.' },
  { id:'s105',page:26,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل أداة بمكانها:',
    paragraph:'الكتاب في المكتبة، الكرة في الساحة، القلم في الحقيبة، التجربة في المختبر. (ص26)',
    pairs:[{left:'الكتاب',right:'المكتبة'},{left:'الكرة',right:'الساحة'},{left:'القلم',right:'الحقيبة'},{left:'التجربة',right:'المختبر'}],
    explanation:'كل أداة في مكانها المناسب = نظام.',
    goldenRule:'أداة + مكان = نظام + حفظ.' },
  { id:'s106',page:28,type:'trueFalse',bloom:'evaluate',difficulty:'medium',
    question:'الصراخ في الممر من آداب المدرسة.',
    paragraph:'الهدوء في الممر من آداب المدرسة. (ص28)',
    correctAnswer:false,
    explanation:'الهدوء أدب، والصراخ إزعاج وإخلال.',
    goldenRule:'ممر = هدوء = احترام، لا صراخ = إزعاج.' },
  { id:'s107',page:30,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "أحب مدرستي وأحافظ على ___ كبيتي."',
    paragraph:'المدرسة بيتك الثاني فاحفظها. (ص21)',
    blanks:['نظافتها'],
    wordBank:['نظافتها','إتلافها','تخريبها','إهمالها'],
    explanation:'المدرسة بيتك الثاني، حفظها حفظ لبيتك.',
    goldenRule:'مدرستي = بيتي الثاني = حفظ + محبة.' },
  { id:'s108',page:32,type:'ordering',bloom:'apply',difficulty:'medium',
    question:'رتّب آداب الخروج من المدرسة:',
    paragraph:'ترتيب المقعد، السلام، الخروج بهدوء، العودة للبيت. (ص32)',
    items:['العودة للبيت','الخروج بهدوء','السلام على المعلم','ترتيب المقعد'],
    correctOrder:[3,2,1,0],
    explanation:'ترتيب ← سلام ← خروج ← عودة.',
    goldenRule:'خروج مؤدب = ترتيب + سلام + هدوء.' },
  { id:'s109',page:20,type:'multipleChoice',bloom:'evaluate',difficulty:'hard',
    question:'لماذا تستحق المدرسة محبتك؟',
    paragraph:'المدرسة تعلّمك وتربيك وتحفظك، فتستحق المحبة. (ص20-21)',
    options:[{text:'لأنها تعلّمني وتربيني وتحفظني',correct:true},{text:'لأنها تلعب فقط',correct:false},{text:'لأنها تنام',correct:false},{text:'لا سبب',correct:false}],
    explanation:'المدرسة = علم + تربية + حفظ = تستحق المحبة.',
    goldenRule:'مدرسة = علم + تربية + حفظ = محبة + احترام.' },
  { id:'s110',page:22,type:'trueFalse',bloom:'understand',difficulty:'easy',
    question:'المعلم له فضل كفضلة الوالد في التعليم.',
    paragraph:'المعلم كالأب في فضل التربية والتعليم. (ص22)',
    correctAnswer:true,
    explanation:'المعلم يربي ويعلّم، فله فضل عظيم.',
    goldenRule:'معلم = مربي = فضل = احترام.' },
];