// الاجتماعيات - الصف الثاني - الفصل الأول - أسئلة إضافية الوحدتين 3 و 4
export const SOCIAL_EXTRA_2 = [
  // ── الوحدة 3: حارتي ومدينتي (ص 34-46) ──
  { id:'s111',page:34,type:'multipleChoice',bloom:'remember',difficulty:'easy',
    question:'الحارة تتكوّن من:',
    paragraph:'الحارة تتكوّن من بيوت وجيران ومرافق قريبة. (ص34)',
    options:[{text:'بيوت + جيران + مرافق قريبة',correct:true},{text:'دولة',correct:false},{text:'قارة',correct:false},{text:'مدينة بعيدة',correct:false}],
    explanation:'الحارة = بيوت + جيران + مسجد + متجر + حديقة قريبة.',
    goldenRule:'حارة = بيوت + جيران + مرافق قريبة.' },
  { id:'s112',page:35,type:'trueFalse',bloom:'understand',difficulty:'easy',
    question:'الجار يراك كل يوم فيستحق الإحسان.',
    paragraph:'الجار أقرب الناس إليك بعد الأهل، فيستحق الإحسان. (ص35)',
    correctAnswer:true,
    explanation:'الجار قريب دائم، فالإحسان إليه واجب.',
    goldenRule:'جار = قريب دائم = إحسان + احترام.' },
  { id:'s113',page:36,type:'multipleChoice',bloom:'remember',difficulty:'easy',
    question:'حق الجار يشمل:',
    paragraph:'حق الجار: السلام، الزيارة، المساعدة، الإحسان. (ص36)',
    options:[{text:'السلام + الزيارة + المساعدة + الإحسان',correct:true},{text:'الإيذاء',correct:false},{text:'الإهمال',correct:false},{text:'الهجر',correct:false}],
    explanation:'حقوق الجار: سلام، زيارة، مساعدة، إحسان.',
    goldenRule:'حق الجار = سلام + زيارة + مساعدة + إحسان.' },
  { id:'s114',page:37,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف ما يوجد في الحارة:',
    paragraph:'في الحارة: مسجد، متجر، حديقة، مدرسة، صيدلية. (ص37)',
    categories:['مرافق الحارة 🏘️','مرافق بعيدة ✈️'],
    items:[
      {text:'المسجد',correct_category:0},{text:'المتجر',correct_category:0},{text:'الحديقة',correct_category:0},{text:'الصيدلية',correct_category:0},
      {text:'المطار',correct_category:1},{text:'المستشفى الكبير',correct_category:1},{text:'الملعب الكبير',correct_category:1},
    ],
    explanation:'الحارة: مسجد، متجر، حديقة، صيدلية. بعيد: مطار، مستشفى كبير.',
    goldenRule:'حارة = مرافق صغيرة قريبة = خدمة يومية.' },
  { id:'s115',page:38,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل مرفق بخدمته:',
    paragraph:'المسجد للصلاة، المتجر للشراء، الحديقة للّعب، الصيدلية للدواء. (ص38)',
    pairs:[{left:'المسجد',right:'الصلاة'},{left:'المتجر',right:'الشراء'},{left:'الحديقة',right:'اللعب'},{left:'الصيدلية',right:'الدواء'}],
    explanation:'كل مرفق يخدم حاجة يومية.',
    goldenRule:'مسجد=صلاة، متجر=شراء، حديقة=لعب، صيدلية=دواء.' },
  { id:'s116',page:39,type:'trueFalse',bloom:'evaluate',difficulty:'medium',
    question:'إيذاء الجار بالإصراخ والقمامة من قبيح الأعمال.',
    paragraph:'إيذاء الجار بالصوت أو القمامة ظلم ومذموم. (ص39)',
    correctAnswer:true,
    explanation:'إيذاء الجار = ظلم + سوء أدب = مذموم.',
    goldenRule:'جار = إحسان، لا إيذاء. الظلم يفسد الحارة.' },
  { id:'s117',page:40,type:'multipleChoice',bloom:'understand',difficulty:'medium',
    question:'المدينة أكبر من الحارة لأن فيها:',
    paragraph:'المدينة أكبر وتحتوي على أحياء ومرافق أكبر. (ص40)',
    options:[{text:'أحياء كثيرة ومرافق أكبر',correct:true},{text:'بيت واحد',correct:false},{text:'لا سكان',correct:false},{text:'لا مدارس',correct:false}],
    explanation:'المدينة = أحياء + مرافق كبيرة + سكان كثر.',
    goldenRule:'مدينة = أحياء + مرافق كبيرة = أكبر من حارة.' },
  { id:'s118',page:41,type:'ordering',bloom:'apply',difficulty:'medium',
    question:'رتّب من الأصغر للأكبر:',
    paragraph:'البيت < الحارة < الحي < المدينة < الدولة. (ص41)',
    items:['الدولة','المدينة','الحي','الحارة','البيت'],
    correctOrder:[4,3,2,1,0],
    explanation:'بيت < حارة < حي < مدينة < دولة.',
    goldenRule:'كبر المكان = كثرة السكان والمرافق.' },
  { id:'s119',page:42,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف المرافق حسب خدمتها:',
    paragraph:'صحة: المستشفى، الصيدلية. تعليم: المدرسة، المكتبة. عبادة: المسجد. (ص42)',
    categories:['مرافق صحية 🏥','مرافق تعليمية 🏫'],
    items:[
      {text:'المستشفى',correct_category:0},{text:'الصيدلية',correct_category:0},
      {text:'المدرسة',correct_category:1},{text:'المكتبة',correct_category:1},
    ],
    explanation:'صحية: مستشفى، صيدلية. تعليمية: مدرسة، مكتبة.',
    goldenRule:'مرافق المدينة = صحية + تعليمية + عبادية + تجارية.' },
  { id:'s120',page:43,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "الشارع في الحارة للسير و___ للعب."',
    paragraph:'الشارع للسير والسيارات، لا للّعب. (ص43)',
    blanks:['لا'],
    wordBank:['لا','مكان','مناسب','جيد'],
    explanation:'الشارع خطر على الأطفال، فاللعب في الحديقة لا الشارع.',
    goldenRule:'شارع = خطر. حديقة = أمان للّعب.' },
  { id:'s121',page:44,type:'trueFalse',bloom:'evaluate',difficulty:'medium',
    question:'المرافق العامة ملك الجميع فالمحافظة عليها واجب وطني.',
    paragraph:'المرافق العامة ملك الأمة، فالمحافظة عليها واجب. (ص44)',
    correctAnswer:true,
    explanation:'المرافق العامة = ملك الجميع = حفظها واجب.',
    goldenRule:'مرفق عام = ملك الجميع = حفظ = واجب وطني.' },
  { id:'s122',page:45,type:'multipleChoice',bloom:'understand',difficulty:'easy',
    question:'لو رأيت حاوية قمامة ممتلئة في الحارة، ما الصواب؟',
    paragraph:'الإبلاغ عن القمامة المتراكمة مسؤولية كل فرد. (ص45)',
    options:[{text:'أبلغ البلدية أو أهلي',correct:true},{text:'أتجاهل',correct:false},{text:'أزيد القمامة',correct:false},{text:'أشكو',correct:false}],
    explanation:'الإبلاغ + عدم الزيادة = مسؤولية.',
    goldenRule:'قمامة متراكمة = إبلاغ + عدم زيادة = نظافة.' },
  { id:'s123',page:46,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل سلوك بأثره على الحارة:',
    paragraph:'نظافة = راحة، قذارة = مرض، إيذاء = عداوة، مساعدة = محبة. (ص46)',
    pairs:[{left:'النظافة',right:'راحة'},{left:'القذارة',right:'مرض'},{left:'الإيذاء',right:'عداوة'},{left:'المساعدة',right:'محبة'}],
    explanation:'كل سلوك له أثر: نظافة=راحة، قذارة=مرض، إيذاء=عداوة، مساعدة=محبة.',
    goldenRule:'سلوكك = أثر. اختر الأثر الحسن.' },
  { id:'s124',page:34,type:'trueFalse',bloom:'remember',difficulty:'easy',
    question:'الحارة جزء من المدينة.',
    paragraph:'الحارة حي صغير داخل المدينة. (ص34)',
    correctAnswer:true,
    explanation:'الحارة حي صغير في المدينة الكبيرة.',
    goldenRule:'حارة < حي < مدينة. كلما زاد زاد.' },
  { id:'s125',page:36,type:'fillBlank',bloom:'understand',difficulty:'easy',
    question:'أكمل: "أحسن إلى جاري وأ___ له."',
    paragraph:'الإحسان للجار بالمساعدة والزيارة. (ص36)',
    blanks:['ساعده'],
    wordBank:['ساعده','ضرّه','تجاهله','أزعجه'],
    explanation:'الإحسان للجار = مساعدة + زيارة + كلمة طيبة.',
    goldenRule:'جار = إحسان + مساعدة + زيارة.' },
  { id:'s126',page:38,type:'multipleChoice',bloom:'understand',difficulty:'medium',
    question:'المسجد في الحارة يخدم:',
    paragraph:'المسجد في الحارة للصلاة والتعليم والاجتماع. (ص38)',
    options:[{text:'الصلاة والتعليم والاجتماع',correct:true},{text:'اللعب',correct:false},{text:'النوم',correct:false},{text:'الأكل',correct:false}],
    explanation:'المسجد = صلاة + تعليم + اجتماع = قلب الحارة.',
    goldenRule:'مسجد الحارة = صلاة + اجتماع + تعليم.' },
  { id:'s127',page:40,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف ما يوجد في المدينة:',
    paragraph:'المدينة فيها: مستشفيات، مدارس، أسواق، مطاعم، ملاعب. (ص40)',
    categories:['مرافق صحية وتعليمية 🏥📚','مرافق تجارية وترفيهية 🛒🎮'],
    items:[
      {text:'مستشفى',correct_category:0},{text:'مدرسة',correct_category:0},{text:'جامعة',correct_category:0},
      {text:'سوق',correct_category:1},{text:'ملعب',correct_category:1},{text:'مطعم',correct_category:1},
    ],
    explanation:'صحية/تعليمية: مستشفى، مدرسة، جامعة. تجارية/ترفيهية: سوق، ملعب، مطعم.',
    goldenRule:'مدينة متكاملة = صحة + تعليم + تجارة + ترفيه.' },
  { id:'s128',page:42,type:'ordering',bloom:'apply',difficulty:'medium',
    question:'رتّب خطوات زيارة مرفق عام باحترام:',
    paragraph:'الدخول بهدوء، الاستخدام بأدب، ترتيب المكان، الخروج. (ص42)',
    items:['الخروج','ترتيب المكان','الاستخدام بأدب','الدخول بهدوء'],
    correctOrder:[3,2,1,0],
    explanation:'دخول ← استخدام ← ترتيب ← خروج.',
    goldenRule:'زيارة مرفق = هدوء + أدب + ترتيب.' },
  { id:'s129',page:44,type:'trueFalse',bloom:'evaluate',difficulty:'medium',
    question:'كتابة الجدار أو التحطيم من المحافظة على المرافق.',
    paragraph:'الكتابة والتحطيم إفساد للمرافق. (ص44)',
    correctAnswer:false,
    explanation:'الكتابة والتحطيم تخريب، لا محافظة.',
    goldenRule:'مرفق = حفظ + ترتيب، لا كتابة + تحطيم.' },
  { id:'s130',page:46,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "أحب حارتي وأحافظ على ___ فيها."',
    paragraph:'المحافظة على نظافة الحارة واجب كل فرد. (ص46)',
    blanks:['نظافتها'],
    wordBank:['نظافتها','إتلافها','تخريبها','قذارتها'],
    explanation:'حارة نظيفة = راحة + صحة + محبة.',
    goldenRule:'حارة نظيفة = راحة + صحة + محبة.' },
  { id:'s131',page:35,type:'multipleChoice',bloom:'evaluate',difficulty:'hard',
    question:'لو أزعج جارك بالصوت، ما الصواب؟',
    paragraph:'النصح بأدب خير من العراك. (ص39)',
    options:[{text:'أنصحه بأدب ولطف',correct:true},{text:'أصرخ عليه',correct:false},{text:'أضربه',correct:false},{text:'أهجره',correct:false}],
    explanation:'النصح بأدب يحل المشكلة، والصراخ يزيدها.',
    goldenRule:'نصح بأدب = حل. صراخ = خراب.',
    feedbackQuestion:{question:'لو سكب جارك ماء أمام بيتك، ماذا تفعل؟',
      options:[{text:'أكلمه بأدب',correct:true},{text:'أصرخ',correct:false},{text:'أسكب مثله',correct:false},{text:'أهجره',correct:false}],
      explanation:'الحوار الهادئ يحل، والانتقام يفسد.'} },
  { id:'s132',page:37,type:'trueFalse',bloom:'understand',difficulty:'easy',
    question:'الجار المسلم له حق، والجار غير المسلم له حق الإحسان.',
    paragraph:'الإسلام أوصى بالإحسان للجار مطلقاً. (ص37)',
    correctAnswer:true,
    explanation:'حق الجار = إحسان، مسلماً كان أو غير مسلم.',
    goldenRule:'جار = إحسان = لا فرق في الحق.' },
  { id:'s133',page:39,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف السلوكيات نحو الجار:',
    paragraph:'إيجابي: سلام، إحسان، مساعدة. سلبي: إيذاء، صراخ، تجاهل. (ص39)',
    categories:['سلوك إيجابي ✅','سلوك سلبي ❌'],
    items:[
      {text:'السلام',correct_category:0},{text:'الإحسان',correct_category:0},{text:'المساعدة',correct_category:0},
      {text:'الإيذاء',correct_category:1},{text:'الصراخ',correct_category:1},{text:'التجاهل',correct_category:1},
    ],
    explanation:'إيجابي: سلام، إحسان، مساعدة. سلبي: إيذاء، صراخ، تجاهل.',
    goldenRule:'جار = إحسان + سلام + مساعدة، لا إيذاء.' },
  { id:'s134',page:41,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل مكان بحجمه:',
    paragraph:'البيت أصغر، الحارة أكبر، الحي أكبر، المدينة أكبر. (ص41)',
    pairs:[{left:'البيت',right:'أصغر'},{left:'الحارة',right:'أكبر من البيت'},{left:'الحي',right:'أكبر من الحارة'},{left:'المدينة',right:'أكبر من الحي'}],
    explanation:'كل مكان أكبر من سابقه.',
    goldenRule:'بيت < حارة < حي < مدينة = تدرج.' },
  { id:'s135',page:43,type:'fillBlank',bloom:'understand',difficulty:'easy',
    question:'أكمل: "الشارع للسيارات، فلا ___ فيه."',
    paragraph:'الشارع للسيارات، لا للّعب الأطفال. (ص43)',
    blanks:['ألعب'],
    wordBank:['ألعب','أسير','أنظر','أتعلم'],
    explanation:'اللعب في الشارع خطر، فاللعب في الحديقة.',
    goldenRule:'شارع = خطر. حديقة = أمان للّعب.' },
  { id:'s136',page:45,type:'trueFalse',bloom:'evaluate',difficulty:'medium',
    question:'المشاركة في تنظيف الحارة من حب الوطن.',
    paragraph:'نظافة الحارة مشاركة وطنية. (ص45)',
    correctAnswer:true,
    explanation:'نظافة الحي = حب للوطن = عمل وطني.',
    goldenRule:'نظافة الحي = حب الوطن = عمل.' },
  { id:'s137',page:46,type:'multipleChoice',bloom:'understand',difficulty:'medium',
    question:'الحياة في الحارة تكون:',
    paragraph:'الحياة في الحارة قريبة ودافئة بين الجيران. (ص46)',
    options:[{text:'قريبة ودافئة بين الجيران',correct:true},{text:'باردة',correct:false},{text:'معزولة',correct:false},{text:'عدائية',correct:false}],
    explanation:'الحارة = جيران + ألفة + تعاون = حياة دافئة.',
    goldenRule:'حارة دافئة = جيران + ألفة + تعاون.' },

  // ── الوحدة 4: وطنيي المملكة العربية السعودية (ص 48-66) ──
  { id:'s138',page:48,type:'multipleChoice',bloom:'remember',difficulty:'easy',
    question:'عاصمة المملكة العربية السعودية:',
    paragraph:'الرياض عاصمة المملكة العربية السعودية. (ص48)',
    options:[{text:'الرياض',correct:true},{text:'جدة',correct:false},{text:'الدمام',correct:false},{text:'مكة',correct:false}],
    explanation:'الرياض = عاصمة = وسط المملكة + مرافق الدولة.',
    goldenRule:'الرياض = عاصمة المملكة العربية السعودية.' },
  { id:'s139',page:49,type:'trueFalse',bloom:'remember',difficulty:'easy',
    question:'المملكة العربية السعودية تقع في جنوب غرب قارة آسيا.',
    paragraph:'المملكة في جنوب غرب آسيا في شبه الجزيرة العربية. (ص49)',
    correctAnswer:true,
    explanation:'المملكة = جنوب غرب آسيا = شبه الجزيرة العربية.',
    goldenRule:'المملكة = جنوب غرب آسيا = شبه الجزيرة العربية.' },
  { id:'s140',page:50,type:'multipleChoice',bloom:'remember',difficulty:'easy',
    question:'لون علم المملكة العربية السعودية:',
    paragraph:'علم المملكة لونه أخضر وفي وسطه الشهادتان والسيف. (ص50)',
    options:[{text:'أخضر',correct:true},{text:'أحمر',correct:false},{text:'أزرق',correct:false},{text:'أبيض',correct:false}],
    explanation:'العلم أخضر + الشهادتان + سيف = رمز الإسلام.',
    goldenRule:'علم المملكة = أخضر + الشهادتان + سيف.' },
  { id:'s141',page:51,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف أركان العلم السعودي:',
    paragraph:'العلم فيه: اللون الأخضر، الشهادتان، السيف، شكل مستطيل. (ص50-51)',
    categories:['عناصر العلم 🇸🇦','لا تنتمي للعلم ❌'],
    items:[
      {text:'اللون الأخضر',correct_category:0},{text:'الشهادتان',correct_category:0},{text:'السيف',correct_category:0},{text:'المستطيل',correct_category:0},
      {text:'النجم الأحمر',correct_category:1},{text:'الهلال',correct_category:1},
    ],
    explanation:'العلم = أخضر + شهادتان + سيف + مستطيل. النجم والهلال لأعلام أخرى.',
    goldenRule:'علم سعودي = أخضر + شهادتان + سيف + مستطيل.' },
  { id:'s142',page:52,type:'trueFalse',bloom:'remember',difficulty:'easy',
    question:'عدد مناطق المملكة العربية السعودية 13 منطقة.',
    paragraph:'المملكة مقسّمة إلى 13 منطقة إدارية. (ص52)',
    correctAnswer:true,
    explanation:'المملكة = 13 منطقة إدارية.',
    goldenRule:'المملكة = 13 منطقة إدارية.' },
  { id:'s143',page:53,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل منطقة بعاصمتها:',
    paragraph:'الرياض عاصمة منطقة الرياض، مكة عاصمة منطقة مكة، جدة في منطقة مكة. (ص53)',
    pairs:[{left:'منطقة الرياض',right:'الرياض'},{left:'منطقة مكة',right:'مكة'},{left:'منطقة المدينة',right:'المدينة'},{left:'منطقة القصيم',right:'بريدة'}],
    explanation:'كل منطقة لها عاصمتها الإدارية.',
    goldenRule:'المنطقة = عاصمة + مدن.' },
  { id:'s144',page:54,type:'multipleChoice',bloom:'understand',difficulty:'medium',
    question:'المملكة العربية السعودية تطلّ على بحرين:',
    paragraph:'المملكة تطلّ على البحر الأحمر غرباً والخليج العربي شرقاً. (ص54)',
    options:[{text:'البحر الأحمر غرباً والخليج العربي شرقاً',correct:true},{text:'بحر واحد',correct:false},{text:'لا بحر',correct:false},{text:'ثلاثة بحار',correct:false}],
    explanation:'المملكة = بحر أحمر (غرب) + خليج عربي (شرق).',
    goldenRule:'غرب=بحر أحمر، شرق=خليج عربي. بحران مهمّان.' },
  { id:'s145',page:55,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف المدن حسب موقعها:',
    paragraph:'غرب: مكة، المدينة، جدة. شرق: الدمام، الخبر، الأحساء. وسط: الرياض. (ص55)',
    categories:['غرب المملكة 🌊','شرق المملكة 🛢️'],
    items:[
      {text:'مكة',correct_category:0},{text:'المدينة',correct_category:0},{text:'جدة',correct_category:0},
      {text:'الدمام',correct_category:1},{text:'الخبر',correct_category:1},{text:'الأحساء',correct_category:1},
    ],
    explanation:'غرب: مكة، المدينة، جدة. شرق: الدمام، الخبر، الأحساء.',
    goldenRule:'غرب=بحر أحمر، شرق=خليج عربي.' },
  { id:'s146',page:56,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "أكبر مدينة في المملكة العربية السعودية هي ___."',
    paragraph:'الرياض أكبر مدن المملكة مساحة وسكاناً. (ص56)',
    blanks:['الرياض'],
    wordBank:['الرياض','جدة','تبوك','أبها'],
    explanation:'الرياض أكبر مدن المملكة سكاناً ومساحة.',
    goldenRule:'الرياض = أكبر مدينة = عاصمة = وسط المملكة.' },
  { id:'s147',page:57,type:'trueFalse',bloom:'understand',difficulty:'easy',
    question:'مكة المكرمة بها الكعبة المشرفة قبلة المسلمين.',
    paragraph:'مكة فيها الكعبة المشرفة، قبلة المسلمين. (ص57)',
    correctAnswer:true,
    explanation:'مكة = الكعبة = قبلة المسلمين في كل العالم.',
    goldenRule:'مكة = الكعبة = قبلة المسلمين.' },
  { id:'s148',page:58,type:'multipleChoice',bloom:'remember',difficulty:'easy',
    question:'المدينة المنورة بها:',
    paragraph:'المدينة المنورة بها المسجد النبوي وقبر النبي ﷺ. (ص58)',
    options:[{text:'المسجد النبوي',correct:true},{text:'الكعبة',correct:false},{text:'المسجد الأقصى',correct:false},{text:'برج ساعة',correct:false}],
    explanation:'المدينة = المسجد النبوي = قبر النبي ﷺ.',
    goldenRule:'المدينة = المسجد النبوي = ثاني أقدس المساجد.' },
  { id:'s149',page:59,type:'ordering',bloom:'apply',difficulty:'hard',
    question:'رتّب مراحل تأسيس المملكة:',
    paragraph:'استرداد الرياض (1319هـ) ثم توحيد نجد ثم الحجاز ثم إعلان المملكة (1351هـ). (ص59)',
    items:['إعلان المملكة','توحيد الحجاز','توحيد نجد','استرداد الرياض'],
    correctOrder:[3,2,1,0],
    explanation:'الرياض ← نجد ← الحجاز ← المملكة.',
    goldenRule:'توحيد المملكة: الرياض ← نجد ← الحجاز ← إعلان.' },
  { id:'s150',page:60,type:'trueFalse',bloom:'remember',difficulty:'easy',
    question:'الملك عبدالعزيز آل سعود هو مؤسس المملكة العربية السعودية.',
    paragraph:'الملك عبدالعزيز وحّد المملكة وأسسها عام 1351هـ. (ص60)',
    correctAnswer:true,
    explanation:'الملك عبدالعزيز = المؤسس = الموحّد.',
    goldenRule:'المؤسس = الملك عبدالعزيز آل سعود رحمه الله.' },
  { id:'s151',page:61,type:'multipleChoice',bloom:'understand',difficulty:'medium',
    question:'الدين الرسمي للمملكة العربية السعودية:',
    paragraph:'الإسلام دين المملكة الرسمي والقرآن دستورها. (ص61)',
    options:[{text:'الإسلام',correct:true},{text:'النصرانية',correct:false},{text:'اليهودية',correct:false},{text:'البوذية',correct:false}],
    explanation:'المملكة = الإسلام = القرآن دستور.',
    goldenRule:'المملكة = الإسلام + القرآن دستور = دولة مسلمة.' },
  { id:'s152',page:62,type:'classify',bloom:'analyze',difficulty:'hard',
    question:'صنّف المعالم حسب مكانها:',
    paragraph:'الكعبة في مكة، المسجد النبوي في المدينة، برج المملكة في الرياض. (ص62)',
    categories:['مكة المكرمة 🕋','المدينة المنورة 🕌'],
    items:[
      {text:'الكعبة',correct_category:0},{text:'المسجد الحرام',correct_category:0},
      {text:'المسجد النبوي',correct_category:1},{text:'قبر النبي ﷺ',correct_category:1},
    ],
    explanation:'مكة: الكعبة، المسجد الحرام. المدينة: المسجد النبوي، قبر النبي ﷺ.',
    goldenRule:'مكة=كعبة، المدينة=مسجد نبوي. مدينتان مقدستان.' },
  { id:'s153',page:63,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل سلوك بنتيجته على الوطن:',
    paragraph:'الدفاع = حماية، المحافظة = جمال، الإفساد = ضرر، الإهمال = تخلّف. (ص63)',
    pairs:[{left:'الدفاع',right:'حماية الوطن'},{left:'المحافظة',right:'جمال الوطن'},{left:'الإفساد',right:'ضرر الوطن'},{left:'الإهمال',right:'تخلّف الوطن'}],
    explanation:'كل سلوك له أثر على الوطن.',
    goldenRule:'سلوكك نحو وطنك = أثر. اختر الأثر الحسن.' },
  { id:'s154',page:64,type:'trueFalse',bloom:'evaluate',difficulty:'medium',
    question:'حب الوطن عمل لا قول فقط.',
    paragraph:'حب الوطن يظهر في الأعمال لا الأقوال. (ص64)',
    correctAnswer:true,
    explanation:'حب الوطن = عمل = نظافة + خدمة + دفاع.',
    goldenRule:'حب الوطن = عمل = نظافة + خدمة + دفاع.' },
  { id:'s155',page:65,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "أفخر بكوني مواطناً في المملكة العربية ___."',
    paragraph:'المملكة العربية السعودية وطننا. (ص65)',
    blanks:['السعودية'],
    wordBank:['السعودية','المغرب','مصر','الأردن'],
    explanation:'المملكة العربية السعودية = وطننا = فخرنا.',
    goldenRule:'وطني = المملكة العربية السعودية = فخري.' },
  { id:'s156',page:66,type:'multipleChoice',bloom:'evaluate',difficulty:'hard',
    question:'لو أردت خدمة وطنك، ما أفضل ما تبدأ به؟',
    paragraph:'خدمة الوطن تبدأ بالعلم والأخلاق والعمل. (ص66)',
    options:[{text:'الدراسة وحسن الأخلاق',correct:true},{text:'اللعب',correct:false},{text:'النوم',correct:false},{text:'الكسل',correct:false}],
    explanation:'خدمة الوطن = علم + أخلاق + عمل = مستقبل زاهر.',
    goldenRule:'خدمة الوطن = علم + أخلاق + عمل.',
    feedbackQuestion:{question:'لو رأيت علم الوطن على الأرض، ماذا تفعل؟',
      options:[{text:'أرفعه وأنظّفه باحترام',correct:true},{text:'أتركه',correct:false},{text:'أدوسه',correct:false},{text:'أخبئه',correct:false}],
      explanation:'العلم رمز الوطن، رفعه واحترامه واجب.'} },
  { id:'s157',page:48,type:'trueFalse',bloom:'remember',difficulty:'easy',
    question:'الرياض في وسط المملكة العربية السعودية.',
    paragraph:'الرياض عاصمة المملكة تقع في وسطها. (ص48)',
    correctAnswer:true,
    explanation:'الرياض = وسط المملكة = سهل + عاصمة.',
    goldenRule:'الرياض = وسط المملكة = عاصمة.' },
  { id:'s158',page:50,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "في وسط العلم السعودي ___ والسيف."',
    paragraph:'العلم فيه الشهادتان والسيف. (ص50)',
    blanks:['الشهادتان'],
    wordBank:['الشهادتان','النجم','الهلال','الصقر'],
    explanation:'الشهادتان + سيف = وسط العلم السعودي.',
    goldenRule:'وسط العلم = الشهادتان + سيف.' },
  { id:'s159',page:52,type:'ordering',bloom:'apply',difficulty:'medium',
    question:'رتّب مناطق المملكة من الشمال للجنوب:',
    paragraph:'تبوك شمالاً، الرياض وسطاً، عسير جنوباً. (ص52)',
    items:['عسير','الرياض','تبوك'],
    correctOrder:[2,1,0],
    explanation:'تبوك (شمال) ← الرياض (وسط) ← عسير (جنوب).',
    goldenRule:'شمال=تبوك، وسط=الرياض، جنوب=عسير.' },
  { id:'s160',page:54,type:'multipleChoice',bloom:'understand',difficulty:'medium',
    question:'المناخ في المملكة يكون:',
    paragraph:'مناخ المملكة صحراوي حار صيفاً ومعتدل شتاءً. (ص54)',
    options:[{text:'صحراوي حار صيفاً ومعتدل شتاءً',correct:true},{text:'بارد طوال العام',correct:false},{text:'ممطر دائماً',correct:false},{text:'معتدل دائماً',correct:false}],
    explanation:'مناخ المملكة = صحراوي = حار صيفاً + معتدل شتاءً.',
    goldenRule:'مناخ سعودي = صحراوي = حار صيفاً + معتدل شتاءً.' },
  { id:'s161',page:56,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف المعالم حسب مكانها:',
    paragraph:'الرياض: برج المملكة. مكة: الكعبة. المدينة: المسجد النبوي. جدة: نافورة. (ص56)',
    categories:['مكة المكرمة 🕋','الرياض 🏙️'],
    items:[
      {text:'الكعبة',correct_category:0},{text:'المسجد الحرام',correct_category:0},
      {text:'برج المملكة',correct_category:1},{text:'قصر الحكم',correct_category:1},
    ],
    explanation:'مكة: كعبة، مسجد حرام. الرياض: برج المملكة، قصر الحكم.',
    goldenRule:'كل مدينة لها معالمها المميزة.' },
  { id:'s162',page:58,type:'trueFalse',bloom:'remember',difficulty:'easy',
    question:'المدينة المنورة بها المسجد النبوي وقبر النبي محمد ﷺ.',
    paragraph:'المدينة المنورة بها المسجد النبوي الشريف. (ص58)',
    correctAnswer:true,
    explanation:'المدينة = المسجد النبوي = قبر النبي ﷺ = ثاني أقدس المساجد.',
    goldenRule:'المدينة = المسجد النبوي = ثاني أقدس المساجد.' },
  { id:'s163',page:60,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "مؤسس المملكة هو الملك ___ آل سعود."',
    paragraph:'الملك عبدالعزيز آل سعود مؤسس المملكة. (ص60)',
    blanks:['عبدالعزيز'],
    wordBank:['عبدالعزيز','فيصل','خالد','فهد'],
    explanation:'الملك عبدالعزيز = المؤسس = الموحّد.',
    goldenRule:'المؤسس = الملك عبدالعزيز آل سعود.' },
  { id:'s164',page:62,type:'multipleChoice',bloom:'evaluate',difficulty:'hard',
    question:'لماذا تتنوع مناخات المملكة؟',
    paragraph:'تتنوع المناطق: جبال في الجنوب، صحراء في الوسط، ساحل غرب وشرق. (ص62)',
    options:[{text:'لتنوع تضاريسها',correct:true},{text:'لصغر مساحتها',correct:false},{text:'لأنها دولة واحدة',correct:false},{text:'لا يوجد تنوع',correct:false}],
    explanation:'التنوع = جبال + صحراء + ساحل = مناخات مختلفة.',
    goldenRule:'تضاريس متنوعة = مناخات متنوعة في وطن واحد.' },
  { id:'s165',page:64,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل سلوك بأثره على الوطن:',
    paragraph:'النظافة = جمال، العبث = إفساد، الدفاع = حماية، التعلم = تقدّم. (ص64)',
    pairs:[{left:'النظافة',right:'جمال الوطن'},{left:'العبث',right:'إفساد الوطن'},{left:'الدفاع',right:'حماية الوطن'},{left:'التعلم',right:'تقدّم الوطن'}],
    explanation:'كل سلوك = أثر على الوطن.',
    goldenRule:'سلوكك نحو وطنك = أثر. اختر الأثر الحسن.' },
  { id:'s166',page:66,type:'trueFalse',bloom:'evaluate',difficulty:'medium',
    question:'الدفاع عن الوطن واجب كل مواطن لا الجند فقط.',
    paragraph:'حماية الوطن مسؤولية كل مواطن بطريقته. (ص66)',
    correctAnswer:true,
    explanation:'الدفاع = جند + عمل + علم + أخلاق = كل مواطن.',
    goldenRule:'الدفاع عن الوطن = واجب الجميع بطريقتهم.' },
  { id:'s167',page:48,type:'fillBlank',bloom:'understand',difficulty:'easy',
    question:'أكمل: "الرياض عاصمة ___ العربية السعودية."',
    paragraph:'الرياض عاصمة المملكة العربية السعودية. (ص48)',
    blanks:['المملكة'],
    wordBank:['المملكة','المدينة','القرية','الحي'],
    explanation:'الرياض = عاصمة = المملكة العربية السعودية.',
    goldenRule:'الرياض = عاصمة المملكة.' },
  { id:'s168',page:50,type:'trueFalse',bloom:'remember',difficulty:'easy',
    question:'اللون الأخضر في العلم السعودي يرمز للإسلام.',
    paragraph:'الأخضر لون الإسلام والعلم السعودي. (ص50)',
    correctAnswer:true,
    explanation:'الأخضر = لون الإسلام = رمز التوحيد.',
    goldenRule:'أخضر = الإسلام = رمز في العلم السعودي.' },
  { id:'s169',page:52,type:'multipleChoice',bloom:'remember',difficulty:'medium',
    question:'من مناطق المملكة الشمالية:',
    paragraph:'تبوك والجوف والحدود الشمالية من المناطق الشمالية. (ص52)',
    options:[{text:'تبوك والجوف',correct:true},{text:'عسير',correct:false},{text:'جازان',correct:false},{text:'نجران',correct:false}],
    explanation:'شمال: تبوك، الجوف، الحدود الشمالية. جنوب: عسير، جازان، نجران.',
    goldenRule:'شمال=تبوك، جنوب=عسير. كل اتجاه له مناطقه.' },
  { id:'s170',page:54,type:'classify',bloom:'analyze',difficulty:'hard',
    question:'صنّف المناطق حسب الاتجاه:',
    paragraph:'شمال: تبوك، الجوف. جنوب: عسير، جازان. شرق: الشرقية. غرب: مكة، المدينة. (ص54)',
    categories:['مناطق جنوبية 🏔️','مناطق شرقية 🛢️'],
    items:[
      {text:'عسير',correct_category:0},{text:'جازان',correct_category:0},{text:'نجران',correct_category:0},
      {text:'الشرقية',correct_category:1},{text:'الأحساء',correct_category:1},
    ],
    explanation:'جنوب: عسير، جازان، نجران. شرق: الشرقية، الأحساء.',
    goldenRule:'جنوب=جبال، شرق=نفط. كل اتجاه له ميزة.' },
  { id:'s171',page:56,type:'ordering',bloom:'apply',difficulty:'medium',
    question:'رتّب المدن من الغرب للشرق:',
    paragraph:'جدة غرباً، الرياض وسطاً، الدمام شرقاً. (ص56)',
    items:['الدمام','الرياض','جدة'],
    correctOrder:[2,1,0],
    explanation:'جدة (غرب) ← الرياض (وسط) ← الدمام (شرق).',
    goldenRule:'غرب=جدة، وسط=الرياض، شرق=الدمام.' },
  { id:'s172',page:58,type:'trueFalse',bloom:'understand',difficulty:'easy',
    question:'مكة المكرمة هي المدينة المقدسة الأولى عند المسلمين.',
    paragraph:'مكة المكرمة بها الكعبة، أعظم مكان في الإسلام. (ص58)',
    correctAnswer:true,
    explanation:'مكة = الكعبة = أعظم مدينة مقدسة = قبلة المسلمين.',
    goldenRule:'مكة = الكعبة = أعظم مدينة = قبلة المسلمين.' },
  { id:'s173',page:60,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "تأسست المملكة عام ___ هـ."',
    paragraph:'تأسست المملكة عام 1351هـ. (ص60)',
    blanks:['1351'],
    wordBank:['1351','1932','1447','1300'],
    explanation:'المملكة تأسست عام 1351هـ الموافق 1932م.',
    goldenRule:'تأسيس المملكة = 1351هـ = 1932م.' },
  { id:'s174',page:62,type:'multipleChoice',bloom:'understand',difficulty:'medium',
    question:'البحر الأحمر يقع ___ المملكة العربية السعودية.',
    paragraph:'البحر الأحمر غرب المملكة. (ص62)',
    options:[{text:'غرب',correct:true},{text:'شرق',correct:false},{text:'شمال',correct:false},{text:'جنوب',correct:false}],
    explanation:'البحر الأحمر = غرب المملكة. الخليج العربي = شرقها.',
    goldenRule:'غرب=بحر أحمر، شرق=خليج عربي.' },
  { id:'s175',page:64,type:'trueFalse',bloom:'evaluate',difficulty:'medium',
    question:'المشاركة في نظافة الحي من حب الوطن.',
    paragraph:'نظافة الحي عمل وطني من حب الوطن. (ص64)',
    correctAnswer:true,
    explanation:'نظافة الحي = حب الوطن = عمل وطني.',
    goldenRule:'نظافة الحي = حب الوطن = عمل.' },
  { id:'s176',page:66,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل مدينة بأهم معالمها:',
    paragraph:'مكة=الكعبة، المدينة=المسجد النبوي، الرياض=برج المملكة، جدة=نافورة. (ص66)',
    pairs:[{left:'مكة',right:'الكعبة'},{left:'المدينة',right:'المسجد النبوي'},{left:'الرياض',right:'برج المملكة'},{left:'جدة',right:'النافورة'}],
    explanation:'كل مدينة لها معالمها المميزة.',
    goldenRule:'مدينة = معالم = هوية.' },
  { id:'s177',page:48,type:'multipleChoice',bloom:'evaluate',difficulty:'hard',
    question:'لماذا الرياض عاصمة المملكة؟',
    paragraph:'الرياض في وسط المملكة وبها مرافق الدولة الكبرى. (ص48)',
    options:[{text:'لأنها في الوسط وبها مرافق الدولة',correct:true},{text:'لأنها أقدم مدينة',correct:false},{text:'لأنها على البحر',correct:false},{text:'لأنها أصغر المدن',correct:false}],
    explanation:'الرياض = وسط + مرافق دولة = عاصمة.',
    goldenRule:'العاصمة = وسط + مرافق الدولة.' },
  { id:'s178',page:50,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "علم المملكة العربية السعودية لونه ___."',
    paragraph:'علم المملكة لونه أخضر. (ص50)',
    blanks:['أخضر'],
    wordBank:['أخضر','أحمر','أزرق','أصفر'],
    explanation:'الأخضر = لون العلم السعودي = لون الإسلام.',
    goldenRule:'أخضر = العلم السعودي = الإسلام.' },
  { id:'s179',page:52,type:'trueFalse',bloom:'remember',difficulty:'easy',
    question:'منطقة عسير في جنوب المملكة العربية السعودية.',
    paragraph:'عسير في جنوب المملكة وفيها جبال السودة. (ص52)',
    correctAnswer:true,
    explanation:'عسير = جنوب = جبال = مناخ معتدل.',
    goldenRule:'عسير = جنوب = جبال = مناخ معتدل.' },
  { id:'s180',page:54,type:'ordering',bloom:'apply',difficulty:'medium',
    question:'رتّب البحار من الغرب للشرق:',
    paragraph:'البحر الأحمر غرب المملكة، الخليج العربي شرقها. (ص54)',
    items:['الخليج العربي','المملكة','البحر الأحمر'],
    correctOrder:[2,1,0],
    explanation:'البحر الأحمر (غرب) ← المملكة ← الخليج العربي (شرق).',
    goldenRule:'غرب=بحر أحمر، شرق=خليج عربي. المملكة بينهما.' },
];