// الاجتماعيات - الصف الثاني - الفصل الأول - أسئلة إضافية متنوعة (وحدات 1-4)
export const SOCIAL_EXTRA_3 = [
  // ── وحدة 1: أسرتي وبيتي ──
  { id:'s181',page:6,type:'multipleChoice',bloom:'remember',difficulty:'easy',
    question:'الأب الذي يرعى أبناءه يُسمى:',
    paragraph:'الأب راعي الأسرة المسؤول عن رعايتها. (ص6)',
    options:[{text:'راعي الأسرة',correct:true},{text:'ضيف',correct:false},{text:'جار',correct:false},{text:'غريب',correct:false}],
    explanation:'الأب = راعي = مسؤول = ينفق + يحمي.',
    goldenRule:'الأب راعي = مسؤولية + إنفاق + حماية.' },
  { id:'s182',page:7,type:'trueFalse',bloom:'remember',difficulty:'easy',
    question:'الإسلام جعل بر الوالدين فرضاً عظيماً.',
    paragraph:'بر الوالدين فرض في الإسلام قرنه الله بالتوحيد. (ص7)',
    correctAnswer:true,
    explanation:'بر الوالدين = فرض = قرن مع التوحيد.',
    goldenRule:'بر الوالدين = فرض = توحيد + بر = أعظم.' },
  { id:'s183',page:8,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف المسؤوليات في البيت:',
    paragraph:'الأب ينفق، الأم تربي، الطالب يدرس ويرتّب. (ص8)',
    categories:['مسؤولية الأب 💼','مسؤولية الطالب 📚'],
    items:[
      {text:'الإنفاق',correct_category:0},{text:'الحماية',correct_category:0},
      {text:'الدراسة',correct_category:1},{text:'ترتيب الغرفة',correct_category:1},
    ],
    explanation:'الأب: إنفاق، حماية. الطالب: دراسة، ترتيب.',
    goldenRule:'كل فرد له مسؤوليات في الأسرة.' },
  { id:'s184',page:10,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل فرد بمكان وجوده في الأسرة:',
    paragraph:'الأب والأم والأبناء في البيت، الجد والجدة في الأسرة الكبيرة. (ص10)',
    pairs:[{left:'الأب',right:'البيت'},{left:'الأم',right:'البيت'},{left:'الأبناء',right:'البيت'},{left:'الجد',right:'الأسرة الكبيرة'}],
    explanation:'الصغيرة في البيت، الكبيرة تشمل الأجداد.',
    goldenRule:'أسرة صغيرة في البيت = أب + أم + أبناء.' },
  { id:'s185',page:12,type:'fillBlank',bloom:'understand',difficulty:'easy',
    question:'أكمل: "أطيع والدي ولا ___ أمرهما."',
    paragraph:'طاعة الوالدين فرض. (ص12)',
    blanks:['أعصي'],
    wordBank:['أعصي','أطع','أحب','أبر'],
    explanation:'العصيان ذنب، والطاعة فرض.',
    goldenRule:'طاعة = فرض. عصيان = ذنب.' },
  { id:'s186',page:14,type:'ordering',bloom:'apply',difficulty:'medium',
    question:'رتّب واجباتك نحو غرفتك:',
    paragraph:'ترتيب السرير، تنظيف المكتب، ترتيب الملابس، كنس الأرض. (ص14)',
    items:['كنس الأرض','ترتيب الملابس','تنظيف المكتب','ترتيب السرير'],
    correctOrder:[3,2,1,0],
    explanation:'سرير ← مكتب ← ملابس ← أرض.',
    goldenRule:'غرفة مرتبة = سرير + مكتب + ملابس + أرض.' },
  { id:'s187',page:16,type:'trueFalse',bloom:'evaluate',difficulty:'medium',
    question:'اللعب كثيراً وترك الدراسة يضر الطالب.',
    paragraph:'الإفراط في اللعب يضر الطالب. (ص16)',
    correctAnswer:true,
    explanation:'إفراط اللعب = إهمال = ضرر. الاعتدال = خير.',
    goldenRule:'اعتدال = خير. إفراط = ضرر.' },
  { id:'s188',page:18,type:'multipleChoice',bloom:'understand',difficulty:'easy',
    question:'من آداب النوم في البيت:',
    paragraph:'النوم على الجنب الأيمن، قراءة الأذكار، النوم مبكراً. (ص18)',
    options:[{text:'الأذكار + الجنب الأيمن + مبكراً',correct:true},{text:'السهر',correct:false},{text:'النوم على البطن',correct:false},{text:'ترك الأذكار',correct:false}],
    explanation:'آداب النوم = أذكار + جنب أيمن + مبكر.',
    goldenRule:'نوم مؤدب = أذكار + جنب أيمن + مبكر.' },
  { id:'s189',page:7,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "رضا الله في ___ الوالدين."',
    paragraph:'رضا الله في رضا الوالدين. (ص7)',
    blanks:['رضا'],
    wordBank:['رضا','غضب','عقوق','عصيان'],
    explanation:'رضا الوالدين = رضا الله = سعادة.',
    goldenRule:'رضا الوالدين = رضا الله = سعادة.' },
  { id:'s190',page:9,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف الأعمال حسب صاحبها:',
    paragraph:'الأب ينفق، الأم تربي، الجد يدعو، الأخت تساعد. (ص9)',
    categories:['عمل الأب 💼','عمل الأم 💕'],
    items:[
      {text:'الإنفاق',correct_category:0},{text:'الحماية',correct_category:0},
      {text:'التربية',correct_category:1},{text:'الإرضاع',correct_category:1},
    ],
    explanation:'الأب: إنفاق، حماية. الأم: تربية، إرضاع.',
    goldenRule:'لكل فرد في الأسرة دور محدد.' },
  { id:'s191',page:11,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل عضو بدرجة قرابته:',
    paragraph:'الأب أقرب، الأم أقرب، الجد قريب، العم قريب. (ص11)',
    pairs:[{left:'الأب',right:'أقرب'},{left:'الأم',right:'أقرب'},{left:'الجد',right:'قريب جداً'},{left:'العم',right:'قريب'}],
    explanation:'الأبوان أقرب، ثم الأجداد، ثم الأعمام.',
    goldenRule:'درجة القرب = درجة البر.' },
  { id:'s192',page:13,type:'trueFalse',bloom:'remember',difficulty:'easy',
    question:'صلة الرحم = بر الأقارب = بركة في العمر والرزق.',
    paragraph:'صلة الرحم تزيد العمر والرزق. (ص13)',
    correctAnswer:true,
    explanation:'صلة الرحم = بركة = عمر + رزق.',
    goldenRule:'صلة الرحم = بركة + طول عمر + سعة رزق.' },
  { id:'s193',page:15,type:'multipleChoice',bloom:'apply',difficulty:'medium',
    question:'لو غضبت أمك منك، ما الصواب؟',
    paragraph:'رضا الأم من رضا الله. (ص15)',
    options:[{text:'أعتذر وأطلب رضاها',correct:true},{text:'أهجرها',correct:false},{text:'أصرخ',correct:false},{text:'أهرب',correct:false}],
    explanation:'الاعتذار + طلب الرضا = بر + أدب.',
    goldenRule:'غضب الأم = اعتذار + طلب رضا = بر.',
    feedbackQuestion:{question:'لو أمر والدك بأمر يفيدك ولا تحبه، ماذا تفعل؟',
      options:[{text:'أطيع بصدر رحب',correct:true},{text:'أرفض',correct:false},{text:'أعاتبه',correct:false},{text:'أهرب',correct:false}],
      explanation:'طاعة الوالد في النافع = بر + حكمة.'} },
  { id:'s194',page:17,type:'fillBlank',bloom:'understand',difficulty:'easy',
    question:'أكمل: "أعاون أمي في ___ البيت."',
    paragraph:'معاونة الأم في أعمال البيت من برها. (ص17)',
    blanks:['تنظيف'],
    wordBank:['تنظيف','إتلاف','تخريب','إهمال'],
    explanation:'معاونة الأم = بر + حب + راحتها.',
    goldenRule:'معاونة الأم = بر + حب = راحتها.' },
  { id:'s195',page:18,type:'trueFalse',bloom:'evaluate',difficulty:'medium',
    question:'الجلسة العائلية تقوي الألفة بين أفراد الأسرة.',
    paragraph:'الجلوس مع الأسرة يقوي الألفة. (ص18)',
    correctAnswer:true,
    explanation:'جلسة عائلية = ألفة + حب + حوار.',
    goldenRule:'جلسة عائلية = ألفة + حب + حوار.' },
  { id:'s196',page:6,type:'multipleChoice',bloom:'remember',difficulty:'easy',
    question:'الجد والجدة من الأسرة:',
    paragraph:'الجد والجدة من الأسرة الكبيرة. (ص6)',
    options:[{text:'الكبيرة',correct:true},{text:'الصغيرة',correct:false},{text:'الجيران',correct:false},{text:'الغرباء',correct:false}],
    explanation:'الجد والجدة = أسرة كبيرة = لهم فضل البر.',
    goldenRule:'أجداد = أسرة كبيرة = بر + إحسان.' },
  { id:'s197',page:8,type:'ordering',bloom:'apply',difficulty:'medium',
    question:'رتّب واجبات الطالب صباحاً:',
    paragraph:'استيقاظ، وضوء، إفطار، حقيبة، ذهاب. (ص8)',
    items:['ذهاب','حقيبة','إفطار','وضوء','استيقاظ'],
    correctOrder:[4,3,2,1,0],
    explanation:'استيقاظ ← وضوء ← إفطار ← حقيبة ← ذهاب.',
    goldenRule:'صباح منظم = استيقاظ ← وضوء ← إفطار ← حقيبة ← ذهاب.' },
  { id:'s198',page:10,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف أفراد الأسرة حسب درجة القرابة:',
    paragraph:'أقرب: أب، أم. قريب: أخ، أخت. أبعد: عم، عمة. (ص10)',
    categories:['أقرب الأقارب ❤️','أبعد الأقارب 👥'],
    items:[
      {text:'الأب',correct_category:0},{text:'الأم',correct_category:0},{text:'الأخ',correct_category:0},
      {text:'العم',correct_category:1},{text:'العمة',correct_category:1},{text:'الخال',correct_category:1},
    ],
    explanation:'أقرب: أب، أم، أخ. أبعد: عم، عمة، خال.',
    goldenRule:'قرب الصلة = قوة الرابطة = أولوية البر.' },
  { id:'s199',page:12,type:'trueFalse',bloom:'understand',difficulty:'easy',
    question:'الخلاف بين الإخوة يحل بالحوار لا الشجار.',
    paragraph:'الحوار الهادئ يحل الخلاف. (ص12)',
    correctAnswer:true,
    explanation:'حوار = حل. شجار = خراب العلاقة.',
    goldenRule:'خلاف = حوار + احترام = حل.' },
  { id:'s200',page:14,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "أحافظ على ___ بيتي وأرتبه."',
    paragraph:'ترتيب البيت من واجبات الطالب. (ص14)',
    blanks:['ترتيب'],
    wordBank:['ترتيب','إتلاف','تخريب','هدم'],
    explanation:'ترتيب البيت = راحة + احترام.',
    goldenRule:'بيت مرتب = راحة + احترام.' },
  { id:'s201',page:16,type:'multipleChoice',bloom:'understand',difficulty:'easy',
    question:'من آداب الطعام مع الأسرة:',
    paragraph:'غسل اليدين، الأكل باليمين، عدم الإسراف. (ص16)',
    options:[{text:'غسل اليدين + اليمين + عدم الإسراف',correct:true},{text:'الشمال',correct:false},{text:'الإسراف',correct:false},{text:'الأكل وحدك',correct:false}],
    explanation:'آداب الطعام = غسل + يمين + قصد + مشاركة.',
    goldenRule:'طعام مؤدب = غسل + يمين + قصد + مشاركة.' },
  { id:'s202',page:18,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل وقت بنشاطه في البيت:',
    paragraph:'الصباح للدراسة، الظهر للراحة، المساء للأسرة، الليل للنوم. (ص18)',
    pairs:[{left:'الصباح',right:'الدراسة'},{left:'الظهر',right:'الراحة'},{left:'المساء',right:'الأسرة'},{left:'الليل',right:'النوم'}],
    explanation:'كل وقت له نشاطه المناسب.',
    goldenRule:'وقت مناسب + نشاط مناسب = نجاح.' },

  // ── وحدة 2: مدرستتي ──
  { id:'s203',page:20,type:'multipleChoice',bloom:'remember',difficulty:'easy',
    question:'المدرسة تعلّمنا القراءة و:',
    paragraph:'المدرسة تعلّم القراءة والكتابة والآداب. (ص20)',
    options:[{text:'الكتابة والآداب',correct:true},{text:'النوم',correct:false},{text:'اللعب',correct:false},{text:'الأكل',correct:false}],
    explanation:'المدرسة = قراءة + كتابة + آداب + معارف.',
    goldenRule:'مدرسة = معارف + آداب = شخصية.' },
  { id:'s204',page:22,type:'trueFalse',bloom:'understand',difficulty:'easy',
    question:'المعلم يحب الطالب الذي ينصت ويحترم.',
    paragraph:'المعلم يحب المنصت المؤدب. (ص22)',
    correctAnswer:true,
    explanation:'معلم = يحب إنصات + أدب + مثابرة.',
    goldenRule:'طالب محبوب = إنصات + أدب + مثابرة.' },
  { id:'s205',page:24,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف المرافق في المدرسة:',
    paragraph:'تعليمية: فصل، مكتبة، مختبر. رياضية: ساحة، حديقة. خدمية: ممرات، دورة مياه. (ص24)',
    categories:['مرافق تعليمية 📚','مرافق رياضية ⚽'],
    items:[
      {text:'الفصل',correct_category:0},{text:'المكتبة',correct_category:0},{text:'المختبر',correct_category:0},
      {text:'الساحة',correct_category:1},{text:'حديقة المدرسة',correct_category:1},
    ],
    explanation:'تعليمية: فصل، مكتبة، مختبر. رياضية: ساحة، حديقة.',
    goldenRule:'مرافق المدرسة = تعليمية + رياضية + خدمية.' },
  { id:'s206',page:26,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل أدب بوقته:',
    paragraph:'الإنصات أثناء الشرح، رفع اليد للسؤال، السلام عند الدخول، الشكر عند الخروج. (ص26)',
    pairs:[{left:'أثناء الشرح',right:'الإنصات'},{left:'للسؤال',right:'رفع اليد'},{left:'عند الدخول',right:'السلام'},{left:'عند الخروج',right:'الشكر'}],
    explanation:'كل أدب له وقته المناسب.',
    goldenRule:'أدب + وقت = نظام + احترام.' },
  { id:'s207',page:28,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "أحافظ على أدوات المدرسة كأنها ___."',
    paragraph:'أدوات المدرسة أمانة كأدوات بيتك. (ص28)',
    blanks:['أمانة'],
    wordBank:['أمانة','لعب','قمامة','لا شيء'],
    explanation:'أدوات المدرسة = أمانة = حفظ = احترام.',
    goldenRule:'أدوات المدرسة = أمانة = حفظ.' },
  { id:'s208',page:30,type:'trueFalse',bloom:'evaluate',difficulty:'medium',
    question:'الغش في الاختبار سلوك مذموم يضر بالطالب.',
    paragraph:'الغش خيانة وظلم للنفس. (ص30)',
    correctAnswer:true,
    explanation:'غش = خيانة + ظلم. صدق = أمانة + نجاح.',
    goldenRule:'غش = خيانة. صدق = أمانة = نجاح.' },
  { id:'s209',page:32,type:'ordering',bloom:'apply',difficulty:'medium',
    question:'رتّب آداب الدخول للمدرسة:',
    paragraph:'السلام، ترتيب الحقيبة، دخول الفصل، الجلوس. (ص32)',
    items:['الجلوس','دخول الفصل','ترتيب الحقيبة','السلام'],
    correctOrder:[3,2,1,0],
    explanation:'سلام ← حقيبة ← فصل ← جلوس.',
    goldenRule:'دخول مؤدب = سلام + ترتيب + جلوس.' },
  { id:'s210',page:22,type:'multipleChoice',bloom:'evaluate',difficulty:'hard',
    question:'لو نسيت واجبك، ما الصواب؟',
    paragraph:'الصدق خير من الكذب. (ص22)',
    options:[{text:'أعتذر بصدق وأحضره غداً',correct:true},{text:'أكذب',correct:false},{text:'أهرب',correct:false},{text:'أعاتب أمي',correct:false}],
    explanation:'صدق + اعتذار = أدب + أمانة.',
    goldenRule:'صدق = أدب + أمانة = نمو.',
    feedbackQuestion:{question:'لو سألك المعلم ولم تعرف الجواب، ماذا تفعل؟',
      options:[{text:'أقول لا أعرف بأدب',correct:true},{text:'أكذب',correct:false},{text:'أصمت',correct:false},{text:'أضحك',correct:false}],
      explanation:'الصدق في عدم المعرفة أدب.'} },
  { id:'s211',page:24,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف الكلام في الفصل:',
    paragraph:'مسموح: سؤال، جواب. ممنوع: صراخ، شتم، مقاطعة. (ص24)',
    categories:['كلام مسموح ✅','كلام ممنوع ❌'],
    items:[
      {text:'سؤال بأدب',correct_category:0},{text:'جواب الدرس',correct_category:0},
      {text:'صراخ',correct_category:1},{text:'شتم',correct_category:1},{text:'مقاطعة',correct_category:1},
    ],
    explanation:'مسموح: سؤال، جواب. ممنوع: صراخ، شتم، مقاطعة.',
    goldenRule:'كلام الفصل = أدب + فائدة، لا صراخ + شتم.' },
  { id:'s212',page:26,type:'trueFalse',bloom:'understand',difficulty:'easy',
    question:'رفع اليد عند السؤال من آداب الفصل.',
    paragraph:'رفع اليد أدب الفصل. (ص26)',
    correctAnswer:true,
    explanation:'رفع اليد = أدب + نظام + احترام.',
    goldenRule:'رفع اليد = أدب + نظام.' },
  { id:'s213',page:28,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "أحفظ كتبي في ___ نظيفة."',
    paragraph:'حفظ الكتب في حقيبة نظيفة. (ص28)',
    blanks:['حقيبة'],
    wordBank:['حقيبة','الأرض','الشارع','الحديقة'],
    explanation:'حقيبة نظيفة = كتب محفوظة = طالب منظم.',
    goldenRule:'حقيبة نظيفة = كتب محفوظة = طالب منظم.' },
  { id:'s214',page:30,type:'multipleChoice',bloom:'understand',difficulty:'medium',
    question:'النظافة في المدرسة مسؤولية:',
    paragraph:'نظافة المدرسة مسؤولية كل طالب. (ص30)',
    options:[{text:'كل طالب',correct:true},{text:'العامل فقط',correct:false},{text:'المعلم',correct:false},{text:'المدير',correct:false}],
    explanation:'النظافة مسؤولية جماعية لا فرد واحد.',
    goldenRule:'نظافة المدرسة = مسؤولية الجميع = بيتك الثاني.' },
  { id:'s215',page:32,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل شخصية بدورها:',
    paragraph:'المعلم يعلّم، المدير يدير، العامل ينظف، الطالب يتعلم. (ص32)',
    pairs:[{left:'المعلم',right:'يعلّم'},{left:'المدير',right:'يدير'},{left:'العامل',right:'ينظف'},{left:'الطالب',right:'يتعلم'}],
    explanation:'كل شخصية لها دور في منظومة المدرسة.',
    goldenRule:'مدرسة منظمة = معلم + مدير + عامل + طالب.' },

  // ── وحدة 3: حارتي ومدينتي ──
  { id:'s216',page:34,type:'multipleChoice',bloom:'remember',difficulty:'easy',
    question:'الحارة تتكوّن من:',
    paragraph:'الحارة = بيوت + جيران + مرافق قريبة. (ص34)',
    options:[{text:'بيوت + جيران + مرافق قريبة',correct:true},{text:'قارة',correct:false},{text:'دولة',correct:false},{text:'مدينة بعيدة',correct:false}],
    explanation:'حارة = بيوت + جيران + مرافق صغيرة قريبة.',
    goldenRule:'حارة = بيوت + جيران + مرافق قريبة.' },
  { id:'s217',page:36,type:'trueFalse',bloom:'understand',difficulty:'easy',
    question:'حق الجار يشمل السلام والزيارة والمساعدة.',
    paragraph:'حق الجار = سلام + زيارة + مساعدة + إحسان. (ص36)',
    correctAnswer:true,
    explanation:'حق الجار = سلام + زيارة + مساعدة + إحسان.',
    goldenRule:'حق الجار = سلام + زيارة + مساعدة + إحسان.' },
  { id:'s218',page:38,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف ما يوجد في الحارة:',
    paragraph:'حارة: مسجد، متجر، حديقة، صيدلية. بعيد: مطار، مستشفى كبير. (ص38)',
    categories:['مرافق الحارة 🏘️','مرافق بعيدة ✈️'],
    items:[
      {text:'المسجد',correct_category:0},{text:'المتجر',correct_category:0},{text:'الحديقة',correct_category:0},
      {text:'المطار',correct_category:1},{text:'المستشفى الكبير',correct_category:1},
    ],
    explanation:'حارة: مسجد، متجر، حديقة. بعيد: مطار، مستشفى كبير.',
    goldenRule:'حارة = مرافق صغيرة قريبة = خدمة يومية.' },
  { id:'s219',page:40,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل مكان بحجمه:',
    paragraph:'البيت أصغر، الحارة أكبر، الحي أكبر، المدينة أكبر. (ص40)',
    pairs:[{left:'البيت',right:'أصغر'},{left:'الحارة',right:'أكبر'},{left:'الحي',right:'أكبر من الحارة'},{left:'المدينة',right:'أكبر'}],
    explanation:'بيت < حارة < حي < مدينة.',
    goldenRule:'بيت < حارة < حي < مدينة.' },
  { id:'s220',page:42,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "المستشفى مكان ___ المرضى."',
    paragraph:'المستشفى للعلاج. (ص42)',
    blanks:['علاج'],
    wordBank:['علاج','اللعب','النوم','الأكل'],
    explanation:'مستشفى = علاج = صحة.',
    goldenRule:'مستشفى = علاج = صحة.' },
  { id:'s221',page:44,type:'trueFalse',bloom:'evaluate',difficulty:'medium',
    question:'المرافق العامة ملك الجميع فالمحافظة عليها واجب.',
    paragraph:'المرافق العامة ملك الأمة. (ص44)',
    correctAnswer:true,
    explanation:'مرفق عام = ملك الجميع = حفظ = واجب.',
    goldenRule:'مرفق عام = ملك الجميع = حفظ = واجب.' },
  { id:'s222',page:46,type:'ordering',bloom:'apply',difficulty:'medium',
    question:'رتّب من الأصغر للأكبر:',
    paragraph:'بيت < حارة < حي < مدينة. (ص46)',
    items:['المدينة','الحي','الحارة','البيت'],
    correctOrder:[3,2,1,0],
    explanation:'بيت < حارة < حي < مدينة.',
    goldenRule:'بيت < حارة < حي < مدينة.' },
  { id:'s223',page:36,type:'multipleChoice',bloom:'evaluate',difficulty:'hard',
    question:'لو أزعجك جارك بالصوت، ما الصواب؟',
    paragraph:'النصح بأدب خير من العراك. (ص36)',
    options:[{text:'أنصحه بأدب',correct:true},{text:'أصرخ',correct:false},{text:'أضربه',correct:false},{text:'أهجره',correct:false}],
    explanation:'نصح بأدب = حل. صراخ = خراب.',
    goldenRule:'نصح بأدب = حل. صراخ = خراب.',
    feedbackQuestion:{question:'لو سكب جارك ماء أمام بيتك، ماذا تفعل؟',
      options:[{text:'أكلمه بأدب',correct:true},{text:'أصرخ',correct:false},{text:'أسكب مثله',correct:false},{text:'أهجره',correct:false}],
      explanation:'الحوار الهادئ يحل.'} },
  { id:'s224',page:38,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف مرافق المدينة:',
    paragraph:'صحية: مستشفى، صيدلية. تعليمية: مدرسة، جامعة. تجارية: سوق، مطعم. (ص38)',
    categories:['مرافق صحية 🏥','مرافق تعليمية 🏫'],
    items:[
      {text:'مستشفى',correct_category:0},{text:'صيدلية',correct_category:0},
      {text:'مدرسة',correct_category:1},{text:'جامعة',correct_category:1},
    ],
    explanation:'صحية: مستشفى، صيدلية. تعليمية: مدرسة، جامعة.',
    goldenRule:'مدينة متكاملة = صحة + تعليم + تجارة + ترفيه.' },
  { id:'s225',page:40,type:'trueFalse',bloom:'understand',difficulty:'easy',
    question:'المدينة أكبر من الحارة وفيها أحياء كثيرة.',
    paragraph:'المدينة = أحياء + مرافق كبيرة. (ص40)',
    correctAnswer:true,
    explanation:'مدينة = أحياء + مرافق كبيرة + سكان كثر.',
    goldenRule:'مدينة > حارة = أحياء + مرافق كبيرة.' },
  { id:'s226',page:42,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "السوق مكان ___ السلع."',
    paragraph:'السوق للتسوق وشراء السلع. (ص42)',
    blanks:['شراء'],
    wordBank:['شراء','علاج','لعب','نوم'],
    explanation:'سوق = شراء + بيع = تجارة.',
    goldenRule:'سوق = شراء + بيع = تجارة.' },
  { id:'s227',page:44,type:'multipleChoice',bloom:'understand',difficulty:'medium',
    question:'الشارع في الحارة للسيارات، فالأطفال يلعبون في:',
    paragraph:'الشارع خطر، فاللعب في الحديقة. (ص44)',
    options:[{text:'الحديقة',correct:true},{text:'الشارع',correct:false},{text:'السطح',correct:false},{text:'المطبخ',correct:false}],
    explanation:'حديقة = أمان. شارع = خطر.',
    goldenRule:'حديقة = أمان للّعب. شارع = خطر.' },
  { id:'s228',page:46,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل سلوك بأثره على الحارة:',
    paragraph:'نظافة = راحة، قذارة = مرض، مساعدة = محبة، إيذاء = عداوة. (ص46)',
    pairs:[{left:'النظافة',right:'راحة'},{left:'القذارة',right:'مرض'},{left:'المساعدة',right:'محبة'},{left:'الإيذاء',right:'عداوة'}],
    explanation:'كل سلوك = أثر على الحارة.',
    goldenRule:'سلوكك = أثر. اختر الأثر الحسن.' },

  // ── وحدة 4: وطنيي المملكة ──
  { id:'s229',page:48,type:'multipleChoice',bloom:'remember',difficulty:'easy',
    question:'عاصمة المملكة العربية السعودية:',
    paragraph:'الرياض عاصمة المملكة. (ص48)',
    options:[{text:'الرياض',correct:true},{text:'جدة',correct:false},{text:'مكة',correct:false},{text:'الدمام',correct:false}],
    explanation:'الرياض = عاصمة = وسط المملكة.',
    goldenRule:'الرياض = عاصمة المملكة العربية السعودية.' },
  { id:'s230',page:50,type:'trueFalse',bloom:'remember',difficulty:'easy',
    question:'علم المملكة لونه أخضر وفيه الشهادتان والسيف.',
    paragraph:'العلم السعودي أخضر + الشهادتان + سيف. (ص50)',
    correctAnswer:true,
    explanation:'علم = أخضر + شهادتان + سيف = رمز الإسلام.',
    goldenRule:'علم سعودي = أخضر + شهادتان + سيف.' },
  { id:'s231',page:52,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف المناطق حسب الاتجاه:',
    paragraph:'شمال: تبوك، الجوف. جنوب: عسير، جازان. شرق: الشرقية. غرب: مكة، المدينة. (ص52)',
    categories:['مناطق شمالية 🏜️','مناطق جنوبية 🏔️'],
    items:[
      {text:'تبوك',correct_category:0},{text:'الجوف',correct_category:0},
      {text:'عسير',correct_category:1},{text:'جازان',correct_category:1},
    ],
    explanation:'شمال: تبوك، الجوف. جنوب: عسير، جازان.',
    goldenRule:'شمال=تبوك، جنوب=عسير. كل اتجاه له مناطقه.' },
  { id:'s232',page:54,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل مدينة بمنطقتها:',
    paragraph:'الرياض في منطقة الرياض، جدة في منطقة مكة، الدمام في الشرقية. (ص54)',
    pairs:[{left:'الرياض',right:'منطقة الرياض'},{left:'جدة',right:'منطقة مكة'},{left:'الدمام',right:'المنطقة الشرقية'},{left:'المدينة',right:'منطقة المدينة'}],
    explanation:'كل مدينة تنتمي لمنطقتها الإدارية.',
    goldenRule:'المدينة تنتمي للمنطقة الإدارية.' },
  { id:'s233',page:56,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "مكة المكرمة بها ___ المشرفة."',
    paragraph:'مكة بها الكعبة المشرفة. (ص56)',
    blanks:['الكعبة'],
    wordBank:['الكعبة','البرج','النافورة','القصر'],
    explanation:'مكة = الكعبة = قبلة المسلمين.',
    goldenRule:'مكة = الكعبة = قبلة المسلمين.' },
  { id:'s234',page:58,type:'trueFalse',bloom:'understand',difficulty:'easy',
    question:'المدينة المنورة بها المسجد النبوي الشريف.',
    paragraph:'المدينة = المسجد النبوي. (ص58)',
    correctAnswer:true,
    explanation:'المدينة = المسجد النبوي = ثاني أقدس المساجد.',
    goldenRule:'المدينة = المسجد النبوي = ثاني أقدس المساجد.' },
  { id:'s235',page:60,type:'multipleChoice',bloom:'remember',difficulty:'easy',
    question:'مؤسس المملكة العربية السعودية:',
    paragraph:'الملك عبدالعزيز آل سعود مؤسس المملكة. (ص60)',
    options:[{text:'الملك عبدالعزيز آل سعود',correct:true},{text:'الملك فيصل',correct:false},{text:'الملك خالد',correct:false},{text:'الملك فهد',correct:false}],
    explanation:'الملك عبدالعزيز = المؤسس = الموحّد.',
    goldenRule:'المؤسس = الملك عبدالعزيز آل سعود.' },
  { id:'s236',page:62,type:'ordering',bloom:'apply',difficulty:'hard',
    question:'رتّب مراحل تأسيس المملكة:',
    paragraph:'استرداد الرياض، توحيد نجد، توحيد الحجاز، إعلان المملكة. (ص62)',
    items:['إعلان المملكة','توحيد الحجاز','توحيد نجد','استرداد الرياض'],
    correctOrder:[3,2,1,0],
    explanation:'الرياض ← نجد ← الحجاز ← المملكة.',
    goldenRule:'توحيد: الرياض ← نجد ← الحجاز ← المملكة.' },
  { id:'s237',page:64,type:'trueFalse',bloom:'evaluate',difficulty:'medium',
    question:'حب الوطن عمل لا قول فقط.',
    paragraph:'حب الوطن يظهر في الأعمال. (ص64)',
    correctAnswer:true,
    explanation:'حب الوطن = عمل = نظافة + خدمة + دفاع.',
    goldenRule:'حب الوطن = عمل = نظافة + خدمة + دفاع.' },
  { id:'s238',page:66,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "أفخر بكوني مواطناً في المملكة العربية ___."',
    paragraph:'المملكة العربية السعودية وطننا. (ص66)',
    blanks:['السعودية'],
    wordBank:['السعودية','المغرب','مصر','الأردن'],
    explanation:'المملكة العربية السعودية = وطننا = فخرنا.',
    goldenRule:'وطني = المملكة العربية السعودية = فخري.' },
  { id:'s239',page:50,type:'multipleChoice',bloom:'remember',difficulty:'easy',
    question:'عدد مناطق المملكة العربية السعودية:',
    paragraph:'المملكة = 13 منطقة إدارية. (ص52)',
    options:[{text:'13 منطقة',correct:true},{text:'5 مناطق',correct:false},{text:'20 منطقة',correct:false},{text:'10 مناطق',correct:false}],
    explanation:'المملكة = 13 منطقة إدارية.',
    goldenRule:'المملكة = 13 منطقة إدارية.' },
  { id:'s240',page:54,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف المدن حسب موقعها:',
    paragraph:'غرب: مكة، المدينة، جدة. شرق: الدمام، الخبر، الأحساء. (ص54)',
    categories:['غرب المملكة 🌊','شرق المملكة 🛢️'],
    items:[
      {text:'مكة',correct_category:0},{text:'المدينة',correct_category:0},{text:'جدة',correct_category:0},
      {text:'الدمام',correct_category:1},{text:'الخبر',correct_category:1},{text:'الأحساء',correct_category:1},
    ],
    explanation:'غرب: مكة، المدينة، جدة. شرق: الدمام، الخبر، الأحساء.',
    goldenRule:'غرب=بحر أحمر، شرق=خليج عربي.' },
  { id:'s241',page:56,type:'trueFalse',bloom:'understand',difficulty:'easy',
    question:'مكة المكرمة أعظم مدينة عند المسلمين.',
    paragraph:'مكة = الكعبة = أعظم مدينة. (ص56)',
    correctAnswer:true,
    explanation:'مكة = الكعبة = قبلة المسلمين = أعظم مدينة.',
    goldenRule:'مكة = الكعبة = أعظم مدينة مقدسة.' },
  { id:'s242',page:58,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل مدينة بأهم معلم فيها:',
    paragraph:'مكة=الكعبة، المدينة=المسجد النبوي، الرياض=برج المملكة، جدة=نافورة. (ص58)',
    pairs:[{left:'مكة',right:'الكعبة'},{left:'المدينة',right:'المسجد النبوي'},{left:'الرياض',right:'برج المملكة'},{left:'جدة',right:'النافورة'}],
    explanation:'كل مدينة لها معالمها المميزة.',
    goldenRule:'مدينة = معالم = هوية.' },
  { id:'s243',page:60,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "تأسست المملكة عام ___ هـ."',
    paragraph:'المملكة تأسست عام 1351هـ. (ص60)',
    blanks:['1351'],
    wordBank:['1351','1932','1447','1300'],
    explanation:'المملكة تأسست عام 1351هـ الموافق 1932م.',
    goldenRule:'تأسيس المملكة = 1351هـ = 1932م.' },
  { id:'s244',page:62,type:'multipleChoice',bloom:'understand',difficulty:'medium',
    question:'المملكة العربية السعودية تطلّ على:',
    paragraph:'المملكة تطلّ على البحر الأحمر والخليج العربي. (ص62)',
    options:[{text:'البحر الأحمر والخليج العربي',correct:true},{text:'بحر واحد',correct:false},{text:'لا بحر',correct:false},{text:'ثلاثة بحار',correct:false}],
    explanation:'المملكة = بحر أحمر (غرب) + خليج عربي (شرق).',
    goldenRule:'غرب=بحر أحمر، شرق=خليج عربي.' },
  { id:'s245',page:64,type:'trueFalse',bloom:'evaluate',difficulty:'medium',
    question:'الدفاع عن الوطن واجب كل مواطن بطريقته.',
    paragraph:'حماية الوطن مسؤولية كل مواطن. (ص64)',
    correctAnswer:true,
    explanation:'الدفاع = جند + عمل + علم + أخلاق = كل مواطن.',
    goldenRule:'الدفاع عن الوطن = واجب الجميع.' },
  { id:'s246',page:66,type:'ordering',bloom:'apply',difficulty:'medium',
    question:'رتّب المدن من الغرب للشرق:',
    paragraph:'جدة غرباً، الرياض وسطاً، الدمام شرقاً. (ص66)',
    items:['الدمام','الرياض','جدة'],
    correctOrder:[2,1,0],
    explanation:'جدة (غرب) ← الرياض (وسط) ← الدمام (شرق).',
    goldenRule:'غرب=جدة، وسط=الرياض، شرق=الدمام.' },
  { id:'s247',page:48,type:'multipleChoice',bloom:'evaluate',difficulty:'hard',
    question:'لماذا الرياض عاصمة المملكة؟',
    paragraph:'الرياض في وسط المملكة وبها مرافق الدولة. (ص48)',
    options:[{text:'لأنها في الوسط وبها مرافق الدولة',correct:true},{text:'لأنها أقدم مدينة',correct:false},{text:'لأنها على البحر',correct:false},{text:'لأنها أصغر المدن',correct:false}],
    explanation:'الرياض = وسط + مرافق الدولة = عاصمة.',
    goldenRule:'العاصمة = وسط + مرافق الدولة.' },
  { id:'s248',page:50,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "لون علم المملكة العربية السعودية ___."',
    paragraph:'علم المملكة لونه أخضر. (ص50)',
    blanks:['أخضر'],
    wordBank:['أخضر','أحمر','أزرق','أصفر'],
    explanation:'أخضر = العلم السعودي = الإسلام.',
    goldenRule:'أخضر = العلم السعودي = الإسلام.' },
  { id:'s249',page:52,type:'trueFalse',bloom:'remember',difficulty:'easy',
    question:'منطقة عسير في جنوب المملكة وفيها جبال.',
    paragraph:'عسير في جنوب المملكة وفيها جبال السودة. (ص52)',
    correctAnswer:true,
    explanation:'عسير = جنوب = جبال = مناخ معتدل.',
    goldenRule:'عسير = جنوب = جبال = مناخ معتدل.' },
  { id:'s250',page:54,type:'classify',bloom:'analyze',difficulty:'hard',
    question:'صنّف المعالم حسب مكانها:',
    paragraph:'مكة: الكعبة. المدينة: المسجد النبوي. الرياض: برج المملكة. (ص54)',
    categories:['مكة المكرمة 🕋','المدينة المنورة 🕌'],
    items:[
      {text:'الكعبة',correct_category:0},{text:'المسجد الحرام',correct_category:0},
      {text:'المسجد النبوي',correct_category:1},{text:'قبر النبي ﷺ',correct_category:1},
    ],
    explanation:'مكة: كعبة، مسجد حرام. المدينة: مسجد نبوي، قبر النبي ﷺ.',
    goldenRule:'مكة=كعبة، المدينة=مسجد نبوي. مدينتان مقدستان.' },
  { id:'s251',page:56,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل سلوك بأثره على الوطن:',
    paragraph:'النظافة = جمال، الدفاع = حماية، العبث = إفساد، التعلم = تقدّم. (ص56)',
    pairs:[{left:'النظافة',right:'جمال الوطن'},{left:'الدفاع',right:'حماية الوطن'},{left:'العبث',right:'إفساد الوطن'},{left:'التعلم',right:'تقدّم الوطن'}],
    explanation:'كل سلوك = أثر على الوطن.',
    goldenRule:'سلوكك نحو وطنك = أثر. اختر الأثر الحسن.' },
  { id:'s252',page:58,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "أصلّي نحو ___ في كل صلاتي."',
    paragraph:'القبلة هي الكعبة في مكة. (ص58)',
    blanks:['الكعبة'],
    wordBank:['الكعبة','الشمس','القمر','الجبل'],
    explanation:'القبلة = الكعبة = مكة = اتجاه الصلاة.',
    goldenRule:'القبلة = الكعبة = مكة = اتجاه كل صلاة.' },
  { id:'s253',page:60,type:'trueFalse',bloom:'understand',difficulty:'easy',
    question:'الإسلام دين المملكة الرسمي والقرآن دستورها.',
    paragraph:'الإسلام دين المملكة والقرآن دستورها. (ص60)',
    correctAnswer:true,
    explanation:'المملكة = الإسلام + القرآن دستور = دولة مسلمة.',
    goldenRule:'المملكة = الإسلام + القرآن دستور = دولة مسلمة.' },
  { id:'s254',page:62,type:'multipleChoice',bloom:'understand',difficulty:'medium',
    question:'البحر الأحمر يقع ___ المملكة العربية السعودية.',
    paragraph:'البحر الأحمر غرب المملكة. (ص62)',
    options:[{text:'غرب',correct:true},{text:'شرق',correct:false},{text:'شمال',correct:false},{text:'جنوب',correct:false}],
    explanation:'البحر الأحمر = غرب. الخليج العربي = شرق.',
    goldenRule:'غرب=بحر أحمر، شرق=خليج عربي.' },
  { id:'s255',page:64,type:'fillBlank',bloom:'understand',difficulty:'easy',
    question:'أكمل: "من واجبي نحو وطني الدفاع عنه و___ على مرافقه."',
    paragraph:'الدفاع عن الوطن والمحافظة على مرافقه واجب. (ص64)',
    blanks:['المحافظة'],
    wordBank:['المحافظة','العبث','الإفساد','الإهمال'],
    explanation:'حب الوطن = دفاع + محافظة + احترام.',
    goldenRule:'حب الوطن = دفاع + محافظة + احترام.' },
  { id:'s256',page:66,type:'trueFalse',bloom:'evaluate',difficulty:'medium',
    question:'المشاركة في نظافة الحي من حب الوطن.',
    paragraph:'نظافة الحي عمل وطني. (ص66)',
    correctAnswer:true,
    explanation:'نظافة الحي = حب الوطن = عمل.',
    goldenRule:'نظافة الحي = حب الوطن = عمل.' },
  { id:'s257',page:48,type:'multipleChoice',bloom:'remember',difficulty:'easy',
    question:'المملكة العربية السعودية تقع في:',
    paragraph:'المملكة في جنوب غرب آسيا في شبه الجزيرة العربية. (ص48)',
    options:[{text:'شبه الجزيرة العربية',correct:true},{text:'أوروبا',correct:false},{text:'أفريقيا',correct:false},{text:'أمريكا',correct:false}],
    explanation:'المملكة = شبه الجزيرة العربية = جنوب غرب آسيا.',
    goldenRule:'المملكة = شبه الجزيرة العربية = جنوب غرب آسيا.' },
  { id:'s258',page:50,type:'trueFalse',bloom:'remember',difficulty:'easy',
    question:'اللون الأخضر في العلم السعودي يرمز للإسلام.',
    paragraph:'الأخضر لون الإسلام. (ص50)',
    correctAnswer:true,
    explanation:'أخضر = الإسلام = رمز في العلم السعودي.',
    goldenRule:'أخضر = الإسلام = رمز في العلم السعودي.' },
  { id:'s259',page:52,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف المدن حسب موقعها:',
    paragraph:'وسط: الرياض. غرب: مكة، جدة. شرق: الدمام. شمال: تبوك. جنوب: أبها. (ص52)',
    categories:['مدن وسط وغرب 🕌','مدن شرق وشمال 🛢️'],
    items:[
      {text:'الرياض',correct_category:0},{text:'مكة',correct_category:0},{text:'جدة',correct_category:0},
      {text:'الدمام',correct_category:1},{text:'تبوك',correct_category:1},
    ],
    explanation:'وسط/غرب: الرياض، مكة، جدة. شرق/شمال: الدمام، تبوك.',
    goldenRule:'مدن المملكة موزعة على الاتجاهات الأربعة.' },
  { id:'s260',page:54,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل بحر بموقعه:',
    paragraph:'البحر الأحمر غرب المملكة، الخليج العربي شرقها. (ص54)',
    pairs:[{left:'البحر الأحمر',right:'غرب المملكة'},{left:'الخليج العربي',right:'شرق المملكة'},{left:'المملكة',right:'بينهما'},{left:'الساحل',right:'عند البحر'}],
    explanation:'المملكة بين بحرين: أحمر غرباً وخليج شرقاً.',
    goldenRule:'المملكة بين بحرين = أحمر غرب + خليج شرق.' },
  { id:'s261',page:56,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "أكبر مدينة في المملكة هي ___."',
    paragraph:'الرياض أكبر مدن المملكة. (ص56)',
    blanks:['الرياض'],
    wordBank:['الرياض','جدة','تبوك','أبها'],
    explanation:'الرياض = أكبر مدينة = عاصمة = وسط.',
    goldenRule:'الرياض = أكبر مدينة = عاصمة = وسط.' },
  { id:'s262',page:58,type:'trueFalse',bloom:'understand',difficulty:'easy',
    question:'المدينة المنورة بها المسجد النبوي وقبر النبي ﷺ.',
    paragraph:'المدينة = المسجد النبوي. (ص58)',
    correctAnswer:true,
    explanation:'المدينة = المسجد النبوي = ثاني أقدس المساجد.',
    goldenRule:'المدينة = المسجد النبوي = ثاني أقدس المساجد.' },
  { id:'s263',page:60,type:'multipleChoice',bloom:'remember',difficulty:'easy',
    question:'المملكة العربية السعودية أكبر دولة في:',
    paragraph:'المملكة أكبر دولة في شبه الجزيرة العربية. (ص60)',
    options:[{text:'شبه الجزيرة العربية',correct:true},{text:'أوروبا',correct:false},{text:'أفريقيا',correct:false},{text:'آسيا',correct:false}],
    explanation:'المملكة = أكبر دولة = شبه الجزيرة العربية.',
    goldenRule:'المملكة = أكبر دولة في شبه الجزيرة العربية.' },
  { id:'s264',page:62,type:'ordering',bloom:'apply',difficulty:'medium',
    question:'رتّب المدن من الشمال للجنوب:',
    paragraph:'تبوك شمالاً، الرياض وسطاً، عسير جنوباً. (ص62)',
    items:['عسير','الرياض','تبوك'],
    correctOrder:[2,1,0],
    explanation:'تبوك (شمال) ← الرياض (وسط) ← عسير (جنوب).',
    goldenRule:'شمال=تبوك، وسط=الرياض، جنوب=عسير.' },
  { id:'s265',page:64,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف السلوكيات نحو الوطن:',
    paragraph:'إيجابي: نظافة، دفاع، تعلم. سلبي: عبث، إهمال، تخريب. (ص64)',
    categories:['سلوك إيجابي ✅','سلوك سلبي ❌'],
    items:[
      {text:'النظافة',correct_category:0},{text:'الدفاع',correct_category:0},{text:'التعلم',correct_category:0},
      {text:'العبث',correct_category:1},{text:'الإهمال',correct_category:1},{text:'التخريب',correct_category:1},
    ],
    explanation:'إيجابي: نظافة، دفاع، تعلم. سلبي: عبث، إهمال، تخريب.',
    goldenRule:'حب الوطن = نظافة + دفاع + تعلم، لا عبث + إهمال.' },
  { id:'s266',page:66,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل مدينة بأهم معلم فيها:',
    paragraph:'مكة=الكعبة، المدينة=المسجد النبوي، الرياض=برج المملكة، جدة=نافورة. (ص66)',
    pairs:[{left:'مكة',right:'الكعبة'},{left:'المدينة',right:'المسجد النبوي'},{left:'الرياض',right:'برج المملكة'},{left:'جدة',right:'النافورة'}],
    explanation:'كل مدينة لها معالمها المميزة.',
    goldenRule:'مدينة = معالم = هوية.' },
  { id:'s267',page:48,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "عاصمة المملكة العربية السعودية هي ___."',
    paragraph:'الرياض عاصمة المملكة. (ص48)',
    blanks:['الرياض'],
    wordBank:['الرياض','جدة','مكة','الدمام'],
    explanation:'الرياض = عاصمة = وسط المملكة.',
    goldenRule:'الرياض = عاصمة المملكة العربية السعودية.' },
  { id:'s268',page:50,type:'trueFalse',bloom:'remember',difficulty:'easy',
    question:'في وسط العلم السعودي الشهادتان والسيف.',
    paragraph:'العلم فيه الشهادتان والسيف. (ص50)',
    correctAnswer:true,
    explanation:'وسط العلم = الشهادتان + سيف.',
    goldenRule:'وسط العلم = الشهادتان + سيف.' },
  { id:'s269',page:52,type:'multipleChoice',bloom:'remember',difficulty:'medium',
    question:'من مناطق المملكة الجنوبية:',
    paragraph:'عسير وجازان ونجران من المناطق الجنوبية. (ص52)',
    options:[{text:'عسير وجازان ونجران',correct:true},{text:'تبوك',correct:false},{text:'الجوف',correct:false},{text:'الرياض',correct:false}],
    explanation:'جنوب: عسير، جازان، نجران = جبال + مناخ معتدل.',
    goldenRule:'جنوب=عسير+جازان+نجران=جبال.' },
  { id:'s270',page:54,type:'classify',bloom:'analyze',difficulty:'hard',
    question:'صنّف المعالم حسب مكانها:',
    paragraph:'مكة: الكعبة، المسجد الحرام. المدينة: المسجد النبوي، قبر النبي ﷺ. الرياض: برج المملكة. (ص54)',
    categories:['مكة المكرمة 🕋','الرياض 🏙️'],
    items:[
      {text:'الكعبة',correct_category:0},{text:'المسجد الحرام',correct_category:0},
      {text:'برج المملكة',correct_category:1},{text:'قصر الحكم',correct_category:1},
    ],
    explanation:'مكة: كعبة، مسجد حرام. الرياض: برج المملكة، قصر الحكم.',
    goldenRule:'كل مدينة لها معالمها المميزة.' },
  { id:'s271',page:56,type:'fillBlank',bloom:'understand',difficulty:'easy',
    question:'أكمل: "أكبر مدينة في المملكة هي ___."',
    paragraph:'الرياض أكبر مدن المملكة. (ص56)',
    blanks:['الرياض'],
    wordBank:['الرياض','جدة','تبوك','أبها'],
    explanation:'الرياض = أكبر = عاصمة = وسط.',
    goldenRule:'الرياض = أكبر = عاصمة = وسط.' },
  { id:'s272',page:58,type:'trueFalse',bloom:'understand',difficulty:'easy',
    question:'المسجد النبوي في المدينة المنورة.',
    paragraph:'المسجد النبوي في المدينة المنورة. (ص58)',
    correctAnswer:true,
    explanation:'المدينة = المسجد النبوي = ثاني أقدس المساجد.',
    goldenRule:'المدينة = المسجد النبوي = ثاني أقدس المساجد.' },
  { id:'s273',page:60,type:'multipleChoice',bloom:'evaluate',difficulty:'hard',
    question:'لو أردت خدمة وطنك، ما أفضل ما تبدأ به؟',
    paragraph:'خدمة الوطن تبدأ بالعلم والأخلاق والعمل. (ص60)',
    options:[{text:'الدراسة وحسن الأخلاق',correct:true},{text:'اللعب',correct:false},{text:'النوم',correct:false},{text:'الكسل',correct:false}],
    explanation:'خدمة الوطن = علم + أخلاق + عمل.',
    goldenRule:'خدمة الوطن = علم + أخلاق + عمل.',
    feedbackQuestion:{question:'لو رأيت علم الوطن على الأرض، ماذا تفعل؟',
      options:[{text:'أرفعه وأنظّفه باحترام',correct:true},{text:'أتركه',correct:false},{text:'أدوسه',correct:false},{text:'أخبئه',correct:false}],
      explanation:'العلم رمز الوطن، رفعه واحترامه واجب.'} },
  { id:'s274',page:62,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "المملكة العربية السعودية تطلّ على البحر الأحمر والخليج ___."',
    paragraph:'المملكة تطلّ على بحرين. (ص62)',
    blanks:['العربي'],
    wordBank:['العربي','الأحمر','الأسود','الأبيض'],
    explanation:'الخليج العربي = شرق المملكة.',
    goldenRule:'غرب=بحر أحمر، شرق=خليج عربي.' },
  { id:'s275',page:64,type:'trueFalse',bloom:'evaluate',difficulty:'medium',
    question:'التعلم والعمل من خدمة الوطن.',
    paragraph:'التعلم والعمل يقدّمان الوطن. (ص64)',
    correctAnswer:true,
    explanation:'تعلم + عمل = تقدّم = خدمة وطن.',
    goldenRule:'تعلم + عمل = خدمة الوطن = تقدّم.' },
  { id:'s276',page:66,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل سلوك بنتيجته على الوطن:',
    paragraph:'النظافة=جمال، الدفاع=حماية، العبث=إفساد، التعلم=تقدّم. (ص66)',
    pairs:[{left:'النظافة',right:'جمال الوطن'},{left:'الدفاع',right:'حماية الوطن'},{left:'العبث',right:'إفساد الوطن'},{left:'التعلم',right:'تقدّم الوطن'}],
    explanation:'كل سلوك = أثر على الوطن.',
    goldenRule:'سلوكك نحو وطنك = أثر. اختر الأثر الحسن.' },
  { id:'s277',page:48,type:'multipleChoice',bloom:'understand',difficulty:'medium',
    question:'الرياض تقع في:',
    paragraph:'الرياض في وسط المملكة. (ص48)',
    options:[{text:'وسط المملكة',correct:true},{text:'الساحل الغربي',correct:false},{text:'الساحل الشرقي',correct:false},{text:'أقصى الجنوب',correct:false}],
    explanation:'الرياض = وسط المملكة = عاصمة.',
    goldenRule:'الرياض = وسط المملكة = عاصمة.' },
  { id:'s278',page:50,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "في وسط علم المملكة ___ والسيف."',
    paragraph:'العلم فيه الشهادتان والسيف. (ص50)',
    blanks:['الشهادتان'],
    wordBank:['الشهادتان','النجم','الهلال','الصقر'],
    explanation:'الشهادتان + سيف = وسط العلم السعودي.',
    goldenRule:'وسط العلم = الشهادتان + سيف.' },
  { id:'s279',page:52,type:'trueFalse',bloom:'remember',difficulty:'easy',
    question:'منطقة الشرقية في شرق المملكة وفيها نفط.',
    paragraph:'الشرقية = شرق = نفط = الدمام. (ص52)',
    correctAnswer:true,
    explanation:'الشرقية = شرق = نفط = ثروة وطن.',
    goldenRule:'الشرقية = شرق = نفط = ثروة الوطن.' },
  { id:'s280',page:54,type:'ordering',bloom:'apply',difficulty:'medium',
    question:'رتّب المدن من الغرب للشرق:',
    paragraph:'جدة غرباً، الرياض وسطاً، الدمام شرقاً. (ص54)',
    items:['الدمام','الرياض','جدة'],
    correctOrder:[2,1,0],
    explanation:'جدة (غرب) ← الرياض (وسط) ← الدمام (شرق).',
    goldenRule:'غرب=جدة، وسط=الرياض، شرق=الدمام.' },
  { id:'s281',page:56,type:'multipleChoice',bloom:'understand',difficulty:'medium',
    question:'مكة المكرمة مدينة مقدسة لأن فيها:',
    paragraph:'مكة = الكعبة = قبلة المسلمين. (ص56)',
    options:[{text:'الكعبة المشرفة',correct:true},{text:'برج المملكة',correct:false},{text:'نافورة',correct:false},{text:'قصر',correct:false}],
    explanation:'مكة = الكعبة = أعظم مدينة مقدسة.',
    goldenRule:'مكة = الكعبة = أعظم مدينة مقدسة.' },
  { id:'s282',page:58,type:'trueFalse',bloom:'remember',difficulty:'easy',
    question:'الملك عبدالعزيز آل سعود هو مؤسس المملكة.',
    paragraph:'الملك عبدالعزيز مؤسس المملكة. (ص58)',
    correctAnswer:true,
    explanation:'الملك عبدالعزيز = المؤسس = الموحّد.',
    goldenRule:'المؤسس = الملك عبدالعزيز آل سعود.' },
  { id:'s283',page:60,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "مؤسس المملكة هو الملك ___ آل سعود."',
    paragraph:'الملك عبدالعزيز آل سعود مؤسس المملكة. (ص60)',
    blanks:['عبدالعزيز'],
    wordBank:['عبدالعزيز','فيصل','خالد','فهد'],
    explanation:'الملك عبدالعزيز = المؤسس = الموحّد.',
    goldenRule:'المؤسس = الملك عبدالعزيز آل سعود.' },
  { id:'s284',page:62,type:'classify',bloom:'analyze',difficulty:'hard',
    question:'صنّف البحار حسب موقعها:',
    paragraph:'البحر الأحمر غرب المملكة، الخليج العربي شرقها. (ص62)',
    categories:['غرب المملكة 🌊','شرق المملكة 🛢️'],
    items:[
      {text:'البحر الأحمر',correct_category:0},
      {text:'الخليج العربي',correct_category:1},
    ],
    explanation:'غرب=بحر أحمر، شرق=خليج عربي.',
    goldenRule:'المملكة بين بحرين = أحمر غرب + خليج شرق.' },
  { id:'s285',page:64,type:'multipleChoice',bloom:'evaluate',difficulty:'hard',
    question:'أفضل طريقة لإظهار حب الوطن:',
    paragraph:'حب الوطن عمل لا قول. (ص64)',
    options:[{text:'العمل والدراسة والمحافظة',correct:true},{text:'الكلام فقط',correct:false},{text:'الشجار',correct:false},{text:'الكسل',correct:false}],
    explanation:'حب الوطن = عمل = دراسة + محافظة + دفاع.',
    goldenRule:'حب الوطن = عمل = دراسة + محافظة + دفاع.' },
  { id:'s286',page:66,type:'trueFalse',bloom:'evaluate',difficulty:'medium',
    question:'من حب الوطن الدفاع عنه والمحافظة على مرافقه.',
    paragraph:'حب الوطن = دفاع + محافظة. (ص66)',
    correctAnswer:true,
    explanation:'حب الوطن = دفاع + محافظة + احترام.',
    goldenRule:'حب الوطن = دفاع + محافظة + احترام.' },
  { id:'s287',page:48,type:'fillBlank',bloom:'understand',difficulty:'easy',
    question:'أكمل: "الرياض في ___ المملكة العربية السعودية."',
    paragraph:'الرياض في وسط المملكة. (ص48)',
    blanks:['وسط'],
    wordBank:['وسط','شرق','غرب','جنوب'],
    explanation:'الرياض = وسط = عاصمة.',
    goldenRule:'الرياض = وسط المملكة = عاصمة.' },
  { id:'s288',page:50,type:'multipleChoice',bloom:'remember',difficulty:'easy',
    question:'علم المملكة العربية السعودية شكله:',
    paragraph:'العلم السعودي مستطيل أخضر. (ص50)',
    options:[{text:'مستطيل أخضر',correct:true},{text:'مثلث',correct:false},{text:'دائرة',correct:false},{text:'مربع',correct:false}],
    explanation:'العلم = مستطيل + أخضر + شهادتان + سيف.',
    goldenRule:'علم سعودي = مستطيل + أخضر + شهادتان + سيف.' },
  { id:'s289',page:52,type:'trueFalse',bloom:'remember',difficulty:'easy',
    question:'تبوك من مناطق شمال المملكة العربية السعودية.',
    paragraph:'تبوك في شمال المملكة. (ص52)',
    correctAnswer:true,
    explanation:'تبوك = شمال = مناخ معتدل صيفاً.',
    goldenRule:'تبوك = شمال = مناخ معتدل.' },
  { id:'s290',page:54,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل منطقة بموقعها:',
    paragraph:'عسير=جنوب، تبوك=شمال، الشرقية=شرق، مكة=غرب. (ص54)',
    pairs:[{left:'عسير',right:'جنوب'},{left:'تبوك',right:'شمال'},{left:'الشرقية',right:'شرق'},{left:'مكة',right:'غرب'}],
    explanation:'كل منطقة في اتجاه محدد.',
    goldenRule:'مناطق المملكة = شمال + جنوب + شرق + غرب + وسط.' },
  { id:'s291',page:56,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "مكة المكرمة بها ___ المشرفة."',
    paragraph:'مكة بها الكعبة المشرفة. (ص56)',
    blanks:['الكعبة'],
    wordBank:['الكعبة','البرج','النافورة','القصر'],
    explanation:'مكة = الكعبة = قبلة المسلمين.',
    goldenRule:'مكة = الكعبة = قبلة المسلمين.' },
  { id:'s292',page:58,type:'multipleChoice',bloom:'understand',difficulty:'medium',
    question:'المدينة المنورة بها:',
    paragraph:'المدينة = المسجد النبوي. (ص58)',
    options:[{text:'المسجد النبوي',correct:true},{text:'الكعبة',correct:false},{text:'برج المملكة',correct:false},{text:'نافورة',correct:false}],
    explanation:'المدينة = المسجد النبوي = ثاني أقدس المساجد.',
    goldenRule:'المدينة = المسجد النبوي = ثاني أقدس المساجد.' },
  { id:'s293',page:60,type:'trueFalse',bloom:'remember',difficulty:'easy',
    question:'المملكة العربية السعودية تأسست عام 1351هـ.',
    paragraph:'المملكة تأسست عام 1351هـ. (ص60)',
    correctAnswer:true,
    explanation:'المملكة = 1351هـ = 1932م = الملك عبدالعزيز.',
    goldenRule:'تأسيس المملكة = 1351هـ = 1932م.' },
  { id:'s294',page:62,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "البحر الأحمر يقع ___ المملكة."',
    paragraph:'البحر الأحمر غرب المملكة. (ص62)',
    blanks:['غرب'],
    wordBank:['غرب','شرق','شمال','جنوب'],
    explanation:'البحر الأحمر = غرب المملكة.',
    goldenRule:'البحر الأحمر = غرب المملكة.' },
  { id:'s295',page:64,type:'classify',bloom:'analyze',difficulty:'medium',
    question:'صنّف السلوكيات نحو الوطن:',
    paragraph:'إيجابي: نظافة، دفاع، تعلم. سلبي: عبث، إهمال، تخريب. (ص64)',
    categories:['سلوك إيجابي ✅','سلوك سلبي ❌'],
    items:[
      {text:'النظافة',correct_category:0},{text:'الدفاع',correct_category:0},{text:'التعلم',correct_category:0},
      {text:'العبث',correct_category:1},{text:'الإهمال',correct_category:1},{text:'التخريب',correct_category:1},
    ],
    explanation:'إيجابي: نظافة، دفاع، تعلم. سلبي: عبث، إهمال، تخريب.',
    goldenRule:'حب الوطن = نظافة + دفاع + تعلم، لا عبث + إهمال.' },
  { id:'s296',page:66,type:'matching',bloom:'remember',difficulty:'medium',
    question:'صِل كل سلوك بنتيجته:',
    paragraph:'النظافة=جمال، الدفاع=حماية، التعلم=تقدّم، الإهمال=تخلّف. (ص66)',
    pairs:[{left:'النظافة',right:'جمال الوطن'},{left:'الدفاع',right:'حماية الوطن'},{left:'التعلم',right:'تقدّم الوطن'},{left:'الإهمال',right:'تخلّف الوطن'}],
    explanation:'كل سلوك = أثر على الوطن.',
    goldenRule:'سلوكك نحو وطنك = أثر. اختر الأثر الحسن.' },
  { id:'s297',page:48,type:'multipleChoice',bloom:'understand',difficulty:'medium',
    question:'الرياض أكبر مدينة في المملكة لأنها:',
    paragraph:'الرياض أكبر مدن المملكة سكاناً ومساحة. (ص48)',
    options:[{text:'أكبر سكاناً ومساحة وبها مرافق الدولة',correct:true},{text:'أصغر مدن المملكة',correct:false},{text:'لا سكان فيها',correct:false},{text:'على البحر',correct:false}],
    explanation:'الرياض = أكبر + عاصمة + مرافق دولة.',
    goldenRule:'الرياض = أكبر + عاصمة + وسط.' },
  { id:'s298',page:50,type:'trueFalse',bloom:'remember',difficulty:'easy',
    question:'السيف في العلم السعودي يرمز للقوة والعدل.',
    paragraph:'السيف في العلم = قوة + عدل. (ص50)',
    correctAnswer:true,
    explanation:'سيف = قوة + عدل + حماية.',
    goldenRule:'سيف = قوة + عدل + حماية الوطن.' },
  { id:'s299',page:52,type:'fillBlank',bloom:'remember',difficulty:'easy',
    question:'أكمل: "عدد مناطق المملكة العربية السعودية ___ منطقة."',
    paragraph:'المملكة = 13 منطقة إدارية. (ص52)',
    blanks:['13'],
    wordBank:['13','5','20','10'],
    explanation:'المملكة = 13 منطقة إدارية.',
    goldenRule:'المملكة = 13 منطقة إدارية.' },
  { id:'s300',page:54,type:'multipleChoice',bloom:'evaluate',difficulty:'hard',
    question:'لو أردت خدمة وطنك حين تكبر، ما الذي تعدّه الآن؟',
    paragraph:'خدمة الوطن تبدأ بالعلم والأخلاق. (ص54)',
    options:[{text:'الدراسة والأخلاق والعمل',correct:true},{text:'اللعب',correct:false},{text:'النوم',correct:false},{text:'الكسل',correct:false}],
    explanation:'خدمة الوطن = علم + أخلاق + عمل = مستقبل.',
    goldenRule:'خدمة الوطن = علم + أخلاق + عمل = مستقبل زاهر.',
    feedbackQuestion:{question:'لو سألك أحد عن وطنك، كيف تصفه؟',
      options:[{text:'أفخر به وأصف محاسنه',correct:true},{text:'أنتقده',correct:false},{text:'أتجاهل',correct:false},{text:'أكذب',correct:false}],
      explanation:'الفخر بالوطن ووصف محاسنه من حبه.'} },
];