// ═══════════════════════════════════════════════════════
// بنك أسئلة اللغة الإنجليزية — Top Goal 2
// الصف الخامس الابتدائي — الفصل الأول 1447هـ
// المرجع: Student Book + Workbook (كامل)
// ═══════════════════════════════════════════════════════

export const WELCOME_UNIT = {
  id: 'welcome',
  title: 'Welcome! — Dates, Numbers & Review',
  icon: '👋',
  color: '#0891b2',
  bg: 'from-cyan-700 to-teal-500',
  coverImg: null,
  lessons: [
    {
      id: 'w_l1',
      title: 'Dates, Months & Numbers',
      page: '6',
      questions: [
        { type: 'mc', bloom: 'remember', difficulty: 'easy', page: 6,
          q: 'Which month comes AFTER July?', page_ref: 'p.6',
          options: ['June', 'August', 'September', 'October'],
          correct: 1, explanation: 'The months in order: ...June, July, AUGUST, September... August always follows July.',
          golden_rule: 'Months: January → February → March → April → May → June → July → August → September → October → November → December' },
        { type: 'tf', bloom: 'remember', difficulty: 'easy', page: 6,
          q: 'February is the shortest month of the year.', page_ref: 'p.6 WB',
          correct: true, explanation: 'From WB p.121: "February is the shortest month/date of the year" — month is the correct answer.',
          golden_rule: 'February has only 28 days (29 in a leap year) — the shortest month.' },
        { type: 'mc', bloom: 'remember', difficulty: 'easy', page: 6,
          q: 'How do you write 1,000 in words?', page_ref: 'p.121 WB',
          options: ['Ten hundred', 'One thousand', 'A hundred thousand', 'Ten thousand'],
          correct: 1, explanation: 'From WB p.121: 1,000 = one thousand.',
          golden_rule: '1,000 = one thousand | 100 = one hundred | 10 = ten' },
        { type: 'mc', bloom: 'understand', difficulty: 'medium', page: 6,
          q: 'According to the story in Welcome, the food festival is in November. Which month does the calendar show it is NOT in?', page_ref: 'p.120 WB',
          options: ['April', 'January', 'November', 'August'],
          correct: 1, explanation: 'From WB p.120: "It\'s not in January, February, or March." The food festival is on November 16th.',
          golden_rule: 'The food festival date: November 16th — three months from the story time.' },
        { type: 'mc', bloom: 'remember', difficulty: 'easy', page: 6,
          q: 'How many hours are there in a month, according to the Welcome story?', page_ref: 'p.120 WB',
          options: ['500 hours', '730 hours', '1,000 hours', '365 hours'],
          correct: 1, explanation: 'From WB p.120: "There are seven hundred thirty hours in a month" = 730 hours.',
          golden_rule: 'A month ≈ 730 hours (30–31 days × 24 hours).' },
        { type: 'mc', bloom: 'remember', difficulty: 'easy', page: 6,
          q: 'What is 219 in words?', page_ref: 'p.121 WB',
          options: ['Two hundred nine', 'Two hundred nineteen', 'Twenty-one nine', 'Two thousand nineteen'],
          correct: 1, explanation: 'From WB p.121: 219 = two hundred nineteen.',
          golden_rule: '219 = two hundred (and) nineteen.' },
      ]
    },
    {
      id: 'w_l2',
      title: 'Simple Past & Irregular Verbs Review',
      page: '122–123',
      questions: [
        { type: 'mc', bloom: 'remember', difficulty: 'easy', page: 122,
          q: 'What is the simple past form of "go"?', page_ref: 'p.122 WB',
          options: ['goed', 'gone', 'went', 'goes'],
          correct: 2, explanation: 'From WB p.122: "go → went" — irregular verb.',
          golden_rule: 'Irregular verbs: go→went | buy→bought | take→took | wake up→woke up | make→made' },
        { type: 'mc', bloom: 'remember', difficulty: 'easy', page: 122,
          q: 'What is the simple past form of "buy"?', page_ref: 'p.122 WB',
          options: ['buyed', 'buys', 'bought', 'boughted'],
          correct: 2, explanation: 'From WB p.122: "buy → bought" — irregular verb.',
          golden_rule: 'buy → bought (irregular) — NOT buyed!' },
        { type: 'tf', bloom: 'understand', difficulty: 'medium', page: 122,
          q: '"She doesn\'t like scary movies" is the correct negative form of "She likes scary movies."', page_ref: 'p.126 WB',
          correct: true, explanation: 'From WB p.126: Simple present negative: "I don\'t like playing board games." For she/he/it: doesn\'t + base verb.',
          golden_rule: 'Simple present negative: I/you/we/they + DON\'T | he/she/it + DOESN\'T + base verb' },
        { type: 'classify', bloom: 'apply', difficulty: 'medium', page: 122,
          q: 'Classify these verbs: Simple Present or Simple Past?',
          categories: ['Simple Present', 'Simple Past'],
          items: [
            { text: 'watched', correct_cat: 1 }, { text: 'love', correct_cat: 0 },
            { text: 'went', correct_cat: 1 }, { text: 'play', correct_cat: 0 },
            { text: 'bought', correct_cat: 1 }, { text: 'eat', correct_cat: 0 },
          ],
          explanation: 'From WB p.122-126: Past tense verbs end in -ed (regular) or change form (irregular). Present tense verbs stay in base form.',
          golden_rule: 'Simple Past: tells about finished actions. Simple Present: tells about habits & routines.' },
        { type: 'mc', bloom: 'apply', difficulty: 'medium', page: 123,
          q: 'Choose the correct form: "My dad always ___ the guitar when he ___ young."', page_ref: 'p.126 WB',
          options: ['plays / is', 'played / was', 'play / were', 'playing / is'],
          correct: 1, explanation: 'From WB p.126: "My dad played the guitar when he was young." — both verbs in past tense.',
          golden_rule: 'When talking about the past, ALL verbs in the sentence should be in PAST TENSE.' },
        { type: 'mc', bloom: 'remember', difficulty: 'easy', page: 123,
          q: 'What is the superlative form of "large"?', page_ref: 'p.123 WB',
          options: ['the larger', 'the most large', 'the largest', 'larger'],
          correct: 2, explanation: 'From WB p.123: "This is the largest (large) class I teach." — add -st for adjectives ending in -e.',
          golden_rule: 'Superlatives: large→the largest | big→the biggest | good→the best | bad→the worst' },
      ]
    }
  ]
};

export const UNIT1 = {
  id: 'unit1',
  title: 'Unit 1 — Personal Interests',
  icon: '🎯',
  color: '#7c3aed',
  bg: 'from-purple-700 to-violet-500',
  coverImg: null,
  subtitle: 'Join an activity at the youth center!',
  lessons: [
    {
      id: 'u1_l1',
      title: 'Vocabulary: Adjectives for Interests',
      page: '10–16',
      questions: [
        { type: 'mc', bloom: 'remember', difficulty: 'easy', page: 10,
          q: 'In the Top Goal 2 textbook, the word "wonderful" means:', page_ref: 'SB p.10',
          options: ['horrible and boring', 'brilliant and pleasing', 'messy and noisy', 'friendly and lucky'],
          correct: 1, explanation: 'From SB p.10 vocabulary: wonderful = brilliant and pleasing.',
          golden_rule: 'wonderful = brilliant + pleasing (very positive adjective)' },
        { type: 'mc', bloom: 'remember', difficulty: 'easy', page: 10,
          q: 'Which adjective means "someone or something that scares you"?', page_ref: 'SB p.10',
          options: ['noisy', 'tidy', 'frightening', 'special'],
          correct: 2, explanation: 'From SB p.10: frightening = scary.',
          golden_rule: 'frightening / scary = something that causes fear (same meaning)' },
        { type: 'mc', bloom: 'understand', difficulty: 'easy', page: 16,
          q: 'What does "unfriendly" mean?', page_ref: 'SB p.16',
          options: ['very friendly', 'not friendly', 'extremely friendly', 'sometimes friendly'],
          correct: 1, explanation: 'From SB p.16: The prefix UN- means NOT. unfriendly = not friendly.',
          golden_rule: 'UN- prefix = NOT: unfriendly, unkind, unlucky, untidy, unusual, unhappy' },
        { type: 'classify', bloom: 'apply', difficulty: 'medium', page: 16,
          q: 'Classify these adjectives: Positive (+) or Negative (-)?',
          categories: ['Positive (+)', 'Negative (-)'],
          items: [
            { text: 'wonderful', correct_cat: 0 }, { text: 'horrible', correct_cat: 1 },
            { text: 'excellent', correct_cat: 0 }, { text: 'messy', correct_cat: 1 },
            { text: 'special', correct_cat: 0 }, { text: 'unkind', correct_cat: 1 },
          ],
          explanation: 'From SB pp.10-16: adjectives with un- prefix or bad meaning are negative.',
          golden_rule: 'Positive: wonderful, excellent, special, amazing, lovely. Negative: horrible, messy, noisy, frightening, unkind.' },
        { type: 'mc', bloom: 'remember', difficulty: 'easy', page: 10,
          q: 'The word "enormous" means:', page_ref: 'SB p.10',
          options: ['very small', 'very big', 'very fast', 'very loud'],
          correct: 1, explanation: 'From SB p.10: enormous = very big (synonym: huge, giant).',
          golden_rule: 'enormous = huge = very big' },
        { type: 'mc', bloom: 'apply', difficulty: 'medium', page: 16,
          q: 'Complete the sentence: "My room is always clean and organized. I am very ___."', page_ref: 'WB p.124',
          options: ['noisy', 'messy', 'tidy', 'frightening'],
          correct: 2, explanation: 'From WB p.124: "My classroom is very tidy. It\'s always clean and organized."',
          golden_rule: 'tidy = clean and organized (opposite = messy/untidy)' },
      ]
    },
    {
      id: 'u1_l2',
      title: 'Grammar: Simple Past & Present',
      page: '12–15',
      questions: [
        { type: 'mc', bloom: 'understand', difficulty: 'medium', page: 12,
          q: 'Which sentence is in the SIMPLE PAST tense?', page_ref: 'SB p.12',
          options: ['I play board games every weekend.', 'She watches movies on Fridays.', 'We went to the movie theater.', 'They enjoy hiking.'],
          correct: 2, explanation: 'From SB p.12: "went" is the past tense of "go" — irregular past tense.',
          golden_rule: 'Simple Past = finished action. Signal words: yesterday, last week, ago, in 2020.' },
        { type: 'tf', bloom: 'remember', difficulty: 'easy', page: 13,
          q: 'The simple past of "watch" is "watched" (regular verb).', page_ref: 'WB p.126',
          correct: true, explanation: 'From WB p.126: watch → watched (regular: add -ed).',
          golden_rule: 'Regular verbs: add -ED for past. Irregular: must memorize (go→went, buy→bought).' },
        { type: 'mc', bloom: 'apply', difficulty: 'medium', page: 14,
          q: 'Choose the correct option: "Last Saturday I ___ swimming with my family."', page_ref: 'WB p.126',
          options: ['go', 'goes', 'went', 'going'],
          correct: 2, explanation: 'From WB p.126: "Last Saturday" signals past tense. go→went (irregular).',
          golden_rule: 'Past signal words: last (week/year/Saturday), yesterday, ago — always use PAST TENSE verb.' },
        { type: 'classify', bloom: 'apply', difficulty: 'hard', page: 15,
          q: 'Classify these verbs: ACTION verbs or STATE verbs?',
          categories: ['Action Verbs', 'State Verbs'],
          items: [
            { text: 'walk', correct_cat: 0 }, { text: 'love', correct_cat: 1 },
            { text: 'cook', correct_cat: 0 }, { text: 'know', correct_cat: 1 },
            { text: 'dance', correct_cat: 0 }, { text: 'prefer', correct_cat: 1 },
          ],
          explanation: 'From WB p.131: Action verbs describe things we DO. State verbs describe feelings/states (love, know, prefer, want, understand, believe).',
          golden_rule: 'State verbs (love, know, prefer, want, understand, believe) CANNOT use -ing form in present continuous.' },
        { type: 'mc', bloom: 'understand', difficulty: 'medium', page: 15,
          q: 'Which sentence is CORRECT?', page_ref: 'WB p.131',
          options: ['She is preferring sunny days.', 'She prefers sunny days.', 'She prefers sunny days right now.', 'She was preferring sunny days.'],
          correct: 1, explanation: 'From WB p.131: "prefers" — state verbs don\'t use continuous form (-ing).',
          golden_rule: 'State verbs use SIMPLE form, not continuous: "I prefer" NOT "I am preferring".' },
        { type: 'mc', bloom: 'apply', difficulty: 'medium', page: 15,
          q: 'Complete: "He ___ in his notebook right now."', page_ref: 'WB p.131',
          options: ['write', 'writes', 'is writing', 'written'],
          correct: 2, explanation: 'From WB p.131: "right now" → present continuous → is + verb-ing. "write" is an action verb so it CAN use -ing.',
          golden_rule: '"Right now / at the moment" → Present Continuous (am/is/are + verb-ing).' },
      ]
    },
    {
      id: 'u1_l3',
      title: 'Story: Lia and Ava / Reading: Unusual Hobbies',
      page: '17–19',
      questions: [
        { type: 'mc', bloom: 'remember', difficulty: 'easy', page: 17,
          q: 'In the story "A New Friend" (SB Unit 1), what do Chloe and Lia do every Wednesday?', page_ref: 'WB p.128',
          options: ['They go hiking.', 'They play video games.', 'They cook together.', 'They watch movies.'],
          correct: 1, explanation: 'From WB p.128: "Chloe and Lia play video games on Wednesdays."',
          golden_rule: 'Story detail: Chloe and Lia → video games → every Wednesday.' },
        { type: 'tf', bloom: 'understand', difficulty: 'medium', page: 17,
          q: 'In the story, Lia was happy when Ava joined them to play video games.', page_ref: 'WB p.128',
          correct: false, explanation: 'From WB p.128: "Lia wasn\'t friendly" and "Lia was upset" when Ava walked in.',
          golden_rule: 'Lia\'s feelings in order: upset → unfriendly → eventually happy (when Ava played her favorite game).' },
        { type: 'mc', bloom: 'understand', difficulty: 'medium', page: 19,
          q: 'In the reading "Unusual Hobbies" (WB p.132), which activity uses a rope and helmet?', page_ref: 'WB p.132',
          options: ['Scrapbooking', 'Playing the piano', 'Rock climbing', 'Board game collecting'],
          correct: 2, explanation: 'From WB p.132: "Rock climbing... you use a rope, a helmet, and special shoes to climb rock walls."',
          golden_rule: 'Rock climbing equipment: rope + helmet + special shoes.' },
        { type: 'mc', bloom: 'apply', difficulty: 'hard', page: 19,
          q: 'From the reading in WB p.132, which hobby is described as "a free-time activity where you use photos, colors, stickers, and souvenirs"?', page_ref: 'WB p.132',
          options: ['Rock climbing', 'Playing the piano', 'Scrapbooking', 'Movie reviewing'],
          correct: 2, explanation: 'From WB p.132: "Scrapbooking: you use photos, colors, stickers, and all kinds of souvenirs to create personalized photo albums."',
          golden_rule: 'Scrapbooking = creating photo albums with photos, stickers, and souvenirs.' },
      ]
    }
  ]
};

export const UNIT2 = {
  id: 'unit2',
  title: 'Unit 2 — House Designs',
  icon: '🏠',
  color: '#0369a1',
  bg: 'from-sky-700 to-blue-500',
  coverImg: null,
  subtitle: 'Sophie moves to a new house.',
  lessons: [
    {
      id: 'u2_l1',
      title: 'Vocabulary: Parts of a House',
      page: '22–28',
      questions: [
        { type: 'mc', bloom: 'remember', difficulty: 'easy', page: 22,
          q: 'In Top Goal 2, what is a "basement"?', page_ref: 'SB p.22',
          options: ['The top floor of a house', 'A room below the ground floor', 'The main entrance of a house', 'The garden area'],
          correct: 1, explanation: 'From SB p.22: basement = an underground room/floor below the main floor.',
          golden_rule: 'basement = underground floor | ground floor = first floor | stairs = connect floors' },
        { type: 'mc', bloom: 'remember', difficulty: 'easy', page: 22,
          q: 'What does an "architect" do?', page_ref: 'SB p.22 + WB p.136',
          options: ['fixes cars', 'designs houses and buildings', 'teaches students', 'reports the news'],
          correct: 1, explanation: 'From WB p.136: "This professional designs houses and buildings = architect."',
          golden_rule: 'architect = a professional who DESIGNS houses and buildings.' },
        { type: 'mc', bloom: 'remember', difficulty: 'easy', page: 22,
          q: 'What is a "key" used for in a house?', page_ref: 'WB p.136',
          options: ['To cook food', 'To unlock the door', 'To measure rooms', 'To fix electricity'],
          correct: 1, explanation: 'From WB p.136: "You need this to unlock the door to your house = key."',
          golden_rule: 'key = used to unlock/lock a door.' },
        { type: 'classify', bloom: 'apply', difficulty: 'medium', page: 22,
          q: 'Classify these words: Parts of a House OR Things IN a House?',
          categories: ['Parts of a House', 'Things in a House'],
          items: [
            { text: 'basement', correct_cat: 0 }, { text: 'fridge', correct_cat: 1 },
            { text: 'first floor', correct_cat: 0 }, { text: 'oven', correct_cat: 1 },
            { text: 'stairs', correct_cat: 0 }, { text: 'Wi-Fi', correct_cat: 1 },
          ],
          explanation: 'From SB p.22: Parts = structural elements (floors, basement, stairs). Things = items inside.',
          golden_rule: 'House PARTS: basement, floors, stairs, entrance, gate. House ITEMS: fridge, oven, screen, Wi-Fi, key.' },
        { type: 'mc', bloom: 'understand', difficulty: 'medium', page: 28,
          q: 'In the "Homes of the Future" text (WB p.146), how will people enter homes in the future?', page_ref: 'WB p.146',
          options: ['With a metal key', 'With a card', 'With smart locks that recognize you', 'With a password'],
          correct: 2, explanation: 'From WB p.146: "Houses won\'t have keys. They will have smart locks that recognize you, so the door opens by itself."',
          golden_rule: 'Future homes: smart locks (no keys!) → door opens automatically when it recognizes you.' },
        { type: 'mc', bloom: 'remember', difficulty: 'easy', page: 28,
          q: 'What will be built INTO the walls of future houses?', page_ref: 'WB p.146',
          options: ['Fridges', 'Ovens', 'Screens/TVs', 'Keys'],
          correct: 2, explanation: 'From WB p.146: "In the future, screens will be built into the walls."',
          golden_rule: 'Future home features: screens in walls + smart fridges/ovens (controlled by phone) + strong Wi-Fi.' },
      ]
    },
    {
      id: 'u2_l2',
      title: 'Grammar: Will / Won\'t & Be Going To',
      page: '24–31',
      questions: [
        { type: 'mc', bloom: 'understand', difficulty: 'easy', page: 24,
          q: 'Which sentence uses WILL to express a spontaneous decision?', page_ref: 'SB p.24 + WB p.138',
          options: ['I am going to study tonight.', 'Don\'t worry! I\'ll call for help.', 'She is going to be a pilot.', 'We planned to visit them.'],
          correct: 1, explanation: 'From WB p.138: "The front door lock doesn\'t open. Don\'t worry! I will call for help." = spontaneous decision at that moment.',
          golden_rule: 'WILL = spontaneous decision / offer / prediction. GOING TO = pre-planned intention.' },
        { type: 'mc', bloom: 'apply', difficulty: 'medium', page: 24,
          q: 'Choose the correct option: "I don\'t like the color of my bedroom anymore! No problem! I ___ repaint it."', page_ref: 'WB p.138',
          options: ['am going to', 'will', 'won\'t', 'am'],
          correct: 1, explanation: 'From WB p.138: Offering help on the spot → use WILL. "I\'ll repaint it."',
          golden_rule: 'WILL for offers/promises/spontaneous decisions: "I\'ll help you!" "I\'ll do it now!"' },
        { type: 'tf', bloom: 'understand', difficulty: 'medium', page: 24,
          q: '"I am going to read a book this evening" shows a PRE-PLANNED intention.', page_ref: 'WB p.143',
          correct: true, explanation: 'From WB p.143: Lucas is going to read a book — he already decided/planned this.',
          golden_rule: 'BE GOING TO = pre-planned intention (decided before the moment of speaking).' },
        { type: 'mc', bloom: 'apply', difficulty: 'medium', page: 26,
          q: 'Complete: "Oops! I completely forgot to call Grandpa. I ___ do it right now."', page_ref: 'WB p.143',
          options: ['am going to', 'will', 'went', 'might'],
          correct: 0, explanation: 'From WB p.143: "I am going to do it right now" — already decided (going to) is also acceptable; but "will do" (spontaneous) is the answer here per WB answer key.',
          golden_rule: 'WILL for spontaneous decisions made at the moment: "I\'ll do it right now!"' },
        { type: 'ordering', bloom: 'apply', difficulty: 'hard', page: 26,
          q: 'Put the words in the correct order: phone / the / I / company / will / contact', page_ref: 'WB p.139',
          items: ["I'll", "contact", "the", "phone", "company"],
          explanation: 'From WB p.139: "I\'ll contact the phone company." = I + will + verb + object.',
          golden_rule: 'WILL sentence structure: Subject + will + base verb + object.' },
        { type: 'mc', bloom: 'understand', difficulty: 'medium', page: 29,
          q: 'In the text "Our New Guest Area" (WB p.144), who designed the basement apartment?', page_ref: 'WB p.144',
          options: ['The parents', 'An architect named Oliver', 'Sophie', 'The guests'],
          correct: 1, explanation: 'From WB p.144: "Mom and Dad asked an architect named Oliver to design the apartment."',
          golden_rule: 'architect = designs buildings. Story: Oliver designed the basement apartment.' },
      ]
    },
    {
      id: 'u2_l3',
      title: 'Story: Sophie\'s House / Reading: Homes of the Future',
      page: '28–33',
      questions: [
        { type: 'mc', bloom: 'remember', difficulty: 'easy', page: 28,
          q: 'In the Sophie story (WB p.140), what did Sophie and her father go to buy?', page_ref: 'WB p.140',
          options: ['Furniture for the house', 'Paint to paint the yard wall', 'A new fridge', 'Garden plants'],
          correct: 1, explanation: 'From WB p.140: "Sophie and her father go to a paint store. They want to buy paint to paint the yard wall."',
          golden_rule: 'Sophie\'s story: paint store → yard wall → raccoon design.' },
        { type: 'mc', bloom: 'understand', difficulty: 'medium', page: 29,
          q: 'What will future homes use, according to the reading "Homes of the Future" (WB p.146)?', page_ref: 'WB p.146',
          options: ['Old wooden materials only', 'Technology and exciting designs', 'Very small rooms', 'Underground construction only'],
          correct: 1, explanation: 'From WB p.146: "Houses will use technology and exciting designs to make homes that won\'t harm the planet."',
          golden_rule: 'Future homes: technology + eco-friendly designs + smart features.' },
      ]
    }
  ]
};

export const UNIT3 = {
  id: 'unit3',
  title: 'Unit 3 — Job Paths',
  icon: '💼',
  color: '#0f5132',
  bg: 'from-emerald-700 to-green-500',
  coverImg: null,
  subtitle: 'Jobs in the community',
  lessons: [
    {
      id: 'u3_l1',
      title: 'Vocabulary: Community Jobs & Workplaces',
      page: '34–40',
      questions: [
        { type: 'mc', bloom: 'remember', difficulty: 'easy', page: 34,
          q: 'In the "Meet Your Community" section (SB p.34), what does a MECHANIC do?', page_ref: 'SB p.34-35',
          options: ['designs clothes', 'repairs cars', 'reports the news', 'manages a business'],
          correct: 1, explanation: 'From SB p.35: "A mechanic fixes cars." / WB p.153: "This person helps you when your car doesn\'t work well."',
          golden_rule: 'mechanic = fixes/repairs cars (works in a garage).' },
        { type: 'mc', bloom: 'remember', difficulty: 'easy', page: 34,
          q: 'Where does an ACTOR usually work?', page_ref: 'SB p.40',
          options: ['office', 'factory', 'stage or gallery', 'airport'],
          correct: 2, explanation: 'From SB p.40: "Actors act on a stage, or sometimes they may perform in an art gallery during an exhibit."',
          golden_rule: 'actor → stage (theater) or gallery. journalist → news studio. pilot → airport.' },
        { type: 'matching', bloom: 'apply', difficulty: 'medium', page: 34,
          q: 'Match each job to its workplace: (SB p.40)',
          pairs: [
            { left: 'pilot', right: 'airport' },
            { left: 'journalist', right: 'news studio' },
            { left: 'artist', right: 'gallery' },
            { left: 'businessman', right: 'office' },
          ],
          explanation: 'From SB p.40: Different jobs have different typical workplaces.',
          golden_rule: 'pilot→airport | journalist→news studio | artist→gallery | businessman→office | actor→stage/theater' },
        { type: 'mc', bloom: 'remember', difficulty: 'easy', page: 34,
          q: 'A "photographer" is someone who:', page_ref: 'SB p.34',
          options: ['designs buildings', 'takes professional photos', 'flies airplanes', 'writes articles'],
          correct: 1, explanation: 'From SB p.34: "Mrs. Taylor: Learn how to take professional photos with this photographer."',
          golden_rule: 'photographer = takes (professional) photos. Photographer + camera = photos.' },
        { type: 'classify', bloom: 'apply', difficulty: 'medium', page: 40,
          q: 'Classify these jobs: Work INDOORS or Work OUTDOORS (mainly)?',
          categories: ['Mainly Indoors', 'Mainly Outdoors'],
          items: [
            { text: 'journalist', correct_cat: 1 }, { text: 'actor (on stage)', correct_cat: 0 },
            { text: 'pilot', correct_cat: 0 }, { text: 'driver', correct_cat: 1 },
            { text: 'businessman', correct_cat: 0 }, { text: 'fashion designer', correct_cat: 0 },
          ],
          explanation: 'From SB p.34-40: Jobs are classified by their typical workplace environment.',
          golden_rule: 'Jobs and their environments: use common sense + textbook context.' },
        { type: 'mc', bloom: 'remember', difficulty: 'easy', page: 34,
          q: 'What does a FLIGHT ATTENDANT do?', page_ref: 'SB p.34 + WB p.158',
          options: ['flies the plane', 'helps passengers on the plane relax', 'checks tickets at the gate', 'loads luggage'],
          correct: 1, explanation: 'From SB p.35: "Fly around the city with a pilot or watch the flight attendant help the passengers."',
          golden_rule: 'pilot → FLIES the plane | flight attendant → HELPS passengers during the flight.' },
        { type: 'mc', bloom: 'understand', difficulty: 'medium', page: 43,
          q: 'In Word Work (SB p.43), what is the "-ist" suffix used for?', page_ref: 'SB p.43',
          options: ['To make adjectives', 'To make people nouns (professions)', 'To make past tenses', 'To make negative words'],
          correct: 1, explanation: 'From SB p.43: cycle→cyclist, art→artist, pharmacy→pharmacist. -ist = person who does something.',
          golden_rule: 'Suffix -ist = a person: art→artist | cycle→cyclist | tour→tourist | journal→journalist' },
        { type: 'mc', bloom: 'remember', difficulty: 'medium', page: 42,
          q: 'According to the reading "What job are you going to do in 2040?" (SB p.42), what will food engineers do in the future?', page_ref: 'SB p.42',
          options: ['They will grow vegetables', 'They will create and design the food we eat', 'They will deliver food', 'They will manage restaurants'],
          correct: 1, explanation: 'From SB p.42: "In 2040, food engineers are going to be popular. They are going to create and design the food we might eat."',
          golden_rule: 'Future jobs in 2040: food engineer + robot therapist + robot manager.' },
      ]
    },
    {
      id: 'u3_l2',
      title: 'Grammar: Going To / May / Might (Future)',
      page: '36–37',
      questions: [
        { type: 'mc', bloom: 'understand', difficulty: 'easy', page: 36,
          q: 'In Top Goal 2 (SB p.36), which expression shows you are 100% CERTAIN about a future plan?', page_ref: 'SB p.36',
          options: ['might', 'may', '(be) going to', 'maybe'],
          correct: 2, explanation: 'From SB p.36: "(be) going to = 100% certain (definite future plans)." might/may show less certainty.',
          golden_rule: '100% sure → (be) going to | 50% likely → may | 30% unlikely → might | 0% → isn\'t going to' },
        { type: 'mc', bloom: 'apply', difficulty: 'medium', page: 36,
          q: 'Maya says: "I\'m not going to work in an office." This means:', page_ref: 'SB p.36',
          options: ['She is unsure about working in an office.', 'She definitely will not work in an office.', 'She might work in an office.', 'She is happy to work in an office.'],
          correct: 1, explanation: 'From SB p.36: "I\'m not going to work in an office. I\'m sure of that!" — 0% possibility.',
          golden_rule: '(be) NOT going to = 0% — impossible / definitely will not happen.' },
        { type: 'mc', bloom: 'apply', difficulty: 'medium', page: 37,
          q: 'Julian says: "My dad\'s a pilot, but I might not do that because I\'m scared of planes!" This shows:', page_ref: 'SB p.36',
          options: ['He will definitely become a pilot.', 'He will never be a pilot.', 'He might or might not become a pilot — it\'s unlikely.', 'He wants to be a pilot.'],
          correct: 2, explanation: 'From SB p.36: "might not" = unlikely (30%) — not completely impossible, but probably won\'t happen.',
          golden_rule: 'might not = it\'s unlikely this will happen (about 30% chance).' },
        { type: 'ordering', bloom: 'apply', difficulty: 'hard', page: 37,
          q: 'Order the words to make a correct sentence: not / the / She / future / might / act / in',
          items: ['She', 'might', 'not', 'act', 'in', 'the', 'future'],
          explanation: 'From WB p.150: "She might not act in the future." = Subject + might + not + base verb.',
          golden_rule: 'might not: Subject + might + NOT + base verb. NOT "mightn\'t" (not common).' },
        { type: 'mc', bloom: 'remember', difficulty: 'easy', page: 37,
          q: 'We use _____ when we are completely sure of a future plan.', page_ref: 'SB p.36',
          options: ['might', 'may', '(be) going to', 'will probably'],
          correct: 2, explanation: 'From SB p.36: "We use (be) going to when we are completely sure of a future plan."',
          golden_rule: '(be) going to = completely sure | may = likely to happen | might = unlikely to happen' },
        { type: 'mc', bloom: 'apply', difficulty: 'medium', page: 36,
          q: 'Complete: "I don\'t have a clue! I ___ be a pilot." (not sure at all)', page_ref: 'SB p.37',
          options: ['am going to', 'will definitely', 'might', 'am'],
          correct: 2, explanation: 'From SB p.37: "No. I don\'t have a clue! I might be a pilot." = not sure → might.',
          golden_rule: '"I don\'t have a clue" / "I\'m not sure" → use MIGHT (uncertain future).' },
      ]
    },
    {
      id: 'u3_l3',
      title: 'Grammar: Question Tags',
      page: '41',
      questions: [
        { type: 'mc', bloom: 'remember', difficulty: 'easy', page: 41,
          q: 'If a statement is AFFIRMATIVE, the question tag is:', page_ref: 'SB p.41',
          options: ['affirmative', 'negative', 'a question word', 'imperative'],
          correct: 1, explanation: 'From SB p.41: "If the statement is affirmative, the question tag is NEGATIVE."',
          golden_rule: 'Rule: Affirmative statement + NEGATIVE tag | Negative statement + AFFIRMATIVE tag' },
        { type: 'mc', bloom: 'apply', difficulty: 'medium', page: 41,
          q: '"This is the theater, ___?"', page_ref: 'SB p.41',
          options: ['isn\'t this', 'isn\'t it', 'is it', 'is this'],
          correct: 1, explanation: 'From SB p.41: "This is the theater, ISN\'T IT?" — affirmative statement → negative tag using "it".',
          golden_rule: 'Question tag for "this is..." → "...isn\'t it?" (use "it" for things/places).' },
        { type: 'mc', bloom: 'apply', difficulty: 'medium', page: 41,
          q: '"You saw a famous actor here, ___?"', page_ref: 'SB p.41',
          options: ['did you', 'didn\'t you', 'do you', 'don\'t you'],
          correct: 1, explanation: 'From SB p.41: "You saw a famous actor here, DIDN\'T YOU?" — affirmative past → past negative tag.',
          golden_rule: 'Past tense statement → past negative tag: "...did/didn\'t...?" He went→didn\'t he? She saw→didn\'t she?' },
        { type: 'mc', bloom: 'apply', difficulty: 'hard', page: 41,
          q: '"She enjoys taking photos, ___?"', page_ref: 'WB p.141',
          options: ['does she', 'isn\'t she', 'doesn\'t she', 'did she'],
          correct: 2, explanation: 'From WB p.141: "She enjoys taking photos, DOESN\'T SHE?" — affirmative simple present (she) → doesn\'t she.',
          golden_rule: 'Simple present (she/he/it enjoys...) → tag: ...doesn\'t she/he/it? | (you/we/they enjoy) → ...don\'t you/we/they?' },
        { type: 'tf', bloom: 'understand', difficulty: 'medium', page: 41,
          q: '"You aren\'t a pilot, ARE you?" is grammatically correct.', page_ref: 'WB p.141',
          correct: true, explanation: 'From WB p.141: "You aren\'t a pilot, are you?" — negative statement → affirmative tag (ARE).',
          golden_rule: 'Negative statement + AFFIRMATIVE tag: "You aren\'t a pilot, ARE you?" / "He can\'t fly, CAN he?"' },
        { type: 'mc', bloom: 'apply', difficulty: 'medium', page: 41,
          q: '"He is going to work here, ___?"', page_ref: 'WB p.141',
          options: ['isn\'t he', 'is he', 'doesn\'t he', 'hasn\'t he'],
          correct: 0, explanation: 'From WB p.141: "He is going to work here, ISN\'T HE?" — affirmative → negative tag (isn\'t he).',
          golden_rule: '"is going to..." → "...isn\'t he/she?" (use the auxiliary verb from the main sentence in the tag).' },
        { type: 'mc', bloom: 'remember', difficulty: 'easy', page: 44,
          q: 'According to the Social Studies integrated text (SB p.44), approximately how many new AI jobs will be created in Saudi Arabia by 2030?', page_ref: 'SB p.44',
          options: ['5,000', '11 million', '15,000', '47,000'],
          correct: 2, explanation: 'From SB p.44: "Around 15,000 new jobs in artificial intelligence will be created by 2030."',
          golden_rule: 'Saudi Arabia 2030 facts: 11 million private sector workers | 47% under 34 | 15,000 new AI jobs.' },
      ]
    },
    {
      id: 'u3_l4',
      title: 'Story: The College Application',
      page: '38',
      questions: [
        { type: 'mc', bloom: 'remember', difficulty: 'easy', page: 38,
          q: 'In "The College Application" story (SB p.38), why is Emilia sad?', page_ref: 'SB p.38',
          options: ['She failed her exams.', 'She doesn\'t know what to study in college.', 'She lost her application form.', 'She doesn\'t want to go to college.'],
          correct: 1, explanation: 'From SB p.38: "I don\'t know what I\'m going to study in college," says Emilia.',
          golden_rule: 'Emilia\'s problem: uncertain about her college major/subject.' },
        { type: 'tf', bloom: 'understand', difficulty: 'medium', page: 38,
          q: 'In the story, Harper says that being happy is MORE important than being rich.', page_ref: 'SB p.38',
          correct: true, explanation: 'From SB p.38: "What matters is that you\'re going to be happy, and no money is better than that."',
          golden_rule: 'Harper\'s message: happiness > money. "Being happy at work matters more than being rich."' },
        { type: 'mc', bloom: 'apply', difficulty: 'medium', page: 38,
          q: 'What does Harper suggest Emilia could become, based on her TALENT?', page_ref: 'SB p.38',
          options: ['an engineer or scientist', 'a great artist or fashion designer', 'a journalist or pilot', 'a doctor or nurse'],
          correct: 1, explanation: 'From SB p.38: "You are very good at drawing! That\'s your talent. You may become a great artist, or you might be a fashion designer."',
          golden_rule: 'Emilia\'s talent = drawing → possible careers: artist OR fashion designer.' },
      ]
    }
  ]
};

export const UNIT4 = {
  id: 'unit4',
  title: 'Unit 4 — Glorious Food',
  icon: '🍪',
  color: '#b45309',
  bg: 'from-amber-700 to-orange-500',
  coverImg: null,
  subtitle: 'Make your favorite snack.',
  lessons: [
    {
      id: 'u4_l1',
      title: 'Vocabulary: Food, Cooking & Ingredients',
      page: '46–52',
      questions: [
        { type: 'mc', bloom: 'remember', difficulty: 'easy', page: 46,
          q: 'In Top Goal 2 Unit 4, what is a "countertop"?', page_ref: 'SB p.46',
          options: ['A type of cookie', 'The flat surface in the kitchen for preparing food', 'An ingredient in baking', 'A cooking tool'],
          correct: 1, explanation: 'From SB p.46: "countertop" = the flat surface in the kitchen where you prepare food.',
          golden_rule: 'countertop = flat kitchen surface for food preparation.' },
        { type: 'mc', bloom: 'remember', difficulty: 'easy', page: 46,
          q: 'Which ingredient is used as a sweet alternative to sugar in baking?', page_ref: 'SB p.46',
          options: ['flour', 'butter', 'honey', 'yogurt'],
          correct: 2, explanation: 'From SB p.46: Recipe ingredients include "sugar OR honey" — honey is the sweet alternative.',
          golden_rule: 'honey = natural sweetener (alternative to sugar in recipes).' },
        { type: 'mc', bloom: 'remember', difficulty: 'easy', page: 52,
          q: 'What does "dough" mean in cooking?', page_ref: 'SB p.52',
          options: ['a finished baked product', 'a thick mixture of flour and liquid used for baking', 'a type of topping', 'a liquid sauce'],
          correct: 1, explanation: 'From SB p.52: dough = thick mixture of flour and liquid — used to make bread, cookies, pizza.',
          golden_rule: 'dough = flour + liquid (water/milk/eggs) mixed together → baked to make bread/pizza/cookies.' },
        { type: 'ordering', bloom: 'remember', difficulty: 'medium', page: 47,
          q: 'Put the cookie-making steps in the correct order (from SB p.47 vocabulary):',
          items: ['Melt the butter in a pan.', 'Mix the ingredients together.', 'Roll the dough.', 'Bake the cookies.', 'Taste the cookies.'],
          explanation: 'From SB p.47: Cooking steps follow a logical order: melt → mix → roll → bake → taste.',
          golden_rule: 'Cookie recipe order: prepare → mix → shape → bake → eat!' },
        { type: 'mc', bloom: 'understand', difficulty: 'medium', page: 47,
          q: 'In the Mutabbaq recipe (WB p.47), what is Mutabbaq?', page_ref: 'WB p.47',
          options: ['A type of cake from Egypt', 'A Saudi dish — dough with filling (meat, chicken, or cheese)', 'A sweet dessert with honey and yogurt', 'A type of pancake'],
          correct: 1, explanation: 'From WB p.47: "My favorite dish is mutabbaq. It is common in Saudi Arabia. It\'s a dough with filling in it... The common ones are meat, chicken, or cheese."',
          golden_rule: 'Mutabbaq = popular Saudi dish = dough + filling (meat/chicken/cheese).' },
        { type: 'classify', bloom: 'apply', difficulty: 'medium', page: 52,
          q: 'Classify these cooking vocabulary words: VERBS (actions) or NOUNS (things)?',
          categories: ['Verbs (actions)', 'Nouns (things)'],
          items: [
            { text: 'stir', correct_cat: 0 }, { text: 'dough', correct_cat: 1 },
            { text: 'pour', correct_cat: 0 }, { text: 'topping', correct_cat: 1 },
            { text: 'measure', correct_cat: 0 }, { text: 'ingredients', correct_cat: 1 },
          ],
          explanation: 'From SB p.52: Cooking verbs are actions you do. Cooking nouns are things you use.',
          golden_rule: 'Cooking VERBS: stir, pour, measure, cut, roll, mix, bake, taste. Cooking NOUNS: dough, topping, ingredients, recipe, countertop.' },
        { type: 'mc', bloom: 'understand', difficulty: 'easy', page: 46,
          q: 'What is a "recipe"?', page_ref: 'WB p.160',
          options: ['A type of dessert', 'Instructions that tell you how to prepare food', 'A cooking tool', 'A food topping'],
          correct: 1, explanation: 'From WB p.160: "It gives instructions to prepare food = recipe."',
          golden_rule: 'recipe = step-by-step instructions for preparing a dish.' },
      ]
    },
    {
      id: 'u4_l2',
      title: 'Grammar: Should / Had Better',
      page: '48–49',
      questions: [
        { type: 'mc', bloom: 'understand', difficulty: 'easy', page: 48,
          q: 'In Top Goal 2 (SB p.48), "SHOULD" is used to express:', page_ref: 'SB p.48',
          options: ['a warning about bad consequences', 'advice (it\'s a good idea)', 'a definite plan', 'something impossible'],
          correct: 1, explanation: 'From SB p.48: "We SHOULD turn the oven on" = advice. Similar to "It\'s a good idea to..."',
          golden_rule: 'SHOULD = advice (it\'s a good idea) | HAD BETTER = strong warning (important/urgent).' },
        { type: 'mc', bloom: 'understand', difficulty: 'medium', page: 48,
          q: '"You had better NOT make a mess!" is similar to:', page_ref: 'SB p.48',
          options: ['It\'s a good idea to be tidy.', 'You mustn\'t make a mess (strong warning).', 'You might make a mess.', 'You could make a mess.'],
          correct: 1, explanation: 'From SB p.48: "had better not" = a strong warning. Similar to "It\'s important NOT to..."',
          golden_rule: 'HAD BETTER NOT = strong warning (something bad will happen if you don\'t listen).' },
        { type: 'tf', bloom: 'apply', difficulty: 'medium', page: 48,
          q: '"You should buy all your ingredients before you begin" gives advice for the PRESENT or FUTURE.', page_ref: 'SB p.49',
          correct: true, explanation: 'From SB p.48: "should" gives advice for present or future situations (not past).',
          golden_rule: 'SHOULD + base verb gives advice for now or future. NOT for past situations.' },
        { type: 'mc', bloom: 'apply', difficulty: 'medium', page: 49,
          q: 'Rewrite using "had better": "You shouldn\'t make a mess in the kitchen."', page_ref: 'WB p.162',
          options: ['You have better not make a mess.', 'You had better not make a mess.', 'You had not better make a mess.', 'You better not to make a mess.'],
          correct: 1, explanation: 'From WB p.162: "You had better NOT make a mess in the kitchen."',
          golden_rule: 'HAD BETTER NOT + base verb. Never: "had not better" or "better not to".' },
        { type: 'mc', bloom: 'apply', difficulty: 'hard', page: 48,
          q: 'From Cooking Safety Tips (WB p.162), which sentence uses SHOULD correctly?', page_ref: 'WB p.162',
          options: ['You should not ask an adult for permission.', 'You should wash your hands before cooking.', 'You should cook alone.', 'You should use knives without help.'],
          correct: 1, explanation: 'From WB p.162: "You should wash your hands before cooking" = safety advice = correct use of should.',
          golden_rule: 'Kitchen safety: SHOULD (good advice) + HAD BETTER (strong warning for safety).' },
      ]
    },
    {
      id: 'u4_l3',
      title: 'Grammar: Zero Conditional',
      page: '53',
      questions: [
        { type: 'mc', bloom: 'understand', difficulty: 'easy', page: 53,
          q: 'The Zero Conditional in Top Goal 2 is used for:', page_ref: 'SB p.53',
          options: ['future predictions', 'facts that are always true / general truths', 'past habits', 'impossible situations'],
          correct: 1, explanation: 'From SB p.53: "If you want a sweet snack, you add sugar." = always true fact.',
          golden_rule: 'Zero Conditional: If + simple present → simple present. Used for FACTS/TRUTHS that always happen.' },
        { type: 'mc', bloom: 'apply', difficulty: 'medium', page: 53,
          q: '"If we don\'t have sugar, we ___ honey." (Zero Conditional)', page_ref: 'SB p.53',
          options: ['used', 'will use', 'use', 'are using'],
          correct: 2, explanation: 'From SB p.53: Zero conditional: "If we don\'t have sugar, we USE honey." — both verbs in simple present.',
          golden_rule: 'Zero Conditional formula: If + simple present, simple present. BOTH verbs stay in present tense.' },
        { type: 'tf', bloom: 'understand', difficulty: 'easy', page: 53,
          q: '"If you want a sweet snack, add sugar" — the if-clause can come SECOND in the sentence.', page_ref: 'SB p.53',
          correct: true, explanation: 'From SB p.53: "Add sugar if you want a sweet snack." = if-clause can come second (no comma needed).',
          golden_rule: 'If-clause FIRST: comma needed. "If you like X, you do Y." SECOND: no comma. "You do Y if you like X."' },
        { type: 'mc', bloom: 'apply', difficulty: 'hard', page: 53,
          q: 'Choose the correct zero conditional: "If the oven is too hot, ___"', page_ref: 'WB p.167',
          options: ['the cookies will burn.', 'the cookies burn.', 'the cookies burned.', 'the cookies are burning.'],
          correct: 1, explanation: 'From WB p.167: Zero conditional: "If the oven is too hot, the cookies BURN." = both present tense.',
          golden_rule: 'Zero conditional: cause (if-clause, present) → result (present tense, not future).' },
        { type: 'mc', bloom: 'apply', difficulty: 'medium', page: 54,
          q: 'From "Food and Sports" reading (SB p.54): What should athletes do if they don\'t like the taste of water?', page_ref: 'SB p.54',
          options: ['drink juice instead', 'not drink anything', 'mix in some fruits or herbs', 'drink sports drinks only'],
          correct: 2, explanation: 'From SB p.54: "If you don\'t like the taste of water, mix in some fruits or herbs."',
          golden_rule: 'Athletes\' advice: drink water → if no taste → add fruits/herbs. Don\'t skip meals!' },
        { type: 'mc', bloom: 'remember', difficulty: 'easy', page: 56,
          q: 'According to "Healthy Eating: The Best Kind of Diet" (SB p.56), what kind of diet is the BEST?', page_ref: 'SB p.56',
          options: ['only vegetables', 'only proteins', 'a balanced diet (a bit of everything)', 'only starches'],
          correct: 2, explanation: 'From SB p.56: "The best kind of diet is a balanced one. That means you shouldn\'t just eat salads. You\'d better eat a bit of everything."',
          golden_rule: 'Best diet = BALANCED = vegetables + proteins + starches + dairy (small amounts of fatty foods).' },
      ]
    },
    {
      id: 'u4_l4',
      title: 'Story: Layla\'s Cookie Experiment',
      page: '50',
      questions: [
        { type: 'mc', bloom: 'remember', difficulty: 'easy', page: 50,
          q: 'In "An Experiment in Cooking Class" (SB p.50), what was the first ingredient Layla tried in her cookies?', page_ref: 'SB p.50',
          options: ['carrots', 'onion', 'garlic', 'broccoli'],
          correct: 2, explanation: 'From SB p.50: "She puts in garlic, but a horrible smell fills the classroom."',
          golden_rule: 'Layla\'s cookie experiment order: garlic (fail) → onion (fail) → carrots (success!)' },
        { type: 'mc', bloom: 'understand', difficulty: 'medium', page: 50,
          q: 'What was the teacher\'s advice to Layla during the experiment?', page_ref: 'SB p.50',
          options: ['"You should try chocolate."', '"You should try carrots."', '"You had better stop cooking."', '"You should use more flour."'],
          correct: 1, explanation: 'From SB p.50: "What\'s that smell?" asks the teacher. "You should try carrots."',
          golden_rule: 'Teacher\'s advice: try carrots (vegetables CAN be in sweet snacks!).' },
        { type: 'tf', bloom: 'understand', difficulty: 'easy', page: 50,
          q: 'Thelma thought Layla\'s carrot cookies were delicious.', page_ref: 'SB p.50',
          correct: true, explanation: 'From SB p.50: "You should sell these!" says Thelma with cookie around her mouth.',
          golden_rule: 'Thelma\'s final reaction: "You should sell these!" = she loved the carrot cookies.' },
      ]
    }
  ]
};

// ─────────────────────────────────────────────────────────
// الوحدات الإضافية (5-8) — بيانات أسئلة مختصرة
// ─────────────────────────────────────────────────────────

export const UNIT5 = {
  id: 'unit5',
  title: 'Unit 5 — Storylines',
  icon: '🎬',
  color: '#1e3a6e',
  bg: 'from-blue-900 to-indigo-700',
  coverImg: null,
  subtitle: 'The magic of storytelling',
  lessons: [
    {
      id: 'u5_l1',
      title: 'Vocabulary: Types of Stories & Movies',
      page: '58–64',
      questions: [
        { type: 'mc', bloom: 'remember', difficulty: 'easy', page: 58,
          q: 'Which type of story involves magic, imaginary worlds, and often has a moral?', page_ref: 'SB p.58',
          options: ['documentary', 'fairy tale', 'western', 'comedy'],
          correct: 1, explanation: 'From SB p.58 vocabulary: fairy tale = story with magic/imaginary world + moral.',
          golden_rule: 'Fairy tale: magic + imaginary world + moral (e.g., Cinderella, Snow White).' },
        { type: 'mc', bloom: 'remember', difficulty: 'easy', page: 58,
          q: 'What is a "documentary"?', page_ref: 'SB p.58',
          options: ['A made-up adventure story', 'A film or TV program about real events/people', 'A comedy movie', 'An animated story'],
          correct: 1, explanation: 'From SB p.58: documentary = a film about real events and real people.',
          golden_rule: 'documentary = REAL events/people. fiction = made-up characters/events.' },
        { type: 'classify', bloom: 'apply', difficulty: 'medium', page: 58,
          q: 'Classify these genres: Fiction or Non-Fiction?',
          categories: ['Fiction (made up)', 'Non-Fiction (real)'],
          items: [
            { text: 'fairy tale', correct_cat: 0 }, { text: 'documentary', correct_cat: 1 },
            { text: 'sci-fi', correct_cat: 0 }, { text: 'animation about real history', correct_cat: 1 },
            { text: 'mystery', correct_cat: 0 }, { text: 'biography film', correct_cat: 1 },
          ],
          explanation: 'From SB p.58: movie/story genres can be fiction (made-up) or non-fiction (real).',
          golden_rule: 'Fiction: fairy tale, sci-fi, mystery, thriller, western. Non-fiction: documentary, biography.' },
        { type: 'mc', bloom: 'remember', difficulty: 'easy', page: 64,
          q: 'What is a "storyboard"?', page_ref: 'SB p.64',
          options: ['A type of board game', 'A sequence of pictures showing the plan of a movie/story', 'A board where you write stories', 'A character in a story'],
          correct: 1, explanation: 'From SB p.64: storyboard = a sequence of pictures/sketches showing the story scenes in order.',
          golden_rule: 'storyboard = visual plan of a movie (pictures in sequence showing each scene).' },
        { type: 'mc', bloom: 'apply', difficulty: 'hard', page: 64,
          q: 'In the Unit 5 reading (WB p.132), which hobby involves collecting board games?', page_ref: 'WB p.134',
          options: ['Movie reviewing', 'Playing the piano', 'Scrapbooking', 'Board game collecting'],
          correct: 3, explanation: 'From WB p.134: "Some people collect different board games to play with their friends on game nights."',
          golden_rule: 'Unusual hobbies: board game collecting + movie reviewing + making art from old things.' },
      ]
    },
    {
      id: 'u5_l2',
      title: 'Grammar: Past Continuous & Past Simple',
      page: '60–65',
      questions: [
        { type: 'mc', bloom: 'understand', difficulty: 'medium', page: 60,
          q: 'Which tense describes an action that was IN PROGRESS at a specific time in the past?', page_ref: 'SB p.60',
          options: ['simple past', 'past continuous', 'present continuous', 'simple present'],
          correct: 1, explanation: 'From SB p.60: Past continuous = was/were + verb-ing = in progress at a past time.',
          golden_rule: 'Past continuous: was/were + verb-ing = action in progress at a specific past time.' },
        { type: 'mc', bloom: 'apply', difficulty: 'medium', page: 60,
          q: 'Choose the correct form: "I ___ a scary movie when my friend called."', page_ref: 'SB p.60',
          options: ['watched', 'was watching', 'am watching', 'watch'],
          correct: 1, explanation: 'From SB p.60: longer action (watching) = past continuous. Interrupting action (called) = simple past.',
          golden_rule: 'When + short action interrupted: "I WAS WATCHING a movie when he CALLED." (was+ing = interrupted action)' },
        { type: 'tf', bloom: 'understand', difficulty: 'easy', page: 60,
          q: '"While I was cooking, the phone rang" — two past actions at the same time: one continuous, one short.', page_ref: 'SB p.60',
          correct: true, explanation: 'From SB p.60: "while" + past continuous + simple past = one long action + one short interruption.',
          golden_rule: 'While + past continuous, simple past = long ongoing action + short interruption.' },
        { type: 'mc', bloom: 'apply', difficulty: 'hard', page: 64,
          q: 'Choose the correct sentence about the animation story:', page_ref: 'SB p.64',
          options: [
            'The character whispered while he was appearing on screen.',
            'The character was whispering a wish when he appeared on screen.',
            'The character whispered when he appeared on screen.',
            'The character was whisper when he appears.',
          ],
          correct: 1, explanation: 'From SB p.64: ongoing action (whispering) = was whispering + single past event (appeared) = simple past.',
          golden_rule: 'Structure: Subject + was/were + verb-ing (ongoing) + when + Subject + verb-ed (event).' },
      ]
    }
  ]
};

export const UNIT6 = {
  id: 'unit6',
  title: 'Unit 6 — Outdoor Activities',
  icon: '⛺',
  color: '#065f46',
  bg: 'from-emerald-900 to-green-600',
  coverImg: null,
  subtitle: 'Adventures in the great outdoors',
  lessons: [
    {
      id: 'u6_l1',
      title: 'Vocabulary: Outdoor Activities & Equipment',
      page: '70–76',
      questions: [
        { type: 'mc', bloom: 'remember', difficulty: 'easy', page: 70,
          q: 'Which activity involves sleeping outdoors in a tent?', page_ref: 'SB p.70',
          options: ['surfing', 'camping', 'mountain biking', 'canoeing'],
          correct: 1, explanation: 'From SB p.70: camping = staying outdoors in a tent (also: backpacking, campfire).',
          golden_rule: 'camping = tent + sleeping outdoors + campfire + backpack.' },
        { type: 'mc', bloom: 'remember', difficulty: 'easy', page: 70,
          q: 'What equipment do you need for FISHING?', page_ref: 'SB p.70',
          options: ['a life jacket and raft', 'a fishing rod', 'hiking boots', 'a helmet and bicycle'],
          correct: 1, explanation: 'From SB p.70: fishing vocabulary includes "fishing rod" as essential equipment.',
          golden_rule: 'Fishing equipment: fishing rod. Camping: tent, sleeping bag. Hiking: hiking boots.' },
        { type: 'classify', bloom: 'apply', difficulty: 'medium', page: 70,
          q: 'Classify these outdoor activities: WATER activities or LAND activities?',
          categories: ['Water Activities', 'Land Activities'],
          items: [
            { text: 'canoeing', correct_cat: 0 }, { text: 'hiking', correct_cat: 1 },
            { text: 'surfing', correct_cat: 0 }, { text: 'mountain biking', correct_cat: 1 },
            { text: 'rafting', correct_cat: 0 }, { text: 'horseback riding', correct_cat: 1 },
          ],
          explanation: 'From SB p.70-76: Activities are classified by environment (water vs. land).',
          golden_rule: 'Water: canoeing, surfing, rafting, fishing. Land: hiking, mountain biking, horseback riding, camping.' },
        { type: 'mc', bloom: 'remember', difficulty: 'easy', page: 76,
          q: 'What safety equipment should you wear when going horseback riding or mountain biking?', page_ref: 'SB p.76',
          options: ['life jacket', 'helmet', 'hiking boots', 'sleeping bag'],
          correct: 1, explanation: 'From SB p.76: helmet = safety equipment for horseback riding and mountain biking.',
          golden_rule: 'Safety: helmet for biking/riding | life jacket for water | hiking boots for trails.' },
      ]
    },
    {
      id: 'u6_l2',
      title: 'Grammar: Present Perfect',
      page: '72–77',
      questions: [
        { type: 'mc', bloom: 'understand', difficulty: 'easy', page: 72,
          q: 'The Present Perfect tense is formed with:', page_ref: 'SB p.72',
          options: ['was/were + verb-ing', 'have/has + past participle', 'did + base verb', 'will + base verb'],
          correct: 1, explanation: 'From SB p.72: Present Perfect = have/has + past participle (e.g., I have gone, She has eaten).',
          golden_rule: 'Present Perfect: have/has + past participle (gone, eaten, done, seen, been).' },
        { type: 'mc', bloom: 'apply', difficulty: 'medium', page: 72,
          q: 'Which sentence is in the PRESENT PERFECT?', page_ref: 'SB p.72',
          options: ['She goes camping every summer.', 'She went camping last summer.', 'She has gone camping many times.', 'She was going camping.'],
          correct: 2, explanation: 'From SB p.72: "has gone" = present perfect. "many times" = experience without specific time.',
          golden_rule: 'Present Perfect for EXPERIENCE (no specific time): "I have tried surfing many times." "She has never been to Canada."' },
        { type: 'tf', bloom: 'understand', difficulty: 'medium', page: 72,
          q: 'The Present Perfect can be used with "ever" and "never" to talk about life experiences.', page_ref: 'SB p.72',
          correct: true, explanation: 'From SB p.72: "Have you EVER tried rafting?" "I have NEVER been camping." — experience questions.',
          golden_rule: 'Ever (in questions) / Never (in negatives) → always use PRESENT PERFECT for life experiences.' },
        { type: 'mc', bloom: 'apply', difficulty: 'hard', page: 73,
          q: 'Choose the correct sentence about Olivia\'s camping trip:', page_ref: 'SB p.76 + WB p.184',
          options: [
            'She has go rafting yesterday.',
            'She went rafting yesterday.',
            'She has went rafting yesterday.',
            'She is going rafting yesterday.',
          ],
          correct: 1, explanation: 'From WB context: "yesterday" = specific past time → use SIMPLE PAST (went), not Present Perfect.',
          golden_rule: 'With specific past time words (yesterday, last week, in 2020) → use SIMPLE PAST (not Present Perfect).' },
      ]
    }
  ]
};

export const UNIT7 = {
  id: 'unit7',
  title: 'Unit 7 — Trips',
  icon: '✈️',
  color: '#312e81',
  bg: 'from-indigo-900 to-purple-700',
  coverImg: null,
  subtitle: 'Adventures in travel',
  lessons: [
    {
      id: 'u7_l1',
      title: 'Vocabulary: Travel & Transportation',
      page: '82–88',
      questions: [
        { type: 'mc', bloom: 'remember', difficulty: 'easy', page: 82,
          q: 'What is a "passport"?', page_ref: 'SB p.82',
          options: ['a ticket to board a plane', 'an official document needed for international travel', 'a type of suitcase', 'a travel guide'],
          correct: 1, explanation: 'From SB p.82: passport = official government document required for international travel.',
          golden_rule: 'passport = official document for international travel (shows identity and nationality).' },
        { type: 'mc', bloom: 'remember', difficulty: 'easy', page: 88,
          q: 'What does "check in" mean at an airport?', page_ref: 'SB p.88',
          options: ['to arrive at your destination', 'to register for your flight and drop off luggage', 'to pass through security', 'to board the plane'],
          correct: 1, explanation: 'From SB p.88: check in = register for your flight, show your passport, drop off luggage at the airport counter.',
          golden_rule: 'Airport steps: check in → security → gate → board → land → check out (of hotel).' },
        { type: 'ordering', bloom: 'apply', difficulty: 'hard', page: 88,
          q: 'Put these travel steps in the correct order at an airport:',
          items: ['Arrive at the airport', 'Check in and drop luggage', 'Pass through security', 'Wait at the gate', 'Board the plane', 'Land at destination'],
          explanation: 'From SB p.88: Airport steps follow a logical security/boarding sequence.',
          golden_rule: 'Airport order: arrive → check in → security → gate → board → land → immigration → collect bags.' },
        { type: 'classify', bloom: 'apply', difficulty: 'medium', page: 82,
          q: 'Classify these: found at an AIRPORT or at a TRAIN STATION?',
          categories: ['Airport', 'Train Station'],
          items: [
            { text: 'terminal', correct_cat: 0 }, { text: 'platform', correct_cat: 1 },
            { text: 'check-in', correct_cat: 0 }, { text: 'railroad', correct_cat: 1 },
            { text: 'passport control', correct_cat: 0 }, { text: 'subway', correct_cat: 1 },
          ],
          explanation: 'From SB p.82: vocabulary includes travel-specific locations.',
          golden_rule: 'Airport: terminal, check-in, departure, security. Train/subway: platform, station, railroad.' },
      ]
    },
    {
      id: 'u7_l2',
      title: 'Grammar: Giving Instructions (Imperatives & Directions)',
      page: '84–90',
      questions: [
        { type: 'mc', bloom: 'understand', difficulty: 'easy', page: 84,
          q: 'When giving DIRECTIONS or INSTRUCTIONS, which form of the verb do we use?', page_ref: 'SB p.84',
          options: ['past tense', 'infinitive (base form) = imperative', 'present continuous', 'present perfect'],
          correct: 1, explanation: 'From SB p.84: directions use imperative = base form of the verb. "Turn left. Go straight. Take the subway."',
          golden_rule: 'Imperative for instructions/directions: base verb only. "Turn left." "Take exit 2." "Don\'t park here."' },
        { type: 'mc', bloom: 'apply', difficulty: 'medium', page: 84,
          q: 'Choose the correct imperative instruction: "You need to go to the airport. ___"', page_ref: 'SB p.84',
          options: ['You should taking the subway.', 'Take the subway to Terminal 3.', 'You are taking the subway.', 'To take the subway.'],
          correct: 1, explanation: 'From SB p.84: Directions use imperative (base verb): "Take the subway" not "You should taking."',
          golden_rule: 'Directions/instructions: "Turn right." "Take bus 5." "Don\'t go that way." — base verb only!' },
      ]
    }
  ]
};

export const UNIT8 = {
  id: 'unit8',
  title: 'Unit 8 — Outfits',
  icon: '👗',
  color: '#9d174d',
  bg: 'from-pink-900 to-rose-600',
  coverImg: null,
  subtitle: 'Fashion and accessories',
  lessons: [
    {
      id: 'u8_l1',
      title: 'Vocabulary: Clothes, Accessories & Materials',
      page: '94–100',
      questions: [
        { type: 'mc', bloom: 'remember', difficulty: 'easy', page: 94,
          q: 'Which word describes the pattern on fabric with uneven color marks?', page_ref: 'SB p.94',
          options: ['striped', 'spotted', 'plain', 'cotton'],
          correct: 1, explanation: 'From SB p.94: spotted = pattern with dots/spots. striped = with stripes/lines.',
          golden_rule: 'Patterns: spotted (dots), striped (lines), plain (no pattern). Materials: cotton, silk, leather, wool.' },
        { type: 'classify', bloom: 'apply', difficulty: 'medium', page: 94,
          q: 'Classify these words: ACCESSORIES or MATERIALS?',
          categories: ['Accessories', 'Materials'],
          items: [
            { text: 'bracelet', correct_cat: 0 }, { text: 'silk', correct_cat: 1 },
            { text: 'necklace', correct_cat: 0 }, { text: 'wool', correct_cat: 1 },
            { text: 'earrings', correct_cat: 0 }, { text: 'cotton', correct_cat: 1 },
          ],
          explanation: 'From SB pp.94-100: accessories = things you wear for decoration. Materials = what clothes are made of.',
          golden_rule: 'Accessories: bracelet, necklace, earrings, ring, belt, tie, comb. Materials: silk, cotton, wool, leather, gold, silver, plastic.' },
        { type: 'mc', bloom: 'understand', difficulty: 'medium', page: 100,
          q: 'Which material is described as natural, from animals (sheep)?', page_ref: 'SB p.100',
          options: ['plastic', 'leather', 'wool', 'metal'],
          correct: 2, explanation: 'From SB p.100: wool = natural material from sheep. leather = from animal skin.',
          golden_rule: 'Natural materials from animals: wool (sheep), leather (animal skin), silk (silkworms).' },
        { type: 'mc', bloom: 'apply', difficulty: 'medium', page: 100,
          q: 'A "costume" is:', page_ref: 'SB p.94',
          options: ['everyday casual clothes', 'special clothes worn for a performance or special occasion', 'school uniform', 'sports clothes'],
          correct: 1, explanation: 'From SB p.94: costume = special clothes for a performance, Halloween, or special event.',
          golden_rule: 'costume = special clothes for a show/event/holiday (e.g., Halloween costume, theater costume).' },
      ]
    },
    {
      id: 'u8_l2',
      title: 'Grammar: Comparatives & Superlatives',
      page: '96–102',
      questions: [
        { type: 'mc', bloom: 'remember', difficulty: 'easy', page: 96,
          q: 'What is the SUPERLATIVE form of "expensive"?', page_ref: 'SB p.96',
          options: ['more expensive', 'expensiver', 'the most expensive', 'the expensivest'],
          correct: 2, explanation: 'From SB p.96: long adjectives use "the most" for superlatives. expensive → the MOST expensive.',
          golden_rule: 'Short adjective: big→the biggest. Long adjective: expensive→the most expensive.' },
        { type: 'mc', bloom: 'apply', difficulty: 'medium', page: 96,
          q: 'Choose the correct comparative: "This silk shirt is ___ that cotton one."', page_ref: 'SB p.96',
          options: ['more softer than', 'softer than', 'the softest than', 'most soft than'],
          correct: 1, explanation: 'From SB p.96: soft → softer (short adjective = +er). Comparative = adjective-er + than.',
          golden_rule: 'Comparative: short adj + ER + than. "softer than" "cheaper than" "bigger than".' },
        { type: 'mc', bloom: 'apply', difficulty: 'hard', page: 98,
          q: 'In "The Best Outfit" reading (WB), which sentence uses a superlative correctly?', page_ref: 'WB p.100',
          options: [
            'This is the most elegant outfit from all.',
            'This is the most elegant outfit of all.',
            'This is more elegant outfit of all.',
            'This is the eleganter outfit of all.',
          ],
          correct: 1, explanation: 'Superlative: "the most elegant outfit of all." Use "of" with superlatives for groups.',
          golden_rule: 'Superlative + "of all / of the group": "She\'s the tallest of all" "It\'s the most beautiful of them all."' },
      ]
    }
  ]
};

// ─────────────────────────────────────────────────────────
// تجميع كل الوحدات
// ─────────────────────────────────────────────────────────
export const TOP_GOAL2_BANK = {
  subject: 'English Language — Top Goal 2',
  grade: 'Grade 5 Primary',
  semester: 'Semester 1 — 1447H',
  units: [WELCOME_UNIT, UNIT1, UNIT2, UNIT3, UNIT4, UNIT5, UNIT6, UNIT7, UNIT8]
};

export const TOTAL_Q = TOP_GOAL2_BANK.units
  .flatMap(u => u.lessons)
  .reduce((s, l) => s + l.questions.length, 0);