// We Can! 2 - Grade 2 English - Term 1 - Units 3-5 Question Bank

const unit3Questions = [
  { id:'u3l1q1', unit:'unit3', lesson:'u3l1', page:80, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'On the phone you say "___" to confirm you are the person they called:',
    paragraph:'"Hello. Can I speak to Joe? — Speaking." (Workbook p.80)',
    options:[{text:'Speaking.',correct:true},{text:'Fine.',correct:false},{text:'Hello.',correct:false},{text:'Goodbye.',correct:false}],
    explanation:'"Speaking" = Yes, this is me! Used when someone asks for you on the phone.',
    goldenRule:'On the phone: "Can I speak to ___?" → "Speaking." (= Yes, it\'s me!)',
    feedbackQuestion:{question:'"Can I speak to Nora?" — Nora answers:',options:[{text:'Speaking!',correct:true},{text:'Hello Joe!',correct:false},{text:'I\'m fine.',correct:false},{text:'Goodbye!',correct:false}]}},

  { id:'u3l1q2', unit:'unit3', lesson:'u3l1', page:80, type:'ordering', bloom:'understand', difficulty:'medium',
    question:'Put the phone conversation in order:',
    paragraph:'"Hello. Can I speak to Joe? — Speaking. — What are you doing? — I\'m doing my homework." (Workbook p.80)',
    items:['I\'m doing my homework.','Hello. Can I speak to Joe?','What are you doing?','Speaking.'],
    correctOrder:[1,3,2,0],
    explanation:'1. Hello, can I speak to Joe? 2. Speaking. 3. What are you doing? 4. I\'m doing my homework.',
    goldenRule:'Phone conversation: Greeting → Identify → Ask → Answer.'},

  { id:'u3l1q3', unit:'unit3', lesson:'u3l1', page:80, type:'multipleChoice', bloom:'apply', difficulty:'medium',
    question:'"He\'s ___ TV." Fill in:',
    paragraph:'"What\'s your dad doing? — He\'s watching TV." (Workbook p.80)',
    options:[{text:'watching',correct:true},{text:'watch',correct:false},{text:'watches',correct:false},{text:'watched',correct:false}],
    explanation:'"He\'s watching" = He is + watching (present continuous).',
    goldenRule:'Present Continuous: I am | He/She is | They are + -ing',
    feedbackQuestion:{question:'"What is she doing?" — Correct answer:',options:[{text:'She\'s doing karate.',correct:true},{text:'She does karate.',correct:false},{text:'She karate.',correct:false},{text:'She done karate.',correct:false}]}},

  { id:'u3l1q4', unit:'unit3', lesson:'u3l1', page:81, type:'trueFalse', bloom:'understand', difficulty:'easy',
    question:'"Good-bye" and "Bye" mean the same thing.',
    paragraph:'"Good-bye. — Bye." (Workbook p.81)',
    correctAnswer:true, explanation:'"Good-bye" and "Bye" both mean farewell.',
    goldenRule:'Goodbye = Bye = See you. These all mean "until next time!"',
    feedbackQuestion:{question:'Which is the INFORMAL way to say goodbye?',options:[{text:'Bye!',correct:true},{text:'Good-bye.',correct:false},{text:'Farewell.',correct:false},{text:'Goodnight.',correct:false}]}},

  { id:'u3l1q5', unit:'unit3', lesson:'u3l1', page:81, type:'fillBlank', bloom:'apply', difficulty:'medium',
    question:'Complete: "Hello. Can I speak to ___? — ___. — What are you doing? — I\'m ___ TV."',
    paragraph:'"Phone conversation." (Workbook p.81)',
    blanks:['Joe','Speaking','watching'], wordBank:['Joe','Speaking','watching','Hello'],
    explanation:'Hello. Can I speak to Joe? Speaking. What are you doing? I\'m watching TV.',
    goldenRule:'Phone dialogue pattern: speak to → Speaking → What are you doing? → I\'m ___-ing.'},

  { id:'u3l1q6', unit:'unit3', lesson:'u3l1', page:81, type:'matching', bloom:'understand', difficulty:'easy',
    question:'Match question with answer:',
    paragraph:'Phone conversation patterns (Workbook p.80-81)',
    pairs:[{left:'Can I speak to Sara?',right:'Speaking.'},{left:'What are you doing?',right:'I\'m doing homework.'},{left:'Good-bye!',right:'Bye!'},{left:'How are you?',right:'I\'m fine.'}],
    explanation:'Standard phone conversation responses.',
    goldenRule:'Speaking=yes it\'s me | I\'m fine=how are you | Bye=goodbye.'},

  { id:'u3l2q1', unit:'unit3', lesson:'u3l2', page:82, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'"I\'m doing karate, doing karate, ___." Complete the chant:',
    paragraph:'"What are you doing? I\'m doing karate." (Workbook p.82)',
    options:[{text:'doing karate',correct:true},{text:'playing football',correct:false},{text:'watching TV',correct:false},{text:'eating snacks',correct:false}],
    explanation:'The chant repeats "doing karate" three times for rhythm.',
    goldenRule:'"I\'m doing karate" = I + am + verb-ing.',
    feedbackQuestion:{question:'"I\'m playing football, playing football, ___."',options:[{text:'playing football',correct:true},{text:'doing karate',correct:false},{text:'watching TV',correct:false},{text:'eating snacks',correct:false}]}},

  { id:'u3l2q2', unit:'unit3', lesson:'u3l2', page:82, type:'matching', bloom:'understand', difficulty:'easy',
    question:'Match the verb with the correct activity:',
    paragraph:'"Match: doing/playing/watching + homework/karate/TV/football." (Workbook p.82)',
    pairs:[{left:'doing',right:'karate'},{left:'playing',right:'football'},{left:'watching',right:'TV'},{left:'doing',right:'homework'}],
    explanation:'doing karate, doing homework, playing football, watching TV.',
    goldenRule:'Collocations: doing homework/karate | playing football/computer games | watching TV'},

  { id:'u3l2q3', unit:'unit3', lesson:'u3l2', page:83, type:'trueFalse', bloom:'apply', difficulty:'medium',
    question:'"I\'m playing football." (picture shows: playing computer games). This is FALSE.',
    paragraph:'"True or False Action Game." (Workbook p.83)',
    correctAnswer:true, explanation:'The sentence says football but the picture shows computer games — FALSE.',
    goldenRule:'True = sentence matches picture. False = it does NOT match.',
    feedbackQuestion:{question:'"I\'m doing karate." (picture shows: doing karate). This is:',options:[{text:'True',correct:true},{text:'False',correct:false}]}},

  { id:'u3l2q4', unit:'unit3', lesson:'u3l2', page:82, type:'classify', bloom:'analyze', difficulty:'medium',
    question:'Classify: indoor or outdoor activities:',
    paragraph:'Activities from Goal 19-20 (Workbook p.82-83)',
    categories:['Indoor Activities','Outdoor Activities'],
    items:[{text:'watching TV',correct_category:0},{text:'playing football',correct_category:1},{text:'doing homework',correct_category:0},{text:'doing karate',correct_category:1},{text:'playing computer games',correct_category:0}],
    explanation:'Indoor: TV, homework, computer. Outdoor: football, karate.',
    goldenRule:'Indoor = inside. Outdoor = outside.'},

  { id:'u3l2q5', unit:'unit3', lesson:'u3l2', page:83, type:'multipleChoice', bloom:'apply', difficulty:'medium',
    question:'"What are you doing?" — Correct present continuous answer:',
    paragraph:'"What are you doing? I\'m eating snacks." (Workbook p.85)',
    options:[{text:'I\'m watching TV.',correct:true},{text:'I watch TV.',correct:false},{text:'I watched TV.',correct:false},{text:'I will watch TV.',correct:false}],
    explanation:'"I\'m watching" = I am + watching. Present continuous for NOW.',
    goldenRule:'Present continuous = I am + verb-ing. For things happening NOW.',
    feedbackQuestion:{question:'Which uses present continuous correctly?',options:[{text:'She\'s doing karate.',correct:true},{text:'She do karate.',correct:false},{text:'She does karate.',correct:false},{text:'She karate now.',correct:false}]}},

  { id:'u3l2q6', unit:'unit3', lesson:'u3l2', page:82, type:'fillBlank', bloom:'apply', difficulty:'medium',
    question:'Fill in: "What are you ___? I\'m ___ karate."',
    paragraph:'"What are you doing? I\'m doing karate." (Workbook p.82)',
    blanks:['doing','doing'], wordBank:['doing','doing','playing','watching'],
    explanation:'What are you DOING? I\'m DOING karate.',
    goldenRule:'"doing" appears twice — in the question and the answer.'},

  { id:'u3l3q1', unit:'unit3', lesson:'u3l3', page:84, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'Which activity involves using a computer to play games?',
    paragraph:'"I\'m playing computer games." (Workbook p.84)',
    options:[{text:'playing computer games',correct:true},{text:'doing karate',correct:false},{text:'eating snacks',correct:false},{text:'playing football',correct:false}],
    explanation:'"Playing computer games" = using a computer/tablet/phone to play.',
    goldenRule:'6 actions: doing homework | playing football | watching TV | eating snacks | playing computer games | doing karate',
    feedbackQuestion:{question:'Which activity uses a ball outside?',options:[{text:'playing football',correct:true},{text:'watching TV',correct:false},{text:'eating snacks',correct:false},{text:'doing homework',correct:false}]}},

  { id:'u3l3q2', unit:'unit3', lesson:'u3l3', page:84, type:'classify', bloom:'analyze', difficulty:'medium',
    question:'Classify: Physical Activity OR Relaxing Activity:',
    paragraph:'Activity cards Goal 21-22 (Workbook p.84-85)',
    categories:['Physical Activity','Relaxing Activity'],
    items:[{text:'playing football',correct_category:0},{text:'watching TV',correct_category:1},{text:'doing karate',correct_category:0},{text:'eating snacks',correct_category:1},{text:'doing my homework',correct_category:1}],
    explanation:'Physical: football, karate. Relaxing: TV, snacks, homework.',
    goldenRule:'Physical = uses body strength. Relaxing = calm and quiet.'},

  { id:'u3l3q3', unit:'unit3', lesson:'u3l3', page:85, type:'multipleChoice', bloom:'apply', difficulty:'medium',
    question:'"I\'m doing ___." Study activity:',
    paragraph:'"What are you doing? I\'m doing my homework." (Workbook p.85)',
    options:[{text:'my homework',correct:true},{text:'my football',correct:false},{text:'my TV',correct:false},{text:'my snacks',correct:false}],
    explanation:'"Doing my homework" is correct. You "do" homework.',
    goldenRule:'Collocations: do homework | play football | watch TV | eat snacks.',
    feedbackQuestion:{question:'Which is the correct collocation?',options:[{text:'eating snacks',correct:true},{text:'eating football',correct:false},{text:'eating TV',correct:false},{text:'eating karate',correct:false}]}},

  { id:'u3l3q4', unit:'unit3', lesson:'u3l3', page:85, type:'trueFalse', bloom:'understand', difficulty:'easy',
    question:'"I\'m doing nothing!" means the person is very busy.',
    paragraph:'"I\'m doing nothing!" (Workbook p.85)',
    correctAnswer:false, explanation:'"I\'m doing nothing" = NOT doing anything = free/relaxing.',
    goldenRule:'"doing nothing" = free time = not busy.',
    feedbackQuestion:{question:'"I\'m doing nothing!" They are:',options:[{text:'Relaxing and free',correct:true},{text:'Very busy',correct:false},{text:'Sleeping',correct:false},{text:'Working hard',correct:false}]}},

  { id:'u3l3q5', unit:'unit3', lesson:'u3l3', page:84, type:'matching', bloom:'remember', difficulty:'easy',
    question:'Match each card number with its action:',
    paragraph:'Card Snap Game — 6 activity cards (Workbook p.84)',
    pairs:[{left:'Card 1',right:'I\'m doing my homework.'},{left:'Card 2',right:'I\'m playing football.'},{left:'Card 3',right:'I\'m watching TV.'},{left:'Card 6',right:'I\'m doing karate.'}],
    explanation:'1=homework, 2=football, 3=TV, 4=snacks, 5=computer games, 6=karate.',
    goldenRule:'Know all 6 action phrases from the Card Snap Game.'},

  { id:'u3l3q6', unit:'unit3', lesson:'u3l3', page:85, type:'ordering', bloom:'apply', difficulty:'medium',
    question:'Order from most to least physical:',
    paragraph:'Actions vocabulary from Unit 3 (Workbook p.82-85)',
    items:['watching TV','doing karate','eating snacks','playing football'], correctOrder:[1,3,2,0],
    explanation:'Most physical: karate → football → eating → watching TV (least).',
    goldenRule:'Physical level: sports > eating > watching TV.'},

  { id:'u3l4q1', unit:'unit3', lesson:'u3l4', page:86, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'The word "tiger" starts with which sound?',
    paragraph:'"Phonics t or d: tiger/tomato, door/doll." (Workbook p.86)',
    options:[{text:'/t/ as in top',correct:true},{text:'/d/ as in dog',correct:false},{text:'/p/ as in pin',correct:false},{text:'/b/ as in ball',correct:false}],
    explanation:'"Tiger" starts with /t/.',
    goldenRule:'/t/: tiger, tomato, telephone, tape. /d/: door, doll, duck.',
    feedbackQuestion:{question:'Which word starts with /d/?',options:[{text:'doll',correct:true},{text:'tiger',correct:false},{text:'tomato',correct:false},{text:'telephone',correct:false}]}},

  { id:'u3l4q2', unit:'unit3', lesson:'u3l4', page:86, type:'classify', bloom:'analyze', difficulty:'medium',
    question:'Classify by starting sound: /t/ or /d/:',
    paragraph:'"Listen and circle t or d." (Workbook p.86)',
    categories:['/t/ sound (tiger)','/d/ sound (door)'],
    items:[{text:'tiger',correct_category:0},{text:'door',correct_category:1},{text:'tomato',correct_category:0},{text:'doll',correct_category:1},{text:'telephone',correct_category:0},{text:'duck',correct_category:1}],
    explanation:'/t/: tiger, tomato, telephone. /d/: door, doll, duck.',
    goldenRule:'/t/=unvoiced. /d/=voiced. Put hand on throat to feel!'},

  { id:'u3l4q3', unit:'unit3', lesson:'u3l4', page:87, type:'trueFalse', bloom:'understand', difficulty:'easy',
    question:'"Duck" and "doll" both start with the /d/ sound.',
    paragraph:'"doll / duck under /d/ words." (Workbook p.87)',
    correctAnswer:true, explanation:'D-uck and D-oll both start with /d/.',
    goldenRule:'/d/ words: duck, doll, door, dog.',
    feedbackQuestion:{question:'Which TWO words start with /t/?',options:[{text:'tiger and tomato',correct:true},{text:'duck and doll',correct:false},{text:'door and doll',correct:false},{text:'bear and bed',correct:false}]}},

  { id:'u3l4q4', unit:'unit3', lesson:'u3l4', page:86, type:'fillBlank', bloom:'apply', difficulty:'medium',
    question:'Write the missing first letter (t or d): ___iger, ___oll, ___oor, ___elephone',
    paragraph:'"Write missing letters t or d." (Workbook p.86)',
    blanks:['t','d','d','t'], wordBank:['t','d','d','t'],
    explanation:'tiger=t, doll=d, door=d, telephone=t.',
    goldenRule:'Listen for the starting sound to know if it\'s t or d.'},

  { id:'u3l4q5', unit:'unit3', lesson:'u3l4', page:87, type:'matching', bloom:'remember', difficulty:'easy',
    question:'Match each word with its starting sound:',
    paragraph:'Phonics t and d (Workbook p.86-87)',
    pairs:[{left:'tiger',right:'/t/'},{left:'door',right:'/d/'},{left:'tomato',right:'/t/'},{left:'duck',right:'/d/'}],
    explanation:'tiger/tomato=/t/. door/duck=/d/.',
    goldenRule:'/t/: tiger, tape, tomato. /d/: door, doll, duck.'},

  { id:'u3l4q6', unit:'unit3', lesson:'u3l4', page:86, type:'multipleChoice', bloom:'evaluate', difficulty:'hard',
    question:'Which pair has DIFFERENT starting sounds?',
    paragraph:'Phonics t and d (Workbook p.86-87)',
    options:[{text:'tiger and doll',correct:true},{text:'tiger and tomato',correct:false},{text:'duck and door',correct:false},{text:'doll and duck',correct:false}],
    explanation:'tiger=/t/, doll=/d/ — DIFFERENT. Others share the same sound.',
    goldenRule:'Same sound: tiger+tomato(/t/). Different: tiger+doll (/t/ vs /d/).',
    feedbackQuestion:{question:'Which pair has the SAME starting sound?',options:[{text:'telephone and tomato',correct:true},{text:'tiger and doll',correct:false},{text:'door and tiger',correct:false},{text:'duck and tape',correct:false}]}},
];

const unit4Questions = [
  { id:'u4l1q1', unit:'unit4', lesson:'u4l1', page:88, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'What does the first person say when they see a snake?',
    paragraph:'"Look! It\'s a snake!" (Workbook p.88)',
    options:[{text:'Look! It\'s a snake!',correct:true},{text:'It\'s beautiful!',correct:false},{text:'It\'s short!',correct:false},{text:'It\'s ugly!',correct:false}],
    explanation:'"Look! It\'s a snake!" draws attention to what they see.',
    goldenRule:'"Look!" = Draw attention. Use it to tell someone to look.',
    feedbackQuestion:{question:'Person B says "short", Person A corrects: "___, it\'s long!"',options:[{text:'No',correct:true},{text:'Yes',correct:false},{text:'Look',correct:false},{text:'Oh',correct:false}]}},

  { id:'u4l1q2', unit:'unit4', lesson:'u4l1', page:89, type:'matching', bloom:'understand', difficulty:'easy',
    question:'Match each thing with beautiful or ugly:',
    paragraph:'"plastic bag/hat/flower/monster." (Workbook p.89)',
    pairs:[{left:'flower',right:'beautiful'},{left:'monster',right:'ugly'},{left:'plastic bag',right:'ugly'},{left:'garden',right:'beautiful'}],
    explanation:'Flowers/gardens = beautiful. Monsters/plastic bags = ugly.',
    goldenRule:'beautiful = nice, pretty. ugly = not nice, unpleasant.'},

  { id:'u4l1q3', unit:'unit4', lesson:'u4l1', page:88, type:'trueFalse', bloom:'understand', difficulty:'easy',
    question:'"Beautiful" and "ugly" are opposites.',
    paragraph:'"It\'s beautiful! / No, it\'s ugly!" (Workbook p.88-89)',
    correctAnswer:true, explanation:'Beautiful = very pretty/nice. Ugly = not pretty. Antonyms!',
    goldenRule:'Opposites: beautiful↔ugly | long↔short | big↔small | quiet↔noisy',
    feedbackQuestion:{question:'What is the opposite of "beautiful"?',options:[{text:'ugly',correct:true},{text:'small',correct:false},{text:'short',correct:false},{text:'quiet',correct:false}]}},

  { id:'u4l1q4', unit:'unit4', lesson:'u4l1', page:89, type:'multipleChoice', bloom:'apply', difficulty:'medium',
    question:'You see a beautiful flower. What do you say?',
    paragraph:'"Look! It\'s a ___! It\'s beautiful." (Workbook p.89)',
    options:[{text:'Look! It\'s a flower! It\'s beautiful!',correct:true},{text:'Look! It\'s a flower! It\'s ugly!',correct:false},{text:'The flower is doing karate!',correct:false},{text:'I\'m wearing a flower.',correct:false}],
    explanation:'A flower is beautiful. Use "Look! It\'s a ___! It\'s beautiful!"',
    goldenRule:'Describe nature: Look! It\'s a ___! It\'s beautiful/ugly!',
    feedbackQuestion:{question:'You see a plastic bag on the ground. You say:',options:[{text:'Look! It\'s a plastic bag! It\'s ugly!',correct:true},{text:'Look! It\'s beautiful!',correct:false},{text:'I\'m wearing a bag.',correct:false},{text:'It\'s doing karate.',correct:false}]}},

  { id:'u4l1q5', unit:'unit4', lesson:'u4l1', page:89, type:'classify', bloom:'evaluate', difficulty:'medium',
    question:'Classify as "Beautiful" or "Ugly":',
    paragraph:'"Draw something beautiful and something ugly." (Workbook p.89)',
    categories:['Beautiful','Ugly'],
    items:[{text:'a flower',correct_category:0},{text:'a monster',correct_category:1},{text:'a rainbow',correct_category:0},{text:'a plastic bag in nature',correct_category:1},{text:'a mountain',correct_category:0}],
    explanation:'Natural beauties: flower, rainbow, mountain. Unpleasant: monster, plastic bag.',
    goldenRule:'Beautiful = nature, art. Ugly = trash, monsters, pollution.'},

  { id:'u4l1q6', unit:'unit4', lesson:'u4l1', page:88, type:'fillBlank', bloom:'apply', difficulty:'medium',
    question:'Fill in: "Look! It\'s a ___! It\'s ___!"',
    paragraph:'"Look! It\'s a snake! B: It\'s beautiful!" (Workbook p.88)',
    blanks:['snake','beautiful'], wordBank:['snake','beautiful','ugly','flower'],
    explanation:'The dialogue: seeing a snake. Person B thinks it\'s beautiful.',
    goldenRule:'"Look! It\'s a ___!" then describe with an adjective.'},

  { id:'u4l2q1', unit:'unit4', lesson:'u4l2', page:90, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'In "I Love the Mountains", which is NOT mentioned?',
    paragraph:'"mountains, rolling hills, flowers, daffodils, campfire, stars." (Workbook p.90)',
    options:[{text:'the ocean',correct:true},{text:'the mountains',correct:false},{text:'the flowers',correct:false},{text:'the campfire',correct:false}],
    explanation:'The chant mentions mountains, hills, flowers, daffodils, campfire, stars. NOT ocean.',
    goldenRule:'Nature words: mountains, hills, flowers, daffodils, campfire, stars.',
    feedbackQuestion:{question:'What comes out at night according to the chant?',options:[{text:'the stars',correct:true},{text:'the flowers',correct:false},{text:'the mountains',correct:false},{text:'the campfire',correct:false}]}},

  { id:'u4l2q2', unit:'unit4', lesson:'u4l2', page:91, type:'classify', bloom:'remember', difficulty:'easy',
    question:'Classify months into Fall or Winter:',
    paragraph:'"fall/September,October,November — winter/December,January,February." (Workbook p.91)',
    categories:['Fall/Autumn','Winter'],
    items:[{text:'September',correct_category:0},{text:'December',correct_category:1},{text:'October',correct_category:0},{text:'January',correct_category:1},{text:'November',correct_category:0},{text:'February',correct_category:1}],
    explanation:'Fall: Sep, Oct, Nov. Winter: Dec, Jan, Feb.',
    goldenRule:'Fall(Sep-Nov) → Winter(Dec-Feb) → Spring(Mar-May) → Summer(Jun-Aug).'},

  { id:'u4l2q3', unit:'unit4', lesson:'u4l2', page:91, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'Which season has flowers and starts in March?',
    paragraph:'"Flowers are out, it\'s ___. ___, April, May." (Workbook p.91)',
    options:[{text:'spring',correct:true},{text:'summer',correct:false},{text:'winter',correct:false},{text:'fall',correct:false}],
    explanation:'Spring: March, April, May — flowers bloom.',
    goldenRule:'Spring = March, April, May. Flowers and warm weather return.',
    feedbackQuestion:{question:'"Back to school, it\'s ___. September, October, November."',options:[{text:'fall',correct:true},{text:'spring',correct:false},{text:'summer',correct:false},{text:'winter',correct:false}]}},

  { id:'u4l2q4', unit:'unit4', lesson:'u4l2', page:91, type:'ordering', bloom:'remember', difficulty:'medium',
    question:'Put the seasons in order starting from fall:',
    paragraph:'Seasons: fall, winter, spring, summer (Workbook p.91)',
    items:['summer','spring','fall','winter'], correctOrder:[2,3,1,0],
    explanation:'fall → winter → spring → summer → (back to fall).',
    goldenRule:'Season cycle: fall → winter → spring → summer.'},

  { id:'u4l2q5', unit:'unit4', lesson:'u4l2', page:90, type:'trueFalse', bloom:'understand', difficulty:'easy',
    question:'"I\'m happy to be under this sky" means the person enjoys being in nature.',
    paragraph:'"I sit and look, I look and smile, I\'m happy to be under this sky." (Workbook p.90)',
    correctAnswer:true, explanation:'Sitting, looking, smiling under the sky = enjoying nature.',
    goldenRule:'Appreciating nature = happy outdoors, looking at mountains and stars.',
    feedbackQuestion:{question:'What does the person do when happy in nature?',options:[{text:'Sit and look and smile',correct:true},{text:'Watch TV',correct:false},{text:'Do homework',correct:false},{text:'Play football',correct:false}]}},

  { id:'u4l2q6', unit:'unit4', lesson:'u4l2', page:91, type:'fillBlank', bloom:'remember', difficulty:'medium',
    question:'"Yummy, ___\'s here. June, July, August."',
    paragraph:'Seasons chant summer months (Workbook p.91)',
    blanks:['summer'], wordBank:['summer','winter','spring','fall'],
    explanation:'June, July, August = summer months.',
    goldenRule:'Summer: June, July, August = hot weather!'},

  { id:'u4l3q1', unit:'unit4', lesson:'u4l3', page:92, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'The opposite of "long" is:',
    paragraph:'"It\'s long. / It\'s short." (Workbook p.92)',
    options:[{text:'short',correct:true},{text:'small',correct:false},{text:'quiet',correct:false},{text:'weak',correct:false}],
    explanation:'"Long" and "short" are opposites.',
    goldenRule:'Opposite pairs: long/short | big/small | quiet/noisy | weak/strong | beautiful/ugly',
    feedbackQuestion:{question:'What is the opposite of "big"?',options:[{text:'small',correct:true},{text:'short',correct:false},{text:'weak',correct:false},{text:'quiet',correct:false}]}},

  { id:'u4l3q2', unit:'unit4', lesson:'u4l3', page:92, type:'matching', bloom:'remember', difficulty:'easy',
    question:'Match each word with its opposite:',
    paragraph:'"Opposites: long/short, big/small, quiet/noisy, weak/strong." (Workbook p.92)',
    pairs:[{left:'long',right:'short'},{left:'big',right:'small'},{left:'quiet',right:'noisy'},{left:'weak',right:'strong'}],
    explanation:'4 opposite pairs: long/short, big/small, quiet/noisy, weak/strong.',
    goldenRule:'Know your opposite pairs for describing and comparing!'},

  { id:'u4l3q3', unit:'unit4', lesson:'u4l3', page:93, type:'classify', bloom:'analyze', difficulty:'medium',
    question:'Classify animals by size:',
    paragraph:'"It\'s small and gray. / It\'s big and strong." (Workbook p.93)',
    categories:['Small Animal','Big Animal'],
    items:[{text:'rabbit (small and gray)',correct_category:0},{text:'bull (big and strong)',correct_category:1},{text:'parrot (small and noisy)',correct_category:0},{text:'fish (small and quiet)',correct_category:0}],
    explanation:'Rabbit, parrot, fish = small. Bull = big and strong.',
    goldenRule:'Use adjectives to describe size: big, small, large, tiny.'},

  { id:'u4l3q4', unit:'unit4', lesson:'u4l3', page:93, type:'trueFalse', bloom:'apply', difficulty:'medium',
    question:'A rabbit is "big and strong".',
    paragraph:'"It\'s small and gray." (describing rabbit — Workbook p.93)',
    correctAnswer:false, explanation:'A rabbit is SMALL and gray. A bull is big and strong.',
    goldenRule:'Rabbit=small and gray. Bull=big and strong.',
    feedbackQuestion:{question:'Which animal is "small and gray"?',options:[{text:'rabbit',correct:true},{text:'bull',correct:false},{text:'elephant',correct:false},{text:'tiger',correct:false}]}},

  { id:'u4l3q5', unit:'unit4', lesson:'u4l3', page:92, type:'fillBlank', bloom:'apply', difficulty:'medium',
    question:'"It\'s long. → It\'s ___. It\'s big. → It\'s ___."',
    paragraph:'"Write the opposites." (Workbook p.92)',
    blanks:['short','small'], wordBank:['short','small','quiet','weak'],
    explanation:'long → short. big → small.',
    goldenRule:'Opposite pairs: long/short, big/small, noisy/quiet, weak/strong.'},

  { id:'u4l3q6', unit:'unit4', lesson:'u4l3', page:93, type:'multipleChoice', bloom:'evaluate', difficulty:'hard',
    question:'Which pair uses opposites correctly?',
    paragraph:'Opposites from Unit 4 (Workbook p.92-93)',
    options:[{text:'It\'s big. / It\'s small.',correct:true},{text:'It\'s big. / It\'s long.',correct:false},{text:'It\'s quiet. / It\'s short.',correct:false},{text:'It\'s strong. / It\'s long.',correct:false}],
    explanation:'big and small are true opposites. Others are NOT opposite pairs.',
    goldenRule:'True opposites: big/small | long/short | quiet/noisy | weak/strong.',
    feedbackQuestion:{question:'What is the opposite of "noisy"?',options:[{text:'quiet',correct:true},{text:'big',correct:false},{text:'long',correct:false},{text:'strong',correct:false}]}},

  { id:'u4l4q1', unit:'unit4', lesson:'u4l4', page:94, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'The word "cat" starts with:',
    paragraph:'"Phonics c or g: cat / cake, gorilla / goat." (Workbook p.94)',
    options:[{text:'/k/ as in cat',correct:true},{text:'/g/ as in goat',correct:false},{text:'/t/ as in tiger',correct:false},{text:'/d/ as in doll',correct:false}],
    explanation:'"Cat" starts with /k/ (spelled c).',
    goldenRule:'/k/ (c): cat, cap, cake. /g/: gorilla, goat, girl.',
    feedbackQuestion:{question:'Which word starts with /g/?',options:[{text:'gorilla',correct:true},{text:'cat',correct:false},{text:'cake',correct:false},{text:'cap',correct:false}]}},

  { id:'u4l4q2', unit:'unit4', lesson:'u4l4', page:94, type:'classify', bloom:'analyze', difficulty:'medium',
    question:'Classify by starting sound: /c/ or /g/:',
    paragraph:'"Listen and circle c or g." (Workbook p.94)',
    categories:['/c/ sound (cat)','/g/ sound (goat)'],
    items:[{text:'cat',correct_category:0},{text:'gorilla',correct_category:1},{text:'cap',correct_category:0},{text:'goat',correct_category:1},{text:'cake',correct_category:0},{text:'girl',correct_category:1}],
    explanation:'/c/: cat, cap, cake. /g/: gorilla, goat, girl.',
    goldenRule:'/c/(k): cat, cap, cake. /g/: gorilla, goat, girl, grass.'},

  { id:'u4l4q3', unit:'unit4', lesson:'u4l4', page:95, type:'trueFalse', bloom:'understand', difficulty:'easy',
    question:'"Gorilla" and "goat" both start with the /g/ sound.',
    paragraph:'"gorilla / goat under /g/ words." (Workbook p.95)',
    correctAnswer:true, explanation:'G-orilla and G-oat both start with /g/.',
    goldenRule:'/g/ words: gorilla, goat, girl, grass.',
    feedbackQuestion:{question:'Which TWO words start with /c/ (k)?',options:[{text:'cat and cake',correct:true},{text:'gorilla and goat',correct:false},{text:'girl and goat',correct:false},{text:'grass and gorilla',correct:false}]}},

  { id:'u4l4q4', unit:'unit4', lesson:'u4l4', page:94, type:'matching', bloom:'remember', difficulty:'easy',
    question:'Match each word with its starting letter:',
    paragraph:'Phonics c and g vocabulary (Workbook p.94-95)',
    pairs:[{left:'cat',right:'c'},{left:'gorilla',right:'g'},{left:'cap',right:'c'},{left:'goat',right:'g'}],
    explanation:'cat/cap = c. gorilla/goat = g.',
    goldenRule:'c words: cat, cap, cake. g words: gorilla, goat, girl.'},

  { id:'u4l4q5', unit:'unit4', lesson:'u4l4', page:94, type:'fillBlank', bloom:'apply', difficulty:'medium',
    question:'Write missing first letter (c or g): ___at, ___irl, ___ap, ___oat',
    paragraph:'"Write missing letters c or g." (Workbook p.94)',
    blanks:['c','g','c','g'], wordBank:['c','g','c','g'],
    explanation:'cat=c, girl=g, cap=c, goat=g.',
    goldenRule:'Listen for starting sound: /k/=c, /g/=g.'},

  { id:'u4l4q6', unit:'unit4', lesson:'u4l4', page:95, type:'multipleChoice', bloom:'evaluate', difficulty:'hard',
    question:'Which pair has the SAME starting sound?',
    paragraph:'"cat / cake, gorilla / goat." (Workbook p.95)',
    options:[{text:'cat and cake',correct:true},{text:'cat and goat',correct:false},{text:'gorilla and cake',correct:false},{text:'girl and cap',correct:false}],
    explanation:'cat and cake both start with /k/. Others are mixed.',
    goldenRule:'Same sound: cat/cake/cap (/k/). gorilla/goat/girl (/g/).',
    feedbackQuestion:{question:'Which pair has DIFFERENT starting sounds?',options:[{text:'cat and goat',correct:true},{text:'gorilla and goat',correct:false},{text:'cat and cap',correct:false},{text:'cake and cat',correct:false}]}},
];

const unit5Questions = [
  { id:'u5l1q1', unit:'unit5', lesson:'u5l1', page:96, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'To introduce your friend to someone, you say:',
    paragraph:'"This is my friend, Omar." (Workbook p.96)',
    options:[{text:'This is my friend, Omar.',correct:true},{text:'I have a friend Omar.',correct:false},{text:'Omar is speaking.',correct:false},{text:'Hello Omar is here.',correct:false}],
    explanation:'"This is my friend, ___" is the standard introduction phrase.',
    goldenRule:'Introduce: "This is my friend, ___." Response: "Nice to meet you!"',
    feedbackQuestion:{question:'Someone introduces you to their friend. You say:',options:[{text:'Nice to meet you!',correct:true},{text:'What are you doing?',correct:false},{text:'Goodbye!',correct:false},{text:'I\'m fine.',correct:false}]}},

  { id:'u5l1q2', unit:'unit5', lesson:'u5l1', page:96, type:'ordering', bloom:'understand', difficulty:'medium',
    question:'Put the introduction dialogue in order:',
    paragraph:'"Good morning Ali. Where\'s Jake? / He can\'t come. / This is my friend, Omar. / Nice to meet you Omar. / Nice to meet you too." (Workbook p.96)',
    items:['Nice to meet you too.','Good morning Ali. Where\'s Jake?','This is my friend, Omar.','He can\'t come.','Nice to meet you Omar.'],
    correctOrder:[1,3,2,4,0],
    explanation:'Order: Greet → Ask about Jake → Explain → Introduce → Nice to meet you → Response.',
    goldenRule:'Introduction: greet → explain → introduce → "Nice to meet you!" → "You too!"'},

  { id:'u5l1q3', unit:'unit5', lesson:'u5l1', page:97, type:'multipleChoice', bloom:'apply', difficulty:'medium',
    question:'"It\'s morning. Let\'s ___."',
    paragraph:'"It\'s morning. 1. Let\'s ___." (Workbook p.97)',
    options:[{text:'go to school',correct:true},{text:'eat lunch',correct:false},{text:'watch TV',correct:false},{text:'go to sleep',correct:false}],
    explanation:'In the morning, we go to school.',
    goldenRule:'Morning=school | Afternoon=lunch | Evening=watch TV',
    feedbackQuestion:{question:'"It\'s afternoon. Let\'s ___."',options:[{text:'eat lunch',correct:true},{text:'go to school',correct:false},{text:'watch TV',correct:false},{text:'go to sleep',correct:false}]}},

  { id:'u5l1q4', unit:'unit5', lesson:'u5l1', page:97, type:'classify', bloom:'analyze', difficulty:'medium',
    question:'Classify greetings by time of day:',
    paragraph:'"Good morning! Good afternoon! Good evening! Goodnight!" (Workbook p.97)',
    categories:['Morning / Daytime','Evening / Night'],
    items:[{text:'Good morning!',correct_category:0},{text:'Good evening!',correct_category:1},{text:'Good afternoon!',correct_category:0},{text:'Goodnight!',correct_category:1}],
    explanation:'Morning/Day: Good morning, Good afternoon. Evening/Night: Good evening, Goodnight.',
    goldenRule:'Greetings by time: morning → afternoon → evening → goodnight.'},

  { id:'u5l1q5', unit:'unit5', lesson:'u5l1', page:96, type:'trueFalse', bloom:'understand', difficulty:'easy',
    question:'"Nice to meet you" and "Nice to meet you too" are responses to an introduction.',
    paragraph:'"Nice to meet you Omar. — Nice to meet you too." (Workbook p.96)',
    correctAnswer:true, explanation:'"Nice to meet you" is said by the introduced person. "Too" is the reply.',
    goldenRule:'Introduction reply: "Nice to meet you!" → "Nice to meet you too!"',
    feedbackQuestion:{question:'Ali says "Nice to meet you, Nora." Nora replies:',options:[{text:'Nice to meet you too!',correct:true},{text:'Good morning!',correct:false},{text:'I\'m fine.',correct:false},{text:'Goodbye!',correct:false}]}},

  { id:'u5l1q6', unit:'unit5', lesson:'u5l1', page:97, type:'fillBlank', bloom:'apply', difficulty:'medium',
    question:'Complete: "It\'s so nice to see ___. Here\'s homework, more ___ for you!"',
    paragraph:'"Chant lyrics." (Workbook p.97)',
    blanks:['you','learning'], wordBank:['you','learning','me','playing'],
    explanation:'"It\'s so nice to see you. More learning for you!"',
    goldenRule:'Learning = studying and growing!'},

  { id:'u5l2q1', unit:'unit5', lesson:'u5l2', page:98, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'"We\'re playing" — "we\'re" is short for:',
    paragraph:'"We\'re playing, we\'re cycling." (Workbook p.98)',
    options:[{text:'we are',correct:true},{text:'we were',correct:false},{text:'we will',correct:false},{text:'we have',correct:false}],
    explanation:'"We\'re" = "we are". A contraction.',
    goldenRule:'I\'m=I am | He\'s=He is | We\'re=We are | They\'re=They are',
    feedbackQuestion:{question:'"They\'re cycling." "They\'re" means:',options:[{text:'They are',correct:true},{text:'They were',correct:false},{text:'They will',correct:false},{text:'Their',correct:false}]}},

  { id:'u5l2q2', unit:'unit5', lesson:'u5l2', page:98, type:'trueFalse', bloom:'apply', difficulty:'medium',
    question:'"He\'s not cycling" means he IS cycling.',
    paragraph:'"He\'s laughing; he\'s not cycling." (Workbook p.98)',
    correctAnswer:false, explanation:'"He\'s NOT cycling" = He is not cycling. "Not" makes it negative.',
    goldenRule:'Negative present continuous: He\'s NOT doing X = not doing it.',
    feedbackQuestion:{question:'"She\'s not watching TV." This means she:',options:[{text:'Is doing something else',correct:true},{text:'Is watching TV',correct:false},{text:'Likes TV',correct:false},{text:'Has a TV',correct:false}]}},

  { id:'u5l2q3', unit:'unit5', lesson:'u5l2', page:99, type:'multipleChoice', bloom:'apply', difficulty:'medium',
    question:'"Is he reading?" — (he is NOT reading). The correct answer:',
    paragraph:'"Is he reading? — No, he isn\'t." (Workbook p.99)',
    options:[{text:'No, he isn\'t.',correct:true},{text:'Yes, he is.',correct:false},{text:'He reading.',correct:false},{text:'He not read.',correct:false}],
    explanation:'"No, he isn\'t" = short negative answer.',
    goldenRule:'Is he ___-ing? → Yes, he is. / No, he isn\'t.',
    feedbackQuestion:{question:'"Is she watching TV?" (she IS watching). Answer:',options:[{text:'Yes, she is.',correct:true},{text:'No, she isn\'t.',correct:false},{text:'Yes, she isn\'t.',correct:false},{text:'No, she is.',correct:false}]}},

  { id:'u5l2q4', unit:'unit5', lesson:'u5l2', page:98, type:'matching', bloom:'understand', difficulty:'medium',
    question:'Match the subject with the correct present continuous form:',
    paragraph:'"We\'re playing. They\'re cycling. He\'s walking." (Workbook p.98)',
    pairs:[{left:'I',right:'I\'m walking'},{left:'He / She',right:'He\'s cycling'},{left:'We',right:'We\'re playing'},{left:'They',right:'They\'re laughing'}],
    explanation:'I am (I\'m), He/She is (He\'s), We are (We\'re), They are (They\'re) + verb-ing.',
    goldenRule:'Present continuous: I\'m | He/She\'s | We\'re | They\'re + verb-ing.'},

  { id:'u5l2q5', unit:'unit5', lesson:'u5l2', page:98, type:'classify', bloom:'analyze', difficulty:'medium',
    question:'Classify: Positive or Negative present continuous:',
    paragraph:'Present continuous affirmative and negative (Workbook p.98-99)',
    categories:['Positive (is doing)','Negative (is NOT doing)'],
    items:[{text:'He\'s walking.',correct_category:0},{text:'We\'re not playing.',correct_category:1},{text:'They\'re cycling.',correct_category:0},{text:'He\'s not cycling.',correct_category:1},{text:'She\'s sitting.',correct_category:0}],
    explanation:'Positive: walking/cycling/sitting. Negative: not playing/not cycling.',
    goldenRule:'Positive: is/are + -ing. Negative: is/are + NOT + -ing.'},

  { id:'u5l2q6', unit:'unit5', lesson:'u5l2', page:99, type:'fillBlank', bloom:'apply', difficulty:'medium',
    question:'"Is he ___? Yes, he ___." / "Is she playing? No, she ___."',
    paragraph:'"Is he sitting? Yes, he is. Is he playing? No, he isn\'t." (Workbook p.99)',
    blanks:['sitting','is','isn\'t'], wordBank:['sitting','is','isn\'t','playing'],
    explanation:'Is he sitting? Yes, he is. Is she playing? No, she isn\'t.',
    goldenRule:'Short answers: Yes, he is. / No, he isn\'t.'},

  { id:'u5l3q1', unit:'unit5', lesson:'u5l3', page:100, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'Which food adjective describes lemons?',
    paragraph:'"Lemons are sour. Apples are sweet." (Workbook p.100)',
    options:[{text:'sour',correct:true},{text:'sweet',correct:false},{text:'salty',correct:false},{text:'hot',correct:false}],
    explanation:'Lemons are sour — sharp, tart taste.',
    goldenRule:'sweet(apples) | sour(lemons) | salty(chips) | hot(soup) | cold(ice cream) | tasty(delicious)',
    feedbackQuestion:{question:'Chips are:',options:[{text:'salty',correct:true},{text:'sweet',correct:false},{text:'sour',correct:false},{text:'cold',correct:false}]}},

  { id:'u5l3q2', unit:'unit5', lesson:'u5l3', page:100, type:'matching', bloom:'remember', difficulty:'easy',
    question:'Match each food with its taste:',
    paragraph:'"Apples are sweet! Lemons are sour. Chips are salty." (Workbook p.100)',
    pairs:[{left:'apples',right:'sweet'},{left:'lemons',right:'sour'},{left:'chips',right:'salty'},{left:'ice cream',right:'cold'}],
    explanation:'apples=sweet, lemons=sour, chips=salty, ice cream=cold.',
    goldenRule:'Taste pairs: sweet/sour/salty/hot/cold/tasty describe food.'},

  { id:'u5l3q3', unit:'unit5', lesson:'u5l3', page:100, type:'classify', bloom:'analyze', difficulty:'medium',
    question:'Classify foods by main taste:',
    paragraph:'"Food adjectives: hot, cold, sour, sweet, salty, tasty." (Workbook p.100)',
    categories:['Sweet','Salty / Sour'],
    items:[{text:'apples',correct_category:0},{text:'chips',correct_category:1},{text:'cherries',correct_category:0},{text:'lemons',correct_category:1},{text:'cookies',correct_category:0}],
    explanation:'Sweet: apples, cherries, cookies. Salty: chips. Sour: lemons.',
    goldenRule:'Sweet: fruit, cookies. Salty: chips, popcorn. Sour: lemons.'},

  { id:'u5l3q4', unit:'unit5', lesson:'u5l3', page:101, type:'trueFalse', bloom:'apply', difficulty:'medium',
    question:'"cold, fruit, yellow, sour" — These clues all point to a lemon.',
    paragraph:'"Guessing game: Is it cold? yellow? sour? — It\'s a lemon!" (Workbook p.101)',
    correctAnswer:true, explanation:'Cold, fruit, yellow, sour → lemon! Clues point to lemon.',
    goldenRule:'Guess food using: color + temperature + taste = the food!',
    feedbackQuestion:{question:'"It\'s sweet, red, and small. It\'s a fruit." What is it?',options:[{text:'cherry',correct:true},{text:'lemon',correct:false},{text:'chip',correct:false},{text:'soup',correct:false}]}},

  { id:'u5l3q5', unit:'unit5', lesson:'u5l3', page:101, type:'multipleChoice', bloom:'apply', difficulty:'medium',
    question:'"No thanks. I don\'t like lemons. I like ___."',
    paragraph:'"I don\'t like lemons. I like oranges." (Workbook p.101)',
    options:[{text:'oranges',correct:true},{text:'lemons',correct:false},{text:'chips',correct:false},{text:'soup',correct:false}],
    explanation:'The person says they like oranges instead of lemons.',
    goldenRule:'"I like ___" / "I don\'t like ___." + food noun.',
    feedbackQuestion:{question:'"I ___ lemons. They are too sour."',options:[{text:'don\'t like',correct:true},{text:'like',correct:false},{text:'eat',correct:false},{text:'am',correct:false}]}},

  { id:'u5l3q6', unit:'unit5', lesson:'u5l3', page:100, type:'fillBlank', bloom:'apply', difficulty:'medium',
    question:'"Apples are ___! Lemons are ___. Chips are ___, And they\'re ___!"',
    paragraph:'Food chant lyrics (Workbook p.100)',
    blanks:['sweet','sour','salty','tasty'], wordBank:['sweet','sour','salty','tasty'],
    explanation:'apples=sweet, lemons=sour, chips=salty+tasty.',
    goldenRule:'Food taste words: sweet, sour, salty, hot, cold, tasty.'},

  { id:'u5l4q1', unit:'unit5', lesson:'u5l4', page:102, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'The plural of "apple" ends with which sound?',
    paragraph:'"apples — /s/ or /z/ or /ɪz/?" (Workbook p.102)',
    options:[{text:'/z/',correct:true},{text:'/s/',correct:false},{text:'/ɪz/',correct:false},{text:'/d/',correct:false}],
    explanation:'"apples" ends with /z/ sound.',
    goldenRule:'-s endings: /s/ (books,cats) | /z/ (apples,pens) | /ɪz/ (buses,glasses)',
    feedbackQuestion:{question:'Which ending sound does "glasses" have?',options:[{text:'/ɪz/',correct:true},{text:'/s/',correct:false},{text:'/z/',correct:false},{text:'/t/',correct:false}]}},

  { id:'u5l4q2', unit:'unit5', lesson:'u5l4', page:103, type:'multipleChoice', bloom:'apply', difficulty:'medium',
    question:'"Whose skirt is this?" — It belongs to Noura. Answer:',
    paragraph:'"Whose skirt is this? It\'s Noura\'s." (Workbook p.103)',
    options:[{text:'It\'s Noura\'s.',correct:true},{text:'It\'s Noura.',correct:false},{text:'It\'s mine.',correct:false},{text:'Noura has a skirt.',correct:false}],
    explanation:'"Noura\'s" uses possessive apostrophe -\'s.',
    goldenRule:'Possessive \'s: Noura\'s = belonging to Noura.',
    feedbackQuestion:{question:'"Whose cap is this?" — It belongs to Faisal:',options:[{text:'It\'s Faisal\'s.',correct:true},{text:'It\'s Faisal.',correct:false},{text:'It\'s mine.',correct:false},{text:'Faisal has a cap.',correct:false}]}},

  { id:'u5l4q3', unit:'unit5', lesson:'u5l4', page:102, type:'trueFalse', bloom:'understand', difficulty:'easy',
    question:'"Do you have a pen?" — "Yes, I do." means the person has a pen.',
    paragraph:'"Do you have a pen? Yes, I do." (Workbook p.102)',
    correctAnswer:true, explanation:'"Yes, I do" = affirmative short answer.',
    goldenRule:'Do you have ___? → Yes, I do. (have it) / No, I don\'t. (don\'t have it)',
    feedbackQuestion:{question:'"Do you have cookies?" (you DON\'T). Answer:',options:[{text:'No, I don\'t.',correct:true},{text:'Yes, I do.',correct:false},{text:'I have cookies.',correct:false},{text:'No, I not.',correct:false}]}},

  { id:'u5l4q4', unit:'unit5', lesson:'u5l4', page:103, type:'matching', bloom:'apply', difficulty:'medium',
    question:'Match the clothing item to its owner:',
    paragraph:'"Whose skirt is this? It\'s Noura\'s." (Workbook p.103)',
    pairs:[{left:'skirt',right:'Noura\'s'},{left:'T-shirt',right:'Faisal\'s'},{left:'blouse',right:'Noura\'s'},{left:'cap',right:'Faisal\'s'}],
    explanation:'Noura: skirt, blouse, dress. Faisal: T-shirt, sweater, cap.',
    goldenRule:'Use \'s to show ownership: item + is + owner\'s.'},

  { id:'u5l4q5', unit:'unit5', lesson:'u5l4', page:102, type:'classify', bloom:'analyze', difficulty:'hard',
    question:'Classify plural words by -s ending sound:',
    paragraph:'"Listen and check /s/ /z/ /ɪz/." (Workbook p.102)',
    categories:['/s/ sound','/z/ sound','/ɪz/ sound'],
    items:[{text:'books',correct_category:0},{text:'apples',correct_category:1},{text:'buses',correct_category:2},{text:'cats',correct_category:0},{text:'pens',correct_category:1}],
    explanation:'/s/: books, cats. /z/: apples, pens. /ɪz/: buses.',
    goldenRule:'-s sounds: /s/ after p,t,k,f | /z/ after vowels/voiced | /ɪz/ after s,z,sh,ch'},

  { id:'u5l4q6', unit:'unit5', lesson:'u5l4', page:103, type:'fillBlank', bloom:'apply', difficulty:'medium',
    question:'Complete: "Whose ___ is this? It\'s ___\'s."',
    paragraph:'"Whose skirt is this? It\'s Noura\'s." (Workbook p.103)',
    blanks:['skirt','Noura'], wordBank:['skirt','Noura','T-shirt','Faisal'],
    explanation:'Whose SKIRT is this? It\'s NOURA\'s.',
    goldenRule:'Possessive: Whose ___? → It\'s [name]\'s.'},
];

export const QUESTIONS_UNITS_3_5 = [...unit3Questions, ...unit4Questions, ...unit5Questions];