// We Can! 2 - Grade 2 English - Term 1 - Units 1-2 Question Bank

export const META = {
  title: 'بنك أسئلة We Can! 2',
  subject: 'اللغة الإنجليزية',
  grade: 'الصف الثاني الابتدائي',
  term: 'الفصل الأول',
  publisher: 'وزارة التعليم - المملكة العربية السعودية',
  book: 'We Can! Student\'s Book 2 - McGraw Hill 2025',
};

export const UNITS = [
  {
    id: 'unit1', title: 'Unit 1: Feelings', titleAr: 'الوحدة الأولى: المشاعر',
    color: '#e91e8c', icon: '😊', pages: '6-14',
    lessons: [
      { id: 'u1l1', title: 'Goal 1-2: Greetings & Ordinal Numbers', page: 64, unitId: 'unit1' },
      { id: 'u1l2', title: 'Goal 3-4: Happy Chant & Alphabet', page: 66, unitId: 'unit1' },
      { id: 'u1l3', title: 'Goal 5-6: Feeling Words', page: 68, unitId: 'unit1' },
      { id: 'u1l4', title: 'Goal 7-8: Phonics a/a_e, i/i_e', page: 70, unitId: 'unit1' },
    ],
  },
  {
    id: 'unit2', title: 'Unit 2: Things We Wear', titleAr: 'الوحدة الثانية: الملابس',
    color: '#0891b2', icon: '👕', pages: '15-20',
    lessons: [
      { id: 'u2l1', title: 'Goal 9-10: Whose is this? / I like your...', page: 72, unitId: 'unit2' },
      { id: 'u2l2', title: 'Goal 11-12: Colors & Chants', page: 74, unitId: 'unit2' },
      { id: 'u2l3', title: 'Goal 13-14: Clothes Vocabulary', page: 76, unitId: 'unit2' },
      { id: 'u2l4', title: 'Goal 15-16: Phonics p & b', page: 78, unitId: 'unit2' },
    ],
  },
  {
    id: 'unit3', title: 'Unit 3: Things We Do', titleAr: 'الوحدة الثالثة: الأفعال اليومية',
    color: '#059669', icon: '⚽', pages: '21-28',
    lessons: [
      { id: 'u3l1', title: 'Goal 17-18: Telephone Conversations', page: 80, unitId: 'unit3' },
      { id: 'u3l2', title: 'Goal 19-20: What are you doing?', page: 82, unitId: 'unit3' },
      { id: 'u3l3', title: 'Goal 21-22: Action Vocabulary', page: 84, unitId: 'unit3' },
      { id: 'u3l4', title: 'Goal 23-24: Phonics t & d', page: 86, unitId: 'unit3' },
    ],
  },
  {
    id: 'unit4', title: 'Unit 4: Beautiful Nature', titleAr: 'الوحدة الرابعة: الطبيعة الجميلة',
    color: '#d97706', icon: '🌿', pages: '29-36',
    lessons: [
      { id: 'u4l1', title: 'Goal 25-26: Beautiful & Ugly', page: 88, unitId: 'unit4' },
      { id: 'u4l2', title: 'Goal 27-28: Mountains / Seasons', page: 90, unitId: 'unit4' },
      { id: 'u4l3', title: 'Goal 29-30: Opposites', page: 92, unitId: 'unit4' },
      { id: 'u4l4', title: 'Goal 31-32: Phonics c & g', page: 94, unitId: 'unit4' },
    ],
  },
  {
    id: 'unit5', title: 'Unit 5: Friends, Actions, Things', titleAr: 'الوحدة الخامسة: الأصدقاء والأفعال',
    color: '#7c3aed', icon: '🤝', pages: '37-44',
    lessons: [
      { id: 'u5l1', title: 'Goal 33-34: Introductions & Time of Day', page: 96, unitId: 'unit5' },
      { id: 'u5l2', title: 'Goal 35-36: Present Continuous', page: 98, unitId: 'unit5' },
      { id: 'u5l3', title: 'Goal 37-38: Food Adjectives', page: 100, unitId: 'unit5' },
      { id: 'u5l4', title: 'Goal 39-40: Phonics -s & Possessives', page: 102, unitId: 'unit5' },
    ],
  },
];

export const BLOOM_LABELS = {
  remember: 'تذكُّر', understand: 'فهم', apply: 'تطبيق',
  analyze: 'تحليل', create: 'تركيب', evaluate: 'تقويم',
};

export const DIFFICULTY_LABELS = { easy: 'سهل', medium: 'متوسط', hard: 'صعب' };

const unit1Questions = [
  // Lesson 1: Greetings & Ordinals
  { id:'u1l1q1', unit:'unit1', lesson:'u1l1', page:64, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'When you meet your teacher in the morning, you say:', paragraph:'"Hello! A — How are you? I\'m great, thanks." (Workbook p.64)',
    options:[{text:'Good morning!',correct:true},{text:'Good night!',correct:false},{text:'Good evening!',correct:false},{text:'Goodbye!',correct:false}],
    explanation:'We say "Good morning!" when we meet someone in the morning.',
    goldenRule:'Morning = Good morning | Afternoon = Good afternoon | Evening = Good evening',
    feedbackQuestion:{question:'At 3 PM you meet your friend. You say:',options:[{text:'Good afternoon!',correct:true},{text:'Good morning!',correct:false},{text:'Goodnight!',correct:false},{text:'Hello morning!',correct:false}]}},

  { id:'u1l1q2', unit:'unit1', lesson:'u1l1', page:64, type:'trueFalse', bloom:'understand', difficulty:'easy',
    question:'"How are you?" is used to ask about someone\'s feelings.', paragraph:'"How are you? I\'m great, thanks." (Workbook p.64)',
    correctAnswer:true, explanation:'Yes! "How are you?" asks how someone feels.',
    goldenRule:'Use "How are you?" to ask about feelings. Answer with "I\'m fine / great / good."',
    feedbackQuestion:{question:'The correct answer to "How are you?" is:',options:[{text:'I\'m fine, thanks.',correct:true},{text:'I\'m Ahmed.',correct:false},{text:'Yes, I am.',correct:false},{text:'My name is Ali.',correct:false}]}},

  { id:'u1l1q3', unit:'unit1', lesson:'u1l1', page:65, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'The student who comes to class first is called:', paragraph:'"I\'m first." (Workbook p.65)',
    options:[{text:'first',correct:true},{text:'second',correct:false},{text:'third',correct:false},{text:'fourth',correct:false}],
    explanation:'"First" (1st) means the number one position.',
    goldenRule:'1st=first | 2nd=second | 3rd=third | 4th=fourth | 5th=fifth',
    feedbackQuestion:{question:'The student who comes 2nd is:',options:[{text:'second',correct:true},{text:'first',correct:false},{text:'third',correct:false},{text:'fourth',correct:false}]}},

  { id:'u1l1q4', unit:'unit1', lesson:'u1l1', page:65, type:'ordering', bloom:'understand', difficulty:'medium',
    question:'Put these ordinal numbers in the correct order (1st to 5th):',
    paragraph:'Ordinal numbers (Workbook p.65)',
    items:['third','first','fifth','second','fourth'], correctOrder:[1,3,0,4,2],
    explanation:'first → second → third → fourth → fifth',
    goldenRule:'Ordinals show position: 1st first, 2nd second, 3rd third, 4th fourth, 5th fifth.'},

  { id:'u1l1q5', unit:'unit1', lesson:'u1l1', page:65, type:'matching', bloom:'remember', difficulty:'easy',
    question:'Match the number with the ordinal word:',
    paragraph:'Goal 2: ordinal numbers (Workbook p.65)',
    pairs:[{left:'1st',right:'first'},{left:'2nd',right:'second'},{left:'3rd',right:'third'},{left:'4th',right:'fourth'}],
    explanation:'1st=first, 2nd=second, 3rd=third, 4th=fourth.',
    goldenRule:'Add -st to 1, -nd to 2, -rd to 3, -th to 4+.'},

  { id:'u1l1q6', unit:'unit1', lesson:'u1l1', page:65, type:'fillBlank', bloom:'apply', difficulty:'medium',
    question:'Fill in the blanks: "I\'m ___ ." and "I\'m ___ ."',
    paragraph:'"Match and write the ordinals." (Workbook p.65)',
    blanks:['fifth','second'], wordBank:['second','fifth','third','first'],
    explanation:'5th person says "I\'m fifth", 2nd person says "I\'m second".',
    goldenRule:'Ordinals tell us position or order.'},

  // Lesson 2: Happy Chant & Alphabet  
  { id:'u1l2q1', unit:'unit1', lesson:'u1l2', page:66, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'In "If You\'re Happy and You Know It", what do you do?',
    paragraph:'"Clap your hands." (Workbook p.66)',
    options:[{text:'Clap your hands',correct:true},{text:'Jump up high',correct:false},{text:'Touch your nose',correct:false},{text:'Stamp your feet',correct:false}],
    explanation:'"Clap your hands!" — a TPR action song.',
    goldenRule:'Happy → Clap your hands!',
    feedbackQuestion:{question:'What does "clap" mean?',options:[{text:'Hit your hands together',correct:true},{text:'Jump up',correct:false},{text:'Sit down',correct:false},{text:'Run fast',correct:false}]}},

  { id:'u1l2q2', unit:'unit1', lesson:'u1l2', page:66, type:'trueFalse', bloom:'understand', difficulty:'easy',
    question:'"Then your face will surely show it" means happy people smile.',
    paragraph:'"Then your face will surely show it." (Workbook p.66)',
    correctAnswer:true, explanation:'When you are happy, your face shows it — you smile!',
    goldenRule:'Our face shows feelings. Smiling = happy!',
    feedbackQuestion:{question:'Which face shows happiness?',options:[{text:'😊 Smiling',correct:true},{text:'😢 Crying',correct:false},{text:'😠 Angry',correct:false},{text:'😴 Sleeping',correct:false}]}},

  { id:'u1l2q3', unit:'unit1', lesson:'u1l2', page:67, type:'multipleChoice', bloom:'remember', difficulty:'medium',
    question:'"e" is which letter of the English alphabet?',
    paragraph:'"e is the ___ letter of the alphabet." (Workbook p.67)',
    options:[{text:'fifth',correct:true},{text:'fourth',correct:false},{text:'sixth',correct:false},{text:'third',correct:false}],
    explanation:'a(1), b(2), c(3), d(4), e(5). So "e" is the fifth letter.',
    goldenRule:'a=1st, b=2nd, c=3rd, d=4th, e=5th, f=6th, g=7th, h=8th...',
    feedbackQuestion:{question:'"h" is which letter?',options:[{text:'eighth',correct:true},{text:'seventh',correct:false},{text:'sixth',correct:false},{text:'ninth',correct:false}]}},

  { id:'u1l2q4', unit:'unit1', lesson:'u1l2', page:67, type:'ordering', bloom:'remember', difficulty:'medium',
    question:'Order these ordinals from smallest to largest:',
    paragraph:'Ordinals 6-10 (Workbook p.67)',
    items:['tenth','sixth','eighth','seventh','ninth'], correctOrder:[1,3,2,4,0],
    explanation:'sixth(6) → seventh(7) → eighth(8) → ninth(9) → tenth(10)',
    goldenRule:'Ordinals 6-10: sixth, seventh, eighth, ninth, tenth.'},

  { id:'u1l2q5', unit:'unit1', lesson:'u1l2', page:67, type:'matching', bloom:'remember', difficulty:'easy',
    question:'Match each ordinal with its number:',
    paragraph:'Confusion Game ordinal numbers (Workbook p.67)',
    pairs:[{left:'6th',right:'sixth'},{left:'7th',right:'seventh'},{left:'8th',right:'eighth'},{left:'10th',right:'tenth'}],
    explanation:'6th=sixth, 7th=seventh, 8th=eighth, 10th=tenth.',
    goldenRule:'Add -th: six+th, seven+th, eight+h, ten+th.'},

  { id:'u1l2q6', unit:'unit1', lesson:'u1l2', page:67, type:'classify', bloom:'analyze', difficulty:'hard',
    question:'Classify: "1st–5th" or "6th–10th":',
    paragraph:'Ordinal numbers from Confusion Game (Workbook p.67)',
    categories:['1st – 5th','6th – 10th'],
    items:[{text:'first',correct_category:0},{text:'seventh',correct_category:1},{text:'third',correct_category:0},{text:'ninth',correct_category:1},{text:'fifth',correct_category:0},{text:'sixth',correct_category:1}],
    explanation:'first/third/fifth = 1–5; sixth/seventh/ninth = 6–10.',
    goldenRule:'1-5: first, second, third, fourth, fifth. 6-10: sixth, seventh, eighth, ninth, tenth.'},

  // Lesson 3: Feeling Words
  { id:'u1l3q1', unit:'unit1', lesson:'u1l3', page:68, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'When you want something to eat, you feel:',
    paragraph:'"I\'m hungry." (Workbook p.68)',
    options:[{text:'hungry',correct:true},{text:'sleepy',correct:false},{text:'cold',correct:false},{text:'scared',correct:false}],
    explanation:'"Hungry" means you need food.',
    goldenRule:'hungry=want food | thirsty=want water | sleepy=want sleep',
    feedbackQuestion:{question:'When you want water, you feel:',options:[{text:'thirsty',correct:true},{text:'hungry',correct:false},{text:'cold',correct:false},{text:'hot',correct:false}]}},

  { id:'u1l3q2', unit:'unit1', lesson:'u1l3', page:68, type:'matching', bloom:'understand', difficulty:'easy',
    question:'Match each feeling with the correct situation:',
    paragraph:'"I\'m hungry / thirsty / hot / cold / sleepy / scared." (Workbook p.68)',
    pairs:[{left:'It\'s 40°C outside.',right:'hot'},{left:'It\'s night and you\'re tired.',right:'sleepy'},{left:'You see a snake!',right:'scared'},{left:'You\'re in the snow.',right:'cold'}],
    explanation:'hot=high temp, sleepy=tired, scared=afraid, cold=low temp.',
    goldenRule:'Match situation to feeling: hot/cold=temperature | hungry/thirsty=need | sleepy=tired | scared=afraid'},

  { id:'u1l3q3', unit:'unit1', lesson:'u1l3', page:68, type:'classify', bloom:'analyze', difficulty:'medium',
    question:'Classify: temperature feelings OR need feelings:',
    paragraph:'Feeling words Goal 5 (Workbook p.68)',
    categories:['Temperature Feelings','Need Feelings'],
    items:[{text:'hot',correct_category:0},{text:'hungry',correct_category:1},{text:'cold',correct_category:0},{text:'thirsty',correct_category:1},{text:'sleepy',correct_category:1}],
    explanation:'Temperature: hot, cold. Need: hungry, thirsty, sleepy.',
    goldenRule:'Hot/cold = temperature. Hungry/thirsty/sleepy = needs.'},

  { id:'u1l3q4', unit:'unit1', lesson:'u1l3', page:69, type:'trueFalse', bloom:'understand', difficulty:'easy',
    question:'"What\'s the matter?" is used to ask about someone\'s problem.',
    paragraph:'"A: What\'s the matter? B: I\'m hungry." (Workbook p.69)',
    correctAnswer:true, explanation:'"What\'s the matter?" means "What is wrong?"',
    goldenRule:'Use "What\'s the matter?" to ask about a problem. Answer: "I\'m + feeling."',
    feedbackQuestion:{question:'Correct response to "What\'s the matter?":',options:[{text:'I\'m cold.',correct:true},{text:'Fine, thank you.',correct:false},{text:'Nice to meet you.',correct:false},{text:'Good morning.',correct:false}]}},

  { id:'u1l3q5', unit:'unit1', lesson:'u1l3', page:69, type:'fillBlank', bloom:'apply', difficulty:'medium',
    question:'Unscramble: "l o c d = ___", "r n h g u y = ___"',
    paragraph:'Unscramble words (Workbook p.69)',
    blanks:['cold','hungry'], wordBank:['cold','hungry','hot','sleepy'],
    explanation:'locd=cold | rnhguy=hungry.',
    goldenRule:'Feeling words: cold, hot, hungry, thirsty, sleepy, scared.'},

  { id:'u1l3q6', unit:'unit1', lesson:'u1l3', page:68, type:'audio', bloom:'remember', difficulty:'easy',
    question:'Choose the word that means "very tired and wanting to rest":',
    paragraph:'"I\'m sleepy." (Workbook p.68)',
    options:[{text:'sleepy',correct:true},{text:'scared',correct:false},{text:'hungry',correct:false},{text:'thirsty',correct:false}],
    audioWord:'sleepy', explanation:'"Sleepy" = tired and want to sleep.',
    goldenRule:'sleepy = tired and want to sleep.',
    feedbackQuestion:{question:'Which action shows you are sleepy?',options:[{text:'Yawning and closing eyes',correct:true},{text:'Running fast',correct:false},{text:'Eating food',correct:false},{text:'Jumping high',correct:false}]}},

  // Lesson 4: Phonics
  { id:'u1l4q1', unit:'unit1', lesson:'u1l4', page:70, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'The word "apple" starts with the sound:',
    paragraph:'"a" sounds — apple(short a), apron(long a). (Workbook p.70)',
    options:[{text:'short a (as in apple)',correct:true},{text:'long a (as in apron)',correct:false},{text:'long i (as in time)',correct:false},{text:'short i (as in pin)',correct:false}],
    explanation:'"Apple" has the short "a" sound /æ/. "Apron" has the long "a" sound /eɪ/.',
    goldenRule:'Short a (apple, cat, tap) vs Long a_e (apron, cape, tape)',
    feedbackQuestion:{question:'Which word has the LONG "a" sound?',options:[{text:'cape',correct:true},{text:'cap',correct:false},{text:'cat',correct:false},{text:'can',correct:false}]}},

  { id:'u1l4q2', unit:'unit1', lesson:'u1l4', page:51, type:'classify', bloom:'analyze', difficulty:'medium',
    question:'Classify: Short "a" sound OR Long "a_e" sound:',
    paragraph:'Words with a and a_e (Student Book p.51)',
    categories:['Short a (cat)','Long a_e (cake)'],
    items:[{text:'tap',correct_category:0},{text:'tape',correct_category:1},{text:'cap',correct_category:0},{text:'cape',correct_category:1},{text:'hat',correct_category:0},{text:'cake',correct_category:1}],
    explanation:'Short a: tap, cap, hat. Long a_e: tape, cape, cake.',
    goldenRule:'Magic e rule: tap → tape. Adding silent "e" makes the vowel say its name!'},

  { id:'u1l4q3', unit:'unit1', lesson:'u1l4', page:51, type:'multipleChoice', bloom:'apply', difficulty:'medium',
    question:'Look at a picture of a snake. The correct word is:',
    paragraph:'"Circle the right word: snak / snake / sack / shake" (Student Book p.51)',
    options:[{text:'snake',correct:true},{text:'snak',correct:false},{text:'sack',correct:false},{text:'shake',correct:false}],
    explanation:'"Snake" has the long a_e pattern. Magic e makes the "a" say its name.',
    goldenRule:'Long a_e: snake, cake, tape, cape, vase.',
    feedbackQuestion:{question:'Which word has the same vowel sound as "snake"?',options:[{text:'cake',correct:true},{text:'back',correct:false},{text:'bat',correct:false},{text:'sat',correct:false}]}},

  { id:'u1l4q4', unit:'unit1', lesson:'u1l4', page:51, type:'trueFalse', bloom:'understand', difficulty:'medium',
    question:'"Tim" and "time" have the same vowel sound.',
    paragraph:'"i / i_e: Tim / time." (Student Book p.51)',
    correctAnswer:false, explanation:'"Tim" = short i /ɪ/. "Time" = long i_e /aɪ/. Different sounds!',
    goldenRule:'Short i: Tim, pin, ink. Long i_e: time, pine. Magic "e" changes the sound!',
    feedbackQuestion:{question:'Which pair has the SAME vowel sound?',options:[{text:'pin / bin',correct:true},{text:'pin / pine',correct:false},{text:'time / Tim',correct:false},{text:'tape / tap',correct:false}]}},

  { id:'u1l4q5', unit:'unit1', lesson:'u1l4', page:70, type:'matching', bloom:'remember', difficulty:'easy',
    question:'Match each word with its vowel type:',
    paragraph:'Vowel sounds (Student Book p.50)',
    pairs:[{left:'apple',right:'short a'},{left:'apron',right:'long a'},{left:'ink',right:'short i'},{left:'ice cream',right:'long i'}],
    explanation:'apple=short a, apron=long a, ink=short i, ice cream=long i.',
    goldenRule:'Short vowels: apple, egg, ink. Long vowels: apron, ice, open.'},

  { id:'u1l4q6', unit:'unit1', lesson:'u1l4', page:70, type:'fillBlank', bloom:'apply', difficulty:'medium',
    question:'Fill in: c___p (hat for your head), c___pe (superhero\'s cloak)',
    paragraph:'"Write the missing letters." (Workbook p.70)',
    blanks:['a','a'],
    wordBank:['a','a','i','e'],
    explanation:'cap (short a) = hat. cape (long a_e) = cloak.',
    goldenRule:'cap vs cape — same letters but magic e changes the vowel sound and meaning!'},
];

const unit2Questions = [
  { id:'u2l1q1', unit:'unit2', lesson:'u2l1', page:72, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'To ask who something belongs to, you say:',
    paragraph:'"Whose ___ is this?" (Workbook p.72)',
    options:[{text:'Whose',correct:true},{text:'What',correct:false},{text:'Where',correct:false},{text:'Who',correct:false}],
    explanation:'"Whose" is the question word for possession.',
    goldenRule:'Whose = belonging to who? Answer: It\'s mine. / It\'s not mine.',
    feedbackQuestion:{question:'"___ hat is this?" Fill in:',options:[{text:'Whose',correct:true},{text:'What',correct:false},{text:'When',correct:false},{text:'How',correct:false}]}},

  { id:'u2l1q2', unit:'unit2', lesson:'u2l1', page:72, type:'trueFalse', bloom:'understand', difficulty:'easy',
    question:'"It\'s mine" means the thing belongs to you.',
    paragraph:'"Whose hat is this? It\'s mine." (Workbook p.72)',
    correctAnswer:true, explanation:'"Mine" = belonging to me.',
    goldenRule:'"mine"=belonging to me | "yours"=to you | "his/hers"=to him/her',
    feedbackQuestion:{question:'If the bag belongs to Sara, you say:',options:[{text:'It\'s hers.',correct:true},{text:'It\'s mine.',correct:false},{text:'It\'s his.',correct:false},{text:'It\'s yours.',correct:false}]}},

  { id:'u2l1q3', unit:'unit2', lesson:'u2l1', page:73, type:'multipleChoice', bloom:'apply', difficulty:'medium',
    question:'Someone is wearing a nice hat. You say:',
    paragraph:'"I like your hat." (Workbook p.73)',
    options:[{text:'I like your hat!',correct:true},{text:'I have your hat!',correct:false},{text:'What hat?',correct:false},{text:'It\'s my hat.',correct:false}],
    explanation:'"I like your ___" is used to give a compliment.',
    goldenRule:'Compliment: "I like your ___!" Response: "Thank you!"',
    feedbackQuestion:{question:'Someone says "I like your T-shirt!" You respond:',options:[{text:'Thank you!',correct:true},{text:'It\'s mine.',correct:false},{text:'Goodbye.',correct:false},{text:'I\'m fine.',correct:false}]}},

  { id:'u2l1q4', unit:'unit2', lesson:'u2l1', page:72, type:'matching', bloom:'understand', difficulty:'easy',
    question:'Match each animal with its food:',
    paragraph:'"Draw lines and match." (Workbook p.72)',
    pairs:[{left:'mouse',right:'cheese'},{left:'squirrel',right:'acorn'},{left:'boy',right:'candy'}],
    explanation:'mouse=cheese, squirrel=acorn, boy=candy.',
    goldenRule:'Matching: connect each animal/person with what belongs to them.'},

  { id:'u2l1q5', unit:'unit2', lesson:'u2l1', page:73, type:'trueFalse', bloom:'understand', difficulty:'easy',
    question:'"It\'s not mine" means the thing belongs to someone else.',
    paragraph:'"It\'s my hat. / It\'s not mine." (Workbook p.73)',
    correctAnswer:true, explanation:'"It\'s not mine" = "This does not belong to me."',
    goldenRule:'"It\'s mine"=belongs to me. "It\'s not mine"=doesn\'t belong to me.',
    feedbackQuestion:{question:'Ali says "It\'s not mine." This means:',options:[{text:'It belongs to someone else.',correct:true},{text:'The bag is his.',correct:false},{text:'He likes it.',correct:false},{text:'It is new.',correct:false}]}},

  { id:'u2l1q6', unit:'unit2', lesson:'u2l1', page:72, type:'fillBlank', bloom:'apply', difficulty:'medium',
    question:'Complete: "Whose ___ is this? It\'s ___."',
    paragraph:'"Whose hat is this? It\'s mine." (Workbook p.72)',
    blanks:['hat','mine'], wordBank:['hat','mine','bag','yours'],
    explanation:'Whose HAT is this? It\'s MINE.',
    goldenRule:'"Whose + noun + is this?" → "It\'s mine/yours/his/hers."'},

  { id:'u2l2q1', unit:'unit2', lesson:'u2l2', page:74, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'In "Who is Wearing Green?" chant, what color is the person wearing?',
    paragraph:'"Who is wearing green today?" (Workbook p.74)',
    options:[{text:'green',correct:true},{text:'blue',correct:false},{text:'red',correct:false},{text:'yellow',correct:false}],
    explanation:'The chant is about wearing green.',
    goldenRule:'"I am wearing green." — Use "wearing" for clothes.',
    feedbackQuestion:{question:'"I am ___ green today." Fill in:',options:[{text:'wearing',correct:true},{text:'putting',correct:false},{text:'having',correct:false},{text:'doing',correct:false}]}},

  { id:'u2l2q2', unit:'unit2', lesson:'u2l2', page:74, type:'trueFalse', bloom:'apply', difficulty:'easy',
    question:'"yellow T-shirt, blue pants, brown jacket, red cap" — the T-shirt is blue.',
    paragraph:'"He is wearing a yellow T-shirt, blue pants, and a brown jacket." (Workbook p.74)',
    correctAnswer:false, explanation:'The T-shirt is YELLOW. Blue = pants.',
    goldenRule:'Read carefully! Each clothing item has a different color.',
    feedbackQuestion:{question:'"yellow T-shirt, blue pants, brown jacket, red cap" — what color is the jacket?',options:[{text:'brown',correct:true},{text:'blue',correct:false},{text:'yellow',correct:false},{text:'red',correct:false}]}},

  { id:'u2l2q3', unit:'unit2', lesson:'u2l2', page:75, type:'classify', bloom:'analyze', difficulty:'medium',
    question:'Classify into "warm" or "cool" colors:',
    paragraph:'Colors: purple, red, pink, white, black, blue (Workbook p.75)',
    categories:['Warm Colors','Cool Colors'],
    items:[{text:'red',correct_category:0},{text:'blue',correct_category:1},{text:'pink',correct_category:0},{text:'purple',correct_category:1},{text:'white',correct_category:1}],
    explanation:'Warm: red, pink. Cool: blue, purple, white.',
    goldenRule:'Warm colors: red, orange, yellow, pink. Cool colors: blue, green, purple.'},

  { id:'u2l2q4', unit:'unit2', lesson:'u2l2', page:74, type:'multipleChoice', bloom:'apply', difficulty:'medium',
    question:'Complete: "That ___ wearing green today."',
    paragraph:'"That I am wearing green today." (Workbook p.74)',
    options:[{text:'I am',correct:true},{text:'he is',correct:false},{text:'you are',correct:false},{text:'they are',correct:false}],
    explanation:'The chant uses "I am wearing" — first person singular present continuous.',
    goldenRule:'I am wearing (I\'m wearing) = talking about yourself right now.',
    feedbackQuestion:{question:'"She ___ a blue dress." Fill in:',options:[{text:'is wearing',correct:true},{text:'am wearing',correct:false},{text:'are wearing',correct:false},{text:'wearing',correct:false}]}},

  { id:'u2l2q5', unit:'unit2', lesson:'u2l2', page:75, type:'fillBlank', bloom:'apply', difficulty:'medium',
    question:'Complete: "I\'m wearing ___ and ___ today."',
    paragraph:'"Write two things you are wearing today." (Workbook p.75)',
    blanks:['blue','a shirt'], wordBank:['blue','a shirt','a hat','red'],
    explanation:'Color + clothing: "I\'m wearing blue. I\'m wearing a shirt today."',
    goldenRule:'Color + clothing = description of what you wear.'},

  { id:'u2l2q6', unit:'unit2', lesson:'u2l2', page:74, type:'trueFalse', bloom:'understand', difficulty:'easy',
    question:'"Look at me, and you will see" — this phrase invites someone to look at you.',
    paragraph:'"Look at me, And you will see, That I am wearing green today." (Workbook p.74)',
    correctAnswer:true, explanation:'"Look at me" = pay attention to me. It\'s an invitation to look.',
    goldenRule:'"Look at me" = a command/invitation to look. Very useful in songs and conversations!'},

  { id:'u2l3q1', unit:'unit2', lesson:'u2l3', page:76, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'Which of these is worn on your head?',
    paragraph:'"a cap, a T-shirt, a jacket, a hat..." (Workbook p.76)',
    options:[{text:'cap',correct:true},{text:'shoes',correct:false},{text:'jeans',correct:false},{text:'blouse',correct:false}],
    explanation:'A "cap" is worn on your head.',
    goldenRule:'Head: cap, hat | Body: T-shirt, blouse, jacket | Legs: jeans, skirt | Feet: shoes, sandals',
    feedbackQuestion:{question:'Which clothing item goes on your feet?',options:[{text:'shoes',correct:true},{text:'cap',correct:false},{text:'jacket',correct:false},{text:'blouse',correct:false}]}},

  { id:'u2l3q2', unit:'unit2', lesson:'u2l3', page:76, type:'classify', bloom:'analyze', difficulty:'medium',
    question:'Classify clothes by where you wear them:',
    paragraph:'"cap, T-shirt, jacket, blouse, sweater, jeans, skirt, shoes, sunglasses." (Workbook p.76)',
    categories:['Upper Body','Lower Body / Feet','Head / Face'],
    items:[{text:'T-shirt',correct_category:0},{text:'jeans',correct_category:1},{text:'cap',correct_category:2},{text:'shoes',correct_category:1},{text:'blouse',correct_category:0},{text:'sunglasses',correct_category:2}],
    explanation:'Upper: T-shirt, blouse. Lower/Feet: jeans, shoes. Head/Face: cap, sunglasses.',
    goldenRule:'Clothes go on different body parts. Sort by location!'},

  { id:'u2l3q3', unit:'unit2', lesson:'u2l3', page:77, type:'multipleChoice', bloom:'apply', difficulty:'medium',
    question:'"My friend is wearing ___ and ___ today."',
    paragraph:'"Write two things your friend is wearing today." (Workbook p.77)',
    options:[{text:'a jacket and jeans',correct:true},{text:'happy and cold',correct:false},{text:'eating and running',correct:false},{text:'good and fine',correct:false}],
    explanation:'You wear clothes — not feelings or actions!',
    goldenRule:'"Wearing" is followed by a clothing item.',
    feedbackQuestion:{question:'Which sentence is correct?',options:[{text:'She is wearing a red skirt.',correct:true},{text:'She is wearing hungry.',correct:false},{text:'She is wearing playing.',correct:false},{text:'She wearing a skirt.',correct:false}]}},

  { id:'u2l3q4', unit:'unit2', lesson:'u2l3', page:76, type:'trueFalse', bloom:'understand', difficulty:'easy',
    question:'"Sunglasses" is a clothing item you wear on your eyes.',
    paragraph:'"sunglasses" in clothes vocabulary (Workbook p.76)',
    correctAnswer:true, explanation:'Sunglasses protect your eyes from the sun.',
    goldenRule:'Sunglasses = eyewear. Worn on/around your eyes.',
    feedbackQuestion:{question:'Where do you wear sunglasses?',options:[{text:'On your eyes/face',correct:true},{text:'On your head',correct:false},{text:'On your feet',correct:false},{text:'On your hands',correct:false}]}},

  { id:'u2l3q5', unit:'unit2', lesson:'u2l3', page:77, type:'matching', bloom:'remember', difficulty:'easy',
    question:'Match each clothing item with its description:',
    paragraph:'Clothes vocabulary Goal 13-14 (Workbook p.76-77)',
    pairs:[{left:'jeans',right:'blue trousers'},{left:'skirt',right:'worn around waist'},{left:'sweater',right:'warm top'},{left:'sandals',right:'open summer shoes'}],
    explanation:'Each word describes a specific clothing item.',
    goldenRule:'Know clothes vocab: jeans, skirt, sweater, sandals, blouse, jacket, cap, hat.'},

  { id:'u2l3q6', unit:'unit2', lesson:'u2l3', page:76, type:'fillBlank', bloom:'apply', difficulty:'medium',
    question:'Fill in: "I\'m wearing ___ and ___ today."',
    paragraph:'"Write two things you are wearing today." (Workbook p.75)',
    blanks:['a T-shirt','jeans'], wordBank:['a T-shirt','jeans','a hat','shoes'],
    explanation:'Use clothing names: I\'m wearing a T-shirt and jeans today.',
    goldenRule:'Describe what you wear: I\'m wearing + clothes.'},

  { id:'u2l4q1', unit:'unit2', lesson:'u2l4', page:78, type:'multipleChoice', bloom:'remember', difficulty:'easy',
    question:'The word "panda" starts with which sound?',
    paragraph:'"panda/pizza, bear/bed." (Workbook p.79)',
    options:[{text:'/p/ as in pan',correct:true},{text:'/b/ as in ball',correct:false},{text:'/d/ as in dog',correct:false},{text:'/m/ as in man',correct:false}],
    explanation:'"Panda" starts with /p/.',
    goldenRule:'/p/: panda, pizza, pen. /b/: bear, bed, banana.',
    feedbackQuestion:{question:'Which word starts with /b/?',options:[{text:'bear',correct:true},{text:'panda',correct:false},{text:'pizza',correct:false},{text:'pine',correct:false}]}},

  { id:'u2l4q2', unit:'unit2', lesson:'u2l4', page:78, type:'classify', bloom:'analyze', difficulty:'medium',
    question:'Classify by starting sound: /p/ or /b/:',
    paragraph:'"Listen and circle p or b." (Workbook p.78)',
    categories:['/p/ sound (pen)','/b/ sound (ball)'],
    items:[{text:'panda',correct_category:0},{text:'bear',correct_category:1},{text:'pizza',correct_category:0},{text:'banana',correct_category:1},{text:'pin',correct_category:0},{text:'box',correct_category:1}],
    explanation:'/p/: panda, pizza, pin. /b/: bear, banana, box.',
    goldenRule:'/p/=unvoiced. /b/=voiced. Feel your throat!'},

  { id:'u2l4q3', unit:'unit2', lesson:'u2l4', page:79, type:'trueFalse', bloom:'understand', difficulty:'easy',
    question:'"Banana" and "box" both start with the /b/ sound.',
    paragraph:'"bear/banana, banana/box." (Workbook p.79)',
    correctAnswer:true, explanation:'B-anana and B-ox both start with /b/.',
    goldenRule:'/b/ words: bear, bed, banana, box.',
    feedbackQuestion:{question:'Which TWO words start with /b/?',options:[{text:'bear and bed',correct:true},{text:'panda and bear',correct:false},{text:'pizza and pen',correct:false},{text:'pin and pine',correct:false}]}},

  { id:'u2l4q4', unit:'unit2', lesson:'u2l4', page:78, type:'matching', bloom:'remember', difficulty:'easy',
    question:'Match each word with its starting sound:',
    paragraph:'Phonics p and b vocabulary (Workbook p.78-79)',
    pairs:[{left:'parrot',right:'/p/'},{left:'bed',right:'/b/'},{left:'pen',right:'/p/'},{left:'bear',right:'/b/'}],
    explanation:'parrot/pen = /p/. bed/bear = /b/.',
    goldenRule:'Parrot, pen, panda, pizza=/p/. Bear, bed, banana, box=/b/.'},

  { id:'u2l4q5', unit:'unit2', lesson:'u2l4', page:79, type:'multipleChoice', bloom:'apply', difficulty:'medium',
    question:'Choose the word that starts with /p/:',
    paragraph:'"Say two words that begin with p and two with b." (Workbook p.79)',
    options:[{text:'pine',correct:true},{text:'bear',correct:false},{text:'banana',correct:false},{text:'bird',correct:false}],
    explanation:'"Pine" starts with /p/. Others start with /b/.',
    goldenRule:'/p/: pin, pine, pen, panda. /b/: bear, bed, banana, box.',
    feedbackQuestion:{question:'Which TWO words begin with /p/?',options:[{text:'pizza and pen',correct:true},{text:'bear and bird',correct:false},{text:'banana and box',correct:false},{text:'bed and bear',correct:false}]}},

  { id:'u2l4q6', unit:'unit2', lesson:'u2l4', page:78, type:'ordering', bloom:'apply', difficulty:'hard',
    question:'Order these words alphabetically:',
    paragraph:'Phonics vocabulary p and b (Workbook p.78-79)',
    items:['pizza','bear','panda','banana'], correctOrder:[1,3,2,0],
    explanation:'Alphabetical: banana → bear → panda → pizza.',
    goldenRule:'Alphabetical order: look at first letter, then second letter if needed.'},
];

export const QUESTIONS_UNITS_1_2 = [...unit1Questions, ...unit2Questions];