// الوحدة الأولى — المخلوقات الحية — أسئلة إضافية
// الدروس: الخلية، الأنسجة والأعضاء، تصنيف المخلوقات الحية

export const U1_EXTRA = [
  // ═══ الدرس 1: الخلية — وحدة الحياة (28 سؤال) ═══
  { id:'s4_101', unit:'u1', lesson:'u1l1', page:2, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'تُعرف الخلية بأنها الوحدة البنائية والوظيفية لجميع المخلوقات الحية. ما معنى "الوحدة البنائية"؟',
    options:[{text:'الخلايا تبني جسم المخلوق الحي',correct:true},{text:'الخلايا تنتج الطاقة فقط',correct:false},{text:'الخلايا تنظم الحرارة',correct:false},{text:'الخلايا تخزن الماء',correct:false}],
    explanation:'الوحدة البنائية تعني أن جسم المخلوق الحي مُكوّن من خلايا، فهي لبنات البناء الأساسية.',
    goldenRule:'الخلية = وحدة بنائية (تبني الجسم) + وحدة وظيفية (تؤدي الوظائف).',
    paragraph:'تعريف الخلية — ص ٢',
  },
  { id:'s4_102', unit:'u1', lesson:'u1l1', page:3, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'اكتشف العالم روبرت هوك الخلايا لأول مرة عند فحصه لشرائح الفلين بالمجهر.',
    correctAnswer:'true',
    explanation:'روبرت هوك أول من اكتشف الخلايا عام 1665 م عند فحص شرائح الفلين بالمجهر.',
    goldenRule:'روبرت هوك = أول من اكتشف الخلايا (1665م).',
    paragraph:'اكتشاف الخلية — ص ٣',
  },
  { id:'s4_103', unit:'u1', lesson:'u1l1', page:4, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'المجهر من الأدوات المهمة في دراسة الخلايا. ما وظيفته الأساسية؟',
    options:[{text:'تكبير الأجسام الصغيرة لرؤيتها بوضوح',correct:true},{text:'تخزين الخلايا',correct:false},{text:'إنتاج الطاقة',correct:false},{text:'قياس درجة الحرارة',correct:false}],
    explanation:'المجهر يُكبّر الأجسام الصغيرة كالخلايا مما يتيح رؤيتها ودراستها.',
    goldenRule:'المجهر = أداة تكبير لرؤية الأجسام الدقيقة كالخلايا.',
    paragraph:'المجهر — ص ٤',
  },
  { id:'s4_104', unit:'u1', lesson:'u1l1', page:5, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'تحتوي الخلية النباتية على تركيب يمنحها شكلاً ثابتاً ومقاومة. ما هذا التركيب؟',
    options:[{text:'الغشاء الخلوي',correct:false},{text:'جدار الخلية',correct:true},{text:'النواة',correct:false},{text:'الفجوة العصارية',correct:false}],
    explanation:'جدار الخلية في الخلية النباتية يمنحها شكلاً ثابتاً ويحميها من الخارج.',
    goldenRule:'جدار الخلية = دعم وحماية للخلية النباتية.',
    paragraph:'جدار الخلية — ص ٥',
  },
  { id:'s4_105', unit:'u1', lesson:'u1l1', page:6, difficulty:'medium', bloom:'understand', type:'trueFalse',
    question:'السيتوبلازم مادة هلامية تحتوي على جميع مكونات الخلية وتتحرك بداخلها العضيات.',
    correctAnswer:'true',
    explanation:'السيتوبلازم مادة شبه هلامية تملأ الخلية وتحوي العضيات وتسمح بحركتها.',
    goldenRule:'السيتوبلازم = الوسط الهلامي الذي تسبو فيه مكونات الخلية.',
    paragraph:'السيتوبلازم — ص ٦',
  },
  { id:'s4_106', unit:'u1', lesson:'u1l1', page:7, difficulty:'hard', bloom:'apply', type:'multipleChoice',
    question:'مخلوق حي يتكوّن من خلية واحدة بلا نواة محاطة بغشاء. إلى أي مجموعة ينتمي؟',
    options:[{text:'البدائيات النوى',correct:true},{text:'الحيوانات',correct:false},{text:'النباتات',correct:false},{text:'الفطريات',correct:false}],
    explanation:'البدائيات النوى كائنات وحيدة الخلية لا تحتوي خلاياها على نواة محاطة بغشاء.',
    goldenRule:'بدائيات النوى = خلية بلا نواة محاطة بغشاء.',
    paragraph:'تصنيف الخلايا — ص ٧',
  },
  { id:'s4_107', unit:'u1', lesson:'u1l1', page:8, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'الميتوكوندريا عضية في الخلية تُعرف بمحطة الطاقة. ما وظيفتها؟',
    options:[{text:'إنتاج الطاقة اللازمة للخلية',correct:true},{text:'تخزين الماء',correct:false},{text:'التحكم في الخلية',correct:false},{text:'حماية الخلية',correct:false}],
    explanation:'الميتوكوندريا تُنتج الطاقة اللازمة لنشاط الخلية من خلال التنفس الخلوي.',
    goldenRule:'الميتوكوندريا = محطة طاقة الخلية.',
    paragraph:'الميتوكوندريا — ص ٨',
  },
  { id:'s4_108', unit:'u1', lesson:'u1l1', page:9, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'المخلوقات الحية تُقسم إلى مخلوقات وحيدة الخلية ومخلوقات متعددة الخلايا.',
    correctAnswer:'true',
    explanation:'بعض المخلوقات كالبكتيريا تتكوّن من خلية واحدة، وبعضها كالإنسان من ملايين الخلايا.',
    goldenRule:'وحيدة الخلية (بكتيريا) | متعددة الخلايا (إنسان، نبات).',
    paragraph:'أنواع المخلوقات — ص ٩',
  },
  { id:'s4_109', unit:'u1', lesson:'u1l1', page:10, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'الخلية وحيدة الخلية كالأميبا تقوم بكل وظائف الحياة داخل خلية واحدة. أيّ وظائف تشملها؟',
    options:[{text:'التغذية والتكاثر والحركة فقط',correct:false},{text:'التغذية والتنفس والتكاثر والحركة والإخراج',correct:true},{text:'الهضم فقط',correct:false},{text:'النمو فقط',correct:false}],
    explanation:'الخلية الواحدة في الكائن وحيد الخلية تقوم بجميع وظائف الحياة: تغذية، تنفس، تكاثر، حركة، إخراج.',
    goldenRule:'الخلية الواحدة تؤدي جميع وظائف الحياة في وحيدات الخلية.',
    paragraph:'وحيدات الخلية — ص ١٠',
  },
  { id:'s4_110', unit:'u1', lesson:'u1l1', page:5, difficulty:'medium', bloom:'understand', type:'classify',
    question:'صنّف مكونات الخلية إلى: موجود في الخلية الحيوانية فقط، ومشترك بين النباتية والحيوانية:',
    categories:['خاص بالخلية الحيوانية', 'مشترك'],
    items:[
      {text:'النواة', correct_category:1},
      {text:'الغشاء الخلوي', correct_category:1},
      {text:'السيتوبلازم', correct_category:1},
      {text:'الميتوكوندريا', correct_category:1},
      {text:'البلاستيدة الخضراء', correct_category:0},
      {text:'جدار الخلية', correct_category:0},
    ],
    explanation:'البلاستيدة الخضراء وجدار الخلية خاصان بالخلية النباتية. باقي المكونات مشتركة.',
    goldenRule:'ما يميز الخلية النباتية: جدار خلوي + بلاستيدة خضراء.',
    paragraph:'مقارنة الخلايا — ص ٥',
  },
  { id:'s4_111', unit:'u1', lesson:'u1l1', page:3, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'الخلية هي أصغر جزء من المخلوق الحي يستطيع الحياة بشكل مستقل.',
    correctAnswer:'true',
    explanation:'الخلية هي أصغر وحدة حية قادرة على أداء وظائف الحياة بشكل مستقل.',
    goldenRule:'الخلية = أصغر وحدة حية مستقلة.',
    paragraph:'الخلية — ص ٣',
  },
  { id:'s4_112', unit:'u1', lesson:'u1l1', page:6, difficulty:'hard', bloom:'analyze', type:'multipleChoice',
    question:'إذا فُقدت النواة من خلية، ما الذي يحدث لها؟',
    options:[{text:'تعيش بشكل طبيعي',correct:false},{text:'لا تستطيع التحكم في نشاطاتها وتموت',correct:true},{text:'تنتج طاقة أكثر',correct:false},{text:'تصبح نباتية',correct:false}],
    explanation:'النواة مركز التحكم، وبدونها لا تستطيع الخلية تنظيم نشاطاتها فتموت.',
    goldenRule:'بلا نواة → لا تحكم → موت الخلية.',
    paragraph:'النواة — ص ٦',
  },
  { id:'s4_113', unit:'u1', lesson:'u1l1', page:9, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'البراميسيوم كائن وحيد الخلية يعيش في الماء العذب. كيف يتحرك؟',
    options:[{text:'بالأهداب',correct:true},{text:'بالأسواط',correct:false},{text:'بالأرجل الكاذبة',correct:false},{text:'بالأجنحة',correct:false}],
    explanation:'البراميسيوم يتحرك بأهداب صغيرة تغطي جسمه وتساعده على الحركة في الماء.',
    goldenRule:'البراميسيوم = وحيد الخلية + يتحرك بالأهداب.',
    paragraph:'البراميسيوم — ص ٩',
  },
  { id:'s4_114', unit:'u1', lesson:'u1l1', page:10, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'في المخلوقات متعددة الخلايا، تتوزع وظائف الحياة على خلايا متخصصة. ما فائدة هذا التخصص؟',
    options:[{text:'زيادة عدد الخلايا',correct:false},{text:'أداء كل وظيفة بكفاءة أعلى عن طريق خلايا متخصصة',correct:true},{text:'تقليل حجم الجسم',correct:false},{text:'تغيير لون الجلد',correct:false}],
    explanation:'التخصص يجعل كل مجموعة خلايا تؤدي وظيفة معينة بكفاءة، كخلايا العضل للحركة وخلايا الدم للنقل.',
    goldenRule:'تخصص الخلايا = كفاءة أعلى في أداء الوظائف.',
    paragraph:'تخصص الخلايا — ص ١٠',
  },
  { id:'s4_115', unit:'u1', lesson:'u1l1', page:4, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'المجهر المركب يتكوّن من عدسات. كم عدسة رئيسية يستخدم؟',
    options:[{text:'عدسة واحدة',correct:false},{text:'عدستان (عينية وموضوعية)',correct:true},{text:'ثلاث عدسات',correct:false},{text:'أربع عدسات',correct:false}],
    explanation:'المجهر المركب يستخدم عدستين: العينية (قرب العين) والموضوعية (قرب الجسم).',
    goldenRule:'المجهر المركب = عدسة عينية + عدسة موضوعية.',
    paragraph:'المجهر المركب — ص ٤',
  },
  { id:'s4_116', unit:'u1', lesson:'u1l1', page:7, difficulty:'medium', bloom:'understand', type:'trueFalse',
    question:'الفجوة العصارية في الخلية النباتية أكبر من الفجوة في الخلية الحيوانية وتخزن الماء والغذاء.',
    correctAnswer:'true',
    explanation:'الفجوة العصارية في الخلية النباتية كبيرة وتخزن الماء والمواد الغذائية والفضلات.',
    goldenRule:'فجوة عصارية كبيرة = ميزة الخلية النباتية لتخزين الماء.',
    paragraph:'الفجوة العصارية — ص ٧',
  },
  { id:'s4_117', unit:'u1', lesson:'u1l1', page:11, difficulty:'hard', bloom:'evaluate', type:'multipleChoice',
    question:'لماذا يُعدّ البحث في الخلايا مهماً في المجال الطبي؟',
    options:[{text:'لأن الخلايا تساعد في معرفة أسباب الأمراض وعلاجها',correct:true},{text:'لأن الخلايا تُستخدم في البناء',correct:false},{text:'لأن الخلايا تنتج الغذاء',correct:false},{text:'لأن الخلايا تنظف الماء',correct:false}],
    explanation:'دراسة الخلايا تساعد الأطباء على فهم الأمراض مثل السرطان وتطوير علاجات لها.',
    goldenRule:'فهم الخلايا = فهم الأمراض → علاج أفضل.',
    paragraph:'أهمية دراسة الخلايا — ص ١١',
  },
  { id:'s4_118', unit:'u1', lesson:'u1l1', page:8, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'البناء الضوئي عملية تتم في الخلية النباتية. أين يحدث؟',
    options:[{text:'في النواة',correct:false},{text:'في البلاستيدة الخضراء',correct:true},{text:'في الميتوكوندريا',correct:false},{text:'في الغشاء الخلوي',correct:false}],
    explanation:'البناء الضوئي يحدث في البلاستيدة الخضراء حيث يُصنع الغذاء بوجود الضوء والكلوروفيل.',
    goldenRule:'البناء الضوئي → في البلاستيدة الخضراء.',
    paragraph:'البناء الضوئي — ص ٨',
  },
  { id:'s4_119', unit:'u1', lesson:'u1l1', page:11, difficulty:'medium', bloom:'apply', type:'trueFalse',
    question:'الخلايا النباتية تستطيع صنع غذائها بنفسها، بينما الخلايا الحيوانية لا تستطيع ذلك.',
    correctAnswer:'true',
    explanation:'الخلية النباتية تمتلك بلاستيدة خضراء تصنع الغذاء، بينما الحيوانية لا تمتلكها.',
    goldenRule:'النبات يصنع غذاءه | الحيوان يحصل على غذائه جاهزاً.',
    paragraph:'الفرق بين الخلايا — ص ١١',
  },
  { id:'s4_120', unit:'u1', lesson:'u1l1', page:9, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'البكتيريا النافعة في الأمعاء تساعد الجسم في أي وظيفة؟',
    options:[{text:'هضم بعض الأطعمة وإنتاج فيتامينات',correct:true},{text:'إنتاج الطاقة',correct:false},{text:'نقل الأكسجين',correct:false},{text:'بناء العظام',correct:false}],
    explanation:'بعض البكتيريا في الأمعاء تساعد في هضم الأطعمة وإنتاج فيتامين ك.',
    goldenRule:'بكتيريا نافعة = هضم + فيتامينات في الأمعاء.',
    paragraph:'البكتيريا النافعة — ص ٩',
  },
  { id:'s4_121', unit:'u1', lesson:'u1l1', page:6, difficulty:'medium', bloom:'understand', type:'ordering',
    question:'رتّب خطوات استخدام المجهر لفحص خلية بالترتيب الصحيح:',
    items:['وضع الشريحة على المنصة', 'توجيه العدسة الموضوعية', 'تعديل الإضاءة', 'النظر عبر العدسة العينية'],
    correctOrder:[2, 0, 1, 3],
    explanation:'نعدّل الإضاءة أولاً، ثم نضع الشريحة، ثم نوجه العدسة الموضوعية، ثم ننظر عبر العينية.',
    goldenRule:'ترتيب الفحص: إضاءة → شريحة → عدسة موضوعية → عدسة عينية.',
    paragraph:'استخدام المجهر — ص ٦',
  },
  { id:'s4_122', unit:'u1', lesson:'u1l1', page:5, difficulty:'hard', bloom:'analyze', type:'multipleChoice',
    question:'ماذا يحدث لو لم تكن للخلية النباتية بلاستيدة خضراء؟',
    options:[{text:'لا تستطيع صنع غذائها بالبناء الضوئي',correct:true},{text:'تموت فوراً',correct:false},{text:'تصبح حيوانية',correct:false},{text:'تكبر حجمها',correct:false}],
    explanation:'بدون البلاستيدة الخضراء لا يحدث البناء الضوئي فلا يصنع النبات غذاءه.',
    goldenRule:'بلا بلاستيدة خضراء → لا بناء ضوئي → لا غذاء.',
    paragraph:'البلاستيدة الخضراء — ص ٥',
  },
  { id:'s4_123', unit:'u1', lesson:'u1l1', page:12, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'تتكون الخلية من غشاء خلوي يحيط بها وينظم دخول وخروج المواد.',
    correctAnswer:'true',
    explanation:'الغشاء الخلوي يحيط بالخلية وينظم مرور المواد من وإلى داخلها.',
    goldenRule:'الغشاء الخلوي = بوابة الخلية (ينظم الدخول والخروج).',
    paragraph:'الغشاء الخلوي — ص ١٢',
  },
  { id:'s4_124', unit:'u1', lesson:'u1l1', page:10, difficulty:'medium', bloom:'apply', type:'multipleChoice',
    question:'لاحظ طالب خلية تحت المجهر فوجد جداراً خلوياً ونواة وفجوة كبيرة. ما نوع هذه الخلية؟',
    options:[{text:'خلية بكتيرية',correct:false},{text:'خلية نباتية',correct:true},{text:'خلية حيوانية',correct:false},{text:'خلية فيروسية',correct:false}],
    explanation:'جدار خلوي وفجوة كبيرة من علامات الخلية النباتية.',
    goldenRule:'جدار خلوي + فجوة كبيرة = خلية نباتية.',
    paragraph:'تحديد نوع الخلية — ص ١٠',
  },
  { id:'s4_125', unit:'u1', lesson:'u1l1', page:8, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'الكلوروفيل صبغة خضراء توجد في البلاستيدة الخضراء. ما دورها؟',
    options:[{text:'امتصاص ضوء الشمس لاستخدامه في البناء الضوئي',correct:true},{text:'حماية الخلية',correct:false},{text:'تنظيم الحرارة',correct:false},{text:'تخزين الماء',correct:false}],
    explanation:'الكلوروفيل يمتص ضوء الشمس ويستخدم طاقته في صنع الغذاء (البناء الضوئي).',
    goldenRule:'الكلوروفيل = صبغة خضراء تمتص الضوء للبناء الضوئي.',
    paragraph:'الكلوروفيل — ص ٨',
  },
  { id:'s4_126', unit:'u1', lesson:'u1l1', page:11, difficulty:'hard', bloom:'evaluate', type:'trueFalse',
    question:'عندما تتعرض خلية لمرض، فإن النواة هي المسؤولة عن نقل المعلومات الوراثية المتعلقة بالمرض.',
    correctAnswer:'true',
    explanation:'النواة تحتوي على المادة الوراثية التي تحمل صفات الكائن ومعلومات عن الأمراض.',
    goldenRule:'النواة = مخزن المعلومات الوراثية للخلية.',
    paragraph:'النواة والوراثة — ص ١١',
  },
  { id:'s4_127', unit:'u1', lesson:'u1l1', page:7, difficulty:'medium', bloom:'understand', type:'classify',
    question:'صنّف الكائنات التالية إلى: وحيدة الخلية أو متعددة الخلايا:',
    categories:['وحيدة الخلية', 'متعددة الخلايا'],
    items:[
      {text:'البكتيريا', correct_category:0},
      {text:'الأميبا', correct_category:0},
      {text:'الإنسان', correct_category:1},
      {text:'النخلة', correct_category:1},
      {text:'البراميسيوم', correct_category:0},
      {text:'الأسد', correct_category:1},
    ],
    explanation:'وحيدة الخلية: بكتيريا، أميبا، براميسيوم. متعددة: إنسان، نخلة، أسد.',
    goldenRule:'بكتيريا/أميبا = خلية واحدة | إنسان/نخلة = خلايا متعددة.',
    paragraph:'أنواع المخلوقات — ص ٧',
  },
  { id:'s4_128', unit:'u1', lesson:'u1l1', page:12, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'الخلية الحيوانية لا تحتوي على جدار خلوي. ما الذي يحيط بها؟',
    options:[{text:'الغشاء الخلوي فقط',correct:true},{text:'جدار الخلية',correct:false},{text:'الفجوة العصارية',correct:false},{text:'البلاستيدة الخضراء',correct:false}],
    explanation:'الخلية الحيوانية محاطة بالغشاء الخلوي فقط، ولا تمتلك جداراً خلوياً.',
    goldenRule:'الخلية الحيوانية = غشاء خلوي فقط (بلا جدار).',
    paragraph:'الخلية الحيوانية — ص ١٢',
  },

  // ═══ الدرس 2: الأنسجة والأعضاء والأجهزة (28 سؤال) ═══
  { id:'s4_129', unit:'u1', lesson:'u1l2', page:13, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'الخلية هي أصغر وحدة بنائية. ما الذي يتكوّن من تجمع خلايا متشابهة؟',
    options:[{text:'النسيج',correct:true},{text:'العضو',correct:false},{text:'الجهاز',correct:false},{text:'الجسم',correct:false}],
    explanation:'النسيج يتكوّن من تجمع خلايا متشابهة في الشكل والوظيفة.',
    goldenRule:'نسيج = خلايا متشابهة + وظيفة واحدة.',
    paragraph:'النسيج — ص ١٣',
  },
  { id:'s4_130', unit:'u1', lesson:'u1l2', page:14, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'نسيج البشرة في جلد الإنسان يُعدّ من الأنسجة الطلائية لأنه يغطي سطح الجسم.',
    correctAnswer:'true',
    explanation:'النسيج الطلائي يغطي أسطح الجسم ويبطّن الأعضاء، كنسيج البشرة.',
    goldenRule:'النسيج الطلائي = تغطية وحماية أسطح الجسم.',
    paragraph:'النسيج الطلائي — ص ١٤',
  },
  { id:'s4_131', unit:'u1', lesson:'u1l2', page:15, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'القلب يضخّ الدم لجميع أنحاء الجسم. ما مستوى التنظيم الذي يمثله القلب؟',
    options:[{text:'خلية',correct:false},{text:'نسيج',correct:false},{text:'عضو',correct:true},{text:'نظام',correct:false}],
    explanation:'القلب عضو لأنه يتكوّن من عدة أنسجة (عضلية، عصبية، طلائية) تعمل معاً.',
    goldenRule:'القلب = عضو (مجموعة أنسجة تعمل معاً).',
    paragraph:'القلب — ص ١٥',
  },
  { id:'s4_132', unit:'u1', lesson:'u1l2', page:16, difficulty:'medium', bloom:'understand', type:'classify',
    question:'صنّف الأمثلة التالية إلى: نسيج أو عضو:',
    categories:['نسيج', 'عضو'],
    items:[
      {text:'نسيج عضلي', correct_category:0},
      {text:'الرئة', correct_category:1},
      {text:'نسيج عظمي', correct_category:0},
      {text:'الكبد', correct_category:1},
      {text:'نسيج الدم', correct_category:0},
      {text:'الكلية', correct_category:1},
    ],
    explanation:'النسيج: عضلي، عظمي، دم. العضو: رئة، كبد، كلية.',
    goldenRule:'نسيج = خلايا متشابهة | عضو = أنسجة مختلفة مجتمعة.',
    paragraph:'الأنسجة والأعضاء — ص ١٦',
  },
  { id:'s4_133', unit:'u1', lesson:'u1l2', page:17, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'الجهاز الهضمي يتكوّن من عدة أعضاء. أيّ الأعضاء التالية تنتمي إليه؟',
    options:[{text:'الفم والمريء والمعدة والأمعاء',correct:true},{text:'القلب والأوعية الدموية',correct:false},{text:'الرئتان والقصبة الهوائية',correct:false},{text:'الدماغ والحبل الشوكي',correct:false}],
    explanation:'الجهاز الهضمي يضم الفم والمريء والمعدة والأمعاء التي تعمل معاً في هضم الطعام.',
    goldenRule:'الجهاز الهضمي = فم + مريء + معدة + أمعاء.',
    paragraph:'الجهاز الهضمي — ص ١٧',
  },
  { id:'s4_134', unit:'u1', lesson:'u1l2', page:18, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'الجهاز العصبي يتكوّن من الدماغ والحبل الشوكي والأعصاب.',
    correctAnswer:'true',
    explanation:'الجهاز العصبي يضم الدماغ والحبل الشوكي والأعصاب المنتشرة في الجسم.',
    goldenRule:'الجهاز العصبي = دماغ + حبل شوكي + أعصاب.',
    paragraph:'الجهاز العصبي — ص ١٨',
  },
  { id:'s4_135', unit:'u1', lesson:'u1l2', page:19, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'النسيج العضلي يقوم بوظيفة محددة. ما هي؟',
    options:[{text:'إنتاج الدم',correct:false},{text:'الحركة وتقلّص الجسم',correct:true},{text:'هضم الطعام',correct:false},{text:'نقل الأكسجين',correct:false}],
    explanation:'النسيج العضلي مسؤول عن الحركة وتقلّص العضلات في الجسم.',
    goldenRule:'النسيج العضلي = حركة وتقلّص.',
    paragraph:'النسيج العضلي — ص ١٩',
  },
  { id:'s4_136', unit:'u1', lesson:'u1l2', page:20, difficulty:'medium', bloom:'apply', type:'ordering',
    question:'رتّب مستويات تنظيم جسم الإنسان من الأصغر للأكبر:',
    items:['الخلية', 'الجهاز', 'النسيج', 'العضو'],
    correctOrder:[0, 2, 3, 1],
    explanation:'الترتيب الصحيح: خلية → نسيج → عضو → جهاز.',
    goldenRule:'خلية → نسيج → عضو → جهاز → كائن حي.',
    paragraph:'مستويات التنظيم — ص ٢٠',
  },
  { id:'s4_137', unit:'u1', lesson:'u1l2', page:21, difficulty:'hard', bloom:'analyze', type:'multipleChoice',
    question:'إذا تعطّل عضو في جهاز حيوي، ماذا يحدث للجسم؟',
    options:[{text:'لا يتأثر شيء',correct:false},{text:'قد يختل عمل الجهاز كله ويتأثر الجسم',correct:true},{text:'يتحسن الجسم',correct:false},{text:'يتوقف القلب فقط',correct:false}],
    explanation:'تعطّل عضو يؤثر على الجهاز بأكمله وقد يؤدي لاختلال وظائف الجسم.',
    goldenRule:'كل عضو مهم → تعطّله يُخلّ بالجهاز والجسم.',
    paragraph:'أهمية الأعضاء — ص ٢١',
  },
  { id:'s4_138', unit:'u1', lesson:'u1l2', page:15, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'الرئة عضو يتبع للجهاز التنفسي.',
    correctAnswer:'true',
    explanation:'الرئة عضو من أعضاء الجهاز التنفسي المسؤول عن التنفس وتبادل الغازات.',
    goldenRule:'الرئة = عضو تنفسي.',
    paragraph:'الرئة — ص ١٥',
  },
  { id:'s4_139', unit:'u1', lesson:'u1l2', page:22, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'نسيج الدم يُعدّ من الأنسجة الضامة. ما وظيفته الرئيسية؟',
    options:[{text:'نقل الأكسجين والغذاء والفضلات',correct:true},{text:'الحركة',correct:false},{text:'الحماية من الجراثيم فقط',correct:false},{text:'تخزين الدهون',correct:false}],
    explanation:'نسيج الدم ينقل الأكسجين والغذاء لخلايا الجسم ويُزيل الفضلات.',
    goldenRule:'نسيج الدم = نقل (أكسجين + غذاء + فضلات).',
    paragraph:'نسيج الدم — ص ٢٢',
  },
  { id:'s4_140', unit:'u1', lesson:'u1l2', page:23, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'الجهاز الهيكلي يتكوّن من العظام. ما وظيفته؟',
    options:[{text:'دعم الجسم وحماية الأعضاء',correct:true},{text:'هضم الطعام',correct:false},{text:'نقل الأكسجين',correct:false},{text:'التنفس',correct:false}],
    explanation:'الجهاز الهيكلي يدعم الجسم ويعطيه شكله ويحمي أعضاءه الداخلية.',
    goldenRule:'الجهاز الهيكلي = دعم + حماية + حركة.',
    paragraph:'الجهاز الهيكلي — ص ٢٣',
  },
  { id:'s4_141', unit:'u1', lesson:'u1l2', page:18, difficulty:'medium', bloom:'understand', type:'trueFalse',
    question:'النسيج العصبي ينقل التنبيهات والرسائل بين أجزاء الجسم والدماغ.',
    correctAnswer:'true',
    explanation:'النسيج العصبي ينقل الإشارات العصبية بين الجسم والدماغ بسرعة كبيرة.',
    goldenRule:'النسيج العصبي = نقل الرسائل والتنبيهات.',
    paragraph:'النسيج العصبي — ص ١٨',
  },
  { id:'s4_142', unit:'u1', lesson:'u1l2', page:19, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'الجلد يُعدّ عضواً لأنه:',
    options:[{text:'يتكوّن من عدة أنسجة تؤدي وظائف محددة',correct:true},{text:'مكوّن من خلية واحدة',correct:false},{text:'لا يؤدي وظيفة',correct:false},{text:'جزء من الجهاز العصبي فقط',correct:false}],
    explanation:'الجلد عضو لأنه يتكوّن من أنسجة (طلائية، ضامة، عصبية) تؤدي وظائف الحماية والإحساس.',
    goldenRule:'الجلد = عضو (أنسجة متعددة + وظائف متعددة).',
    paragraph:'الجلد — ص ١٩',
  },
  { id:'s4_143', unit:'u1', lesson:'u1l2', page:20, difficulty:'hard', bloom:'apply', type:'multipleChoice',
    question:'المعدة عضو يتبع للجهاز الهضمي. ما النسيج الذي يُفرز العصارة المعدية؟',
    options:[{text:'النسيج الطلائي المبطّن للمعدة',correct:true},{text:'النسيج العضلي',correct:false},{text:'النسيج العصبي',correct:false},{text:'النسيج العظمي',correct:false}],
    explanation:'النسيج الطلائي المبطّن للمعدة يُفرز العصارة الهاضمة.',
    goldenRule:'النسيج الطلائي للمعدة = إفراز العصارة الهاضمة.',
    paragraph:'معدة — ص ٢٠',
  },
  { id:'s4_144', unit:'u1', lesson:'u1l2', page:21, difficulty:'medium', bloom:'understand', type:'classify',
    question:'صنّف الأعضاء التالية حسب الجهاز الذي تنتمي إليه:',
    categories:['جهاز دوراني', 'جهاز تنفسي'],
    items:[
      {text:'القلب', correct_category:0},
      {text:'الرئة', correct_category:1},
      {text:'الأوعية الدموية', correct_category:0},
      {text:'القصبة الهوائية', correct_category:1},
      {text:'الدم', correct_category:0},
    ],
    explanation:'الدوراني: قلب، أوعية، دم. التنفسي: رئة، قصبة هوائية.',
    goldenRule:'دوراني = قلب وأوعية | تنفسي = رئة وقصبة.',
    paragraph:'الأجهزة الحيوية — ص ٢١',
  },
  { id:'s4_145', unit:'u1', lesson:'u1l2', page:22, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'الكبد عضو كبير يتبع للجهاز الهضمي ويُساعد في تنظيم نسبة السكر في الدم.',
    correctAnswer:'true',
    explanation:'الكبد عضو هضمي يُنظّم السكر ويخزّن الفيتامينات ويُزيل السموم.',
    goldenRule:'الكبد = تنظيم سكر + تخزين فيتامينات + إزالة سموم.',
    paragraph:'الكبد — ص ٢٢',
  },
  { id:'s4_146', unit:'u1', lesson:'u1l2', page:24, difficulty:'hard', bloom:'evaluate', type:'multipleChoice',
    question:'لماذا يُعدّ جسم الإنسان أكثر تعقيداً من جسم الأميبا؟',
    options:[{text:'لأن الإنسان أكبر حجماً',correct:false},{text:'لأن جسم الإنسان يتكوّن من أجهزة وأعضاء وأنسجة متخصصة',correct:true},{text:'لأن الإنسان يتحرك أسرع',correct:false},{text:'لأن الإنسان يأكل أكثر',correct:false}],
    explanation:'تعقيد جسم الإنسان يأتي من تخصص خلاياه في أنسجة وأعضاء وأجهزة تعمل بانسجام.',
    goldenRule:'التعقيد = تخصص + تنظيم متدرج (خلية → نسيج → عضو → جهاز).',
    paragraph:'مقارنة الكائنات — ص ٢٤',
  },
  { id:'s4_147', unit:'u1', lesson:'u1l2', page:16, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'النسيج الذي يربط الأعضاء ويحمي الجسم هو:',
    options:[{text:'النسيج الضام',correct:true},{text:'النسيج الطلائي',correct:false},{text:'النسيج العصبي',correct:false},{text:'النسيج العضلي',correct:false}],
    explanation:'النسيج الضام يربط الأعضاء ويحميها ويشمل الدم والعظام والغضاريف.',
    goldenRule:'النسيج الضام = ربط + حماية (دم، عظام، غضاريف).',
    paragraph:'النسيج الضام — ص ١٦',
  },
  { id:'s4_148', unit:'u1', lesson:'u1l2', page:23, difficulty:'medium', bloom:'understand', type:'trueFalse',
    question:'الأعضاء في الجهاز الواحد تعمل بشكل مستقل دون تنسيق بينها.',
    correctAnswer:'false',
    explanation:'أعضاء الجهاز الواحد تعمل بتنسيق تام لتحقيق وظيفة الجهاز بشكل عام.',
    goldenRule:'أعضاء الجهاز = عمل منسق لتحقيق وظيفة واحدة.',
    paragraph:'تنسيق الأعضاء — ص ٢٣',
  },
  { id:'s4_149', unit:'u1', lesson:'u1l2', page:14, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'النسيج الذي يبطّن المعدة والأمعاء يُعرف بـ:',
    options:[{text:'النسيج الطلائي',correct:true},{text:'النسيج العضلي',correct:false},{text:'النسيج العصبي',correct:false},{text:'النسيج العظمي',correct:false}],
    explanation:'النسيج الطلائي يبطّن تجاويف الجسم كالمعدة والأمعاء ويُفرز العصارات.',
    goldenRule:'النسيج الطلائي = تبطين + إفراز.',
    paragraph:'النسيج الطلائي — ص ١٤',
  },
  { id:'s4_150', unit:'u1', lesson:'u1l2', page:24, difficulty:'hard', bloom:'analyze', type:'multipleChoice',
    question:'إذا توقفت الكليتان عن العمل، أيّ جهاز يتأثر بشكل مباشر؟',
    options:[{text:'الجهاز الإخراجي',correct:true},{text:'الجهاز العصبي',correct:false},{text:'الجهاز الهيكلي',correct:false},{text:'الجهاز العضلي',correct:false}],
    explanation:'الكليتان من أعضاء الجهاز الإخراجي، وتوقفها يعطّل إخراج الفضلات من الجسم.',
    goldenRule:'الكليتان = جهاز إخراجي → توقفها = تراكم الفضلات.',
    paragraph:'الجهاز الإخراجي — ص ٢٤',
  },
  { id:'s4_151', unit:'u1', lesson:'u1l2', page:17, difficulty:'medium', bloom:'apply', type:'ordering',
    question:'رتّب الأجهزة التالية حسب ارتباطها بعملية الهضم:',
    items:['الجهاز الهضمي', 'الجهاز الدوراني', 'الجهاز الإخراجي'],
    correctOrder:[0, 1, 2],
    explanation:'الهضم: جهاز هضمي يهضم → دوراني ينقل الغذاء → إخراجي يُخرج الفضلات.',
    goldenRule:'الهضم: هضمي → دوراني (نقل) → إخراجي (فضلات).',
    paragraph:'تنسيق الأجهزة — ص ١٧',
  },
  { id:'s4_152', unit:'u1', lesson:'u1l2', page:20, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'العظام والغضاريف تُعدّ من الأنسجة الضامة.',
    correctAnswer:'true',
    explanation:'العظام والغضاريف نسيج ضام يدعم الجسم ويحمي أعضاءه.',
    goldenRule:'العظام والغضاريف = نسيج ضام (دعم وحماية).',
    paragraph:'النسيج الضام — ص ٢٠',
  },
  { id:'s4_153', unit:'u1', lesson:'u1l2', page:23, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'العين عضو يتبع لأي جهاز؟',
    options:[{text:'الجهاز العصبي',correct:true},{text:'الجهاز الهضمي',correct:false},{text:'الجهاز التنفسي',correct:false},{text:'الجهاز الهيكلي',correct:false}],
    explanation:'العين عضو من الجهاز العصبي تستقبل المثيرات وتُرسلها للدماغ.',
    goldenRule:'العين = عضو عصبي (استقبال المثيرات).',
    paragraph:'العين — ص ٢٣',
  },
  { id:'s4_154', unit:'u1', lesson:'u1l2', page:15, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'العضو يتكوّن من:',
    options:[{text:'عدة أنسجة مختلفة تعمل معاً',correct:true},{text:'خلية واحدة',correct:false},{text:'نسيج واحد فقط',correct:false},{text:'جهاز كامل',correct:false}],
    explanation:'العضو يتكوّن من عدة أنسجة مختلفة تجتمع لتؤدي وظيفة محددة.',
    goldenRule:'العضو = أنسجة متعددة + وظيفة محددة.',
    paragraph:'العضو — ص ١٥',
  },
  { id:'s4_155', unit:'u1', lesson:'u1l2', page:22, difficulty:'hard', bloom:'evaluate', type:'trueFalse',
    question:'عملية التنفس تتطلب تنسيق الجهاز التنفسي والجهاز الدوراني معاً.',
    correctAnswer:'true',
    explanation:'التنفس يحتاج الجهاز التنفسي لأخذ الأكسجين والدوراني لنقله لخلايا الجسم.',
    goldenRule:'التنفس = تنفسي (أخذ أكسجين) + دوراني (نقله).',
    paragraph:'تنسيق الأجهزة — ص ٢٢',
  },
  { id:'s4_156', unit:'u1', lesson:'u1l2', page:13, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'الخلايا تتكوّن من أنسجة، والأنسجة تتكوّن من أعضاء.',
    correctAnswer:'false',
    explanation:'العكس صحيح: الخلايا تتجمع لتكوّن الأنسجة، والأنسجة تتجمع لتكوّن الأعضاء.',
    goldenRule:'الخلايا → أنسجة → أعضاء → أجهزة.',
    paragraph:'مستويات التنظيم — ص ١٣',
  },

  // ═══ الدرس 3: تصنيف المخلوقات الحية (28 سؤال) ═══
  { id:'s4_157', unit:'u1', lesson:'u1l3', page:25, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'العلماء يصنّفون المخلوقات الحية لتسهيل دراستها. كم مملكة رئيسية يصنّفونها؟',
    options:[{text:'خمس ممالك',correct:true},{text:'ثلاث ممالك',correct:false},{text:'سبع ممالك',correct:false},{text:'مملكتان',correct:false}],
    explanation:'تُصنّف المخلوقات الحية في خمس ممالك: البدائيات، الطلائعيات، الفطريات، النباتات، الحيوانات.',
    goldenRule:'5 ممالك: بدائيات + طلائعيات + فطريات + نباتات + حيوانات.',
    paragraph:'ممالك المخلوقات — ص ٢٥',
  },
  { id:'s4_158', unit:'u1', lesson:'u1l3', page:26, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'مملكة البدائيات تضم البكتيريا وهي كائنات وحيدة الخلية بلا نواة محاطة بغشاء.',
    correctAnswer:'true',
    explanation:'البدائيات كائنات وحيدة الخلية لا تحتوي خلاياها على نواة حقيقية محاطة بغشاء.',
    goldenRule:'البدائيات = بكتيريا + بلا نواة حقيقية.',
    paragraph:'مملكة البدائيات — ص ٢٦',
  },
  { id:'s4_159', unit:'u1', lesson:'u1l3', page:27, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'الطلائعيات كائنات وحيدة الخلية لها نواة. أيّ الكائنات التالية ينتمي إليها؟',
    options:[{text:'الأميبا والبراميسيوم',correct:true},{text:'الأسد والنمر',correct:false},{text:'النخيل والورد',correct:false},{text:'البكتيريا',correct:false}],
    explanation:'الطلائعيات تضم الأميبا والبراميسيوم وهي وحيدة الخلية ولها نواة.',
    goldenRule:'الطلائعيات = وحيدة الخلية + نواة (أميبا، براميسيوم).',
    paragraph:'مملكة الطلائعيات — ص ٢٧',
  },
  { id:'s4_160', unit:'u1', lesson:'u1l3', page:28, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'الفطريات لا تستطيع صنع غذائها. كيف تحصل عليه؟',
    options:[{text:'تمتصّه من البيئة أو الكائنات الأخرى',correct:true},{text:'تصنعه بالبناء الضوئي',correct:false},{text:'تشربه من الماء',correct:false},{text:'تنتجه من الهواء',correct:false}],
    explanation:'الفطريات تمتصّ الغذاء من البيئة المحيطة أو من الكائنات الأخرى.',
    goldenRule:'الفطريات = لا تصنع غذاءها (تمتصّه).',
    paragraph:'مملكة الفطريات — ص ٢٨',
  },
  { id:'s4_161', unit:'u1', lesson:'u1l3', page:29, difficulty:'medium', bloom:'understand', type:'classify',
    question:'صنّف الكائنات التالية حسب المملكة:',
    categories:['مملكة النباتات', 'مملكة الفطريات'],
    items:[
      {text:'النخلة', correct_category:0},
      {text:'العفن (القالع)',correct:false},{text:'الورد', correct_category:0},
      {text:'الفطر', correct_category:1},
      {text:'الطحالب', correct_category:0},
      {text:'الخبز المتعفن', correct_category:1},
    ],
    explanation:'النباتات: نخلة، ورد، طحالب. الفطريات: عفن، فطر، خبز متعفن.',
    goldenRule:'نباتات = تصنع غذاءها | فطريات = تمتصّ الغذاء.',
    paragraph:'تصنيف الكائنات — ص ٢٩',
  },
  { id:'s4_162', unit:'u1', lesson:'u1l3', page:30, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'الفيروسات كائنات دقيقة لا تُصنّف ضمن الممالك الخمس لأنها لا تتميز بخصائص الحياة الكاملة.',
    correctAnswer:'true',
    explanation:'الفيروسات لا تتكاثر وحدها بل داخل خلايا مضيفة، فلا تُصنّف كمخلوقات حية كاملة.',
    goldenRule:'الفيروس = لا حياة كاملة (يحتاج مضيف للتكاثر).',
    paragraph:'الفيروسات — ص ٣٠',
  },
  { id:'s4_163', unit:'u1', lesson:'u1l3', page:31, difficulty:'medium', bloom:'apply', type:'multipleChoice',
    question:'حيوان له عمود فقري وأربع أرجل ويرضع صغاره. إلى أي مجموعة ينتمي؟',
    options:[{text:'الثدييات',correct:true},{text:'الطيور',correct:false},{text:'الأسماك',correct:false},{text:'الزواحف',correct:false}],
    explanation:'الثدييات فقارية ترضع صغارها ولها شعر ودرجة حرارة ثابتة.',
    goldenRule:'الثدييات = فقارية + رضاعة + شعر + حرارة ثابتة.',
    paragraph:'الثدييات — ص ٣١',
  },
  { id:'s4_164', unit:'u1', lesson:'u1l3', page:32, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'الأسماك تعيش في الماء وتتنفس بـ:',
    options:[{text:'الخياشيم',correct:true},{text:'الرئتين',correct:false},{text:'الأنف',correct:false},{text:'الجلد',correct:false}],
    explanation:'الأسماك تتنفس بالخياشيم التي تستخلص الأكسجين الذائب في الماء.',
    goldenRule:'الأسماك = خياشيم (تنفس في الماء).',
    paragraph:'الأسماك — ص ٣٢',
  },
  { id:'s4_165', unit:'u1', lesson:'u1l3', page:33, difficulty:'medium', bloom:'understand', type:'trueFalse',
    question:'الزواحف كالسحالي والثعابين حيوانات متكيفة للحياة على اليابسة بجلدها الجاف وحراشفه.',
    correctAnswer:'true',
    explanation:'الزواحف لها جلد جاف مغطى بالحراشف وتتنفس بالرئتين وتبيض على اليابسة.',
    goldenRule:'الزواحف = جلد جاف + حراشف + رئتان + بيض على اليابسة.',
    paragraph:'الزواحف — ص ٣٣',
  },
  { id:'s4_166', unit:'u1', lesson:'u1l3', page:34, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'الحشرات تنتمي إلى مجموعة المفصليات. ما صفتها المميزة؟',
    options:[{text:'ثلاثة أزواج من الأرجل وجسم مقسوم لثلاثة أجزاء',correct:true},{text:'أربع أرجل وجسم واحد',correct:false},{text:'لا أرجل لها',correct:false},{text:'عشر أرجل',correct:false}],
    explanation:'الحشرات مفصليات لها 6 أرجل (3 أزواج) وجسم مقسوم لرأس وصدر وبطن.',
    goldenRule:'الحشرة = 6 أرجل + جسم من 3 أجزاء.',
    paragraph:'الحشرات — ص ٣٤',
  },
  { id:'s4_167', unit:'u1', lesson:'u1l3', page:35, difficulty:'hard', bloom:'analyze', type:'multipleChoice',
    question:'العناكب تُصنّف ضمن المفصليات لكنها ليست حشرات. ما الفرق؟',
    options:[{text:'لها 8 أرجل وجسم من جزأين',correct:true},{text:'لها 6 أرجل وثلاثة أجزاء',correct:false},{text:'لا أرجل لها',correct:false},{text:'لها 10 أرجل',correct:false}],
    explanation:'العناكب لها 8 أرجل (4 أزواج) وجسم من جزأين، بينما الحشرات 6 أرجل و3 أجزاء.',
    goldenRule:'العنكبوت = 8 أرجل + جسمان ≠ الحشرة = 6 أرجل + 3 أجزاء.',
    paragraph:'العناكب — ص ٣٥',
  },
  { id:'s4_168', unit:'u1', lesson:'u1l3', page:26, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'النباتات مخلوقات حية قادرة على صنع غذائها بنفسها عن طريق البناء الضوئي.',
    correctAnswer:'true',
    explanation:'النباتات كائنات ذاتية التغذية تصنع غذاءها بالبناء الضوئي بوجود الضوء.',
    goldenRule:'النبات = ذاتي التغذية (يصنع غذاءه).',
    paragraph:'مملكة النباتات — ص ٢٦',
  },
  { id:'s4_169', unit:'u1', lesson:'u1l3', page:36, difficulty:'medium', bloom:'understand', type:'classify',
    question:'صنّف الحيوانات التالية إلى فقارية أو لافقارية:',
    categories:['فقارية', 'لافقارية'],
    items:[
      {text:'الضفدع', correct_category:0},
      {text:'الديدان', correct_category:1},
      {text:'الثعبان', correct_category:0},
      {text:'المحار', correct_category:1},
      {text:'الخفاش', correct_category:0},
      {text:'قنفذ البحر', correct_category:1},
    ],
    explanation:'فقارية: ضفدع، ثعبان، خفاش. لافقارية: ديدان، محار، قنفذ البحر.',
    goldenRule:'فقارية = عمود فقري | لافقارية = بلا عمود فقري.',
    paragraph:'الفقاريات واللافقاريات — ص ٣٦',
  },
  { id:'s4_170', unit:'u1', lesson:'u1l3', page:31, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'الطيور تتميز بقدرتها على الطيران في أغلب الأنواع. ما الذي يساعدها على ذلك؟',
    options:[{text:'الأجنحة والريش والعظام المجوفة',correct:true},{text:'الخياشيم',correct:false},{text:'الأرجل الكثيرة',correct:false},{text:'الحراشف',correct:false}],
    explanation:'الطيور تتميز بالأجنجة والريش والعظام المجوفة الخفيفة التي تساعدها على الطيران.',
    goldenRule:'الطيور = أجنحة + ريش + عظام مجوفة.',
    paragraph:'الطيور — ص ٣١',
  },
  { id:'s4_171', unit:'u1', lesson:'u1l3', page:30, difficulty:'hard', bloom:'evaluate', type:'trueFalse',
    question:'البكتيريا كلها ضارة وتسبب الأمراض فقط دون أي فائدة للإنسان.',
    correctAnswer:'false',
    explanation:'بعض البكتيريا نافعة كالبكتيريا في الأمعاء وبعضها ضار كالمسبب للأمراض.',
    goldenRule:'البكتيريا: نافعة (هضم، فيتامينات) + ضارة (أمراض).',
    paragraph:'البكتيريا — ص ٣٠',
  },
  { id:'s4_172', unit:'u1', lesson:'u1l3', page:32, difficulty:'medium', bloom:'apply', type:'multipleChoice',
    question:'كائن حي يعيش في الماء وله زعانف وخياشيم وفقالس. ما تصنيفه؟',
    options:[{text:'سمكة',correct:true},{text:'طائر',correct:false},{text:'ثديي',correct:false},{text:'زاحف',correct:false}],
    explanation:'السمكة لها زعانف وخياشيم وحراشف وتعيش في الماء.',
    goldenRule:'زعانف + خياشيم + حراشف + ماء = سمكة.',
    paragraph:'الأسماك — ص ٣٢',
  },
  { id:'s4_173', unit:'u1', lesson:'u1l3', page:28, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'الفطريات تُعدّ من الممالك الخمس للمخلوقات الحية.',
    correctAnswer:'true',
    explanation:'الفطريات مملكة من الممالك الخمس، تضم الكائنات التي تمتصّ الغذاء من البيئة.',
    goldenRule:'الفطريات = إحدى الممالك الخمس.',
    paragraph:'مملكة الفطريات — ص ٢٨',
  },
  { id:'s4_174', unit:'u1', lesson:'u1l3', page:34, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'الحشرات من أكثر الحيوانات انتشاراً على الأرض. كم زوجاً من الأجنحة تمتلكه الحشرة؟',
    options:[{text:'زوج واحد',correct:false},{text:'زوجان من الأجنحة',correct:true},{text:'ثلاثة أزواج',correct:false},{text:'لا أجنحة لها',correct:false}],
    explanation:'معظم الحشرات لها زوجان من الأجنحة (4 أجنحة) على الصدر.',
    goldenRule:'الحشرة = زوجان من الأجنحة (4 أجنحة).',
    paragraph:'الحشرات — ص ٣٤',
  },
  { id:'s4_175', unit:'u1', lesson:'u1l3', page:36, difficulty:'hard', bloom:'analyze', type:'multipleChoice',
    question:'أيّ الخصائص التالية تجعل من النبات منتجاً ذاتياً؟',
    options:[{text:'وجود بلاستيدة خضراء تصنع الغذاء',correct:true},{text:'وجود جذور فقط',correct:false},{text:'حجمه الكبير',correct:false},{text:'لونه الأخضر فقط',correct:false}],
    explanation:'البلاستيدة الخضراء في النبات تصنع الغذاء بالبناء الضوئي مما يجعله منتجاً ذاتياً.',
    goldenRule:'النبات = منتج ذاتي (بالبلاستيدة الخضراء).',
    paragraph:'النباتات — ص ٣٦',
  },
  { id:'s4_176', unit:'u1', lesson:'u1l3', page:29, difficulty:'medium', bloom:'understand', type:'trueFalse',
    question:'الطحالب التي تعيش في الماء تُصنّف ضمن مملكة النباتات لأنها تصنع غذاءها بالبناء الضوئي.',
    correctAnswer:'true',
    explanation:'الطحالب كائنات ذاتية التغذية تصنع غذاءها بالبناء الضوئي فتُصنّف ضمن النباتات.',
    goldenRule:'الطحالب = نباتات مائية (تصنع غذاءها).',
    paragraph:'الطحالب — ص ٢٩',
  },
  { id:'s4_177', unit:'u1', lesson:'u1l3', page:33, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'الضفدع حيوان برمائي يعيش:',
    options:[{text:'في الماء وعلى اليابسة',correct:true},{text:'في الماء فقط',correct:false},{text:'في الصحراء فقط',correct:false},{text:'في الجو فقط',correct:false}],
    explanation:'الضفدع برمائي يعيش جزءاً من حياته في الماء وجزءاً على اليابسة.',
    goldenRule:'البرمائيات = ماء + يابسة (ضفدع، تمساح).',
    paragraph:'البرمائيات — ص ٣٣',
  },
  { id:'s4_178', unit:'u1', lesson:'u1l3', page:25, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'التصنيف العلمي للمخلوقات الحية يُساعد العلماء على فهم العلاقات بينها.',
    correctAnswer:'true',
    explanation:'التصنيف يُنظّم المخلوقات في مجموعات ويُسهّل دراستها وفهم العلاقات بينها.',
    goldenRule:'التصنيف = تنظيم + فهم العلاقات بين الكائنات.',
    paragraph:'أهمية التصنيف — ص ٢٥',
  },
  { id:'s4_179', unit:'u1', lesson:'u1l3', page:35, difficulty:'medium', bloom:'apply', type:'classify',
    question:'صنّف الحيوانات التالية حسب طريقة تنفسها:',
    categories:['تنفس بالخياشيم', 'تنفس بالرئتين'],
    items:[
      {text:'السمكة', correct_category:0},
      {text:'الحوت', correct_category:1},
      {text:'الأسد', correct_category:1},
      {text:'الروبيان', correct_category:0},
      {text:'الحمامة', correct_category:1},
    ],
    explanation:'خياشيم: سمكة، روبيان. رئتان: حوت، أسد، حمامة.',
    goldenRule:'خياشيم = ماء | رئتان = يابسة (وبعض المائي كالحوت).',
    paragraph:'طرق التنفس — ص ٣٥',
  },
  { id:'s4_180', unit:'u1', lesson:'u1l3', page:36, difficulty:'hard', bloom:'evaluate', type:'multipleChoice',
    question:'لماذا يُعدّ تصنيف الكائنات مهماً في حفظ التنوع البيولوجي؟',
    options:[{text:'لأنه يُساعد في حصر الأنواع ومعرفة المهددة بالانقراض',correct:true},{text:'لأنه يُساعد في طبخ الطعام',correct:false},{text:'لأنه يُغير شكل الكائنات',correct:false},{text:'لأنه يُنتج الطاقة',correct:false}],
    explanation:'التصنيف يُساعد في معرفة الأنواع وحصرها وحماية المهددة بالانقراض.',
    goldenRule:'التصنيف = حماية التنوع البيولوجي.',
    paragraph:'أهمية التصنيف — ص ٣٦',
  },
  { id:'s4_181', unit:'u1', lesson:'u1l3', page:30, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'البكتيريا كائنات وحيدة الخلية تنتمي إلى مملكة:',
    options:[{text:'البدائيات',correct:true},{text:'النباتات',correct:false},{text:'الحيوانات',correct:false},{text:'الطلائعيات',correct:false}],
    explanation:'البكتيريا من مملكة البدائيات لأن خليتها بلا نواة حقيقية.',
    goldenRule:'البكتيريا = بدائيات (بلا نواة حقيقية).',
    paragraph:'البكتيريا — ص ٣٠',
  },
  { id:'s4_182', unit:'u1', lesson:'u1l3', page:31, difficulty:'medium', bloom:'understand', type:'trueFalse',
    question:'الحيتان والدلافين تُصنّف ضمن الثدييات رغم أنها تعيش في الماء.',
    correctAnswer:'true',
    explanation:'الحيتان والدلافين ثدييات لأنها ترضع صغارها ولها شعر وتتنفس بالرئتين.',
    goldenRule:'الحوت والدلفين = ثدييات (رضاعة + رئتان) رغم الماء.',
    paragraph:'الثدييات البحرية — ص ٣١',
  },
  { id:'s4_183', unit:'u1', lesson:'u1l3', page:34, difficulty:'medium', bloom:'apply', type:'multipleChoice',
    question:'لاحظ طالب حشرة لها 8 أرجل وجسم من جزأين. ماذا يستنتج؟',
    options:[{text:'إنها عنكبوت وليست حشرة',correct:true},{text:'إنها حشرة عادية',correct:false},{text:'إنها ثديي',correct:false},{text:'إنها سمكة',correct:false}],
    explanation:'الكائن بـ 8 أرجل وجسم من جزأين هو عنكبوت وليس حشرة (الحشرات 6 أرجل).',
    goldenRule:'8 أرجل + جسمان = عنكبوت ≠ حشرة.',
    paragraph:'تمييز العناكب — ص ٣٤',
  },
  { id:'s4_184', unit:'u1', lesson:'u1l3', page:35, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'القشريات كالسرطان والروبيان من المفصليات التي تعيش في الماء.',
    correctAnswer:'true',
    explanation:'القشريات مفصليات مائية لها هيكل خارجي صلب كالسرطان والروبيان.',
    goldenRule:'القشريات = مفصليات مائية (سرطان، روبيان).',
    paragraph:'القشريات — ص ٣٥',
  },
];