// الوحدة الثانية — النظام البيئي — أسئلة إضافية

export const U2_EXTRA = [
  // ═══ الدرس 1: مكونات النظام البيئي (28 سؤال) ═══
  { id:'s4_201', unit:'u2', lesson:'u2l1', page:37, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'النظام البيئي هو المنطقة التي تتفاعل فيها المخلوقات الحية مع بعضها ومع بيئتها. ما أنواع العوامل فيه؟',
    options:[{text:'عوامل حيوية وعوامل غير حيوية',correct:true},{text:'نباتات وحيوانات فقط',correct:false},{text:'ماء وهواء فقط',correct:false},{text:'تربة وضوء فقط',correct:false}],
    explanation:'النظام البيئي يتكوّن من عوامل حيوية (كائنات حية) وعوامل غير حيوية (ماء، هواء، ضوء، تربة).',
    goldenRule:'النظام البيئي = حيوي + غير حيوي.',
    paragraph:'تعريف النظام البيئي — ص ٣٧',
  },
  { id:'s4_202', unit:'u2', lesson:'u2l1', page:38, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'النظام البيئي قد يكون كبيراً كالغابة أو صغيراً كحوض مائي صغير.',
    correctAnswer:'true',
    explanation:'النظم البيئية تتفاوت في الحجم من بركة صغيرة إلى غابة أو محيط.',
    goldenRule:'النظم البيئية متفاوتة الحجم (بركة → محيط).',
    paragraph:'أنواع النظم البيئية — ص ٣٨',
  },
  { id:'s4_203', unit:'u2', lesson:'u2l1', page:39, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'الشمس مصدر الطاقة في النظام البيئي. ما نوع هذا العامل؟',
    options:[{text:'عامل غير حيوي',correct:true},{text:'عامل حيوي',correct:false},{text:'كائن حي',correct:false},{text:'مخلوق حي',correct:false}],
    explanation:'الشمس عامل غير حيوي لأنها ليست كائناً حياً لكنها تمدّ النظام بالطاقة.',
    goldenRule:'الشمس = عامل غير حيوي (مصدر الطاقة).',
    paragraph:'الشمس — ص ٣٩',
  },
  { id:'s4_204', unit:'u2', lesson:'u2l1', page:40, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'أيّ مما يلي يُعدّ من العوامل الحيوية في النظام البيئي؟',
    options:[{text:'الأشجار والحيوانات والبكتيريا',correct:true},{text:'الضوء والماء',correct:false},{text:'التربة والحجارة',correct:false},{text:'الحرارة والرطوبة',correct:false}],
    explanation:'العوامل الحيوية هي المخلوقات الحية كالأشجار والحيوانات والبكتيريا.',
    goldenRule:'حيوي = كائن حي | غير حيوي = ماء، ضوء، تربة، حرارة.',
    paragraph:'العوامل الحيوية — ص ٤٠',
  },
  { id:'s4_205', unit:'u2', lesson:'u2l1', page:41, difficulty:'medium', bloom:'understand', type:'classify',
    question:'صنّف العوامل التالية في النظام البيئي:',
    categories:['عامل حيوي', 'عامل غير حيوي'],
    items:[
      {text:'الضفدع', correct_category:0},
      {text:'درجة الحرارة', correct_category:1},
      {text:'الطحالب', correct_category:0},
      {text:'الرطوبة', correct_category:1},
      {text:'الأسماك', correct_category:0},
      {text:'الرياح', correct_category:1},
    ],
    explanation:'حيوي: ضفدع، طحالب، أسماك. غير حيوي: حرارة، رطوبة، رياح.',
    goldenRule:'كل كائن حي = حيوي | كل ظاهرة طبيعية = غير حيوي.',
    paragraph:'تصنيف العوامل — ص ٤١',
  },
  { id:'s4_206', unit:'u2', lesson:'u2l1', page:42, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'الماء من العوامل غير الحيوية الضرورية لحياة جميع المخلوقات الحية.',
    correctAnswer:'true',
    explanation:'الماء عامل غير حيوي لا غنى عنه لحياة كل الكائنات الحية.',
    goldenRule:'الماء = عامل غير حيوي ضروري للحياة.',
    paragraph:'الماء — ص ٤٢',
  },
  { id:'s4_207', unit:'u2', lesson:'u2l1', page:43, difficulty:'medium', bloom:'apply', type:'multipleChoice',
    question:'إذا نقصت كمية الماء في نظام بيئي صحراوي، ماذا يحدث للكائنات الحية؟',
    options:[{text:'تتأثر حياتها وقد تموت بعضها',correct:true},{text:'تزداد أعدادها',correct:false},{text:'لا يتغير شيء',correct:false},{text:'تصبح أكبر حجماً',correct:false}],
    explanation:'نقص الماء يؤثر على حياة الكائنات وقد يسبب موت بعضها أو هجرتها.',
    goldenRule:'الماء = عامل محدد لحياة الكائنات في النظام البيئي.',
    paragraph:'تأثير الماء — ص ٤٣',
  },
  { id:'s4_208', unit:'u2', lesson:'u2l1', page:44, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'التربة من العوامل غير الحيوية المهمة. ما دورها بالنسبة للنباتات؟',
    options:[{text:'توفير الماء والأملاح والمواد الغذائية وتثبيت الجذور',correct:true},{text:'إنتاج الضوء',correct:false},{text:'تنظيم الحرارة فقط',correct:false},{text:'تخزين الهواء',correct:false}],
    explanation:'التربة توفّر للنبات الماء والأملاح الغذائية وتثبّت جذوره.',
    goldenRule:'التربة = ماء + أملاح + تثبيت للجذور.',
    paragraph:'التربة — ص ٤٤',
  },
  { id:'s4_209', unit:'u2', lesson:'u2l1', page:45, difficulty:'medium', bloom:'understand', type:'trueFalse',
    question:'درجة الحرارة تؤثر في توزيع الكائنات الحية في النظام البيئي.',
    correctAnswer:'true',
    explanation:'كل كائن حي يحتاج درجة حرارة مناسبة، واختلافها يؤثر في توزيعه الجغرافي.',
    goldenRule:'الحرارة = عامل يحدد توزيع الكائنات.',
    paragraph:'درجة الحرارة — ص ٤٥',
  },
  { id:'s4_210', unit:'u2', lesson:'u2l1', page:46, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'الضوء ضروري لعملية البناء الضوئي. ما الكائنات التي تحتاجه مباشرة؟',
    options:[{text:'النباتات فقط',correct:true},{text:'الأسود فقط',correct:false},{text:'البكتيريا فقط',correct:false},{text:'الفطريات فقط',correct:false}],
    explanation:'النباتات تحتاج الضوء للبناء الضوئي وصنع الغذاء.',
    goldenRule:'الضوء = شرط للبناء الضوئي في النباتات.',
    paragraph:'الضوء — ص ٤٦',
  },
  { id:'s4_211', unit:'u2', lesson:'u2l1', page:47, difficulty:'hard', bloom:'analyze', type:'multipleChoice',
    question:'إذا انعدم الضوء في نظام بيئي مائي عميق، كيف تتأثر النباتات؟',
    options:[{text:'لا تستطيع القيام بالبناء الضوئي',correct:true},{text:'تنمو بشكل أسرع',correct:false},{text:'تصبح أكبر',correct:false},{text:'لا تتأثر إطلاقاً',correct:false}],
    explanation:'بدون ضوء لا يحدث البناء الضوئي، فلا تصنع النباتات غذاءها وتتأثر.',
    goldenRule:'بلا ضوء → لا بناء ضوئي → لا غذاء للنبات.',
    paragraph:'الضوء والنباتات — ص ٤٧',
  },
  { id:'s4_212', unit:'u2', lesson:'u2l1', page:48, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'الهواء يحتوي على غازات ضرورية للحياة كالأكسجين وثاني أكسيد الكربون.',
    correctAnswer:'true',
    explanation:'الهواء يضمّ الأكسجين اللازم للتنفس وثاني أكسيد الكربون للبناء الضوئي.',
    goldenRule:'الهواء = أكسجين (تنفس) + ثاني أكسيد الكربون (بناء ضوئي).',
    paragraph:'الهواء — ص ٤٨',
  },
  { id:'s4_213', unit:'u2', lesson:'u2l1', page:38, difficulty:'medium', bloom:'apply', type:'multipleChoice',
    question:'أيّ الأمثلة التالية يُمثّل نظاماً بيئياً طبيعياً؟',
    options:[{text:'الغابة',correct:true},{text:'الحديقة المنزلية',correct:false},{text:'الحوض الزجاجي',correct:false},{text:'المزرعة',correct:false}],
    explanation:'الغابة نظام بيئي طبيعي يتكوّن دون تدخل الإنسان.',
    goldenRule:'غابة = نظام بيئي طبيعي | حديقة = نظام بيئي صناعي.',
    paragraph:'الأنظمة البيئية — ص ٣٨',
  },
  { id:'s4_214', unit:'u2', lesson:'u2l1', page:40, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'الحمام والورود والبكتيريا في الحديقة تُعدّ:',
    options:[{text:'عوامل حيوية',correct:true},{text:'عوامل غير حيوية',correct:false},{text:'عوامل مادية',correct:false},{text:'عوامل كيميائية',correct:false}],
    explanation:'الحمام والورود والبكتيريا كائنات حية فهي عوامل حيوية.',
    goldenRule:'كل كائن حي = عامل حيوي.',
    paragraph:'العوامل الحيوية — ص ٤٠',
  },
  { id:'s4_215', unit:'u2', lesson:'u2l1', page:42, difficulty:'medium', bloom:'understand', type:'trueFalse',
    question:'العوامل غير الحيوية تؤثر في العوامل الحيوية والعكس صحيح.',
    correctAnswer:'true',
    explanation:'الحرارة تؤثر في الكائنات، والكائنات تؤثر في التربة والهواء (كالنبات يُطلق أكسجين).',
    goldenRule:'تفاعل متبادل: حيوي ↔ غير حيوي.',
    paragraph:'تفاعل العوامل — ص ٤٢',
  },
  { id:'s4_216', unit:'u2', lesson:'u2l1', page:44, difficulty:'medium', bloom:'understand', type:'classify',
    question:'صنّف مكونات الغابة إلى حيوية وغير حيوية:',
    categories:['حيوي', 'غير حيوي'],
    items:[
      {text:'الأشجار', correct_category:0},
      {text:'الغزلان', correct_category:0},
      {text:'الشمس', correct_category:1},
      {text:'التربة', correct_category:1},
      {text:'الطيور', correct_category:0},
      {text:'الأمطار', correct_category:1},
    ],
    explanation:'حيوي: أشجار، غزلان، طيور. غير حيوي: شمس، تربة، أمطار.',
    goldenRule:'في الغابة: كائنات = حيوي | ظواهر = غير حيوي.',
    paragraph:'نظام الغابة — ص ٤٤',
  },
  { id:'s4_217', unit:'u2', lesson:'u2l1', page:46, difficulty:'hard', bloom:'evaluate', type:'multipleChoice',
    question:'لماذا يُعدّ الماء أهم عامل غير حيوي في النظام البيئي المائي؟',
    options:[{text:'لأنه الوسط الذي تعيش فيه الكائنات المائية',correct:true},{text:'لأنه ينتج الضوء',correct:false},{text:'لأنه يحمي من الأمراض',correct:false},{text:'لأنه يُنتج الغذاء',correct:false}],
    explanation:'الماء هو الوسط الذي تعيش وتتنفس وتتكاثر فيه الكائنات المائية.',
    goldenRule:'الماء = وسط حياة الكائنات المائية.',
    paragraph:'النظام البيئي المائي — ص ٤٦',
  },
  { id:'s4_218', unit:'u2', lesson:'u2l1', page:47, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'الأنظمة البيئية تختلف باختلاف العوامل غير الحيوية كالمناخ والتربة.',
    correctAnswer:'true',
    explanation:'الاختلاف في المناخ والتربة يُنتج أنظمة بيئية مختلفة كالصحراء والغابة والبحر.',
    goldenRule:'مناخ + تربة = نوع النظام البيئي.',
    paragraph:'تنوع النظم البيئية — ص ٤٧',
  },
  { id:'s4_219', unit:'u2', lesson:'u2l1', page:43, difficulty:'medium', bloom:'apply', type:'multipleChoice',
    question:'في صحراء قليلة الماء، أيّ الكائنات أكثر تكيفاً للعيش فيها؟',
    options:[{text:'نباتات ذات جذور عميقة وأوراق صغيرة',correct:true},{text:'نباتات ذات أوراق عريضة',correct:false},{text:'أسماك',correct:false},{text:'طيور مائية',correct:false}],
    explanation:'نباتات الصحراء لها جذور عميقة وأوراق صغيرة لتقليل فقد الماء.',
    goldenRule:'تكيف الصحراء = جذور عميقة + أوراق صغيرة.',
    paragraph:'التكيف في الصحراء — ص ٤٣',
  },
  { id:'s4_220', unit:'u2', lesson:'u2l1', page:48, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'غاز ثاني أكسيد الكربون يستخدمه النبات في:',
    options:[{text:'البناء الضوئي',correct:true},{text:'التنفس فقط',correct:false},{text:'التكاثر',correct:false},{text:'هضم الطعام',correct:false}],
    explanation:'النبات يستخدم ثاني أكسيد الكربون في البناء الضوئي لصنع الغذاء.',
    goldenRule:'CO₂ = غذاء النبات (في البناء الضوئي).',
    paragraph:'ثاني أكسيد الكربون — ص ٤٨',
  },
  { id:'s4_221', unit:'u2', lesson:'u2l1', page:41, difficulty:'medium', bloom:'understand', type:'trueFalse',
    question:'البكتيريا والفطريات في التربة تُعدّ من العوامل الحيوية المفيدة للنظام البيئي.',
    correctAnswer:'true',
    explanation:'البكتيريا والفطريات تُحلّل المواد العضوية وتُخصّب التربة فتُعدّ عوامل حيوية مفيدة.',
    goldenRule:'بكتيريا + فطريات = تحليل وتخصيب التربة.',
    paragraph:'البكتيريا في التربة — ص ٤١',
  },
  { id:'s4_222', unit:'u2', lesson:'u2l1', page:45, difficulty:'hard', bloom:'analyze', type:'multipleChoice',
    question:'ارتفاع درجة الحرارة في نظام بيئي قد يؤدي إلى:',
    options:[{text:'هجرة بعض الكائنات أو موتها',correct:true},{text:'زيادة كل الأنواع',correct:false},{text:'لا تأثير',correct:false},{text:'نمو النباتات بشكل أسرع',correct:false}],
    explanation:'الحرارة المرتفعة قد تُسبب هجرة أو موت الكائنات الحساسة لها.',
    goldenRule:'الحرارة المرتفعة = هجرة/موت الكائنات الحساسة.',
    paragraph:'تأثير الحرارة — ص ٤٥',
  },
  { id:'s4_223', unit:'u2', lesson:'u2l1', page:39, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'النظام البيئي هو مكان تفاعل الكائنات الحية مع بيئتها غير الحية.',
    correctAnswer:'true',
    explanation:'النظام البيئي = تفاعل الكائنات الحية مع العوامل غير الحية في مكان محدد.',
    goldenRule:'النظام البيئي = تفاعل حيوي + غير حيوي.',
    paragraph:'تعريف النظام البيئي — ص ٣٩',
  },
  { id:'s4_224', unit:'u2', lesson:'u2l1', page:46, difficulty:'medium', bloom:'apply', type:'multipleChoice',
    question:'أيّ العوامل التالية لا يحتاجها النبات مباشرة؟',
    options:[{text:'اللحوم',correct:true},{text:'الضوء',correct:false},{text:'الماء',correct:false},{text:'ثاني أكسيد الكربون',correct:false}],
    explanation:'النبات لا يحتاج اللحوم لأنه يصنع غذاءه بالبناء الضوئي.',
    goldenRule:'النبات يحتاج: ضوء + ماء + CO₂ (لا لحوم).',
    paragraph:'احتياجات النبات — ص ٤٦',
  },
  { id:'s4_225', unit:'u2', lesson:'u2l1', page:42, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'العوامل غير الحيوية في النظام البيئي تشمل:',
    options:[{text:'الضوء والماء والهواء والتربة والحرارة',correct:true},{text:'النباتات فقط',correct:false},{text:'الحيوانات فقط',correct:false},{text:'البكتيريا فقط',correct:false}],
    explanation:'العوامل غير الحيوية: ضوء، ماء، هواء، تربة، حرارة، رطوبة.',
    goldenRule:'غير حيوي = ضوء + ماء + هواء + تربة + حرارة.',
    paragraph:'العوامل غير الحيوية — ص ٤٢',
  },
  { id:'s4_226', unit:'u2', lesson:'u2l1', page:44, difficulty:'hard', bloom:'evaluate', type:'trueFalse',
    question:'تلوث الماء في نظام بيئي مائي يؤثر على الكائنات الحية فيه وقد يقضي على بعضها.',
    correctAnswer:'true',
    explanation:'التلوث يُغيّر العوامل غير الحيوية (الماء) فيؤثر سلباً على الكائنات الحية.',
    goldenRule:'تلوث الماء → اختلال النظام البيئي → موت الكائنات.',
    paragraph:'تأثير التلوث — ص ٤٤',
  },
  { id:'s4_227', unit:'u2', lesson:'u2l1', page:47, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'المناطق الجبلية والساحلية والصحراوية تختلف في:',
    options:[{text:'العوامل غير الحيوية كالمناخ',correct:true},{text:'عدد الكواكب',correct:false},{text:'لون السماء',correct:false},{text:'حجم القمر',correct:false}],
    explanation:'الاختلاف بين المناطق يأتي من اختلاف العوامل غير الحيوية كالمناخ والماء والتربة.',
    goldenRule:'مناطق مختلفة = عوامل غير حيوية مختلفة.',
    paragraph:'تنوع المناطق — ص ٤٧',
  },
  { id:'s4_228', unit:'u2', lesson:'u2l1', page:48, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'الأكسجين غاز ضروري لتنفس معظم الكائنات الحية في النظام البيئي.',
    correctAnswer:'true',
    explanation:'الأكسجين ضروري لتنفس الحيوانات والنباتات (ليلاً) في النظام البيئي.',
    goldenRule:'الأكسجين = غاز التنفس للكائنات الحية.',
    paragraph:'الأكسجين — ص ٤٨',
  },

  // ═══ الدرس 2: العلاقات في النظام البيئي (28 سؤال) ═══
  { id:'s4_229', unit:'u2', lesson:'u2l2', page:49, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'المخلوقات التي تصنع غذاءها بنفسها تُسمّى:',
    options:[{text:'المنتجات',correct:true},{text:'المستهلكات',correct:false},{text:'المحللات',correct:false},{text:'المفترسات',correct:false}],
    explanation:'المنتجات كائنات تصنع غذاءها بالبناء الضوئي كالنباتات.',
    goldenRule:'المنتج = يصنع غذاءه (نبات).',
    paragraph:'المنتجات — ص ٤٩',
  },
  { id:'s4_230', unit:'u2', lesson:'u2l2', page:50, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'المستهلكات كائنات لا تستطيع صنع غذائها وتحصل عليه من أكل كائنات أخرى.',
    correctAnswer:'true',
    explanation:'المستهلكات تأكل الكائنات الأخرى أو منتجاتها لأنها لا تصنع غذاءها.',
    goldenRule:'المستهلك = يأكل الغذاء جاهزاً (لا يصنعه).',
    paragraph:'المستهلكات — ص ٥٠',
  },
  { id:'s4_231', unit:'u2', lesson:'u2l2', page:51, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'الغزال يأكل العشب، والأسد يأكل الغزال. في هذه السلسلة، الغزال يُعدّ:',
    options:[{text:'مستهلكاً أولياً',correct:true},{text:'منتجاً',correct:false},{text:'ممحللاً',correct:false},{text:'مفترساً ثانوياً',correct:false}],
    explanation:'الغزال يأكل المنتج (العشب) فيُعدّ مستهلكاً أولياً.',
    goldenRule:'مستهلك أول = يأكل المنتج مباشرة.',
    paragraph:'المستهلكات — ص ٥١',
  },
  { id:'s4_232', unit:'u2', lesson:'u2l2', page:52, difficulty:'medium', bloom:'apply', type:'ordering',
    question:'رتّب السلسلة الغذائية من المنتج إلى المستهلك النهائي:',
    items:['العشب', 'الأسد', 'الغزال'],
    correctOrder:[0, 2, 1],
    explanation:'العشب (منتج) → الغزال (مستهلك أول) → الأسد (مستهلك ثانٍ).',
    goldenRule:'السلسلة: منتج → مستهلك أول → مستهلك ثانٍ.',
    paragraph:'السلسلة الغذائية — ص ٥٢',
  },
  { id:'s4_233', unit:'u2', lesson:'u2l2', page:53, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'المحللات كائنات تُحلّل بقايا الكائنات الميتة. أيّ مما يلي من المحللات؟',
    options:[{text:'البكتيريا والفطريات',correct:true},{text:'الأسود',correct:false},{text:'النباتات',correct:false},{text:'الأبقار',correct:false}],
    explanation:'البكتيريا والفطريات من المحللات التي تُحلّل المواد العضوية الميتة.',
    goldenRule:'المحللات = بكتيريا + فطريات (تحليل الميت).',
    paragraph:'المحللات — ص ٥٣',
  },
  { id:'s4_234', unit:'u2', lesson:'u2l2', page:54, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'المفترس كائن حي يصطاد كائنات حية أخرى ويتغذى عليها.',
    correctAnswer:'true',
    explanation:'المفترس يصطاد فريسته الحية كالأسد والنمر والصقر.',
    goldenRule:'المفترس = يصطاد فريسة حية.',
    paragraph:'المفترسات — ص ٥٤',
  },
  { id:'s4_235', unit:'u2', lesson:'u2l2', page:55, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'العلاقة بين الأسد والغزال هي علاقة:',
    options:[{text:'افتراس',correct:true},{text:'تعايش',correct:false},{text:'تنافس',correct:false},{text:'تطفل',correct:false}],
    explanation:'الأسد يفترس الغزال ويتغذى عليه، فالعلاقة افتراس.',
    goldenRule:'افتراس = مفترس يأكل فريسة.',
    paragraph:'الافتراس — ص ٥٥',
  },
  { id:'s4_236', unit:'u2', lesson:'u2l2', page:56, difficulty:'medium', bloom:'understand', type:'classify',
    question:'صنّف الكائنات التالية حسب نوعها في السلسلة الغذائية:',
    categories:['منتج', 'مستهلك'],
    items:[
      {text:'العشب', correct_category:0},
      {text:'الشجرة', correct_category:0},
      {text:'الأرنب', correct_category:1},
      {text:'الثعلب', correct_category:1},
      {text:'الطحالب', correct_category:0},
      {text:'السمكة', correct_category:1},
    ],
    explanation:'منتج: عشب، شجرة، طحالب. مستهلك: أرنب، ثعلب، سمكة.',
    goldenRule:'نبات/طحالب = منتج | حيوان = مستهلك.',
    paragraph:'تصنيف الكائنات — ص ٥٦',
  },
  { id:'s4_237', unit:'u2', lesson:'u2l2', page:57, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'التطفل علاقة بين كائنين يستفيد فيها أحدهما ويضرّ الآخر. ما الكائن المستفيد؟',
    options:[{text:'الطفيل',correct:true},{text:'المضيف',correct:false},{text:'المنتج',correct:false},{text:'المحلل',correct:false}],
    explanation:'الطفيل يستفيد من المضيف ويضرّه، كالبراغيث على جسم الكلب.',
    goldenRule:'تطفل = طفيل (يستفيد) + مضيف (يُضر).',
    paragraph:'التطفل — ص ٥٧',
  },
  { id:'s4_238', unit:'u2', lesson:'u2l2', page:58, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'التعايش علاقة بين كائنين يستفيد فيها أحدهما دون ضرر أو فائدة للآخر.',
    correctAnswer:'true',
    explanation:'التعايش: كائن يستفيد والآخر لا يستفيد ولا يتضرر، كالسمكة المرافقة لسمك القرش.',
    goldenRule:'تعايش = مستفيد + لا متضرر/مستفيد.',
    paragraph:'التعايش — ص ٥٨',
  },
  { id:'s4_239', unit:'u2', lesson:'u2l2', page:59, difficulty:'hard', bloom:'analyze', type:'multipleChoice',
    question:'النحلة تتغذى من رحيق الأزهار وفي نفس الوقت تنقل حبوب اللقاح بينها. ما نوع هذه العلاقة؟',
    options:[{text:'تعاون (تبادل منفعة)',correct:true},{text:'تطفل',correct:false},{text:'افتراس',correct:false},{text:'تنافس',correct:false}],
    explanation:'النحلة والأزهار تستفيدان معاً: النحلة تأخذ الرحيق والزهرة تُلقّح. علاقة تعاون.',
    goldenRule:'تعاون = تبادل منفعة (نحلة ↔ زهرة).',
    paragraph:'التعاون — ص ٥٩',
  },
  { id:'s4_240', unit:'u2', lesson:'u2l2', page:60, difficulty:'medium', bloom:'understand', type:'trueFalse',
    question:'التنافس بين الكائنات الحية يكون على الموارد كالغذاء والماء والضوء.',
    correctAnswer:'true',
    explanation:'التنافس يكون على مورد محدود كالغذاء أو الماء أو المكان أو الضوء.',
    goldenRule:'التنافس = صراع على مورد محدود.',
    paragraph:'التنافس — ص ٦٠',
  },
  { id:'s4_241', unit:'u2', lesson:'u2l2', page:50, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'الأرنب يأكل الجزر. الأرنب في السلسلة الغذائية يُعدّ:',
    options:[{text:'مستهلكاً أولياً (عاشباً)',correct:true},{text:'منتجاً',correct:false},{text:'مفترساً',correct:false},{text:'ممحللاً',correct:false}],
    explanation:'الأرنب يأكل النبات (المنتج) فهو مستهلك أولي (عاشب).',
    goldenRule:'العاشب = مستهلك أول (يأكل النبات).',
    paragraph:'المستهلك الأول — ص ٥٠',
  },
  { id:'s4_242', unit:'u2', lesson:'u2l2', page:51, difficulty:'medium', bloom:'apply', type:'multipleChoice',
    question:'في سلسلة: طحالب → روبيان → سمكة صغيرة → سمكة كبيرة. ما المستهلك الثالث؟',
    options:[{text:'السمكة الكبيرة',correct:true},{text:'الطحالب',correct:false},{text:'الروبيان',correct:false},{text:'السمكة الصغيرة',correct:false}],
    explanation:'السمكة الكبيرة هي المستهلك الثالث في هذه السلسلة.',
    goldenRule:'المستهلك الثالث = الرابع في السلسلة بعد المنتج.',
    paragraph:'السلاسل الغذائية — ص ٥١',
  },
  { id:'s4_243', unit:'u2', lesson:'u2l2', page:53, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'المحللات تُعيد المواد الغذائية للتربة لتستفيد منها النباتات من جديد.',
    correctAnswer:'true',
    explanation:'المحللات تُحلّل الميت إلى مواد بسيطة تعود للتربة وتستفيد منها النباتات.',
    goldenRule:'المحللات = إعادة المواد للتربة → النبات.',
    paragraph:'دور المحللات — ص ٥٣',
  },
  { id:'s4_244', unit:'u2', lesson:'u2l2', page:55, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'الضبع يأكل بقايا فريسة الأسد. ما نوع هذا السلوك؟',
    options:[{text:'التقميش (أكل الجيف)',correct:true},{text:'الافتراس',correct:false},{text:'التطفل',correct:false},{text:'التعايش',correct:false}],
    explanation:'الضبع يأكل بقايا الحيوانات الميتة (الجيف) وهو ما يُسمّى التقميش.',
    goldenRule:'التقميش = أكل الجيف (بقايا الميت).',
    paragraph:'التقميش — ص ٥٥',
  },
  { id:'s4_245', unit:'u2', lesson:'u2l2', page:57, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'البراغيث التي تعيش على جسم الكلب علاقتها بالكلب هي:',
    options:[{text:'تطفل',correct:true},{text:'تعاون',correct:false},{text:'تنافس',correct:false},{text:'افتراس',correct:false}],
    explanation:'البراغيث تتغذى على دم الكلب وتضرّه، فالعلاقة تطفل.',
    goldenRule:'براغيث على كلب = تطفل (استفادة + ضرر).',
    paragraph:'التطفل — ص ٥٧',
  },
  { id:'s4_246', unit:'u2', lesson:'u2l2', page:59, difficulty:'hard', bloom:'analyze', type:'trueFalse',
    question:'في علاقة التعاون بين الكائنين، يستفيد كل منهما من الآخر.',
    correctAnswer:'true',
    explanation:'التعاون (التبادل) يعني أن كلا الكائنين يستفيدان من العلاقة.',
    goldenRule:'تعاون = كلاهما يستفيد (تبادل منفعة).',
    paragraph:'التعاون — ص ٥٩',
  },
  { id:'s4_247', unit:'u2', lesson:'u2l2', page:60, difficulty:'medium', bloom:'apply', type:'multipleChoice',
    question:'نبتتان تنموان قرب بعضهما وتتنافسان على الضوء والماء. ما نوع العلاقة؟',
    options:[{text:'تنافس',correct:true},{text:'تعاون',correct:false},{text:'تطفل',correct:false},{text:'تعايش',correct:false}],
    explanation:'التنافس بين النباتين على الضوء والماء علاقة تنافس.',
    goldenRule:'نباتان + مورد محدود = تنافس.',
    paragraph:'التنافس — ص ٦٠',
  },
  { id:'s4_248', unit:'u2', lesson:'u2l2', page:52, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'السلسلة الغذائية تبدأ دائماً بالمنتجات (النباتات).',
    correctAnswer:'true',
    explanation:'السلسلة الغذائية تبدأ بالمنتج الذي يصنع الغذاء ثم تتبعه المستهلكات.',
    goldenRule:'السلسلة الغذائية تبدأ بالمنتج.',
    paragraph:'بداية السلسلة — ص ٥٢',
  },
  { id:'s4_249', unit:'u2', lesson:'u2l2', page:54, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'الشبكة الغذائية تختلف عن السلسلة الغذائية في أنّها:',
    options:[{text:'تضم عدة سلاسل غذائية مترابطة',correct:true},{text:'سلسلة واحدة فقط',correct:false},{text:'تبدأ بالمفترس',correct:false},{text:'لا تشمل المنتجات',correct:false}],
    explanation:'الشبكة الغذائية مجموعة سلاسل غذائية مترابطة في النظام البيئي.',
    goldenRule:'الشبكة الغذائية = سلاسل مترابطة.',
    paragraph:'الشبكة الغذائية — ص ٥٤',
  },
  { id:'s4_250', unit:'u2', lesson:'u2l2', page:56, difficulty:'hard', bloom:'evaluate', type:'trueFalse',
    question:'الإفراط في صيد الأسماك في بحيرة قد يُخلّ بالشبكة الغذائية فيها.',
    correctAnswer:'true',
    explanation:'صيد كميات كبيرة من الأسماك يُؤثر على السلسلة والشبكة الغذائية في البحيرة.',
    goldenRule:'صيد مفرط = اختلال الشبكة الغذائية.',
    paragraph:'تأثير الصيد — ص ٥٦',
  },
  { id:'s4_251', unit:'u2', lesson:'u2l2', page:58, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'القراش يصطاد الأسماك الصغيرة. ما دوره في السلسلة؟',
    options:[{text:'مستهلك ثانٍ (مفترس)',correct:true},{text:'منتج',correct:false},{text:'ممحلل',correct:false},{text:'مستهلك أول',correct:false}],
    explanation:'القرش مفترس يصطاد الأسماك فهو مستهلك ثانٍ.',
    goldenRule:'المفترس = مستهلك ثانٍ (يصطاد الحي).',
    paragraph:'المفترسات — ص ٥٨',
  },
  { id:'s4_252', unit:'u2', lesson:'u2l2', page:59, difficulty:'medium', bloom:'understand', type:'classify',
    question:'صنّف العلاقات التالية:',
    categories:['افتراس', 'تعاون'],
    items:[
      {text:'أسد يأكل غزالاً', correct_category:0},
      {text:'نحلة وزهرة', correct_category:1},
      {text:'صقر يصطاد عصفوراً', correct_category:0},
      {text:'بكتيريا في أمعاء إنسان', correct_category:1},
      {text:'ثعلب يأكل أرنباً', correct_category:0},
    ],
    explanation:'افتراس: أسد/غزال، صقر/عصفور، ثعلب/أرنب. تعاون: نحلة/زهرة، بكتيريا/أمعاء.',
    goldenRule:'افتراس = ضرر | تعاون = تبادل منفعة.',
    paragraph:'أنواع العلاقات — ص ٥٩',
  },
  { id:'s4_253', unit:'u2', lesson:'u2l2', page:60, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'كل كائن حي في النظام البيئي له دور محدد يحافظ على التوازن.',
    correctAnswer:'true',
    explanation:'لكل كائن دور (منتج، مستهلك، محلل) يساهم في توازن النظام البيئي.',
    goldenRule:'كل كائن = دور → توازن النظام البيئي.',
    paragraph:'التوازن البيئي — ص ٦٠',
  },
  { id:'s4_254', unit:'u2', lesson:'u2l2', page:53, difficulty:'medium', bloom:'apply', type:'multipleChoice',
    question:'إذا اختفى المحللات من النظام البيئي، ماذا يتراكم؟',
    options:[{text:'بقايا الكائنات الميتة دون تحليل',correct:true},{text:'النباتات فقط',correct:false},{text:'الضوء',correct:false},{text:'الماء',correct:false}],
    explanation:'بدون المحللات تتراكم بقايا الكائنات الميتة دون تحليل وتُلوّث البيئة.',
    goldenRule:'بلا محللات → تراكم الميت → تلوث.',
    paragraph:'دور المحللات — ص ٥٣',
  },
  { id:'s4_255', unit:'u2', lesson:'u2l2', page:55, difficulty:'hard', bloom:'analyze', type:'trueFalse',
    question:'المفترس الكبير يضرّ النظام البيئي دائماً ويجب إبادته.',
    correctAnswer:'false',
    explanation:'المفترس ضروري لتوازن النظام البيئي إذ يتحكم في أعداد الفرائس.',
    goldenRule:'المفترس = ضامن التوازن (لا يجب إبادته).',
    paragraph:'دور المفترس — ص ٥٥',
  },
  { id:'s4_256', unit:'u2', lesson:'u2l2', page:57, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'البلهارسيا كائن طفيلي يعيش في:',
    options:[{text:'دم الإنسان',correct:true},{text:'التربة فقط',correct:false},{text:'الهواء',correct:false},{text:'الشمس',correct:false}],
    explanation:'البلهارسيا طفيلي يعيش في دم الإنسان ويُسبب مرض البلهارسيا.',
    goldenRule:'البلهارسيا = طفيلي في دم الإنسان.',
    paragraph:'الطفيليات — ص ٥٧',
  },

  // ═══ الدرس 3: التغيرات في النظام البيئي (28 سؤال) ═══
  { id:'s4_257', unit:'u2', lesson:'u2l3', page:61, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'التغيرات في النظام البيئي قد تكون طبيعية أو ناتجة عن:',
    options:[{text:'نشاط الإنسان',correct:true},{text:'حركة القمر',correct:false},{text:'لون السماء',correct:false},{text:'حجم الشمس',correct:false}],
    explanation:'التغيرات في النظام البيئي طبيعية (كالجفاف) أو بشرية (كالقطع والتلوث).',
    goldenRule:'تغيرات النظام: طبيعية + بشرية.',
    paragraph:'تغيرات النظام البيئي — ص ٦١',
  },
  { id:'s4_258', unit:'u2', lesson:'u2l3', page:62, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'الحرائق والفيضانات والجفاف من التغيرات الطبيعية في النظام البيئي.',
    correctAnswer:'true',
    explanation:'الحرائق والفيضانات والجفاف تغيرات طبيعية تؤثر على النظام البيئي.',
    goldenRule:'تغيرات طبيعية: حريق + فيضان + جفاف.',
    paragraph:'التغيرات الطبيعية — ص ٦٢',
  },
  { id:'s4_259', unit:'u2', lesson:'u2l3', page:63, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'قطع الأشجار بكثرة في الغابة يؤدي إلى:',
    options:[{text:'تدمير موئل الكائنات وتقليل التنوع البيولوجي',correct:true},{text:'زيادة عدد الحيوانات',correct:false},{text:'تحسن المناخ',correct:false},{text:'زيادة الماء',correct:false}],
    explanation:'قطع الأشجار يدمر بيئة الكائنات ويقلل التنوع البيولوجي ويزيد التصحر.',
    goldenRule:'قطع الأشجار = تدمير موئل + تصحر.',
    paragraph:'قطع الأشجار — ص ٦٣',
  },
  { id:'s4_260', unit:'u2', lesson:'u2l3', page:64, difficulty:'medium', bloom:'understand', type:'classify',
    question:'صنّف التغيرات التالية إلى طبيعية أو بشرية:',
    categories:['تغير طبيعي', 'تغير بشري'],
    items:[
      {text:'البراكين', correct_category:0},
      {text:'قطع الغابات', correct_category:1},
      {text:'الفيضانات', correct_category:0},
      {text:'التلوث', correct_category:1},
      {text:'الجفاف', correct_category:0},
      {text:'الصيد الجائر', correct_category:1},
    ],
    explanation:'طبيعي: براكين، فيضانات، جفاف. بشرية: قطع غابات، تلوث، صيد جائر.',
    goldenRule:'طبيعي = بلا تدخل بشرية | بشرية = بنشاط الإنسان.',
    paragraph:'أنواع التغيرات — ص ٦٤',
  },
  { id:'s4_261', unit:'u2', lesson:'u2l3', page:65, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'التوازن في النظام البيئي يعني:',
    options:[{text:'حفظ أعداد الكائنات وتنوعها',correct:true},{text:'زيادة المفترسات فقط',correct:false},{text:'إزالة النباتات',correct:false},{text:'تقليل الماء',correct:false}],
    explanation:'التوازن البيئي يعني بقاء أعداد الكائنات وتنوعها مستقراً.',
    goldenRule:'التوازن = استقرار الأعداد والتنوع.',
    paragraph:'التوازن البيئي — ص ٦٥',
  },
  { id:'s4_262', unit:'u2', lesson:'u2l3', page:66, difficulty:'medium', bloom:'understand', type:'trueFalse',
    question:'الصيد الجائر للحيوانات يهدد التوازن البيئي وقد يؤدي لانقراض بعض الأنواع.',
    correctAnswer:'true',
    explanation:'الصيد الجائر يقلل أعداد الحيوانات ويهدد بالانقراض ويخلّ بالتوازن.',
    goldenRule:'صيد جائر = انقراض + اختلال.',
    paragraph:'الصيد الجائر — ص ٦٦',
  },
  { id:'s4_263', unit:'u2', lesson:'u2l3', page:67, difficulty:'hard', bloom:'analyze', type:'multipleChoice',
    question:'إذا انقرض نوع من النباتات في نظام بيئي، ماذا يحدث للكائنات التي تعتمد عليه؟',
    options:[{text:'تنقص أعدادها أو تنقرض هي الأخرى',correct:true},{text:'تزداد أعدادها',correct:false},{text:'لا تتأثر',correct:false},{text:'تصبح مفترسات',correct:false}],
    explanation:'انقراض نبات يؤثر على الكائنات التي تتغذى عليه فتنقص أعدادها أو تنقرض.',
    goldenRule:'انقراض منتج → انقراض مستهلك.',
    paragraph:'التأثير المتسلسل — ص ٦٧',
  },
  { id:'s4_264', unit:'u2', lesson:'u2l3', page:68, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'التصحر ظاهرة تنتج عن:',
    options:[{text:'قطع الأشجار والرعي الجائر ونقص الماء',correct:true},{text:'كثرة الأمطار',correct:false},{text:'زيادة النباتات',correct:false},{text:'برودة الجو',correct:false}],
    explanation:'التصحر ينتج من قطع الأشجار والرعي الجائر ونقص الماء والجفاف.',
    goldenRule:'التصحر = قطع + رعي جائر + جفاف.',
    paragraph:'التصحر — ص ٦٨',
  },
  { id:'s4_265', unit:'u2', lesson:'u2l3', page:69, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'التلوث من أبرز أسباب تدهور النظام البيئي.',
    correctAnswer:'true',
    explanation:'تلوث الماء والهواء والتربة من أهم أسباب تدهور النظام البيئي.',
    goldenRule:'تلوث = تدهور النظام البيئي.',
    paragraph:'التلوث — ص ٦٩',
  },
  { id:'s4_266', unit:'u2', lesson:'u2l3', page:70, difficulty:'medium', bloom:'apply', type:'multipleChoice',
    question:'لتقليل التصحر وحماية البيئة، نسعى إلى:',
    options:[{text:'التشجير والحد من الرعي الجائر',correct:true},{text:'قطع المزيد من الأشجار',correct:false},{text:'رمي النفايات',correct:false},{text:'إبادة الحيوانات',correct:false}],
    explanation:'التشجير والحد من الرعي الجائر من أهم طرق مكافحة التصحر.',
    goldenRule:'مكافحة التصحر = تشجير + تنظيم رعي.',
    paragraph:'مكافحة التصحر — ص ٧٠',
  },
  { id:'s4_267', unit:'u2', lesson:'u2l3', page:71, difficulty:'medium', bloom:'understand', type:'trueFalse',
    question:'المحميات الطبيعية مناطق تُحمى فيها الكائنات الحية وموائلها من التدمير.',
    correctAnswer:'true',
    explanation:'المحميات الطبيعية مناطق محمية تُصان فيها الكائنات الحية وموائلها من التدمير.',
    goldenRule:'المحميات = حماية الكائنات + الموائل.',
    paragraph:'المحميات الطبيعية — ص ٧١',
  },
  { id:'s4_268', unit:'u2', lesson:'u2l3', page:72, difficulty:'hard', bloom:'evaluate', type:'multipleChoice',
    question:'لماذا يُعدّ حفظ التنوع البيولوجي مهماً؟',
    options:[{text:'لأنه يحفظ التوازن البيئي ويحمي الأنواع من الانقراض',correct:true},{text:'لأنه يزيد التلوث',correct:false},{text:'لأنه يقلل الغذاء',correct:false},{text:'لأنه لا فائدة منه',correct:false}],
    explanation:'حفظ التنوع البيولوجي يحفظ التوازن ويحمي الأنواع ويضمن استمرار الحياة.',
    goldenRule:'التنوع البيولوجي = توازن + حماية + استمرار.',
    paragraph:'التنوع البيولوجي — ص ٧٢',
  },
  { id:'s4_269', unit:'u2', lesson:'u2l3', page:62, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'الفيضانات تؤثر على النظام البيئي بـ:',
    options:[{text:'إغراق المناطق وتغيير التربة وتشريد الكائنات',correct:true},{text:'زيادة الضوء',correct:false},{text:'تقليل الماء',correct:false},{text:'إنتاج الغذاء',correct:false}],
    explanation:'الفيضانات تُغرق المناطق وتُغيّر التربة وتُشرد الكائنات الحية.',
    goldenRule:'فيضان = إغراق + تغيير تربة + تشريد.',
    paragraph:'الفيضانات — ص ٦٢',
  },
  { id:'s4_270', unit:'u2', lesson:'u2l3', page:64, difficulty:'medium', bloom:'understand', type:'trueFalse',
    question:'الاحتباس الحراري ظاهرة تؤدي إلى ارتفاع درجة حرارة الأرض وتغير المناخ.',
    correctAnswer:'true',
    explanation:'الاحتباس الحراري يرفع حرارة الأرض ويُغيّر المناخ ويؤثر على النظم البيئية.',
    goldenRule:'احتباس حراري = ارتفاع حرارة الأرض + تغير مناخ.',
    paragraph:'الاحتباس الحراري — ص ٦٤',
  },
  { id:'s4_271', unit:'u2', lesson:'u2l3', page:66, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'الأنواع المهددة بالانقراض هي:',
    options:[{text:'أنواع قلت أعدادها كثيراً ومعرضة للزوال',correct:true},{text:'أنواع كثيرة العدد',correct:false},{text:'أنواع جديدة',correct:false},{text:'أنواع لا تتأثر',correct:false}],
    explanation:'الأنواع المهددة بالانقراض قلّت أعدادها جداً وقد تزول إذا لم تُحمَ.',
    goldenRule:'مهدد بالانقراض = أعداد قليلة جداً + خطر الزوال.',
    paragraph:'الأنواع المهددة — ص ٦٦',
  },
  { id:'s4_272', unit:'u2', lesson:'u2l3', page:68, difficulty:'medium', bloom:'apply', type:'multipleChoice',
    question:'أيّ التصرفات التالية يساهم في حماية النظام البيئي؟',
    options:[{text:'إعادة تدوير النفايات وزراعة الأشجار',correct:true},{text:'رمي النفايات في النهر',correct:false},{text:'قطع الغابات',correct:false},{text:'صيد الحيوانات النادرة',correct:false}],
    explanation:'إعادة التدوير والتشجير من أهم سبل حماية النظام البيئي.',
    goldenRule:'حماية البيئة = تدوير + تشجير + ترشيد.',
    paragraph:'حماية البيئة — ص ٦٨',
  },
  { id:'s4_273', unit:'u2', lesson:'u2l3', page:70, difficulty:'hard', bloom:'analyze', type:'trueFalse',
    question:'إدخال نوع جديد من الكائنات إلى نظام بيئي قد يخلّ بتوازنه.',
    correctAnswer:'true',
    explanation:'إدخال نوع جديد قد ينافس الأنواع المحلية ويخلّ بتوازن النظام البيئي.',
    goldenRule:'إدخال نوع غريب = اختلال محتمل للتوازن.',
    paragraph:'إدخال الأنواع — ص ٧٠',
  },
  { id:'s4_274', unit:'u2', lesson:'u2l3', page:71, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'من طرق حماية البيئة:',
    options:[{text:'ترشيد استهلاك الماء والكهرباء',correct:true},{text:'زيادة التلوث',correct:false},{text:'قطع الأشجار',correct:false},{text:'إبادة الحيوانات',correct:false}],
    explanation:'ترشيد استهلاك الماء والكهرباء من أهم طرق حماية البيئة.',
    goldenRule:'ترشيد = حماية موارد البيئة.',
    paragraph:'حماية البيئة — ص ٧١',
  },
  { id:'s4_275', unit:'u2', lesson:'u2l3', page:72, difficulty:'medium', bloom:'understand', type:'classify',
    question:'صنّف التصرفات التالية:',
    categories:['يحمي البيئة', 'يضرّ البيئة'],
    items:[
      {text:'زراعة الأشجار', correct_category:0},
      {text:'رمي النفايات في البحر', correct_category:1},
      {text:'إعادة تدوير الورق', correct_category:0},
      {text:'قطع الغابات', correct_category:1},
      {text:'استخدام النقل العام', correct_category:0},
      {text:'الصيد الجائر', correct_category:1},
    ],
    explanation:'يحمي: زراعة، تدوير، نقل عام. يضر: رمي نفايات، قطع غابات، صيد جائر.',
    goldenRule:'حماية = زراعة + تدوير + ترشيد | ضرر = تلوث + قطع + صيد.',
    paragraph:'حماية البيئة — ص ٧٢',
  },
  { id:'s4_276', unit:'u2', lesson:'u2l3', page:65, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'التوازن البيئي يتحقق عندما تعمل كل العوامل الحيوية وغير الحيوية بانسجام.',
    correctAnswer:'true',
    explanation:'التوازن البيئي يتحقق بانسجام العوامل الحيوية وغير الحيوية معاً.',
    goldenRule:'توازن = انسجام حيوي + غير حيوي.',
    paragraph:'التوازن البيئي — ص ٦٥',
  },
  { id:'s4_277', unit:'u2', lesson:'u2l3', page:67, difficulty:'hard', bloom:'evaluate', type:'multipleChoice',
    question:'إذا أردت حماية نظام بيئي محلي، أيّ الإجراءات الأنفع؟',
    options:[{text:'نشر الوعي وعدم رمي النفايات وزراعة النباتات المحلية',correct:true},{text:'قطع الأشجار',correct:false},{text:'صيد الحيوانات',correct:false},{text:'تلوث الماء',correct:false}],
    explanation:'الوعي وعدم رمي النفايات وزراعة النباتات المحلية من أنفع الإجراءات.',
    goldenRule:'حماية محلية = وعي + نظافة + تشجير محلي.',
    paragraph:'حماية النظام البيئي — ص ٦٧',
  },
  { id:'s4_278', unit:'u2', lesson:'u2l3', page:69, difficulty:'medium', bloom:'apply', type:'trueFalse',
    question:'تلوث الهواء بالغازات الضارة يؤثر على صحة الكائنات الحية في النظام البيئي.',
    correctAnswer:'true',
    explanation:'تلوث الهواء يضر الكائنات الحية ويسبب أمراض التنفس ويؤثر على النباتات.',
    goldenRule:'تلوث هواء = أمراض + ضرر للنبات.',
    paragraph:'تلوث الهواء — ص ٦٩',
  },
  { id:'s4_279', unit:'u2', lesson:'u2l3', page:72, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'الموئل هو:',
    options:[{text:'المكان الذي يعيش فيه الكائن الحي ويجد احتياجاته',correct:true},{text:'مكان الصيد فقط',correct:false},{text:'المكان الذي لا يعيش فيه أحد',correct:false},{text:'كوكب آخر',correct:false}],
    explanation:'الموئل هو المكان الطبيعي الذي يعيش فيه الكائن ويجد فيه غذاءه وماءه ومأواه.',
    goldenRule:'الموئل = بيت الكائن الحي الطبيعي.',
    paragraph:'الموئل — ص ٧٢',
  },
  { id:'s4_280', unit:'u2', lesson:'u2l3', page:71, difficulty:'medium', bloom:'understand', type:'trueFalse',
    question:'حماية الموائل الطبيعية تحمي الكائنات الحية من الانقراض.',
    correctAnswer:'true',
    explanation:'حماية الموائل تضمن بقاء الكائنات الحية وتكاثرها وتحفظها من الانقراض.',
    goldenRule:'حماية موئل = حماية كائن.',
    paragraph:'حماية الموائل — ص ٧١',
  },
];