// الوحدة السادسة — تنظيم البيانات — أسئلة إضافية

export const U6_EXTRA = [
  // ═══ الدرس 1: الخرائط والجداول (28 سؤال) ═══
  { id:'s4_701', unit:'u6', lesson:'u6l1', page:186, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'الخريطة المفاهيمية أداة تُساعد على:',
    options:[{text:'تنظيم المعلومات وإظهار العلاقات بين الأفكار',correct:true},{text:'حساب الأرقام',correct:false},{text:'قياس الأطوال',correct:false},{text:'إنتاج الطاقة',correct:false}],
    explanation:'الخريطة المفاهيمية تُنظّم المعلومات وتُظهر العلاقات بين المفاهيم والأفكار.',
    goldenRule:'خريطة مفاهيمية = تنظيم أفكار + علاقات بينها.',
    paragraph:'الخريطة المفاهيمية — ص ١٨٦',
  },
  { id:'s4_702', unit:'u6', lesson:'u6l1', page:187, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'الخريطة المفاهيمية تبدأ بمفهوم رئيسي تتفرع منه مفاهيم فرعية.',
    correctAnswer:'true',
    explanation:'الخريطة المفاهيمية تبدأ بمفهوم رئيسي في الأعلى وتتفرع منه المفاهيم المتعلقة به.',
    goldenRule:'خريطة = مفهوم رئيسي + تفرعات.',
    paragraph:'بناء الخريطة المفاهيمية — ص ١٨٧',
  },
  { id:'s4_703', unit:'u6', lesson:'u6l1', page:188, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'في الخريطة المفاهيمية تُربط المفاهيم بـ:',
    options:[{text:'كلمات رابطة (مثل: يحتوي، يعيش)',correct:true},{text:'خطوط بلا كلمات',correct:false},{text:'ألوان فقط',correct:false},{text:'صور فقط',correct:false}],
    explanation:'تُربط المفاهيم في الخريطة بكلمات رابطة توضح نوع العلاقة بينها.',
    goldenRule:'كلمة رابطة = توضح العلاقة بين مفهومين.',
    paragraph:'الروابط في الخريطة — ص ١٨٨',
  },
  { id:'s4_704', unit:'u6', lesson:'u6l1', page:189, difficulty:'medium', bloom:'apply', type:'multipleChoice',
    question:'أيّ المخططات التالية أفضل لتنظيم معلومات عن أنواع الحيوانات؟',
    options:[{text:'الخريطة المفاهيمية',correct:true},{text:'الرسم البياني الخطي',correct:false},{text:'الجدول الزمني',correct:false},{text:'الخريطة الجغرافية',correct:false}],
    explanation:'الخريطة المفاهيمية مناسبة لتنظيم المفاهيم المتفرعة كأنواع الحيوانات.',
    goldenRule:'تنظيم مفاهيم = خريطة مفاهيمية.',
    paragraph:'استخدام الخريطة المفاهيمية — ص ١٨٩',
  },
  { id:'s4_705', unit:'u6', lesson:'u6l1', page:190, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'الجدول يعرض البيانات في صفوف وأعمدة لتسهيل القراءة والمقارنة.',
    correctAnswer:'true',
    explanation:'الجدول يُنظّم البيانات في صفوف (أفقياً) وأعمدة (رأسياً) لتسهيل قراءتها ومقارنتها.',
    goldenRule:'جدول = صفوف + أعمدة.',
    paragraph:'الجداول — ص ١٩٠',
  },
  { id:'s4_706', unit:'u6', lesson:'u6l1', page:191, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'في جدول درجات الحرارة، الأعمدة تمثل:',
    options:[{text:'التصنيفات (مثل الشهور)',correct:true},{text:'الأرقام فقط',correct:false},{text:'الصور',correct:false},{text:'الألوان',correct:false}],
    explanation:'في الجدول، الأعمدة تمثل التصنيفات كالشهور أو الأنواع، والصفوف تمثل القيم.',
    goldenRule:'عمود = تصنيف | صف = قيمة.',
    paragraph:'مكونات الجدول — ص ١٩١',
  },
  { id:'s4_707', unit:'u6', lesson:'u6l1', page:192, difficulty:'medium', bloom:'apply', type:'classify',
    question:'صنّف أدوات تنظيم البيانات:',
    categories:['خريطة مفاهيمية', 'جدول'],
    items:[
      {text:'علاقات بين مفاهيم', correct_category:0},
      {text:'صفوف وأعمدة', correct_category:1},
      {text:'كلمات رابطة', correct_category:0},
      {text:'أرقام مرتبة', correct_category:1},
      {text:'تفرعات من مفهوم رئيسي', correct_category:0},
    ],
    explanation:'خريطة: علاقات، كلمات رابطة، تفرعات. جدول: صفوف/أعمدة، أرقام مرتبة.',
    goldenRule:'مفاهيم = خريطة | أرقام = جدول.',
    paragraph:'أدوات تنظيم البيانات — ص ١٩٢',
  },
  { id:'s4_708', unit:'u6', lesson:'u6l1', page:193, difficulty:'hard', bloom:'analyze', type:'multipleChoice',
    question:'لماذا يُفضّل استخدام الجدول عند مقارنة خصائص خمس حيوانات؟',
    options:[{text:'لأنه يعرض البيانات بشكل منظم يسهّل المقارنة',correct:true},{text:'لأنه أجمل شكلاً',correct:false},{text:'لأنه أقصر',correct:false},{text:'لأنه لا يحتاج تفكير',correct:false}],
    explanation:'الجدول يعرض خصائص متعددة لحيوانات متعددة في شكل منظم يسهّل المقارنة.',
    goldenRule:'مقارنة خصائص = جدول.',
    paragraph:'مقارنة البيانات — ص ١٩٣',
  },
  { id:'s4_709', unit:'u6', lesson:'u6l1', page:194, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'الخريطة المفاهيمية تُساعد على فهم الدرس وتلخيصه.',
    correctAnswer:'true',
    explanation:'الخريطة المفاهيمية تُلخّص المعلومات وتُظهر العلاقات فتُسهّل الفهم.',
    goldenRule:'خريطة مفاهيمية = تلخيص + فهم.',
    paragraph:'فوائد الخريطة المفاهيمية — ص ١٩٤',
  },
  { id:'s4_710', unit:'u6', lesson:'u6l1', page:195, difficulty:'medium', bloom:'apply', type:'multipleChoice',
    question:'أيّ الأمثلة التالية يُمثّل جدولاً؟',
    options:[{text:'جدول درجات الحرارة في 4 فصول',correct:true},{text:'مخطط دائري',correct:false},{text:'خريطة جغرافية',correct:false},{text:'رسم خطي',correct:false}],
    explanation:'جدول درجات الحرارة في الفصول مثال على جدول بأعمدة وصفوف.',
    goldenRule:'جدول = أعمدة + صفوف (مثل درجات الحرارة).',
    paragraph:'أمثلة الجداول — ص ١٩٥',
  },
  { id:'s4_711', unit:'u6', lesson:'u6l1', page:196, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'الخريطة المفاهيمية تتكوّن من:',
    options:[{text:'مفاهيم (فقاعات) وروابط (خطوط)',correct:true},{text:'أرقام فقط',correct:false},{text:'صور فقط',correct:false},{text:'ألوان فقط',correct:false}],
    explanation:'الخريطة المفاهيمية تتكوّن من فقاعات (مفاهيم) وخطوط (روابط).',
    goldenRule:'خريطة = فقاعات مفاهيم + خطوط روابط.',
    paragraph:'مكونات الخريطة المفاهيمية — ص ١٩٦',
  },
  { id:'s4_712', unit:'u6', lesson:'u6l1', page:187, difficulty:'medium', bloom:'understand', type:'trueFalse',
    question:'كل مفهوم في الخريطة المفاهيمية يُكتب داخل فقاعة أو مستطيل.',
    correctAnswer:'true',
    explanation:'المفاهيم تُكتب داخل فقاعات أو مستطيلات وتربطها خطوط مع كلمات رابطة.',
    goldenRule:'مفهوم = فقاعة + رابط.',
    paragraph:'كتابة المفاهيم — ص ١٨٧',
  },
  { id:'s4_713', unit:'u6', lesson:'u6l1', page:190, difficulty:'hard', bloom:'evaluate', type:'multipleChoice',
    question:'أيّ أدوات تنظيم البيانات أنسب لتسجيل نتائج تجربة علمية يومية؟',
    options:[{text:'جدول البيانات',correct:true},{text:'الخريطة المفاهيمية',correct:false},{text:'الرسم التخطيطي',correct:false},{text:'الخريطة الجغرافية',correct:false}],
    explanation:'جدول البيانات أنسب لتسجيل نتائج التجربة يومياً لأنه يعرض القيم منظمّة.',
    goldenRule:'نتائج تجربة = جدول بيانات.',
    paragraph:'تسجيل البيانات — ص ١٩٠',
  },
  { id:'s4_714', unit:'u6', lesson:'u6l1', page:191, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'عنوان الجدول يُكتب عادة في:',
    options:[{text:'أعلى الجدول',correct:true},{text:'أسفله',correct:false},{text:'بجانبه',correct:false},{text:'لا يحتاج عنوان',correct:false}],
    explanation:'عنوان الجدول يُكتب في أعلاه ليوضح محتواه.',
    goldenRule:'عنوان الجدول = أعلاه.',
    paragraph:'عنوان الجدول — ص ١٩١',
  },
  { id:'s4_715', unit:'u6', lesson:'u6l1', page:192, difficulty:'medium', bloom:'apply', type:'trueFalse',
    question:'قراءة الجدول تتطلب فهم عنوان الأعمدة والصفوف أولاً.',
    correctAnswer:'true',
    explanation:'قبل قراءة بيانات الجدول يجب فهم عناوين الأعمدة والصفوف.',
    goldenRule:'اقرأ عناوين الجدول أولاً = فهم البيانات.',
    paragraph:'قراءة الجدول — ص ١٩٢',
  },
  { id:'s4_716', unit:'u6', lesson:'u6l1', page:193, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'في جدول يقارن بين حيوانات (الأرنب، الأسد، الحصان)، ما الذي يُكتب في الأعمدة؟',
    options:[{text:'الخصائص (الغذاء، المسكن، الجسم)',correct:true},{text:'أسماء الحيوانات فقط',correct:false},{text:'الأرقام',correct:false},{text:'الألوان',correct:false}],
    explanation:'في جدول المقارنة، تُكتب خصائص المقارنة في الأعمدة والحيوانات في الصفوف.',
    goldenRule:'أعمدة = خصائص | صفوف = عناصر مقارنة.',
    paragraph:'جدول المقارنة — ص ١٩٣',
  },
  { id:'s4_717', unit:'u6', lesson:'u6l1', page:194, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'الخريطة المفاهيمية تُسهّل تذكّر المعلومات.',
    correctAnswer:'true',
    explanation:'الخريطة المفاهيمية تُنظّم المعلومات بصرياً فيسهل تذكّرها.',
    goldenRule:'خريطة = تذكّر أسهل.',
    paragraph:'تذكّر المعلومات — ص ١٩٤',
  },
  { id:'s4_718', unit:'u6', lesson:'u6l1', page:195, difficulty:'hard', bloom:'analyze', type:'multipleChoice',
    question:'إذا أردت تلخيص درس "الخلية" فأيّ الأدوات أنسب؟',
    options:[{text:'الخريطة المفاهيمية',correct:true},{text:'الجدول الزمني',correct:false},{text:'الرسم الخطي',correct:false},{text:'الخريطة الجغرافية',correct:false}],
    explanation:'الخريطة المفاهيمية أنسب لتلخيص المفاهيم المتعلقة بالخلية وعلاقاتها.',
    goldenRule:'تلخيص مفاهيم = خريطة مفاهيمية.',
    paragraph:'تلخيص الدرس — ص ١٩٥',
  },
  { id:'s4_719', unit:'u6', lesson:'u6l1', page:196, difficulty:'medium', bloom:'understand', type:'classify',
    question:'صنّف الأدوات حسب نوعها:',
    categories:['خريطة مفاهيمية', 'جدول بيانات'],
    items:[
      {text:'مفهوم رئيسي + تفرعات', correct_category:0},
      {text:'صفوف وأعمدة', correct_category:1},
      {text:'كلمات رابطة', correct_category:0},
      {text:'أرقام مرتبة', correct_category:1},
      {text:'مقارنة خصائص', correct_category:1},
    ],
    explanation:'خريطة: مفهوم + كلمات رابطة. جدول: صفوف/أعمدة + أرقام + مقارنة.',
    goldenRule:'خريطة = علاقات | جدول = أرقام/مقارنة.',
    paragraph:'أنواع أدوات التنظيم — ص ١٩٦',
  },
  { id:'s4_720', unit:'u6', lesson:'u6l1', page:188, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'عند بناء خريطة مفاهيمية، نبدأ بـ:',
    options:[{text:'تحديد المفهوم الرئيسي',correct:true},{text:'رسم الفقاعات الفرعية',correct:false},{text:'كتابة الروابط',correct:false},{text:'تلوين الخريطة',correct:false}],
    explanation:'نبدأ بتحديد المفهوم الرئيسي ثم نتفرع منه للمفاهيم الفرعية.',
    goldenRule:'ابدأ الخريطة بالمفهوم الرئيسي.',
    paragraph:'بناء الخريطة المفاهيمية — ص ١٨٨',
  },
  { id:'s4_721', unit:'u6', lesson:'u6l1', page:189, difficulty:'medium', bloom:'apply', type:'trueFalse',
    question:'يمكن استخدام الخريطة المفاهيمية لتلخيص أي درس في أي مادة.',
    correctAnswer:'true',
    explanation:'الخريطة المفاهيمية أداة عامة تُستخدم في تلخيص دروس جميع المواد.',
    goldenRule:'خريطة مفاهيمية = أداة عامة لتلخيص.',
    paragraph:'عمومية الخريطة المفاهيمية — ص ١٨٩',
  },
  { id:'s4_722', unit:'u6', lesson:'u6l1', page:190, difficulty:'hard', bloom:'evaluate', type:'multipleChoice',
    question:'أيّ مميزات الجدول تجعله مناسباً لتسجيل البيانات العلمية؟',
    options:[{text:'دقته في عرض الأرقام والتصنيفات',correct:true},{text:'جماله البصري فقط',correct:false},{text:'سهولة تلوينه',correct:false},{text:'صغر حجمه',correct:false}],
    explanation:'الجدول دقيق في عرض الأرقام والتصنيفات مما يجعله مناسباً للبيانات العلمية.',
    goldenRule:'جدول = دقة أرقام + تصنيفات.',
    paragraph:'مميزات الجدول — ص ١٩٠',
  },
  { id:'s4_723', unit:'u6', lesson:'u6l1', page:191, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'الجدول يُستخدم لتنظيم البيانات الرقمية والتصنيفية.',
    correctAnswer:'true',
    explanation:'الجدول ينظّم البيانات الرقمية والتصنيفية بشكل منظم.',
    goldenRule:'جدول = أرقام + تصنيفات.',
    paragraph:'استخدام الجدول — ص ١٩١',
  },
  { id:'s4_724', unit:'u6', lesson:'u6l1', page:192, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'أيّ مما يلي لا يُعد جزءاً من الخريطة المفاهيمية؟',
    options:[{text:'الأعمدة الرقمية',correct:true},{text:'المفهوم الرئيسي',correct:false},{text:'المفاهيم الفرعية',correct:false},{text:'الكلمات الرابطة',correct:false}],
    explanation:'الأعمدة الرقمية جزء من الجدول وليس من الخريطة المفاهيمية.',
    goldenRule:'أعمدة رقمية = جدول ≠ خريطة.',
    paragraph:'مكونات الخريطة — ص ١٩٢',
  },
  { id:'s4_725', unit:'u6', lesson:'u6l1', page:196, difficulty:'medium', bloom:'apply', type:'multipleChoice',
    question:'عندما تكون البيانات أرقاماً متكررة (مثل درجات الحرارة الشهرية)، أيّ الأدوات أنسب؟',
    options:[{text:'الجدول',correct:true},{text:'الخريطة المفاهيمية',correct:false},{text:'الرسم التخطيطي',correct:false},{text:'الخريطة الجغرافية',correct:false}],
    explanation:'الجدول أنسب لعرض أرقام متكررة كدرجات الحرارة الشهرية.',
    goldenRule:'أرقام متكررة = جدول.',
    paragraph:'اختيار الأداة — ص ١٩٦',
  },
  { id:'s4_726', unit:'u6', lesson:'u6l1', page:194, difficulty:'hard', bloom:'evaluate', type:'trueFalse',
    question:'الخريطة المفاهيمية والجدول أداتان مختلفتان لتنظيم البيانات ولكل واحدة استخدام مناسب.',
    correctAnswer:'true',
    explanation:'الخريطة للمفاهيم والعلاقات والجدول للأرقام والتصنيفات، وكل أداة لاستخدام مناسب.',
    goldenRule:'خريطة = مفاهيم | جدول = أرقام.',
    paragraph:'مقارنة الأدوات — ص ١٩٤',
  },
  { id:'s4_727', unit:'u6', lesson:'u6l1', page:195, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'الخريطة المفاهيمية تُستخدم بشكل واسع في:',
    options:[{text:'تلخيص الدروس وعرض المفاهيم',correct:true},{text:'حساب الأرقام',correct:false},{text:'قياس الأطوال',correct:false},{text:'إنتاج الطاقة',correct:false}],
    explanation:'الخريطة المفاهيمية تُستخدم لتلخيص الدروس وعرض العلاقات بين المفاهيم.',
    goldenRule:'خريطة = تلخيص + عرض مفاهيم.',
    paragraph:'استخدامات الخريطة — ص ١٩٥',
  },
  { id:'s4_728', unit:'u6', lesson:'u6l1', page:189, difficulty:'medium', bloom:'understand', type:'trueFalse',
    question:'الخريطة المفاهيمية تُظهر العلاقة بين المفاهيم بشكل واضح.',
    correctAnswer:'true',
    explanation:'الخريطة المفاهيمية تُظهر العلاقات بين المفاهيم بفضل الروابط والكلمات الرابطة.',
    goldenRule:'روابط = إظهار العلاقات.',
    paragraph:'إظهار العلاقات — ص ١٨٩',
  },

  // ═══ الدرس 2: الرسوم البيانية (28 سؤال) ═══
  { id:'s4_729', unit:'u6', lesson:'u6l2', page:197, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'الرسوم البيانية أدوات لعرض البيانات. الرسم البياني بالأعمدة يُستخدم لـ:',
    options:[{text:'مقارنة الكميات بين مجموعات مختلفة',correct:true},{text:'إظهار التغيّر عبر الزمن فقط',correct:false},{text:'عرض النسب المئوية',correct:false},{text:'رسم الخرائط',correct:false}],
    explanation:'الرسم بالأعمدة يُقارن كميات بين مجموعات مختلفة بارتفاع الأعمدة.',
    goldenRule:'رسم أعمدة = مقارنة كميات.',
    paragraph:'الرسم البياني بالأعمدة — ص ١٩٧',
  },
  { id:'s4_730', unit:'u6', lesson:'u6l2', page:198, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'الرسم البياني الخطي يُناسب إظهار التغيّر في ظاهرة عبر الزمن.',
    correctAnswer:'true',
    explanation:'الرسم الخطي يُظهر التغيّر عبر الزمن بخط متصل بين النقاط.',
    goldenRule:'رسم خطي = تغيّر عبر الزمن.',
    paragraph:'الرسم الخطي — ص ١٩٨',
  },
  { id:'s4_731', unit:'u6', lesson:'u6l2', page:199, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'الرسم البياني الدائري يُستخدم لإظهار:',
    options:[{text:'النسب المئوية لكل جزء من الكل',correct:true},{text:'المقارنة بين مجموعات',correct:false},{text:'التغيّر عبر الزمن',correct:false},{text:'الأعداد',correct:false}],
    explanation:'الرسم الدائري يُظهر نسبة كل جزء من الكل بدائرة مقسّمة إلى شرائح.',
    goldenRule:'دائري = نسبة كل جزء من الكل.',
    paragraph:'الرسم الدائري — ص ١٩٩',
  },
  { id:'s4_732', unit:'u6', lesson:'u6l2', page:200, difficulty:'medium', bloom:'apply', type:'classify',
    question:'صنّف الرسوم حسب نوع البيانات المناسبة:',
    categories:['رسم أعمدة', 'رسم خطي'],
    items:[
      {text:'مقارنة أعداد الطلاب في 5 صفوف', correct_category:0},
      {text:'تغيّر درجة الحرارة عبر الشهور', correct_category:1},
      {text:'أعداد الحيوانات في حديقة', correct_category:0},
      {text:'تغيّر النمو عبر الأشهر', correct_category:1},
      {text:'أعداد الكتب في مكتبات', correct_category:0},
    ],
    explanation:'أعمدة: مقارنة أعداد. خطي: تغيّر عبر الزمن.',
    goldenRule:'مقارنة = أعمدة | تغيّر زمن = خطي.',
    paragraph:'أنواع الرسوم — ص ٢٠٠',
  },
  { id:'s4_733', unit:'u6', lesson:'u6l2', page:201, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'الرسم البياني البيكتوغرافي يستخدم:',
    options:[{text:'صوراً أو رموزاً لتمثيل البيانات',correct:true},{text:'خطوطاً فقط',correct:false},{text:'دوائر فقط',correct:false},{text:'أرقاماً فقط',correct:false}],
    explanation:'الرسم البيكتوغرافي يستخدم صوراً (أيقونات) لتمثيل البيانات بصرياً.',
    goldenRule:'بيكتوغرافي = صور تمثّل البيانات.',
    paragraph:'الرسم البيكتوغرافي — ص ٢٠١',
  },
  { id:'s4_734', unit:'u6', lesson:'u6l2', page:202, difficulty:'medium', bloom:'apply', type:'multipleChoice',
    question:'من جدول: يناير=10، فبراير=12، مارس=15. أيّ الشهور الأعلى حرارة؟',
    options:[{text:'مارس',correct:true},{text:'يناير',correct:false},{text:'فبراير',correct:false},{text:'متساوية',correct:false}],
    explanation:'مارس (15) أعلى من يناير (10) وفبراير (12).',
    goldenRule:'نقرأ الجدول ونقارن الأرقام.',
    paragraph:'قراءة البيانات — ص ٢٠٢',
  },
  { id:'s4_735', unit:'u6', lesson:'u6l2', page:203, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'الرسم البياني يُساعد على فهم البيانات بسرعة أكبر من الجدول.',
    correctAnswer:'true',
    explanation:'الرسم البياني يعرض البيانات بصرياً فيسهل فهمها وتحليلها.',
    goldenRule:'رسم = فهم أسرع للبيانات.',
    paragraph:'فوائد الرسوم — ص ٢٠٣',
  },
  { id:'s4_736', unit:'u6', lesson:'u6l2', page:204, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'عنوان الرسم البياني يُكتب في:',
    options:[{text:'أعلى الرسم',correct:true},{text:'أسفله فقط',correct:false},{text:'بجانبه فقط',correct:false},{text:'لا يحتاج عنوان',correct:false}],
    explanation:'عنوان الرسم البياني يُكتب في أعلاه ليوضح محتواه.',
    goldenRule:'عنوان الرسم = أعلاه.',
    paragraph:'عنوان الرسم — ص ٢٠٤',
  },
  { id:'s4_737', unit:'u6', lesson:'u6l2', page:205, difficulty:'hard', bloom:'analyze', type:'multipleChoice',
    question:'إذا أردت إظهار نسبة استهلاك الماء في المنزل (شرب، غسيل، استحمام)، أيّ رسم أنسب؟',
    options:[{text:'الرسم الدائري',correct:true},{text:'الرسم الخطي',correct:false},{text:'الرسم البيكتوغرافي فقط',correct:false},{text:'الجدول فقط',correct:false}],
    explanation:'الرسم الدائري أنسب لإظهار نسبة كل جزء من الكل (شرب، غسيل، استحمام).',
    goldenRule:'نسب من كل = دائري.',
    paragraph:'اختيار الرسم — ص ٢٠٥',
  },
  { id:'s4_738', unit:'u6', lesson:'u6l2', page:206, difficulty:'medium', bloom:'apply', type:'multipleChoice',
    question:'في رسم أعمدة لعدد طلاب 3 صفوف، ماذا يمثل ارتفاع العمود؟',
    options:[{text:'عدد الطلاب في كل صف',correct:true},{text:'أسماء الطلاب',correct:false},{text:'أعمار الطلاب',correct:false},{text:'ألوان الطلاب',correct:false}],
    explanation:'ارتفاع العمود يمثل القيمة (عدد الطلاب) في كل صف.',
    goldenRule:'ارتفاع عمود = قيمة المجموعة.',
    paragraph:'قراءة الرسم — ص ٢٠٦',
  },
  { id:'s4_739', unit:'u6', lesson:'u6l2', page:207, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'الرسم البياني الدائري يقسم الدائرة إلى شرائح تمثل نسب كل جزء.',
    correctAnswer:'true',
    explanation:'الدائري يقسم الدائرة إلى شرائح، كل شريحة تمثل نسبة جزء من الكل.',
    goldenRule:'دائري = شرائح نسبية.',
    paragraph:'الرسم الدائري — ص ٢٠٧',
  },
  { id:'s4_740', unit:'u6', lesson:'u6l2', page:198, difficulty:'medium', bloom:'understand', type:'classify',
    question:'صنّف أنواع الرسوم البيانية:',
    categories:['رسم أعمدة', 'رسم دائري'],
    items:[
      {text:'مقارنة كميات بين مجموعات', correct_category:0},
      {text:'نسبة كل جزء من الكل', correct_category:1},
      {text:'شرائح دائرية', correct_category:1},
      {text:'أعمدة مستطيلة', correct_category:0},
    ],
    explanation:'أعمدة: مقارنة كميات، أعمدة مستطيلة. دائري: نسبة من كل، شرائح.',
    goldenRule:'أعمدة = مقارنة | دائري = نسب.',
    paragraph:'أنواع الرسوم — ص ١٩٨',
  },
  { id:'s4_741', unit:'u6', lesson:'u6l2', page:199, difficulty:'hard', bloom:'evaluate', type:'multipleChoice',
    question:'أيّ الرسوم التالية أنسب لإظهار نمو نبتة عبر الأسابيع؟',
    options:[{text:'الرسم الخطي',correct:true},{text:'الرسم الدائري',correct:false},{text:'الرسم البيكتوغرافي',correct:false},{text:'الجدول فقط',correct:false}],
    explanation:'الرسم الخطي أنسب لإظهار التغيّر عبر الزمن كنمو نبتة عبر الأسابيع.',
    goldenRule:'نمو عبر الزمن = خطي.',
    paragraph:'اختيار الرسم — ص ١٩٩',
  },
  { id:'s4_742', unit:'u6', lesson:'u6l2', page:200, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'الرسم البياني بالأعمدة يتكون من:',
    options:[{text:'أعمدة مستطيلة بارتفاعات مختلفة',correct:true},{text:'خطوط منحنية',correct:false},{text:'دوائر',correct:false},{text:'صور',correct:false}],
    explanation:'الرسم بالأعمدة مكوّن من أعمدة مستطيلة تختلف بارتفاعاتها حسب القيم.',
    goldenRule:'أعمدة مستطيلة = ارتفاع حسب قيمة.',
    paragraph:'مكونات الرسم — ص ٢٠٠',
  },
  { id:'s4_743', unit:'u6', lesson:'u6l2', page:201, difficulty:'medium', bloom:'apply', type:'trueFalse',
    question:'في رسم بيكتوغرافي، كل صورة قد تمثل عدداً ثابتاً من العناصر.',
    correctAnswer:'true',
    explanation:'في البيكتوغرافي، كل صورة (رمز) تمثل عدداً ثابتاً (مثلاً صورة = 10 طلاب).',
    goldenRule:'صورة واحدة = عدد ثابت في البيكتوغرافي.',
    paragraph:'الرسم البيكتوغرافي — ص ٢٠١',
  },
  { id:'s4_744', unit:'u6', lesson:'u6l2', page:202, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'المحور الأفقي في الرسم البياني يُستخدم عادة لـ:',
    options:[{text:'عرض التصنيفات (مثل الشهور)',correct:true},{text:'عرض القيم',correct:false},{text:'عرض الألوان',correct:false},{text:'عرض العناوين',correct:false}],
    explanation:'المحور الأفقي (السيني) يعرض التصنيفات كالشهور، والرأسي يعرض القيم.',
    goldenRule:'أفقي = تصنيفات | رأسي = قيم.',
    paragraph:'المحاور — ص ٢٠٢',
  },
  { id:'s4_745', unit:'u6', lesson:'u6l2', page:203, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'الرسوم البيانية تُسهّل قراءة وتحليل البيانات.',
    correctAnswer:'true',
    explanation:'الرسوم البيانية تعرض البيانات بصرياً فتسهل قراءتها وتحليلها.',
    goldenRule:'رسم = قراءة + تحليل أسهل.',
    paragraph:'فوائد الرسوم — ص ٢٠٣',
  },
  { id:'s4_746', unit:'u6', lesson:'u6l2', page:204, difficulty:'hard', bloom:'analyze', type:'multipleChoice',
    question:'في رسم خطي لإظهار تغيّر درجة الحرارة، ماذا تمثل النقاط؟',
    options:[{text:'قيمة الحرارة في كل شهر',correct:true},{text:'أسماء الطلاب',correct:false},{text:'ألوان',correct:false},{text:'صور',correct:false}],
    explanation:'كل نقطة في الرسم الخطي تمثل قيمة الحرارة في شهر معين، وتربطها خطوط.',
    goldenRule:'نقطة = قيمة في وقت | الخط = التغيّر.',
    paragraph:'مكونات الرسم الخطي — ص ٢٠٤',
  },
  { id:'s4_747', unit:'u6', lesson:'u6l2', page:205, difficulty:'medium', bloom:'apply', type:'multipleChoice',
    question:'أيّ الرسوم أنسب لمقارنة أعداد أنواع 4 حيوانات في حديقة؟',
    options:[{text:'الرسم بالأعمدة',correct:true},{text:'الرسم الدائري',correct:false},{text:'الرسم الخطي',correct:false},{text:'الرسم الجغرافي',correct:false}],
    explanation:'الرسم بالأعمدة أنسب لمقارنة أعداد أنواع الحيوانات الأربعة.',
    goldenRule:'مقارنة أعداد = أعمدة.',
    paragraph:'مقارنة الأعداد — ص ٢٠٥',
  },
  { id:'s4_748', unit:'u6', lesson:'u6l2', page:206, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'مفتاح الرسم البياني يوضح معنى الرموز والألوان المستخدمة.',
    correctAnswer:'true',
    explanation:'المفتاح (الوسيلة الإيضاحية) يوضح معنى الألوان والرموز في الرسم.',
    goldenRule:'مفتاح = توضيح الرموز والألوان.',
    paragraph:'مفتاح الرسم — ص ٢٠٦',
  },
  { id:'s4_749', unit:'u6', lesson:'u6l2', page:207, difficulty:'medium', bloom:'understand', type:'classify',
    question:'صنّف البيانات حسب الرسم الأنسب لها:',
    categories:['رسم خطي', 'رسم دائري'],
    items:[
      {text:'تغيّر الوزن عبر الأسابيع', correct_category:0},
      {text:'نسبة أنواع الغذاء في وجبة', correct_category:1},
      {text:'تغيّر درجة الحرارة يومياً', correct_category:0},
      {text:'نسبة استهلاك الماء في المنزل', correct_category:1},
    ],
    explanation:'خطي: تغيّر عبر الزمن. دائري: نسبة من كل.',
    goldenRule:'تغيّر = خطي | نسبة = دائري.',
    paragraph:'اختيار الرسم — ص ٢٠٧',
  },
  { id:'s4_750', unit:'u6', lesson:'u6l2', page:197, difficulty:'hard', bloom:'evaluate', type:'multipleChoice',
    question:'لماذا يُفضّل الرسم البياني على الجدول عند عرض البيانات لجمهور عام؟',
    options:[{text:'لأنه أسهل في الفهم البصري',correct:true},{text:'لأنه أصغر حجماً',correct:false},{text:'لأنه أرخص',correct:false},{text:'لأنه لا يحتاج عنوان',correct:false}],
    explanation:'الرسم البياني أسهل في الفهم البصري للجمهور العام من جدول مليء بالأرقام.',
    goldenRule:'رسم = فهم بصري أسهل للجمهور.',
    paragraph:'الرسم vs الجدول — ص ١٩٧',
  },
  { id:'s4_751', unit:'u6', lesson:'u6l2', page:200, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'كل عمود في الرسم البياني بالأعمدة يمثل مجموعة أو تصنيف.',
    correctAnswer:'true',
    explanation:'كل عمود يمثل مجموعة (مثل صف، شهر) وارتفاعه يمثل القيمة.',
    goldenRule:'عمود = مجموعة + ارتفاع = قيمة.',
    paragraph:'الأعمدة — ص ٢٠٠',
  },
  { id:'s4_752', unit:'u6', lesson:'u6l2', page:201, difficulty:'medium', bloom:'apply', type:'multipleChoice',
    question:'في رسم بيكتوغرافي، إذا كانت كل صورة تمثل 5 طلاب وظهر 4 صور، فعدد الطلاب:',
    options:[{text:'20 طالباً',correct:true},{text:'5 طلاب',correct:false},{text:'4 طلاب',correct:false},{text:'9 طلاب',correct:false}],
    explanation:'4 صور × 5 طلاب = 20 طالباً.',
    goldenRule:'عدد صور × قيمة كل صورة = المجموع.',
    paragraph:'حساب البيكتوغرافي — ص ٢٠١',
  },
  { id:'s4_753', unit:'u6', lesson:'u6l2', page:203, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'المحور الرأسي في الرسم البياني بالأعمدة يمثل عادة:',
    options:[{text:'القيم (الأرقام)',correct:true},{text:'التصنيفات',correct:false},{text:'الألوان',correct:false},{text:'العناوين',correct:false}],
    explanation:'المحور الرأسي (الصادي) يعرض القيم الرقمية والارتفاعات.',
    goldenRule:'رأسي = قيم | أفقي = تصنيفات.',
    paragraph:'المحاور — ص ٢٠٣',
  },
  { id:'s4_754', unit:'u6', lesson:'u6l2', page:206, difficulty:'hard', bloom:'evaluate', type:'trueFalse',
    question:'اختيار نوع الرسم البياني المناسب يعتمد على نوع البيانات والغرض من عرضها.',
    correctAnswer:'true',
    explanation:'نوع البيانات والغرض (مقارنة، تغيّر، نسبة) يحددان نوع الرسم الأنسب.',
    goldenRule:'نوع البيانات + الغرض = نوع الرسم.',
    paragraph:'اختيار الرسم المناسب — ص ٢٠٦',
  },
  { id:'s4_755', unit:'u6', lesson:'u6l2', page:207, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'أيّ الرسوم التالية يستخدم الخطوط المتصلة؟',
    options:[{text:'الرسم الخطي',correct:true},{text:'الرسم الدائري',correct:false},{text:'الرسم البيكتوغرافي',correct:false},{text:'الرسم بالأعمدة',correct:false}],
    explanation:'الرسم الخطي يستخدم خطوطاً متصلة بين النقاط لإظهار التغيّر.',
    goldenRule:'خطي = خطوط متصلة.',
    paragraph:'الرسم الخطي — ص ٢٠٧',
  },
  { id:'s4_756', unit:'u6', lesson:'u6l2', page:199, difficulty:'medium', bloom:'apply', type:'trueFalse',
    question:'الرسم الدائري لا يُناسب مقارنة كميات بين مجموعات متعددة.',
    correctAnswer:'true',
    explanation:'الرسم الدائري للنسب، وليس الأنسب لمقارنة كميات بين مجموعات (الأعمدة أنسب).',
    goldenRule:'دائري = نسب | أعمدة = مقارنة كميات.',
    paragraph:'أنواع الرسوم — ص ١٩٩',
  },
];