// الوحدة الرابعة — أجهزة جسم الإنسان — أسئلة إضافية

export const U4_EXTRA = [
  // ═══ الدرس 1: الجهاز الهيكلي والعضلي (28 سؤال) ═══
  { id:'s4_401', unit:'u4', lesson:'u4l1', page:97, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'الجهاز الهيكلي للإنسان يتكوّن من العظام والغضاريف والمفاصل. كم عدد العظام في جسم البالغ؟',
    options:[{text:'٢٠٦ عظمة',correct:true},{text:'١٠٠ عظمة',correct:false},{text:'٥٠٠ عظمة',correct:false},{text:'٣٠ عظمة',correct:false}],
    explanation:'يحتوي جسم الإنسان البالغ على ٢٠٦ عظمة تتوزع في جميع أنحاء الجسم.',
    goldenRule:'جسم البالغ = ٢٠٦ عظمة.',
    paragraph:'الجهاز الهيكلي — ص ٩٧',
  },
  { id:'s4_402', unit:'u4', lesson:'u4l1', page:98, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'العمود الفقري يحمي النخاع الشوكي ويساند الجسم.',
    correctAnswer:'true',
    explanation:'العمود الفقري يحمي النخاع الشوكي ويحفظ توازن الجسم ويسانده.',
    goldenRule:'عمود فقري = حماية نخاع + دعامة الجسم.',
    paragraph:'العمود الفقري — ص ٩٨',
  },
  { id:'s4_403', unit:'u4', lesson:'u4l1', page:99, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'المفصل الذي يربط الذراع بالكتف يسمح بحركة دائرية واسعة. ما نوعه؟',
    options:[{text:'مفصل كروي',correct:true},{text:'مفصل رزني',correct:false},{text:'مفصل منزلق',correct:false},{text:'مفصل ثابت',correct:false}],
    explanation:'مفصل الكتف كروي يسمح بحركة دائرية واسعة للذراع.',
    goldenRule:'مفصل كروي = حركة دائرية (كتف).',
    paragraph:'أنواع المفاصل — ص ٩٩',
  },
  { id:'s4_404', unit:'u4', lesson:'u4l1', page:100, difficulty:'medium', bloom:'understand', type:'classify',
    question:'صنّف العظام التالية حسب موقعها:',
    categories:['عظام الرأس', 'عظام الأطراف'],
    items:[
      {text:'الجمجمة', correct_category:0},
      {text:'الفك السفلي', correct_category:0},
      {text:'عظمة الفخذ', correct_category:1},
      {text:'عظمة الذراع', correct_category:1},
      {text:'الترقوة', correct_category:1},
    ],
    explanation:'الرأس: جمجمة، فك سفلي. الأطراف: فخذ، ذراع، ترقوة.',
    goldenRule:'عظام الرأس ≠ عظام الأطراف.',
    paragraph:'تصنيف العظام — ص ١٠٠',
  },
  { id:'s4_405', unit:'u4', lesson:'u4l1', page:101, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'العضلات تختلف حسب التحكم بها. العضلات الإرادية هي:',
    options:[{text:'التي نتحكم بحركتها كعضلات الذراع',correct:true},{text:'التي تعمل تلقائياً',correct:false},{text:'عضلة القلب',correct:false},{text:'عضلات المعدة',correct:false}],
    explanation:'العضلات الإرادية نتحكم بها كعضلات الذراع والساق.',
    goldenRule:'إرادية = نتحكم بها | لاإرادية = تلقائية.',
    paragraph:'العضلات الإرادية — ص ١٠١',
  },
  { id:'s4_406', unit:'u4', lesson:'u4l1', page:102, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'عضلة القلب تعمل لا إرادياً وتتقلص بانتظام مدى الحياة.',
    correctAnswer:'true',
    explanation:'عضلة القلب لاإرادية وتتقلص بانتظام لضخّ الدم مدى الحياة.',
    goldenRule:'عضلة قلب = لاإرادية + دائمة الانقباض.',
    paragraph:'عضلة القلب — ص ١٠٢',
  },
  { id:'s4_407', unit:'u4', lesson:'u4l1', page:103, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'العضلات تعمل في أزواج متقابلة. عند ثني الذراع ماذا يحدث؟',
    options:[{text:'تنقبض العضلة الأمامية وتنبسط الخلفية',correct:true},{text:'تنقبض كلتاهما',correct:false},{text:'تنبسط كلتاهما',correct:false},{text:'لا يحدث شيء',correct:false}],
    explanation:'عند ثني الذراع تنقبض العضلة الأمامية (ثنائية) وتنبسط الخلفية (ثلاثائية).',
    goldenRule:'ثني = انقباض أمامي + انبساط خلفي.',
    paragraph:'عمل العضلات — ص ١٠٣',
  },
  { id:'s4_408', unit:'u4', lesson:'u4l1', page:104, difficulty:'medium', bloom:'apply', type:'multipleChoice',
    question:'رياضي يكثر من تمارين القوة. ما النتيجة على عضلاته؟',
    options:[{text:'تزداد قوة وحجماً',correct:true},{text:'تضعف',correct:false},{text:'تختفي',correct:false},{text:'تصبح لاإرادية',correct:false}],
    explanation:'التمارين المنتظمة تزيد قوة العضلات وحجمها.',
    goldenRule:'تمارين قوة = عضلات أقوى وأكبر.',
    paragraph:'تقوية العضلات — ص ١٠٤',
  },
  { id:'s4_409', unit:'u4', lesson:'u4l1', page:105, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'الغضاريف تُغطي نهايات العظام عند المفاصل لتسهّل الحركة وتقلل الاحتكاك.',
    correctAnswer:'true',
    explanation:'الغضاريف تُغطي نهايات العظام فتسهّل الحركة وتقلل الاحتكاك.',
    goldenRule:'غضاريف = سهولة حركة + قليل احتكاك.',
    paragraph:'الغضاريف — ص ١٠٥',
  },
  { id:'s4_410', unit:'u4', lesson:'u4l1', page:106, difficulty:'hard', bloom:'analyze', type:'multipleChoice',
    question:'إذا تعرض الإنسان لكسر في عظمة الفخذ، ما الذي يتأثر مباشرة؟',
    options:[{text:'القدرة على المشي ودعم الجسم',correct:true},{text:'التنفس',correct:false},{text:'الهضم',correct:false},{text:'الرؤية',correct:false}],
    explanation:'كسر الفخذ يؤثر على الدعم والمشي لأن الفخذ أكبر عظمة تحمل الوزن.',
    goldenRule:'فخذ = دعم + مشي → كسرها = فقد الدعم.',
    paragraph:'كسر العظام — ص ١٠٦',
  },
  { id:'s4_411', unit:'u4', lesson:'u4l1', page:107, difficulty:'medium', bloom:'understand', type:'classify',
    question:'صنّف العضلات حسب التحكم:',
    categories:['إرادية', 'لا إرادية'],
    items:[
      {text:'عضلات الساق', correct_category:0},
      {text:'عضلات الذراع', correct_category:0},
      {text:'عضلات المعدة', correct_category:1},
      {text:'عضلة القلب', correct_category:1},
      {text:'عضلات الأمعاء', correct_category:1},
      {text:'عضلات الوجه', correct_category:0},
    ],
    explanation:'إرادية: ساق، ذراع، وجه. لاإرادية: معدة، قلب، أمعاء.',
    goldenRule:'إرادية = نتحكم بها | لاإرادية = تلقائية.',
    paragraph:'أنواع العضلات — ص ١٠٧',
  },
  { id:'s4_412', unit:'u4', lesson:'u4l1', page:108, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'القفص الصدري يحمي القلب والرئتين.',
    correctAnswer:'true',
    explanation:'القفص الصدري يحمي الأعضاء الحيوية كالقلب والرئتين من الإصابات.',
    goldenRule:'قفص صدري = حماية قلب + رئتين.',
    paragraph:'القفص الصدري — ص ١٠٨',
  },
  { id:'s4_413', unit:'u4', lesson:'u4l1', page:100, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'المفصل بين عظام الجمجمة يُسمّى:',
    options:[{text:'مفصلاً ثابتاً (لا يتحرك)',correct:true},{text:'مفصلاً متحركاً',correct:false},{text:'مفصلاً كروياً',correct:false},{text:'مفصلاً رزنياً',correct:false}],
    explanation:'مفاصل الجمجمة ثابتة لا تتحرك، وتحمي الدماغ.',
    goldenRule:'جمجمة = مفاصل ثابتة (حماية الدماغ).',
    paragraph:'مفاصل الجمجمة — ص ١٠٠',
  },
  { id:'s4_414', unit:'u4', lesson:'u4l1', page:101, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'العضلة تتصل بالعظم عن طريق:',
    options:[{text:'الوتر',correct:true},{text:'الغضروف',correct:false},{text:'الجلد',correct:false},{text:'العصب فقط',correct:false}],
    explanation:'الوتر يربط العضلة بالعظم لينقل قوة الانقباض للحركة.',
    goldenRule:'الوتر = رابط العضلة بالعظم.',
    paragraph:'الأوتار — ص ١٠١',
  },
  { id:'s4_415', unit:'u4', lesson:'u4l1', page:103, difficulty:'hard', bloom:'analyze', type:'trueFalse',
    question:'الجهاز العصبي يتحكم في حركة العضلات الإرادية عبر رسائل عصبية.',
    correctAnswer:'true',
    explanation:'الأعصاب تنقل أوامر الدماغ للعضلات الإرادية لتنقبض أو تنبسط.',
    goldenRule:'دماغ → عصب → عضلة = حركة إرادية.',
    paragraph:'التحكم العصبي — ص ١٠٣',
  },
  { id:'s4_416', unit:'u4', lesson:'u4l1', page:105, difficulty:'medium', bloom:'apply', type:'multipleChoice',
    question:'نقص الكالسيوم في الجسم يؤثر على:',
    options:[{text:'قوة العظام وصحتها',correct:true},{text:'الرؤية',correct:false},{text:'السمع',correct:false},{text:'حاسة الشم',correct:false}],
    explanation:'الكالسيوم ضروري لبناء العظام ونقصه يُضعفها ويجعلها هشة.',
    goldenRule:'كالسيوم = قوة عظام (نقصه = هشاشة).',
    paragraph:'الكالسيوم والعظام — ص ١٠٥',
  },
  { id:'s4_417', unit:'u4', lesson:'u4l1', page:106, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'الحفاظ على القوام السليم يحمي العمود الفقري من التشوه.',
    correctAnswer:'true',
    explanation:'الجلوس والوقوف بشكل صحيح يحمي العمود الفقري من التشوه والانحناء.',
    goldenRule:'قوام سليم = حماية العمود الفقري.',
    paragraph:'القوام السليم — ص ١٠٦',
  },
  { id:'s4_418', unit:'u4', lesson:'u4l1', page:108, difficulty:'hard', bloom:'evaluate', type:'multipleChoice',
    question:'لماذا يُنصح بتناول الأطعمة الغنية بالكالسيوم وفيتامين د في سن النمو؟',
    options:[{text:'لبناء عظام قوية وتجنّب الكساح',correct:true},{text:'لزيادة الوزن',correct:false},{text:'لتحسين الرؤية',correct:false},{text:'لزيادة الطول فجأة',correct:false}],
    explanation:'الكالسيوم وفيتامين د يبنيان عظاماً قوية ويقيان من الكساح في النمو.',
    goldenRule:'كالسيوم + فيتامين د = عظام قوية (وقاية من الكساح).',
    paragraph:'تغذية العظام — ص ١٠٨',
  },
  { id:'s4_419', unit:'u4', lesson:'u4l1', page:99, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'المفصل هو:',
    options:[{text:'نقطة اتصال عظمتين أو أكثر',correct:true},{text:'عظمة واحدة',correct:false},{text:'عضلة',correct:false},{text:'عصب',correct:false}],
    explanation:'المفصل نقطة التقاء عظمتين أو أكثر ويتيح الحركة.',
    goldenRule:'مفصل = مكان التقاء عظام.',
    paragraph:'المفاصل — ص ٩٩',
  },
  { id:'s4_420', unit:'u4', lesson:'u4l1', page:102, difficulty:'medium', bloom:'understand', type:'trueFalse',
    question:'عضلات المعدة تتحرك الطعام فيها دون إرادة منّا.',
    correctAnswer:'true',
    explanation:'عضلات المعدة لاإرادية تحرك الطعام وتختلط بالعصارة الهاضمة.',
    goldenRule:'عضلات معدة = لاإرادية (هضم تلقائي).',
    paragraph:'عضلات المعدة — ص ١٠٢',
  },
  { id:'s4_421', unit:'u4', lesson:'u4l1', page:104, difficulty:'medium', bloom:'apply', type:'multipleChoice',
    question:'أيّ التمارين التالية يقوّي عضلات الساق؟',
    options:[{text:'الجري والقفز',correct:true},{text:'القراءة',correct:false},{text:'الكتابة',correct:false},{text:'النوم',correct:false}],
    explanation:'الجري والقفز من التمارين التي تقوّي عضلات الساق.',
    goldenRule:'جري + قفز = قوة عضلات ساق.',
    paragraph:'تمارين الساق — ص ١٠٤',
  },
  { id:'s4_422', unit:'u4', lesson:'u4l1', page:107, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'الجلد والعظام والغضاريف تُصنّف ضمن أجهزة الجسم:',
    options:[{text:'الهيكلي والعضلي والوقائي',correct:true},{text:'الهضمي',correct:false},{text:'التنفسي',correct:false},{text:'العصبي',correct:false}],
    explanation:'الجلد عضو وقائي، والعظام والغضاريف هيكلية، والعضلات حركية.',
    goldenRule:'عظام + عضلات + جلد = دعم + حركة + وقاية.',
    paragraph:'أجهزة الجسم — ص ١٠٧',
  },
  { id:'s4_423', unit:'u4', lesson:'u4l1', page:100, difficulty:'hard', bloom:'analyze', type:'trueFalse',
    question:'مفصل الركبة يسمح بالثني والبسط فقط دون حركة دائرية.',
    correctAnswer:'true',
    explanation:'مفصل الركبة رزني يسمح بالثني والبسط فقط دون دوران.',
    goldenRule:'مفصل رزني = ثني + بسط (لا دوران).',
    paragraph:'مفصل الركبة — ص ١٠٠',
  },
  { id:'s4_424', unit:'u4', lesson:'u4l1', page:105, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'الغضروف في الأذن الخارجية يُعطيها:',
    options:[{text:'المرونة والشكل',correct:true},{text:'الصلابة الكاملة',correct:false},{text:'عدم الحركة',correct:false},{text:'اللون',correct:false}],
    explanation:'الغضروف في الأذن يعطيها مرونة وشكلاً دون عظم صلب.',
    goldenRule:'غضروف أذن = مرونة + شكل.',
    paragraph:'غضروف الأذن — ص ١٠٥',
  },
  { id:'s4_425', unit:'u4', lesson:'u4l1', page:108, difficulty:'medium', bloom:'evaluate', type:'trueFalse',
    question:'الإفراط في حمل أثقال كبيرة قد يضرّ العمود الفقري في سن النمو.',
    correctAnswer:'true',
    explanation:'حمل الأثقال الكبيرة في سن النمو قد يُسبب تشوّهاً في العمود الفقري.',
    goldenRule:'أثقال كبيرة + نمو = خطر على العمود الفقري.',
    paragraph:'حمل الأثقال — ص ١٠٨',
  },
  { id:'s4_426', unit:'u4', lesson:'u4l1', page:98, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'يحمي الدماغ داخل الجمجمة من الإصابات الخارجية:',
    options:[{text:'الجمجمة',correct:true},{text:'القفص الصدري',correct:false},{text:'الحبل الشوكي',correct:false},{text:'الغضروف',correct:false}],
    explanation:'الجمجمة تحيط بالدماغ وتحميه من الإصابات.',
    goldenRule:'جمجمة = صندوق حماية الدماغ.',
    paragraph:'الجمجمة — ص ٩٨',
  },
  { id:'s4_427', unit:'u4', lesson:'u4l1', page:102, difficulty:'hard', bloom:'analyze', type:'multipleChoice',
    question:'لماذا لا نتعب من نبض القلب رغم أنه دائم الانقباض؟',
    options:[{text:'لأنه عضلة لاإرادية تعمل تلقائياً وتتجدد طاقتها',correct:true},{text:'لأنه لا يعمل',correct:false},{text:'لأنه صغير',correct:false},{text:'لأنه بلا أعصاب',correct:false}],
    explanation:'عضلة القلب لاإرادية متخصصة تتجدد طاقتها فلا تتعب كالعضلات الإرادية.',
    goldenRule:'قلب = لاإرادي + لا يتعب (يتجدد).',
    paragraph:'عضلة القلب — ص ١٠٢',
  },
  { id:'s4_428', unit:'u4', lesson:'u4l1', page:107, difficulty:'medium', bloom:'apply', type:'trueFalse',
    question:'الإحماء قبل التمارين يقلل من إصابات العضلات والمفاصل.',
    correctAnswer:'true',
    explanation:'الإحماء يُهيّئ العضلات والمفاصل للتمارين ويقلل الإصابات.',
    goldenRule:'إحماء = عضلات جاهزة + إصابات أقل.',
    paragraph:'الإحماء — ص ١٠٧',
  },

  // ═══ الدرس 2: الجهاز الدوراني والتنفسي (28 سؤال) ═══
  { id:'s4_429', unit:'u4', lesson:'u4l2', page:109, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'القلب عضو أجوف يقع في الصدر. كم حجيرة في قلب الإنسان؟',
    options:[{text:'أربع حجيرات',correct:true},{text:'حجرة واحدة',correct:false},{text:'حجرتان',correct:false},{text:'ست حجيرات',correct:false}],
    explanation:'القلب أربع حجيرات: أذينان وبطينان، لتجعل الدم المؤكسج وغير المؤكسج منفصلين.',
    goldenRule:'قلب = 2 أذين + 2 بطين (4 حجيرات).',
    paragraph:'القلب — ص ١٠٩',
  },
  { id:'s4_430', unit:'u4', lesson:'u4l2', page:110, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'الشرايين تحمل الدم من القلب إلى الجسم والأوردة تحمله من الجسم إلى القلب.',
    correctAnswer:'true',
    explanation:'الشرايين تنقل من القلب للجسم، والأوردة تنقل من الجسم للقلب.',
    goldenRule:'شريان = من القلب | وريد = للقلب.',
    paragraph:'الأوعية الدموية — ص ١١٠',
  },
  { id:'s4_431', unit:'u4', lesson:'u4l2', page:111, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'الشعيرات الدموية هي أصغر الأوعية الدموية. أين يحدث تبادل الغازات والغذاء؟',
    options:[{text:'في الشعيرات الدموية',correct:true},{text:'في الشرايين الكبيرة',correct:false},{text:'في الأوردة الكبيرة',correct:false},{text:'في القلب',correct:false}],
    explanation:'الشعيرات الدموية أصغر أوعية تسمح بتبادل الغازات والغذاء بين الدم والخلايا.',
    goldenRule:'شعيرات = مكان التبادل (غازات + غذاء).',
    paragraph:'الشعيرات الدموية — ص ١١١',
  },
  { id:'s4_432', unit:'u4', lesson:'u4l2', page:112, difficulty:'medium', bloom:'understand', type:'classify',
    question:'صنّف مكونات الدم:',
    categories:['خلايا دم حمراء', 'خلايا دم بيضاء'],
    items:[
      {text:'تنقل الأكسجين', correct_category:0},
      {text:'تكافح الجراثيم', correct_category:1},
      {text:'تحتوي الهيموغلوبين', correct_category:0},
      {text:'تنتج أجساماً مضادة', correct_category:1},
      {text:'تعطي الدم لونه الأحمر', correct_category:0},
    ],
    explanation:'الحمراء: نقل أكسجين + هيموغلوبين + لون أحمر. البيضاء: مكافحة + أجسام مضادة.',
    goldenRule:'حمراء = أكسجين | بيضاء = مناعة.',
    paragraph:'مكونات الدم — ص ١١٢',
  },
  { id:'s4_433', unit:'u4', lesson:'u4l2', page:113, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'الصفائح الدموية تُساعد على:',
    options:[{text:'تجلّط الدم ووقف النزيف عند الجروح',correct:true},{text:'نقل الأكسجين',correct:false},{text:'مكافحة الجراثيم',correct:false},{text:'هضم الطعام',correct:false}],
    explanation:'الصفائح الدموية تُكوّن جلطة عند الجروح فتوقف النزيف.',
    goldenRule:'صفائح = تجلّط + وقف نزيف.',
    paragraph:'الصفائح الدموية — ص ١١٣',
  },
  { id:'s4_434', unit:'u4', lesson:'u4l2', page:114, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'الهواء يدخل الجسم عن طريق الأنف ثم القصبة الهوائية ثم يصل إلى الرئتين.',
    correctAnswer:'true',
    explanation:'مسار الهواء: أنف → قصبة هوائية → رئتان → حويصلات هوائية.',
    goldenRule:'مسار الهواء: أنف → قصبة → رئة → حويصلة.',
    paragraph:'الجهاز التنفسي — ص ١١٤',
  },
  { id:'s4_435', unit:'u4', lesson:'u4l2', page:115, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'التبادل الغازي في الرئتين يحدث في:',
    options:[{text:'الحويصلات الهوائية',correct:true},{text:'القصبة الهوائية',correct:false},{text:'الأنف',correct:false},{text:'الحنجرة',correct:false}],
    explanation:'الحويصلات الهوائية مكان التبادل: يدخل الأكسجين للدم ويخرج ثاني أكسيد الكربون.',
    goldenRule:'حويصلات = تبادل غازي (O₂ داخل / CO₂ خارج).',
    paragraph:'الحويصلات الهوائية — ص ١١٥',
  },
  { id:'s4_436', unit:'u4', lesson:'u4l2', page:116, difficulty:'medium', bloom:'apply', type:'multipleChoice',
    question:'عند الشهيق (الاستنشاق) ماذا يحدث؟',
    options:[{text:'يتمدد الصدر ويدخل الهواء',correct:true},{text:'ينكمش الصدر ويخرج الهواء',correct:false},{text:'يتوقف التنفس',correct:false},{text:'ينقبض الحجاب الحاجز',correct:false}],
    explanation:'عند الشهيق يتمدد الصدر ويهبط الحجاب الحاجز فيدخل الهواء.',
    goldenRule:'شهيق = توسّع صدر + دخول هواء.',
    paragraph:'الشهيق — ص ١١٦',
  },
  { id:'s4_437', unit:'u4', lesson:'u4l2', page:117, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'الحجاب الحاجز عضلة تفصل التجويف الصدري عن البطني وتُساعد في التنفس.',
    correctAnswer:'true',
    explanation:'الحجاب الحاجز عضلة تنفّسية تفصل الصدر عن البطن وتتحرك عند الشهيق والزفير.',
    goldenRule:'حجاب حاجز = عضلة تنفس.',
    paragraph:'الحجاب الحاجز — ص ١١٧',
  },
  { id:'s4_438', unit:'u4', lesson:'u4l2', page:118, difficulty:'hard', bloom:'analyze', type:'multipleChoice',
    question:'ماذا يحدث لنبض القلب بعد الجري مسافة طويلة؟',
    options:[{text:'يزداد لزيادة احتياج الجسم للأكسجين',correct:true},{text:'يقل',correct:false},{text:'يتوقف',correct:false},{text:'لا يتغير',correct:false}],
    explanation:'بعد الجري يزيد نبض القلب لتوصيل الأكسجين اللازم للعضلات.',
    goldenRule:'جري = حاجة أكسجين → نبض أكثر.',
    paragraph:'نبض القلب والرياضة — ص ١١٨',
  },
  { id:'s4_439', unit:'u4', lesson:'u4l2', page:119, difficulty:'medium', bloom:'understand', type:'classify',
    question:'صنّف الغازات حسب دورها في التنفس:',
    categories:['يدخل الجسم', 'يخرج من الجسم'],
    items:[
      {text:'الأكسجين', correct_category:0},
      {text:'ثاني أكسيد الكربون', correct_category:1},
      {text:'غاز النيتروجين (داخل هواء الزفير)', correct_category:1},
      {text:'هواء الشهيق', correct_category:0},
    ],
    explanation:'يدخل: أكسجين + هواء شهيق. يخرج: ثاني أكسيد الكربون + هواء زفير.',
    goldenRule:'شهيق = O₂ داخل | زفير = CO₂ خارج.',
    paragraph:'غازات التنفس — ص ١١٩',
  },
  { id:'s4_440', unit:'u4', lesson:'u4l2', page:110, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'جدران الشرايين تتميز بـ:',
    options:[{text:'السمك والمرونة لتحمل ضغط الدم',correct:true},{text:'الرفع الشديد',correct:false},{text:'عدم وجود جدران',correct:false},{text:'كونها شفافة',correct:false}],
    explanation:'جدران الشرايين سميكة ومرنة تتحمل ضغط الدم الصادر من القلب.',
    goldenRule:'شريان = جدار سميك + مرونة.',
    paragraph:'جدران الشرايين — ص ١١٠',
  },
  { id:'s4_441', unit:'u4', lesson:'u4l2', page:113, difficulty:'medium', bloom:'apply', type:'trueFalse',
    question:'عند جرح الجلد تتجمّع الصفائح الدموية لتكوّن جلطة توقف النزيف.',
    correctAnswer:'true',
    explanation:'الصفائح الدموية تتجمّع عند الجرح وتكوّن جلطة توقف النزيف.',
    goldenRule:'صفائح + جرح = جلطة + وقف نزيف.',
    paragraph:'تجلّط الدم — ص ١١٣',
  },
  { id:'s4_442', unit:'u4', lesson:'u4l2', page:114, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'الأنف يقوم بوظيفة في التنفس وهي:',
    options:[{text:'ترطيب وتدفئة وتنقية هواء التنفس',correct:true},{text:'هضم الطعام',correct:false},{text:'إنتاج الدم',correct:false},{text:'إخراج البول',correct:false}],
    explanation:'الأنف يرطّب ويدفئ وينقّي هواء التنفس قبل دخوله الرئتين.',
    goldenRule:'أنف = ترطيب + تدفئة + تنقية هواء.',
    paragraph:'وظيفة الأنف — ص ١١٤',
  },
  { id:'s4_443', unit:'u4', lesson:'u4l2', page:115, difficulty:'hard', bloom:'analyze', type:'multipleChoice',
    question:'التدخين يضر الرئتين لأنه:',
    options:[{text:'يُتلف الحويصلات الهوائية ويقلل كفاءة التنفس',correct:true},{text:'يقوّي الرئتين',correct:false},{text:'يزيد الأكسجين',correct:false},{text:'لا يؤثر فيها',correct:false}],
    explanation:'التدخين يُتلف الحويصلات الهوائية ويُقلل كفاءة التبادل الغازي.',
    goldenRule:'تدخين = تلف حويصلات + ضعف تنفس.',
    paragraph:'أضرار التدخين — ص ١١٥',
  },
  { id:'s4_444', unit:'u4', lesson:'u4l2', page:116, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'الزفير هو إخراج الهواء من الرئتين إلى الخارج.',
    correctAnswer:'true',
    explanation:'الزفير هو خروج الهواء من الرئتين بعد تبادل الغازات.',
    goldenRule:'زفير = خروج هواء (CO₂).',
    paragraph:'الزفير — ص ١١٦',
  },
  { id:'s4_445', unit:'u4', lesson:'u4l2', page:111, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'الأوعية الدموية تنقسم إلى:',
    options:[{text:'شرايين وأوردة وشعيرات',correct:true},{text:'عروق كبيرة فقط',correct:false},{text:'شعيرات فقط',correct:false},{text:'أوردة فقط',correct:false}],
    explanation:'الأوعية الدموية ثلاثة أنواع: شرايين (من القلب) وأوردة (للقلب) وشعيرات (تبادل).',
    goldenRule:'أوعية = شرايين + أوردة + شعيرات.',
    paragraph:'أنواع الأوعية — ص ١١١',
  },
  { id:'s4_446', unit:'u4', lesson:'u4l2', page:117, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'القصبة الهوائية تتفرع إلى:',
    options:[{text:'قصبتين تصلان إلى الرئتين',correct:true},{text:'شريان واحد',correct:false},{text:'وريد واحد',correct:false},{text:'أذين واحد',correct:false}],
    explanation:'القصبة الهوائية تتفرع إلى قصبتين تصل كل واحدة إلى رئة.',
    goldenRule:'قصبة هوائية → قصبتان → رئتان.',
    paragraph:'القصبة الهوائية — ص ١١٧',
  },
  { id:'s4_447', unit:'u4', lesson:'u4l2', page:118, difficulty:'hard', bloom:'evaluate', type:'trueFalse',
    question:'الاستنشاق العميق المنتظم يُحسّن كفاءة الرئتين ووصول الأكسجين للدم.',
    correctAnswer:'true',
    explanation:'التنفس العميق المنتظم يقوّي الرئتين ويحسّن وصول الأكسجين للدم.',
    goldenRule:'تنفس عميق = رئتان أفضل + أكسجين أكثر.',
    paragraph:'التنفس العميق — ص ١١٨',
  },
  { id:'s4_448', unit:'u4', lesson:'u4l2', page:112, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'الهيموغلوبين بروتين في خلايا الدم الحمراء وظيفته:',
    options:[{text:'حمل الأكسجين من الرئتين إلى خلايا الجسم',correct:true},{text:'هضم الطعام',correct:false},{text:'إنتاج الطاقة',correct:false},{text:'تنظيم النوم',correct:false}],
    explanation:'الهيموغلوبين يحمل الأكسجين في الدم وينقله من الرئتين للخلايا.',
    goldenRule:'هيموغلوبين = ناقل الأكسجين.',
    paragraph:'الهيموغلوبين — ص ١١٢',
  },
  { id:'s4_449', unit:'u4', lesson:'u4l2', page:119, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'القلب يضخّ الدم المؤكسج من البطين الأيسر إلى الجسم.',
    correctAnswer:'true',
    explanation:'البطين الأيسر يضخّ الدم المؤكسج عبر الشريان الأورطي إلى جميع أنحاء الجسم.',
    goldenRule:'بطين أيسر = ضخّ دم مؤكسج للجسم.',
    paragraph:'ضخّ الدم — ص ١١٩',
  },
  { id:'s4_450', unit:'u4', lesson:'u4l2', page:109, difficulty:'medium', bloom:'apply', type:'multipleChoice',
    question:'إذا انسدّت قصبة هوائية، ماذا يحدث؟',
    options:[{text:'صعوبة في التنفس وقد يختنق الشخص',correct:true},{text:'سهولة في التنفس',correct:false},{text:'لا تأثير',correct:false},{text:'تحسّن الرئتين',correct:false}],
    explanation:'انسداد القصبة الهوائية يمنع دخول الهواء ويسبب الاختناق.',
    goldenRule:'انسداد قصبة = خطر اختناق.',
    paragraph:'انسداد القصبة — ص ١٠٩',
  },
  { id:'s4_451', unit:'u4', lesson:'u4l2', page:114, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'الأهداب الصغيرة في القصبة الهوائية وظيفتها:',
    options:[{text:'إخراج الأوساخ والجراثيم مع المخاط',correct:true},{text:'هضم الطعام',correct:false},{text:'ضخّ الدم',correct:false},{text:'إنتاج العصارة',correct:false}],
    explanation:'الأهداب تحرّك المخاط مع الأوساخ والجراثيم خارج الجهاز التنفسي.',
    goldenRule:'أهداب = تنظيف القصبة (مخاط + أوساخ).',
    paragraph:'الأهداب — ص ١١٤',
  },
  { id:'s4_452', unit:'u4', lesson:'u4l2', page:116, difficulty:'hard', bloom:'analyze', type:'trueFalse',
    question:'عند الغوص تحت الماء يجب حبس النفس لأن الرئتين لا تتنفسان الماء.',
    correctAnswer:'true',
    explanation:'الرئتان تتنفسان الهواء لا الماء، ولذلك نحبس النفس عند الغوص.',
    goldenRule:'رئتان = هواء (لا ماء) → حبس نَفَس عند الغوص.',
    paragraph:'الغوص والتنفس — ص ١١٦',
  },
  { id:'s4_453', unit:'u4', lesson:'u4l2', page:111, difficulty:'medium', bloom:'understand', type:'classify',
    question:'صنّف أجزاء الجهاز التنفسي:',
    categories:['أعلى الجهاز', 'أسفل الجهاز'],
    items:[
      {text:'الأنف', correct_category:0},
      {text:'الحنجرة', correct_category:0},
      {text:'القصبة الهوائية', correct_category:1},
      {text:'الحويصلات', correct_category:1},
      {text:'الرئتان', correct_category:1},
    ],
    explanation:'أعلى: أنف، حنجرة. أسفل: قصبة، حويصلات، رئتان.',
    goldenRule:'أنف/حنجرة = أعلى | قصبة/رئة = أسفل.',
    paragraph:'أجزاء الجهاز التنفسي — ص ١١١',
  },
  { id:'s4_454', unit:'u4', lesson:'u4l2', page:113, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'نقص كمية خلايا الدم الحمراء يسبب فقر الدم (الأنيميا).',
    correctAnswer:'true',
    explanation:'نقص خلايا الدم الحمراء يقلل الأكسجين الواصل للخلايا فيسبب الأنيميا.',
    goldenRule:'نقص حمراء = أنيميا (نقص أكسجين).',
    paragraph:'فقر الدم — ص ١١٣',
  },
  { id:'s4_455', unit:'u4', lesson:'u4l2', page:118, difficulty:'medium', bloom:'apply', type:'multipleChoice',
    question:'عند ممارسة الرياضة يزيد عدد مرات التنفس لأن:',
    options:[{text:'العضلات تحتاج أكسجين أكثر وتنتج ثاني أكسيد كربون أكثر',correct:true},{text:'الرئتان تتوقفان',correct:false},{text:'القلب يبطؤ',correct:false},{text:'لا يوجد سبب',correct:false}],
    explanation:'الرياضة تزيد حاجة العضلات للأكسجين فيزيد التنفس لتلبية الحاجة.',
    goldenRule:'رياضة = حاجة أكسجين → تنفس أكثر.',
    paragraph:'التنفس والرياضة — ص ١١٨',
  },
  { id:'s4_456', unit:'u4', lesson:'u4l2', page:119, difficulty:'hard', bloom:'evaluate', type:'trueFalse',
    question:'التحكم المنتظم في معدل التنفس من خلال التمارين يُحسّن الصحة العامة.',
    correctAnswer:'true',
    explanation:'التنفس المنتظم يقوّي الرئتين ويُحسّن وصول الأكسجين ويُهدّئ النفس.',
    goldenRule:'تنفس منتظم = رئتان قوية + صحة أفضل.',
    paragraph:'التحكم في التنفس — ص ١١٩',
  },

  // ═══ الدرس 3: الجهاز الهضمي والإخراجي (28 سؤال) ═══
  { id:'s4_457', unit:'u4', lesson:'u4l3', page:120, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'يبدأ الهضم في الفم. ما الإنزيم الذي يُحلّل النشا في الفم؟',
    options:[{text:'اللعاب (أميلاز اللعاب)',correct:true},{text:'العصارة المعدية',correct:false},{text:'الصفراء',correct:false},{text:'عصارة البنكرياس',correct:false}],
    explanation:'اللعاب يحتوي إنزيم الأميلاز الذي يبدأ هضم النشا في الفم.',
    goldenRule:'الفم = بداية هضم النشا (أميلاز).',
    paragraph:'الهضم في الفم — ص ١٢٠',
  },
  { id:'s4_458', unit:'u4', lesson:'u4l3', page:121, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'الأسنان تساعد في عملية الهضم بتقطيع الطعام وطحنه.',
    correctAnswer:'true',
    explanation:'الأسنان تقطّع وتطحن الطعام لتسهيل بلعه وهضمه.',
    goldenRule:'أسنان = تقطيع + طحن الطعام.',
    paragraph:'الأسنان — ص ١٢١',
  },
  { id:'s4_459', unit:'u4', lesson:'u4l3', page:122, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'المعدة تُفرز عصارة هاضمة تحتوي على:',
    options:[{text:'حمض الهيدروكلوريك وإنزيمات لهضم البروتين',correct:true},{text:'اللعاب',correct:false},{text:'الصفراء فقط',correct:false},{text:'الأنسولين',correct:false}],
    explanation:'المعدة تُفرز حمض الهيدروكلوريك وإنزيمات تُحلّل البروتينات.',
    goldenRule:'معدة = حمض + إنزيمات (هضم بروتين).',
    paragraph:'العصارة المعدية — ص ١٢٢',
  },
  { id:'s4_460', unit:'u4', lesson:'u4l3', page:123, difficulty:'medium', bloom:'apply', type:'ordering',
    question:'رتّب مسار الطعام في الجهاز الهضمي:',
    items:['الفم', 'المعدة', 'الأمعاء الدقيقة', 'المريء'],
    correctOrder:[0, 3, 1, 2],
    explanation:'المسار: الفم → المريء → المعدة → الأمعاء الدقيقة.',
    goldenRule:'هضم: فم → مريء → معدة → أمعاء دقيقة.',
    paragraph:'مسار الطعام — ص ١٢٣',
  },
  { id:'s4_461', unit:'u4', lesson:'u4l3', page:124, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'الكبد يُفرز الصفراء التي تساعد في هضم الدهون.',
    correctAnswer:'true',
    explanation:'الكبد يُفرز الصفراء المخزّنة في المرارة، وتُحلّل الدهون في الأمعاء.',
    goldenRule:'كبد = صفراء (هضم دهون).',
    paragraph:'الكبد والصفراء — ص ١٢٤',
  },
  { id:'s4_462', unit:'u4', lesson:'u4l3', page:125, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'الأمعاء الدقيقة تتميز بـ:',
    options:[{text:'وجود زغابات تزيد سطح الامتصاص',correct:true},{text:'بلا امتصاص',correct:false},{text:'طول قصير',correct:false},{text:'إنتاج الدم',correct:false}],
    explanation:'الأمعاء الدقيقة لها زغابات صغيرة تزيد سطح الامتصاص للغذاء المهضوم.',
    goldenRule:'زغابات = سطح امتصاص كبير في الأمعاء الدقيقة.',
    paragraph:'الأمعاء الدقيقة — ص ١٢٥',
  },
  { id:'s4_463', unit:'u4', lesson:'u4l3', page:126, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'البنكرياس يُفرز عصارة هاضمة في:',
    options:[{text:'الأمعاء الدقيقة',correct:true},{text:'الفم',correct:false},{text:'المعدة',correct:false},{text:'المرارة',correct:false}],
    explanation:'البنكرياس يُفرز عصارات هاضمة للسكريات والدهون والبروتينات في الأمعاء الدقيقة.',
    goldenRule:'بنكرياس = عصارة في الأمعاء الدقيقة.',
    paragraph:'البنكرياس — ص ١٢٦',
  },
  { id:'s4_464', unit:'u4', lesson:'u4l3', page:127, difficulty:'medium', bloom:'understand', type:'classify',
    question:'صنّف العضو حسب وظيفته الهضمية:',
    categories:['هضم', 'امتصاص'],
    items:[
      {text:'المعدة', correct_category:0},
      {text:'الأمعاء الدقيقة', correct_category:1},
      {text:'الفم', correct_category:0},
      {text:'الأمعاء الغليظة (امتصاص ماء)', correct_category:1},
      {text:'البنكرياس (إفراز هضمي)', correct_category:0},
    ],
    explanation:'هضم: فم، معدة، بنكرياس. امتصاص: أمعاء دقيقة (غذاء) + غليظة (ماء).',
    goldenRule:'هضم = تكسير | امتصاص = دخول الدم.',
    paragraph:'وظائف الهضم — ص ١٢٧',
  },
  { id:'s4_465', unit:'u4', lesson:'u4l3', page:128, difficulty:'hard', bloom:'analyze', type:'multipleChoice',
    question:'إذا توقف البنكرياس عن إفراز عصارته ماذا يتأثر من الهضم؟',
    options:[{text:'هضم الدهون والبروتينات والسكريات في الأمعاء',correct:true},{text:'هضم النشا في الفم',correct:false},{text:'لا تأثير',correct:false},{text:'امتصاص الماء',correct:false}],
    explanation:'البنكرياس يفرز إنزيمات تُحلّل الدهون والبروتينات والسكريات في الأمعاء.',
    goldenRule:'بنكرياس = هضم شامل (دهون + بروتين + سكر).',
    paragraph:'وظيفة البنكرياس — ص ١٢٨',
  },
  { id:'s4_466', unit:'u4', lesson:'u4l3', page:129, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'الأمعاء الغليظة تمتصّ الماء والفضلات وتُكوّن البراز.',
    correctAnswer:'true',
    explanation:'الأمعاء الغليظة تمتصّ الماء من الفضلات وتُكوّن البراز لإخراجه.',
    goldenRule:'أمعاء غليظة = امتصاص ماء + تكوين براز.',
    paragraph:'الأمعاء الغليظة — ص ١٢٩',
  },
  { id:'s4_467', unit:'u4', lesson:'u4l3', page:130, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'الجهاز الإخراجي يتكوّن من عدة أعضاء. أيّ منها يُطرد البول؟',
    options:[{text:'الكليتان والمثانة',correct:true},{text:'الرئتان فقط',correct:false},{text:'القلب',correct:false},{text:'المعدة',correct:false}],
    explanation:'الجهاز الإخراجي للبول: كليتان (تصفية) + حالب + مثانة (تخزين) + إخراج.',
    goldenRule:'إخراج البول: كليتان → حالب → مثانة.',
    paragraph:'الجهاز الإخراجي — ص ١٣٠',
  },
  { id:'s4_468', unit:'u4', lesson:'u4l3', page:122, difficulty:'medium', bloom:'apply', type:'multipleChoice',
    question:'عند شرب كمية كبيرة من الماء، ماذا يفعل الجهاز الإخراجي؟',
    options:[{text:'يزيد إخراج البول للحفاظ على توازن الماء',correct:true},{text:'يقلل البول',correct:false},{text:'يوقف البول',correct:false},{text:'لا تغيير',correct:false}],
    explanation:'زيادة الماء يزيد إخراج البول للحفاظ على التوازن المائي في الجسم.',
    goldenRule:'ماء زائد = بول زائد (توازن مائي).',
    paragraph:'التوازن المائي — ص ١٢٢',
  },
  { id:'s4_469', unit:'u4', lesson:'u4l3', page:124, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'المرارة تخزّن الصفراء التي يُنتجها الكبد.',
    correctAnswer:'true',
    explanation:'المرارة كيس صغير يخزّن الصفراء التي يفرزها الكبد حتى تحتاجها الأمعاء.',
    goldenRule:'مرارة = مخزن الصفراء.',
    paragraph:'المرارة — ص ١٢٤',
  },
  { id:'s4_470', unit:'u4', lesson:'u4l3', page:126, difficulty:'hard', bloom:'analyze', type:'multipleChoice',
    question:'الكبد يقوم بأكثر من وظيفة. أيّ مما يلي من وظائفه؟',
    options:[{text:'إفراز الصفراء وتنظيم السكر وتخزين الفيتامينات',correct:true},{text:'هضم النشا فقط',correct:false},{text:'إنتاج الدم فقط',correct:false},{text:'تنظيم النوم',correct:false}],
    explanation:'الكبد يفرز الصفراء وينظم السكر ويخزن الفيتامينات ويُزيل السموم.',
    goldenRule:'كبد = صفراء + سكر + فيتامينات + سموم.',
    paragraph:'وظائف الكبد — ص ١٢٦',
  },
  { id:'s4_471', unit:'u4', lesson:'u4l3', page:127, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'اللعاب في الفم يُحلّل:',
    options:[{text:'النشا إلى سكر بسيط',correct:true},{text:'البروتين',correct:false},{text:'الدهون',correct:false},{text:'الماء',correct:false}],
    explanation:'إنزيم الأميلاز في اللعاب يبدأ تحويل النشا إلى سكر بسيط.',
    goldenRule:'لعاب = هضم النشا → سكر.',
    paragraph:'اللعاب — ص ١٢٧',
  },
  { id:'s4_472', unit:'u4', lesson:'u4l3', page:128, difficulty:'medium', bloom:'understand', type:'trueFalse',
    question:'امتصاص الغذاء المهضوم يتم أساساً في الأمعاء الدقيقة.',
    correctAnswer:'true',
    explanation:'الأمعاء الدقيقة هي المكان الرئيسي لامتصاص الغذاء المهضوم إلى الدم.',
    goldenRule:'أمعاء دقيقة = امتصاص الغذاء.',
    paragraph:'امتصاص الغذاء — ص ١٢٨',
  },
  { id:'s4_473', unit:'u4', lesson:'u4l3', page:129, difficulty:'medium', bloom:'apply', type:'multipleChoice',
    question:'إذا أصيب شخص بإسهال شديد، ما الذي يُفقد بكثرة من جسمه؟',
    options:[{text:'الماء والأملاح',correct:true},{text:'الدم',correct:false},{text:'الأكسجين',correct:false},{text:'الفيتامينات فقط',correct:false}],
    explanation:'الإسهال يُفقد الجسم كميات كبيرة من الماء والأملاح فيُسبب الجفاف.',
    goldenRule:'إسهال = فقد ماء + أملاح (خطر الجفاف).',
    paragraph:'الإسهال — ص ١٢٩',
  },
  { id:'s4_474', unit:'u4', lesson:'u4l3', page:130, difficulty:'hard', bloom:'evaluate', type:'trueFalse',
    question:'فشل الكليتين يعطّل تصفية الدم وتراكم الفضلات في الجسم.',
    correctAnswer:'true',
    explanation:'فشل الكليتين يمنع تصفية الدم فيتراكم البولينا والفضلات وتسمم الجسم.',
    goldenRule:'فشل كليتين = تراكم فضلات = تسمم.',
    paragraph:'فشل الكليتين — ص ١٣٠',
  },
  { id:'s4_475', unit:'u4', lesson:'u4l3', page:121, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'المريء أنبوب يصل بين:',
    options:[{text:'الفم والمعدة',correct:true},{text:'المعدة والأمعاء',correct:false},{text:'القلب والرئة',correct:false},{text:'الكبد والبنكرياس',correct:false}],
    explanation:'المريء أنبوب ينقل الطعام من الفم إلى المعدة بعد بلعه.',
    goldenRule:'مريء = فم → معدة.',
    paragraph:'المريء — ص ١٢١',
  },
  { id:'s4_476', unit:'u4', lesson:'u4l3', page:123, difficulty:'medium', bloom:'understand', type:'trueFalse',
    question:'المعدة تقوم بهضم البروتينات بفضل حمض الهيدروكلوريك وإنزيم الببسين.',
    correctAnswer:'true',
    explanation:'المعدة تُحلّل البروتين بالحمض وإنزيم الببسين إلى مركبات أبسط.',
    goldenRule:'معدة = حمض + ببسين → هضم بروتين.',
    paragraph:'هضم البروتين — ص ١٢٣',
  },
  { id:'s4_477', unit:'u4', lesson:'u4l3', page:125, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'الزغابات في الأمعاء الدقيقة تُساعد على:',
    options:[{text:'زيادة سطح الامتصاص للغذاء',correct:true},{text:'هضم الطعام في الفم',correct:false},{text:'إنتاج الصفراء',correct:false},{text:'ضخّ الدم',correct:false}],
    explanation:'الزغابات تكبّر سطح الأمعاء الدقيقة فيزيد امتصاص الغذاء.',
    goldenRule:'زغابات = امتصاص أكبر للغذاء.',
    paragraph:'الزغابات — ص ١٢٥',
  },
  { id:'s4_478', unit:'u4', lesson:'u4l3', page:127, difficulty:'hard', bloom:'analyze', type:'multipleChoice',
    question:'لماذا يُعدّ الكبد من أهم أعضاء الجسم رغم أنه ليس في مسار الطعام مباشرة؟',
    options:[{text:'لأنه يفرز الصفراء وينظّم السكر ويخزّن الفيتامينات',correct:true},{text:'لأنه يهضم النشا فقط',correct:false},{text:'لأنه لا فائدة منه',correct:false},{text:'لأنه يخزّن الدم فقط',correct:false}],
    explanation:'الكبد لا يهضم الطعام مباشرة لكنه يفرز الصفراء ويُنظّم السكر ويخزّن الفيتامينات.',
    goldenRule:'كبد = صفراء + سكر + فيتامينات (وظائف حيوية).',
    paragraph:'أهمية الكبد — ص ١٢٧',
  },
  { id:'s4_479', unit:'u4', lesson:'u4l3', page:130, difficulty:'medium', bloom:'apply', type:'trueFalse',
    question:'شرب كميات معتدلة من الماء يساعد الكليتين على أداء وظيفتهما في التصفية.',
    correctAnswer:'true',
    explanation:'شرب الماء بكميات معتدلة يساعد الكليتين على طرد الفضلات وإبقاء الدم نقياً.',
    goldenRule:'ماء كافٍ = كليتان صحيتان.',
    paragraph:'الماء والكليتان — ص ١٣٠',
  },
  { id:'s4_480', unit:'u4', lesson:'u4l3', page:122, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'العصارة المعدية تفرز في:',
    options:[{text:'المعدة',correct:true},{text:'الفم',correct:false},{text:'الكبد',correct:false},{text:'البنكرياس',correct:false}],
    explanation:'العصارة المعدية تُفرز في المعدة وتُحلّل البروتين.',
    goldenRule:'عصارة معدية = في المعدة.',
    paragraph:'العصارة المعدية — ص ١٢٢',
  },
  { id:'s4_481', unit:'u4', lesson:'u4l3', page:124, difficulty:'medium', bloom:'understand', type:'classify',
    question:'صنّف العصارات الهاضمة حسب مصدرها:',
    categories:['من المعدة', 'من الكبد'],
    items:[
      {text:'حمض الهيدروكلوريك', correct_category:0},
      {text:'الصفراء', correct_category:1},
      {text:'الببسين', correct_category:0},
      {text:'المرارة مخزن لها', correct_category:1},
    ],
    explanation:'معدة: حمض + ببسين. كبد: صفراء + مرارة مخزن.',
    goldenRule:'معدة = حمض/ببسين | كبد = صفراء.',
    paragraph:'العصارات الهاضمة — ص ١٢٤',
  },
  { id:'s4_482', unit:'u4', lesson:'u4l3', page:129, difficulty:'hard', bloom:'evaluate', type:'trueFalse',
    question:'صحة الجهاز الهضمي تعتمد على الغذاء المتوازن وشرب الماء والألياف.',
    correctAnswer:'true',
    explanation:'الألياف والماء والغذاء المتوازن يحافظون على صحة الجهاز الهضمي ويمنعون الإمساك.',
    goldenRule:'ألياف + ماء + توازن = جهاز هضمي صحي.',
    paragraph:'صحة الجهاز الهضمي — ص ١٢٩',
  },
  { id:'s4_483', unit:'u4', lesson:'u4l3', page:128, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'الأمعاء الدقيقة تتصل بالأمعاء الغليظة. ما الفرق بينهما في الوظيفة؟',
    options:[{text:'الدقيقة تمتصّ الغذاء والغليظة تمتصّ الماء',correct:true},{text:'كلاهما يمتصّ الغذاء',correct:false},{text:'كلاهما ينتج الصفراء',correct:false},{text:'الدقيقة تنتج البول',correct:false}],
    explanation:'الدقيقة: امتصاص الغذاء المهضوم. الغليظة: امتصاص الماء وتكوين البراز.',
    goldenRule:'دقيقة = غذاء | غليظة = ماء + براز.',
    paragraph:'الفرق بين الأمعاء — ص ١٢٨',
  },
  { id:'s4_484', unit:'u4', lesson:'u4l3', page:130, difficulty:'medium', bloom:'apply', type:'multipleChoice',
    question:'عند تراكم الفضلات في الدم، أيّ جهاز يُطرد الفضلات السائلة؟',
    options:[{text:'الجهاز الإخراجي (الكليتان)',correct:true},{text:'الجهاز العصبي',correct:false},{text:'الجهاز الهيكلي',correct:false},{text:'الجهاز العضلي',correct:false}],
    explanation:'الكليتان تُصفّيان الدم وتُخرجان الفضلات السائلة عن طريق البول.',
    goldenRule:'فضلات سائلة = كليتان → بول.',
    paragraph:'إخراج الفضلات — ص ١٣٠',
  },

  // ═══ الدرس 4: الجهاز العصبي والمناعة (28 سؤال) ═══
  { id:'s4_485', unit:'u4', lesson:'u4l4', page:131, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'الجهاز العصبي يقوم بنقل الرسائل بين أجزاء الجسم والدماغ. ما الوظيفة الأساسية؟',
    options:[{text:'التحكم في وظائف الجسم والاستجابة للمثيرات',correct:true},{text:'هضم الطعام',correct:false},{text:'إنتاج الدم',correct:false},{text:'بناء العظام',correct:false}],
    explanation:'الجهاز العصبي يتحكم في وظائف الجسم وينقل الاستجابات بسرعة.',
    goldenRule:'عصبي = تحكم + استجابة.',
    paragraph:'الجهاز العصبي — ص ١٣١',
  },
  { id:'s4_486', unit:'u4', lesson:'u4l4', page:132, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'الدماغ والحبل الشوكي هما الجزء المركزي في الجهاز العصبي.',
    correctAnswer:'true',
    explanation:'الجهاز العصبي المركزي يضمّ الدماغ والحبل الشوكي.',
    goldenRule:'مركزي = دماغ + حبل شوكي.',
    paragraph:'الجهاز المركزي — ص ١٣٢',
  },
  { id:'s4_487', unit:'u4', lesson:'u4l4', page:133, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'الدماغ يتكوّن من عدة أجزاء. أيّ منها يتحكم في التوازن وحركة الجسم؟',
    options:[{text:'المخيخ',correct:true},{text:'النخاع المستطيل',correct:false},{text:'الفص الأمامي فقط',correct:false},{text:'الجهاز الطرفي',correct:false}],
    explanation:'المخيخ يحفظ توازن الجسم وينسّق الحركة.',
    goldenRule:'مخيخ = توازن + تنسيق حركة.',
    paragraph:'المخيخ — ص ١٣٣',
  },
  { id:'s4_488', unit:'u4', lesson:'u4l4', page:134, difficulty:'medium', bloom:'understand', type:'classify',
    question:'صنّف أجزاء الجهاز العصبي:',
    categories:['مركزي', 'طرفي'],
    items:[
      {text:'الدماغ', correct_category:0},
      {text:'الحبل الشوكي', correct_category:0},
      {text:'الأعصاب المنتشرة في الجسم', correct_category:1},
      {text:'العصب البصري', correct_category:1},
    ],
    explanation:'مركزي: دماغ + حبل شوكي. طرفي: أعصاب الجسم والعصب البصري.',
    goldenRule:'مركزي = دماغ/حبل | طرفي = أعصاب الجسم.',
    paragraph:'أجزاء الجهاز العصبي — ص ١٣٤',
  },
  { id:'s4_489', unit:'u4', lesson:'u4l4', page:135, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'المناعة هي قدرة الجسم على:',
    options:[{text:'مقاومة الأمراض والجراثيم',correct:true},{text:'هضم الطعام',correct:false},{text:'نقل الأكسجين',correct:false},{text:'بناء العضلات',correct:false}],
    explanation:'المناعة قدرة الجسم على التصدي للجراثيم والأمراض والقضاء عليها.',
    goldenRule:'مناعة = مقاومة الأمراض.',
    paragraph:'المناعة — ص ١٣٥',
  },
  { id:'s4_490', unit:'u4', lesson:'u4l4', page:136, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'خلايا الدم البيضاء هي المسؤولة عن مكافحة الجراثيم في الجسم.',
    correctAnswer:'true',
    explanation:'خلايا الدم البيضاء تُهاجم الجراثيم وتُحلّلها وتُكوّن خط الدفاع الأساسي.',
    goldenRule:'بيضاء = جنود المناعة.',
    paragraph:'خلايا الدم البيضاء — ص ١٣٦',
  },
  { id:'s4_491', unit:'u4', lesson:'u4l4', page:137, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'الأجسام المضادة مواد تُنتجها خلايا الدم البيضاء. ما وظيفتها؟',
    options:[{text:'التعرف على الجراثيم وتحييدها',correct:true},{text:'نقل الأكسجين',correct:false},{text:'هضم الطعام',correct:false},{text:'بناء العظام',correct:false}],
    explanation:'الأجسام المضادة تتعرّف على الجرثوم وتُبطّل مفعوله أو تُعلّم خلايا أخرى بقتله.',
    goldenRule:'أجسام مضادة = تعريف + تحييد جرثوم.',
    paragraph:'الأجسام المضادة — ص ١٣٧',
  },
  { id:'s4_492', unit:'u4', lesson:'u4l4', page:138, difficulty:'medium', bloom:'apply', type:'multipleChoice',
    question:'عندما يدخل فيروس للجسم لأول مرة، كم يستغرق تكوين الأجسام المضادة؟',
    options:[{text:'عدة أيام لأن الجسم يتعرف عليه أول مرة',correct:true},{text:'ثانية واحدة',correct:false},{text:'لا ينتجها أبداً',correct:false},{text:'سنوات',correct:false}],
    explanation:'في أول مرة، يحتاج الجهاز المناعي عدة أيام ليتعرف على الفيروس ويُنتج أجساماً مضادة.',
    goldenRule:'أول دخول = أيام للتعرف والإنتاج.',
    paragraph:'بناء المناعة — ص ١٣٨',
  },
  { id:'s4_493', unit:'u4', lesson:'u4l4', page:139, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'الحبل الشوكي ينقل الرسائل بين الدماغ وأجزاء الجسم.',
    correctAnswer:'true',
    explanation:'الحبل الشوكي يمتد داخل العمود الفقري وينقل الإشارات بين الدماغ والجسم.',
    goldenRule:'حبل شوكي = طريق الرسائل (دماغ ↔ جسم).',
    paragraph:'الحبل الشوكي — ص ١٣٩',
  },
  { id:'s4_494', unit:'u4', lesson:'u4l4', page:140, difficulty:'hard', bloom:'analyze', type:'multipleChoice',
    question:'إذا تعطل الدماغ، ماذا يحدث للجسم؟',
    options:[{text:'لا يستطيع التحكم في وظائفه وقد يفقد الحياة',correct:true},{text:'يزداد نشاطه',correct:false},{text:'لا يتأثر',correct:false},{text:'يصبح أقوى',correct:false}],
    explanation:'تعطّل الدماغ يوقف التحكم في الجسم كله وقد يُسبب الوفاة.',
    goldenRule:'دماغ = مركز الحياة → تعطّله = خطر.',
    paragraph:'أهمية الدماغ — ص ١٤٠',
  },
  { id:'s4_495', unit:'u4', lesson:'u4l4', page:141, difficulty:'medium', bloom:'understand', type:'classify',
    question:'صنّف المهام حسب جزء الدماغ المسؤول:',
    categories:['المخ', 'المخيخ'],
    items:[
      {text:'التفكير والذاكرة', correct_category:0},
      {text:'التوازن ونسق الحركة', correct_category:1},
      {text:'الكلام', correct_category:0},
      {text:'الوقوف دون سقوط', correct_category:1},
    ],
    explanation:'المخ: تفكير، ذاكرة، كلام. المخيخ: توازن ونسق حركة.',
    goldenRule:'مخ = ذكاء | مخيخ = توازن.',
    paragraph:'أجزاء الدماغ — ص ١٤١',
  },
  { id:'s4_496', unit:'u4', lesson:'u4l4', page:135, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'الأنواع الثلاثة من خلايا الدم هي:',
    options:[{text:'الحمراء والبيضاء والصفائح',correct:true},{text:'الحمراء فقط',correct:false},{text:'البيضاء فقط',correct:false},{text:'الصفائح فقط',correct:false}],
    explanation:'الدم يحتوي خلايا حمراء (أكسجين) وبيضاء (مناعة) وصفائح (تجلّط).',
    goldenRule:'دم = حمراء + بيضاء + صفائح.',
    paragraph:'مكونات الدم — ص ١٣٥',
  },
  { id:'s4_497', unit:'u4', lesson:'u4l4', page:136, difficulty:'medium', bloom:'apply', type:'trueFalse',
    question:'عند الإصابة بعدوى، يزيد عدد خلايا الدم البيضاء لمكافحة الجرثوم.',
    correctAnswer:'true',
    explanation:'عند العدوى يزيد الجسم إنتاج خلايا الدم البيضاء لمواجهة الجرثوم.',
    goldenRule:'عدوى = زيادة بيضاء (مكافحة).',
    paragraph:'استجابة المناعة — ص ١٣٦',
  },
  { id:'s4_498', unit:'u4', lesson:'u4l4', page:137, difficulty:'hard', bloom:'evaluate', type:'multipleChoice',
    question:'التطعيم يُعدّ من طرق اكتساب المناعة:',
    options:[{text:'الصناعية (المكتسبة)',correct:true},{text:'الطبيعية الموروثة',correct:false},{text:'الوراثية',correct:false},{text:'لا يكتسب مناعة',correct:false}],
    explanation:'التطعيم يُكسب الجسم مناعة صناعية مكتسبة ضد مرض معين.',
    goldenRule:'تطعيم = مناعة مكتسبة (صناعية).',
    paragraph:'أنواع المناعة — ص ١٣٧',
  },
  { id:'s4_499', unit:'u4', lesson:'u4l4', page:138, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'المناعة الطبيعية قد تكون موروثة (فطرية) أو مكتسبة بعد المرض.',
    correctAnswer:'true',
    explanation:'المناعة الفطرية تولد مع الإنسان، والمكتسبة تحصل بعد الإصابة أو التطعيم.',
    goldenRule:'مناعة: فطرية (موروثة) + مكتسبة (مرض/لقاح).',
    paragraph:'أنواع المناعة — ص ١٣٨',
  },
  { id:'s4_500', unit:'u4', lesson:'u4l4', page:139, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'العصب البصري مسؤول عن:',
    options:[{text:'نقل الإشارات من العين إلى الدماغ',correct:true},{text:'هضم الطعام',correct:false},{text:'بناء العظام',correct:false},{text:'ضخّ الدم',correct:false}],
    explanation:'العصب البصري ينقل ما تراه العين على شكل إشارات للدماغ ليتم تفسيره.',
    goldenRule:'عصب بصري = عين → دماغ.',
    paragraph:'العصب البصري — ص ١٣٩',
  },
  { id:'s4_501', unit:'u4', lesson:'u4l4', page:140, difficulty:'hard', bloom:'analyze', type:'multipleChoice',
    question:'لماذا يستجيب الجسم بسرعة عند لمس شيء ساخن؟',
    options:[{text:'لأن الأعصاب تنقل الإشارة فوراً للدماغ فيسحب اليد',correct:true},{text:'لأن الجلد يبرد نفسه',correct:false},{text:'لأن العظام تتحرك وحدها',correct:false},{text:'لأن الدم يبرد',correct:false}],
    explanation:'الأعصاب تنقل تنبيه الحرارة للنخاع الشوكي والدماغ فيأمر بسحب اليد فوراً.',
    goldenRule:'سحب اليد من الحرارة = منعكس عصبي سريع.',
    paragraph:'المنعكس العصبي — ص ١٤٠',
  },
  { id:'s4_502', unit:'u4', lesson:'u4l4', page:141, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'النخاع المستطيل يتحكم في وظائف حيوية كالتنفس ونبض القلب.',
    correctAnswer:'true',
    explanation:'النخاع المستطيل يتحكم في وظائف تلقائية كالتنفس وضربات القلب والبلع.',
    goldenRule:'نخاع مستطيل = تنفس + قلب + بلع (حيوي).',
    paragraph:'النخاع المستطيل — ص ١٤١',
  },
  { id:'s4_503', unit:'u4', lesson:'u4l4', page:132, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'الأعصاب الطرفية تنتشر في:',
    options:[{text:'جميع أنحاء الجسم',correct:true},{text:'الدماغ فقط',correct:false},{text:'القلب فقط',correct:false},{text:'الرئتين فقط',correct:false}],
    explanation:'الأعصاب الطرفية تنتشر في جميع أنحاء الجسم وتربطه بالجهاز المركزي.',
    goldenRule:'طرفي = أعصاب في كل الجسم.',
    paragraph:'الأعصاب الطرفية — ص ١٣٢',
  },
  { id:'s4_504', unit:'u4', lesson:'u4l4', page:134, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'الجهاز العصبي الطرفي يتكوّن من:',
    options:[{text:'الأعصاب المنتشرة في الجسم',correct:true},{text:'الدماغ فقط',correct:false},{text:'القلب والأوعية',correct:false},{text:'العظام',correct:false}],
    explanation:'الطرفي يتكوّن من الأعصاب المنتشرة في الجسم التي تربطه بالمركزي.',
    goldenRule:'طرفي = أعصاب الجسم.',
    paragraph:'الجهاز الطرفي — ص ١٣٤',
  },
  { id:'s4_505', unit:'u4', lesson:'u4l4', page:136, difficulty:'hard', bloom:'analyze', type:'trueFalse',
    question:'الإصابة بنقص المناعة تجعل الجسم عاجزاً عن مقاومة أبسط الأمراض.',
    correctAnswer:'true',
    explanation:'نقص المناعة يُضعف قدرة الجسم على مقاومة الجراثيم فيصبح عرضة لأبسط الأمراض.',
    goldenRule:'نقص مناعة = ضعف مقاومة = أمراض متكررة.',
    paragraph:'نقص المناعة — ص ١٣٦',
  },
  { id:'s4_506', unit:'u4', lesson:'u4l4', page:138, difficulty:'medium', bloom:'apply', type:'multipleChoice',
    question:'أيّ العوامل التالية تُقوّي المناعة؟',
    options:[{text:'الغذاء المتوازن والرياضة والنوم الكافي',correct:true},{text:'السهر والتدخين',correct:false},{text:'نقص النوم',correct:false},{text:'الإفراط في السكريات',correct:false}],
    explanation:'الغذاء المتوازن والرياضة والنوم الكافي من أهم مقوّيات المناعة.',
    goldenRule:'مناعة قوية = غذاء + رياضة + نوم.',
    paragraph:'تقوية المناعة — ص ١٣٨',
  },
  { id:'s4_507', unit:'u4', lesson:'u4l4', page:141, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'الحفاظ على صحة الجهاز العصبي يتطلب النوم الكافي وتجنب التوتر.',
    correctAnswer:'true',
    explanation:'النوم الكافي وتجنب التوتر يحافظان على صحة الجهاز العصبي ووظائفه.',
    goldenRule:'نوم + هدوء = عصبي صحي.',
    paragraph:'صحة الجهاز العصبي — ص ١٤١',
  },
  { id:'s4_508', unit:'u4', lesson:'u4l4', page:140, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'العلاقة بين الجهاز العصبي والعضلات هي:',
    options:[{text:'العصبي يرسل الأوامر والعضلات تنفذ الحركة',correct:true},{text:'لا علاقة بينهما',correct:false},{text:'العضلات تتحكم بالدماغ',correct:false},{text:'الدماغ يهضم الطعام',correct:false}],
    explanation:'الدماغ يرسل إشارات عبر الأعصاب للعضلات فتنقبض وتتم الحركة.',
    goldenRule:'عصبي → أمر → عضلة → حركة.',
    paragraph:'العلاقة العصبية العضلية — ص ١٤٠',
  },
  { id:'s4_509', unit:'u4', lesson:'u4l4', page:137, difficulty:'hard', bloom:'evaluate', type:'multipleChoice',
    question:'لماذا يُنصح بعدم إعطاء الطفل مضاداً حيوياً دون استشارة الطبيب؟',
    options:[{text:'لأنه قد يضعف مناعته ويجعل البكتيريا مقاومة',correct:true},{text:'لأنه يقوّي المناعة دائماً',correct:false},{text:'لأنه لا تأثير له',correct:false},{text:'لأنه مفيد دائماً',correct:false}],
    explanation:'الإفراط في المضادات الحيوية دون حاجة قد يُضعف المناعة ويُكسب البكتيريا مقاومة.',
    goldenRule:'مضاد حيوي بلا استشارة = خطر مقاومة + ضعف مناعة.',
    paragraph:'المضادات الحيوية — ص ١٣٧',
  },
  { id:'s4_510', unit:'u4', lesson:'u4l4', page:133, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'المخ هو الجزء الأكبر من الدماغ ومسؤول عن التفكير والذاكرة والكلام.',
    correctAnswer:'true',
    explanation:'المخ أكبر أجزاء الدماغ ومسؤول عن الوظائف العليا كالتفكير والذاكرة والكلام.',
    goldenRule:'مخ = تفكير + ذاكرة + كلام.',
    paragraph:'المخ — ص ١٣٣',
  },
  { id:'s4_511', unit:'u4', lesson:'u4l4', page:139, difficulty:'medium', bloom:'apply', type:'multipleChoice',
    question:'طفل تلقّى لقاح الحصبة. بعد سنوات تعرّض للمرض. ماذا يحدث؟',
    options:[{text:'لا يصاب أو تصابته خفيفة بسبب الأجسام المضادة',correct:true},{text:'يصاب بمرض شديد',correct:false},{text:'لا فائدة من اللقاح',correct:false},{text:'يصاب أكثر',correct:false}],
    explanation:'اللقاح يُكسب الجسم أجساماً مضادة جاهزة تتعرّف على الفيروس وتقضي عليه سريعاً.',
    goldenRule:'لقاح سابق = أجسام مضادة جاهزة → حماية سريعة.',
    paragraph:'اللقاح والمناعة — ص ١٣٩',
  },
  { id:'s4_512', unit:'u4', lesson:'u4l4', page:141, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'العمود الفقري يحمي الحبل الشوكي من الإصابات.',
    correctAnswer:'true',
    explanation:'العمود الفقري يحيط بالحبل الشوكي ويحميه من الإصابات الخارجية.',
    goldenRule:'عمود فقري = درع الحبل الشوكي.',
    paragraph:'حماية الحبل الشوكي — ص ١٤١',
  },
];