// الوحدة الخامسة — الغذاء والصحة — أسئلة إضافية

export const U5_EXTRA = [
  // ═══ الدرس 1: مجموعات الغذاء (28 سؤال) ═══
  { id:'s4_601', unit:'u5', lesson:'u5l1', page:142, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'الأغذية التي نتناولها تنقسم إلى عدة مجموعات. ما المجموعة التي تُعطي الطاقة الرئيسية؟',
    options:[{text:'الكربوهيدرات',correct:true},{text:'الفيتامينات',correct:false},{text:'الأملاح',correct:false},{text:'الماء',correct:false}],
    explanation:'الكربوهيدرات المصدر الرئيسي للطاقة في الجسم.',
    goldenRule:'كربوهيدرات = طاقة الجسم الرئيسية.',
    paragraph:'مجموعات الغذاء — ص ١٤٢',
  },
  { id:'s4_602', unit:'u5', lesson:'u5l1', page:143, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'البروتينات تُعدّ ضرورية لنمو الجسم وبناء الخلايا.',
    correctAnswer:'true',
    explanation:'البروتينات تبني خلايا الجسم وتُساعد على النمو وتعويض الخلايا التالفة.',
    goldenRule:'بروتين = نمو + بناء + تعويض خلايا.',
    paragraph:'البروتينات — ص ١٤٣',
  },
  { id:'s4_603', unit:'u5', lesson:'u5l1', page:144, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'أيّ الأطعمة التالية من مصادر البروتين؟',
    options:[{text:'اللحوم والبيض والبقوليات',correct:true},{text:'الخبز والأرز',correct:false},{text:'الزيوت والسمن',correct:false},{text:'الفواكه فقط',correct:false}],
    explanation:'مصادر البروتين: لحوم، بيض، أسماك، بقوليات، حليب.',
    goldenRule:'بروتين = لحم + بيض + سمك + بقوليات + حليب.',
    paragraph:'مصادر البروتين — ص ١٤٤',
  },
  { id:'s4_604', unit:'u5', lesson:'u5l1', page:145, difficulty:'medium', bloom:'understand', type:'classify',
    question:'صنّف الأطعمة حسب المجموعة الغذائية:',
    categories:['كربوهيدرات', 'دهون'],
    items:[
      {text:'الخبز', correct_category:0},
      {text:'الأرز', correct_category:0},
      {text:'الزيت', correct_category:1},
      {text:'الزبدة', correct_category:1},
      {text:'التمر', correct_category:0},
      {text:'السمن', correct_category:1},
    ],
    explanation:'كربوهيدرات: خبز، أرز، تمر. دهون: زيت، زبدة، سمن.',
    goldenRule:'نشويات = كربوهيدرات | زيت/زبدة = دهون.',
    paragraph:'تصنيف الأطعمة — ص ١٤٥',
  },
  { id:'s4_605', unit:'u5', lesson:'u5l1', page:146, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'الفيتامينات تُساعد على:',
    options:[{text:'حماية الجسم والوقاية من الأمراض',correct:true},{text:'إنتاج الطاقة فقط',correct:false},{text:'بناء العضلات',correct:false},{text:'تنظيم النوم',correct:false}],
    explanation:'الفيتامينات تُساعد على بناء الخلايا والوقاية من الأمراض.',
    goldenRule:'فيتامينات = وقاية + بناء خلايا.',
    paragraph:'الفيتامينات — ص ١٤٦',
  },
  { id:'s4_606', unit:'u5', lesson:'u5l1', page:147, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'الأملاح المعدنية كالكالسيوم والحديد ضرورية لصحة الجسم.',
    correctAnswer:'true',
    explanation:'الأملاح المعدنية (كالسيوم، حديد، يود) ضرورية لبناء الجسم ووقايته.',
    goldenRule:'أملاح معدنية = كالسيوم + حديد + يود.',
    paragraph:'الأملاح المعدنية — ص ١٤٧',
  },
  { id:'s4_607', unit:'u5', lesson:'u5l1', page:148, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'الكالسيوم من الأملاح المعدنية المهمة. ما وظيفته؟',
    options:[{text:'بناء العظام والأسنان',correct:true},{text:'نقل الأكسجين',correct:false},{text:'إنتاج الطاقة',correct:false},{text:'تنظيم النوم',correct:false}],
    explanation:'الكالسيوم يبني العظام والأسنان ويقوّيها ويوجد في الحليب والخضروات.',
    goldenRule:'كالسيوم = عظام + أسنان قوية.',
    paragraph:'الكالسيوم — ص ١٤٨',
  },
  { id:'s4_608', unit:'u5', lesson:'u5l1', page:149, difficulty:'medium', bloom:'apply', type:'multipleChoice',
    question:'الحديد من الأملاح المعدنية. نقصه يُسبب:',
    options:[{text:'فقر الدم (الأنيميا)',correct:true},{text:'زيادة الوزن',correct:false},{text:'تحسّن الرؤية',correct:false},{text:'قوة العظام',correct:false}],
    explanation:'نقص الحديد يُسبب فقر الدم لأنه يدخل في تكوين الهيموغلوبين.',
    goldenRule:'حديد = هيموغلوبين → نقصه = أنيميا.',
    paragraph:'الحديد — ص ١٤٩',
  },
  { id:'s4_609', unit:'u5', lesson:'u5l1', page:150, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'الماء يُعدّ من أهم المواد الغذائية لأنه يشكّل أكثر من نصف جسم الإنسان.',
    correctAnswer:'true',
    explanation:'الماء يشكّل نحو ثلثي جسم الإنسان وهو ضروري لكل وظيفة حيوية.',
    goldenRule:'ماء = ثلثا الجسم + ضروري للحياة.',
    paragraph:'الماء — ص ١٥٠',
  },
  { id:'s4_610', unit:'u5', lesson:'u5l1', page:151, difficulty:'medium', bloom:'understand', type:'classify',
    question:'صنّف الفيتامينات حسب مصدرها:',
    categories:['يوجد في الحمضيات', 'يوجد في زيت السمك'],
    items:[
      {text:'فيتامين ج (C)', correct_category:0},
      {text:'فيتامين د (D)', correct_category:1},
      {text:'البرتقال', correct_category:0},
      {text:'أشعة الشمس تساعد إنتاجه', correct_category:1},
    ],
    explanation:'ج في الحمضيات (برتقال). د في زيت السمك وأشعة الشمس تساعد إنتاجه.',
    goldenRule:'ج = حمضيات | د = زيت سمك + شمس.',
    paragraph:'مصادر الفيتامينات — ص ١٥١',
  },
  { id:'s4_611', unit:'u5', lesson:'u5l1', page:152, difficulty:'hard', bloom:'analyze', type:'multipleChoice',
    question:'لماذا يُنصح بتناول الألياف بكثرة؟',
    options:[{text:'لأنها تساعد على الهضم وتمنع الإمساك',correct:true},{text:'لأنها تُكثر الدهون',correct:false},{text:'لأنها تُضعف الجسم',correct:false},{text:'لأنها تزيد العطش',correct:false}],
    explanation:'الألياف تُحسّن الهضم وتمنع الإمساك وتُساعد على الشعور بالشبع.',
    goldenRule:'ألياف = هضم سليم + وقاية من إمساك.',
    paragraph:'الألياف — ص ١٥٢',
  },
  { id:'s4_612', unit:'u5', lesson:'u5l1', page:153, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'أيّ الأطعمة التالية غني بالألياف؟',
    options:[{text:'الخضروات والفواكه والبقوليات',correct:true},{text:'اللحوم',correct:false},{text:'الزيوت',correct:false},{text:'السكر',correct:false}],
    explanation:'الألياف توجد في الخضروات والفواكه والبقوليات والحبوب الكاملة.',
    goldenRule:'ألياف = خضروات + فواكه + بقوليات.',
    paragraph:'مصادر الألياف — ص ١٥٣',
  },
  { id:'s4_613', unit:'u5', lesson:'u5l1', page:154, difficulty:'medium', bloom:'understand', type:'trueFalse',
    question:'الإفراط في تناول الدهون يُسبب أمراض القلب والسمنة.',
    correctAnswer:'true',
    explanation:'الإفراط في الدهون يُسبب السمنة وأمراض القلب وارتفاع الكوليسترول.',
    goldenRule:'دهون زائدة = سمنة + قلب + كوليسترول.',
    paragraph:'أضرار الدهون — ص ١٥٤',
  },
  { id:'s4_614', unit:'u5', lesson:'u5l1', page:155, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'السكر من الكربوهيدرات البسيطة. الإفراط فيه يُسبب:',
    options:[{text:'تسوس الأسنان والسمنة',correct:true},{text:'قوة العظام',correct:false},{text:'تحسّن الرؤية',correct:false},{text:'زيادة النشاط',correct:false}],
    explanation:'الإفراط في السكر يُسبب تسوس الأسنان والسمنة وارتفاع السكر في الدم.',
    goldenRule:'سكر زائد = تسوس + سمنة + سكر دم.',
    paragraph:'أضرار السكر — ص ١٥٥',
  },
  { id:'s4_615', unit:'u5', lesson:'u5l1', page:156, difficulty:'medium', bloom:'apply', type:'multipleChoice',
    question:'وجبة تحتوي على دجاج + أرز + خضار + عصير برتقال. ما العناصر الغذائية فيها؟',
    options:[{text:'بروتين + كربوهيدرات + فيتامينات + ألياف',correct:true},{text:'بروتين فقط',correct:false},{text:'كربوهيدرات فقط',correct:false},{text:'دهون فقط',correct:false}],
    explanation:'دجاج=بروتين، أرز=كربوهيدرات، خضار=ألياف، عصير=فيتامينات. وجبة متوازنة.',
    goldenRule:'وجبة متوازنة = بروتين + نشويات + ألياف + فيتامينات.',
    paragraph:'الوجبة المتوازنة — ص ١٥٦',
  },
  { id:'s4_616', unit:'u5', lesson:'u5l1', page:157, difficulty:'hard', bloom:'evaluate', type:'trueFalse',
    question:'تنظيم وجبات الطعام في مواعيد ثابتة يحافظ على صحة الجهاز الهضمي.',
    correctAnswer:'true',
    explanation:'الانتظام في مواعيد الوجبات يُحافظ على صحة الجهاز الهضمي وانتظام الهضم.',
    goldenRule:'مواعيد ثابتة = جهاز هضمي صحي.',
    paragraph:'انتظام الوجبات — ص ١٥٧',
  },
  { id:'s4_617', unit:'u5', lesson:'u5l1', page:158, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'الإفطار من أهم الوجبات لأنه:',
    options:[{text:'يُعطي الطاقة للجسم بعد النوم',correct:true},{text:'يزيد الوزن',correct:false},{text:'يُضعف الجسم',correct:false},{text:'لا أهمية له',correct:false}],
    explanation:'الإفطار يُعطي الطاقة والنشاط بعد صيام النوم ويساعد على التركيز في المدرسة.',
    goldenRule:'إفطار = طاقة + تركيز (بعد النوم).',
    paragraph:'أهمية الإفطار — ص ١٥٨',
  },
  { id:'s4_618', unit:'u5', lesson:'u5l1', page:159, difficulty:'medium', bloom:'understand', type:'classify',
    question:'صنّف العناصر الغذائية حسب وظيفتها:',
    categories:['طاقة', 'نمو'],
    items:[
      {text:'الكربوهيدرات', correct_category:0},
      {text:'البروتينات', correct_category:1},
      {text:'الدهون', correct_category:0},
      {text:'الكالسيوم (عظام)', correct_category:1},
      {text:'السكر', correct_category:0},
    ],
    explanation:'طاقة: كربوهيدرات، دهون، سكر. نمو: بروتينات، كالسيوم.',
    goldenRule:'طاقة = كربوهيدرات/دهون | نمو = بروتين/كالسيوم.',
    paragraph:'وظائف العناصر — ص ١٥٩',
  },
  { id:'s4_619', unit:'u5', lesson:'u5l1', page:160, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'الفواكه والخضروات غنية بالفيتامينات والألياف.',
    correctAnswer:'true',
    explanation:'الفواكه والخضروات غنية بالفيتامينات والألياف والماء وتقي من الأمراض.',
    goldenRule:'فواكه + خضروات = فيتامينات + ألياف + وقاية.',
    paragraph:'الفواكه والخضروات — ص ١٦٠',
  },
  { id:'s4_620', unit:'u5', lesson:'u5l1', page:161, difficulty:'medium', bloom:'apply', type:'multipleChoice',
    question:'أيّ الوجبات التالية تُعدّ غير صحية؟',
    options:[{text:'همبرغر وبطاطس مقلية ومشروب غازي',correct:true},{text:'سمك مشوي وأرز وسلطة',correct:false},{text:'حليب وخبز وعسل',correct:false},{text:'فواكه وشوفان',correct:false}],
    explanation:'الهمبرغر والبطاطس المقلية والمشروبات الغازية وجبة غير صحية لزيادة الدهون والسكر.',
    goldenRule:'وجبات سريعة + مشروبات غازية = غير صحية.',
    paragraph:'الوجبات غير الصحية — ص ١٦١',
  },
  { id:'s4_621', unit:'u5', lesson:'u5l1', page:162, difficulty:'hard', bloom:'analyze', type:'trueFalse',
    question:'نقص فيتامين د يُسبب الكساح وتشوّه العظام.',
    correctAnswer:'true',
    explanation:'فيتامين د يساعد على امتصاص الكالسيوم ونقصه يُسبب الكساح وتشوّه العظام.',
    goldenRule:'نقص د = كساح (نقص امتصاص كالسيوم).',
    paragraph:'نقص فيتامين د — ص ١٦٢',
  },
  { id:'s4_622', unit:'u5', lesson:'u5l1', page:163, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'أيّ العناصر التالية يُساعد على امتصاص الكالسيوم؟',
    options:[{text:'فيتامين د',correct:true},{text:'فيتامين ج',correct:false},{text:'الحديد',correct:false},{text:'السكر',correct:false}],
    explanation:'فيتامين د يُساعد الأمعاء على امتصاص الكالسيوم من الغذاء.',
    goldenRule:'د = يُساعد امتصاص الكالسيوم.',
    paragraph:'فيتامين د — ص ١٦٣',
  },
  { id:'s4_623', unit:'u5', lesson:'u5l1', page:145, difficulty:'medium', bloom:'understand', type:'trueFalse',
    question:'الدهون تُخزّن الفيتامينات الذائبة في الدهون كأ، د، هـ، ك.',
    correctAnswer:'true',
    explanation:'الدهون تُساعد على امتصاص وتخزين الفيتامينات الذائبة فيها (أ، د، هـ، ك).',
    goldenRule:'دهون = تخزين فيتامينات (أ، د، هـ، ك).',
    paragraph:'دور الدهون — ص ١٤٥',
  },
  { id:'s4_624', unit:'u5', lesson:'u5l1', page:148, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'أيّ الأطعمة التالية غني بالكالسيوم؟',
    options:[{text:'الحليب ومنتجاته',correct:true},{text:'اللحوم الحمراء',correct:false},{text:'السكر',correct:false},{text:'الزيوت',correct:false}],
    explanation:'الحليب والجبن والزبادي من أغنى مصادر الكالسيوم.',
    goldenRule:'حليب + جبن + زبادي = كالسيوم.',
    paragraph:'مصادر الكالسيوم — ص ١٤٨',
  },
  { id:'s4_625', unit:'u5', lesson:'u5l1', page:152, difficulty:'medium', bloom:'apply', type:'multipleChoice',
    question:'طفل يعاني من إمساك متكرر. ما النصيحة الغذائية الأنسب؟',
    options:[{text:'زيادة الألياف والماء',correct:true},{text:'زيادة الدهون',correct:false},{text:'تقليل الماء',correct:false},{text:'زيادة السكر',correct:false}],
    explanation:'الألياف والماء يُحسّنان حركة الأمعاء ويمنعان الإمساك.',
    goldenRule:'إمساك = نقص ألياف/ماء → زيادتها.',
    paragraph:'علاج الإمساك — ص ١٥٢',
  },
  { id:'s4_626', unit:'u5', lesson:'u5l1', page:149, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'الحديد يوجد في اللحوم والكبد والبقوليات والخضروات الورقية.',
    correctAnswer:'true',
    explanation:'الحديد يوجد في اللحوم والكبد والبقوليات والخضروات الورقية كالسبانخ.',
    goldenRule:'حديد = لحم + كبد + بقوليات + سبانخ.',
    paragraph:'مصادر الحديد — ص ١٤٩',
  },
  { id:'s4_627', unit:'u5', lesson:'u5l1', page:157, difficulty:'hard', bloom:'evaluate', type:'multipleChoice',
    question:'لماذا يُنصح بعدم الإفراط في تناول الأملاح؟',
    options:[{text:'لأنها ترفع ضغط الدم',correct:true},{text:'لأنها تُقوّي العظام',correct:false},{text:'لأنها تُحسّن الرؤية',correct:false},{text:'لأنها تزيد النشاط',correct:false}],
    explanation:'الإفراط في الأملاح (الصوديوم) يرفع ضغط الدم ويُؤذي القلب.',
    goldenRule:'أملاح زائدة = ضغط دم مرتفع.',
    paragraph:'الإفراط في الأملاح — ص ١٥٧',
  },
  { id:'s4_628', unit:'u5', lesson:'u5l1', page:163, difficulty:'medium', bloom:'understand', type:'trueFalse',
    question:'تناول وجبات متنوعة من كل المجموعات الغذائية يحافظ على صحة الجسم.',
    correctAnswer:'true',
    explanation:'التنويع في الوجبات يضمن حصول الجسم على جميع العناصر الغذائية اللازمة.',
    goldenRule:'تنويع = غذاء متوازن = صحة.',
    paragraph:'الغذاء المتوازن — ص ١٦٣',
  },

  // ═══ الدرس 2: الهرم الغذائي والتغذية الصحية (28 سؤال) ═══
  { id:'s4_629', unit:'u5', lesson:'u5l2', page:164, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'الهرم الغذائي دليل يساعد على:',
    options:[{text:'اختيار الغذاء الصحي المتوازن',correct:true},{text:'حساب الوزن',correct:false},{text:'قياس الطول',correct:false},{text:'تحديد العمر',correct:false}],
    explanation:'الهرم الغذائي دليل يُرشد الإنسان لاختيار الغذاء المتوازن المناسب.',
    goldenRule:'هرم غذائي = دليل الغذاء المتوازن.',
    paragraph:'الهرم الغذائي — ص ١٦٤',
  },
  { id:'s4_630', unit:'u5', lesson:'u5l2', page:165, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'قاعدة الهرم الغذائي تضمّ الأطعمة التي يجب تناولها بكثرة.',
    correctAnswer:'true',
    explanation:'قاعدة الهرم (الخبز، الخضروات، الفواكه) تُؤكل بكثرة يومياً.',
    goldenRule:'قاعدة الهرم = أكثر تناولاً.',
    paragraph:'قاعدة الهرم — ص ١٦٥',
  },
  { id:'s4_631', unit:'u5', lesson:'u5l2', page:166, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'أيّ الأطعمة في قمة الهرم الغذائي؟',
    options:[{text:'الدهون والسكريات والحلوى',correct:true},{text:'الخضروات',correct:false},{text:'الخبز',correct:false},{text:'الفواكه',correct:false}],
    explanation:'قمة الهرم: دهون وسكريات وحلوى، يجب تناولها بكميات قليلة جداً.',
    goldenRule:'قمة الهرم = أقل تناولاً (دهون/سكريات).',
    paragraph:'قمة الهرم — ص ١٦٦',
  },
  { id:'s4_632', unit:'u5', lesson:'u5l2', page:167, difficulty:'medium', bloom:'understand', type:'classify',
    question:'صنّف الأطعمة حسب موقعها في الهرم:',
    categories:['القاعدة (أكثر تناولاً)', 'القمة (أقل تناولاً)'],
    items:[
      {text:'الخبز', correct_category:0},
      {text:'الحلوى', correct_category:1},
      {text:'الخضروات', correct_category:0},
      {text:'الزبدة', correct_category:1},
      {text:'الفواكه', correct_category:0},
      {text:'المشروبات الغازية', correct_category:1},
    ],
    explanation:'قاعدة: خبز، خضروات، فواكه. قمة: حلوى، زبدة، غازية.',
    goldenRule:'قاعدة = أكثر | قمة = أقل.',
    paragraph:'طبقات الهرم — ص ١٦٧',
  },
  { id:'s4_633', unit:'u5', lesson:'u5l2', page:168, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'عدد وجبات الطعام اليومية المناسبة للطفل:',
    options:[{text:'ثلاث وجبات رئيسية',correct:true},{text:'وجبة واحدة',correct:false},{text:'خمس وجبات كبيرة',correct:false},{text:'لا وجبات',correct:false}],
    explanation:'يُنصح بثلاث وجبات رئيسية (إفطار، غداء، عشاء) مع وجبتين خفيفتين.',
    goldenRule:'3 وجبات رئيسية + 2 خفيفة = نظام صحي.',
    paragraph:'الوجبات اليومية — ص ١٦٨',
  },
  { id:'s4_634', unit:'u5', lesson:'u5l2', page:169, difficulty:'medium', bloom:'apply', type:'trueFalse',
    question:'الإفطار الصحي يُحسّن أداء الطالب في المدرسة وتركيزه.',
    correctAnswer:'true',
    explanation:'الإفطار يُعطي الطاقة للدماغ ويُحسّن التركيز والأداء الدراسي.',
    goldenRule:'إفطار = طاقة + تركيز في المدرسة.',
    paragraph:'أهمية الإفطار — ص ١٦٩',
  },
  { id:'s4_635', unit:'u5', lesson:'u5l2', page:170, difficulty:'hard', bloom:'analyze', type:'multipleChoice',
    question:'الإفراط في الوجبات السريعة يُسبب:',
    options:[{text:'السمنة وأمراض القلب وارتفاع الكوليسترول',correct:true},{text:'قوة العضلات',correct:false},{text:'تحسّن الرؤية',correct:false},{text:'زيادة النشاط',correct:false}],
    explanation:'الوجبات السريعة غنية بالدهون والسكر، والإفراط فيها يُسبب السمنة وأمراض القلب.',
    goldenRule:'وجبات سريعة زائدة = سمنة + قلب + كوليسترول.',
    paragraph:'أضرار الوجبات السريعة — ص ١٧٠',
  },
  { id:'s4_636', unit:'u5', lesson:'u5l2', page:171, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'الماء من العناصر المهمة. كم كوباً يُنصح بشربها يومياً؟',
    options:[{text:'6-8 أكواب',correct:true},{text:'كوب واحد',correct:false},{text:'3 أكواب',correct:false},{text:'لا ماء',correct:false}],
    explanation:'يُنصح بشرب 6-8 أكواب ماء يومياً للحفاظ على صحة الجسم.',
    goldenRule:'6-8 أكواب ماء = حاجة يومية.',
    paragraph:'شرب الماء — ص ١٧١',
  },
  { id:'s4_637', unit:'u5', lesson:'u5l2', page:172, difficulty:'medium', bloom:'understand', type:'trueFalse',
    question:'الوجبة المتوازنة تحتوي على جميع المجموعات الغذائية بنسب مناسبة.',
    correctAnswer:'true',
    explanation:'الوجبة المتوازنة تضمّ كربوهيدرات + بروتين + دهون + فيتامينات + ألياف + ماء.',
    goldenRule:'وجبة متوازنة = كل المجموعات بنسب مناسبة.',
    paragraph:'الوجبة المتوازنة — ص ١٧٢',
  },
  { id:'s4_638', unit:'u5', lesson:'u5l2', page:173, difficulty:'medium', bloom:'apply', type:'multipleChoice',
    question:'أيّ الخيارات التالية يُمثّل وجبة متوازنة؟',
    options:[{text:'سمك + أرز + سلطة + حليب',correct:true},{text:'شوكولاتة فقط',correct:false},{text:'خبز فقط',correct:false},{text:'مشروب غازي فقط',correct:false}],
    explanation:'سمك(بروتين) + أرز(كربوهيدرات) + سلطة(فيتامينات/ألياف) + حليب(كالسيوم) = متوازنة.',
    goldenRule:'متوازنة = بروتين + نشويات + خضار + كالسيوم.',
    paragraph:'الوجبة المتوازنة — ص ١٧٣',
  },
  { id:'s4_639', unit:'u5', lesson:'u5l2', page:174, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'المشروبات الغازية تحتوي على سكريات عالية ولا تُعدّ صحية.',
    correctAnswer:'true',
    explanation:'المشروبات الغازية غنية بالسكر والصودا وتُسبب تسوس الأسنان والسمنة.',
    goldenRule:'غازية = سكر عالي + غير صحية.',
    paragraph:'المشروبات الغازية — ص ١٧٤',
  },
  { id:'s4_640', unit:'u5', lesson:'u5l2', page:166, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'في الهرم الغذائي، مجموعة الحليب واللحوم:',
    options:[{text:'تُؤكل بكميات معتدلة',correct:true},{text:'تُؤكل بكثرة',correct:false},{text:'لا تُؤكل',correct:false},{text:'تُؤكل بكميات قليلة جداً',correct:false}],
    explanation:'الحليب واللحوم في الطبقة الوسطى من الهرم تُؤكل بكميات معتدلة.',
    goldenRule:'حليب/لحوم = معتدل (وسط الهرم).',
    paragraph:'طبقات الهرم — ص ١٦٦',
  },
  { id:'s4_641', unit:'u5', lesson:'u5l2', page:168, difficulty:'hard', bloom:'analyze', type:'trueFalse',
    question:'تناول الطعام قبل النوم مباشرة قد يُسبب عسر الهضم ويزيد الوزن.',
    correctAnswer:'true',
    explanation:'الأكل قبل النوم يُسبب عسر الهضم ويزيد الوزن لأن الجسم لا يحرق السعرات.',
    goldenRule:'لا تأكل قبل النوم = هضم سليم + وزن معتدل.',
    paragraph:'الأكل قبل النوم — ص ١٦٨',
  },
  { id:'s4_642', unit:'u5', lesson:'u5l2', page:169, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'أيّ المشروبات التالية بديل صحي للمشروبات الغازية؟',
    options:[{text:'الماء والعصير الطبيعي',correct:true},{text:'العصير المصنّع المحلّى',correct:false},{text:'المشروبات الغازية',correct:false},{text:'القهوة بكثرة',correct:false}],
    explanation:'الماء والعصير الطبيعي بدائل صحية للمشروبات الغازية.',
    goldenRule:'ماء + عصير طبيعي = بديل صحي.',
    paragraph:'بدائل صحية — ص ١٦٩',
  },
  { id:'s4_643', unit:'u5', lesson:'u5l2', page:172, difficulty:'medium', bloom:'understand', type:'classify',
    question:'صنّف الأطعمة حسب صحتها:',
    categories:['صحي', 'أقل صحة'],
    items:[
      {text:'الفواكه', correct_category:0},
      {text:'الخضروات', correct_category:0},
      {text:'الوجبات السريعة', correct_category:1},
      {text:'الحلويات', correct_category:1},
      {text:'الحليب', correct_category:0},
      {text:'المشروبات الغازية', correct_category:1},
    ],
    explanation:'صحي: فواكه، خضروات، حليب. أقل: وجبات سريعة، حلويات، غازية.',
    goldenRule:'طبيعي = صحي | مصنّع = أقل صحة.',
    paragraph:'تصنيف الأطعمة — ص ١٧٢',
  },
  { id:'s4_644', unit:'u5', lesson:'u5l2', page:170, difficulty:'medium', bloom:'apply', type:'multipleChoice',
    question:'طفل يكثر من أكل الحلوى ولا يراجع الطبيب. ما المخاطر المتوقعة؟',
    options:[{text:'تسوس الأسنان والسمنة وارتفاع السكر',correct:true},{text:'قوة العظام',correct:false},{text:'تحسّن الرؤية',correct:false},{text:'زيادة الطول',correct:false}],
    explanation:'كثرة الحلوى تُسبب تسوس الأسنان والسمنة وارتفاع السكر في الدم.',
    goldenRule:'حلوى زائدة = تسوس + سمنة + سكر مرتفع.',
    paragraph:'أضرار الحلوى — ص ١٧٠',
  },
  { id:'s4_645', unit:'u5', lesson:'u5l2', page:171, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'شرب الماء أثناء الوجبات يساعد على الهضم.',
    correctAnswer:'true',
    explanation:'الماء يُساعد على هضم الطعام وامتصاصه وإزالة الفضلات.',
    goldenRule:'ماء + وجبة = هضم أفضل.',
    paragraph:'الماء والهضم — ص ١٧١',
  },
  { id:'s4_646', unit:'u5', lesson:'u5l2', page:173, difficulty:'hard', bloom:'evaluate', type:'multipleChoice',
    question:'لماذا يُنصح بتنويع الطعام في كل وجبة؟',
    options:[{text:'لضمان حصول الجسم على جميع العناصر الغذائية',correct:true},{text:'لزيادة الوزن',correct:false},{text:'لإضعاف الجسم',correct:false},{text:'لكثرة الأكل',correct:false}],
    explanation:'تنويع الطعام يضمن حصول الجسم على كل العناصر (بروتين، كربوهيدرات، فيتامينات).',
    goldenRule:'تنويع = كل العناصر الغذائية.',
    paragraph:'تنويع الطعام — ص ١٧٣',
  },
  { id:'s4_647', unit:'u5', lesson:'u5l2', page:164, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'الهرم الغذائي مقسّم إلى:',
    options:[{text:'طبقات (مجموعات)',correct:true},{text:'طبقة واحدة',correct:false},{text:'دوائر',correct:false},{text:'خطوط',correct:false}],
    explanation:'الهرم الغذائي مقسّم إلى طبقات تمثّل مجموعات غذائية.',
    goldenRule:'هرم = طبقات (مجموعات غذائية).',
    paragraph:'طبقات الهرم — ص ١٦٤',
  },
  { id:'s4_648', unit:'u5', lesson:'u5l2', page:167, difficulty:'medium', bloom:'understand', type:'trueFalse',
    question:'كلما ارتفعنا في الهرم الغذائي قلّت كمية الطعام المسموح تناولها.',
    correctAnswer:'true',
    explanation:'القاعدة أكبر كمية والقمة أقل كمية، فالارتفاع يقلل الكمية.',
    goldenRule:'ارتفاع في الهرم = قلة الكمية.',
    paragraph:'ارتفاع الهرم — ص ١٦٧',
  },
  { id:'s4_649', unit:'u5', lesson:'u5l2', page:169, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'الوجبة الخفيفة الصحية بين الوجبات الرئيسية تضم:',
    options:[{text:'فواكه أو خضروات أو مكسرات',correct:true},{text:'حلوى بكثرة',correct:false},{text:'مشروبات غازية',correct:false},{text:'وجبات سريعة',correct:false}],
    explanation:'الوجبة الخفيفة الصحية: فواكه، خضروات، مكسرات، زبادي.',
    goldenRule:'خفيفة صحية = فواكه/خضروات/مكسرات.',
    paragraph:'الوجبات الخفيفة — ص ١٦٩',
  },
  { id:'s4_650', unit:'u5', lesson:'u5l2', page:174, difficulty:'medium', bloom:'apply', type:'multipleChoice',
    question:'أيّ النصائح التالية تُحسّن التغذية الصحية؟',
    options:[{text:'تنويع الطعام وتقليل السكر والدهون',correct:true},{text:'زيادة الوجبات السريعة',correct:false},{text:'شرب غازيات بكثرة',correct:false},{text:'إهمال الإفطار',correct:false}],
    explanation:'تنويع الطعام وتقليل السكر والدهون من أهم قواعد التغذية الصحية.',
    goldenRule:'تغذية صحية = تنويع + تقليل سكر/دهون.',
    paragraph:'التغذية الصحية — ص ١٧٤',
  },
  { id:'s4_651', unit:'u5', lesson:'u5l2', page:165, difficulty:'hard', bloom:'analyze', type:'trueFalse',
    question:'الخضروات والفواكه تُؤكل بكميات كبيرة لأنها قليلة السعرات وغنية بالفيتامينات.',
    correctAnswer:'true',
    explanation:'الخضروات والفواكه قليلة السعرات غنية بالفيتامينات والألياف فيُؤكل منها الكثير.',
    goldenRule:'خضروات + فواكه = فيتامينات + قليل سعرات = كمية أكبر.',
    paragraph:'الخضروات والفواكه — ص ١٦٥',
  },
  { id:'s4_652', unit:'u5', lesson:'u5l2', page:172, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'قراءة المعلومات الغذائية على المنتجات تساعد على:',
    options:[{text:'معرفة محتوى السعرات والدهون والسكر',correct:true},{text:'زيادة الوزن',correct:false},{text:'تخفيف لون المنتج',correct:false},{text:'تغيير طعمه',correct:false}],
    explanation:'قراءة الملصق الغذائي تُعرف كمية السعرات والدهون والسكر وتساعد على الاختيار الصحي.',
    goldenRule:'اقرأ الملصق = اعرف المحتوى = اختيار صحي.',
    paragraph:'الملصق الغذائي — ص ١٧٢',
  },
  { id:'s4_653', unit:'u5', lesson:'u5l2', page:174, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'الغذاء الصحي جزء من نمط الحياة الصحي.',
    correctAnswer:'true',
    explanation:'الغذاء الصحي مع الرياضة والنوم الكافي جزء من نمط الحياة الصحي.',
    goldenRule:'غذاء صحي + رياضة + نوم = حياة صحية.',
    paragraph:'نمط الحياة الصحي — ص ١٧٤',
  },
  { id:'s4_654', unit:'u5', lesson:'u5l2', page:166, difficulty:'medium', bloom:'apply', type:'multipleChoice',
    question:'في وجبة غداء، تناول طالب خبزاً ودجاجاً وأرزاً. ما المجموعة الناقصة؟',
    options:[{text:'الخضروات والفواكه',correct:true},{text:'الكربوهيدرات',correct:false},{text:'البروتين',correct:false},{text:'الدهون',correct:false}],
    explanation:'نقص الخضروات والفواكه يُقلل الفيتامينات والألياف في الوجبة.',
    goldenRule:'وجبة بدون خضار/فواكه = ناقصة.',
    paragraph:'الوجبة الناقصة — ص ١٦٦',
  },
  { id:'s4_655', unit:'u5', lesson:'u5l2', page:170, difficulty:'hard', bloom:'evaluate', type:'trueFalse',
    question:'استبدال الوجبات السريعة بوجبات منزلية متوازنة يُحسّن الصحة ويُقلل الأمراض.',
    correctAnswer:'true',
    explanation:'الوجبات المنزلية المتوازنة تتحكم في الدهون والسكر وتُحسّن الصحة.',
    goldenRule:'منزلي متوازن > سريع = صحة أفضل.',
    paragraph:'الوجبات المنزلية — ص ١٧٠',
  },
  { id:'s4_656', unit:'u5', lesson:'u5l2', page:171, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'شرب العصائر الطبيعية أفضل من المصنّعة لأن:',
    options:[{text:'الطبيعية بلا سكر مضاف وغنية بالفيتامينات',correct:true},{text:'المصنّعة أرخص',correct:false},{text:'المصنّعة أحلى',correct:false},{text:'لا فرق',correct:false}],
    explanation:'العصير الطبيعي بلا سكر مضاف ويحتفظ بالفيتامينات على عكس المصنّع.',
    goldenRule:'طبيعي > مصنّع (لا سكر مضاف + فيتامينات).',
    paragraph:'العصير الطبيعي — ص ١٧١',
  },

  // ═══ الدرس 3: العادات الصحية (28 سؤال) ═══
  { id:'s4_657', unit:'u5', lesson:'u5l3', page:175, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'الرياضة من أهم العادات الصحية. ما فوائدها؟',
    options:[{text:'تقوية القلب والعضلات وتحسين الصحة',correct:true},{text:'زيادة الوزن',correct:false},{text:'إضعاف الجسم',correct:false},{text:'إقلال المناعة',correct:false}],
    explanation:'الرياضة تقوّي القلب والعضلات وتُحسّن المزاج والمناعة.',
    goldenRule:'رياضة = قلب + عضلات + مزاج + مناعة.',
    paragraph:'الرياضة — ص ١٧٥',
  },
  { id:'s4_658', unit:'u5', lesson:'u5l3', page:176, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'النوم الكافي يساعد على تجدد خلايا الجسم ونشاطه.',
    correctAnswer:'true',
    explanation:'النوم الكافي يجدد الخلايا ويصلح التالف ويخزن الطاقة.',
    goldenRule:'نوم = تجدد + إصلاح + طاقة.',
    paragraph:'أهمية النوم — ص ١٧٦',
  },
  { id:'s4_659', unit:'u5', lesson:'u5l3', page:177, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'كم ساعة نوم يحتاجها الطفل يومياً؟',
    options:[{text:'8-10 ساعات',correct:true},{text:'ساعتان',correct:false},{text:'أربع ساعات',correct:false},{text:'عشر ساعات للبالغ',correct:false}],
    explanation:'يحتاج الطفل 8-10 ساعات نوم يومياً لنمو سليم وتجدد خلاياه.',
    goldenRule:'طفل = 8-10 ساعات نوم.',
    paragraph:'ساعات النوم — ص ١٧٧',
  },
  { id:'s4_660', unit:'u5', lesson:'u5l3', page:178, difficulty:'medium', bloom:'apply', type:'classify',
    question:'صنّف العادات التالية:',
    categories:['صحي', 'مضر'],
    items:[
      {text:'ممارسة الرياضة', correct_category:0},
      {text:'السهر لوقت متأخر', correct_category:1},
      {text:'شرب الماء بكثرة', correct_category:0},
      {text:'تناول وجبات سريعة بكثرة', correct_category:1},
      {text:'النوم المبكر', correct_category:0},
      {text:'التدخين', correct_category:1},
    ],
    explanation:'صحي: رياضة، ماء، نوم مبكر. مضر: سهر، وجبات سريعة، تدخين.',
    goldenRule:'صحي = رياضة/ماء/نوم | مضر = سهر/سريع/تدخين.',
    paragraph:'العادات الصحية والمضرة — ص ١٧٨',
  },
  { id:'s4_661', unit:'u5', lesson:'u5l3', page:179, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'النظافة الشخصية تُساعد على:',
    options:[{text:'الوقاية من الأمراض والإحساس بالنشاط',correct:true},{text:'زيادة الوزن',correct:false},{text:'إضعاف الجسم',correct:false},{text:'تغيير لون الجلد',correct:false}],
    explanation:'النظافة الشخصية تمنع انتقال الجراثيم وتُحسّن المزاج والصحة.',
    goldenRule:'نظافة شخصية = وقاية + نشاط + صحة.',
    paragraph:'النظافة الشخصية — ص ١٧٩',
  },
  { id:'s4_662', unit:'u5', lesson:'u5l3', page:180, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'غسل الأسنان مرتين يومياً على الأقل يقي من التسوس وأمراض اللثة.',
    correctAnswer:'true',
    explanation:'تنظيف الأسنان مرتين يومياً بالفرشاة والمعجون يقي من التسوس.',
    goldenRule:'تنظيف أسنان 2× يومياً = وقاية.',
    paragraph:'نظافة الأسنان — ص ١٨٠',
  },
  { id:'s4_663', unit:'u5', lesson:'u5l3', page:181, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'أيّ العادات التالية يُحسّن النوم؟',
    options:[{text:'النوم في وقت ثابت وفي مكان هادئ',correct:true},{text:'النوم بمروحة قوية',correct:false},{text:'النوم بعد قهوة بكثرة',correct:false},{text:'النوم بالنهار دائماً',correct:false}],
    explanation:'النوم في وقت ثابت ومكان هادئ يُحسّن جودة النوم وصحته.',
    goldenRule:'وقت ثابت + مكان هادئ = نوم جيد.',
    paragraph:'جودة النوم — ص ١٨١',
  },
  { id:'s4_664', unit:'u5', lesson:'u5l3', page:182, difficulty:'medium', bloom:'apply', type:'multipleChoice',
    question:'أيّ التصرفات التالية يُحافظ على القوام السليم؟',
    options:[{text:'الجلوس والوقوف بظهر مستقيم',correct:true},{text:'الجلوس بظهر منحنٍ',correct:false},{text:'حمل حقائب ثقيلة على كتف واحدة',correct:false},{text:'النوم على وسادة عالية',correct:false}],
    explanation:'الجلوس والوقوف بظهر مستقيم يحمي العمود الفقري من التشوه.',
    goldenRule:'ظهر مستقيم = عمود فقري سليم.',
    paragraph:'القوام السليم — ص ١٨٢',
  },
  { id:'s4_665', unit:'u5', lesson:'u5l3', page:183, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'الإفراط في استخدام الهاتف قبل النوم يُضعف جودة النوم.',
    correctAnswer:'true',
    explanation:'ضوء الهاتف يُأخرّر النوم ويُضعف جودته.',
    goldenRule:'هاتف قبل النوم = نوم ضعيف.',
    paragraph:'الهاتف والنوم — ص ١٨٣',
  },
  { id:'s4_666', unit:'u5', lesson:'u5l3', page:184, difficulty:'medium', bloom:'understand', type:'classify',
    question:'صنّف العادات حسب تأثيرها على النوم:',
    categories:['يُحسّن النوم', 'يُضعف النوم'],
    items:[
      {text:'النوم المبكر', correct_category:0},
      {text:'شرب قهوة بكثرة ليلاً', correct_category:1},
      {text:'غرفة هادئة ومظلمة', correct_category:0},
      {text:'السهر على الهاتف', correct_category:1},
      {text:'مزاملة قيلولة قصيرة', correct_category:0},
    ],
    explanation:'يُحسّن: نوم مبكر، غرفة هادئة، قيلولة. يُضعف: قهوة ليلاً، هاتف، سهر.',
    goldenRule:'نوم جيد = هدوء + ظلام + لا قهوة/هاتف.',
    paragraph:'جودة النوم — ص ١٨٤',
  },
  { id:'s4_667', unit:'u5', lesson:'u5l3', page:185, difficulty:'hard', bloom:'analyze', type:'multipleChoice',
    question:'لماذا يُنصح بعدم تناول المنبهات بكثرة للأطفال؟',
    options:[{text:'لأنها تُؤثر على النوم والتركيز والنمو',correct:true},{text:'لأنها تُقوّي المناعة',correct:false},{text:'لأنها تزيد الطول',correct:false},{text:'لأنها مفيدة دائماً',correct:false}],
    explanation:'المنبهات (قهوة، شاي، غازيات) تُؤثر على نوم وتركيز ونمو الأطفال.',
    goldenRule:'منبهات + أطفال = نوم ضعيف + ضعف تركيز.',
    paragraph:'المنبهات والأطفال — ص ١٨٥',
  },
  { id:'s4_668', unit:'u5', lesson:'u5l3', page:175, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'أيّ الأنشطة التالية يُعدّ رياضة؟',
    options:[{text:'الجري والسباحة وركوب الدراجة',correct:true},{text:'المشاهدة التلفاز',correct:false},{text:'اللعب بالهاتف',correct:false},{text:'الأكل',correct:false}],
    explanation:'الجري والسباحة وركوب الدراجة من الرياضات المفيدة للجسم.',
    goldenRule:'جري/سباحة/دراجة = رياضة.',
    paragraph:'أنواع الرياضة — ص ١٧٥',
  },
  { id:'s4_669', unit:'u5', lesson:'u5l3', page:176, difficulty:'medium', bloom:'understand', type:'trueFalse',
    question:'النوم المنتظم يساعد على تحسين الأداء الدراسي.',
    correctAnswer:'true',
    explanation:'النوم المنتظم يُحسّن التركيز والذاكرة والأداء الدراسي.',
    goldenRule:'نوم منتظم = تركيز + ذاكرة + أداء أفضل.',
    paragraph:'النوم والدراسة — ص ١٧٦',
  },
  { id:'s4_670', unit:'u5', lesson:'u5l3', page:177, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'أيّ العادات التالية تُحافظ على صحة الجلد؟',
    options:[{text:'الاستحمام وترطيب الجلد وشرب الماء',correct:true},{text:'عدم الغسل',correct:false},{text:'التعرض للشمس بكثرة',correct:false},{text:'شرب غازيات بكثرة',correct:false}],
    explanation:'الاستحمام والترطيب وشرب الماء يحافظون على صحة الجلد.',
    goldenRule:'جلد صحي = استحمام + ترطيب + ماء.',
    paragraph:'صحة الجلد — ص ١٧٧',
  },
  { id:'s4_671', unit:'u5', lesson:'u5l3', page:178, difficulty:'medium', bloom:'apply', type:'multipleChoice',
    question:'طالب يكثر من الجلوس أمام الشاشة. ما النصيحة الأنسب؟',
    options:[{text:'أخذ فترات راحة وتقليل وقت الشاشة',correct:true},{text:'زيادة وقت الشاشة',correct:false},{text:'لا حاجة لراحة',correct:false},{text:'الجلوس في الظلام',correct:false}],
    explanation:'أخذ فترات راحة وتقليل وقت الشاشة يحمي العينين والظهر.',
    goldenRule:'فترات راحة + قلل شاشة = عيون وظهر صحية.',
    paragraph:'وقت الشاشة — ص ١٧٨',
  },
  { id:'s4_672', unit:'u5', lesson:'u5l3', page:179, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'قص الأظافر بانتظام من العادات الصحية الشخصية.',
    correctAnswer:'true',
    explanation:'قص الأظافر يمنع تراكم الأوساخ والجراثيم تحتها.',
    goldenRule:'أظافر قصيرة = نظافة + لا جراثيم.',
    paragraph:'نظافة الأظافر — ص ١٧٩',
  },
  { id:'s4_673', unit:'u5', lesson:'u5l3', page:180, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'الإفراط في تناول السكريات يُسبب:',
    options:[{text:'تسوس الأسنان والسمنة',correct:true},{text:'قوة العظام',correct:false},{text:'تحسّن الرؤية',correct:false},{text:'زيادة المناعة',correct:false}],
    explanation:'الإفراط في السكريات يُسبب التسوس والسمنة وارتفاع السكر.',
    goldenRule:'سكر زائد = تسوس + سمنة + سكر دم.',
    paragraph:'أضرار السكريات — ص ١٨٠',
  },
  { id:'s4_674', unit:'u5', lesson:'u5l3', page:181, difficulty:'hard', bloom:'evaluate', type:'trueFalse',
    question:'الوعي الصحي يساعد الفرد على اتخاذ قرارات صحية سليمة في حياته.',
    correctAnswer:'true',
    explanation:'الوعي الصحي يُمكّن الفرد من اختيار العادات الصحية واتخاذ القرارات السليمة.',
    goldenRule:'وعي صحي = قرارات سليمة = حياة صحية.',
    paragraph:'الوعي الصحي — ص ١٨١',
  },
  { id:'s4_675', unit:'u5', lesson:'u5l3', page:182, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'القيلولة القصيرة بعد الظهر تُساعد على:',
    options:[{text:'تجديد النشاط والطاقة',correct:true},{text:'زيادة الوزن',correct:false},{text:'إضعاف الجسم',correct:false},{text:'تقليل المناعة',correct:false}],
    explanation:'القيلولة القصيرة (20-30 دقيقة) تُجدد النشاط وتُحسّن التركيز.',
    goldenRule:'قيلولة قصيرة = نشاط + تركيز.',
    paragraph:'القيلولة — ص ١٨٢',
  },
  { id:'s4_676', unit:'u5', lesson:'u5l3', page:183, difficulty:'medium', bloom:'apply', type:'multipleChoice',
    question:'أيّ العادات التالية يحمي العينين من التعب؟',
    options:[{text:'قراءة في إضاءة جيدة وأخذ فترات راحة',correct:true},{text:'القراءة في الظلام',correct:false},{text:'القراءة بمصدر قوي قريب',correct:false},{text:'القراءة لساعات بلا راحة',correct:false}],
    explanation:'الإضاءة الجيدة وفترات الراحة تحمي العينين من التعب.',
    goldenRule:'إضاءة جيدة + راحة = عينان صحية.',
    paragraph:'صحة العينين — ص ١٨٣',
  },
  { id:'s4_677', unit:'u5', lesson:'u5l3', page:184, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'غسل اليدين قبل الأكل وبعد دخول الحمام من العادات الصحية.',
    correctAnswer:'true',
    explanation:'غسل اليدين قبل الأكل وبعد الحمام يمنع انتقال الجراثيم.',
    goldenRule:'غسل يدين (قبل أكل + بعد حمام) = وقاية.',
    paragraph:'غسل اليدين — ص ١٨٤',
  },
  { id:'s4_678', unit:'u5', lesson:'u5l3', page:185, difficulty:'medium', bloom:'understand', type:'classify',
    question:'صنّف العادات حسب تأثيرها على الأسنان:',
    categories:['يُحافظ على الأسنان', 'يضرّ الأسنان'],
    items:[
      {text:'تنظيف الأسنان', correct_category:0},
      {text:'كثرة الحلوى', correct_category:1},
      {text:'شرب ماء بكثرة', correct_category:0},
      {text:'شرب مشروبات غازية', correct_category:1},
      {text:'زيارة طبيب الأسنان', correct_category:0},
    ],
    explanation:'يحافظ: تنظيف، ماء، طبيب. يضر: حلوى، غازية.',
    goldenRule:'تنظيف + ماء + طبيب = أسنان صحية.',
    paragraph:'صحة الأسنان — ص ١٨٥',
  },
  { id:'s4_679', unit:'u5', lesson:'u5l3', page:175, difficulty:'hard', bloom:'analyze', type:'multipleChoice',
    question:'لماذا تُعدّ الرياضة من أهم العادات الصحية؟',
    options:[{text:'لأنها تقوّي القلب والعضلات وتحسّن المزاج والمناعة',correct:true},{text:'لأنها تزيد الوزن',correct:false},{text:'لأنها تُضعف الجسم',correct:false},{text:'لأنها لا فائدة منها',correct:false}],
    explanation:'الرياضة تقوّي القلب والعضلات وتُحسّن المزاج وتزيد المناعة.',
    goldenRule:'رياضة = قلب + عضلات + مزاج + مناعة.',
    paragraph:'أهمية الرياضة — ص ١٧٥',
  },
  { id:'s4_680', unit:'u5', lesson:'u5l3', page:181, difficulty:'medium', bloom:'apply', type:'trueFalse',
    question:'تنظيم وقت النوم والاستيقاظ يساعد على شعور أفضل بالنشاط طوال اليوم.',
    correctAnswer:'true',
    explanation:'تنظيم وقت النوم والاستيقاظ يُحافظ على الساعة البيولوجية للجسم.',
    goldenRule:'وقت ثابت للنوم/الاستيقاظ = ساعة بيولوجية منتظمة.',
    paragraph:'تنظيم النوم — ص ١٨١',
  },
  { id:'s4_681', unit:'u5', lesson:'u5l3', page:185, difficulty:'easy', bloom:'remember', type:'multipleChoice',
    question:'من العادات الصحية للوقاية من الأمراض:',
    options:[{text:'النظافة والتغذية السليمة والرياضة',correct:true},{text:'السهر',correct:false},{text:'التدخين',correct:false},{text:'إهمال النظافة',correct:false}],
    explanation:'النظافة والتغذية السليمة والرياضة من أهم العادات الصحية الوقائية.',
    goldenRule:'نظافة + تغذية + رياضة = وقاية.',
    paragraph:'العادات الوقائية — ص ١٨٥',
  },
  { id:'s4_682', unit:'u5', lesson:'u5l3', page:183, difficulty:'hard', bloom:'evaluate', type:'trueFalse',
    question:'اتباع العادات الصحية منذ الصغر يُقلل خطر الأمراض في الكبر.',
    correctAnswer:'true',
    explanation:'العادات الصحية منذ الصغر تحمي الجسم وتُقلل الأمراض المزمنة في الكبر.',
    goldenRule:'عادات صحية مبكرة = أمراض أقل في الكبر.',
    paragraph:'العادات الصحية المبكرة — ص ١٨٣',
  },
  { id:'s4_683', unit:'u5', lesson:'u5l3', page:184, difficulty:'medium', bloom:'understand', type:'multipleChoice',
    question:'الجلوس الصحيح أمام الكمبيوتر يتطلب:',
    options:[{text:'ظهر مستقيم والشاشة بمستوى العين',correct:true},{text:'ظهر منحنٍ والشاشة قريبة',correct:false},{text:'الجلوس بلا مسند',correct:false},{text:'الجلوس في الظلام',correct:false}],
    explanation:'الظهر المستقيم والشاشة بمستوى العين يحميان الظهر والعينين.',
    goldenRule:'ظهر مستقيم + شاشة عين = جلسة صحية.',
    paragraph:'الجلوس الصحي — ص ١٨٤',
  },
  { id:'s4_684', unit:'u5', lesson:'u5l3', page:182, difficulty:'easy', bloom:'remember', type:'trueFalse',
    question:'الإكثار من شرب الماء من العادات الصحية المهمة.',
    correctAnswer:'true',
    explanation:'شرب الماء بكثرة يُحافظ على التوازن المائي ويُساعد جميع أجهزة الجسم.',
    goldenRule:'ماء كافٍ = جسم متوازن وصحي.',
    paragraph:'شرب الماء — ص ١٨٢',
  },
];