// لغتي - الصف الثالث الابتدائي - الوحدة الرابعة: وَسَائِلُ الِاتِّصَالَاتِ
// مَدْخَلُ الْوَحْدَة + درسان (وَسَائِلُ الِاتِّصَالِ قَدِيمًا + وَسَائِلُ الِاتِّصَالِ حَدِيثًا)

export const UNIT4_QUESTIONS = [
  // ─── مَدْخَلُ الْوَحْدَة الرابعة: وَسَائِلُ الِاتِّصَالَاتِ ─────────────
  {
    id:'u4introq1', unit:'unit4', lesson:'u4intro', page:104, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'عنوان الوحدة الرابعة في كتاب لغتي هو:',
    paragraph:'الوحدة الرابعة: وَسَائِلُ الِاتِّصَالَاتِ — ص ١٠٤.',
    options:[
      {text:'وَسَائِلُ الِاتِّصَالَاتِ',correct:true},
      {text:'أَخْلَاقُ الْمُسْلِمِ',correct:false},
      {text:'رُبُوعٌ مِنْ بِلَادِي',correct:false},
      {text:'التَّعَامُلُ مَعَ الْآخَرِينَ',correct:false},
    ],
    explanation:'عنوان الوحدة الرابعة: وَسَائِلُ الِاتِّصَالَاتِ.',
    goldenRule:'الوحدة الرابعة = وَسَائِلُ الِاتِّصَالَاتِ.',
    feedbackQuestion:{question:'ما عنوان الوحدة الرابعة؟',options:[{text:'وَسَائِلُ الِاتِّصَالَاتِ',correct:true},{text:'أَخْلَاقُ الْمُسْلِمِ',correct:false},{text:'رُبُوعٌ مِنْ بِلَادِي',correct:false},{text:'التَّعَامُلُ مَعَ الْآخَرِينَ',correct:false}]},
  },
  {
    id:'u4introq2', unit:'unit4', lesson:'u4intro', page:104, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'كم عدد دروس الوحدة الرابعة؟',
    paragraph:'الوحدة الرابعة تضم درسين: وسائل الاتصال قديماً + وسائل الاتصال حديثاً.',
    options:[
      {text:'درسان',correct:true},
      {text:'ثلاثة دروس',correct:false},
      {text:'أربعة دروس',correct:false},
      {text:'خمسة دروس',correct:false},
    ],
    explanation:'الوحدة الرابعة تضم درسين: وسائل الاتصال قديماً وحديثاً.',
    goldenRule:'وحدة وسائل الاتصالات = درسان (قديماً + حديثاً).',
    feedbackQuestion:{question:'كم درسًا في الوحدة الرابعة؟',options:[{text:'درسان',correct:true},{text:'ثلاثة',correct:false},{text:'أربعة',correct:false},{text:'خمسة',correct:false}]},
  },
  {
    id:'u4introq3', unit:'unit4', lesson:'u4intro', page:104, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'من دروس الوحدة الرابعة:',
    paragraph:'درسا الوحدة: وسائل الاتصال قديماً + وسائل الاتصال حديثاً.',
    options:[
      {text:'وسائل الاتصال قديماً وحديثاً',correct:true},
      {text:'الصدق والأمانة',correct:false},
      {text:'معالم بلادي',correct:false},
      {text:'آداب الحديث',correct:false},
    ],
    explanation:'درسا الوحدة الرابعة: وسائل الاتصال قديماً ووسائل الاتصال حديثاً.',
    goldenRule:'درسا الاتصالات = قديماً + حديثاً.',
    feedbackQuestion:{question:'ما درسا الوحدة الرابعة؟',options:[{text:'وسائل الاتصال قديماً وحديثاً',correct:true},{text:'الصدق والأمانة',correct:false},{text:'معالم بلادي',correct:false},{text:'آداب الحديث',correct:false}]},
  },
  {
    id:'u4introq4', unit:'unit4', lesson:'u4intro', page:104, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'الِاتِّصَال يعني:',
    paragraph:'الاتصال: نقل المعلومات والأخبار بين الناس. (ص١٠٤)',
    options:[
      {text:'نقل المعلومات والأخبار بين الناس',correct:true},
      {text:'اللعب',correct:false},
      {text:'الأكل',correct:false},
      {text:'النوم',correct:false},
    ],
    explanation:'الاتصال يعني نقل المعلومات والأخبار بين الناس.',
    goldenRule:'الاتصال = نقل + معلومات + أخبار + بين الناس.',
    feedbackQuestion:{question:'ماذا يعني الاتصال؟',options:[{text:'نقل المعلومات بين الناس',correct:true},{text:'اللعب',correct:false},{text:'الأكل',correct:false},{text:'النوم',correct:false}]},
  },
  {
    id:'u4introq5', unit:'unit4', lesson:'u4intro', page:105, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'وَسَائِلُ الِاتِّصَال تعني:',
    paragraph:'وسائل الاتصال: الأدوات التي نستعملها للتواصل. (ص١٠٥)',
    options:[
      {text:'الأدوات التي نستعملها للتواصل',correct:true},
      {text:'الأطعمة',correct:false},
      {text:'الملابس',correct:false},
      {text:'الألعاب',correct:false},
    ],
    explanation:'وسائل الاتصال: الأدوات التي نستعملها للتواصل ونقل المعلومات.',
    goldenRule:'وسائل الاتصال = أدوات + تواصل + نقل + معلومات.',
    feedbackQuestion:{question:'ما وسائل الاتصال؟',options:[{text:'أدوات للتواصل',correct:true},{text:'أطعمة',correct:false},{text:'ملابس',correct:false},{text:'ألعاب',correct:false}]},
  },
  {
    id:'u4introq6', unit:'unit4', lesson:'u4intro', page:105, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'وسائل الاتصال نوعان:',
    paragraph:'وسائل الاتصال: قديمة (الرسائل، الحمام) + حديثة (الهاتف، الإنترنت). (ص١٠٥)',
    options:[
      {text:'قديمة وحديثة',correct:true},
      {text:'قديمة فقط',correct:false},
      {text:'حديثة فقط',correct:false},
      {text:'لا شيء',correct:false},
    ],
    explanation:'وسائل الاتصال نوعان: قديمة (كالرسائل والحمام الزاجل) وحديثة (كالهاتف والإنترنت).',
    goldenRule:'وسائل الاتصال = قديمة + حديثة.',
    feedbackQuestion:{question:'ما نوعا وسائل الاتصال؟',options:[{text:'قديمة وحديثة',correct:true},{text:'قديمة فقط',correct:false},{text:'حديثة فقط',correct:false},{text:'لا شيء',correct:false}]},
  },
  {
    id:'u4introq7', unit:'unit4', lesson:'u4intro', page:104, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'وسائل الاتصال تساعد على نقل الأخبار بين الناس.',
    paragraph:'وسائل الاتصال تسهل نقل المعلومات والأخبار. (ص١٠٤)',
    correctAnswer:true,
    explanation:'نعم، وسائل الاتصال تساعد على نقل الأخبار بين الناس بسرعة.',
    goldenRule:'وسائل الاتصال = نقل + سرعة + أخبار + تواصل.',
    feedbackQuestion:{question:'هل وسائل الاتصال تساعد على نقل الأخبار؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'لا أعرف',correct:false},{text:'بعض الأحيان',correct:false}]},
  },
  {
    id:'u4introq8', unit:'unit4', lesson:'u4intro', page:105, type:'multipleChoice',
    bloom:'apply', difficulty:'medium',
    question:'إذا أردت إرسال رسالة لقريب بعيد بسرعة، فمن وسائل الاتصال:',
    paragraph:'وسائل الاتصال الحديثة سريعة كالهاتف والإنترنت. (ص١٠٥)',
    options:[
      {text:'الهاتف أو الإنترنت',correct:true},
      {text:'الحمام الزاجل',correct:false},
      {text:'الرسالة الورقية',correct:false},
      {text:'إشارة الدخان',correct:false},
    ],
    explanation:'لإرسال رسالة سريعة لبعيد، نستعمل الهاتف أو الإنترنت.',
    goldenRule:'الاتصال السريع = هاتف + إنترنت + رسالة فورية + أدب.',
    feedbackQuestion:{question:'كيف ترسل رسالة سريعة لبعيد؟',options:[{text:'الهاتف أو الإنترنت',correct:true},{text:'الحمام',correct:false},{text:'رسالة ورقية',correct:false},{text:'دخان',correct:false}]},
  },
  {
    id:'u4introq9', unit:'unit4', lesson:'u4intro', page:104, type:'fillBlank',
    bloom:'apply', difficulty:'easy',
    question:'أكمل: عنوان الوحدة الرابعة هو وَسَائِلُ ___',
    paragraph:'الوحدة الرابعة: وَسَائِلُ الِاتِّصَالَاتِ.',
    blanks:['الِاتِّصَالَاتِ'],
    wordBank:['الِاتِّصَالَاتِ','الْأَخْلَاق','الْبِلَاد','النَّاس'],
    explanation:'عنوان الوحدة الرابعة: وَسَائِلُ الِاتِّصَالَاتِ.',
    goldenRule:'عنوان الوحدة الرابعة = وَسَائِلُ الِاتِّصَالَاتِ.',
  },
  {
    id:'u4introq10', unit:'unit4', lesson:'u4intro', page:105, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف: وسيلة اتصال قديمة / حديثة.',
    paragraph:'قديمة: رسائل + حمام + إشارات. حديثة: هاتف + إنترنت + بريد إلكتروني. (ص١٠٥)',
    categories:['قديمة 📜','حديثة 📱'],
    items:[
      {text:'الحمام الزاجل',correct_category:0},
      {text:'الهاتف',correct_category:1},
      {text:'الرسالة الورقية',correct_category:0},
      {text:'الإنترنت',correct_category:1},
      {text:'إشارة الدخان',correct_category:0},
      {text:'البريد الإلكتروني',correct_category:1},
    ],
    explanation:'قديمة: حمام + رسائل + إشارات. حديثة: هاتف + إنترنت + بريد.',
    goldenRule:'قديمة: حمام + رسائل. حديثة: هاتف + إنترنت.',
  },
  {
    id:'u4introq11', unit:'unit4', lesson:'u4intro', page:105, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'لماذا تطورت وسائل الاتصال؟',
    paragraph:'تطورت وسائل الاتصال لتسهيل التواصل وتسريع نقل الأخبار. (ص١٠٥)',
    options:[
      {text:'لتسهيل التواصل وتسريع نقل الأخبار',correct:true},
      {text:'عادة',correct:false},
      {text:'لا سبب',correct:false},
      {text:'مكروه',correct:false},
    ],
    explanation:'تطورت وسائل الاتصال لتسهيل التواصل وتسريع نقل الأخبار بين الناس.',
    goldenRule:'تطور الاتصال = تسهيل + سرعة + تواصل + أجر.',
    feedbackQuestion:{question:'لماذا تطورت وسائل الاتصال؟',options:[{text:'لتسهيل التواصل',correct:true},{text:'عادة',correct:false},{text:'لا سبب',correct:false},{text:'مكروه',correct:false}]},
  },
  {
    id:'u4introq12', unit:'unit4', lesson:'u4intro', page:104, type:'matching',
    bloom:'understand', difficulty:'medium',
    question:'صِل الكلمة بمعناها.',
    paragraph:'الاتصال = نقل. الوسيلة = أداة. قديمة = ماضٍ. حديثة = الآن. (ص١٠٤-١٠٥)',
    pairs:[
      {left:'الاتصال',right:'نقل المعلومات'},
      {left:'الوسيلة',right:'الأداة'},
      {left:'قديمة',right:'الماضي'},
      {left:'حديثة',right:'الآن'},
    ],
    explanation:'الاتصال=نقل، الوسيلة=أداة، قديمة=ماضٍ، حديثة=الآن.',
    goldenRule:'الاتصال=نقل، الوسيلة=أداة، قديمة=ماضٍ، حديثة=الآن.',
  },
  {
    id:'u4introq13', unit:'unit4', lesson:'u4intro', page:105, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'الهاتف من وسائل الاتصال الحديثة.',
    paragraph:'الهاتف وسيلة اتصال حديثة سريعة. (ص١٠٥)',
    correctAnswer:true,
    explanation:'نعم، الهاتف من وسائل الاتصال الحديثة.',
    goldenRule:'الهاتف = حديثة + سريعة + اتصال + تواصل.',
    feedbackQuestion:{question:'هل الهاتف من الوسائل الحديثة؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'لا أعرف',correct:false},{text:'بعض الأحيان',correct:false}]},
  },
  {
    id:'u4introq14', unit:'unit4', lesson:'u4intro', page:105, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'من فوائد وسائل الاتصال:',
    paragraph:'فوائد وسائل الاتصال: نقل الأخبار + التواصل + التعلم + التعاون. (ص١٠٥)',
    options:[
      {text:'نقل الأخبار والتواصل والتعلم',correct:true},
      {text:'العزلة',correct:false},
      {text:'الانقطاع',correct:false},
      {text:'لا شيء',correct:false},
    ],
    explanation:'من فوائد وسائل الاتصال: نقل الأخبار والتواصل والتعلم والتعاون.',
    goldenRule:'فوائد الاتصال = أخبار + تواصل + تعلم + تعاون.',
    feedbackQuestion:{question:'ما فوائد وسائل الاتصال؟',options:[{text:'نقل الأخبار والتواصل',correct:true},{text:'العزلة',correct:false},{text:'الانقطاع',correct:false},{text:'لا شيء',correct:false}]},
  },
  {
    id:'u4introq15', unit:'unit4', lesson:'u4intro', page:105, type:'multipleChoice',
    bloom:'create', difficulty:'hard',
    question:'ركّب جملة فيها: اتصال + وسيلة + قديمة + حديثة.',
    paragraph:'وسائل الاتصال قديمة وحديثة تنقل الأخبار. (ص١٠٤-١٠٥)',
    options:[
      {text:'وسائل الاتصال قديمة وحديثة تنقل الأخبار',correct:true},
      {text:'الاتصال لا فائدة',correct:false},
      {text:'الوسيلة لا تنقل',correct:false},
      {text:'لا شيء',correct:false},
    ],
    explanation:'الجملة: وسائل الاتصال قديمة وحديثة تنقل الأخبار.',
    goldenRule:'وسائل الاتصال = قديمة + حديثة + نقل أخبار.',
  },

  // ─── الدرس 1: وَسَائِلُ الِاتِّصَالِ قَدِيمًا (ص ١٠٦–١١١) ─────────────────────
  {
    id:'u4l1q1', unit:'unit4', lesson:'u4l1', page:106, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'من وسائل الاتصال قديماً:',
    paragraph:'وسائل الاتصال قديماً: الرسائل، الحمام الزاجل، إشارات الدخان، إشعال النار. (ص١٠٦)',
    options:[
      {text:'الرسائل والحمام الزاجل وإشارات الدخان',correct:true},
      {text:'الهاتف',correct:false},
      {text:'الإنترنت',correct:false},
      {text:'البريد الإلكتروني',correct:false},
    ],
    explanation:'من وسائل الاتصال قديماً: الرسائل والحمام الزاجل وإشارات الدخان وإشعال النار.',
    goldenRule:'وسائل قديمة = رسائل + حمام + دخان + نار.',
    feedbackQuestion:{question:'ما وسائل الاتصال قديماً؟',options:[{text:'الرسائل والحمام والدخان',correct:true},{text:'الهاتف',correct:false},{text:'الإنترنت',correct:false},{text:'البريد',correct:false}]},
  },
  {
    id:'u4l1q2', unit:'unit4', lesson:'u4l1', page:106, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'الحمام الزاجل كان يُستعمل لـ:',
    paragraph:'الحمام الزاجل: طير كان يُربى ويُرسل لحمل الرسائل بين المدن. (ص١٠٦)',
    options:[
      {text:'حمل الرسائل بين المدن',correct:true},
      {text:'الأكل',correct:false},
      {text:'اللعب',correct:false},
      {text:'الصيد',correct:false},
    ],
    explanation:'الحمام الزاجل كان يُستعمل لحمل الرسائل بين المدن والبلدان.',
    goldenRule:'الحمام الزاجل = رسائل + نقل + بين المدن + سريع.',
    feedbackQuestion:{question:'لماذا كان يُستعمل الحمام الزاجل؟',options:[{text:'حمل الرسائل',correct:true},{text:'الأكل',correct:false},{text:'اللعب',correct:false},{text:'الصيد',correct:false}]},
  },
  {
    id:'u4l1q3', unit:'unit4', lesson:'u4l1', page:107, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'إشارات الدخان كانت تُستعمل لـ:',
    paragraph:'إشارة الدخان: يُشعل الناس النار في أعلى الجبل لإيصال خبر. (ص١٠٧)',
    options:[
      {text:'إيصال الأخبار بسرعة لمسافات بعيدة',correct:true},
      {text:'الطبخ',correct:false},
      {text:'التدفئة',correct:false},
      {text:'الإضاءة',correct:false},
    ],
    explanation:'إشارات الدخان كانت تُستعمل لإيصال الأخبار بسرعة لمسافات بعيدة.',
    goldenRule:'إشارة الدخان = نار + جبل + خبر + سرعة.',
    feedbackQuestion:{question:'لماذا كانت تُستعمل إشارات الدخان؟',options:[{text:'إيصال الأخبار',correct:true},{text:'الطبخ',correct:false},{text:'التدفئة',correct:false},{text:'الإضاءة',correct:false}]},
  },
  {
    id:'u4l1q4', unit:'unit4', lesson:'u4l1', page:107, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'الرسائل الورقية كانت تُحمل على يد الرسل والخدم.',
    paragraph:'الرسائل تُكتب وتُحمل يدوياً للوصول للمرسل إليه. (ص١٠٧)',
    correctAnswer:true,
    explanation:'نعم، الرسائل الورقية كانت تُحمل على يد الرسل والخدم.',
    goldenRule:'الرسالة الورقية = كتابة + حمل يدوي + توصيل + أمانة.',
    feedbackQuestion:{question:'هل الرسائل كانت تُحمل يدوياً؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'لا أعرف',correct:false},{text:'بعض الأحيان',correct:false}]},
  },
  {
    id:'u4l1q5', unit:'unit4', lesson:'u4l1', page:108, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'الرسالة الورقية تحتاج إلى:',
    paragraph:'الرسالة: ورق + قلم + حامل + مُرسَل إليه. (ص١٠٨)',
    options:[
      {text:'ورق وقلم وحامل ومُرسَل إليه',correct:true},
      {text:'هاتف',correct:false},
      {text:'إنترنت',correct:false},
      {text:'لا شيء',correct:false},
    ],
    explanation:'الرسالة الورقية تحتاج إلى ورق وقلم وحامل ومُرسَل إليه.',
    goldenRule:'الرسالة = ورق + قلم + حامل + مُرسَل إليه.',
    feedbackQuestion:{question:'ماذا تحتاج الرسالة الورقية؟',options:[{text:'ورق وقلم وحامل',correct:true},{text:'هاتف',correct:false},{text:'إنترنت',correct:false},{text:'لا شيء',correct:false}]},
  },
  {
    id:'u4l1q6', unit:'unit4', lesson:'u4l1', page:108, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'من عيوب وسائل الاتصال القديمة:',
    paragraph:'عيوب الوسائل القديمة: بطء + جهد + صعوبة + مسافة. (ص١٠٨)',
    options:[
      {text:'البطء والجهد وصعوبة المسافة',correct:true},
      {text:'السرعة',correct:false},
      {text:'السهولة',correct:false},
      {text:'لا شيء',correct:false},
    ],
    explanation:'من عيوب الوسائل القديمة: البطء والجهد وصعوبة المسافة.',
    goldenRule:'عيوب الوسائل القديمة = بطء + جهد + صعوبة + مسافة.',
    feedbackQuestion:{question:'ما عيوب وسائل الاتصال القديمة؟',options:[{text:'البطء والجهد',correct:true},{text:'السرعة',correct:false},{text:'السهولة',correct:false},{text:'لا شيء',correct:false}]},
  },
  {
    id:'u4l1q7', unit:'unit4', lesson:'u4l1', page:109, type:'multipleChoice',
    bloom:'apply', difficulty:'medium',
    question:'إذا أراد ملك قديم إرسال خبر عاجل لمدينة بعيدة، فإنه يستعمل:',
    paragraph:'الملوك استعملوا الحمام الزاجل وإشارات الدخان للإرسال السريع. (ص١٠٦-١٠٩)',
    options:[
      {text:'الحمام الزاجل أو إشارات الدخان',correct:true},
      {text:'الهاتف',correct:false},
      {text:'الإنترنت',correct:false},
      {text:'البريد الإلكتروني',correct:false},
    ],
    explanation:'إذا أراد ملك إرسال خبر عاجل قديماً، استعمل الحمام الزاجل أو إشارات الدخان.',
    goldenRule:'الإرسال السريع قديماً = حمام + دخان + خبر + عاجل.',
    feedbackQuestion:{question:'كيف يرسل الملك خبراً عاجلاً قديماً؟',options:[{text:'الحمام أو الدخان',correct:true},{text:'الهاتف',correct:false},{text:'الإنترنت',correct:false},{text:'البريد',correct:false}]},
  },
  {
    id:'u4l1q8', unit:'unit4', lesson:'u4l1', page:109, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'الحمام الزاجل يعرف طريق العودة إلى مكانه.',
    paragraph:'الحمام الزاجل يمتلك قدرة على معرفة طريق العودة. (ص١٠٩)',
    correctAnswer:true,
    explanation:'نعم، الحمام الزاجل يعرف طريق العودة إلى مكانه الأصلي.',
    goldenRule:'الحمام الزاجل = يعرف الطريق + عودة + رسالة + تواصل.',
    feedbackQuestion:{question:'هل الحمام الزاجل يعرف طريق العودة؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'لا أعرف',correct:false},{text:'بعض الأحيان',correct:false}]},
  },
  {
    id:'u4l1q9', unit:'unit4', lesson:'u4l1', page:110, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'من وسائل الاتصال قديماً في الصحراء:',
    paragraph:'في الصحراء استعمل الناس إشعال النار وإشارات الدخان. (ص١١٠)',
    options:[
      {text:'إشعال النار وإشارات الدخان',correct:true},
      {text:'الهاتف',correct:false},
      {text:'الإنترنت',correct:false},
      {text:'البريد',correct:false},
    ],
    explanation:'في الصحراء استعمل الناس إشعال النار وإشارات الدخان للتواصل.',
    goldenRule:'الصحراء = نار + دخان + إشارة + خبر.',
    feedbackQuestion:{question:'ما وسائل الاتصال في الصحراء؟',options:[{text:'النار والدخان',correct:true},{text:'الهاتف',correct:false},{text:'الإنترنت',correct:false},{text:'البريد',correct:false}]},
  },
  {
    id:'u4l1q10', unit:'unit4', lesson:'u4l1', page:110, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'الرسالة الورقية تصل إلى المُرسَل إليه:',
    paragraph:'الرسالة الورقية تستغرق وقتاً طويلاً للوصول. (ص١١٠)',
    options:[
      {text:'بعد وقت طويل',correct:true},
      {text:'فوراً',correct:false},
      {text:'لا تصل',correct:false},
      {text:'لا أعرف',correct:false},
    ],
    explanation:'الرسالة الورقية تستغرق وقتاً طويلاً للوصول.',
    goldenRule:'الرسالة الورقية = وقت طويل + جهد + مسافة + بطء.',
    feedbackQuestion:{question:'متى تصل الرسالة الورقية؟',options:[{text:'بعد وقت طويل',correct:true},{text:'فوراً',correct:false},{text:'لا تصل',correct:false},{text:'لا أعرف',correct:false}]},
  },
  {
    id:'u4l1q11', unit:'unit4', lesson:'u4l1', page:111, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'لماذا استعمل الناس قديماً الحمام الزاجل؟',
    paragraph:'الحمام الزاجل أسرع من المشي لحمل الرسائل. (ص١٠٦-١١١)',
    options:[
      {text:'لأنه أسرع في نقل الرسائل',correct:true},
      {text:'عادة',correct:false},
      {text:'لا سبب',correct:false},
      {text:'مكروه',correct:false},
    ],
    explanation:'استعمل الناس الحمام الزاجل لأنه أسرع في نقل الرسائل بين المدن.',
    goldenRule:'الحمام = أسرع + نقل + رسائل + بين المدن.',
    feedbackQuestion:{question:'لماذا استعملوا الحمام الزاجل؟',options:[{text:'لأنه أسرع',correct:true},{text:'عادة',correct:false},{text:'لا سبب',correct:false},{text:'مكروه',correct:false}]},
  },
  {
    id:'u4l1q12', unit:'unit4', lesson:'u4l1', page:106, type:'fillBlank',
    bloom:'apply', difficulty:'easy',
    question:'أكمل: من وسائل الاتصال قديماً: الرسائل و___ الزاجل.',
    paragraph:'الحمام الزاجل من وسائل الاتصال القديمة. (ص١٠٦)',
    blanks:['الْحَمَامِ'],
    wordBank:['الْحَمَامِ','الْهَاتِف','الإِنْتَرْنَت','الْبَرِيد'],
    explanation:'من وسائل الاتصال قديماً: الرسائل والحمام الزاجل.',
    goldenRule:'وسائل قديمة = رسائل + حمام.',
  },
  {
    id:'u4l1q13', unit:'unit4', lesson:'u4l1', page:111, type:'ordering',
    bloom:'apply', difficulty:'medium',
    question:'رتّب خطوات إرسال رسالة ورقية قديماً.',
    paragraph:'الرسالة: كتابة ← طي ← تسليم للحامل ← وصول للمُرسَل إليه. (ص١٠٨-١١١)',
    items:['كتابة الرسالة','طي الرسالة','تسليمها للحامل','وصولها للمُرسَل إليه'],
    correctOrder:[0,1,2,3],
    explanation:'الرسالة: كتابة ← طي ← تسليم ← وصول.',
    goldenRule:'الرسالة = كتابة ← طي ← تسليم ← وصول.',
  },
  {
    id:'u4l1q14', unit:'unit4', lesson:'u4l1', page:110, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف: وسيلة اتصال قديمة / حديثة.',
    paragraph:'قديمة: حمام + دخان + رسالة. حديثة: هاتف + إنترنت + بريد. (ص١٠٦-١١٠)',
    categories:['قديمة 📜','حديثة 📱'],
    items:[
      {text:'الحمام الزاجل',correct_category:0},
      {text:'الهاتف',correct_category:1},
      {text:'إشارة الدخان',correct_category:0},
      {text:'الإنترنت',correct_category:1},
      {text:'الرسالة الورقية',correct_category:0},
      {text:'البريد الإلكتروني',correct_category:1},
    ],
    explanation:'قديمة: حمام + دخان + رسالة. حديثة: هاتف + إنترنت + بريد.',
    goldenRule:'قديمة: حمام + دخان + رسالة. حديثة: هاتف + إنترنت + بريد.',
  },
  {
    id:'u4l1q15', unit:'unit4', lesson:'u4l1', page:108, type:'matching',
    bloom:'understand', difficulty:'medium',
    question:'صِل الوسيلة بفائدتها قديماً.',
    paragraph:'الحمام = نقل رسائل. الدخان = إشارة. النار = إنذار. الرسالة = خبر مكتوب. (ص١٠٦-١١٠)',
    pairs:[
      {left:'الحمام الزاجل',right:'نقل الرسائل'},
      {left:'إشارة الدخان',right:'إيصال خبر'},
      {left:'إشعال النار',right:'إنذار'},
      {left:'الرسالة الورقية',right:'خبر مكتوب'},
    ],
    explanation:'الحمام=نقل، الدخان=خبر، النار=إنذار، الرسالة=مكتوب.',
    goldenRule:'الحمام=نقل، الدخان=خبر، النار=إنذار، الرسالة=مكتوب.',
  },
  {
    id:'u4l1q16', unit:'unit4', lesson:'u4l1', page:106, type:'trueFalse',
    bloom:'remember', difficulty:'easy',
    question:'الحمام الزاجل من وسائل الاتصال القديمة.',
    paragraph:'الحمام الزاجل من وسائل الاتصال القديمة. (ص١٠٦)',
    correctAnswer:true,
    explanation:'نعم، الحمام الزاجل من وسائل الاتصال القديمة.',
    goldenRule:'الحمام الزاجل = قديمة + رسائل + نقل + تواصل.',
    feedbackQuestion:{question:'هل الحمام الزاجل من الوسائل القديمة؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'لا أعرف',correct:false},{text:'بعض الأحيان',correct:false}]},
  },
  {
    id:'u4l1q17', unit:'unit4', lesson:'u4l1', page:109, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'الرسالة الورقية تحتاج إلى حامل يُوصِلها ويسمى:',
    paragraph:'الرسول أو الساعي ينقل الرسالة. (ص١٠٩)',
    options:[
      {text:'الرسول أو الساعي',correct:true},
      {text:'الحمام',correct:false},
      {text:'الهاتف',correct:false},
      {text:'لا أحد',correct:false},
    ],
    explanation:'الرسالة الورقية تحتاج إلى رسول أو ساعي ينقلها.',
    goldenRule:'الرسالة = ورق + رسول + نقل + توصيل.',
    feedbackQuestion:{question:'من ينقل الرسالة الورقية؟',options:[{text:'الرسول أو الساعي',correct:true},{text:'الحمام',correct:false},{text:'الهاتف',correct:false},{text:'لا أحد',correct:false}]},
  },
  {
    id:'u4l1q18', unit:'unit4', lesson:'u4l1', page:111, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'وسائل الاتصال القديمة كانت:',
    paragraph:'الوسائل القديمة بطيئة وتحتاج جهداً ووقتاً. (ص١١١)',
    options:[
      {text:'بطيئة وتحتاج جهداً',correct:true},
      {text:'سريعة',correct:false},
      {text:'سهلة',correct:false},
      {text:'فورية',correct:false},
    ],
    explanation:'وسائل الاتصال القديمة كانت بطيئة وتحتاج جهداً ووقتاً.',
    goldenRule:'الوسائل القديمة = بطء + جهد + وقت + صعوبة.',
    feedbackQuestion:{question:'كيف كانت الوسائل القديمة؟',options:[{text:'بطيئة وتحتاج جهداً',correct:true},{text:'سريعة',correct:false},{text:'سهلة',correct:false},{text:'فورية',correct:false}]},
  },
  {
    id:'u4l1q19', unit:'unit4', lesson:'u4l1', page:107, type:'trueFalse',
    bloom:'understand', difficulty:'medium',
    question:'إشعال النار كان وسيلة لإنذار الناس بخبر.',
    paragraph:'النار وسيلة إنذار وإيصال خبر. (ص١٠٧)',
    correctAnswer:true,
    explanation:'نعم، إشعال النار كان وسيلة لإنذار الناس بخبر.',
    goldenRule:'النار = إنذار + خبر + إشارة + تواصل.',
    feedbackQuestion:{question:'هل النار كانت وسيلة إنذار؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'لا أعرف',correct:false},{text:'بعض الأحيان',correct:false}]},
  },
  {
    id:'u4l1q20', unit:'unit4', lesson:'u4l1', page:111, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'ماذا تعلمنا من وسائل الاتصال القديمة؟',
    paragraph:'وسائل الاتصال القديمة علّمتنا الإبداع والصبر. (ص١٠٦-١١١)',
    options:[
      {text:'الإبداع والصبر في التواصل',correct:true},
      {text:'العزلة',correct:false},
      {text:'الكذب',correct:false},
      {text:'لا شيء',correct:false},
    ],
    explanation:'تعلمنا من وسائل الاتصال القديمة الإبداع والصبر في التواصل.',
    goldenRule:'الوسائل القديمة = إبداع + صبر + تواصل + أجر.',
    feedbackQuestion:{question:'ماذا تعلمنا من الوسائل القديمة؟',options:[{text:'الإبداع والصبر',correct:true},{text:'العزلة',correct:false},{text:'الكذب',correct:false},{text:'لا شيء',correct:false}]},
  },
  {
    id:'u4l1q21', unit:'unit4', lesson:'u4l1', page:110, type:'fillBlank',
    bloom:'apply', difficulty:'easy',
    question:'أكمل: كانت الرسائل تُحمل على يد ___ أو الساعي.',
    paragraph:'الرسول أو الساعي ينقل الرسالة. (ص١٠٩)',
    blanks:['الرَّسُول'],
    wordBank:['الرَّسُول','الْهَاتِف','الْحَمَام','الإِنْتَرْنَت'],
    explanation:'كانت الرسائل تُحمل على يد الرسول أو الساعي.',
    goldenRule:'الرسالة = رسول + ساعي + نقل + توصيل.',
  },
  {
    id:'u4l1q22', unit:'unit4', lesson:'u4l1', page:111, type:'multipleChoice',
    bloom:'create', difficulty:'hard',
    question:'ركّب جملة فيها: حمام + رسالة + نقل + قديماً.',
    paragraph:'الحمام الزاجل كان ينقل الرسائل قديماً. (ص١٠٦-١١١)',
    options:[
      {text:'الحمام الزاجل كان ينقل الرسائل قديماً',correct:true},
      {text:'الحمام للأكل',correct:false},
      {text:'الرسالة لا تصل',correct:false},
      {text:'لا شيء',correct:false},
    ],
    explanation:'الجملة: الحمام الزاجل كان ينقل الرسائل قديماً.',
    goldenRule:'الحمام الزاجل = نقل + رسائل + قديماً.',
  },
  {
    id:'u4l1q23', unit:'unit4', lesson:'u4l1', page:108, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'الرسالة الورقية تُكتب بـ:',
    paragraph:'الرسالة الورقية تُكتب بالقلم على الورق. (ص١٠٨)',
    options:[
      {text:'القلم على الورق',correct:true},
      {text:'الهاتف',correct:false},
      {text:'الكمبيوتر',correct:false},
      {text:'الإنترنت',correct:false},
    ],
    explanation:'الرسالة الورقية تُكتب بالقلم على الورق.',
    goldenRule:'الرسالة = قلم + ورق + كتابة + توصيل.',
    feedbackQuestion:{question:'بماذا تُكتب الرسالة الورقية؟',options:[{text:'القلم على الورق',correct:true},{text:'الهاتف',correct:false},{text:'الكمبيوتر',correct:false},{text:'الإنترنت',correct:false}]},
  },
  {
    id:'u4l1q24', unit:'unit4', lesson:'u4l1', page:106, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'الحمام الزاجل نوع من:',
    paragraph:'الحمام الزاجل طير يربى لحمل الرسائل. (ص١٠٦)',
    options:[
      {text:'الطيور',correct:true},
      {text:'الأسماك',correct:false},
      {text:'الحيوانات المفترسة',correct:false},
      {text:'الحشرات',correct:false},
    ],
    explanation:'الحمام الزاجل نوع من الطيور.',
    goldenRule:'الحمام الزاجل = طير + رسائل + نقل + تواصل.',
    feedbackQuestion:{question:'ما نوع الحمام الزاجل؟',options:[{text:'طيور',correct:true},{text:'أسماك',correct:false},{text:'مفترس',correct:false},{text:'حشرات',correct:false}]},
  },
  {
    id:'u4l1q25', unit:'unit4', lesson:'u4l1', page:111, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'ما الفرق بين وسائل الاتصال القديمة والحديثة؟',
    paragraph:'القديمة بطيئة والحديثة سريعة. (ص١٠٦-١١١)',
    options:[
      {text:'الحديثة أسرع وأسهل من القديمة',correct:true},
      {text:'القديمة أسرع',correct:false},
      {text:'لا فرق',correct:false},
      {text:'الحديثة أبطأ',correct:false},
    ],
    explanation:'الحديثة أسرع وأسهل من القديمة.',
    goldenRule:'الحديثة = سرعة + سهولة. القديمة = بطء + جهد.',
    feedbackQuestion:{question:'ما الفرق بين القديمة والحديثة؟',options:[{text:'الحديثة أسرع',correct:true},{text:'القديمة أسرع',correct:false},{text:'لا فرق',correct:false},{text:'الحديثة أبطأ',correct:false}]},
  },
  {
    id:'u4l1q26', unit:'unit4', lesson:'u4l1', page:107, type:'trueFalse',
    bloom:'understand', difficulty:'medium',
    question:'إشارات الدخان وسيلة قديمة للتواصل بين القبائل.',
    paragraph:'إشارات الدخان للتواصل بين القبائل. (ص١٠٧)',
    correctAnswer:true,
    explanation:'نعم، إشارات الدخان وسيلة قديمة للتواصل بين القبائل.',
    goldenRule:'الدخان = قبائل + تواصل + إشارة + خبر.',
    feedbackQuestion:{question:'هل الدخان للتواصل بين القبائل؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'لا أعرف',correct:false},{text:'بعض الأحيان',correct:false}]},
  },
  {
    id:'u4l1q27', unit:'unit4', lesson:'u4l1', page:109, type:'multipleChoice',
    bloom:'apply', difficulty:'medium',
    question:'إذا أردت إرسال خبر سريع في زمن قديم، فالأفضل:',
    paragraph:'الحمام الزاجل أو إشارات الدخان للإرسال السريع. (ص١٠٦-١٠٩)',
    options:[
      {text:'الحمام الزاجل أو الدخان',correct:true},
      {text:'الرسالة الورقية',correct:false},
      {text:'المشي',correct:false},
      {text:'الانتظار',correct:false},
    ],
    explanation:'لإرسال خبر سريع قديماً، الأفضل الحمام الزاجل أو إشارات الدخان.',
    goldenRule:'الإرسال السريع قديماً = حمام + دخان + خبر + عاجل.',
    feedbackQuestion:{question:'كيف ترسل خبراً سريعاً قديماً؟',options:[{text:'الحمام أو الدخان',correct:true},{text:'الرسالة',correct:false},{text:'المشي',correct:false},{text:'الانتظار',correct:false}]},
  },
  {
    id:'u4l1q28', unit:'unit4', lesson:'u4l1', page:110, type:'fillBlank',
    bloom:'apply', difficulty:'easy',
    question:'أكمل: إشارة ___ كانت وسيلة اتصال قديمة.',
    paragraph:'إشارة الدخان وسيلة اتصال قديمة. (ص١١٠)',
    blanks:['الدُّخَان'],
    wordBank:['الدُّخَان','الْهَاتِف','الإِنْتَرْنَت','الْبَرِيد'],
    explanation:'إشارة الدخان كانت وسيلة اتصال قديمة.',
    goldenRule:'الدخان = إشارة + اتصال + قديمة + خبر.',
  },
  {
    id:'u4l1q29', unit:'unit4', lesson:'u4l1', page:111, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'لماذا احتاج الناس قديماً لوسائل اتصال؟',
    paragraph:'احتاجوا وسائل الاتصال لنقل الأخبار والتواصل. (ص١٠٦-١١١)',
    options:[
      {text:'لنقل الأخبار والتواصل بين الناس',correct:true},
      {text:'عادة',correct:false},
      {text:'لا سبب',correct:false},
      {text:'مكروه',correct:false},
    ],
    explanation:'احتاج الناس قديماً وسائل الاتصال لنقل الأخبار والتواصل بين الناس.',
    goldenRule:'الاتصال القديم = نقل أخبار + تواصل + إبداع + حاجة.',
    feedbackQuestion:{question:'لماذا احتاجوا وسائل الاتصال؟',options:[{text:'لنقل الأخبار',correct:true},{text:'عادة',correct:false},{text:'لا سبب',correct:false},{text:'مكروه',correct:false}]},
  },
  {
    id:'u4l1q30', unit:'unit4', lesson:'u4l1', page:111, type:'multipleChoice',
    bloom:'create', difficulty:'hard',
    question:'اكتب جملة فيها: رسالة + حمام + دخان + قديماً.',
    paragraph:'قديماً: الرسالة والحمام والدخان وسائل اتصال. (ص١٠٦-١١١)',
    options:[
      {text:'قديماً: الرسالة والحمام والدخان وسائل اتصال',correct:true},
      {text:'الاتصال لا فائدة',correct:false},
      {text:'لا وسائل',correct:false},
      {text:'لا شيء',correct:false},
    ],
    explanation:'الجملة: قديماً: الرسالة والحمام والدخان وسائل اتصال.',
    goldenRule:'قديماً = رسالة + حمام + دخان + اتصال.',
  },

  // ─── الدرس 2: وَسَائِلُ الِاتِّصَالِ حَدِيثًا (ص ١١٢–١١٨) ─────────────────────
  {
    id:'u4l2q1', unit:'unit4', lesson:'u4l2', page:112, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'من وسائل الاتصال حديثاً:',
    paragraph:'وسائل الاتصال الحديثة: الهاتف، الإنترنت، البريد الإلكتروني، الرسائل النصية. (ص١١٢)',
    options:[
      {text:'الهاتف والإنترنت والبريد الإلكتروني',correct:true},
      {text:'الحمام الزاجل',correct:false},
      {text:'إشارات الدخان',correct:false},
      {text:'إشعال النار',correct:false},
    ],
    explanation:'من وسائل الاتصال الحديثة: الهاتف والإنترنت والبريد الإلكتروني.',
    goldenRule:'وسائل حديثة = هاتف + إنترنت + بريد + رسائل.',
    feedbackQuestion:{question:'ما وسائل الاتصال الحديثة؟',options:[{text:'الهاتف والإنترنت',correct:true},{text:'الحمام',correct:false},{text:'الدخان',correct:false},{text:'النار',correct:false}]},
  },
  {
    id:'u4l2q2', unit:'unit4', lesson:'u4l2', page:112, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'الهاتف وسيلة اتصال:',
    paragraph:'الهاتف وسيلة اتصال حديثة سريعة. (ص١١٢)',
    options:[
      {text:'حديثة سريعة',correct:true},
      {text:'قديمة بطيئة',correct:false},
      {text:'لا تصل',correct:false},
      {text:'مكروهة',correct:false},
    ],
    explanation:'الهاتف وسيلة اتصال حديثة وسريعة.',
    goldenRule:'الهاتف = حديثة + سريعة + صوت + تواصل.',
    feedbackQuestion:{question:'ما نوع الهاتف كوسيلة اتصال؟',options:[{text:'حديثة سريعة',correct:true},{text:'قديمة',correct:false},{text:'لا تصل',correct:false},{text:'مكروهة',correct:false}]},
  },
  {
    id:'u4l2q3', unit:'unit4', lesson:'u4l2', page:113, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'الإنترنت يُستعمل لـ:',
    paragraph:'الإنترنت: شبكة عالمية لنقل المعلومات والصور والأخبار. (ص١١٣)',
    options:[
      {text:'نقل المعلومات والصور والأخبار',correct:true},
      {text:'الطبخ',correct:false},
      {text:'النوم',correct:false},
      {text:'اللعب فقط',correct:false},
    ],
    explanation:'الإنترنت يُستعمل لنقل المعلومات والصور والأخبار بسرعة.',
    goldenRule:'الإنترنت = معلومات + صور + أخبار + سرعة.',
    feedbackQuestion:{question:'لماذا يُستعمل الإنترنت؟',options:[{text:'نقل المعلومات',correct:true},{text:'الطبخ',correct:false},{text:'النوم',correct:false},{text:'اللعب',correct:false}]},
  },
  {
    id:'u4l2q4', unit:'unit4', lesson:'u4l2', page:113, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'الإنترنت يصل الأخبار بسرعة بين الناس.',
    paragraph:'الإنترنت سريع في نقل الأخبار. (ص١١٣)',
    correctAnswer:true,
    explanation:'نعم، الإنترنت يصل الأخبار بسرعة بين الناس.',
    goldenRule:'الإنترنت = سرعة + أخبار + تواصل + فوري.',
    feedbackQuestion:{question:'هل الإنترنت سريع في نقل الأخبار؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'لا أعرف',correct:false},{text:'بعض الأحيان',correct:false}]},
  },
  {
    id:'u4l2q5', unit:'unit4', lesson:'u4l2', page:114, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'البريد الإلكتروني يُستعمل لـ:',
    paragraph:'البريد الإلكتروني: رسائل تُرسل عبر الإنترنت. (ص١١٤)',
    options:[
      {text:'إرسال الرسائل عبر الإنترنت',correct:true},
      {text:'الطبخ',correct:false},
      {text:'النوم',correct:false},
      {text:'الصيد',correct:false},
    ],
    explanation:'البريد الإلكتروني يُستعمل لإرسال الرسائل عبر الإنترنت.',
    goldenRule:'البريد الإلكتروني = رسائل + إنترنت + إرسال + سرعة.',
    feedbackQuestion:{question:'لماذا يُستعمل البريد الإلكتروني؟',options:[{text:'إرسال الرسائل',correct:true},{text:'الطبخ',correct:false},{text:'النوم',correct:false},{text:'الصيد',correct:false}]},
  },
  {
    id:'u4l2q6', unit:'unit4', lesson:'u4l2', page:114, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'من فوائد وسائل الاتصال الحديثة:',
    paragraph:'فوائد الحديثة: سرعة + سهولة + دقة + رخص. (ص١١٤)',
    options:[
      {text:'السرعة والسهولة والدقة',correct:true},
      {text:'البطء',correct:false},
      {text:'الصعوبة',correct:false},
      {text:'لا شيء',correct:false},
    ],
    explanation:'من فوائد الوسائل الحديثة: السرعة والسهولة والدقة.',
    goldenRule:'فوائد الحديثة = سرعة + سهولة + دقة + رخص.',
    feedbackQuestion:{question:'ما فوائد الوسائل الحديثة؟',options:[{text:'السرعة والسهولة',correct:true},{text:'البطء',correct:false},{text:'الصعوبة',correct:false},{text:'لا شيء',correct:false}]},
  },
  {
    id:'u4l2q7', unit:'unit4', lesson:'u4l2', page:115, type:'multipleChoice',
    bloom:'apply', difficulty:'medium',
    question:'إذا أردت إرسال صورة لصديقك فوراً، فتستعمل:',
    paragraph:'الإنترنت والهاتف من وسائل الاتصال الحديثة. (ص١١٥)',
    options:[
      {text:'الإنترنت أو الهاتف',correct:true},
      {text:'الحمام الزاجل',correct:false},
      {text:'الرسالة الورقية',correct:false},
      {text:'إشارة الدخان',correct:false},
    ],
    explanation:'لإرسال صورة فوراً، تستعمل الإنترنت أو الهاتف.',
    goldenRule:'الإرسال الفوري = إنترنت + هاتف + صورة + سرعة.',
    feedbackQuestion:{question:'كيف ترسل صورة فوراً؟',options:[{text:'الإنترنت أو الهاتف',correct:true},{text:'الحمام',correct:false},{text:'الرسالة',correct:false},{text:'الدخان',correct:false}]},
  },
  {
    id:'u4l2q8', unit:'unit4', lesson:'u4l2', page:115, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'وسائل الاتصال الحديثة أسرع من القديمة.',
    paragraph:'الحديثة أسرع وأسهل من القديمة. (ص١١٥)',
    correctAnswer:true,
    explanation:'نعم، وسائل الاتصال الحديثة أسرع من القديمة.',
    goldenRule:'الحديثة = سرعة. القديمة = بطء.',
    feedbackQuestion:{question:'هل الحديثة أسرع من القديمة؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'لا أعرف',correct:false},{text:'بعض الأحيان',correct:false}]},
  },
  {
    id:'u4l2q9', unit:'unit4', lesson:'u4l2', page:116, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'الرسائل النصية تُرسل عبر:',
    paragraph:'الرسائل النصية تُرسل عبر الهاتف المحمول. (ص١١٦)',
    options:[
      {text:'الهاتف المحمول',correct:true},
      {text:'الحمام الزاجل',correct:false},
      {text:'إشارات الدخان',correct:false},
      {text:'الرسالة الورقية',correct:false},
    ],
    explanation:'الرسائل النصية تُرسل عبر الهاتف المحمول.',
    goldenRule:'الرسائل النصية = هاتف محمول + نص + إرسال + سرعة.',
    feedbackQuestion:{question:'كيف تُرسل الرسائل النصية؟',options:[{text:'الهاتف المحمول',correct:true},{text:'الحمام',correct:false},{text:'الدخان',correct:false},{text:'الورق',correct:false}]},
  },
  {
    id:'u4l2q10', unit:'unit4', lesson:'u4l2', page:116, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'من عيوب وسائل الاتصال الحديثة:',
    paragraph:'عيوب الحديثة: الإدمان + إضاعة الوقت + الأخبار الكاذبة. (ص١١٦)',
    options:[
      {text:'الإدمان وإضاعة الوقت والأخبار الكاذبة',correct:true},
      {text:'السرعة',correct:false},
      {text:'السهولة',correct:false},
      {text:'لا شيء',correct:false},
    ],
    explanation:'من عيوب الوسائل الحديثة: الإدمان وإضاعة الوقت والأخبار الكاذبة.',
    goldenRule:'عيوب الحديثة = إدمان + وقت + أخبار كاذبة + تحذير.',
    feedbackQuestion:{question:'ما عيوب الوسائل الحديثة؟',options:[{text:'الإدمان وضياع الوقت',correct:true},{text:'السرعة',correct:false},{text:'السهولة',correct:false},{text:'لا شيء',correct:false}]},
  },
  {
    id:'u4l2q11', unit:'unit4', lesson:'u4l2', page:117, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'كيف نستعمل وسائل الاتصال الحديثة بأمان؟',
    paragraph:'الأمان: عدم إفشاء الأسرار + تجنب المواقع السيئة + احترام الناس. (ص١١٧)',
    options:[
      {text:'عدم إفشاء الأسرار وتجنب المواقع السيئة',correct:true},
      {text:'إفشاء الأسرار',correct:false},
      {text:'زيارة كل المواقع',correct:false},
      {text:'الإدمان',correct:false},
    ],
    explanation:'نستعمل وسائل الاتصال بأمان: لا إفشاء أسرار + تجنب مواقع سيئة + احترام.',
    goldenRule:'الأمان = لا أسرار + لا مواقع سيئة + احترام + أدب.',
    feedbackQuestion:{question:'كيف نستعمل الوسائل الحديثة بأمان؟',options:[{text:'لا إفشاء أسرار',correct:true},{text:'إفشاء',correct:false},{text:'كل المواقع',correct:false},{text:'إدمان',correct:false}]},
  },
  {
    id:'u4l2q12', unit:'unit4', lesson:'u4l2', page:112, type:'fillBlank',
    bloom:'apply', difficulty:'easy',
    question:'أكمل: من وسائل الاتصال الحديثة: الهاتف و___',
    paragraph:'الإنترنت من وسائل الاتصال الحديثة. (ص١١٢)',
    blanks:['الإِنْتَرْنَت'],
    wordBank:['الإِنْتَرْنَت','الْحَمَام','الدُّخَان','النَّار'],
    explanation:'من وسائل الاتصال الحديثة: الهاتف والإنترنت.',
    goldenRule:'الحديثة = هاتف + إنترنت.',
  },
  {
    id:'u4l2q13', unit:'unit4', lesson:'u4l2', page:117, type:'trueFalse',
    bloom:'understand', difficulty:'medium',
    question:'يجب على المسلم حفظ أسراره عند استعمال الإنترنت.',
    paragraph:'المسلم يحفظ أسراره في وسائل الاتصال. (ص١١٧)',
    correctAnswer:true,
    explanation:'نعم، يجب على المسلم حفظ أسراره عند استعمال وسائل الاتصال.',
    goldenRule:'حفظ الأسرار = أمانة + حماية + أدب + لا إفشاء.',
    feedbackQuestion:{question:'هل يجب حفظ الأسرار في الإنترنت؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'لا أعرف',correct:false},{text:'بعض الأحيان',correct:false}]},
  },
  {
    id:'u4l2q14', unit:'unit4', lesson:'u4l2', page:114, type:'ordering',
    bloom:'apply', difficulty:'medium',
    question:'رتّب خطوات إرسال بريد إلكتروني.',
    paragraph:'البريد: كتابة ← إدخال عنوان ← إرسال ← وصول. (ص١١٤-١١٧)',
    items:['كتابة الرسالة','إدخال عنوان المُرسَل إليه','ضغط زر الإرسال','وصول الرسالة'],
    correctOrder:[0,1,2,3],
    explanation:'البريد: كتابة ← عنوان ← إرسال ← وصول.',
    goldenRule:'البريد = كتابة ← عنوان ← إرسال ← وصول.',
  },
  {
    id:'u4l2q15', unit:'unit4', lesson:'u4l2', page:116, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف: من فوائد الوسائل الحديثة / من عيوبها.',
    paragraph:'فوائد: سرعة + سهولة + دقة. عيوب: إدمان + وقت + أخبار كاذبة. (ص١١٤-١١٦)',
    categories:['فوائد ✅','عيوب ❌'],
    items:[
      {text:'السرعة',correct_category:0},
      {text:'الإدمان',correct_category:1},
      {text:'السهولة',correct_category:0},
      {text:'إضاعة الوقت',correct_category:1},
      {text:'الدقة',correct_category:0},
      {text:'الأخبار الكاذبة',correct_category:1},
    ],
    explanation:'فوائد: سرعة + سهولة + دقة. عيوب: إدمان + وقت + أخبار كاذبة.',
    goldenRule:'فوائد = سرعة + سهولة + دقة. عيوب = إدمان + وقت + كذب.',
  },
  {
    id:'u4l2q16', unit:'unit4', lesson:'u4l2', page:115, type:'matching',
    bloom:'understand', difficulty:'medium',
    question:'صِل الوسيلة بفائدتها حديثاً.',
    paragraph:'الهاتف = صوت. الإنترنت = معلومات. البريد = رسائل. الرسائل النصية = نص. (ص١١٢-١١٦)',
    pairs:[
      {left:'الهاتف',right:'صوت فوري'},
      {left:'الإنترنت',right:'معلومات وصور'},
      {left:'البريد الإلكتروني',right:'رسائل مكتوبة'},
      {left:'الرسائل النصية',right:'نص سريع'},
    ],
    explanation:'الهاتف=صوت، الإنترنت=معلومات، البريد=رسائل، النصية=نص.',
    goldenRule:'الهاتف=صوت، الإنترنت=معلومات، البريد=رسائل، النصية=نص.',
  },
  {
    id:'u4l2q17', unit:'unit4', lesson:'u4l2', page:112, type:'trueFalse',
    bloom:'remember', difficulty:'easy',
    question:'الهاتف من وسائل الاتصال الحديثة.',
    paragraph:'الهاتف وسيلة حديثة. (ص١١٢)',
    correctAnswer:true,
    explanation:'نعم، الهاتف من وسائل الاتصال الحديثة.',
    goldenRule:'الهاتف = حديثة + صوت + تواصل + سرعة.',
    feedbackQuestion:{question:'هل الهاتف من الوسائل الحديثة؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'لا أعرف',correct:false},{text:'بعض الأحيان',correct:false}]},
  },
  {
    id:'u4l2q18', unit:'unit4', lesson:'u4l2', page:116, type:'multipleChoice',
    bloom:'apply', difficulty:'medium',
    question:'إذا تلقيت خبراً كاذباً على الإنترنت، فمن الأدب:',
    paragraph:'المسلم يتحقق من الأخبار ولا ينشر الكاذبة. (ص١١٦-١١٧)',
    options:[
      {text:'أتثبت ولا أنشره',correct:true},
      {text:'أنشره',correct:false},
      {text:'أصدقه',correct:false},
      {text:'أتجاهل',correct:false},
    ],
    explanation:'إذا تلقيت خبراً كاذباً فمن الأدب أن تتثبت ولا تنشره.',
    goldenRule:'التحقق = تثبت + لا نشر + صدق + أدب.',
    feedbackQuestion:{question:'ماذا تفعل إذا تلقيت خبراً كاذباً؟',options:[{text:'أتثبت ولا أنشر',correct:true},{text:'أنشره',correct:false},{text:'أصدقه',correct:false},{text:'أتجاهل',correct:false}]},
  },
  {
    id:'u4l2q19', unit:'unit4', lesson:'u4l2', page:117, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'لماذا يجب الحذر عند استعمال وسائل الاتصال الحديثة؟',
    paragraph:'الحذر: حفظ الأسرار + تجنب المواقع السيئة + لا إدمان. (ص١١٧)',
    options:[
      {text:'لحفظ الأسرار وتجنب المواقع السيئة',correct:true},
      {text:'عادة',correct:false},
      {text:'لا سبب',correct:false},
      {text:'مكروه',correct:false},
    ],
    explanation:'يجب الحذر لحفظ الأسرار وتجنب المواقع السيئة وعدم الإدمان.',
    goldenRule:'الحذر = حفظ + تجنب + لا إدمان + أمان.',
    feedbackQuestion:{question:'لماذا يجب الحذر في الوسائل الحديثة؟',options:[{text:'حفظ الأسرار وتجنب المواقع',correct:true},{text:'عادة',correct:false},{text:'لا سبب',correct:false},{text:'مكروه',correct:false}]},
  },
  {
    id:'u4l2q20', unit:'unit4', lesson:'u4l2', page:113, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'الإنترنت شبكة عالمية تربط:',
    paragraph:'الإنترنت يربط الناس في كل العالم. (ص١١٣)',
    options:[
      {text:'الناس في كل العالم',correct:true},
      {text:'مدينة واحدة',correct:false},
      {text:'حي واحد',correct:false},
      {text:'لا أحد',correct:false},
    ],
    explanation:'الإنترنت شبكة عالمية تربط الناس في كل العالم.',
    goldenRule:'الإنترنت = عالمي + ربط + تواصل + معلومات.',
    feedbackQuestion:{question:'بمن يربط الإنترنت؟',options:[{text:'الناس في العالم',correct:true},{text:'مدينة',correct:false},{text:'حي',correct:false},{text:'لا أحد',correct:false}]},
  },
  {
    id:'u4l2q21', unit:'unit4', lesson:'u4l2', page:114, type:'fillBlank',
    bloom:'apply', difficulty:'easy',
    question:'أكمل: البريد ___ يُرسل الرسائل عبر الإنترنت.',
    paragraph:'البريد الإلكتروني عبر الإنترنت. (ص١١٤)',
    blanks:['الإِلِكْتَرُونِيّ'],
    wordBank:['الإِلِكْتَرُونِيّ','الْوَرَقِيّ','الْقَدِيم','الْعَادِي'],
    explanation:'البريد الإلكتروني يُرسل الرسائل عبر الإنترنت.',
    goldenRule:'البريد الإلكتروني = إنترنت + رسائل + إرسال + سرعة.',
  },
  {
    id:'u4l2q22', unit:'unit4', lesson:'u4l2', page:116, type:'trueFalse',
    bloom:'understand', difficulty:'medium',
    question:'الإدمان على الهاتف والإنترنت مذموم.',
    paragraph:'الإدمان على الوسائل الحديثة يضيع الوقت. (ص١١٦)',
    correctAnswer:true,
    explanation:'نعم، الإدمان على الهاتف والإنترنت مذموم لأنه يضيع الوقت.',
    goldenRule:'الإدمان = ضياع وقت + ذم + مفسدة + لا خير.',
    feedbackQuestion:{question:'هل الإدمان مذموم؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'لا أعرف',correct:false},{text:'بعض الأحيان',correct:false}]},
  },
  {
    id:'u4l2q23', unit:'unit4', lesson:'u4l2', page:117, type:'multipleChoice',
    bloom:'apply', difficulty:'medium',
    question:'إذا رأيت موقعاً سيئاً على الإنترنت، فمن الأدب:',
    paragraph:'المسلم يغلق المواقع السيئة ويبتعد عنها. (ص١١٧)',
    options:[
      {text:'أغلقه وأبتعد عنه',correct:true},
      {text:'أبقى فيه',correct:false},
      {text:'أنشره',correct:false},
      {text:'أدعو له',correct:false},
    ],
    explanation:'إذا رأيت موقعاً سيئاً فمن الأدب أن تغلقه وتبتعد عنه.',
    goldenRule:'تجنب المواقع السيئة = إغلاق + بعد + أدب + حماية.',
    feedbackQuestion:{question:'ماذا تفعل إذا رأيت موقعاً سيئاً؟',options:[{text:'أغلقه',correct:true},{text:'أبقى',correct:false},{text:'أنشر',correct:false},{text:'أدعو',correct:false}]},
  },
  {
    id:'u4l2q24', unit:'unit4', lesson:'u4l2', page:113, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'الرسائل النصية تُرسل عبر:',
    paragraph:'الرسائل النصية تُرسل عبر الهاتف المحمول. (ص١١٦)',
    options:[
      {text:'الهاتف المحمول',correct:true},
      {text:'الحمام الزاجل',correct:false},
      {text:'الرسالة الورقية',correct:false},
      {text:'إشارة الدخان',correct:false},
    ],
    explanation:'الرسائل النصية تُرسل عبر الهاتف المحمول.',
    goldenRule:'الرسائل النصية = هاتف + نص + إرسال + سرعة.',
    feedbackQuestion:{question:'كيف تُرسل الرسائل النصية؟',options:[{text:'الهاتف المحمول',correct:true},{text:'الحمام',correct:false},{text:'الورق',correct:false},{text:'الدخان',correct:false}]},
  },
  {
    id:'u4l2q25', unit:'unit4', lesson:'u4l2', page:118, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'ما الفرق بين وسائل الاتصال القديمة والحديثة؟',
    paragraph:'القديمة بطيئة والحديثة سريعة. (ص١١٢-١١٨)',
    options:[
      {text:'الحديثة أسرع وأسهل وأدق',correct:true},
      {text:'القديمة أسرع',correct:false},
      {text:'لا فرق',correct:false},
      {text:'الحديثة أبطأ',correct:false},
    ],
    explanation:'الحديثة أسرع وأسهل وأدق من القديمة.',
    goldenRule:'الحديثة = سرعة + سهولة + دقة. القديمة = بطء + جهد.',
    feedbackQuestion:{question:'ما الفرق بين القديمة والحديثة؟',options:[{text:'الحديثة أسرع وأدق',correct:true},{text:'القديمة أسرع',correct:false},{text:'لا فرق',correct:false},{text:'الحديثة أبطأ',correct:false}]},
  },
  {
    id:'u4l2q26', unit:'unit4', lesson:'u4l2', page:117, type:'multipleChoice',
    bloom:'create', difficulty:'hard',
    question:'ركّب جملة فيها: هاتف + إنترنت + بريد + حديثة.',
    paragraph:'الهاتف والإنترنت والبريد من الوسائل الحديثة. (ص١١٢-١١٨)',
    options:[
      {text:'الهاتف والإنترنت والبريد من الوسائل الحديثة',correct:true},
      {text:'الهاتف للأكل',correct:false},
      {text:'الإنترنت للنوم',correct:false},
      {text:'لا شيء',correct:false},
    ],
    explanation:'الجملة: الهاتف والإنترنت والبريد من الوسائل الحديثة.',
    goldenRule:'الحديثة = هاتف + إنترنت + بريد + سرعة.',
  },
  {
    id:'u4l2q27', unit:'unit4', lesson:'u4l2', page:115, type:'trueFalse',
    bloom:'understand', difficulty:'medium',
    question:'وسائل الاتصال الحديثة تساعد على التعلم والتعاون.',
    paragraph:'وسائل الاتصال الحديثة تساعد على التعلم والتعاون. (ص١١٥)',
    correctAnswer:true,
    explanation:'نعم، وسائل الاتصال الحديثة تساعد على التعلم والتعاون.',
    goldenRule:'الحديثة = تعلم + تعاون + تواصل + أجر.',
    feedbackQuestion:{question:'هل الوسائل الحديثة تساعد على التعلم؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'لا أعرف',correct:false},{text:'بعض الأحيان',correct:false}]},
  },
  {
    id:'u4l2q28', unit:'unit4', lesson:'u4l2', page:116, type:'fillBlank',
    bloom:'apply', difficulty:'easy',
    question:'أكمل: من عيوب الوسائل الحديثة: الإدمان و___ الوقت.',
    paragraph:'العيوب: إدمان + إضاعة وقت + أخبار كاذبة. (ص١١٦)',
    blanks:['إِضَاعَة'],
    wordBank:['إِضَاعَة','السُّرْعَة','السُّهُولَة','الدِّقَّة'],
    explanation:'من عيوب الوسائل الحديثة: الإدمان وإضاعة الوقت.',
    goldenRule:'عيوب الحديثة = إدمان + إضاعة وقت + أخبار كاذبة.',
  },
  {
    id:'u4l2q29', unit:'unit4', lesson:'u4l2', page:118, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'لماذا يجب استعمال وسائل الاتصال الحديثة بأمان؟',
    paragraph:'الأمان يحفظ الأسرار ويحمي من المواقع السيئة. (ص١١٧-١١٨)',
    options:[
      {text:'لحفظ الأسرار والحماية من المواقع السيئة',correct:true},
      {text:'عادة',correct:false},
      {text:'لا سبب',correct:false},
      {text:'مكروه',correct:false},
    ],
    explanation:'يجب استعمال الوسائل الحديثة بأمان لحفظ الأسرار والحماية من المواقع السيئة.',
    goldenRule:'الأمان = حفظ + حماية + أدب + أجر.',
    feedbackQuestion:{question:'لماذا نستعمل الوسائل بأمان؟',options:[{text:'حفظ الأسرار والحماية',correct:true},{text:'عادة',correct:false},{text:'لا سبب',correct:false},{text:'مكروه',correct:false}]},
  },
  {
    id:'u4l2q30', unit:'unit4', lesson:'u4l2', page:118, type:'multipleChoice',
    bloom:'create', difficulty:'hard',
    question:'اكتب جملة فيها: وسائل حديثة + سرعة + أمان + أدب.',
    paragraph:'نستعمل الوسائل الحديثة بسرعة وأمان وأدب. (ص١١٢-١١٨)',
    options:[
      {text:'نستعمل الوسائل الحديثة بسرعة وأمان وأدب',correct:true},
      {text:'الوسائل سيئة',correct:false},
      {text:'لا فائدة',correct:false},
      {text:'لا شيء',correct:false},
    ],
    explanation:'الجملة: نستعمل الوسائل الحديثة بسرعة وأمان وأدب.',
    goldenRule:'الوسائل الحديثة = سرعة + أمان + أدب + خير.',
  },
];

export default UNIT4_QUESTIONS;