// لغتي - الصف الثالث الابتدائي - الوحدة الثالثة: أَخْلَاقُ الْمُسْلِمِ
// مَدْخَلُ الْوَحْدَة + درسان (الصِّدْق + الْأَمَانَة)

export const UNIT3_QUESTIONS = [
  // ─── مَدْخَلُ الْوَحْدَة الثالثة: أَخْلَاقُ الْمُسْلِمِ ─────────────
  {
    id:'u3introq1', unit:'unit3', lesson:'u3intro', page:88, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'عنوان الوحدة الثالثة في كتاب لغتي هو:',
    paragraph:'الوحدة الثالثة: أَخْلَاقُ الْمُسْلِمِ — ص ٨٨.',
    options:[
      {text:'أَخْلَاقُ الْمُسْلِمِ',correct:true},
      {text:'رُبُوعٌ مِنْ بِلَادِي',correct:false},
      {text:'التَّعَامُلُ مَعَ الْآخَرِينَ',correct:false},
      {text:'وَسَائِلُ الِاتِّصَالَاتِ',correct:false},
    ],
    explanation:'عنوان الوحدة الثالثة: أَخْلَاقُ الْمُسْلِمِ.',
    goldenRule:'أخلاق المسلم = صفات + سلوك + تعامل + أدب.',
    feedbackQuestion:{question:'ما عنوان الوحدة الثالثة؟',options:[{text:'أَخْلَاقُ الْمُسْلِمِ',correct:true},{text:'رُبُوعٌ مِنْ بِلَادِي',correct:false},{text:'وَسَائِلُ الِاتِّصَالَاتِ',correct:false},{text:'التَّعَامُلُ مَعَ الْآخَرِينَ',correct:false}]},
  },
  {
    id:'u3introq2', unit:'unit3', lesson:'u3intro', page:88, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'كم عدد دروس الوحدة الثالثة (أَخْلَاقُ الْمُسْلِمِ)؟',
    paragraph:'الوحدة الثالثة تضم درسين: الصِّدْق + الْأَمَانَة.',
    options:[
      {text:'درسان',correct:true},
      {text:'ثلاثة دروس',correct:false},
      {text:'أربعة دروس',correct:false},
      {text:'خمسة دروس',correct:false},
    ],
    explanation:'الوحدة الثالثة تضم درسين: الصِّدْق والْأَمَانَة.',
    goldenRule:'وحدة أخلاق المسلم = درسان (الصدق + الأمانة).',
    feedbackQuestion:{question:'كم درسًا في الوحدة الثالثة؟',options:[{text:'درسان',correct:true},{text:'ثلاثة',correct:false},{text:'أربعة',correct:false},{text:'خمسة',correct:false}]},
  },
  {
    id:'u3introq3', unit:'unit3', lesson:'u3intro', page:88, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'من دروس الوحدة الثالثة:',
    paragraph:'درسا الوحدة: الصِّدْق (الدرس الأول) + الْأَمَانَة (الدرس الثاني).',
    options:[
      {text:'الصِّدْق والْأَمَانَة',correct:true},
      {text:'الصِّدْق والكذب',correct:false},
      {text:'الْأَمَانَة والخيانة',correct:false},
      {text:'الصِّدْق فقط',correct:false},
    ],
    explanation:'درسا الوحدة الثالثة: الصِّدْق والْأَمَانَة.',
    goldenRule:'درسا أخلاق المسلم = الصدق + الأمانة.',
    feedbackQuestion:{question:'ما درسا الوحدة الثالثة؟',options:[{text:'الصِّدْق والْأَمَانَة',correct:true},{text:'الصِّدْق والكذب',correct:false},{text:'الْأَمَانَة والخيانة',correct:false},{text:'الصِّدْق فقط',correct:false}]},
  },
  {
    id:'u3introq4', unit:'unit3', lesson:'u3intro', page:88, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'الأخلاق تعني صفات الإنسان وتعامله مع الآخرين.',
    paragraph:'الأخلاق: صفات + سلوك + تعامل + أدب.',
    correctAnswer:true,
    explanation:'نعم، الأخلاق تعني صفات الإنسان وتعامله مع الآخرين في الحياة.',
    goldenRule:'الأخلاق = صفات + سلوك + تعامل + أدب.',
    feedbackQuestion:{question:'هل الأخلاق تعني صفات الإنسان وتعامله؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'لا أعرف',correct:false},{text:'بعض الأحيان',correct:false}]},
  },
  {
    id:'u3introq5', unit:'unit3', lesson:'u3intro', page:89, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'المسلم يتحلى بـ:',
    paragraph:'المسلم يتحلى بالأخلاق الحسنة: الصدق، الأمانة، الاحترام، التعاون.',
    options:[
      {text:'الأخلاق الحسنة',correct:true},
      {text:'الأخلاق السيئة',correct:false},
      {text:'الكذب',correct:false},
      {text:'الخيانة',correct:false},
    ],
    explanation:'المسلم يتحلى بالأخلاق الحسنة كالصدق والأمانة والاحترام.',
    goldenRule:'المسلم = أخلاق حسنة + صدق + أمانة + احترام.',
    feedbackQuestion:{question:'بماذا يتحلى المسلم؟',options:[{text:'الأخلاق الحسنة',correct:true},{text:'الأخلاق السيئة',correct:false},{text:'الكذب',correct:false},{text:'الخيانة',correct:false}]},
  },
  {
    id:'u3introq6', unit:'unit3', lesson:'u3intro', page:89, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'من أخلاق المسلم في تعامله مع الناس:',
    paragraph:'أخلاق المسلم: الصدق + الأمانة + الاحترام + التعاون + العفو.',
    options:[
      {text:'الصدق والأمانة والاحترام',correct:true},
      {text:'الكذب والخيانة',correct:false},
      {text:'الغش والظلم',correct:false},
      {text:'الأنانية والحسد',correct:false},
    ],
    explanation:'من أخلاق المسلم: الصدق والأمانة والاحترام والتعاون والعفو.',
    goldenRule:'أخلاق المسلم = صدق + أمانة + احترام + تعاون + عفو.',
    feedbackQuestion:{question:'ما أخلاق المسلم مع الناس؟',options:[{text:'الصدق والأمانة',correct:true},{text:'الكذب والخيانة',correct:false},{text:'الغش والظلم',correct:false},{text:'الأنانية والحسد',correct:false}]},
  },
  {
    id:'u3introq7', unit:'unit3', lesson:'u3intro', page:88, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'الصدق والأمانة من أهم أخلاق المسلم.',
    paragraph:'الصدق والأمانة من أعظم الأخلاق التي يتحلى بها المسلم.',
    correctAnswer:true,
    explanation:'نعم، الصدق والأمانة من أهم وأعظم أخلاق المسلم.',
    goldenRule:'الصدق + الأمانة = أعظم أخلاق المسلم.',
    feedbackQuestion:{question:'هل الصدق والأمانة من أخلاق المسلم؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'لا أعرف',correct:false},{text:'بعض الأحيان',correct:false}]},
  },
  {
    id:'u3introq8', unit:'unit3', lesson:'u3intro', page:89, type:'multipleChoice',
    bloom:'apply', difficulty:'medium',
    question:'إذا وعدت صديقك بزيارة، فمن أخلاق المسلم:',
    paragraph:'المسلم يفي بوعده ويصدق في حديثه.',
    options:[
      {text:'أن أفي بوعدي وأزوره',correct:true},
      {text:'أن أكسر وعدي',correct:false},
      {text:'أن أكذب عليه',correct:false},
      {text:'أن أتجاهله',correct:false},
    ],
    explanation:'إذا وعدت صديقك فمن أخلاق المسلم أن تفي بوعدك وتزوره.',
    goldenRule:'الوعد = وفاء + صدق + احترام + أدب.',
    feedbackQuestion:{question:'ماذا تفعل إذا وعدت صديقك؟',options:[{text:'أفي بوعدي',correct:true},{text:'أكسر وعدي',correct:false},{text:'أكذب',correct:false},{text:'أتجاهل',correct:false}]},
  },
  {
    id:'u3introq9', unit:'unit3', lesson:'u3intro', page:88, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'الأخلاق الحسنة سبب في:',
    paragraph:'الأخلاق الحسنة سبب في محبة الناس ومحبة الله.',
    options:[
      {text:'محبة الله ومحبة الناس',correct:true},
      {text:'كراهية الناس',correct:false},
      {text:'العزلة',correct:false},
      {text:'لا شيء',correct:false},
    ],
    explanation:'الأخلاق الحسنة سبب في محبة الله ومحبة الناس للمسلم.',
    goldenRule:'الأخلاق الحسنة = محبة الله + محبة الناس + أجر.',
    feedbackQuestion:{question:'ماذا تسبب الأخلاق الحسنة؟',options:[{text:'محبة الله والناس',correct:true},{text:'كراهية',correct:false},{text:'عزلة',correct:false},{text:'لا شيء',correct:false}]},
  },
  {
    id:'u3introq10', unit:'unit3', lesson:'u3intro', page:89, type:'trueFalse',
    bloom:'evaluate', difficulty:'hard',
    question:'حسن الخلق من أثقل الأعمال في ميزان المؤمن يوم القيامة.',
    paragraph:'حسن الخلق من أثقل ما يوضع في ميزان العبد يوم القيامة.',
    correctAnswer:true,
    explanation:'نعم، حسن الخلق من أثقل الأعمال في ميزان المؤمن يوم القيامة.',
    goldenRule:'حسن الخلق = أثقل العمل + أجر + ثواب + رفعة.',
    feedbackQuestion:{question:'هل حسن الخلق من أثقل الأعمال؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'لا أعرف',correct:false},{text:'بعض الأحيان',correct:false}]},
  },
  {
    id:'u3introq11', unit:'unit3', lesson:'u3intro', page:88, type:'fillBlank',
    bloom:'apply', difficulty:'easy',
    question:'أكمل: عنوان الوحدة الثالثة هو أَخْلَاقُ ___',
    paragraph:'الوحدة الثالثة: أَخْلَاقُ الْمُسْلِمِ.',
    blanks:['الْمُسْلِمِ'],
    wordBank:['الْمُسْلِمِ','الْكَافِرِ','الْقَرْيَة','الْمَدِينَة'],
    explanation:'عنوان الوحدة الثالثة: أَخْلَاقُ الْمُسْلِمِ.',
    goldenRule:'عنوان الوحدة الثالثة = أَخْلَاقُ الْمُسْلِمِ.',
  },
  {
    id:'u3introq12', unit:'unit3', lesson:'u3intro', page:89, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'من opposites أخلاق المسلم الحسنة:',
    paragraph:'أخلاق المسلم الحسنة: صدق + أمانة + احترام. أضدادها: كذب + خيانة + سوء أدب.',
    options:[
      {text:'الكذب والخيانة وسوء الأدب',correct:true},
      {text:'الصدق والأمانة',correct:false},
      {text:'الاحترام والتواضع',correct:false},
      {text:'التعاون والعفو',correct:false},
    ],
    explanation:'أضداد الأخلاق الحسنة: الكذب والخيانة وسوء الأدب.',
    goldenRule:'ضد الصدق = كذب. ضد الأمانة = خيانة. ضد الاحترام = سوء أدب.',
    feedbackQuestion:{question:'ما opposites أخلاق المسلم الحسنة؟',options:[{text:'الكذب والخيانة',correct:true},{text:'الصدق والأمانة',correct:false},{text:'الاحترام',correct:false},{text:'التعاون',correct:false}]},
  },
  {
    id:'u3introq13', unit:'unit3', lesson:'u3intro', page:88, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف: أخلاق حسنة / أخلاق سيئة.',
    paragraph:'الحسنة: صدق + أمانة + احترام. السيئة: كذب + خيانة + غش.',
    categories:['أخلاق حسنة ✅','أخلاق سيئة ❌'],
    items:[
      {text:'الصدق',correct_category:0},
      {text:'الكذب',correct_category:1},
      {text:'الأمانة',correct_category:0},
      {text:'الخيانة',correct_category:1},
      {text:'الاحترام',correct_category:0},
      {text:'الغش',correct_category:1},
    ],
    explanation:'حسنة: صدق + أمانة + احترام. سيئة: كذب + خيانة + غش.',
    goldenRule:'الحسنة: صدق + أمانة + احترام. السيئة: كذب + خيانة + غش.',
  },
  {
    id:'u3introq14', unit:'unit3', lesson:'u3intro', page:89, type:'matching',
    bloom:'understand', difficulty:'medium',
    question:'صِل الخلق بضده.',
    paragraph:'الصدق ضد الكذب. الأمانة ضد الخيانة. الاحترام ضد الإساءة.',
    pairs:[
      {left:'الصدق',right:'الكذب'},
      {left:'الأمانة',right:'الخيانة'},
      {left:'الاحترام',right:'الإساءة'},
      {left:'التعاون',right:'الأنانية'},
    ],
    explanation:'كل خلق حسن له ضد سيء.',
    goldenRule:'الصدق ضد الكذب. الأمانة ضد الخيانة. الاحترام ضد الإساءة.',
  },
  {
    id:'u3introq15', unit:'unit3', lesson:'u3intro', page:89, type:'multipleChoice',
    bloom:'create', difficulty:'hard',
    question:'ركّب جملة فيها: صدق + أمانة + احترام.',
    paragraph:'المسلم يتحلى بالصدق والأمانة والاحترام.',
    options:[
      {text:'المسلم يتحلى بالصدق والأمانة والاحترام',correct:true},
      {text:'المسلم يكذب ويخون',correct:false},
      {text:'المسلم يغش ويسيء',correct:false},
      {text:'المسلم يأنق',correct:false},
    ],
    explanation:'الجملة: المسلم يتحلى بالصدق والأمانة والاحترام.',
    goldenRule:'الجملة: المسلم = صدق + أمانة + احترام.',
  },

  // ─── الدرس 1: الصِّدْق (ص ٩٠–٩٥) ─────────────────────
  {
    id:'u3l1q1', unit:'unit3', lesson:'u3l1', page:90, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'الصِّدْق هو:',
    paragraph:'الصدق: مطابقة الظاهر للباطن، قول الحق وعدم الكذب. (ص٩٠)',
    options:[
      {text:'قول الحق وعدم الكذب',correct:true},
      {text:'قول غير الحق',correct:false},
      {text:'الإخبار بما لا يحدث',correct:false},
      {text:'إخفاء الحقيقة',correct:false},
    ],
    explanation:'الصدق هو قول الحق وعدم الكذب، ومطابقة الظاهر للباطن.',
    goldenRule:'الصدق = قول الحق + مطابقة الظاهر للباطن + لا كذب.',
    feedbackQuestion:{question:'ما هو الصدق؟',options:[{text:'قول الحق وعدم الكذب',correct:true},{text:'قول غير الحق',correct:false},{text:'الإخبار بما لا يحدث',correct:false},{text:'إخفاء الحقيقة',correct:false}]},
  },
  {
    id:'u3l1q2', unit:'unit3', lesson:'u3l1', page:90, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'ضد الصدق هو:',
    paragraph:'ضد الصدق: الكذب. (ص٩٠)',
    options:[
      {text:'الكذب',correct:true},
      {text:'الأمانة',correct:false},
      {text:'الاحترام',correct:false},
      {text:'التعاون',correct:false},
    ],
    explanation:'ضد الصدق هو الكذب.',
    goldenRule:'ضد الصدق = الكذب.',
    feedbackQuestion:{question:'ما ضد الصدق؟',options:[{text:'الكذب',correct:true},{text:'الأمانة',correct:false},{text:'الاحترام',correct:false},{text:'التعاون',correct:false}]},
  },
  {
    id:'u3l1q3', unit:'unit3', lesson:'u3l1', page:90, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'الكاذب لا يصدقه الناس ويفقد ثقتهم.',
    paragraph:'الكاذب يفقد ثقة الناس ولا يصدقونه. (ص٩٠)',
    correctAnswer:true,
    explanation:'نعم، الكاذب يفقد ثقة الناس ولا يصدقونه.',
    goldenRule:'الكذب = فقدان الثقة + كراهية + ضياع + ذنب.',
    feedbackQuestion:{question:'هل الكاذب يفقد ثقة الناس؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'لا أعرف',correct:false},{text:'بعض الأحيان',correct:false}]},
  },
  {
    id:'u3l1q4', unit:'unit3', lesson:'u3l1', page:91, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'من أنواع الصدق:',
    paragraph:'أنواع الصدق: صدق الحديث + صدق النية + صدق العزم. (ص٩١)',
    options:[
      {text:'صدق الحديث والنية والعزم',correct:true},
      {text:'صدق الكذب',correct:false},
      {text:'صدق الخيانة',correct:false},
      {text:'صدق الغش',correct:false},
    ],
    explanation:'من أنواع الصدق: صدق الحديث، صدق النية، صدق العزم.',
    goldenRule:'أنواع الصدق = حديث + نية + عزم.',
    feedbackQuestion:{question:'ما أنواع الصدق؟',options:[{text:'الحديث والنية والعزم',correct:true},{text:'الكذب',correct:false},{text:'الخيانة',correct:false},{text:'الغش',correct:false}]},
  },
  {
    id:'u3l1q5', unit:'unit3', lesson:'u3l1', page:91, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'صدق الحديث يعني:',
    paragraph:'صدق الحديث: أن تقول ما حدث كما هو دون تغيير. (ص٩١)',
    options:[
      {text:'قول ما حدث كما هو دون تغيير',correct:true},
      {text:'تحريف الحديث',correct:false},
      {text:'إخفاء الحقيقة',correct:false},
      {text:'الكذب',correct:false},
    ],
    explanation:'صدق الحديث: قول ما حدث كما هو دون تغيير أو تحريف.',
    goldenRule:'صدق الحديث = قول + لا تحريف + لا إخفاء + لا كذب.',
    feedbackQuestion:{question:'ما صدق الحديث؟',options:[{text:'قول ما حدث كما هو',correct:true},{text:'تحريف',correct:false},{text:'إخفاء',correct:false},{text:'كذب',correct:false}]},
  },
  {
    id:'u3l1q6', unit:'unit3', lesson:'u3l1', page:91, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'صدق النية يعني:',
    paragraph:'صدق النية: إخلاص العمل لله دون رياء. (ص٩١)',
    options:[
      {text:'إخلاص العمل لله دون رياء',correct:true},
      {text:'الرياء',correct:false},
      {text:'النفاق',correct:false},
      {text:'السمعة',correct:false},
    ],
    explanation:'صدق النية: إخلاص العمل لله دون رياء أو سمعة.',
    goldenRule:'صدق النية = إخلاص + لله + لا رياء + لا سمعة.',
    feedbackQuestion:{question:'ما صدق النية؟',options:[{text:'إخلاص العمل لله',correct:true},{text:'الرياء',correct:false},{text:'النفاق',correct:false},{text:'السمعة',correct:false}]},
  },
  {
    id:'u3l1q7', unit:'unit3', lesson:'u3l1', page:92, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'قال رسول الله ﷺ: «إنَّ الصِّدْقَ يَهْدِي إلى الْبِرِّ، وإنَّ الْبِرَّ يَهْدِي إلى...»',
    paragraph:'حديث: «الصدق يهدي إلى البر، والبر يهدي إلى الجنة». (ص٩٢)',
    options:[
      {text:'الجنة',correct:true},
      {text:'النار',correct:false},
      {text:'الضلال',correct:false},
      {text:'لا شيء',correct:false},
    ],
    explanation:'قال ﷺ: «إن الصدق يهدي إلى البر، وإن البر يهدي إلى الجنة».',
    goldenRule:'الصدق → البر → الجنة.',
    feedbackQuestion:{question:'إلى أين يهدي الصدق؟',options:[{text:'الجنة',correct:true},{text:'النار',correct:false},{text:'الضلال',correct:false},{text:'لا شيء',correct:false}]},
  },
  {
    id:'u3l1q8', unit:'unit3', lesson:'u3l1', page:92, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'في الحديث: «وإنَّ الْكَذِبَ يَهْدِي إلى...»',
    paragraph:'حديث: «الكذب يهدي إلى الفجور، والفجور يهدي إلى النار». (ص٩٢)',
    options:[
      {text:'الفجور ثم النار',correct:true},
      {text:'الجنة',correct:false},
      {text:'البر',correct:false},
      {text:'الخير',correct:false},
    ],
    explanation:'قال ﷺ: «وإن الكذب يهدي إلى الفجور، وإن الفجور يهدي إلى النار».',
    goldenRule:'الكذب → الفجور → النار.',
    feedbackQuestion:{question:'إلى أين يهدي الكذب؟',options:[{text:'الفجور ثم النار',correct:true},{text:'الجنة',correct:false},{text:'البر',correct:false},{text:'الخير',correct:false}]},
  },
  {
    id:'u3l1q9', unit:'unit3', lesson:'u3l1', page:92, type:'trueFalse',
    bloom:'understand', difficulty:'medium',
    question:'الصادق محبوب عند الله وعند الناس.',
    paragraph:'الصادق محبوب عند الله وعند الناس. (ص٩٢)',
    correctAnswer:true,
    explanation:'نعم، الصادق محبوب عند الله وعند الناس.',
    goldenRule:'الصادق = محبة الله + محبة الناس + ثقة + أجر.',
    feedbackQuestion:{question:'هل الصادق محبوب عند الله والناس؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'لا أعرف',correct:false},{text:'بعض الأحيان',correct:false}]},
  },
  {
    id:'u3l1q10', unit:'unit3', lesson:'u3l1', page:93, type:'multipleChoice',
    bloom:'apply', difficulty:'medium',
    question:'إذا سألك والداك عن دروسك، فمن الصدق:',
    paragraph:'المسلم يصدق مع والديه في كل شيء. (ص٩٣)',
    options:[
      {text:'أخبرهما بالحقيقة',correct:true},
      {text:'أكذب عليهما',correct:false},
      {text:'أخفي عنهما',correct:false},
      {text:'أتظاهر',correct:false},
    ],
    explanation:'إذا سألك والداك فمن الصدق أن تخبرهما بالحقيقة دون كذب.',
    goldenRule:'الصدق مع الوالدين = حقيقة + لا كذب + لا إخفاء + أدب.',
    feedbackQuestion:{question:'ماذا تفعل إذا سألك والداك؟',options:[{text:'أخبرهما بالحقيقة',correct:true},{text:'أكذب',correct:false},{text:'أخفي',correct:false},{text:'أتظاهر',correct:false}]},
  },
  {
    id:'u3l1q11', unit:'unit3', lesson:'u3l1', page:93, type:'multipleChoice',
    bloom:'apply', difficulty:'medium',
    question:'إذا أخطأت في المدرسة، فمن الصدق:',
    paragraph:'المسلم يصدق ويعترف بخطئه. (ص٩٣)',
    options:[
      {text:'أعترف بخطئي بصدق',correct:true},
      {text:'أنكر وأكذب',correct:false},
      {text:'ألوم غيري',correct:false},
      {text:'أتهرب',correct:false},
    ],
    explanation:'إذا أخطأت فمن الصدق أن تعترف بخطئك بصدق دون كذب.',
    goldenRule:'الاعتراف بالخطأ = صدق + شجاعة + أدب + لا كذب.',
    feedbackQuestion:{question:'ماذا تفعل إذا أخطأت؟',options:[{text:'أعترف بصدق',correct:true},{text:'أنكر وأكذب',correct:false},{text:'ألوم غيري',correct:false},{text:'أتهرب',correct:false}]},
  },
  {
    id:'u3l1q12', unit:'unit3', lesson:'u3l1', page:94, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'من فوائد الصدق:',
    paragraph:'فوائد الصدق: محبة الله + محبة الناس + الثقة + الأجر + النجاح. (ص٩٤)',
    options:[
      {text:'محبة الله والناس والثقة والأجر',correct:true},
      {text:'كراهية الناس',correct:false},
      {text:'فقدان الثقة',correct:false},
      {text:'الضياع',correct:false},
    ],
    explanation:'من فوائد الصدق: محبة الله ومحبة الناس والثقة والأجر والنجاح.',
    goldenRule:'الصدق = محبة + ثقة + أجر + نجاح.',
    feedbackQuestion:{question:'ما فوائد الصدق؟',options:[{text:'محبة الله والناس',correct:true},{text:'كراهية',correct:false},{text:'فقدان ثقة',correct:false},{text:'ضياع',correct:false}]},
  },
  {
    id:'u3l1q13', unit:'unit3', lesson:'u3l1', page:94, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'الكذب يفسد العلاقات بين الناس.',
    paragraph:'الكذب يفسد العلاقات ويهدم الثقة. (ص٩٤)',
    correctAnswer:true,
    explanation:'نعم، الكذب يفسد العلاقات بين الناس ويهدم الثقة.',
    goldenRule:'الكذب = فساد علاقات + هدم ثقة + كراهية + ذنب.',
    feedbackQuestion:{question:'هل الكذب يفسد العلاقات؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'لا أعرف',correct:false},{text:'بعض الأحيان',correct:false}]},
  },
  {
    id:'u3l1q14', unit:'unit3', lesson:'u3l1', page:94, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'لماذا أمر الإسلام بالصدق؟',
    paragraph:'الصدق خلق عظيم، يهدي إلى الجنة ويبني الثقة. (ص٩٢-٩٤)',
    options:[
      {text:'لأنه يهدي إلى الجنة ويبني الثقة بين الناس',correct:true},
      {text:'لأنه عادة',correct:false},
      {text:'لا سبب',correct:false},
      {text:'لأنه مكروه',correct:false},
    ],
    explanation:'أمر الإسلام بالصدق لأنه يهدي إلى الجنة ويبني الثقة بين الناس.',
    goldenRule:'الصدق = هداية للجنة + بناء ثقة + أجر + محبة.',
    feedbackQuestion:{question:'لماذا أمر الإسلام بالصدق؟',options:[{text:'يهدي للجنة ويبني الثقة',correct:true},{text:'عادة',correct:false},{text:'لا سبب',correct:false},{text:'مكروه',correct:false}]},
  },
  {
    id:'u3l1q15', unit:'unit3', lesson:'u3l1', page:95, type:'multipleChoice',
    bloom:'apply', difficulty:'medium',
    question:'إذا وجدت شيئاً ضاع من صديقك، فمن الصدق:',
    paragraph:'المسلم يصدق ويرد الأمانة لأصحابها. (ص٩٥)',
    options:[
      {text:'أعيده إليه بصدق',correct:true},
      {text:'أكتمه',correct:false},
      {text:'أنكر معرفته',correct:false},
      {text:'آخذه',correct:false},
    ],
    explanation:'إذا وجدت ما ضاع من صديقك فمن الصدق أن تعيده إليه.',
    goldenRule:'رد الضائع = صدق + أمانة + أدب + خلق.',
    feedbackQuestion:{question:'ماذا تفعل إذا وجدت ضائع صديقك؟',options:[{text:'أعيده بصدق',correct:true},{text:'أكتمه',correct:false},{text:'أنكر',correct:false},{text:'آخذه',correct:false}]},
  },
  {
    id:'u3l1q16', unit:'unit3', lesson:'u3l1', page:92, type:'fillBlank',
    bloom:'apply', difficulty:'easy',
    question:'أكمل الحديث: «إنَّ الصِّدْقَ يَهْدِي إلى الْبِرِّ، وإنَّ الْبِرَّ يَهْدِي إلى ___»',
    paragraph:'حديث: «الصدق يهدي إلى البر، والبر يهدي إلى الجنة». (ص٩٢)',
    blanks:['الْجَنَّة'],
    wordBank:['الْجَنَّة','النَّار','الضَّلَال','الْفُجُور'],
    explanation:'«إن الصدق يهدي إلى البر، وإن البر يهدي إلى الجنة».',
    goldenRule:'الصدق → البر → الجنة.',
  },
  {
    id:'u3l1q17', unit:'unit3', lesson:'u3l1', page:92, type:'fillBlank',
    bloom:'apply', difficulty:'easy',
    question:'أكمل: «وإنَّ الْكَذِبَ يَهْدِي إلى الْفُجُورِ، وإنَّ الْفُجُورَ يَهْدِي إلى ___»',
    paragraph:'حديث: «الكذب يهدي إلى الفجور، والفجور يهدي إلى النار». (ص٩٢)',
    blanks:['النَّار'],
    wordBank:['النَّار','الْجَنَّة','الْبِرِّ','الْخَيْر'],
    explanation:'«وإن الكذب يهدي إلى الفجور، وإن الفجور يهدي إلى النار».',
    goldenRule:'الكذب → الفجور → النار.',
  },
  {
    id:'u3l1q18', unit:'unit3', lesson:'u3l1', page:93, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'الصادق في الوعد يسمى:',
    paragraph:'المسلم يصدق في وعده فيفي به. (ص٩٣)',
    options:[
      {text:'صادقاً موفياً بوعده',correct:true},
      {text:'كاذباً',correct:false},
      {text:'خائناً',correct:false},
      {text:'ناقضاً',correct:false},
    ],
    explanation:'الصادق في الوعد يفي به ويصدق في قوله.',
    goldenRule:'الصدق في الوعد = وفاء + لا نقض + أدب + أجر.',
    feedbackQuestion:{question:'ماذا يسمى الصادق في الوعد؟',options:[{text:'موفياً بوعده',correct:true},{text:'كاذباً',correct:false},{text:'خائناً',correct:false},{text:'ناقضاً',correct:false}]},
  },
  {
    id:'u3l1q19', unit:'unit3', lesson:'u3l1', page:94, type:'ordering',
    bloom:'apply', difficulty:'medium',
    question:'رتّب مراتب الصدق حسب الأهمية.',
    paragraph:'الصدق في الحديث أساس، ثم النية، ثم العزم. (ص٩١)',
    items:['صدق الحديث','صدق النية','صدق العزم'],
    correctOrder:[0,1,2],
    explanation:'الصدق يبدأ بالحديث ثم النية ثم العزم.',
    goldenRule:'الصدق = حديث ← نية ← عزم.',
  },
  {
    id:'u3l1q20', unit:'unit3', lesson:'u3l1', page:94, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف: من الصدق / من الكذب.',
    paragraph:'الصدق: قول الحق + الاعتراف + رد الأمانة. الكذب: إنكار + إخفاء + غش. (ص٩٠-٩٤)',
    categories:['من الصدق ✅','من الكذب ❌'],
    items:[
      {text:'قول الحق',correct_category:0},
      {text:'إنكار الحقيقة',correct_category:1},
      {text:'الاعتراف بالخطأ',correct_category:0},
      {text:'الإخفاء والغش',correct_category:1},
      {text:'رد الأمانة',correct_category:0},
      {text:'نقض الوعد',correct_category:1},
    ],
    explanation:'الصدق: قول الحق + اعتراف + رد أمانة. الكذب: إنكار + إخفاء + نقض.',
    goldenRule:'الصدق: قول + اعتراف + رد. الكذب: إنكار + إخفاء + نقض.',
  },
  {
    id:'u3l1q21', unit:'unit3', lesson:'u3l1', page:95, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'ماذا يحدث لو كثر الكذب في المجتمع؟',
    paragraph:'الكذب يفسد العلاقات ويهدم الثقة في المجتمع. (ص٩٤)',
    options:[
      {text:'فساد العلاقات وفقدان الثقة',correct:true},
      {text:'محبة وتعاون',correct:false},
      {text:'أمان',correct:false},
      {text:'لا شيء',correct:false},
    ],
    explanation:'لو كثر الكذب في المجتمع فسدت العلاقات وفقدت الثقة بين الناس.',
    goldenRule:'كثرة الكذب = فساد + فقدان ثقة + كراهية + ضياع.',
    feedbackQuestion:{question:'ماذا يحدث لو كثر الكذب؟',options:[{text:'فساد وفقدان ثقة',correct:true},{text:'محبة',correct:false},{text:'أمان',correct:false},{text:'لا شيء',correct:false}]},
  },
  {
    id:'u3l1q22', unit:'unit3', lesson:'u3l1', page:95, type:'matching',
    bloom:'understand', difficulty:'medium',
    question:'صِل الكلمة بمعناها.',
    paragraph:'الصدق: قول الحق. الكذب: قول غير الحق. الفجور: انبعاث المعصية. البر: الخير والإحسان. (ص٩٢)',
    pairs:[
      {left:'الصدق',right:'قول الحق'},
      {left:'الكذب',right:'قول غير الحق'},
      {left:'البر',right:'الخير والإحسان'},
      {left:'الفجور',right:'الانبعاث في المعصية'},
    ],
    explanation:'الصدق=حق، الكذب=غير حق، البر=خير، الفجور=معصية.',
    goldenRule:'الصدق=حق. الكذب=غير حق. البر=خير. الفجور=معصية.',
  },
  {
    id:'u3l1q23', unit:'unit3', lesson:'u3l1', page:93, type:'multipleChoice',
    bloom:'create', difficulty:'hard',
    question:'ركّب جملة فيها: صدق + وعد + وفاء.',
    paragraph:'المسلم يصدق في وعده ويفي به. (ص٩٣)',
    options:[
      {text:'المسلم يصدق في وعده ويفي به',correct:true},
      {text:'المسلم يكذب وينقض',correct:false},
      {text:'المسلم يخون',correct:false},
      {text:'المسلم يتهرب',correct:false},
    ],
    explanation:'الجملة: المسلم يصدق في وعده ويفي به.',
    goldenRule:'الجملة: المسلم = صدق + وعد + وفاء.',
  },
  {
    id:'u3l1q24', unit:'unit3', lesson:'u3l1', page:90, type:'trueFalse',
    bloom:'remember', difficulty:'easy',
    question:'الصدق من أعظم أخلاق المسلم.',
    paragraph:'الصدق من أعظم الأخلاق في الإسلام. (ص٩٠)',
    correctAnswer:true,
    explanation:'نعم، الصدق من أعظم أخلاق المسلم.',
    goldenRule:'الصدق = أعظم الأخلاق + خلق المسلم + أجر + محبة.',
    feedbackQuestion:{question:'هل الصدق من أعظم الأخلاق؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'لا أعرف',correct:false},{text:'بعض الأحيان',correct:false}]},
  },
  {
    id:'u3l1q25', unit:'unit3', lesson:'u3l1', page:95, type:'multipleChoice',
    bloom:'apply', difficulty:'medium',
    question:'إذا رأيت زميلك يكذب، فمن النصح:',
    paragraph:'المسلم ينصح صاحبه ويأمره بالصدق. (ص٩٥)',
    options:[
      {text:'أنصحه بالصدق بلطف',correct:true},
      {text:'أسكت',correct:false},
      {text:'أشجعه',correct:false},
      {text:'أشاركه',correct:false},
    ],
    explanation:'إذا رأيت زميلك يكذب فمن النصح أن تنصحه بالصدق بلطف.',
    goldenRule:'النصح = لطف + صدق + أمر بالمعروف + أدب.',
    feedbackQuestion:{question:'ماذا تفعل إذا رأيت زميلك يكذب؟',options:[{text:'أنصحه بالصدق',correct:true},{text:'أسكت',correct:false},{text:'أشجعه',correct:false},{text:'أشاركه',correct:false}]},
  },
  {
    id:'u3l1q26', unit:'unit3', lesson:'u3l1', page:91, type:'trueFalse',
    bloom:'understand', difficulty:'medium',
    question:'صدق النية أن تعمل لله دون رياء.',
    paragraph:'صدق النية: إخلاص العمل لله دون رياء أو سمعة. (ص٩١)',
    correctAnswer:true,
    explanation:'نعم، صدق النية أن تعمل لله دون رياء أو سمعة.',
    goldenRule:'صدق النية = لله + إخلاص + لا رياء + لا سمعة.',
    feedbackQuestion:{question:'هل صدق النية أن تعمل لله دون رياء؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'لا أعرف',correct:false},{text:'بعض الأحيان',correct:false}]},
  },
  {
    id:'u3l1q27', unit:'unit3', lesson:'u3l1', page:94, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'الصادق ينال:',
    paragraph:'الصادق ينال محبة الله ومحبة الناس والثقة والأجر. (ص٩٤)',
    options:[
      {text:'محبة الله والناس والثقة',correct:true},
      {text:'كراهية',correct:false},
      {text:'ضياع',correct:false},
      {text:'لا شيء',correct:false},
    ],
    explanation:'الصادق ينال محبة الله ومحبة الناس والثقة والأجر.',
    goldenRule:'الصادق = محبة + ثقة + أجر + نجاح.',
    feedbackQuestion:{question:'ماذا ينال الصادق؟',options:[{text:'محبة وثقة وأجر',correct:true},{text:'كراهية',correct:false},{text:'ضياع',correct:false},{text:'لا شيء',correct:false}]},
  },
  {
    id:'u3l1q28', unit:'unit3', lesson:'u3l1', page:90, type:'fillBlank',
    bloom:'apply', difficulty:'easy',
    question:'أكمل: الصدق هو قول ___ وعدم الكذب.',
    paragraph:'الصدق: قول الحق وعدم الكذب. (ص٩٠)',
    blanks:['الْحَقِّ'],
    wordBank:['الْحَقِّ','الْبَاطِلِ','الْكَذِبِ','الْخَيَالِ'],
    explanation:'الصدق هو قول الحق وعدم الكذب.',
    goldenRule:'الصدق = قول الحق + لا كذب.',
  },
  {
    id:'u3l1q29', unit:'unit3', lesson:'u3l1', page:95, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'ماذا يحدث للصادق يوم القيامة؟',
    paragraph:'الصادق ينال رضوان الله ودخول الجنة. (ص٩٢)',
    options:[
      {text:'رضوان الله ودخول الجنة',correct:true},
      {text:'العذاب',correct:false},
      {text:'الضياع',correct:false},
      {text:'لا شيء',correct:false},
    ],
    explanation:'الصادق ينال رضوان الله ودخول الجنة يوم القيامة.',
    goldenRule:'الصادق يوم القيامة = رضوان + جنة + أجر + نعيم.',
    feedbackQuestion:{question:'ماذا ينال الصادق يوم القيامة؟',options:[{text:'رضوان الله والجنة',correct:true},{text:'العذاب',correct:false},{text:'الضياع',correct:false},{text:'لا شيء',correct:false}]},
  },
  {
    id:'u3l1q30', unit:'unit3', lesson:'u3l1', page:95, type:'multipleChoice',
    bloom:'create', difficulty:'hard',
    question:'اكتب جملة فيها: صدق + حديث + أمانة + احترام.',
    paragraph:'المسلم يصدق في حديثه ويؤتمن ويحترم الناس. (ص٩٠-٩٥)',
    options:[
      {text:'المسلم يصدق في حديثه ويؤتمن ويحترم',correct:true},
      {text:'المسلم يكذب ويخون',correct:false},
      {text:'المسلم يغش',correct:false},
      {text:'المسلم يأنق',correct:false},
    ],
    explanation:'الجملة: المسلم يصدق في حديثه ويؤتمن ويحترم.',
    goldenRule:'المسلم = صدق + أمانة + احترام + أدب.',
  },

  // ─── الدرس 2: الْأَمَانَة (ص ٩٦–١٠٢) ─────────────────────
  {
    id:'u3l2q1', unit:'unit3', lesson:'u3l2', page:96, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'الْأَمَانَة هي:',
    paragraph:'الأمانة: حفظ ما اؤتمن عليه الإنسان وأداؤه لأصحابه. (ص٩٦)',
    options:[
      {text:'حفظ ما اؤتمن عليه وأداؤه لأصحابه',correct:true},
      {text:'إخفاء الأشياء',correct:false},
      {text:'أخذ الأشياء',correct:false},
      {text:'إتلاف الأشياء',correct:false},
    ],
    explanation:'الأمانة هي حفظ ما اؤتمن عليه الإنسان وأداؤه لأصحابه.',
    goldenRule:'الأمانة = حفظ + أداء + حفظ الحقوق + أدب.',
    feedbackQuestion:{question:'ما هي الأمانة؟',options:[{text:'حفظ ما اؤتمن وأداؤه',correct:true},{text:'إخفاء',correct:false},{text:'أخذ',correct:false},{text:'إتلاف',correct:false}]},
  },
  {
    id:'u3l2q2', unit:'unit3', lesson:'u3l2', page:96, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'ضد الأمانة:',
    paragraph:'ضد الأمانة: الخيانة. (ص٩٦)',
    options:[
      {text:'الخيانة',correct:true},
      {text:'الصدق',correct:false},
      {text:'الاحترام',correct:false},
      {text:'التعاون',correct:false},
    ],
    explanation:'ضد الأمانة هو الخيانة.',
    goldenRule:'ضد الأمانة = الخيانة.',
    feedbackQuestion:{question:'ما ضد الأمانة؟',options:[{text:'الخيانة',correct:true},{text:'الصدق',correct:false},{text:'الاحترام',correct:false},{text:'التعاون',correct:false}]},
  },
  {
    id:'u3l2q3', unit:'unit3', lesson:'u3l2', page:96, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'من أنواع الأمانة:',
    paragraph:'أنواع الأمانة: الأشياء + الأسرار + الوظائف + العبادات. (ص٩٦)',
    options:[
      {text:'الأشياء والأسرار والوظائف والعبادات',correct:true},
      {text:'الكذب',correct:false},
      {text:'الخيانة',correct:false},
      {text:'الغش',correct:false},
    ],
    explanation:'من أنواع الأمانة: الأشياء، الأسرار، الوظائف، والعبادات.',
    goldenRule:'أنواع الأمانة = أشياء + أسرار + وظائف + عبادات.',
    feedbackQuestion:{question:'ما أنواع الأمانة؟',options:[{text:'الأشياء والأسرار والوظائف',correct:true},{text:'الكذب',correct:false},{text:'الخيانة',correct:false},{text:'الغش',correct:false}]},
  },
  {
    id:'u3l2q4', unit:'unit3', lesson:'u3l2', page:97, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'أمانة الأشياء تعني:',
    paragraph:'أمانة الأشياء: حفظ ما يُؤتمن عليه الإنسان من أشياء وإعادتها. (ص٩٧)',
    options:[
      {text:'حفظ الأشياء وإعادتها لأصحابها',correct:true},
      {text:'أخذها',correct:false},
      {text:'إتلافها',correct:false},
      {text:'إخفاؤها',correct:false},
    ],
    explanation:'أمانة الأشياء: حفظها وإعادتها لأصحابها كما أخذت.',
    goldenRule:'أمانة الأشياء = حفظ + إعادة + لا إتلاف + لا أخذ.',
    feedbackQuestion:{question:'ما أمانة الأشياء؟',options:[{text:'حفظ وإعادة لأصحابها',correct:true},{text:'أخذ',correct:false},{text:'إتلاف',correct:false},{text:'إخفاء',correct:false}]},
  },
  {
    id:'u3l2q5', unit:'unit3', lesson:'u3l2', page:97, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'أمانة الأسرار تعني:',
    paragraph:'أمانة الأسرار: كتمان ما يُسرّ إليك ولا تبوح به. (ص٩٧)',
    options:[
      {text:'كتمان الأسرار وعدم إفشائها',correct:true},
      {text:'إفشاؤها',correct:false},
      {text:'نشرها',correct:false},
      {text:'قولها للكل',correct:false},
    ],
    explanation:'أمانة الأسرار: كتمانها وعدم إفشائها.',
    goldenRule:'أمانة الأسرار = كتمان + لا إفشاء + لا نشر + حفظ.',
    feedbackQuestion:{question:'ما أمانة الأسرار؟',options:[{text:'كتمان وعدم إفشاء',correct:true},{text:'إفشاء',correct:false},{text:'نشر',correct:false},{text:'قول للكل',correct:false}]},
  },
  {
    id:'u3l2q6', unit:'unit3', lesson:'u3l2', page:97, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'إفشاء سر صديقك من الخيانة.',
    paragraph:'إفشاء السر خيانة للأمانة. (ص٩٧)',
    correctAnswer:true,
    explanation:'نعم، إفشاء سر صديقك من الخيانة وترك الأمانة.',
    goldenRule:'إفشاء السر = خيانة + ذنب + فقدان ثقة + قبح.',
    feedbackQuestion:{question:'هل إفشاء السر خيانة؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'لا أعرف',correct:false},{text:'بعض الأحيان',correct:false}]},
  },
  {
    id:'u3l2q7', unit:'unit3', lesson:'u3l2', page:98, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'أمانة العبادات تعني:',
    paragraph:'أمانة العبادات: أداء العبادات بإخلاص لله كما أمر. (ص٩٨)',
    options:[
      {text:'أداء العبادات بإخلاص لله',correct:true},
      {text:'الرياء',correct:false},
      {text:'تركها',correct:false},
      {text:'التأخر',correct:false},
    ],
    explanation:'أمانة العبادات: أداؤها بإخلاص لله كما أمر.',
    goldenRule:'أمانة العبادات = إخلاص + أداء + لله + لا رياء.',
    feedbackQuestion:{question:'ما أمانة العبادات؟',options:[{text:'أداء بإخلاص لله',correct:true},{text:'الرياء',correct:false},{text:'تركها',correct:false},{text:'التأخر',correct:false}]},
  },
  {
    id:'u3l2q8', unit:'unit3', lesson:'u3l2', page:98, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'أمانة الوظائف تعني:',
    paragraph:'أمانة الوظائف: أداء العمل بإتقان وإخلاص. (ص٩٨)',
    options:[
      {text:'أداء العمل بإتقان وإخلاص',correct:true},
      {text:'التقصير',correct:false},
      {text:'الإهمال',correct:false},
      {text:'الغش',correct:false},
    ],
    explanation:'أمانة الوظائف: أداء العمل بإتقان وإخلاص.',
    goldenRule:'أمانة الوظائف = إتقان + إخلاص + أداء + لا إهمال.',
    feedbackQuestion:{question:'ما أمانة الوظائف؟',options:[{text:'إتقان وإخلاص',correct:true},{text:'تقصير',correct:false},{text:'إهمال',correct:false},{text:'غش',correct:false}]},
  },
  {
    id:'u3l2q9', unit:'unit3', lesson:'u3l2', page:99, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'قال الله تعالى: «إِنَّ اللَّهَ يَأْمُرُكُمْ أَنْ تُؤَدُّوا الْأَمَانَاتِ إلى...»',
    paragraph:'آية: «إن الله يأمركم أن تؤدوا الأمانات إلى أهلها». (ص٩٩)',
    options:[
      {text:'أهلها',correct:true},
      {text:'غيرهم',correct:false},
      {text:'الكل',correct:false},
      {text:'لا أحد',correct:false},
    ],
    explanation:'قال الله: «إن الله يأمركم أن تؤدوا الأمانات إلى أهلها».',
    goldenRule:'الأمانة تُؤدى إلى أهلها = أمر الله + حفظ + أداء + أدب.',
    feedbackQuestion:{question:'إلى من تُؤدى الأمانة؟',options:[{text:'أهلها',correct:true},{text:'غيرهم',correct:false},{text:'الكل',correct:false},{text:'لا أحد',correct:false}]},
  },
  {
    id:'u3l2q10', unit:'unit3', lesson:'u3l2', page:99, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'أداء الأمانة أمر من الله تعالى.',
    paragraph:'الله أمر بأداء الأمانات إلى أهلها. (ص٩٩)',
    correctAnswer:true,
    explanation:'نعم، أداء الأمانة أمر من الله تعالى في القرآن.',
    goldenRule:'أداء الأمانة = أمر الله + طاعة + أجر + أدب.',
    feedbackQuestion:{question:'هل أداء الأمانة أمر من الله؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'لا أعرف',correct:false},{text:'بعض الأحيان',correct:false}]},
  },
  {
    id:'u3l2q11', unit:'unit3', lesson:'u3l2', page:100, type:'multipleChoice',
    bloom:'apply', difficulty:'medium',
    question:'إذا استعرت قلماً من زميلك، فمن الأمانة:',
    paragraph:'المسلم يؤدي الأمانة ويردها لأصحابها. (ص١٠٠)',
    options:[
      {text:'أعيده كما أخذته',correct:true},
      {text:'أكتمه',correct:false},
      {text:'أتلفه',correct:false},
      {text:'أنكر معرفته',correct:false},
    ],
    explanation:'إذا استعرت قلماً فمن الأمانة أن تعيده كما أخذته.',
    goldenRule:'رد الأمانة = إعادة + حفظ + أداء + أدب.',
    feedbackQuestion:{question:'ماذا تفعل إذا استعرت قلماً؟',options:[{text:'أعيده',correct:true},{text:'أكتمه',correct:false},{text:'أتلفه',correct:false},{text:'أنكر',correct:false}]},
  },
  {
    id:'u3l2q12', unit:'unit3', lesson:'u3l2', page:100, type:'multipleChoice',
    bloom:'apply', difficulty:'medium',
    question:'إذا ائتمنك صديق على سر، فمن الأمانة:',
    paragraph:'المسلم يحفظ السر ولا يفشيه. (ص٩٧-١٠٠)',
    options:[
      {text:'أكتمه ولا أفشيه',correct:true},
      {text:'أفشيه',correct:false},
      {text:'أنشره',correct:false},
      {text:'أقوله للكل',correct:false},
    ],
    explanation:'إذا ائتمنك صديق على سر فمن الأمانة أن تكتمه.',
    goldenRule:'كتمان السر = أمانة + حفظ + لا إفشاء + أدب.',
    feedbackQuestion:{question:'ماذا تفعل إذا ائتمنك صديق على سر؟',options:[{text:'أكتمه',correct:true},{text:'أفشيه',correct:false},{text:'أنشره',correct:false},{text:'أقوله',correct:false}]},
  },
  {
    id:'u3l2q13', unit:'unit3', lesson:'u3l2', page:100, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'الخائن للأمانة يفقد ثقة الناس.',
    paragraph:'الخائن يفقد ثقة الناس ويُذم. (ص١٠٠)',
    correctAnswer:true,
    explanation:'نعم، الخائن للأمانة يفقد ثقة الناس.',
    goldenRule:'الخيانة = فقدان ثقة + ذنب + ذم + كراهية.',
    feedbackQuestion:{question:'هل الخائن يفقد ثقة الناس؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'لا أعرف',correct:false},{text:'بعض الأحيان',correct:false}]},
  },
  {
    id:'u3l2q14', unit:'unit3', lesson:'u3l2', page:101, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'من فوائد الأمانة:',
    paragraph:'فوائد الأمانة: محبة الله + محبة الناس + الثقة + الأجر. (ص١٠١)',
    options:[
      {text:'محبة الله والناس والثقة',correct:true},
      {text:'كراهية',correct:false},
      {text:'فقدان الثقة',correct:false},
      {text:'الضياع',correct:false},
    ],
    explanation:'من فوائد الأمانة: محبة الله ومحبة الناس والثقة والأجر.',
    goldenRule:'الأمانة = محبة + ثقة + أجر + نجاح.',
    feedbackQuestion:{question:'ما فوائد الأمانة؟',options:[{text:'محبة وثقة',correct:true},{text:'كراهية',correct:false},{text:'فقدان ثقة',correct:false},{text:'ضياع',correct:false}]},
  },
  {
    id:'u3l2q15', unit:'unit3', lesson:'u3l2', page:101, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'الأمانة من أخلاق الأنبياء والرسل.',
    paragraph:'الأنبياء والرسل أمناء في تبليغ رسالة الله. (ص١٠١)',
    correctAnswer:true,
    explanation:'نعم، الأمانة من أخلاق الأنبياء والرسل.',
    goldenRule:'الأنبياء = أمانة + صدق + تبليغ + إخلاص.',
    feedbackQuestion:{question:'هل الأمانة من أخلاق الأنبياء؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'لا أعرف',correct:false},{text:'بعض الأحيان',correct:false}]},
  },
  {
    id:'u3l2q16', unit:'unit3', lesson:'u3l2', page:99, type:'fillBlank',
    bloom:'apply', difficulty:'easy',
    question:'أكمل الآية: «إِنَّ اللَّهَ يَأْمُرُكُمْ أَنْ تُؤَدُّوا الْأَمَانَاتِ إلى ___»',
    paragraph:'آية: «إن الله يأمركم أن تؤدوا الأمانات إلى أهلها». (ص٩٩)',
    blanks:['أَهْلِهَا'],
    wordBank:['أَهْلِهَا','غَيْرِهِمْ','النَّاسِ','الْكُلِّ'],
    explanation:'«إن الله يأمركم أن تؤدوا الأمانات إلى أهلها».',
    goldenRule:'الأمانة تُؤدى إلى أهلها = أمر الله.',
  },
  {
    id:'u3l2q17', unit:'unit3', lesson:'u3l2', page:101, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'لماذا أمر الله بأداء الأمانات؟',
    paragraph:'أداء الأمانات يبني الثقة ويحفظ الحقوق. (ص٩٩-١٠١)',
    options:[
      {text:'لأنه يبني الثقة ويحفظ الحقوق',correct:true},
      {text:'عادة',correct:false},
      {text:'لا سبب',correct:false},
      {text:'مكروه',correct:false},
    ],
    explanation:'أمر الله بأداء الأمانات لأنه يبني الثقة ويحفظ الحقوق.',
    goldenRule:'أداء الأمانة = ثقة + حفظ حقوق + أجر + أمر الله.',
    feedbackQuestion:{question:'لماذا أمر الله بأداء الأمانات؟',options:[{text:'يبني الثقة ويحفظ الحقوق',correct:true},{text:'عادة',correct:false},{text:'لا سبب',correct:false},{text:'مكروه',correct:false}]},
  },
  {
    id:'u3l2q18', unit:'unit3', lesson:'u3l2', page:102, type:'ordering',
    bloom:'apply', difficulty:'medium',
    question:'رتّب أنواع الأمانة حسب أهميتها.',
    paragraph:'أنواع الأمانة: أشياء + أسرار + وظائف + عبادات. (ص٩٦-٩٨)',
    items:['أمانة العبادات','أمانة الأسرار','أمانة الأشياء','أمانة الوظائف'],
    correctOrder:[0,1,2,3],
    explanation:'العبادات أعظم، ثم الأسرار، ثم الأشياء، ثم الوظائف.',
    goldenRule:'أمانة = عبادات ← أسرار ← أشياء ← وظائف.',
  },
  {
    id:'u3l2q19', unit:'unit3', lesson:'u3l2', page:102, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف: من الأمانة / من الخيانة.',
    paragraph:'الأمانة: حفظ + رد + كتمان. الخيانة: إفشاء + إخفاء + إتلاف. (ص٩٦-١٠١)',
    categories:['من الأمانة ✅','من الخيانة ❌'],
    items:[
      {text:'حفظ السر',correct_category:0},
      {text:'إفشاء السر',correct_category:1},
      {text:'رد الأمانة',correct_category:0},
      {text:'إتلاف الأمانة',correct_category:1},
      {text:'إتقان العمل',correct_category:0},
      {text:'الإهمال',correct_category:1},
    ],
    explanation:'الأمانة: حفظ + رد + إتقان. الخيانة: إفشاء + إتلاف + إهمال.',
    goldenRule:'الأمانة: حفظ + رد + إتقان. الخيانة: إفشاء + إتلاف + إهمال.',
  },
  {
    id:'u3l2q20', unit:'unit3', lesson:'u3l2', page:100, type:'matching',
    bloom:'understand', difficulty:'medium',
    question:'صِل نوع الأمانة بمعناها.',
    paragraph:'أنواع الأمانة: أشياء + أسرار + وظائف + عبادات. (ص٩٦-٩٨)',
    pairs:[
      {left:'أمانة الأشياء',right:'حفظ وإعادة'},
      {left:'أمانة الأسرار',right:'كتمان'},
      {left:'أمانة الوظائف',right:'إتقان'},
      {left:'أمانة العبادات',right:'إخلاص لله'},
    ],
    explanation:'الأشياء=حفظ، الأسرار=كتمان، الوظائف=إتقان، العبادات=إخلاص.',
    goldenRule:'أشياء=حفظ، أسرار=كتمان، وظائف=إتقان، عبادات=إخلاص.',
  },
  {
    id:'u3l2q21', unit:'unit3', lesson:'u3l2', page:102, type:'multipleChoice',
    bloom:'apply', difficulty:'medium',
    question:'إذا وجدت محفظة في الطريق، فمن الأمانة:',
    paragraph:'المسلم يؤدي الأمانة ولو وجدها في الطريق. (ص١٠٢)',
    options:[
      {text:'أبحث عن صاحبها وأعيدها',correct:true},
      {text:'آخذها',correct:false},
      {text:'أتركها',correct:false},
      {text:'أكتمها',correct:false},
    ],
    explanation:'إذا وجدت محفظة فمن الأمانة أن تبحث عن صاحبها وتعيدها.',
    goldenRule:'رد الضائعة = أمانة + بحث + إعادة + أجر.',
    feedbackQuestion:{question:'ماذا تفعل إذا وجدت محفظة؟',options:[{text:'أبحث عن صاحبها',correct:true},{text:'آخذها',correct:false},{text:'أتركها',correct:false},{text:'أكتمها',correct:false}]},
  },
  {
    id:'u3l2q22', unit:'unit3', lesson:'u3l2', page:97, type:'trueFalse',
    bloom:'understand', difficulty:'medium',
    question:'كتمان السر وعدم إفشائه من الأمانة.',
    paragraph:'أمانة الأسرار: كتمانها وعدم إفشائها. (ص٩٧)',
    correctAnswer:true,
    explanation:'نعم، كتمان السر وعدم إفشائه من الأمانة.',
    goldenRule:'كتمان السر = أمانة + حفظ + لا إفشاء + أدب.',
    feedbackQuestion:{question:'هل كتمان السر من الأمانة؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'لا أعرف',correct:false},{text:'بعض الأحيان',correct:false}]},
  },
  {
    id:'u3l2q23', unit:'unit3', lesson:'u3l2', page:101, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'ماذا يحدث لو انتشرت الخيانة في المجتمع؟',
    paragraph:'الخيانة تفسد المجتمع وتهدم الثقة. (ص١٠١)',
    options:[
      {text:'فساد المجتمع وفقدان الثقة',correct:true},
      {text:'محبة وتعاون',correct:false},
      {text:'أمان',correct:false},
      {text:'لا شيء',correct:false},
    ],
    explanation:'لو انتشرت الخيانة فسد المجتمع وفقدت الثقة بين الناس.',
    goldenRule:'انتشار الخيانة = فساد + فقدان ثقة + ضياع + ذنب.',
    feedbackQuestion:{question:'ماذا يحدث لو انتشرت الخيانة؟',options:[{text:'فساد وفقدان ثقة',correct:true},{text:'محبة',correct:false},{text:'أمان',correct:false},{text:'لا شيء',correct:false}]},
  },
  {
    id:'u3l2q24', unit:'unit3', lesson:'u3l2', page:96, type:'fillBlank',
    bloom:'apply', difficulty:'easy',
    question:'أكمل: ضِدّ الْأَمَانَة هو ___',
    paragraph:'ضد الأمانة: الخيانة. (ص٩٦)',
    blanks:['الْخِيَانَة'],
    wordBank:['الْخِيَانَة','الصِّدْق','الاحْتِرَام','التَّعَاوُن'],
    explanation:'ضد الأمانة هو الخيانة.',
    goldenRule:'ضد الأمانة = الخيانة.',
  },
  {
    id:'u3l2q25', unit:'unit3', lesson:'u3l2', page:102, type:'multipleChoice',
    bloom:'create', difficulty:'hard',
    question:'اكتب جملة فيها: أمانة + حفظ + أداء + صدق.',
    paragraph:'المسلم يؤدي الأمانة ويحفظها ويصدق. (ص٩٦-١٠٢)',
    options:[
      {text:'المسلم يؤدي الأمانة ويحفظها ويصدق',correct:true},
      {text:'المسلم يخون',correct:false},
      {text:'المسلم يكذب',correct:false},
      {text:'المسلم يهمل',correct:false},
    ],
    explanation:'الجملة: المسلم يؤدي الأمانة ويحفظها ويصدق.',
    goldenRule:'المسلم = أمانة + حفظ + أداء + صدق.',
  },
  {
    id:'u3l2q26', unit:'unit3', lesson:'u3l2', page:98, type:'trueFalse',
    bloom:'understand', difficulty:'medium',
    question:'إتقان العمل في الوظيفة من أمانة الوظائف.',
    paragraph:'أمانة الوظائف: أداء العمل بإتقان وإخلاص. (ص٩٨)',
    correctAnswer:true,
    explanation:'نعم، إتقان العمل من أمانة الوظائف.',
    goldenRule:'إتقان العمل = أمانة وظيفة + إخلاص + أداء + أجر.',
    feedbackQuestion:{question:'هل إتقان العمل من الأمانة؟',options:[{text:'نعم',correct:true},{text:'لا',correct:false},{text:'لا أعرف',correct:false},{text:'بعض الأحيان',correct:false}]},
  },
  {
    id:'u3l2q27', unit:'unit3', lesson:'u3l2', page:101, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'الأمين ينال:',
    paragraph:'الأمين ينال محبة الله ومحبة الناس والثقة. (ص١٠١)',
    options:[
      {text:'محبة الله والناس والثقة',correct:true},
      {text:'كراهية',correct:false},
      {text:'ضياع',correct:false},
      {text:'لا شيء',correct:false},
    ],
    explanation:'الأمين ينال محبة الله ومحبة الناس والثقة.',
    goldenRule:'الأمين = محبة + ثقة + أجر + نجاح.',
    feedbackQuestion:{question:'ماذا ينال الأمين؟',options:[{text:'محبة وثقة',correct:true},{text:'كراهية',correct:false},{text:'ضياع',correct:false},{text:'لا شيء',correct:false}]},
  },
  {
    id:'u3l2q28', unit:'unit3', lesson:'u3l2', page:99, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'«إِنَّ اللَّهَ يَأْمُرُكُمْ أَنْ تُؤَدُّوا الْأَمَانَاتِ إلى أَهْلِهَا» تدل على:',
    paragraph:'الآية أمر بأداء الأمانات إلى أهلها. (ص٩٩)',
    options:[
      {text:'وجوب أداء الأمانة إلى أهلها',correct:true},
      {text:'جواز الخيانة',correct:false},
      {text:'عدم الأمانة',correct:false},
      {text:'إبقاء الأمانة',correct:false},
    ],
    explanation:'الآية تدل على وجوب أداء الأمانة إلى أهلها.',
    goldenRule:'الآية = وجوب + أداء + أهل + أمر الله.',
    feedbackQuestion:{question:'على ماذا تدل الآية؟',options:[{text:'وجوب أداء الأمانة',correct:true},{text:'جواز الخيانة',correct:false},{text:'عدم الأمانة',correct:false},{text:'إبقاء',correct:false}]},
  },
  {
    id:'u3l2q29', unit:'unit3', lesson:'u3l2', page:102, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'لماذا يُمدح الأمين في المجتمع؟',
    paragraph:'الأمين محبوب وموثوق في المجتمع. (ص١٠١-١٠٢)',
    options:[
      {text:'لأنه يحفظ الحقوق ويبني الثقة',correct:true},
      {text:'عادة',correct:false},
      {text:'لا سبب',correct:false},
      {text:'مكروه',correct:false},
    ],
    explanation:'يُمدح الأمين لأنه يحفظ الحقوق ويبني الثقة في المجتمع.',
    goldenRule:'الأمين = حفظ حقوق + بناء ثقة + محبة + أجر.',
    feedbackQuestion:{question:'لماذا يُمدح الأمين؟',options:[{text:'يحفظ الحقوق ويبني الثقة',correct:true},{text:'عادة',correct:false},{text:'لا سبب',correct:false},{text:'مكروه',correct:false}]},
  },
  {
    id:'u3l2q30', unit:'unit3', lesson:'u3l2', page:102, type:'multipleChoice',
    bloom:'create', difficulty:'hard',
    question:'ركّب جملة فيها: أمانة + أشياء + أسرار + عبادات.',
    paragraph:'المسلم يحفظ أمانة الأشياء والأسرار والعبادات. (ص٩٦-١٠٢)',
    options:[
      {text:'المسلم يحفظ أمانة الأشياء والأسرار والعبادات',correct:true},
      {text:'المسلم يخون',correct:false},
      {text:'المسلم يكذب',correct:false},
      {text:'المسلم يهمل',correct:false},
    ],
    explanation:'الجملة: المسلم يحفظ أمانة الأشياء والأسرار والعبادات.',
    goldenRule:'المسلم = أمانة أشياء + أسرار + عبادات + حفظ.',
  },
];

export default UNIT3_QUESTIONS;