// الوحدة 1: التّعَامُلُ مَعَ الْآخَرِينَ
// الدروس 1-4
export const U1L1_QS = [
  {
    id:'u1l1q1', unit:'unit1', lesson:'u1l1', page:7, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'حروف (الشمسية) هي الحروف التي لا تُنطق بعد (ال) التعريف، وتُشَدَّد. أيٌّ مما يلي حرف شمسي؟',
    paragraph:'حروف «ال» الشمسية: ت د ث ر ز س ش ص ض ط ظ ل ن. (ص7-8)',
    options:[
      {text:'الراء (ر)',correct:true},
      {text:'الباء (ب)',correct:false},
      {text:'الجيم (ج)',correct:false},
      {text:'القاف (ق)',correct:false},
    ],
    explanation:'حروف «ال» الشمسية هي: ت، د، ث، ر، ز، س، ش، ص، ض، ط، ظ، ل، ن. الراء حرف شمسي يُشَدَّد بعد «ال».',
    goldenRule:'الحروف الشمسية ١٤ حرفاً: ت د ث ر ز س ش ص ض ط ظ ل ن — تُشَدَّد بعد «ال».',
    feedbackQuestion:{question:'في كلمة «الشمس»، ما نوع حرف الشين بعد «ال»؟',options:[{text:'شمسي يُشَدَّد',correct:true},{text:'قمري يُسكَّن',correct:false},{text:'لا يُكتب',correct:false},{text:'يُحذف',correct:false}]},
  },
  {
    id:'u1l1q2', unit:'unit1', lesson:'u1l1', page:7, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'حروف (القمرية) هي الحروف التي يُسكَن اللام بعد «ال» التعريف. أيٌّ مما يلي حرف قمري؟',
    paragraph:'حروف «ال» القمرية: أ ب ج ح خ ع غ ف ق ك م ه و ي. (ص7-8)',
    options:[
      {text:'الميم (م)',correct:true},
      {text:'السين (س)',correct:false},
      {text:'الطاء (ط)',correct:false},
      {text:'النون (ن)',correct:false},
    ],
    explanation:'حروف «ال» القمرية: أ، ب، ج، ح، خ، ع، غ، ف، ق، ك، م، ه، و، ي. الميم حرف قمري يُسكَن بعده اللام.',
    goldenRule:'الحروف القمرية ١٤ حرفاً: أ ب ج ح خ ع غ ف ق ك م ه و ي — يُسكَن اللام بعدها.',
    feedbackQuestion:{question:'في كلمة «القمر»، ما نوع حرف القاف؟',options:[{text:'قمري يُسكَن اللام',correct:true},{text:'شمسي يُشَدَّد',correct:false},{text:'لا شيء',correct:false},{text:'يُحذف',correct:false}]},
  },
  {
    id:'u1l1q3', unit:'unit1', lesson:'u1l1', page:8, type:'classify',
    bloom:'understand', difficulty:'medium',
    question:'صنّف الكلمات التالية: هل اللام فيها شمسية أم قمرية؟',
    paragraph:'الكلمات: الشمس، القمر، النور، الكتاب، الدر، السر. (ص7-8)',
    categories:['ال شمسية ☀️','ال قمرية 🌙'],
    items:[
      {text:'الشمس',correct_category:0},
      {text:'القمر',correct_category:1},
      {text:'النور',correct_category:0},
      {text:'الكتاب',correct_category:1},
      {text:'الدر',correct_category:0},
      {text:'السر',correct_category:0},
    ],
    explanation:'الشمسية (تُشَدَّد): الشمس، النور، الدر، السر. القمرية (يُسكَن): القمر، الكتاب.',
    goldenRule:'ال شمسية = تشديد. ال قمرية = تسكين اللام. افحص الحرف الأول بعد ال.',
  },
  {
    id:'u1l1q4', unit:'unit1', lesson:'u1l1', page:8, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'في كلمة «السماء»، اللام قمرية ويُسكَن بعدها حرف السين.',
    paragraph:'السُّماء: السين حرف شمسي، فاللام تُشَدَّد وتُدمج مع السين. (ص8)',
    correctAnswer:false,
    explanation:'السين حرف شمسي، لذا اللام تُشَدَّد وتُدمج: اَسْـماء (السين مُشَدَّد).',
    goldenRule:'السماء: السين شمسية ← اللام تُشَدَّد وتُدمج مع السين.',
    feedbackQuestion:{question:'في كلمة «النجم»، اللام:',options:[{text:'شمسية تُشَدَّد',correct:true},{text:'قمرية تُسكَن',correct:false},{text:'تُحذف',correct:false},{text:'مفتوحة',correct:false}]},
  },
  {
    id:'u1l1q5', unit:'unit1', lesson:'u1l1', page:9, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'التنوين هو نون ساكنة تُلحق آخر الاسم نطقاً لا كتابةً. له ثلاث حالات: الضم (ـٌ)، الفتح (ـً)، الكسر (ـٍ). تنوين الفتح يُكتب على الحرف:',
    paragraph:'التنوين: ضم (ـٌ)، فتح (ـً)، كسر (ـٍ). (ص9)',
    options:[
      {text:'ويُلحق بألفًا إذا كان الحرف صالحاً للألف',correct:true},
      {text:'ويُلحق بياءً دائماً',correct:false},
      {text:'يُكتب على الحرف فقط دون ألف',correct:false},
      {text:'لا يُكتب إطلاقاً',correct:false},
    ],
    explanation:'تنوين الفتح (ـً) يُكتب على الحرف ويُلحق بألف مفتوحة، إلا في (ـة) تُكتب على التاء.',
    goldenRule:'تنوين الفتح = فتحة + ألف (ـًا). تنوين الضم = ضمتان (ـٌ). تنوين الكسر = كسرتان (ـٍ).',
    feedbackQuestion:{question:'كيف يُكتب تنوين الفتح في كلمة «كتاباً»؟',options:[{text:'كتابًا (بألف)',correct:true},{text:'كتابٍ (بكسرتين)',correct:false},{text:'كتابٌ (بضمتين)',correct:false},{text:'كتاب (بدون)',correct:false}]},
  },
  {
    id:'u1l1q6', unit:'unit1', lesson:'u1l1', page:9, type:'fillBlank',
    bloom:'apply', difficulty:'medium',
    question:'أكمل بنوع التنوين المناسب: «رأيتُ طائرً___ يطير في السماء»',
    paragraph:'تنوين الفتح يُلحق بألف في الأسماء: رأيتُ طائرًا. (ص9)',
    blanks:['ا'],
    wordBank:['ا','ٍ','ٌ','ه'],
    explanation:'تنوين الفتح (ـًا) يُلحق بألف بعد الحرف الصالح: طائرًا.',
    goldenRule:'تنوين الفتح في الاسم المنصرف = فتحة + ألف.',
  },
  {
    id:'u1l1q7', unit:'unit1', lesson:'u1l1', page:10, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'الحروف اللينة (ممدودة) المدية هي الألف والواو والياء. تُمدّ الألف حركتان، والواو والياء كذلك. الكلمة التي تحتوي على مدّ بالألف:',
    paragraph:'الحروف اللينة: الألف (مدّ حركتان)، الواو (مدّ حركتان)، الياء (مدّ حركتان). (ص10)',
    options:[
      {text:'قال',correct:true},
      {text:'قيل',correct:false},
      {text:'قُول',correct:false},
      {text:'قل',correct:false},
    ],
    explanation:'«قال» فيها ألف ممدودة بعد القاف المفتوحة = مدّ بالألف حركتين.',
    goldenRule:'مدّ الألف = بعد حرف مفتوح (قال). مدّ الواو = بعد حرف مضموم (قُول). مدّ الياء = بعد حرف مكسور (قيل).',
    feedbackQuestion:{question:'في كلمة «نُور»، نوع المدّ هو:',options:[{text:'مدّ بالواو',correct:true},{text:'مدّ بالألف',correct:false},{text:'مدّ بالياء',correct:false},{text:'لا مدّ',correct:false}]},
  },
  {
    id:'u1l1q8', unit:'unit1', lesson:'u1l1', page:10, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف الكلمات حسب نوع المدّ فيها:',
    paragraph:'أنواع المدّ: الألف (بعد مفتوح)، الواو (بعد مضموم)، الياء (بعد مكسور). (ص10)',
    categories:['مدّ بالألف','مدّ بالواو','مدّ بالياء'],
    items:[
      {text:'قال',correct_category:0},
      {text:'نُور',correct_category:1},
      {text:'بِير',correct_category:2},
      {text:'دَار',correct_category:0},
      {text:'رُوس',correct_category:1},
      {text:'دِين',correct_category:2},
    ],
    explanation:'الألف بعد مفتوح (قال، دَار). الواو بعد مضموم (نُور، رُوس). الياء بعد مكسور (بِير، دِين).',
    goldenRule:'المدّ يتحدد بحركة الحرف قبله: فتحة→ألف، ضمة→واو، كسرة→ياء.',
  },
  {
    id:'u1l1q9', unit:'unit1', lesson:'u1l1', page:10, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'التاء المربوطة (ـة) تُكتب في آخر الاسم وتُنطق تاءً عند الوقف هاءً. أيُّ كلمة تنتهي بتاء مربوطة؟',
    paragraph:'التاء المربوطة (ـة): فاطمة، مدرسة، حديقة. والتاء المفتوحة (ة/ـة): في الفعل مثل «بقيت». (ص10-11)',
    options:[
      {text:'مدرسة',correct:true},
      {text:'كتبت',correct:false},
      {text:'بيت',correct:false},
      {text:'ذهب',correct:false},
    ],
    explanation:'«مدرسة» تنتهي بتاء مربوطة (ـة) وتُنطق هاء عند الوقف: مدرسهْ.',
    goldenRule:'التاء المربوطة (ـة) في الاسم وتُنطق هاءً عند الوقف. التاء المفتوحة (ة) في الفعل أو الاسم المذكر.',
    feedbackQuestion:{question:'كيف تُنطق تاء «حديقة» عند الوقف عليها؟',options:[{text:'حديقهْ (هاء)',correct:true},{text:'حديقت (تاء)',correct:false},{text:'حديقا (ألف)',correct:false},{text:'تُحذف',correct:false}]},
  },
  {
    id:'u1l1q10', unit:'unit1', lesson:'u1l1', page:11, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'الاسم هو كلمة تدل على شخص أو شيء أو مكان. الفعل يدل على حدث في زمن. الحرف لا يدل على معنى بمفرده. أيٌّ مما يلي فعل؟',
    paragraph:'الاسم: كتاب، محمد، مدرسة. الفعل: كتب، يكتب، اكتب. الحرف: من، إلى، عن. (ص11)',
    options:[
      {text:'كتبَ',correct:true},
      {text:'كتاب',correct:false},
      {text:'في',correct:false},
      {text:'مدرسة',correct:false},
    ],
    explanation:'«كتبَ» فعل ماضٍ يدل على حدث في الزمن الماضي. «كتاب» اسم. «في» حرف جر.',
    goldenRule:'الاسم = شخص/شيء/مكان. الفعل = حدث في زمن (ماضٍ/مضارع/أمر). الحرف = لا معنى وحده.',
    feedbackQuestion:{question:'أيٌّ مما يلي اسم؟',options:[{text:'محمد',correct:true},{text:'يلعب',correct:false},{text:'على',correct:false},{text:'اكتب',correct:false}]},
  },
  {
    id:'u1l1q11', unit:'unit1', lesson:'u1l1', page:11, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف الكلمات: اسم، فعل، حرف؟',
    paragraph:'الاسم: مدرسة، طالب. الفعل: قرأ، يقرأ، اقرأ. الحرف: في، من، إلى. (ص11)',
    categories:['اسم','فعل','حرف'],
    items:[
      {text:'مدرسة',correct_category:0},
      {text:'قرأ',correct_category:1},
      {text:'في',correct_category:2},
      {text:'طالب',correct_category:0},
      {text:'من',correct_category:2},
      {text:'يلعب',correct_category:1},
    ],
    explanation:'الاسم: مدرسة، طالب. الفعل: قرأ، يلعب. الحرف: في، من.',
    goldenRule:'قسّم الكلمة: اسم (شيء) / فعل (حدث) / حرف (لا معنى وحده).',
  },
  {
    id:'u1l1q12', unit:'unit1', lesson:'u1l1', page:11, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'كلمة «من» حرف جر لا يدل على معنى بمفرده.',
    paragraph:'حروف الجر: من، إلى، عن، على، في، الباء، الكاف، اللام. (ص11)',
    correctAnswer:true,
    explanation:'«من» حرف جر لا يدل على معنى مستقل، بل يربط الاسم بما قبله.',
    goldenRule:'الحرف لا يدل على معنى بمفرده، بل يربط الكلمات (من، في، إلى).',
    feedbackQuestion:{question:'كلمة «إلى» هي:',options:[{text:'حرف جر',correct:true},{text:'اسم',correct:false},{text:'فعل',correct:false},{text:'ضمير',correct:false}]},
  },
  {
    id:'u1l1q13', unit:'unit1', lesson:'u1l1', page:11, type:'ordering',
    bloom:'apply', difficulty:'medium',
    question:'رتّب الكلمات لتكوين جملة مفيدة صحيحة:',
    paragraph:'ترتيب الجملة الاسمية: مبتدأ + خبر. (الطالبُ / مجتهدٌ / في / فصلِهِ). (ص11)',
    items:['مجتهدٌ','في','فصلِهِ','الطالبُ'],
    correctOrder:[3,0,1,2],
    explanation:'الترتيب: الطالبُ (مبتدأ) + مجتهدٌ (خبر) + في فصلِهِ (جار ومجرور).',
    goldenRule:'الجملة الاسمية = مبتدأ + خبر. ابدأ بالاسم المرفوع ثم صفته أو خبره.',
  },
  {
    id:'u1l1q14', unit:'unit1', lesson:'u1l1', page:11, type:'fillBlank',
    bloom:'apply', difficulty:'medium',
    question:'أكمل الجملة بالكلمة المناسبة: «___ كتابُنا الجديدُ»',
    paragraph:'إكمال الجملة: هذا كتابُنا الجديدُ. (ص11)',
    blanks:['هذا'],
    wordBank:['هذا','هذه','هؤلاء','ذلك'],
    explanation:'«هذا» اسم إشارة للمذكر، والكتاب مذكر، فتكون الجملة: هذا كتابُنا الجديدُ.',
    goldenRule:'اسم الإشارة للمذكر: هذا، هذه للمؤنث، هؤلاء للجمع.',
  },
  {
    id:'u1l1q15', unit:'unit1', lesson:'u1l1', page:11, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'علامات الترقيم تساعد على فهم النص. النقطة (.) تُوضع في نهاية الجملة التامة. الفاصلة (،) تُوضع:',
    paragraph:'علامات الترقيم: النقطة (.) نهاية الجملة. الفاصلة (،) بين الجمل المعطوفة. علامة الاستفهام (؟) للسؤال. (ص11)',
    options:[
      {text:'بين الجمل المعطوفة وأجزاء الجملة المتعادلة',correct:true},
      {text:'في نهاية الجملة',correct:false},
      {text:'في بداية الجملة',correct:false},
      {text:'في منتصف الكلمة',correct:false},
    ],
    explanation:'الفاصلة (،) تُفصل بين أجزاء الجملة المتعادلة أو الجمل المعطوفة.',
    goldenRule:'النقطة (.) = نهاية الجملة. الفاصلة (،) = فصل العطف. الاستفهام (؟) = سؤال.',
    feedbackQuestion:{question:'أي علامة تُوضع في نهاية جملة استفهام؟',options:[{text:'؟',correct:true},{text:'.',correct:false},{text:',',correct:false},{text:'!',correct:false}]},
  },
  {
    id:'u1l1q16', unit:'unit1', lesson:'u1l1', page:8, type:'matching',
    bloom:'remember', difficulty:'medium',
    question:'صِل كل كلمة بنوع اللام فيها:',
    paragraph:'ال شمسية: الشمس، النور. ال قمرية: القمر، الكتاب. (ص7-8)',
    pairs:[
      {left:'الشمس',right:'شمسي (تُشَدَّد)'},
      {left:'القمر',right:'قمري (يُسكَن)'},
      {left:'النور',right:'شمسي (تُشَدَّد)'},
      {left:'الكتاب',right:'قمري (يُسكَن)'},
    ],
    explanation:'الشمس، النور ← شمسية. القمر، الكتاب ← قمرية.',
    goldenRule:'افحص الحرف الأول بعد ال: شمسي ← تشديد، قمري ← تسكين.',
  },
  {
    id:'u1l1q17', unit:'unit1', lesson:'u1l1', page:10, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'في كلمة «بِير» نوع المدّ هو مدّ بالياء لأن الباء مكسورة.',
    paragraph:'مدّ الياء: بعد حرف مكسور (بِير، دِين). (ص10)',
    correctAnswer:true,
    explanation:'الباء في «بِير» مكسورة، فالياء بعدها مدّ بالياء حركتين.',
    goldenRule:'مدّ الياء = بعد حرف مكسور. مدّ الواو = بعد حرف مضموم. مدّ الألف = بعد حرف مفتوح.',
    feedbackQuestion:{question:'في كلمة «دَار» نوع المدّ هو:',options:[{text:'مدّ بالألف',correct:true},{text:'مدّ بالواو',correct:false},{text:'مدّ بالياء',correct:false},{text:'لا مدّ',correct:false}]},
  },
  {
    id:'u1l1q18', unit:'unit1', lesson:'u1l1', page:10, type:'trueFalse',
    bloom:'analyze', difficulty:'medium',
    question:'كلمة «بنت» تنتهي بتاء مفتوحة لأنها اسم مؤنث.',
    paragraph:'التاء المفتوحة (ة) تُكتب في الاسم المذكر أو المؤنث الذي يصح الوقف عليه بتاء. (ص10-11)',
    correctAnswer:false,
    explanation:'«بنت» تنتهي بتاء مفتوحة لأن الوقف عليها يبقي تاءً، لكن القاعدة العامة: الأسماء المؤنثة غالباً تنتهي بتاء مربوطة (مدرسة). «بنت» استثناء شائع.',
    goldenRule:'التاء المربوطة: في الغالب مؤنث (مدرسة). التاء المفتوحة: جمع أو فعل أو أسماء خاصة (بنات).',
    feedbackQuestion:{question:'كلمة «فاطمة» تنتهي بـ:',options:[{text:'تاء مربوطة',correct:true},{text:'تاء مفتوحة',correct:false},{text:'ألف',correct:false},{text:'هاء',correct:false}]},
  },
  {
    id:'u1l1q19', unit:'unit1', lesson:'u1l1', page:9, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'في جملة «مررتُ بنورٍ ساطعٍ»، نوع التنوين على كلمة «نورٍ» هو:',
    paragraph:'تنوين الكسر (ـٍ) يُكتب بكسرتين في آخر الاسم المجرور. (ص9)',
    options:[
      {text:'تنوين كسر (ـٍ)',correct:true},
      {text:'تنوين ضم (ـٌ)',correct:false},
      {text:'تنوين فتح (ـً)',correct:false},
      {text:'لا تنوين',correct:false},
    ],
    explanation:'«نورٍ» مجرورة بالكسر، فتنوينها تنوين كسر (ـٍ).',
    goldenRule:'تنوين الكسر (ـٍ) في الاسم المجرور. تنوين الضم (ـٌ) في المرفوع. تنوين الفتح (ـًا) في المنصوب.',
    feedbackQuestion:{question:'في جملة «جاء طالبٌ مجتهدٌ»، تنوين «طالبٌ» هو:',options:[{text:'تنوين ضم (ـٌ)',correct:true},{text:'تنوين كسر (ـٍ)',correct:false},{text:'تنوين فتح (ـًا)',correct:false},{text:'لا تنوين',correct:false}]},
  },
  {
    id:'u1l1q20', unit:'unit1', lesson:'u1l1', page:11, type:'ordering',
    bloom:'apply', difficulty:'medium',
    question:'رتّب علامات الترقيم حسب موضعها في الجملة:',
    paragraph:'علامات الترقيم: النقطة (.)، الفاصلة (،)، الاستفهام (؟). (ص11)',
    items:['النقطة في نهاية الجملة','الفاصلة بين المعطوف','الاستفهام للسؤال'],
    correctOrder:[2,1,0],
    explanation:'الترتيب: الاستفهام (؟) + الفاصلة (،) + النقطة (.).',
    goldenRule:'الترتيب المنطقي: استفهام ← فاصلة عطف ← نقطة نهاية.',
  },
  {
    id:'u1l1q21', unit:'unit1', lesson:'u1l1', page:8, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'عدد الحروف الشمسية هو:',
    paragraph:'الحروف الشمسية ١٤ حرفاً: ت د ث ر ز س ش ص ض ط ظ ل ن. (ص8)',
    options:[
      {text:'١٤ حرفاً',correct:true},
      {text:'١٣ حرفاً',correct:false},
      {text:'١٥ حرفاً',correct:false},
      {text:'١٢ حرفاً',correct:false},
    ],
    explanation:'الحروف الشمسية ١٤ حرفاً، والقمرية ١٤ حرفاً، والمجموع ٢٨ حرفاً (عدا الهمزة).',
    goldenRule:'الشمسي ١٤ + القمري ١٤ = ٢٨ حرفاً (أبجدية العربية).',
    feedbackQuestion:{question:'كم عدد الحروف القمرية؟',options:[{text:'١٤ حرفاً',correct:true},{text:'١٣ حرفاً',correct:false},{text:'١٥ حرفاً',correct:false},{text:'١٢ حرفاً',correct:false}]},
  },
  {
    id:'u1l1q22', unit:'unit1', lesson:'u1l1', page:10, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'مدّ الألف يكون بعد حرف:',
    paragraph:'مدّ الألف: بعد حرف مفتوح (دَار، قَال). (ص10)',
    options:[
      {text:'مفتوح',correct:true},
      {text:'مضموم',correct:false},
      {text:'مكسور',correct:false},
      {text:'ساكن',correct:false},
    ],
    explanation:'مدّ الألف يكون بعد حرف مفتوح، ويمدّ حركتين.',
    goldenRule:'الألف بعد فتح ← مدّ. الواو بعد ضم ← مدّ. الياء بعد كسر ← مدّ.',
    feedbackQuestion:{question:'مدّ الواو يكون بعد حرف:',options:[{text:'مضموم',correct:true},{text:'مفتوح',correct:false},{text:'مكسور',correct:false},{text:'ساكن',correct:false}]},
  },
  {
    id:'u1l1q23', unit:'unit1', lesson:'u1l1', page:11, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'في جملة «ذهبَ الطالبُ إلى المدرسةِ»، الكلمة «إلى» هي:',
    paragraph:'حروف الجر: إلى، من، عن، على، في. (ص11)',
    options:[
      {text:'حرف جر',correct:true},
      {text:'فعل',correct:false},
      {text:'اسم',correct:false},
      {text:'ضمير',correct:false},
    ],
    explanation:'«إلى» حرف جر يدل على انتهاء الغاية، وجرّ الاسم بعده.',
    goldenRule:'حروف الجر: من، إلى، عن، على، في، الباء، الكاف، اللام — تجرّ الاسم.',
    feedbackQuestion:{question:'في جملة «كتبتُ بالقلمِ»، كلمة «الباء» في «بالقلم» هي:',options:[{text:'حرف جر',correct:true},{text:'فعل',correct:false},{text:'اسم',correct:false},{text:'أداة استفهام',correct:false}]},
  },
  {
    id:'u1l1q24', unit:'unit1', lesson:'u1l1', page:9, type:'trueFalse',
    bloom:'apply', difficulty:'medium',
    question:'في كلمة «كتابٌ» (مرفوعة) نوع التنوين تنوين ضم.',
    paragraph:'تنوين الضم (ـٌ) في الاسم المرفوع. (ص9)',
    correctAnswer:true,
    explanation:'«كتابٌ» مبتدأ مرفوع بالضمة، فتنوينها تنوين ضم (ـٌ).',
    goldenRule:'المرفوع ← تنوين ضم. المنصوب ← تنوين فتح. المجرور ← تنوين كسر.',
    feedbackQuestion:{question:'في جملة «رأيتُ كتابًا»، تنوين «كتابًا» هو:',options:[{text:'تنوين فتح',correct:true},{text:'تنوين ضم',correct:false},{text:'تنوين كسر',correct:false},{text:'لا تنوين',correct:false}]},
  },
  {
    id:'u1l1q25', unit:'unit1', lesson:'u1l1', page:11, type:'fillBlank',
    bloom:'apply', difficulty:'medium',
    question:'أكمل الجملة بالكلمة المناسبة: «ذهبَ الطالبُ ___ المدرسةِ»',
    paragraph:'حروف الجر: إلى، من، عن، على. (ص11)',
    blanks:['إلى'],
    wordBank:['إلى','من','عن','على'],
    explanation:'«إلى» تدل على انتهاء الغاية: ذهب إلى المدرسة.',
    goldenRule:'إلى = انتهاء الغاية. من = ابتداء الغاية. عن = المجاوزة. على = الاستعلاء.',
  },
  {
    id:'u1l1q26', unit:'unit1', lesson:'u1l1', page:8, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'أيُّ كلمة مما يلي تحتوي على حرف قمري؟',
    paragraph:'القمرية: أ ب ج ح خ ع غ ف ق ك م ه و ي. (ص8)',
    options:[
      {text:'الحمد',correct:true},
      {text:'الشمس',correct:false},
      {text:'النجم',correct:false},
      {text:'الدر',correct:false},
    ],
    explanation:'«الحمد»: الحاء حرف قمري، فاللام تُسكَن: الحَمْد.',
    goldenRule:'القمرية: الحاء، الخاء، العين، الغين، الفاء، القاف، الكاف، الميم، الهاء، الواو، الياء، الألف، الباء، الجيم.',
    feedbackQuestion:{question:'في كلمة «الجمال»، اللام:',options:[{text:'قمري يُسكَن',correct:true},{text:'شمسي يُشَدَّد',correct:false},{text:'مفتوحة',correct:false},{text:'مكسورة',correct:false}]},
  },
  {
    id:'u1l1q27', unit:'unit1', lesson:'u1l1', page:10, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'خريطة المفردات تساعدنا على توسيع ثروتنا اللغوية. الكلمة المرتبطة بـ«معلم» في خريطة المفردات:',
    paragraph:'خريطة المفردات: معلم ← مدرسة، تلميذ، درس، علم، تعليم. (ص10)',
    options:[
      {text:'تلميذ',correct:true},
      {text:'بحر',correct:false},
      {text:'جبل',correct:false},
      {text:'قمر',correct:false},
    ],
    explanation:'«تلميذ» مرتبطة بـ«معلم» في خريطة المفردات (علاقة مهنة/متعلِّم).',
    goldenRule:'خريطة المفردات تربط الكلمة بمرادفاتها ومتعلقاتها لتوسيع المعجم.',
    feedbackQuestion:{question:'أيُّ كلمة مرتبطة بـ«كتاب» في خريطة المفردات؟',options:[{text:'مكتبة',correct:true},{text:'بحر',correct:false},{text:'نخلة',correct:false},{text:'جمل',correct:false}]},
  },
  {
    id:'u1l1q28', unit:'unit1', lesson:'u1l1', page:11, type:'classify',
    bloom:'analyze', difficulty:'hard',
    question:'صنّف الجمل: اسمية أم فعلية؟',
    paragraph:'الجملة الاسمية: مبتدأ + خبر. الجملة الفعلية: فعل + فاعل. (ص11)',
    categories:['جملة اسمية','جملة فعلية'],
    items:[
      {text:'الطالبُ مجتهدٌ',correct_category:0},
      {text:'كتبَ الطالبُ الدرسَ',correct_category:1},
      {text:'السماءُ صافيةٌ',correct_category:0},
      {text:'شربَ الطفلُ الماءَ',correct_category:1},
      {text:'المؤمنُ أخو المؤمنِ',correct_category:0},
    ],
    explanation:'الاسمية تبدأ باسم (الطالب، السماء، المؤمن). الفعلية تبدأ بفعل (كتب، شرب).',
    goldenRule:'الجملة الاسمية تبدأ باسم. الجملة الفعلية تبدأ بفعل.',
  },
  {
    id:'u1l1q29', unit:'unit1', lesson:'u1l1', page:11, type:'trueFalse',
    bloom:'evaluate', difficulty:'medium',
    question:'الجملة «ذهبَ الطالبُ إلى المدرسةِ» هي جملة فعلية لأنها تبدأ بفعل.',
    paragraph:'الجملة الفعلية: فعل + فاعل + مفعول/جار ومجرور. (ص11)',
    correctAnswer:true,
    explanation:'الجملة تبدأ بفعل «ذهبَ»، فهي جملة فعلية، فاعلها «الطالبُ».',
    goldenRule:'بداية الجملة تحدد نوعها: اسم ← اسمية، فعل ← فعلية.',
    feedbackQuestion:{question:'الجملة «النخلُ طويلٌ» هي:',options:[{text:'جملة اسمية',correct:true},{text:'جملة فعلية',correct:false},{text:'لا جملة',correct:false},{text:'جملة شرط',correct:false}]},
  },
  {
    id:'u1l1q30', unit:'unit1', lesson:'u1l1', page:10, type:'matching',
    bloom:'understand', difficulty:'medium',
    question:'صِل كل كلمة بنوع المدّ فيها:',
    paragraph:'المدّ: الألف بعد فتح، الواو بعد ضم، الياء بعد كسر. (ص10)',
    pairs:[
      {left:'قال',right:'مدّ بالألف'},
      {left:'نُور',right:'مدّ بالواو'},
      {left:'دِين',right:'مدّ بالياء'},
      {left:'بِير',right:'مدّ بالياء'},
    ],
    explanation:'قال ← ألف. نُور ← واو. دِين، بِير ← ياء.',
    goldenRule:'حركة الحرف قبل المدّ تحدد نوعه: فتح→ألف، ضم→واو، كسر→ياء.',
  },
  {
    id:'u1l1q31', unit:'unit1', lesson:'u1l1', page:11, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'الجملة الفعلية تتكوّن من:',
    paragraph:'الجملة الفعلية: فعل + فاعل (+ مفعول). (ص11)',
    options:[
      {text:'فعل + فاعل',correct:true},
      {text:'مبتدأ + خبر',correct:false},
      {text:'حرف + اسم',correct:false},
      {text:'اسم + حرف',correct:false},
    ],
    explanation:'الجملة الفعلية = فعل + فاعل (وقد يأتي مفعول أو جار ومجرور).',
    goldenRule:'الجملة الفعلية = فعل + فاعل. الجملة الاسمية = مبتدأ + خبر.',
    feedbackQuestion:{question:'الجملة الاسمية تتكوّن من:',options:[{text:'مبتدأ + خبر',correct:true},{text:'فعل + فاعل',correct:false},{text:'حرف + اسم',correct:false},{text:'فعل + حرف',correct:false}]},
  },
  {
    id:'u1l1q32', unit:'unit1', lesson:'u1l1', page:9, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف نوع التنوين على الكلمات التالية:',
    paragraph:'التنوين: ضم (ـٌ)، فتح (ـًا)، كسر (ـٍ). (ص9)',
    categories:['تنوين ضم','تنوين فتح','تنوين كسر'],
    items:[
      {text:'كتابٌ',correct_category:0},
      {text:'كتابًا',correct_category:1},
      {text:'كتابٍ',correct_category:2},
      {text:'قلمٌ',correct_category:0},
      {text:'قلمٍ',correct_category:2},
      {text:'قلمًا',correct_category:1},
    ],
    explanation:'الضمة المزدوجة ← ضم. الفتح بألف ← فتح. الكسرتان ← كسر.',
    goldenRule:'ـٌ = ضم. ـًا = فتح. ـٍ = كسر.',
  },
  {
    id:'u1l1q33', unit:'unit1', lesson:'u1l1', page:10, type:'trueFalse',
    bloom:'remember', difficulty:'easy',
    question:'مدّ الألف والواو والياء يكون بمقدار حركتين.',
    paragraph:'المدّ الأصلي: حركتان. (ص10)',
    correctAnswer:true,
    explanation:'المدّ الأصلي (الطبيعي) في الألف والواو والياء حركتان.',
    goldenRule:'المدّ الطبيعي = حركتان في الألف والواو والياء.',
    feedbackQuestion:{question:'كم حركة مدّ الألف في «قال»؟',options:[{text:'حركتان',correct:true},{text:'حركة واحدة',correct:false},{text:'ثلاث حركات',correct:false},{text:'أربع حركات',correct:false}]},
  },
  {
    id:'u1l1q34', unit:'unit1', lesson:'u1l1', page:8, type:'fillBlank',
    bloom:'apply', difficulty:'medium',
    question:'أكمل: «في كلمة النور، اللام ___ لأن النون حرف ___»',
    paragraph:'النون حرف شمسي، فاللام تُشَدَّد. (ص8)',
    blanks:['تُشَدَّد','شمسي'],
    wordBank:['تُشَدَّد','شمسي','تُسكَن','قمري'],
    explanation:'النون شمسية، فاللام تُشَدَّد وتُدمج مع النون: النُّور.',
    goldenRule:'الحرف الشمسي يُشَدَّد بعد ال. الحرف القمري يُسكَن بعده اللام.',
  },
  {
    id:'u1l1q35', unit:'unit1', lesson:'u1l1', page:11, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'أيُّ جملة مما يلي جملة اسمية؟',
    paragraph:'الاسمية: مبتدأ + خبر. الفعلية: فعل + فاعل. (ص11)',
    options:[
      {text:'العلمُ نورٌ',correct:true},
      {text:'كتبَ الطالبُ',correct:false},
      {text:'ذهبَ الرجلُ',correct:false},
      {text:'لعبَ الولدُ',correct:false},
    ],
    explanation:'«العلمُ نورٌ» تبدأ باسم (العلمُ) فخبرها (نورٌ) = جملة اسمية.',
    goldenRule:'الجملة الاسمية تبدأ باسم مرفوع (مبتدأ) ويأتي بعده الخبر.',
    feedbackQuestion:{question:'أيُّ جملة مما يلي جملة فعلية؟',options:[{text:'قرأَ الطالبُ الكتابَ',correct:true},{text:'الكتابُ مفيدٌ',correct:false},{text:'الماءُ باردٌ',correct:false},{text:'النخلُ طويلٌ',correct:false}]},
  },
];

export const U1L2_QS = [
  {
    id:'u1l2q1', unit:'unit1', lesson:'u1l2', page:12, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'فنّ الخط العربي من الفنون الإسلامية العريقة. الخط النسخي هو الخط الذي يُكتب به:',
    paragraph:'الخط النسخي: الخط الذي تُكتب به المصاحف والكتب. (ص12)',
    options:[
      {text:'المصاحف والكتب',correct:true},
      {text:'العملات فقط',correct:false},
      {text:'اللافتات فقط',correct:false},
      {text:'الرسائل الإلكترونية',correct:false},
    ],
    explanation:'الخط النسخي يُستعمل لكتابة المصاحف والكتب لوضوحه وجماله.',
    goldenRule:'الخط النسخي = خط المصاحف والكتب — واضح ومقروء.',
    feedbackQuestion:{question:'أيُّ خط يُستعمل لكتابة المصاحف؟',options:[{text:'النسخي',correct:true},{text:'الكوفي',correct:false},{text:'الرقعي',correct:false},{text:'الديواني',correct:false}]},
  },
  {
    id:'u1l2q2', unit:'unit1', lesson:'u1l2', page:12, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'يحتوي الخط النسخي على أربعة أسطر رئيسة: الخط الأساس، خط الصورة، الخط العلوي، الخط السفلي. الخط الذي تجلس عليه معظم الحروف هو:',
    paragraph:'أسطر الخط النسخي: خط الأساس (السطر السفلي للجلوس)، خط الصورة (المنتصف)، الخط العلوي (ارتفاع الألف)، الخط السفلي (امتداد الحروف). (ص12-13)',
    options:[
      {text:'خط الأساس',correct:true},
      {text:'خط الصورة',correct:false},
      {text:'الخط العلوي',correct:false},
      {text:'الخط السفلي',correct:false},
    ],
    explanation:'خط الأساس هو السطر الذي تجلس عليه معظم الحروف (ب، ت، ث، ج...).',
    goldenRule:'أسطر الخط الأربعة: الأساس (جلوس) + الصورة (وسط) + العلوي (ارتفاع) + السفلي (امتداد).',
    feedbackQuestion:{question:'أيُّ خط يحدد ارتفاع الألف واللام؟',options:[{text:'الخط العلوي',correct:true},{text:'خط الأساس',correct:false},{text:'الخط السفلي',correct:false},{text:'خط الصورة',correct:false}]},
  },
  {
    id:'u1l2q3', unit:'unit1', lesson:'u1l2', page:13, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'الحرف (ج) في الخط النسخي يجلس على خط الأساس.',
    paragraph:'الحروف الجالسة على خط الأساس: ب، ت، ث، ج، ح، خ، س، ش، ص، ض، ط، ظ، ع، غ، ف، ق، ك، م، ن، ه، و، ي. (ص13)',
    correctAnswer:true,
    explanation:'(ج) يجلس على خط الأساس ولا ينزل عنه ولا يرتفع فوق خط الصورة.',
    goldenRule:'معظم الحروف العربية تجلس على خط الأساس في الخط النسخي.',
    feedbackQuestion:{question:'الحرف (د) في الخط النسخي:',options:[{text:'يجلس على خط الأساس',correct:true},{text:'ينزل تحت الخط السفلي',correct:false},{text:'يرتفع فوق العلوي',correct:false},{text:'يطفو في المنتصف',correct:false}]},
  },
  {
    id:'u1l2q4', unit:'unit1', lesson:'u1l2', page:13, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف الحروف حسب موقعها في الخط النسخي:',
    paragraph:'الحروف الراقية (تصل الخط العلوي): أ، ل، ك، ط، ظ. الحروف النازلة (تنزل تحت الأساس): ج، ح، خ، ع، غ، م. الحروف الجالسة: ب، ت، ث، س، ش. (ص13)',
    categories:['راقية (خط علوي)','نازلة (تحت الأساس)','جالسة (خط الأساس)'],
    items:[
      {text:'الألف',correct_category:0},
      {text:'الجيم',correct_category:1},
      {text:'الباء',correct_category:2},
      {text:'اللام',correct_category:0},
      {text:'العين',correct_category:1},
      {text:'السين',correct_category:2},
    ],
    explanation:'الراقية: أ، ل. النازلة: ج، ع. الجالسة: ب، س.',
    goldenRule:'الحروف الراقية تصل العلوي. النازلة تهبط تحت الأساس. الجالسة تستوي على الأساس.',
  },
  {
    id:'u1l2q5', unit:'unit1', lesson:'u1l2', page:12, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'خط الصورة في الخط النسخي هو الخط الذي:',
    paragraph:'خط الصورة: الخط الأوسط الذي تحدد به صورة الحرف (حجم الحرف الدائري مثل ع، غ، ه). (ص13)',
    options:[
      {text:'يحدد صورة الحرف ومستواه الأوسط',correct:true},
      {text:'يحدد ارتفاع الألف',correct:false},
      {text:'يحدد امتداد النازلة',correct:false},
      {text:'يحدد قاعدة الجلوس',correct:false},
    ],
    explanation:'خط الصورة يحدد الحجم الأوسط للحروف الدائرية (ع، غ، ه) ومستواها.',
    goldenRule:'خط الصورة = المستوى الأوسط للحرف — يحدد حجم الحروف الدائرية.',
    feedbackQuestion:{question:'أيُّ حرف يحدد حجمه خط الصورة بشكل واضح؟',options:[{text:'العين',correct:true},{text:'الألف',correct:false},{text:'الباء',correct:false},{text:'النون',correct:false}]},
  },
  {
    id:'u1l2q6', unit:'unit1', lesson:'u1l2', page:13, type:'trueFalse',
    bloom:'remember', difficulty:'easy',
    question:'الحرف (ر) في الخط النسخي يجلس على خط الأساس ولا ينزل تحته.',
    paragraph:'الحروف الجالسة على خط الأساس: ر، د، و، ا. (ص13)',
    correctAnswer:true,
    explanation:'(ر) يجلس على خط الأساس ولا يهبط تحته ولا يرتفع فوق خط الصورة كثيراً.',
    goldenRule:'(ر) و(د) حرفان جالسان على خط الأساس في الخط النسخي.',
    feedbackQuestion:{question:'الحرف (و) في الخط النسخي:',options:[{text:'يجلس على خط الأساس',correct:true},{text:'يرتفع للخط العلوي',correct:false},{text:'ينزل للخط السفلي',correct:false},{text:'يطفو فوق الصورة',correct:false}]},
  },
  {
    id:'u1l2q7', unit:'unit1', lesson:'u1l2', page:12, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'عدد الأسطر الرئيسة في الخط النسخي:',
    paragraph:'أسطر الخط النسخي: ١) الأساس ٢) الصورة ٣) العلوي ٤) السفلي. (ص12-13)',
    options:[
      {text:'أربعة أسطر',correct:true},
      {text:'خمسة أسطر',correct:false},
      {text:'ثلاثة أسطر',correct:false},
      {text:'ستة أسطر',correct:false},
    ],
    explanation:'الأسطر الأربعة: الأساس، الصورة، العلوي، السفلي.',
    goldenRule:'أسطر النسخي أربعة: أساس + صورة + علوي + سفلي.',
    feedbackQuestion:{question:'أيُّ خط من هذه أسطر النسخي الأربعة؟',options:[{text:'خط الأساس',correct:true},{text:'خط الرأس',correct:false},{text:'خط الذيل',correct:false},{text:'خط القاعدة',correct:false}]},
  },
  {
    id:'u1l2q8', unit:'unit1', lesson:'u1l2', page:13, type:'matching',
    bloom:'understand', difficulty:'medium',
    question:'صِل كل خط بوظيفته:',
    paragraph:'الأسطر: الأساس (جلوس)، الصورة (أوسط)، العلوي (ارتفاع)، السفلي (امتداد). (ص12-13)',
    pairs:[
      {left:'خط الأساس',right:'جلوس معظم الحروف'},
      {left:'خط الصورة',right:'تحديد صورة الحرف الأوسط'},
      {left:'الخط العلوي',right:'ارتفاع الألف واللام'},
      {left:'الخط السفلي',right:'امتداد الحروف النازلة'},
    ],
    explanation:'الأساس: جلوس. الصورة: أوسط. العلوي: ارتفاع. السفلي: امتداد.',
    goldenRule:'كل خط له وظيفة: جلوس، أوسط، ارتفاع، امتداد.',
  },
  {
    id:'u1l2q9', unit:'unit1', lesson:'u1l2', page:13, type:'trueFalse',
    bloom:'understand', difficulty:'medium',
    question:'الحرف (ك) من الحروف الراقية التي تصل الخط العلوي في الخط النسخي.',
    paragraph:'الحروف الراقية: ا، ل، ك، ط، ظ، ف (في بعض الصور). (ص13)',
    correctAnswer:true,
    explanation:'(ك) يرتفع كتفه حتى يصل الخط العلوي مثل الألف واللام.',
    goldenRule:'الراقية في النسخي: ا، ل، ك، ط، ظ — تصل الخط العلوي.',
    feedbackQuestion:{question:'الحرف (ط) في الخط النسخي:',options:[{text:'يرتفع للخط العلوي',correct:true},{text:'يجلس على الأساس',correct:false},{text:'ينزل للسفلي',correct:false},{text:'يطفو في الصورة',correct:false}]},
  },
  {
    id:'u1l2q10', unit:'unit1', lesson:'u1l2', page:13, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف الحروف: راقية أم نازلة أم جالسة؟',
    paragraph:'الراقية: ا ل ك ط ظ. النازلة: ج ح خ ع غ م ن (في بعض الصور). الجالسة: ب ت ث س ش ص د ر و. (ص13)',
    categories:['راقية','نازلة','جالسة'],
    items:[
      {text:'الألف',correct_category:0},
      {text:'الحاء',correct_category:1},
      {text:'الدال',correct_category:2},
      {text:'الكاف',correct_category:0},
      {text:'الخاء',correct_category:1},
      {text:'الراء',correct_category:2},
    ],
    explanation:'الراقية: ا، ك. النازلة: ح، خ. الجالسة: د، ر.',
    goldenRule:'الراقية تصل العلوي. النازلة تهبط تحت الأساس. الجالسة تستوي على الأساس.',
  },
  {
    id:'u1l2q11', unit:'unit1', lesson:'u1l2', page:12, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'أهم ما يميز الخط النسخي ويجعله مناسبًا لكتابة المصاحف:',
    paragraph:'الخط النسخي: وضوح، دقة، تجانس، سهولة القراءة. (ص12)',
    options:[
      {text:'وضوحه وسهولة قراءته',correct:true},
      {text:'كثرة زخارفه',correct:false},
      {text:'صعوبة قراءته',correct:false},
      {text:'كبر حجم حروفه',correct:false},
    ],
    explanation:'الخط النسخي واضح ومقروء، لذا يُستعمل في المصاحف والكتب.',
    goldenRule:'النسخي = وضوح + دقة + تجانس = مناسب للقراءة الطويلة.',
    feedbackQuestion:{question:'لماذا يُفضَّل النسخي لكتابة الكتب؟',options:[{text:'لوضوحه وسهولة قراءته',correct:true},{text:'لجماله فقط',correct:false},{text:'لصعوبته',correct:false},{text:'لكثرة زخارفه',correct:false}]},
  },
  {
    id:'u1l2q12', unit:'unit1', lesson:'u1l2', page:13, type:'trueFalse',
    bloom:'remember', difficulty:'easy',
    question:'الحرف (ن) في الخط النسخي ينزل جزؤه السفلي تحت خط الأساس.',
    paragraph:'الحروف النازلة: ج ح خ ع غ ن م (لها أجزاء نازلة). (ص13)',
    correctAnswer:true,
    explanation:'(ن) لها جزء دائري ينزل تحت خط الأساس في الخط النسخي.',
    goldenRule:'(ن) و(م) و(ع) و(غ) حروف نازلة لها أجزاء تحت الأساس.',
    feedbackQuestion:{question:'أيُّ حرف ينزل جزؤه تحت الأساس؟',options:[{text:'العين',correct:true},{text:'الألف',correct:false},{text:'الدال',correct:false},{text:'الراء',correct:false}]},
  },
  {
    id:'u1l2q13', unit:'unit1', lesson:'u1l2', page:13, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'الحرف (ه) في الخط النسخي في وسط الكلمة يُكتب على شكل:',
    paragraph:'(ه) وسط الكلمة: تشبه العين المقلوبة، تجلس على خط الصورة. (ص13)',
    options:[
      {text:'دائرة على خط الصورة',correct:true},
      {text:'خط عمودي على الخط العلوي',correct:false},
      {text:'خط أفقي على الأساس',correct:false},
      {text:'نقطة تحت السفلي',correct:false},
    ],
    explanation:'(ه) وسط الكلمة تأخذ شكلاً دائرياً على خط الصورة.',
    goldenRule:'شكل الحرف يتغير حسب موقعه (أول، وسط، آخر) في الخط النسخي.',
    feedbackQuestion:{question:'شكل الحرف في الخط النسخي يتغير حسب:',options:[{text:'موقعه في الكلمة',correct:true},{text:'لون القلم',correct:false},{text:'نوع الورق',correct:false},{text:'حجم الخط',correct:false}]},
  },
  {
    id:'u1l2q14', unit:'unit1', lesson:'u1l2', page:13, type:'ordering',
    bloom:'apply', difficulty:'medium',
    question:'رتّب أسطر الخط النسخي من الأعلى إلى الأسفل:',
    paragraph:'الأسطر: علوي، صورة، أساس، سفلي. (ص12-13)',
    items:['خط الأساس','الخط العلوي','الخط السفلي','خط الصورة'],
    correctOrder:[1,3,0,2],
    explanation:'من الأعلى: العلوي ← الصورة ← الأساس ← السفلي.',
    goldenRule:'ترتيب الأسطر من الأعلى: علوي ← صورة ← أساس ← سفلي.',
  },
  {
    id:'u1l2q15', unit:'unit1', lesson:'u1l2', page:12, type:'fillBlank',
    bloom:'apply', difficulty:'medium',
    question:'أكمل: «الخط ___ هو الخط الذي تُكتب به المصاحف والكتب»',
    paragraph:'الخط النسخي = خط المصاحف والكتب. (ص12)',
    blanks:['النسخي'],
    wordBank:['النسخي','الكوفي','الرقعي','الديواني'],
    explanation:'الخط النسخي هو خط المصاحف والكتب لوضوحه.',
    goldenRule:'النسخي = المصاحف والكتب. الكوفي = الزخرفة والنقوش.',
  },
  {
    id:'u1l2q16', unit:'unit1', lesson:'u1l2', page:13, type:'trueFalse',
    bloom:'understand', difficulty:'medium',
    question:'الحرف (ص) في الخط النسخي يجلس على خط الأساس وله قوس يصل خط الصورة.',
    paragraph:'(ص): حرف جالس على الأساس، قوسه يرتفع حتى خط الصورة. (ص13)',
    correctAnswer:true,
    explanation:'(ص) يجلس على الأساس وقوسه يصل الصورة.',
    goldenRule:'(ص) و(ض) حرفان جالسان، قوسهما يرتفع للصورة.',
    feedbackQuestion:{question:'الحرف (ض) في الخط النسخي:',options:[{text:'جالس على الأساس، قوسه يصل الصورة',correct:true},{text:'نازل تحت السفلي',correct:false},{text:'راقٍ للعلوي',correct:false},{text:'يطفو في الصورة',correct:false}]},
  },
  {
    id:'u1l2q17', unit:'unit1', lesson:'u1l2', page:12, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'الخط الذي يُستعمل في زخرفة المساجد والقصور والعملات القديمة هو:',
    paragraph:'الخط الكوفي: خط الزخرفة والنقوش على الجدران والعملات. (ص12)',
    options:[
      {text:'الخط الكوفي',correct:true},
      {text:'الخط النسخي',correct:false},
      {text:'الخط الرقعي',correct:false},
      {text:'الخط الديواني',correct:false},
    ],
    explanation:'الخط الكوفي يُستعمل في الزخرفة لطابعه الهندسي الجميل.',
    goldenRule:'الكوفي = زخرفة وجدران. النسخي = مصاحف وكتب. الرقعي = مراسلات.',
    feedbackQuestion:{question:'أيُّ خط يُستعمل في كتابة المصاحف؟',options:[{text:'النسخي',correct:true},{text:'الكوفي',correct:false},{text:'الرقعي',correct:false},{text:'الديواني',correct:false}]},
  },
  {
    id:'u1l2q18', unit:'unit1', lesson:'u1l2', page:13, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'الحرف (ل) في الخط النسخي يرتفع حتى:',
    paragraph:'(ل): حرف راقٍ يصل الخط العلوي، ويجلس قاعدته على خط الأساس. (ص13)',
    options:[
      {text:'الخط العلوي',correct:true},
      {text:'الخط السفلي',correct:false},
      {text:'خط الصورة فقط',correct:false},
      {text:'تحت خط الأساس',correct:false},
    ],
    explanation:'(ل) حرف راقٍ، قمته تصل الخط العلوي وقاعدته على الأساس.',
    goldenRule:'(ل) و(ا) و(ك) و(ط) حروف راقية تصل الخط العلوي.',
    feedbackQuestion:{question:'الحرف (ا) في الخط النسخي يصل:',options:[{text:'الخط العلوي',correct:true},{text:'خط الصورة',correct:false},{text:'الخط السفلي',correct:false},{text:'خط الأساس فقط',correct:false}]},
  },
  {
    id:'u1l2q19', unit:'unit1', lesson:'u1l2', page:13, type:'classify',
    bloom:'analyze', difficulty:'hard',
    question:'صنّف الحروف حسب ارتفاعها في الخط النسخي:',
    paragraph:'الراقية: ا ل ك ط ظ. النازلة: ج ح خ ع غ. الجالسة: ب ت ث د ر س ش ص ض ع. (ص13)',
    categories:['رافعة رأسها','خافضة رأسها','مستوية'],
    items:[
      {text:'الألف',correct_category:0},
      {text:'الجيم',correct_category:1},
      {text:'الباء',correct_category:2},
      {text:'الطاء',correct_category:0},
      {text:'الخاء',correct_category:1},
      {text:'الراء',correct_category:2},
    ],
    explanation:'رافعة: ا، ط. خافضة: ج، خ. مستوية: ب، ر.',
    goldenRule:'رافعة ← علوي. خافضة ← سفلي. مستوية ← أساس.',
  },
  {
    id:'u1l2q20', unit:'unit1', lesson:'u1l2', page:13, type:'trueFalse',
    bloom:'evaluate', difficulty:'medium',
    question:'جمال الخط النسخي يعتمد على ضبط المسافات بين الحروف والكلمات.',
    paragraph:'ضبط المسافات: من أهم عناصر جمال الخط النسخي. (ص13)',
    correctAnswer:true,
    explanation:'جمال الخط يتحقق بضبط المسافات وتساوي ارتفاع الحروف الراقية وامتداد النازلة.',
    goldenRule:'جمال الخط = ضبط المسافات + تساوي الارتفاع + وضوح الحروف.',
    feedbackQuestion:{question:'ما أهم عنصر في جمال الخط النسخي؟',options:[{text:'ضبط المسافات والارتفاع',correct:true},{text:'كثرة الزخرفة',correct:false},{text:'كبر الحروف',correct:false},{text:'لون الحبر',correct:false}]},
  },
  {
    id:'u1l2q21', unit:'unit1', lesson:'u1l2', page:13, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'الحرف (ظ) في الخط النسخي:',
    paragraph:'(ظ): حرف راقٍ، قمته تصل الخط العلوي، وقاعدته على الأساس. (ص13)',
    options:[
      {text:'يرتفع للخط العلوي',correct:true},
      {text:'ينزل للخط السفلي',correct:false},
      {text:'يجلس على الصورة فقط',correct:false},
      {text:'يطفو فوق العلوي',correct:false},
    ],
    explanation:'(ظ) حرف راقٍ مثل (ط) يصل قمته الخط العلوي.',
    goldenRule:'(ط) و(ظ) حرفان راقيان يصلان الخط العلوي.',
    feedbackQuestion:{question:'الحرف (ط) في الخط النسخي يصل:',options:[{text:'الخط العلوي',correct:true},{text:'خط الصورة',correct:false},{text:'الخط السفلي',correct:false},{text:'خط الأساس',correct:false}]},
  },
  {
    id:'u1l2q22', unit:'unit1', lesson:'u1l2', page:13, type:'fillBlank',
    bloom:'apply', difficulty:'medium',
    question:'أكمل: «الحرف (ل) في الخط النسخي يصل الخط ___ وقاعدته على خط ___»',
    paragraph:'(ل): راقٍ يصل العلوي، قاعدته على الأساس. (ص13)',
    blanks:['العلوي','الأساس'],
    wordBank:['العلوي','الأساس','السفلي','الصورة'],
    explanation:'(ل) يصل الخط العلوي وقاعدته على خط الأساس.',
    goldenRule:'الحروف الراقية: قمتها العلوي وقاعدتها الأساس.',
  },
  {
    id:'u1l2q23', unit:'unit1', lesson:'u1l2', page:12, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'الخط الكوفي يتميز عن الخط النسخي بأنه:',
    paragraph:'الكوفي: حروفه زاويّة صلبة، يُستعمل في الزخرفة. النسخي: حروفه منحنية، يُستعمل في الكتابة. (ص12)',
    options:[
      {text:'حروفه زاويّة صلبة تصلح للزخرفة',correct:true},
      {text:'حروفه منحنية تصلح للكتب',correct:false},
      {text:'يُكتب به المصاحف',correct:false},
      {text:'سهل القراءة',correct:false},
    ],
    explanation:'الكوفي حروفه زاويّة صلبة تناسب الزخرفة، بينما النسخي منحنٍ مناسب للقراءة.',
    goldenRule:'الكوفي = زوايا صلبة للزخرفة. النسخي = انحناءات للقراءة.',
    feedbackQuestion:{question:'ما الذي يميز الخط النسخي عن الكوفي؟',options:[{text:'حروفه منحنية وسهلة القراءة',correct:true},{text:'حروفه زاويّة',correct:false},{text:'يُستعمل للزخرفة',correct:false},{text:'صعب القراءة',correct:false}]},
  },
  {
    id:'u1l2q24', unit:'unit1', lesson:'u1l2', page:13, type:'matching',
    bloom:'understand', difficulty:'medium',
    question:'صِل كل حرف بموقعه في الخط النسخي:',
    paragraph:'الراقية: ا ل ك ط. النازلة: ج ح خ. الجالسة: ب د ر. (ص13)',
    pairs:[
      {left:'الألف',right:'راقٍ يصل العلوي'},
      {left:'الجيم',right:'نازل تحت الأساس'},
      {left:'الباء',right:'جالس على الأساس'},
      {left:'الكاف',right:'راقٍ يصل العلوي'},
    ],
    explanation:'الألف والكاف ← راقيان. الجيم ← نازل. الباء ← جالس.',
    goldenRule:'كل حرف له موقع محدد في أسطر النسخي الأربعة.',
  },
  {
    id:'u1l2q25', unit:'unit1', lesson:'u1l2', page:13, type:'trueFalse',
    bloom:'remember', difficulty:'easy',
    question:'الحرف (م) في الخط النسخي ينزل جزؤه الدائري تحت خط الأساس.',
    paragraph:'(م): حرف نازل، جزؤه الدائري يهبط تحت الأساس. (ص13)',
    correctAnswer:true,
    explanation:'(م) كالحرف (ن) له جزء دائري ينزل تحت خط الأساس.',
    goldenRule:'(م) و(ن) حرفان نازلان، أجزاؤهما الدائرية تحت الأساس.',
    feedbackQuestion:{question:'أيُّ حرف ينزل جزؤه تحت الأساس؟',options:[{text:'الميم',correct:true},{text:'الألف',correct:false},{text:'الدال',correct:false},{text:'الراء',correct:false}]},
  },
  {
    id:'u1l2q26', unit:'unit1', lesson:'u1l2', page:12, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'الخط النسخي سُمِّي بهذا الاسم لأنه:',
    paragraph:'النسخي: من النسخ، أي استنساخ الكتب والمصاحف. (ص12)',
    options:[
      {text:'يُستعمل في نسخ الكتب والمصاحف',correct:true},
      {text:'يُكتب به النقوش على الجدران',correct:false},
      {text:'يُستعمل في المراسلات',correct:false},
      {text:'يُكتب به الشعر فقط',correct:false},
    ],
    explanation:'سُمِّي نسخياً لأنه يُستعمل في نسخ الكتب والمصاحف لوضوحه.',
    goldenRule:'النسخي = نسخ الكتب والمصاحف — من هنا جاء اسمه.',
    feedbackQuestion:{question:'لماذا سُمِّي الخط النسخي بهذا الاسم؟',options:[{text:'لأنه يُستعمل في نسخ الكتب',correct:true},{text:'لأنه يُكتب على الجدران',correct:false},{text:'لأنه صعب',correct:false},{text:'لأنه قديم',correct:false}]},
  },
  {
    id:'u1l2q27', unit:'unit1', lesson:'u1l2', page:13, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'الحرف (ف) في الخط النسخي:',
    paragraph:'(ف): حرف راقٍ يصل الخط العلوي، له نقطة فوقه، وقاعدته على الأساس. (ص13)',
    options:[
      {text:'يرتفع للخط العلوي',correct:true},
      {text:'ينزل للخط السفلي',correct:false},
      {text:'يجلس على الصورة فقط',correct:false},
      {text:'يطفو فوق العلوي',correct:false},
    ],
    explanation:'(ف) حرف راقٍ يصل الخط العلوي مثل القاف.',
    goldenRule:'(ف) و(ق) حرفان راقيان يصلان الخط العلوي.',
    feedbackQuestion:{question:'الحرف (ق) في الخط النسخي يصل:',options:[{text:'الخط العلوي',correct:true},{text:'خط الصورة',correct:false},{text:'الخط السفلي',correct:false},{text:'خط الأساس',correct:false}]},
  },
  {
    id:'u1l2q28', unit:'unit1', lesson:'u1l2', page:13, type:'trueFalse',
    bloom:'apply', difficulty:'medium',
    question:'الحرف (ي) في الخط النسخي يجلس على خط الأساس ولا ينزل تحته.',
    paragraph:'(ي): حرف جالس على الأساس، له نقطتان تحته. (ص13)',
    correctAnswer:true,
    explanation:'(ي) يجلس على خط الأساس ولا يهبط تحته.',
    goldenRule:'(ي) و(ب) و(ت) و(ث) حروف جالسة على الأساس.',
    feedbackQuestion:{question:'الحرف (ت) في الخط النسخي:',options:[{text:'يجلس على الأساس',correct:true},{text:'يرتفع للعلوي',correct:false},{text:'ينزل للسفلي',correct:false},{text:'يطفو في الصورة',correct:false}]},
  },
  {
    id:'u1l2q29', unit:'unit1', lesson:'u1l2', page:13, type:'classify',
    bloom:'analyze', difficulty:'hard',
    question:'صنّف الحروف: نقطة فوق أم نقطتان تحت أم بلا نقطة؟',
    paragraph:'نقطة فوق: ف ق ن ب ت ث خ ج ي. نقطتان تحت: ي. بلا نقطة: ا ل د ر س ص ط ع م ه و. (ص13)',
    categories:['نقطة فوق','نقطتان تحت','بلا نقطة'],
    items:[
      {text:'الباء',correct_category:0},
      {text:'الياء',correct_category:1},
      {text:'الألف',correct_category:2},
      {text:'النون',correct_category:0},
      {text:'الدال',correct_category:2},
      {text:'التاء',correct_category:0},
    ],
    explanation:'فوق: ب، ن، ت. تحت: ي. بلا: ا، د.',
    goldenRule:'النقطة تميز الحروف المتشابهة في الخط النسخي.',
  },
  {
    id:'u1l2q30', unit:'unit1', lesson:'u1l2', page:13, type:'ordering',
    bloom:'apply', difficulty:'medium',
    question:'رتّب خطوات كتابة الحرف (ع) في الخط النسخي:',
    paragraph:'(ع): حرف نازل، يُكتب من الأعلى (الرأس) ثم ينزل للجسم الدائري. (ص13)',
    items:['نزول الجزء الدائري تحت الأساس','رسم الرأس على الصورة','النقطة فوق'],
    correctOrder:[1,0,2],
    explanation:'الترتيب: الرأس على الصورة ← الجزء الدائري تحت الأساس ← النقطة فوق.',
    goldenRule:'كتابة الحرف تبدأ من الأعلى إلى الأسفل في الخط النسخي.',
  },
  {
    id:'u1l2q31', unit:'unit1', lesson:'u1l2', page:12, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'أيُّ خط من التالي يُستعمل في كتابة المراسلات اليومية؟',
    paragraph:'الخط الرقعي: خط المراسلات اليومية، سريع الكتابة. (ص12)',
    options:[
      {text:'الخط الرقعي',correct:true},
      {text:'الخط الكوفي',correct:false},
      {text:'الخط الديواني',correct:false},
      {text:'الخط النسخي',correct:false},
    ],
    explanation:'الرقعي يُستعمل في المراسلات اليومية لسرعته وسهولته.',
    goldenRule:'الرقعي = مراسلات. النسخي = مصاحف وكتب. الكوفي = زخرفة. الديواني = وثائق رسمية.',
    feedbackQuestion:{question:'أيُّ خط يُستعمل في الزخرفة والنقوش؟',options:[{text:'الكوفي',correct:true},{text:'الرقعي',correct:false},{text:'النسخي',correct:false},{text:'الديواني',correct:false}]},
  },
  {
    id:'u1l2q32', unit:'unit1', lesson:'u1l2', page:13, type:'trueFalse',
    bloom:'understand', difficulty:'medium',
    question:'الحرف (ض) في الخط النسخي حرف جالس له قوس يرتفع إلى خط الصورة.',
    paragraph:'(ض): جالس على الأساس، قوسه يصل الصورة، له نقطة فوق. (ص13)',
    correctAnswer:true,
    explanation:'(ض) يجلس على الأساس وقوسه يرتفع حتى خط الصورة.',
    goldenRule:'(ض) و(ص) حرفان جالسان، قوسهما يصل الصورة.',
    feedbackQuestion:{question:'الحرف (ص) في الخط النسخي:',options:[{text:'جالس، قوسه يصل الصورة',correct:true},{text:'نازل تحت السفلي',correct:false},{text:'راقٍ للعلوي',correct:false},{text:'يطفو في الصورة',correct:false}]},
  },
  {
    id:'u1l2q33', unit:'unit1', lesson:'u1l2', page:13, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'الحرف (د) في الخط النسخي:',
    paragraph:'(د): حرف جالس على خط الأساس، بلا نقطة، على شكل حلقة صغيرة. (ص13)',
    options:[
      {text:'يجلس على خط الأساس بلا نقطة',correct:true},
      {text:'يرتفع للخط العلوي',correct:false},
      {text:'ينزل للخط السفلي',correct:false},
      {text:'يطفو في الصورة',correct:false},
    ],
    explanation:'(د) جالس على الأساس، بلا نقطة، يشبه حلقة صغيرة ملتصقة.',
    goldenRule:'(د) جالس بلا نقطة. (ذ) مثله但有 نقطة فوق.',
    feedbackQuestion:{question:'الحرف (ذ) في الخط النسخي:',options:[{text:'جالس على الأساس مع نقطة فوق',correct:true},{text:'يرتفع للعلوي',correct:false},{text:'ينزل للسفلي',correct:false},{text:'بلا نقطة',correct:false}]},
  },
  {
    id:'u1l2q34', unit:'unit1', lesson:'u1l2', page:12, type:'fillBlank',
    bloom:'apply', difficulty:'medium',
    question:'أكمل: «الخط النسخي يحتوي على ___ أسطر رئيسة»',
    paragraph:'أسطر النسخي: أربعة. (ص12-13)',
    blanks:['أربعة'],
    wordBank:['أربعة','ثلاثة','خمسة','ستة'],
    explanation:'الأسطر الأربعة: الأساس، الصورة، العلوي، السفلي.',
    goldenRule:'أسطر النسخي = ٤ (أساس + صورة + علوي + سفلي).',
  },
  {
    id:'u1l2q35', unit:'unit1', lesson:'u1l2', page:13, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'لماذا يعتبر خط الأساس من أهم أسطر الخط النسخي؟',
    paragraph:'خط الأساس: تجلس عليه معظم الحروف، ويحدد استقامة الكتابة. (ص12-13)',
    options:[
      {text:'لأن معظم الحروف تجلس عليه ويحدد استقامة الكتابة',correct:true},
      {text:'لأنه أطول خط',correct:false},
      {text:'لأنه أعلى خط',correct:false},
      {text:'لأنه أجمل خط',correct:false},
    ],
    explanation:'خط الأساس يجلس عليه معظم الحروف، ويحدد استقامة الأسطر.',
    goldenRule:'خط الأساس = قاعدة الكتابة، عليه تجلس الحروف، ويحدد استقامة السطر.',
    feedbackQuestion:{question:'ما أهمية خط الصورة في النسخي؟',options:[{text:'يحدد صورة الحرف الأوسط',correct:true},{text:'يحدد ارتفاع الألف',correct:false},{text:'يحدد امتداد النازلة',correct:false},{text:'يحدد قاعدة الجلوس',correct:false}]},
  },
];

export const U1L3_QS = [
  {
    id:'u1l3q1', unit:'unit1', lesson:'u1l3', page:15, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'من الصفات الحميدة التي يجب أن يتحلى بها الإنسان في تعامله مع الآخرين:',
    paragraph:'الصفات الحميدة: الصدق، الأمانة، احترام الآخرين، التعاون، العدل. (ص15)',
    options:[
      {text:'الصدق والأمانة',correct:true},
      {text:'الكذب والخيانة',correct:false},
      {text:'الأنانية والحسد',correct:false},
      {text:'الغش والظلم',correct:false},
    ],
    explanation:'الصدق والأمانة من الصفات الحميدة التي يقوي بها الإنسان علاقته مع الآخرين.',
    goldenRule:'الصفات الحميدة = صدق + أمانة + تعاون + عدل + احترام.',
    feedbackQuestion:{question:'أيٌّ مما يلي صفة ذميمة؟',options:[{text:'الكذب',correct:true},{text:'الصدق',correct:false},{text:'الأمانة',correct:false},{text:'العدل',correct:false}]},
  },
  {
    id:'u1l3q2', unit:'unit1', lesson:'u1l3', page:15, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'احترام الكبير والعطف على الصغير من الصفات الحميدة.',
    paragraph:'الصفات الحميدة: احترام الكبير، العطف على الصغير، مساعدة المحتاج. (ص15)',
    correctAnswer:true,
    explanation:'احترام الكبير والعطف على الصغير من الصفات الحميدة التي يُثاب عليها الإنسان.',
    goldenRule:'احترام الكبير + عطف الصغير + مساعدة المحتاج = صفات حميدة.',
    feedbackQuestion:{question:'الأنانية وعدم الاكتراث بالآخرين هي:',options:[{text:'صفة ذميمة',correct:true},{text:'صفة حميدة',correct:false},{text:'مطلوبة',correct:false},{text:'لا شيء',correct:false}]},
  },
  {
    id:'u1l3q3', unit:'unit1', lesson:'u1l3', page:15, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف الصفات: حميدة أم ذميمة؟',
    paragraph:'الحميدة: صدق، أمانة، تعاون، إخلاص، احترام. الذميمة: كذب، خيانة، أنانية، حسد، غش. (ص15)',
    categories:['صفة حميدة ✅','صفة ذميمة ❌'],
    items:[
      {text:'الصدق',correct_category:0},
      {text:'الكذب',correct_category:1},
      {text:'الأمانة',correct_category:0},
      {text:'الخيانة',correct_category:1},
      {text:'التعاون',correct_category:0},
      {text:'الأنانية',correct_category:1},
    ],
    explanation:'الحميدة: صدق، أمانة، تعاون. الذميمة: كذب، خيانة، أنانية.',
    goldenRule:'الحميدة تبني العلاقات. الذميمة تهدّمها.',
  },
  {
    id:'u1l3q4', unit:'unit1', lesson:'u1l3', page:15, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'في صورة طالب يكتب عن إعلان لجمعيات الإحسان، القيمة التي يكتسبها الطالب من هذا النشاط:',
    paragraph:'النشاط: إعداد حملة توعية بجمعيات الإحسان لخدمة المجتمع. (ص15)',
    options:[
      {text:'الإحسان والعطاء ومساعدة المحتاجين',correct:true},
      {text:'الأنانية وحب الذات',correct:false},
      {text:'الكسل والإهمال',correct:false},
      {text:'التبذير والإسراف',correct:false},
    ],
    explanation:'إعداد حملة لجمعيات الإحسان يغرس في الطالب قيمة الإحسان والعطاء.',
    goldenRule:'النشاط الاجتماعي يغرس فينا قيم الإحسان والعطاء والتعاون.',
    feedbackQuestion:{question:'ماذا يكتسب الطالب من المشاركة في حملة خيرية؟',options:[{text:'الإحسان والعطاء',correct:true},{text:'الأنانية',correct:false},{text:'الكسل',correct:false},{text:'الحسد',correct:false}]},
  },
  {
    id:'u1l3q5', unit:'unit1', lesson:'u1l3', page:15, type:'trueFalse',
    bloom:'apply', difficulty:'medium',
    question:'مشاركة الطلاب في إعداد حملة توعية عن آداب التعامل تعتبر نشاطاً مفيداً.',
    paragraph:'النشاط: إعداد حملة توعية عن حسن التعامل مع الآخرين. (ص15)',
    correctAnswer:true,
    explanation:'إعداد حملة توعية ينمّي روح المسؤولية والتعاون وينشر القيم الحميدة.',
    goldenRule:'الحملات التوعوية تنشر القيم وتنمّي روح المسؤولية والمبادرة.',
    feedbackQuestion:{question:'ما فائدة المشاركة في حملة توعية؟',options:[{text:'نشر القيم وتنمية التعاون',correct:true},{text:'إضاعة الوقت',correct:false},{text:'الكسل',correct:false},{text:'لا فائدة',correct:false}]},
  },
  {
    id:'u1l3q6', unit:'unit1', lesson:'u1l3', page:15, type:'ordering',
    bloom:'apply', difficulty:'medium',
    question:'رتّب خطوات إعداد حملة توعية عن آداب التعامل:',
    paragraph:'خطوات الحملة: تحديد الهدف ← جمع المعلومات ← تصميم الإعلان ← نشر الحملة. (ص15)',
    items:['نشر الحملة','تحديد الهدف','تصميم الإعلان','جمع المعلومات'],
    correctOrder:[1,3,2,0],
    explanation:'الترتيب: تحديد الهدف ← جمع المعلومات ← تصميم الإعلان ← نشر الحملة.',
    goldenRule:'الحملة الناجحة: هدف ← معلومات ← تصميم ← نشر.',
  },
  {
    id:'u1l3q7', unit:'unit1', lesson:'u1l3', page:15, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'من الصفات الذميمة التي يجب أن يتجنبها الإنسان:',
    paragraph:'الصفات الذميمة: الكذب، الخيانة، الأنانية، الحسد، الغش، الظلم. (ص15)',
    options:[
      {text:'الحسد',correct:true},
      {text:'الصدق',correct:false},
      {text:'الأمانة',correct:false},
      {text:'العدل',correct:false},
    ],
    explanation:'الحسد صفة ذميمة تأكل الحسنات وتضرّ بصاحبها.',
    goldenRule:'الذميمة: كذب + خيانة + أنانية + حسد + غش + ظلم.',
    feedbackQuestion:{question:'أيٌّ مما يلي صفة حميدة؟',options:[{text:'الإخلاص',correct:true},{text:'الحسد',correct:false},{text:'الغش',correct:false},{text:'الظلم',correct:false}]},
  },
  {
    id:'u1l3q8', unit:'unit1', lesson:'u1l3', page:15, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف التصرفات: حسن تعامل أم سوء تعامل؟',
    paragraph:'حسن التعامل: مساعدة، احترام، إصلاح، عفو. سوء التعامل: إيذاء، كذب، إهانة، قطيعة. (ص15)',
    categories:['حسن تعامل ✅','سوء تعامل ❌'],
    items:[
      {text:'مساعدة المحتاج',correct_category:0},
      {text:'إيذاء الجار',correct_category:1},
      {text:'احترام الكبير',correct_category:0},
      {text:'إهانة الضعيف',correct_category:1},
      {text:'العفو عند المقدرة',correct_category:0},
      {text:'القطيعة بين الأرحام',correct_category:1},
    ],
    explanation:'حسن: مساعدة، احترام، عفو. سوء: إيذاء، إهانة، قطيعة.',
    goldenRule:'حسن التعامل يبني. سوء التعامل يهدّم.',
  },
  {
    id:'u1l3q9', unit:'unit1', lesson:'u1l3', page:15, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'التعاون مع الزملاء في عمل الخير صفة محمودة.',
    paragraph:'التعاون: من الصفات الحميدة، يقوّي الروابط بين الناس. (ص15)',
    correctAnswer:true,
    explanation:'التعاون على البر والتقوى من الصفات الحميدة.',
    goldenRule:'التعاون = قوة وبرّ. الأنانية = ضعف وشرّ.',
    feedbackQuestion:{question:'الأنانية وعدم التعاون مع الزملاء هي:',options:[{text:'صفة ذميمة',correct:true},{text:'صفة حميدة',correct:false},{text:'مطلوبة',correct:false},{text:'لا شيء',correct:false}]},
  },
  {
    id:'u1l3q10', unit:'unit1', lesson:'u1l3', page:15, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'الهدف من إعداد حملة توعية عن حسن التعامل:',
    paragraph:'الهدف: نشر الوعي بقيم حسن التعامل وتجنب سوء التعامل. (ص15)',
    options:[
      {text:'نشر الوعي بقيم حسن التعامل',correct:true},
      {text:'إضاعة الوقت',correct:false},
      {text:'التشهير بالآخرين',correct:false},
      {text:'إثارة المشاكل',correct:false},
    ],
    explanation:'الهدف نشر الوعي بالقيم الحميدة وحسن التعامل بين الناس.',
    goldenRule:'الحملة التوعوية = نشر القيم + توعية المجتمع.',
    feedbackQuestion:{question:'ما الهدف من حملة توعية عن آداب التعامل؟',options:[{text:'نشر الوعي بالقيم الحميدة',correct:true},{text:'إضاعة الوقت',correct:false},{text:'إثارة المشاكل',correct:false},{text:'التشهير',correct:false}]},
  },
  {
    id:'u1l3q11', unit:'unit1', lesson:'u1l3', page:15, type:'matching',
    bloom:'understand', difficulty:'medium',
    question:'صِل كل صفة بضدها:',
    paragraph:'الصدق ← الكذب. الأمانة ← الخيانة. التعاون ← الأنانية. الإحسان ← الإساءة. (ص15)',
    pairs:[
      {left:'الصدق',right:'الكذب'},
      {left:'الأمانة',right:'الخيانة'},
      {left:'التعاون',right:'الأنانية'},
      {left:'الإحسان',right:'الإساءة'},
    ],
    explanation:'كل صفة حميدة لها ضدها الذميم.',
    goldenRule:'لكل صفة حميدة ضدها الذميم — احرص على الحميدة واجتنب الذميمة.',
  },
  {
    id:'u1l3q12', unit:'unit1', lesson:'u1l3', page:15, type:'trueFalse',
    bloom:'analyze', difficulty:'medium',
    question:'الإنسان الذي يكذب ويخون لا يثق به الناس.',
    paragraph:'الكذب والخيانة يفقدان صاحبهما ثقة الناس. (ص15)',
    correctAnswer:true,
    explanation:'الكذب والخيانة يفقدان صاحبهما الثقة والمحبة في المجتمع.',
    goldenRule:'الكذب والخيانة = فقدان الثقة. الصدق والأمانة = كسب الثقة.',
    feedbackQuestion:{question:'ماذا يفقد الكاذب في المجتمع؟',options:[{text:'ثقة الناس',correct:true},{text:'ماله',correct:false},{text:'اسمه فقط',correct:false},{text:'لا شيء',correct:false}]},
  },
  {
    id:'u1l3q13', unit:'unit1', lesson:'u1l3', page:15, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'من الصفات الحميدة التي ينبغي للمسلم التحلي بها عند الحديث مع الآخرين:',
    paragraph:'آداب الحديث: الصدق، خفض الصوت، الإصغاء، عدم المقاطعة. (ص15)',
    options:[
      {text:'الصدق وخفض الصوت',correct:true},
      {text:'رفع الصوت',correct:false},
      {text:'الكذب',correct:false},
      {text:'المقاطعة',correct:false},
    ],
    explanation:'الصدق وخفض الصوت من آداب الحديث الحميدة.',
    goldenRule:'آداب الحديث: صدق + خفض صوت + إصغاء + لا مقاطعة.',
    feedbackQuestion:{question:'رفع الصوت في الحديث هو:',options:[{text:'سوء أدب',correct:true},{text:'أدب حسن',correct:false},{text:'مطلوب',correct:false},{text:'لا شيء',correct:false}]},
  },
  {
    id:'u1l3q14', unit:'unit1', lesson:'u1l3', page:15, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف التصرفات في الحديث: أدب أم سوء أدب؟',
    paragraph:'الأدب: إصغاء، خفض صوت، صدق، ابتسامة. سوء الأدب: مقاطعة، صراخ، كذب، عبوس. (ص15)',
    categories:['أدب في الحديث','سوء أدب في الحديث'],
    items:[
      {text:'الإصغاء للمتحدث',correct_category:0},
      {text:'المقاطعة في الكلام',correct_category:1},
      {text:'خفض الصوت',correct_category:0},
      {text:'الصراخ في الحديث',correct_category:1},
      {text:'الصدق في الكلام',correct_category:0},
      {text:'العبوس في الوجه',correct_category:1},
    ],
    explanation:'أدب: إصغاء، خفض، صدق. سوء: مقاطعة، صراخ، عبوس.',
    goldenRule:'أدب الحديث: إصغاء + خفض + صدق + ابتسامة.',
  },
  {
    id:'u1l3q15', unit:'unit1', lesson:'u1l3', page:15, type:'trueFalse',
    bloom:'evaluate', difficulty:'medium',
    question:'الإصغاء إلى المتحدث وعدم مقاطعته من علامات حسن الخلق.',
    paragraph:'الإصغاء وعدم المقاطعة = أدب الحديث الحسن. (ص15)',
    correctAnswer:true,
    explanation:'الإصغاء وعدم المقاطعة من آداب الحوار الحسن وعلامات حسن الخلق.',
    goldenRule:'الإصغاء = احترام + فهم + أدب. المقاطعة = سوء أدب + إهمال.',
    feedbackQuestion:{question:'ماذا يُظهر الإصغاء للمتحدث؟',options:[{text:'الاحترام وحسن الخلق',correct:true},{text:'الضعف',correct:false},{text:'الجهل',correct:false},{text:'الأنانية',correct:false}]},
  },
  {
    id:'u1l3q16', unit:'unit1', lesson:'u1l3', page:15, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'الإعلان عن جمعية الإحسان يهدف إلى:',
    paragraph:'جمعية الإحسان: جمع التبرعات لمساعدة المحتاجين. (ص15)',
    options:[
      {text:'جمع التبرعات لمساعدة المحتاجين',correct:true},
      {text:'الربح الشخصي',correct:false},
      {text:'إضاعة المال',correct:false},
      {text:'إثارة المشاكل',correct:false},
    ],
    explanation:'جمعية الإحسان تجمع التبرعات لمساعدة المحتاجين والفقراء.',
    goldenRule:'جمعيات الإحسان = جمع التبرعات + مساعدة المحتاجين + نشر الخير.',
    feedbackQuestion:{question:'ما هدف جمعيات الإحسان؟',options:[{text:'مساعدة المحتاجين',correct:true},{text:'الربح الشخصي',correct:false},{text:'إضاعة المال',correct:false},{text:'إثارة المشاكل',correct:false}]},
  },
  {
    id:'u1l3q17', unit:'unit1', lesson:'u1l3', page:15, type:'fillBlank',
    bloom:'apply', difficulty:'medium',
    question:'أكمل: «من الصفات الحميدة في التعامل: ___ و___»',
    paragraph:'الحميدة: صدق، أمانة، تعاون، عدل. (ص15)',
    blanks:['الصدق','الأمانة'],
    wordBank:['الصدق','الأمانة','الكذب','الخيانة'],
    explanation:'الصدق والأمانة من الصفات الحميدة في التعامل مع الآخرين.',
    goldenRule:'الصدق + الأمانة = أساس الثقة في التعامل.',
  },
  {
    id:'u1l3q18', unit:'unit1', lesson:'u1l3', page:15, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'العدل صفة ذميمة يجب تجنبها.',
    paragraph:'العدل: من الصفات الحميدة التي أمر بها الله. (ص15)',
    correctAnswer:false,
    explanation:'العدل صفة حميدة أمر الله بها في كتابه: «إن الله يأمر بالعدل».',
    goldenRule:'العدل = قسط + إنصاف + حميدة. الظلم = جور + ذميمة.',
    feedbackQuestion:{question:'الظلم في التعامل هو:',options:[{text:'صفة ذميمة',correct:true},{text:'صفة حميدة',correct:false},{text:'مطلوبة',correct:false},{text:'لا شيء',correct:false}]},
  },
  {
    id:'u1l3q19', unit:'unit1', lesson:'u1l3', page:15, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'الإخلاص في العمل من الصفات:',
    paragraph:'الإخلاص: من الصفات الحميدة، يبتغى به وجه الله. (ص15)',
    options:[
      {text:'الحميدة',correct:true},
      {text:'الذميمة',correct:false},
      {text:'السيئة',correct:false},
      {text:'غير المحبوبة',correct:false},
    ],
    explanation:'الإخلاص صفة حميدة يُثاب عليها الإنسان عند الله.',
    goldenRule:'الإخلاص = صدق النية + ابتغاء الأجر من الله.',
    feedbackQuestion:{question:'الرياء في العمل هو:',options:[{text:'صفة ذميمة',correct:true},{text:'صفة حميدة',correct:false},{text:'مطلوبة',correct:false},{text:'لا شيء',correct:false}]},
  },
  {
    id:'u1l3q20', unit:'unit1', lesson:'u1l3', page:15, type:'classify',
    bloom:'analyze', difficulty:'hard',
    question:'صنّف القيم حسب تأثيرها على المجتمع:',
    paragraph:'البناءة: صدق، أمانة، تعاون، إحسان. الهدّامة: كذب، خيانة، أنانية، حسد. (ص15)',
    categories:['تبني المجتمع','تهدّم المجتمع'],
    items:[
      {text:'الصدق',correct_category:0},
      {text:'الكذب',correct_category:1},
      {text:'التعاون',correct_category:0},
      {text:'الأنانية',correct_category:1},
      {text:'الإحسان',correct_category:0},
      {text:'الحسد',correct_category:1},
    ],
    explanation:'البناءة: صدق، تعاون، إحسان. الهدّامة: كذب، أنانية، حسد.',
    goldenRule:'القيم الحميدة تبني المجتمع. الذميمة تهدّمه.',
  },
  {
    id:'u1l3q21', unit:'unit1', lesson:'u1l3', page:15, type:'trueFalse',
    bloom:'apply', difficulty:'medium',
    question:'القيام بحملة توعية عن آداب التعامل يُعد عملاً جماعياً ينبغي التخطيط له.',
    paragraph:'الحملة: تحتاج تخطيطاً جماعياً وتوزيعاً للمهام. (ص15)',
    correctAnswer:true,
    explanation:'الحملة التوعوية تحتاج تخطيطاً وتوزيع مهام بين الأفراد.',
    goldenRule:'الحملة الناجحة = تخطيط + تعاون + توزيع مهام + تنفيذ.',
    feedbackQuestion:{question:'ماذا تحتاج حملة التوعية لتنجح؟',options:[{text:'تخطيط وتعاون',correct:true},{text:'فرد واحد',correct:false},{text:'إهمال',correct:false},{text:'لا شيء',correct:false}]},
  },
  {
    id:'u1l3q22', unit:'unit1', lesson:'u1l3', page:15, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'العفو عند المقدرة يُعد من:',
    paragraph:'العفو: من أعظم الصفات الحميدة، يُثيب الله صاحبه. (ص15)',
    options:[
      {text:'الصفات الحميدة',correct:true},
      {text:'الصفات الذميمة',correct:false},
      {text:'الضعف',correct:false},
      {text:'الجبن',correct:false},
    ],
    explanation:'العفو عند المقدرة قوة لا ضعف، ومن أعظم الصفات الحميدة.',
    goldenRule:'العفو عند المقدرة = قوة + أجر + حميدة.',
    feedbackQuestion:{question:'الانتقام لمن أساء إليك هو:',options:[{text:'ليس من أخلاق المسلم',correct:true},{text:'من أخلاق المسلم',correct:false},{text:'واجب',correct:false},{text:'مستحب',correct:false}]},
  },
  {
    id:'u1l3q23', unit:'unit1', lesson:'u1l3', page:15, type:'matching',
    bloom:'understand', difficulty:'medium',
    question:'صِل كل تصرف بنتيجته:',
    paragraph:'الصدق ← ثقة. الكذب ← فقدان ثقة. التعاون ← قوة. الأنانية ← ضعف. (ص15)',
    pairs:[
      {left:'الصدق في القول',right:'كسب ثقة الناس'},
      {left:'الكذب في القول',right:'فقدان ثقة الناس'},
      {left:'التعاون مع الزملاء',right:'قوة وتماسك'},
      {left:'الأنانية',right:'ضعف وتفرق'},
    ],
    explanation:'الصدق ← ثقة. الكذب ← فقدان. التعاون ← قوة. الأنانية ← ضعف.',
    goldenRule:'كل تصرف له نتيجة: حسن ← خير، سيئ ← شر.',
  },
  {
    id:'u1l3q24', unit:'unit1', lesson:'u1l3', page:15, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'أيُّ تصرف يدل على نضج الشخصية وحسن الخلق؟',
    paragraph:'النضج: ضبط النفس، العفو، الصدق، الاحترام. (ص15)',
    options:[
      {text:'ضبط النفس عند الغضب والعفو',correct:true},
      {text:'الانتقام عند الغضب',correct:false},
      {text:'رفع الصوت',correct:false},
      {text:'السبّ والشتم',correct:false},
    ],
    explanation:'ضبط النفس عند الغضب والعفو من أعظم علامات النضج وحسن الخلق.',
    goldenRule:'النضج = ضبط نفس + عفو + صدق + احترام.',
    feedbackQuestion:{question:'أيُّ تصرف يدل على ضعف الشخصية؟',options:[{text:'الانفعال والانتقام',correct:true},{text:'ضبط النفس',correct:false},{text:'العفو',correct:false},{text:'الصبر',correct:false}]},
  },
  {
    id:'u1l3q25', unit:'unit1', lesson:'u1l3', page:15, type:'ordering',
    bloom:'apply', difficulty:'medium',
    question:'رتّب الصفات الحميدة من حيث أهميتها في التعامل:',
    paragraph:'الصفات: الصدق أساسها، ثم الأمانة، ثم التعاون، ثم الإحسان. (ص15)',
    items:['الإحسان','الصدق','التعاون','الأمانة'],
    correctOrder:[1,3,2,0],
    explanation:'الترتيب المنطقي: صدق ← أمانة ← تعاون ← إحسان.',
    goldenRule:'أساس التعامل: صدق + أمانة، ثم تعاون وإحسان.',
  },
  {
    id:'u1l3q26', unit:'unit1', lesson:'u1l3', page:15, type:'trueFalse',
    bloom:'remember', difficulty:'easy',
    question:'الأمانة في الحفظ والرد من الصفات الحميدة.',
    paragraph:'الأمانة: حفظ الودائع وردّها لأصحابها. (ص15)',
    correctAnswer:true,
    explanation:'الأمانة حفظ ما يُؤتمن عليه وردّه لصاحبه، وهي صفة حميدة.',
    goldenRule:'الأمانة = حفظ + ردّ + صدق في التعامل.',
    feedbackQuestion:{question:'الخيانة في الودائع هي:',options:[{text:'صفة ذميمة',correct:true},{text:'صفة حميدة',correct:false},{text:'مطلوبة',correct:false},{text:'لا شيء',correct:false}]},
  },
  {
    id:'u1l3q27', unit:'unit1', lesson:'u1l3', page:15, type:'fillBlank',
    bloom:'apply', difficulty:'medium',
    question:'أكمل: «من سوء التعامل: ___ الجار و___ الضعيف»',
    paragraph:'سوء التعامل: إيذاء الجار، إهانة الضعيف. (ص15)',
    blanks:['إيذاء','إهانة'],
    wordBank:['إيذاء','إهانة','احترام','مساعدة'],
    explanation:'إيذاء الجار وإهانة الضعيف من سوء التعامل.',
    goldenRule:'سوء التعامل: إيذاء + إهانة + كذب + قطيعة.',
  },
  {
    id:'u1l3q28', unit:'unit1', lesson:'u1l3', page:15, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'الإحسان إلى الناس يكون بـ:',
    paragraph:'الإحسان: مساعدة، عطاء، إطعام، إكرام، إنصاف. (ص15)',
    options:[
      {text:'مساعدة المحتاجين والإحسان إليهم',correct:true},
      {text:'إيذاء الناس',correct:false},
      {text:'الأنانية',correct:false},
      {text:'البخل',correct:false},
    ],
    explanation:'الإحسان يكون بمساعدة الناس والعطاء والإنصاف.',
    goldenRule:'الإحسان = مساعدة + عطاء + إكرام + إنصاف.',
    feedbackQuestion:{question:'البخل وعدم العطاء هو:',options:[{text:'صفة ذميمة',correct:true},{text:'صفة حميدة',correct:false},{text:'مطلوبة',correct:false},{text:'لا شيء',correct:false}]},
  },
  {
    id:'u1l3q29', unit:'unit1', lesson:'u1l3', page:15, type:'trueFalse',
    bloom:'analyze', difficulty:'medium',
    question:'القيم الحميدة تساهم في بناء مجتمع متماسك قوي.',
    paragraph:'القيم الحميدة: تبني المجتمع وتقوّي روابطه. (ص15)',
    correctAnswer:true,
    explanation:'القيم الحميدة تبني المجتمع وتقوّي روابطه وتزيد محبته.',
    goldenRule:'القيم الحميدة = مجتمع قوي متماسك. الذميمة = مجتمع ضعيف متفرق.',
    feedbackQuestion:{question:'ما تأثير القيم الذميمة على المجتمع؟',options:[{text:'تفرّقه وتضعفه',correct:true},{text:'تقوّيه',correct:false},{text:'توحده',correct:false},{text:'لا تأثير',correct:false}]},
  },
  {
    id:'u1l3q30', unit:'unit1', lesson:'u1l3', page:15, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'ما العلاقة بين الصفات الحميدة والمجتمع الفاضل؟',
    paragraph:'المجتمع الفاضل: يقوم على الصدق والأمانة والتعاون والعدل. (ص15)',
    options:[
      {text:'الصفات الحميدة تبني المجتمع الفاضل',correct:true},
      {text:'لا علاقة بينهما',correct:false},
      {text:'الصفات الحميدة تهدّم المجتمع',correct:false},
      {text:'الصفات الذميمة تبني المجتمع',correct:false},
    ],
    explanation:'المجتمع الفاضل يقوم على الصفات الحميدة (صدق، أمانة، تعاون، عدل).',
    goldenRule:'المجتمع الفاضل = صدق + أمانة + تعاون + عدل + إحسان.',
    feedbackQuestion:{question:'ما أساس المجتمع الفاضل؟',options:[{text:'الصفات الحميدة',correct:true},{text:'الصفات الذميمة',correct:false},{text:'لا شيء',correct:false},{text:'المال',correct:false}]},
  },
  {
    id:'u1l3q31', unit:'unit1', lesson:'u1l3', page:15, type:'classify',
    bloom:'analyze', difficulty:'hard',
    question:'صنّف: ماذا يكتسب الإنسان من كل تصرف؟',
    paragraph:'الصدق ← ثقة. الكذب ← فقدان. الإحسان ← محبة. الأنانية ← كراهية. (ص15)',
    categories:['يكتسب خيراً','يفقد خيراً'],
    items:[
      {text:'الصدق في القول',correct_category:0},
      {text:'الكذب في القول',correct_category:1},
      {text:'الإحسان للناس',correct_category:0},
      {text:'الأنانية',correct_category:1},
      {text:'الأمانة',correct_category:0},
      {text:'الخيانة',correct_category:1},
    ],
    explanation:'يكتسب خيراً: صدق، إحسان، أمانة. يفقد: كذب، أنانية، خيانة.',
    goldenRule:'كل تصرف له ثمرته: حسن ← خير، سيئ ← شر.',
  },
  {
    id:'u1l3q32', unit:'unit1', lesson:'u1l3', page:15, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'حملة التوعية بآداب التعامل تساعد في نشر القيم الحميدة.',
    paragraph:'الحملة: تنشر القيم وتوعي المجتمع. (ص15)',
    correctAnswer:true,
    explanation:'حملة التوعية تنشر القيم الحميدة وتوعي المجتمع بأهميتها.',
    goldenRule:'الحملة التوعوية = نشر قيم + توعية + إصلاح مجتمع.',
    feedbackQuestion:{question:'ماذا تنشر حملة التوعية؟',options:[{text:'القيم الحميدة',correct:true},{text:'الأكاذيب',correct:false},{text:'الفتن',correct:false},{text:'لا شيء',correct:false}]},
  },
  {
    id:'u1l3q33', unit:'unit1', lesson:'u1l3', page:15, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'من الصفات التي تجعل الإنسان محبوباً بين الناس:',
    paragraph:'المحبة: الصدق، الأمانة، التعاون، الإحسان، التواضع. (ص15)',
    options:[
      {text:'التواضع والإحسان',correct:true},
      {text:'التكبر والتعالي',correct:false},
      {text:'الأنانية',correct:false},
      {text:'الحسد',correct:false},
    ],
    explanation:'التواضع والإحسان يجعلان الإنسان محبوباً بين الناس.',
    goldenRule:'المحبة = تواضع + إحسان + صدق + تعاون.',
    feedbackQuestion:{question:'التكبر والتعالي على الناس يجعلان صاحبهما:',options:[{text:'مكروهاً',correct:true},{text:'محبوباً',correct:false},{text:'محترماً',correct:false},{text:'لا شيء',correct:false}]},
  },
  {
    id:'u1l3q34', unit:'unit1', lesson:'u1l3', page:15, type:'ordering',
    bloom:'apply', difficulty:'medium',
    question:'رتّب تصرفات حسن التعامل من الأبسط للأعمق:',
    paragraph:'حسن التعامل: ابتسامة ← تحية ← مساعدة ← إحسان. (ص15)',
    items:['الإحسان','الابتسامة','المساعدة','التحية'],
    correctOrder:[1,3,2,0],
    explanation:'الترتيب من الأبسط: ابتسامة ← تحية ← مساعدة ← إحسان.',
    goldenRule:'حسن التعامل يبدأ بالابتسامة وينتهي بالإحسان.',
  },
  {
    id:'u1l3q35', unit:'unit1', lesson:'u1l3', page:15, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'القيمة العظمى التي تعلّمناها من نشاط التهيئة عن التعامل مع الآخرين:',
    paragraph:'القيمة العظمى: حسن التعامل أساس بناء المجتمع وعماد العلاقات. (ص15)',
    options:[
      {text:'حسن التعامل أساس بناء المجتمع',correct:true},
      {text:'الأنانية أساس القوة',correct:false},
      {text:'الكذب أساس النجاح',correct:false},
      {text:'الظلم أساس العدل',correct:false},
    ],
    explanation:'القيمة العظمى: حسن التعامل مع الآخرين أساس بناء المجتمع الفاضل.',
    goldenRule:'حسن التعامل = أساس بناء المجتمع + عماد العلاقات + سبب المحبة.',
    feedbackQuestion:{question:'ما الأساس الذي يقوم عليه المجتمع الفاضل؟',options:[{text:'حسن التعامل بين الأفراد',correct:true},{text:'الأنانية',correct:false},{text:'الكذب',correct:false},{text:'الظلم',correct:false}]},
  },
];

export const U1L4_QS = [
  {
    id:'u1l4q1', unit:'unit1', lesson:'u1l4', page:16, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'قصة «شُكْرًا يا جارتي» تحكي عن جارٍ أحسن إلى جارته. أين تدور أحداث القصة؟',
    paragraph:'تدور أحداث القصة في حيٍّ سكني بين جيران متجاورين. (ص16-19)',
    options:[
      {text:'في حيٍّ سكني بين جيران',correct:true},
      {text:'في المدرسة',correct:false},
      {text:'في السوق',correct:false},
      {text:'في المسجد',correct:false},
    ],
    explanation:'أحداث القصة تدور في حيٍّ سكني بين جار وجارته.',
    goldenRule:'قصة «شُكْرًا يا جارتي» = علاقة جوار وإحسان.',
    feedbackQuestion:{question:'علاقة الجيران في القصة قائمة على:',options:[{text:'الإحسان والتعاون',correct:true},{text:'الإيذاء',correct:false},{text:'القطيعة',correct:false},{text:'الجفاء',correct:false}]},
  },
  {
    id:'u1l4q2', unit:'unit1', lesson:'u1l4', page:16, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'الجار في القصة أحسن إلى جارته عندما مرضت ولم تستطع القيام بأعمالها.',
    paragraph:'الجار: ذهبت إلى جارتها المريضة، أحضرت لها الطعام، ونظّفت منزلها. (ص17-18)',
    correctAnswer:true,
    explanation:'الجار أحسن إلى جارته بالطعام والتنظيف والعون عند مرضها.',
    goldenRule:'الإحسان للجار = عون عند الحاجة + طعام + تنظيف + مراعاة.',
    feedbackQuestion:{question:'ماذا فعل الجار لجارته المريضة؟',options:[{text:'أعانها بالطعام والتنظيف',correct:true},{text:'تركها وحدها',correct:false},{text:'أخبر الناس عنها',correct:false},{text:'لا شيء',correct:false}]},
  },
  {
    id:'u1l4q3', unit:'unit1', lesson:'u1l4', page:17, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'شخصيات القصة الرئيسة هم:',
    paragraph:'الشخصيات: الجار، الجارة، أبناء الجارة. (ص16-19)',
    options:[
      {text:'الجار والجارة',correct:true},
      {text:'المعلم والطالب',correct:false},
      {text:'التاجر والزبون',correct:false},
      {text:'الطبيب والمريض',correct:false},
    ],
    explanation:'الشخصيات الرئيسة في القصة: الجار والجارة.',
    goldenRule:'شخصيات القصة: من يدور حولهم الحدث (الجار والجارة).',
    feedbackQuestion:{question:'أين تقع أحداث القصة؟',options:[{text:'في الحي السكني',correct:true},{text:'في المدرسة',correct:false},{text:'في المسجد',correct:false},{text:'في البحر',correct:false}]},
  },
  {
    id:'u1l4q4', unit:'unit1', lesson:'u1l4', page:18, type:'ordering',
    bloom:'apply', difficulty:'medium',
    question:'رتّب أحداث القصة حسب تسلسلها الزمني:',
    paragraph:'الأحداث: مرض الجارة ← ذهاب الجار إليها ← إحضار الطعام ← شكر الجارة. (ص16-19)',
    items:['إحضار الطعام','مرض الجارة','شكر الجارة','ذهاب الجار إليها'],
    correctOrder:[1,3,0,2],
    explanation:'الترتيب: مرض الجارة ← ذهاب الجار ← إحضار الطعام ← شكر الجارة.',
    goldenRule:'تسلسل القصة: حدث ابتدائي ← تطور ← نهاية.',
  },
  {
    id:'u1l4q5', unit:'unit1', lesson:'u1l4', page:18, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف التصرفات في القصة: حسن جوار أم سوء جوار؟',
    paragraph:'حسن الجوار: زيارة، إطعام، عون. سوء الجوار: إيذاء، إهمال، قطيعة. (ص16-19)',
    categories:['حسن جوار ✅','سوء جوار ❌'],
    items:[
      {text:'زيارة الجار المريض',correct_category:0},
      {text:'إيذاء الجار بالضوضاء',correct_category:1},
      {text:'إطعام الجار الجائع',correct_category:0},
      {text:'إهمال الجار المحتاج',correct_category:1},
      {text:'الإعانة عند الحاجة',correct_category:0},
      {text:'القطيعة بين الجيران',correct_category:1},
    ],
    explanation:'حسن: زيارة، إطعام، إعانة. سوء: إيذاء، إهمال، قطيعة.',
    goldenRule:'حسن الجوار = زيارة + إطعام + إعانة + مراعاة.',
  },
  {
    id:'u1l4q6', unit:'unit1', lesson:'u1l4', page:19, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'أهم درس نتعلمه من قصة «شُكْرًا يا جارتي»:',
    paragraph:'الدرس: الإحسان إلى الجار ومراعاة حقه. (ص16-19)',
    options:[
      {text:'الإحسان إلى الجار ومراعاة حقه',correct:true},
      {text:'إيذاء الجار',correct:false},
      {text:'تجاهل الجار',correct:false},
      {text:'الأنانية',correct:false},
    ],
    explanation:'الدرس: الإحسان إلى الجار ومراعاة حقه من صفات المسلم.',
    goldenRule:'درس القصة = إحسان للجار + مراعاة حق + عون عند الحاجة.',
    feedbackQuestion:{question:'ما الذي يجب على المسلم تجاه جاره؟',options:[{text:'الإحسان إليه ومراعاة حقه',correct:true},{text:'إيذاؤه',correct:false},{text:'تجاهله',correct:false},{text:'لا شيء',correct:false}]},
  },
  {
    id:'u1l4q7', unit:'unit1', lesson:'u1l4', page:19, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'في نهاية القصة، شكرت الجارة جارها على إحسانه إليها.',
    paragraph:'النهاية: قالت الجارة لجارها: «شُكْرًا يا جارتي» على إحسانه. (ص19)',
    correctAnswer:true,
    explanation:'الجارة شكرت جارها على إحسانه، وهو عنوان القصة «شُكْرًا يا جارتي».',
    goldenRule:'الشكر على الإحسان = أدب وفضل. لذلك سميت القصة «شُكْرًا يا جارتي».',
    feedbackQuestion:{question:'لماذا سميت القصة «شُكْرًا يا جارتي»؟',options:[{text:'لأن الجارة شكرت جارها على إحسانه',correct:true},{text:'لأن الجار لم يحسن',correct:false},{text:'لأن الجارة غضبت',correct:false},{text:'لا سبب',correct:false}]},
  },
  {
    id:'u1l4q8', unit:'unit1', lesson:'u1l4', page:16, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'أحداث القصة تدور في:',
    paragraph:'مكان القصة: الحي السكني. الزمان: غير محدد (يوميات الجوار). (ص16)',
    options:[
      {text:'حي سكني',correct:true},
      {text:'مدرسة',correct:false},
      {text:'مسجد',correct:false},
      {text:'سوق',correct:false},
    ],
    explanation:'أحداث القصة في حي سكني بين جيران متجاورين.',
    goldenRule:'عناصر القصة: شخصيات + مكان + زمان + أحداث + نهاية.',
    feedbackQuestion:{question:'من شخصيات القصة الرئيسة؟',options:[{text:'الجار والجارة',correct:true},{text:'المعلم والطالب',correct:false},{text:'الطبيب والمريض',correct:false},{text:'التاجر والزبون',correct:false}]},
  },
  {
    id:'u1l4q9', unit:'unit1', lesson:'u1l4', page:17, type:'trueFalse',
    bloom:'understand', difficulty:'medium',
    question:'الجار في القصة انتظر أن تطلب منه الجارة المساعدة ثم ذهب إليها.',
    paragraph:'الجار بادر بمساعدة جارته دون أن تطلب منه. (ص17-18)',
    correctAnswer:false,
    explanation:'الجار بادر بمساعدة جارته من تلقاء نفسه دون أن تطلب منه.',
    goldenRule:'مبادرة الخير = لا انتظار طلب. الجار الصالح يبادر.',
    feedbackQuestion:{question:'ماذا فعل الجار عندما علم بمرض جارته؟',options:[{text:'بادر بمساعدتها',correct:true},{text:'انتظر طلبها',correct:false},{text:'لم يفعل شيئاً',correct:false},{text:'أخبر الناس',correct:false}]},
  },
  {
    id:'u1l4q10', unit:'unit1', lesson:'u1l4', page:17, type:'fillBlank',
    bloom:'apply', difficulty:'medium',
    question:'أكمل: «ذهب الجار إلى جارته المريضة و___ لها الطعام و___ منزلها»',
    paragraph:'الجار: أحضر الطعام، ونظّف المنزل لجارته المريضة. (ص17-18)',
    blanks:['أحضر','نظّف'],
    wordBank:['أحضر','نظّف','ترك','أهمل'],
    explanation:'الجار أحضر الطعام ونظّف المنزل لجارته المريضة.',
    goldenRule:'إحسان الجار = إحضار طعام + تنظيف + عون.',
  },
  {
    id:'u1l4q11', unit:'unit1', lesson:'u1l4', page:18, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'المشكلة التي واجهتها الجارة في القصة:',
    paragraph:'المشكلة: مرض الجارة وعدم قدرتها على القيام بأعمال منزلها. (ص16-17)',
    options:[
      {text:'مرضها وعجزها عن القيام بأعمالها',correct:true},
      {text:'فقدان مالها',correct:false},
      {text:'خلاف مع الجار',correct:false},
      {text:'سفر زوجها',correct:false},
    ],
    explanation:'المشكلة: مرض الجارة وعجزها عن القيام بأعمال منزلها.',
    goldenRule:'المشكلة في القصة = ما يعوق الشخصيات ويتطلب حلاً.',
    feedbackQuestion:{question:'كيف حُلّت مشكلة الجارة؟',options:[{text:'بمساعدة الجار',correct:true},{text:'بالانتظار',correct:false},{text:'بالبكاء',correct:false},{text:'لا حل',correct:false}]},
  },
  {
    id:'u1l4q12', unit:'unit1', lesson:'u1l4', page:18, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف عناصر القصة: شخصيات أم مكان أم حدث؟',
    paragraph:'عناصر القصة: شخصيات (الجار، الجارة)، مكان (الحي السكني)، أحداث (المرض، الإحسان، الشكر). (ص16-19)',
    categories:['شخصيات','مكان','أحداث'],
    items:[
      {text:'الجار',correct_category:0},
      {text:'الحي السكني',correct_category:1},
      {text:'مرض الجارة',correct_category:2},
      {text:'الجارة',correct_category:0},
      {text:'إحضار الطعام',correct_category:2},
      {text:'منزل الجارة',correct_category:1},
    ],
    explanation:'شخصيات: الجار، الجارة. مكان: الحي، المنزل. أحداث: المرض، إحضار الطعام.',
    goldenRule:'عناصر القصة: شخصيات + مكان + زمان + أحداث.',
  },
  {
    id:'u1l4q13', unit:'unit1', lesson:'u1l4', page:19, type:'trueFalse',
    bloom:'evaluate', difficulty:'medium',
    question:'قصة «شُكْرًا يا جارتي» تشجّع على الإحسان للجار.',
    paragraph:'القصة: نموذج للإحسان للجار والشكر على المعروف. (ص16-19)',
    correctAnswer:true,
    explanation:'القصة تشجّع على الإحسان للجار والشكر على المعروف.',
    goldenRule:'القصة الحسنة = عبرة + تشجيع على الخير + نموذج يُحتذى.',
    feedbackQuestion:{question:'ما القيمة التي تعلّمناها من القصة؟',options:[{text:'الإحسان إلى الجار',correct:true},{text:'إيذاء الجار',correct:false},{text:'تجاهل الجار',correct:false},{text:'الأنانية',correct:false}]},
  },
  {
    id:'u1l4q14', unit:'unit1', lesson:'u1l4', page:17, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'عندما مرضت الجارة، تصرّف الجار كان:',
    paragraph:'الجار: بادر بمساعدة جارته المريضة. (ص17-18)',
    options:[
      {text:'مبادرة بالخير',correct:true},
      {text:'تجاهل',correct:false},
      {text:'انتظار طلب',correct:false},
      {text:'إيذاء',correct:false},
    ],
    explanation:'الجار بادر بالخير دون انتظار طلب أو مقابل.',
    goldenRule:'مبادرة الخير = صفة المسلم الذي يفعل الخير دون انتظار.',
    feedbackQuestion:{question:'التجاهل وعدم المبادرة بمساعدة الجار هو:',options:[{text:'سوء خلق',correct:true},{text:'حسن خلق',correct:false},{text:'واجب',correct:false},{text:'لا شيء',correct:false}]},
  },
  {
    id:'u1l4q15', unit:'unit1', lesson:'u1l4', page:18, type:'ordering',
    bloom:'apply', difficulty:'medium',
    question:'رتّب تصرّفات الجار من البداية للنهاية:',
    paragraph:'تصرّفات الجار: سماع الخبر ← الذهاب ← الإحسان ← العودة. (ص17-18)',
    items:['العودة','سماع الخبر','الإحسان','الذهاب'],
    correctOrder:[1,3,2,0],
    explanation:'الترتيب: سماع الخبر ← الذهاب ← الإحسان ← العودة.',
    goldenRule:'تسلسل التصرّف: سماع ← ذهاب ← إحسان ← عودة.',
  },
  {
    id:'u1l4q16', unit:'unit1', lesson:'u1l4', page:16, type:'matching',
    bloom:'understand', difficulty:'medium',
    question:'صِل كل عنصر بقيمته في القصة:',
    paragraph:'العناصر: الجار (فاعل الخير)، الجارة (متلقّي الإحسان)، الطعام (وسيلة الإحسان)، الشكر (ردّ الجميل). (ص16-19)',
    pairs:[
      {left:'الجار',right:'فاعل الإحسان'},
      {left:'الجارة',right:'متلقّي الإحسان'},
      {left:'الطعام',right:'وسيلة الإحسان'},
      {left:'الشكر',right:'ردّ الجميل'},
    ],
    explanation:'الجار فاعل، الجارة متلقّية، الطعام وسيلة، الشكر ردّ.',
    goldenRule:'عناصر القصة: فاعل + متلقٍّ + وسيلة + نتيجة.',
  },
  {
    id:'u1l4q17', unit:'unit1', lesson:'u1l4', page:19, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'الشكر على المعروف صفة من صفات المسلم الحسن.',
    paragraph:'الشكر: من الآداب الحميدة، يُثيب الله صاحبه. (ص19)',
    correctAnswer:true,
    explanation:'الشكر على المعروف أدب حميد يكثر المودة بين الناس.',
    goldenRule:'الشكر = أدب + محبة + زيادة نعمة.',
    feedbackQuestion:{question:'عدم شكر من أحسن إليك هو:',options:[[{text:'كفران نعمة',correct:true}]]},
  },
  {
    id:'u1l4q18', unit:'unit1', lesson:'u1l4', page:18, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'القيمة الأخلاقية الأساسية في قصة «شُكْرًا يا جارتي»:',
    paragraph:'القيمة: الإحسان إلى الجار. (ص16-19)',
    options:[
      {text:'الإحسان إلى الجار',correct:true},
      {text:'الأنانية',correct:false},
      {text:'الكذب',correct:false},
      {text:'الظلم',correct:false},
    ],
    explanation:'القيمة الأساسية في القصة: الإحسان إلى الجار والشكر على المعروف.',
    goldenRule:'قيمة القصة = إحسان + شكر + مراعاة حق الجار.',
    feedbackQuestion:{question:'ما القيمة الأساسية في القصة؟',options:[{text:'الإحسان إلى الجار',correct:true},{text:'الإيذاء',correct:false},{text:'الأنانية',correct:false},{text:'الكذب',correct:false}]},
  },
  {
    id:'u1l4q19', unit:'unit1', lesson:'u1l4', page:17, type:'trueFalse',
    bloom:'remember', difficulty:'easy',
    question:'من أفعال الجار في القصة أنه أحضر الطعام لجارته المريضة.',
    paragraph:'الجار: أحضر الطعام لجارته المريضة. (ص17-18)',
    correctAnswer:true,
    explanation:'نعم، من أفعال الجار أنه أحضر الطعام لجارته المريضة.',
    goldenRule:'إحضار الطعام للمريض = إحسان + رحمة + أدب.',
    feedbackQuestion:{question:'ماذا أحضر الجار لجارته؟',options:[{text:'الطعام',correct:true},{text:'الكتاب',correct:false},{text:'اللعبة',correct:false},{text:'لا شيء',correct:false}]},
  },
  {
    id:'u1l4q20', unit:'unit1', lesson:'u1l4', page:18, type:'classify',
    bloom:'analyze', difficulty:'hard',
    question:'صنّف ما تعلّمناه من القصة: قول أم فعل؟',
    paragraph:'القول: «شُكْرًا يا جارتي». الفعل: إحضار الطعام، تنظيف المنزل. (ص16-19)',
    categories:['قول (أدب)','فعل (إحسان)'],
    items:[
      {text:'«شُكْرًا يا جارتي»',correct_category:0},
      {text:'إحضار الطعام',correct_category:1},
      {text:'تنظيف المنزل',correct_category:1},
      {text:'الزيارة',correct_category:1},
      {text:'«عوفيتِ»',correct_category:0},
    ],
    explanation:'الأقوال: شكر، دعاء. الأفعال: إحضار، تنظيف، زيارة.',
    goldenRule:'الإحسان = قول طيب + فعل خير.',
  },
  {
    id:'u1l4q21', unit:'unit1', lesson:'u1l4', page:16, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'عنوان القصة «شُكْرًا يا جارتي» يدل على:',
    paragraph:'العنوان: يدل على شكر الجارة لجارها على إحسانه. (ص16)',
    options:[
      {text:'الشكر على الإحسان',correct:true},
      {text:'الإيذاء',correct:false},
      {text:'القطيعة',correct:false},
      {text:'الجفاء',correct:false},
    ],
    explanation:'العنوان يدل على الشكر على الإحسان بين الجيران.',
    goldenRule:'عنوان القصة يكشف فكرتها الأساسية.',
    feedbackQuestion:{question:'ما الفكرة الأساسية من عنوان القصة؟',options:[{text:'الشكر على الإحسان',correct:true},{text:'الإيذاء',correct:false},{text:'الجفاء',correct:false},{text:'لا شيء',correct:false}]},
  },
  {
    id:'u1l4q22', unit:'unit1', lesson:'u1l4', page:17, type:'trueFalse',
    bloom:'understand', difficulty:'medium',
    question:'الجار في القصة غضب من جارته لأنها لم تطلب المساعدة.',
    paragraph:'الجار لم يغضب، بل بادر بمساعدتها. (ص17-18)',
    correctAnswer:false,
    explanation:'الجار لم يغضب، بل بادر بمساعدة جارته دون طلب.',
    goldenRule:'المسلم يبادر بالخير ولا ينتظر طلباً ولا يغضب.',
    feedbackQuestion:{question:'هل ينبغي للمسلم أن ينتظر طلب المساعدة؟',options:[{text:'لا، يبادر',correct:true},{text:'نعم',correct:false},{text:'أحياناً',correct:false},{text:'لا أدري',correct:false}]},
  },
  {
    id:'u1l4q23', unit:'unit1', lesson:'u1l4', page:18, type:'fillBlank',
    bloom:'apply', difficulty:'medium',
    question:'أكمل: «في نهاية القصة، قالت الجارة لجارها: ___ يا جاري»',
    paragraph:'النهاية: «شُكْرًا يا جارتي» على إحسانه. (ص19)',
    blanks:['شُكْرًا'],
    wordBank:['شُكْرًا','عذرًا','سلامٌ','وداعاً'],
    explanation:'قالت الجارة: «شُكْرًا يا جارتي» على إحسانه.',
    goldenRule:'الشكر على المعروف = أدب وفضل. لذلك سميت القصة به.',
  },
  {
    id:'u1l4q24', unit:'unit1', lesson:'u1l4', page:19, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'ما العبرة الأعمق من قصة «شُكْرًا يا جارتي»؟',
    paragraph:'العبرة: الإحسان إلى الجار يبني المودة والشكر يزيد النعمة. (ص16-19)',
    options:[
      {text:'الإحسان إلى الجار يبني المودة',correct:true},
      {text:'الأنانية تبني المجتمع',correct:false},
      {text:'الكذب يبني الثقة',correct:false},
      {text:'الظلم يبني العدل',correct:false},
    ],
    explanation:'العبرة: الإحسان إلى الجار يبني المودة والشكر يزيد النعمة.',
    goldenRule:'العبرة = إحسان + شكر + مودة + مجتمع فاضل.',
    feedbackQuestion:{question:'ما الذي يبنيه الإحسان بين الجيران؟',options:[{text:'المودة والألفة',correct:true},{text:'الكراهية',correct:false},{text:'القطيعة',correct:false},{text:'الجفاء',correct:false}]},
  },
  {
    id:'u1l4q25', unit:'unit1', lesson:'u1l4', page:16, type:'ordering',
    bloom:'apply', difficulty:'medium',
    question:'رتّب عناصر القصة من البداية للنهاية:',
    paragraph:'العناصر: المكان والشخصيات ← المشكلة ← الحل ← النهاية. (ص16-19)',
    items:['الحل (الإحسان)','المكان والشخصيات','النهاية (الشكر)','المشكلة (المرض)'],
    correctOrder:[1,3,0,2],
    explanation:'الترتيب: المكان والشخصيات ← المشكلة ← الحل ← النهاية.',
    goldenRule:'هيكل القصة: بداية ← مشكلة ← حل ← نهاية.',
  },
  {
    id:'u1l4q26', unit:'unit1', lesson:'u1l4', page:17, type:'trueFalse',
    bloom:'remember', difficulty:'easy',
    question:'من أفعال الإحسان في القصة: تنظيف المنزل وزيارته.',
    paragraph:'الأفعال: تنظيف المنزل، إحضار الطعام، الزيارة. (ص17-18)',
    correctAnswer:true,
    explanation:'نعم، تنظيف المنزل والزيارة من أفعال الإحسان في القصة.',
    goldenRule:'الإحسان = أفعال خير + أقوال طيبة + مراعاة.',
    feedbackQuestion:{question:'أيٌّ مما يلي فعل إحسان في القصة؟',options:[{text:'تنظيف المنزل',correct:true},{text:'الإيذاء',correct:false},{text:'السبّ',correct:false},{text:'الضوضاء',correct:false}]},
  },
  {
    id:'u1l4q27', unit:'unit1', lesson:'u1l4', page:18, type:'classify',
    bloom:'analyze', difficulty:'medium',
    question:'صنّف: ما الذي يدل على حسن الخلق وما يدل على ضده؟',
    paragraph:'حسن الخلق: مبادرة، إحسان، شكر. ضده: إهمال، أنانية، جحود. (ص16-19)',
    categories:['حسن خلق ✅','سوء خلق ❌'],
    items:[
      {text:'مبادرة الجار بالخير',correct_category:0},
      {text:'إهمال الجار المحتاج',correct_category:1},
      {text:'شكر الجارة للإحسان',correct_category:0},
      {text:'جحود المعروف',correct_category:1},
      {text:'الزيارة والمراعاة',correct_category:0},
      {text:'القطيعة والجفاء',correct_category:1},
    ],
    explanation:'حسن: مبادرة، شكر، زيارة. سوء: إهمال، جحود، قطيعة.',
    goldenRule:'حسن الخلق = مبادرة + إحسان + شكر + زيارة.',
  },
  {
    id:'u1l4q28', unit:'unit1', lesson:'u1l4', page:16, type:'multipleChoice',
    bloom:'understand', difficulty:'medium',
    question:'الجيرة في الإسلام لها حقوق، منها:',
    paragraph:'حقوق الجار: الإحسان، عدم الإيذاء، الزيارة، إغاثة الملهوف. (ص16)',
    options:[
      {text:'الإحسان وعدم الإيذاء',correct:true},
      {text:'الإيذاء',correct:false},
      {text:'القطيعة',correct:false},
      {text:'الجفاء',correct:false},
    ],
    explanation:'من حقوق الجار: الإحسان إليه وعدم إيذائه وزيارته وإغاثته.',
    goldenRule:'حقوق الجار = إحسان + لا إيذاء + زيارة + إغاثة.',
    feedbackQuestion:{question:'إيذاء الجار بالضوضاء:',options:[{text:'حرام',correct:true},{text:'حلال',correct:false},{text:'مكروه',correct:false},{text:'مستحب',correct:false}]},
  },
  {
    id:'u1l4q29', unit:'unit1', lesson:'u1l4', page:19, type:'trueFalse',
    bloom:'evaluate', difficulty:'medium',
    question:'قصة «شُكْرًا يا جارتي» تُعلّم أن الجار الصالح يبادر بالخير ويشكر على المعروف.',
    paragraph:'القصة: مبادرة بالخير + شكر على المعروف. (ص16-19)',
    correctAnswer:true,
    explanation:'القصة تُعلّم المبادرة بالخير والشكر على المعروف بين الجيران.',
    goldenRule:'القصة تُعلّم: مبادرة + إحسان + شكر + حسن خلق.',
    feedbackQuestion:{question:'ماذا تُعلّم قصة «شُكْرًا يا جارتي»؟',options:[{text:'المبادرة بالخير والشكر',correct:true},{text:'الأنانية',correct:false},{text:'الإيذاء',correct:false},{text:'القطيعة',correct:false}]},
  },
  {
    id:'u1l4q30', unit:'unit1', lesson:'u1l4', page:17, type:'multipleChoice',
    bloom:'remember', difficulty:'easy',
    question:'من وسائل الإحسان في القصة التي قام بها الجار:',
    paragraph:'الوسائل: إحضار الطعام، تنظيف المنزل، الزيارة. (ص17-18)',
    options:[
      {text:'إحضار الطعام والزيارة',correct:true},
      {text:'السبّ والشتم',correct:false},
      {text:'الضوضاء',correct:false},
      {text:'الإهمال',correct:false},
    ],
    explanation:'من وسائل الإحسان: إحضار الطعام والزيارة والتنظيف.',
    goldenRule:'وسائل الإحسان = طعام + زيارة + تنظيف + مراعاة.',
    feedbackQuestion:{question:'أيٌّ مما يلي وسيلة إحسان للجار؟',options:[{text:'إحضار الطعام',correct:true},{text:'الضوضاء',correct:false},{text:'السبّ',correct:false},{text:'الإهمال',correct:false}]},
  },
  {
    id:'u1l4q31', unit:'unit1', lesson:'u1l4', page:18, type:'fillBlank',
    bloom:'apply', difficulty:'medium',
    question:'أكمل: «في القصة، ___ الجار جارته المريضة، ف___ له»',
    paragraph:'الأحداث: أحسن الجار، فشكرت الجارة. (ص16-19)',
    blanks:['أحسن','شكرت'],
    wordBank:['أحسن','شكرت','أهمل','ترك'],
    explanation:'أحسن الجار لجارته، فشكرت له إحسانه.',
    goldenRule:'الإحسان يُولّد الشكر، والشكر يكثر المودة.',
  },
  {
    id:'u1l4q32', unit:'unit1', lesson:'u1l4', page:16, type:'trueFalse',
    bloom:'understand', difficulty:'easy',
    question:'القصة تدور حول علاقة جوار قائمة على الإحسان.',
    paragraph:'القصة: علاقة جوار قائمة على الإحسان والشكر. (ص16-19)',
    correctAnswer:true,
    explanation:'نعم، القصة تدور حول علاقة جوار قائمة على الإحسان والشكر.',
    goldenRule:'جوهر القصة = علاقة جوار + إحسان + شكر.',
    feedbackQuestion:{question:'علاقة الجوار في القصة قائمة على:',options:[{text:'الإحسان والشكر',correct:true},{text:'الإيذاء',correct:false},{text:'القطيعة',correct:false},{text:'الجفاء',correct:false}]},
  },
  {
    id:'u1l4q33', unit:'unit1', lesson:'u1l4', page:19, type:'multipleChoice',
    bloom:'evaluate', difficulty:'hard',
    question:'لو لم يُحسن الجار إلى جارته، ماذا كان يحدث؟',
    paragraph:'لو لم يُحسن: بقيت الجارة في ضيقها وعجزها. (ص16-19)',
    options:[
      {text:'بقيت الجارة في ضيقها وعجزها',correct:true},
      {text:'لا شيء يتغير',correct:false},
      {text:'تتحسن حالها',correct:false},
      {text:'لا تأثير',correct:false},
    ],
    explanation:'لو لم يُحسن الجار، لبقيت الجارة في ضيقها وعجزها.',
    goldenRule:'الإحسان = راحة للمحتاج + أجر للفاعل + مودة للجميع.',
    feedbackQuestion:{question:'ماذا يحدث لو ترك الجار جارته دون مساعدة؟',options:[{text:'تبقى في ضيقها',correct:true},{text:'تتحسن حالها',correct:false},{text:'لا شيء',correct:false},{text:'تفرح',correct:false}]},
  },
  {
    id:'u1l4q34', unit:'unit1', lesson:'u1l4', page:16, type:'ordering',
    bloom:'apply', difficulty:'medium',
    question:'رتّب ما تعلّمناه من القصة حسب الأولوية:',
    paragraph:'القيم: الإحسان → الشكر → المودة → المجتمع الفاضل. (ص16-19)',
    items:['المودة','الإحسان','المجتمع الفاضل','الشكر'],
    correctOrder:[1,3,0,2],
    explanation:'الترتيب: إحسان ← شكر ← مودة ← مجتمع فاضل.',
    goldenRule:'الإحسان يبني المودة والشكر، والمودة تبني المجتمع الفاضل.',
  },
  {
    id:'u1l4q35', unit:'unit1', lesson:'u1l4', page:19, type:'trueFalse',
    bloom:'evaluate', difficulty:'hard',
    question:'قصة «شُكْرًا يا جارتي» تؤكد أن الإسلام يحث على الإحسان للجار.',
    paragraph:'الإسلام: يحث على الإحسان للجار وعدم إيذائه. (ص16)',
    correctAnswer:true,
    explanation:'القصة تؤكد أن الإسلام يحث على الإحسان للجار وعدم إيذائه.',
    goldenRule:'الإسلام = إحسان للجار + نهي عن الإيذاء + شكر على المعروف.',
    feedbackQuestion:{question:'ماذا يحث الإسلام على فعله تجاه الجار؟',options:[{text:'الإحسان',correct:true},{text:'الإيذاء',correct:false},{text:'القطيعة',correct:false},{text:'الجفاء',correct:false}]},
  },
];

export const UNIT1_PART1 = [...U1L1_QS, ...U1L2_QS, ...U1L3_QS, ...U1L4_QS];