// Unit 3: Stories — Extra Questions Batch 2
export const UNIT3_EXTRA2 = {
  u3_l1: [
    { id:'u3_l1x2_1', type:'multipleChoice', bloom:'remember', difficulty:'easy',
      question_en:'The past of "clean" is:',
      paragraph:'Regular verb: clean + ed = cleaned.',
      options_en:['cleaned','cleant','cleans','cleaning'], correct:0,
      explanation_en:'clean → cleaned (regular: +ed).',
      golden_rule_en:'Regular: base + ed. clean → cleaned.',
      feedbackQuestion:{ question_en:'The past of "walk" is:', options_en:['walked','walkt','walks','walking'], correct:0, explanation_en:'walk → walked.' } },
    { id:'u3_l1x2_2', type:'trueFalse', bloom:'understand', difficulty:'medium',
      question_en:'"Did she played football?" is a correct past question.',
      paragraph:'After Did → base verb: play (NOT played).',
      options_en:['True','False'], correct:'false',
      explanation_en:'FALSE. Did + base: Did she play (NOT played).',
      golden_rule_en:'Did + subject + BASE verb. ❌ Did she played | ✓ Did she play.',
      feedbackQuestion:{ question_en:'Did he ( go – went ) to school?', options_en:['went','go','going','gone'], correct:1, explanation_en:'Did + base: go.' } },
    { id:'u3_l1x2_3', type:'multipleChoice', bloom:'apply', difficulty:'medium',
      question_en:'The past of "carry" is:',
      paragraph:'Regular verb ending in consonant+y: y → ied. carry → carried.',
      options_en:['carried','carryed','carried','carryied'], correct:0,
      explanation_en:'carry → carried (y → ied). Regular.',
      golden_rule_en:'Consonant + y → ied. carry → carried, study → studied.',
      feedbackQuestion:{ question_en:'The past of "study" is:', options_en:['studyed','studied','studys','studying'], correct:1, explanation_en:'study → studied.' } },
    { id:'u3_l1x2_4', type:'classify', bloom:'analyze', difficulty:'hard',
      question_en:'Classify: Regular or Irregular past verbs?',
      paragraph:'Regular: +ed. Irregular: special forms.',
      categories:['Regular (+ed)','Irregular (special)'],
      items:[
        { text:'play → played', correct_category:0 },
        { text:'go → went', correct_category:1 },
        { text:'walk → walked', correct_category:0 },
        { text:'see → saw', correct_category:1 },
        { text:'dream → dreamed', correct_category:0 },
        { text:'sleep → slept', correct_category:1 },
      ],
      explanation_en:'Regular: +ed. Irregular: went, saw, slept.',
      golden_rule_en:'Regular: +ed | Irregular: went, saw, slept, took, came.',
      feedbackQuestion:{ question_en:'"play → played" is:', options_en:['regular','irregular','both','neither'], correct:0, explanation_en:'played = +ed = regular.' } },
    { id:'u3_l1x2_5', type:'matching', bloom:'remember', difficulty:'easy',
      question_en:'Match the verb with its past form:',
      paragraph:'Regular past: dream→dreamed, plan→planned, play→played, carry→carried, score→scored.',
      pairs:[
        { left:'dream', right:'dreamed' },
        { left:'plan', right:'planned' },
        { left:'play', right:'played' },
        { left:'score', right:'scored' },
      ],
      explanation_en:'Regular verbs: add -ed. CVC → double consonant. y → ied.',
      golden_rule_en:'+ed | CVC → double (plan→planned) | y → ied (carry→carried).',
      feedbackQuestion:{ question_en:'The past of "plan" is:', options_en:['planed','planned','plant','planning'], correct:1, explanation_en:'CVC → double n: planned.' } },
    { id:'u3_l1x2_6', type:'multipleChoice', bloom:'apply', difficulty:'medium',
      question_en:'She didn\'t ( watched – watch – watching ) TV yesterday.',
      paragraph:'After didn\'t → base verb: watch (NOT watched).',
      options_en:['watched','watch','watching','watches'], correct:1,
      explanation_en:'didn\'t + base: watch. She didn\'t watch TV.',
      golden_rule_en:'didn\'t + BASE verb. No -ed, no -ing, no -s.',
      feedbackQuestion:{ question_en:'Did you ( play – played ) football?', options_en:['played','play','playing','plays'], correct:1, explanation_en:'Did + base: play.' } },
    { id:'u3_l1x2_7', type:'trueFalse', bloom:'apply', difficulty:'medium',
      question_en:'"I didn\'t goed to school" is correct.',
      paragraph:'didn\'t + base verb: go. Also, go → went (irregular).',
      options_en:['True','False'], correct:'false',
      explanation_en:'FALSE. didn\'t + base: go. "I didn\'t go" (NOT "goed" or "went").',
      golden_rule_en:'didn\'t + BASE. Even irregular → base after didn\'t.',
      feedbackQuestion:{ question_en:'She didn\'t ( see – saw ) the movie.', options_en:['saw','see','seeing','seen'], correct:1, explanation_en:'didn\'t + base: see.' } },
    { id:'u3_l1x2_8', type:'fillBlank', bloom:'apply', difficulty:'medium',
      question_en:'Yesterday, I _____ to school by bus. (go - irregular)',
      paragraph:'go → went (irregular). Yesterday = past.',
      blanks:['went'], wordBank:['went','goed','go','going'],
      explanation_en:'go → went. Yesterday I went to school.',
      golden_rule_en:'Irregular: go → went.',
      feedbackQuestion:{ question_en:'Last week, she _____ a movie. (see)', options_en:['saw','seed','see','seen'], correct:0, explanation_en:'see → saw.' } },
    { id:'u3_l1x2_9', type:'multipleChoice', bloom:'understand', difficulty:'medium',
      question_en:'The story "The Kind Man" has a setting that is:',
      paragraph:'Setting = where the story happens. The Kind Man: on top of a mountain.',
      options_en:['in a city','on the top of a mountain','at school','at the beach'], correct:1,
      explanation_en:'The Kind Man: setting = on the top of a mountain.',
      golden_rule_en:'Setting = مكان القصة. The Kind Man → on top of a mountain.',
      feedbackQuestion:{ question_en:'The CHARACTERS of "The Kind Man" are:', options_en:['an old man and two young friends','kings','animals','children only'], correct:0, explanation_en:'Characters = old man + 2 young friends.' } },
    { id:'u3_l1x2_10', type:'multipleChoice', bloom:'apply', difficulty:'hard',
      question_en:'Choose the correct sentence:',
      paragraph:'Past: Did + base. didn\'t + base. Irregular past forms.',
      options_en:['Did she go to school?','Did she went to school?','Did she goes to school?','Did she going to school?'], correct:0,
      explanation_en:'Did + base: go. Did she go to school?',
      golden_rule_en:'Did + subject + BASE verb.',
      feedbackQuestion:{ question_en:'She didn\'t ( take – took ) the bus.', options_en:['took','take','taking','taken'], correct:1, explanation_en:'didn\'t + base: take.' } },
  ],
  u3_l2: [
    { id:'u3_l2x2_1', type:'matching', bloom:'remember', difficulty:'easy',
      question_en:'Match the irregular verb with its past form:',
      paragraph:'Irregular: come→came, eat→ate, write→wrote, run→ran, give→gave, sing→sang.',
      pairs:[
        { left:'come', right:'came' },
        { left:'eat', right:'ate' },
        { left:'write', right:'wrote' },
        { left:'run', right:'ran' },
      ],
      explanation_en:'Irregular verbs: unique past forms. Must be memorized.',
      golden_rule_en:'Irregular: come→came, eat→ate, write→wrote, run→ran, give→gave.',
      feedbackQuestion:{ question_en:'The past of "eat" is:', options_en:['eated','ate','eats','eating'], correct:1, explanation_en:'eat → ate.' } },
    { id:'u3_l2x2_2', type:'multipleChoice', bloom:'apply', difficulty:'medium',
      question_en:'She ( go – goes – went ) to the market yesterday.',
      paragraph:'Yesterday = past. go → went (irregular).',
      options_en:['go','goes','went','going'], correct:2,
      explanation_en:'Yesterday = past → went (irregular: go → went).',
      golden_rule_en:'Past + irregular verb → special past form.',
      feedbackQuestion:{ question_en:'He ( see – saw – seen ) a bird last night.', options_en:['see','saw','seen','sees'], correct:1, explanation_en:'see → saw.' } },
    { id:'u3_l2x2_3', type:'trueFalse', bloom:'apply', difficulty:'medium',
      question_en:'"I goed to the park" is correct.',
      paragraph:'go is irregular → went. NOT "goed".',
      options_en:['True','False'], correct:'false',
      explanation_en:'FALSE. go → went (irregular). Never "goed".',
      golden_rule_en:'go → went. Never "goed".',
      feedbackQuestion:{ question_en:'I _____ to the park yesterday. (go)', options_en:['goed','went','go','going'], correct:1, explanation_en:'go → went.' } },
    { id:'u3_l2x2_4', type:'classify', bloom:'apply', difficulty:'medium',
      question_en:'Classify: Regular or Irregular?',
      paragraph:'Regular: +ed. Irregular: special forms.',
      categories:['Regular (+ed)','Irregular'],
      items:[
        { text:'play → played', correct_category:0 },
        { text:'go → went', correct_category:1 },
        { text:'walk → walked', correct_category:0 },
        { text:'see → saw', correct_category:1 },
        { text:'dream → dreamed', correct_category:0 },
        { text:'sleep → slept', correct_category:1 },
      ],
      explanation_en:'Regular: +ed. Irregular: went, saw, slept.',
      golden_rule_en:'Regular: +ed | Irregular: went, saw, took, slept.',
      feedbackQuestion:{ question_en:'"See → saw" is:', options_en:['regular','irregular','both','neither'], correct:1, explanation_en:'saw ≠ seed. Irregular.' } },
    { id:'u3_l2x2_5', type:'fillBlank', bloom:'apply', difficulty:'medium',
      question_en:'Last night, I _____ well. (sleep - irregular)',
      paragraph:'sleep → slept (irregular).',
      blanks:['slept'], wordBank:['slept','sleeped','sleep','sleeping'],
      explanation_en:'sleep → slept. Last night I slept well.',
      golden_rule_en:'Irregular: sleep→slept, keep→kept, sweep→swept.',
      feedbackQuestion:{ question_en:'She _____ a photo. (take)', options_en:['taked','took','take','taking'], correct:1, explanation_en:'take → took.' } },
    { id:'u3_l2x2_6', type:'multipleChoice', bloom:'understand', difficulty:'medium',
      question_en:'"Did she go to school?" — Correct short answer:',
      paragraph:'Did...? → Yes, she did. / No, she didn\'t.',
      options_en:['Yes, she went.','Yes, she did.','No, she don\'t.','Yes, she does.'], correct:1,
      explanation_en:'Short answer: Yes, she did. / No, she didn\'t. Use did/didn\'t.',
      golden_rule_en:'Did...? → Yes, I did. / No, I didn\'t.',
      feedbackQuestion:{ question_en:'"Did they come?" — Negative short:', options_en:['No, they don\'t.','No, they didn\'t.','No, they weren\'t.','No, they aren\'t.'], correct:1, explanation_en:'No, they didn\'t.' } },
    { id:'u3_l2x2_7', type:'trueFalse', bloom:'remember', difficulty:'easy',
      question_en:'"Go → went" is an irregular past form.',
      paragraph:'go is irregular: went (not +ed).',
      options_en:['True','False'], correct:'true',
      explanation_en:'Correct! go → went is irregular.',
      golden_rule_en:'Irregular: go→went, see→saw, take→took, sleep→slept.',
      feedbackQuestion:{ question_en:'"Walk → walked" is:', options_en:['regular','irregular','both','neither'], correct:0, explanation_en:'walk + ed = regular.' } },
    { id:'u3_l2x2_8', type:'multipleChoice', bloom:'apply', difficulty:'hard',
      question_en:'Choose the correct sentence:',
      paragraph:'didn\'t + base. Did + base. Irregular verbs.',
      options_en:['She didn\'t go to school.','She didn\'t went to school.','She didn\'t goes to school.','She didn\'t going to school.'], correct:0,
      explanation_en:'didn\'t + base: go. She didn\'t go to school.',
      golden_rule_en:'didn\'t + BASE verb (even irregular → base).',
      feedbackQuestion:{ question_en:'Did you ( take – took ) the bus?', options_en:['took','take','taking','taken'], correct:1, explanation_en:'Did + base: take.' } },
    { id:'u3_l2x2_9', type:'matching', bloom:'remember', difficulty:'easy',
      question_en:'Match the irregular verb with its past form:',
      paragraph:'More irregular: send→sent, spend→spent, build→built, think→thought, buy→bought, teach→taught.',
      pairs:[
        { left:'send', right:'sent' },
        { left:'spend', right:'spent' },
        { left:'build', right:'built' },
        { left:'buy', right:'bought' },
      ],
      explanation_en:'More irregular verbs with unique past forms.',
      golden_rule_en:'Irregular: send→sent, spend→spent, build→built, buy→bought.',
      feedbackQuestion:{ question_en:'The past of "send" is:', options_en:['sended','sent','send','sending'], correct:1, explanation_en:'send → sent.' } },
    { id:'u3_l2x2_10', type:'multipleChoice', bloom:'analyze', difficulty:'hard',
      question_en:'Which sentence has a MISTAKE?',
      paragraph:'Rules: didn\'t + base. Did + base. Irregular verbs have special forms.',
      options_en:['She went home.','She didn\'t go home.','She goed home.','Did she go home?'], correct:2,
      explanation_en:'"She goed home" is WRONG. go → went (irregular, not "goed").',
      golden_rule_en:'go → went. Never "goed".',
      feedbackQuestion:{ question_en:'Which is correct?', options_en:['He didn\'t went.','He didn\'t go.','He didn\'t goes.','He didn\'t going.'], correct:1, explanation_en:'didn\'t + base: go.' } },
  ],
};