// Unit 1: Family Events — Extra Questions
export const UNIT1_EXTRA = {
  u1_l1: [
    { id:'u1_l1_e1', type:'multipleChoice', bloom:'remember', difficulty:'easy',
      question_en:'My father\'s sister is my:',
      paragraph:'Family: father\'s sister = aunt (عمة/خالة) | father\'s brother = uncle (عم/خال).',
      options_en:['cousin','aunt','uncle','grandma'], correct:1,
      explanation_en:'Father\'s sister = aunt (عمة). Father\'s brother = uncle (عم).',
      golden_rule_en:'aunt = father/mother\'s sister | uncle = father/mother\'s brother.',
      feedbackQuestion:{ question_en:'My mother\'s brother is my:', options_en:['uncle','aunt','cousin','grandpa'], correct:0, explanation_en:'Mother\'s brother = uncle (خال).' } },
    { id:'u1_l1_e2', type:'trueFalse', bloom:'understand', difficulty:'easy',
      question_en:'My uncle\'s children are my cousins.',
      paragraph:'cousin = ابن العم/العمة/الخال/الخالة. Uncle\'s children = cousins.',
      options_en:['True','False'], correct:'true',
      explanation_en:'Correct! Uncle\'s children = cousins (أبناء العم/الخال).',
      golden_rule_en:'cousin = uncle/aunt\'s children.',
      feedbackQuestion:{ question_en:'My aunt\'s son is my:', options_en:['brother','cousin','uncle','nephew'], correct:1, explanation_en:'Aunt\'s son = cousin.' } },
    { id:'u1_l1_e3', type:'multipleChoice', bloom:'remember', difficulty:'easy',
      question_en:'A child who does not behave well is:',
      paragraph:'naughty = شقي = badly-behaved. A naughty child doesn\'t follow rules.',
      options_en:['helpful','naughty','brilliant','shy'], correct:1,
      explanation_en:'naughty = شقي = doesn\'t behave well.',
      golden_rule_en:'naughty = badly-behaved = شقي.',
      feedbackQuestion:{ question_en:'A _____ child never listens to his parents.', options_en:['helpful','naughty','shy','brilliant'], correct:1, explanation_en:'naughty = doesn\'t listen.' } },
    { id:'u1_l1_e4', type:'classify', bloom:'apply', difficulty:'medium',
      question_en:'Classify: Formal or Informal family words?',
      paragraph:'Formal: aunt, mom, dad, grandma, grandpa | Informal: aunty, mommy, daddy, granny, grandpa.',
      categories:['Formal (رسمي)','Informal (غير رسمي)'],
      items:[
        { text:'grandfather', correct_category:0 },
        { text:'grandpa', correct_category:1 },
        { text:'mother', correct_category:0 },
        { text:'mommy', correct_category:1 },
        { text:'father', correct_category:0 },
        { text:'daddy', correct_category:1 },
      ],
      explanation_en:'Formal words are official. Informal are affectionate/childish versions.',
      golden_rule_en:'Formal: grandfather, mother, father | Informal: grandpa, mommy, daddy.',
      feedbackQuestion:{ question_en:'"Daddy" is the _____ form of "father".', options_en:['formal','informal','plural','past'], correct:1, explanation_en:'daddy = informal.' } },
    { id:'u1_l1_e5', type:'matching', bloom:'remember', difficulty:'easy',
      question_en:'Match the family word with its Arabic meaning:',
      paragraph:'Family vocabulary: parents, grandparents, grandchildren, cousins, aunt, uncle.',
      pairs:[
        { left:'grandparents', right:'الأجداد' },
        { left:'grandchildren', right:'الأحفاد' },
        { left:'cousins', right:'أبناء العم/الخال' },
        { left:'parents', right:'الوالدان' },
      ],
      explanation_en:'Match each family word with its Arabic meaning.',
      golden_rule_en:'parents=الوالدان | grandparents=الأجداد | grandchildren=الأحفاد | cousins=أبناء العم/الخال.',
      feedbackQuestion:{ question_en:'My mother\'s parents are my:', options_en:['parents','grandparents','cousins','children'], correct:1, explanation_en:'Mother\'s parents = grandparents.' } },
    { id:'u1_l1_e6', type:'multipleChoice', bloom:'understand', difficulty:'medium',
      question_en:'Nada is my mom\'s sister. She is my:',
      paragraph:'Mom\'s sister = aunt (خالة). Dad\'s sister = aunt (عمة). Both = aunt.',
      options_en:['cousin','aunt','grandma','sister'], correct:1,
      explanation_en:'Mom\'s sister = aunt (خالة). In English, both عم and خالة = aunt.',
      golden_rule_en:'aunt = father\'s or mother\'s sister.',
      feedbackQuestion:{ question_en:'My father\'s brother is my:', options_en:['uncle','aunt','cousin','grandpa'], correct:0, explanation_en:'Father\'s brother = uncle.' } },
    { id:'u1_l1_e7', type:'trueFalse', bloom:'understand', difficulty:'medium',
      question_en:'"Chatty" and "shy" are opposites.',
      paragraph:'chatty = loves talking | shy = doesn\'t talk much. They are opposites.',
      options_en:['True','False'], correct:'true',
      explanation_en:'Correct! chatty = talks a lot, shy = doesn\'t talk much. They are opposites.',
      golden_rule_en:'chatty ↔ shy (opposites).',
      feedbackQuestion:{ question_en:'A person who doesn\'t talk much is:', options_en:['chatty','shy','helpful','lazy'], correct:1, explanation_en:'shy = doesn\'t talk much.' } },
    { id:'u1_l1_e8', type:'multipleChoice', bloom:'apply', difficulty:'medium',
      question_en:'My grandfather is old and _____. He can\'t lift heavy things.',
      paragraph:'weak = ضعيف (not strong) | strong = قوي. Opposites: weak ↔ strong.',
      options_en:['strong','weak','brilliant','chatty'], correct:1,
      explanation_en:'Can\'t lift heavy = not strong = weak (ضعيف).',
      golden_rule_en:'weak = ضعيف | strong = قوي. They are opposites.',
      feedbackQuestion:{ question_en:'My uncle is very _____. He can carry heavy boxes.', options_en:['weak','strong','shy','naughty'], correct:1, explanation_en:'Can carry heavy = strong.' } },
    { id:'u1_l1_e9', type:'fillBlank', bloom:'apply', difficulty:'medium',
      question_en:'My dad\'s father is my _____. (father\'s father)',
      paragraph:'Dad\'s father = grandfather (جد). Mom\'s father = grandfather too.',
      blanks:['grandfather'], wordBank:['grandfather','uncle','cousin','brother'],
      explanation_en:'Dad\'s father = grandfather (جد).',
      golden_rule_en:'grandfather = father/mother of your parents.',
      feedbackQuestion:{ question_en:'My mom\'s mother is my:', options_en:['aunt','grandmother','cousin','sister'], correct:1, explanation_en:'Mom\'s mother = grandmother.' } },
    { id:'u1_l1_e10', type:'classify', bloom:'apply', difficulty:'medium',
      question_en:'Classify: Male or Female family members?',
      paragraph:'Male: grandfather, father, uncle, brother, son | Female: grandmother, mother, aunt, sister, daughter.',
      categories:['Male (ذكر)','Female (أنثى)'],
      items:[
        { text:'grandfather', correct_category:0 },
        { text:'grandmother', correct_category:1 },
        { text:'uncle', correct_category:0 },
        { text:'aunt', correct_category:1 },
        { text:'nephew', correct_category:0 },
        { text:'niece', correct_category:1 },
      ],
      explanation_en:'Male family words: grandfather, uncle, nephew. Female: grandmother, aunt, niece.',
      golden_rule_en:'Male: -father, uncle, nephew | Female: -mother, aunt, niece.',
      feedbackQuestion:{ question_en:'"Niece" is a _____ family member.', options_en:['male','female','both','neither'], correct:1, explanation_en:'niece = female (بنت الأخ/الأخت).' } },
    { id:'u1_l1_e11', type:'multipleChoice', bloom:'remember', difficulty:'easy',
      question_en:'The opposite of "husband" is:',
      paragraph:'husband = زوج | wife = زوجة. They are opposites.',
      options_en:['wife','sister','aunt','mother'], correct:0,
      explanation_en:'husband ↔ wife. They are opposites (زوج / زوجة).',
      golden_rule_en:'husband ↔ wife | father ↔ mother | son ↔ daughter.',
      feedbackQuestion:{ question_en:'The opposite of "brother" is:', options_en:['sister','father','uncle','cousin'], correct:0, explanation_en:'brother ↔ sister.' } },
    { id:'u1_l1_e12', type:'trueFalse', bloom:'remember', difficulty:'easy',
      question_en:'"Grandchildren" means the children of your children.',
      paragraph:'grandchildren = أحفاد = the children of your children.',
      options_en:['True','False'], correct:'true',
      explanation_en:'Correct! grandchildren = أحفاد = your children\'s children.',
      golden_rule_en:'grandchildren = أحفاد (children of your children).',
      feedbackQuestion:{ question_en:'My son\'s son is my:', options_en:['grandson','granddaughter','cousin','nephew'], correct:0, explanation_en:'Son\'s son = grandson (حفيد).' } },
    { id:'u1_l1_e13', type:'multipleChoice', bloom:'understand', difficulty:'medium',
      question_en:'She talks all the time. She never stops talking. She is very _____.',
      paragraph:'chatty = loves talking a lot. Someone who talks all the time = chatty.',
      options_en:['shy','chatty','lazy','weak'], correct:1,
      explanation_en:'Talks all the time = chatty (محب للدردشة).',
      golden_rule_en:'chatty = talks a lot | shy = barely talks.',
      feedbackQuestion:{ question_en:'He never says a word. He is very _____.', options_en:['chatty','shy','naughty','helpful'], correct:1, explanation_en:'Never talks = shy.' } },
    { id:'u1_l1_e14', type:'matching', bloom:'remember', difficulty:'easy',
      question_en:'Match the adjective with its opposite:',
      paragraph:'Opposites: strong↔weak | chatty↔shy | husband↔wife | always↔never.',
      pairs:[
        { left:'strong', right:'weak' },
        { left:'chatty', right:'shy' },
        { left:'husband', right:'wife' },
        { left:'always', right:'never' },
      ],
      explanation_en:'These are opposite pairs from Unit 1.',
      golden_rule_en:'strong↔weak | chatty↔shy | husband↔wife | always↔never.',
      feedbackQuestion:{ question_en:'The opposite of "strong" is:', options_en:['weak','shy','chatty','helpful'], correct:0, explanation_en:'strong ↔ weak.' } },
    { id:'u1_l1_e15', type:'multipleChoice', bloom:'apply', difficulty:'medium',
      question_en:'"Mommy" is used by _____ children to call their mother.',
      paragraph:'Informal: mommy, daddy, granny = used by small children. Formal: mother, father.',
      options_en:['old','young','adult','tall'], correct:1,
      explanation_en:'"Mommy" is the informal/childish way young children call their mother.',
      golden_rule_en:'Informal (mommy, daddy, granny) = used by young children.',
      feedbackQuestion:{ question_en:'"Mother" is the _____ form of "mommy".', options_en:['informal','formal','plural','past'], correct:1, explanation_en:'mother = formal.' } },
  ],
  u1_l2: [
    { id:'u1_l2_e1', type:'multipleChoice', bloom:'remember', difficulty:'easy',
      question_en:'How often do you visit your grandparents? — "I _____ visit them." (80% of the time)',
      paragraph:'Adverbs of frequency: always(100%), usually(80%), often(60%), sometimes(50%), rarely(25%), never(0%).',
      options_en:['never','usually','rarely','sometimes'], correct:1,
      explanation_en:'80% = usually. always=100%, usually=80%, often=60%.',
      golden_rule_en:'always(100%) > usually(80%) > often(60%) > sometimes(50%) > rarely(25%) > never(0%).',
      feedbackQuestion:{ question_en:'I _____ eat pizza. (50% — sometimes yes, sometimes no)', options_en:['always','usually','sometimes','never'], correct:2, explanation_en:'50% = sometimes.' } },
    { id:'u1_l2_e2', type:'multipleChoice', bloom:'apply', difficulty:'medium',
      question_en:'How often ( do – does – did ) she play tennis?',
      paragraph:'How often + do (I/you/we/they) | does (he/she/it). Present tense.',
      options_en:['do','does','did','is'], correct:1,
      explanation_en:'"She" = 3rd person → does. How often does she play tennis?',
      golden_rule_en:'How often + do (I/you/we/they) | does (he/she/it).',
      feedbackQuestion:{ question_en:'How often ( do – does ) you go to the park?', options_en:['does','do','did','are'], correct:1, explanation_en:'you → do.' } },
    { id:'u1_l2_e3', type:'ordering', bloom:'apply', difficulty:'medium',
      question_en:'Reorder: usually / park / I / the / visit / on Fridays',
      paragraph:'Word order: Subject + Adverb of Frequency + Verb + Object + Time.',
      items:['I','usually','visit','the park','on Fridays'], correctOrder:[0,1,2,3,4],
      explanation_en:'I (subject) + usually (adverb) + visit (verb) + the park (object) + on Fridays (time).',
      golden_rule_en:'Subject + Adverb of Frequency + Main Verb + Object + Time.',
      feedbackQuestion:{ question_en:'Which is correct?', options_en:['I visit usually the park.','Usually I visit the park.','I usually visit the park.','I visit the park usually.'], correct:2, explanation_en:'I usually visit the park.' } },
    { id:'u1_l2_e4', type:'trueFalse', bloom:'understand', difficulty:'medium',
      question_en:'"Always" comes after the main verb in a sentence.',
      paragraph:'Adverb of frequency comes BEFORE the main verb. She always plays.',
      options_en:['True','False'], correct:'false',
      explanation_en:'FALSE. Adverb of frequency comes BEFORE the main verb: She always plays.',
      golden_rule_en:'Adverb of frequency + BEFORE main verb. She always plays. NOT "She plays always".',
      feedbackQuestion:{ question_en:'She _____ sleeps early. (always)', options_en:['always','sleeps always','always sleeps','sleeps'], correct:2, explanation_en:'always + sleeps: She always sleeps early.' } },
    { id:'u1_l2_e5', type:'multipleChoice', bloom:'apply', difficulty:'medium',
      question_en:'Omar usually ( go – goes – going ) to the park.',
      paragraph:'Simple Present: he/she/it + verb + s/es. Omar = he → goes.',
      options_en:['go','goes','going','gone'], correct:1,
      explanation_en:'Omar = he → goes (go + es). Simple Present routine.',
      golden_rule_en:'Simple Present: he/she/it + verb + s/es. go → goes, watch → watches.',
      feedbackQuestion:{ question_en:'She sometimes ( watch – watches – watching ) TV.', options_en:['watch','watches','watching','watched'], correct:1, explanation_en:'She → watches.' } },
    { id:'u1_l2_e6', type:'classify', bloom:'apply', difficulty:'medium',
      question_en:'Classify: High frequency or Low frequency?',
      paragraph:'High: always, usually, often. Low: rarely, never, seldom.',
      categories:['High frequency (عالي)','Low frequency (منخفض)'],
      items:[
        { text:'always', correct_category:0 },
        { text:'usually', correct_category:0 },
        { text:'often', correct_category:0 },
        { text:'sometimes', correct_category:1 },
        { text:'rarely', correct_category:1 },
        { text:'never', correct_category:1 },
      ],
      explanation_en:'always/usually/often = high. rarely/never/seldom = low. sometimes = middle.',
      golden_rule_en:'High: always, usually, often | Low: rarely, never, seldom.',
      feedbackQuestion:{ question_en:'"Rarely" is a _____ frequency adverb.', options_en:['high','low','medium','zero'], correct:1, explanation_en:'rarely = low frequency.' } },
    { id:'u1_l2_e7', type:'multipleChoice', bloom:'remember', difficulty:'easy',
      question_en:'Which adverb means 0% of the time?',
      paragraph:'never = 0% = the action does not happen at all.',
      options_en:['always','usually','sometimes','never'], correct:3,
      explanation_en:'never = 0% = the action never happens.',
      golden_rule_en:'never = 0% = لا يحدث أبداً.',
      feedbackQuestion:{ question_en:'Which adverb means 100% of the time?', options_en:['never','always','rarely','sometimes'], correct:1, explanation_en:'always = 100%.' } },
    { id:'u1_l2_e8', type:'trueFalse', bloom:'apply', difficulty:'medium',
      question_en:'"I never don\'t play football" is a correct sentence.',
      paragraph:'never is already negative. Don\'t use "don\'t" with "never". Double negative = wrong.',
      options_en:['True','False'], correct:'false',
      explanation_en:'FALSE. "never" is already negative. Don\'t use "don\'t" with it. Say: I never play football.',
      golden_rule_en:'never = already negative. Never use "don\'t" with "never". ❌ I don\'t never play.',
      feedbackQuestion:{ question_en:'Which is correct?', options_en:['I don\'t never play.','I never play.','I don\'t never go.','I never don\'t play.'], correct:1, explanation_en:'I never play (no double negative).' } },
    { id:'u1_l2_e9', type:'multipleChoice', bloom:'understand', difficulty:'medium',
      question_en:'"How often" is used to ask about:',
      paragraph:'How often = asks about frequency (كم مرة). How many = asks about quantity.',
      options_en:['time (when)','frequency (how often)','place (where)','reason (why)'], correct:1,
      explanation_en:'How often = asks about frequency (كم مرة يحدث الشيء).',
      golden_rule_en:'How often = frequency | When = time | Where = place | Why = reason.',
      feedbackQuestion:{ question_en:'"_____ do you go to the park?" — asks about frequency.', options_en:['When','How often','Where','Why'], correct:1, explanation_en:'How often = frequency.' } },
    { id:'u1_l2_e10', type:'fillBlank', bloom:'apply', difficulty:'medium',
      question_en:'I _____ eat vegetables. (25% — not often)',
      paragraph:'rarely = 25% = not often. Less than sometimes, more than never.',
      blanks:['rarely'], wordBank:['rarely','always','often','usually'],
      explanation_en:'25% = rarely. Not often but not zero.',
      golden_rule_en:'rarely = 25% = نادراً. Between sometimes and never.',
      feedbackQuestion:{ question_en:'I _____ drink water. (100% — every time)', options_en:['never','rarely','always','sometimes'], correct:2, explanation_en:'100% = always.' } },
    { id:'u1_l2_e11', type:'multipleChoice', bloom:'apply', difficulty:'medium',
      question_en:'My brother always ( cut – cuts – cutting ) the grass on Saturday.',
      paragraph:'Simple Present: my brother = he → verb + s. cut → cuts.',
      options_en:['cut','cuts','cutting','cuted'], correct:1,
      explanation_en:'My brother = he → cuts (add -s). "Always" = routine = Simple Present.',
      golden_rule_en:'he/she/it + verb + s. cut → cuts, run → runs, watch → watches.',
      feedbackQuestion:{ question_en:'She always ( wash – washes – washing ) the dishes.', options_en:['wash','washes','washing','washed'], correct:1, explanation_en:'She → washes (add -es after -ch).' } },
    { id:'u1_l2_e12', type:'trueFalse', bloom:'understand', difficulty:'medium',
      question_en:'"She usually go to school" is a correct sentence.',
      paragraph:'Simple Present: she → verb + s. go → goes (NOT "go").',
      options_en:['True','False'], correct:'false',
      explanation_en:'FALSE. She → goes (not "go"). Correct: She usually goes to school.',
      golden_rule_en:'he/she/it → verb + s/es. ❌ she go | ✓ she goes.',
      feedbackQuestion:{ question_en:'He always ( play – plays – playing ) football.', options_en:['play','plays','playing','played'], correct:1, explanation_en:'He → plays.' } },
    { id:'u1_l2_e13', type:'matching', bloom:'remember', difficulty:'easy',
      question_en:'Match the adverb with its percentage:',
      paragraph:'Adverbs of frequency percentages: always=100%, usually=80%, often=60%, sometimes=50%, rarely=25%, never=0%.',
      pairs:[
        { left:'always', right:'100%' },
        { left:'often', right:'60%' },
        { left:'sometimes', right:'50%' },
        { left:'never', right:'0%' },
      ],
      explanation_en:'Match each adverb of frequency with its correct percentage.',
      golden_rule_en:'always=100% | usually=80% | often=60% | sometimes=50% | rarely=25% | never=0%.',
      feedbackQuestion:{ question_en:'"Usually" means _____ of the time.', options_en:['100%','80%','50%','0%'], correct:1, explanation_en:'usually = 80%.' } },
    { id:'u1_l2_e14', type:'multipleChoice', bloom:'apply', difficulty:'hard',
      question_en:'Choose the correct sentence:',
      paragraph:'Adverb of frequency BEFORE main verb. Simple Present: he/she/it + s.',
      options_en:['She always plays tennis.','She plays always tennis.','Always she plays tennis.','She always play tennis.'], correct:0,
      explanation_en:'She (subject) + always (adverb) + plays (verb+s) + tennis. Correct!',
      golden_rule_en:'Subject + Adverb + verb(+s for he/she/it) + Object.',
      feedbackQuestion:{ question_en:'He usually ( go – goes ) to school by bus.', options_en:['go','goes','going','gone'], correct:1, explanation_en:'He → goes.' } },
    { id:'u1_l2_e15', type:'trueFalse', bloom:'remember', difficulty:'easy',
      question_en:'"Often" means more than "sometimes" but less than "always".',
      paragraph:'Order: always > usually > often > sometimes > rarely > never.',
      options_en:['True','False'], correct:'true',
      explanation_en:'Correct! often (60%) is between usually (80%) and sometimes (50%).',
      golden_rule_en:'always > usually > often > sometimes > rarely > never.',
      feedbackQuestion:{ question_en:'Which is MORE frequent?', options_en:['sometimes','always','rarely','never'], correct:1, explanation_en:'always = 100% = most frequent.' } },
  ],
  u1_l3: [
    { id:'u1_l3_e1', type:'multipleChoice', bloom:'remember', difficulty:'easy',
      question_en:'It is her bag. It is ( hers – her – she ).',
      paragraph:'Possessive pronoun replaces noun: her bag → it is hers.',
      options_en:['hers','her','she','herself'], correct:0,
      explanation_en:'"Her" → possessive pronoun = "hers". It is hers (not "her" — that\'s an adjective).',
      golden_rule_en:'my→mine | your→yours | his→his | her→hers | our→ours | their→theirs.',
      feedbackQuestion:{ question_en:'It is our house. It is:', options_en:['our','ours','us','ourselves'], correct:1, explanation_en:'our → ours.' } },
    { id:'u1_l3_e2', type:'trueFalse', bloom:'understand', difficulty:'medium',
      question_en:'"Whose" is used to ask about ownership/possession.',
      paragraph:'Whose = لمن = asks about ownership. Whose bag is this? → It is mine.',
      options_en:['True','False'], correct:'true',
      explanation_en:'Correct! Whose = asks about ownership. Whose book? → It is mine.',
      golden_rule_en:'Whose = ownership (لمن). Whose + noun? Whose pen is this?',
      feedbackQuestion:{ question_en:'"_____ car is this?" — asking who owns it.', options_en:['Who','Whose','How','What'], correct:1, explanation_en:'Whose = ownership.' } },
    { id:'u1_l3_e3', type:'multipleChoice', bloom:'apply', difficulty:'medium',
      question_en:'They are ( our – ours – us ) books.',
      paragraph:'Possessive adjective (our) comes BEFORE a noun. Possessive pronoun (ours) replaces it.',
      options_en:['our','ours','us','ourselves'], correct:0,
      explanation_en:'Before a noun (books) → possessive adjective "our". "Our books" not "ours books".',
      golden_rule_en:'Possessive adjective BEFORE noun: my, your, his, her, our, their. Possessive pronoun REPLACES noun: mine, yours, his, hers, ours, theirs.',
      feedbackQuestion:{ question_en:'These books are ( our – ours ).', options_en:['our','ours','us','we'], correct:1, explanation_en:'No noun after → possessive pronoun "ours".' } },
    { id:'u1_l3_e4', type:'classify', bloom:'apply', difficulty:'hard',
      question_en:'Classify: Possessive Adjective or Possessive Pronoun?',
      paragraph:'Adjective before noun (my book). Pronoun replaces noun (it\'s mine).',
      categories:['Possessive Adjective','Possessive Pronoun'],
      items:[
        { text:'my', correct_category:0 },
        { text:'mine', correct_category:1 },
        { text:'their', correct_category:0 },
        { text:'theirs', correct_category:1 },
        { text:'your', correct_category:0 },
        { text:'yours', correct_category:1 },
      ],
      explanation_en:'Adjectives: my, your, his, her, our, their (before noun). Pronouns: mine, yours, his, hers, ours, theirs (replace noun).',
      golden_rule_en:'Adjective (before noun): my, your, his, her, our, their | Pronoun (replaces noun): mine, yours, his, hers, ours, theirs.',
      feedbackQuestion:{ question_en:'"His" can be both adjective and pronoun. "Hers" is a:', options_en:['adjective only','pronoun only','both','neither'], correct:1, explanation_en:'hers = pronoun only. (his = both).' } },
    { id:'u1_l3_e5', type:'matching', bloom:'remember', difficulty:'easy',
      question_en:'Match the possessive adjective with its pronoun:',
      paragraph:'my→mine | your→yours | his→his | her→hers | our→ours | their→theirs.',
      pairs:[
        { left:'my', right:'mine' },
        { left:'his', right:'his' },
        { left:'our', right:'ours' },
        { left:'their', right:'theirs' },
      ],
      explanation_en:'Possessive pronouns replace the noun. my book → it is mine.',
      golden_rule_en:'my→mine | your→yours | his→his | her→hers | our→ours | their→theirs.',
      feedbackQuestion:{ question_en:'The pronoun of "her" is:', options_en:['her','hers','she','herself'], correct:1, explanation_en:'her → hers.' } },
    { id:'u1_l3_e6', type:'multipleChoice', bloom:'understand', difficulty:'medium',
      question_en:'"This is my pen" → Replace "my pen" with a pronoun:',
      paragraph:'Possessive pronoun replaces the noun phrase. my pen → mine.',
      options_en:['This is mine.','This is my.','This is me.','This is I.'], correct:0,
      explanation_en:'my → mine. "This is mine" replaces "my pen".',
      golden_rule_en:'To replace noun: my→mine, your→yours, his→his, her→hers, our→ours, their→theirs.',
      feedbackQuestion:{ question_en:'"These are their books" → Replace:', options_en:['These are their.','These are theirs.','These are them.','These are they.'], correct:1, explanation_en:'their → theirs.' } },
    { id:'u1_l3_e7', type:'trueFalse', bloom:'apply', difficulty:'medium',
      question_en:'"It is his" and "It is his book" are both correct.',
      paragraph:'"his" is both adjective (his book) and pronoun (it is his).',
      options_en:['True','False'], correct:'true',
      explanation_en:'Correct! "his" works as both adjective (his book) and pronoun (it is his). Unique!',
      golden_rule_en:'his = both adjective and pronoun. his book (adj) | it is his (pronoun).',
      feedbackQuestion:{ question_en:'"This is _____ hat." (possessive adjective)', options_en:['his','him','he','himself'], correct:0, explanation_en:'Before noun → adjective: his.' } },
    { id:'u1_l3_e8', type:'fillBlank', bloom:'apply', difficulty:'medium',
      question_en:'It is ( my / I ) book. It is _____ . (possessive pronoun)',
      paragraph:'my → mine. "my book" → "it is mine".',
      blanks:['mine'], wordBank:['mine','my','me','I'],
      explanation_en:'my → mine. The possessive pronoun replaces "my book".',
      golden_rule_en:'my → mine (pronoun replaces noun).',
      feedbackQuestion:{ question_en:'It is ( your / you ) car. It is _____ .', options_en:['your','yours','you','yourself'], correct:1, explanation_en:'your → yours.' } },
    { id:'u1_l3_e9', type:'multipleChoice', bloom:'remember', difficulty:'easy',
      question_en:'The possessive pronoun for "they" is:',
      paragraph:'their (adjective) → theirs (pronoun). These are theirs.',
      options_en:['their','theirs','them','they'], correct:1,
      explanation_en:'their → theirs. Possessive pronoun replaces the noun.',
      golden_rule_en:'their (adj) → theirs (pronoun). their books → they are theirs.',
      feedbackQuestion:{ question_en:'"These are _____ books." (adjective)', options_en:['their','theirs','them','they'], correct:0, explanation_en:'Before noun → adjective: their.' } },
    { id:'u1_l3_e10', type:'classify', bloom:'apply', difficulty:'medium',
      question_en:'Classify: Correct or Incorrect possessive pronoun use?',
      paragraph:'Pronoun replaces noun (no noun after). Adjective before noun.',
      categories:['Correct (صحيح)','Incorrect (خطأ)'],
      items:[
        { text:'It is mine.', correct_category:0 },
        { text:'It is mine book.', correct_category:1 },
        { text:'These are ours.', correct_category:0 },
        { text:'These are ours books.', correct_category:1 },
        { text:'This is hers.', correct_category:0 },
        { text:'This is hers pen.', correct_category:1 },
      ],
      explanation_en:'Pronouns stand alone (no noun after). Adjectives need a noun after them.',
      golden_rule_en:'Pronoun: NO noun after (it is mine). Adjective: noun after (my book).',
      feedbackQuestion:{ question_en:'Which is correct?', options_en:['It is hers.','It is hers bag.','It is her.','It is she.'], correct:0, explanation_en:'It is hers (pronoun, no noun after).' } },
    { id:'u1_l3_e11', type:'multipleChoice', bloom:'understand', difficulty:'medium',
      question_en:'"Whose pencil is this?" — "It is _____ ." (belongs to me)',
      paragraph:'Whose asks about ownership. Answer with possessive pronoun: mine, yours, his, hers.',
      options_en:['my','me','mine','I'], correct:2,
      explanation_en:'Belongs to me → mine. "It is mine" (possessive pronoun, no noun after).',
      golden_rule_en:'Whose + noun? → Answer: mine/yours/his/hers/ours/theirs.',
      feedbackQuestion:{ question_en:'"Whose bag is that?" — "It is _____ ." (belongs to her)', options_en:['her','hers','she','herself'], correct:1, explanation_en:'Belongs to her → hers.' } },
    { id:'u1_l3_e12', type:'trueFalse', bloom:'remember', difficulty:'easy',
      question_en:'"Hers" and "her" are the same word with the same use.',
      paragraph:'her = adjective (her book). hers = pronoun (it is hers). Different uses!',
      options_en:['True','False'], correct:'false',
      explanation_en:'FALSE. her = adjective (before noun: her book). hers = pronoun (replaces noun: it is hers).',
      golden_rule_en:'her = adjective (her book) | hers = pronoun (it is hers). NOT the same!',
      feedbackQuestion:{ question_en:'"This is _____ ring." (adjective before noun)', options_en:['hers','her','she','herself'], correct:1, explanation_en:'Before noun → adjective: her.' } },
    { id:'u1_l3_e13', type:'multipleChoice', bloom:'apply', difficulty:'hard',
      question_en:'Choose the correct sentence:',
      paragraph:'Possessive pronoun stands alone. Possessive adjective before noun.',
      options_en:['These pens are our.','These pens are ours.','These are ours pens.','These are our pens ours.'], correct:1,
      explanation_en:'"These pens are ours" — pronoun replaces noun. NOT "our" (adjective) after noun.',
      golden_rule_en:'After noun → pronoun (ours, theirs, his). Before noun → adjective (our, their, his).',
      feedbackQuestion:{ question_en:'"This is _____ car." (adjective before noun "car")', options_en:['ours','our','us','we'], correct:1, explanation_en:'Before noun → adjective: our.' } },
    { id:'u1_l3_e14', type:'matching', bloom:'apply', difficulty:'medium',
      question_en:'Match the question with the correct answer:',
      paragraph:'Whose questions → answer with possessive pronoun. How often → frequency.',
      pairs:[
        { left:'Whose bag is this?', right:'It is mine.' },
        { left:'Whose car is that?', right:'It is hers.' },
        { left:'Whose books are these?', right:'They are ours.' },
        { left:'Whose pencil is this?', right:'It is his.' },
      ],
      explanation_en:'Match Whose questions with possessive pronoun answers.',
      golden_rule_en:'Whose + noun? → It is mine/yours/his/hers/ours/theirs.',
      feedbackQuestion:{ question_en:'"Whose house is this?" — "It is _____ ." (belongs to them)', options_en:['their','theirs','them','they'], correct:1, explanation_en:'Belongs to them → theirs.' } },
    { id:'u1_l3_e15', type:'fillBlank', bloom:'remember', difficulty:'easy',
      question_en:'my → mine, your → yours, his → his, her → _____ .',
      paragraph:'Possessive pronouns: my→mine, your→yours, his→his, her→hers, our→ours, their→theirs.',
      blanks:['hers'], wordBank:['hers','her','she','herself'],
      explanation_en:'her → hers. Possessive pronoun replaces the noun.',
      golden_rule_en:'her → hers | our → ours | their → theirs.',
      feedbackQuestion:{ question_en:'our → _____ (possessive pronoun)', options_en:['our','ours','us','we'], correct:1, explanation_en:'our → ours.' } },
  ],
};