// Unit 4: After-School Fun — Extra Questions Batch 2
export const UNIT4_EXTRA2 = {
  u4_l1: [
    { id:'u4_l1x2_1', type:'multipleChoice', bloom:'remember', difficulty:'easy',
      question_en:'The adverb of "good" is:',
      paragraph:'good → well (irregular). He plays well, NOT "goodly".',
      options_en:['goodly','well','gooder','good'], correct:1,
      explanation_en:'good → well (irregular adverb).',
      golden_rule_en:'good (adjective) → well (adverb). Irregular!',
      feedbackQuestion:{ question_en:'She did the job _____ . (adverb of good)', options_en:['good','well','goodly','better'], correct:1, explanation_en:'good → well.' } },
    { id:'u4_l1x2_2', type:'trueFalse', bloom:'understand', difficulty:'medium',
      question_en:'"Quickly" is an adverb describing how an action is done.',
      paragraph:'Adverbs (often -ly) describe verbs.',
      options_en:['True','False'], correct:'true',
      explanation_en:'Correct! quickly = adverb describing how someone runs/works.',
      golden_rule_en:'Adverb (often -ly) describes a verb.',
      feedbackQuestion:{ question_en:'"She sings beautifully." — "beautifully" is a/an:', options_en:['noun','adjective','adverb','verb'], correct:2, explanation_en:'beautifully = adverb.' } },
    { id:'u4_l1x2_3', type:'multipleChoice', bloom:'apply', difficulty:'medium',
      question_en:'The adverb of "happy" is:',
      paragraph:'Adjective ending in consonant+y: y → ily. happy → happily.',
      options_en:['happyly','happily','happylier','happilier'], correct:1,
      explanation_en:'happy → happily (y → ily).',
      golden_rule_en:'Consonant + y → ily. happy→happily, lucky→luckily.',
      feedbackQuestion:{ question_en:'The adverb of "easy" is:', options_en:['easily','easyly','easilier','easylier'], correct:0, explanation_en:'easy → easily.' } },
    { id:'u4_l1x2_4', type:'classify', bloom:'apply', difficulty:'medium',
      question_en:'Classify: Adjective or Adverb?',
      paragraph:'Adjectives describe nouns. Adverbs (often -ly) describe verbs.',
      categories:['Adjective','Adverb'],
      items:[
        { text:'quick', correct_category:0 },
        { text:'quickly', correct_category:1 },
        { text:'slow', correct_category:0 },
        { text:'slowly', correct_category:1 },
        { text:'careful', correct_category:0 },
        { text:'carefully', correct_category:1 },
      ],
      explanation_en:'Adjective → noun | Adverb (-ly) → verb.',
      golden_rule_en:'Adjective: quick, slow, careful | Adverb: quickly, slowly, carefully.',
      feedbackQuestion:{ question_en:'She talks _____ . (how)', options_en:['loud','quietly','quiet','slow'], correct:1, explanation_en:'talks (verb) → quietly.' } },
    { id:'u4_l1x2_5', type:'matching', bloom:'remember', difficulty:'easy',
      question_en:'Match the adjective with its adverb form:',
      paragraph:'Adjective + ly = adverb. y → ily. good → well (irregular).',
      pairs:[
        { left:'quick', right:'quickly' },
        { left:'slow', right:'slowly' },
        { left:'happy', right:'happily' },
        { left:'good', right:'well' },
      ],
      explanation_en:'Match each adjective with its adverb form.',
      golden_rule_en:'+ly (y→ily). Irregular: good→well.',
      feedbackQuestion:{ question_en:'The adverb of "careful" is:', options_en:['carefuly','carefully','carefullier','careful'], correct:1, explanation_en:'careful + ly = carefully.' } },
    { id:'u4_l1x2_6', type:'multipleChoice', bloom:'remember', difficulty:'easy',
      question_en:'"Dominoes" is a type of:',
      paragraph:'After-school: board games (dominoes, chess, checkers).',
      options_en:['outdoor sport','board game','musical instrument','school subject'], correct:1,
      explanation_en:'Dominoes is a board game.',
      golden_rule_en:'Board games: dominoes, chess, checkers.',
      feedbackQuestion:{ question_en:'"Vlogging" means:', options_en:['playing football','making video blogs','reading books','playing piano'], correct:1, explanation_en:'vlogging = video blogs.' } },
    { id:'u4_l1x2_7', type:'trueFalse', bloom:'understand', difficulty:'medium',
      question_en:'"Slow" is an adjective and "slowly" is its adverb.',
      paragraph:'Adjective + ly → adverb (usually). slow → slowly.',
      options_en:['True','False'], correct:'true',
      explanation_en:'Correct! slow = adjective. slowly = adverb.',
      golden_rule_en:'Adjective + ly → adverb. slow→slowly, quick→quickly.',
      feedbackQuestion:{ question_en:'The adverb of "quick" is:', options_en:['quicker','quickly','quickest','quickily'], correct:1, explanation_en:'quick + ly = quickly.' } },
    { id:'u4_l1x2_8', type:'fillBlank', bloom:'apply', difficulty:'medium',
      question_en:'He drives _____ . (adverb of careful)',
      paragraph:'careful + ly = carefully.',
      blanks:['carefully'], wordBank:['carefully','careful','carefuls','carefuler'],
      explanation_en:'careful + ly = carefully. He drives carefully.',
      golden_rule_en:'careful → carefully.',
      feedbackQuestion:{ question_en:'She speaks _____ . (adverb of loud)', options_en:['loud','loudly','louds','louder'], correct:1, explanation_en:'loud + ly = loudly.' } },
    { id:'u4_l1x2_9', type:'multipleChoice', bloom:'apply', difficulty:'hard',
      question_en:'Choose the correct sentence:',
      paragraph:'Adverb (-ly) describes verb. Adjective describes noun.',
      options_en:['He runs quick.','He runs quickly.','He quicks runs.','He runs quicker.'], correct:1,
      explanation_en:'runs (verb) → quickly (adverb). NOT "quick" (adjective).',
      golden_rule_en:'Verb → adverb: runs quickly.',
      feedbackQuestion:{ question_en:'She speaks _____ to the children.', options_en:['quiet','quietly','quiets','quietness'], correct:1, explanation_en:'speaks → quietly.' } },
    { id:'u4_l1x2_10', type:'classify', bloom:'understand', difficulty:'medium',
      question_en:'Classify: Board game or Outdoor activity?',
      paragraph:'Board: dominoes, chess. Outdoor: dodgeball, hide and seek, football.',
      categories:['Board game','Outdoor activity'],
      items:[
        { text:'dominoes', correct_category:0 },
        { text:'chess', correct_category:0 },
        { text:'checkers', correct_category:0 },
        { text:'dodgeball', correct_category:1 },
        { text:'hide and seek', correct_category:1 },
        { text:'football', correct_category:1 },
      ],
      explanation_en:'Board games: on a table. Outdoor: outside.',
      golden_rule_en:'Board: dominoes, chess, checkers | Outdoor: dodgeball, hide and seek.',
      feedbackQuestion:{ question_en:'"Chess" is a/an _____ activity.', options_en:['outdoor','board game','musical','sport'], correct:1, explanation_en:'chess = board game.' } },
  ],
  u4_l2: [
    { id:'u4_l2x2_1', type:'multipleChoice', bloom:'understand', difficulty:'medium',
      question_en:'She can run, ( but – and – so ) she can\'t swim.',
      paragraph:'but = contrast. and = addition. so = result.',
      options_en:['and','but','so','because'], correct:1,
      explanation_en:'but = contrast. She can run BUT she can\'t swim.',
      golden_rule_en:'but=contrast | and=addition | so=result | because=reason | when=time.',
      feedbackQuestion:{ question_en:'I am hungry, ( and – but – so ) I eat a sandwich.', options_en:['and','but','so','because'], correct:2, explanation_en:'so = result.' } },
    { id:'u4_l2x2_2', type:'trueFalse', bloom:'understand', difficulty:'easy',
      question_en:'"I go to the hospital because I am sick." — "because" = reason.',
      paragraph:'because = لأن = reason.',
      options_en:['True','False'], correct:'true',
      explanation_en:'Correct! because = reason. Why? → because I am sick.',
      golden_rule_en:'because = reason.',
      feedbackQuestion:{ question_en:'I go swimming ( when – because – and ) playing tennis on Saturdays.', options_en:['because','when','and','but'], correct:2, explanation_en:'and = addition.' } },
    { id:'u4_l2x2_3', type:'multipleChoice', bloom:'apply', difficulty:'medium',
      question_en:'He ( sleeps – slept ) late last night.',
      paragraph:'Last night = past. sleep → slept (irregular).',
      options_en:['sleeps','slept','sleeping','sleep'], correct:1,
      explanation_en:'Last night = past → slept (irregular: sleep → slept).',
      golden_rule_en:'Irregular: sleep→slept, go→went, see→saw, take→took.',
      feedbackQuestion:{ question_en:'She ( didn\'t see – didn\'t saw ) a movie.', options_en:['didn\'t saw','didn\'t see','doesn\'t see','didn\'t seeing'], correct:1, explanation_en:'didn\'t + base: see.' } },
    { id:'u4_l2x2_4', type:'classify', bloom:'apply', difficulty:'hard',
      question_en:'Classify the conjunction: contrast, reason, or result?',
      paragraph:'but=contrast, because=reason, so=result, when=time, and=addition.',
      categories:['Contrast (but)','Reason (because)','Result (so)'],
      items:[
        { text:'but', correct_category:0 },
        { text:'because', correct_category:1 },
        { text:'so', correct_category:2 },
        { text:'however', correct_category:0 },
        { text:'since', correct_category:1 },
        { text:'therefore', correct_category:2 },
      ],
      explanation_en:'but/however = contrast. because/since = reason. so/therefore = result.',
      golden_rule_en:'Contrast: but | Reason: because | Result: so | Time: when | Addition: and.',
      feedbackQuestion:{ question_en:'"Therefore" is similar to:', options_en:['but','because','so','when'], correct:2, explanation_en:'therefore = so = result.' } },
    { id:'u4_l2x2_5', type:'multipleChoice', bloom:'understand', difficulty:'medium',
      question_en:'"When I was a child, I loved playing outside." — "when" introduces:',
      paragraph:'when = time (عندما).',
      options_en:['a reason','a result','a contrast','a time'], correct:3,
      explanation_en:'when = time. When I was a child = the TIME.',
      golden_rule_en:'when = time.',
      feedbackQuestion:{ question_en:'"When do you do the activity?" — Best answer:', options_en:['Yes, I do.','I usually do it on the weekend.','Because I like it.','I go swimming.'], correct:1, explanation_en:'When → time answer.' } },
    { id:'u4_l2x2_6', type:'fillBlank', bloom:'apply', difficulty:'medium',
      question_en:'I am tired _____ I slept late last night. (reason)',
      paragraph:'because = reason.',
      blanks:['because'], wordBank:['because','but','so','when'],
      explanation_en:'because = reason. I am tired BECAUSE I slept late.',
      golden_rule_en:'because = reason.',
      feedbackQuestion:{ question_en:'I stayed home _____ it was raining. (reason)', options_en:['but','so','because','when'], correct:2, explanation_en:'because = reason.' } },
    { id:'u4_l2x2_7', type:'trueFalse', bloom:'apply', difficulty:'medium',
      question_en:'"I like soccer but I don\'t like tennis" shows addition.',
      paragraph:'but = contrast, NOT addition. and = addition.',
      options_en:['True','False'], correct:'false',
      explanation_en:'FALSE. but = contrast. and = addition.',
      golden_rule_en:'but = contrast | and = addition.',
      feedbackQuestion:{ question_en:'"I like soccer _____ I like tennis." (addition)', options_en:['but','and','so','because'], correct:1, explanation_en:'and = addition.' } },
    { id:'u4_l2x2_8', type:'multipleChoice', bloom:'apply', difficulty:'medium',
      question_en:'It was raining, ( so – but – when ) we stayed home.',
      paragraph:'so = result.',
      options_en:['so','but','when','because'], correct:0,
      explanation_en:'so = result. It rained → so we stayed home.',
      golden_rule_en:'so = result. Cause → so → Result.',
      feedbackQuestion:{ question_en:'She studied hard, ( so – but – because ) she passed.', options_en:['so','but','because','when'], correct:0, explanation_en:'so = result.' } },
    { id:'u4_l2x2_9', type:'matching', bloom:'apply', difficulty:'medium',
      question_en:'Match the conjunction with its meaning:',
      paragraph:'but=لكن, and=و, so=لذلك, because=لأن, when=عندما.',
      pairs:[
        { left:'but', right:'لكن (contrast)' },
        { left:'so', right:'لذلك (result)' },
        { left:'because', right:'لأن (reason)' },
        { left:'when', right:'عندما (time)' },
      ],
      explanation_en:'Match each conjunction with its Arabic meaning.',
      golden_rule_en:'but=لكن | so=لذلك | because=لأن | when=عندما | and=و.',
      feedbackQuestion:{ question_en:'"لأن" in English is:', options_en:['but','so','because','when'], correct:2, explanation_en:'because = لأن.' } },
    { id:'u4_l2x2_10', type:'multipleChoice', bloom:'apply', difficulty:'hard',
      question_en:'Choose the correct sentence:',
      paragraph:'Conjunctions connect ideas with correct logic.',
      options_en:['I was sick so I stayed home.','I was sick because I stayed home.','I was sick but I stayed home.','I was sick when I stayed home.'], correct:0,
      explanation_en:'so = result. I was sick (cause) → so I stayed home (result).',
      golden_rule_en:'Cause → so → Result.',
      feedbackQuestion:{ question_en:'"I stayed home _____ I was sick." (reason)', options_en:['but','so','because','when'], correct:2, explanation_en:'because = reason.' } },
  ],
  u4_l3: [
    { id:'u4_l3x2_1', type:'multipleChoice', bloom:'remember', difficulty:'medium',
      question_en:'Fatima didn\'t ( wrote – write – writing ) stories on Saturday.',
      paragraph:'didn\'t + base: write.',
      options_en:['wrote','write','writing','writes'], correct:1,
      explanation_en:'didn\'t + base: write. Fatima didn\'t write stories.',
      golden_rule_en:'didn\'t + BASE verb.',
      feedbackQuestion:{ question_en:'Fatima ( wrote – write – writing ) stories last Saturday.', options_en:['write','wrote','writing','writes'], correct:1, explanation_en:'Last Saturday = past → wrote.' } },
    { id:'u4_l3x2_2', type:'classify', bloom:'apply', difficulty:'hard',
      question_en:'Does the verb take "to + infinitive" or "gerund (-ing)"?',
      paragraph:'want/plan/decide → to + infinitive | enjoy/avoid/finish → gerund.',
      categories:['to + infinitive','gerund (-ing)'],
      items:[
        { text:'want to eat', correct_category:0 },
        { text:'enjoy reading', correct_category:1 },
        { text:'decided to go', correct_category:0 },
        { text:'keeps talking', correct_category:1 },
        { text:'plan to visit', correct_category:0 },
        { text:'avoid running', correct_category:1 },
      ],
      explanation_en:'want/plan/decide + to + verb | enjoy/avoid/finish + verb + ing.',
      golden_rule_en:'to + infinitive: want, plan, decide | gerund: enjoy, avoid, finish.',
      feedbackQuestion:{ question_en:'"I finished _____ my homework." (do)', options_en:['to do','doing','did','does'], correct:1, explanation_en:'finish + gerund: doing.' } },
    { id:'u4_l3x2_3', type:'trueFalse', bloom:'understand', difficulty:'medium',
      question_en:'"Could" is the past form of "can" and expresses past ability.',
      paragraph:'can → could (past ability).',
      options_en:['True','False'], correct:'true',
      explanation_en:'Correct! could = past of can = past ability.',
      golden_rule_en:'can = present ability | could = past ability.',
      feedbackQuestion:{ question_en:'"He couldn\'t find his keys" means:', options_en:['was able to find','was not able to find','will not find','is not able to find'], correct:1, explanation_en:'couldn\'t = was not able to.' } },
    { id:'u4_l3x2_4', type:'multipleChoice', bloom:'apply', difficulty:'medium',
      question_en:'Did he ( see – saw – seeing ) a movie last night?',
      paragraph:'Did + base: see.',
      options_en:['saw','see','seeing','seen'], correct:1,
      explanation_en:'Did + base: see. Did he see a movie?',
      golden_rule_en:'Did + subject + BASE verb.',
      feedbackQuestion:{ question_en:'Did you ( take – took ) photos in the park?', options_en:['took','take','taking','taken'], correct:1, explanation_en:'Did + base: take.' } },
    { id:'u4_l3x2_5', type:'matching', bloom:'apply', difficulty:'medium',
      question_en:'Match the question with its best answer:',
      paragraph:'After-school activities Q&A.',
      pairs:[
        { left:'Do you want to play hide and seek?', right:'No, I prefer board games.' },
        { left:'What activities do you do in your free time?', right:'I usually do it on the weekend.' },
        { left:'Did you go shopping on Saturday?', right:'No, I didn\'t.' },
        { left:'Why did you go to the mall?', right:'Because I had to buy clothes.' },
      ],
      explanation_en:'Match using context: prefer → alternative | when → time | did → yes/no | why → because.',
      golden_rule_en:'Why → because | Did → Yes/No | Do you want → preference.',
      feedbackQuestion:{ question_en:'"Why did you go to the mall?" — Best answer:', options_en:['I go swimming.','Yes, I did.','Because I had to buy clothes.','I usually do it on weekends.'], correct:2, explanation_en:'Why → because.' } },
    { id:'u4_l3x2_6', type:'fillBlank', bloom:'apply', difficulty:'medium',
      question_en:'I want _____ a movie tonight. (watch)',
      paragraph:'want + to + base verb.',
      blanks:['to watch'], wordBank:['to watch','watching','watched','watch'],
      explanation_en:'want + to + watch.',
      golden_rule_en:'want + to + base verb.',
      feedbackQuestion:{ question_en:'She enjoys _____ models. (make)', options_en:['to make','making','made','makes'], correct:1, explanation_en:'enjoy + gerund: making.' } },
    { id:'u4_l3x2_7', type:'multipleChoice', bloom:'understand', difficulty:'medium',
      question_en:'"Could" expresses:',
      paragraph:'could = past ability.',
      options_en:['present ability','past ability','future ability','no ability'], correct:1,
      explanation_en:'could = past ability.',
      golden_rule_en:'can = present | could = past.',
      feedbackQuestion:{ question_en:'"I _____ swim when I was six." (past ability)', options_en:['can','could','will','must'], correct:1, explanation_en:'past → could.' } },
    { id:'u4_l3x2_8', type:'trueFalse', bloom:'apply', difficulty:'medium',
      question_en:'"I want to eating pizza" is correct.',
      paragraph:'want + to + base verb: eat. NOT "to eating".',
      options_en:['True','False'], correct:'false',
      explanation_en:'FALSE. want + to + eat. NOT "to eating".',
      golden_rule_en:'want + to + BASE. ❌ to eating | ✓ to eat.',
      feedbackQuestion:{ question_en:'I want _____ a sandwich. (eat)', options_en:['to eating','to eat','eating','eat'], correct:1, explanation_en:'want + to + eat.' } },
    { id:'u4_l3x2_9', type:'multipleChoice', bloom:'apply', difficulty:'hard',
      question_en:'Choose the correct sentence:',
      paragraph:'enjoy + gerund. want + to + infinitive.',
      options_en:['She enjoys swimming.','She enjoys to swim.','She enjoys swim.','She enjoys swam.'], correct:0,
      explanation_en:'enjoy + gerund: swimming. She enjoys swimming.',
      golden_rule_en:'enjoy + verb + ing. ❌ enjoy to swim | ✓ enjoy swimming.',
      feedbackQuestion:{ question_en:'He wants _____ football. (play)', options_en:['to play','playing','played','plays'], correct:0, explanation_en:'want + to + play.' } },
    { id:'u4_l3x2_10', type:'matching', bloom:'remember', difficulty:'easy',
      question_en:'Match the verb with its correct pattern:',
      paragraph:'want → to + infinitive | enjoy → gerund | could → past ability | didn\'t → base.',
      pairs:[
        { left:'want', right:'to + infinitive' },
        { left:'enjoy', right:'gerund (-ing)' },
        { left:'could', right:'past ability' },
        { left:'didn\'t', right:'base verb' },
      ],
      explanation_en:'Each verb has a specific pattern for what follows.',
      golden_rule_en:'want→to+verb | enjoy→verb+ing | could→past | didn\'t→base.',
      feedbackQuestion:{ question_en:'"Enjoy" is followed by:', options_en:['to + infinitive','gerund (-ing)','past verb','base only'], correct:1, explanation_en:'enjoy + gerund.' } },
  ],
};