// Unit 2: Chores — Extra Questions Batch 2
export const UNIT2_EXTRA2 = {
  u2_l1: [
    { id:'u2_l1x2_1', type:'multipleChoice', bloom:'remember', difficulty:'easy',
      question_en:'The past of "make" (as in make the bed) in Simple Present with "she" is:',
      paragraph:'Simple Present: she → makes (add -s). make → makes.',
      options_en:['make','makes','making','made'], correct:1,
      explanation_en:'She → makes (add -s). Simple Present routine.',
      golden_rule_en:'he/she/it + verb + s. make → makes.',
      feedbackQuestion:{ question_en:'She ( make – makes – making ) the bed every morning.', options_en:['make','makes','making','made'], correct:1, explanation_en:'She → makes.' } },
    { id:'u2_l1x2_2', type:'trueFalse', bloom:'understand', difficulty:'medium',
      question_en:'"She is washing the dishes now" is Present Progressive.',
      paragraph:'is + washing = Present Progressive (happening now).',
      options_en:['True','False'], correct:'true',
      explanation_en:'Correct! is + washing = Present Progressive (now).',
      golden_rule_en:'am/is/are + verb + ing = Present Progressive.',
      feedbackQuestion:{ question_en:'"She washes the dishes every day" is _____ tense.', options_en:['Present Progressive','Simple Present','Past','Future'], correct:1, explanation_en:'Every day → Simple Present.' } },
    { id:'u2_l1x2_3', type:'multipleChoice', bloom:'apply', difficulty:'medium',
      question_en:'They ( isn\'t – aren\'t – am not ) sweeping the floor now.',
      paragraph:'Present Progressive negative: aren\'t + ing (they).',
      options_en:['isn\'t','aren\'t','am not','don\'t'], correct:1,
      explanation_en:'They → aren\'t. aren\'t sweeping.',
      golden_rule_en:'Negative Progressive: isn\'t (he/she/it) | aren\'t (you/we/they) | am not (I).',
      feedbackQuestion:{ question_en:'She ( isn\'t – aren\'t ) making the bed now.', options_en:['isn\'t','aren\'t','am not','don\'t'], correct:0, explanation_en:'She → isn\'t.' } },
    { id:'u2_l1x2_4', type:'classify', bloom:'apply', difficulty:'hard',
      question_en:'Classify: Present Progressive or Simple Present?',
      paragraph:'Progressive = now. Simple Present = routine.',
      categories:['Present Progressive','Simple Present'],
      items:[
        { text:'She is making the bed now.', correct_category:0 },
        { text:'She makes the bed every day.', correct_category:1 },
        { text:'They are washing dishes.', correct_category:0 },
        { text:'They wash dishes on Fridays.', correct_category:1 },
        { text:'I am feeding the cat.', correct_category:0 },
        { text:'I feed the cat every morning.', correct_category:1 },
      ],
      explanation_en:'now/at the moment → Progressive. every day/always → Simple Present.',
      golden_rule_en:'Now → Progressive | Routine → Simple Present.',
      feedbackQuestion:{ question_en:'"She is sweeping now" is _____ .', options_en:['Simple Present','Present Progressive','Past','Future'], correct:1, explanation_en:'is + sweeping = Progressive.' } },
    { id:'u2_l1x2_5', type:'matching', bloom:'remember', difficulty:'easy',
      question_en:'Match the chore with its Arabic meaning:',
      paragraph:'Chores: sweep the floor, make the bed, wash the dishes, clear the table, take out the trash, feed the animals.',
      pairs:[
        { left:'make the bed', right:'يرتب السرير' },
        { left:'wash the dishes', right:'يغسل الصحون' },
        { left:'clear the table', right:'ينظف الطاولة' },
        { left:'feed the animals', right:'يطعم الحيوانات' },
      ],
      explanation_en:'Match each chore with its Arabic translation.',
      golden_rule_en:'make=يرتب | wash=يغسل | clear=ينظف | feed=يطعم | sweep=يكنس | take out=يخرج.',
      feedbackQuestion:{ question_en:'"Sweep the floor" means:', options_en:['يكنس الأرض','يغسل الصحون','يرتب السرير','يطعم الحيوانات'], correct:0, explanation_en:'sweep = يكنس.' } },
    { id:'u2_l1x2_6', type:'multipleChoice', bloom:'apply', difficulty:'medium',
      question_en:'Do you ( wash – washes – washing ) the dishes every day?',
      paragraph:'Do + I/you/we/they + base verb. you → wash.',
      options_en:['wash','washes','washing','washed'], correct:0,
      explanation_en:'Do you → base: wash. Do you wash the dishes every day?',
      golden_rule_en:'Do + I/you/we/they + base verb.',
      feedbackQuestion:{ question_en:'Does she ( wash – washes ) the dishes?', options_en:['wash','washes','washing','washed'], correct:0, explanation_en:'Does + she + base: wash.' } },
    { id:'u2_l1x2_7', type:'trueFalse', bloom:'apply', difficulty:'medium',
      question_en:'"She don\'t wash the dishes" is correct.',
      paragraph:'She → doesn\'t (NOT don\'t).',
      options_en:['True','False'], correct:'false',
      explanation_en:'FALSE. She → doesn\'t. Correct: She doesn\'t wash the dishes.',
      golden_rule_en:'don\'t = I/you/we/they | doesn\'t = he/she/it.',
      feedbackQuestion:{ question_en:'They ( don\'t – doesn\'t ) wash the dishes.', options_en:['don\'t','doesn\'t','isn\'t','aren\'t'], correct:0, explanation_en:'They → don\'t.' } },
    { id:'u2_l1x2_8', type:'fillBlank', bloom:'apply', difficulty:'medium',
      question_en:'She is _____ the table now. (clear - happening now)',
      paragraph:'Present Progressive: is + verb + ing. clear → clearing.',
      blanks:['clearing'], wordBank:['clearing','clear','clears','cleared'],
      explanation_en:'is + clearing. She is clearing the table now.',
      golden_rule_en:'is/am/are + verb + ing = happening now.',
      feedbackQuestion:{ question_en:'He is _____ the trash now. (take out)', options_en:['take out','taking out','takes out','took out'], correct:1, explanation_en:'is + taking out.' } },
    { id:'u2_l1x2_9', type:'multipleChoice', bloom:'understand', difficulty:'medium',
      question_en:'"Now" is a signal word for:',
      paragraph:'now/today/at the moment → Present Progressive.',
      options_en:['Simple Present','Present Progressive','Past Simple','Future'], correct:1,
      explanation_en:'now → Present Progressive.',
      golden_rule_en:'now/today/at the moment → Progressive. every day/always → Simple Present.',
      feedbackQuestion:{ question_en:'"Every day" is a signal word for:', options_en:['Simple Present','Present Progressive','Past','Future'], correct:0, explanation_en:'every day → Simple Present.' } },
    { id:'u2_l1x2_10', type:'multipleChoice', bloom:'apply', difficulty:'hard',
      question_en:'Choose the correct sentence:',
      paragraph:'Progressive: is + ing. Simple Present: she + s.',
      options_en:['She is wash the dishes.','She is washing the dishes.','She wash the dishes now.','She is washes the dishes.'], correct:1,
      explanation_en:'is + washing = Present Progressive. She is washing the dishes.',
      golden_rule_en:'is/am/are + verb + ing.',
      feedbackQuestion:{ question_en:'She ( wash – washes – is washing ) the dishes now.', options_en:['wash','washes','is washing','washed'], correct:2, explanation_en:'now → is washing.' } },
  ],
  u2_l2: [
    { id:'u2_l2x2_1', type:'multipleChoice', bloom:'remember', difficulty:'easy',
      question_en:'"Can I help you?" — This is a/an:',
      paragraph:'Can I = offer (عرض). Can you = request (طلب).',
      options_en:['request','offer','command','statement'], correct:1,
      explanation_en:'Can I = offer. I am offering to help.',
      golden_rule_en:'Can I = offer | Can you = request.',
      feedbackQuestion:{ question_en:'"Can you help me?" is a:', options_en:['offer','request','command','statement'], correct:1, explanation_en:'Can you = request.' } },
    { id:'u2_l2x2_2', type:'trueFalse', bloom:'understand', difficulty:'easy',
      question_en:'"Can you set the table?" is a request.',
      paragraph:'Can you = request (asking someone to do something).',
      options_en:['True','False'], correct:'true',
      explanation_en:'Correct! Can you = request (طلب).',
      golden_rule_en:'Can you = request | Can I = offer.',
      feedbackQuestion:{ question_en:'"Can I set the table?" is an:', options_en:['offer','request','command','statement'], correct:0, explanation_en:'Can I = offer.' } },
    { id:'u2_l2x2_3', type:'multipleChoice', bloom:'apply', difficulty:'medium',
      question_en:'Reorder: the floor / Can / sweep / I / ?',
      paragraph:'Can + I + base verb + object. Offer structure.',
      options_en:['Can I sweep the floor?','I can sweep the floor?','Sweep can I the floor?','Can sweep I the floor?'], correct:0,
      explanation_en:'Can I + sweep + the floor? → offer.',
      golden_rule_en:'Offer: Can I + verb + object?',
      feedbackQuestion:{ question_en:'Reorder: help / Can / you / me / ?', options_en:['Can you help me?','Help can you me?','You can help me?','Can me help you?'], correct:0, explanation_en:'Can you + help me?' } },
    { id:'u2_l2x2_4', type:'classify', bloom:'apply', difficulty:'medium',
      question_en:'Classify: Offer or Request?',
      paragraph:'Can I = offer. Can you = request.',
      categories:['Offer (عرض)','Request (طلب)'],
      items:[
        { text:'Can I wash the dishes?', correct_category:0 },
        { text:'Can you feed the animals?', correct_category:1 },
        { text:'Can I make the bed?', correct_category:0 },
        { text:'Can you clear the table?', correct_category:1 },
        { text:'Can I take out the trash?', correct_category:0 },
        { text:'Can you sweep the floor?', correct_category:1 },
      ],
      explanation_en:'Can I = speaker offers. Can you = asking the listener.',
      golden_rule_en:'Can I = offer | Can you = request.',
      feedbackQuestion:{ question_en:'"Can I help?" is a/an:', options_en:['request','offer','command','statement'], correct:1, explanation_en:'Can I = offer.' } },
    { id:'u2_l2x2_5', type:'matching', bloom:'apply', difficulty:'medium',
      question_en:'Match the request with the correct response:',
      paragraph:'Can I / Can you and polite responses.',
      pairs:[
        { left:'Can you set the table?', right:'Sure, I can.' },
        { left:'Can I help you?', right:'Yes, please.' },
        { left:'Can you feed the cat?', right:'Of course.' },
        { left:'Can I wash the dishes?', right:'That would be great!' },
      ],
      explanation_en:'Match requests with appropriate polite responses.',
      golden_rule_en:'Polite: Sure, Yes please, Of course, That would be great.',
      feedbackQuestion:{ question_en:'"Can you help me?" — Best response:', options_en:['No!','Sure, I can.','Maybe later.','I don\'t know.'], correct:1, explanation_en:'Sure, I can.' } },
    { id:'u2_l2x2_6', type:'multipleChoice', bloom:'remember', difficulty:'easy',
      question_en:'"Make the bed" means:',
      paragraph:'make the bed = يرتب السرير = arrange sheets and pillows.',
      options_en:['يغسل السرير','يرتب السرير','يشتري سريراً','يكسر السرير'], correct:1,
      explanation_en:'make the bed = يرتب السرير.',
      golden_rule_en:'make the bed = يرتب السرير (not literally "make").',
      feedbackQuestion:{ question_en:'"Clear the table" means:', options_en:['يغسل الطاولة','ينظف الطاولة','يكسر الطاولة','يشتري طاولة'], correct:1, explanation_en:'clear the table = ينظف الطاولة.' } },
    { id:'u2_l2x2_7', type:'trueFalse', bloom:'understand', difficulty:'medium',
      question_en:'"Can" can express ability, offer, and request.',
      paragraph:'can = ability (I can swim) | offer (Can I help?) | request (Can you help?).',
      options_en:['True','False'], correct:'true',
      explanation_en:'Correct! can = ability, offer, and request depending on context.',
      golden_rule_en:'can = ability | Can I = offer | Can you = request.',
      feedbackQuestion:{ question_en:'"I can swim" — "can" expresses:', options_en:['offer','ability','request','command'], correct:1, explanation_en:'can = ability.' } },
    { id:'u2_l2x2_8', type:'fillBlank', bloom:'apply', difficulty:'medium',
      question_en:'"Can I _____ the trash?" (chore = take outside)',
      paragraph:'take out the trash = يخرج النفايات.',
      blanks:['take out'], wordBank:['take out','clear','sweep','wash'],
      explanation_en:'take out the trash = يخرج النفايات.',
      golden_rule_en:'take out the trash = يخرج النفايات.',
      feedbackQuestion:{ question_en:'"Can you _____ the dishes?" (chore = clean plates)', options_en:['make','wash','clear','sweep'], correct:1, explanation_en:'wash the dishes.' } },
    { id:'u2_l2x2_9', type:'multipleChoice', bloom:'understand', difficulty:'medium',
      question_en:'"Can you help me wash my car?" — Who is being asked to help?',
      paragraph:'Can you = asking the listener (you) to help.',
      options_en:['The speaker','The listener','Nobody','Everyone'], correct:1,
      explanation_en:'Can you = asking the listener to help.',
      golden_rule_en:'Can you = listener is asked | Can I = speaker offers.',
      feedbackQuestion:{ question_en:'"Can I help you?" — Who is offering?', options_en:['The speaker','The listener','Nobody','Everyone'], correct:0, explanation_en:'Can I = speaker offers.' } },
    { id:'u2_l2x2_10', type:'multipleChoice', bloom:'apply', difficulty:'hard',
      question_en:'Choose the correct polite request:',
      paragraph:'Polite requests use "Can you" + please.',
      options_en:['Can you set the table, please?','Set the table now!','You set the table.','Set table you can?'], correct:0,
      explanation_en:'"Can you...please?" = polite request. Correct!',
      golden_rule_en:'Polite request: Can you + verb + object + please?',
      feedbackQuestion:{ question_en:'"Can I wash the dishes?" is a polite:', options_en:['request','offer','command','refusal'], correct:1, explanation_en:'Can I = polite offer.' } },
  ],
  u2_l3: [
    { id:'u2_l3x2_1', type:'classify', bloom:'analyze', difficulty:'hard',
      question_en:'Classify: Simple Present or Present Progressive?',
      paragraph:'Routine → Simple Present. Now → Progressive.',
      categories:['Simple Present','Present Progressive'],
      items:[
        { text:'She always reads books.', correct_category:0 },
        { text:'She is reading now.', correct_category:1 },
        { text:'I go to school every day.', correct_category:0 },
        { text:'I am doing homework.', correct_category:1 },
        { text:'They play every Friday.', correct_category:0 },
        { text:'They are playing today.', correct_category:1 },
      ],
      explanation_en:'every day/always → Simple Present. now/today → Progressive.',
      golden_rule_en:'Routine → Simple Present | Now → Progressive.',
      feedbackQuestion:{ question_en:'"She is studying _____ ." Which fits?', options_en:['every day','usually','now','always'], correct:2, explanation_en:'is studying → now.' } },
    { id:'u2_l3x2_2', type:'multipleChoice', bloom:'apply', difficulty:'medium',
      question_en:'They sleep early. → Negative:',
      paragraph:'They → don\'t + base verb.',
      options_en:['They doesn\'t sleep.','They aren\'t sleeping.','They don\'t sleep.','They not sleep.'], correct:2,
      explanation_en:'They → don\'t + sleep. They don\'t sleep early.',
      golden_rule_en:'don\'t + base (I/you/we/they) | doesn\'t + base (he/she/it).',
      feedbackQuestion:{ question_en:'She sleeps early. → Negative:', options_en:['She doesn\'t sleep.','She don\'t sleep.','She isn\'t sleeping.','She not sleep.'], correct:0, explanation_en:'She → doesn\'t + sleep.' } },
    { id:'u2_l3x2_3', type:'trueFalse', bloom:'analyze', difficulty:'hard',
      question_en:'"I am making the bed every day" describes a routine correctly.',
      paragraph:'am + ing = happening now, NOT a routine. Routine = Simple Present.',
      options_en:['True','False'], correct:'false',
      explanation_en:'FALSE. "I am making" = now. Routine = "I make the bed every day".',
      golden_rule_en:'ing = now. Simple Present = routine.',
      feedbackQuestion:{ question_en:'"I make the bed every day" is _____ .', options_en:['Present Progressive','Simple Present','Past','Future'], correct:1, explanation_en:'Every day → Simple Present.' } },
    { id:'u2_l3x2_4', type:'multipleChoice', bloom:'apply', difficulty:'medium',
      question_en:'Does she ( live – lives – living ) in Riyadh?',
      paragraph:'Does + she + base verb: live.',
      options_en:['live','lives','living','lived'], correct:0,
      explanation_en:'Does + she + base: live. Does she live in Riyadh?',
      golden_rule_en:'Does + he/she/it + base verb.',
      feedbackQuestion:{ question_en:'Do you ( live – lives ) in Riyadh?', options_en:['live','lives','living','lived'], correct:0, explanation_en:'Do + you + base: live.' } },
    { id:'u2_l3x2_5', type:'ordering', bloom:'apply', difficulty:'medium',
      question_en:'Reorder: Can / you / set / the table / ?',
      paragraph:'Can you + base verb + object? Request structure.',
      items:['Can','you','set','the table?'], correctOrder:[0,1,2,3],
      explanation_en:'Can you set the table? → request.',
      golden_rule_en:'Request: Can you + verb + object?',
      feedbackQuestion:{ question_en:'Reorder: I / Can / sweep / the floor / ?', options_en:['Can I sweep the floor?','I can sweep the floor?','Sweep can I the floor?','Can sweep I the floor?'], correct:0, explanation_en:'Can I + sweep + the floor?' } },
    { id:'u2_l3x2_6', type:'fillBlank', bloom:'apply', difficulty:'medium',
      question_en:'She always _____ the dishes. (wash, she = 3rd person)',
      paragraph:'Simple Present: she → washes (add -es after -ch).',
      blanks:['washes'], wordBank:['washes','wash','washing','washed'],
      explanation_en:'She → washes. always = routine = Simple Present.',
      golden_rule_en:'she/he/it + verb + s/es. wash → washes.',
      feedbackQuestion:{ question_en:'He always _____ the trash. (take out)', options_en:['take out','takes out','taking out','took out'], correct:1, explanation_en:'He → takes out.' } },
    { id:'u2_l3x2_7', type:'multipleChoice', bloom:'understand', difficulty:'medium',
      question_en:'"At the moment" signals which tense?',
      paragraph:'at the moment = now → Present Progressive.',
      options_en:['Simple Present','Present Progressive','Past','Future'], correct:1,
      explanation_en:'at the moment → Present Progressive.',
      golden_rule_en:'now/at the moment/today → Progressive | every day/always → Simple Present.',
      feedbackQuestion:{ question_en:'"Every Friday" signals which tense?', options_en:['Simple Present','Present Progressive','Past','Future'], correct:0, explanation_en:'Every Friday → Simple Present.' } },
    { id:'u2_l3x2_8', type:'trueFalse', bloom:'understand', difficulty:'medium',
      question_en:'"Does she wash the dishes?" is a Present Progressive question.',
      paragraph:'"Does she wash" = Simple Present question. Progressive = "Is she washing?".',
      options_en:['True','False'], correct:'false',
      explanation_en:'FALSE. "Does she wash" = Simple Present. Progressive = "Is she washing?".',
      golden_rule_en:'Simple Present question: Do/Does + base. Progressive: Is/Are + ing.',
      feedbackQuestion:{ question_en:'"Is she washing the dishes?" is _____ .', options_en:['Simple Present','Present Progressive','Past','Future'], correct:1, explanation_en:'is + washing = Progressive.' } },
    { id:'u2_l3x2_9', type:'classify', bloom:'apply', difficulty:'medium',
      question_en:'Classify: Chores or Free-time activities?',
      paragraph:'Chores = home tasks. Free-time = fun.',
      categories:['Chores (مهام)','Free-time (ترفيه)'],
      items:[
        { text:'wash the dishes', correct_category:0 },
        { text:'make the bed', correct_category:0 },
        { text:'play football', correct_category:1 },
        { text:'watch TV', correct_category:1 },
        { text:'sweep the floor', correct_category:0 },
        { text:'read comics', correct_category:1 },
      ],
      explanation_en:'Chores = home tasks. Free-time = enjoyable activities.',
      golden_rule_en:'Chores: wash, sweep, make bed | Free-time: play, read, watch.',
      feedbackQuestion:{ question_en:'"Take out the trash" is a:', options_en:['chore','free-time activity','sport','game'], correct:0, explanation_en:'Home task = chore.' } },
    { id:'u2_l3x2_10', type:'multipleChoice', bloom:'apply', difficulty:'hard',
      question_en:'Choose the correct negative sentence:',
      paragraph:'doesn\'t + base verb. Progressive: isn\'t + ing.',
      options_en:['She doesn\'t wash the dishes.','She don\'t wash the dishes.','She doesn\'t washes the dishes.','She not wash the dishes.'], correct:0,
      explanation_en:'She → doesn\'t + base (wash, no -s). She doesn\'t wash the dishes.',
      golden_rule_en:'doesn\'t + BASE verb (no -s).',
      feedbackQuestion:{ question_en:'"They don\'t _____ the dishes."', options_en:['washes','wash','washing','washed'], correct:1, explanation_en:'don\'t + base: wash.' } },
  ],
};