// Unit 3: Stories — Extra Questions
export const UNIT3_EXTRA = {
  u3_l1: [
    { id:'u3_l1_e1', type:'multipleChoice', bloom:'remember', difficulty:'easy',
      question_en:'The past form of "play" is:',
      paragraph:'Regular verbs: add -ed. play → played. walk → walked. clean → cleaned.',
      options_en:['played','plaied','plays','playing'], correct:0,
      explanation_en:'Regular verb: play + ed = played.',
      golden_rule_en:'Regular Past: verb + ed. play → played, walk → walked.',
      feedbackQuestion:{ question_en:'The past form of "clean" is:', options_en:['cleaned','cleant','cleans','cleaning'], correct:0, explanation_en:'clean → cleaned.' } },
    { id:'u3_l1_e2', type:'multipleChoice', bloom:'apply', difficulty:'medium',
      question_en:'What ( did – does – doing ) you do yesterday?',
      paragraph:'Past Simple question: Did + subject + base verb? Yesterday = past.',
      options_en:['did','does','doing','do'], correct:0,
      explanation_en:'Yesterday = past → did. Past question: What did you do yesterday?',
      golden_rule_en:'Past question: Did + subject + base verb? (not "does").',
      feedbackQuestion:{ question_en:'( Did – Does ) he send an email last week?', options_en:['Does','Did','Do','Is'], correct:1, explanation_en:'Last week = past → Did.' } },
    { id:'u3_l1_e3', type:'matching', bloom:'remember', difficulty:'easy',
      question_en:'Match the base form with its past form:',
      paragraph:'Regular past: dream→dreamed, stop→stopped, plan→planned, play→played, carry→carried.',
      pairs:[
        { left:'dream', right:'dreamed' },
        { left:'stop', right:'stopped' },
        { left:'plan', right:'planned' },
        { left:'carry', right:'carried' },
      ],
      explanation_en:'Regular verbs: add -ed. CVC → double consonant (stop→stopped). y→ied (carry→carried).',
      golden_rule_en:'+ed | CVC → double + ed (stop→stopped) | consonant+y → ied (carry→carried).',
      feedbackQuestion:{ question_en:'The past of "stop" is:', options_en:['stoped','stopped','stopt','stopping'], correct:1, explanation_en:'CVC → double p: stopped.' } },
    { id:'u3_l1_e4', type:'trueFalse', bloom:'apply', difficulty:'medium',
      question_en:'"She didn\'t watched TV" is correct.',
      paragraph:'After didn\'t → BASE verb (no -ed). didn\'t watch, NOT didn\'t watched.',
      options_en:['True','False'], correct:'false',
      explanation_en:'FALSE. After didn\'t → base: didn\'t watch (NOT watched).',
      golden_rule_en:'didn\'t + base verb. ❌ didn\'t watched | ✓ didn\'t watch.',
      feedbackQuestion:{ question_en:'She ( didn\'t call – didn\'t called ) her mom.', options_en:['didn\'t called','didn\'t call','doesn\'t call','wasn\'t call'], correct:1, explanation_en:'didn\'t + base: call.' } },
    { id:'u3_l1_e5', type:'multipleChoice', bloom:'apply', difficulty:'medium',
      question_en:'My dad (fix – fixed – fixes) my computer last week.',
      paragraph:'Last week = past. Regular verb: fix + ed = fixed.',
      options_en:['fix','fixed','fixes','fixing'], correct:1,
      explanation_en:'Last week = past → fixed (fix + ed).',
      golden_rule_en:'Past time → verb + ed (regular). yesterday, last week, last year.',
      feedbackQuestion:{ question_en:'My friend ( e-mail – e-mailed – emails ) me yesterday.', options_en:['e-mail','e-mailed','emails','e-mailing'], correct:1, explanation_en:'Yesterday → e-mailed.' } },
    { id:'u3_l1_e6', type:'classify', bloom:'analyze', difficulty:'hard',
      question_en:'Classify: Action (verb) or Thing (noun)?',
      paragraph:'Some words can be both: ride (verb: to ride) / ride (noun: a ride). leaves (verb) / leaves (noun).',
      categories:['Action (فعل)','Thing (شيء)'],
      items:[
        { text:'a ride to school', correct_category:1 },
        { text:'to ride a bike', correct_category:0 },
        { text:'leave school', correct_category:0 },
        { text:'autumn leaves', correct_category:1 },
        { text:'water the plants', correct_category:0 },
        { text:'a glass of water', correct_category:1 },
      ],
      explanation_en:'Some words function as both noun and verb depending on context.',
      golden_rule_en:'Same word can be noun (thing) or verb (action): ride, leave, water, play.',
      feedbackQuestion:{ question_en:'"I play football." — "play" is a/an:', options_en:['thing','action','adjective','place'], correct:1, explanation_en:'play = action (verb).' } },
    { id:'u3_l1_e7', type:'multipleChoice', bloom:'understand', difficulty:'medium',
      question_en:'The story "The Kind Man" has characters who are:',
      paragraph:'Characters in "The Kind Man": an old man and two young friends.',
      options_en:['animals','an old man and two young friends','only children','kings'], correct:1,
      explanation_en:'The characters of "The Kind Man" are an old man and two young friends.',
      golden_rule_en:'Characters = who is in the story. The Kind Man: old man + 2 young friends.',
      feedbackQuestion:{ question_en:'The SETTING of "The Kind Man" is:', options_en:['in a village','on top of a mountain','in a school','at a beach'], correct:1, explanation_en:'Setting = where. The Kind Man: on top of a mountain.' } },
    { id:'u3_l1_e8', type:'trueFalse', bloom:'remember', difficulty:'easy',
      question_en:'Regular past verbs are formed by adding -ed.',
      paragraph:'Regular verbs: base + ed. play→played, dream→dreamed, stop→stopped.',
      options_en:['True','False'], correct:'true',
      explanation_en:'Correct! Regular verbs form past by adding -ed.',
      golden_rule_en:'Regular Past = base + ed. (With CVC: double consonant. With y: ied.)',
      feedbackQuestion:{ question_en:'The past of "walk" is:', options_en:['walked','walkt','walks','walking'], correct:0, explanation_en:'walk → walked (+ed).' } },
    { id:'u3_l1_e9', type:'multipleChoice', bloom:'apply', difficulty:'medium',
      question_en:'He ( laugh – laughs – laughed ) at my joke last night.',
      paragraph:'Last night = past → laughed (laugh + ed).',
      options_en:['laugh','laughs','laughed','laughing'], correct:2,
      explanation_en:'Last night = past → laughed (regular: laugh + ed).',
      golden_rule_en:'Past time + regular verb → verb + ed.',
      feedbackQuestion:{ question_en:'She ( play – plays – played ) the piano yesterday.', options_en:['play','plays','played','playing'], correct:2, explanation_en:'Yesterday → played.' } },
    { id:'u3_l1_e10', type:'fillBlank', bloom:'apply', difficulty:'medium',
      question_en:'Yesterday, I _____ to school by bus. (go - irregular)',
      paragraph:'go is irregular: go → went (NOT goed).',
      blanks:['went'], wordBank:['went','goed','go','going'],
      explanation_en:'go → went (irregular). Yesterday I went to school.',
      golden_rule_en:'Irregular: go→went, see→saw, sleep→slept, take→took, come→came.',
      feedbackQuestion:{ question_en:'Last week, she _____ a movie. (see)', options_en:['saw','seed','see','seen'], correct:0, explanation_en:'see → saw.' } },
    { id:'u3_l1_e11', type:'multipleChoice', bloom:'remember', difficulty:'easy',
      question_en:'The past of "stop" is:',
      paragraph:'CVC (consonant-vowel-consonant) → double last consonant + ed. stop → stopped.',
      options_en:['stoped','stopped','stopt','stopping'], correct:1,
      explanation_en:'stop ends in CVC → double p: stopped (NOT stoped).',
      golden_rule_en:'CVC → double consonant + ed. stop→stopped, plan→planned, drop→dropped.',
      feedbackQuestion:{ question_en:'The past of "plan" is:', options_en:['planed','planned','plant','planning'], correct:1, explanation_en:'CVC → double n: planned.' } },
    { id:'u3_l1_e12', type:'trueFalse', bloom:'understand', difficulty:'medium',
      question_en:'"Did you played football?" is a correct past question.',
      paragraph:'After Did → base verb. Did you play (NOT played).',
      options_en:['True','False'], correct:'false',
      explanation_en:'FALSE. After Did → base verb: Did you play (NOT played).',
      golden_rule_en:'Did + subject + BASE verb. ❌ Did you played | ✓ Did you play.',
      feedbackQuestion:{ question_en:'Did he ( go – went ) to school?', options_en:['went','go','going','gone'], correct:1, explanation_en:'Did + base: go.' } },
    { id:'u3_l1_e13', type:'multipleChoice', bloom:'apply', difficulty:'medium',
      question_en:'They ( didn\'t – don\'t – doesn\'t ) play football last Friday.',
      paragraph:'Last Friday = past → didn\'t. Negative past: didn\'t + base.',
      options_en:['didn\'t','don\'t','doesn\'t','wasn\'t'], correct:0,
      explanation_en:'Last Friday = past → didn\'t. They didn\'t play football.',
      golden_rule_en:'Past negative: didn\'t + base verb. Present negative: don\'t/doesn\'t.',
      feedbackQuestion:{ question_en:'She ( didn\'t – doesn\'t ) go to school yesterday.', options_en:['doesn\'t','didn\'t','don\'t','isn\'t'], correct:1, explanation_en:'Yesterday = past → didn\'t.' } },
    { id:'u3_l1_e14', type:'matching', bloom:'remember', difficulty:'easy',
      question_en:'Match the question with the correct answer:',
      paragraph:'Past Simple questions and short answers. Did you...? → Yes, I did. / No, I didn\'t.',
      pairs:[
        { left:'Did you play football?', right:'Yes, I did.' },
        { left:'Did she go to school?', right:'No, she didn\'t.' },
        { left:'Did he watch TV?', right:'Yes, he did.' },
        { left:'Did they visit grandma?', right:'No, they didn\'t.' },
      ],
      explanation_en:'Past short answers: Yes + did | No + didn\'t.',
      golden_rule_en:'Did you...? → Yes, I did. / No, I didn\'t.',
      feedbackQuestion:{ question_en:'"Did you see the movie?" — Short positive answer:', options_en:['Yes, I saw.','Yes, I did.','No, I didn\'t.','Yes, I see.'], correct:1, explanation_en:'Yes, I did.' } },
    { id:'u3_l1_e15', type:'multipleChoice', bloom:'understand', difficulty:'medium',
      question_en:'"What did you do yesterday?" — This asks about:',
      paragraph:'What did you do = asks about past actions. Yesterday = past time signal.',
      options_en:['future plans','past actions','present routine','present actions'], correct:1,
      explanation_en:'Did + yesterday = asking about PAST actions.',
      golden_rule_en:'Did = past question word. What/Where/When + did + subject + base?',
      feedbackQuestion:{ question_en:'"Where did you go last week?" — asks about:', options_en:['past place','present place','future place','routine'], correct:0, explanation_en:'did + last week = past.' } },
  ],
  u3_l2: [
    { id:'u3_l2_e1', type:'matching', bloom:'remember', difficulty:'easy',
      question_en:'Match the irregular verb with its past form:',
      paragraph:'Irregular: go→went, see→saw, sleep→slept, take→took, come→came, eat→ate.',
      pairs:[
        { left:'go', right:'went' },
        { left:'see', right:'saw' },
        { left:'sleep', right:'slept' },
        { left:'take', right:'took' },
      ],
      explanation_en:'Irregular verbs don\'t follow -ed rule. Must be memorized.',
      golden_rule_en:'Irregular: go→went | see→saw | sleep→slept | take→took | come→came | eat→ate.',
      feedbackQuestion:{ question_en:'The past of "go" is:', options_en:['goed','went','gone','goes'], correct:1, explanation_en:'go → went.' } },
    { id:'u3_l2_e2', type:'multipleChoice', bloom:'apply', difficulty:'medium',
      question_en:'He ( play – plays – played ) soccer yesterday.',
      paragraph:'Yesterday = past. Regular verb: play + ed = played.',
      options_en:['play','plays','played','playing'], correct:2,
      explanation_en:'Yesterday = past → played (regular: +ed).',
      golden_rule_en:'Yesterday + regular verb → verb + ed.',
      feedbackQuestion:{ question_en:'He ( laughs – laughed ) at my joke last night.', options_en:['laughs','laughed','laughing','laugh'], correct:1, explanation_en:'Last night → laughed.' } },
    { id:'u3_l2_e3', type:'trueFalse', bloom:'analyze', difficulty:'medium',
      question_en:'"He didn\'t played soccer" is grammatically correct.',
      paragraph:'After didn\'t → BASE form. didn\'t play, NOT didn\'t played.',
      options_en:['True','False'], correct:'false',
      explanation_en:'FALSE. didn\'t + base: didn\'t play. NOT "didn\'t played".',
      golden_rule_en:'didn\'t + BASE. ❌ didn\'t played | ✓ didn\'t play.',
      feedbackQuestion:{ question_en:'Did you ( invite – invited ) your friends?', options_en:['invited','invite','inviting','invites'], correct:1, explanation_en:'Did + base: invite.' } },
    { id:'u3_l2_e4', type:'multipleChoice', bloom:'understand', difficulty:'medium',
      question_en:'In the story "The Kind Man", the SETTING is:',
      paragraph:'Story elements: Title, Characters, Setting. The Kind Man: setting = on top of a mountain.',
      options_en:['In a village','On the top of a mountain','At school','At the beach'], correct:1,
      explanation_en:'Setting = WHERE. The Kind Man takes place on the top of a mountain.',
      golden_rule_en:'Setting = مكان وزمان القصة. The Kind Man → on top of a mountain.',
      feedbackQuestion:{ question_en:'The CHARACTERS of "The Kind Man" are:', options_en:['An old man and two friends','Kings','Animals','Children only'], correct:0, explanation_en:'Characters = an old man and two young friends.' } },
    { id:'u3_l2_e5', type:'multipleChoice', bloom:'apply', difficulty:'medium',
      question_en:'I didn\'t ( watered – watering – water ) the plants.',
      paragraph:'After didn\'t → base form: water. No -ed, no -ing, no -s.',
      options_en:['watered','watering','water','waters'], correct:2,
      explanation_en:'didn\'t + base: water. I didn\'t water the plants.',
      golden_rule_en:'didn\'t + BASE verb. No -ed, no -ing, no -s.',
      feedbackQuestion:{ question_en:'Did she finish the story?', options_en:['Yes, she didn\'t.','No, she did.','No, she didn\'t.','Yes, she didn\'t finish.'], correct:2, explanation_en:'Negative short: No, she didn\'t.' } },
    { id:'u3_l2_e6', type:'classify', bloom:'apply', difficulty:'medium',
      question_en:'Classify: Regular or Irregular past verbs?',
      paragraph:'Regular: +ed (played, walked). Irregular: special forms (went, saw, took).',
      categories:['Regular (منتظم)','Irregular (غير منتظم)'],
      items:[
        { text:'play → played', correct_category:0 },
        { text:'go → went', correct_category:1 },
        { text:'walk → walked', correct_category:0 },
        { text:'see → saw', correct_category:1 },
        { text:'dream → dreamed', correct_category:0 },
        { text:'sleep → slept', correct_category:1 },
      ],
      explanation_en:'Regular: +ed. Irregular: unique forms must be memorized.',
      golden_rule_en:'Regular: +ed | Irregular: went, saw, took, slept, came, ate.',
      feedbackQuestion:{ question_en:'"See → saw" is:', options_en:['regular','irregular','both','neither'], correct:1, explanation_en:'saw ≠ seed. Irregular.' } },
    { id:'u3_l2_e7', type:'trueFalse', bloom:'remember', difficulty:'easy',
      question_en:'"Go → went" is an irregular past form.',
      paragraph:'go is irregular: went (NOT goed).',
      options_en:['True','False'], correct:'true',
      explanation_en:'Correct! go → went is irregular (not +ed).',
      golden_rule_en:'Irregular: go→went, see→saw, take→took, sleep→slept, come→came.',
      feedbackQuestion:{ question_en:'"Walk → walked" is:', options_en:['regular','irregular','both','neither'], correct:0, explanation_en:'walk + ed = regular.' } },
    { id:'u3_l2_e8', type:'multipleChoice', bloom:'apply', difficulty:'medium',
      question_en:'She ( go – goes – went ) to the market yesterday.',
      paragraph:'Yesterday = past. go is irregular → went.',
      options_en:['go','goes','went','going'], correct:2,
      explanation_en:'Yesterday = past. go → went (irregular).',
      golden_rule_en:'Past + irregular verb → special past form (went, saw, took).',
      feedbackQuestion:{ question_en:'He ( see – saw – seen ) a bird last night.', options_en:['see','saw','seen','sees'], correct:1, explanation_en:'see → saw.' } },
    { id:'u3_l2_e9', type:'fillBlank', bloom:'apply', difficulty:'medium',
      question_en:'Last night, I _____ well. (sleep - irregular)',
      paragraph:'sleep is irregular: sleep → slept.',
      blanks:['slept'], wordBank:['slept','sleeped','sleep','sleeping'],
      explanation_en:'sleep → slept (irregular). Last night I slept well.',
      golden_rule_en:'Irregular: sleep→slept, keep→kept, sweep→swept, weep→wept.',
      feedbackQuestion:{ question_en:'She _____ a photo of the mountain. (take)', options_en:['taked','took','take','taking'], correct:1, explanation_en:'take → took.' } },
    { id:'u3_l2_e10', type:'multipleChoice', bloom:'understand', difficulty:'medium',
      question_en:'"Did she go to school?" — The correct short answer is:',
      paragraph:'Past short answers: Yes, she did. / No, she didn\'t. Use did/didn\'t.',
      options_en:['Yes, she went.','Yes, she did.','No, she don\'t.','Yes, she does.'], correct:1,
      explanation_en:'Short answer to Did: Yes, she did. / No, she didn\'t. (Use did/didn\'t, not the verb).',
      golden_rule_en:'Did...? → Yes, I did. / No, I didn\'t. (Don\'t repeat the main verb.)',
      feedbackQuestion:{ question_en:'"Did they come?" — Negative short:', options_en:['No, they don\'t.','No, they didn\'t.','No, they weren\'t.','No, they aren\'t.'], correct:1, explanation_en:'No, they didn\'t.' } },
    { id:'u3_l2_e11', type:'trueFalse', bloom:'apply', difficulty:'medium',
      question_en:'"I goed to the park" is correct.',
      paragraph:'go is irregular → went, NOT goed.',
      options_en:['True','False'], correct:'false',
      explanation_en:'FALSE. go → went (irregular). NOT "goed".',
      golden_rule_en:'go → went. Never "goed".',
      feedbackQuestion:{ question_en:'"I _____ to the park yesterday." (go)', options_en:['goed','went','go','going'], correct:1, explanation_en:'go → went.' } },
    { id:'u3_l2_e12', type:'multipleChoice', bloom:'apply', difficulty:'hard',
      question_en:'Choose the correct sentence:',
      paragraph:'Past: regular +ed, irregular = special. didn\'t + base. Did + base.',
      options_en:['She didn\'t went to school.','She didn\'t go to school.','She didn\'t goes to school.','She didn\'t going to school.'], correct:1,
      explanation_en:'didn\'t + BASE verb: go. She didn\'t go (NOT went/goes/going).',
      golden_rule_en:'didn\'t + BASE. Even irregular verbs use base after didn\'t.',
      feedbackQuestion:{ question_en:'Did you ( take – took ) the bus?', options_en:['took','take','taking','taken'], correct:1, explanation_en:'Did + base: take.' } },
    { id:'u3_l2_e13', type:'matching', bloom:'remember', difficulty:'easy',
      question_en:'Match the irregular verb with its past form:',
      paragraph:'Irregular past forms: come→came, eat→ate, write→wrote, run→ran, give→gave, sing→sang.',
      pairs:[
        { left:'come', right:'came' },
        { left:'eat', right:'ate' },
        { left:'write', right:'wrote' },
        { left:'run', right:'ran' },
      ],
      explanation_en:'More irregular verbs. Must be memorized individually.',
      golden_rule_en:'Irregular: come→came, eat→ate, write→wrote, run→ran, give→gave.',
      feedbackQuestion:{ question_en:'The past of "eat" is:', options_en:['eated','ate','eats','eating'], correct:1, explanation_en:'eat → ate.' } },
    { id:'u3_l2_e14', type:'multipleChoice', bloom:'analyze', difficulty:'hard',
      question_en:'Which sentence has a grammar MISTAKE?',
      paragraph:'Rules: didn\'t + base. Did + base. Irregular verbs have special forms.',
      options_en:['She went home.','She didn\'t go home.','She goed home.','Did she go home?'], correct:2,
      explanation_en:'"She goed home" is WRONG. go → went (irregular, not goed).',
      golden_rule_en:'go → went. Never "goed".',
      feedbackQuestion:{ question_en:'Which is correct?', options_en:['He didn\'t went.','He didn\'t go.','He didn\'t goes.','He didn\'t going.'], correct:1, explanation_en:'didn\'t + base: go.' } },
    { id:'u3_l2_e15', type:'fillBlank', bloom:'apply', difficulty:'medium',
      question_en:'Yesterday, he _____ an email. (send - irregular)',
      paragraph:'send is irregular: send → sent.',
      blanks:['sent'], wordBank:['sent','sended','send','sending'],
      explanation_en:'send → sent (irregular). Yesterday he sent an email.',
      golden_rule_en:'Irregular: send→sent, spend→spent, build→built, lend→lent.',
      feedbackQuestion:{ question_en:'She _____ a letter yesterday. (write)', options_en:['writed','wrote','write','writing'], correct:1, explanation_en:'write → wrote.' } },
  ],
};