// Welcome Unit — Extra Questions (to reach ~40-50 per lesson)
export const WELCOME_EXTRA = {
  wel_l1: [
    { id:'wel_l1_e1', type:'multipleChoice', bloom:'remember', difficulty:'easy',
      question_en:'The word "exciting" means something that makes you feel:',
      paragraph:'exciting - مثير | terrible - سيء جداً | dangerous - خطير | different - مختلف',
      options_en:['bored','thrilled/happy','afraid','tired'], correct:1,
      explanation_en:'"Exciting" means something that fills you with thrill and enthusiasm.',
      golden_rule_en:'exciting = مثير = fills you with enthusiasm and joy.',
      feedbackQuestion:{ question_en:'A football match can be very _____ to watch.', options_en:['terrible','exciting','dangerous','afraid'], correct:1, explanation_en:'exciting = مثير.' } },
    { id:'wel_l1_e2', type:'trueFalse', bloom:'understand', difficulty:'easy',
      question_en:'If someone is "surprised", it means they expected what happened.',
      paragraph:'surprised - متفاجئ — describes someone who did NOT expect something to happen.',
      options_en:['True','False'], correct:'false',
      explanation_en:'"Surprised" means you did NOT expect it. Example: I was surprised by the gift.',
      golden_rule_en:'surprised = متفاجئ = did not expect something.',
      feedbackQuestion:{ question_en:'When I got the gift, I was very _____.', options_en:['afraid','surprised','terrible','different'], correct:1, explanation_en:'surprised = متفاجئ.' } },
    { id:'wel_l1_e3', type:'multipleChoice', bloom:'apply', difficulty:'medium',
      question_en:'The snake is _____ . Do not touch it. (dangerous)',
      paragraph:'dangerous - خطير — used to describe something that can harm you.',
      options_en:['brilliant','dangerous','exciting','different'], correct:1,
      explanation_en:'"Dangerous" means it can harm you. A snake is dangerous.',
      golden_rule_en:'dangerous = خطير = can cause harm.',
      feedbackQuestion:{ question_en:'The road is very _____ at night. Drive carefully.', options_en:['safe','dangerous','brilliant','exciting'], correct:1, explanation_en:'dangerous = خطير.' } },
    { id:'wel_l1_e4', type:'multipleChoice', bloom:'understand', difficulty:'medium',
      question_en:'My friend is not the same as me. He is _____ .',
      paragraph:'different - مختلف — not the same as something/someone else.',
      options_en:['the same','similar','different','identical'], correct:2,
      explanation_en:'"Different" means not the same. My friend is different from me.',
      golden_rule_en:'different = مختلف = not the same.',
      feedbackQuestion:{ question_en:'These two shirts are not the same. They are _____.', options_en:['same','different','similar','identical'], correct:1, explanation_en:'different = مختلف.' } },
    { id:'wel_l1_e5', type:'classify', bloom:'apply', difficulty:'medium',
      question_en:'Classify: Positive or Negative adjectives?',
      paragraph:'Positive adjectives describe good things | Negative adjectives describe bad things.',
      categories:['Positive (إيجابي)','Negative (سلبي)'],
      items:[
        { text:'brilliant', correct_category:0 },
        { text:'exciting', correct_category:0 },
        { text:'helpful', correct_category:0 },
        { text:'terrible', correct_category:1 },
        { text:'naughty', correct_category:1 },
        { text:'dangerous', correct_category:1 },
      ],
      explanation_en:'brilliant/exciting/helpful = positive. terrible/naughty/dangerous = negative.',
      golden_rule_en:'Positive: brilliant, exciting, helpful | Negative: terrible, naughty, dangerous.',
      feedbackQuestion:{ question_en:'"Terrible" is a _____ adjective.', options_en:['positive','negative','neutral','question'], correct:1, explanation_en:'terrible = سيء جداً = negative.' } },
    { id:'wel_l1_e6', type:'multipleChoice', bloom:'remember', difficulty:'easy',
      question_en:'The past form of "is" (for I) is:',
      paragraph:'was/were: I/he/she/it → was | you/we/they → were. I was at school.',
      options_en:['were','was','is','are'], correct:1,
      explanation_en:'"I" uses "was". I was, he was, she was, it was.',
      golden_rule_en:'I/he/she/it → was | you/we/they → were.',
      feedbackQuestion:{ question_en:'They ( was – were ) at the party last night.', options_en:['was','were','is','are'], correct:1, explanation_en:'they → were.' } },
    { id:'wel_l1_e7', type:'trueFalse', bloom:'understand', difficulty:'medium',
      question_en:'We use "was" with "they" in the past tense.',
      paragraph:'was = singular (I, he, she, it) | were = plural (you, we, they).',
      options_en:['True','False'], correct:'false',
      explanation_en:'FALSE. "They" is plural → use "were", not "was".',
      golden_rule_en:'they/we/you → were. I/he/she/it → was.',
      feedbackQuestion:{ question_en:'He ( was – were ) at home yesterday.', options_en:['were','was','is','are'], correct:1, explanation_en:'he → was.' } },
    { id:'wel_l1_e8', type:'multipleChoice', bloom:'apply', difficulty:'medium',
      question_en:'My mark is ( good – better – best ) than yesterday. Comparing TWO marks:',
      paragraph:'Comparative: comparing 2 things → adjective + er + than. good → better (irregular).',
      options_en:['good','better','best','more good'], correct:1,
      explanation_en:'Comparing 2 marks → comparative. good → better (irregular, not "gooder").',
      golden_rule_en:'Comparative (2 things): good → better, bad → worse, tall → taller.',
      feedbackQuestion:{ question_en:'This book is ( good – better – best ) than that one.', options_en:['good','better','best','more good'], correct:1, explanation_en:'better = comparative of good.' } },
    { id:'wel_l1_e9', type:'ordering', bloom:'apply', difficulty:'medium',
      question_en:'Reorder: never / I / early / sleep',
      paragraph:'Adverb of frequency: Subject + Adverb + Verb + Object. I never sleep early.',
      items:['I','never','sleep','early'], correctOrder:[0,1,2,3],
      explanation_en:'I (subject) + never (adverb) + sleep (verb) + early (adverb of time).',
      golden_rule_en:'Subject + Adverb of Frequency + Main Verb + rest.',
      feedbackQuestion:{ question_en:'Which is correct?', options_en:['I sleep never early.','Never I sleep early.','I never sleep early.','I early never sleep.'], correct:2, explanation_en:'I never sleep early.' } },
    { id:'wel_l1_e10', type:'multipleChoice', bloom:'apply', difficulty:'medium',
      question_en:'She ( is – was – were ) at the hospital last weekend.',
      paragraph:'"Last weekend" = past → was/were. She (singular) → was.',
      options_en:['is','was','were','are'], correct:1,
      explanation_en:'"Last weekend" = past. She (singular) → was.',
      golden_rule_en:'Past: she → was. Present: she → is.',
      feedbackQuestion:{ question_en:'I ( am – was – were ) in Makkah last week.', options_en:['am','was','were','is'], correct:1, explanation_en:'I → was (past).' } },
    { id:'wel_l1_e11', type:'trueFalse', bloom:'remember', difficulty:'easy',
      question_en:'"Afraid" and "scared" have similar meanings.',
      paragraph:'afraid = خائف | scared = خائف — both mean feeling fear.',
      options_en:['True','False'], correct:'true',
      explanation_en:'Correct! afraid = scared. Both mean feeling fear (خائف).',
      golden_rule_en:'afraid = scared = خائف.',
      feedbackQuestion:{ question_en:'I am _____ of the dark. (I fear the dark)', options_en:['brilliant','afraid','exciting','different'], correct:1, explanation_en:'afraid = خائف.' } },
    { id:'wel_l1_e12', type:'multipleChoice', bloom:'understand', difficulty:'medium',
      question_en:'Sara always helps her friends. She is very _____.',
      paragraph:'helpful = مساعد — likes to help others.',
      options_en:['naughty','helpful','afraid','terrible'], correct:1,
      explanation_en:'"Helpful" = likes to help. Sara always helps → she is helpful.',
      golden_rule_en:'helpful = مساعد = likes to help.',
      feedbackQuestion:{ question_en:'A _____ person always helps others.', options_en:['naughty','helpful','shy','lazy'], correct:1, explanation_en:'helpful = مساعد.' } },
    { id:'wel_l1_e13', type:'matching', bloom:'remember', difficulty:'easy',
      question_en:'Match the adjective with its Arabic meaning:',
      paragraph:'Welcome unit key adjectives: afraid, brilliant, dangerous, different, exciting, naughty, terrible, surprised.',
      pairs:[
        { left:'exciting', right:'مثير' },
        { left:'surprised', right:'متفاجئ' },
        { left:'helpful', right:'مساعد' },
        { left:'terrible', right:'سيء جداً' },
      ],
      explanation_en:'Match each adjective with its Arabic translation.',
      golden_rule_en:'exciting=مثير | surprised=متفاجئ | helpful=مساعد | terrible=سيء جداً.',
      feedbackQuestion:{ question_en:'"Surprised" in Arabic is:', options_en:['خائف','متفاجئ','ذكي','شقي'], correct:1, explanation_en:'surprised = متفاجئ.' } },
    { id:'wel_l1_e14', type:'multipleChoice', bloom:'apply', difficulty:'hard',
      question_en:'Choose the correct sentence:',
      paragraph:'Word order: Subject + Adverb of Frequency + Main Verb. Was/were for past.',
      options_en:['She always is helpful.','She is always helpful.','Always she is helpful.','She is helpful always.'], correct:1,
      explanation_en:'Adverb of frequency (always) comes AFTER the verb "to be". She is always helpful.',
      golden_rule_en:'With verb "to be": Subject + is/am/are + Adverb of Frequency. She is always helpful.',
      feedbackQuestion:{ question_en:'He _____ late for school. (never + is)', options_en:['never is','is never','never','is'], correct:1, explanation_en:'After "is": He is never late.' } },
    { id:'wel_l1_e15', type:'trueFalse', bloom:'understand', difficulty:'medium',
      question_en:'"I\'m doing my homework" means I finished it already.',
      paragraph:'Present Progressive: am/is/are + verb + ing = happening NOW.',
      options_en:['True','False'], correct:'false',
      explanation_en:'FALSE. "I\'m doing" = I am doing it NOW (not finished yet).',
      golden_rule_en:'I\'m doing = happening now (Present Progressive).',
      feedbackQuestion:{ question_en:'She ( is – was ) brushing her teeth now.', options_en:['is','was','are','were'], correct:0, explanation_en:'"now" → Present Progressive → is.' } },
    { id:'wel_l1_e16', type:'multipleChoice', bloom:'apply', difficulty:'medium',
      question_en:'My sister is ( short – shorter – shortest ) than me.',
      paragraph:'Comparative: short adjective + er + than. Comparing 2 people.',
      options_en:['short','shorter','shortest','more short'], correct:1,
      explanation_en:'Comparing 2 (my sister and me) → shorter than.',
      golden_rule_en:'Comparative (2): adjective + er + than.',
      feedbackQuestion:{ question_en:'Ahmad is ( tall – taller – tallest ) than his brother.', options_en:['tall','taller','tallest','more tall'], correct:1, explanation_en:'Comparing 2 → taller.' } },
    { id:'wel_l1_e17', type:'classify', bloom:'apply', difficulty:'medium',
      question_en:'Classify: was or were?',
      paragraph:'was = I/he/she/it | were = you/we/they.',
      categories:['Use "was"','Use "were"'],
      items:[
        { text:'She', correct_category:0 },
        { text:'It', correct_category:0 },
        { text:'They', correct_category:1 },
        { text:'We', correct_category:1 },
        { text:'He', correct_category:0 },
        { text:'You', correct_category:1 },
      ],
      explanation_en:'Singular pronouns → was. Plural pronouns + you → were.',
      golden_rule_en:'was: I, he, she, it | were: you, we, they.',
      feedbackQuestion:{ question_en:'The cat ( was – were ) sleeping.', options_en:['was','were','is','are'], correct:0, explanation_en:'The cat (it) → was.' } },
    { id:'wel_l1_e18', type:'fillBlank', bloom:'apply', difficulty:'medium',
      question_en:'The opposite of "always" is _____ .',
      paragraph:'Adverbs of frequency: always(100%) ↔ never(0%).',
      blanks:['never'], wordBank:['never','often','sometimes','usually'],
      explanation_en:'always = 100%. Its opposite = never = 0%.',
      golden_rule_en:'always ↔ never | often ↔ rarely.',
      feedbackQuestion:{ question_en:'I _____ eat pizza. (0% of the time)', options_en:['always','never','often','usually'], correct:1, explanation_en:'never = 0%.' } },
    { id:'wel_l1_e19', type:'multipleChoice', bloom:'remember', difficulty:'easy',
      question_en:'"Brilliant" is closest in meaning to:',
      paragraph:'brilliant = very smart/clever. Synonyms: smart, clever, intelligent.',
      options_en:['scared','smart','naughty','terrible'], correct:1,
      explanation_en:'brilliant = smart/clever/ذكي.',
      golden_rule_en:'brilliant = smart = clever = ذكي.',
      feedbackQuestion:{ question_en:'A _____ student gets high marks.', options_en:['naughty','brilliant','afraid','terrible'], correct:1, explanation_en:'brilliant = smart student.' } },
    { id:'wel_l1_e20', type:'trueFalse', bloom:'understand', difficulty:'easy',
      question_en:'"Different" means "the same".',
      paragraph:'different = مختلف = NOT the same.',
      options_en:['True','False'], correct:'false',
      explanation_en:'FALSE. different = NOT the same. It means مختلف.',
      golden_rule_en:'different ≠ same. different = مختلف.',
      feedbackQuestion:{ question_en:'My two shoes are not the same. They are _____.', options_en:['same','different','identical','similar'], correct:1, explanation_en:'different = مختلف.' } },
  ],
  wel_l2: [
    { id:'wel_l2_e1', type:'multipleChoice', bloom:'remember', difficulty:'easy',
      question_en:'The comparative of "good" is:',
      paragraph:'Irregular comparatives: good → better → best | bad → worse → worst.',
      options_en:['gooder','better','more good','best'], correct:1,
      explanation_en:'good is irregular: good → better (comparative) → best (superlative).',
      golden_rule_en:'good → better → best (irregular, NOT "gooder").',
      feedbackQuestion:{ question_en:'The superlative of "good" is:', options_en:['gooder','better','best','more good'], correct:2, explanation_en:'good → better → best.' } },
    { id:'wel_l2_e2', type:'multipleChoice', bloom:'apply', difficulty:'medium',
      question_en:'This is the ( good – better – best ) book I have ever read. Comparing ALL my books:',
      paragraph:'Superlative: the + adjective + est. Comparing 3 or more. good → the best.',
      options_en:['good','better','best','more good'], correct:2,
      explanation_en:'"The best book I have ever read" = comparing all books → superlative: the best.',
      golden_rule_en:'Superlative (3+): the + best, the + tallest, the + most interesting.',
      feedbackQuestion:{ question_en:'She is the ( good – better – best ) student in the class.', options_en:['good','better','best','more good'], correct:2, explanation_en:'Superlative → the best.' } },
    { id:'wel_l2_e3', type:'trueFalse', bloom:'understand', difficulty:'medium',
      question_en:'The comparative of "bad" is "badder".',
      paragraph:'Irregular: bad → worse (comparative) → worst (superlative).',
      options_en:['True','False'], correct:'false',
      explanation_en:'FALSE. bad → worse (NOT "badder"). Irregular adjective.',
      golden_rule_en:'bad → worse → worst. Never "badder" or "baddest".',
      feedbackQuestion:{ question_en:'Today\'s weather is ( bad – worse – worst ) than yesterday.', options_en:['bad','worse','worst','badder'], correct:1, explanation_en:'Comparing 2 days → worse.' } },
    { id:'wel_l2_e4', type:'classify', bloom:'apply', difficulty:'hard',
      question_en:'Classify: comparative or superlative form?',
      paragraph:'Comparative: -er/more + than (2 things) | Superlative: the + -est/most (3+ things).',
      categories:['Comparative (مقارنة)','Superlative (تفضيل)'],
      items:[
        { text:'taller than', correct_category:0 },
        { text:'the tallest', correct_category:1 },
        { text:'more beautiful than', correct_category:0 },
        { text:'the most beautiful', correct_category:1 },
        { text:'worse than', correct_category:0 },
        { text:'the worst', correct_category:1 },
      ],
      explanation_en:'Comparative compares 2 (uses "than"). Superlative compares 3+ (uses "the").',
      golden_rule_en:'Comparative + than | The + superlative.',
      feedbackQuestion:{ question_en:'"The most interesting" is a _____ form.', options_en:['comparative','superlative','positive','negative'], correct:1, explanation_en:'the most + adjective = superlative.' } },
    { id:'wel_l2_e5', type:'multipleChoice', bloom:'apply', difficulty:'medium',
      question_en:'Art is ( interesting – more interesting – most interesting ) than math.',
      paragraph:'Long adjectives (2+ syllables): comparative = more + adjective + than.',
      options_en:['interesting','more interesting','most interesting','interestinger'], correct:1,
      explanation_en:'"Interesting" is a long adjective → comparative = more interesting than.',
      golden_rule_en:'Long adjective comparative: more + adjective + than. more beautiful, more interesting.',
      feedbackQuestion:{ question_en:'Science is the ( interesting – more interesting – most interesting ) subject.', options_en:['interesting','more interesting','most interesting','interestinger'], correct:2, explanation_en:'Superlative of long adjective: the most interesting.' } },
    { id:'wel_l2_e6', type:'ordering', bloom:'remember', difficulty:'easy',
      question_en:'Order the ordinal numbers: fourth / first / third / second',
      paragraph:'Ordinal numbers: 1st=first, 2nd=second, 3rd=third, 4th=fourth.',
      items:['first','second','third','fourth'], correctOrder:[0,1,2,3],
      explanation_en:'1st → first, 2nd → second, 3rd → third, 4th → fourth.',
      golden_rule_en:'1st=first, 2nd=second, 3rd=third, 4th=fourth, 5th=fifth.',
      feedbackQuestion:{ question_en:'The _____ day of the week is Sunday (if Saturday is 1st).', options_en:['first','second','third','fourth'], correct:1, explanation_en:'Saturday=1st, Sunday=2nd.' } },
    { id:'wel_l2_e7', type:'trueFalse', bloom:'remember', difficulty:'easy',
      question_en:'The short form of "third" is "3rd".',
      paragraph:'Ordinal short forms: 1st, 2nd, 3rd, 4th, 5th.',
      options_en:['True','False'], correct:'true',
      explanation_en:'Correct! third = 3rd. Only 1st, 2nd, 3rd are irregular; rest use -th.',
      golden_rule_en:'1st, 2nd, 3rd are irregular. 4th onwards = number + th.',
      feedbackQuestion:{ question_en:'The short form of "second" is:', options_en:['2st','2nd','2th','2rd'], correct:1, explanation_en:'second = 2nd.' } },
    { id:'wel_l2_e8', type:'multipleChoice', bloom:'apply', difficulty:'medium',
      question_en:'He is the ( tall – taller – tallest ) boy in the class.',
      paragraph:'Superlative: the + adjective + est. Comparing all students in class.',
      options_en:['tall','taller','tallest','more tall'], correct:2,
      explanation_en:'"In the class" = comparing all → superlative: the tallest.',
      golden_rule_en:'Superlative: the + adjective + est (short) | the most + adjective (long).',
      feedbackQuestion:{ question_en:'She is the ( good – better – best ) player on the team.', options_en:['good','better','best','more good'], correct:2, explanation_en:'Superlative of good = the best.' } },
    { id:'wel_l2_e9', type:'matching', bloom:'remember', difficulty:'easy',
      question_en:'Match the ordinal with its short form:',
      paragraph:'Ordinal short forms: first=1st, second=2nd, third=3rd, fourth=4th, fifth=5th.',
      pairs:[
        { left:'first', right:'1st' },
        { left:'second', right:'2nd' },
        { left:'third', right:'3rd' },
        { left:'fourth', right:'4th' },
      ],
      explanation_en:'Ordinal short forms use the last 2 letters: 1st, 2nd, 3rd, 4th.',
      golden_rule_en:'1st, 2nd, 3rd, 4th, 5th, 6th...21st, 22nd, 23rd.',
      feedbackQuestion:{ question_en:'The short form of "fifth" is:', options_en:['5st','5nd','5th','5rd'], correct:2, explanation_en:'fifth = 5th.' } },
    { id:'wel_l2_e10', type:'multipleChoice', bloom:'understand', difficulty:'medium',
      question_en:'My mark is ( good – better – best ) than Ali\'s mark.',
      paragraph:'Comparing 2 marks (mine and Ali\'s) → comparative. good → better.',
      options_en:['good','better','best','more good'], correct:1,
      explanation_en:'Comparing 2 marks → better than. Irregular: good → better.',
      golden_rule_en:'Comparative (2 things): good → better than.',
      feedbackQuestion:{ question_en:'This cake is ( good – better – best ) than the one I made yesterday.', options_en:['good','better','best','more good'], correct:1, explanation_en:'Comparing 2 cakes → better.' } },
    { id:'wel_l2_e11', type:'trueFalse', bloom:'understand', difficulty:'medium',
      question_en:'"The worst" is the superlative form of "bad".',
      paragraph:'bad → worse (comparative) → worst (superlative). Irregular.',
      options_en:['True','False'], correct:'true',
      explanation_en:'Correct! bad → worse → worst. "The worst" = superlative of bad.',
      golden_rule_en:'bad → worse → worst (irregular).',
      feedbackQuestion:{ question_en:'That was the ( bad – worse – worst ) movie ever.', options_en:['bad','worse','worst','badder'], correct:2, explanation_en:'Superlative of bad = worst.' } },
    { id:'wel_l2_e12', type:'classify', bloom:'apply', difficulty:'hard',
      question_en:'Classify: short adjective or long adjective?',
      paragraph:'Short adjectives (1 syllable): tall, big, small → +er/est | Long adjectives (2+ syllables): beautiful, interesting → more/most.',
      categories:['Short adjective (+er/est)','Long adjective (more/most)'],
      items:[
        { text:'tall', correct_category:0 },
        { text:'small', correct_category:0 },
        { text:'beautiful', correct_category:1 },
        { text:'interesting', correct_category:1 },
        { text:'big', correct_category:0 },
        { text:'expensive', correct_category:1 },
      ],
      explanation_en:'Short (1 syllable) → +er/est. Long (2+ syllables) → more/most.',
      golden_rule_en:'Short: tall→taller→tallest | Long: beautiful→more beautiful→most beautiful.',
      feedbackQuestion:{ question_en:'The comparative of "expensive" is:', options_en:['expensiver','more expensive','most expensive','expensiveer'], correct:1, explanation_en:'Long adjective → more expensive.' } },
    { id:'wel_l2_e13', type:'multipleChoice', bloom:'apply', difficulty:'medium',
      question_en:'She is ( happy – happier – happiest ) than her sister.',
      paragraph:'Short adjective ending in -y: y → ier. happy → happier → happiest.',
      options_en:['happy','happier','happiest','more happy'], correct:1,
      explanation_en:'happy → happier (y → ier). Comparative: happier than.',
      golden_rule_en:'Adjective ending in consonant+y: y → ier. happy → happier, lucky → luckier.',
      feedbackQuestion:{ question_en:'He is the ( happy – happier – happiest ) person I know.', options_en:['happy','happier','happiest','more happy'], correct:2, explanation_en:'Superlative: happiest (y → iest).' } },
    { id:'wel_l2_e14', type:'fillBlank', bloom:'remember', difficulty:'easy',
      question_en:'The superlative of "good" is the _____ .',
      paragraph:'Irregular: good → better → best. Superlative = the best.',
      blanks:['best'], wordBank:['best','better','good','more good'],
      explanation_en:'good → better (comparative) → best (superlative). The best.',
      golden_rule_en:'good → better → best.',
      feedbackQuestion:{ question_en:'The comparative of "bad" is _____ .', options_en:['worse','worst','badder','bad'], correct:0, explanation_en:'bad → worse.' } },
    { id:'wel_l2_e15', type:'multipleChoice', bloom:'understand', difficulty:'medium',
      question_en:'"Big" is a _____ adjective, so we add -er/-est.',
      paragraph:'Short adjectives (1 syllable): big, tall, small → bigger/biggest, taller/tallest.',
      options_en:['long','short','irregular','special'], correct:1,
      explanation_en:'"Big" is a short adjective (1 syllable) → big → bigger → biggest.',
      golden_rule_en:'Short adjective (1 syllable) → +er, +est. big → bigger → biggest.',
      feedbackQuestion:{ question_en:'The comparative of "big" is:', options_en:['bigger','more big','biggest','biger'], correct:0, explanation_en:'Short adjective → bigger (double g: big → bigger).' } },
    { id:'wel_l2_e16', type:'trueFalse', bloom:'apply', difficulty:'medium',
      question_en:'The comparative of "big" is "biger" (one g).',
      paragraph:'Short adjective ending in CVC (consonant-vowel-consonant): double the last letter. big → bigger.',
      options_en:['True','False'], correct:'false',
      explanation_en:'FALSE. big → bigger (double the g). CVC pattern → double consonant.',
      golden_rule_en:'CVC adjectives double the last consonant: big → bigger, hot → hotter, thin → thinner.',
      feedbackQuestion:{ question_en:'The comparative of "hot" is:', options_en:['hoter','hotter','more hot','hottest'], correct:1, explanation_en:'hot → hotter (CVC → double t).' } },
    { id:'wel_l2_e17', type:'multipleChoice', bloom:'remember', difficulty:'easy',
      question_en:'The ordinal number for 5 is:',
      paragraph:'Ordinal numbers: 1=first, 2=second, 3=third, 4=fourth, 5=fifth.',
      options_en:['fiveth','fifth','five','fivth'], correct:1,
      explanation_en:'5 → fifth (irregular spelling: five → fifth, not "fiveth").',
      golden_rule_en:'5 = fifth, 8 = eighth, 9 = ninth, 12 = twelfth (special spellings).',
      feedbackQuestion:{ question_en:'The ordinal for 8 is:', options_en:['eightth','eighth','eight','eigheth'], correct:1, explanation_en:'8 → eighth (just add -h, not "eightth").' } },
    { id:'wel_l2_e18', type:'ordering', bloom:'remember', difficulty:'easy',
      question_en:'Order from 1st to 5th: fifth / third / first / fourth / second',
      paragraph:'Ordinal sequence: 1st first, 2nd second, 3rd third, 4th fourth, 5th fifth.',
      items:['first','second','third','fourth','fifth'], correctOrder:[0,1,2,3,4],
      explanation_en:'1st → first, 2nd → second, 3rd → third, 4th → fourth, 5th → fifth.',
      golden_rule_en:'Ordinal order: first, second, third, fourth, fifth.',
      feedbackQuestion:{ question_en:'The _____ month of the year is May.', options_en:['first','third','fifth','second'], correct:2, explanation_en:'May = 5th month → fifth.' } },
    { id:'wel_l2_e19', type:'multipleChoice', bloom:'apply', difficulty:'hard',
      question_en:'Choose the correct sentence:',
      paragraph:'Superlative needs "the" before it. Comparative uses "than".',
      options_en:['She is tallest girl.','She is the tallest girl.','She is taller than all girls.','She is tallest than all.'], correct:1,
      explanation_en:'Superlative needs "the": She is the tallest girl. Comparing all → superlative.',
      golden_rule_en:'Superlative = the + adjective + est. "the" is required.',
      feedbackQuestion:{ question_en:'He is _____ student in the class. (superlative of tall)', options_en:['taller','the tallest','tallest','more tall'], correct:1, explanation_en:'Superlative: the tallest.' } },
    { id:'wel_l2_e20', type:'trueFalse', bloom:'understand', difficulty:'easy',
      question_en:'"More tall" is the correct comparative form of "tall".',
      paragraph:'Short adjectives (1 syllable) → +er. tall → taller (NOT "more tall").',
      options_en:['True','False'], correct:'false',
      explanation_en:'FALSE. "tall" is short → taller (NOT "more tall"). "More" is for long adjectives.',
      golden_rule_en:'Short adjective → +er (taller). Long adjective → more + adjective (more beautiful).',
      feedbackQuestion:{ question_en:'The comparative of "beautiful" is:', options_en:['beautifuler','more beautiful','beautifuller','most beautiful'], correct:1, explanation_en:'Long adjective → more beautiful.' } },
  ],
};