// Quantitative - Statistics & Probability (30 real GAT-style questions)
export default [
  {
    question_ar: "ما متوسط الأعداد: 4، 8، 6، 10، 12؟",
    question_en: "What is the average of: 4, 8, 6, 10, 12?",
    type: "multiple_choice",
    options_ar: ["6", "7", "8", "9"],
    options_en: ["6", "7", "8", "9"],
    correct_answer: "2",
    explanation_ar: "المجموع = 40، المتوسط = 40 ÷ 5 = 8",
    explanation_en: "Sum = 40, average = 40 ÷ 5 = 8",
    difficulty: "easy"
  },
  {
    question_ar: "ما وسيط الأعداد: 3، 7، 9، 11، 15؟",
    question_en: "What is the median of: 3, 7, 9, 11, 15?",
    type: "multiple_choice",
    options_ar: ["7", "9", "11", "10"],
    options_en: ["7", "9", "11", "10"],
    correct_answer: "1",
    explanation_ar: "العدد الأوسط بعد الترتيب هو 9",
    explanation_en: "The middle value after sorting is 9",
    difficulty: "easy"
  },
  {
    question_ar: "ما منوال الأعداد: 2، 4، 4، 6، 8، 4، 10؟",
    question_en: "What is the mode of: 2, 4, 4, 6, 8, 4, 10?",
    type: "multiple_choice",
    options_ar: ["2", "4", "6", "8"],
    options_en: ["2", "4", "6", "8"],
    correct_answer: "1",
    explanation_ar: "العدد الأكثر تكراراً هو 4 (ثلاث مرات)",
    explanation_en: "The most frequent number is 4 (three times)",
    difficulty: "easy"
  },
  {
    question_ar: "ما احتمال ظهور وجه عند رمي عملة مرة واحدة؟",
    question_en: "What is the probability of heads in a single coin toss?",
    type: "multiple_choice",
    options_ar: ["1/4", "1/3", "1/2", "2/3"],
    options_en: ["1/4", "1/3", "1/2", "2/3"],
    correct_answer: "2",
    explanation_ar: "نتيجتان محتملتان، وجه واحد، فالاحتمال = 1/2",
    explanation_en: "Two outcomes, one head, probability = 1/2",
    difficulty: "easy"
  },
  {
    question_ar: "ما احتمال ظهور عدد زوجي عند رمي حجر نرد مرة واحدة؟",
    question_en: "What is the probability of an even number on a single die roll?",
    type: "multiple_choice",
    options_ar: ["1/6", "1/3", "1/2", "2/3"],
    options_en: ["1/6", "1/3", "1/2", "2/3"],
    correct_answer: "2",
    explanation_ar: "3 أعداد زوجية من 6، الاحتمال = 3/6 = 1/2",
    explanation_en: "3 even numbers out of 6, probability = 3/6 = 1/2",
    difficulty: "easy"
  },
  {
    question_ar: "إذا كان متوسط 5 أعداد هو 12، فما مجموعها؟",
    question_en: "If the average of 5 numbers is 12, what is their sum?",
    type: "multiple_choice",
    options_ar: ["50", "55", "60", "65"],
    options_en: ["50", "55", "60", "65"],
    correct_answer: "2",
    explanation_ar: "المجموع = المتوسط × العدد = 12 × 5 = 60",
    explanation_en: "Sum = average × count = 12 × 5 = 60",
    difficulty: "easy"
  },
  {
    question_ar: "ما احتمال ظهور عدد أكبر من 4 عند رمي حجر نرد؟",
    question_en: "What is the probability of a number greater than 4 on a die?",
    type: "multiple_choice",
    options_ar: ["1/6", "1/3", "1/2", "2/3"],
    options_en: ["1/6", "1/3", "1/2", "2/3"],
    correct_answer: "1",
    explanation_ar: "العددان 5 و6 أكبر من 4، الاحتمال = 2/6 = 1/3",
    explanation_en: "5 and 6 are greater than 4, probability = 2/6 = 1/3",
    difficulty: "medium"
  },
  {
    question_ar: "ما نطاق الأعداد: 15، 22، 8، 30، 12؟",
    question_en: "What is the range of: 15, 22, 8, 30, 12?",
    type: "multiple_choice",
    options_ar: ["18", "20", "22", "30"],
    options_en: ["18", "20", "22", "30"],
    correct_answer: "2",
    explanation_ar: "النطاق = الأكبر - الأصغر = 30 - 8 = 22",
    explanation_en: "Range = max - min = 30 - 8 = 22",
    difficulty: "easy"
  },
  {
    question_ar: "في كيس 5 كرات حمراء و3 زرقاء، ما احتمال سحب كرة حمراء؟",
    question_en: "A bag has 5 red and 3 blue balls; what is the probability of drawing red?",
    type: "multiple_choice",
    options_ar: ["3/8", "5/8", "5/3", "1/2"],
    options_en: ["3/8", "5/8", "5/3", "1/2"],
    correct_answer: "1",
    explanation_ar: "الحمر 5 من أصل 8، الاحتمال = 5/8",
    explanation_en: "Red are 5 of 8, probability = 5/8",
    difficulty: "easy"
  },
  {
    question_ar: "ما متوسط الأعداد: 10، 20، 30، 40، 50؟",
    question_en: "What is the average of: 10, 20, 30, 40, 50?",
    type: "multiple_choice",
    options_ar: ["25", "28", "30", "35"],
    options_en: ["25", "28", "30", "35"],
    correct_answer: "2",
    explanation_ar: "المجموع = 150، المتوسط = 150 ÷ 5 = 30",
    explanation_en: "Sum = 150, average = 150 ÷ 5 = 30",
    difficulty: "easy"
  },
  {
    question_ar: "ما احتمال ظهور رقم 3 عند رمي حجر نرد مرة واحدة؟",
    question_en: "What is the probability of rolling a 3 on a die?",
    type: "multiple_choice",
    options_ar: ["1/6", "1/3", "1/2", "5/6"],
    options_en: ["1/6", "1/3", "1/2", "5/6"],
    correct_answer: "0",
    explanation_ar: "وجه واحد من 6، الاحتمال = 1/6",
    explanation_en: "One face out of 6, probability = 1/6",
    difficulty: "easy"
  },
  {
    question_ar: "إذا كانت درجات طالب: 80، 85، 90، فما متوسط درجاته؟",
    question_en: "A student's grades: 80, 85, 90; what is the average?",
    type: "multiple_choice",
    options_ar: ["82", "83", "85", "88"],
    options_en: ["82", "83", "85", "88"],
    correct_answer: "2",
    explanation_ar: "المجموع = 255، المتوسط = 255 ÷ 3 = 85",
    explanation_en: "Sum = 255, average = 255 ÷ 3 = 85",
    difficulty: "easy"
  },
  {
    question_ar: "ما وسيط الأعداد: 2، 4، 6، 8؟",
    question_en: "What is the median of: 2, 4, 6, 8?",
    type: "multiple_choice",
    options_ar: ["4", "5", "6", "7"],
    options_en: ["4", "5", "6", "7"],
    correct_answer: "1",
    explanation_ar: "متوسط العددين الأوسطين = (4+6)/2 = 5",
    explanation_en: "Average of middle two = (4+6)/2 = 5",
    difficulty: "medium"
  },
  {
    question_ar: "ما احتمال ظهور عدد أولي عند رمي حجر نرد؟",
    question_en: "What is the probability of a prime number on a die?",
    type: "multiple_choice",
    options_ar: ["1/6", "1/3", "1/2", "2/3"],
    options_en: ["1/6", "1/3", "1/2", "2/3"],
    correct_answer: "2",
    explanation_ar: "الأعداد الأولية: 2، 3، 5 (ثلاثة)، الاحتمال = 3/6 = 1/2",
    explanation_en: "Primes: 2, 3, 5 (three), probability = 3/6 = 1/2",
    difficulty: "medium"
  },
  {
    question_ar: "إذا كان مجموع 4 أعداد 80، وحذفنا عدداً قيمته 20، فما متوسط الباقي؟",
    question_en: "If 4 numbers sum to 80, and we remove 20, what is the average of the rest?",
    type: "multiple_choice",
    options_ar: ["15", "18", "20", "25"],
    options_en: ["15", "18", "20", "25"],
    correct_answer: "2",
    explanation_ar: "المتبقي = 80 - 20 = 60، المتوسط = 60 ÷ 3 = 20",
    explanation_en: "Remaining = 80 - 20 = 60, average = 60 ÷ 3 = 20",
    difficulty: "medium"
  },
  {
    question_ar: "ما احتمال ظهور رقمين متتاليين عند رمي حجرين؟ (مثل 3و4)",
    question_en: "What is the probability of two consecutive numbers on two dice? (e.g., 3 and 4)",
    type: "multiple_choice",
    options_ar: ["1/9", "1/6", "1/3", "2/9"],
    options_en: ["1/9", "1/6", "1/3", "2/9"],
    correct_answer: "3",
    explanation_ar: "8 حالات متتالية من 36، الاحتمال = 8/36 = 2/9",
    explanation_en: "8 consecutive cases of 36, probability = 8/36 = 2/9",
    difficulty: "hard"
  },
  {
    question_ar: "ما منوال الأعداد: 5، 5، 7، 8، 9، 9، 9؟",
    question_en: "What is the mode of: 5, 5, 7, 8, 9, 9, 9?",
    type: "multiple_choice",
    options_ar: ["5", "7", "8", "9"],
    options_en: ["5", "7", "8", "9"],
    correct_answer: "3",
    explanation_ar: "العدد 9 تكرر 3 مرات وهو الأكثر",
    explanation_en: "9 appears 3 times, the most frequent",
    difficulty: "easy"
  },
  {
    question_ar: "إذا رمينا قطعة نقود مرتين، فما احتمال ظهور وجهين؟",
    question_en: "If we toss a coin twice, what is the probability of two heads?",
    type: "multiple_choice",
    options_ar: ["1/8", "1/4", "1/2", "3/4"],
    options_en: ["1/8", "1/4", "1/2", "3/4"],
    correct_answer: "1",
    explanation_ar: "4 نتائج محتملة، حالة واحدة، الاحتمال = 1/4",
    explanation_en: "4 outcomes, one case, probability = 1/4",
    difficulty: "medium"
  },
  {
    question_ar: "ما متوسط الأعداد: 1، 2، 3، 4، 5، 6، 7؟",
    question_en: "What is the average of: 1, 2, 3, 4, 5, 6, 7?",
    type: "multiple_choice",
    options_ar: ["3", "4", "5", "6"],
    options_en: ["3", "4", "5", "6"],
    correct_answer: "1",
    explanation_ar: "المجموع = 28، المتوسط = 28 ÷ 7 = 4",
    explanation_en: "Sum = 28, average = 28 ÷ 7 = 4",
    difficulty: "easy"
  },
  {
    question_ar: "في صف 20 طالباً، نسبة الناجحين 85%، فكم عدد الناجحين؟",
    question_en: "In a class of 20, 85% passed; how many passed?",
    type: "multiple_choice",
    options_ar: ["15", "16", "17", "18"],
    options_en: ["15", "16", "17", "18"],
    correct_answer: "2",
    explanation_ar: "85% × 20 = 17",
    explanation_en: "85% × 20 = 17",
    difficulty: "medium"
  },
  {
    question_ar: "ما احتمال سحب بطاقة (آس) من 52 بطاقة؟",
    question_en: "What is the probability of drawing an ace from 52 cards?",
    type: "multiple_choice",
    options_ar: ["1/52", "1/26", "1/13", "1/4"],
    options_en: ["1/52", "1/26", "1/13", "1/4"],
    correct_answer: "2",
    explanation_ar: "4 آسات من 52، الاحتمال = 4/52 = 1/13",
    explanation_en: "4 aces of 52, probability = 4/52 = 1/13",
    difficulty: "medium"
  },
  {
    question_ar: "ما نطاق الأعداد: 5، 5، 5، 5؟",
    question_en: "What is the range of: 5, 5, 5, 5?",
    type: "multiple_choice",
    options_ar: ["0", "1", "5", "10"],
    options_en: ["0", "1", "5", "10"],
    correct_answer: "0",
    explanation_ar: "النطاق = الأكبر - الأصغر = 5 - 5 = 0",
    explanation_en: "Range = max - min = 5 - 5 = 0",
    difficulty: "easy"
  },
  {
    question_ar: "ما وسيط الأعداد: 1، 3، 5، 7، 9، 11؟",
    question_en: "What is the median of: 1, 3, 5, 7, 9, 11?",
    type: "multiple_choice",
    options_ar: ["5", "6", "7", "8"],
    options_en: ["5", "6", "7", "8"],
    correct_answer: "1",
    explanation_ar: "متوسط العددين الأوسطين = (5+7)/2 = 6",
    explanation_en: "Average of middle two = (5+7)/2 = 6",
    difficulty: "medium"
  },
  {
    question_ar: "ما احتمال سحب كرة حمراء من كيس فيه 4 حمراء و6 بيضاء؟",
    question_en: "What is the probability of red from a bag with 4 red and 6 white?",
    type: "multiple_choice",
    options_ar: ["2/5", "3/5", "1/2", "2/3"],
    options_en: ["2/5", "3/5", "1/2", "2/3"],
    correct_answer: "0",
    explanation_ar: "4 حمراء من 10، الاحتمال = 4/10 = 2/5",
    explanation_en: "4 red of 10, probability = 4/10 = 2/5",
    difficulty: "easy"
  },
  {
    question_ar: "إذا كانت نسبة نجاح 90% في صف 30 طالباً، فكم عدد الراسبين؟",
    question_en: "If 90% pass in a class of 30, how many failed?",
    type: "multiple_choice",
    options_ar: ["2", "3", "4", "5"],
    options_en: ["2", "3", "4", "5"],
    correct_answer: "1",
    explanation_ar: "الناجحون = 27، الراسبون = 30 - 27 = 3",
    explanation_en: "Passed = 27, failed = 30 - 27 = 3",
    difficulty: "easy"
  },
  {
    question_ar: "ما متوسط 8 أعداد مجموعها 96؟",
    question_en: "What is the average of 8 numbers summing to 96?",
    type: "multiple_choice",
    options_ar: ["10", "11", "12", "14"],
    options_en: ["10", "11", "12", "14"],
    correct_answer: "2",
    explanation_ar: "96 ÷ 8 = 12",
    explanation_en: "96 ÷ 8 = 12",
    difficulty: "easy"
  },
  {
    question_ar: "ما احتمال ظهور مجموع 7 عند رمي حجرين؟",
    question_en: "What is the probability of a sum of 7 on two dice?",
    type: "multiple_choice",
    options_ar: ["1/12", "1/9", "1/6", "5/36"],
    options_en: ["1/12", "1/9", "1/6", "5/36"],
    correct_answer: "2",
    explanation_ar: "6 حالات تعطي 7 من 36، الاحتمال = 6/36 = 1/6",
    explanation_en: "6 cases give 7 of 36, probability = 6/36 = 1/6",
    difficulty: "hard"
  },
  {
    question_ar: "إذا أضفنا العدد 10 إلى مجموعة {2، 4، 6، 8}، فكيف يتأثر المتوسط؟",
    question_en: "If we add 10 to the set {2, 4, 6, 8}, how is the average affected?",
    type: "multiple_choice",
    options_ar: ["ينقص", "لا يتغير", "يزيد", "يصبح صفراً"],
    options_en: ["Decreases", "Unchanged", "Increases", "Becomes zero"],
    correct_answer: "2",
    explanation_ar: "المتوسط القديم = 5، الجديد = 30/5 = 6، أي زاد",
    explanation_en: "Old average = 5, new = 30/5 = 6, increased",
    difficulty: "medium"
  }
];