// Verbal - Vocabulary & Meanings (30 real GAT-style questions)
export default [
  {
    question_ar: "ما معنى كلمة «السَّداد» في قولنا: «كان أبوه ذا سَدادٍ في قضاء حوائج الناس»؟",
    question_en: "What is the meaning of 'سَداد' in: 'His father was one of سَداد in meeting people's needs'?",
    type: "multiple_choice",
    options_ar: ["تأخير", "قضاء وإنجاز", "تعلل", "هروب"],
    options_en: ["Delay", "Fulfillment", "Excuse", "Escape"],
    correct_answer: "1",
    explanation_ar: "السَّداد معناه القضاء والإنجاز في قضاء الحوائج",
    explanation_en: "سَداد means fulfilling and accomplishing needs",
    difficulty: "easy"
  },
  {
    question_ar: "ما معنى «النَّجد» في الجملة: «رأينا نَجْداً واسعة بين جبال شاهقة»؟",
    question_en: "What does 'نَجْد' mean in: 'We saw a wide نَجْد between towering mountains'?",
    type: "multiple_choice",
    options_ar: ["هضبة مرتفعة", "وادٍ منخفض", "بحر عميق", "غابة كثيفة"],
    options_en: ["High plateau", "Low valley", "Deep sea", "Dense forest"],
    correct_answer: "0",
    explanation_ar: "النَّجد هو الهضبة المرتفعة عن سطح الأرض",
    explanation_en: "نَجْد is a high plateau elevated above ground",
    difficulty: "medium"
  },
  {
    question_ar: "ما معنى «الخَوْص» في الجملة: «خَاص الرجل في ماله»؟",
    question_en: "What does 'خَوْص' mean in: 'The man خَاص in his wealth'?",
    type: "multiple_choice",
    options_ar: ["بذل", "ضيّق", "أخفى", "هجر"],
    options_en: ["Spent", "Tightened", "Hid", "Abandoned"],
    correct_answer: "0",
    explanation_ar: "خَاص في المال أي بذل وأعطى بسخاء",
    explanation_en: "خَاص in wealth means giving generously",
    difficulty: "hard"
  },
  {
    question_ar: "ما معنى «الرِّفق» في الجملة: «عامل الناس بالرِّفق تألف قلوبهم»؟",
    question_en: "What does 'رِفْق' mean in: 'Treat people with رِفْق to win their hearts'?",
    type: "multiple_choice",
    options_ar: ["شدة", "لين ولطف", "قسوة", "إهمال"],
    options_en: ["Harshness", "Gentleness and kindness", "Cruelty", "Neglect"],
    correct_answer: "1",
    explanation_ar: "الرِّفق اللين واللطف في معاملة الناس",
    explanation_en: "رِفْق is gentleness and kindness in treating people",
    difficulty: "easy"
  },
  {
    question_ar: "ما معنى «الصَّدى» في الجملة: «سمع صَدى صوته في الوادي»؟",
    question_en: "What does 'صَدى' mean in: 'He heard the صَدى of his voice in the valley'?",
    type: "multiple_choice",
    options_ar: ["ردّ الصوت", "نهاية الصوت", "انقطاع الصوت", "ضعف الصوت"],
    options_en: ["Echo of sound", "End of sound", "Cutoff of sound", "Weakness of sound"],
    correct_answer: "0",
    explanation_ar: "الصَّدى رجع الصوت المردد",
    explanation_en: "صَدى is the echoing return of sound",
    difficulty: "easy"
  },
  {
    question_ar: "ما معنى «البَلاء» في الجملة: «لقد ابتلاه الله بالمال الكثير»؟",
    question_en: "What does 'بَلاء' mean in: 'God tested him with abundant wealth'?",
    type: "multiple_choice",
    options_ar: ["عقاب", "اختبار وامتحان", "هدية", "عار"],
    options_en: ["Punishment", "Test and trial", "Gift", "Disgrace"],
    correct_answer: "1",
    explanation_ar: "البَلاء يكون بالخير والشر وهو الاختبار والامتحان",
    explanation_en: "بَلاء can be good or bad; it means test and trial",
    difficulty: "medium"
  },
  {
    question_ar: "ما معنى «القَرْم» في الجملة: «كان رجلاً قَرْماً لا يُعرف له نظير»؟",
    question_en: "What does 'قَرْم' mean in: 'He was a قَرْم man with no equal'?",
    type: "multiple_choice",
    options_ar: ["ضعيف", "سيّد مطاع", "فقر", "مجهول"],
    options_en: ["Weak", "Obeyed chief", "Poor", "Unknown"],
    correct_answer: "1",
    explanation_ar: "القَرْم السيد المطاع بين قومه",
    explanation_en: "قَرْم is the obeyed chief among his people",
    difficulty: "hard"
  },
  {
    question_ar: "ما معنى «الرَّدَى» في الجملة: «إن في الرَّدَى لراحة للمؤمن»؟",
    question_en: "What does 'رَدَى' mean in: 'In رَدَى there is rest for the believer'?",
    type: "multiple_choice",
    options_ar: ["الموت", "المرض", "السفر", "النوم"],
    options_en: ["Death", "Illness", "Travel", "Sleep"],
    correct_answer: "0",
    explanation_ar: "الرَّدى هو الموت والهلاك",
    explanation_en: "رَدَى means death and perishing",
    difficulty: "medium"
  },
  {
    question_ar: "ما معنى «العُقْم» في الجملة: «أصابه عُقْم بعد أن كان مستوراً»؟",
    question_en: "What does 'عُقْم' mean in: 'He was afflicted with عُقْم after being prosperous'?",
    type: "multiple_choice",
    options_ar: ["عطاء", "خيبة وخسران", "نصر", "صحة"],
    options_en: ["Gift", "Disappointment and loss", "Victory", "Health"],
    correct_answer: "1",
    explanation_ar: "العُقْم الخيبة والخسران",
    explanation_en: "عُقْم means disappointment and loss",
    difficulty: "hard"
  },
  {
    question_ar: "ما معنى «النَّفَض» في الجملة: «نَفَض الثوب من الغبار»؟",
    question_en: "What does 'نَفَض' mean in: 'He نَفَض the garment of dust'?",
    type: "multiple_choice",
    options_ar: ["صبغ", "حرّك وأزال", "أخفى", "جمع"],
    options_en: ["Dyed", "Shook off and removed", "Hid", "Gathered"],
    correct_answer: "1",
    explanation_ar: "نَفَض الشيء أي حرّكه وأزاله",
    explanation_en: "نَفَض means shaking off and removing",
    difficulty: "easy"
  },
  {
    question_ar: "ما معنى «المُعْتَمّ» في الجملة: «يومٌ مُعْتَمّ بنوائب الدهر»؟",
    question_en: "What does 'مُعْتَمّ' mean in: 'A day مُعْتَمّ with life's calamities'?",
    type: "multiple_choice",
    options_ar: ["ساطع", "مظلم مُثقل", "مشرق", "خفيف"],
    options_en: ["Bright", "Dark and heavy", "Radiant", "Light"],
    correct_answer: "1",
    explanation_ar: "المُعْتَم المظلم المُثقل بالهموم",
    explanation_en: "مُعْتَمّ means dark and burdened with worries",
    difficulty: "medium"
  },
  {
    question_ar: "ما معنى «الزَّلَل» في الجملة: «احفظ لسانك من الزَّلَل»؟",
    question_en: "What does 'زَلَل' mean in: 'Guard your tongue from زَلَل'?",
    type: "multiple_choice",
    options_ar: ["صدق", "خطأ وسقوط", "صمت", "عزيمة"],
    options_en: ["Truth", "Slip and error", "Silence", "Resolve"],
    correct_answer: "1",
    explanation_ar: "الزَّلل الخطأ والسقوط في القول",
    explanation_en: "زَلَل means slipping and error in speech",
    difficulty: "easy"
  },
  {
    question_ar: "ما معنى «الغَضَن» في الجملة: «التفت حولها الغَضَن من الأشجار»؟",
    question_en: "What does 'غَضَن' mean in: 'The غَضَن of trees wrapped around it'?",
    type: "multiple_choice",
    options_ar: ["جذع", "غصن ملتوٍ", "ورقة", "زهرة"],
    options_en: ["Trunk", "Twisted branch", "Leaf", "Flower"],
    correct_answer: "1",
    explanation_ar: "الغَضَن الغصن الملتوي من الشجر",
    explanation_en: "غَضَن is a twisted tree branch",
    difficulty: "hard"
  },
  {
    question_ar: "ما معنى «الصَّدَأ» في الجملة: «أكل الصَّدَأ جسم الحديد»؟",
    question_en: "What does 'صَدَأ' mean in: 'Rust ate the iron body'?",
    type: "multiple_choice",
    options_ar: ["اللون", "البريق", "الصدأ الذي يصيب الحديد", "القوة"],
    options_en: ["Color", "Shine", "Rust on iron", "Strength"],
    correct_answer: "2",
    explanation_ar: "الصَّدأ ما يعلو الحديد من فساد",
    explanation_en: "صَدَأ is what corrupts iron's surface",
    difficulty: "easy"
  },
  {
    question_ar: "ما معنى «النَّدّ» في الجملة: «هو ندّي في النَّدّ»؟",
    question_en: "What does 'نَدّ' mean in: 'He is my نَدّ in the نَدّ'?",
    type: "multiple_choice",
    options_ar: ["عدو", "مساوٍ ونظير", "تابع", "غريب"],
    options_en: ["Enemy", "Equal and peer", "Follower", "Stranger"],
    correct_answer: "1",
    explanation_ar: "النَّدّ المساوي والنظير، والمجلس الذي فيه أنداء",
    explanation_en: "نَدّ means equal/peer, and the council of peers",
    difficulty: "hard"
  },
  {
    question_ar: "ما معنى «الحَصْحَص» في الجملة: «حَصْحَص الحق»؟",
    question_en: "What does 'حَصْحَص' mean in: 'The truth حَصْحَص'?",
    type: "multiple_choice",
    options_ar: ["اختفى", "ظهر وبيّن", "ضعف", "هلك"],
    options_en: ["Disappeared", "Appeared and became clear", "Weakened", "Perished"],
    correct_answer: "1",
    explanation_ar: "حَصْحَص الحق أي ظهر وبيّن",
    explanation_en: "حَصْحَص means it appeared and became clear",
    difficulty: "medium"
  },
  {
    question_ar: "ما معنى «الرَّسّ» في الجملة: «نزل الماء على الرَّسّ»؟",
    question_en: "What does 'رَسّ' mean in: 'Water fell on the رَسّ'?",
    type: "multiple_choice",
    options_ar: ["جبل", "بئر قليلة الماء", "بحر", "سماء"],
    options_en: ["Mountain", "Well with little water", "Sea", "Sky"],
    correct_answer: "1",
    explanation_ar: "الرَّسّ البئر القليلة الماء أو الأرض المنخفضة",
    explanation_en: "رَسّ is a well with little water or low ground",
    difficulty: "hard"
  },
  {
    question_ar: "ما معنى «القَسْوَة» في الجملة: «قسا قلبه فلم يرق لمن حوله»؟",
    question_en: "What does 'قَسْوَة' mean in: 'His heart hardened and didn't soften for those around him'?",
    type: "multiple_choice",
    options_ar: ["رقة", "صلابة وغلظة", "حزن", "فرح"],
    options_en: ["Softness", "Hardness and harshness", "Sadness", "Joy"],
    correct_answer: "1",
    explanation_ar: "القَسوة صلابة القلب وغلظته",
    explanation_en: "قَسْوَة is hardness and harshness of heart",
    difficulty: "easy"
  },
  {
    question_ar: "ما معنى «النَّجْم» في الجملة: «ظهر النَّجْم في السماء»؟",
    question_en: "What does 'نَجْم' mean in: 'The نَجْم appeared in the sky'?",
    type: "multiple_choice",
    options_ar: ["قمر", "كوكب مضيء", "طائر", "سحاب"],
    options_en: ["Moon", "Luminous star", "Bird", "Cloud"],
    correct_answer: "1",
    explanation_ar: "النَّجم الكوكب المضيء في السماء",
    explanation_en: "نَجْم is a luminous star in the sky",
    difficulty: "easy"
  },
  {
    question_ar: "ما معنى «الحَنَق» في الجملة: «امتلىء قلبه حَنَقاً»؟",
    question_en: "What does 'حَنَق' mean in: 'His heart filled with حَنَق'?",
    type: "multiple_choice",
    options_ar: ["غضب شديد", "رضا", "حزن", "طمأنينة"],
    options_en: ["Intense anger", "Satisfaction", "Sadness", "Peace"],
    correct_answer: "0",
    explanation_ar: "الحَنَق الغضب الشديد المكظوم",
    explanation_en: "حَنَق is intense suppressed anger",
    difficulty: "medium"
  },
  {
    question_ar: "ما معنى «الوَهْم» في الجملة: «طار الوَهْمُ في رأسه»؟",
    question_en: "What does 'وَهْم' mean in: 'A وَهْم flew in his head'?",
    type: "multiple_choice",
    options_ar: ["خيال وظنّ", "حقيقة", "شهادة", "حلم"],
    options_en: ["Illusion and assumption", "Truth", "Testimony", "Dream"],
    correct_answer: "0",
    explanation_ar: "الوَهْم الخيال والظنّ الباطل",
    explanation_en: "وَهْم is illusion and false assumption",
    difficulty: "easy"
  },
  {
    question_ar: "ما معنى «الجَلَد» في الجملة: «صبر صبر الجَلَد»؟",
    question_en: "What does 'جَلَد' mean in: 'He had the patience of جَلَد'?",
    type: "multiple_choice",
    options_ar: ["ضعف", "قوة وصبر", "عجلة", "جبن"],
    options_en: ["Weakness", "Strength and patience", "Haste", "Cowardice"],
    correct_answer: "1",
    explanation_ar: "الجَلَد القوة والصبر على الشدائد",
    explanation_en: "جَلَد is strength and patience in hardship",
    difficulty: "medium"
  },
  {
    question_ar: "ما معنى «الخَوْل» في الجملة: «أطال الله خَوْله»؟",
    question_en: "What does 'خَوْل' mean in: 'God lengthened his خَوْل'?",
    type: "multiple_choice",
    options_ar: ["عمر وملك", "دين", "مرض", "سفر"],
    options_en: ["Life and dominion", "Debt", "Illness", "Travel"],
    correct_answer: "0",
    explanation_ar: "الخَوْل العمر والملك والنّعمة",
    explanation_en: "خَوْل means life, dominion, and blessing",
    difficulty: "hard"
  },
  {
    question_ar: "ما معنى «الرَّوْع» في الجملة: «طار رَوْعُه من الفزع»؟",
    question_en: "What does 'رَوْع' mean in: 'His رَوْع flew from fright'?",
    type: "multiple_choice",
    options_ar: ["عقل", "قلب وفزع", "سمع", "بصر"],
    options_en: ["Mind", "Heart and fright", "Hearing", "Sight"],
    correct_answer: "1",
    explanation_ar: "الرَّوْع القلب والفزع يأخذ القلب",
    explanation_en: "رَوْع is the heart and the fright that takes it",
    difficulty: "medium"
  },
  {
    question_ar: "ما معنى «السِّدْر» في الجملة: «جلسنا تحت سِدْرَة في الفلاة»؟",
    question_en: "What does 'سِدْر' mean in: 'We sat under a سِدْرَة in the desert'?",
    type: "multiple_choice",
    options_ar: ["نخلة", "شجرة نبق", "صخرة", "خيمة"],
    options_en: ["Palm tree", "Lote tree", "Rock", "Tent"],
    correct_answer: "1",
    explanation_ar: "السِّدْر شجر النبق المعروف في الجزيرة",
    explanation_en: "سِدْر is the lote tree known in the peninsula",
    difficulty: "medium"
  },
  {
    question_ar: "ما معنى «النَّكَد» في الجملة: «عاش عيشاً نَكِداً»؟",
    question_en: "What does 'نَكَد' mean in: 'He lived a نَكِد life'?",
    type: "multiple_choice",
    options_ar: ["رخيّ", "شديد ضنك", "قصير", "هادئ"],
    options_en: ["Prosperous", "Harsh and miserable", "Short", "Calm"],
    correct_answer: "1",
    explanation_ar: "النَّكَد العيش الشديد الضنك قليل الخير",
    explanation_en: "نَكَد is a harsh, miserable life with little good",
    difficulty: "medium"
  },
  {
    question_ar: "ما معنى «القَيْء» في الجملة: «أصابه قَيْءٌ بعد الطعام»؟",
    question_en: "What does 'قَيْء' mean in: 'He had قَيْء after eating'?",
    type: "multiple_choice",
    options_ar: ["جوع", "تقيّؤ ما في المعدة", "نعاس", "دوخة"],
    options_en: ["Hunger", "Vomiting stomach contents", "Sleepiness", "Dizziness"],
    correct_answer: "1",
    explanation_ar: "القَيْء ما يخرج من المعدة عن طريق الفم",
    explanation_en: "قَيْء is what exits the stomach through the mouth",
    difficulty: "easy"
  },
  {
    question_ar: "ما معنى «النُّصْح» في الجملة: «قدّم له نُصْحاً خالصاً»؟",
    question_en: "What does 'نُصْح' mean in: 'He offered him sincere نُصْح'?",
    type: "multiple_choice",
    options_ar: ["غش", "نصيحة صادقة", "مال", "هداية"],
    options_en: ["Deceit", "Sincere advice", "Money", "Gift"],
    correct_answer: "1",
    explanation_ar: "النُّصْح النصيحة الصادقة الخالصة",
    explanation_en: "نُصْح is sincere, pure advice",
    difficulty: "easy"
  }
];