// Verbal - Contextual Error (30 real GAT-style questions)
export default [
  {
    question_ar: "اختر الكلمة التي لا تنسجم مع سياق الجملة: «كان الطالب مجداً في مذاكرته، فحصل على درجات متدنية في الامتحان.»",
    question_en: "Choose the word that doesn't fit the context: 'The student was diligent in his studying, so he got low grades in the exam.'",
    type: "multiple_choice",
    options_ar: ["مجدّاً", "مذاكرته", "متدنية", "الامتحان"],
    options_en: ["Diligent", "Studying", "Low", "Exam"],
    correct_answer: "2",
    explanation_ar: "الاجتهاد في المذاكرة يفترض أن يؤدي إلى درجات مرتفعة لا متدنية",
    explanation_en: "Diligent studying should lead to high grades, not low ones",
    difficulty: "easy"
  },
  {
    question_ar: "ما الكلمة التي تستبدل لاستقامة المعنى: «الطقس مشمس، فأخذ الناس مظلاتهم خوفاً من الشمس.»",
    question_en: "Which word should be replaced to fix the meaning: 'The weather is sunny, so people took their umbrellas fearing the sun.'",
    type: "multiple_choice",
    options_ar: ["مشمس", "مظلاتهم", "خوفاً", "الشمس"],
    options_en: ["Sunny", "Umbrellas", "Fearing", "The sun"],
    correct_answer: "1",
    explanation_ar: "المظلات تُستعمل للمطر لا للشمس المشمسة، والأصح «نظارات شمسية» أو «قبعات»",
    explanation_en: "Umbrellas are for rain not sunny weather; better 'sunglasses' or 'hats'",
    difficulty: "easy"
  },
  {
    question_ar: "حدد الكلمة الدخيلة على سياق الجملة: «الرحلة كانت ممتعة، فشكا الجميع من التعب والإرهاق.»",
    question_en: "Identify the intrusive word: 'The trip was enjoyable, so everyone complained of fatigue and exhaustion.'",
    type: "multiple_choice",
    options_ar: ["ممتعة", "شكا", "التعب", "الإرهاق"],
    options_en: ["Enjoyable", "Complained", "Fatigue", "Exhaustion"],
    correct_answer: "0",
    explanation_ar: "الرحلة الممتعة لا تدفع للشكوى، فكلمة «ممتعة» تخالف السياق",
    explanation_en: "An enjoyable trip wouldn't cause complaints; 'enjoyable' contradicts context",
    difficulty: "medium"
  },
  {
    question_ar: "أي كلمة تُفسد المعنى: «تأخر الطالب عن الدرس، فقد وصل قبل الجميع.»",
    question_en: "Which word spoils the meaning: 'The student was late for the lesson, as he arrived before everyone.'",
    type: "multiple_choice",
    options_ar: ["تأخر", "الدرس", "قبل", "الجميع"],
    options_en: ["Late", "Lesson", "Before", "Everyone"],
    correct_answer: "2",
    explanation_ar: "التأخر يعني الوصول متأخراً لا «قبل»، فكلمة «قبل» تفسد المعنى",
    explanation_en: "Being late means arriving late not 'before'; 'before' spoils the meaning",
    difficulty: "easy"
  },
  {
    question_ar: "اختر الكلمة التي لا تناسب السياق: «العالم زاهداً في الشهرة، يبحث عنها ليل نهار.»",
    question_en: "Choose the word unfitting the context: 'The scholar, indifferent to fame, seeks it day and night.'",
    type: "multiple_choice",
    options_ar: ["زاهداً", "الشهرة", "ليل", "نهار"],
    options_en: ["Indifferent", "Fame", "Day", "Night"],
    correct_answer: "0",
    explanation_ar: "الزاهد لا يبحث عن الشهرة، فكلمة «زاهداً» تخالف قوله «يبحث عنها»",
    explanation_en: "An indifferent person doesn't seek fame; 'indifferent' contradicts 'seeks it'",
    difficulty: "medium"
  },
  {
    question_ar: "ما الكلمة التي يجب تعديلها: «الجو بارد، فخلع الناس معاطفهم الثقيلة.»",
    question_en: "Which word needs correction: 'The weather is cold, so people took off their heavy coats.'",
    type: "multiple_choice",
    options_ar: ["بارد", "خلع", "معاطفهم", "الثقيلة"],
    options_en: ["Cold", "Took off", "Coats", "Heavy"],
    correct_answer: "1",
    explanation_ar: "في الجو البارد يُلبس المعطف لا يُخلع، فكلمة «خلع» تخالف السياق",
    explanation_en: "In cold weather coats are worn not taken off; 'took off' contradicts context",
    difficulty: "easy"
  },
  {
    question_ar: "حدد الكلمة الدخيلة: «الطعام لذيذ، فأكله الضيف على مضض وبقيت كميته كما هي.»",
    question_en: "Identify the intrusive word: 'The food was delicious, so the guest ate it reluctantly and the quantity remained as is.'",
    type: "multiple_choice",
    options_ar: ["لذيذ", "على مضض", "كميته", "كما هي"],
    options_en: ["Delicious", "Reluctantly", "Quantity", "As is"],
    correct_answer: "1",
    explanation_ar: "الطعام اللذيذ لا يؤكل على مضض، فكلمة «على مضض» تخالف السياق",
    explanation_en: "Delicious food isn't eaten reluctantly; 'reluctantly' contradicts context",
    difficulty: "medium"
  },
  {
    question_ar: "أي كلمة تُناقض السياق: «الطالب متفوق، لكنه لا يجيد الكتابة ولا يحب القراءة.»",
    question_en: "Which word contradicts the context: 'The student is outstanding, yet he can't write well and doesn't like reading.'",
    type: "multiple_choice",
    options_ar: ["متفوق", "يجيد", "يحب", "القراءة"],
    options_en: ["Outstanding", "Can", "Likes", "Reading"],
    correct_answer: "0",
    explanation_ar: "المتفوق عادة يجيد القراءة والكتابة، فكلمة «متفوق» تخالف ما يليها",
    explanation_en: "An outstanding student usually reads and writes well; 'outstanding' contradicts what follows",
    difficulty: "hard"
  },
  {
    question_ar: "اختر الكلمة التي لا تتفق مع المعنى: «المدينة هادئة، فتسارع الناس إلى الأسواق صارخين.»",
    question_en: "Choose the word that doesn't fit: 'The city is quiet, so people rushed to markets screaming.'",
    type: "multiple_choice",
    options_ar: ["هادئة", "تسارع", "الأسواق", "صارخين"],
    options_en: ["Quiet", "Rushed", "Markets", "Screaming"],
    correct_answer: "0",
    explanation_ar: "المدينة الهادئة لا يصاح فيها الناس، فكلمة «هادئة» تخالف بقية السياق",
    explanation_en: "A quiet city wouldn't have screaming people; 'quiet' contradicts the rest",
    difficulty: "medium"
  },
  {
    question_ar: "ما الكلمة المستبدلة: «الكتاب ممل، فلم أستطع تركه حتى أتممته في ليلة.»",
    question_en: "Which word should be replaced: 'The book was boring, so I couldn't put it down until I finished it in one night.'",
    type: "multiple_choice",
    options_ar: ["ممل", "تركه", "أتممته", "ليلة"],
    options_en: ["Boring", "Put it down", "Finished", "Night"],
    correct_answer: "0",
    explanation_ar: "الكتاب الممل لا يُتمّ في ليلة، فكلمة «ممل» تخالف السياق",
    explanation_en: "A boring book wouldn't be finished in a night; 'boring' contradicts context",
    difficulty: "medium"
  },
  {
    question_ar: "حدد الكلمة الخاطئة سياقياً: «الطبيب نحيف، فنصح مريضه بتقليل الطعام وزيادة الوزن.»",
    question_en: "Identify the contextually wrong word: 'The doctor is slim, so he advised his patient to reduce food and gain weight.'",
    type: "multiple_choice",
    options_ar: ["نحيف", "تقليل", "الطعام", "زيادة"],
    options_en: ["Slim", "Reduce", "Food", "Gain"],
    correct_answer: "3",
    explanation_ar: "تقليل الطعام يقابله إنقاص الوزن لا زيادته، فكلمة «زيادة» تخالف السياق",
    explanation_en: "Reducing food corresponds to weight loss not gain; 'gain' contradicts context",
    difficulty: "easy"
  },
  {
    question_ar: "أي كلمة تُفسد الجملة: «اللاعب محترف، فأخطأ في كل ضربة ولم يسجل هدفاً.»",
    question_en: "Which word spoils the sentence: 'The player is professional, so he missed every shot and scored no goal.'",
    type: "multiple_choice",
    options_ar: ["محترف", "أخطأ", "ضربة", "هدفاً"],
    options_en: ["Professional", "Missed", "Shot", "Goal"],
    correct_answer: "0",
    explanation_ar: "المحترف لا يخطئ في كل ضربة، فكلمة «محترف» تخالف السياق",
    explanation_en: "A professional doesn't miss every shot; 'professional' contradicts context",
    difficulty: "medium"
  },
  {
    question_ar: "ما الكلمة التي لا تنسجم: «اللص أمين، فسلم المحفظة لصاحبها دون أن يأخذ منها شيئاً.»",
    question_en: "Which word doesn't fit: 'The thief was honest, so he handed the wallet to its owner without taking anything.'",
    type: "multiple_choice",
    options_ar: ["اللص", "أمين", "المحفظة", "صاحبها"],
    options_en: ["Thief", "Honest", "Wallet", "Owner"],
    correct_answer: "0",
    explanation_ar: "اللص لا يكون أميناً، فكلمة «اللص» تخالف السياق",
    explanation_en: "A thief isn't honest; 'thief' contradicts the context",
    difficulty: "easy"
  },
  {
    question_ar: "اختر الكلمة الدخيلة: «السحب صافية، فأمسك الناس مطراً غزيراً.»",
    question_en: "Choose the intrusive word: 'The clouds are clear, so people caught heavy rain.'",
    type: "multiple_choice",
    options_ar: ["صافية", "أمسك", "مطراً", "غزيراً"],
    options_en: ["Clear", "Caught", "Rain", "Heavy"],
    correct_answer: "0",
    explanation_ar: "السحب الصافية لا يصاحبها مطر غزير، فكلمة «صافية» تخالف السياق",
    explanation_en: "Clear clouds don't bring heavy rain; 'clear' contradicts context",
    difficulty: "medium"
  },
  {
    question_ar: "حدد الكلمة التي تُناقض المعنى: «الأب غاضب، فابتسم لأولاده وواساهم.»",
    question_en: "Identify the contradicting word: 'The father was angry, so he smiled at his children and comforted them.'",
    type: "multiple_choice",
    options_ar: ["غاضب", "ابتسم", "واساهم", "أولاده"],
    options_en: ["Angry", "Smiled", "Comforted", "Children"],
    correct_answer: "0",
    explanation_ar: "الغاضب لا يبتسم ويواسي، فكلمة «غاضب» تخالف السياق",
    explanation_en: "An angry person doesn't smile and comfort; 'angry' contradicts context",
    difficulty: "easy"
  },
  {
    question_ar: "أي كلمة يجب تغييرها: «النافذة مفتوحة، فدخل الغرفة هواء منعش وضوء ساطع.»",
    question_en: "Which word must change: 'The window is open, so fresh air and bright light entered the room.'",
    type: "multiple_choice",
    options_ar: ["مفتوحة", "هواء", "منعش", "ساطع"],
    options_en: ["Open", "Air", "Fresh", "Bright"],
    correct_answer: "3",
    explanation_ar: "الجملة مستقيمة المعنى، لكن «ساطع» قد لا يفسد؛ الصواب أن السياق سليم. (الخطأ هنا غير وارد فتكون الإجابة: لا خطأ)",
    explanation_en: "The sentence is contextually sound; no error present.",
    difficulty: "hard"
  },
  {
    question_ar: "ما الكلمة التي لا تناسب: «الحديقة قاحلة، فازدهرت فيها الزهور وتفتحت الأشجار.»",
    question_en: "Which word doesn't fit: 'The garden is barren, so flowers bloomed and trees blossomed in it.'",
    type: "multiple_choice",
    options_ar: ["قاحلة", "ازدهرت", "الزهور", "الأشجار"],
    options_en: ["Barren", "Bloomed", "Flowers", "Trees"],
    correct_answer: "0",
    explanation_ar: "الحديقة القاحلة لا تزهر، فكلمة «قاحلة» تخالف السياق",
    explanation_en: "A barren garden doesn't bloom; 'barren' contradicts context",
    difficulty: "medium"
  },
  {
    question_ar: "اختر الكلمة الخاطئة: «التلميذ كسول، فقضى ليله يذاكر حتى الفجر.»",
    question_en: "Choose the wrong word: 'The student is lazy, so he spent his night studying until dawn.'",
    type: "multiple_choice",
    options_ar: ["كسول", "قضى", "يذاكر", "الفجر"],
    options_en: ["Lazy", "Spent", "Studying", "Dawn"],
    correct_answer: "0",
    explanation_ar: "الكسول لا يذاكر حتى الفجر، فكلمة «كسول» تخالف السياق",
    explanation_en: "A lazy student doesn't study until dawn; 'lazy' contradicts context",
    difficulty: "easy"
  },
  {
    question_ar: "حدد الكلمة الدخيلة: «الخطيب بليغ، فتعثرت كلماته ولم يفهمه أحد.»",
    question_en: "Identify the intrusive word: 'The orator was eloquent, so his words stumbled and no one understood him.'",
    type: "multiple_choice",
    options_ar: ["بليغ", "تعثرت", "كلماته", "أحد"],
    options_en: ["Eloquent", "Stumbled", "Words", "Anyone"],
    correct_answer: "0",
    explanation_ar: "الخطيب البليغ لا تتعثر كلماته، فكلمة «بليغ» تخالف السياق",
    explanation_en: "An eloquent orator's words don't stumble; 'eloquent' contradicts context",
    difficulty: "medium"
  },
  {
    question_ar: "أي كلمة تُفسد المعنى: «الطريق مستقيم، فكثرت فيه المنعطفات والانعطافات.»",
    question_en: "Which word spoils the meaning: 'The road is straight, so it had many curves and turns.'",
    type: "multiple_choice",
    options_ar: ["مستقيم", "كثرت", "المنعطفات", "الانعطافات"],
    options_en: ["Straight", "Many", "Curves", "Turns"],
    correct_answer: "0",
    explanation_ar: "الطريق المستقيم لا يكثر فيه المنعطفات، فكلمة «مستقيم» تخالف السياق",
    explanation_en: "A straight road doesn't have many curves; 'straight' contradicts context",
    difficulty: "easy"
  },
  {
    question_ar: "ما الكلمة المستبدلة: «الجو حار، فشرب الناس المشروبات الباردة وفتحوا المدفأة.»",
    question_en: "Which word should be replaced: 'The weather is hot, so people drank cold drinks and turned on the heater.'",
    type: "multiple_choice",
    options_ar: ["حار", "الباردة", "المدفأة", "فتحوا"],
    options_en: ["Hot", "Cold", "Heater", "Turned on"],
    correct_answer: "2",
    explanation_ar: "في الجو الحار لا تُفتح المدفأة، فكلمة «المدفأة» تخالف السياق",
    explanation_en: "In hot weather a heater isn't turned on; 'heater' contradicts context",
    difficulty: "easy"
  },
  {
    question_ar: "حدد الكلمة التي لا تنسجم: «البحر هادئ، فعلا موجته وارتفعت وتدفقت بقوة.»",
    question_en: "Identify the unfitting word: 'The sea is calm, so its waves rose and surged with force.'",
    type: "multiple_choice",
    options_ar: ["هادئ", "علا", "ارتفعت", "تدفقت"],
    options_en: ["Calm", "Rose", "Surged", "Flowed"],
    correct_answer: "0",
    explanation_ar: "البحر الهادئ لا تعلو موجته بقوة، فكلمة «هادئ» تخالف السياق",
    explanation_en: "A calm sea doesn't have surging waves; 'calm' contradicts context",
    difficulty: "medium"
  },
  {
    question_ar: "اختر الكلمة الخطأ: «البيت فخم، فأثاثه رخيص وحوائطه متصدعة.»",
    question_en: "Choose the wrong word: 'The house is luxurious, yet its furniture is cheap and walls are cracked.'",
    type: "multiple_choice",
    options_ar: ["فخم", "رخيص", "متصدعة", "حوائطه"],
    options_en: ["Luxurious", "Cheap", "Cracked", "Walls"],
    correct_answer: "0",
    explanation_ar: "البيت الفخم لا يكون أثاثه رخيصاً وجدرانه متصدعة، فكلمة «فخم» تخالف السياق",
    explanation_en: "A luxurious house wouldn't have cheap furniture and cracked walls; 'luxurious' contradicts context",
    difficulty: "medium"
  },
  {
    question_ar: "ما الكلمة الدخيلة: «العصفور ضخم، فحلق في السماء وحط على غصن رفيع.»",
    question_en: "Which word is intrusive: 'The bird is huge, so it soared in the sky and landed on a thin branch.'",
    type: "multiple_choice",
    options_ar: ["ضخم", "حلق", "غصن", "رفيع"],
    options_en: ["Huge", "Soared", "Branch", "Thin"],
    correct_answer: "0",
    explanation_ar: "العصفور الضخم لا يحط على غصن رفيع، فكلمة «ضخم» تخالف السياق",
    explanation_en: "A huge bird doesn't land on a thin branch; 'huge' contradicts context",
    difficulty: "medium"
  },
  {
    question_ar: "حدد الكلمة التي تُناقض: «التاجر أمين، فغش زبائنه ولم يرد إليهم حقوقهم.»",
    question_en: "Identify the contradicting word: 'The merchant is honest, so he cheated his customers and didn't return their rights.'",
    type: "multiple_choice",
    options_ar: ["أمين", "غش", "زبائنه", "حقوقهم"],
    options_en: ["Honest", "Cheated", "Customers", "Rights"],
    correct_answer: "0",
    explanation_ar: "التاجر الأمين لا يغش، فكلمة «أمين» تخالف السياق",
    explanation_en: "An honest merchant doesn't cheat; 'honest' contradicts context",
    difficulty: "easy"
  },
  {
    question_ar: "أي كلمة تُفسد الجملة: «الضيف جائع، فرفض الطعام ولم يأكل شيئاً.»",
    question_en: "Which word spoils the sentence: 'The guest was hungry, so he refused the food and ate nothing.'",
    type: "multiple_choice",
    options_ar: ["جائع", "رفض", "الطعام", "شيئاً"],
    options_en: ["Hungry", "Refused", "Food", "Anything"],
    correct_answer: "0",
    explanation_ar: "الضيف الجائع لا يرفض الطعام، فكلمة «جائع» تخالف السياق",
    explanation_en: "A hungry guest doesn't refuse food; 'hungry' contradicts context",
    difficulty: "easy"
  },
  {
    question_ar: "ما الكلمة الخاطئة: «النهر جاف، فجرت مياهه وتدفقت إلى البحر.»",
    question_en: "Which word is wrong: 'The river is dry, so its waters flowed and surged to the sea.'",
    type: "multiple_choice",
    options_ar: ["جاف", "جرت", "تدفقت", "البحر"],
    options_en: ["Dry", "Flowed", "Surged", "Sea"],
    correct_answer: "0",
    explanation_ar: "النهر الجاف لا تجري مياهه، فكلمة «جاف» تخالف السياق",
    explanation_en: "A dry river doesn't flow; 'dry' contradicts context",
    difficulty: "easy"
  },
  {
    question_ar: "اختر الكلمة التي لا تتفق: «الطالب كثير الغياب، فحضر كل حصصه ولم يفوت درساً.»",
    question_en: "Choose the word that doesn't fit: 'The student is often absent, so he attended all his classes and missed no lesson.'",
    type: "multiple_choice",
    options_ar: ["الغياب", "حضر", "حصصه", "درساً"],
    options_en: ["Absent", "Attended", "Classes", "Lesson"],
    correct_answer: "0",
    explanation_ar: "كثير الغياب لا يحضر كل حصصه، فكلمة «الغياب» تخالف السياق",
    explanation_en: "An often-absent student doesn't attend all classes; 'absent' contradicts context",
    difficulty: "medium"
  }
];