// Verbal - Sentence Completion (30 real GAT-style questions)
export default [
  {
    question_ar: "الكتاب الذي قرأته أمس كان غاية في .........، فقد شرح أصعب المسائل بأسلوب بسيط.",
    question_en: "The book I read yesterday was extremely ........., explaining the most difficult issues in a simple style.",
    type: "multiple_choice",
    options_ar: ["التعقيد", "الوضوح", "الغموض", "الإطالة"],
    options_en: ["Complexity", "Clarity", "Ambiguity", "Lengthiness"],
    correct_answer: "1",
    explanation_ar: "السياق يدل على سهولة الشرح، فالكلمة المناسبة «الوضوح»",
    explanation_en: "Context indicates easy explanation, so the fitting word is 'Clarity'",
    difficulty: "easy"
  },
  {
    question_ar: "على الرغم من صعوبة الموقف، حافظ الطالب على ......... ولم يفقد أعصابه.",
    question_en: "Despite the difficult situation, the student maintained ......... and didn't lose his nerves.",
    type: "multiple_choice",
    options_ar: ["الهدوء", "الغضب", "الفوضى", "الجزع"],
    options_en: ["Calmness", "Anger", "Chaos", "Panic"],
    correct_answer: "0",
    explanation_ar: "عبارة «لم يفقد أعصابه» تدل على أنه حافظ على الهدوء",
    explanation_en: "The phrase 'didn't lose his nerves' indicates he maintained calmness",
    difficulty: "easy"
  },
  {
    question_ar: "كانت سيرته ......... بين الناس، إذ يحبه القريب والبعيد لكرمه وأخلاقه.",
    question_en: "His reputation was ......... among people, as he was loved by near and far for his generosity and morals.",
    type: "multiple_choice",
    options_ar: ["سيئة", "مجهولة", "طيبة", "مشكوك فيها"],
    options_en: ["Bad", "Unknown", "Good", "Doubtful"],
    correct_answer: "2",
    explanation_ar: "محبة الناس لكرمه تدل على سيرة طيبة",
    explanation_en: "People's love for his generosity indicates a good reputation",
    difficulty: "easy"
  },
  {
    question_ar: "نجح المتحدث في ......... انتباه الجمهور من اللحظة الأولى بكلماته المؤثرة.",
    question_en: "The speaker succeeded in ......... the audience's attention from the first moment with his impactful words.",
    type: "multiple_choice",
    options_ar: ["إهمال", "تفقد", "جذب", "صرف"],
    options_en: ["Neglecting", "Losing", "Attracting", "Diverting"],
    correct_answer: "2",
    explanation_ar: "الكلمات المؤثرة تجذب الانتباه",
    explanation_en: "Impactful words attract attention",
    difficulty: "easy"
  },
  {
    question_ar: "المعلم الذي ......... على طلابه لا ينسونه أبداً، ويذكرونه بخير طوال حياتهم.",
    question_en: "The teacher who ......... on his students is never forgotten; they remember him fondly throughout their lives.",
    type: "multiple_choice",
    options_ar: ["قسا", "أثر", "تجاهل", "أهمل"],
    options_en: ["Was harsh", "Influenced", "Ignored", "Neglected"],
    correct_answer: "1",
    explanation_ar: "ذكر الطالب له بخير يدل على أنه أثر فيه إيجابياً",
    explanation_en: "Remembering the teacher fondly indicates he positively influenced them",
    difficulty: "medium"
  },
  {
    question_ar: "لا تنجح الأمة إلا بسواعد أبنائها، فلا ......... للكسالى في بناء المجد.",
    question_en: "A nation only succeeds through its people's efforts; there is no ......... for the lazy in building glory.",
    type: "multiple_choice",
    options_ar: ["مكان", "مكافأة", "عقاب", "شكوى"],
    options_en: ["Place", "Reward", "Punishment", "Complaint"],
    correct_answer: "0",
    explanation_ar: "السياق ينفي مكان الكسالى في بناء المجد",
    explanation_en: "The context negates a place for the lazy in building glory",
    difficulty: "medium"
  },
  {
    question_ar: "التلميذ ......... يصل إلى هدفه قبل المجدّد وإن تأخر، لأن الثبات مفتاح النجاح.",
    question_en: "The ......... student reaches his goal before the diligent one even if late, because perseverance is the key to success.",
    type: "multiple_choice",
    options_ar: ["المثابر", "الكسول", "الواهن", "المتردد"],
    options_en: ["Persevering", "Lazy", "Weak", "Hesitant"],
    correct_answer: "0",
    explanation_ar: "الثبات مفتاح النجاح يدل على أن المثابر يصل لهدفه",
    explanation_en: "Perseverance being the key indicates the persevering student reaches his goal",
    difficulty: "easy"
  },
  {
    question_ar: "تتميز المدينة الساحلية بأن هوائها .........، فيستنشقه الزائر فيشعر بالانتعاش.",
    question_en: "The coastal city is characterized by its ......... air; visitors breathe it and feel refreshed.",
    type: "multiple_choice",
    options_ar: ["محرّم", "عليل", "نقي", "ملوث"],
    options_en: ["Forbidden", "Fresh", "Pure", "Polluted"],
    correct_answer: "2",
    explanation_ar: "الانتعاش يدل على أن الهواء نقي",
    explanation_en: "Feeling refreshed indicates the air is pure",
    difficulty: "easy"
  },
  {
    question_ar: "العالم الذي يبحث عن الحقيقة ............. يبالغ في النتائج، بل يعرضها كما هي.",
    question_en: "The scholar who seeks truth ......... exaggerates the results, but presents them as they are.",
    type: "multiple_choice",
    options_ar: ["كثيراً", "لا", "قد", "يحب"],
    options_en: ["Often", "Does not", "May", "Loves"],
    correct_answer: "1",
    explanation_ar: "عرض النتائج كما هي يدل على أنه لا يبالغ",
    explanation_en: "Presenting results as they are indicates he does not exaggerate",
    difficulty: "medium"
  },
  {
    question_ar: "الأب الكريم يُربّي أبناءه على الاعتماد على أنفسهم، فلا ......... لهم على أحد بعد الله.",
    question_en: "A generous father raises his children to rely on themselves, so they ......... on no one after God.",
    type: "multiple_choice",
    options_ar: ["يتوكلون", "يحسنون", "يستندون", "يفرضون"],
    options_en: ["Rely", "Do well", "Lean", "Impose"],
    correct_answer: "2",
    explanation_ar: "الاعتماد على النفس يقابله عدم الاستناد على أحد",
    explanation_en: "Self-reliance is opposed to leaning on anyone",
    difficulty: "medium"
  },
  {
    question_ar: "بعد سنوات من الكدّ، ......... الجاهد ثمار سعيه نجاحاً باهراً.",
    question_en: "After years of hard work, the striving person ......... the fruits of his effort as dazzling success.",
    type: "multiple_choice",
    options_ar: ["فقد", "حصد", "أضاع", "تجاهل"],
    options_en: ["Lost", "Reaped", "Wasted", "Ignored"],
    correct_answer: "1",
    explanation_ar: "ثمار السعي تُحصد بعد الجدّ",
    explanation_en: "The fruits of effort are reaped after hard work",
    difficulty: "easy"
  },
  {
    question_ar: "من سار على درب الحق ......... من المخاوف، لأن الضمير الحي يمنحه الطمأنينة.",
    question_en: "Whoever walks the path of truth ......... of fears, because a living conscience gives him peace of mind.",
    type: "multiple_choice",
    options_ar: ["كثر", "قلّ", "امتلأ", "زاد"],
    options_en: ["Increased", "Decreased", "Filled", "Grew"],
    correct_answer: "1",
    explanation_ar: "الطمأنينة تدل على قلة المخاوف",
    explanation_en: "Peace of mind indicates decreased fears",
    difficulty: "medium"
  },
  {
    question_ar: "المياه الراكدة ......... الأمراض، أما الجارية فتحيا فيها الحياة.",
    question_en: "Stagnant water ......... diseases, while flowing water teems with life.",
    type: "multiple_choice",
    options_ar: ["تمنع", "تنقي", "تولد", "تنظف"],
    options_en: ["Prevents", "Purifies", "Breeds", "Cleans"],
    correct_answer: "2",
    explanation_ar: "المياه الراكدة تولد الأمراض بعكس الجارية",
    explanation_en: "Stagnant water breeds diseases unlike flowing water",
    difficulty: "easy"
  },
  {
    question_ar: "الجالس بين الناس يخشى الزلل، ولهذا ......... في الكلام ولا يتكلم بغير علم.",
    question_en: "One sitting among people fears slips, so he ......... in speech and doesn't speak without knowledge.",
    type: "multiple_choice",
    options_ar: ["يطلق", "يتأنى", "يندفع", "يهذر"],
    options_en: ["Releases", "Deliberates", "Rushes", "Chatters"],
    correct_answer: "1",
    explanation_ar: "خشية الزلل تدل على التأني في الكلام",
    explanation_en: "Fearing slips indicates deliberation in speech",
    difficulty: "medium"
  },
  {
    question_ar: "كلما ازداد العلم بإنسان ......... تواضعه، لأن العلم يكشف له حجم جهله.",
    question_en: "The more a person's knowledge increases, ......... his humility, because knowledge reveals the size of his ignorance.",
    type: "multiple_choice",
    options_ar: ["قلّ", "ازداد", "ثبت", "انقطع"],
    options_en: ["Decreased", "Increased", "Stabilized", "Stopped"],
    correct_answer: "1",
    explanation_ar: "كثرة العلم تزيد التواضع لكشف حجم الجهل",
    explanation_en: "More knowledge increases humility by revealing the size of ignorance",
    difficulty: "medium"
  },
  {
    question_ar: "إن الأمم لا تُبنى بالأمنيات، بل بالعمل ......... والصبر الطويل.",
    question_en: "Nations are not built by wishes, but by ......... work and long patience.",
    type: "multiple_choice",
    options_ar: ["المتواصل", "النادر", "المتقطع", "المصطنع"],
    options_en: ["Continuous", "Rare", "Intermittent", "Artificial"],
    correct_answer: "0",
    explanation_ar: "بناء الأمم يحتاج عملاً متواصلاً مع الصبر",
    explanation_en: "Building nations needs continuous work with patience",
    difficulty: "easy"
  },
  {
    question_ar: "الصديق الوفي ينصحك في ......... لا في العلن، حفاظاً على كرامتك.",
    question_en: "The loyal friend advises you in ......... not in public, to preserve your dignity.",
    type: "multiple_choice",
    options_ar: ["السوق", "السر", "المجلس", "النادي"],
    options_en: ["The market", "Secret", "The council", "The club"],
    correct_answer: "1",
    explanation_ar: "الحفاظ على الكرامة يدل على النصح في السر",
    explanation_en: "Preserving dignity indicates advising in secret",
    difficulty: "easy"
  },
  {
    question_ar: "النقاش الذي ......... عن الحقيقة لا يورث إلا خصومة، أما الذي يقصد الفهم فينمي المعرفة.",
    question_en: "A discussion that ......... from the truth breeds only enmity, while one aimed at understanding grows knowledge.",
    type: "multiple_choice",
    options_ar: ["يسعى", "يبتعد", "يقترب", "يدور"],
    options_en: ["Seeks", "Departs", "Approaches", "Rotates"],
    correct_answer: "1",
    explanation_ar: "الخصومة تنتج عن النقاش الذي يبتعد عن الحقيقة",
    explanation_en: "Enmity results from a discussion that departs from the truth",
    difficulty: "medium"
  },
  {
    question_ar: "من يحقر عمل اليوم ......... نادماً حين يرى تقدم أقرانه.",
    question_en: "Whoever belittles today's work ends up ......... when seeing peers advance.",
    type: "multiple_choice",
    options_ar: ["مسرووراً", "نادماً", "مطمئناً", "فخوراً"],
    options_en: ["Happy", "Regretful", "Reassured", "Proud"],
    correct_answer: "1",
    explanation_ar: "النص يكرر «نادماً» لتأكيده كنتيجة لاحتقار عمل اليوم",
    explanation_en: "The text repeats 'regretful' to emphasize it as a result of belittling today's work",
    difficulty: "easy"
  },
  {
    question_ar: "إن في تنوع الآراء ......... للعقول، لا ضعفاً، لأنها تكشف وجوهاً متعددة للحقيقة.",
    question_en: "Diversity of opinions is a ......... for minds, not a weakness, as it reveals multiple facets of the truth.",
    type: "multiple_choice",
    options_ar: ["إجهاداً", "صقل", "بلاءً", "عبثاً"],
    options_en: ["Exhaustion", "Refinement", "Affliction", "Futility"],
    correct_answer: "1",
    explanation_ar: "كشف وجوه الحقيقة يصقل العقول لا يضعفها",
    explanation_en: "Revealing facets of the truth refines minds, not weakens them",
    difficulty: "hard"
  },
  {
    question_ar: "العاقل من ......... تجارب غيره فلا يقع فيما وقعوا فيه.",
    question_en: "The wise person ......... others' experiences so he doesn't fall into what they fell into.",
    type: "multiple_choice",
    options_ar: ["يتجاهل", "يستفيد من", "يحارب", "يحذف"],
    options_en: ["Ignores", "Benefits from", "Fights", "Deletes"],
    correct_answer: "1",
    explanation_ar: "تجنب الوقوع في أخطاء الآخرين يدل على الاستفادة من تجاربهم",
    explanation_en: "Avoiding others' mistakes indicates benefiting from their experiences",
    difficulty: "easy"
  },
  {
    question_ar: "الجبال الشاهقة لا تُصعد دفعة واحدة، بل ......... خطوة خطوة حتى القمة.",
    question_en: "Towering mountains aren't climbed at once, but ......... step by step to the summit.",
    type: "multiple_choice",
    options_ar: ["تهبط", "تصعد", "تُحفر", "تُدمر"],
    options_en: ["Descend", "Ascend", "Dig", "Destroy"],
    correct_answer: "1",
    explanation_ar: "الوصول إلى القمة يستلزم الصعود خطوة خطوة",
    explanation_en: "Reaching the summit requires ascending step by step",
    difficulty: "easy"
  },
  {
    question_ar: "حينما ......... الخطر يقوى الموقف، فإن الفرار لا يصنع رجالاً.",
    question_en: "When danger ......... the position strengthens; fleeing doesn't make men.",
    type: "multiple_choice",
    options_ar: ["يشتد", "يهون", "يغيب", "ينتفي"],
    options_en: ["Intensifies", "Eases", "Disappears", "Ceases"],
    correct_answer: "0",
    explanation_ar: "اشتداد الخطر يقوى الموقف ويثبت الرجال",
    explanation_en: "Intensifying danger strengthens the position and proves men",
    difficulty: "medium"
  },
  {
    question_ar: "السفينة لا ......... بسبب البحر الهادئ، بل بسبب ربّانها الماهر وقت العواصف.",
    question_en: "A ship doesn't ......... because of calm seas, but because of its skilled captain during storms.",
    type: "multiple_choice",
    options_ar: ["تغرق", "تنجو", "تهرب", "تتأخر"],
    options_en: ["Sink", "Survive", "Flee", "Delay"],
    correct_answer: "1",
    explanation_ar: "ربّان ماهر وقت العواصف هو سبب النجاة",
    explanation_en: "A skilled captain during storms is the cause of survival",
    difficulty: "medium"
  },
  {
    question_ar: "المال ......... في يد السخياء، فهو يزيد بقدر ما ينفق.",
    question_en: "Money ......... in the hands of the generous; it grows the more they spend.",
    type: "multiple_choice",
    options_ar: ["ينفد", "ينمو", "يختفي", "يقل"],
    options_en: ["Runs out", "Grows", "Disappears", "Decreases"],
    correct_answer: "1",
    explanation_ar: "النص يقول إن المال يزيد بقدر ما ينفق، أي ينمو",
    explanation_en: "The text says money grows the more spent, i.e. it grows",
    difficulty: "medium"
  },
  {
    question_ar: "النملة ......... صيفاً لتأكل شتاءً، فعلمت البشر معنى التدبير.",
    question_en: "The ant ......... in summer to eat in winter, teaching people the meaning of planning.",
    type: "multiple_choice",
    options_ar: ["تنام", "تدّخر", "تلعب", "تهرب"],
    options_en: ["Sleeps", "Stores", "Plays", "Flees"],
    correct_answer: "1",
    explanation_ar: "التدبير معناه ادخار الطعام للشتاء",
    explanation_en: "Planning means storing food for winter",
    difficulty: "easy"
  },
  {
    question_ar: "إذا ......... المرء على رأيه بغير حجة، دلّ ذلك على ضعف حجته.",
    question_en: "If a person ......... on his opinion without proof, it indicates the weakness of his argument.",
    type: "multiple_choice",
    options_ar: ["تماسك", "أصرّ", "تنازل", "تردد"],
    options_en: ["Held firm", "Insisted", "Conceded", "Hesitated"],
    correct_answer: "1",
    explanation_ar: "الإصرار بلا حجة دليل ضعف الحجة",
    explanation_en: "Insisting without proof indicates weak argument",
    difficulty: "medium"
  },
  {
    question_ar: "لا خير في علم لا ......... به القلوب، وإن ردده اللسان.",
    question_en: "There is no good in knowledge that doesn't ......... the hearts, even if the tongue repeats it.",
    type: "multiple_choice",
    options_ar: ["تنفعه", "تمرّ", "تطمئن", "تنجلي"],
    options_en: ["Benefit", "Pass", "Reassure", "Clear"],
    correct_answer: "0",
    explanation_ar: "النص يذم العلم الذي لا ينفع القلوب رغم ترداده على اللسان",
    explanation_en: "The text criticizes knowledge that doesn't benefit hearts despite tongue repetition",
    difficulty: "hard"
  }
];