// التربية الإسلامية — الصف الثالث الابتدائي — الفصل الأول
// الفقه والسلوك — الوحدة الثالثة: مكان الصلاة وشروطها
// المصدر: كتاب التوحيد والفقه والسلوك 1447هـ — ص 58-70

export const PDF_58_60 = 'https://media.base44.com/files/public/6a459ddfe6fb4264c098136d/9473652be________58-60.pdf';
export const PDF_61_63 = 'https://media.base44.com/files/public/6a459ddfe6fb4264c098136d/559a10a32________61-63.pdf';
export const PDF_64_66 = 'https://media.base44.com/files/public/6a459ddfe6fb4264c098136d/f28495089________64-66.pdf';
export const PDF_67_69 = 'https://media.base44.com/files/public/6a459ddfe6fb4264c098136d/a5ed5d055________67-69.pdf';
export const PDF_70_72 = 'https://media.base44.com/files/public/6a459ddfe6fb4264c098136d/7ef9d6d18________70-72.pdf';

export const FIQH_UNIT3_QUESTIONS = [
  // ص 58-60: شروط الصلاة (الأولى إلى الرابعة)
  {
    id: 'f3q1', unit: 'fiqh3', lesson: 'f3l1', page: 58,
    type: 'multipleChoice', bloom: 'remember', difficulty: 'easy',
    bookRef: PDF_58_60,
    question: 'كم عدد شروط الصلاة؟',
    options: [
      { text: 'تسعة شروط', correct: true },
      { text: 'خمسة شروط', correct: false },
      { text: 'سبعة شروط', correct: false },
      { text: 'أحد عشر شرطاً', correct: false },
    ],
    explanation: 'للصلاة تسعة شروط لا تصح إلا بها جميعاً.',
    goldenRule: 'شروط الصلاة تسعة.',
  },
  {
    id: 'f3q2', unit: 'fiqh3', lesson: 'f3l1', page: 58,
    type: 'multipleChoice', bloom: 'remember', difficulty: 'easy',
    bookRef: PDF_58_60,
    question: 'الشرط الأول من شروط الصلاة هو:',
    options: [
      { text: 'الإسلام', correct: true },
      { text: 'الطهارة', correct: false },
      { text: 'النية', correct: false },
      { text: 'دخول الوقت', correct: false },
    ],
    explanation: 'الشرط الأول: الإسلام، فالصلاة لا تصح من كافر.',
    goldenRule: 'الشروط: ١-الإسلام، ٢-العقل، ٣-التمييز، ٤-الطهارة، ٥-إزالة النجاسة، ٦-ستر العورة، ٧-دخول الوقت، ٨-استقبال القبلة، ٩-النية.',
  },
  {
    id: 'f3q3', unit: 'fiqh3', lesson: 'f3l1', page: 58,
    type: 'trueFalse', bloom: 'understand', difficulty: 'easy',
    bookRef: PDF_58_60,
    question: 'الطهارة من شروط صحة الصلاة.',
    correctAnswer: true,
    explanation: 'الطهارة من الحدثين الأصغر (الوضوء) والأكبر (الغسل) شرط لصحة الصلاة.',
    goldenRule: 'الطهارة شرط صحة الصلاة.',
  },
  {
    id: 'f3q4', unit: 'fiqh3', lesson: 'f3l1', page: 59,
    type: 'multipleChoice', bloom: 'remember', difficulty: 'easy',
    bookRef: PDF_58_60,
    question: 'الشرط الثالث من شروط الصلاة هو:',
    options: [
      { text: 'التمييز', correct: true },
      { text: 'الإسلام', correct: false },
      { text: 'النية', correct: false },
      { text: 'الطهارة', correct: false },
    ],
    explanation: 'الشرط الثالث: التمييز، وسن التمييز هو سبع سنوات تقريباً.',
    goldenRule: 'التمييز = سبع سنوات تقريباً.',
  },
  // ص 60-63: الشروط الرابعة إلى السادسة
  {
    id: 'f3q5', unit: 'fiqh3', lesson: 'f3l2', page: 60,
    type: 'multipleChoice', bloom: 'understand', difficulty: 'medium',
    bookRef: PDF_58_60,
    question: 'الشرط الرابع من شروط الصلاة هو:',
    options: [
      { text: 'إزالة النجاسة عن البدن والثوب والمكان', correct: true },
      { text: 'دخول الوقت', correct: false },
      { text: 'استقبال القبلة', correct: false },
      { text: 'سن البلوغ', correct: false },
    ],
    explanation: 'الشرط الرابع: إزالة النجاسة عن البدن والثوب والمكان، وهو شرط لصحة الصلاة.',
    goldenRule: 'الشرط الرابع: طهارة البدن + الثوب + المكان من النجاسة.',
  },
  {
    id: 'f3q6', unit: 'fiqh3', lesson: 'f3l2', page: 62,
    type: 'multipleChoice', bloom: 'remember', difficulty: 'easy',
    bookRef: PDF_61_63,
    question: 'الشرط الخامس من شروط الصلاة هو:',
    options: [
      { text: 'الطهارة (الوضوء والغسل)', correct: true },
      { text: 'ستر العورة', correct: false },
      { text: 'دخول الوقت', correct: false },
      { text: 'النية', correct: false },
    ],
    explanation: 'الشرط الخامس: الطهارة من الحدث الأصغر بالوضوء، ومن الحدث الأكبر بالغسل.',
    goldenRule: 'الطهارة = وضوء من الحدث الأصغر + غسل من الحدث الأكبر.',
  },
  {
    id: 'f3q7', unit: 'fiqh3', lesson: 'f3l2', page: 63,
    type: 'multipleChoice', bloom: 'understand', difficulty: 'medium',
    bookRef: PDF_61_63,
    question: 'الشرط السادس من شروط الصلاة: ستر العورة. ما عورة الرجل في الصلاة؟',
    options: [
      { text: 'من السرة إلى الركبة', correct: true },
      { text: 'الجسم كاملاً', correct: false },
      { text: 'من الكتف إلى القدم', correct: false },
      { text: 'العورة الغليظة فقط', correct: false },
    ],
    explanation: 'عورة الرجل في الصلاة: من السُّرة إلى الركبة. وعورة المرأة: جسدها كاملاً ما عدا وجهها وكفيها.',
    goldenRule: 'عورة الرجل: السُّرة ← الركبة. عورة المرأة: جسدها كاملاً ما عدا الوجه والكفين.',
  },
  {
    id: 'f3q8', unit: 'fiqh3', lesson: 'f3l2', page: 64,
    type: 'trueFalse', bloom: 'understand', difficulty: 'easy',
    bookRef: PDF_64_66,
    question: 'عورة المرأة في الصلاة: جسدها كاملاً ما عدا وجهها وكفيها.',
    correctAnswer: true,
    explanation: 'عورة المرأة في الصلاة: تغطي جسدها كاملاً ما عدا وجهها وكفيها في الصلاة.',
    goldenRule: 'المرأة تُصلي مغطية جسدها ما عدا وجهها وكفيها.',
  },
  // ص 66-69: الشروط السابعة إلى التاسعة
  {
    id: 'f3q9', unit: 'fiqh3', lesson: 'f3l3', page: 66,
    type: 'multipleChoice', bloom: 'understand', difficulty: 'medium',
    bookRef: PDF_64_66,
    question: 'الشرط السابع من شروط الصلاة هو:',
    options: [
      { text: 'دخول وقت الصلاة', correct: true },
      { text: 'ستر العورة', correct: false },
      { text: 'استقبال القبلة', correct: false },
      { text: 'النية', correct: false },
    ],
    explanation: 'الشرط السابع: دخول وقت الصلاة. قال تعالى: ﴿إِنَّ الصَّلَاةَ كَانَتْ عَلَى الْمُؤْمِنِينَ كِتَابًا مَّوْقُوتًا﴾.',
    goldenRule: 'الصلاة لا تصح قبل دخول وقتها.',
  },
  {
    id: 'f3q10', unit: 'fiqh3', lesson: 'f3l3', page: 66,
    type: 'matching', bloom: 'remember', difficulty: 'medium',
    bookRef: PDF_64_66,
    question: 'صل كل صلاة بوقتها:',
    pairs: [
      { left: 'الفجر', right: 'من طلوع الفجر الثاني إلى طلوع الشمس' },
      { left: 'الظهر', right: 'من زوال الشمس إلى أن يصير ظل كل شيء مثله' },
      { left: 'المغرب', right: 'من غروب الشمس إلى أن يغيب الشفق الأحمر' },
      { left: 'العشاء', right: 'من مغيب الشفق الأحمر إلى نصف الليل' },
    ],
    explanation: 'لكل صلاة وقت محدد شرعاً لا يصح أداؤها قبله.',
    goldenRule: 'أوقات الصلوات الخمس محددة شرعاً.',
  },
  {
    id: 'f3q11', unit: 'fiqh3', lesson: 'f3l3', page: 68,
    type: 'multipleChoice', bloom: 'remember', difficulty: 'easy',
    bookRef: PDF_67_69,
    question: 'الشرط الثامن من شروط الصلاة هو:',
    options: [
      { text: 'استقبال القبلة (الكعبة المشرفة)', correct: true },
      { text: 'دخول الوقت', correct: false },
      { text: 'النية', correct: false },
      { text: 'الطهارة', correct: false },
    ],
    explanation: 'الشرط الثامن: استقبال القبلة وهي الكعبة المشرفة في مكة المكرمة.',
    goldenRule: 'استقبال القبلة = التوجه نحو الكعبة المشرفة.',
  },
  {
    id: 'f3q12', unit: 'fiqh3', lesson: 'f3l3', page: 68,
    type: 'trueFalse', bloom: 'understand', difficulty: 'easy',
    bookRef: PDF_67_69,
    question: 'الكعبة المشرفة تقع في المدينة المنورة.',
    correctAnswer: false,
    explanation: 'الكعبة المشرفة تقع في مكة المكرمة وهي قبلة المسلمين في الصلاة.',
    goldenRule: 'الكعبة المشرفة = مكة المكرمة = قبلة المسلمين.',
  },
  {
    id: 'f3q13', unit: 'fiqh3', lesson: 'f3l3', page: 68,
    type: 'multipleChoice', bloom: 'remember', difficulty: 'easy',
    bookRef: PDF_67_69,
    question: 'الشرط التاسع والأخير من شروط الصلاة هو:',
    options: [
      { text: 'النية', correct: true },
      { text: 'الطهارة', correct: false },
      { text: 'ستر العورة', correct: false },
      { text: 'دخول الوقت', correct: false },
    ],
    explanation: 'الشرط التاسع: النية. قال ﷺ: "إنما الأعمال بالنيات". والنية محلها القلب.',
    goldenRule: 'النية: محلها القلب ولا تنطق باللسان.',
  },
  {
    id: 'f3q14', unit: 'fiqh3', lesson: 'f3l3', page: 68,
    type: 'trueFalse', bloom: 'understand', difficulty: 'easy',
    bookRef: PDF_67_69,
    question: 'النية محلها القلب ولا تُنطق باللسان.',
    correctAnswer: true,
    explanation: 'النية محلها القلب، قال ﷺ: "إنما الأعمال بالنيات"، ولم يثبت النطق بها عن النبي ﷺ.',
    goldenRule: 'النية في القلب لا في اللسان.',
  },
  {
    id: 'f3q15', unit: 'fiqh3', lesson: 'f3l1', page: 59,
    type: 'ordering', bloom: 'analyze', difficulty: 'hard',
    bookRef: PDF_58_60,
    question: 'رتّب شروط الصلاة التسعة:',
    items: ['النية', 'الإسلام', 'استقبال القبلة', 'العقل', 'دخول الوقت', 'التمييز', 'ستر العورة', 'الطهارة', 'إزالة النجاسة'],
    correctOrder: [1, 3, 5, 8, 7, 6, 4, 2, 0],
    explanation: 'الترتيب: الإسلام ← العقل ← التمييز ← إزالة النجاسة ← الطهارة ← ستر العورة ← دخول الوقت ← القبلة ← النية.',
    goldenRule: 'شروط الصلاة التسعة كلها لازمة.',
  },
  {
    id: 'f3q16', unit: 'fiqh3', lesson: 'f3l2', page: 65,
    type: 'multipleChoice', bloom: 'apply', difficulty: 'medium',
    bookRef: PDF_64_66,
    question: 'صلّى سليمان ملابسه فوق الركبة. ما الحكم؟',
    options: [
      { text: 'صلاته غير صحيحة لأن ستر العورة لم يكتمل', correct: true },
      { text: 'صلاته صحيحة لأنه غطى معظم جسده', correct: false },
      { text: 'عليه سجود السهو', correct: false },
      { text: 'صلاته مقبولة لأنه لم يقصد', correct: false },
    ],
    explanation: 'ستر العورة شرط من شروط الصلاة، وعورة الرجل من السُّرة إلى الركبة، فمن لم يسترها لم تصح صلاته.',
    goldenRule: 'ستر العورة شرط صحة وليس شرط كمال.',
  },
  {
    id: 'f3q17', unit: 'fiqh3', lesson: 'f3l3', page: 69,
    type: 'trueFalse', bloom: 'understand', difficulty: 'easy',
    bookRef: PDF_67_69,
    question: 'إذا صلّى أحد قبل دخول وقت الصلاة فصلاته صحيحة.',
    correctAnswer: false,
    explanation: 'لا تصح الصلاة قبل دخول وقتها، فدخول الوقت شرط من شروط الصلاة.',
    goldenRule: 'دخول الوقت شرط لا تصح الصلاة قبله.',
  },
  {
    id: 'f3q18', unit: 'fiqh3', lesson: 'f3l1', page: 58,
    type: 'classify', bloom: 'analyze', difficulty: 'medium',
    bookRef: PDF_58_60,
    question: 'صنّف: هل هذا شرط من شروط الصلاة أم لا؟',
    categories: ['شرط من شروط الصلاة ✓', 'ليس شرطاً ✗'],
    items: [
      { text: 'الإسلام', correct_category: 0 },
      { text: 'الصدق', correct_category: 1 },
      { text: 'ستر العورة', correct_category: 0 },
      { text: 'حفظ القرآن', correct_category: 1 },
      { text: 'استقبال القبلة', correct_category: 0 },
      { text: 'النية', correct_category: 0 },
    ],
    explanation: 'شروط الصلاة التسعة محددة، والصدق وحفظ القرآن من الفضائل لا من الشروط.',
    goldenRule: 'شروط الصلاة التسعة لا زيادة عليها ولا نقصان.',
  },
  {
    id: 'f3q19', unit: 'fiqh3', lesson: 'f3l3', page: 70,
    type: 'multipleChoice', bloom: 'evaluate', difficulty: 'hard',
    bookRef: PDF_70_72,
    question: 'ما الحكمة من اشتراط استقبال القبلة في الصلاة؟',
    options: [
      { text: 'توحيد اتجاه المسلمين في صلاتهم وتجميع قلوبهم نحو بيت الله', correct: true },
      { text: 'لا توجد حكمة', correct: false },
      { text: 'لأن الكعبة أجمل مكان', correct: false },
      { text: 'تذكير المسلمين بالحج فقط', correct: false },
    ],
    explanation: 'الحكمة: توحيد قبلة المسلمين يجمع قلوبهم ويوحد صفوفهم، وهو دليل على الوحدة الإسلامية.',
    goldenRule: 'القبلة الواحدة = وحدة المسلمين.',
  },
  {
    id: 'f3q20', unit: 'fiqh3', lesson: 'f3l1', page: 59,
    type: 'multipleChoice', bloom: 'remember', difficulty: 'easy',
    bookRef: PDF_58_60,
    question: 'سن التمييز الذي تجب فيه الصلاة تقريباً هو:',
    options: [
      { text: 'سبع سنوات', correct: true },
      { text: 'عشر سنوات', correct: false },
      { text: 'خمس سنوات', correct: false },
      { text: 'خمس عشرة سنة', correct: false },
    ],
    explanation: 'سن التمييز تقريباً سبع سنوات، ويؤمر الصبي بالصلاة لسبع ويُضرب عليها لعشر.',
    goldenRule: 'يُؤمر بالصلاة لسبع، ويُضرب عليها لعشر.',
  },
];