// التربية الإسلامية — الصف الثالث الابتدائي — الفصل الأول
// التوحيد — الوحدة الأولى: مراتب الدين
// المصدر: كتاب التوحيد والفقه والسلوك 1447هـ — ص 6-11

export const PDF_1_3   = 'https://media.base44.com/files/public/6a459ddfe6fb4264c098136d/454da0f01________1-3.pdf';
export const PDF_4_6   = 'https://media.base44.com/files/public/6a459ddfe6fb4264c098136d/b423fa050________4-6.pdf';
export const PDF_7_9   = 'https://media.base44.com/files/public/6a459ddfe6fb4264c098136d/de90d63cb________7-9.pdf';

export const TAWHEED_UNIT1_QUESTIONS = [
  // ص 6-7: مراتب الدين — الإسلام والإيمان والإحسان
  {
    id: 't1q1', unit: 'tawheed1', lesson: 't1l1', page: 6,
    type: 'multipleChoice', bloom: 'remember', difficulty: 'easy',
    bookRef: PDF_4_6,
    question: 'مراتب الدين ثلاثة، وهي:',
    options: [
      { text: 'الإسلام والإيمان والإحسان', correct: true },
      { text: 'الصلاة والصيام والزكاة', correct: false },
      { text: 'التوحيد والفقه والسلوك', correct: false },
      { text: 'الطهارة والصلاة والحج', correct: false },
    ],
    explanation: 'مراتب الدين ثلاثة: الإسلام، والإيمان، والإحسان. قال النبي ﷺ لجبريل لمّا سأله عن الإسلام والإيمان والإحسان.',
    goldenRule: 'مراتب الدين = الإسلام + الإيمان + الإحسان.',
  },
  {
    id: 't1q2', unit: 'tawheed1', lesson: 't1l1', page: 6,
    type: 'multipleChoice', bloom: 'understand', difficulty: 'easy',
    bookRef: PDF_4_6,
    question: 'الإسلام هو:',
    options: [
      { text: 'الاستسلام لله بالتوحيد والانقياد له بالطاعة والبراءة من الشرك وأهله', correct: true },
      { text: 'أن تعبد الله كأنك تراه', correct: false },
      { text: 'أن تؤمن بالله وملائكته وكتبه ورسله واليوم الآخر والقدر', correct: false },
      { text: 'أداء الصلاة والصيام والزكاة', correct: false },
    ],
    explanation: 'الإسلام: الاستسلام لله بالتوحيد، والانقياد له بالطاعة، والبراءة من الشرك وأهله.',
    goldenRule: 'الإسلام = استسلام + انقياد + براءة من الشرك.',
  },
  {
    id: 't1q3', unit: 'tawheed1', lesson: 't1l1', page: 7,
    type: 'multipleChoice', bloom: 'remember', difficulty: 'easy',
    bookRef: PDF_4_6,
    question: 'الإيمان هو:',
    options: [
      { text: 'التصديق بالله وملائكته وكتبه ورسله واليوم الآخر والقدر خيره وشره', correct: true },
      { text: 'الاستسلام لله بالتوحيد', correct: false },
      { text: 'أن تعبد الله كأنك تراه', correct: false },
      { text: 'أداء الشهادتين والصلاة والزكاة', correct: false },
    ],
    explanation: 'الإيمان: التصديق بالله وملائكته وكتبه ورسله واليوم الآخر والقدر خيره وشره.',
    goldenRule: 'أركان الإيمان ستة: الله + الملائكة + الكتب + الرسل + اليوم الآخر + القدر.',
  },
  {
    id: 't1q4', unit: 'tawheed1', lesson: 't1l1', page: 7,
    type: 'multipleChoice', bloom: 'remember', difficulty: 'easy',
    bookRef: PDF_4_6,
    question: 'الإحسان هو:',
    options: [
      { text: 'أن تعبد الله كأنك تراه، فإن لم تكن تراه فإنه يراك', correct: true },
      { text: 'الاستسلام لله بالتوحيد', correct: false },
      { text: 'التصديق بالله وملائكته وكتبه ورسله', correct: false },
      { text: 'أداء الصلاة في وقتها', correct: false },
    ],
    explanation: 'الإحسان: أن تعبد الله كأنك تراه، فإن لم تكن تراه فإنه يراك.',
    goldenRule: 'الإحسان = عبادة الله كأنك تراه، فإن لم تكن تراه فإنه يراك.',
  },
  {
    id: 't1q5', unit: 'tawheed1', lesson: 't1l1', page: 7,
    type: 'trueFalse', bloom: 'understand', difficulty: 'easy',
    bookRef: PDF_4_6,
    question: 'الإحسان أعلى مراتب الدين.',
    correctAnswer: true,
    explanation: 'الإحسان أعلى مراتب الدين وأرفعها، لأنه يعني عبادة الله بمراقبة تامة كأنك تراه.',
    goldenRule: 'مراتب الدين: الإسلام < الإيمان < الإحسان (الأعلى).',
  },
  {
    id: 't1q6', unit: 'tawheed1', lesson: 't1l1', page: 6,
    type: 'trueFalse', bloom: 'understand', difficulty: 'easy',
    bookRef: PDF_4_6,
    question: 'مراتب الدين اثنتان فقط: الإسلام والإيمان.',
    correctAnswer: false,
    explanation: 'مراتب الدين ثلاثة: الإسلام، والإيمان، والإحسان.',
    goldenRule: 'مراتب الدين ثلاثة لا اثنتان: الإسلام + الإيمان + الإحسان.',
  },
  {
    id: 't1q7', unit: 'tawheed1', lesson: 't1l1', page: 7,
    type: 'matching', bloom: 'understand', difficulty: 'medium',
    bookRef: PDF_4_6,
    question: 'صل كل مرتبة بتعريفها الصحيح:',
    pairs: [
      { left: 'الإسلام', right: 'الاستسلام لله بالتوحيد والانقياد له بالطاعة' },
      { left: 'الإيمان', right: 'التصديق بالله وملائكته وكتبه ورسله واليوم الآخر والقدر' },
      { left: 'الإحسان', right: 'أن تعبد الله كأنك تراه فإن لم تكن تراه فإنه يراك' },
    ],
    explanation: 'الإسلام = استسلام وانقياد. الإيمان = تصديق بأركان الإيمان الستة. الإحسان = مراقبة الله في العبادة.',
    goldenRule: 'كل مرتبة أشمل وأعمق من التي قبلها.',
  },
  {
    id: 't1q8', unit: 'tawheed1', lesson: 't1l1', page: 7,
    type: 'classify', bloom: 'analyze', difficulty: 'medium',
    bookRef: PDF_4_6,
    question: 'صنّف كل عبارة تحت المرتبة الصحيحة:',
    categories: ['الإسلام', 'الإيمان', 'الإحسان'],
    items: [
      { text: 'الاستسلام لله بالتوحيد', correct_category: 0 },
      { text: 'التصديق بالقدر خيره وشره', correct_category: 1 },
      { text: 'عبادة الله كأنك تراه', correct_category: 2 },
      { text: 'الانقياد لله بالطاعة', correct_category: 0 },
      { text: 'التصديق بالملائكة', correct_category: 1 },
      { text: 'مراقبة الله في السر والعلن', correct_category: 2 },
    ],
    explanation: 'الإسلام: استسلام وانقياد. الإيمان: تصديق بأركان الإيمان الستة. الإحسان: مراقبة الله.',
    goldenRule: 'مراتب الدين الثلاث متكاملة ومترابطة.',
  },
  {
    id: 't1q9', unit: 'tawheed1', lesson: 't1l1', page: 7,
    type: 'multipleChoice', bloom: 'apply', difficulty: 'medium',
    bookRef: PDF_4_6,
    question: 'عندما يصلي أحمد ويشعر بأن الله يراه ويراقبه، فهو يطبّق مرتبة:',
    options: [
      { text: 'الإحسان', correct: true },
      { text: 'الإسلام', correct: false },
      { text: 'الإيمان', correct: false },
      { text: 'التوحيد', correct: false },
    ],
    explanation: 'الإحسان هو أن تعبد الله كأنك تراه، فإن لم تكن تراه فإنه يراك. وهذا ما يطبقه أحمد في صلاته.',
    goldenRule: 'الإحسان = مراقبة الله في العبادة.',
  },
  {
    id: 't1q10', unit: 'tawheed1', lesson: 't1l1', page: 6,
    type: 'ordering', bloom: 'analyze', difficulty: 'medium',
    bookRef: PDF_4_6,
    question: 'رتّب مراتب الدين من الأدنى إلى الأعلى:',
    items: ['الإيمان', 'الإحسان', 'الإسلام'],
    correctOrder: [2, 0, 1],
    explanation: 'مراتب الدين من الأدنى إلى الأعلى: الإسلام ← الإيمان ← الإحسان.',
    goldenRule: 'الإسلام أول ← الإيمان وسط ← الإحسان أعلى.',
  },
  {
    id: 't1q11', unit: 'tawheed1', lesson: 't1l1', page: 8,
    type: 'multipleChoice', bloom: 'remember', difficulty: 'easy',
    bookRef: PDF_7_9,
    question: 'أركان الإيمان ستة، ما هو الركن السادس؟',
    options: [
      { text: 'الإيمان بالقدر خيره وشره', correct: true },
      { text: 'الإيمان بالله', correct: false },
      { text: 'الإيمان بالرسل', correct: false },
      { text: 'الإيمان باليوم الآخر', correct: false },
    ],
    explanation: 'الركن السادس من أركان الإيمان هو: الإيمان بالقدر خيره وشره.',
    goldenRule: 'أركان الإيمان الستة: الله + الملائكة + الكتب + الرسل + اليوم الآخر + القدر.',
  },
  {
    id: 't1q12', unit: 'tawheed1', lesson: 't1l1', page: 8,
    type: 'multipleChoice', bloom: 'remember', difficulty: 'easy',
    bookRef: PDF_7_9,
    question: 'كم عدد أركان الإيمان؟',
    options: [
      { text: 'ستة', correct: true },
      { text: 'خمسة', correct: false },
      { text: 'سبعة', correct: false },
      { text: 'أربعة', correct: false },
    ],
    explanation: 'أركان الإيمان ستة: الإيمان بالله، وملائكته، وكتبه، ورسله، واليوم الآخر، والقدر خيره وشره.',
    goldenRule: 'أركان الإيمان = ستة أركان.',
  },
  {
    id: 't1q13', unit: 'tawheed1', lesson: 't1l1', page: 9,
    type: 'trueFalse', bloom: 'understand', difficulty: 'easy',
    bookRef: PDF_7_9,
    question: 'الإيمان بالقدر يعني أن كل شيء في الكون بتقدير الله تعالى.',
    correctAnswer: true,
    explanation: 'الإيمان بالقدر يعني الإيمان بأن كل ما يقع في الكون من خير وشر هو بعلم الله وتقديره وإرادته وخلقه.',
    goldenRule: 'القدر = علم الله + كتابته + إرادته + خلقه.',
  },
  {
    id: 't1q14', unit: 'tawheed1', lesson: 't1l1', page: 9,
    type: 'multipleChoice', bloom: 'apply', difficulty: 'medium',
    bookRef: PDF_7_9,
    question: 'سامي يؤمن بالله وملائكته وكتبه ورسله واليوم الآخر والقدر. هذا يعني أنه يطبّق:',
    options: [
      { text: 'أركان الإيمان كاملة', correct: true },
      { text: 'أركان الإسلام فقط', correct: false },
      { text: 'مرتبة الإحسان فقط', correct: false },
      { text: 'ثلاثة أركان فقط', correct: false },
    ],
    explanation: 'من آمن بالله وملائكته وكتبه ورسله واليوم الآخر والقدر خيره وشره فقد استوفى أركان الإيمان الستة.',
    goldenRule: 'استيفاء الأركان الستة = إيمان صحيح.',
  },
  {
    id: 't1q15', unit: 'tawheed1', lesson: 't1l1', page: 10,
    type: 'multipleChoice', bloom: 'evaluate', difficulty: 'hard',
    bookRef: PDF_7_9,
    question: 'لماذا يُعدّ الإحسان أرقى مراتب الدين؟',
    options: [
      { text: 'لأنه يجمع الإسلام والإيمان مع المراقبة الدائمة لله', correct: true },
      { text: 'لأنه أسهل تطبيقاً', correct: false },
      { text: 'لأنه لا يتطلب عملاً', correct: false },
      { text: 'لأنه خاص بالأنبياء فقط', correct: false },
    ],
    explanation: 'الإحسان أرقى المراتب لأنه يضم الإسلام والإيمان إضافة إلى مراقبة الله دائماً في السر والعلن.',
    goldenRule: 'الإحسان = إسلام + إيمان + مراقبة دائمة لله.',
  },
];